### PR TITLE
Fix ZStandard native memory leaks

### LINKED ISSUE #14028: Native memory leak in zstd compression handler
**Jetty version(s)**
12.1.4

**Jetty Environment**
ee10

**HTTP version**
http/1.1, http/2

**Java version/vendor** 
```
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)
```

**OS type/version**
```
Ubuntu 24.04.3 LTS
```

**Description**

When zstd compression is used for data served as resources by ServletContextHandler, there is native memory leak. It happens on both http/1.1 and http/2.

Scenario: Page with lot of small resources, 5× refreshes in Brave browser

Scenario - Variant A: `compressPreferredEncodings(List.of("gzip"))`

Image

Scenario - Variant B: `compressPreferredEncodings(List.of("zstd","gzip"))`

Image

When I continue to hit F5 for refresh few more times, RSS memory usage rises until there is no more free memory and oom killer terminates process.

JVM heap and non-heap memory seems to be fine, but process memory rises rapidly. Values from chart are obtained using:
```
cat /proc/<PID>/status | grep Vm
```

We are using same library for zstd compression (`com.github.luben:zstd-jni:1.5.7-6`) as `jetty-compression-zstandard` for the storing and retrieving data in our application and we are not experiencing memory leak in our storage routines. It might suggest that memory leak is not in `zstd-jni` library by itself.

**How to reproduce?**

Just configure compressPreferredEncodings to value, where "zstd" is on the first place
```
  CompressionConfig compressionConfig = CompressionConfig.builder().defaults()
                .compressPreferredEncodings(List.of("zstd","gzip"))
                .build();
        compressionHandler.putConfiguration("/*", compressionConfig);
        compressionHandler.putCompression(new ZstandardCompression());
        compressionHandler.putCompression(new GzipCompression());
```

And open a page with huge amount of small resources in Chromium based browser and hit refresh few times.

### PR DESCRIPTION
**Pull request by lorban**
Fixes #14028 by closing the zstd context when sources / sinks are released or when the GC cleans them up.

Also add buffer pooling to the zstd streams.

### CODE REVIEW

**Review by joakime — DISMISSED** [review]
Simple enough.

File: jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/ZstandardDecoderConfig.java [hunk 1]
```diff
@@ -35,7 +35,7 @@ public class ZstandardDecoderConfig implements DecoderConfig
         // Get the recommended buffer size from zstd-jni (actually comes from zstandard lib),
         // but put some upper limit on it for our default buffer size.
         // The user can still configure the buffer size to be higher if they want to.
-        long bufferSizeCeiling = 256_000;
+        long bufferSizeCeiling = 64 * 1024L; // TODO this is the default ArrayByteBufferPool maxCapacity, there should be a way to discover that
```
Comment (joakime) [inline jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/ZstandardDecoderConfig.java]: This size is smaller than the recommended size by the zstandard lib.

File: jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/ZstandardEncoderConfig.java [hunk 2]
```diff
@@ -36,7 +36,7 @@ public class ZstandardEncoderConfig implements EncoderConfig
         // Get the recommended buffer size from zstd-jni (actually comes from zstandard lib),
         // but put some upper limit on it for our default buffer size.
         // The user can still configure the buffer size to be higher if they want to.
-        long bufferSizeCeiling = 256_000;
+        long bufferSizeCeiling = 64 * 1024L; // TODO this is the default ArrayByteBufferPool maxCapacity, there should be a way to discover that
```
Comment (joakime) [inline jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/ZstandardEncoderConfig.java]: This size is smaller than the recommended size by the zstandard lib.

**Review by joakime — CHANGES_REQUESTED** [review]
I don't like the reduction in recommended default size.

Can we instead have a log warning be produced if the bufferPool isn't setup properly to allow for zstandard lib recommendations?

**Comment by lorban** [comment]
@joakime we currently have no API to detect the maximum pooled buffer size, so if we were to warn "please make  sure your pool is properly configured" we'd always do it, even when the pool is properly configured.

I hardcoded 64 KB here because the default maximum pooled buffer size is 64 KB, and it is the only solution that is both quick and easy to do that I could think of.

If zstd were to use non-pooled buffer, the performance would go down the drain: each direct byte buffer object has to be finalized (requires enqueuing/dequeuing from a concurrent queue, expensive!) and each time a new buffer is allocated it has to be zero'ed (filling 132 KB of memory with zeros, expensive!).

I agree this solution isn't ideal, but the only alternative I can come up that doesn't require modifying the `ByteBufferPool` interface with is to change the default `ArrayByteBufferPool` implementation to pool up to 256 KB buffers, i.e.: the previous ceiling value.

@sbordet @gregw opinions?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java [hunk 3]
```diff
@@ -66,7 +66,7 @@
 public class ArrayByteBufferPool implements ByteBufferPool, Dumpable
 {
     static final int DEFAULT_FACTOR = 4096;
-    static final int DEFAULT_MAX_CAPACITY_BY_FACTOR = 16;
+    static final int DEFAULT_MAX_CAPACITY_BY_FACTOR = 64;
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java]: I don't like this change to the generic component (the buffer pool) driven by a component (zstd) that may not even be used.

I think it should be the other way around.

I would rather document the zstd `*Config.setBufferSize()` methods so that they refer back to the `ByteBufferPool`, saying that whatever size is set, it should fall within the limits of the `ByteBufferPool`.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by sbordet** [comment]
Reading https://datatracker.ietf.org/doc/html/rfc8878#section-3.1.1.1.2, the min window size can be just 1 KiB.
However, there is a recommendation for 8 MiB, which seems just huge.

I think it's best for us to stick with a smaller size like 64 KiB, and document the implications with the `ByteBufferPool`.

**Comment by lorban** [comment]
So I've reverted to capping the zstd buffer sizes to 64 KB, and I added a comment to the javadoc explaining that this setting has implications on the `ByteBufferPool` configuration.

I believe this is the most reasonable thing to do for now as a user can always manually set the buffer size.

**Comment by joakime** [comment]
The zstandard requirements are `Window_Size + 2 * Block_Maximum_Size`

Of which, ...

* `Window_Size` defaults to 128 KB.
* `Block_Maximum_Size = min(128 KB, Window_Size)`.

https://github.com/facebook/zstd/wiki/Using-libzstd-in-a-memory-constrained-environment

**Comment by joakime** [comment]
We use the `zstd-jni` which is just a Java JNI layer on top of the facebook zstandard lib.
That lib has updated real-world defaults of 128 KB for Window Size.

It recommends using 128KB for the Window Size if dealing with sub 2GB inputs on non-streaming modes (we don't use the streaming modes).
It recommends higher Windows Size of up to 8MB if dealing with inputs over 2GB.

File: jetty-core/jetty-compression/jetty-compression-common/src/main/java/org/eclipse/jetty/compression/Compression.java [hunk 4]
```diff
@@ -82,18 +81,6 @@ public String etag(String etag)
         return etag + etagSuffix;
     }
 
-    public int getBufferSize()
```
Comment (lachlan-roberts) [inline jetty-core/jetty-compression/jetty-compression-common/src/main/java/org/eclipse/jetty/compression/Compression.java:85]: This is public API so we should not remove these methods in a dot release, these should be deprecated instead.

**Review by lachlan-roberts — DISMISSED** [review]

File: jetty-core/jetty-compression/jetty-compression-common/src/main/java/org/eclipse/jetty/compression/Compression.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-compression/jetty-compression-common/src/main/java/org/eclipse/jetty/compression/Compression.java:85]: Good catch, let me restore them and document them as deprecated.

**Comment by lorban** [comment]
@joakime @sbordet I've reverted the code changes related to the zstd buffer size and left the issue as-is for now, with only changes to the javadoc to hint at the problem.

This isn't a regression as this problem exists since the introduction of zstd (de)compression and we need the other fixes to be included in the next release that has to be cut this week, so let's postpone the buffer problem to the next release and simply ignore it for now.

File: jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/ZstandardDecoderConfig.java [hunk 5]
```diff
@@ -15,38 +15,12 @@
...
-        {
-            if (LOG.isDebugEnabled())
-                LOG.debug("Lowering zstd-jni recommended/default decoder buffer size of: {} to {}", bufferSize, bufferSizeCeiling);
-            bufferSize = bufferSizeCeiling;
-        }
-        DEFAULT_BUFFER_SIZE = (int)bufferSize;
-    }
-
-    private int bufferSize = DEFAULT_BUFFER_SIZE;
+    private int bufferSize = org.eclipse.jetty.util.IO.DEFAULT_BUFFER_SIZE;
```
Comment (joakime) [inline jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/ZstandardDecoderConfig.java:28]: This is an invalid configuration on it's own.
The IO.DEFAULT_BUFFER_SIZE value is currently at 8192.
That's below the 128KB Window Size that you didn't change.

This WILL cause problems in zstandard lib.

Note that 256_000 is the ceiling that we implement for buffer size.
We stick with the recommended size from the zstandard lib implementation (from a call to `ZstdInputStreamNoFinalizer.recommendedDOutSize()`, which is currently at the value of `131591` with this version of the lib)

The logic in the original code needs to exist, somewhere, just to ensure that valid values are being used.
Probably on the .setBufferSize() call, to warn if setting a buffer size lower than recommended.

If we want a smaller default buffer size, then we also need to tune the Window Size Log, with calls to both ...

* `ZstdOutputStreamNoFinalizer.setLong(int)`
* `ZstdOutputStreamNoFinalizer.setWindowLog(int)`

Note, the two settings above are log values, not direct byte sizes.

This is not as simple as setting a small buffer size, zstandard needs many knobs tuned to achieve this end goal.

**Review by joakime — CHANGES_REQUESTED** [review]
The current PR is invalid for zstandard, and will break it.

File: jetty-core/jetty-compression/jetty-compression-gzip/src/test/java/org/eclipse/jetty/compression/gzip/AbstractGzipTest.java [hunk 6]
```diff
@@ -95,15 +95,8 @@ public void tearDown()
     }
 
     protected void startGzip() throws Exception
```
Comment (joakime) [inline jetty-core/jetty-compression/jetty-compression-gzip/src/test/java/org/eclipse/jetty/compression/gzip/AbstractGzipTest.java:97]: Don't change the behavior outside of zstandard in this PR.

File: jetty-core/jetty-compression/jetty-compression-gzip/src/test/java/org/eclipse/jetty/compression/gzip/GzipCompressionTest.java [hunk 7]
```diff
@@ -35,7 +35,6 @@ public class GzipCompressionTest extends AbstractGzipTest
     @Test
     public void testBigBlockWithExtraBytesViaGzipInputStream() throws Exception
     {
-        startGzip(64);
         String data1 = "0123456789ABCDEF".repeat(10);
```
Comment (joakime) [inline jetty-core/jetty-compression/jetty-compression-gzip/src/test/java/org/eclipse/jetty/compression/gzip/GzipCompressionTest.java:38]: You broke the purpose of these test cases.
These are historical test cases for small buffer size configurations that have caused us problems in the past.
Revert these changes to Gzip, and the base EncoderSink

Comment (lorban) [reply jetty-core/jetty-compression/jetty-compression-gzip/src/test/java/org/eclipse/jetty/compression/gzip/GzipCompressionTest.java:38]: `startGzip` was initializing a `GzipCompression` instance that was not used in this test. So if that was meant to control a buffer size, the test was bogus to being with.

File: jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/ZstandardDecoderConfig.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/ZstandardDecoderConfig.java:28]: How is that `bufferSize` setting impacting the zstd buffer? AFAICT it's only used as the output to copy decompressed bytes, the zstd lib still uses a buffer with a size of its choice internally.

Comment (joakime) [reply jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/ZstandardDecoderConfig.java:28]: Sorry, `ZstdOutputStreamNoFinalizer` is for Encoding, not Decoding.

**Review by joakime — DISMISSED** [review]
Good, for now.
We need a new issue to track the ByteBufferPool changes to make it expose it's limits.

**Review by sbordet — APPROVED** [review]

**Review by joakime — APPROVED** [review]
