### PR TITLE
Fixes #4195: making test assertion more stable.

### LINKED ISSUE #4195: Test may fail due if HashMap iterates in a different order
`testToString` in `org/eclipse/jetty/util/MultiMapTest.java` tests the `toString` function of the MultiMap, which inherits HashMap. However, HashMap does not guarantee any specific order of entries. Therefore, the assertions in those test cases will fail if the order is different.

For example:
```
expected: <{color=red, food=[apple, cherry, raspberry]}> but was: <{food=[apple, cherry, raspb    erry], color=red}>
```

### PR DESCRIPTION
**Pull request by contextshuffling**
In this PR, we propose to fix #4195 by making the test assertions consider both valid cases of `toString` function of the MultiMap.

### CODE REVIEW

File: jetty-util/src/test/java/org/eclipse/jetty/util/MultiMapTest.java [hunk 1]
```diff
@@ -471,7 +471,10 @@ public void testToString()
 
         mm.putValues("food", "apple", "cherry", "raspberry");
 
-        assertEquals("{color=red, food=[apple, cherry, raspberry]}", mm.toString());
+        String expected1 = "{color=red, food=[apple, cherry, raspberry]}";
+        String expected2 = "{food=[apple, cherry, raspberry], color=red}";
+        String actual = mm.toString();
+        assertTrue(actual.equals(expected1) || actual.equals(expected2));
```
Comment (joakime) [inline jetty-util/src/test/java/org/eclipse/jetty/util/MultiMapTest.java]: The correct way is ... `assertThat(actual, anyOf(is(expected1), is(expected2));`
As that will produce a meaningful error message when it fails.
