### PR TITLE
Issue #5868 - allow request attributes to be set in websocket upgrade

### LINKED ISSUE #5865: Upgrade response stored by the WebSocketSession is recycled.
**Jetty version**
10.0.x

**Description**
The `UpgradeResponse` stored by the `WebSocketSession` is recycled by Jetty after the websocket upgrade.
At the point where the upgrade response is committed we need to copy the correct response details so we can store them in the `WebSocketSession`.

### LINKED ISSUE #5868: Cleaning up request attributes after websocket upgrade in Jetty 10
**Jetty version**
10.0.0

**Description**

Hi, Jetty maintainers! 

I'm currently in the progress of migrating from `9.4.x` to `10.0.0`, and I stumbled across a difference in the behaviour of the `JettyWebSocketCreator`. In Jetty `9.4.x`, the upgrade request allows for removing servlet attributes:
https://github.com/eclipse/jetty.project/blob/403d5ec318ffaa20f1f2c0b62df217cfc99ebbe0/jetty-websocket/websocket-servlet/src/main/java/org/eclipse/jetty/websocket/servlet/UpgradeHttpServletRequest.java#L407-L414

However, `10.0.0` throws an exception when an attempt to modify the request attributes is made: 
https://github.com/eclipse/jetty.project/blob/7dfb44f7ad7c70d5dda509587629b825bacafce4/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/internal/UpgradeHttpServletRequest.java#L406-L410

The issue with not being able to remove the attributes is that the WebSocket applications often maintain a large number of connections and additional attributes on the request lead to a significant increase in memory usage. In `9.4.x`, it would be possible to read the attributes within `JettyWebSocketCreator`, act upon them, and then establish a socket and completely remove the attributes freeing up a significant amount of memory. Is there a way to achieve similar behaviour in Jetty 10 where attributes are removed after establishing the WebSocket connection?

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Issue #5868 & #5865**

We now remove references to the `HttpServletRequest` and `HttpServletResponse` after the websocket upgrade, and allow access to the request attribute setters during and after the websocket upgrade. 

After the upgrade all relevant information from the request & response are copied locally into `UpgradeHttpServletRequest` and `UpgradeHttpServletResponse` before they are recycled.

### CODE REVIEW

File: jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java [hunk 1]
```diff
@@ -51,20 +52,17 @@
     public ServerUpgradeRequest(WebSocketNegotiation negotiation) throws BadMessageException
     {
         this.negotiation = negotiation;
-        HttpServletRequest httpRequest = negotiation.getRequest();
-        this.queryString = httpRequest.getQueryString();
-        this.secure = httpRequest.isSecure();
+        this.request = negotiation.getRequest();
```
Comment (gregw) [inline jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java:59]: OK I'm now totally confused by this class?
I thought it had a reference to the request that at some point was nulled out and all the required request fields copied.  But this class is holding it for all time and calling it at any time it likes?

How is this different to `UpgradeHttpServletRequest`?

Can you explain what is going on?  Perhaps in the javadoc for the class?

File: jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/internal/UpgradeHttpServletRequest.java [hunk 2]
```diff
@@ -276,56 +288,50 @@ public HttpSession getSession()
...
-    public Request getBaseRequest()
-    {
-        return baseRequest;
-    }
-
     @Override
     public String getRequestedSessionId()
     {
-        throw new UnsupportedOperationException(UNSUPPORTED_WITH_WEBSOCKET_UPGRADE);
+        throw new UnsupportedOperationException(UNSUPPORTED_AFTER_WEBSOCKET_UPGRADE);
```
Comment (gregw) [inline jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/internal/UpgradeHttpServletRequest.java]: All these methods could use the request object while not null and only throw once it is null.

File: jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/internal/UpgradeHttpServletRequest.java [hunk 3]
```diff
@@ -400,13 +406,17 @@ public String getRemoteHost()
     @Override
     public void setAttribute(String name, Object value)
     {
-        throw new UnsupportedOperationException(UNSUPPORTED_WITH_WEBSOCKET_UPGRADE);
+        if (request == null)
+            throw new UnsupportedOperationException(UNSUPPORTED_AFTER_WEBSOCKET_UPGRADE);
```
Comment (gregw) [inline jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/internal/UpgradeHttpServletRequest.java]: This is not what the OP requested.  If request is null, then the attribute needs to be removed from the copy of the attributes.

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java:59]: This is just the interface used during the negotiation so it is easy to set websocket stuff like extensions and subprotocol without having to actually set headers directly.

**Comment by joakime** [comment]
@lachlan-roberts don't forget to set labels, projects, linked issues, etc ...

**Review by gregw — APPROVED** [review]
