### PR TITLE
Fixes #4141 - Servlet not async + async Filter + wrapped request

### LINKED ISSUE #4141: ClassCastException with non-async Servlet + async Filter + HttpServletRequestWrapper
After upgrading jetty from 9.4.20 -> 9.4.21
I am seeing:
```
java.lang.ClassCastException: class org.springframework.security.web.firewall.StrictHttpFirewall$1 cannot be cast 
  to class org.eclipse.jetty.server.Request (org.springframework.security.web.firewall.StrictHttpFirewall$1 is in 
  unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @11e355ca; 
  org.eclipse.jetty.server.Request is in unnamed module of loader org.eclipse.jetty.start.Classpath$Loader @311d617d)
```

in both cases I am running java 12 + spring security 5.1.6

### PR DESCRIPTION
**Pull request by joakime**
+ Fixing ClassCastException

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

File: jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletWrapperTest.java [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+        }
+
+        @Override
+        public void destroy()
+        {
+            // ignore
+        }
+    }
+
+    public static class NoopRequestWrapper extends HttpServletRequestWrapper
```
Comment (joakime) [inline jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletWrapperTest.java]: Should probably rename this to something other then "Noop", perhaps "SimpleRequestWrapper"?
