### PR TITLE
Issue #12739 Fix NPE if WEB-INF is CombinedResource

### LINKED ISSUE #12739: Regression in handing CombinedResource WEB-INF between Jetty 11 and Jetty 12
**Jetty version(s)**
Jetty 12.0.16 vs Jetty 11.0.24

**Jetty Environment**
 EE 10

**Description**

We have embedded jetty servers that use a shared resources "layer" packed as a jar.
The setup works as expected in Jetty 11, but an attempt to migrate to Jetty 12 leads to the following exception:

```
java.lang.NullPointerException: Cannot invoke "java.net.URI.toString()" because the return value of "org.eclipse.jetty.util.resource.Resource.getURI()" is null
	at org.eclipse.jetty.ee10.webapp.JettyWebXmlConfiguration.setupXmlConfiguration(JettyWebXmlConfiguration.java:135) ~[jetty-ee10-webapp-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.ee10.webapp.JettyWebXmlConfiguration.configure(JettyWebXmlConfiguration.java:70) ~[jetty-ee10-webapp-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.ee10.webapp.Configurations.configure(Configurations.java:505) ~[jetty-ee10-webapp-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.ee10.webapp.WebAppContext.configure(WebAppContext.java:484) ~[jetty-ee10-webapp-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.ee10.webapp.WebAppContext.startContext(WebAppContext.java:1300) ~[jetty-ee10-webapp-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0(ServletContextHandler.java:1047) ~[jetty-ee10-servlet-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1452) ~[jetty-server-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart(ServletContextHandler.java:1044) ~[jetty-ee10-servlet-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart(WebAppContext.java:503) ~[jetty-ee10-webapp-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:120) ~[jetty-util-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:491) ~[jetty-server-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.server.Server.start(Server.java:641) ~[jetty-server-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:120) ~[jetty-util-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:491) ~[jetty-server-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.server.Server.doStart(Server.java:582) ~[jetty-server-12.0.16.jar:12.0.16]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-12.0.16.jar:12.0.16]
```

Looking further into Jetty codebase the exception happens in `JettyWebXmlConfiguration`:
```
        props.put(PROPERTY_WEB_INF_URI, XmlConfiguration.normalizeURI(webInf.getURI().toString()));
```
because webInf is a `CombinedResource` and `getURI` returns null for it. Meanwhile, it looks like it's allowed and expected for webInf resource to be a `CombinedResource` based on the following comment from  `WebAppContext`:
```
    public Resource getWebInf() throws IOException
    {
        if (getBaseResource() == null)
            return null;

        // Is there a WEB-INF directory anywhere in the Resource Base?
        // ResourceBase could be a CombinedResource
        // The result could be a CombinedResource with multiple WEB-INF directories
        // Can return from WEB-INF/lib/foo.jar!/WEB-INF
        // Can also never return from a META-INF/versions/#/WEB-INF location
        Resource webInf = getBaseResource().resolve("WEB-INF/");
        if (Resources.isReadableDirectory(webInf))
            return webInf;

        return null;
    }
```

This looks like a regression in a supported scenario from Jetty 11.

Image

### PR DESCRIPTION
**Pull request by janbartel**
Closes #12739 

If `WEB-INF` is represented by a `CombinedResource` we throw an `NPE` in `JettyWebXmlConfiguration` when we try to obtain it's `URI`.

 This is because `CombinedResource` will return `null` for a call to `getURI()` if it has more than one component `Resource` that exists and has a `URI`. This is a behaviour change from earlier versions of jetty, where `ResourceCollection` would always just return the `URI` of the first component `Resource`.

### CODE REVIEW

**Review by gregw — DISMISSED** [review]

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java [hunk 1]
```diff
@@ -132,7 +133,11 @@ private void setupXmlConfiguration(WebAppContext context, XmlConfiguration jetty
...
         jettyConfig.setJettyStandardIdsAndProperties(context.getServer(), null);
         Map<String, String> props = jettyConfig.getProperties();
-        props.put(PROPERTY_WEB_INF_URI, XmlConfiguration.normalizeURI(webInf.getURI().toString()));
-        props.put(PROPERTY_WEB_INF, webInf.toString());
+        URI uri = webInf.getURI();
+        if (uri != null)
+        {
+            props.put(PROPERTY_WEB_INF_URI, XmlConfiguration.normalizeURI(uri.toString()));
+            props.put(PROPERTY_WEB_INF, webInf.toString());
+        }
```
Comment (joakime) [inline jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java]: So if a webapp has more than one `/WEB-INF/` location (per its `Resource`), what happens now?
Is it ignored?
Will the `WEB-INF/web.xml` still be read?
What happens if there is more than one `WEB-INF/web.xml` present due to the `CombinedResource`?

**Review by joakime — COMMENTED** [review]
I don't understand what this code does.
It looks like a bug to ignore this situation, but likely depends on how this property used.

**Comment by Spikhalskiy** [comment]
@joak @janbartel If I understand it covertly, if this solution is merged as-is, it may not solve the underlying issue. It may just sweep it deeper under the rug by avoiding null pointer.
The underlying issue is that the correct `jetty-web.xml` may be located in any of the resources of the `CombinedResource`. Ignoring `jetty-web.xml` altogether surely avoids the NullPointer, but it's not an expected behavior. 

I think the desired solution here would be for all the resources in `CombinedResource` to be scanned for the presence of the `jetty-web.xml` file in a certain order until found. 

This way, `jetty-web.xml` options 
 - will be picked appropriately up
 - there will be deterministic logic which `jetty-web.xml` is getting preference if there is a conflict.
 
If this is merged as-is, I will have to open another issue asking for a way to specify the `jetty-web.xml` path explicitly somehow.

Further, this solution may confuse users and cause them to waste time trying to understand what's up and why their present `jetty-web.xml` is not respected in some cases (when they add a test WEB-INF for example), while it works fine in others.

**Comment by Spikhalskiy** [comment]
I could implement the resource discovery code and submit a PR. Just let me know if this would work for the Jetty team.

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java (hunk 1 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java]: If a deployment has a combined resource base with more that one WEB-INF directory, then that cannot be represented by either a single URI.    So the properties for the WEB-INF are simply not available and any configuration on such a deployment will have to use something more explicit (or resource based).

There is no problem if there is more than one `WEB-INF/web.xml` in the `CombinedResource` as for non directories we always pick the first that exists (because there is no meaningful way to merge them).  The problem only exists for directories, because they can be meaningfully merged in a combined resource.   If there truly are two WEB-INF directories, then we don't know which one to use the answer depends on what actual file is going to be referenced by it, as it may be in one, the other or both.

**Comment by gregw** [comment]
@Spikhalskiy our own code that searches for a web.xml or jetty-web.xml should be able to cope with CombinedResources and will handle the file existing in any of the combined resources.

The issue here is that we also make a URI property available to XML configurations so they can do things like `${web-inf.uri}/myresouce.xml` in their XML.  But if there are multiple WEB-INF directories combined into one, then we cannot obtain a single URI for them.  We are currently throwing a NPE trying to set that property.   The fix is to avoid the NPE and not set that property.  The Jetty code will then handle web.xml and jetty-web.xml correctly.   Only configurations trying to use the property will have problems.

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java (hunk 1 above)
Comment (Spikhalskiy) [reply jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java]: > If there truly are two WEB-INF directories, then we don't know which one to use

But that's not exactly the case all the time. At a minimum, if only one of them is having the jetty-web.xml file, that directory can be used.

But even using "the first one in the list" is a better approach than using none, at least it provides compatibility with Jetty 10/11 and still allows users a way to pass the jetty-web.xml at least somehow.

Comment (gregw) [reply jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java]: @Spikhalskiy This is only an issue for code that tries to use a URI property for WEB-INF.  Our code handles "first one in the list" when it looks for actual resources like jetty-web.xml.    The NPE is not coming from the main lookup path, but rather an optional mechanism to allow a single URI to be used in some circumstances.    If we fix the NPE, then our lookup of web.xml and jetty-web.xml should work exactly as you want

**Comment by Spikhalskiy** [comment]
@gregw so you are saying that configurations that are aware that there is a CombinedResource possible as WebInf resource will handle this correctly and jetty-web.xml will be successfully found by the Jetty code even while we passed null in JettyWebXmlConfiguration into these properties? 

It makes it better, thanks for the clarification.

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java (hunk 1 above)
Comment (Spikhalskiy) [reply jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JettyWebXmlConfiguration.java]: Makes sense, thank you for the clarification.

**Comment by Spikhalskiy** [comment]
My only suggestion here would be to add a debug or info log about not being able to populate the property because of several paths in WebInf config to simplify debugging for users. Thank you!

**Comment by janbartel** [comment]
> @gregw so you are saying that configurations that are aware that there is a CombinedResource possible as WebInf resource will handle this correctly and jetty-web.xml will be successfully found by the Jetty code even while we passed null in JettyWebXmlConfiguration into these properties?
> 
> It makes it better, thanks for the clarification.

Yes, that's exactly what he's saying.

I can add a `DEBUG` level log message about the the properties.

**Review by Spikhalskiy — APPROVED** [review]

**Review by gregw — APPROVED** [review]
