### PR TITLE
Issue #13457 threadsafe access to @HandlesTypes values

### LINKED ISSUE #13457: ClassCastException due to HashSet being used in a non thread-safe way
**Jetty version(s)**
12.0.24

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.7" 2025-04-15 LTS
OpenJDK Runtime Environment Temurin-21.0.7+6 (build 21.0.7+6-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.7+6 (build 21.0.7+6-LTS, mixed mode, sharing)

**OS type/version**
Windows 11

**Description**
Sometimes we get the following error upon startup:

```
Error scanning entry java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')

Ursprüngliche Fehlerbeschreibung:
(java.lang.ClassCastException)
class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
	java.lang.RuntimeException: Error scanning entry java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
		at org.eclipse.jetty.ee10.annotations.AnnotationParser.parseDir(AnnotationParser.java:613)
		at org.eclipse.jetty.ee10.annotations.AnnotationParser.parse(AnnotationParser.java:561)
		at org.eclipse.jetty.ee10.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
		at org.eclipse.jetty.util.ExceptionUtil.call(ExceptionUtil.java:339)
		at org.eclipse.jetty.util.ExceptionUtil$MultiException.callAndCatch(ExceptionUtil.java:277)
		at org.eclipse.jetty.ee10.annotations.AnnotationConfiguration.lambda$scanForAnnotations$0(AnnotationConfiguration.java:547)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:981)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1211)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1166)
		at java.base/java.lang.Thread.run(Thread.java:1583)
	Caused by: java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
		at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1994)
		at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:2110)
		at java.base/java.util.HashMap.treeifyBin(HashMap.java:778)
		at java.base/java.util.HashMap.putVal(HashMap.java:650)
		at java.base/java.util.HashMap.put(HashMap.java:618)
		at java.base/java.util.HashSet.add(HashSet.java:229)
		at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:338)
		at org.eclipse.jetty.ee10.annotations.AnnotationConfiguration$DiscoveredServletContainerInitializerHolder.addStartupClasses(AnnotationConfiguration.java:336)
		at org.eclipse.jetty.ee10.annotations.ContainerInitializerAnnotationHandler.handle(ContainerInitializerAnnotationHandler.java:49)
		at org.eclipse.jetty.ee10.annotations.AnnotationParser$MyClassVisitor.visitAnnotation(AnnotationParser.java:491)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:610)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
		at org.eclipse.jetty.ee10.annotations.AnnotationParser.parseClass(AnnotationParser.java:663)
		at org.eclipse.jetty.ee10.annotations.AnnotationParser.parseDir(AnnotationParser.java:609)
```

This happens when annotations are scanned asynchronously here:
https://github.com/jetty/jetty.project/blob/9a23f063144c0f70dc1a3d5021759419125cd149/jetty-ee9/jetty-ee9-annotations/src/main/java/org/eclipse/jetty/ee9/annotations/AnnotationConfiguration.java#L530C25-L543

Because then, `AnnotationConfiguration.DiscoveredServletContainerInitializerHolder.addStartupClasses` is called concurrently from multiple threads, and just adds the provided classes into a `HashSet` without any synchronization.

But HashSet is not thread-safe, so either some thread-safe alternative should be used, or access to it must be synchronized externally.

The workaround is to disable multi-threading for annotation scanning via the "org.eclipse.jetty.annotations.multiThreaded" property.

**How to reproduce?**
The failure happens intermittently, and more often on machines with lots of processors. Also, the probability to run into this is probably higher in large code bases.

### PR DESCRIPTION
**Pull request by janbartel**
closes #13457

### CODE REVIEW

File: jetty-ee9/jetty-ee9-annotations/src/main/java/org/eclipse/jetty/ee9/annotations/AnnotationConfiguration.java [hunk 1]
```diff
@@ -309,8 +309,8 @@ public int compare(ServletContainerInitializer sci1, ServletContainerInitializer
     
     public static class DiscoveredServletContainerInitializerHolder extends ServletContainerInitializerHolder
     {
-        private Set<Class<?>> _handlesTypes = new HashSet<>();
-        private Set<String> _discoveredClassNames = new HashSet<>();
+        private final Set<Class<?>> _handlesTypes = new HashSet<>();
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-annotations/src/main/java/org/eclipse/jetty/ee9/annotations/AnnotationConfiguration.java]: It's probably easier to just use thread-safe `Set` implementations here:

```java
private final Set<Class<?>> _handlesTypes = ConcurrentHashMap.newKeySet();
private final Set<String> _discoveredClassNames = ConcurrentHashMap.newKeySet();
```

instead of using `synchronized` blocks.

**Review by olamy — APPROVED** [review]

**Review by lorban — APPROVED** [review]
