### PR TITLE
Issue #13046 - Standardize URL Parameter Decoding in UrlEncoder methods

### LINKED ISSUE #13046: Restore `ee9` (and `ee8`) behaviors with parsing `application/x-www-form-urlencoded` parameters
**Jetty version(s)**
12.0.19

**Jetty Environment**
ee9/ee8 (not ee10)

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
In Jetty 10/11 the parsing of bad POST request body results in a 400 response.
In Jetty 12, on the ee9/ee8 environments, this doesn't happen anymore.
The bad encoding results in a replacement character instead.

Examples:

**Jetty 11.0.25 - `--add-modules=http,demo`**

```
$ curl -X POST http://localhost:8080/test/dump -d "foo=%88%A4"
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Unable to parse form content</title>
</head>
<body><h2>HTTP ERROR 400 Unable to parse form content</h2>
<table>
<tr><th>URI:</th><td>/test/dump</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Unable to parse form content</td></tr>
<tr><th>SERVLET:</th><td>Dump</td></tr>
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content</td></tr>
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! byte 88 in state 0</td></tr>
</table>
<h3>Caused by:</h3><pre>org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content
	at org.eclipse.jetty.server.Request.getParameters(Request.java:471)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:1049)
	at com.acme.Dump.doGet(Dump.java:123)
	at com.acme.Dump.doPost(Dump.java:86)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:520)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder$RunAs.service(ServletHolder.java:1371)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at com.acme.TestFilter.doFilter(TestFilter.java:92)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:197)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:569)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:301)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:193)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! byte 88 in state 0
	at org.eclipse.jetty.util.Utf8Appendable.appendByte(Utf8Appendable.java:249)
	at org.eclipse.jetty.util.Utf8Appendable.append(Utf8Appendable.java:151)
	at org.eclipse.jetty.util.UrlEncoded.decodeUtf8To(UrlEncoded.java:465)
	at org.eclipse.jetty.util.UrlEncoded.decodeTo(UrlEncoded.java:515)
	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:599)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:546)
	at org.eclipse.jetty.server.Request.getParameters(Request.java:466)
	... 56 more
</pre>
<hr/><a href="https://jetty.org">Powered by Jetty:// 11.0.25</a><hr/>

</body>
</html>
```

**Jetty 12.0.19 - `--add-modules=http,ee8-demos`**

```
$ curl -k -X POST http://localhost:8080/ee8-test/dump/info -d "foo=%88%A4"
<html>
<body>
<h1>Dump Servlet</h1>
<table width="95%"><tr>
<th align="right">getContentLength:&nbsp;</th><td>10</td></tr><tr>
<th align="right">getContentType:&nbsp;</th><td>application/x-www-form-urlencoded</td></tr><tr>
<th align="right">getContextPath:&nbsp;</th><td>/ee8-test</td></tr><tr>
<th align="right">getDispatcherType:&nbsp;</th><td>REQUEST</td></tr><tr>
...(snip lots of output)...
<th align="right">Content-Length:&nbsp;</th><td>10</td></tr><tr>
<th align="right">Content-Type:&nbsp;</th><td>application/x-www-form-urlencoded</td></tr><tr>
<th align="left" colspan="2"><big><br/>Request Parameters:</big></th></tr><tr>
<th align="right">foo:&nbsp;</th><td>��</td></tr><tr>
...(snip lots of output)...
</body>
</html>
```

Yet oddly, this behavior is maintained in ee10...

**Jetty 12.0.19 - `--add-modules=http,ee10-demos`**
```
$ curl -X POST http://localhost:8080/ee10-test/dump/info -d "foo=%88%A4"
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Unable to parse form content</title>
</head>
<body><h2>HTTP ERROR 400 Unable to parse form content</h2>
<table>
<tr><th>URI:</th><td>/ee10-test/dump/info</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Unable to parse form content</td></tr>
<tr><th>SERVLET:</th><td>Dump</td></tr>
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content</td></tr>
<tr><th>CAUSED BY:</th><td>java.util.concurrent.CompletionException: CharacterCodingException@1f7a33d9: Invalid UTF-8</td></tr>
<tr><th>CAUSED BY:</th><td>CharacterCodingException@1f7a33d9: Invalid UTF-8</td></tr>
</table>
<h3>Caused by:</h3><pre>org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.extractContentParameters(ServletApiRequest.java:1008)
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getParameters(ServletApiRequest.java:963)
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getParameter(ServletApiRequest.java:932)
	at org.example.Dump.doGet(Dump.java:121)
	at org.example.Dump.doPost(Dump.java:84)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder$RunAs.service(ServletHolder.java:1340)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1622)
	at org.example.TestFilter.doFilter(TestFilter.java:92)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.eclipse.jetty.ee10.servlets.QoSFilter.doFilter(QoSFilter.java:200)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1555)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:819)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:470)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:611)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1064)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:181)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler$LastRuleHandler.handle(RewriteHandler.java:159)
	at org.eclipse.jetty.rewrite.handler.Rule$Handler.handle(Rule.java:108)
	at org.eclipse.jetty.rewrite.handler.CookiePatternRule$1.handle(CookiePatternRule.java:99)
	at org.eclipse.jetty.rewrite.handler.Rule$Handler.handle(Rule.java:108)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:143)
	at org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:416)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.CompletionException: CharacterCodingException@1f7a33d9: Invalid UTF-8
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at org.eclipse.jetty.io.content.ContentSourceCompletableFuture.join(ContentSourceCompletableFuture.java:234)
	at org.eclipse.jetty.server.FormFields.getFields(FormFields.java:143)
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.extractContentParameters(ServletApiRequest.java:1003)
	... 42 more
Caused by: CharacterCodingException@1f7a33d9: Invalid UTF-8
	at org.eclipse.jetty.util.Utf8StringBuilder.takePartialString(Utf8StringBuilder.java:394)
	at org.eclipse.jetty.util.Utf8StringBuilder.takeCompleteString(Utf8StringBuilder.java:378)
	at org.eclipse.jetty.util.Utf8StringBuilder.build(Utf8StringBuilder.java:406)
	at org.eclipse.jetty.server.FormFields.parse(FormFields.java:404)
	at org.eclipse.jetty.server.FormFields.parse(FormFields.java:40)
	at org.eclipse.jetty.io.content.ContentSourceCompletableFuture.parse(ContentSourceCompletableFuture.java:126)
	at org.eclipse.jetty.server.FormFields.from(FormFields.java:293)
	... 44 more
</pre>
<hr/><a href="https://jetty.org/">Powered by Jetty:// 12.0.19</a><hr/>

</body>
</html>
```

### PR DESCRIPTION
**Pull request by joakime**
Attempt at standardizing the `UrlEncoder.decode*` methods into a standalone class that applies the same rules regardless if it's an input `String` or an `InputStream`, or even if charset is `UTF-8` or `US-ASCII` or `ISO-8859-1`. (no more UTF-8 specific API hacks/usage needed)

A new non-public `UrlParameterDecoder` class is introduced that parses 1 byte at a time. (this could easily be an internal class)
Taking the best of the implementations in `UrlEncoder` (legacy behaviors, allow modes) and `FormFields` (one byte at a time processing).

The existing testcases are mostly unchanged, just one expected throwable difference encountered.
Hopefully this will make the behaviors consistent across the board.

Closes #13046

### CODE REVIEW

**Review by gregw — COMMENTED** [review]
This will need JMH testing for performance

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java [hunk 1]
```diff
@@ -0,0 +1,330 @@
...
+        InputStreamReader reader = new InputStreamReader(input, charset);
+        while ((c = reader.read()) != -1)
+        {
+            parse((char)c);
+        }
+        complete();
+        return builder.hasCodingErrors();
+    }
+
+    private void parse(char c) throws CharacterCodingException
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java]: I think this method is too large to be JIT inlined.    So rather than call it in a loop char by char, perhaps it would be better to pass in a `Supplier<Character>` or an interface with a `char` equivalent.     The loop could then be in the method and bounds checking could be common.

@lorban is my optimization knowledge out of date? will this make a difference?

**Comment by joakime** [comment]
Looks like this is ready for a review now.
I'm starting to get green builds.

**Comment by joakime** [comment]
@gregw there are a few TODO's I added in UrlEncoder that could use a once over if you do a review of this.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java]: My knowledge of this level of detail probably is out of date too, but from the top of my head, all methods under ~20 bytecodes are candidates to be inlined.

This method seems to fit that bytecode limit, and even if it didn't, I fail to see how an equivalent method accepting a `Supplier<Character>` would be that different.

If you want to be certain, writing a microbenchmark is the way to go.

**Comment by lorban** [comment]
@gregw this implementation is naturally going to be slow, at least because it works with one byte/character at a time and has tons of (IMHO hard to predict) branches.

At first look, it seems @joakime just shuffled existing code around so I would say this PR probably doesn't have any perf impact and should be merged solely on its code cleanup merits.

But we could try to have a look at what it would take to optimize such code since this is all private implementation. Barring any algorithmic changes, it's going to be about concentrating on super-low-level details: can we parse 8 bytes at a time? Can we parse without branching, or by helping the JIT generate branchless code? If there are branches left, are they well predicted? Can we help the predictor? I don't think we've ever dug that deep, so this would mostly be an exercise in learning.

**Comment by lorban** [comment]
I wrote a small JMH benchmark to get a first impression of this code's performance as it currently is, and once again the results are surprising me. FYI, I benchmarked `urlParameterDecoder.parse("param=aaa&other=foo")` with JDK 24.

Here are the good parts:

```
UrlParameterDecoderBenchmark.testSmall:IPC                      thrpt             5.358              insns/clk
UrlParameterDecoderBenchmark.testSmall:branch-misses            thrpt             0.073                   #/op
UrlParameterDecoderBenchmark.testSmall:branches                 thrpt           551.031                   #/op
```

The pipeline is kept well fed; the benchmarking CPU is capable of executing 5-6 instructions per clock and the measured average (`IPC`) is at 5.3, which is excellent. There are many branches taken (`branches`) at 551 per operation bu they are well predicted as the mis-predictions (`branch-misses`) only are at 0.07 per operation. So my intuitions were mostly wrong.

And here are the parts that could be improved, but not by a large amount:

```
UrlParameterDecoderBenchmark.testSmall:instructions             thrpt          2391.939                   #/op
UrlParameterDecoderBenchmark.testSmall:cycles                   thrpt           446.386                   #/op
UrlParameterDecoderBenchmark.testSmall:stalled-cycles-frontend  thrpt             4.219                   #/op
UrlParameterDecoderBenchmark.testSmall:L1-dcache-load-misses    thrpt             2.537                   #/op
UrlParameterDecoderBenchmark.testSmall:L1-dcache-loads          thrpt           752.793                   #/op
```

The code only needs 446 clock cycles (`cycles`) per operation, but since we execute ~5 instructions per clock that still amounts to 2391 instructions per operation (`instructions`). The pipeline stalls 4.2 times per operation (`stalled-cycles-frontend`) meaning we could not feed enough data to keep it running. This is probably because we do 752 data loads (`L1-dcache-loads`) per operation and 2 of them miss the L1 (`L1-dcache-load-misses`).

Here is where most of the time is spent:

```
....[Hottest Methods (after inlining)]..............................................................
  49.75%     c2, level 4  org.eclipse.jetty.util.UrlParameterDecoder::parse, version 2, compile id 1128 
  17.06%     c2, level 4  org.eclipse.jetty.util.UrlParameterDecoder::parse, version 2, compile id 1135 
  12.08%    runtime stub  StubRoutines::jlong_disjoint_arraycopy_avx3 
  12.03%     c2, level 4  org.eclipse.jetty.util.UrlParameterDecoder::takeBuiltString, version 2, compile id 1137 
   5.72%          kernel  [unknown] 
```
so `takeBuiltString()` may be optimizable, as well as the disjoint array copy (I have no idea what needs it so far), plus I've counted 3 branches per loop in the generated ASM.

Conclusion: there isn't much perf left on the table, this code already is quite efficient.

**Comment by lorban** [comment]
Addendum: I think `jlong_disjoint_arraycopy_avx3` is caused by the `StringBuilder.toString()` call in `Utf8StringBuilder.takePartialString()`. This looks unavoidable as `String`s are immutable and require a copy.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java [hunk 2]
```diff
@@ -0,0 +1,330 @@
...
+        this.allowPartialBufferString = allowBadEncoding;
+    }
+
+    /**
+     * <p>Parse a String completely.</p>
+     *
+     * <p>The {@code newFieldAdder} is called for each encountered {@code key=value} pair.</p>
+     *
+     * @param str the string to parse, completing the parsing after parsing.
+     * @return true if there were no coding errors, false otherwise.
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java]: Javadoc is wrong: the method returns `true` if there _were_ coding errors.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java [hunk 3]
```diff
@@ -0,0 +1,330 @@
...
+
+    /**
+     * <p>Parse a String completely.</p>
+     *
+     * <p>The {@code newFieldAdder} is called for each encountered {@code key=value} pair.</p>
+     *
+     * @param str the string to parse, completing the parsing after parsing.
+     * @param offset the offset in the string to start parsing from.
+     * @param length the length of the substring to parse.
+     * @return true if there were no coding errors, false otherwise.
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java]: Javadoc is wrong: the method returns `true` if there _were_ coding errors.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java [hunk 4]
```diff
@@ -0,0 +1,330 @@
...
+
+    /**
+     * <p>Parse a InputStream completely.</p>
+     *
+     * <p>The {@code newFieldAdder} is called for each encountered {@code key=value} pair.</p>
+     *
+     * <p>The InputStream is read until EOF</p>
+     *
+     * @param input the InputStream to parse, completing the parsing after parsing.
+     * @return true if there were no coding errors, false otherwise.
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java]: Javadoc is wrong: the method returns `true` if there _were_ coding errors.

**Comment by joakime** [comment]
Some additional jmh comparison ...

There is a new [`UrlEncodedBenchmark`](https://github.com/jetty/jetty.project/blob/12.0.x/jmh-urlencoded/tests/jetty-jmh/src/main/java/org/eclipse/jetty/util/UrlEncodedBenchmark.java) found in branch [`12.0.x/jmh-urlencoded`](https://github.com/jetty/jetty.project/tree/12.0.x/jmh-urlencoded), with the following results.

```
Benchmark                            Mode  Cnt        Score        Error  Units
UrlEncodedBenchmark.testLargeForm   thrpt   10   248573.029 ±  24375.375  ops/s
UrlEncodedBenchmark.testLargeQuery  thrpt   10   684189.930 ±  22029.987  ops/s
UrlEncodedBenchmark.testSmallForm   thrpt   10  2599661.928 ± 198296.825  ops/s
UrlEncodedBenchmark.testSmallQuery  thrpt   10  6033048.044 ± 518752.652  ops/s
```

Raw jmh logs Attached: [12.0.x-jmh-urlencoded.log](https://github.com/user-attachments/files/19959425/12.0.x-jmh-urlencoded.log)

And the existing [`UrlParameterDecoderBenchmark`](https://github.com/jetty/jetty.project/blob/fix/12.0.x/restore-ee8-ee9-formparse-error/tests/jetty-jmh/src/main/java/org/eclipse/jetty/util/UrlParameterDecoderBenchmark.java) had 2 extra tests added (for InputStream / Form), with the following results.

```
Benchmark                                     Mode  Cnt        Score        Error  Units
UrlParameterDecoderBenchmark.testLargeForm   thrpt   10    63501.238 ±  10646.536  ops/s
UrlParameterDecoderBenchmark.testLargeQuery  thrpt   10   309100.686 ±  13351.519  ops/s
UrlParameterDecoderBenchmark.testSmallForm   thrpt   10   537784.069 ±  58279.181  ops/s
UrlParameterDecoderBenchmark.testSmallQuery  thrpt   10  4382828.755 ± 663287.794  ops/s
```

Raw jmh logs Attached: [12.0.x-jmh-urlparamdecoder.log](https://github.com/user-attachments/files/19959456/12.0.x-jmh-urlparamdecoder.log)

It is worth noting that the InputStream version on the original UrlEncoded does essentially 1/3rd of what the String version does due to it lacking nearly all of the `allowed*` behaviors.

Also, both the new `String` and new `InputStream` versions correctly handle the input when multi-byte characters are present, unlike the old version.

What this means ... imagine a form with `name=%£` was provided.
* In the original UrlEncoded the result would be `name=%?`
* In the new code in this PR the result is `name=%£`

This is because of a byte to char conversion bug in the original code.
Fixing this bug requires the use of a Charset against the InputStream. (for example)

**Comment by lorban** [comment]
@joakime enabling the `LinuxPerfAsmProfiler` reveals the following:

```
....[Hottest Methods (after inlining)]..............................................................
  31.60%           c2, level 4  sun.nio.cs.StreamDecoder::read0, version 2, compile id 1206 
  25.37%           c2, level 4  sun.nio.cs.StreamDecoder::forInputStreamReader, version 2, compile id 1242 
   9.78%           c2, level 4  sun.nio.cs.StreamDecoder::readBytes, version 2, compile id 1236 
   8.59%           c2, level 4  org.eclipse.jetty.util.jmh_generated.UrlParameterDecoderBenchmark_testSmallForm_jmhTest::testSmallForm_thrpt_jmhStub, version 5, compile id 1256 
   7.90%                kernel  [unknown] 
   5.91%           c2, level 4  org.eclipse.jetty.util.UrlParameterDecoder::parse, version 2, compile id 1207 
   4.32%           c2, level 4  sun.nio.cs.UTF_8$Decoder::decodeArrayLoop, version 2, compile id 1224 
   1.42%           c2, level 4  org.eclipse.jetty.util.UrlParameterDecoder::takeBuiltString, version 2, compile id 1230 
   1.16%           c2, level 4  sun.nio.cs.StreamDecoder::inReady, version 2, compile id 1241 
```

`StreamDecoder::forInputStreamReader` is called from the constructor of `InputStreamReader` and allocates an 8 KB byte buffer. We could save 25% of the execution time if the `InputStreamReader` did not need to be allocated for each `parse()` call.

So I tried adding this method:

```java
    public boolean parse(Reader reader) throws IOException
    {
        int c;
        while ((c = reader.read()) != -1)
        {
            parse((char)c);
        }
        complete();
        return builder.hasCodingErrors();
    }
```

and used this benchmark:

```java
    private final Reader reader = new InputStreamReader(new ByteArrayInputStream("param=aaa&other=foo".getBytes(UTF_8)));

    @Benchmark
    @BenchmarkMode(Mode.Throughput)
    public void testSmallForm(Blackhole blackhole) throws Exception
    {
        newFieldAdder.blackhole = blackhole;
        blackhole.consume(decoder.parse(reader));
    }
```

and I got a much better profile:

```
....[Hottest Methods (after inlining)]..............................................................
  74.42%  c2, level 4  java.io.InputStreamReader::read, version 2, compile id 1174 
  13.20%  c2, level 4  org.eclipse.jetty.util.jmh_generated.UrlParameterDecoderBenchmark_testSmallForm_jmhTest::testSmallForm_thrpt_jmhStub, version 6, compile id 1211 
   6.37%       kernel  [unknown] 
   4.94%  c2, level 4  sun.nio.cs.UTF_8$Decoder::decodeArrayLoop, version 2, compile id 1192 
```

but that would require modifying the API of `UrlParameterDecoder` and I'm not sure we can cache the `InputStreamReader` instances.

WDYT?

**Comment by joakime** [comment]
@lorban with a Reader based parse, I get the following on jmh ...

```
Benchmark                                           Mode  Cnt         Score         Error  Units
UrlParameterDecoderBenchmark.testLargeInputStream  thrpt   10    925489.606 ±  237698.845  ops/s
UrlParameterDecoderBenchmark.testLargeReader       thrpt   10  12001014.661 ± 1778580.368  ops/s
UrlParameterDecoderBenchmark.testLargeString       thrpt   10    291734.016 ±    8794.300  ops/s
UrlParameterDecoderBenchmark.testSmallInputStream  thrpt   10    996695.260 ±  149644.730  ops/s
UrlParameterDecoderBenchmark.testSmallReader       thrpt   10  12422690.315 ± 5172784.166  ops/s
UrlParameterDecoderBenchmark.testSmallString       thrpt   10   4074707.303 ±  546545.620  ops/s
```

**Comment by joakime** [comment]
With a better testing setup we get more realistic numbers.

```
Benchmark                                           Mode  Cnt        Score        Error  Units
UrlParameterDecoderBenchmark.testLargeInputStream  thrpt   10    54942.710 ±  14684.747  ops/s
UrlParameterDecoderBenchmark.testLargeReader       thrpt   10    60607.262 ±  22204.855  ops/s
UrlParameterDecoderBenchmark.testLargeString       thrpt   10   310555.497 ±  15057.205  ops/s
UrlParameterDecoderBenchmark.testSmallInputStream  thrpt   10   452588.767 ±  65690.304  ops/s
UrlParameterDecoderBenchmark.testSmallReader       thrpt   10   905345.879 ±  32401.785  ops/s
UrlParameterDecoderBenchmark.testSmallString       thrpt   10  3715869.088 ± 252428.945  ops/s
```

I'll change the UrlEncodedBenchmark too with these Setup changes.

**Comment by joakime** [comment]
This branch is now using the pull based parser.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java [hunk 5]
```diff
@@ -0,0 +1,422 @@
...
+class UrlParameterDecoder
+{
+    private final BiConsumer<String, String> newFieldAdder;
+    private final int maxLength;
+    private final int maxKeys;
+    private final boolean allowBadEncoding;
+    private final boolean allowBadPercent;
+    private final boolean allowTruncatedEncoding;
+    private final CharsetStringBuilder builder;
+    private final boolean allowPartialBufferString;
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java]: never assigned or used??

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java [hunk 6]
```diff
@@ -0,0 +1,422 @@
...
+            onNewField(name, "");
+        }
+    }
+
+    private String notValidPctEncoding(char hi, char lo)
+    {
+        return "Not valid encoding '%%%c%c'".formatted(hi != 0 ? hi : '?', lo != 0 ? lo : '?');
+    }
+
+    private void appendHexByte(char hi, char lo)
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java]: not used

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Utf8StringBuilder.java [hunk 7]
```diff
@@ -88,8 +96,31 @@ public Utf8StringBuilder(int capacity)
...
     {
         _buffer = buffer;
+        _handleMalformedInput = newRunnableErrorAction(onMalformedInput);
+        _handleUnmappableCharacter = newRunnableErrorAction(onUnmappableCharacter);
+    }
+
+    private Runnable newRunnableErrorAction(CodingErrorAction codingErrorAction)
+    {
+        if (codingErrorAction == CodingErrorAction.REPORT)
+            return () ->
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Utf8StringBuilder.java]: have a private static method and use a method reference here.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Utf8StringBuilder.java [hunk 8]
```diff
@@ -88,8 +96,31 @@ public Utf8StringBuilder(int capacity)
...
+            {
+                throw new Utf8IllegalArgumentException();
+            };
+
+        if (codingErrorAction == CodingErrorAction.REPLACE)
+            return () ->
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Utf8StringBuilder.java]: have a private method and use a method reference here.

**Review by gregw — CHANGES_REQUESTED** [review]

**Review by lorban — APPROVED** [review]
LGTM

**Review by gregw — APPROVED** [review]
Nice

**Comment by Bob20484096** [comment]
Hi, I tested the performance of Jetty 9.4 and Jetty 12.1.0 with the same code and identical CPU resources. The Jetty 9.4 service handled only 2,000 QPS, whereas Jetty 12 reached 8,000 QPS. Can this optimization be back-ported to version 9.4?

`
@RestController
@RequestMapping("/api")
public class EncodingTestController {

    @PostMapping(value = "/encoding", consumes = "application/x-www-form-urlencoded")
    public void testEncodingPostForm(
            @RequestParam(value = "field1", required = false) String field1,
            @RequestParam(value = "field2", required = false) String field2,
            @RequestParam(value = "field3", required = false) String field3,
            @RequestParam(value = "field4", required = false) String field4) {
        System.out.println("Form data - field1: " + field1);
        System.out.println("Form data - field2: " + field2);
        System.out.println("Form data - field3: " + field3);
        System.out.println("Form data - field4: " + field4);
    }
}`


field1~4=%E0%B8%9F%E0%B8%AB%E0%B8%81%E0%B8%A7%E0%B8%94%E0%B8%B2%E0%B9%88%E0%B8%81%E0%B8%9F%E0%B8%A7%E0%B8%AB%E0%B8%AA%E0%B8%94%E0%B8%B2%E0%B9%88%E0%B8%AB%E0%B8%9F%E0%B8%81%E0%B8%A7%E0%B8%94%E0%B8%AA%E0%B8%B2%E0%B8%9F%E0%B8%81%E0%B8%AB%E0%B8%A3%E0%B8%94%E0%B9%89%E0%B8%9F%E0%B8%AB%E0%B8%99%E0%B8%81%E0%B8%A3%E0%B8%94%E0%B8%B5
@joakime joakime Thank you! Wishing you a wonderful day as well.

**Comment by joakime** [comment]
> Can this optimization be back-ported to version 9.4?

No, Jetty 9.4 is at End of Life.

* #7958 

Jetty 9.4 is for Java 8, which cannot take advantage of the various performance improvements in the newer Java APIs that are necessary.
