### PR TITLE
Pass special content to interceptors

### LINKED ISSUE #7281: EOFs are not passed to interceptors any more - shouldn't they?
**Jetty version(s)**
10.x, 11.x

**Java version/vendor**
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

**OS type/version**
Windows 10 20H2, 64 bit

**Description**
Starting with the overhaul of `HttpInput` in PR #4556, EOFs are not passed to interceptors any more. The author was obviously also unsure whether this is a good idea, see `AsyncContentProducer.nextTransformedContent()`:
```
// TODO does EOF need to be passed to the interceptors?
```
So custom interceptors cannot react to EOF any more - which we have seen in use by an OSS library based on Jetty 9.4.

If one *would* pass EOF to the interceptors, this would require a small change in `GzipHttpInputInterceptor.readFrom()`, because it tries `getByteBuffer()` without a guard --> `IllegalStateException` in case of `SpecialContent`. For Comparison: In Jetty 9.4, `EofContent` had a `BufferUtil.EMPTY_BUFFER`, so `getByteBuffer()` worked like a charm.

Shouldn't custom interceptors be able to react to EOF nowadays?
This should at least be clarified in a detailed comment instead of the TODO comment.

**How to reproduce?**
Set a breakpoint next to the TODO comment in `AsyncContentProducer.nextTransformedContent()`.

### PR DESCRIPTION
**Pull request by lorban**
Modify the `AsyncContentProducer` accordingly and update `GzipHttpInputInterceptor` to correctly handle the existing `HttpInput.Content` contract.

I have not modified the special contents (error and EOF) to make them return an empty buffer when `getByteBuffer()` is called as IMHO the `Content` contract already is clear on that: calling `getByteBuffer()` when `isSpecial()` returns `true` does throw ISE.

So IMHO if there is some code out there that calls `Content.getByteBuffer()` without first checking the special flag, it is in breach of the contract as it was documented since 10.0.0; the fact that we never passed special content to interceptors should be irrelevant.

### CODE REVIEW

**Comment by lorban** [comment]
Note: I have not modified the special contents (error and EOF) to make them return an empty buffer when `getByteBuffer()` is called as IMHO the `Content` contract already is clear on that: calling `getByteBuffer()` when `isSpecial()` returns `true` does throw ISE.

So IMHO if there is some code out there that calls `Content.getByteBuffer()` without first checking the special flag, it is in breach of the contract as it was documented since 10.0.0; the fact that we never passed special content to interceptors should be irrelevant.

**Review by gregw — CHANGES_REQUESTED** [review]
Can we add and example to the javadoc somewhere like:
```java
@Override
public HttpInput.Content readFrom(HttpInput.Content content) {
    if (content.hasContent())
        processContent(content.getByteBuffer());
    if (content.isEof())
        endProcessing();
    return processedContent();
}
```

**Comment by lorban** [comment]
@gregw I've added some javadoc to the `Interceptor` interface, including some code examples and a reference to `GzipHttpInputInterceptor`.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java [hunk 1]
```diff
@@ -414,6 +414,40 @@ public String toString()
...
+     * which would not do anything with the content besides logging it. A more involved implementation could look like the
+     * following:
+     * <pre>
+     * public HttpInput.Content readFrom(HttpInput.Content content)
+     * {
+     *     if (content.hasContent())
+     *         processContent(content.getByteBuffer());
+     *     if (content.isEof())
+     *         endProcessing();
+     *     return processedContent();
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java]: This example is missing is `isSpecial()` call, which is the one actually used in the implementations.

I would suggest:

```suggestion
     *     if (content.hasContent())
     *         this.processedContent = processContent(content.getByteBuffer());
     *     if (content.isEof())
     *         disposeResources();
     *     return content.isSpecial() ? content : this.processedContent;
```

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java [hunk 2]
```diff
@@ -414,6 +414,40 @@ public String toString()
...
+     * }
+     * </pre>
+     * Please note that the {@link Content} contract must be respected by implementations, like for instance
+     * that calling {@link Content#getByteBuffer()} when {@link Content#isSpecial()} returns <code>true</code>
+     * throws {@link IllegalStateException}.
+     * </p>
+     * <p>Implementations implementing both this interface and {@link Destroyable} will have their {@link Destroyable#destroy()}
+     * method called when {@link #recycle()} is called.</p>
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java]: I would also add what implementation should do, since `HttpInput.Content` is a `Callback`, when they return a different object, with respect to the callback methods. Should an implementation call them or not?

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java [hunk 3]
```diff
@@ -334,34 +334,11 @@ public boolean isReady()
...
-                if (LOG.isDebugEnabled())
-                    LOG.debug("raw content is special (with error = {}), returning it {}", _error, this);
-                return _rawContent;
-            }
-
             if (_interceptor != null)
             {
                 if (LOG.isDebugEnabled())
                     LOG.debug("using interceptor to transform raw content {}", this);
                 _transformedContent = intercept();
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java]: If the interceptor returns an error or EOF, is it handled correctly in the block below?
Test cases for these 2 cases?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java (hunk 2 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java]: I've added some doc explicitly that it's up to the caller of the interceptor to manage the `Callback` lifecycle.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java (hunk 3 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java]: Fixed and added some more tests, thanks.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java (hunk 1 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java]: Okay, updated javadoc.

Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java]: Wait, does this mean `content.isSpecial()` is mutually exclusive to `content.hasContent()` always?

You'll never have a scenario where `(content.hasContent() && content.isSpecial())` is true?

Comment (winne42) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java]: @joakime at least, the JavaDoc on `HttpInput.hasContent()` says so:

> Always false on a special content.

File: jetty-server/src/test/java/org/eclipse/jetty/server/BlockingContentProducerTest.java [hunk 4]
```diff
@@ -116,6 +119,160 @@ public void testBlockingContentProducerNoInterceptorWithError()
...
+            {
+                contentSucceededCount.incrementAndGet();
+            }
+        })));
+        try (AutoLock lock = contentProducer.lock())
+        {
+            contentProducer.setInterceptor(content -> new HttpInput.ErrorContent(new Throwable("testBlockingContentProducerInterceptorGeneratesError interceptor error")));
+
+            HttpInput.Content content1 = contentProducer.nextContent();
+            assertThat(content1.isSpecial(), Matchers.is(true));
```
Comment (winne42) [inline jetty-server/src/test/java/org/eclipse/jetty/server/BlockingContentProducerTest.java]: `import static org.hamcrest.Matchers.is;` like in `AsyncContentProducerTest` looks nicer

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java [hunk 5]
```diff
@@ -414,6 +414,52 @@ public String toString()
...
+     *     instances, once {@link ByteBuffer#hasRemaining()} returns <code>false</code> {@link HttpInput} will make sure
+     *     {@link Callback#succeeded()} is called, or {@link Callback#failed(Throwable)} if an error occurs.</li>
+     *     <li>After {@link #readFrom(Content)} is called for the first time, subsequent {@link #readFrom(Content)} calls will
+     *     occur only after the contained byte buffer is empty (see above) or at any time if the returned content was special.</li>
+     *     <li>Once {@link #readFrom(Content)} returned a special content, subsequent calls to {@link #readFrom(Content)} must
+     *     always return the same special content.</li>
+     *     <li>Implementations implementing both this interface and {@link Destroyable} will have their
+     *     {@link Destroyable#destroy()} method called when {@link #recycle()} is called.</li>
+     * </ul>
+     * </p>
```
Comment (winne42) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java]: brilliant JavaDoc!

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java (hunk 1 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java]: @joakime a `Content` is special when it doesn't hold bytes but something more akin to a special event: EOF or an error. So yes, as was pointed out, the `Content` contract explicitly states that `hasContent()` returns `false` when content is special. Other methods also document specific behavior when the content is special.

I've modified the `Content.isSpecial()` javadoc to better explain this.

File: jetty-server/src/test/java/org/eclipse/jetty/server/BlockingContentProducerTest.java (hunk 4 above)
Comment (lorban) [reply jetty-server/src/test/java/org/eclipse/jetty/server/BlockingContentProducerTest.java]: Done, thanks.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java [hunk 6]
```diff
@@ -316,120 +316,144 @@ public boolean isReady()
...
+
+            // If the interceptor returned the raw content, recycle the raw content now if its empty.
+            if (_transformedContent == _rawContent && _rawContent.isEmpty() && !_rawContent.isSpecial())
             {
                 if (LOG.isDebugEnabled())
-                    LOG.debug("transformed content is not empty {}", this);
+                    LOG.debug("interceptor returned the raw content, recycle the empty raw content now {}", this);
+                _rawContent.succeeded();
+                _rawContent = _transformedContent = null;
+                return;
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java]: Unnecessary `return` statement.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java [hunk 7]
```diff
@@ -316,119 +316,144 @@ public boolean isReady()
...
-        while (_transformedContent == null)
-        {
-            if (_interceptor != null)
-            {
-                if (LOG.isDebugEnabled())
-                    LOG.debug("using interceptor to transform raw content {}", this);
-                _transformedContent = intercept();
-            }
-            else
+            if (_transformedContent != null && (_transformedContent.isSpecial() || !_transformedContent.isEmpty()))
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java]: 2nd & 3rd expressions are the opposite of the expressions at 343.
I think this could be simplified via:

```java
if (_transformed != null) 
{
    if (special && !empty) 
    {
        ...
    }
    else 
    {
        // block at 344
    }
}
```

In this way it would be IMHO clearer and less expression repetitions.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java [hunk 8]
```diff
@@ -316,119 +316,144 @@ public boolean isReady()
...
+            _transformedContent = intercept();
+
+            // If the interceptor generated a special content, _rawContent must become that special content.
+            if (_transformedContent != null && _transformedContent.isSpecial() && _transformedContent != _rawContent)
+            {
+                if (LOG.isDebugEnabled())
+                    LOG.debug("interceptor generated a special content, _rawContent must become that special content {}", this);
+                _rawContent.succeeded();
+                _rawContent = _transformedContent;
+                return;
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java:392]: If the interceptor generated an error content, should you not set `_error` as well?

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java [hunk 9]
```diff
@@ -316,119 +316,144 @@ public boolean isReady()
...
                 if (LOG.isDebugEnabled())
-                    LOG.debug("transformed content is not empty {}", this);
+                    LOG.debug("interceptor generated a null content, recycling the empty raw content now {}", this);
+                _rawContent.succeeded();
+                _rawContent = null;
+                return;
+            }
+
+            // If the interceptor returned the raw content, recycle the raw content now if its empty.
+            if (_transformedContent == _rawContent && _rawContent.isEmpty() && !_rawContent.isSpecial())
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java:406]: This `if` condition basically states that interceptors MUST completely consume the content.

It is what it is, but A) needs to be javadoc'ed and B) needs a safeguard (and a test case) because otherwise the implementation goes into a spin loop!

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java (hunk 5 above)
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java]: Remove this and following HTML `p` tags.

**Review by sbordet — CHANGES_REQUESTED** [review]
Please fix redundant `return`.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java (hunk 5 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpInput.java]: ok.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java (hunk 8 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java:392]: This is already done in the `intercept()` method.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java (hunk 7 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java]: Ok, done.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java (hunk 6 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java]: Removed it.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java (hunk 9 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContentProducer.java:406]: Good catch, let me add the necessary javadoc, safeguard check and tests.

**Review by sbordet — CHANGES_REQUESTED** [review]
I see 3 variables here:
- what type of input content (some content, empty content, EOF content, error content)
- what the interceptor does with the input content (full consume, partial consume, no consume)
- what type of output content (null, empty, non-empty, EOF, error, throw)

I would like, if possible, to have tests that cover all combinations of the 3 variables above.
I'd be happy to see tests for the most common cases.
Otherwise I'm good.

**Review by sbordet — DISMISSED** [review]

**Comment by gregw** [comment]
Doh! forced push!!!!! I can't review just the changes since my last review!!!!

**Review by gregw — DISMISSED** [review]

**Review by sbordet — APPROVED** [review]
