### PR TITLE
Fix ee10 path info only (alternative)

### LINKED ISSUE #9910: Inconsistent handling of welcome files between Jetty 10 and 12
**Jetty version(s)**
12.0.0.beta1

**Java version/vendor** `(use: java -version)`
```
$ java -version
java version "11.0.19" 2023-04-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.19+9-LTS-224, mixed mode)
```

**OS type/version**
```
$ uname -srv
Linux 6.3.6-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jun  5 15:45:04 UTC 2023
```

**Description**
When working on Pax Web welcome file handling, I found some differences between Jetty 10 and Jetty 12.

**How to reproduce?**

I have a quite complicated setup related to welcome file handling. For Pax Web 9 / Jetty 10 it is: 
https://github.com/ops4j/org.ops4j.pax.web/blob/web-9.0.9/pax-web-jetty/src/test/java/org/ops4j/pax/web/service/jetty/internal/UnifiedJettyTest.java#L659

Pax Web provides a copy of Jetty's DefaultServlet just to unprivate some methods and uses its extension called `org.ops4j.pax.web.service.jetty.internal.web.JettyResourceServlet` which is more aware of OSGi resource handling.

In this setup (`paxWebWelcomePagesWithDifferentContext()` test) I have:
* one `org.eclipse.jetty.ee10.servlet.ServletContextHandler` with `/c` context path and `{ "index.y", "index.x" }` welcome files
* 5 servlets:
  * `org.eclipse.jetty.ee10.servlet.DefaultServlet` mapped to `/` (redirectWelcome=false, welcomeServlets=true, pathInfoOnly=false, baseResource="target/b1")
  * `org.eclipse.jetty.ee10.servlet.DefaultServlet` mapped to `/r/*` (redirectWelcome=false, welcomeServlets=true, pathInfoOnly=true, baseResource="target/b2")
  * `org.eclipse.jetty.ee10.servlet.DefaultServlet` mapped to `/s/*` (redirectWelcome=true, welcomeServlets=true, pathInfoOnly=true baseResource="target/b3")
  * servlet mapped to `{ "*.x", "*.y" }` to print out values of attributes like `jakarta.servlet.forward.request_uri`
  * servlet mapped to `/gateway/*` which can be controlled to do redirect, forward or include

While almost everything works like it worked with Jetty 10, there's a difference when handling `/c/r/` URI.

In Jetty 10:
* servlet mapped to `/r/*` is invoked first
* in doGet(), `servletPath` is set to `/` because pathInfoOnly is true
* `javax.servlet.http.HttpServletRequest#getPathInfo()` returns `/`
* `pathInContext = URIUtil.addPaths(servletPath, pathInfo);` is `/` because both servletPath and pathInfo are `/`
* `org.eclipse.jetty.http.HttpContent.ContentFactory#getContent()` returns a resource which is directory, so `org.eclipse.jetty.server.ResourceService#sendWelcome()` is called
* `org.eclipse.jetty.server.ResourceService.WelcomeFactory#getWelcomeFile()` is called with `/`
* `_welcomes == ["index.y", "index.x"]`, but there are no such resources, so `org.eclipse.jetty.servlet.ServletHandler#getMatchedServlet()` is called with `/index.y` because `URIUtil.addPaths(pathInContext, s)` returned `/index.y` for `/` and `index.y`
* proper servlet mapped to `{ "*.x", "*.y" }` is returned.

In Jetty 12:
* servlet mapped to `/r/*` is invoked first
* in `org.eclipse.jetty.ee10.servlet.DefaultServlet#doGet()`:
  * `isPathInfoOnly()` returns true (as configured)
  * `jakarta.servlet.http.HttpServletRequest#getPathInfo()` returns `/` (as in Jetty 10)
  * `URIUtil.encodePath(req.getPathInfo())` returns `/` (correct)
  * `org.eclipse.jetty.server.ResourceService#getContent()` returns a directory resource (correct)
  * `org.eclipse.jetty.server.ResourceService#doGet()` continues and because the content is directory, `org.eclipse.jetty.server.ResourceService#sendWelcome()` is called
* `org.eclipse.jetty.server.ResourceService#welcome()` is called
* `org.eclipse.jetty.server.ResourceService#processWelcome()` is called
* `org.eclipse.jetty.server.ResourceService.WelcomeFactory#getWelcomeTarget()` is called
  * `request.getPathInfo()` is `/` (ok)
  * `org.ops4j.pax.web.service.jetty.internal.web.DefaultServlet#isPathInfoOnly()` returns true (as configured)
  * `requestTarget` is set to `/`
  * however `pathInContext` is set to the result of `org.eclipse.jetty.server.Request#getPathInContext()` and it's `/r/`
  * `URIUtil.addPaths(pathInContext, welcome)` returns `/r/index.y` for the first welcome file instead of expected `/index.y`

So while Jetty 10 consistently uses "path info" (full URI minus context path minus servlet path), in Jetty 12, the `path in context` is different in various places:
* in `org.eclipse.jetty.ee10.servlet.DefaultServlet#doGet()`, `encodedPathInContext` is set to the result of `URIUtil.encodePath(req.getPathInfo())` which is `/` (because pathInfoOnly is set to true and "path info" is `/`)
* however further down the thread, in `org.ops4j.pax.web.service.jetty.internal.web.DefaultServlet.ServletResourceService#getWelcomeTarget()`, `pathInContext` varilable is set to the result of `Request.getPathInContext(coreRequest)` which doesn't bother with the setting of `pathInfoOnly`.
* `requestTarget` variable is correct: `requestTarget = isPathInfoOnly() ? request.getPathInfo() : pathInContext`, but the welcome file is calculated using `String welcomeInContext = URIUtil.addPaths(pathInContext, welcome)` - IMO, `requestTarget` should be used here instead of `pathInContext`.

### PR DESCRIPTION
**Pull request by lorban**
Minimalistic fix for https://github.com/eclipse/jetty.project/issues/9910

This is an alternative to https://github.com/eclipse/jetty.project/pull/9921

### CODE REVIEW

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java [hunk 1]
```diff
@@ -1015,23 +1015,14 @@ private ServletResourceService(ServletContextHandler servletContextHandler)
...
-            String includedServletPath = (String)request.getAttribute(RequestDispatcher.INCLUDE_SERVLET_PATH);
-            String requestTarget;
-            if (includedServletPath != null)
-                requestTarget = getIncludedPathInContext(request, includedServletPath, isPathInfoOnly());
-            else
-                requestTarget = isPathInfoOnly() ? request.getPathInfo() : pathInContext;
-
             String welcomeTarget = null;
-            Resource base = _baseResource.resolve(requestTarget);
+            Resource base = content.getResource();
```
Comment (janbartel) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java:1025]: Do we need more null checks on content before using it? Both here and in `ResourceService.doGet()`?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java [hunk 2]
```diff
@@ -1015,23 +1015,14 @@ private ServletResourceService(ServletContextHandler servletContextHandler)
...
             if (Resources.isReadableDirectory(base))
```
Comment (janbartel) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java:1026]: Should we be checking the content instead of the base?

**Review by janbartel — APPROVED** [review]

**Comment by lorban** [comment]
@gregw What's your opinion? Do you prefer this PR or #9921?

**Review by gregw — APPROVED** [review]
This is much simpler
