### PR TITLE
Fix a bug around handling "Negotiate" case-insensitively in SpnegoAut…

### LINKED ISSUE #1709: Broke SpnegoAuthenticator trying to handle Negotiate case-insensitively
Over on #1698, we tried to be good citizens and accept a case-insensitive version of `Negotiate` sent by the client, but accidentally broke it in the process.

### PR DESCRIPTION
**Pull request by joshelser**
…henticator

Closes #1709

Signed-off-by: Josh Elser <elserj@apache.org>

### CODE REVIEW

File: jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java [hunk 1]
```diff
@@ -106,6 +108,47 @@ public Authentication validateRequest(ServletRequest request, ServletResponse re
...
+     * @return True if the auth scheme component is case-insensitively equal to {@code negotiate}, False otherwise.
+     */
+    boolean isAuthSchemeNegotiate(String authScheme)
+    {
+        if (authScheme == null || authScheme.isEmpty())
+        {
+            return false;
+        }
+        // Headers should be treated case-insensitively, so we have to jump through some extra hoops.
+        return authScheme.toLowerCase().startsWith(__NEGOTIATE_LC_TEXT);
```
Comment (Maaartinus) [inline jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java]: This does not do what the javadoc says. It returns true also for `"negotiate-when-hell-freezes-over"`.

I'd suggest just `__NEGOTIATE_LC_TEXT.equalsIgnoreCase(authScheme)`.

File: jetty-security/src/test/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticatorTest.java [hunk 2]
```diff
@@ -110,4 +112,32 @@ public void close()
...
+    public void testCaseInsensitiveHeaderParsing()
+    {
+        assertFalse(_authenticator.isAuthSchemeNegotiate(null));
+        assertFalse(_authenticator.isAuthSchemeNegotiate(""));
+        assertFalse(_authenticator.isAuthSchemeNegotiate("Basic"));
+        assertFalse(_authenticator.isAuthSchemeNegotiate("Basic foobar"));
+        assertFalse(_authenticator.isAuthSchemeNegotiate("Digest foobar"));
+        assertFalse(_authenticator.isAuthSchemeNegotiate("LotsandLotsandLots of nonsense"));
+        assertFalse(_authenticator.isAuthSchemeNegotiate("Negotiat asdfasdf"));
+
```
Comment (Maaartinus) [inline jetty-security/src/test/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticatorTest.java]: Please add
`assertFalse(_authenticator.isAuthSchemeNegotiate("Negotiated"));`

File: jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java (hunk 1 above)
Comment (gregw) [inline jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java]: Correct!  Since you added `getAuthSchemeFromHeader` a strict equality test can be used rather than startsWith!

**Comment by gregw** [comment]
@joshelser if you can fix that equality test from the comments, I'll merge this.

**Comment by joshelser** [comment]
> I'd suggest just __NEGOTIATE_LC_TEXT.equalsIgnoreCase(authScheme).

>  Since you added getAuthSchemeFromHeader a strict equality test can be used rather than startsWith!

Oops! Rather nice simplification :)

> Please add
assertFalse(_authenticator.isAuthSchemeNegotiate("Negotiated"));

Done.

These both are contained in db703af

**Comment by gregw** [comment]
Thanks @joshelser for the PR and @Maaartinus for the code review!
