### PR TITLE
Issue #14821 - fix race condition in websocket WebSocketDemander

### LINKED ISSUE #14821: Websocket IllegalStateException ('Demand already fulfilled') since Jetty 12.1
We're experiencing sporadic IllegalStateExceptions with error message 'Demand already fulfilled' since upgrading from Jetty 12.0 to Jetty 12.1.

The error happens in the websocket subsystem, the precise stacktrace is
```
java.lang.IllegalStateException: Demand already fulfilled
        at org.eclipse.jetty.websocket.core.util.WebSocketDemander.emitFrame(WebSocketDemander.java:101)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingDemander.inflate(PerMessageDeflateExtension.java:487)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingDemander.handle(PerMessageDeflateExtension.java:412)
        at org.eclipse.jetty.websocket.core.util.WebSocketDemander.process(WebSocketDemander.java:236)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:377)
        at org.eclipse.jetty.util.IteratingCallback.lambda$doOnSuccessProcessing$0(IteratingCallback.java:271)
        at org.eclipse.jetty.util.ExceptionUtil.callAndThen(ExceptionUtil.java:503)
        at org.eclipse.jetty.util.IteratingCallback.doOnSuccessProcessing(IteratingCallback.java:271)
        at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:575)
        at org.eclipse.jetty.websocket.core.util.WebSocketDemander.onFrame(WebSocketDemander.java:168)
        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.onFrame(PerMessageDeflateExtension.java:97)
        at org.eclipse.jetty.websocket.core.ExtensionStack.onFrame(ExtensionStack.java:115)
        at org.eclipse.jetty.websocket.core.WebSocketCoreSession.onFrame(WebSocketCoreSession.java:473)
        at org.eclipse.jetty.websocket.core.WebSocketConnection.onFrame(WebSocketConnection.java:296)
        at org.eclipse.jetty.websocket.core.WebSocketConnection.fillAndParse(WebSocketConnection.java:499)
        at org.eclipse.jetty.websocket.core.WebSocketConnection.onFillable(WebSocketConnection.java:365)
        at org.eclipse.jetty.io.AbstractConnection$FillableCallback.succeeded(AbstractConnection.java:319)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:54)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:492)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.epcRunTask(AdaptiveExecutionStrategy.java:428)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:401)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:255)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:204)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:317)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:1009)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1239)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1194)
        at java.base/java.lang.Thread.run(Thread.java:1516)
```
We are using the Jakarta WebSocket API (`@ServerEndpoint`) and not Jetty's websocket API directly. One observation we made is, that the error always happens when the `PerMessageDeflateExtension` handler is involved.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Closes #14821

If `demand()` is not called within `WebSocketDemander.emitFrame`, then there is a race condition where the `WebSocketDemander` will not check if there is still outgoing demand before processing another frame.

This results in the following exception `java.lang.IllegalStateException: Demand already fulfilled`.

The WebSocketDemander is used by the `permessage-deflate` extension and the `fragment` extension.

### CODE REVIEW

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/extensions/PerMessageDeflateDemandTest.java [hunk 1]
```diff
@@ -15,31 +15,34 @@
...
+import org.eclipse.jetty.websocket.core.TestMessageHandler;
+import org.eclipse.jetty.websocket.core.WebSocketComponents;
 import org.eclipse.jetty.websocket.core.client.CoreClientUpgradeRequest;
 import org.eclipse.jetty.websocket.core.client.WebSocketCoreClient;
 import org.eclipse.jetty.websocket.core.server.WebSocketUpgradeHandler;
 import org.junit.jupiter.api.AfterEach;
 import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
 
+import static org.awaitility.Awaitility.await;
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/extensions/PerMessageDeflateDemandTest.java:45]: Please rename this class to `PerMessage...` (capital M), since we are modifying it.
Other classes should be renamed similarly, but they are test classes and not involved in these changes.

**Review by sbordet — DISMISSED** [review]
LGTM. If you want to do the renaming that'll be good.

I think this should be fixed in 12.0.x as well.

**Comment by lachlan-roberts** [comment]
@sbordet this cannot be backported to `12.0.x` because we only reworked permessage-deflate in `12.1.x` to use this `WebSocketDemander` class.

**Review by sbordet — APPROVED** [review]
