### PR TITLE
#9984 fix URLResourceFactory isDirectory and newReadableByteChannel

### LINKED ISSUE #9984: URLResource.isDirectory() throws a NullPointerException when created from a jar:file: URL
**Jetty version(s)**
12.0.0.Beta2

**Java version/vendor** `(use: java -version)`
```
openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM (build 17.0.7+7-LTS, mixed mode, sharing)
```
**OS type/version**
macOS 13.4

**Description**
`URI.getPath()` can return `null` but `URLResourceFactory.URLResource.isDirectory()` assumes that it will not. This can result in a `NullPointerException`.

**How to reproduce?**

```java
new URLResourceFactory().newResource(new URL("jar:file:/example.jar!/")).isDirectory();
```

### PR DESCRIPTION
**Pull request by lorban**
Here are a couple of small fixes reported to us by the Spring team here: https://github.com/eclipse/jetty.project/issues/9984

The Jetty code base never goes into those codepaths, but they're nevertheless incorrect.

### CODE REVIEW

**Review by gregw — APPROVED** [review]
LGTM

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/UrlResourceFactoryTest.java [hunk 1]
```diff
@@ -38,35 +44,97 @@ public class UrlResourceFactoryTest
...
+            int read = channel.read(buffer);
+            assertThat(read, is(fileSize));
+        }
+    }
+
+    @Test
+    public void testJarFileUrl() throws Exception
+    {
+        Path path = MavenTestingUtils.getTestResourcePath("example.jar");
+        URL jarFileUrl = new URL("jar:file:" + path.toAbsolutePath() + "!/WEB-INF/web.xml");
```
Comment (joakime) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/UrlResourceFactoryTest.java:109]: One niggle, converting the path to a URL should be done properly, as windows users will have issues.
