### PR TITLE
Fixes #13375 - WebSocketClient attempts to use HTTP/2 on servers without SETTINGS_ENABLE_CONNECT_PROTOCOL

### LINKED ISSUE #13375: WebSocketClient attempts to use HTTP/2 on servers without SETTINGS_ENABLE_CONNECT_PROTOCOL
**Jetty version(s)**
12.0.23

**Description**

When a Jetty WebSocketClient has HTTP/2 enabled using HttpClientTransportDynamic it attempts to establish HTTP/2 WebSockets on servers that do not support it.

**How to reproduce?**

For example try connecting to `wss://echo.websocket.org` - this server currently supports HTTP/2 for HTML but not for WebSockets:

```java
public class WebSocketHttp2 {

    public static class Listener implements Session.Listener {
        private volatile Session session;

        @Override
        public void onWebSocketOpen(Session session) {
            this.session = session;
            session.demand();
        }
    }

    public static void main(String[] args) throws Exception {
        ClientConnector clientConnector = new ClientConnector();
        ClientConnectionFactory.Info http1 = HttpClientConnectionFactory.HTTP11;
        ClientConnectionFactory.Info http2 = new ClientConnectionFactoryOverHTTP2.HTTP2(new HTTP2Client(clientConnector));
        HttpClient httpClient = new HttpClient(new HttpClientTransportDynamic(clientConnector, http1, http2));
        WebSocketClient client = new WebSocketClient(httpClient);
        client.start();
        client.connect(new Listener(), URI.create("wss://echo.websocket.org")).get();
    }
}
```

Output:

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.io.IOException: protocol_error
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.example.WebSocketHttp2.main(WebSocketHttp2.java:35)
Caused by: java.io.IOException: protocol_error
	at org.eclipse.jetty.http2.client.transport.internal.HttpReceiverOverHTTP2.lambda$onReset$4(HttpReceiverOverHTTP2.java:242)
	at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:177)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:480)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:428)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:210)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:157)
```

You can see with `nghttp2` that this server does not advertise support:

```
nghttp -v https://echo.websocket.org/
[  0.087] recv SETTINGS frame <length=24, flags=0x00, stream_id=0>
          (niv=4)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):1048576]
          [SETTINGS_MAX_FRAME_SIZE(0x05):16384]
          [SETTINGS_MAX_HEADER_LIST_SIZE(0x06):262144]
```

Compare to a Jetty server which does:

```
nghttp -v https://localhost:8443
[  0.406] recv SETTINGS frame <length=24, flags=0x00, stream_id=0>
          (niv=4)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):128]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):524288]
          [SETTINGS_MAX_HEADER_LIST_SIZE(0x06):131072]
          [SETTINGS_ENABLE_CONNECT_PROTOCOL(0x08):1]
```

**Expected Behavior**

https://datatracker.ietf.org/doc/html/rfc8441#section-3

If the server does not advertise `SETTINGS_ENABLE_CONNECT_PROTOCOL` then the WebSocketClient should dynamically use HTTP/1.1 instead.

```
If a client were to use the provisions of the extended CONNECT method defined in
this document without first receiving a SETTINGS_ENABLE_CONNECT_PROTOCOL parameter, a non-supporting peer
would detect a malformed request and generate a stream error
```

Presumably Firefox is checking for this:

Image

Image

### PR DESCRIPTION
**Pull request by sbordet**
Now the client does not try to use HTTP/2 CONNECT + :protocol=websocket if the server does not support it, so the failure will happen in the client, not on the server.

When using `HttpClientTransportDynamic`, the client will try to fallback from HTTP/2 to HTTP/1 if possible, and retry the upgrade.

Moved the WebSocketOverHTTP2Test class to core, to avoid the eeN duplicates.

### CODE REVIEW

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java [hunk 1]
```diff
@@ -215,12 +219,40 @@ public void upgrade(Map<String, Object> context)
     protected void normalizeRequest(HttpRequest request)
     {
         super.normalizeRequest(request);
+        // Do not set the version explicitly, in case the
+        // request needs to be retried with a different version.
+        request.setVersion(HttpVersion.HTTP_2);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java]: The comment is unclear as it says _do not set the version explicitly_ but the next line does set the version explicitly.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketOverHTTP2Test.java [hunk 2]
```diff
@@ -391,23 +397,70 @@ public void testServerTimeout() throws Exception
...
+
+        startClient(clientConnector -> List.of(new ClientConnectionFactoryOverHTTP2.HTTP2(new HTTP2Client(clientConnector)), HttpClientConnectionFactory.HTTP11));
+
+        EventSocket clientEndpoint = new EventSocket();
+        URI uri = URI.create("ws://localhost:" + connector.getLocalPort() + "/echo");
+        ClientUpgradeRequest upgradeRequest = new ClientUpgradeRequest(uri);
+        // Force WebSocket upgrade with HTTP/2.
+        upgradeRequest.setHttpVersion(HttpVersion.HTTP_2.asString());
+
+        assertThrows(ExecutionException.class, () -> wsClient.connect(clientEndpoint, upgradeRequest).get(5, TimeUnit.SECONDS));
```
Comment (lorban) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketOverHTTP2Test.java]: Could you please add an assertion checking the type of the `ExecutionException`'s cause?

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java
Comment (lorban) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java:1]: Are all these tests redundant?

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee9/websocket/tests/WebSocketOverHTTP2Test.java
Comment (lorban) [inline jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee9/websocket/tests/WebSocketOverHTTP2Test.java:1]: Are all these tests redundant? Also, don't they have ee11 equivalents?

**Review by lorban — CHANGES_REQUESTED** [review]
Looks alright (minus a couple of nits) but I would like to be reassured about the tests.

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java [hunk 3]
```diff
@@ -215,12 +219,40 @@ public void upgrade(Map<String, Object> context)
...
+            else
+            {
+                // Check whether we can fall back to another HttpClientTransport.
+                boolean dynamic = getHttpDestination().getHttpClient().getHttpClientTransport() instanceof HttpClientTransportDynamic;
+                if (!dynamic)
+                    throw new HttpRequestException("Could not upgrade: CONNECT with :protocol disabled", request);
+
+                // We may be able to retry with another HttpClientTransport,
+                // therefore exclude this protocol from the next attempt.
+                List<String> excluded = new ArrayList<>(List.of("h2c", "h2"));
```
Comment (lachlan-roberts) [inline jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java]: We could avoid creating this list in the case there is already one in the attribute, and also avoid resetting the attribute if there was already a list there.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpClientTransportDynamic.java [hunk 4]
```diff
@@ -117,11 +122,12 @@ public Origin newOrigin(Request request)
                 // Find the first protocol that matches the version.
                 for (String p : info.getProtocols(secure))
                 {
-                    if (wanted.contains(p))
-                    {
-                        matchingInfos.add(info);
+                    if (excludedProtocols.contains(p))
```
Comment (lachlan-roberts) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpClientTransportDynamic.java]: Why is this case `break` and not `continue`?

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java]: I clarified the comment and added javadocs to the relevant methods.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpClientTransportDynamic.java (hunk 4 above)
Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpClientTransportDynamic.java]: Because for an `info` with `protocols=[h2c-17,h2c]`, if the first is excluded, then also the second would be.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketOverHTTP2Test.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/WebSocketOverHTTP2Test.java]: Done.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java
Comment (sbordet) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java:1]: These tests have been moved to core, rather than having duplicates in eeN.

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java]: Done.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpClientTransportDynamic.java (hunk 4 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpClientTransportDynamic.java]: But if the second protocol is excluded then the first can still be added to `matchingInfos` and break out of the loop. So the order of the protocols determines the result. Is this intentional?

Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpClientTransportDynamic.java]: Good point, I modified the code accordingly.

**Review by lachlan-roberts — DISMISSED** [review]

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/HttpClientTransportOverHTTP2.java [hunk 5]
```diff
@@ -98,6 +101,10 @@ static void configure(HttpClient httpClient, HTTP2Client http2Client)
     @Override
     public Origin newOrigin(Request request)
     {
+        HttpVersion version = request.getVersion();
+        HttpVersion http2 = HttpVersion.HTTP_2;
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/HttpClientTransportOverHTTP2.java]: why the variable? do a static import

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpRequest.java [hunk 6]
```diff
@@ -319,11 +323,23 @@ public boolean isVersionExplicit()
...
     }
 
+    /**
+     * <p>Sets the HTTP version, but non-explicitly.</p>
+     * <p>Use {@link #version(HttpVersion)} to set the version explicitly.</p>
+     *
+     * @param version the HTTP version
+     * @see #isVersionExplicit()
+     */
+    public void setVersion(HttpVersion version)
```
Comment (gregw) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpRequest.java]: The difference between `version` and `setVersion` is a little subtle especially when such standard names are used.   How about `useVersion(HttpVersion version)` for this method?

File: jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/HttpClientTransportOverHTTP3.java [hunk 7]
```diff
@@ -93,6 +96,10 @@ static void configure(HttpClient httpClient, HTTP3Client http3Client)
     @Override
     public Origin newOrigin(Request request)
     {
+        HttpVersion version = request.getVersion();
+        HttpVersion http3 = HttpVersion.HTTP_3;
```
Comment (gregw) [inline jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/HttpClientTransportOverHTTP3.java]: why the variable?

**Review by gregw — CHANGES_REQUESTED** [review]
A couple of niggles. I need to review a bit deeper

**Review by gregw — DISMISSED** [review]
