### PR TITLE
UriCompliance mode improvements #6132

### LINKED ISSUE #6132: Ambiguous segment in URI in DELETE /a/projects/foo/branches/refs%2Fheads%2Ftest request after upgrade from 10.0.0 to 10.0.2
**Jetty version**

10.0.0 vs. 10.0.02

**Java version**

Open JDK 11

**OS type/version**

Linux

**Description**

After upgrading Gerrit Code Review from 10.0.0 to 10.0.2: [1] DELETE requests are failing with 400.

If I activate debug logging in Jetty, I can see this ISE on Jetty 10.0.2: [2]. All is fine in Jetty 10.0.0 on Gerrit@HEAD:

```
DEBUG org.eclipse.jetty.server.HttpConnection : abort HttpConnection@32d5a0c9::SocketChannelEndPoint@22741abc{l=/127.0.0.1:35311,r=/127.0.0.1:37224,OSHUT,fill=-,flush=-,to=14/30000}{io=0/0,kio=0,kro=1}->HttpConnection@32d5a0c9[p=HttpParser{s=CLOSE,0 of -1},g=HttpGenerator@6d8711da{s=END}]=>HttpChannelOverHttp@b78266e{s=HttpChannelState@7c286cc6{s=HANDLING rs=BLOCKING os=ABORTED is=IDLE awp=false se=false i=true al=0},r=2,c=false/false,a=HANDLING,uri=null,age=35} {}
java.lang.IllegalStateException: s=HANDLING rs=BLOCKING os=COMPLETED is=IDLE awp=false se=false i=true al=0
	at org.eclipse.jetty.server.HttpChannelState.recycle(HttpChannelState.java:1025)
	at org.eclipse.jetty.server.Request.recycle(Request.java:1799)
	at org.eclipse.jetty.server.HttpChannel.recycle(HttpChannel.java:339)
	at org.eclipse.jetty.server.HttpChannelOverHttp.recycle(HttpChannelOverHttp.java:557)
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:452)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:865)
	at org.eclipse.jetty.server.HttpChannel.onBadMessage(HttpChannel.java:913)
	at org.eclipse.jetty.server.HttpChannelOverHttp.badMessage(HttpChannelOverHttp.java:182)
	at org.eclipse.jetty.http.HttpParser.badMessage(HttpParser.java:1636)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1618)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:379)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

To reproduce, clone [gerrit](https://gerrit.googlesource.com/gerrit) recursively, apply this CL: [1] and run from the command line:

  $ bazel test //javatests/com/google/gerrit/acceptance/rest/project:DeleteBranchIT

or, if you prefer to debug in Eclipse, generate `.project` and `.classpath`, running:

  $ tools/eclipse/project.py

And import gerrit workspace in Eclipse IDE. Then open `DeleteBranchIT.java`, and Run "debug as JUint test".

[1] https://gerrit-review.googlesource.com/c/gerrit/+/238383
[2] [jetty_logging.zip](https://github.com/eclipse/jetty.project/files/6257643/jetty_logging.zip)

### PR DESCRIPTION
**Pull request by gregw**
Fixes #6132 
This PR reverts the default behaviour to allows URIs that contain `%2F`.     I'm only 80% convinced of this and we need to consider really carefully before changing the default again.

The PR also contains a non-string based way to create custom `UriCompliance` instances.
It also introduces a new `Violation` that will allow ambiguous Uri to be passed to the application without extra normalisation.

### CODE REVIEW

File: jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java [hunk 1]
```diff
@@ -53,7 +55,11 @@
         /**
          * Ambiguous path parameters within a URI segment e.g. <code>/foo/..;/bar</code>
          */
-        AMBIGUOUS_PATH_PARAMETER("https://tools.ietf.org/html/rfc3986#section-3.3", "Ambiguous URI path parameter");
+        AMBIGUOUS_PATH_PARAMETER("https://tools.ietf.org/html/rfc3986#section-3.3", "Ambiguous URI path parameter"),
+        /**
+         * Non normal ambiguous paths. eg <code>/foo/x@2f/%2e%2e%/bar</code> provided to applications as <code>/foo/x/../bar</code>
+         */
+        NON_NORMAL_AMBIGUOUS_PATHS("https://tools.ietf.org/html/rfc3986#section-3.3", "Non normal ambiguous paths");
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: I think "non normal" is not descriptive enough. I'm not sure you wanted to have `@2f` in the javadocs, did you mean `%2f`?

How about `NON_CANONICAL_AMBIGUOUS_PATHS`?

File: jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java [hunk 2]
```diff
@@ -151,22 +178,22 @@ public static UriCompliance valueOf(String name)
...
             case "*":
-                sections = allOf(Violation.class);
+                violations = allOf(Violation.class);
                 break;
 
             default:
             {
                 UriCompliance mode = UriCompliance.valueOf(elements[0]);
-                sections = (mode == null) ? noneOf(Violation.class) : copyOf(mode.getAllowed());
+                violations = (mode == null) ? noneOf(Violation.class) : copyOf(mode.getAllowed());
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java:197]: Missing `break`.

File: jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java [hunk 3]
```diff
@@ -1733,12 +1734,45 @@ public void testAmbiguousSeparators() throws Exception
...
+    @Test
+    public void testAmbiguousPaths() throws Exception
+    {
+        _handler._checker = (request, response) ->
+        {
+            response.getOutputStream().println("servletPath=" + request.getServletPath());
+            response.getOutputStream().println("pathInfo=" + request.getPathInfo());
+            return true;
+        };
+        String request = "GET /unnormal/.././path/amiguous%2f%2e%2e/%2e;/info HTTP/1.0\r\n" +
```
Comment (sbordet) [inline jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java]: Fix typo: "amiguous".

File: jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java [hunk 4]
```diff
@@ -1733,12 +1734,45 @@ public void testAmbiguousSeparators() throws Exception
...
+            containsString("pathInfo=/path/info")));
+
+        _connector.getBean(HttpConnectionFactory.class).getHttpConfiguration().setUriCompliance(UriCompliance.from(EnumSet.of(
+            UriCompliance.Violation.AMBIGUOUS_PATH_SEPARATOR,
+            UriCompliance.Violation.AMBIGUOUS_PATH_SEGMENT,
+            UriCompliance.Violation.AMBIGUOUS_PATH_PARAMETER,
+            UriCompliance.Violation.NON_NORMAL_AMBIGUOUS_PATHS)));
+        assertThat(_connector.getResponse(request), Matchers.allOf(
+            startsWith("HTTP/1.1 200"),
+            containsString("pathInfo=/path/amiguous/.././info")));
```
Comment (sbordet) [inline jetty-server/src/test/java/org/eclipse/jetty/server/RequestTest.java]: Fix typo: "amiguous".

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java [hunk 5]
```diff
@@ -37,23 +39,29 @@
...
          */
         AMBIGUOUS_PATH_SEPARATOR("https://tools.ietf.org/html/rfc3986#section-3.3", "Ambiguous URI path separator"),
         /**
-         * Ambiguous path parameters within a URI segment e.g. <code>/foo/..;/bar</code>
+         * Allow ambiguous path parameters within a URI segment e.g. <code>/foo/..;/bar</code>
          */
-        AMBIGUOUS_PATH_PARAMETER("https://tools.ietf.org/html/rfc3986#section-3.3", "Ambiguous URI path parameter");
+        AMBIGUOUS_PATH_PARAMETER("https://tools.ietf.org/html/rfc3986#section-3.3", "Ambiguous URI path parameter"),
+        /**
+         * Allow Non canonical ambiguous paths. eg <code>/foo/x@2f/%2e%2e%/bar</code> provided to applications as <code>/foo/x/../bar</code>
```
Comment (joakime) [inline jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: Typo: `@2f`

File: jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java [hunk 6]
```diff
@@ -84,19 +92,29 @@ public String getDescription()
...
     /**
      * LEGACY compliance mode that disallows only ambiguous path parameters as per Jetty-9.4
      */
-    public static final UriCompliance LEGACY = new UriCompliance("LEGACY", EnumSet.of(Violation.AMBIGUOUS_PATH_SEGMENT, Violation.AMBIGUOUS_PATH_SEPARATOR));
+    public static final UriCompliance LEGACY = new UriCompliance("LEGACY", of(Violation.AMBIGUOUS_PATH_SEGMENT, Violation.AMBIGUOUS_PATH_SEPARATOR));
 
     /**
-     * Compliance mode that exactly follows RFC3986, including allowing all additional ambiguous URI Violations
+     * Compliance mode that exactly follows RFC3986, including allowing all additional ambiguous URI Violations. However ambiguous paths are
+     * normalised.
```
Comment (joakime) [inline jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: Typo: `normalized` - https://www.merriam-webster.com/dictionary/normalize

yes, I realize your usage is the British spelling, but we should remain consistent with the Java API and also the URI Spec usage of the more common English spelling.

* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URI.html#normalize()
* https://tools.ietf.org/html/rfc3986#section-6

**Review by joakime — CHANGES_REQUESTED** [review]
Minor changes.

File: jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java [hunk 7]
```diff
@@ -84,19 +92,29 @@ public String getDescription()
...
+     * The default compliance mode that extends RFC3986 compliance with additional violations to avoid most ambiguous URIs.
+     * This mode does allow {@link Violation#AMBIGUOUS_PATH_SEPARATOR}, but disallows
+     * {@link Violation#AMBIGUOUS_PATH_PARAMETER} and {@link Violation#AMBIGUOUS_PATH_SEGMENT}.
+     * Ambiguous paths are not allowed by {@link Violation#NON_CANONICAL_AMBIGUOUS_PATHS}.
      */
-    public static final UriCompliance DEFAULT = new UriCompliance("DEFAULT", noneOf(Violation.class));
+    public static final UriCompliance DEFAULT = new UriCompliance("DEFAULT", of(Violation.AMBIGUOUS_PATH_SEPARATOR));
 
     /**
      * LEGACY compliance mode that disallows only ambiguous path parameters as per Jetty-9.4
```
Comment (joakime) [inline jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: This description should probably be clear about which `Violation` types we allow here (like you did with the `DEFAULT` description, which is a good change btw)

File: jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java [hunk 8]
```diff
@@ -84,19 +92,29 @@ public String getDescription()
...
      */
-    public static final UriCompliance LEGACY = new UriCompliance("LEGACY", EnumSet.of(Violation.AMBIGUOUS_PATH_SEGMENT, Violation.AMBIGUOUS_PATH_SEPARATOR));
+    public static final UriCompliance LEGACY = new UriCompliance("LEGACY", of(Violation.AMBIGUOUS_PATH_SEGMENT, Violation.AMBIGUOUS_PATH_SEPARATOR));
 
     /**
-     * Compliance mode that exactly follows RFC3986, including allowing all additional ambiguous URI Violations
+     * Compliance mode that exactly follows RFC3986, including allowing all additional ambiguous URI Violations. However ambiguous paths are
+     * canonicalized for safety.
```
Comment (joakime) [inline jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: This description should probably be clear about which `Violation` types we allow here too.

File: jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java [hunk 9]
```diff
@@ -84,19 +92,29 @@ public String getDescription()
...
      */
-    public static final UriCompliance RFC3986 = new UriCompliance("RFC3986", allOf(Violation.class));
+    public static final UriCompliance RFC3986 = new UriCompliance("RFC3986", complementOf(of(Violation.NON_CANONICAL_AMBIGUOUS_PATHS)));
+
+    /**
+     * Compliance mode that exactly follows RFC3986, including allowing all additional ambiguous URI Violations, which may be passed
+     * to the application in non-normal form.
```
Comment (joakime) [inline jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: And this description too should probably be clear about which `Violation` types we allow here.

**Review by joakime — CHANGES_REQUESTED** [review]
~Is there a reason that the `private UriCompliance(String name, Set<Violation> violations)` is still private?~
~Can it be `public` to allow embedded users a better API?~

Never mind, the `.from(Set)` API is sufficient.

File: jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 10]
```diff
@@ -1746,9 +1746,9 @@ else if (encoded.startsWith("/"))
             path = (encoded.length() == 1) ? "/" : _uri.getDecodedPath();
             // Strictly speaking if a URI is legal and encodes ambiguous segments, then they should be
             // reflected in the decoded string version.  However, it can be ambiguous to provide a decoded path as
-            // a string, so we normalize again.  If an application wishes to see ambiguous URIs, then they can look
-            // at the encoded form of the URI
-            if (ambiguous)
+            // a string, so we normalize again.  If an application wishes to see ambiguous URIs, then they must
+            // set the NON_NORMAL_AMBIGUOUS_PATHS compliance.
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: Update comment to `NON_CANONICAL...`.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by gregw** [comment]
@joakime with regards to the `from` API, that doesn't allow us to set a name... do you think we should also allow custom mode names?

**Review by sbordet — APPROVED** [review]

**Comment by gregw** [comment]
@joakime nudge

**Review by joakime — APPROVED** [review]

**Comment by gregw** [comment]
@joakime something strange is happening.... you've approved the changes, but I'm still seeing a red cross and requested changes from you??? What does this issue look like to you?

**Comment by gregw** [comment]
Oh... as soon as I commented it went green! strange!!!
