### PR TITLE
Prevent `RBB.DynamicCapacity` from aggregating into a buffer passed to `add(ByteBuffer)`

### LINKED ISSUE #13567: Jetty 12.1.1 HTTP2 broken data
**Jetty version(s)**
12.1.1

**Jetty Environment**
ee11

**Java version/vendor** `(use: java -version)`
17.0.11

**OS type/version**
Windows 11

**Description**
Some Data that Jetty send to the client are broken which break the site. See the images for samples. If I disable HTTP/2 then all is working. Also with version 12.0.25 all is working.

Image

Image

### PR DESCRIPTION
**Pull request by lorban**
Modify `DynamicCapacity` to stop using the last enlisted buffer as an aggregator, as this buffer's ownership may not totally be under `DynamicCapacity`'s control.

Fixes #13567

### CODE REVIEW

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java [hunk 1]
```diff
@@ -2222,7 +2222,7 @@ public Mutable add(ByteBuffer bytes) throws ReadOnlyBufferException, BufferOverf
             if (LOG.isDebugEnabled())
                 LOG.debug("add BB {} <- {}", this, BufferUtil.toDetailString(bytes));
             checkNotReleased();
-            add(RetainableByteBuffer.wrap(bytes));
+            add(RetainableByteBuffer.wrap(bytes.asReadOnlyBuffer()));
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: Not another allocation!

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTest.java [hunk 2]
```diff
@@ -84,6 +87,53 @@
 
 public class HttpClientTest extends AbstractTest
 {
+    @ParameterizedTest
+    @MethodSource("transports")
+    public void testWriteSingleByteBufferInstanceInTwoParts(TransportType transportType) throws Exception
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTest.java:94]: This test should have:

* a barrier as first line in `handle()`, so that we maximize concurrency on the server.
* it must store what we sent from the server, and collect what we receive on the client, and compare the two. The point is that the server may overwrite content, but the number of bytes sent and received is the same.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/generator/DataGenerator.java [hunk 3]
```diff
@@ -45,7 +45,9 @@ public int generateData(RetainableByteBuffer.Mutable accumulator, int streamId,
         int length = Math.min(dataLength, Math.min(maxFrameSize, maxLength));
         if (length == dataLength)
         {
-            generateFrame(accumulator, streamId, data, last);
+            ByteBuffer readOnlyBuffer = data.asReadOnlyBuffer();
+            data.position(data.limit());
+            generateFrame(accumulator, streamId, readOnlyBuffer, last);
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/generator/DataGenerator.java]: Avoid allocation.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTest.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTest.java:94]: Was the above implemented? I unresolved this conversation as I think it's important to have it.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTest.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientTest.java:94]: I dismissed this too fast, now the test does use a barrier before each write and checks the integrity of the buffers.

**Review by sbordet — APPROVED** [review]
