### PR TITLE
Fixes #5409 - HttpClient fails intermittently with "Invalid response …

### LINKED ISSUE #5409: HttpClient fails intermittently with "Invalid response state TRANSIENT"
**Jetty version**
9.4.32.v20200930

**Java version**
11.0.8+10

**OS type/version**
- Windows Server 2012 R2 Standard
- Windows Server 2016 Data Center
- Windows Server 2016 Standard

**Description**
Since upgrading to Jetty 9.4.31, Requests sent from a Jetty `HttpClient` in our production system fail intermittently with an error saying "Invalid response state TRANSIENT".
The code that throws this exception resides in `HttpReceiver` and was introduced here:
https://github.com/eclipse/jetty.project/commit/e0955192b8e6aae6a20614388279ad5c4f893866#diff-c4aa5ed6568d33c882382bc50f770a82R841

The server to which the failing request should go is a Jetty server of the same version in the same local network.
We are now on 9.4.32, but the problem persists.

It's not clear to us whether the problem is due to a misuse of the `HttpClient` on our side, or whether it is a bug.
It's also hard to track down, since it fails intermittently and only in production.

Do you have any idea what could be the reason?

### PR DESCRIPTION
**Pull request by sbordet**
…state TRANSIENT".

The problem was a race condition during content decoding.
Since decoding needs to be done in a loop, the condition to loop is to
check whether there is demand for the next chunk of decoded content.

Checking for demand also sets the stalled flag, and this must be done
only after the response state has been set back to CONTENT.
Unfortunately this was not done in the decoding loop.

The fix is to always update the response state in the decoding loop.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java [hunk 1]
```diff
@@ -614,15 +565,42 @@ public boolean abort(HttpExchange exchange, Throwable failure)
         }
     }
 
+    private boolean updateResponseState(ResponseState from1, ResponseState from2, ResponseState to)
```
Comment (lorban) [inline jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java:568]: I'm not fond of this method's signature, what do you think of that one instead?
```java
private boolean updateResponseState(EnumSet<ResponseState> from, ResponseState to)
```
that would make the callers look like this:
```java
if (updateResponseState(EnumSet.of(ResponseState.HEADERS, ResponseState.CONTENT), ResponseState.TRANSIENT))
```

**Review by lorban — APPROVED** [review]
LGTM besides the minor proposal for a signature change. Good to go as-is if you don't like my suggestion.

File: jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java (hunk 1 above)
Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/HttpReceiver.java:568]: It allocates :smiley:
