### PR TITLE
Issue #10500 - preserve request header quoting when accessed through `JettyHttpExchangeDelegate`

### LINKED ISSUE #10500: Jetty 12 HTTP SPI does not preserve double-quotes on valid request headers
**Jetty version(s)**
12.01

**Jetty Environment**
ee10 and org.eclipse.jetty.http.spi

**Java version/vendor** `(use: java -version)`
Java 17, reproducable with any Java 17 version.

**OS type/version**
Windows 11

**Description**
A Soap request sets the following header value:

`Content-Type: multipart/related;start="<rootpart*dcb36243-479b-418e-868e-9681dcbedd73@example.jaxws.sun.com>";type="application/xop+xml";boundary="uuid:dcb36243-479b-418e-868e-9681dcbedd73";start-info="application/soap+xml;action=\"urn:ihe:iti:2007:ProvideAndRegisterDocumentSet-b\""`

It is of paramount importance that this header value is preserved AS-IS otherwise the soap request will fail.
Jetty will remove all " chars in this header value.

org.eclipse.jetty.http.spi.JettyHttpExchangeDelegate will do this in the getRequestHeaders() method.

Debugging yielded the following:
field.getValue() does return the correct header value with all quotes.
field.getValues() does returns a Collection with 1 element.

The one element is my header but without all my very important " marks.
Upon further inspection it appears that
QuotedCSV list = new QuotedCSV(false, value);
in org.eclipse.jetty.http.HttpField#getValueList removes my " marks.

This behavior did not occur in jetty 11.0.15 and breaks all my soap servers.

My Soap Endpoints are registered via normal Endpoint.publish means and that works with Both Jetty 11 and Jetty 12.
The Issue of removal of " only occurs in Jetty 12.

The entire getRequestHeaders() method is called by
com.sun.xml.ws.transport.http.server.ServerConnectionImpl#getRequestHeader
of com.sun.xml.ws:jaxws-rt.2.3.2
The code that calls JettyHttpExchangeDelegate  looks like this:

return httpExchange.getRequestHeaders().getFirst(headerName);

headerName is as mentioned before "Content-Type"

**How to reproduce?**

Do anything involving org.eclipse.jetty.http.spi.JettyHttpExchangeDelegate and set the `Content-Type` header to
`multipart/related;start="<rootpart*dcb36243-479b-418e-868e-9681dcbedd73@example.jaxws.sun.com>";type="application/xop+xml";boundary="uuid:dcb36243-479b-418e-868e-9681dcbedd73";start-info="application/soap+xml;action=\"urn:ihe:iti:2007:ProvideAndRegisterDocumentSet-b\""`

### PR DESCRIPTION
**Pull request by joakime**
* Add unit test for complex response header
* Add unit test for complex request header
* Add unit test for complex request multi-header
* Implement workaround in `JettyHttpExchangeDelegate` to preserve quoting on request headers

### CODE REVIEW

File: jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java [hunk 1]
```diff
@@ -68,9 +69,12 @@ public Headers getRequestHeaders()
...
         for (HttpField field : _request.getHeaders())
         {
-            if (field.getValue() == null)
+            String rawValue = field.getValue();
+            if (rawValue == null)
                 continue;
-            for (String value : field.getValues())
+            // Using raw QuotedCSV here to preserve quotes (which HttpField.getValues() doesn't do)
+            QuotedCSV quotedCSV = new QuotedCSV(true, rawValue);
+            for (String value : quotedCSV.getValues())
```
Comment (sbordet) [inline jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java]: Not all headers can be parsed with `QuotedCSV`, for example `User-Agent: ... (KHTML, like Gecko)...`.
`Expires` too has a comma, but it's only a response field.
Not sure if there are request fields that have dates in them, maybe `Date`, `If-Modified-Since`, etc.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java]: I've updated the PR.
On review of RFC9110, the following list of headers do not have value lists.

https://github.com/eclipse/jetty.project/blob/b64c2b431ea01f26fc17d7bab68cfa7c4fd0dd4d/jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java#L80-L97

File: jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java [hunk 2]
```diff
@@ -68,10 +69,40 @@ public Headers getRequestHeaders()
...
         for (HttpField field : _request.getHeaders())
         {
-            if (field.getValue() == null)
+            String rawValue = field.getValue();
+            if (rawValue == null)
                 continue;
-            for (String value : field.getValues())
-                headers.add(field.getName(), value);
+
+            String headerName = field.getLowerCaseName();
```
Comment (sbordet) [inline jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java]: No, use `field.getHeader()` so there is no need to lowercase and the switch will be more efficient.

File: jetty-core/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/SPIServerTest.java [hunk 3]
```diff
@@ -82,7 +87,244 @@ public void handle(HttpExchange exchange) throws IOException
         });
 
         URL url = new URL("http://localhost:" + port + "/");
-        assertThat(IO.toString(url.openConnection().getInputStream()), is("Hello"));
+        HttpURLConnection http = (HttpURLConnection)url.openConnection();
```
Comment (sbordet) [inline jetty-core/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/SPIServerTest.java]: We should not be using `HttpURLConnection`.
Either JDK's `HttpClient` or Jetty's, or `Socket` + `HttpTester` or `LocalConnector`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/SPIServerTest.java (hunk 3 above)
Comment (joakime) [reply jetty-core/jetty-http-spi/src/test/java/org/eclipse/jetty/http/spi/SPIServerTest.java]: Fixed

File: jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java (hunk 2 above)
Comment (joakime) [reply jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpExchangeDelegate.java]: `field.getHeader()` returns an `HttpHeader`, which is null for headers that are not hardcoded in the `HttpHeader` class.

**Review by sbordet — APPROVED** [review]

**Review by sbordet — APPROVED** [review]
