### PR TITLE
Log as info exceptions from server after sending stop with StopMojo.

### LINKED ISSUE #9129: jetty-maven-plugin JettyStopMojo intermittently errors with SocketException: Connection reset
**Jetty version(s)**
10.x and 11.x
(This issue does not happen with Jetty 9)

**Java version/vendor**
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**OS type/version**
Windows 10 Enterprise 

**Description**
Intermittently, the JettyStopMojo will error and print the following to console:
```
[INFO] --- jetty-maven-plugin:10.0.13:stop (stop-jetty) @ catalog-webapp ---
[INFO] Waiting 10 seconds for jetty 48952 to stop
[ERROR]
java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read (SocketInputStream.java:186)
    at java.net.SocketInputStream.read (SocketInputStream.java:140)
    at java.net.SocketInputStream.read (SocketInputStream.java:200)
    at org.eclipse.jetty.maven.plugin.JettyStopMojo.send (JettyStopMojo.java:225)
    at org.eclipse.jetty.maven.plugin.JettyStopMojo.lambda$execute$0 (JettyStopMojo.java:146)
    at java.util.Optional.ifPresentOrElse (Optional.java:201)
    at org.eclipse.jetty.maven.plugin.JettyStopMojo.execute (JettyStopMojo.java:133)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```
The process does shutdown successfully even when the error occurs and is printed to the console. Changing the stopWait value to 0 or a positive number has no effect on the behavior.

**How to reproduce?**

I am running 3 Jetty instances on 3 different ports to run integration tests against 3 different configurations of my webapp. Sometimes the error does not occur at all. Other times it will occur randomly for 1, 2, or all 3 of the stop-jetty calls.

Here is an abbreviated version of my pom.xml:

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <properties>
        <!-- Millis to wait between jetty startup checks -->        
        <maxChildStartCheckMs>1000</maxChildStartCheckMs>

        <!-- Seconds to wait for jetty to shutdown -->        
        <stopWait>5</stopWait>
        
        <!-- The stop ports for the jetty servers -->
        <stopPort1>10001</stopPort1>
        <stopPort2>10002</stopPort2>
        <stopPort3>10003</stopPort3>
        
        <stopKey>STOP</stopKey>
    </properties>

    <build>
        <plugins>

...

            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>10.0.13</version>
                <configuration>
                    <webApp>
                        <contextPath>/geocatalog</contextPath>
                    </webApp>
                    <useTestScope>true</useTestScope>
                </configuration>
                <!-- 
                    Here we start 3 webapps at the same time running on different ports.
                    
                    You can only run one jetty per jvm, so theortically one could run one
                    embedded and the other two forked.
                    
                    But for consistency of implementation, we fork them all.
                -->
                <executions>                    
                    <!-- Test server 1 -->
                    <execution>
                        <id>start-jetty-mongodb</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <!-- This jetty instance will run on default port 8080 -->
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <deployMode>FORK</deployMode>
                            <maxChildStartCheckMs>${maxChildStartCheckMs}</maxChildStartCheckMs>
                            <stopKey>${stopKey}</stopKey>
                            <stopPort>${stopPort1}</stopPort>
                            <!-- specify web xml location so it is not shared by the jetty instances -->
                            <forkWebXml>target/fork-mongo.xml</forkWebXml>
                        </configuration>
                    </execution>
                    <execution>
                        <id>stop-jetty-mongodb</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                        <configuration>
                            <stopKey>${stopKey}</stopKey>
                            <stopPort>${stopPort1}</stopPort>
                            <stopWait>${stopWait}</stopWait>
                        </configuration>
                    </execution>

                    <!-- Test server 2 -->
                    <execution>
                        <id>start-jetty-imageserver</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <deployMode>FORK</deployMode>
                            <maxChildStartCheckMs>${maxChildStartCheckMs}</maxChildStartCheckMs>
                            <stopKey>${stopKey}</stopKey>
                            <stopPort>${stopPort2}</stopPort>
                            <jvmArgs>-Djetty.port=8282</jvmArgs>
                            <!-- specify web xml location so it is not shared by the jetty instances -->
                            <forkWebXml>target/fork-is.xml</forkWebXml>
                        </configuration>
                    </execution>
                    <execution>
                        <id>stop-jetty-imageserver</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                        <configuration>
                            <stopKey>${stopKey}</stopKey>
                            <stopPort>${stopPort2}</stopPort>
                            <stopWait>${stopWait}</stopWait>
                        </configuration>
                    </execution>

                    <!-- Test server 3 -->
                    <execution>
                        <id>start-jetty-multidatasource</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <deployMode>FORK</deployMode>
                            <maxChildStartCheckMs>${maxChildStartCheckMs}</maxChildStartCheckMs>
                            <stopKey>${stopKey}</stopKey>
                            <stopPort>${stopPort3}</stopPort>
                            <jvmArgs>-Djetty.port=8383</jvmArgs>
                            <!-- specify web xml location so it is not shared by the jetty instances -->
                            <forkWebXml>target/fork-md.xml</forkWebXml>
                        </configuration>
                    </execution>
                    <execution>
                        <id>stop-jetty-multidatasource</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                        <configuration>
                            <stopKey>${stopKey}</stopKey>
                            <stopPort>${stopPort3}</stopPort>
                            <stopWait>${stopWait}</stopWait>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

...

        </plugins>
    </build>
</project>
```

### PR DESCRIPTION
**Pull request by janbartel**
Closes #9129

Catch and log at info level any exceptions from server after jetty StopMojo sends stop command.

### CODE REVIEW

**Review by sbordet — DISMISSED** [review]
I would `catch (Throwable)` like we do elsewhere, but besides that LGTM.

**Comment by hgs-sellis** [comment]
I might go the other direction and only `catch (SocketException)`, since we know it is expected and harmless. Anything else is unexpected and maybe should be propagated up the stack?

**Comment by janbartel** [comment]
> I might go the other direction and only `catch (SocketException)`, since we know it is expected and harmless. Anything else is unexpected and maybe should be propagated up the stack?

@gsf-sellis there's not much the plugin can do if there's any kind of exception thrown after we've sent the `forcestop` command. Depending on the configuration, the plugin will either exit straight away after sending the `forcestop` command, or - if we have been able to obtain the `pid` of the forked child ` - we will wait for the process to exit.

**Comment by hgs-sellis** [comment]
I'm just thinking in terms of keeping the catch block specific to the case that we know is harmless and that we can recover from. Anything else would be uncaught, propagated up the stack, and logged at a higher level than `info` (like the `SocketException` was before this PR). That said, however you all want to implement it is fine with me. Thanks for addressing the issue! I look forward to having clean logs again. :-)

**Comment by hgs-sellis** [comment]
> I look forward to having clean logs again. 

Oops I'm realizing now that `info` is the default log level, so that means this error will still appear in the logs?

I was hoping to maybe hide this error at the `info` level, since it is not really an error and makes the logs messy.

One option might be to `catch SocketException` and log it at `debug` or `trace`?

**Comment by janbartel** [comment]
> > I look forward to having clean logs again.
> 
> Oops I'm realizing now that `info` is the default log level, so that means this error will still appear in the logs?
> 
> I was hoping to maybe hide this error at the `info` level, since it is not really an error and makes the logs messy.
> 
> One option might be to `catch SocketException` and log it at `debug` or `trace`?

How about this: if `debug` is enabled we output the full stacktrace, otherwise we output an `info` with just the message?

**Comment by hgs-sellis** [comment]
That sounds great, thanks!

File: jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStopMojo.java [hunk 1]
```diff
@@ -220,9 +220,19 @@ private String send(String command, int wait)
...
+                    //Wait only a small amount of time to ensure TCP has sent the message
+                    s.setSoTimeout(1000);
+                    s.getInputStream().read();
+                }
+                catch (Exception e)
+                {
+                    if (getLog().isDebugEnabled())
+                        getLog().error("Error after sending command: " + command + ". Check the server state.", e);
+                    else
+                        getLog().info("Error after sending command: " + command + ". Check the server state.");
```
Comment (hgs-sellis) [inline jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStopMojo.java]: Maybe "Error" could be `e.getMessage()`? It's probably `SocketException: Connection reset` but could be something else.

Comment (janbartel) [reply jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStopMojo.java]: OK, how about the latest commit then?

Comment (hgs-sellis) [reply jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStopMojo.java]: Looks great! It's too bad we have to work around Windows TCP issues like this but it will be a quality of life improvement for me and others. Thanks!

**Review by hgs-sellis — APPROVED** [review]
