### PR TITLE
Fixes #2311 - TimeoutException when server sends unexpected content.

### LINKED ISSUE #2311: TimeoutException when server sends unexpected content
I use jetty 9.2.24.

Recently, I encounter a strange problem about "java.util.concurrent.TimeoutException: Total timeout elapsed" as following:

First, my log print this error: 
```
2018-03-10 10:39:23,972 WARN  [HttpClient@481748570-64][ROOT][org.eclipse.jetty.http.HttpParser 1318] badMessage: 400 Unknown Version for HttpReceiverOverHTTP@7181bf8e(rsp=IDLE,failure=null)[HttpParser{s=RESPONSE_VERSION,0 of -1}]".
```
Then,the next request always occur timeout exception. （I found this suspicious pattern in my log）.
So, I suspect this is a new bug of jetty.
Following is my reason:

At the very beginning, my first guess is the server didn't response,bug then i capture the network packeges,then i found when the time i send the request which would have TimeoutException, the packeges had sent and received the answer and ack.and the server has logs that has response the request . So i begin to suspect there is some bug maybe.

Then I began to search the log ,then I found the error pattern： If "badMessage: 400 Unknown Version for HttpReceiverOverHTTP" error occur,the next request would have timeoutException.

Please pay attention to my question,help very wanted!!!!!

### PR DESCRIPTION
**Pull request by sbordet**
Now exiting the parse loop when the response is complete; if there
are bytes remaining in the buffer, then it's cleared out.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java [hunk 1]
```diff
@@ -168,13 +169,23 @@ private boolean parse()
     {
         while (true)
         {
-            // Must parse even if the buffer is fully consumed, to allow the
-            // parser to advance from asynchronous content to response complete.
             boolean handle = parser.parseNext(buffer);
+            boolean complete = this.complete;
+            if (complete)
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java]: This `if` is not really needed and doesn't really help code readability

**Comment by sbordet** [comment]
100-Continue tests were broken by this change, working on it.
