### PR TITLE
Unable to redirect to error-page that is an HTML

### LINKED ISSUE #10122: in jetty12 beta build error-page redirects wrongly?
**Jetty version(s)**
I built jetty-12.0.x from source.
Modules I enabled:
java -jar start.jar --add-module=server,http,deploy,ee10-deploy,ee10-jsp,resources,ee10-jstl,client

**Java version/vendor** `(use: java -version)`
OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8)

**OS type/version**
Windows

**Description**
I have a web.xml that contains an error page:
```
	<error-page>
		<error-code>500</error-code>
		<location>/500.html</location>
	</error-page>
```
Now my normal servlet throws an exception:
```
protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
  throw new ServletException("This exception was thrown for testing purposes by testErrorPage test. It is not a bug!");
}
```
I should reach 500.html page after the error. It worked in older jettys for example 10 and 11.
But now it redirects into:
http://localhost:8080/pkg-sdkRequest-errorPage/500.html/
And this page gets a 404. If I remove the tailing / then it works correctly. In older jetty versions the redirect into 500.html worked correctly.

### PR DESCRIPTION
**Pull request by joakime**
The `Dispatcher$ErrorRequest` wasn't allowing the `DefaultServlet` (and `ResourceService`) to see the error-page mapping properly.

``` xml
	<error-page>
		<error-code>500</error-code>
		<location>/500.html</location>
	</error-page>
```

The internal RequestDispatcher is essentially doing ...

``` java
RequestDispatcher dispatcher = servletContext.getRequestDispatcher("/500.html");
dispatcher.error(request, response);
```

The ERROR dispatch to the `DefaultServlet` (and `ResourceService`) were however processing the original request to `/exception-servlet` and seeing a request with no pathInfo, a requestURL of `/exception-servlet`, a requestURI of `/500.html` and getting confused, thinking this was a request for a directory and issuing a 302 redirect to `/500.html/` to handle the directory properly.

### CODE REVIEW

**Comment by joakime** [comment]
I'm restoring the original assertion from https://github.com/eclipse/jetty.project/commit/9efce1580422fe35a978070e58ec4f0c53241afc#diff-2db903d841617ed7161f2eecd4945d01ddcddbe5e1e4ee0e937349f7c4d9d1cbL706

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DispatcherTest.java [hunk 1]
```diff
@@ -772,7 +772,7 @@ public void testDispatchMapping404() throws Exception
             \r
             """);
         response = HttpTester.parseResponse(rawResponse);
-        assertThat(response.getContent(), containsString("matchValue=DispatchServlet, pattern=/DispatchServlet, servletName=DispatchServlet, mappingMatch=EXACT"));
+        assertThat(response.getContent(), containsString("matchValue=TestServlet, pattern=/TestServlet, servletName=TestServlet, mappingMatch=EXACT"));
```
Comment (joakime) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/DispatcherTest.java:775]: This change was me just reverting the assertion change from commit https://github.com/eclipse/jetty.project/commit/9efce1580422fe35a978070e58ec4f0c53241afc#diff-2db903d841617ed7161f2eecd4945d01ddcddbe5e1e4ee0e937349f7c4d9d1cbL706

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 2]
```diff
@@ -645,26 +655,13 @@ public String getQueryString()
         @Override
         public String getRequestURI()
         {
-            return _uri == null ? null : _uri.getPath();
-        }
-
-        @Override
-        public Object getAttribute(String name)
```
Comment (lachlan-roberts) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java:652]: I think we still need to add certain attributes here for error dispatch. Why remove this TODO?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 3]
```diff
@@ -620,19 +619,30 @@ public DispatcherType getDispatcherType()
...
+            return _servletPathMapping;
+        }
+
         @Override
         public String getQueryString()
         {
-            // TODO
             if (_uri != null)
             {
                 String targetQuery = _uri.getQuery();
```
Comment (lachlan-roberts) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: I think this should always be target query and never the query from `_httpServletRequest`.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 4]
```diff
@@ -620,19 +619,30 @@ public DispatcherType getDispatcherType()
...
         {
+            if (_servletPathMapping == null)
+                return super.getServletPath();
             return _servletPathMapping.getServletPath();
         }
 
+        @Override
+        public HttpServletMapping getHttpServletMapping()
+        {
+            if (_servletPathMapping == null)
```
Comment (lachlan-roberts) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: For the same method in `ForwardRequest` this check is `_named != null`, maybe these should be consistent.

**Review by sbordet — CHANGES_REQUESTED** [review]
@joakime I have reservations about this PR, let's discuss them when you can.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 2 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java:652]: All of the `RequestDispatcher.ERROR*` attributes already exist at this point in time, there's no point doing it again at this level.

Also, many of the test cases in ErrorPageTest use those same attributes for assertions, proving that they are still present.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 4 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: If this is `_named != null` then it fails some DispatcherTests. (specifically AsyncContext.dispatch() tests to destination paths that don't exist and should throw a 404)
If this is `_servletPathMapping == null` then it passes both ErrorPageTest and DispatcherTest.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 3 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: I can find no statement in the spec about how to handle query here.
Original? ERROR Dispatch version? Merge here? Merge in RequestDispatcher?

We have no tests for query during error dispatch, even in Jetty 10/11.
Nor can I find a TCK tests that does this.

So I used the query from `_httpServletRequest`, as that `HttpServletRequest` has already been modified / wrapped to satisfy the HttpURI before this `Dispatcher$ErrorRequest` has been called, making the decision on which query to use moot.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 4 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: I tried to create a test case that uses a named servlet reference to handle a `sendError(597)` but was unable to support it.

``` xml
	<error-page>
		<error-code>597</error-code>
		<location>NamedErrorServlet</location>
	</error-page>
```

I don't think supporting `_named` in `Dispatcher$ErrorRequest` is possible.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 3 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: Fixed

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 4 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: I do not think it is possible to get a named error dispatcher as we only ever lookup a dispatcher for an error page by URI.  

Could probably put an `assert _named==null` in the `error` method.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 2 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java:652]: The `RequestDispatcher.ERROR_*` attributes are being set from 2 places before this `Dispatcher$ErrorRequest` is created.

* `org.eclipse.jetty.ee10.servlet.ServletRequestState.sendError(int code, String message)`
* `org.eclipse.jetty.ee10.servlet.ServletRequestState.sendError(Throwable th)`

If we want to mimic how `Dispatcher$ForwardRequest` attributes are handled in a future PR sure, but that's a bigger change that is out of scope for this PR.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 5]
```diff
@@ -620,19 +619,30 @@ public DispatcherType getDispatcherType()
         @Override
         public String getPathInfo()
         {
+            if (_servletPathMapping == null)
+                return super.getPathInfo();
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: what is the situation when we have an error dispatch with `_servletPathMapping == null`?  I don't think that is possible?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 6]
```diff
@@ -645,26 +655,13 @@ public String getQueryString()
...
-        @Override
-        public Object getAttribute(String name)
-        {
-            switch (name)
-            {
-                // TODO
-                default:
-                    return super.getAttribute(name);
-            }
+            return _uri == null ? super.getRequestURI() : _uri.getPath();
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: Is it possible to have an error page dispatch with a null URI?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 2 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java:652]: It is interesting that the attributes for forwarding and including are "set" by their request wrappers, but for error handling we still set the attributes on the actual request rather than just adding them via a wrapper.
That might be in part because we want to log some of them?  But it is probably mostly that we didn't get around to converting to the wrapping style.

I'm not sure we need to change this... just something to be aware of.... maybe put a comment in saying how/why it is different.

Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java:652]: I opened an issue on this at #10129 so we can review this behavior after 12.0.0 release.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 4 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: > Could probably put an `assert _named==null` in the `error` method.

Done.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 5 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: I thought only if there was no Default servlet on `/` url-pattern.
Turns out that's not a case either.

The `ErrorHandler.handle()` won't dispatch if the `RequestDispatcher` cannot find a page to dispatch to.
Meaning that even if the default servlet is unset, and something like `/doesnotexist` is requested, no `Dispatcher$ErrorRequest` is ever created.
The `ErrorHandler.handle()` will just return a generic error response if there is no match/mapping.

I changed all of these to `Objects.requireNonNull(_servletPathMapping)`

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java (hunk 6 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: in diagnosing the behavior on null `_servletPathMapping` it was discovered that having `_uri` be null is also no possible.

So I changed all of these to `Objects.requireNonNull(_uri)` too

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 7]
```diff
@@ -620,51 +621,42 @@ public DispatcherType getDispatcherType()
...
+        public StringBuffer getRequestURL()
         {
-            ArrayList<String> names = new ArrayList<>(Collections.list(super.getAttributeNames()));
-            // TODO
-            return Collections.enumeration(names);
+            Objects.requireNonNull(_uri);
+            return new StringBuffer(HttpURI.build(_uri)
+                .scheme(super.getScheme())
+                .host(super.getServerName())
+                .port(super.getServerPort())
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: This is sketchy to me. Why are we calling `super` here?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 8]
```diff
@@ -620,51 +621,42 @@ public DispatcherType getDispatcherType()
         @Override
         public String getPathInfo()
         {
-            return _servletPathMapping.getPathInfo();
+            return Objects.requireNonNull(_servletPathMapping).getPathInfo();
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: How is guaranteed that `_servletPathMapping` is non-null?

I think we should throw elsewhere, possibly from the creation of the dispatcher if `_servletPathMapping` is null.

Here I think we are just looking for trouble, wrapping into an `ErrorRequest` that when used throws NPE, therefore producing another error.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — DISMISSED** [review]

**Comment by joakime** [comment]
@sbordet @gregw the `AsyncServletTest` has a few test cases that expect the results of an ERROR dispatch to retain the query string.

The flow in the test cases are ...
1. an Async timeout occurs.
2. That is caught by ServletRequestState.unhandle
3. ServletRequestState triggers sendError that changes the state of the request
4. ServletChannel.handle handles the SEND_ERROR action
5. An ErrorPageErrorHandler mapping of all status codes 300 thru 599 (specified in the AsyncServletTest) returns the error-page of `"/error/custom"` (no query)
6. The history is added as path + query in the testcase, which is will return an empty query on ERROR dispatch in this flow

I had to remove the test of the query portion of those history assertions in `AsyncServletTest`

**Review by sbordet — APPROVED** [review]

**Comment by gregw** [comment]
@joakime @sbordet I'm pretty sure we need to restore the query string behavior. Even when forwarding the original query string is preserved on both the string and parameters.

**Comment by joakime** [comment]
@gregw is the query string merged? like in the case of forward/include?

Scenario 1:

1. Original request to `/foo?a=b`
2. During handling, servlet calls `sendError(500)`
3. Error mapping exists for status code 500, pointing to location `/error`
4. The ERROR dispatch to `/error` is a servlet.

Scenario 2:

1. Original request to `/foo?a=b`
2. During handling, servlet calls `sendError(500)`
3. Error mapping exists for status code 500, pointing to location `/error?c=d`
4. The ERROR dispatch to `/error` is a servlet.


Scenario 3:

1. Original request to `/foo?a=b`
2. During handling, servlet calls `AsyncContext.dispatch("/does-not-exist")`
3. Results in a 404
4. Error mapping exists for status code 404, pointing to location `/error`
5. The ERROR dispatch to `/error` is a servlet.


Scenario 4:

1. Original request to `/foo?a=b`
2. During handling, servlet calls `AsyncContext.dispatch("/does-not-exist")`
3. Results in a 404
4. Error mapping exists for status code 404, pointing to location `/error?c=d`
5. The ERROR dispatch to `/error` is a servlet.


What should `HttpServletRequest.getQueryString()` return in each case?

For the two AsyncContext.dispatch() scenarios, this is basically a double dispatch. (original, requested-bad-page, error)

**Comment by joakime** [comment]
I'm going to open an issue for this.

**Comment by joakime** [comment]
Opened new issue #10131
