### PR TITLE
Issue #5057 - Included root context path

### LINKED ISSUE #5057: `javax.servlet.include.context_path` attribute on root context. should be empty string, but is `"/"`
By the way - I don't have test yet, but when checking Jetty / Tomcat / Undertow, I saw that Jetty sets wrong value to `javax.servlet.include.context_path` attribute when using root context. should be empty string, but is `"/"`. I can think about PR later, but maybe already you have idea if it's wrong? (Undertow and Tomcat set it to `""`).

_Originally posted by @grgrzybek in https://github.com/eclipse/jetty.project/pull/5026#issuecomment-659326117_

### PR DESCRIPTION
**Pull request by gregw**
Root context path in include should be empty string.

### CODE REVIEW

**Review by joakime — APPROVED** [review]
Looks pretty straight forward to me.
+1

File: jetty-servlet/src/test/java/org/eclipse/jetty/servlet/IncludedServletTest.java [hunk 1]
```diff
@@ -173,4 +219,54 @@ private String getPotentialBody(HttpURLConnection connection)
             IO.close(in);
         }
     }
+
+    @Test
+    public void testIncludeAttributes() throws IOException
+    {
+        URI uri = baseUri.resolve("/attr/one");
+        System.out.println("GET (String): " + uri.toASCIIString());
```
Comment (lachlan-roberts) [inline jetty-servlet/src/test/java/org/eclipse/jetty/servlet/IncludedServletTest.java]: You might want to remove the print here and log instead.

**Review by lachlan-roberts — APPROVED** [review]

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 2]
```diff
@@ -591,6 +591,16 @@ public String getContextPathEncoded()
         return _contextPathEncoded;
     }
 
+    /**
+     * Get the context path in a form suitable to be returned from {@link HttpServletRequest#getContextPath()}
+     * @return Returns the encoded contextPath, or empty string for root context
+     */
+    public String getRequestContextPath()
```
Comment (janbartel) [inline jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java:599]: How does this compare to ContextHandler.Context.getContextPath()? see for example https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java#L2421.

**Review by janbartel — CHANGES_REQUESTED** [review]
Just clarify the difference with ContextHandler.Context.getContextPath() (ie should one use the other?) and then I'm +1.

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java (hunk 2 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java:599]: Interesting question, because I think `ContextHandler.Context.getContextPath()` is actually wrong in that it should be returning the encoded path. 
Eitherway, I think we should only have one of the two methods.... stand by....

Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java:599]: Question ... 

What happens in this situation ...

``` shell
$ cd /path/to/mybase
$ cd webapps
$ mkdir "this%2Fpath"
$ echo "can you see this" > "this%2Fpath/index.html"
```

What is the context path here?

Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java:599]: I think technically it would be`/this%252fpath` and should be ok other than being confusing.
But we should test and I expect some nasties.

Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java:599]: But I'd prefer not to hold up this PR for that.

**Review by janbartel — APPROVED** [review]
