### PR TITLE
Issue #11398 - allow frames to be demanded in WebSocket onOpen

### LINKED ISSUE #11398: WebSocket ClosedChannelException when demanding frames in onOpen
**Jetty version(s)**
12

**How to reproduce?**
For the `FrameHandler.onOpen` event, the callback is used to transition from state `CONNECTED` to `OPEN`. When you receive the `onOpen` notification in the Jetty WebSocket API the callback has not been completed and the session is in state `CONNECTED`. If the application then demands from `onOpen` a frame could be delivered before the callback is complete and throws a `CloseChannelException` because the session is not input open yet.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #11398

An alternate to this fix would be succeeding the `FrameHandler.onOpen` callback before calling the `openHandle` in `JettyWebSocketFrameHandler`.

### CODE REVIEW

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java [hunk 1]
```diff
@@ -213,4 +254,23 @@ public void testServerPing() throws Exception
...
+        URI uri = new URI("ws://localhost:" + connector.getLocalPort() + "/onOpen");
+        EventSocket clientSocket = new EventSocket();
+
+        Future<Session> connect = client.connect(clientSocket, uri);
+        Session session = connect.get(5, TimeUnit.SECONDS);
+        session.sendText("test-text", Callback.NOOP);
+
+        String received = onOpenSocket.textMessages.poll(5, TimeUnit.SECONDS);
+        assertThat(received, equalTo("test-text"));
+        onOpenSocket.onOpen.countDown();
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java]: @lachlan-roberts I think this is wrong.

We do not want 2 threads to enter WebSocket endpoint event methods concurrently, and I don't think we want the same thread to re-enter different event methods either.

The behavior that I'm expecting here is that the thread first exits `onWebSocketOpen()`, and then enters `onWebSocketFrame()`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java]: What about when processing a TEXT based message handler, and a PING control frame comes in and needs to be send to an endpoint ping handler?

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java [hunk 2]
```diff
@@ -213,4 +254,27 @@ public void testServerPing() throws Exception
...
+    public void testDemandInOnOpen() throws Exception
+    {
+        URI uri = new URI("ws://localhost:" + connector.getLocalPort() + "/onOpen");
+        EventSocket clientSocket = new EventSocket();
+
+        Future<Session> connect = client.connect(clientSocket, uri);
+        Session session = connect.get(5, TimeUnit.SECONDS);
+        session.sendText("test-text", Callback.NOOP);
+
+        // We cannot receive messages in onOpen even if we have demanded.
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java]:
```suggestion
        // We cannot receive messages while in onOpen, even if we have demanded.
```

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java [hunk 3]
```diff
@@ -74,6 +81,38 @@ public void onWebSocketFrame(Frame frame, Callback callback)
...
+            }
+        }
+
+        @Override
+        public void onWebSocketFrame(Frame frame, Callback callback)
+        {
+            if (frame.getOpCode() == OpCode.TEXT)
+                textMessages.add(BufferUtil.toString(frame.getPayload()));
+            callback.succeed();
+
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java]: Empty line!

Strictly speaking, this method should demand, otherwise CLOSE frames won't be received.
I think, also for example purposes, that would be better to demand.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java [hunk 4]
```diff
@@ -199,6 +199,43 @@ public void setUseOutputDirectByteBuffers(boolean useOutputDirectByteBuffers)
...
+            networkBuffer = newNetworkBuffer(initialBuffer.remaining());
+        }
+        ByteBuffer buffer = networkBuffer.getByteBuffer();
+        BufferUtil.clearToFill(buffer);
+        BufferUtil.put(initialBuffer, buffer);
+        BufferUtil.flipToFlush(buffer, 0);
+    }
+
+    /**
+     * Physical connection Open.
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java]: What does "Physical" mean here?

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java]: As not demanding for a close frame is probably an oft repeated mistake, then it is probably best to have tests for both demanding the close and not demanding for it.

**Review by gregw — DISMISSED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java]: > Strictly speaking, this method should demand, otherwise CLOSE frames won't be received.

I do not think this is true, demanding here will cause a `ReadPendingException`. Because there is no message sink registered, the JettyWebSocketFrameHandler will demand automatically when receiving a text/binary/continuation frame.

Maybe after addressing issue https://github.com/jetty/jetty.project/issues/11307 we would need to demand in the onFrame, but that is for a different PR.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java]: This has now been fixed in `WebSocketConnection`.

> What about when processing a TEXT based message handler, and a PING control frame comes in and needs to be send to an endpoint ping handler?

There is already logic to ensure only one thread doing the reading, parsing and delivering of the frames, so if we are delivering a TEXT message there can be no ping/pong being read/delivered simultaneously.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java (hunk 4 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java]: These are pre-existing comments and I didn't write them.

I will remove these comments, I don't think they are more helpful than the inherited javadoc.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java [hunk 5]
```diff
@@ -200,10 +200,39 @@ public void setUseOutputDirectByteBuffers(boolean useOutputDirectByteBuffers)
...
+    public void onOpen()
+    {
+        if (LOG.isDebugEnabled())
+            LOG.debug("onOpen() {}", this);
+
+        // Open Session
+        super.onOpen();
+        coreSession.onOpen();
+        if (moreDemand())
+            fillAndParse();
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java]: Ah this is the fix.  Hard to see as the methods were moved for some reason???

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java [hunk 6]
```diff
@@ -394,7 +418,7 @@ public boolean moreDemand()
                 case NOT_DEMANDING ->
                 {
                     fillingAndParsing = false;
-                    if (!networkBuffer.hasRemaining())
+                    if (networkBuffer != null && !networkBuffer.hasRemaining())
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java:387]:
```suggestion
                    if (BufferUtil.hasContent(networkBuffer))
```

**Review by gregw — DISMISSED** [review]
A little niggle/suggestion, otherwise OK

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java (hunk 5 above)
Comment (gregw) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java]: Actually, for better history, can you move these methods back to where they were?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java (hunk 6 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java:387]: Can't do because `networkBuffer` is a `RetainableByteBuffer`.

Unless you want me to make a new version of hasContent for this.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java (hunk 5 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java]: I'll move it back.

Although the ordering of the methods in this class is pretty unusual.
I would prefer to see `onOpen` and `onClose` grouped together, instead of `onClose` at the very top and `onOpen` at the very bottom.

**Review by gregw — APPROVED** [review]

**Review by sbordet — APPROVED** [review]
