### PR TITLE
Fix Content.Source InputStreamContentSource fillBufferFromInputStream

### LINKED ISSUE #13196: Download of large file may get stuck in an infinite loop (bug in `IOResources.copy` / `Content.Source`)
**Jetty version(s)**
12.0.21

**Jetty Environment**
any

**Java version/vendor**
any

**OS type/version**
any

**Description**
Assumptions around a requested content length being known when it's actually not (= `-1`) may lead to an infinite loop preventing a download to succeed.

**How to reproduce?**
Using `Content.Source`, read chunks of data from a data source providing at least 4 GiB of data

see attached example.

**Proposed fix**
1. In `fillBufferFromInputStream` of the anonymous `InputStreamContentSource` subclass under  `Content.Source.from(ByteBufferPool.Sized, InputStream, int, int)`, add code that checks for `toRead == -1`. Alternatively, create a separate anonymous  `InputStreamContentSource` implementation when `length == -1`, and perhaps also handle a simple case for `length == 0`? 

Minimal change, add the following check below the check for `if (toRead == 0)`:
```
                    if (toRead < 0)
                      return inputStream.read(buffer, 0, buffer.length);
```

3. Document that `-1` is a valid length in the corresponding JavaDoc for `Content.Source.from(ByteBufferPool.Sized, InputStream, int, int)
4. While we're at it, check the result of `inputStream.read` for a negative value, and return `-1` instead of erroneously subtracting a negative value from `toRead`.

### PR DESCRIPTION
**Pull request by kohlschuetter**
Previously, that method would fail to correctly handle downloads of large InputStreams returning at least 4 GiB when the specified length was -1.

Address several boundary checks and restructure the code a little bit.

Also document the use of "-1" indicating "full length" in the javadoc.

Fixes #13196

### CODE REVIEW

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 1]
```diff
@@ -293,9 +293,15 @@ protected int fillBufferFromInputStream(InputStream inputStream, byte[] buffer)
 
                     if (toRead == 0)
                         return -1;
-                    int toReadInt = (int)Math.min(Integer.MAX_VALUE, toRead);
-                    int len = toReadInt > -1 ? Math.min(toReadInt, buffer.length) : buffer.length;
+                    if (toRead < 0 || toRead > Integer.MAX_VALUE)
+                        return inputStream.read(buffer, 0, buffer.length);
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: shouldn't toRead be reduced by how many bytes are read here?

**Review by gregw — CHANGES_REQUESTED** [review]
Note that this has been reworked in 12.1 and thus this fix should not be merged forward

**Review by lorban — CHANGES_REQUESTED** [review]
This fix is missing a test.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 2]
```diff
@@ -293,9 +293,15 @@ protected int fillBufferFromInputStream(InputStream inputStream, byte[] buffer)
...
+
+                    int len = Math.min((int)toRead, buffer.length);
                     int read = inputStream.read(buffer, 0, len);
+                    if (read < 0)
+                    {
+                      return -1;
+                    }
                     toRead -= read;
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]:
```suggestion
                    if (read > 0)
                        toRead -= read;
```

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by sbordet** [comment]
@gregw note that also 12.1.x had bad handling of the correspondent code, so I opened #13206.

**Review by sbordet — APPROVED** [review]

**Review by lorban — APPROVED** [review]
