### PR TITLE
Issue #11271 - fix use of AliasCheckers with CombinedResource

### LINKED ISSUE #11271: `AllowedResourceAliasChecker` and `SymlinkAllowedResourceAliasChecker` do not work with a `CombinedResource`
**Jetty version(s)**
12

**Jetty Environment**
All

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
Both the `AllowedResourceAliasChecker` and `SymlinkAllowedResourceAliasChecker` implementations will fail if the base resource is a `CombinedResource` due to the `_base` logic between the two classes.

Those default implementations should work with a `CombinedResource`.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Issue #11271

Add support for CombinedResource in `AllowedResourceAliasChecker` and `SymlinkAllowedResourceAliasChecker`.

Also added more testing into `AliasCheckerSymlinkTest`.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java [hunk 1]
```diff
@@ -172,14 +180,20 @@ protected boolean isAllowed(Path path)
...
+                if (isSameFile(path, _baseResource))
                     return true;
 
                 // If the path is the same file as any protected resources, then it is protected.
-                for (Path p : _protected)
+                for (String protectedTarget : _protected)
                 {
-                    if (isSameFile(path, p))
-                        return false;
+                    Resource p = _baseResource.resolve(protectedTarget);
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java:188]: @gregw this is probably not ideal, can you think of a better way to do this?

If we do the resolve where it was done before in `extractBaseResourceFromContext()` then it could return null if the protected target resource does not exist at that time. But do we want to just never check the protected target if it didn't exist initially?

Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java:188]: Don't we already have the precise `Resource` (to check) already resolved and handed to us in the `public boolean checkAlias(String pathInContext, Resource resource)` method?

Why are we attempting to resolve it again against the context.baseResource?

Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java:188]: We're resolving the protectedTarget here. We can pull a list of protectedTargets as strings from the `ContextHandler`.

Previously we were resolving the protectedTarget as a path against the base resource during the initialization. However with the `CombinedResource` there may be multiple protected targets for each string like `WEB-INF`. If we resolve them at initialization they could be null meaning they don't exist at that time.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/SymlinkAllowedResourceAliasChecker.java [hunk 2]
```diff
@@ -57,29 +57,33 @@ protected boolean check(String pathInContext, Path path)
...
 
         try
         {
             for (String segment : segments)
             {
                 // Add the segment to the path and realURI.
-                fromBase = fromBase.resolve(segment);
-                realURI.append("/").append(fromBase.toRealPath(NO_FOLLOW_LINKS).getFileName());
+                segmentPath.append("/").append(segment);
+                Resource fromBase = _baseResource.resolve(segmentPath.toString());
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/SymlinkAllowedResourceAliasChecker.java:69]: This line has a different behaviour than before which is causing the change to the test at `DefaultServletTest#testGetPercent2F`. Before we were resolving a path, this caused the `toRealPath` would throw because it still had the `%2F` which did not exist.

However the `Resource.resolve()` resolves as a URI then does a `Paths.get()` which resolves the `%2F` to a `/`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java:188]: @lachlan-roberts Could you do the resolves of protected resources to resources in `extraceBaseResourceFromContext` and then just have a list of them (yes they would now be a `List<Resource>` rather than a `CombinedResource` that contained a `List<Resources>`)

We can have Resources that don't exist right???

Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java:188]:
```suggestion
                    Resource r = _baseResource.resolve(protectedTarget);
```

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java [hunk 3]
```diff
@@ -192,6 +206,26 @@ protected boolean isAllowed(Path path)
         return false;
     }
 
+    protected boolean isSameFile(Path path, Resource resource)
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java]: We could have `isSameFile(Path)` as a method on `Resource`, then only `CombinedResource` would need the iteration.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/AliasCheckerSymlinkTest.java [hunk 4]
```diff
@@ -69,69 +73,111 @@ private static void delete(Path path)
         IO.delete(path.toFile());
     }
 
-    private static void setAliasChecker(AliasCheck aliasChecker)
+    private static void setAliasChecker(ContextHandler contextHandler, AliasCheck aliasChecker) throws Exception
     {
-        _context.clearAliasChecks();
+        // TODO: why do I need to manually manage the lifecycle???
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/AliasCheckerSymlinkTest.java]: Good question!  Why do you?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java:188]: > We can have Resources that don't exist right???

No we can't, if you do the `resource.resolve()` and it doesn't exist it will return null.

Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java:188]: Can't do, will conflict with another Resource r.

p for protected resource, seems okay to me.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/AliasCheckerSymlinkTest.java (hunk 4 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-tests/jetty-ee10-test-integration/src/test/java/org/eclipse/jetty/ee10/test/AliasCheckerSymlinkTest.java]: it was a bug in the `HotSwapHandler`. fixed now

**Comment by lachlan-roberts** [comment]
@gregw with the change in behaviour to `SymlinkAllowedResourceAliasChecker`, now `testRelativeRedirect` and `testResourceRedirect` are failing from `ResourceHandlerTest`.

They are expecting a request for `/context/dir/index.html/` will redirect to `/context/dir/index.html`, but now the alias is rejected (because there is no symlink) and we get 404.

Are we ok with this behaviour change? if so I will just make these tests use the `AllowedResourceAliasChecker`.

**Comment by gregw** [comment]
@lachlan-roberts there is a bit to unpack here.

Firstly the redirect from `/context/dir/index.html/` to `/context/dir/index.html` is kind of to avoid the alias in the first place. @lorban Could (should?) the redirection of resources like this happen before we check for aliases?

Otherwise, I don't like behaviour changes.... but I think in this case it is really REALLY strange that by adding something to allows symlinks we are also allowing arbitrary aliasing within the docroot, possibly bypassing security checks etc.  To me that was wrong behaviour in the first place, so I'm kind of OK with changing it.

What is the additive behaviour of alias checkers?   Does it just need to be approved by one?   In which case the fix for anybody that complains is to add both symlinks and allowed alias checkers (does that fix the failing test?)

However, I am still curious as to why there is a behaviour change?   What was the previous checker doing that says `/context/dir/index.html/` is an OK alias, but that `/context/dir%2Findex.html` is not?   What operation was not decoding the %2F before?

**Comment by lorban** [comment]
@gregw AFAICT alias checking should take precedence over everything else. This is how they were designed, and it's what I think makes the most sense.

So it feels like this (fortunately small) change of behavior is actually fixing something that used to be incorrect.

**Comment by lachlan-roberts** [comment]
> What is the additive behaviour of alias checkers? Does it just need to be approved by one? 

@gregw yes it just needs to be approved by one, so adding `AllowedResourceAliasChecker` will cause it to pass.

> However, I am still curious as to why there is a behaviour change? What was the previous checker doing that says /context/dir/index.html/ is an OK alias, but that /context/dir%2Findex.html is not? What operation was not decoding the %2F before?

In the `/dir%2Findex.html` case, previously we would throw because the file `dir%2Findex.html` did not exist. Now we are passing the test as it matches to an alias of `dir/index.html` which does exist, but there is no symlink in the path so the `SymlinkAllowedResourceAliasChecker` still rejects it. So this one still contains some behaviour change.

The `/context/dir/index.html/` case it is an alias for the `index.html` file, which if approved `ResourceService` will see its a file ending with `/` and will redirect to  `/context/dir/index.html`.

**Comment by gregw** [comment]
We should not allow dir%2Findex.html just because we allow symlinks.  This is exactly the kind of security constraint bypassing alias that the alias mechanism was implemented to protect against.

**Comment by lachlan-roberts** [comment]
> We should not allow dir%2Findex.html just because we allow symlinks. This is exactly the kind of security constraint bypassing alias that the alias mechanism was implemented to protect against.

Then we are going to have to rethink the design of our alias checkers. We never re-verify against the security constraints, only the protected targets. We even say in the javadoc:
```
Aliases approved by this may still be able to bypass SecurityConstraints, 
so this class would need to be extended to enforce any additional 
security constraints that are required.
```

We only base this on whether it is a file inside the base resource which is not a protected target. And for the symlink checker once we hit a symlink file which is an allowed resource we approve, regardless of what comes after that symlink.

**Comment by gregw** [comment]
@Lachlan why do we need a big rethink? If somebody adds the allowed file resource checker, then any alias is ok so long as it is in the docroot and not protected.

If they add them symlink checker it should just allow Sym links and not arbitrary other aliases.  The name says it!

**Comment by lachlan-roberts** [comment]
> If they add them symlink checker it should just allow Sym links and not arbitrary other aliases. The name says it!

Well the name says `SymlinkAllowedResourceAliasChecker` not `SymlinkAliasChecker` and it extends `AllowedResourceAliasChecker`.  And the javadoc says:
> will allow symlinks alias to arbitrary targets, so long as the symlink file itself is an allowed resource

So right now if there is a symlink file which is an "allowed resource" as defined by the `AllowedResourceAliasChecker` then it will be approved.

From what I understand you want the symlink alias checker to approve aliases if they are an alias only because of symlinks and nothing else. But to do this we would need to separate it from the logic of the `AllowedResourceAliasChecker` and find some way of determining why a given resource is an alias. Right now we only know if it is an allowed resource but we don't know exactly why it's an alias, we just know that `path.toRealPath()` resolved to something different than `path`.

**Comment by gregw** [comment]
@lachlan-roberts I don't understand why you want to combine allowed resources with symlink checking? If you want both then add both be alias checkers.

What's wrong with the implementation as we last reviewed it together. Just remove that last conditional return true after checking for symlinks and it is ok.

**Comment by lachlan-roberts** [comment]
@gregw I'm not trying to combine them they already are. This is just how it is currently works. If you want to separate them then we're going to have to make some bigger changes to `SymlinkAllowedResourceAliasChecker`.

> What's wrong with the implementation as we last reviewed it together. Just remove that last conditional return true after checking for symlinks and it is ok.

This is already removed. 

That check was saying if it didn't contain a symlink we could approve it anyway if its an allowed resource. But now we're talking about the case where it does contain a symlink.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/TrailingSlashAliasChecker.java [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+
+package org.eclipse.jetty.server;
+
+import java.util.Objects;
+
+import org.eclipse.jetty.util.component.AbstractLifeCycle;
+import org.eclipse.jetty.util.resource.Resource;
+
+/**
+ * <p>This will approve an alias where the only difference is a trailing slash.</p>
```
Comment (joakime) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/TrailingSlashAliasChecker.java:22]: Can you provide an example in this javadoc?

Something like ... "Real resource on disk is a directory `/path/to/docroot/css/` and the resource requested was `/css` ..."

Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/TrailingSlashAliasChecker.java:22]: I have added an example to this javadoc.

**Comment by lachlan-roberts** [comment]
failing due to unrelated flaky tests

**Comment by lachlan-roberts** [comment]
After re-running tests it is getting to an actual failure.
It is breaking `AliasCheckerMultipleResourceBasesTest`.

It is failing after the changes we made to `SymlinkAllowedResourceAliasChecker`, because the baseResource is the symlink.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/TrailingSlashAliasChecker.java (hunk 5 above)
Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/TrailingSlashAliasChecker.java:22]: I read your new javadoc.

It's not clear what is the requested path (from the HTTP request) vs the `Resource` path (resolved from the Base Resource), and what state the `Resource` path is (is it a file? is it a directory? does it exist?)

Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/TrailingSlashAliasChecker.java:22]: I thought these were quite obvious given the context of it being `index.html`.

But I have tried to clarify these points in the javadoc. 
Let me know if its ok, otherwise maybe you can just rewrite it how you want and post it as a comment here.

**Comment by lachlan-roberts** [comment]
@gregw @joakime this is ready for review

**Review by joakime — DISMISSED** [review]

**Comment by joakime** [comment]
@gregw bump

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java:188]: I really do not like the change in resource that made resolve return null for a non existent resource.  It makes doing logic on resources too difficult.

We should look at reverting that... but in a different PR. @lachlan-roberts can you open an issue for that and then resolve this conversation.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java]: @lachlan-roberts  bump

**Review by gregw — CHANGES_REQUESTED** [review]
Any idea why it is not passing CI?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AllowedResourceAliasChecker.java:188]: I opened https://github.com/jetty/jetty.project/issues/11411

**Comment by lachlan-roberts** [comment]
@gregw the failures were flaky tests

**Review by gregw — APPROVED** [review]
