### PR TITLE
Decode safe Path for #9444

### LINKED ISSUE #9444: Unexpected encoding in request.getPathInfo() with Jetty 12 beta 0
**Jetty version(s)**
12.0.0.beta0

**Java version/vendor**
openjdk version "19.0.1" 2022-10-18

**OS type/version**
mac os

**Description**
When requesting a URL like

http://localhost:8888/view/VAADIN/dynamic/resource/5/4a2dc788-7f04-43e4-8471-70d713d6d001/file%20name

with a servlet mapping of `/view/*` then `request.getPathInfo()` in 

Jetty < 12 returns `"/VAADIN/dynamic/resource/5/4a2dc788-7f04-43e4-8471-70d713d6d001/file name"` while 
Jetty 12 returns `"/VAADIN/dynamic/resource/5/4a2dc788-7f04-43e4-8471-70d713d6d001/file%20name"`

Is this an intentional change in some spec or accidental?

This breaks handling of resources like "file name" in Vaadin when run in 12 beta0 as Vaadin assumes the path info is decoded and then encodes it to match with a stored, encoded value.

### PR DESCRIPTION
**Pull request by gregw**
Added URIUtil.decodeSafePath for EE10, to allow for %2F and %25 to remain encoded in the servlet API.

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java [hunk 1]
```diff
@@ -149,7 +149,7 @@ public String getDescription()
      */
     @SuppressWarnings("DeprecatedIsStillUsed")
     @Deprecated
-    public static final UriCompliance STRICT = new UriCompliance("STRICT", RFC3986.getAllowed());
+    public static final UriCompliance STRICT = new UriCompliance("STRICT", RFC3986_UNAMBIGUOUS.getAllowed());
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: Why are we keeping this if it's deprecated?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 2]
```diff
@@ -459,7 +460,8 @@ public static StringBuilder encodeString(StringBuilder buf,
     }
 
     /**
-     * Decode a URI path and strip parameters
+     * Decode a URI path and strip parameters.
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java]:
```suggestion
     * Decodes a percent-encoded URI path (assuming UTF-8 characters) and strips path parameters.
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 3]
```diff
@@ -469,11 +471,59 @@ public static String decodePath(String path)
     }
 
     /**
-     * Decode a URI path and strip parameters of UTF-8 path
+     * Decode a URI path and strip parameters of UTF-8 path.
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java]:
```suggestion
     * Decodes a percent-encoded URI path (assuming UTF-8 characters) and strips path parameters.
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 4]
```diff
@@ -469,11 +471,59 @@ public static String decodePath(String path)
...
+        return decodePath(path, offset, length, Utf8StringBuilder::append);
+    }
+
+    /**
+     * Decode a URI path and strip parameters of UTF-8 path, but URI leaves reserved path characters encoded.
+     * @param path A String holding the URI path to decode
+     * @see #canonicalPath(String)
+     * @see #normalizePath(String)
+     */
+    public static String decodeSafePath(String path)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java]: Rename to `safeDecodePath()`, as "safe" refers to decode, not path.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 5]
```diff
@@ -469,11 +471,59 @@ public static String decodePath(String path)
...
      * @see #canonicalPath(String)
      * @see #normalizePath(String)
      */
     public static String decodePath(String path, int offset, int length)
+    {
+        return decodePath(path, offset, length, Utf8StringBuilder::append);
+    }
+
+    /**
+     * Decode a URI path and strip parameters of UTF-8 path, but URI leaves reserved path characters encoded.
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java]:
```suggestion
     * Decodes a percent-encoded URI path (assuming UTF-8 characters) and strips path parameters, but leaves reserved path characters percent-encoded.
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 6]
```diff
@@ -469,11 +471,59 @@ public static String decodePath(String path)
...
+     * @see #canonicalPath(String)
+     * @see #normalizePath(String)
+     */
+    public static String decodeSafePath(String path)
+    {
+        return decodeSafePath(path, 0, path.length());
+    }
+
+    /**
+     * Decode a URI path and strip parameters of UTF-8 path, but URI leaves reserved path characters encoded.
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java]:
```suggestion
     * Decodes a percent-encoded URI path (assuming UTF-8 characters) and strips path parameters, but leaves reserved path characters percent-encoded.
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 7]
```diff
@@ -469,11 +471,59 @@ public static String decodePath(String path)
...
+     * @param path A String holding the URI path to decode
+     * @param offset The start of the URI within the path string
+     * @param length The length of the URI within the path string
+     * @see #canonicalPath(String)
+     * @see #normalizePath(String)
+     */
+    public static String decodeSafePath(String path, int offset, int length)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java]: Rename to `safeDecodePath()`.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java [hunk 8]
```diff
@@ -1159,9 +1159,8 @@ protected ServletContextRequest newServletContextRequest(ServletChannel servletC
     @Override
     protected ServletContextRequest wrapRequest(Request request, Response response)
     {
-        // Need to ask directly to the Context for the pathInContext, rather than using
-        // Request.getPathInContext(), as the request is not yet wrapped in this Context.
-        String pathInContext = getContext().getPathInContext(request.getHttpURI().getCanonicalPath());
+        String pathInContext = URIUtil.decodeSafePath(getContext().getPathInContext(request.getHttpURI().getCanonicalPath()));
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java]: I would restore the comment that was there previously.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]
