### PR TITLE
Issue #10942 Fix flakey IdleSessionTest

### LINKED ISSUE #10942: Flaky test `IdleSessionTest.testNullSessionCache`
**Jetty version(s)**
12.0.x

**Jetty Environment**
ee9

**Description**

`org.eclipse.jetty.ee9.session.IdleSessionTest.testNullSessionCache` sometimes fails with:

```
expected: <200> but was: <500>
```

See: https://jenkins.webtide.net/job/jetty.project/job/jetty-12.0.x/1710/testReport/junit/org.eclipse.jetty.ee9.session/IdleSessionTest/Parallel_Stage___Build___Test___JDK21___testNullSessionCache/

### PR DESCRIPTION
**Pull request by janbartel**
closes #10942

### CODE REVIEW

File: jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-common/src/test/java/org/eclipse/jetty/ee9/session/IdleSessionTest.java [hunk 1]
```diff
@@ -246,7 +255,69 @@ public void testNullSessionCache() throws Exception
...
+         * @param request the HTTP request to handle 
+         * @param response the HTTP response to handle
+         * @param callback the callback to complete when the handling is complete
+         * @return
+         * @throws Exception
+         */
+        @Override
+        public boolean handle(org.eclipse.jetty.server.Request request, Response response, Callback callback) throws Exception
+        {
+            request.addHttpStreamWrapper(s -> new RequestListenerWrapper(s, _countDownLatch));
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-tests/jetty-ee9-test-sessions/jetty-ee9-test-sessions-common/src/test/java/org/eclipse/jetty/ee9/session/IdleSessionTest.java:309]: This could be replaced with the following:
```java
org.eclipse.jetty.server.Request.addCompletionListener(request, x ->
{
    if (_countDownLatch != null)
        _countDownLatch.countDown();
});
```

which makes the `RequestListenerWrapper` class not needed anymore.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/test/java/org/eclipse/jetty/ee10/session/IdleSessionTest.java [hunk 2]
```diff
@@ -247,7 +254,69 @@ public void testNullSessionCache() throws Exception
...
+         * @param request the HTTP request to handle
+         * @param response the HTTP response to handle
+         * @param callback the callback to complete when the handling is complete
+         * @return
+         * @throws Exception
+         */
+        @Override
+        public boolean handle(org.eclipse.jetty.server.Request request, Response response, Callback callback) throws Exception
+        {
+            request.addHttpStreamWrapper(s -> new RequestListenerWrapper(s, _countDownLatch));
```
Comment (lorban) [inline jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sessions/jetty-ee10-test-sessions-common/src/test/java/org/eclipse/jetty/ee10/session/IdleSessionTest.java:308]: This could be replaced with the following:
```java
org.eclipse.jetty.server.Request.addCompletionListener(request, x ->
{
    if (_countDownLatch != null)
        _countDownLatch.countDown();
});
```

which makes the `RequestListenerWrapper` class not needed anymore.

**Review by lorban — APPROVED** [review]
