### PR TITLE
Make sure `ContentSourceTransformer.read()` calls `release()` on `fail()` and never call `release()` more than once

### LINKED ISSUE #12855: `ContentSourceTransformer.read()` may call `release()` more than once
**Jetty version(s)**
12.1.x

**Description**
After `ContentSourceTransformer.fail(x, true)` is called, each call to `ContentSourceTransformer.read()` calls `ContentSourceTransformer.release()`.

If the implementation does not implement `release()` in an idempotent way, `ContentSourceTransformer.read()` may throw or misbehave.

**How to reproduce?**

Here is a test to be added to `GzipDecoderSourceTest` that illustrates the bug for `GzipDecoderSource`:

```java
@ParameterizedTest
@MethodSource("textResources")
public void testTransformerBug(String textResourceName) throws Exception
{
    startGzip();
    String compressedName = String.format("%s.%s", textResourceName, gzip.getFileExtensionNames().get(0));
    Path compressed = MavenPaths.findTestResourceFile(compressedName);

    Content.Source fileSource = Content.Source.from(sizedPool, compressed);
    Content.Source decoderSource = gzip.newDecoderSource(fileSource);

    decoderSource.fail(new Throwable(), true);

    Content.Chunk chunk1 = decoderSource.read();
    Content.Chunk chunk2 = decoderSource.read();
    Content.Chunk chunk3 = decoderSource.read(); // this throws NPE
}
```

which fails with:
```
java.lang.NullPointerException: Inflater has been closed

	at java.base/java.util.zip.Inflater.ensureOpen(Inflater.java:714)
	at java.base/java.util.zip.Inflater.reset(Inflater.java:685)
	at org.eclipse.jetty.util@12.1.0-SNAPSHOT/org.eclipse.jetty.util.compression.InflaterPool.reset(InflaterPool.java:56)
	at org.eclipse.jetty.util@12.1.0-SNAPSHOT/org.eclipse.jetty.util.compression.InflaterPool.reset(InflaterPool.java:21)
	at org.eclipse.jetty.util@12.1.0-SNAPSHOT/org.eclipse.jetty.util.compression.CompressionPool$Entry.release(CompressionPool.java:142)
	at org.eclipse.jetty.compression.gzip@12.1.0-SNAPSHOT/org.eclipse.jetty.compression.gzip.internal.GzipDecoderSource.release(GzipDecoderSource.java:277)
	at org.eclipse.jetty.io@12.1.0-SNAPSHOT/org.eclipse.jetty.io.content.ContentSourceTransformer.read(ContentSourceTransformer.java:77)
	at org.eclipse.jetty.compression.gzip@12.1.0-SNAPSHOT/org.eclipse.jetty.compression.gzip.GzipDecoderSourceTest.testTransformerBug(GzipDecoderSourceTest.java:44)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
```

### PR DESCRIPTION
**Pull request by lorban**
Fixes #12855

### CODE REVIEW

File: jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/org/eclipse/jetty/compression/brotli/internal/BrotliDecoderSource.java [hunk 1]
```diff
@@ -28,6 +28,7 @@ public class BrotliDecoderSource extends DecoderSource
 {
     private final DecoderJNI.Wrapper decoder;
     private final BrotliCompression compression;
+    private boolean released;
```
Comment (sbordet) [inline jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/org/eclipse/jetty/compression/brotli/internal/BrotliDecoderSource.java]: This is unnecessary, as `release()` is called from `ContentSourceTransformer.finish()` and it is already protected from multiple invocations there.

Likewise, `isReleased()` could be moved to `ContentSourceTransformer`.

File: jetty-core/jetty-compression/jetty-compression-gzip/src/main/java/org/eclipse/jetty/compression/gzip/internal/GzipDecoderSource.java [hunk 2]
```diff
@@ -43,6 +43,7 @@ private enum State
     private int size;
     private long value;
     private byte flags;
+    private boolean released;
```
Comment (sbordet) [inline jetty-core/jetty-compression/jetty-compression-gzip/src/main/java/org/eclipse/jetty/compression/gzip/internal/GzipDecoderSource.java]: Same comment as brotli.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java [hunk 3]
```diff
@@ -72,10 +72,7 @@ public Content.Chunk read()
                 rawChunk = Content.Chunk.next(rawChunk);
                 needsRawRead = rawChunk == null;
                 if (rawChunk != null)
-                {
-                    finished = true;
-                    release();
-                }
+                    finish();
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: Uhm, so `finished` is only used to early return EOF.

Here we handle `rawChunk` failures, so I think it was wrong before that `finished` was set; we should just call `release()` and make sure it is called only once in case of multiple reads.

Perhaps rename `finished` to `eof`, `finish()` to `terminate()` and use a boolean `terminated` to guarantee only one call to `release()`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java [hunk 4]
```diff
@@ -129,10 +126,7 @@ public Content.Chunk read()
                 transformedChunk = Content.Chunk.next(result);
 
                 if (terminated || terminalFailure)
-                {
-                    finished = true;
-                    release();
-                }
+                    finish();
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: Here also, if `terminated==true`, set `eof=true`, but if `terminalFailure==true` we only need to call `terminate()` (see previous comment about renaming).

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java [hunk 5]
```diff
@@ -158,7 +152,25 @@ public void fail(Throwable failure)
...
+
         rawSource.fail(failure);
+        needsRawRead = false;
+        if (rawChunk != null)
+            rawChunk.release();
+        rawChunk = Content.Chunk.from(failure, true);
+        if (transformedChunk != null)
+            transformedChunk.release();
+        transformedChunk = rawChunk;
+        finish();
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: This needs to be re-evaluated.
As failures are asynchronous, we want to do as little as possible here to avoid having to use a lock.
Possibly just delegating to the `rawSource`.

The reason is that there may be non-failed transformed content to read, and possibly the failure has been serialized in the `rawSource` so reading would be possible, and only eventually the failure is detected (for example a queued `rawSource`).

The idea was to do as little as possible, as the failure would be handled by the `rawSource`, and will be eventually seen via `read()`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: Remember that after a call to `fail()`, all resources should have been released, even if you may decide to stop reading entirely.

File: jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/org/eclipse/jetty/compression/brotli/internal/BrotliDecoderSource.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/org/eclipse/jetty/compression/brotli/internal/BrotliDecoderSource.java]: I added `isReleased()` only to test that the `DecoderSource` implementation received the `release()` call. It's not meant to be a useful API.

File: jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/org/eclipse/jetty/compression/brotli/internal/BrotliDecoderSource.java [hunk 6]
```diff
@@ -93,9 +94,19 @@ protected Content.Chunk transform(Content.Chunk inputChunk)
         }
     }
 
+    // Only used for testing.
+    public boolean isReleased()
```
Comment (gregw) [inline jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/org/eclipse/jetty/compression/brotli/internal/BrotliDecoderSource.java]:
```suggestion
    boolean isReleased()
```

File: jetty-core/jetty-compression/jetty-compression-gzip/src/main/java/org/eclipse/jetty/compression/gzip/internal/GzipDecoderSource.java [hunk 7]
```diff
@@ -271,9 +272,19 @@ else if (inflater.finished())
         }
     }
 
+    // Only used for testing.
+    public boolean isReleased()
```
Comment (gregw) [inline jetty-core/jetty-compression/jetty-compression-gzip/src/main/java/org/eclipse/jetty/compression/gzip/internal/GzipDecoderSource.java]:
```suggestion
    boolean isReleased()
```

File: jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/internal/ZstandardDecoderSource.java [hunk 8]
```diff
@@ -52,4 +53,15 @@ protected Content.Chunk transform(Content.Chunk inputChunk)
...
         return Content.Chunk.asChunk(dst.getByteBuffer(), last, dst);
     }
+
+    @Override
+    protected void release()
+    {
+        released = true;
+    }
+
+    public boolean isReleased()
```
Comment (gregw) [inline jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/internal/ZstandardDecoderSource.java]:
```suggestion
    boolean isReleased()
```

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-compression/jetty-compression-brotli/src/test/java/org/eclipse/jetty/compression/brotli/BrotliDecoderSourceTest.java [hunk 9]
```diff
@@ -35,10 +39,70 @@ public void testDecodeText(String textResourceName) throws Exception
...
+
+        Content.Chunk chunk = decoderSource.read();
+        // skip empty chunks
+        while (chunk.isEmpty() && !chunk.isLast())
+            chunk = decoderSource.read();
+        assertTrue(chunk.hasRemaining());
+        chunk.release();
+        // This test tests the behavior of
+        // a failure before the last chunk.
+        assumeFalse(chunk.isLast());
```
Comment (lorban) [inline jetty-core/jetty-compression/jetty-compression-brotli/src/test/java/org/eclipse/jetty/compression/brotli/BrotliDecoderSourceTest.java:99]: You mean `assertFalse`, right?

File: jetty-core/jetty-compression/jetty-compression-gzip/src/test/java/org/eclipse/jetty/compression/gzip/GzipDecoderSourceTest.java [hunk 10]
```diff
@@ -35,10 +39,67 @@ public void testDecodeText(String textResourceName) throws Exception
...
+        Content.Source fileSource = Content.Source.from(sizedPool, compressed);
+        DecoderSource decoderSource = gzip.newDecoderSource(fileSource);
+        assertFalse(decoderSource.isComplete());
+
+        Content.Chunk chunk = decoderSource.read();
+        assertTrue(chunk.hasRemaining());
+        chunk.release();
+        // This test tests the behavior of
+        // a failure before the last chunk.
+        assumeFalse(chunk.isLast());
```
Comment (lorban) [inline jetty-core/jetty-compression/jetty-compression-gzip/src/test/java/org/eclipse/jetty/compression/gzip/GzipDecoderSourceTest.java:96]: Yo mean `assertFalse`?

File: jetty-core/jetty-compression/jetty-compression-zstandard/src/test/java/org/eclipse/jetty/compression/zstandard/ZstandardDecoderSourceTest.java [hunk 11]
```diff
@@ -34,12 +39,71 @@ public void testDecodeText(String textResourceName) throws Exception
...
+
+        Content.Chunk chunk = decoderSource.read();
+        // skip empty chunks
+        while (chunk.isEmpty() && !chunk.isLast())
+            chunk = decoderSource.read();
+        assertTrue(chunk.hasRemaining());
+        chunk.release();
+        // This test tests the behavior of
+        // a failure before the last chunk.
+        assumeFalse(chunk.isLast());
```
Comment (lorban) [inline jetty-core/jetty-compression/jetty-compression-zstandard/src/test/java/org/eclipse/jetty/compression/zstandard/ZstandardDecoderSourceTest.java:100]: You mean `assertFalse`?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java [hunk 12]
```diff
@@ -122,25 +145,68 @@ public Content.Chunk read()
...
+        {
+            State current = state.get();
+            switch (current.type)
+            {
+                case IDLE, EOF, FAILED -> throw new IllegalStateException();
+                case READING ->
+                {
+                    switch (type)
+                    {
+                        case IDLE ->
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java:172]: It's confusing when reading to have `State` constants named like `State.Type` values. Maybe use a prefix for the `State` constants to help discriminate them at sight?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java [hunk 13]
```diff
@@ -31,11 +34,10 @@ public abstract class ContentSourceTransformer implements Content.Source
 {
     private static final Logger LOG = LoggerFactory.getLogger(ContentSourceTransformer.class);
 
+    private final AtomicReference<State> state = new AtomicReference<>(State.IDLE);
     private final Content.Source rawSource;
     private Content.Chunk rawChunk;
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: `rawChunk` also needs to be volatile as there isn't always a good visibility-enforcing action. `fail()` for instance modifies this variable without enforcing its visibility.

File: jetty-core/jetty-compression/jetty-compression-brotli/src/test/java/org/eclipse/jetty/compression/brotli/BrotliDecoderSourceTest.java (hunk 9 above)
Comment (sbordet) [reply jetty-core/jetty-compression/jetty-compression-brotli/src/test/java/org/eclipse/jetty/compression/brotli/BrotliDecoderSourceTest.java:99]: No, I really mean assume.
It is really complicated to avoid to read the smaller file in just one chunk.
If we do, there is no point trying the rest of the test, so `assume` rather than `assert`.

**Review by sbordet — APPROVED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java [hunk 14]
```diff
@@ -63,31 +95,22 @@ public Content.Chunk read()
...
                 rawChunk = Content.Chunk.next(rawChunk);
                 needsRawRead = rawChunk == null;
                 if (rawChunk != null)
-                {
-                    finished = true;
-                    release();
-                }
-                return failure;
+                    return afterRead(State.Type.FAILED, failureChunk);
+                return afterRead(State.Type.IDLE, failureChunk);
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: I'm not sure this is correct.   You should return the chunk just read, but the failure chunk set to be returned from future reads should be the result of `Content.Chunk.next(rawChunk)`.    If the next chunk is null, then we should return to idle state.

If you had a transitive error, then you would return it forever

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java [hunk 15]
```diff
@@ -122,25 +145,68 @@ public Content.Chunk read()
...
+                    }
+                }
+                case FAILING ->
+                {
+                    Content.Chunk failedChunk = ((State.Failing)current).chunk;
+                    if (state.compareAndSet(current, new State.Failed(failedChunk)))
+                    {
+                        dispose(failedChunk.getFailure());
+                        return chunk;
+                    }
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: I also don't think this is correct.   Once we have a persistent failure, then any future failures should just be added as suppressed exceptions to the original.

**Review by gregw — CHANGES_REQUESTED** [review]
I don't think transitive or multiple failures are handled correctly

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java (hunk 14 above)
Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: What you describe is exactly what the code does. The code always returns the chunk just read (`failureChunk`), calls `Chunk.next()` to update `this.rawChunk`, and the logic that follows operates on the "next" chunk.
For transient errors, the code sets `this.rawChunk` to `null`, moves to `IDLE` and returns the transient `failureChunk`. The next read would see `this.rawChunk=null`, `needsRawRead=true` and `IDLE` state.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java (hunk 15 above)
Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: I don't follow? This code handles a concurrent call to `fail()` during a call to `read()`. There is only 1 failure, so it cannot be added as suppressed, as it is the first failure.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java (hunk 14 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: @sbordet On line 107, it sets the afterRead state with `failureChunk` not with the updated `rawChunk`.   The on line 108, it is going to idle with the `failureChunk` instead of null.

 I think it would be clearer if you introduced a `nextChunk` variable.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java (hunk 15 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceTransformer.java]: We are already in FAILING state, so somebody has called `fail` with the first failure.  This may or maynot be the same failure associated with the chunk passed in.  In fact, couldn't the chunk passed in be a normal data chunk that has raced with the fail call?

**Review by gregw — APPROVED** [review]
