### PR TITLE
Fixes #3983 - JarFileResource directory listing is invalid

### LINKED ISSUE #3983: JarFileResource incorrectly lists the contents of directories with spaces
In [Issue 1539](https://github.com/eclipse/jetty.project/issues/1539), I noted JarFileResource failed to serve any resource with a space in its name that is located in a jar file. While my patch fixed that problem, it did not fix a related problem: a directory with a space in its name that is located in a jar file will not list any entries when queried for directory listing.

I have attached a zip file with two files:

1. test.jar, which contains a directory named "dir1" with a file "file1" and a directory named "dir 2" with a file "file2" (note the space in the second directory name).
2. JarDirWithSpaceTest.java, which shows that JarFileResource.list() returns the wrong number of files in "dir 2".

The Java file was compiled and run with a classpath including jetty-util-9.4.11.v20180605.jar.

The problem lies in JarFileResource.listEntries() in the line

String dir=_urlString.substring(_urlString.lastIndexOf("!/")+2);

Here, as in issue 1539, the substring value must be decoded before use. The fix is to change the line to 

String dir=URIUtil.decodePath(_urlString.substring(_urlString.lastIndexOf("!/")+2));

### PR DESCRIPTION
**Pull request by joakime**
+ Correcting encoded path searching
+ Adding more unit tests to ensure no regression

### CODE REVIEW

File: jetty-util/src/main/java/org/eclipse/jetty/util/resource/JarFileResource.java [hunk 1]
```diff
@@ -316,11 +317,12 @@ public long lastModified()
         }
 
         Enumeration<JarEntry> e = jarFile.entries();
-        String dir = _urlString.substring(_urlString.lastIndexOf("!/") + 2);
+        String encodedDir = _urlString.substring(_urlString.lastIndexOf("!/") + 2);
+        String dir = URIUtil.decodePath(encodedDir);
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/resource/JarFileResource.java]: Method `newConnection()` has a similar logic (searching for `!/`) and has been changed from using `_urlString` to use `_url.getPath()`. Why here we are not doing the same?

Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/resource/JarFileResource.java]: Reverted change in `newConnection`, but with comment indicating assumption.
