### PR TITLE
Fixes #13098 - HTTP2 Server Error Handling is different than HTTP1

### LINKED ISSUE #13098: HTTP2 Server Error Handling is different than HTTP1
**Jetty version(s)**
12.0.19

**Jetty Environment**
All

**Description**
When an error occurs on HTTP/1.1 during the parsing of a request, the error will be processed through the server/core level `ErrorHandler`

Example request:

```
GET /dump/%7= HTTP/1.1
Host: localhost
Connection: close

```

This will fail in the HTTP/1.1 parser (in the `HttpURI` parsing)

```
Caused by: java.lang.NumberFormatException: !hex =
	at org.eclipse.jetty.util.TypeUtil.convertHexDigit(TypeUtil.java:452)
	at org.eclipse.jetty.http.HttpURI$Mutable.parse(HttpURI.java:1455)
	at org.eclipse.jetty.http.HttpURI$Mutable.path(HttpURI.java:1005)
```

The error handling for this will reach the server / core-level `ErrorHandler` to produce a response from.

But if the same request is sent via HTTP/2, then the connection is closed without producing a response, and without calling the server / core level `ErrorHandler`.

```
   at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onClose(HTTP2ServerConnectionFactory.java:123)
   at org.eclipse.jetty.http2.HTTP2Session.notifyClose(HTTP2Session.java:1218)
   at org.eclipse.jetty.http2.HTTP2Session$StreamsState.terminate(HTTP2Session.java:2145)
   at org.eclipse.jetty.http2.HTTP2Session$StreamsState.onSessionFailure(HTTP2Session.java:2027)
   at org.eclipse.jetty.http2.HTTP2Session.onSessionFailure(HTTP2Session.java:601)
   at org.eclipse.jetty.http2.HTTP2Session.onConnectionFailure(HTTP2Session.java:596)
   at org.eclipse.jetty.http2.HTTP2Connection.onConnectionFailure(HTTP2Connection.java:300)
   at org.eclipse.jetty.http2.parser.BodyParser.notifyConnectionFailure(BodyParser.java:218)
   at org.eclipse.jetty.http2.parser.BodyParser.connectionFailure(BodyParser.java:210)
   at org.eclipse.jetty.http2.parser.Parser.connectionFailure(Parser.java:241)
```

Is it possible to send an error response in these kinds of HTTP2 errors cases? or is a harsh close the only option?

If you manage to send the path `/dump/%7=` in an HTTP/2 client, the fundamental Parser.parse error is due to a `NumberFormatException`.

```
java.lang.NumberFormatException: !hex =
  at org.eclipse.jetty.util.TypeUtil.convertHexDigit(TypeUtil.java:452)
  at org.eclipse.jetty.http.HttpURI$Mutable.parse(HttpURI.java:1455)
  at org.eclipse.jetty.http.HttpURI$Mutable.pathQuery(HttpURI.java:1031)
  at org.eclipse.jetty.http.MetaData$Request.(MetaData.java:158)
  at org.eclipse.jetty.http2.hpack.internal.MetaDataBuilder.build(MetaDataBuilder.java:269)
  at org.eclipse.jetty.http2.hpack.HpackDecoder.decode(HpackDecoder.java:305)
  at org.eclipse.jetty.http2.parser.HeaderBlockParser.parse(HeaderBlockParser.java:103)
  at org.eclipse.jetty.http2.parser.HeadersBodyParser.parse(HeadersBodyParser.java:197)
  at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:230)
  at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:157)
  at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:121)
```

### PR DESCRIPTION
**Pull request by sbordet**
Errors happening before the request is handled are now handled similarly to HTTP/1.1, and are now hitting the `ErrorHandler`, so that a 400 response can be generated.

### CODE REVIEW

**Comment by gregw** [comment]
@lorban will h3 need similar changes?

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/parser/HeaderBlockParser.java [hunk 1]
```diff
@@ -135,4 +139,68 @@ public MetaData parse(ByteBuffer buffer, int blockLength)
             }
         }
     }
+
+    public static class SessionFailureMetaData extends MetaData
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/parser/HeaderBlockParser.java]: javadoc

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/parser/HeaderBlockParser.java [hunk 2]
```diff
@@ -135,4 +139,68 @@ public MetaData parse(ByteBuffer buffer, int blockLength)
...
+    {
+        private SessionFailureMetaData()
+        {
+            super(HttpVersion.HTTP_2, HttpFields.EMPTY);
+        }
+    }
+
+    public interface StreamFailureMetaData
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/parser/HeaderBlockParser.java]: javadoc

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/parser/HeaderBlockParser.java [hunk 3]
```diff
@@ -135,4 +139,68 @@ public MetaData parse(ByteBuffer buffer, int blockLength)
...
+    {
+        Throwable getFailure();
+    }
+
+    public static class StreamFailureMetaDataRequest extends MetaData.Request implements StreamFailureMetaData
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/parser/HeaderBlockParser.java]: javadoc

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/parser/HeaderBlockParser.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/parser/HeaderBlockParser.java]: Why is both a session and stream failure needed?   Can't a session failure be detected by the fact that it has a failed stream?

Or perhaps it could just be a FailureMetaData with reason in the getFailure?

**Review by gregw — CHANGES_REQUESTED** [review]
CI is badly broken as well.

**Comment by lorban** [comment]
@gregw yes, H3 probably suffers from the same problem.

**Comment by sbordet** [comment]
@gregw @lorban I have implemented also for HTTP/3.

File: jetty-core/jetty-http3/jetty-http3-qpack/src/main/java/org/eclipse/jetty/http3/qpack/QpackException.java [hunk 4]
```diff
@@ -41,14 +47,28 @@ public long getErrorCode()
      */
     public static class StreamException extends QpackException
     {
-        public StreamException(long errorCode, String messageFormat)
+        private final Boolean type;
+
+        public StreamException(boolean request, boolean response, long errorCode, String message)
+        {
+            super(errorCode, message);
+            this.type = request ? Boolean.TRUE : response ? Boolean.FALSE : null;
```
Comment (lorban) [inline jetty-core/jetty-http3/jetty-http3-qpack/src/main/java/org/eclipse/jetty/http3/qpack/QpackException.java]: Shouldn't you store the two booleans instead of using this conversion? Passing true to both `request` and `response` would store `Boolean.TRUE` which would make `isResponse()` return false.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java [hunk 5]
```diff
@@ -303,13 +307,12 @@ private Immutable(Mutable builder)
...
         {
             _uri = null;
-
             _scheme = URIUtil.normalizeScheme(scheme);
             _user = null;
             _host = host;
             _port = (port > 0) ? port : URIUtil.UNDEFINED_PORT;
             _path = path;
-            _canonicalPath = _path == null ? null : URIUtil.canonicalPath(_path);
+            _canonicalPath = path;
```
Comment (lorban) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java]: Why making canonical path identical to path?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java]: Because `URIUtil.canonicalPath()` would throw exceptions for invalid paths, but for this class we don't want to perform (much) validation checks.

File: jetty-core/jetty-http3/jetty-http3-qpack/src/main/java/org/eclipse/jetty/http3/qpack/QpackException.java (hunk 4 above)
Comment (sbordet) [reply jetty-core/jetty-http3/jetty-http3-qpack/src/main/java/org/eclipse/jetty/http3/qpack/QpackException.java]: True, but if both are `true` it's really more a bad request (that also contains response-only pseudo-headers), so it's fine.
Although 2 booleans would be 8 bytes, while a reference is 12-16 (header) + 4 (boolean), so it's less memory with 2 booleans.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java]: Then maybe we also don't want to normalize the scheme nor disallow port 0?

Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java]: This class (HttpURI) does lots of path validations, see the parse() methods.

Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java]: Ah, this is a Unsafe mode.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java [hunk 6]
```diff
@@ -506,6 +507,27 @@ public String toString()
         }
     }
 
+    /**
+     * <p>An unsafe {@link HttpURI} that accepts URI parts without checking whether they are valid.</p>
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java:511]:
```suggestion
     * <p>An unsafe {@link HttpURI} that accepts URI parts without checking whether they are valid.
     * Primarily intended for testing, as un-validated may break arbitrary code.</p>
```

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java [hunk 7]
```diff
@@ -331,4 +331,121 @@ public String toString()
             return String.format("%s{s=%d,h=%d,cl=%d}", getHttpVersion(), getStatus(), headers.size(), getContentLength());
         }
     }
+
+    /**
+     * <p>Marker interface to signal that a {@link MetaData} could not be created,
+     * for example due to an invalid URI or invalid headers.</p>
+     */
+    public interface Failed
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java:339]: I know it is not needed, but the methods are MetaData only, so the interface should extend
```suggestion
    public interface Failed extends MetaData
```

File: jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/internal/MetaDataBuilder.java [hunk 8]
```diff
@@ -297,4 +303,20 @@ public MetaData build() throws HpackException.StreamException
...
+
+    private HttpURI newHttpURI() throws HpackException.StreamException
+    {
+        try
+        {
+            return HttpURI.build()
+                .scheme(_scheme)
+                .host(_authority == null ? null : _authority.getHost())
+                .port(_authority == null ? -1 : _authority.getPort())
+                .pathQuery(_path);
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/internal/MetaDataBuilder.java:315]: Do we need?
```suggestion
                .pathQuery(_path)
                .asImmutable();
```

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java [hunk 9]
```diff
@@ -331,4 +331,121 @@ public String toString()
...
+    }
+
+    private static class FailedMetaDataRequest extends MetaData.Request implements Failed
+    {
+        private final Throwable failure;
+
+        private FailedMetaDataRequest(HttpVersion httpVersion, Throwable failure)
+        {
+            super("GET", HttpURI.build(), httpVersion, HttpFields.EMPTY);
+            this.failure = failure;
```
Comment (lorban) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java]: Can failure be null? If not, there should be a null check.

File: jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackException.java [hunk 10]
```diff
@@ -29,9 +34,31 @@ public abstract class HpackException extends Exception
      */
     public static class StreamException extends HpackException
     {
-        public StreamException(String messageFormat, Object... args)
+        private final boolean request;
+        private final boolean response;
+
+        public StreamException(boolean request, boolean response, String messageFormat, Object... args)
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackException.java:40]: Why are these exceptions taking format + args instead of a pre-formatted string?

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 11]
```diff
@@ -701,4 +676,31 @@ public EndPoint getEndPoint()
...
+
+    private static class FailureTask implements Runnable
+    {
+        private final Runnable task;
+        private final Callback callback;
+
+        private FailureTask(Runnable task, Callback callback)
+        {
+            this.task = task;
+            this.callback = callback;
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: Add a null check on the callback?

File: jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/internal/HttpSenderOverHTTP3.java [hunk 12]
```diff
@@ -72,12 +72,8 @@ protected void sendHeaders(HttpExchange exchange, ByteBuffer contentBuffer, bool
...
         {
             String path = relativize(request.getPath());
-            HttpURI uri = HttpURI.build()
-                .scheme(request.getScheme())
-                .host(request.getHost())
-                .port(request.getPort())
-                .path(path)
-                .query(request.getQuery());
+            // URI validations already performed by using the java.net.URI class.
+            HttpURI uri = new HttpURI.Unsafe(request.getScheme(), request.getHost(), request.getPort(), path, request.getQuery(), null);
```
Comment (lorban) [inline jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/internal/HttpSenderOverHTTP3.java]: A side-effect of this change makes the `HttpURI` immutable.

I wonder if the `MetaData.Request` constructors shouldn't always call `immutable()` on the `HttpURI` parameter they are given?

File: jetty-core/jetty-http3/jetty-http3-qpack/src/main/java/org/eclipse/jetty/http3/qpack/internal/metadata/MetaDataBuilder.java [hunk 13]
```diff
@@ -294,4 +293,20 @@ public MetaData build() throws QpackException.StreamException
...
+
+    private HttpURI newHttpURI() throws QpackException.StreamException
+    {
+        try
+        {
+            return HttpURI.build()
+                .scheme(_scheme)
+                .host(_authority == null ? null : _authority.getHost())
+                .port(_authority == null ? -1 : _authority.getPort())
+                .pathQuery(_path);
```
Comment (lorban) [inline jetty-core/jetty-http3/jetty-http3-qpack/src/main/java/org/eclipse/jetty/http3/qpack/internal/metadata/MetaDataBuilder.java:305]: `immutable()`?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java (hunk 6 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java:511]: It's also used by Jetty HttpClient to allow it to make requests that other servers would allow, but we don't.

An example would be using the `%00` in the request path.
In jetty-12.0.x HEAD our HttpURI and MetaData classes both reject that pct-encoding, but it's 100% allowed to be sent from a user-agent.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java (hunk 7 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java:339]: @gregw `MetaData` is a class, so I cannot do the above.

File: jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/internal/MetaDataBuilder.java (hunk 8 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/internal/MetaDataBuilder.java:315]: It creates another object in the hot path, and the return type is already just `HttpURI`, not its `Mutable` subclass.

File: jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/internal/HttpSenderOverHTTP3.java (hunk 12 above)
Comment (sbordet) [reply jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/internal/HttpSenderOverHTTP3.java]: It would be another allocation in the hot path, and the signature returns the immutable `HttpURI` type.

**Review by lorban — APPROVED** [review]
There is still the oddity of `StreamException` and `HpackException` taking format + args, otherwise LGTM.

**Comment by joakime** [comment]
Can this be merged ?
