### PR TITLE
Serialize onCompleteFailure for #9059

### LINKED ISSUE #9059: IteratingCallback not serializing close() and failed()
**Jetty version(s)**
10+

**Description**
Thread1 is inside `IC.process()`, acting on some custom state.

Thread2 calls `IC.close()` or `IC.failed(failure)`, and this may call `onCompleteFailure()` directly, which may (for example) reset the custom state, or null it out, etc.

Therefore, the contract of IC that it will serialize the processing is not respected, because now 2 threads can access the IC custom state.

We should be more precise at serializing in case of a `close()` call, and possibly introduce a `close(Throwable)` or `fail(Throwable)` different from `failed(Throwable)` if necessary to handle the serialization more precisely.

### PR DESCRIPTION
**Pull request by gregw**
Delay `onCompleteFailure` call until process has returned.

### CODE REVIEW

File: jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java [hunk 1]
```diff
@@ -19,103 +19,111 @@
...
+         * sub-task, where the execution has started but the callback
+         * that signals the completion of the asynchronous sub-task
          * may have not yet been invoked.
          */
         SCHEDULED,
-
         /**
-         * Indicates that {@link #process()} has completed the overall job.
+         * Indicates that {@link #process()} has completed the whole
+         * iteration successfully.
```
Comment (joakime) [inline jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java:126]: +1 for the clearer javadoc on `Action`

**Review by sbordet — APPROVED** [review]
