### PR TITLE
Issue #6118 Warn if hazelcast cfg file is missing SessionDataSerializer

### LINKED ISSUE #6118: Display a warning when Hazelcast configuration does not contain Jetty session serializer
It's possible to configure Hazelcast Session Manager with a single `hazelcast.xml` file but the Jetty session manager needs to have the serializer configured as is:
```
  <serialization>
    <serializers>
      <serializer type-class="org.eclipse.jetty.server.session.SessionData"
                  class-name="org.eclipse.jetty.hazelcast.session.SessionDataSerializer" />
    </serializers>
  </serialization> 
```
If it's not configured we should display a warning in the logs telling the user the Hazelcast Jetty session integration will not work

### PR DESCRIPTION
**Pull request by janbartel**
Fixes #6118 

Output a log warning if the user has supplied an optional hazelcast xml config file to configure hazelcast, and it is missing the serializer for the SessionData class.

### CODE REVIEW

File: jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStoreFactory.java [hunk 1]
```diff
@@ -91,20 +96,22 @@ public SessionDataStore getSessionDataStore(SessionHandler handler)
...
                         config.getSerializationConfig().addSerializerConfig(sc);
-                        hazelcastInstance = HazelcastClient.newHazelcastClient(config);
                     }
                     else
                     {
-                        hazelcastInstance = HazelcastClient.newHazelcastClient(
-                            new XmlClientConfigBuilder(configurationLocation).build());
+                        config = new XmlClientConfigBuilder(configurationLocation).build();
+                        if (config.getSerializationConfig().getSerializerConfigs().stream().noneMatch(s ->
+                        SessionData.class.getName().equals(s.getTypeClassName()) && s.getImplementation() instanceof SessionDataSerializer))
```
Comment (olamy) [inline jetty-hazelcast/src/main/java/org/eclipse/jetty/hazelcast/session/HazelcastSessionDataStoreFactory.java]: if you fix this checkstyle issue it should be fine :P

**Review by olamy — CHANGES_REQUESTED** [review]

**Review by olamy — APPROVED** [review]
