### PR TITLE
Issue #11410 - PathMappingsHandler does not set Server on added handlers

### LINKED ISSUE #11410: PathMappingsHandler does not start ResourceHandler properly
**Jetty version(s)**
12.0.6

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

**OS type/version**
Windows 11

**Description**
I'm suspecting I've found a bug with ResourceHandler after upgrading to jetty 12. I can't get any files served unless I nest the ResourceHandler in a ContextHandler, the latter having set the needed base resource. And even then there's behavior I don't understand where some configs will yield only 404s. Ideally, ResourceHandler should work out of the box withouit being nested in a ContextHandler, and behaving in a predictable way.
I've made this simplest example of the issue, [based on the example in the programming guide](https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-server-http-handler-use-resource), and it can only serve 404s. I've verified that the Path and underlying Resource are valid.

Here's the error when requesting something from the ResourceHandler:
Screenshot 2024-02-15 124435

Here's the verification that this is not a problem with an invalid Path or null Resource:
Screenshot 2024-02-15 124258

**How to reproduce?**

``` java
public class Main implements Runnable {

    public final int PORT = 8443;
    private Server jettyServer;

    public static void main(String[] args) {
        new Main().run();
    }

    @Override
    public void run() {
        jettyServer = new Server();

        ServerConnector connector = new ServerConnector(jettyServer);
        connector.setPort(PORT);

        jettyServer.addConnector(connector);

        PathMappingsHandler mapHandler = new PathMappingsHandler();
        jettyServer.setHandler(mapHandler);

        ResourceHandler resourceHandler = new ResourceHandler();
        Path baseDir = Path.of("resources/public/");
        Resource baseResource = ResourceFactory.of(resourceHandler).newResource(baseDir);
        if (!Resources.isReadableDirectory(baseResource)) {
            throw new RuntimeException("Resource is not a readable directory");
        }
        resourceHandler.setBaseResource(baseResource);
        resourceHandler.setDirAllowed(true);
        resourceHandler.setUseFileMapping(true);
        resourceHandler.setServer(jettyServer);
        mapHandler.addMapping(PathSpec.from("/files/*"), resourceHandler);

        jettyServer.setDumpAfterStart(true);

        try {
            jettyServer.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

### PR DESCRIPTION
**Pull request by joakime**
When `PathMappingsHandler` starts, the added `Handler` instances do not get their `Handler.setServer(Server)` method called.

With most Handler's this isn't a big deal, but with `ResourceHandler` this results in a badly started `ResourceHandler`.

This PR fixes this specific issue with `PathMappingsHandler`

Issue: #11410

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java [hunk 1]
```diff
@@ -79,6 +80,15 @@ public void dump(Appendable out, String indent) throws IOException
...
 
+    @Override
+    protected void doStart() throws Exception
+    {
+        Server server = getServer();
+        for (MappedResource<Handler> mapping: mappings)
+            mapping.getResource().setServer(server);
+        super.doStart();
+    }
+
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java]: Uhm, this is not where other containers do it.
They typically override `setServer()` and also do it in their own specific methods to add children such as `Handler.Sequence.setHandlers()`, etc.
I would do the same, not overriding `doStart()` which may happen too late.

I'd check also if `Singleton.updateHandler()` would do the job.
Currently, `PathMappingsHandler.addMapping()` calls only `addBean()`, but if it calls `Singleton.updateHandler()` it will probably be best?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java]: `Singleton.updateHandler()` is not appropriate, as that's for a container that has only 1 handler.

Note that the `Handler.setServer(Seerver)` call occurs during `.setHandler(Handler)` calls in normal Handlers, such as the `Server.setHandler(handlers)` call.
So that means if you add the `PathMappingHandler` to the `Server.setHandlers(handler)` tree, THEN add handlers to the `PathMappingsHandler` you wind up with no further `Handler.setServer()` calls.

Anyway, I'll move this out from `doStart()` and to `addMapping()` instead, where this is more appropriate, and fits in line with the best practices of other Handlers.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java [hunk 2]
```diff
@@ -67,6 +72,19 @@ public void addMapping(PathSpec pathSpec, Handler handler)
...
+        invocationType = Invocable.combine(invocationType, handler.getInvocationType());
+        if (server != null)
+            handler.setServer(server);
+
+        // If the collection can be changed dynamically, then the risk is that if we switch from NON_BLOCKING to BLOCKING
+        // whilst the execution strategy may have already dispatched the very last available thread, thinking it would
+        // never block, only for it to lose the race and find a newly added BLOCKING handler.
+        if (isDynamic() && server != null && server.isStarted() && serverInvocationType != invocationType && serverInvocationType != InvocationType.BLOCKING)
+            throw new IllegalArgumentException("Cannot change invocation type of started server");
+
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java]: Very minor, but this reads better:
```suggestion
        Server server = getServer();
         if (server != null)
        {
            handler.setServer(server);
        
            // If the collection can be changed dynamically, then the risk is that if we switch from NON_BLOCKING to BLOCKING
            // whilst the execution strategy may have already dispatched the very last available thread, thinking it would
            // never block, only for it to lose the race and find a newly added BLOCKING handler.
            InvocationType serverInvocationType = server.getInvocationType();
            InvocationType invocationType = Invocable.combine(InvocationType.NON_BLOCKING, handler.getInvocationType());
            
            if (isDynamic() && server.isStarted() && serverInvocationType != invocationType && serverInvocationType != InvocationType.BLOCKING)
                    throw new IllegalArgumentException("Cannot change invocation type of started server");
        }
```

**Review by gregw — CHANGES_REQUESTED** [review]
Just a minor reordering of the code please.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java (hunk 2 above)
Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java]: I took this from Handler.Sequence.setHandler(), but pruned it.
Shame I cannot clean up that original place this way too.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java [hunk 3]
```diff
@@ -67,6 +72,21 @@ public void addMapping(PathSpec pathSpec, Handler handler)
...
+            InvocationType invocationType = InvocationType.NON_BLOCKING;
+            invocationType = Invocable.combine(invocationType, handler.getInvocationType());
+            handler.setServer(server);
+
+            // If the collection can be changed dynamically, then the risk is that if we switch from NON_BLOCKING to BLOCKING
+            // whilst the execution strategy may have already dispatched the very last available thread, thinking it would
+            // never block, only for it to lose the race and find a newly added BLOCKING handler.
+            if (isDynamic() && server.isStarted() && serverInvocationType != invocationType && serverInvocationType != InvocationType.BLOCKING)
+                throw new IllegalArgumentException("Cannot change invocation type of started server");
+        }
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/PathMappingsHandler.java]: I'm being very pedantic here.... the the getters for invocationType should be after the comments about dynamic invocationType:

```suggestion
        Server server = getServer();
        if (server != null)
        {
            handler.setServer(server);

            // If the collection can be changed dynamically, then the risk is that if we switch from NON_BLOCKING to BLOCKING
            // whilst the execution strategy may have already dispatched the very last available thread, thinking it would
            // never block, only for it to lose the race and find a newly added BLOCKING handler.
            InvocationType serverInvocationType = server.getInvocationType();
            InvocationType invocationType = InvocationType.NON_BLOCKING;
            invocationType = Invocable.combine(invocationType, handler.getInvocationType());
            if (isDynamic() && server.isStarted() && serverInvocationType != invocationType && serverInvocationType != InvocationType.BLOCKING)
                throw new IllegalArgumentException("Cannot change invocation type of started server");
        }
```

**Review by gregw — CHANGES_REQUESTED** [review]

**Review by gregw — DISMISSED** [review]

**Review by sbordet — DISMISSED** [review]
