### PR TITLE
Issue #14137 - `ETag` response header not properly set on "304 Not Modified" from `CompressionHandler`.

### LINKED ISSUE #14137: 304 Not Modified produces incorrect ETag from CompressionHandler.
**Jetty version(s)**
12.1.4

**Jetty Environment**
Any

**HTTP version**
Any

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
When using the `CompressionHandler` and it is answering a request with a `If-None-Match` (that has an Etag) with a 304 Not Modified, the resulting `Etag` is different than the one supplied.

It should be the identical one.

Namely, the `--<compression>` suffix (eg: `--gzip`) has been removed, when it shouldn't have been.

If the compression COULD happen (if it were to produce a 200 response), then the 304 Not Modified should return the ETag that WOULD have been produced (which SHOULD have been the same as the supplied ETag, otherwise if its a different ETag then the content has changed and normal 200 response should be produced).

We should also verify the Etag behavior on ResourceService for similar reasons.

### PR DESCRIPTION
**Pull request by joakime**
Addresses the 4 behaviors seen from child handlers of `CompressionHandler`.

1. child sets response ETag header, then response status 200, then writes.
2. child sets response ETag header, then response status 304, then doesn't write.
3. child sets response status 200, then response ETag header, then writes.
3. child sets response status 304, then response ETag header, then doesn't write.

Fixes #14137

### CODE REVIEW

File: jetty-core/jetty-compression/jetty-compression-server/src/main/java/org/eclipse/jetty/compression/server/internal/CompressionResponse.java [hunk 1]
```diff
@@ -38,14 +38,59 @@ public class CompressionResponse extends Response.Wrapper
...
+        // Now need to re-add the compression etag suffix that was stripped
+        // from the request before the handling request.
+        return new HttpFields.Mutable.Wrapper(super.getHeaders())
+        {
+            @Override
+            public HttpField onAddField(HttpField field)
+            {
+                if (getStatus() == HttpStatus.NOT_MODIFIED_304)
+                {
+                    if (field.getHeader() == HttpHeader.ETAG)
```
Comment (lorban) [inline jetty-core/jetty-compression/jetty-compression-server/src/main/java/org/eclipse/jetty/compression/server/internal/CompressionResponse.java:69]: You can combine the two `if`s with `&&`.

**Review by lorban — APPROVED** [review]
Just a nit, otherwise LGTM.
