### PR TITLE
Issue #12505 - Server to Servlet Error Handling

### LINKED ISSUE #12505: `ErrorPageErrorHandler` does not use the proper attributes for error handling
**Jetty version(s)**
12.0.14

**Jetty Environment**
ee10

**Java version/vendor**
openjdk 21.0.3 2024-04-16 LTS

**OS type/version**
MacOS

**Description**
I'm upgrading an app from Jetty 10 to 12 and I'm running into some unexpected errors being mapped by jetty. I'm using the latest Spring Boot 3.3 version with no special custom configuration.

Basically I have a request that is clearly a poor hacking attempt on the path `//WEB-INF/classes/META-INF/microprofile-config.properties`. This is correctly mapped to a 404 by Jetty, however during error handling, I end up with a blank 500.

Tracing into the code, I see that I end up in the `ErrorPageErrorHandler` class here : https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ErrorPageErrorHandler.java#L63. This fails because it can't find any `Throwable`(which is normal AFAICT) but it cannot find a `errorStatusCode` either so it falls back on the generic error page.

Walking up the stack trace, I see that it's called from the `Response` interface https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java#L605 with an `ErrorHandler.ErrorRequest` instance. The `ErrorRequest` instance has the proper information (the status code + message) but it's under the keys in the `ErrorHandler` class : 
image

Now, I understand that the servlet + server part has been decoupled completely and that the `ErrorPageErrorHandler` is correctly looking at the servlet spec keys to find the exception or the status code. However, shouldn't this class also look at the server specific keys as a fallback?

Thanks in advance!

### PR DESCRIPTION
**Pull request by janbartel**
Fixes #12505

Addresses:
+ difference between jetty core error attributes and servlet api attributes
+ handling error generated in core before servlet context is selected

### CODE REVIEW

File: jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java [hunk 1]
```diff
@@ -153,6 +165,52 @@ private Path createWar(Path tempDir, String name) throws Exception
         return warFile;
     }
 
+    @Test
+    public void testProtectedTargetErrorPage() throws Exception
+    {
+        //TODO  -  the ErrorPageErrorHandler is looking for servlet api attributes, but the Response.writeError is using server api attributes
```
Comment (janbartel) [inline jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java]: Delete this comment, no longer relevant.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannelState.java [hunk 2]
```diff
@@ -1054,7 +1064,7 @@ public void sendError(int code, String message)
             request.setAttribute(ERROR_ORIGIN, servletContextRequest.getServletName());
             request.setAttribute(ErrorHandler.ERROR_CONTEXT, servletContextRequest.getServletContext());
             request.setAttribute(ErrorHandler.ERROR_MESSAGE, message);
-            request.setAttribute(ErrorHandler.ERROR_STATUS, code);
+            request.setAttribute(ERROR_STATUS, code);
```
Comment (janbartel) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannelState.java]: These attributes should all either be referenced via the `ErrorHandler` or none for consistency.

File: jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/WebAppContextTest.java [hunk 3]
```diff
@@ -547,6 +559,53 @@ public void testNullSessionAndSecurityHandler() throws Exception
         assertTrue(context.isAvailable());
     }
 
+    @Test
+    public void testErrorPage() throws Exception
+    {
+        //TODO  -  the ErrorPageErrorHandler is looking for servlet api attributes, but the Response.writeError is using server api attributes
```
Comment (janbartel) [inline jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/WebAppContextTest.java]: I don't think these comments are valid any longer

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java [hunk 4]
```diff
@@ -2681,6 +2681,12 @@ public class CoreContextHandler extends org.eclipse.jetty.server.handler.Context
             installBean(ContextHandler.this, true);
         }
 
+        @Override
+        protected boolean handleByContextHandler(String pathInContext, ContextRequest request, Response response, Callback callback)
+        {
+            return false;
```
Comment (janbartel) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java:2688]: We should - meaning I should have - added a comment here as to why we don't want the nested `ContextHandler` doing the handling.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java [hunk 5]
```diff
@@ -1196,7 +1196,14 @@ protected boolean handleByContextHandler(String pathInContext, ContextRequest re
...
             return false;
-        return super.handleByContextHandler(pathInContext, request, response, callback);
+
+        if (isProtectedTarget(pathInContext))
+        {
+            // Do nothing here other than set the error status so that the ServletHandler will handle as if a sendError
+            request.setAttribute(org.eclipse.jetty.server.handler.ErrorHandler.ERROR_STATUS, 404);
+            response.setStatus(HttpStatus.NOT_FOUND_404);
+        }
+        return false;
```
Comment (janbartel) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java:1209]: This is now different to `ee11` - is that on purpose or an omission?

**Review by janbartel — COMMENTED** [review]
A couple of things

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java (hunk 5 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java:1209]: The changes in ee11 required a change to the ErrorPageMapper API and implementation, that I do not want to do in EE10, so just doing the simplest solution here.   In EE11, I have tried to clean up the ErrorPageMapper API somewhat... but I think more could be done (maybe a different PR?)

**Review by gregw — APPROVED** [review]
I approve, but then I have worked on this, so my review is not enough

**Review by janbartel — COMMENTED** [review]
I approve! But I can't officially as I've created the PR.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 6]
```diff
@@ -753,9 +756,12 @@ public Enumeration<String> getAttributeNames()
 
     private class ErrorRequest extends ParameterRequestWrapper
     {
+         private final HttpServletRequest _httpServletRequest;
```
Comment (lorban) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: This line is oddly aligned. I'm surprised checkstyle let it go through.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 7]
```diff
@@ -797,6 +803,34 @@ public StringBuffer getRequestURL()
                 .port(getServerPort())
                 .asString());
         }
+
+        @Override
+        public Object getAttribute(String name)
+        {
+            return switch (name)
+            {
+                case ERROR_REQUEST_URI -> _httpServletRequest.getRequestURI();
```
Comment (lorban) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java:812]: You could call `getRequest` and cast it to `HttpServletRequest` instead of introducing the `_httpServletRequest` field.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 8]
```diff
@@ -797,6 +803,34 @@ public StringBuffer getRequestURL()
...
+                    yield err == null ? null : err.getClass();
+                }
+                default -> super.getAttribute(name);
+            };
+        }
+
+        @Override
+        public Enumeration<String> getAttributeNames()
+        {
+            // TODO add all names?
```
Comment (lorban) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java:829]: Shouldn't you add all the names present in `getAttribute()`'s `switch`?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 9]
```diff
@@ -1067,12 +1077,15 @@ public void sendError(int code, String message)
             // Set Jetty Specific Attributes.
             request.setAttribute(ErrorHandler.ERROR_CONTEXT, servletContextRequest.getServletContext());
             request.setAttribute(ErrorHandler.ERROR_MESSAGE, message);
-            request.setAttribute(ErrorHandler.ERROR_STATUS, code);
+            request.setAttribute(ERROR_STATUS, code);
```
Comment (lorban) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: Why was `ERROR_STATUS` statically imported? Other constants are not.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ErrorPageErrorHandler.java [hunk 10]
```diff
@@ -60,118 +54,62 @@ public void setUnwrapServletException(boolean unwrapServletException)
...
+                exClass = exClass.getSuperclass();
             }
-        }
 
-        // Try servlet 3.x global error page.
-        if (errorPage == null)
-        {
-            pageSource = PageLookupTechnique.GLOBAL;
-            errorPage = _errorPages.get(GLOBAL_ERROR_PAGE);
+            cause = (cause instanceof ServletException) ? ((ServletException)cause).getRootCause() : cause.getCause();
```
Comment (lorban) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ErrorPageErrorHandler.java]:
```diff
--- cause = (cause instanceof ServletException) ? ((ServletException)cause).getRootCause() : cause.getCause();
+++ cause = (cause instanceof ServletException se) ? se.getRootCause() : cause.getCause();
```

**Review by lorban — APPROVED** [review]
Just found a few nits.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 11]
```diff
@@ -797,6 +803,34 @@ public StringBuffer getRequestURL()
...
+        public Object getAttribute(String name)
+        {
+            return switch (name)
+            {
+                case ERROR_REQUEST_URI -> _httpServletRequest.getRequestURI();
+                case ERROR_STATUS_CODE -> super.getAttribute(ErrorHandler.ERROR_STATUS);
+                case ERROR_MESSAGE -> super.getAttribute(ErrorHandler.ERROR_MESSAGE);
+                case ERROR_SERVLET_NAME -> super.getAttribute(ErrorHandler.ERROR_ORIGIN);
+                case ERROR_EXCEPTION -> super.getAttribute(ErrorHandler.ERROR_EXCEPTION);
+                case ERROR_EXCEPTION_TYPE ->
```
Comment (lachlan-roberts) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java:817]: This is a bit confusing because we now set these jakarta attributes in two places. So I think we should try to make sure they're only set in one of these, because as far as I can tell now you could remove this and it wouldn't break anything because the attributes are set by `ServletChannelState.sendError`.

See https://github.com/jetty/jetty.project/blob/156b083e2cc1a6bb653b07488d4ba81b2cb4529c/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java#L1061-L1070

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java [hunk 12]
```diff
@@ -1196,7 +1196,14 @@ protected boolean handleByContextHandler(String pathInContext, ContextRequest re
         boolean initialDispatch = request instanceof ServletContextRequest;
         if (!initialDispatch)
             return false;
-        return super.handleByContextHandler(pathInContext, request, response, callback);
+
+        if (isProtectedTarget(pathInContext))
+        {
+            // Do nothing here other than set the error status so that the ServletHandler will handle as if a sendError
+            request.setAttribute(org.eclipse.jetty.server.handler.ErrorHandler.ERROR_STATUS, 404);
```
Comment (lachlan-roberts) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java:1206]: Its also possible to directly do a `sendError` directly here, which might be more clear, but might require some tweaks to the `ServletChannelState` to handle `sendError` from `IDLE`.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java [hunk 13]
```diff
@@ -1195,7 +1196,23 @@ protected boolean handleByContextHandler(String pathInContext, ContextRequest re
...
+                ErrorHandler.ErrorPageMapper.ErrorPage errorPage = mapper.getErrorPage(404, null);
+                if (errorPage != null)
+                {
+                    // Do nothing here other than set the error status so that the ServletHandler will handle as if a sendError
+                    request.setAttribute(ERROR_STATUS, 404);
+                    response.setStatus(HttpStatus.NOT_FOUND_404);
+                    return false;
+                }
+            }
+            Response.writeError(request, response, callback, HttpStatus.NOT_FOUND_404, null);
```
Comment (lachlan-roberts) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java:1212]: I don't see how this ever sets the error attributes, as it doesn't go through the servlet `sendError`.

I actually think this doesn't work at all if they have a `org.eclipse.jetty.ee11.servlet.ErrorHandler` and want to handle the request with servlet APIs, because we never enter the `ServletChannel`.

**Review by lachlan-roberts — CHANGES_REQUESTED** [review]

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java (hunk 13 above)
Comment (janbartel) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java:1212]: The `ErrorPageTest` in ee9,10,11 have tests that check that a configured error servlet is invoked, see: https://github.com/jetty/jetty.project/blob/jetty-12.1.x-12505-server-to-servlet-errorhandling/jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/ErrorPageTest.java#L2041

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java (hunk 12 above)
Comment (janbartel) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java:1206]: I don't think it's any clearer - at this point we have a core `Response`, not a `HttpServletResponse`.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java (hunk 13 above)
Comment (lachlan-roberts) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java:1212]: @janbartel that test is only ever testing with `ErrorPageErrorHandler` so it is never reaching this line of code.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java (hunk 12 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java:1206]: We do already know here it is a `ServletContextRequest` so we have access to the `HttpServletResponse` (checked directly above at the start of this method). 

So you could do this `servletContextRequest.getServletContextResponse().getServletRequestState().sendError(404, null);`.

Currently this needs to set a special attribute to trigger calling `sendError` internally, when the call to `sendError` could be done right here.

Comment (janbartel) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java:1206]: Well, we got into trouble last time by trying to handle the error here (with a `Response.writeError` that bypassed the `ServletChannel` etc), rather than letting the normal mechanism take care of it.  IMHO that call chain isn't particularly clear either - (also, side note, that method is badly named, if it returns a `ServletChannelState` it shouldn't be called `getServletRequestState`). 

@gregw what's your take on this? Want to try and take the short cut to `sendError` or set the attribute and flow through the normal execution path?

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java (hunk 13 above)
Comment (janbartel) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java:1212]: @lachlan-roberts not following you - if they do not have an error page, but instead have configured a customized `ee11 ErrorHandler` or a `core ErrorHandler` then they're not using the servlet api, they're using jetty core api?

Comment (lachlan-roberts) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java:1212]: I just assumed if you use the ee11 `ErrorHandler` class, you would be allowed to use the Servlet API if you override it.

But I guess that's not possible because we're returning true here, so they would have to use core APIs.

I don't understand why the EE11 does not combine `ErrorHandler`, `ErrorPageErrorHandler` and `ErrorPageMapper` into one class.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java (hunk 12 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java:1206]: @lachlan-roberts At this point we have not entered the ServletHandler, so the ServletChannel state machine has not started.   Thus I'm not sure that calling sendError here is exactly what we want to do.  It might work, but it might also do other stuff that is not necessary.    It is more likely to throw an ISE because the ServletChannelState will be IDLE.

The idea of this PR is to signal that a call to sendError is necessary, but to delay that until we are within the ServletChannelState machine.

Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java:1206]: It would take only 3-4 lines to be changed in ServletChannelState to make it work.

I would just prefer use of API, either sendError or something else, because someone working on a similar case in future will not know they have to set both the response status and this attribute to trigger a sendError if it hasn't entered the SerlvetChannel yet.

**Review by lachlan-roberts — APPROVED** [review]

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java (hunk 12 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java:1206]: @lachlan-roberts I'm  the other way.  I like the ISE being thrown if sendError is being called outside of the scope it should be.   If we want to cause a send error on entry to the ServletHandler, it is best to use a different mechanism.
In this case the mechanism is to have both the response status set AND the error attribute set.  It is done this way because checking attributes is a little expensive, so we first check the status.  But unfortunately checking the status is not enough as there are some strange circumstances where a status is spuriously set before arriving at the ServletHandler.   So if it is non-zero, we then check the attribute to be sure an error dispatch was intended.

@janbartel perhaps we should put a comment to explain that?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java [hunk 14]
```diff
@@ -1199,7 +1199,10 @@ protected boolean handleByContextHandler(String pathInContext, ContextRequest re
 
         if (isProtectedTarget(pathInContext))
         {
-            // Do nothing here other than set the error status so that the ServletHandler will handle as if a sendError
+            // At this point we have not entered the state machine of the ServletChannelState, so we do nothing here
+            // other than to set the error status attribute (and also status). When execution proceeds normally into the
+            // state machine the request will be treated as an error. Note that we set both the error status and request
+            // status because the request status is cheaper to check than the error status attribute.
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java:1205]: Nice

**Review by gregw — APPROVED** [review]
