### PR TITLE
Issue #14431 - fixes for ServletContainerInitializer exclusion with absolute-ordering

### LINKED ISSUE #14431: ServletContainerInitializers are always excluded when used with absolute-ordering
**Jetty version(s)**
12.0.x+

**Jetty Environment**
EE8

**Description**
Any `ServletContainerInitializer` from JARs contained within WEB-INF/lib are all excluded if the `web.xml` file contains an `<absolute-ordering>` element, even if this lists `<others/>`.

Here is an analysis of what exactly happens when starting:
1. `WebXmlConfiguration` calls `MetaData.orderFragments`.
2. `MetaInfConfiguation` calls `MetaData.addWebInfResource`.
3. `AnnotationConfiguration` uses `MetaData.getWebInfResources(true)` to get the ordered WEB-INF resources.
4. `MetaData.getWebInfResources(true)` is now always null because `MetaData.orderFragments` was called before the resources were added with `MetaData.addWebInfResource`.

see https://github.com/GoogleCloudPlatform/appengine-java-standard/issues/462

### PR DESCRIPTION
**Pull request by lachlan-roberts**
### Closes #14431

Change `MetaData` to lazily order its resources only when `getWebInfResources(true)` is called, and reset this ordering when `metadata.setOrdering()` is called.

### CODE REVIEW

File: jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaData.java [hunk 1]
```diff
@@ -56,7 +56,7 @@ public class MetaData
     protected final List<Resource> _webInfClasses = new ArrayList<>();
     protected final List<Resource> _webInfJars = new ArrayList<>();
     protected final List<Resource> _orderedContainerResources = new ArrayList<>();
-    protected final List<Resource> _orderedWebInfResources = new ArrayList<>();
+    protected List<Resource> _orderedWebInfResources;
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaData.java]: I'm not too fond of the idea of changing a `List` field to non-final, _especially_ a `protected` one, _especially_ in a class whose instances can be read from multiple threads in parallel.

Couldn't you do with clearing the list instead as it used to be done? At worst, I would prefer adding a `boolean` flag.

**Review by lorban — CHANGES_REQUESTED** [review]
We may need to discuss what exactly needs to be done to avoid changing a final field to a non-final one if there is no easy solution in sight.

**Review by sbordet — CHANGES_REQUESTED** [review]
I don't mind the lazy solution, but from the issue description feels like `MetaData.orderFragments()` is called at the wrong time.

If it was called at the right time, then we would not need the lazy solution, right?

Also, don't we have this problem in EE10 and EE11 too?

File: jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaData.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaData.java]: I have changed the list back to final, and now there is a boolean flag instead.

But I don't think this is used by multiple threads in parallel, it is only used from `WebAppContext.doStart()`.

**Comment by lachlan-roberts** [comment]
>I don't mind the lazy solution, but from the issue description feels like MetaData.orderFragments() is called at the wrong time.
>
> If it was called at the right time, then we would not need the lazy solution, right?

I don't think there is a single spot where its the right time to call `orderFragments()`. The `WebAppContext` loops over its configurations and they can all independently use the `MetaData`. So I think its best for `MetaData` itself to keep track of when `orderFragments()` needs to be called, because it would be more error prone to manage it externally.

> Also, don't we have this problem in EE10 and EE11 too?

I have now added tests and the fix to both EE10 and EE11.

File: jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaData.java (hunk 1 above)
Comment (lorban) [reply jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaData.java]: `MedaData` instances are stored in `WebAppContext` and made accessible via `getMetaData()`, so any thread can read that list at any time. I'm not worried about __mutual exclusion__ but __memory visibility__ here.

Having that field marked as `final` makes that problem go away, so I'm happy.

**Review by lorban — DISMISSED** [review]

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaData.java [hunk 2]
```diff
@@ -173,6 +174,7 @@ public void clear()
         _annotations.clear();
         _webInfJars.clear();
         _orderedWebInfResources.clear();
+        _webInfResourcesNeedsOrdering = true;
```
Comment (janbartel) [inline jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaData.java]: Can we do this without having this new boolean? What if `orderFragments()` just always cleared the current order, then did a (re)order. Then in `getWebInfResources(true)`, we call `orderFragments()` iff  there is an ordering set, and the current order is empty?

**Review by janbartel — DISMISSED** [review]

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaData.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaData.java]: We could remove the boolean by using the combination of `_orderedWebInfResources.isEmpty() && !_webInfJars.isEmpty()` to give the same state the boolean would give. And then we would need to do a `_orderedWebInfResources.clear()` every time the ordering goes stale in `addWebInfResource()` or `setOrdering()`.

This removes the boolean but adds a few extra cycles calling `_orderedWebInfResources.clear()` multiple times.

Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaData.java]: I have made these changes.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sci-jar/pom.xml [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+    <groupId>org.eclipse.jetty.ee10</groupId>
+    <artifactId>jetty-ee10-tests</artifactId>
+    <version>12.1.8-SNAPSHOT</version>
+  </parent>
+  <artifactId>jetty-ee10-test-sci-jar</artifactId>
+  <name>EE10 :: Tests :: SCI Test JAR</name>
+  <description>Jetty SCI Test JAR</description>
+  <properties>
+    <bundle-symbolic-name>${project.groupId}.tests.sci.jar</bundle-symbolic-name>
+  </properties>
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sci-jar/pom.xml:15]: Add:

`    <maven.deploy.skip>true</maven.deploy.skip>`

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sci-webapp/pom.xml [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+    <artifactId>jetty-ee10-tests</artifactId>
+    <version>12.1.8-SNAPSHOT</version>
+  </parent>
+  <artifactId>jetty-ee10-test-sci-webapp</artifactId>
+  <packaging>war</packaging>
+  <name>EE10 :: Tests :: SCI Test WebApp</name>
+  <description>Jetty SCI Test JAR</description>
+  <properties>
+    <bundle-symbolic-name>${project.groupId}.tests.sci.webapp</bundle-symbolic-name>
+  </properties>
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-tests/jetty-ee10-test-sci-webapp/pom.xml:16]: Add `<maven.deploy.skip>true</maven.deploy.skip>`.

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaData.java [hunk 5]
```diff
@@ -580,14 +580,18 @@ public boolean isMetaDataComplete()
...
         _webInfJars.add(newResource);
+        _orderedWebInfResources.clear();
     }
 
     public List<Resource> getWebInfResources(boolean withOrdering)
     {
         if (!withOrdering)
             return Collections.unmodifiableList(_webInfJars);
         else
+        {
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaData.java]: Remove `else`.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]
