### PR TITLE
Issue #5224 X-Forwarded-Host support for port

### LINKED ISSUE #5224: HttpServletRequest.getServerName can include port when using ForwardedRequestCustomizer
**Jetty version**
9.4.30

**Java version**
Any supported

**OS type/version**
Any supported

**Description**

Nexus Repository Manager was upgraded from using Jetty 9.4.18 to 9.4.30.

Customers have reported certain combinations of previously working X-Forwarded-* headers to no longer work. ( https://issues.sonatype.org/browse/NEXUS-25158 ).

It appears a certain combination of X-Forwarded headers can cause HttpServletRequest.getServerName to return a value which is not a host name because it includes a port number. This fails the validation that NXRM does on host name value.

This test case:

```
Index: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java	(revision 271836e4c1f4612f12b7bb13ef5a92a927634b0d)
+++ jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java	(date 1599052223742)
@@ -497,7 +497,21 @@
                     .requestURL("http://fw.example.com:4333/")
                     .remoteAddr("8.5.4.3").remotePort(2222)
             ),
-
+            Arguments.of(new Request("X-Forwarded-* ( Multiple Ports )")
+                    .headers(
+                        "GET / HTTP/1.1",
+                        "Host: myhost:10001",
+                        "X-Forwarded-For: 127.0.0.1:8888,127.0.0.2:9999",
+                        "X-Forwarded-Port: 10002",
+                        "X-Forwarded-Proto: https",
+                        "X-Forwarded-Host: sub1.example.com:10003",
+                        "X-Forwarded-Server: sub2.example.com"
+                    ),
+                new Expectations()
+                    .scheme("https").serverName("sub1.example.com").serverPort(10002) // Jetty 9.4.18 serverPort is 10003
+                    .requestURL("https://sub.example.com:10002/")
+                    .remoteAddr("127.0.0.1").remotePort(8888)
+            ),
             // =================================================================
             // Mixed Behavior
             Arguments.of(new Request("RFC7239 mixed with X-Forwarded-* headers")

```

Fails with:

```
java.lang.AssertionError: serverName
Expected: is "sub1.example.com"
     but: was "[sub1.example.com:10003]"
Expected :sub1.example.com
Actual   :[sub1.example.com:10003]

```

We noticed if `X-Forwarded-Port` header is not set, then the test will pass. Still since this was working in 9.4.18, we did not expect this to break on a micro version upgrade.

### PR DESCRIPTION
**Pull request by joakime**

### CODE REVIEW

**Review by sbordet — APPROVED** [review]

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java [hunk 1]
```diff
@@ -497,7 +497,67 @@ public void destroy() throws Exception
...
+                        "Host: myhost:10001",
+                        "X-Forwarded-For: 127.0.0.1:8888,127.0.0.2:9999",
+                        "X-Forwarded-Port: 10002",
+                        "X-Forwarded-Proto: https",
+                        "X-Forwarded-Host: sub1.example.com:10003",
+                        "X-Forwarded-Server: sub2.example.com"
+                    ),
+                new Expectations()
+                    .scheme("https").serverName("sub1.example.com").serverPort(10003)
+                    .requestURL("https://sub1.example.com:10003/")
```
Comment (gregw) [inline jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java:543]: I don't agree with this test.  We should be order independent for such headers.  If we decide that `X-Forwarded-Port` takes precedent over any port specified in `X-Forwarded-Host` then it should do so regardless of the order of those headers!

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java [hunk 2]
```diff
@@ -598,16 +598,18 @@ public void handleSslSessionId(HttpField field)
         @SuppressWarnings("unused")
         public void handleHost(HttpField field)
         {
+            HostPort hp = new HostPort(getLeftMost(field.getValue()));
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: `s/hp/hostField/`

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java [hunk 3]
```diff
@@ -497,7 +497,67 @@ public void destroy() throws Exception
...
+                        "Host: myhost:10001",
+                        "X-Forwarded-For: 127.0.0.1:8888,127.0.0.2:9999",
+                        "X-Forwarded-Proto: https",
+                        "X-Forwarded-Host: sub1.example.com:10003",
+                        "X-Forwarded-Port: 10002",
+                        "X-Forwarded-Server: sub2.example.com"
+                    ),
+                new Expectations()
+                    .scheme("https").serverName("sub1.example.com").serverPort(10003)
+                    .requestURL("https://sub1.example.com:10003/")
```
Comment (gregw) [inline jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java:558]: Ditto the port here should be 10002... in fact isn't that what the code already does?  Wont the code at :+1: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L662
always replace the port of the host header?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java (hunk 1 above)
Comment (joakime) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java:543]: The code in ForwardedRequestCustomizer is most definitely order dependent, esp around host/port/authority.  (IIRC, these are not the only tests that show this order dependency, i'll point out which other ones we have tomm.).
This order dependency was introduced when the code changed to iterating the fields from querying the fields.

If we want to change this code to not be order dependent, then we should go over all of the tests and expectations first, discuss them, then fix the code to conform to the expectations.

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java (hunk 3 above)
Comment (joakime) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java:558]: IIRC, it resolves as ...

* `Host` becomes authority
* `X-Forwarded-Port` changes authority
* `X-Forwarded-Host` changes host (but not port, as it was set by `X-Forwarded-Port`) to new authority

So the following headers ...

```
Host: myhost:10001
X-Forwarded-Port: 10002
X-Forwarded-Host: sub1.example.com:10003
```

becomes in order ....

1. authority is `myhost:10001` (from `Host`)
2. authority is `myhost:10002` (from `X-Forwarded-Port`)
3. authority is `sub1.example.com:10002` (from `X-Forwarded-Host`)

but the headers in a different order ...

```
Host: myhost:10001
X-Forwarded-Host: sub1.example.com:10003
X-Forwarded-Port: 10002
```

Goes thru ...

1. authority is `myhost:10001` (from `Host`)
2. authority is `sub1.example.com:10003` (from `X-Forwarded-Host`)
3. authority is unchanged, and stays at `sub1.example.com:10003` because it set "host" and "port" already (the `X-Forwarded-Port` doesn't change it again)

Lets chat about the test cases tomm, I'll take a stab at fixing them in a more sane way (keeping iteration).
I see authority going thru a state change for both host and port of (UNSET, LAZY, AUTHORITATIVE), where LAZY is only used for `Host`, but other headers can upgrade the state to AUTHORITATIVE, and then when it's all done parsing the final server/host authority is calculated. (and not using the overly complicated extended HostPort classes that have confusing meanings with no javadoc explaining them)

Comment (gregw) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java:558]: @joakime the code has been explicitly designed to be order independent for host and port.  That is why we have `PortSetHostPort` and `PossiblyPartialHostPort` classes to record if a port or a host has been set before another header arrives that sets the other one.

So specifically the outcome for:
```
X-Forwarded-Host: sub1.example.com:10003
X-Forwarded-Port: 10002
```

should be no different from the outcome for:

```
X-Forwarded-Port: 10002
X-Forwarded-Host: sub1.example.com:10003
```

My preference is for the explicit port header to always win, so the result will be `sub1.example.com:1002` in both cases.  Let me find some time to play with your branch  to see how your tests are even passing, then we can chat about it.

Comment (gregw) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java:558]: OK part of the problem is [here](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x-5224-xforwarded-multiple-ports/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L639-L640):
```java
        public void handleFor(HttpField field)
        {
            String authority = getLeftMost(field.getValue());
            if (!getForwardedPortAsAuthority() && !StringUtil.isEmpty(getForwardedPortHeader()))
            {
                if (_for == null)
                    _for = new PossiblyPartialHostPort(authority);
                else if (_for instanceof PortSetHostPort)
                    _for = new HostPort(HostPort.normalizeHost(authority), _for.getPort());
            }
            else if (_for == null)
            {
                _for = new HostPort(authority);
            }
        }
```

This code is not checking if in the case a `PortSetHostPort` exists if the `For` header also has a port. Thus in this case we are giving precedence to the port header.

But the [code for the port header](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x-5224-xforwarded-multiple-ports/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L663) does the opposite:
```java
        public void handlePort(HttpField field)
        {
            int port = HostPort.parsePort(getLeftMost(field.getValue()));
            if (!getForwardedPortAsAuthority())
            {
                if (_for == null)
                    _for = new PortSetHostPort(_request.getRemoteHost(), port);
                else if (_for instanceof PossiblyPartialHostPort && _for.getPort() <= 0)
                    _for = new HostPort(HostPort.normalizeHost(_for.getHost()), port);
            }
            else
            {
                if (_host == null)
                    _host = new PortSetHostPort(_request.getServerName(), port);
                else if (_host instanceof PossiblyPartialHostPort && _host.getPort() <= 0)
                    _host = new HostPort(HostPort.normalizeHost(_host.getHost()), port);
            }
        }
```
It is checking if there is actually a port set in the `PossiblyPartiallyHostPort` and if so it gives it precedence and ignores the port header.

So you need to make the same policy decision in both places - either the port header has precedence or it doesn't - I guess I don't mind either way, we just need to be consistent.

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java [hunk 4]
```diff
@@ -598,16 +598,18 @@ public void handleSslSessionId(HttpField field)
...
+
             if (getForwardedPortAsAuthority() && !StringUtil.isEmpty(getForwardedPortHeader()))
             {
                 if (_host == null)
-                    _host = new PossiblyPartialHostPort(getLeftMost(field.getValue()));
+                    _host = new PossiblyPartialHostPort(hp.getHost(), hp.getPort());
                 else if (_host instanceof PortSetHostPort)
-                    _host = new HostPort(HostPort.normalizeHost(getLeftMost(field.getValue())), _host.getPort());
+                    _host = new HostPort(hp.getHost(), _host.getPort());
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: This would make it the same as `handlePort`
```suggestion
                    _host = new HostPort(hp.getHost(), hp.getPort() >0 ? hp.getPort() : _host.getPort());
```

alternately take the `port <= 0` test out of `handlePort` to get the alternate precedence.

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java (hunk 2 above)
Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: Fixed.

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java (hunk 1 above)
Comment (joakime) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java:543]: I opened Issue #5247, proposing a better way.

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java (hunk 3 above)
Comment (joakime) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java:558]: I opened Issue #5247, proposing a better way.

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java (hunk 4 above)
Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: Done.

**Review by gregw — APPROVED** [review]
