### PR TITLE
Issue #4819 - Workarounds for old (pre API 24) Android SDKs

### LINKED ISSUE #4819: Some methods used on Jetty 9.2.29 are not available on Android API 23 (or older)
**Jetty version**
Android API 23 (or older)

**Java version**
Android

**OS type/version**
Android

**Description**
Some SSL/TLS code paths in Jetty use methods that are only introduced in Android API 24.
Using this Jetty code on Android API 23 (or older) causes NoSuchMethodError exceptions.

Ignoring these NoSuchMethodError exceptions and continuing is acceptable on these older Android API revisions.

### PR DESCRIPTION
**Pull request by joakime**
There's a number of SSL/TLS related API calls that we use in Jetty 9.2.x that are not available in older versions of Android.

These are a set of workarounds to not crash when those APIs are not present in the JVM runtime.

### CODE REVIEW

**Comment by joakime** [comment]
This is strictly for Jetty 9.2.x branch.
If PR is approved, these changes will not be merged into newer versions of Jetty.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java [hunk 1]
```diff
@@ -143,9 +142,22 @@ public void setRenegotiationAllowed(boolean renegotiationAllowed)
         this._renegotiationAllowed = renegotiationAllowed;
     }
 
+    private SSLSession getOptionalHandshakeSession()
```
Comment (sbordet) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java]: Just call it `getHandshakeSession()`.

**Review by sbordet — CHANGES_REQUESTED** [review]
Apart the renaming, LGTM, but please do the renaming.

**Comment by joakime** [comment]
@sbordet I made the change, but I also ...

* Created an issue for this: Issue #4819 
* Rebased all 3 commits into one to make tracking of this change easier in git. (and used new Issue number in resulting commit)
* Forced push (with lease) the changes to this branch.

Once I get a confirmed green build from CI It should be ready to merge.

**Review by sbordet — APPROVED** [review]
