### PR TITLE
Issue #13043 - review of websocket Flushers for 12.1

### LINKED ISSUE #13043: Review WebSocket flushers
**Jetty version(s)**
12.1.x

**Enhancement Description**
After #13034, review WebSocket flushers, in particular:

* Use `Deflater.deflate(ByteBuffer)` instead of `deflate(byte[])`, and honor the use of direct `ByteBuffer`s also for deflate.
* Make sure that fields are reset and inflater/deflaters are re-pooled in case of exceptions.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #13043

- rename `TransformingFlusher` to `WebSocketFlusher` and update it to use an `OutgoingEntry` API instead of `frame + callback + batch`.
- add method to override to handle `onCompleteFailure` on `WebSocketFlusher`
- `WebSocketFlusher` now wraps the callback needed to continue processing in the `OutgoingEntry` itself.
- Rename `DemandingFlusher` to `WebSocketDemander`, and use a lock instead of multiple atomic variables for the implementation.

### CODE REVIEW

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java [hunk 1]
```diff
@@ -37,15 +37,17 @@
...
     private static final Throwable SENTINEL_CLOSE_EXCEPTION = new StaticException("Closed");
 
+    private final AutoLock _lock = new AutoLock();
     private final IncomingFrames _emitFrame;
-    private final AtomicBoolean _demand = new AtomicBoolean();
-    private final AtomicReference<Throwable> _failure = new AtomicReference<>();
-    private DemandChain _nextDemand;
 
+    private boolean _upstreamDemand = false;
+    private boolean _downstreamDemand = false;
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: probably a little comment to clarify which direction upstream and downstream are.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java [hunk 2]
```diff
@@ -54,19 +56,25 @@ public abstract class DemandingFlusher extends IteratingCallback implements Dema
...
      * @param emitFrame where frames generated by {@link #handle(Frame, Callback, boolean)} are forwarded.
      */
-    public DemandingFlusher(IncomingFrames emitFrame)
+    public WebSocketDemander(IncomingFrames emitFrame)
     {
         _emitFrame = emitFrame;
     }
 
+    @Override
+    public void setNextDemand(DemandChain nextDemand)
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java:65]: Should "Next" be "downstream"?  Or if next/prev makes sense, then use them instead of upstream/downstream ?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java [hunk 3]
```diff
@@ -75,18 +83,54 @@ public DemandingFlusher(IncomingFrames emitFrame)
...
+            failFlusher(failure);
+        }
+        else
+        {
+            _emitFrame.onFrame(frame, callback);
+        }
     }
 
+    /**
+     * This is used by the downstream layer to demand a new frame to be processed in {@link #handle(Frame, Callback, boolean)}.
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: Oh - I would have called the layer calling demand upstream, as it is the layer above.
Hmmmm maybe I suggested bad names for you???

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java [hunk 4]
```diff
@@ -97,21 +141,43 @@ public void setNextDemand(DemandChain nextDemand)
...
+        try (AutoLock l = _lock.lock())
+        {
+            if (_failure != null)
+            {
+                failure = _failure;
+            }
+            else if (_upstreamDemand)
+            {
+                // Fulfill the incoming demand to receive a new frame.
+                _upstreamDemand = false;
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: Oh the layer above is called upstream?  Hmmmm is the comment to demand wrong?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: I actually think you meant upstream

**Review by gregw — CHANGES_REQUESTED** [review]
Mostly looks good, but I think some comments are wrong with their upstream/downstream usage?    which way the stream flows needs to be made clear in comments.

Then I'm not sure mixing in "Next" is a good idea.  Isn't that just "Downstream"?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: I was thinking that the most upstream would be the WebSocketConnection as the source of the frames, and the most downstream would be the application demanding the frames. In which case this method would correspond to the downstream demand.

But if you think about the demand itself originating from the application then that would be the most upstream. 

So I could just reverse all the naming of all my upstream/downstreams.

Comment (gregw) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: @lachlan-roberts Let me think...  I could be confused myself...
In this case, data is flowing from the network to the application, so in one sense the "stream" is flowing from low layers down to the application, so the application calling demand would be "downstream" as you said in at least one of your comments.
But more typically (and chatGPT backs me here) upstream is towards a higher layer of the protocol stack, so the application and/or layer above calling demand is "upstream".

Needless to say, the most important thing is to be internally consistent, and I don't think you current comments are.  Also you have used "Next" in at least once circumstance, which is a mixed metaphor.

So pick a pair: upstream/downstream; downstream/upstream; prev/next; above/below; etc.   and then explain the metaphor in the opening comments apply it rigorously to all code and comments

Comment (gregw) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: Demandee/demandor? 

Source/Consumer?

Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: The fact that we need to have this discussion probably means the names aren't suitable and are likely to cause some confusion. 

I can try using producerDemand and consumerDemand names.

>  Also you have used "Next" in at least once circumstance

This is a pre-existing method on the `DemandChain` interface. But it would be a little confusing to rename this to `setProducerDemand()` when there is no concept of consumer demand on the interface.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/FragmentExtension.java [hunk 5]
```diff
@@ -97,8 +92,10 @@ public void init(ExtensionConfig config, WebSocketComponents components)
         configuration.setMaxFrameSize(maxLength);
     }
 
-    public class FragmentingDemandingFlusher extends DemandingFlusher
+    public class FragmentingDemandingFlusher extends WebSocketDemander
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/FragmentExtension.java]: Rename class to `FragmentingDemander`?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/FragmentExtension.java [hunk 6]
```diff
@@ -107,40 +104,42 @@ public FragmentingDemandingFlusher()
...
             {
-                if (frame.isControlFrame())
+                if (frame.isControlFrame() || maxFrameSize <= 0 || frame.getPayloadLength() <= maxFrameSize)
                 {
                     emitFrame(frame, callback);
                     return true;
                 }
+
+                // Slice the payload so we don't modify the original.
+                _payload = frame.getPayload().slice();
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/FragmentExtension.java]: Actually, feels "natural" that the incoming payload is consumed as it is sliced into fragments.
Other flushers, e.g. those that compress/decompress, would also consume the input, so here would feel natural too.
This is the hot path, and if we can save the allocation would be great.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java [hunk 7]
```diff
@@ -264,57 +263,37 @@ public void demand()
...
+                    return true;
+                }
 
-        @Override
-        protected boolean transform(Callback callback)
-        {
-            boolean finished = deflate(callback);
-            _first = false;
+                // Provide the frames payload as input to the Deflater.
+                getDeflater().setInput(entry.getFrame().getPayload().slice());
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java:280]: Do you need slicing here?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java [hunk 8]
```diff
@@ -342,44 +321,45 @@ private boolean deflate(Callback callback)
...
                 .callback(callback)
-                .build();
-            nextOutgoingFrame(entry);
+                .build());
             return finished;
         }
     }
 
-    private class IncomingFlusher extends DemandingFlusher
+    private class IncomingFlusher extends WebSocketDemander
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java]: Rename to `IncomingDemander`?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/FragmentingFlusher.java [hunk 9]
```diff
@@ -15,89 +15,82 @@
...
 
-    @Override
-    protected boolean transform(Callback callback)
-    {
-        boolean finished = fragment(callback, false);
-        if (finished)
-            payload = null;
-        return finished;
-    }
+            _payload = frame.getPayload().slice();
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/FragmentingFlusher.java:56]: Not necessary?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java [hunk 10]
```diff
@@ -75,18 +83,54 @@ public DemandingFlusher(IncomingFrames emitFrame)
...
+     * @param frame the WebSocket frame.
+     * @param callback to release frame payload.
+     */
+    public void emitFrame(Frame frame, Callback callback)
     {
-        if (!_demand.compareAndSet(false, true))
-            throw new ReadPendingException();
-        iterate();
+        Throwable failure = null;
+        try (AutoLock l = _lock.lock())
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]:
```suggestion
        try (AutoLock ignored = _lock.lock())
```

Using `ignored` saves warnings in the IDE. Please update also elsewhere.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java [hunk 11]
```diff
@@ -97,21 +141,43 @@ public void setNextDemand(DemandChain nextDemand)
...
+            if (_failure != null)
+            {
+                failure = _failure;
+            }
+            else if (_inputDemand)
+            {
+                // Fulfill the incoming demand to receive a new frame.
+                _inputDemand = false;
+                _frame = frame;
+                _callback = new CountingCallback(callback, 1);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java:158]: No need to wrap with `CountingCallback` is the count is `1`, no?

I see the comment in `onCompleteFailure()`, but either that comment should be here, or better we should try to avoid to double-complete the callback (this should be controlled, as this is an `IteratingCallback` so it should never be double-completed).

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java [hunk 12]
```diff
@@ -97,21 +141,43 @@ public void setNextDemand(DemandChain nextDemand)
...
-        succeeded();
+        if (failure == null)
+        {
+            succeeded();
+        }
+        else
+        {
+            callback.failed(failure);
+            failFlusher(failure);
+        }
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: This feels wrong, because if no failure, the whole `IteratingCallback` is succeeded, but not the `callback` parameter, and if there is a failure, the `callback` parameter is failed, but not the `IteratingCallback` (which is instead aborted).

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java [hunk 13]
```diff
@@ -0,0 +1,213 @@
...
+    private final IteratingCallback _flusher = new Flusher();
+    private Throwable _failure;
+
+    /**
+     * Called when a frame is ready to be transformed.
+     * @param entry the entry containing the frame to be transformed.
+     * @param first true if this is the first time this entry is being processed.
+     * @return true to indicate that you have finished transforming this entry.
+     */
+    protected abstract boolean onFrame(OutgoingEntry entry, boolean first);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java:52]: Can the entry transformation be asynchronous, so that this should rather be:

```suggestion
    protected abstract void onFrame(OutgoingEntry entry, boolean first, Promise<Boolean> promise);
```

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java [hunk 14]
```diff
@@ -0,0 +1,213 @@
...
+        if (log.isDebugEnabled())
+            log.debug("notifyCallbackSuccess {}", entry);
+
+        try
+        {
+            entry.getCallback().succeeded();
+        }
+        catch (Throwable x)
+        {
+            log.warn("Exception while notifying success of entry {}", entry, x);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java:195]: Use LOG.info() like in the other cases of exceptions while notifying listeners.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java [hunk 15]
```diff
@@ -0,0 +1,213 @@
...
+        if (log.isDebugEnabled())
+            log.debug("notifyCallbackFailure {} {}", entry, failure.toString());
+
+        try
+        {
+            entry.getCallback().failed(failure);
+        }
+        catch (Throwable x)
+        {
+            log.warn("Exception while notifying failure of entry {}", entry, x);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java:210]: LOG.info()

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java (hunk 15 above)
Comment (gregw) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java:210]: Debug or warn.  info is for more expected stuff.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/FragmentExtension.java (hunk 6 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/FragmentExtension.java]: I was trying to align this class with the FragmentingFlusher which slices the payload. But yes we don't need to slice for the incoming payloads at least, so I removed this slice.

Also, this is not really the hot path, I don't think the `FragmentExtension` is actually used by anyone.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java (hunk 7 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java:280]: We do because currently the contract is that we do not consume the frame payload on a sendFrame (see https://github.com/jetty/jetty.project/issues/13290).

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/FragmentingFlusher.java (hunk 9 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/FragmentingFlusher.java:56]: To be determined in https://github.com/jetty/jetty.project/issues/13290

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java (hunk 11 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java:158]: Currently if the `WebSocketDemander` is failed, we fail the callback from the `_callback` field, but the application might also have that callback which it can complete.

We cannot control this through the IteratingCallback because the application does not need to succeed the callback to get the next frame, they just call demand.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java (hunk 12 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: We can't succeed the callback parameter because we are not done with the frames payload, but if we have a non-null `failure` we need to fail it because it wasn't added to the state and so won't be failed later on.

I don't think we want to just fail the iterating callback. It is really a terminal failure so we want to ensure that the Demander is aborted. Looking at ICB.failed there are cases where it just turns into a NOOP, for example if it has already been completed.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java (hunk 13 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java:52]: I don't think there is a need for this.

And I don't see how this would work with the Flusher.process implementation.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java (hunk 15 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketFlusher.java:210]: Debug seems a bit light for this error.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java (hunk 12 above)
Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/WebSocketDemander.java]: Please add a comment to the call to `succeeded()`, something like:

```
// Succeed this IteratingCallback, since we are not done with the frame's payload.

**Review by sbordet — COMMENTED** [review]
LGTM, just the nit of adding a comment.
