### PR TITLE
H3: Fix racy read from stream-less channel

### LINKED ISSUE #9655: Flaky test in jetty-12 org.eclipse.jetty.test.client.transport.HttpClientLoadTest#testIterative
**Jetty version(s)**
12

**Description**

When building locally:
```
[ERROR] Failures: 
[ERROR]   HttpClientLoadTest.testIterative:98->run:176 [Result failed Result[HttpRequest[GET /20 HTTP/3.0]@2a159815 > HttpResponse[HTTP/3.0 200 null]@6f170333] java.util.concurrent.TimeoutException: idle timeout 30000 ms elapsed] ==> expected: <true> but was: <false>

```

### PR DESCRIPTION
**Pull request by lorban**
There is a race condition in the client when it is setting the stream, which happens _after_ a new request is created and its headers are sent onto the network. If the network and the server happen to be fast enough, the response could arrive at the client before the channel's stream has been set, making `HttpReceiverOverHTTP3` see a `null` stream.

The solution is to set the stream field before any data is sent onto the network, like HTTP/2 is doing.

Fixes https://github.com/eclipse/jetty.project/issues/9655 once merged to 12.

### CODE REVIEW

File: jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3SessionClient.java [hunk 1]
```diff
@@ -106,6 +106,7 @@ private CompletableFuture<Stream> newRequest(long streamId, HeadersFrame frame,
             return promise;
 
         stream.setListener(listener);
+        notifyNewStream(listener, stream);
```
Comment (sbordet) [inline jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3SessionClient.java]: I'd like this to be moved to `HTTP3StreamClient` via a new method `stream.onOpen()`, because `HTTP3StreamClient` has all the other `notifyXYZ()` methods.

File: jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3SessionClient.java [hunk 2]
```diff
@@ -127,6 +128,21 @@ private CompletableFuture<Stream> newRequest(long streamId, HeadersFrame frame,
         return promise;
     }
 
+    private void notifyNewStream(Stream.Client.Listener listener, HTTP3StreamClient stream)
```
Comment (sbordet) [inline jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3SessionClient.java]: Move it to `HTTP3StreamClient`.

File: jetty-http3/http3-http-client-transport/src/main/java/org/eclipse/jetty/http3/client/http/internal/HttpReceiverOverHTTP3.java [hunk 3]
```diff
@@ -59,9 +59,24 @@ protected void receive()
...
             responseSuccess(exchange);
+        }
         else
-            getHttpChannel().getStream().demand();
+        {
+            Stream stream = getHttpChannel().getStream();
+            if (LOG.isDebugEnabled())
+                LOG.debug("Demanding from {} in {}", stream, this);
+            if (stream == null)
+                return;
```
Comment (sbordet) [inline jetty-http3/http3-http-client-transport/src/main/java/org/eclipse/jetty/http3/client/http/internal/HttpReceiverOverHTTP3.java:71]: Ok for this additional check, but did you remove the similar check in `read(boolean)` that was in #9756?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3SessionClient.java (hunk 1 above)
Comment (lorban) [reply jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3SessionClient.java]: Done.

File: jetty-http3/http3-http-client-transport/src/main/java/org/eclipse/jetty/http3/client/http/internal/HttpReceiverOverHTTP3.java (hunk 3 above)
Comment (lorban) [reply jetty-http3/http3-http-client-transport/src/main/java/org/eclipse/jetty/http3/client/http/internal/HttpReceiverOverHTTP3.java:71]: Done.

File: jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3SessionClient.java (hunk 2 above)
Comment (lorban) [reply jetty-http3/http3-client/src/main/java/org/eclipse/jetty/http3/client/internal/HTTP3SessionClient.java]: Done.

File: jetty-http3/http3-http-client-transport/src/main/java/org/eclipse/jetty/http3/client/http/internal/HttpReceiverOverHTTP3.java (hunk 3 above)
Comment (lorban) [reply jetty-http3/http3-http-client-transport/src/main/java/org/eclipse/jetty/http3/client/http/internal/HttpReceiverOverHTTP3.java:71]: No, I did not. This change won't merge to 12 and my plan is to replace this change with the `if (stream == null) return Content.Chunk.from(new EOFException())` check.

**Review by sbordet — APPROVED** [review]
