### PR TITLE
Fixes #11763 - Race condition in QoSHandler.

### LINKED ISSUE #11763: Race condition in QoSHandler
**Jetty version(s)**
12.0.x

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
irrelevant

**OS type/version**
irrelevant

**Description**
QoSHandler contains a race between 'expire' (getServer().getScheduler()) and 'resume' threads (getServer().getThreadPool()) , which causes the "resume" thread to busy-loop until another request is suspended, i.e. added to one of the queues, which may never happen.
Consider the following serialization order (Jetty codestyle dropped for brevity):
```java
// 1. resume thread (QoSHandler.java#L291)
int permits = state.getAndIncrement();
if (permits >= 0)
    return;

// 2. expire thread (QoSHandler.java#L361)
boolean removed = queues.get(priority).remove(this);

// 3. resume thread (QoSHandler.java#L299) - now trapped in a busy loop
while (!resumeSuspended())
    Thread.onSpinWait();
```

**How to reproduce?**
This might be notoriously hard to reproduce on purpose, but one could reason about the issue without reproduction steps.

### PR DESCRIPTION
**Pull request by sbordet**
Now using a read-write lock to atomically execute expire(). 
This guarantees that there are no races with resume().

The concurrency between handle() and resume(), which should be the most common case, is handled by concurrent data structures.

### CODE REVIEW

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java [hunk 1]
```diff
@@ -185,31 +188,43 @@ public boolean onConditionsMet(Request request, Response response, Callback call
...
+        boolean expired = false;
+        lock.readLock().lock();
+        try
         {
-            return handleWithPermit(request, response, callback);
-        }
-        else
-        {
-            if (request.getAttribute(EXPIRED_ATTRIBUTE_NAME) != null)
+            int permits = state.decrementAndGet();
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java:203]: Mixing locks and atomics is pretty much an anti-pattern.  Would be good to just have an `int` here, but then you are modifying it within a read lock?

So at the very least, I'm confused by this code and it needs a lot more javadoc.  But ideally I'd like to see only a single synchronization mechanism, not two.

**Review by gregw — CHANGES_REQUESTED** [review]
I've found that if one synchronization mechanism doesn't prevent a race, then it is rarely fixed by adding yet another.     The use of read/write lock and an atomic is strange and a bit confusing.    I think I understand what it is doing, but at the very least it needs a lot more javadoc explaining the race and how this fixes it.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java:203]: > Mixing locks and atomics is pretty much an anti-pattern.

Why? We have concurrent readers so we need atomics.

If we go with a full lock, then it's going to be more contended.

Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java:203]: > Mixing locks and atomics is pretty much an anti-pattern.

Generally, yes. In this particular case, I think not. As a reminder, `ConcurrentPool` also mixes atomics and locks with a fast path/slow path pattern much like this proposed change.

**Review by lorban — APPROVED** [review]

**Review by gregw — APPROVED** [review]
