### PR TITLE
Issue #11851 export org.eclipse.jetty.ee8.websocket.javax.server

### LINKED ISSUE #11851: jetty-ee8-websocket-javax-server export not honoured
**Jetty version(s)**
12.0.9

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)

**OS type/version**
Win11

**Description**

Declared export package in Maven Bundle Plugin is not included in manifest:

<Export-Package>org.eclipse.jetty.websocket.javax.server.*;version="${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}"</Export-Package>

**How to reproduce?**
noop

### PR DESCRIPTION
**Pull request by janbartel**
Closes #11851

### CODE REVIEW

**Review by olamy — DISMISSED** [review]
I was looking at this and found some warning in the logs such 
```
[WARNING] Manifest org.eclipse.jetty.ee8.websocket:jetty-ee8-websocket-javax-server:jar:12.0.10-SNAPSHOT : Unused Export-Package instructions: [org.eclipse.jetty.websocket.javax.server.*] 
```
I was hoping yeah we could fail the build for such error but looks not even with this configuration 
```
          <failOnWarning>true</failOnWarning>
          <failOnError>true</failOnError>
```

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java [hunk 1]
```diff
@@ -833,7 +833,8 @@ public void testDump() throws Exception
         assertThat(count(dump, " - STARTED"), is(3));
         assertThat(dump, containsString(",3<=3<=4,i=1,r=2,"));
         assertThat(dump, containsString("[ReservedThreadExecutor@"));
-        assertThat(count(dump, "+> 0: ReservedThread@"), is(1));
+        // Flaky
+        //assertThat(count(dump, "+> 0: ReservedThread@"), is(1));
```
Comment (gregw) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java]: I would just delete rather than comment out.  This approach is always going to be flaky

**Review by gregw — DISMISSED** [review]
I prefer it be removed rather than commented out.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java (hunk 1 above)
Comment (olamy) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java]: deleted. cf55c3aa71f

**Review by olamy — APPROVED** [review]
