### PR TITLE
keep matching exception to found errorpage

### LINKED ISSUE #7777: Failing Test Jetty 11 - ServletContextHandlerTest.testAsyncServletRequestListenerListener
Jetty 11 build keep failing with this
```
java.lang.AssertionError: 

Expected: <2>
     but: was <9>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.servlet@11.0.9-SNAPSHOT/org.eclipse.jetty.servlet.ServletContextHandlerTest.testAsyncServletRequestListenerListener(ServletContextHandlerTest.java:1052)
```

https://jenkins.webtide.net/job/jetty.project/job/jetty-11.0.x/1026/testReport/

### LINKED ISSUE #7891: Better Servlet PathMappings for Regex
**Jetty version(s)**
 >= 10

**Description**

The path mappings for RegexPathSpec does not use groups for prefix matches to set `servletPath` and `pathInfo`.

### LINKED ISSUE #8211: Jetty-12 already complete exception
**Jetty version(s)**
jetty-12

**Java version/vendor** `(use: java -version)`

**OS type/version**

**Description**

When building with tests, the following exception is produced many times from many tests.  This should either not happen, or if it is normal (??) then the log should be stackless at least.

```
java.lang.IllegalStateException: already completed
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.lockedOnComplete(HttpChannelState.java:1422)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.failed(HttpChannelState.java:1367)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:666)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190)
	at org.eclipse.jetty.http2.internal.HTTP2Connection.produce(HTTP2Connection.java:209)
	at org.eclipse.jetty.http2.internal.HTTP2Connection.onFillable(HTTP2Connection.java:156)
	at org.eclipse.jetty.http2.internal.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:379)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### LINKED ISSUE #8442: Jetty 12 : `Handler.Collection` does not propagate `Server` to handlers in expected way
**Jetty version(s)**
Jetty 12

**Description**

In Jetty 12, if you use the jetty-core `org.eclipse.jetty.server.Handler$Collection` the `.setHandlers(List)` does not propagate the `Server` correctly.

Example code.

``` java
WebAppContext context = new WebAppContext();
context.setContextPath("/");
context.setBaseResource(context.getResourceFactory().newResource(staticBase));
server.setHandler(new Handler.Collection(context, new DefaultHandler()));
server.start();
```

The `DefaultHandler.setServer(Server)` never gets called with a valid Server instance.

This is because the internal `Handler.Collection` processing does it's `handler.setServer(server)` far too early.
AFAICT, this seems to be the only Handler implementation with this bug.

### LINKED ISSUE #8448: incomplete Blocking.Callback and write errors
**Jetty version(s)**
12

**Description**
```
2022-08-11 14:00:26.792:WARN :oeju.Blocker:qtp813656972-15: Blocking.Callback incomplete
2022-08-11 14:00:26.796:WARN :oeju.Blocker:qtp813656972-32: Blocking.Callback incomplete
2022-08-11 14:00:26.797:WARN :oeju.Blocker:qtp813656972-32: Blocking.Callback incomplete
2022-08-11 14:00:30.918:INFO :oejshC.ee10_demo_jetty:qtp813656972-15: resume request
2022-08-11 14:00:47.033:WARN :oeju.Blocker:qtp813656972-30: Blocking.Callback incomplete
2022-08-11 14:00:47.035:WARN :oeju.Blocker:qtp813656972-30: Blocking.Callback incomplete
2022-08-11 14:00:47.035:WARN :oejs.Response:qtp813656972-30: writeError: status=304, message=null, response=org.eclipse.jetty.ee10.servlet.DefaultServlet$ServletCoreResponse@2325be3a
2022-08-11 14:01:01.025:WARN :oeju.Blocker:qtp813656972-32: Blocking.Callback incomplete
2022-08-11 14:01:01.026:WARN :oeju.Blocker:qtp813656972-32: Blocking.Callback incomplete
2022-08-11 14:01:24.665:WARN :oeju.Blocker:qtp813656972-20: Blocking.Callback incomplete
2022-08-11 14:01:24.666:WARN :oeju.Blocker:qtp813656972-20: Blocking.Callback incomplete

```
**How to reproduce?**

Run the ee10 ws chat demo

### LINKED ISSUE #8723: Provide a thread-safe way to modify HttpClient proxies at runtime
**Jetty version(s)**
11.0.12

**Enhancement Description**
`HttpClient.getProxyConfiguration().getProxies()` is backed by a `ArrayList` which is not thread-safe.

Currently, I am forced to externally lock each time I make an HTTP request, or modifying proxies. I am making thousands of requests per second, which means that I need to acquire a lock thousands of times per second.

**Possible solutions**: 

1. Force users to externally-synchronize access.
2. Replace `ArrayList` by `LinkedBlockingQueue`.
3. Others???

### LINKED ISSUE #8726: Jetty 12 - Improve ErrorProcessor to handle error pages
**Jetty version(s)**
12+

**Description**
It would be nice if `ErrorProcessor` (or a subclass) can be configured with a mapping between the HTTP status code and an error page, something like:

```java
errorProcessor.addPage(404, "/404.html");
```

### LINKED ISSUE #8858: Jetty 12 - Review MovedContextHandler
**Jetty version(s)**
12+

**Description**
`MovedContextHandler` is not tested and it's currently broken.
Methods are still named after Servlets, but should be renamed to a more generic naming.

### LINKED ISSUE #8896: Flaky Test - org.eclipse.jetty.http2.tests.TrailersTest.testTrailersSentByServerShouldNotSendEmptyDataFrame
**Jetty version(s)**
Jetty 12

**Description**

_Stacktrace_

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:456)
	at org.eclipse.jetty.http2.tests.TrailersTest.testTrailersSentByServerShouldNotSendEmptyDataFrame(TrailersTest.java:301)
```

_Standard Error_
```
Running org.eclipse.jetty.http2.tests.TrailersTest.testTrailersSentByServerShouldNotSendEmptyDataFrame()
2022-11-14 19:26:21.747:INFO :oejs.Server:main: jetty-12.0.0-SNAPSHOT; built: 2022-11-14T19:10:45.095Z; git: f1822c9720f1f33e268717972ad0c0e9c19b1045; jvm 17.0.2+8
2022-11-14 19:26:21.748:INFO :oejs.AbstractConnector:main: Started ServerConnector@2f4fc18{h2c, (h2c)}{0.0.0.0:38433}
2022-11-14 19:26:21.748:INFO :oejs.Server:main: Started oejs.Server@6e612122{STARTING}[12.0.0-SNAPSHOT,sto=0] @184775ms
2022-11-14 19:26:21.754:INFO :oejs.Server:main: Stopped oejs.Server@6e612122{STOPPING}[12.0.0-SNAPSHOT,sto=0]
2022-11-14 19:26:21.754:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@2f4fc18{h2c, (h2c)}{0.0.0.0:0}
```

### LINKED ISSUE #8975: Jetty 12 - rename getBaseResponse() to getServletContextResponse()
**Jetty version(s)**
12+

**Description**
Rename `getBaseResponse()` to `getServletContextResponse()` as reported in #8938.

### LINKED ISSUE #8980: jetty-12.0.x WebappClassloader addJars(Resource) incorrectly transforms into a CombinedResource
**jetty-12.0.x**

The `WebAppClassloader.addJars(Resource)` method looks for all `jar` files inside the `Resource` (that is a directory), turning each of the `jar`s into a `String` and calling `addClassPath(String)`. That method is expecting either a single jar, or a comma separated list of jars.  There are 2 bugs in this method:

1. if even a single jar is passed as the argument, a `List<URI>` is produced and passed to the `ResourceFactory`, which turns it into a `CombinedResource`. It should be just a single `Resource`.
2. if multiple jars are passed as the argument, it is incorrect to transform them into a `CombinedResource`. They are simply a list of different jar `Resources`, they are _not_ a `CombinedResource` (which is a combination of resources, all of which are _directories_).

### LINKED ISSUE #9038: Jetty 12 - Review EE10 Http[Input|Output].Interceptor APIs
**Jetty version(s)**
12+

**Description**
`HttpInput.Interceptor` has the same signature as `ContentSourceTransformer`, and should have a similar contract.
Furthermore, the current implementation has a API contract that is not precise, so it is possible that an `Interceptor` implementation releases the input (raw) chunk (which goes back into the pool), but the `HttpInput` implementation still references it, causing race conditions.
It would be best if the API contract could be aligned with the one in `ContentSourceTransformer`.

Also, `HttpOutput.Interceptor` should be a sub-interface of `Content.Sink` as their `write()` methods have the same signature.

### PR DESCRIPTION
**Pull request by olamy**
fix TCK test `com.sun.ts.tests.servlet.spec.errorpage1.URLClient#servletExceptionTest`

### CODE REVIEW

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ErrorPageErrorHandler.java [hunk 1]
```diff
@@ -175,13 +175,16 @@ public String getErrorPage(HttpServletRequest request)
     /**
      *
      * @param t the initial exception
+     * @param matchedThrowable the class we found matching the error page (can be null)
      * @return the first non {@link ServletException} from root cause chain
      */
-    private Throwable getFirstNonServletException(Throwable t)
+    private Throwable getFirstNonServletException(Throwable t, Class<?> matchedThrowable)
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ErrorPageErrorHandler.java]: This name is not correct now.  How about:
```suggestion
    private Throwable unwrapServletException(Throwable t, Class<?> matchedThrowable)
```
```suggestion
    private Throwable getFirstNonServletException(Throwable t, Class<?> matchedThrowable)
```

**Review by gregw — APPROVED** [review]
Other than a name niggle OK

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ErrorPageErrorHandler.java (hunk 1 above)
Comment (olamy) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ErrorPageErrorHandler.java]: good idea!
done in 36438582c26a64e61a2c03325bb47f35b58b1a6d
