### PR TITLE
Issue #12070 fix session lastAccessedTime and isNew

### LINKED ISSUE #12070: HttpSession lastAccessedTime and isNew not getting updated
**Jetty version(s)**
12.0.11

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

**OS type/version**
Windows 10 and Windows 11

**Description**
In our environment the value of the `HttpSession.getLastAccessedTime()` is always identical to `HttpSession.getCreationTime()`. Also the value of `HttpSession.isNew()` returns always `true`.

The `getId()` and the `hashCode()` does not change between different HTTP request. This means the session cookie was send and received correctly. It was not a new session.

The requests are HTTP1/1 POST requests.

Attached is JettyServer Dump:
[jettydump.txt](https://github.com/user-attachments/files/16334501/jettydump.txt)

### PR DESCRIPTION
**Pull request by janbartel**
For ee8/9 the `HttpSession` was not being updated correctly upon receipt of a new request referencing an existing session. The `lastAccessedTime`, `isNew` and `expiryTime` fields were not being updated correctly after the introduction of cross-context dispatch in PR #11451.

### CODE REVIEW

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/SessionHandler.java [hunk 1]
```diff
@@ -520,7 +520,10 @@ public void doScope(String target, Request baseRequest, HttpServletRequest reque
                     coreRequest.setSessionManager(_sessionManager);
                     coreRequest.setRequestedSession(currentRequestedSession);
                     if (currentRequestedSession != null)
+                    {
                         coreRequest.setManagedSession(currentRequestedSession.session());
+                        currentSession = currentRequestedSession.session();
```
Comment (joakime) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/SessionHandler.java:525]: Simple fix. nice.

**Review by joakime — APPROVED** [review]
Looking good.
And the unit tests will help prevent regression in the future too.

Do we have the same issue on ee10 / ee11?

**Comment by janbartel** [comment]
> Looking good. And the unit tests will help prevent regression in the future too.
> 
> Do we have the same issue on ee10 / ee11?

Nope, it's implemented completely differently. In any case, I added an ee10 test for it, just in case ;)

**Review by gregw — APPROVED** [review]
