### PR TITLE
Issue #13624 use context classloader for resumed qos threads

### LINKED ISSUE #13624: ContextClassLoader changed on resumed requests with QoSHandler
**Jetty version(s)**
jetty-12.1.1 with dropwizard-5.0.0

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`

```
java version "17.0.16" 2025-07-15 LTS
Java(TM) SE Runtime Environment (build 17.0.16+12-LTS-247)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.16+12-LTS-247, mixed mode, sharing)
```

**OS type/version**

Oracle Linux 8 in a docker container

**Description**

When using the `QoSHandler` the context classloader is different on resumed requests. The different context classloader has two issues observed thus far. JNDI lookups start failing because the context classloader is different from the one in context when those bindings were made. Calls to `Thread.currentThread().getContextClassLoader().loadClass()` on the resumed request start failing. I copied QoSHandler into my project and added additional logging to print the context classloader during `process` and `resumeSuspended` to confirm the difference. 

What I'm unsure about is if this is intended behavior. Or if I need to call `Thread.currentThread().setContextClassLoader(ClassLoader.getSystemClassLoader())` to restore the context classloader once the request gets to a point where setting Thread level properties will persist.

```
2025-09-25T16:25:17,630Z DEBUG [dw-204] org.eclipse.jetty.server.handler.QoSHandler MyCustomQoSHandler@3fc2a1d1{STARTED} processing oeje10s.ServletContextRequest@2e5d2d4a{idj.ZipExceptionHandlingRequestWrapper@5699b1f{oejsh.GracefulHandler$ShutdownTrackingRequest@506e27ba{oejs.SecureRequestCustomizer$SecureRequestWithSslSessionData@129e3642{GET@556e6e26 https://<redacted> HTTP/1.1}}}} with context classloader MyCustomContextClassLoader@27c170f0

2025-09-25T16:25:17,630Z DEBUG [dw-204] org.eclipse.jetty.server.handler.QoSHandler MyCustomQoSHandler@3fc2a1d1{STARTED} suspending priority=0 oeje10s.ServletContextRequest@2e5d2d4a{idj.ZipExceptionHandlingRequestWrapper@5699b1f{oejsh.GracefulHandler$ShutdownTrackingRequest@506e27ba{oejs.SecureRequestCustomizer$SecureRequestWithSslSessionData@129e3642{GET@556e6e26 https://<redacted> HTTP/1.1}}}}

2025-09-25T16:25:19,122Z DEBUG [dw-213] org.eclipse.jetty.server.handler.QoSHandler MyCustomQoSHandler@3fc2a1d1{STARTED} resuming oeje10s.ServletContextRequest@2e5d2d4a{idj.ZipExceptionHandlingRequestWrapper@5699b1f{oejsh.GracefulHandler$ShutdownTrackingRequest@506e27ba{oejs.SecureRequestCustomizer$SecureRequestWithSslSessionData@129e3642{GET@556e6e26 https://<redacted> HTTP/1.1}}}} for context classloader jdk.internal.loader.ClassLoaders$AppClassLoader@7ad041f3

2025-09-25T16:25:19,122Z DEBUG [dw-213] org.eclipse.jetty.server.handler.QoSHandler MyCustomQoSHandler@3fc2a1d1{STARTED} forwarding oeje10s.ServletContextRequest@2e5d2d4a{idj.ZipExceptionHandlingRequestWrapper@5699b1f{oejsh.GracefulHandler$ShutdownTrackingRequest@506e27ba{oejs.SecureRequestCustomizer$SecureRequestWithSslSessionData@129e3642{GET@556e6e26 https://<redacted> HTTP/1.1}}}}
```

**How to reproduce?**

Run the process with a [custom ClassLoader](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/ClassLoader.html#getSystemClassLoader()) via `-Djava.system.class.loader=<FQCN>`. With this option the result of `Thread.currentThread().getContextClassLoader()` in the `main` method will be your custom ClassLoader. On non QoS resumed requests the context classloader is the same.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #13624

Ensure that  resumed requests in the `QoSHandler` uses the context's `execute` method so that the threads will use the context's classloader (if there is one).

### CODE REVIEW

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java [hunk 1]
```diff
@@ -452,7 +536,7 @@ public boolean handle(Request request, Response response, Callback callback)
             LocalConnector.LocalEndPoint endPoint = connector.executeRequest("""
                 GET /pass/%d HTTP/1.1
                 Host: localhost
-                
+
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java]: Remove these spaces, added in this PR.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java [hunk 2]
```diff
@@ -405,7 +405,7 @@ private boolean resumeSuspended()
 
     private void execute(Request request, Runnable task)
     {
-        request.getComponents().getExecutor().execute(task);
+        request.getContext().execute(task);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java:408]: This bypasses the use of the components for this request and fails the virtual thread test.

It should be:

`request.getComponents().getExecutor().execute(() -> request.getContext().run(task));`

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java [hunk 3]
```diff
@@ -83,6 +85,89 @@ public void testMaxRequests() throws Exception
         assertThat(qosHandler.getMaxRequestCount(), greaterThan(0));
     }
 
+    @Test
+    public void testInContext() throws Exception
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java]: Rename to `testRequestIsResumedInSameContextClassLoader()`

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java [hunk 4]
```diff
@@ -83,6 +85,89 @@ public void testMaxRequests() throws Exception
...
+    {
+        int maxRequests = 2;
+        ContextHandler context = new ContextHandler();
+        URLClassLoader contextClassLoader = new URLClassLoader(new URL[0], Thread.currentThread().getContextClassLoader());
+        context.setClassLoader(contextClassLoader);
+        context.setContextPath("/");
+        ContextHandlerCollection contexts = new ContextHandlerCollection(context);
+        Server server = new Server();
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java:97]: No need to allocate `Server` here, you can call `start()`, please have a look at e.g. `testRequestInVirtualThreadIsResumedInVirtualThread`, so you won't need the `finally` block either to stop the server.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java (hunk 4 above)
Comment (janbartel) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java:97]: The `start` method sets the `QoSHandler` as the handler on the `server`, but we need the `ContextHandlerCollection` to be the handler on the `server`.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java (hunk 1 above)
Comment (janbartel) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java]: I reformatted the file, using the standard code formatting rules and these spaces appeared, so they must be required by these formatting rules.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java [hunk 5]
```diff
@@ -83,6 +85,89 @@ public void testMaxRequests() throws Exception
...
+            await().atMost(5, TimeUnit.SECONDS).until(callbacks::size, is(1));
+
+            // Finish the resumed request that is now waiting.
+            callbacks.get(0).succeeded();
+
+            String text = endPoints.get(endPoints.size() - 1).getResponse(false, 5, TimeUnit.SECONDS);
+            HttpTester.Response response = HttpTester.parseResponse(text);
+            assertEquals(HttpStatus.OK_200, response.getStatus());
+        }
+       finally
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java]: Misaligned `finally`?

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/QoSHandlerTest.java]: I don't think the formatting rules specify these extra spaces that are unnecessary.

**Review by sbordet — COMMENTED** [review]
LGTM, but please fix the formatting.

**Review by sbordet — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java:408]: @sbordet I disagree.  Any setup for virtual threads or thread groups or anything else like that should be equally available via either request.getContext().execute(Runnable) or via the executor returned from the components.   If the context execute is bypassing anything that the virtual threads need, then that is a bug in the ScopedContext and ServerContext implementations and not this code.

**Review by gregw — CHANGES_REQUESTED** [review]
The context execute should handle virtual threads.

If you like, I'll make a commit to this branch to fix that.... unless @sbordet wants to do it to speed things up?

**Comment by mattnelson** [comment]
> The context execute should handle virtual threads.
> 
> If you like, I'll make a commit to this branch to fix that.... unless @sbordet wants to do it to speed things up?

One anecdotal data point. I tried both variants, they work for my non virtual flow.

```java
request.getComponents().getExecutor().execute(() -> request.getContext().run(task));
request.getContext().execute(task);
```

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/QoSHandler.java:408]: @sbordet Can you re-review with the changes so that the context executor always handles virtuals as well

**Review by gregw — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 6]
```diff
@@ -1671,7 +1672,7 @@ public void execute(Runnable runnable)
 
         public void execute(Runnable runnable, Request request)
         {
-            getServer().getContext().execute(() -> run(runnable, request));
+            VirtualThreads.asPossiblyVirtual(getServer().getThreadPool()).execute(() -> run(runnable, request));
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: Just `virtualThreads.execute()`.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/VirtualThreads.java [hunk 7]
```diff
@@ -35,6 +35,34 @@ public class VirtualThreads
...
+     * Get an executor that will use virtual threads if the given executor
+     * has been configured to use them.
+     * If the given executor does not implement {@link Configurable},
+     * or it has not been configured to use virtual threads, then the
+     * given executor is returned.
+     * @param executor The executor to use
+     * @return An executor that will use virtual threads if configured, otherwise the passed executor
+     * @see #getVirtualThreadsExecutor(Executor)
+     */
+    public static Executor asPossiblyVirtual(Executor executor)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/VirtualThreads.java]: I would just rename as `getExecutor(Executor)`, as the class prefix necessary to call this method is already hinting virtual threads.
This also pairs with the existing `VirtualThreads.getVirtualThreadExecutor()`.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/VirtualThreads.java [hunk 8]
```diff
@@ -35,6 +35,34 @@ public class VirtualThreads
...
+    {
+        Executor virtualExecutor = VirtualThreads.getVirtualThreadsExecutor(executor);
+        return virtualExecutor == null ? executor : virtualExecutor;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/VirtualThreads.java:51]: This same logic is also present in `AdaptiveExecutionStrategy.execute()`, so perhaps we can refactor there too?
I won't mind `AES.isUseVirtualThreads()` be implemented as `VirtualThreads.getVirtualThreadExecutor() != null` (the method is not used much, if at all), and remove `AES._virtualExecutor`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 9]
```diff
@@ -133,9 +133,9 @@ private enum SubStrategy
     private final LongAdder _epcMode = new LongAdder();
     private final LongAdder _epcProduce = new LongAdder();
     private final Producer _producer;
-    private final Executor _executor;
+    private final Executor _baseExecutor;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: "base" is confusing, not sure what it means?
I think like it was previously, we just want the original `Executor`, and the "virtual" `Executor`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java (hunk 9 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: It means the base executor from which the executor and tryExecutor are extracted. We must remember the original executor, as we cannot ask a virtual executor if it is a virtual executor.  I guess I could do it with a boolean...

**Review by sbordet — APPROVED** [review]
