### PR TITLE
Fix misc race conditions

### LINKED ISSUE #14732: possible race condition in jetty 12.x code
**Jetty version(s)**
Jetty 12.1 
**Jetty Environment**

**HTTP version**

**Java version/vendor** `(use: java -version)`

**OS type/version**
**Description**
Internal Google code scanner and tests have detected some race conditions in AppEngine code, that we are fixing. While doing the fixes other race conditions were seen in Jetty code. Google Gemini recommended these changes:

org.eclipse.jetty.io.SelectableChannelEndPoint: The race occurs because toEndPointString() reads _currentInterestOps and _desiredInterestOps concurrently with modifications in updateKey() and onSelected(). These variables must be read inside a locked block.

```
--- a/jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java
+++ b/jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java
@@ -324,11 +324,19 @@
     @Override
     public String toEndPointString()
     {
+        int currentInterestOps;
+        int desiredInterestOps;
+        try (AutoLock l = _lock.lock())
+        {
+            currentInterestOps = _currentInterestOps;
+            desiredInterestOps = _desiredInterestOps;
+        }
+
         // We do a best effort to print the right toString() and that's it.
         return String.format("%s{io=%d/%d,kio=%d,kro=%d}",
             super.toEndPointString(),
-            _currentInterestOps,
-            _desiredInterestOps,
+            currentInterestOps,
+            desiredInterestOps,
             ManagedSelector.safeInterestOps(_key),
             ManagedSelector.safeReadyOps(_key));
     }
```

org.eclipse.jetty.server.AbstractConnector: There are multiple data races related to the concurrent access to the _acceptors array elements from the shutdown thread (isShutdownDone()) while the Acceptor.run() worker loops modify them. Furthermore, primitive timeout configurations like _idleTimeout, _shutdownIdleTimeout, and _acceptorPriorityDelta are not volatile.

```
--- a/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java
+++ b/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java
@@ -153,13 +153,13 @@
     private final Set<EndPoint> _endpoints = Collections.newSetFromMap(new ConcurrentHashMap<>());
     private final Set<EndPoint> _immutableEndPoints = Collections.unmodifiableSet(_endpoints);
     private volatile Shutdown _shutdown;
-    private long _idleTimeout = 30000;
-    private long _shutdownIdleTimeout = 1000L;
+    private volatile long _idleTimeout = 30000;
+    private volatile long _shutdownIdleTimeout = 1000L;
     private String _defaultProtocol;
     private ConnectionFactory _defaultConnectionFactory;
     /* The name used to link up virtual host configuration to named connectors */
     private String _name;
-    private int _acceptorPriorityDelta = -2;
+    private volatile int _acceptorPriorityDelta = -2;
     private boolean _accepting = true;
     private ThreadPoolBudget.Lease _lease;
 
@@ -291,10 +291,13 @@
                 if (!_endpoints.isEmpty())
                     return false;
 
-                for (Thread a : _acceptors)
+                try (AutoLock lock = _lock.lock())
                 {
-                    if (a != null)
-                        return false;
+                    for (Thread a : _acceptors)
+                    {
+                        if (a != null)
+                            return false;
+                    }
                 }
 
                 return true;
```

Feel free to analyse and apply the fixes if you see they are valuable.

Similar  for Jetty9, but no need to look at.
**How to reproduce?**

### PR DESCRIPTION
**Pull request by lorban**
Fixes #14732

### CODE REVIEW

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java [hunk 1]
```diff
@@ -325,13 +325,17 @@ public void replaceKey(SelectionKey newKey)
...
+        try (AutoLock ignore = _lock.tryLock())
+        {
+            boolean locked = _lock.isHeldByCurrentThread();
+            // We do a best effort to print the right toString() and that's it.
+            return String.format("%s{io=%d/%d,kio=%d,kro=%d}",
+                super.toEndPointString(),
+                locked ? _currentInterestOps : -1,
+                locked ? _desiredInterestOps : -1,
+                locked ? ManagedSelector.safeInterestOps(_key) : -1,
+                locked ? ManagedSelector.safeReadyOps(_key) : -1);
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java]: I would report the values as before, with a prefix that indicates that the values may be stale, like we do in `HTTP2Flusher.toString()`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java [hunk 2]
```diff
@@ -244,6 +244,8 @@ public long getIdleTimeout()
      */
     public void setIdleTimeout(long idleTimeout)
     {
+        if (isStarted())
+            throw new IllegalStateException();
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java]: No, the idle timeout can be changed, for example by the low resource monitor, or `ConnectionLimit`, during shutdown, etc.
Please revert.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java [hunk 3]
```diff
@@ -254,6 +256,8 @@ public void setIdleTimeout(long idleTimeout)
      */
     public void setShutdownIdleTimeout(long idle)
     {
+        if (isStarted())
+            throw new IllegalStateException();
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java]: I'd also revert this.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java]: Done.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java]: Ok, reverted.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java]: Ok, reverted.

**Review by sbordet — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java [hunk 4]
```diff
@@ -580,9 +583,12 @@ public void setAcceptorPriorityDelta(int acceptorPriorityDelta)
         _acceptorPriorityDelta = acceptorPriorityDelta;
         if (old != acceptorPriorityDelta && isStarted())
         {
-            for (Thread thread : _acceptors)
+            try (AutoLock ignore = _lock.lock())
             {
-                thread.setPriority(Math.max(Thread.MIN_PRIORITY, Math.min(Thread.MAX_PRIORITY, thread.getPriority() - old + acceptorPriorityDelta)));
+                for (Thread thread : _acceptors)
+                {
+                    thread.setPriority(Math.max(Thread.MIN_PRIORITY, Math.min(Thread.MAX_PRIORITY, thread.getPriority() - old + acceptorPriorityDelta)));
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java]: Should we not check whether the thread is null here as well?

Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnector.java]: Good catch, we never call `setAcceptorPriorityDelta()` on a started `Connector` but nothing prevents that, so we could indeed encounter `null` threads.

**Review by sbordet — APPROVED** [review]
