### PR TITLE
Issue #4885 do not allow cookies to be set from an include

### LINKED ISSUE #4885: setCookie() must not change the headers in a response during an include
**9.4**

Servlet Spec 4.0 Section 9.3 The Include Method:

> It cannot set headers or call any method that affects the headers of the response, with
> the exception of the HttpServletRequest.getSession() and
> HttpServletRequest.getSession(boolean) methods. 

Whilst we handle the session correctly, the generic Response.addCookie() method is not protected.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #4885

According to the servlet spec section 9.3, an application cannot set a cookie on a response during an include.

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/Response.java [hunk 1]
```diff
@@ -280,27 +280,31 @@ else if (!cookie.getPath().equals(oldCookie.getPath()))
...
-            (long)cookie.getMaxAge(),
-            httpOnly,
-            cookie.getSecure(),
-            comment,
-            cookie.getVersion(),
-            sameSite));
+    { 
+        //Servlet Spec 9.3 Include method: cannot set a cookie if handling an include
+        if (isMutable())
+        {
```
Comment (joakime) [inline jetty-server/src/main/java/org/eclipse/jetty/server/Response.java:286]: So it silently fails if an attempt is made to addCookie during an INCLUDE?

Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/Response.java:286]: Can we at least log at debug level this behavior?

Such as ...

``` java
if (!isMutable())
{
    LOG.debug("Not able to add/set Cookie during INCLUDE dispatch: {}", cookie);
    return;
}

if (StringUtil.isBlank(cookie.getName()))
    throw new IllegalArgumentException("Cookie.name cannot be blank/null");

...
```

Comment (janbartel) [reply jetty-server/src/main/java/org/eclipse/jetty/server/Response.java:286]: Yep, that's what the spec wants us to do, ignore it. All of the other api methods that add headers do the same isMutable() test and ignore if an include.

Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/Response.java:286]: Yeah, typical strange spec behavior.
Can we (jetty) at least offer debug messages for those that are attempting to troubleshoot why their application isn't behaving like they expect?

Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/Response.java:286]: Don't worry about the debug thing on this PR.
I've opened issue #4916 to address this in a more consistent way.

**Review by joakime — APPROVED** [review]
I'm good with this PR as it sits currently.
