### PR TITLE
Issue #9906 Empty path info

### LINKED ISSUE #9906: Inconsistent handling of empty "path info" between Jetty 10 and 12
**Jetty version(s)**
12.0.0.beta1

**Java version/vendor** `(use: java -version)`
```
$ java -version
java version "11.0.19" 2023-04-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.19+9-LTS-224, mixed mode)
```

**OS type/version**
```
$ uname -srv
Linux 6.3.6-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jun  5 15:45:04 UTC 2023
```

**Description**
When trying to use ServletContextHandler with default servlet only, there's different behavior between Jetty 10 and 12.

**How to reproduce?**
I'm working on Pax Web (OSGi CMPN implementation of web related specification based on Jetty, Tomcat and Undertow). When trying to move to `jakarta` namespace (JakartaEE 10 / Servlet API 6), I now check if everything works consistently.

One of the "showcase tests" (where I try to provide canonical _embedded_ examples) is (Jetty 10): https://github.com/ops4j/org.ops4j.pax.web/blob/web-9.0.9/pax-web-jetty/src/test/java/org/ops4j/pax/web/service/jetty/internal/EmbeddedJettyTest.java#L356-L443

Roughly speaking there's:
* org.eclipse.jetty.server.Server + org.eclipse.jetty.server.ServerConnector
* org.eclipse.jetty.server.handler.ContextHandlerCollection set as Server's handler
* two org.eclipse.jetty.ee10.servlet.ServletContextHandler instances added as `/c1` and `/c2` to the above chc
* the ServletContextHandler has been configured with `ServletContextHandler#setAllowNullPathInfo(true)` and `ContextHandler#setAllowNullPathInContext(true)`
* each ServletContextHandler has one ServletHolder with default servlet mapped to `/`
* I call `GET /c1` and `GET /c2`

In Jetty 10.0.15, I'm at this stage:
```
"qtp1336777650-22@2859" prio=5 tid=0x16 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1282)
	  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
	  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	  at org.eclipse.jetty.server.Server.handle(Server.java:563)
	  at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	  at org.eclipse.jetty.server.HttpChannel$$Lambda$192.1150165308.dispatch(Unknown Source:-1)
	  at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	  at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	  at java.lang.Thread.run(Thread.java:834)
```
`target` parameter is `/c1` and this branch is invoked:
```java
else
{
    target = URIUtil.SLASH;
    pathInContext = null;
}
```

Then in `org.eclipse.jetty.servlet.ServletHandler#getMatchedServlet()` target is `/` and proper mapping is taken using:
```java
if (target.startsWith("/"))
{
    if (_servletPathMap == null)
        return null;
    return _servletPathMap.getMatched(target);
}
```

However in Jetty 12.0.0.beta1, there's different code being called here:
```
"qtp366803687-22@3399" prio=5 tid=0x16 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.eclipse.jetty.server.Context.getPathInContext(Context.java:129)
	  at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.getPathInContext(ContextHandler.java:1313)
	  at org.eclipse.jetty.ee10.servlet.ServletContextHandler.wrapRequest(ServletContextHandler.java:1146)
	  at org.eclipse.jetty.ee10.servlet.ServletContextHandler.wrapRequest(ServletContextHandler.java:123)
	  at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:805)
	  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:179)
	  at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:611)
	  at org.eclipse.jetty.server.Server.handle(Server.java:175)
	  at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:553)
	  at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:480)
	  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	  at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	  at java.lang.Thread.run(Thread.java:833)
```

and it's this branch (`encodedContextPath` == `encodedPath` == `/c1`):
```java
if (encodedPath.length() == encodedContextPath.length())
    return "";
```

this time `org.eclipse.jetty.ee10.servlet.ServletHandler#getMatchedServlet()` is being passed `""` value and while `_servletPathMap` is correct:
```
_servletPathMap = {org.eclipse.jetty.http.pathmap.PathMappings@4295}  size = 1
 {org.eclipse.jetty.http.pathmap.ServletPathSpec@4466} "ServletPathSpec@9457dcb7{DEFAULT,/}" -> {org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet@4467} "MappedServlet6faad6a5{/->default-servlet==org.ops4j.pax.web.service.jetty.internal.EmbeddedJettyTest$5@2c16bab9{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:<null>,STARTED}}"
  key: org.eclipse.jetty.http.pathmap.ServletPathSpec  = {org.eclipse.jetty.http.pathmap.ServletPathSpec@4466} "ServletPathSpec@9457dcb7{DEFAULT,/}"
  value: org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet  = {org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet@4467} "MappedServlet6faad6a5{/->default-servlet==org.ops4j.pax.web.service.jetty.internal.EmbeddedJettyTest$5@2c16bab9{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:<null>,STARTED}}"
```

this fragment is used instead:
```java
MappedServlet holder = _servletNameMap.get(target);
```

and `null` is returned.

I know that Jetty 12 is still being worked on, but I hope you don't mind reporting such differences ;)

### PR DESCRIPTION
**Pull request by janbartel**
Closes #9906 

When using `ContextHandler.setAllowNullPathInfo(true)` a URL like `/ctx` is not redirected to `/ctx/`. In older versions of jetty, the resulting path in context of `""` is forced to be `/` and is thus sent on to whatever servlet matches that (usually the default servlet). In jetty-12 we do not fake the path to be `/` and we were returning a `404`.  

This PR allows the path in context of `""` to match the _same_ servlet as does a path in context of `/`. 

However, unlike previous versions of jetty, we do _not_ force the path in context to be `/`, the path in context will continue to be `""`.  To do the forcing would impose extra processing on the critical path of handling a request that isn't justified by this edge-case. If skipping the redirect of `/ctx` to `/ctx/` is desired _and_ the application wants the path in context to be `/`, then the `RewriteHandler` can be used to rewrite `/ctx` to `/ctx/` before the request hits the `ServletContextHandler`.

### CODE REVIEW

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletContextHandlerTest.java [hunk 1]
```diff
@@ -2432,4 +2432,35 @@ protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws Se
...
+        String rawRequest = """
+            GET /c1 HTTP/1.1\r
+            Host: localhost\r
+            Connection: close\r
+            \r
+            """;
+
+        String rawResponse = _connector.getResponse(rawRequest);
+        HttpTester.Response response = HttpTester.parseResponse(rawResponse);
+        assertThat(response.getContent(), containsString("OK"));
```
Comment (olamy) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletContextHandlerTest.java]:
```suggestion
        assertThat(response.getContent(), containsString("OK2"));
```

shouldn't we test "OK2" as this is what the servlet writes?

File: jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ServletContextHandlerTest.java [hunk 2]
```diff
@@ -2272,4 +2272,35 @@ public void init() throws ServletException
...
+        String rawRequest = """
+            GET /c1 HTTP/1.1\r
+            Host: localhost\r
+            Connection: close\r
+            \r
+            """;
+
+        String rawResponse = _connector.getResponse(rawRequest);
+        HttpTester.Response response = HttpTester.parseResponse(rawResponse);
+        assertThat(response.getContent(), containsString("OK"));
```
Comment (olamy) [inline jetty-ee9/jetty-ee9-servlet/src/test/java/org/eclipse/jetty/ee9/servlet/ServletContextHandlerTest.java]:
```suggestion
        assertThat(response.getContent(), containsString("OK2"));
```

**Review by olamy — CHANGES_REQUESTED** [review]
LGTM except minor change
