### PR TITLE
Fixes #12249 - HTTP/2 responses with Content-Length may have no content.

### LINKED ISSUE #12249: HTTP/2 responses with Content-Length may have no content
**Jetty version(s)**
12

**Description**
Since #10655, a RST_STREAM frame may drain unread DATA frames in `HTTP2Stream`.

It is possible that the server sends a good response with content, but fails to fully read the request content, and this results in a RST_STREAM to be sent to the client.

The client may see the response headers, possibly indicating a `Content-Length` header with a positive value, but may decide to read the response content later.
This results in the DATA frames to be queued in the stream, but then the RST_STREAM drains them.

There is a small window between draining the DATA frames and notifying the upper layer that a RST_STREAM was received.

If an application tries to read during that small window, it reads an EOF chunk, rather than a failure chunk, and it may think the response was successful and had no content, even if the `Content-Length` header indicated that there was content.

This is the reason for the flakyness reported by #11960.

### PR DESCRIPTION
**Pull request by sbordet**
Fixed HttpReceiverOverHTTP2.read() to return a failed chunk if the stream has been reset.

This closes the window where a RST_STREAM frame may be received, drain the DATA frames in HTTP2Stream, and the application reading exactly at that point.

### CODE REVIEW

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java [hunk 1]
```diff
@@ -826,6 +827,55 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+        Thread.sleep(1000);
+
+        // Verify that the chunk read at the request failure event is a failure chunk.
+        Content.Chunk chunk = chunkRef.get();
+        assertNotNull(chunk);
+        assertNotNull(chunk.getFailure());
+        // Reading more also yields a failure chunk.
+        chunk = contentSourceRef.get().read();
+        assertNotNull(chunk);
+        assertNotNull(chunk.getFailure());
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java]: Use `assertTrue(Chunk.isFailure(chunk, true))` instead to make sure the failure is last.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java [hunk 2]
```diff
@@ -826,6 +827,55 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+            .method(HttpMethod.POST)
+            .body(new AsyncRequestContent(ByteBuffer.allocate(1024)))
+            .onResponseContentSource((response, contentSource) -> contentSourceRef.set(contentSource))
+            // The request is failed before the response, verify that
+            // reading at the request failure event yields a failure chunk.
+            .onRequestFailure((request, failure) -> chunkRef.set(contentSourceRef.get().read()))
+            .send(resultRef::set);
+
+        // Wait for the RST_STREAM to arrive and drain the response content.
+        Thread.sleep(1000);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java]: Each time we use a `sleep()` in a test, a kitten dies. Is there nothing we can rely upon to assert that the stream has been reset?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java]: Done.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/HttpClientTransportOverHTTP2Test.java]: Done.

**Review by lorban — APPROVED** [review]
