### PR TITLE
Jetty 12.0.x 10582 servlethttpwrapper

### LINKED ISSUE #10582: NPE when including a directory that should be resolved with servlet-mapped welcome file
**Jetty version(s)**
12.0.2-SNAPSHOT

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
```
$ java -version
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)
```

**OS type/version**
```
$ uname -srv
Linux 6.4.15-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep  7 00:25:01 UTC 2023
```

**Description**
See https://github.com/grgrzybek/jetty.project/commit/53f7a6eaf7dd05a3edf0fede0490b3caf7b83d34 for reproducer.

When doing `dispatcher.include()` for a resource which is a directory and with welcome files configured, I'm getting this NPE:
```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "method" is null
	at jakarta.servlet@6.0.0/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:522)
	at jakarta.servlet@6.0.0/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1609)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1542)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.Dispatcher.include(Dispatcher.java:152)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.DispatcherTest$DispatchServletServlet.doGet(DispatcherTest.java:1186)
	at jakarta.servlet@6.0.0/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at jakarta.servlet@6.0.0/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1609)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1542)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:886)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:491)
	at org.eclipse.jetty.ee10.servlet/org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:812)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:177)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:713)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.Server.handle(Server.java:176)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:649)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:471)
	at org.eclipse.jetty.io/org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io/org.eclipse.jetty.io.ByteArrayEndPoint.lambda$new$0(ByteArrayEndPoint.java:58)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It's a bit of follow up of #10558, my work on Pax Web 10 (with Jetty 12, Tomcat 10.1 and Undertow 2.3 progresses) and while I've finally managed to unify this _path info only_ behavior, this is the problem I got in Jetty.

In my adjusted Pax Web tests, included directory which should be resolved by processing welcome files is empty because of how DefaultServlet handles include dispatch:
```java
// Check whether a Servlet may serve the welcome resource.
if (_welcomeServletMode != WelcomeServletMode.NONE && welcomeTarget == null)
{
    if (!isDefaultMapping(getServletRequest(coreRequest)) && !isIncluded(getServletRequest(coreRequest)))
        welcomeTarget = URIUtil.addPaths(getServletRequest(coreRequest).getPathInfo(), welcome);
    ServletHandler.MappedServlet entry = _servletContextHandler.getServletHandler().getMappedServlet(welcomeInContext);
    // Is there a different Servlet that may serve the welcome resource?
    if (entry != null && entry.getServletHolder().getServletInstance() != DefaultServlet.this)
    {
        if (_welcomeServletMode == WelcomeServletMode.MATCH || entry.getPathSpec().getDeclaration().equals(welcomeInContext))
        {
            welcomeTarget = welcomeInContext;
            // Do not break the loop, because we want to try other welcome resources
            // that may be files and take precedence over Servlet welcome resources.
        }
    }
}
```

I didn't change it and while in Pax Web I'm not getting welcome file resolved, in Jetty tests I have NPE.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #10582

### CODE REVIEW

**Review by gregw — CHANGES_REQUESTED** [review]
We now need a specific test to check that we can handle non HTTP Servlet wrappers for request and response.

P.S. we can probably squeak this into 12.0.2 if it is ready soon

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletWrapperTest.java [hunk 1]
```diff
@@ -99,7 +121,27 @@ protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws Se
...
+    }
+
+    public static class ServletRequestHttpWrapperFilter implements Filter
+    {
+        @Override
+        public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException
+        {
+            HttpServletRequest wrappedRequest = new ServletRequestHttpWrapper(request);
+            HttpServletResponse wrappedResponse = new ServletResponseHttpWrapper(response);
+            chain.doFilter(wrappedRequest, wrappedResponse);
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/ServletWrapperTest.java]: I want to see:
```suggestion
            chain.doFilter(new ServletRequestWrapper(request), new ServletResponseWrapper(response));
```

**Review by gregw — CHANGES_REQUESTED** [review]

**Review by gregw — APPROVED** [review]
