### PR TITLE
Fix StatisticsHandler not receiving implicit status 200

### LINKED ISSUE #11482: The StatisticsHandler doesn't count 2xx codes
**Jetty version(s)**
12.0.6

**Jetty Environment**
ee10

**Java version/vendor** 
18.0.2

**OS type/version**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.04
DISTRIB_CODENAME=lunar

**Description**
Hello friends!!!
When I use `StatisticsHandler` in Jetty 12, I come across the fact that `2xx` codes are not counted, that is, the counter is always 0.

For example, I have a rest controller in a simple spring-boot project. And when my controller writes json in a response, `StatisticsHandler` does not count this event as `2xx`. 
When I looked closely at the `StatisticsHandler`, I saw that the response codes are calculated in the `onResponseBegin` method. This method is called in the `notifyOnResponseBegin` method of the parent `EventsHandler` class. `notifyOnResponseBegin` is called in two places:
```
    @Override
    public boolean handle(Request request, Response response, Callback callback) throws Exception
    {
         ...
         Request.addCompletionListener(request, x ->
         {
             notifyOnResponseBegin(roRequest, wrappedResponse);
             ...
         });
        ...
    }
```
```
private class EventsResponse extends Response.Wrapper
    {
        ...
        @Override
        public void write(boolean last, ByteBuffer byteBuffer, Callback callback)
        {
            notifyOnResponseBegin(getRequest(), this);
            ...
        }
        ...
    }
```
When the rest controller writes the response body, the `write` method is called first and the `listener` is called at the end. But when the `write` method is called, the response status is 0, and when the `listener` is called, the response status is 200, but it is ignored.

**How to reproduce?**
[Here](https://github.com/AlekseyMishanin/jetty-statistics-handler) is a project that can help you reproduce the problem. This project shows that `StatisticsHandler` counts 4xx/5xx codes, but not 2xx

### PR DESCRIPTION
**Pull request by lorban**
Fixes #11482

### CODE REVIEW

**Review by sbordet — CHANGES_REQUESTED** [review]
@lorban I would restore the code as it was, and compute the response status code later, after the response is committed.

I would also add a test case where an application changes the status code from the `EventHandler`'s event that is the last chance to modify the response, and see if it is counted correctly.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java [hunk 1]
```diff
@@ -179,11 +179,11 @@ private void notifyOnResponseTrailersComplete(Request request, EventsResponse re
         }
     }
 
-    private void notifyOnComplete(Request request, Throwable failure)
+    private void notifyOnComplete(Request request, EventsResponse response, Throwable failure)
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java]: I'd use just `Response` in the signature.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java [hunk 2]
```diff
@@ -309,11 +309,30 @@ protected void onResponseTrailersComplete(Request request, HttpFields trailers)
      *
      * @param request the request object. The {@code read()}, {@code demand(Runnable)} and {@code fail(Throwable)} methods must not be called by the listener.
      * @param failure if there was a failure to complete
+     * @deprecated Override {@link #onComplete(Request, int, HttpFields, Throwable)} instead.
      */
+    @Deprecated
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java:314]: Now that this method is deprecated, please update the documentation as well, namely `HTTPServerDocs.eventsHandler()`.
Also look at the `*.adoc` text referring to that example, to see if it can be expanded to talk about the new parameters.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java]: Done.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/EventsHandler.java:314]: Done. There wasn't much to change in the documentation, everything seems to still be accurate in the adoc files, only `HTTPServerDocs.eventsHandler()` needed some modifications.

**Review by sbordet — APPROVED** [review]
