### PR TITLE
Issue #13465 - ensure that WebSocketClient onHandshakeResponse is not called twice

### LINKED ISSUE #13465: Review invocation of `UpgradeListener.onHandshakeResponse()` in case of failures
**Jetty version(s)**
12.1.x

**Description**
WebSocket's core client `UpgradeListener.onHandshakeResponse()` is invoked from `CoreClientUpgradeRequest.upgrade()`, which sets the `upgraded` field, but also from `CoreClientUpgradeRequest.onComplete()` that reads the `upgraded` field.

I think it is possible that `CoreClientUpgradeRequest.upgrade()` calls `UpgradeListener.onHandshakeResponse()` which may throw, and eventually `CoreClientUpgradeRequest.onComplete()` might be called and call `UpgradeListener.onHandshakeResponse()` again.

We need to write a test case that throws from `UpgradeListener.onHandshakeResponse()` and verify what happens.

### LINKED ISSUE #13466: Lost WebSocket upgrade failure
**Jetty version(s)**
12.1.x

**Description**
If a WebSocket upgrade receives a response with a status code, but also the client exchange is failed, then the exchange failure is lost and only an `UpgradeException` is reported.

This logic is in `CoreClientUpgradeRequest.onComplete(Result)` and should be reviewed so that the exchange exception, if any, is not lost.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #13465

### CODE REVIEW

File: jetty-core/jetty-websocket/jetty-websocket-core-client/src/main/java/org/eclipse/jetty/websocket/core/client/CoreClientUpgradeRequest.java [hunk 1]
```diff
@@ -261,14 +263,21 @@ public void onComplete(Result result)
...
+                {
+                    if (LOG.isDebugEnabled())
+                        LOG.debug("Failure while notifying handshake response listeners", listenerError);
+                }
             }
-            handleException(new UpgradeException(requestURI, status,
-                "Failed to upgrade to websocket: Unexpected HTTP Response Status Code: " + responseLine));
+
+            if (result.getFailure() != null)
+                handleException(new UpgradeException(requestURI, status, result.getFailure().getMessage()));
```
Comment (lachlan-roberts) [inline jetty-core/jetty-websocket/jetty-websocket-core-client/src/main/java/org/eclipse/jetty/websocket/core/client/CoreClientUpgradeRequest.java:277]: I think this also fixes https://github.com/jetty/jetty.project/issues/13466

Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-client/src/main/java/org/eclipse/jetty/websocket/core/client/CoreClientUpgradeRequest.java:277]: This change seems to be resulting in a lot of flakiness in the HTTP/2 WebSocket tests. 

> "Unexpected HTTP Response Status Code: 500" ignoring case
     but: was "org.eclipse.jetty.websocket.core.exception.UpgradeException: Stream has been reset"

**Review by sbordet — CHANGES_REQUESTED** [review]
@lachlan-roberts yes it should also fix #13466.

The fix should be less flaky, so the test failures should be investigated.

**Comment by lachlan-roberts** [comment]
@sbordet I have investigated the failures.

In the test the client is trying to upgrade to websocket over HTTP/2 and the server is throwing an exception in the websocket creator.

When the client sends the headers frame to upgrade it does not include an END_STREAM flag because the subsequent data frames it sends will be websocket bytes.

The server sees the exception and tries to send a 500 response, it sends a HEADERS frame with the END_STREAM flag.
But the server sees that the client has not sent an END_STREAM flag so it resets the stream.

The client then has a race whether it processes the HEADERS frame with the 500 response, or the RST_STREAM frame first.

**Comment by sbordet** [comment]
@lachlan-roberts I fixed the tests, please review the fix.

The build failed due to #13533, so I think this PR is fine now.

**Comment by lachlan-roberts** [comment]
@sbordet it seems after merging with `12.1.x` it still has the same failures.
CI shows the `Stream has been reset` failure is still there in `WebSocketOverHTTP2Test`.

**Review by sbordet — APPROVED** [review]
