### PR TITLE
Issue #12695 - don't return ByteBuffer from .toMappedBuffer if FS reports as UnsupportedOperationException.

### LINKED ISSUE #12695: 12.1.0 - ResourceHandler is unable to serve content from PathResource that doesn't support mapped file buffers.
**Jetty version(s)**
12.1.0.alpha1

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
```
openjdk 17.0.11 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)
```

**OS type/version**
Linux / Ubuntu

**Description**
If you have a Resource Base that is a PathResource that points to a FS that doesn't support file mapping, like zipfs, then you are unable to serve files from ResourceHandler.

This works in 12.0.16 just fine.

```
2025-01-09 13:43:22.809:WARN :oejs.Response:qtp2008106788-169: writeError: status=500, message=java.lang.UnsupportedOperationException, response=ErrorResponse@1e15b2b8{500,GET@2e2db70a http://192.168.1.221:40715/jars/webjars/bootstrap/5.3.3/js/bootstrap.bundle.js HTTP/1.1}
java.lang.UnsupportedOperationException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$1.map(ZipFileSystem.java:1102)
	at org.eclipse.jetty.util.BufferUtil.toMappedBuffer(BufferUtil.java:1178)
	at org.eclipse.jetty.util.BufferUtil.toMappedBuffer(BufferUtil.java:1171)
	at org.eclipse.jetty.http.content.FileMappingHttpContentFactory$SingleBufferFileMappedHttpContent.<init>(FileMappingHttpContentFactory.java:103)
	at org.eclipse.jetty.http.content.FileMappingHttpContentFactory.getContent(FileMappingHttpContentFactory.java:78)
	at org.eclipse.jetty.http.content.VirtualHttpContentFactory.getContent(VirtualHttpContentFactory.java:60)
	at org.eclipse.jetty.http.content.PreCompressedHttpContentFactory.getContent(PreCompressedHttpContentFactory.java:48)
	at org.eclipse.jetty.http.content.CachingHttpContentFactory.getContent(CachingHttpContentFactory.java:229)
	at org.eclipse.jetty.server.ResourceService.getContent(ResourceService.java:88)
	at org.eclipse.jetty.server.handler.ResourceHandler.handle(ResourceHandler.java:174)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740)
	at examples.PathMappingServer$PathNameWrapper.handle(PathMappingServer.java:177)
	at org.eclipse.jetty.server.handler.PathMappingsHandler.handle(PathMappingsHandler.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:672)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:411)
	at org.eclipse.jetty.server.internal.HttpConnection$FillableCallback.succeeded(HttpConnection.java:1688)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

I think the `toMappedBuffer` should catch `UnsupportedOperationException` and fallback to non-mapped option.

### PR DESCRIPTION
**Pull request by joakime**
To fix issue with UnsupportedOperationException, just have toMappedBuffer return null (that is an existing contract) if that exception is triggered.

### CODE REVIEW

**Comment by joakime** [comment]
This is an incomplete fix, as the usages of `toMappedBuffer` in `org.eclipse.jetty.http.content.FileMappingHttpContentFactory` incorrectly assume that they will always get a mapped ByteBuffer.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpTester.java [hunk 1]
```diff
@@ -262,17 +262,25 @@ public static Response parseResponse(Input input) throws IOException
         return parseResponse(input, false);
     }
 
+    public static Response parseResponse(Input input, Response response) throws IOException
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpTester.java:265]: While restoring `FileBufferedResponseHandlerTest` (from earlier versions of Jetty) this method in `HttpTester` was also restored.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java [hunk 2]
```diff
@@ -205,9 +206,9 @@ protected Action process() throws Exception
                     if (_last)
                         return Action.SUCCEEDED;
 
-                    long len = Math.min(MAX_MAPPED_BUFFER_SIZE, fileLength - _pos);
+                    long len = Math.min(MAX_BUFFER_SIZE, fileLength - _pos);
                     _last = (_pos + len == fileLength);
-                    ByteBuffer buffer = BufferUtil.toMappedBuffer(_filePath, _pos, len);
+                    ByteBuffer buffer = readByteBuffer(_filePath, _pos, len);
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: `readByteBuffer()` could allocate a 1 GB buffer, each time a file is served! Yikes!

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java [hunk 3]
```diff
@@ -229,5 +230,23 @@ protected void onFailure(Throwable cause)
...
+            ByteBuffer buffer = BufferUtil.toMappedBuffer(path, pos, len);
+            if (buffer != null)
+                return buffer;
+
+            // if we reached here, then file mapped byte buffers is not supported.
+            // we fall back to using traditional I/O instead.
+            try (SeekableByteChannel channel = Files.newByteChannel(path))
+            {
+                channel.position(pos);
+                buffer = ByteBuffer.allocate((int)len);
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: Please use direct byte buffers by default.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java [hunk 4]
```diff
@@ -229,5 +230,23 @@ protected void onFailure(Throwable cause)
...
+                channel.read(buffer);
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: IIRC `channel.read()` does not guarantee that the buffer will be filled as this API is non-blocking. You are going to either spin loop or use some form of blocking API instead.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 2 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: If you have 1 GB of generated response body, then yup, and that's what the javadoc at the top of this handler warns about.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 4 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: I don't see that as a problem, we read what we can and return, even if the buffer isn't full, the iterating calback that calls this method will just get a new position to read from, right?

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 2 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: Addressed this with the new internal `SendFileCallback` class, along with bufferSize configurable (defaults to 64kb)

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 3 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: Addressed this with the new internal `SendFileCallback` class

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 4 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: The new `FileBufferedResponseHandler.setUseFileMapping(boolean)` allows me to test these new features in unit tests too.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java [hunk 5]
```diff
@@ -193,41 +215,154 @@ private void commit(Callback callback)
...
+        private final FileBufferedInterceptor _interceptor;
+        private final Callback _callback;
+        private final int _bufferSize;
+        private long _pos = 0;
+        private boolean _last = false;
+        private Mode _mode = Mode.DISCOVER;
+
+        enum Mode
+        {
+            DISCOVER,
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: `AUTO` sounds better than `DISCOVER` to me as it implies that some logic is going to automatically choose between the other two.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java [hunk 6]
```diff
@@ -193,41 +215,154 @@ private void commit(Callback callback)
...
+                // attempt to read past end of file, consider this an EOF
+                return null;
+            }
+            ByteBuffer buffer = BufferUtil.toMappedBuffer(path, pos, len);
+            if (buffer != null)
+                _mode = Mode.MAPPED;
+            return buffer;
+        }
+
+        private ByteBuffer toRead(Path path, long pos) throws IOException
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: This method allocates a 64 KB direct buffer, opens and closes a file for each 64 KB chunk of data in the file, which is going to be way too costly.

The buffer should be allocated at most once and the file should be opened and closed at most once.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java [hunk 7]
```diff
@@ -193,41 +215,154 @@ private void commit(Callback callback)
...
             {
-                private final long fileLength = _filePath.toFile().length();
-                private long _pos = 0;
-                private boolean _last = false;
+                callback.failed(e);
+            }
+        }
+    }
+
+    // TODO: can this be made generic enough to put into jetty-io somewhere?
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: To answer your comment: I don't think so. We do 99% of our IO's using `Content.Source` and `Content.Sink` for which we already have `Content.copy()`.

**Review by lorban — CHANGES_REQUESTED** [review]
I'm wondering if this whole implementation could be replaced with a simple `Content.copy()`?

Writing a `Content.Sink` that does `_interceptor.getNextInterceptor().write(buffer, last, callback)` looks trivial; so if a memory-mapping `Content.Source` could be created, with a fallback to `Content.Source.from(Path)` if mmap is disabled or unavailable could be written then the whole `Content` logic could be re-used.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 4 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: No longer relevant.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 3 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: No longer relevant.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 2 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: No longer relevant.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 5 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: No longer relevant, using `Content.copy()` now

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 6 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: No longer relevant, using `Content.copy()` now

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 7 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: Implemented `Content.copy()` technique instead.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java [hunk 8]
```diff
@@ -122,6 +122,21 @@ class Sized extends Wrapper
...
 
+        /**
+         * Get a sized pool for any arbitrary ByteBufferPool.
+         *
+         * @param pool the pool
+         * @param direct {@code true} for direct buffers (if wrapping pool)
+         * @param size The specified size in bytes of the buffer, or -1 for a default
+         * @return the pool as a sized pool
+         */
+        public static ByteBufferPool.Sized as(ByteBufferPool pool, boolean direct, int size)
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java]: I don't think I like this new helper as it takes parameters that could be ignored without any hint.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java [hunk 9]
```diff
@@ -193,41 +204,27 @@ private void commit(Callback callback)
             }
 
             // Create an iterating callback to do the writing
-            IteratingCallback icb = new IteratingCallback()
-            {
-                private final long fileLength = _filePath.toFile().length();
-                private long _pos = 0;
-                private boolean _last = false;
+            ByteBufferPool.Sized sizedPool = ByteBufferPool.Sized.as(getServer().getByteBufferPool(), true, getBufferSize());
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: I think I'd rather see a new instance of `ByteBufferPool.Sized` being created.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java [hunk 10]
```diff
@@ -193,41 +204,27 @@ private void commit(Callback callback)
...
-                        return Action.SUCCEEDED;
-
-                    long len = Math.min(MAX_MAPPED_BUFFER_SIZE, fileLength - _pos);
-                    _last = (_pos + len == fileLength);
-                    ByteBuffer buffer = BufferUtil.toMappedBuffer(_filePath, _pos, len);
-                    getNextInterceptor().write(buffer, _last, this);
-                    _pos += len;
-                    return Action.SCHEDULED;
-                }
+    private static class InterceptorSink implements Content.Sink
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java]: You could inline this class as a simple lambda:
```java
Content.Sink sink = (last, byteBuffer, callback) -> _interceptor.write(last, byteBuffer, callback);
```

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java [hunk 11]
```diff
@@ -193,41 +204,27 @@ private void commit(Callback callback)
             }
 
             // Create an iterating callback to do the writing
-            IteratingCallback icb = new IteratingCallback()
-            {
-                private final long fileLength = _filePath.toFile().length();
-                private long _pos = 0;
-                private boolean _last = false;
+            ByteBufferPool.Sized sizedPool = ByteBufferPool.Sized.as(getServer().getByteBufferPool(), true, getBufferSize());
+            Content.Source source = Content.Source.from(sizedPool, _filePath);
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java:208]: This does not `mmap` files naymore, but honestly I think it is for the best.

**Review by lorban — APPROVED** [review]
I'll leave it up to you to decide to keep the new `ByteBufferPool.Sized.as()` helper or not, as well as inlining the `InterceptorSink` or not.

LGTM either way.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java (hunk 11 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/FileBufferedResponseHandler.java:208]: Supporting mmap from Content.Source.from(path) is still possible, but in a future PR.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java (hunk 8 above)
Comment (joakime) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java]: Removed

**Review by lorban — APPROVED** [review]
