### PR TITLE
Jetty 12.0.x 10716 charset printwriter

### LINKED ISSUE #10716: Incorrect setting of content type with charset encoding before and after PrintWriter obtained
Related to tck omnibus issue #10712.

Tests:

```
com/sun/ts/tests/servlet/api/jakarta_servlet/servletresponse/URLClient.java.getContentTypeNull2Test
com/sun/ts/tests/servlet/api/jakarta_servlet/servletresponse/URLClient.java.getWriterAfterTest
com/sun/ts/tests/servlet/pluggability/api/jakarta_servlet/servletresponse/URLClient.java.getContentTypeNull2Test
com/sun/ts/tests/servlet/pluggability/api/jakarta_servlet/servletresponse/URLClient.java.getWriterAfterTest
```

These tests play around with calling `response.setContentType()` before and after the `PrintWriter` is obtained, and also setting the content type with and without a character encoding.

### PR DESCRIPTION
**Pull request by janbartel**
Fix #10716

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 1]
```diff
@@ -1702,9 +1707,9 @@ public void set(HttpField field)
                         }
                         else
                         {
-                            if (last != null && onRemoveField(last))
+                            if (last != null)
                             {
-                                field = onAddField(field);
+                                field = onReplaceField(last, field);
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:1748]: There is a problem here.   A put method is implemented as an iteration over all fields, setting the first one and then removing the remaining ones.  Unfortunately if there are multiple fields, then that will be seen as "replace", "remove", "remove", which whilst it passes the field value itself, might be a little confusing.   We probably need to do something to make the order: remove, remove, replace.

**Review by gregw — CHANGES_REQUESTED** [review]
I'll ponder this....

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java [hunk 2]
```diff
@@ -582,18 +582,59 @@ public boolean onRemoveField(HttpField field)
...
+        /**
+         *
+         */
+        @Override
+        public HttpField onReplaceField(HttpField oldField, HttpField newField)
+        {
+            if (oldField == null)
+            {
+                return onAddField(newField);
+            }
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java]: This can never happen, so most efficient to just do an
```suggestion
            assert oldField != null;
```

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java [hunk 3]
```diff
@@ -582,18 +582,59 @@ public boolean onRemoveField(HttpField field)
...
+
+            if (newField == null)
+            {
+                onRemoveField(oldField);
+                return null;
+            }
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java]: This also can never happen:
```suggestion
            assert newField != null;
```

maybe combine both asserts?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java [hunk 4]
```diff
@@ -582,18 +582,59 @@ public boolean onRemoveField(HttpField field)
...
+
+            switch (newField.getHeader())
+            {
+                case CONTENT_LENGTH ->
+                {
+                    if (!isCommitted())
+                    {
+                        return setContentLength(newField);
+                    }
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java]: I think this is a pre-existing bug!  If it is committed this should be a noop

```suggestion
                    return isCommitted() ? null : setContentLength(newField);
```

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java [hunk 5]
```diff
@@ -582,18 +582,59 @@ public boolean onRemoveField(HttpField field)
...
+                }
+                case CONTENT_TYPE ->
+                {
+                    if (!isCommitted())
+                    {
+                        return setContentType(newField);
+                    }
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java]: ditto
```suggestion
                    return isCommitted() ? null : setContentType(newField);
```

Oh no, and all the add and remove ones are wrong as well!

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:1748]: I think I'm caring about this less because I can't see an easy fix.  It is technically correct.

**Review by gregw — CHANGES_REQUESTED** [review]

**Comment by gregw** [comment]
```diff
diff --git a/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java b/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java
index ca7988dc34..125c733e51 100644
--- a/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java
+++ b/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java
@@ -540,99 +540,65 @@ public class ServletContextResponse extends ContextResponse implements ServletCo
         @Override
         public HttpField onAddField(HttpField field)
         {
-            if (field.getHeader() != null)
-            {
-                switch (field.getHeader())
-                {
-                    case CONTENT_LENGTH ->
-                    {
-                        if (!isCommitted())
-                        {
-                            return setContentLength(field);
-                        }
-                    }
-                    case CONTENT_TYPE ->
-                    {
-                        if (!isCommitted())
-                        {
-                            return setContentType(field);
-                        }
-                    }
-                }
-            }
+            if (isCommitted())
+                return null;
+
+            if (field.getHeader() == null)
+                return super.onAddField(field);
 
-            return super.onAddField(field);
+            return switch (field.getHeader())
+            {
+                case CONTENT_LENGTH -> setContentLength(field);
+                case CONTENT_TYPE -> setContentType(field);
+                default -> super.onAddField(field);
+            };
         }
 
         @Override
         public boolean onRemoveField(HttpField field)
         {
-            if (field.getHeader() != null)
+            if (isCommitted())
+                return false;
+            if (field.getHeader() == null)
+                return true;
+            switch (field.getHeader())
             {
-                switch (field.getHeader())
+                case CONTENT_LENGTH -> _contentLength = -1;
+                case CONTENT_TYPE ->
                 {
-                    case CONTENT_LENGTH ->
+                    _contentType = null;
+                    _mimeType = null;
+                    if (!isWriting())
                     {
-                        if (!isCommitted())
-                            _contentLength = -1;
-                    }
-                    case CONTENT_TYPE ->
-                    {
-                        if (!isCommitted())
+                        _characterEncoding = switch (_encodingFrom)
                         {
-                            _contentType = null;
-                            _mimeType = null;
-                            if (!isWriting())
-                            {
-                                _characterEncoding = switch (_encodingFrom)
-                                {
-                                    case SET_CHARACTER_ENCODING, SET_LOCALE -> _characterEncoding;
-                                    default -> null;
-                                };
-                            }
-                        }
+                            case SET_CHARACTER_ENCODING, SET_LOCALE -> _characterEncoding;
+                            default -> null;
+                        };
                     }
                 }
             }
+
             return true;
         }
 
-        /**
-         *
-         */
         @Override
         public HttpField onReplaceField(HttpField oldField, HttpField newField)
         {
-            if (oldField == null)
-            {
-                return onAddField(newField);
-            }
+            assert oldField != null && newField != null;
 
-            if (newField == null)
-            {
-                onRemoveField(oldField);
+            if (isCommitted())
                 return null;
-            }
 
-            switch (newField.getHeader())
-            {
-                case CONTENT_LENGTH ->
-                {
-                    if (!isCommitted())
-                    {
-                        return setContentLength(newField);
-                    }
-                }
-                case CONTENT_TYPE ->
-                {
-                    if (!isCommitted())
-                    {
-                        return setContentType(newField);
-                    }
-                }
-            }
+            if (newField.getHeader() == null)
+                return newField;
 
-            return newField;
+            return switch (newField.getHeader())
+            {
+                case CONTENT_LENGTH -> setContentLength(newField);
+                case CONTENT_TYPE -> setContentType(newField);
+                default -> newField;
+            };
         }
 
         private HttpField setContentLength(HttpField field)
```

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:1748]: Hmm it can be fixed with:
```diff
diff --git a/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java b/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
index 3db9d3a61b..811d447599 100644
--- a/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
+++ b/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java
@@ -1628,11 +1628,47 @@ public interface HttpFields extends Iterable<HttpField>, Supplier<HttpFields>
                 {
                     field = onAddField(field);
                     if (field != null)
-                        return _fields.add(field);
+                        _fields.add(field);
                 }
                 return this;
             }
 
+            @Override
+            public Mutable put(HttpField field)
+            {
+                // rewrite put to ensure that removes are called before replace
+                int put = -1;
+                ListIterator<HttpField> i = _fields.listIterator();
+                while (i.hasNext())
+                {
+                    HttpField f = i.next();
+                    if (f.isSameName(field))
+                    {
+                        if (put < 0)
+                            put = i.previousIndex();
+                        else if (onRemoveField(f))
+                            i.remove();
+                    }
+                }
+
+                if (put < 0)
+                {
+                    field = onAddField(field);
+                    if (field != null)
+                        add(field);
+                }
+                else
+                {
+                    i = _fields.listIterator(put);
+                    HttpField old = i.next();
+                    field = onReplaceField(old, field);
+                    if (field != null)
+                        i.set(field);
+                }
+
+                return this;
+            }
+
             @Override
             public Mutable clear()
             {
```

**Comment by janbartel** [comment]
@gregw it will be faster if you just commit your diffs straight to the branch

**Review by gregw — APPROVED** [review]
