### PR TITLE
Fix `DynamicCapacity.release()`

### LINKED ISSUE #12082: `RetainableByteBuffer.DynamicCapacity` enters a corrupt state when released
**Jetty version(s)**
12.1.x

**Description**
`HttpClientTransportOverHTTP2Test.testClientStopsServerDoesNotCloseClientCloses()` illustrates the problem.

When you run that test, it passes but dumps the following stack trace to `stderr`:

```
java.lang.IllegalStateException: already released ReferenceCounter@7bd4937b[r=0]
	at org.eclipse.jetty.io.Retainable$ReferenceCounter.lambda$release$2(Retainable.java:226)
	at java.base/java.util.concurrent.atomic.AtomicInteger.updateAndGet(AtomicInteger.java:281)
	at org.eclipse.jetty.io.Retainable$ReferenceCounter.release(Retainable.java:223)
	at org.eclipse.jetty.io.Retainable$Wrapper.release(Retainable.java:149)
	at org.eclipse.jetty.io.RetainableByteBuffer$DynamicCapacity.release(RetainableByteBuffer.java:1913)
	at org.eclipse.jetty.http2.tests.HttpClientTransportOverHTTP2Test$13.writeFrames(HttpClientTransportOverHTTP2Test.java:602)
	at org.eclipse.jetty.http2.tests.HttpClientTransportOverHTTP2Test$13.onHeaders(HttpClientTransportOverHTTP2Test.java:588)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyHeaders(BodyParser.java:115)
	at org.eclipse.jetty.http2.parser.HeadersBodyParser.onHeaders(HeadersBodyParser.java:269)
	at org.eclipse.jetty.http2.parser.HeadersBodyParser.onHeaders(HeadersBodyParser.java:264)
	at org.eclipse.jetty.http2.parser.HeadersBodyParser.parse(HeadersBodyParser.java:208)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:229)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:156)
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:121)
	at org.eclipse.jetty.http2.tests.HttpClientTransportOverHTTP2Test.testClientStopsServerDoesNotCloseClientCloses(HttpClientTransportOverHTTP2Test.java:618)
	...
```

This happens because `writeFrames()` is called more than once, and itself calls `RetainableByteBuffer.DynamicCapacity.release()`.

The first time `writeFrames()` is called, everything works as expected: `release()` figures out it's time to cleanup and does it well.
The second time, `release()` relies on a `ReferenceCounter` instance held it a superclass that was not reset by the first call, hence it throws the above exception to complain that release was already performed. Unfortunately, in the meantime the dynamic capacity accumulator was asked to accumulate, and it did without error. At this point in time, `RetainableByteBuffer.DynamicCapacity` contains lifecycled resources that it does not correctly track and is incapable of releasing.

### PR DESCRIPTION
**Pull request by lorban**
Add assertions to `DynamicCapacity` to avoid entering an undetected corrupt state after it is released.

Fixes #12082

### CODE REVIEW

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java [hunk 1]
```diff
@@ -1916,6 +1916,8 @@ public boolean release()
                     buffer.release();
                 _buffers.clear();
                 _aggregate = null;
+                // Re-acquire the ref counter to make sure this instance is reusable.
+                ((ReferenceCounter)getWrapped()).acquire();
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: This is the actual fix here and the change to super above is not strictly necessary?

If this is needed here, then why is it not also needed for all other extensions of RBB.Abstract?

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: Actually I really don't understand this fix?  If we have been released to 0, then we should not be reusable.   Maybe we can reacquire is a reset method?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: Maybe all the add methods of `RBB.DC` should have:
```java
            assert getWrapped() instanceof ReferenceCounter counter && counter.get() > 0;
```

or even a real check to that effect?


Ultimately `RBB.DC` is just a `RBB` and that it is a programming error to keep using it after releasing to zero.   If it was a pooled buffer, then you'd be using a buffer that might be used by a different process.      If it is being used as an accumulator that will be reused over and over, but release by a method it is passed to, then you need to retain before you pass it.

Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: The change to the constructor calling super with a `ReferenceCounter` instance is to guarantee the cast in `release()` won't fail.

The test that highlighted this problem does the following:

```
RBB.DC.put(...)
RBB.DC.writeTo(...)
RBB.DC.release(...)

RBB.DC.put(...)
RBB.DC.writeTo(...)
RBB.DC.release(...)
```

You're totally right that using a RBB after the final `release()` is an error, and we should consider adding some checks to our implementations to prevent the usage of any RBB impl after release.

But in this particular case, I noticed that altering `release()` to make it reset the wrapped `ReferenceCounter` was all it took for `RBB.DC` to behave correctly, so I figured that since it was be simpler to make `RBB.DC` behave correctly despite being incorrectly used then preventing its incorrect use I'd go with that solution.

But I agree this is debatable, and that opens some questions: should we modify the `RBB` contract to state it throws when used after release returned true? Is there anything wrong with allowing certain implementations to allow being reused after release returned true?

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: I think there is something wrong with that approach. If code is written without knowledge of the specific type of RBB, then it will work with one implementation but fail with another

Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: Sure, and since this is happening in the context of a test, we are free to decide to either modify the test to strictly follow the RBB contract or to leave the test the way it is if we consider this RBB.DC usage is reasonable.

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: Let's do that and add the asserts I suggested

Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: Ok, I added checks instead and adapted the test.

**Comment by lorban** [comment]
@sbordet nudge

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java [hunk 2]
```diff
@@ -1445,7 +1445,7 @@ public DynamicCapacity(ByteBufferPool pool, boolean direct, long maxSize, int ag
 
         private DynamicCapacity(List<RetainableByteBuffer> buffers, ByteBufferPool.Sized pool, long maxSize, int minRetainSize)
         {
-            super();
+            super(new ReferenceCounter()); // Make sure the wrapped retainable is a ReferenceCounter.
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: The comment tells what the code does, so it can be removed.
Actually the previous code was doing the same, so I'd restore the previous code.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java [hunk 3]
```diff
@@ -1456,6 +1456,13 @@ private DynamicCapacity(List<RetainableByteBuffer> buffers, ByteBufferPool.Sized
                 throw new IllegalArgumentException("must always retain if cannot aggregate");
         }
 
+        private void checkNotReleased()
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java:1483]: This method is only used in this class, but I guess all subclasses of `Abstract` would need to do the same checks.
Feels like it's either too much defensive programming, or it needs to be done in the base class once.

**Review by sbordet — APPROVED** [review]
The fix is fine, but the rest is incomplete, I guess.

I'll approve this PR, but RBBP needs a large simplification.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: or remove the `super()` call entirely?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java [hunk 4]
```diff
@@ -1456,6 +1456,13 @@ private DynamicCapacity(List<RetainableByteBuffer> buffers, ByteBufferPool.Sized
...
+        {
+            ReferenceCounter counter = (ReferenceCounter)getWrapped();
+            if (counter.get() == 0)
+                throw new IllegalStateException("Already released");
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: Use the API:
```suggestion
            if (getRetained() <= 0)
                throw new IllegalStateException("Already released");
```

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: Actually I'd prefer:
```suggestion
            assert getRetained() > 0;
```

and then inline the method.

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: or maybe:
```suggestion
            if(LOG.isDebugEnabled() && getRetained() <= 0)
                throw new IllegalStateException("Already released");
```

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java:1483]: If those checks were done in the base class, pretty much all method implementations would need to call super. This would basically double the changes and I don't see how this would improve clarity.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: I changed the code to use the API as suggested, but I'm not in favor of only enforcing this check when assertions or debug logs are enabled as IMHO the atomic get is cheap enough that it's virtually free in practice.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java [hunk 5]
```diff
@@ -1481,6 +1480,12 @@ private DynamicCapacity(List<RetainableByteBuffer> buffers, ByteBufferPool.Sized
                 throw new IllegalArgumentException("must always retain if cannot aggregate");
         }
 
+        private void checkNotReleased()
+        {
+            if (getRetained() <= 0)
+                throw new IllegalStateException("Already released");
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java:1486]:
```suggestion
            if (LOG.isDebugEnabled() && getRetained() <= 0)
                throw new IllegalStateException("Already released");
```

**Review by gregw — APPROVED** [review]
I'm OK with this... but I'm also OK for the checkNotReleased is only done if debug is enabled.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java:1486]: If we ever re-introduce this bug by accident, only doing this check when debug logs are enabled means the tests will let it slip.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: Done.
