### PR TITLE
Issue #11270 - Improve XmlConfiguration reporting of Resource location during error

### LINKED ISSUE #11270: Windows 11 pro - problem launching Jetty with  ${jetty.home}\etc\jetty-ee10-deploy.xml <Configure> (or next one ?)
I was trying to migrate a Jetty 9 project to Jetty 12.
Windows is up to date, so are most programs.

**Jetty version(s)**
12.0.5

**Jetty Environment**
```
Enabled Modules:
----------------
  0) resources                 transitive provider of resources for logging-logback
  1) logging/slf4j             dynamic dependency of logging-logback
                               transitive provider of logging/slf4j for logging-logback
  2) logging-logback           ${jetty.base}\start.d\logging-logback.ini
  3) bytebufferpool            transitive provider of bytebufferpool for server
                               ini template available with --add-modules=bytebufferpool
  4) client                    transitive provider of client for ee10-websocket-jakarta
  5) threadpool                transitive provider of threadpool for server
                               ini template available with --add-modules=threadpool
  6) server                    transitive provider of server for http
                               transitive provider of server for ee10-plus
                               transitive provider of server for deploy
                               transitive provider of server for plus
                               transitive provider of server for security
                               transitive provider of server for sessions
                               transitive provider of server for ee10-security
                               transitive provider of server for ee10-servlet
                               transitive provider of server for jndi
                               transitive provider of server for gzip
                               ini template available with --add-modules=server
  7) deploy                    transitive provider of deploy for ee10-deploy
  8) sessions                  transitive provider of sessions for ee10-servlet
                               ini template available with --add-modules=sessions
  9) ee10-servlet              transitive provider of ee10-servlet for ee10-webapp
                               transitive provider of ee10-servlet for ee10-security
 10) security                  transitive provider of security for ee10-security
 11) ee10-security             transitive provider of ee10-security for ee10-webapp
                               transitive provider of ee10-security for ee10-plus
 12) ee10-webapp               transitive provider of ee10-webapp for ee10-plus
                               transitive provider of ee10-webapp for ee10-deploy
                               ini template available with --add-modules=ee10-webapp
 13) plus                      ${jetty.base}\start.d\plus.ini
 14) jndi                      transitive provider of jndi for ee10-plus
 15) ee10-plus                 transitive provider of ee10-plus for ee10-annotations
 16) ee10-annotations          transitive provider of ee10-annotations for ee10-websocket-jakarta
 17) ee10-deploy               ${jetty.base}\start.d\ee10-deploy.ini
 18) ee10-websocket-jakarta    ${jetty.base}\start.d\ee10-websocket-jakarta.ini
 19) gzip                      ${jetty.base}\start.d\gzip.ini
 20) http                      ${jetty.base}\start.d\http.ini

JVM Version & Properties:
-------------------------
 java.home = C:\tools\64bits\java\jdk-21.0.1
 java.vm.vendor = Oracle Corporation
 java.vm.version = 21.0.1+12-29
 java.vm.name = OpenJDK 64-Bit Server VM
 java.vm.info = mixed mode, sharing
 java.runtime.name = OpenJDK Runtime Environment
 java.runtime.version = 21.0.1+12-29
 java.io.tmpdir = C:\Users\...\AppData\Local\Temp\
 user.dir = C:\DEV\GIT\...\tools\jetty\go-base
 user.language = fr
 user.country = FR

Jetty Version & Properties:
---------------------------
 jetty.version = 12.0.5
 jetty.tag.version = jetty-12.0.5
 jetty.build = 3aed62e4959bb8c01f5975fe81e078e3ff626126
 jetty.home = C:\tools\noarch\jetty\12.0.5
 jetty.base = C:\DEV\GIT\...\tools\jetty\go-base

Config Search Order:
--------------------
 <command-line>
 ${jetty.base} -> C:\DEV\GIT\...\tools\jetty\go-base
 ${jetty.home} -> C:\tools\noarch\jetty\12.0.5

System Properties:
------------------
 (no system properties specified)

Properties: Jetty
-----------------
 java.version = 21.0.1
 java.version.major = 21
 java.version.micro = 1
 java.version.minor = 0
 java.version.platform = 21
 jetty.base = C:\DEV\GIT\...\tools\jetty\go-base
 jetty.base.uri = file:///C:/DEV/GIT/.../tools/jetty/go-base
 jetty.home = C:\tools\noarch\jetty\12.0.5
 jetty.home.uri = file:///C:/tools/noarch/jetty/12.0.5
 jetty.webapp.addServerClasses = ch.qos.logback.,org.slf4j.
 logback.version = 1.4.14
 runtime.feature.alpn = true
 slf4j.version = 2.0.9

Classpath: Jetty
----------------
Version Information on 16 entries in the classpath.
Note: order presented here is how they would appear on the classpath.
      changes to the --module=name command line options will be reflected here.
 0:                    (dir) | ${jetty.base}\resources
 1:                    2.0.9 | ${jetty.home}\lib\logging\slf4j-api-2.0.9.jar
 2:                   1.4.14 | ${jetty.base}\lib\logging\logback-classic-1.4.14.jar
 3:                   1.4.14 | ${jetty.base}\lib\logging\logback-core-1.4.14.jar
 4:                   12.0.5 | ${jetty.home}\lib\jetty-client-12.0.5.jar
 5:                   12.0.5 | ${jetty.home}\lib\jetty-alpn-client-12.0.5.jar
 6:                   12.0.5 | ${jetty.home}\lib\jetty-http-12.0.5.jar
 7:                   12.0.5 | ${jetty.home}\lib\jetty-server-12.0.5.jar
 8:                   12.0.5 | ${jetty.home}\lib\jetty-xml-12.0.5.jar
 9:                   12.0.5 | ${jetty.home}\lib\jetty-util-12.0.5.jar
10:                   12.0.5 | ${jetty.home}\lib\jetty-io-12.0.5.jar
11:                   12.0.5 | ${jetty.home}\lib\jetty-deploy-12.0.5.jar
12:                   12.0.5 | ${jetty.home}\lib\jetty-session-12.0.5.jar
13:                   12.0.5 | ${jetty.home}\lib\jetty-security-12.0.5.jar
14:                   12.0.5 | ${jetty.home}\lib\jetty-plus-12.0.5.jar
15:                   12.0.5 | ${jetty.home}\lib\jetty-jndi-12.0.5.jar

Active XMLs: Jetty
------------------
 ${jetty.home}\etc\jetty-bytebufferpool.xml
 ${jetty.home}\etc\jetty-threadpool.xml
 ${jetty.base}\etc\jetty.xml
 ${jetty.base}\etc\jetty-deploy.xml
 ${jetty.home}\etc\sessions\id-manager.xml
 ${jetty.home}\etc\jetty-gzip.xml
 ${jetty.home}\etc\jetty-http.xml

Properties: ee10
----------------
 contextHandlerClass = org.eclipse.jetty.ee10.webapp.WebAppContext

Classpath: ee10
---------------
Version Information on 24 entries in the classpath.
Note: order presented here is how they would appear on the classpath.
      changes to the --module=name command line options will be reflected here.
 0:                    6.0.0 | ${jetty.home}\lib\jakarta.servlet-api-6.0.0.jar
 1:                   12.0.5 | ${jetty.home}\lib\jetty-ee10-servlet-12.0.5.jar
 2:                   12.0.5 | ${jetty.home}\lib\jetty-ee10-webapp-12.0.5.jar
 3:                   12.0.5 | ${jetty.home}\lib\jetty-ee10-plus-12.0.5.jar
 4:                    2.0.1 | ${jetty.home}\lib\jakarta.transaction-api-2.0.1.jar
 5:                    2.1.0 | ${jetty.home}\lib\jakarta.interceptor-api-2.1.0.jar
 6:                    4.0.1 | ${jetty.home}\lib\jakarta.enterprise.cdi-api-4.0.1.jar
 7:                      2.0 | ${jetty.home}\lib\jakarta.inject-api-2.0.1.jar
 8:                    4.0.1 | ${jetty.home}\lib\jakarta.enterprise.lang-model-4.0.1.jar
 9:                   12.0.5 | ${jetty.home}\lib\jetty-ee10-annotations-12.0.5.jar
10:                      9.6 | ${jetty.home}\lib\ee10-annotations\asm-9.6.jar
11:                      9.6 | ${jetty.home}\lib\ee10-annotations\asm-analysis-9.6.jar
12:                      9.6 | ${jetty.home}\lib\ee10-annotations\asm-commons-9.6.jar
13:                      9.6 | ${jetty.home}\lib\ee10-annotations\asm-tree-9.6.jar
14:                    2.1.1 | ${jetty.home}\lib\ee10-annotations\jakarta.annotation-api-2.1.1.jar
15:                   12.0.5 | ${jetty.home}\lib\jetty-websocket-core-common-12.0.5.jar
16:                   12.0.5 | ${jetty.home}\lib\jetty-websocket-core-client-12.0.5.jar
17:                   12.0.5 | ${jetty.home}\lib\jetty-websocket-core-server-12.0.5.jar
18:                   12.0.5 | ${jetty.home}\lib\ee10-websocket\jetty-ee10-websocket-servlet-12.0.5.jar
19:                    2.1.1 | ${jetty.home}\lib\ee10-websocket\jakarta.websocket-client-api-2.1.1.jar
20:                    2.1.1 | ${jetty.home}\lib\ee10-websocket\jakarta.websocket-api-2.1.1.jar
21:                   12.0.5 | ${jetty.home}\lib\ee10-websocket\jetty-ee10-websocket-jakarta-client-12.0.5.jar
22:                   12.0.5 | ${jetty.home}\lib\ee10-websocket\jetty-ee10-websocket-jakarta-common-12.0.5.jar
23:                   12.0.5 | ${jetty.home}\lib\ee10-websocket\jetty-ee10-websocket-jakarta-server-12.0.5.jar
```

**Java version/vendor** `(use: java -version)`
Tested with java 17 and 21

```
java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

java --version
openjdk 21.0.1 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-29)
OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)
```

**OS type/version**
```
ver

Microsoft Windows [version 10.0.22631.3007]
```

**Description**
Launching Jetty failed.   I extracted Jetty from the ZIP or TGZ from Official site: https://eclipse.dev/jetty/download.php
And didn't modify the {jetty.home}.

I checked the `jetty-ee10-deploy.xml` in XML validators or in Hex editor (to find weird characters).
But it's perhaps the next one ?  But not in the logs

Error:
```
Active XMLs: ee10
-----------------
 ${jetty.home}\etc\jetty-ee10-webapp.xml
 ${jetty.home}\etc\jetty-ee10-deploy.xml
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
        at org.eclipse.jetty.start.Main.start(Main.java:519)
        at org.eclipse.jetty.start.Main.main(Main.java:76)
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 64; cvc-elt.1.a: Cannot find the declaration of element 'Configure'.
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:254)
        at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:303)
        at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:278)
        at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:260)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1963)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 4 more
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
        at org.eclipse.jetty.start.Main.start(Main.java:519)
        at org.eclipse.jetty.start.Main.main(Main.java:76)
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 64; cvc-elt.1.a: Cannot find the declaration of element 'Configure'.
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:254)
        at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:303)
        at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:278)
        at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:260)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1963)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 4 more

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
Appuyez sur une touche pour continuer...
```

**How to reproduce?**
Launch Jetty
`java -jar %JETTY_HOME%/start.jar %JETTY_OPTIONS% %JETTY_STOP_OPTIONS% --module=ext
`

### PR DESCRIPTION
**Pull request by joakime**
Attempt to unify all of the Exception flows on `XmlConfiguration` to always report the location of the `XmlConfiguration` resource (if able to).

Fixes: #11270

### CODE REVIEW

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 1]
```diff
@@ -280,10 +277,14 @@ public XmlConfiguration(Resource resource, Map<String, Object> idMap, Map<String
...
         }
+        catch (Throwable t)
+        {
+            throw new XmlConfigurationException("Bad Xml Config in " + this, t);
+        }
         finally
         {
-            if (parser instanceof Closeable)
-                ((Closeable)parser).close();
+            if (parser instanceof Closeable closable)
```
Comment (sbordet) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Typo: `closeable`

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 2]
```diff
@@ -252,10 +251,9 @@ public XmlParser getXmlParser()
      * Reads and parses the XML configuration file.
      *
      * @param resource the Resource to the XML configuration
-     * @throws IOException if the configuration could not be read
-     * @throws SAXException if the configuration could not be parsed
+     * @throws XmlConfigurationException if configuration was not able to loaded from XML provided
      */
-    public XmlConfiguration(Resource resource) throws SAXException, IOException
+    public XmlConfiguration(Resource resource)
```
Comment (sbordet) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Uhm, this is now a breaking change, as user code that did `try/catch (IOException)` will now get a compilation error.

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 3]
```diff
@@ -280,10 +277,14 @@ public XmlConfiguration(Resource resource, Map<String, Object> idMap, Map<String
             _idMap = idMap == null ? new HashMap<>() : idMap;
             _propertyMap = properties == null ? new HashMap<>() : properties;
         }
+        catch (Throwable t)
+        {
+            throw new XmlConfigurationException("Bad Xml Config in " + this, t);
```
Comment (sbordet) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]:
```suggestion
            throw new XmlConfigurationException("Bad Jetty XML configuration in " + this, t);
```

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 4]
```diff
@@ -465,14 +466,14 @@ public Object configure() throws Exception
                 }
                 catch (NoSuchMethodException x)
                 {
-                    throw new IllegalStateException(String.format("No matching constructor %s in %s", oClass, _configuration));
+                    throw new XmlConfigurationException("No matching constructor " + oClass);
```
Comment (sbordet) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: I would throw `IllegalStateException` here as before, because A) in many other places you did not convert to throw `XmlConfigurationException` (you converted just a couple), and it's caught and rethrown as `XmlConfigurationException` anyway.

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 5]
```diff
@@ -429,7 +430,7 @@ public Object configure(Object obj) throws Exception
             if (oClass != null && !oClass.isInstance(obj))
             {
                 String loaders = (oClass.getClassLoader() == obj.getClass().getClassLoader()) ? "" : "Object Class and type Class are from different loaders.";
-                throw new IllegalArgumentException("Object of class '" + obj.getClass().getCanonicalName() + "' is not of type '" + oClass.getCanonicalName() + "'. " + loaders + " in " + _configuration);
+                throw new XmlConfigurationException("Object of class '" + obj.getClass().getCanonicalName() + "' is not of type '" + oClass.getCanonicalName() + "'. " + loaders);
```
Comment (sbordet) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Ditto.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 2 above)
Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Guess I can leave those `throws` declarations to not change the signature, 
Doesn't matter if that they will never happen with the other changes in this PR.

Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Done.

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 3 above)
Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Fixed.

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 4 above)
Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Done.

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 5 above)
Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Done.

**Review by sbordet — APPROVED** [review]
