### PR TITLE
Fixes #11081 - Dropped WebSocket messages due to race condition in WebSocket frame handling.

### LINKED ISSUE #11081: Dropped WebSocket messages due to race condition in WebSocket frame handling
**Jetty version(s)**
11.0.18

**Java version/vendor** `(use: java -version)`
11.0.17

**OS type/version**
Windows 11/Linux CentOS 8

**Description**
After migrating a CometD-based application from Jetty 9 to Jetty 11, we started finding that some automated tests started randomly failing when using WebSockets. We traced the issue to some CometD messages being lost/never delivered to the server.

Further analysis showed that the content of multiple WebSocket frames ends up packed into a single onMessage event on the application side, which is unexpected. Indeed, CometD expects multiple messages to be delivered as an array, not as back-to-back objects in a single message, so it only parses the first one found, while all subsequent ones are discarded.

Annotated application logs are attached to show that the same Utf8StringBuilder instance in StringMessageSink is used by 2 separate threads even though both are delivering a FIN frame, which should case immediate delivery to the application and a builder reset.
The logs were obtained using the distributed Jetty 11.0.18 with only the following modification to the org.eclipse.jetty.websocket.core.internal.messages.StringMessageSink class to add debugging traces:

``` diff
// StringMessageSink.java
@@ -14,17 +14,22 @@
 package org.eclipse.jetty.websocket.core.internal.messages;
 
 import java.lang.invoke.MethodHandle;
+import java.util.Objects;
 
 import org.eclipse.jetty.util.Callback;
 import org.eclipse.jetty.util.Utf8StringBuilder;
 import org.eclipse.jetty.websocket.core.CoreSession;
 import org.eclipse.jetty.websocket.core.Frame;
 import org.eclipse.jetty.websocket.core.exception.MessageTooLargeException;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 public class StringMessageSink extends AbstractMessageSink
 {
     private Utf8StringBuilder out;
     private int size;
+    
+    private static Logger LOG = LoggerFactory.getLogger(StringMessageSink.class);
 
     public StringMessageSink(CoreSession session, MethodHandle methodHandle)
     {
@@ -46,7 +51,14 @@
             }
 
             if (out == null)
-                out = new Utf8StringBuilder(session.getInputBufferSize());
+            {
+                out = new Utf8StringBuilder(session.getInputBufferSize());                
+                LOG.info("NEW Utf8StringBuilder {} created", System.identityHashCode(out));
+            }
+            else
+            {
+                LOG.warn("Utf8StringBuilder {} reused with {} bytes for {} with FIN {}", System.identityHashCode(out), out.length(), callback, frame.isFin());
+            }
 
             out.append(frame.getPayload());
             if (frame.isFin())

```

**How to reproduce?**
Not reproducible systematically.

[analysis on possibile race condition on StringMessageSink.txt](https://github.com/jetty/jetty.project/files/13706559/analysis.on.possibile.race.condition.on.StringMessageSink.txt)

### PR DESCRIPTION
**Pull request by sbordet**
Now the reset of the MessageSink internal accumulators happens before the demand.

This avoids the race, since as soon as there is demand another thread could enter the MessageSink, but the accumulator has already been reset.

### CODE REVIEW

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java [hunk 1]
```diff
@@ -79,38 +82,38 @@ public void accept(Frame frame, Callback callback)
...
+                callback = Callback.NOOP;
             }
 
-            // If the methodHandle throws we don't want to fail callback twice.
-            callback = Callback.NOOP;
             if (frame.isFin())
             {
                 byte[] buf = out.takeByteArray();
                 methodHandle.invoke(buf, 0, buf.length);
+                reset();
```
Comment (lachlan-roberts) [inline jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java]: Can we just make the `ByteBufferCallbackAccumulator` final?

I don't really understand why we need to be nulling it out and re-creating it for every message. Same deal for the other message sinks.

**Review by lachlan-roberts — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java (hunk 1 above)
Comment (sbordet) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java]: I think the idea is to _not_ create it if the messages are always FIN single-frame.

However, if it gets created, we can keep it around, which is what I have done now.

The only glitch is for `StringMessageSink` where a large message will allocate a large `StringBuilder` and if then only small messages arrive, we are potentially wasting memory.
For binary sinks, the accumulator is a list that gets cleared so no problems with memory.
@gregw opinions?

Comment (gregw) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java]: for binary sinks, I have a PR that merges the ByteBufferAccumulator and ByteBufferAggregator, so hopefully we can just retain the frames and avoid a copy until they have all arrived.

For string messages, I guess we could modify the Utf8StringBuilder so that if a small message is taken and the StringBuilder has a much larger capacity than was needed, then the reset nulls it rather than sets the length to 0.    Pity it doesn't have take symantics!

Comment (gregw) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java]: Hmmm we could change the Utf8StringBuilder so that if the taken string was substantially smaller than the capacity, then we can do a StringBuilder.trimToSize after the reset.  Something like:
```java

    protected void bufferReset()
    {
        if ((_buffer.length() * 10) < _buffer.capacity())
            _buffer.trimToSize();
        _buffer.setLength(0);
    }
```

Comment (gregw) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java]: Actually probably better to go to empty buffer and start again to determine new optimal length:
```java 
    protected void bufferReset()
    {
        boolean trim = _buffer.capacity() > (_buffer.length() * 8);
        _buffer.setLength(0);
        if (trim)
            _buffer.trimToSize();
    }
```

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java [hunk 2]
```diff
@@ -56,16 +53,19 @@ public void accept(Frame frame, Callback callback)
                     String.format("Binary message too large: (actual) %,d > (configured max binary message size) %,d", size, maxBinaryMessageSize));
             }
 
-            // If we are fin and no OutputStream has been created we don't need to aggregate.
-            if (frame.isFin() && (out == null))
+            // If the frame is fin and no accumulator has
+            // been created, then we don't need to aggregate.
+            if (frame.isFin() && (out == null || out.getLength() == 0))
```
Comment (gregw) [inline jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java]:
```suggestion
            // If the frame is fin and no accumulator has
            // been used, then we don't need to aggregate.
            if (frame.isFin() && (out == null || out.getLength() == 0))
```

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java [hunk 3]
```diff
@@ -79,32 +79,25 @@ public void accept(Frame frame, Callback callback)
                 if (out == null)
                     out = new ByteBufferCallbackAccumulator();
                 out.addEntry(payload, callback);
+                // The callback is now stored in the accumulator, so if
```
Comment (gregw) [inline jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java:82]: What!!! we have yet another `ByteBufferAccumulator`!!!  Will fix in my other PR!

Comment (gregw) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java:82]: @lachlan-roberts it is really unclear in the javadoc what the difference is between succeeding and failing the callback passed to this method?  Is there a difference?

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java]: > for binary sinks, I have a PR that merges the ByteBufferAccumulator and ByteBufferAggregator, so hopefully we can just retain the frames and avoid a copy until they have all arrived.

@gregw we already do this, the binary message sinks don't use `ByteBufferAccumulator` or `ByteBufferAggregator`. They use `ByteBufferCallbackAccumulator` which stores the buffers with their callbacks and only combines them when the full message has arrived.

Comment (gregw) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java]: @lachlan-roberts see  #11058

**Review by gregw — CHANGES_REQUESTED** [review]

**Comment by gregw** [comment]
Does this replace #11086 or augment it?

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java (hunk 1 above)
Comment (gregw) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java]: I've added this trim behavior to #11058

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/messages/ByteArrayMessageSink.java:82]: yes, failing the callback will fail the websocket connection, succeeding it just releases the payload

**Comment by lachlan-roberts** [comment]
@gregw @sbordet we still need the changes from https://github.com/jetty/jetty.project/pull/11086
so please approve that so it can be merged, or bring in the same changes here

**Comment by sbordet** [comment]
@lachlan-roberts #11086 is for Jetty 12, so its changes will not be here. The correspondent PR for Jetty 10 is #11084, and its changes are already incorporated in this PR.

**Comment by lachlan-roberts** [comment]
@sbordet you have some ECA validation failure.
> Author did not have a signed ECA on file. (simone.bordet@gm*il DOT com)

**Review by lachlan-roberts — APPROVED** [review]
