### PR TITLE
Fixes #12900 - JPMS and environments.

### LINKED ISSUE #12900: Make JPMS work with new Environments features
**Jetty version(s)**
12.x

**Jetty Environment**
Any 2

**Description**

When start.jar is used in --jpms mode, the classloaders are not built correctly for environments. Specifically all the modules for the environment are put on the system classloader as well as into the environment URL ClassLoader.  This prevents multiple environments being used and required a hack in Environment.ensure as the wrong classloader is used.

 - [ ] stop putting env modules on the system classpath
 - [ ] use a layer for env classloader if in JPMS mode
 - [ ] remove the hack done in Environment.ensure

### PR DESCRIPTION
**Pull request by sbordet**
* Environments are now built using a ModuleLayer, that contains all the jars related to that environment.
* Introduced websocket-core-[client|server].mod to avoid that the WebSocket core jars will be present in both the server ModuleLayer and the environment ModuleLayer, causing JPMS errors.
* Now server.mod specifies --add-modules ALL-DEFAULT,ALL-MODULE-PATH. ALL-DEFAULT is necessary to expose JDK modules to the environment ModuleLayer. ALL-MODULE-PATH was previously hardcoded in the code, now it's externalized.
* Removed most of the [jpms] directives in *.mod files, as they are either covered by ALL-DEFAULT, or not necessary.
* EnvironmentBuilder now uses the ModuleLayer APIs to create an environment ModuleLayer child of the server ModuleLayer (the latter created by the JVM at startup, containing all the server/core jars).

### CODE REVIEW

File: jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/JPMSOpts.java [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+import java.nio.file.Path;
+import java.util.Arrays;
+import java.util.LinkedHashMap;
+import java.util.LinkedHashSet;
+import java.util.List;
+import java.util.Map;
+import java.util.Set;
+import java.util.stream.Collectors;
+
+class JPMSOpts
```
Comment (gregw) [inline jetty-core/jetty-start/src/main/java/org/eclipse/jetty/start/JPMSOpts.java]: `JPMSArgs` would match better with the other usage of `Args` in this code.
Also some minimal javadoc would be good

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 2]
```diff
@@ -1886,176 +1886,164 @@ private static List<XmlParser.Node> getNodes(XmlParser.Node node, String element
...
-                            throw new IllegalStateException("Not building an environment");
+                        environment = envBuilder.build();
+                        Environment.set(environment);
+                        envBuilder = null;
                     }
-                    default ->
+                    String envName = args[++i];
+                    environment = Environment.get(envName);
+                    if (environment == null)
+                        envBuilder = new EnvironmentBuilder(envName);
```
Comment (gregw) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: This code will work so that an already known environment will switch subsequent args back to acting on the main environment.    I don't think we want that.  Maybe throw?

**Review by gregw — CHANGES_REQUESTED** [review]
Just a few niggles

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Not sure I understand? 
An already known environment will be retrieved by `Environment.get` but it will have that given name, so it would act on that environment, not the "main" environment (not sure what you refer to here by "main": you mean the current environment, or the core (i.e. not eeN) environment?).

A command line `--env ee10 --add-modules foo --env ee11 --add-modules bar --env ee10 --add-modules baz` would be badly formatted, I don't think we want to support that.

Comment (gregw) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Exactly. We should throw. Currently the second --env ee10 will reset the environment builder to null and then continue.

Comment (sbordet) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: > Currently the second --env ee10 will reset the environment bullet to null and then continue.

Yes. And if a `--add-modules` (or the others explicitly mentioned in the `case`s) is specified, it will throw NPE.
Otherwise, if it's an XML or properties file, will be applied to the right environment.

Seems to me we already do the right thing.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-client/src/main/config/modules/websocket-jetty-client.mod [hunk 3]
```diff
@@ -1,15 +1,13 @@
 [description]
-Expose the Jetty WebSocket Client classes to deployed web applications.
+Exposes the Jetty WebSocket Client classes to deployed web applications.
 
 [tags]
 websocket
 
-[depend]
-client
+[depends]
```
Comment (lorban) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-client/src/main/config/modules/websocket-jetty-client.mod:7]: That used to be a `[depend]` block (without the trailing 's'). Are they synonyms?

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/EnvironmentBuilder.java [hunk 4]
```diff
@@ -13,54 +13,187 @@
...
+    {
+        _jpmsExports.add(exports);
+    }
+
+    void addReads(String reads)
+    {
+        _jpmsReads.add(reads);
+    }
+
+    public Environment build() throws Exception
```
Comment (lorban) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/EnvironmentBuilder.java:93]: That now looks complicated enough to be worthy of a test. But can we use junit to write JPMS tests?

File: jetty-core/jetty-websocket/jetty-websocket-jetty-client/src/main/config/modules/websocket-jetty-client.mod (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-client/src/main/config/modules/websocket-jetty-client.mod:7]: Yes, they are synonyms.

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Nope. There are paths through that don't throw. Just throw if an environment is already defined

Comment (sbordet) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: @gregw I have added a test case, and are now throwing if the environment already exists.

**Review by gregw — DISMISSED** [review]
Lgtm

**Review by lorban — DISMISSED** [review]

**Review by lorban — APPROVED** [review]

**Review by joakime — APPROVED** [review]
The build failure is a network failure with nexus on JDK23.
I'm ok with this PR as it stands.
Merge it.
