### PR TITLE
Fix NPE in `ArrayByteBufferPool.removeAndRelease()` when the RBB comes from `QueuedPool`

### LINKED ISSUE #12776: ByteBufferPool - all ongoing requests fail when single request is cancelled on HTTP/2
**Jetty version(s)**

12.0.16 (11.0.x version since 11.0.21) 12.1.x

**Jetty Environment**

Embedded + EE9

**Java version/vendor (use: java -version)**
```
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)
```

**OS type/version**

Ubuntu 24, Arch Linux, Manjaro...

**Description**

When web browsers plays video / audio and sending requests with header Range and request got cancelled (for example because user is seeking in video),
all other currently processed requests gets cancelled (there is HTTP2_ERROR in Chrome or Firefox network console).

Issue occurs only when HTTP/2 is used.  It works on Jetty 11.0.20, but fails on Jetty 11.0.21, 11.0.22, 11.0.23, 11.0.24 and 12.0.16.

When we disable HTTP/2 or revert this [commit](https://github.com/jetty/jetty.project/commit/57266039d8da2bd04b33b6a3e387744ab067ed80) on Jetty 11.0.24 it never fails.

This issue also never occured when tested on localhost or LAN (probably due to transfer speed).

**How to reproduce?**

[jetty-issue.zip](https://github.com/user-attachments/files/18690326/jetty-issue.zip)

Run attached code with JDK 21 using:
```bash
mvn compile exec:java
```

It starts Jetty 12.0.16 on port 9443 with HTTP/2 connections, downloads sample [video](https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4)
and starts to serve contents of `web` folder and provides endpoint `/video` for serving video data and `/sse` as Server Sent Events source.

When you open web browser https://IP:9443 it estabilish Server Send Event connections and starts to play video.

Try to seek in the video before it gets fully buffered to web browser. You can see that SSE connection will fail (alert will be shown).

NOTE: We were never able to reproduce this when using localhost or LAN address. Only way to reproduce this is to forward port to public IP address and access to address "in internet" (we have tried multiple ISP to be sure that this issue is not caused by some firewalls or network devices).
Our only thought why it happens only when access from internet is effect of transfer speed and thus different buffer usage.

Image

  
  In TCP dump you can see HTTP2 GOAWAY was sent.
  
  Reverting back to Jetty 11.0.20 helps. We also tried to revert commit [commit](https://github.com/jetty/jetty.project/commit/57266039d8da2bd04b33b6a3e387744ab067ed80) on  Jetty 11.0.24 and it also works.
  
  On Jetty 12 our only solution to fix this is to set `ByteBufferPool.NON_POOLING` in constructor of Jetty `Server` instance.

### LINKED ISSUE #12790: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.getByteBuffer()" because "buffer" is null
**Jetty version(s)**

12.0.16

**Jetty Environment**

ee8

**Java version/vendor** `(use: java -version)`

openjdk version "22.0.2" 2024-07-16
OpenJDK Runtime Environment Temurin-22.0.2+9 (build 22.0.2+9)
OpenJDK 64-Bit Server VM Temurin-22.0.2+9 (build 22.0.2+9, mixed mode, sharing)

**OS type/version**

Linux 6.1.0-1015-oem #15-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 16 09:51:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Description**

We register a consistent rate of NPEs on multiple servers running jetty since at least Dec 2024. They surface when serializing JSON responses with Jackson. The response size is < 3kB.

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.getByteBuffer()" because "buffer" is null
        at org.eclipse.jetty.io.ArrayByteBufferPool.release(ArrayByteBufferPool.java:281)
        at org.eclipse.jetty.io.ArrayByteBufferPool$Buffer.release(ArrayByteBufferPool.java:653)
        at org.eclipse.jetty.io.ArrayByteBufferPool.removeAndRelease(ArrayByteBufferPool.java:244)
        at org.eclipse.jetty.ee8.nested.HttpOutput.lockedReleaseBuffer(HttpOutput.java:599)
        at org.eclipse.jetty.ee8.nested.HttpOutput.onWriteComplete(HttpOutput.java:310)
        at org.eclipse.jetty.ee8.nested.HttpOutput.close(HttpOutput.java:573)
        at org.eclipse.jetty.io.WriteThroughWriter.close(WriteThroughWriter.java:103)
        at org.eclipse.jetty.ee8.nested.ResponseWriter.close(ResponseWriter.java:136)
        ...

Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.getByteBuffer()" because "buffer" is null
        at org.eclipse.jetty.io.ArrayByteBufferPool.release(ArrayByteBufferPool.java:281)
        at org.eclipse.jetty.io.ArrayByteBufferPool$Buffer.release(ArrayByteBufferPool.java:653)
        at org.eclipse.jetty.io.ArrayByteBufferPool.removeAndRelease(ArrayByteBufferPool.java:244)
        at org.eclipse.jetty.ee8.nested.HttpOutput.lockedReleaseBuffer(HttpOutput.java:599)
        at org.eclipse.jetty.ee8.nested.HttpOutput.onWriteComplete(HttpOutput.java:310)
        at org.eclipse.jetty.ee8.nested.HttpOutput.write(HttpOutput.java:781)
        at java.base/java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:170)
        at org.eclipse.jetty.io.WriteThroughWriter$Utf8Writer.append(WriteThroughWriter.java:335)
        at org.eclipse.jetty.io.WriteThroughWriter.write(WriteThroughWriter.java:133)
        at org.eclipse.jetty.ee8.nested.ResponseWriter.write(ResponseWriter.java:174)
        ...
```

**How to reproduce?**

Not sure yet. Flagging the issue in case somebody with context about Jetty can help pin down the problem.

### PR DESCRIPTION
**Pull request by lorban**
Fixes #12790

### CODE REVIEW

**Comment by lorban** [comment]
@gregw @sbordet nudge

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/QueuedPool.java [hunk 1]
```diff
@@ -273,6 +275,7 @@ public boolean remove()
             P p = pooled.get(inUse);
             if (p == null && inUse[0])
                 return false;
+            removedReference = p;
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/QueuedPool.java]: Is the `&&` on line 276 correct? shouldn't it be `||`?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/QueuedPool.java [hunk 2]
```diff
@@ -203,6 +203,7 @@ private static class QueuedEntry<P> implements Entry<P>
         // val/false -> idle
         // val/true  -> in use
         private final AtomicMarkableReference<P> pooled = new AtomicMarkableReference<>(null, false);
+        private P removedReference; // Only written before setting 'pooled', only read after getting 'pooled'.
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/QueuedPool.java]: If we always remember the reference, why not just have it as a normal field?

**Review by gregw — CHANGES_REQUESTED** [review]

**Comment by gregw** [comment]
@sbordet can you be @lorban on this one so we can get it merged

**Review by sbordet — DISMISSED** [review]

**Review by gregw — DISMISSED** [review]

**Review by gregw — CHANGES_REQUESTED** [review]
what simone says

**Review by sbordet — APPROVED** [review]

**Review by gregw — APPROVED** [review]

**Comment by lorban** [comment]
This should fix https://github.com/jetty/jetty.project/issues/12776 for the 12.0.x branch; ABBP used to reset the buffer  when `removeAndRelease()` is called. This is wrong as once a buffer has been removed, it should not be touched by the pool anymore as there might be a concurrent write pending.
