### PR TITLE
10.0.x: Add defensive check in HttpConnection content production

### LINKED ISSUE #6491: onDataAvailable() not called when HttpParser is closed prematurely
**Jetty version(s)**
9.4.42

**Description**
If the `HttpParser` is closed prematurely (state = `CLOSE`), then trying to read content asynchronously fail because `HttpConnection.fillAndParseForContent()` tests whether the parser is in content state.

### PR DESCRIPTION
**Pull request by lorban**
Port of #6533 to 10.0.x branch.

Currently, if the parser gets closed and the connection isn't aborted, the code enters a select/wakeup/fillAndParseForContent/wait infinite loop.

The above should never happen unless a bug gets introduced, but if such bug would happen at least the situation would be detected and acted upon.

See #6491.

### CODE REVIEW

**Review by sbordet — DISMISSED** [review]

**Comment by sbordet** [comment]
@lorban please check why the tests are failing?

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelOverHttp.java [hunk 1]
```diff
@@ -111,7 +118,14 @@ public boolean needContent()
...
                 LOG.debug("produceContent has no content, parsing and filling");
-            _httpConnection.parseAndFillForContent();
+            try
+            {
+                _httpConnection.parseAndFillForContent();
+            }
+            catch (Throwable x)
+            {
+                _content = new HttpInput.ErrorContent(x);
+            }
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelOverHttp.java]: Please refactor into a common method the two occurrences.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelOverHttp.java (hunk 1 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelOverHttp.java]: Done.

**Review by sbordet — APPROVED** [review]
