### PR TITLE
Issue #7086 - fix issues when calling websocket demand

### LINKED ISSUE #7086: WebSocket: java.lang.IllegalStateException: already released RetainableByteBuffer
**Jetty version(s)**
10.0.7
**Java version/vendor** `(use: java -version)`
openjdk 11
**OS type/version**
Linux version 2.6.32-642.el6.x86_64 (mockbuild@worker1.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Tue May 10 17:27:01 UTC 2016
**Description**
occur exception on our prod env

```
AdaptiveExecutionStrategy.runTask:416]Task run failed
java.lang.IllegalStateException: already released RetainableByteBuffer@2c03deb4{DirectByteBuffer@6bbc693a[p=0,l=0,c=4096,r=0]={<<<>>>??ÖW?{i...},r=0}
at org.eclipse.jetty.io.RetainableByteBuffer.lambdarelease2(RetainableByteBuffer.java:109)
at java.base/java.util.concurrent.atomic.AtomicInteger.updateAndGet(AtomicInteger.java:279)
at org.eclipse.jetty.io.RetainableByteBuffer.release(RetainableByteBuffer.java:106)
at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.releaseNetworkBuffer(WebSocketConnection.java:333)
at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:507)
at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:343)
at org.eclipse.jetty.io.AbstractConnectionReadCallback.succeeded(AbstractConnection.java:319)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
at org.eclipse.jetty.io.SocketChannelEndPoint1.run(SocketChannelEndPoint.java:101)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambdanew0(AdaptiveExecutionStrategy.java:138)
at org.eclipse.jetty.util.thread.ReservedThreadExecutorReservedThread.run(ReservedThreadExecutor.java:407)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
at org.eclipse.jetty.util.thread.QueuedThreadPoolRunner.run(QueuedThreadPool.java:1038)
at java.base/java.lang.Thread.run(Thread.java:834)
```
_Do not report security issues here! See [Jetty Security Reports](https://www.eclipse.org/jetty/security_reports.php)._

**How to reproduce?**

it`s hard to reproduce

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Closes #7086

If the call to `CoreSession.demand(1)` throws then the callback will be completed for success and failure. This seems to be the most likely cause for what we are seeing in #7086, and I have been able to reproduce the same error stack trace in a test.

- Do not throw from demand() if the session state is not input open.
- Fix bug where demand was not called when there was a null message sink.

### CODE REVIEW

File: jetty-websocket/websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WebSocketOpenTest.java [hunk 1]
```diff
@@ -157,22 +158,22 @@ public void testAsyncOnOpen() throws Exception
...
         assertThat(frame.getPayloadAsUTF8(), is("Hello"));
 
-        // But cannot receive
-        client.getOutputStream().write(RawFrameBuilder.buildClose(new CloseStatus(CloseStatus.NORMAL), true));
-        assertFalse(serverHandler.closeLatch.await(1, TimeUnit.SECONDS));
-
-        // Can't demand until open
-        assertThrows(Throwable.class, () -> coreSession.demand(1));
-        client.getOutputStream().write(RawFrameBuilder.buildClose(new CloseStatus(CloseStatus.NORMAL), true));
-        assertFalse(serverHandler.closeLatch.await(1, TimeUnit.SECONDS));
```
Comment (sbordet) [inline jetty-websocket/websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WebSocketOpenTest.java:167]: The code above seems to be nice to retain to enforce the behavior that you can't receive until open, etc.
Any reason it was removed? Seems slightly unrelated to this PR.

File: jetty-websocket/websocket-javax-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/SingleMessageHandlerTest.java [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+    public void testBinary() throws Exception
+    {
+        URI uri = URI.create("ws://localhost:" + _connector.getLocalPort() + "/binary");
+        EventSocket eventSocket = new EventSocket();
+        Session session = _client.connectToServer(eventSocket, uri);
+
+        // Can send/receive binary message successfully.
+        ByteBuffer binaryMessage = BufferUtil.toBuffer("hello world");
+        session.getBasicRemote().sendBinary(binaryMessage);
+        assertThat(BINARY_MESSAGES.poll(5, TimeUnit.SECONDS), is(binaryMessage));
```
Comment (sbordet) [inline jetty-websocket/websocket-javax-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/SingleMessageHandlerTest.java]: This is so confusing. That `is(binaryMessage)` actually calls `equals()` is so weird. Why not using `assertEquals()`?

Also, why `binaryMessage` is not consumed after `sendBinary()`?!? This seems like a bug, I wonder how the test is passing?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WebSocketOpenTest.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WebSocketOpenTest.java:167]: The change to demand breaks this test. This was testing that `demand()` throws if called before succeeding the onOpen callback, this PR changes it so `demand()` does not throw.

So now if demand is called before the callback, we can receive a frame while still in `CONNECTED` mode and not `OPEN`. So once the frame is received the whole connection is failed.

File: jetty-websocket/websocket-javax-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/SingleMessageHandlerTest.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-javax-tests/src/test/java/org/eclipse/jetty/websocket/javax/tests/SingleMessageHandlerTest.java]: > This is so confusing. That is(binaryMessage) actually calls equals() is so weird. Why not using assertEquals()?

I don't see this as confusing, this pattern is frequently used in other tests.

> Also, why binaryMessage is not consumed after sendBinary()?!? This seems like a bug, I wonder how the test is passing?

This was an intentional change that was made. See issue #4341. @gregw has previously said that sending a frame should not modify the position/limit of the original buffer.

**Review by sbordet — APPROVED** [review]
