### PR TITLE
Fix buffer leak in `HttpClientStreamTest.testUploadWithConcurrentServerCloseClosesStream()`

### LINKED ISSUE #10277: Review read failures impacting writes
**Jetty version(s)**
12

**Description**
Read failures should not impact writes (too much), as a write might still be possible even if the read failed.
Typical examples are early EOF in reads -- they should not impact writes.

The idea is that if a read failure is catastrophic, we would attempt the write anyway and will get the failure through the write, rather than assuming that the writes will fail.

Child issues / prs
 - [ ] #10431 
 - [ ] #10432

### PR DESCRIPTION
**Pull request by lorban**
Depends on https://github.com/jetty/jetty.project/pull/10432 - so this PR is a branch of that other PR.

See #10226

### CODE REVIEW

**Review by joakime — DISMISSED** [review]

**Comment by lorban** [comment]
This requires more investigations as stopping the connector should release any pending buffer not yet handed over to user code.

**Review by gregw — DISMISSED** [review]

**Comment by lorban** [comment]
@sbordet nudge

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/AbstractHttpTest.java [hunk 1]
```diff
@@ -57,8 +60,16 @@ public void setUp() throws Exception
...
+        try
+        {
+            Set<ArrayByteBufferPool.Tracking.Buffer> serverLeaks = bufferPool.getLeaks();
+            assertEquals(0, serverLeaks.size(), bufferPool.dumpLeaks());
+        }
+        finally
+        {
+            server.stop();
+            stacklessChannelLogging.close();
+        }
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/AbstractHttpTest.java]: Can you re-arrange to avoid the `finally`...
getLeaks()
stop()
close()
assert()

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 2]
```diff
@@ -108,7 +108,7 @@ public class HttpConnection extends AbstractConnection implements Runnable, Writ
     private final LongAdder bytesOut = new LongAdder();
     private final AtomicBoolean _handling = new AtomicBoolean(false);
     private final HttpFields.Mutable _headerBuilder = HttpFields.build();
-    private volatile RetainableByteBuffer _retainableByteBuffer;
+    private final AtomicReference<RetainableByteBuffer> _retainableByteBuffer = new AtomicReference<>();
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Why was it necessary to use an atomic here?
As this field is "hot", so avoiding an indirection would be good.

However, the changes to atomic revealed that the code before was not really paying attention to the fact that the field was `volatile`, so the code is now better, but with an indirection.
Can we have better without indirection?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/AbstractHttpTest.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/AbstractHttpTest.java]: Done.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: I agree that `_retainableByteBuffer` should not need to be thread-safe, and I cannot remember exactly where I found a race condition that made me write this change.

Let me investigate, at the very least the reasoning should be documented but ideally, this field should not require any thread-safety.

**Comment by lorban** [comment]
On hold until #10277 is sorted.

**Comment by lorban** [comment]
The problem is that stopping the connector is notifying the HttpConnection via onClose, but that notification isn't reported to the channel state.

The tentative fix of releasing the buffer in onClose and ensuring the buffer only gets released once by making it atomic isn't right as HttpConnection's buffer shouldn't need any thread safety.

**Comment by joakime** [comment]
@lorban I think this PR needs to be updated from `jetty-12.0.x`

**Comment by joakime** [comment]
@lorban this PR needs a merge from `jetty-12.0.x` HEAD.

**Comment by lorban** [comment]
@sbordet nudge

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java [hunk 3]
```diff
@@ -407,4 +408,12 @@ public void onFailure(int request, Throwable failure)
             stream = null;
         }
     }
+
+    @Override
+    public void close()
+    {
+        if (stream != null)
+            stream.getHttpChannel().onFailure(new EofException());
```
Comment (sbordet) [inline jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java]: `onFailure()` returns a `Runnable` that must be run.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 4]
```diff
@@ -610,6 +610,13 @@ public boolean onIdleExpired(TimeoutException timeout)
         return false; // We've handle the exception
     }
 
+    @Override
+    public void close()
+    {
+        _httpChannel.onFailure(new EofException());
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Ditto.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java]: Done.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Done.

**Review by joakime — DISMISSED** [review]
Anything holding back this from being merged?

**Comment by lorban** [comment]
@joakime not that I know. A final review pass from @sbordet would be preferable but I think I addressed all his concerns.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 5]
```diff
@@ -1065,6 +1059,99 @@ public void close() throws IOException
         assertTrue(closeLatch.await(5, TimeUnit.SECONDS));
     }
 
+    @ParameterizedTest
+    @MethodSource("transports")
+    public void testUploadWithPendingReadConcurrentServerCloseClosesStream(Transport transport) throws Exception
+    {
+        CountDownLatch serverDemandLatch = new CountDownLatch(1);
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java:1066]: What's this for?
Should you not count it down in the server-side demand callback?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java:1066]: Yes, this latch should be counted down after `lastChunk` has been set and awaited before reading it.

**Review by joakime — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 6]
```diff
@@ -610,6 +610,15 @@ public boolean onIdleExpired(TimeoutException timeout)
         return false; // We've handle the exception
     }
 
+    @Override
+    public void close()
+    {
+        Runnable task = _httpChannel.onFailure(new EofException());
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: I don't like creating an `EofException` for every normal close.   
If you really need this, then create a `_httpChannel.onClose()` method that grabs the state lock, checks the state and only creates the exception if it is actually needed.

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java [hunk 7]
```diff
@@ -407,4 +408,16 @@ public void onFailure(int request, Throwable failure)
             stream = null;
         }
     }
+
+    @Override
+    public void close()
+    {
+        if (stream != null)
+        {
+            Runnable task = stream.getHttpChannel().onFailure(new EofException());
```
Comment (gregw) [inline jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java]: See comment on HttpConnection... but I care a little less about FCGI

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 6 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: I added an extra check so the channel is only failed when `_httpChannel.getRequest()` is not null, such as the channel is only failed (and the exception created) only if there is a pending request, which is not the case for a normal close.

That makes the implementation a bit more elegant and takes care of that unneeded exception allocation in the normal case.

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java (hunk 7 above)
Comment (lorban) [reply jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java]: I applied the same change I made in `HttpConnection`.

**Review by sbordet — APPROVED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 8]
```diff
@@ -463,6 +464,21 @@ public Runnable onFailure(Throwable x)
...
+    @Override
+    public Runnable onClose()
+    {
+        try (AutoLock ignored = _lock.lock())
+        {
+            if (LOG.isDebugEnabled())
+                LOG.debug("onClose {} stream={}", this, _stream);
+
+            // If the channel doesn't have a stream, then no action is needed.
+            if (_stream == null)
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:476]: would `_request == null` be a better test.    Do we want an EofException if a connection is opened then closed without a request?

**Review by gregw — APPROVED** [review]
Conditional approval... with one question

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 8 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:476]: I used the `_stream == null` test for consistency with `onFailure()` that tests for that too, but in practice it's identical to `_request == null` as both are reset to null at the same place in `recycle()`.

And I do believe it is correct to fail with a `EofException` when a connection is opened then immediately closed without sending a byte.

@sbordet Do you agree?
