### PR TITLE
Refactor PathSpec and fix javax.websocket URI Template matching

### LINKED ISSUE #4776: Incorrect path matching for WebSocket using PathMappings
**Description**
Currently we use `PathMappings` to do URI mappings to websocket server endpoints. However this does not use the process described in JSR356 and it seems it gives incorrect matches for some cases.

Example:
```java
PathMappings<String> mapping = new PathMappings<>();
mapping.put(new UriTemplatePathSpec("/{a}/b"), "endpointA");
mapping.put(new UriTemplatePathSpec("/{a}/{b}"), "endpointB");
assertThat(mapping.getMatch("/a/b").getResource(), is("endpointA"));
```

As described in the JSR356 we should traverse the segments left to right, and prefer exact matches to those that have variable segments. Because of this we should match `"endpointA"` in this example as its last segment is an exact match, however `PathMappings` currently matches `"endpointB"`.

Paragraph from JSR356 describing the matching process:
```
Since the endpoint paths are either relative URIs or URI templates level 1, the paths do not match if they do
not have the same number of segments, using ’/’ as the separator. So, the container will traverse the segments
of the endpoint paths with the same number of segments as the incoming URI from left to right, comparing
each segment with the corresponding segment of the incoming URI. At each segment, the implementation
will retain those endpoint paths that match exactly, or if there are none, those that are a variable segment,
before moving to check the next segment. If there is an endpoint path at the end of this process there is a
match.
```

### LINKED ISSUE #4877: Review PathSpec classes
The current implementation of PathSpec is an abstract base class with mutable protected fields.
PathSpec itself is immutable once constructed, so it would be best if the fields themselves were final and private.  Perhaps the class should just be an interface?

### PR DESCRIPTION
**Pull request by lorban**
This PR also includes the changes made in https://github.com/eclipse/jetty.project/pull/4788.

The only difference is that https://github.com/eclipse/jetty.project/pull/4788 targets 10.x while this one targets 9.4.x.

Closes #4877
Closes #4776

### CODE REVIEW

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java [hunk 1]
```diff
@@ -18,67 +18,12 @@
 
 package org.eclipse.jetty.http.pathmap;
 
-/**
- * The base PathSpec, what all other path specs are based on
- */
-public abstract class PathSpec implements Comparable<PathSpec>
+public interface PathSpec extends Comparable<PathSpec>
```
Comment (janbartel) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java:24]: While you're editing this file, could you add a header that describes what a PathSpec is.

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/BasePathSpec.java [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+//
+
+package org.eclipse.jetty.http.pathmap;
+
+/**
+ * The base PathSpec, what all other path specs are based on
+ */
+public abstract class BasePathSpec implements PathSpec
+{
+    protected static class Decomposition
```
Comment (janbartel) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/BasePathSpec.java]: I'm not sure I see the benefit of the Decomposition class? What benefit does it give over and above being just  private fields on the BasePathSpec class?

Comment (janbartel) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/BasePathSpec.java]: OK, I've had an offline conversation with @gregw and I see why you might have introduced the Decomposition class. IMHO the behaviour in the base class is so trivial as to not warrant the complexity of introducing the Decomposition class, so I would ditch the BasePathSpec and have ServletPathSpec, RegexPathSpec directly implement the PathSpec interface.

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/BasePathSpec.java [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+//  You may elect to redistribute this code under either of these licenses.
+//  ========================================================================
+//
+
+package org.eclipse.jetty.http.pathmap;
+
+/**
+ * The base PathSpec, what all other path specs are based on
+ */
+public abstract class BasePathSpec implements PathSpec
```
Comment (gregw) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/BasePathSpec.java]: I'm not sure it is worthwhile having `BasePathSpec` and `Decomposition`.

I understand they exist to try and achieve some code reuse between the 3 implementations, but ultimately you are creating two new classes just to save duplicating a few simple getters.

Perhaps a compromise is to keep `Decomposition` available as a getter on the interface, and then have default methods for the ohter getters.    Or just have an abstract base class and no interface.  Or just duplicate the fields/getters in the impls.

I'd probably like `Decomposition` better if it had a better name.... `PathSpecComponets`??? nah still horrid....

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/BasePathSpec.java (hunk 3 above)
Comment (lorban) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/BasePathSpec.java]: `BasePathSpec` doesn't do much, but there's a little more in common between `RegexPathSpec` and `UriTemplatePathSpec`.

It still doesn't justify the `Decomposition`, though so I'll also duplicate that around.

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/BasePathSpec.java (hunk 2 above)
Comment (lorban) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/BasePathSpec.java]: I introduced `Decomposition` more for the bits in common between `RegexPathSpec` and `UriTemplatePathSpec`.

But it's getting apparent now that the code has been written that it's not worth it.

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java (hunk 1 above)
Comment (lorban) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathSpec.java:24]: Sure, I'll do it.

**Review by gregw — APPROVED** [review]

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/LogicalDeclarationComparator.java [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+//
+
+package org.eclipse.jetty.http.pathmap;
+
+import java.util.Comparator;
+
+/**
+ * Sort {@link MappedResource}s by their {@link MappedResource#getPathSpec()} logical declarations.
+ */
+public class LogicalDeclarationComparator implements Comparator<MappedResource>
```
Comment (janbartel) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/LogicalDeclarationComparator.java]: Can we think of a better name than LogicalDeclarationComparator? It's a comparator that works for MappedResources based on their PathSpecs .... is it a MappedResourceComparator? Is it a PathSpecComparator? In fact, could it be an anonymous class defined in PathMappings in the constructor for _mappings at line 49? I can't see where it's used anywhere else, but maybe it is?

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java [hunk 5]
```diff
@@ -56,54 +59,65 @@ public RegexPathSpec(String regex)
...
-            this.group = PathSpecGroup.SUFFIX_GLOB;
-        }
+            group = PathSpecGroup.SUFFIX_GLOB;
         else
-        {
-            this.group = PathSpecGroup.MIDDLE_GLOB;
-        }
+            group = PathSpecGroup.MIDDLE_GLOB;
+
+        //return new RegexDecomposition(declaration, group, pathDepth, specLength, null, null, pattern);
```
Comment (janbartel) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java]: You can delete this line now.

**Review by janbartel — CHANGES_REQUESTED** [review]
If you can remove the one unnecessary comment, and maybe think of a more meaningful name than LogicalDeclarationComparator, then I'm good.

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/LogicalDeclarationComparator.java (hunk 4 above)
Comment (lorban) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/LogicalDeclarationComparator.java]: I think this class should go and be replaced with a lambda in the `PathMappings`' `TreeSet` constructor instead.

Comment (lorban) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/LogicalDeclarationComparator.java]: But since this is @joakime 's code, maybe he had something else in mind?

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java (hunk 5 above)
Comment (lorban) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java]: Indeed, thanks.

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/LogicalDeclarationComparator.java (hunk 4 above)
Comment (joakime) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/LogicalDeclarationComparator.java]: If you can make the tests pass then i'm good with any change you want to make.

Comment (lorban) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/LogicalDeclarationComparator.java]: Okay, done.

**Comment by joakime** [comment]
I'd like to hold off on merging this one until we can get 9.4.29 released officially

**Comment by lachlan-roberts** [comment]
We good to merge this now 9.4.29 is out?

**Comment by joakime** [comment]
Yes.
