### PR TITLE
Fix #9953 handled HEAD

### LINKED ISSUE #9953: Jetty 12.0 Handle HEAD requests in Handler
Hi,

I work on the Spring Framework, where we are in the process of upgrading to Jetty 12 as part of our 6.1 branch. As part of this migration, I have run into an issue.

This issue occurs when an asynchronous `WriteListener` does not write the amount of bytes specified in `Content-Length`. This is fine for typical requests, but not for `HEAD` requests, given [Section 14.13 of RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13):

> The Content-Length entity-header field indicates the size of the entity-body [...] sent to the recipient or, **in the case of the HEAD method, the size of the entity-body that would have been sent had the request been a GET**.

The following Servlet can be used to reproduce this issue:

```java
@WebServlet(urlPatterns={"/"}, asyncSupported=true)
public class AsyncServlet extends GenericServlet {
	@Override
	public void service(ServletRequest req, ServletResponse res) throws IOException {
		HttpServletRequest request = (HttpServletRequest) req;
		if (request.getMethod().equals("GET") || request.getMethod().equals("HEAD")) {
			AsyncContext context = req.startAsync();
			res.getOutputStream().setWriteListener(new HeadWriteListener(context));
		}
		else {
			HttpServletResponse response = (HttpServletResponse) res;
			response.sendError(404);
		}
	}

	private static class HeadWriteListener implements WriteListener {
		private final AsyncContext context;

		public HeadWriteListener(AsyncContext context) {
			this.context = context;
		}

		@Override
		public void onWritePossible() throws IOException {
			HttpServletRequest req = (HttpServletRequest) this.context.getRequest();
			HttpServletResponse resp = (HttpServletResponse) this.context.getResponse();
			resp.setContentType("text/plain");
			resp.setContentLength(9);
			if (req.getMethod().equals("GET")) {
				try (ServletOutputStream outputStream = resp.getOutputStream()) {
					outputStream.write("FooBarBaz".getBytes(UTF_8));
				}
			}
			this.context.complete();
		}

		@Override
		public void onError(Throwable t) {
			t.printStackTrace();
		}
	}
}
```

Running this servlet on Jetty 12.0 beta 2 results in the following exception in `HttpChannelState`:

```
java.io.IOException: written 0 < 9 content-length
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1208)
	at org.eclipse.jetty.ee10.servlet.HttpOutput.channelWrite(HttpOutput.java:215)
	at org.eclipse.jetty.ee10.servlet.HttpOutput.complete(HttpOutput.java:447)
	at org.eclipse.jetty.ee10.servlet.ServletContextResponse.completeOutput(ServletContextResponse.java:209)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:625)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:458)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:798)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:611)
	at org.eclipse.jetty.server.Server.handle(Server.java:177)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:617)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:480)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:436)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
**Jetty version(s)**
Jetty 12.0 beta2

**Java version/vendor** `(use: java -version)`

openjdk version "17.0.7" 2023-04-18 LTS

### PR DESCRIPTION
**Pull request by gregw**
Fix #9953 so that if a Handler self handles HEAD by not writing content, then the length checks do not fire if 0 bytes have been written.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 1]
```diff
@@ -1193,11 +1193,14 @@ public void write(boolean last, ByteBuffer content, Callback callback)
                 else
                 {
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1193]: Extra cleanup proposal:
`long totalWritten` and `HttpChannelState httpChannelState` could be moved within the `try` block.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 2]
```diff
@@ -1193,11 +1193,14 @@ public void write(boolean last, ByteBuffer content, Callback callback)
...
                     failure = getFailure(httpChannelState);
-                    if (failure == null && contentLength >= 0)
+                    if (failure == null && contentLength >= 0 && totalWritten != contentLength)
                     {
                         // If the content length were not compatible with what was written, then we need to abort.
-                        String lengthError = (totalWritten > contentLength) ? "written %d > %d content-length"
-                            : (last && totalWritten < contentLength) ? "written %d < %d content-length" : null;
+                        String lengthError = null;
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1198]: There doesn't seem to be any test coverage for when `lengthError != null`

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1198]: Thanks the normal path?!?!?

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1198]: That is the normal path and is explicitly tested by the HEAD requests with no body.

**Review by lorban — APPROVED** [review]
