### PR TITLE
Fixes #9121 - Flaky BlockedWritesWithSmallThreadPoolTest.testServerThreadsBlockedInWrites().

### LINKED ISSUE #9121: Jetty 12 - Flaky BlockedWritesWithSmallThreadPoolTest.testServerThreadsBlockedInWrites()
**Jetty version(s)**
12+

**Description**
In Jetty 11, writes from a `Handler` via `response.getOutputStream()` are blocking, but internally that blocking call is converted into a non-blocking call typically via:
```java
try (Blocker blocker = _writeBlocker.acquire())
{
    channelWrite(content, complete, blocker);
    blocker.block();
}
```
where `blocker.invocationType==NON_BLOCKING`.

For large writes that TCP congest, this means that task `SelectableChannelEndPoint._runCompleteWrite` is non-blocking; in case all threads are taken, unblocking a write is possible because the task is non-blocking and will be run by the selector thread when it wakes up being write-ready.

In Jetty 12, writes from a `Handler` receive a `Callback` whose `invocationType` depends on the `HttpStream` implementation.
All of them do not override `getInvocationType()` so they are all blocking.
This means that task `SelectableChannelEndPoint._runCompleteWrite` is blocking; in case all threads are taken the task will be queued, rather than executed by the selector thread, therefore locking up the server as it is the task that would have unblocked a write, but there are no threads to execute it.

This is the reason of the flakyness of this test: sometimes there always is a thread that can run the `completeWrite` task, but in some cases there is not and the test fails.

### PR DESCRIPTION
**Pull request by sbordet**
The test uncovered a larger problem detailed in the issue: the Handler Callback should be non-blocking.

Since all implementations of HttpStream are non-blocking, overridden HttpStream.getInvocationType() to return NON_BLOCKING.

This guarantees that even in case of all server threads blocked, blocked/pending writes can be completed.

### CODE REVIEW

**Review by gregw — APPROVED** [review]

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/BlockedWritesWithSmallThreadPoolTest.java [hunk 1]
```diff
@@ -100,19 +100,19 @@ public void dispose()
...
         {
             @Override
-            public boolean handle(Request request, Response response, Callback callback)
+            public boolean handle(Request request, Response response, Callback callback) throws Exception
             {
                 serverEndPointRef.compareAndSet(null, (AbstractEndPoint)request.getConnectionMetaData().getConnection().getEndPoint());
-                // Write a large content to cause TCP congestion.
-                response.write(true, ByteBuffer.wrap(new byte[contentLength]), callback);
+                // Blocking write a large content to cause TCP congestion.
+                Content.Sink.write(response, true, ByteBuffer.wrap(new byte[contentLength]));
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/BlockedWritesWithSmallThreadPoolTest.java:114]: Can we test both async and blocking writes here?

**Review by gregw — CHANGES_REQUESTED** [review]

**Review by gregw — APPROVED** [review]
