### PR TITLE
Issue #13409 ensure classpath Resource conversion uses full path

### LINKED ISSUE #13409: Jetty fails to discover WebFragments in Library Files on classpath
**Jetty version(s)**
>12.0.13
Reproduced with 12.0.14 and 12.0.23

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
Eclipse Temurin 21.0.8

**OS type/version**
Win11 - also reproducable in Docker environment

**Description**

After upgrading past Jetty 12.0.13 with ee10 my application is no longer able to detect webfragments from my libraries.

Some debugging shows that the issue is different types used in a map and to query said map. This happens here:
``org/eclipse/jetty/ee10/webapp/MetaData.java:495``

The map contains resources of type ``PathResource`` and the resource used for the lookup is of the type ``MountedPathResource``, which is a subclass - this makes the equality-check fail.

It seems that there was a change in how the resources being used to query the map has been calculated between versions 12.0.13 and 12.0.14 where the issue started:

See the file ``jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaInfConfiguration.java`` in the comparison https://github.com/jetty/jetty.project/compare/jetty-12.0.13...jetty-12.0.14

**How to reproduce?**

Create a small library with a webfragment, and have it published as a jar.
Create a new project importing said library, and see that the mappings from the webfragment are not respected.

### PR DESCRIPTION
**Pull request by janbartel**
closes #13409

The problem described in #13409 has 2 parts to it:

1.  #11092 converted all classpath jars into `MountedPathResource` instead of `PathResource`
2.  after the change in #10889 to use non-ephemeral `Resources` to refer to the results of scanning for `web-fragment.xml`, `*.tld` and `META-INF/resources` (so that we avoid keeping mount points around for jars that don't actually contain any of these things), whenever we compare `Resources` we must ensure that their `path`s are the same.

For example, when running with a command line like:

> java -cp target/dependency/*:target/application-1.0.jar  some.Main

and `target/dependency/library-1.0.jar` contains a `web-fragment.xml` we see the following:

The container `Resource` is a `MountedPathResource` and has:

```
path = /
uri = jar:file:///home/janb/src/tmp/application/target/dependency/library-1.0.jar!/
```
The `Resource` of the jar known to contain the `web-fragment.xml` is a `PathResource` and has:

```
path=/home/janb/src/tmp/application/target/dependency/library-1.0.jar
uri=file:///home/janb/src/tmp/application/target/dependency/library-1.0.jar
```
As can be seen, there are 2 problems:

1 A comparison of these 2 resources fails because `MountedPathResource` is not a `PathResource` 
2 Even if they were both `PathResources`, the paths are different 

Reverting the change to `MetaInfConfiguration` from #11092, we now have both `Resources` as `PathResource`, but one resource has a relative path whilst the other is fully qualified:

The container `Resource`  has:

```
path=target/dependency/library-1.0.jar
uri=file:///home/janb/src/tmp/application/target/dependency/library-1.0.jar
```

The `Resource` that represents the jar with fragment has:

```
path=/home/janb/src/tmp/application/target/dependency/library-1.0.jar
uri=file:///home/janb/src/tmp/application/target/dependency/library-1.0.jar
```

This PR reverts the change from #11092, but also ensures that _both_ the container `Resource` and jar containing the fragment `Resource` have fully qualified paths.

@joakime is there a way to modify your change from #11092 to keep some of the goodness, but ensure that it doesn't always create `MountedPathResource`? We definitely don't want to always do the mount, because we only want to mount if we are going to be keeping the resource around because it has something useful in it (ie see the changes we made in #10889). We do need to retain the fix in this PR to ensure that the paths are fully qualified.

### CODE REVIEW

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaInfConfiguration.java [hunk 1]
```diff
@@ -168,10 +169,17 @@ public void findAndFilterContainerPaths(final WebAppContext context) throws Exce
...
         {
-            resourceFactory.split(classPath, File.pathSeparator)
-                .stream()
+            //The classpath may contain relative paths of jar files etc. We
+            //must convert these relative paths to full paths. This is because
+            //in eg scanForFragment, the web-fragment.xml Resource is a
+            //fully qualified path. In MetaData.resolve() we compare this
+            //fully qualified path with the container Resources, and thus both
+            //must be fully qualified for a match (as per PathResource.equals() method).
+            Stream.of(classPath.split(File.pathSeparator))
```
Comment (joakime) [inline jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaInfConfiguration.java]: This should be fixed in resourceFactory.split() instead, as that's used from multiple place that need this same logic.  (eg: WebAppContext.setExtraClassPath())

**Review by joakime — CHANGES_REQUESTED** [review]
The fix should be in ResourceFactory.split()

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/CombinedResourceTest.java [hunk 2]
```diff
@@ -455,6 +457,15 @@ public void testUserSpaceConfigurationWithGlob() throws Exception
 
         // To use this, we need to split it (and optionally honor globs)
         List<Resource> resources = resourceFactory.split(config);
+
+        // Perform Archive file mounting (if needed)
+        for (ListIterator<Resource> i = resources.listIterator(); i.hasNext(); )
+        {
+            Resource resource = i.next();
+            if (resource.exists() && !resource.isDirectory() && FileID.isLibArchive(resource.getName()))
+                i.set(resourceFactory.newResource(URIUtil.toJarFileUri(resource.getURI())));
```
Comment (joakime) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/CombinedResourceTest.java:466]: This would eliminate the previous Resource that might need to be cleaned up by a future the ResourceFactory close (this looks like a Resource leak).

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java [hunk 3]
```diff
@@ -311,33 +314,59 @@ public void testNewResource(String inputRaw, String expectedUri)
...
-    public void testSplitSingleJar()
+    public void testSplitSingleJar() throws URISyntaxException
     {
         try (ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable())
         {
             Path testJar = MavenPaths.findTestResourceFile("jar-file-resource.jar");
             String input = testJar.toUri().toASCIIString();
             List<Resource> resources = resourceFactory.split(input);
-            String expected = URIUtil.toJarFileUri(testJar.toUri()).toASCIIString();
+            String expected = testJar.toUri().toASCIIString();
```
Comment (joakime) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:324]: This is the same value as `input` now.
Seems wrong, as the result of `ResourceFactory.split()` should be the mounted JAR.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java [hunk 4]
```diff
@@ -311,33 +314,59 @@ public void testNewResource(String inputRaw, String expectedUri)
...
-    public void testSplitSinglePath()
+    public void testSplitSinglePath() throws URISyntaxException
     {
         try (ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable())
         {
             Path testJar = MavenPaths.findTestResourceFile("jar-file-resource.jar");
             String input = testJar.toString();
             List<Resource> resources = resourceFactory.split(input);
-            String expected = URIUtil.toJarFileUri(testJar.toUri()).toASCIIString();
+            String expected = testJar.toUri().toASCIIString();
```
Comment (joakime) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:337]: Ditto (from above)

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java [hunk 5]
```diff
@@ -311,33 +314,59 @@ public void testNewResource(String inputRaw, String expectedUri)
...
         }
     }
 
     @Test
-    public void testSplitOnComma()
+    public void testSplitIsAbsolute() throws Exception
+    {
+        try (ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable())
+        {
+            String config = String.format("%s,%s,%s,%s,%s,%s", "dir/a", "foo/b", "bar/c", "jar:file:///foo/bar.jar!/", "file:///foo/bar.jar", "/foo/bar.jar");
```
Comment (joakime) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:347]: All of these would need to exist for this test to be valid.

**Review by joakime — CHANGES_REQUESTED** [review]
Some thoughts

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java (hunk 3 above)
Comment (janbartel) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:324]: We cannot let `ResourceFactory.split()` do any jar mounting, otherwise we wind up with system resources being consumed for jars that ultimately don't contain anything that we are interested in.  That was the problem that we fixed in #10889. It can only be the caller of `split()` that can decide if it needs to mount in order to use the individual resources.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java (hunk 5 above)
Comment (janbartel) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:347]: Not really, if you read further in the test, we're just testing certain things about how it is converted, not that they exist. The comments explain it.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/CombinedResourceTest.java (hunk 2 above)
Comment (janbartel) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/CombinedResourceTest.java:466]: You always have to be aware that Resources you obtain from a ResourceFactory have to be cleaned up.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java [hunk 6]
```diff
@@ -499,25 +505,40 @@ default List<Resource> split(String str, String delims)
...
+                    // that point to the same resource but one is relative and one is absolute
+                    // will fail.
+                    if (URIUtil.hasScheme(reference))
+                    {
+                        // Could be a jar:file url, ensure it is unwrapped back to the file
+                        // otherwise it will be a MountedPathResource and consume a mount point
+                        // that might be unnecessary - the caller should always decide whether to mount
+                        URI uri = new URI(reference);
+                        if (unwrap)
+                            list.add(newResource(URIUtil.unwrapContainer(uri)));
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:520]: Should we throw here if the path inside the jar is not / ?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java [hunk 7]
```diff
@@ -499,25 +505,40 @@ default List<Resource> split(String str, String delims)
...
+                        else
+                            list.add(newResource(uri.toASCIIString()));
+                    }
+                    else
+                    {
+                        Path p = Paths.get(reference);
+                        if (!p.isAbsolute() && LOG.isDebugEnabled())
+                            LOG.warn("Non-absolute path: {}", reference);
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:528]: throw rather than warn?

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaInfConfiguration.java [hunk 8]
```diff
@@ -168,10 +168,10 @@ public void findAndFilterContainerPaths(final WebAppContext context) throws Exce
         String classPath = System.getProperty("java.class.path");
         if (classPath != null)
         {
-            resourceFactory.split(classPath, File.pathSeparator)
+            resourceFactory.split(classPath, File.pathSeparator, true)
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/MetaInfConfiguration.java:174]: maybe a comment here on why you are passing true

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java [hunk 9]
```diff
@@ -1259,7 +1260,7 @@ public List<Resource> getExtraClasspath()
      */
     public void setExtraClasspath(String extraClasspath)
     {
-        setExtraClasspath(getResourceFactory().split(extraClasspath));
+        setExtraClasspath(getResourceFactory().split(extraClasspath, File.pathSeparator, true));
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java:1266]: ditto

File: jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaInfConfiguration.java [hunk 10]
```diff
@@ -170,10 +170,10 @@ public void findAndFilterContainerPaths(final WebAppContext context) throws Exce
         String classPath = System.getProperty("java.class.path");
         if (classPath != null)
         {
-            resourceFactory.split(classPath, File.pathSeparator)
+            resourceFactory.split(classPath, File.pathSeparator, true)
```
Comment (gregw) [inline jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaInfConfiguration.java:176]: ditto

File: jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppContext.java [hunk 11]
```diff
@@ -1267,7 +1267,7 @@ public List<Resource> getExtraClasspath()
      */
     public void setExtraClasspath(String extraClasspath) throws IOException
     {
-        setExtraClasspath(getResourceFactory().split(extraClasspath));
+        setExtraClasspath(getResourceFactory().split(extraClasspath, File.pathSeparator, true));
```
Comment (gregw) [inline jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppContext.java:1273]: ditto

**Review by gregw — DISMISSED** [review]
A couple of niggles but otherwise OK

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java (hunk 7 above)
Comment (janbartel) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:528]: I think it's caller dependent - `MetaInfConfiguration` will have a problem if it's not an absolute path, but other callers may be ok with that.

Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:528]: It should always return absolute Resource paths IMO.
Since this method returns `Resource`, there's no real useful way to work with relative paths in any way other than to convert it to absolute first.

How about ...

``` java
   Path p = Path.of(reference).toAbsolutePath(); // enforce absolute path.
```

The `Path.of(String)` will happily accept absolute, and relative strings.
We don't have to worry about URI strings, as that's a different code path protected by the `if (URIUtil.hasScheme(reference))` earlier.

The `Path.toAbsolutePath()` will just return the path if it's already absolute, but fix it if isn't absolute.

```
jshell> var p1 = Path.of("12.0.x/jetty-core/pom.xml")
p1 ==> 12.0.x/jetty-core/pom.xml

jshell> p1.toAbsolutePath()
$2 ==> /home/joakim/code/jetty/12.0.x/jetty-core/pom.xml

jshell> var p2 = Path.of("/home/joakim/code/jetty/9.4.x/jetty-util/src/main/config/modules/console-capture.mod")
p2 ==> /home/joakim/code/jetty/9.4.x/jetty-util/src/main ... odules/console-capture.mod

jshell> p2.toAbsolutePath()
$4 ==> /home/joakim/code/jetty/9.4.x/jetty-util/src/main/config/modules/console-capture.mod
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java (hunk 6 above)
Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:520]: Nah, that's a valid use case IMO

Comment (janbartel) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:520]: Maybe, but not necessary???

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java (hunk 7 above)
Comment (janbartel) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:528]: If you look at the line below the `throw` you will see that we always convert to absolute path, so I think your concern is already addressed.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java (hunk 6 above)
Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:520]: This isn't a restriction we need (right now)

**Review by joakime — APPROVED** [review]

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java [hunk 12]
```diff
@@ -1259,7 +1260,10 @@ public List<Resource> getExtraClasspath()
      */
     public void setExtraClasspath(String extraClasspath)
     {
-        setExtraClasspath(getResourceFactory().split(extraClasspath));
+        //convert classpath into Resources. Any jar:file: references will be
+        //unwrapped, because we need the location of the file, not the contents
+        //of the file
+        setExtraClasspath(getResourceFactory().split(extraClasspath, File.pathSeparator, true));
```
Comment (timja) [inline jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java:1266]: Caused https://github.com/jetty/jetty.project/issues/13698
