### PR TITLE
Fixes #2828 - AbstractHTTP2ServerConnectionFactory concurrent connect low performance.

### LINKED ISSUE #2828: connectionListener of AbstractHTTP2ServerConnectionFactory cause the low performance of concurrent connect of http2
Hi,
   Thanks for your project. and i like jetty very much.I am writing one http2 server based on Jetty 9.4.x
    Now I got one question,i found that:
     One server can accept and hold  connections up to 460,000 connections in one connection server if  clients make connections: 50000 by 50000 through several client pc.
     But  the server can only  accept  up to about 160000 connections if the clients connect server 'at the same time', for example: 5 client pc make 300000 connection at the same time.(through multi ip), The other connect client get an connect timeout exception . And i found the recv-q multi in the server jvm.
    I dump the jvm stack and found this:

```
"qtp1620112330-73" #73 prio=5 os_prio=0 tid=0x00007f1038001000 nid=0xcca40 waiting on condition [0x00007f10c24e5000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007f122869a050> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at java.util.concurrent.CopyOnWriteArrayList.add(CopyOnWriteArrayList.java:436)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:283)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:267)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addManaged(ContainerLifeCycle.java:362)
	at org.eclipse.jetty.http2.server.AbstractHTTP2ServerConnectionFactory$ConnectionListener.onOpened(AbstractHTTP2ServerConnectionFactory.java:226)
	at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:202)
	at org.eclipse.jetty.http2.HTTP2Connection.onOpen(HTTP2Connection.java:116)
	at org.eclipse.jetty.http2.server.HTTP2ServerConnection.onOpen(HTTP2ServerConnection.java:147)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:440)
	at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:131)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
```

I read the source and found that:

```
private final Connection.Listener connectionListener = new ConnectionListener();
```

the connectionListener object cause the lock.
and an comment it to test.

I got the better performance  accept the connection more faster and more connection and have no timeout.

so ,how about  remove the member connectionListener of AbstractHTTP2ServerConnectionFactory for more high performance? or other solution?

### PR DESCRIPTION
**Pull request by sbordet**
Now HTTP/2 sessions are not added to the Jetty component tree,
but rather just held by HTTP2SessionContainer that is added to
the Jetty container tree at startup.

HTTP2SessionContainer uses a concurrent Set to hold HTTP/2 sessions
to have good add/remove performance.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java [hunk 1]
```diff
@@ -245,18 +252,43 @@ protected ServerParser newServerParser(Connector connector, ServerParser.Listene
...
     {
+        private final Set<Session> sessions = ConcurrentHashMap.newKeySet();
+
         @Override
         public void onOpened(Connection connection)
         {
-            addManaged((LifeCycle)((HTTP2Connection)connection).getSession());
+            Session session = ((HTTP2Connection)connection).getSession();
+            sessions.add(session);
+            LifeCycle.start(session);
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java]: if start throws an exception, will onClosed be called to remove it?

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java [hunk 2]
```diff
@@ -245,18 +252,43 @@ protected ServerParser newServerParser(Connector connector, ServerParser.Listene
         return new ServerParser(connector.getByteBufferPool(), listener, getMaxDynamicTableSize(), getHttpConfiguration().getRequestHeaderSize());
     }
 
-    private class ConnectionListener implements Connection.Listener
+    private class HTTP2SessionContainer implements Connection.Listener, Dumpable
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java]: make this a `ManagedObject` and `dump()` a `ManagedOperation`, so we can dump just the sessions from JMX.  Also make the size of the sessions collection a managed attribute.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java (hunk 1 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java]: Historically, if an exception was thrown from a `Connection.Listener` we let it unwind the stack, which I don't think it's ideal.
I think such listeners should be wrapped in `try/catch`, log the exception and continue.
So either we wrap, or we leave it as is. I'm for wrapping.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java (hunk 2 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.java]: Good suggestions, will do.
