### PR TITLE
Fixes #10919 - EE10 multipart parsing may include '\r' at the front under certain conditions

### LINKED ISSUE #10919: EE10 multipart parsing may include '\r' at the front under certain conditions
**Jetty version(s)**
12.0.3

**Jetty Environment**
ee10

**Java version/vendor**

> openjdk version "21.0.1" 2023-10-17 LTS
> OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
> OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)

**OS type/version**
Arch Linux

**Description**
Under certain conditions the multi-part form parsing will add a wrong `'\r'` character at the front of the content. The issue seems to only occur for requests in "chunked" transfer encoding and depends on the position in the multi-part data (see tests below).

I am not 100% sure about the specifics of mime-multipart, so it could also be an error in the request. But the issue did not occur in previous versions of jetty (at the very least not in version 11 where this works), it also does not occur in "ee9" environment and not when sending to the real target (some old Perl-CGI).

**How to reproduce?**

Adding this test to MultiPartServletTest.java will fail at `assertEquals("abcde", content1)` because `content1` will contain `"\rabcde"` instead of the expected "abcde".

```java
    // to be used in org.eclipse.jetty.ee10.servlet.MultiPartServletTest
    @Test
    public void testCRLFChunkedBug() throws Exception
    {
        start(new HttpServlet()
        {
            @Override
            protected void service(HttpServletRequest request, HttpServletResponse response1) throws ServletException, IOException
            {
                assertEquals(2, request.getParts().size());
                Part part = request.getPart("file_upload");
                final String content1 = IO.toString(part.getInputStream(), UTF_8);
                assertEquals("abcde", content1);
            }
        }, null, false);

        try (Socket socket = new Socket("localhost", connector.getLocalPort()))
        {
            OutputStream output = socket.getOutputStream();

            String content = """
              90\r
              --908d442b-2c7d-401a-ab46-7c6ec6f89fe6\r
              Content-Disposition: form-data; name="az"\r
              Content-Type: text/plain; charset=ISO-8859-1\r
              \r
              upload_file\r
              \r
              94\r
              --908d442b-2c7d-401a-ab46-7c6ec6f89fe6\r
              Content-Disposition: form-data; name="file_upload"; filename="testUpload.test"\r
              Content-Type: text/plain\r
              \r
              5\r
              abcde\r
              2\r
              \r
              28\r
              --908d442b-2c7d-401a-ab46-7c6ec6f89fe6--\r
              0\r
              \r
              """;
            String header = """
                POST / HTTP/1.1\r
                Host: localhost\r
                Transfer-encoding: chunked\r
                Content-Type: multipart/form-data; boundary=908d442b-2c7d-401a-ab46-7c6ec6f89fe6\r
                \r
                """;

            output.write(header.getBytes(UTF_8));
            output.write(content.getBytes(UTF_8));
            output.flush();

            HttpTester.Response response = HttpTester.parseResponse(socket.getInputStream());
            assertNotNull(response);
            assertEquals(HttpStatus.OK_200, response.getStatus());
        }
    }
```

If you move the `file_upload` part within the multipart-section to the top, it will work and give me `"abcde"`. The code for this is included in the folded section below.

Additionally I created a testcase for the MultiPartServletTest.java of the ee9 module where the same request will have the expected result `"abcde"`. This is also included in the folded section below.

<details>
<summary>More testcases</summary>

```java

    // to be used in org.eclipse.jetty.ee10.servlet.MultiPartServletTest
    @Test
    public void testCRLFChunkedBug() throws Exception
    {
        start(new HttpServlet()
        {
            @Override
            protected void service(HttpServletRequest request, HttpServletResponse response1) throws ServletException, IOException
            {
                assertEquals(2, request.getParts().size());
                Part part = request.getPart("file_upload");
                final String content1 = IO.toString(part.getInputStream(), UTF_8);
                assertEquals("abcde", content1);
            }
        }, null, false);

        try (Socket socket = new Socket("localhost", connector.getLocalPort()))
        {
            OutputStream output = socket.getOutputStream();

            String content = """
              94\r
              --908d442b-2c7d-401a-ab46-7c6ec6f89fe6\r
              Content-Disposition: form-data; name="file_upload"; filename="testUpload.test"\r
              Content-Type: text/plain\r
              \r
              5\r
              abcde\r
              2\r
              \r
              90\r
              --908d442b-2c7d-401a-ab46-7c6ec6f89fe6\r
              Content-Disposition: form-data; name="az"\r
              Content-Type: text/plain; charset=ISO-8859-1\r
              \r
              upload_file\r
              \r
              28\r
              --908d442b-2c7d-401a-ab46-7c6ec6f89fe6--\r
              0\r
              \r
              """;
            String header = """
                POST / HTTP/1.1\r
                Host: localhost\r
                Transfer-encoding: chunked\r
                Content-Type: multipart/form-data; boundary=908d442b-2c7d-401a-ab46-7c6ec6f89fe6\r
                \r
                """;

            output.write(header.getBytes(UTF_8));
            output.write(content.getBytes(UTF_8));
            output.flush();

            HttpTester.Response response = HttpTester.parseResponse(socket.getInputStream());
            assertNotNull(response);
            assertEquals(HttpStatus.OK_200, response.getStatus());
        }
    }
```

Testcase for `org.eclipse.jetty.ee9.servlet.MultiPartServletTest` (this will work because the bug does not occur for ee9)

```java
    // to be used in org.eclipse.jetty.ee9.servlet.MultiPartServletTest
    @Test
    public void testCRLFChunkedForEE9_NoBug() throws Exception
    {
        MultipartConfigElement config = new MultipartConfigElement(tmpDir.toAbsolutePath().toString(), MAX_FILE_SIZE, -1, 1);
        ServletHolder servletHolder = new ServletHolder(new HttpServlet() {
            @Override
            protected void service(HttpServletRequest request, HttpServletResponse resp) throws ServletException, IOException {
                assertEquals(2, request.getParts().size());
                Part part = request.getPart("file_upload");
                final String content1 = IO.toString(part.getInputStream(), UTF_8);
                assertEquals("abcde", content1);
            }
        });
        servletHolder.getRegistration().setMultipartConfig(config);
        contextHandler.addServlet(servletHolder, "/testCRLFChunkedBug");

        try (Socket socket = new Socket("localhost", connector.getLocalPort())) {
            OutputStream output = socket.getOutputStream();

            String content = """
              90\r
              --908d442b-2c7d-401a-ab46-7c6ec6f89fe6\r
              Content-Disposition: form-data; name="az"\r
              Content-Type: text/plain; charset=ISO-8859-1\r
              \r
              upload_file\r
              \r
              94\r
              --908d442b-2c7d-401a-ab46-7c6ec6f89fe6\r
              Content-Disposition: form-data; name="file_upload"; filename="testUpload.test"\r
              Content-Type: text/plain\r
              \r
              5\r
              abcde\r
              2\r
              \r
              28\r
              --908d442b-2c7d-401a-ab46-7c6ec6f89fe6--\r
              0\r
              \r
              """;
            String header = """
              POST /testCRLFChunkedBug HTTP/1.1\r
              Host: localhost\r
              Transfer-encoding: chunked\r
              Content-Type: multipart/form-data; boundary=908d442b-2c7d-401a-ab46-7c6ec6f89fe6\r
              \r
              """;

            output.write(header.getBytes(UTF_8));
            output.write(content.getBytes(UTF_8));
            output.flush();

            HttpTester.Response response = HttpTester.parseResponse(socket.getInputStream());
            assertNotNull(response);
            assertEquals(HttpStatus.OK_200, response.getStatus());
        }
    }
```
</details>

### PR DESCRIPTION
**Pull request by sbordet**
Setting MultiPart.Parser.crContent=false when the boundary is matched. This is necessary when a read chunk ends with \r\n, and then matches the boundary on the next read chunk, and avoids to emit the CR as part content.

### CODE REVIEW

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 1]
```diff
@@ -1371,6 +1371,15 @@ private boolean parseContent(Content.Chunk chunk)
             int boundaryOffset = boundaryFinder.match(buffer);
             if (boundaryOffset >= 0)
             {
+                // Output as content the previous partial match, if any.
+                if (crContent)
+                {
+                    crContent = false;
+                    Content.Chunk partContentChunk = Content.Chunk.from(CR.slice(), false);
```
Comment (lorban) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Why duplicating the chunk?

Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: What duplication are you referring to?

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 2]
```diff
@@ -1370,6 +1365,8 @@ private boolean parseContent(Content.Chunk chunk)
             int boundaryOffset = boundaryFinder.match(buffer);
             if (boundaryOffset >= 0)
             {
+                // Output as content the previous partial match, if any.
+                notifyCRContent();
```
Comment (lachlan-roberts) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1371]: I don't think this is correct.

If we matched `\n--Boundary` at position 0. Then the previous `\r` is part of the boundary and should not be emitted as content.

**Review by lachlan-roberts — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1371]: Good catch, fixed.

**Review by lachlan-roberts — APPROVED** [review]
