### PR TITLE
Fixes #12300: add null check in RewriteHandler.doStart() and unit test

### LINKED ISSUE #12300: Use of RewriteHandler.LastRuleHandler without a child handler should produce a clear error message.
**Jetty version(s)**
12.0.13

**Jetty Environment**
Any

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
If an instance of a `Handler.Wrapper` without a child is allowed to start and begin handling requests, the error message is unclear.

`java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.server.Request$Handler.handle(org.eclipse.jetty.server.Request, org.eclipse.jetty.server.Response, org.eclipse.jetty.util.Callback)" because "this._handler" is null`

We should make the start of this kind of handler fail the start and throw a meaningful message that the `Handler.Wrapper` is missing a child.

### PR DESCRIPTION
**Pull request by sanjerai**
Added null check in RewriteHandler#doStart() to prevent misuse when no child Handler is set. included a test verifying the behavior.

### CODE REVIEW

**Comment by joakime** [comment]
@sanjerai we need a signed Eclipse ECA in order to merge this.  This is a requirement by the Eclipse Foundation Legal department.

See: https://github.com/jetty/jetty.project/blob/jetty-12.0.x/CONTRIBUTING.md#eclipse-contributor-agreement

**Comment by sanjerai** [comment]
@joakime thank you. i have signed the ECA

**Comment by joakime** [comment]
Last build fails due to checkstyle violation.

```
[INFO] --- checkstyle:3.6.0:check (checkstyle-check) @ jetty-rewrite ---
[INFO] Starting audit...
[WARN] /home/jenkins/agent/workspace/jetty.project_PR-13358/jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java:147:47: '{' at column 47 should be on a new line. [LeftCurly]
[WARN] /home/jenkins/agent/workspace/jetty.project_PR-13358/jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java:148:35: '{' at column 35 should be on a new line. [LeftCurly]
[WARN] /home/jenkins/agent/workspace/jetty.project_PR-13358/jetty-core/jetty-rewrite/src/test/java/org/eclipse/jetty/rewrite/handler/RewriteHandlerTest.java:128:49: '{' at column 49 should be on a new line. [LeftCurly]
Audit done.
[WARNING] src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java:[147,47] (blocks) LeftCurly: '{' at column 47 should be on a new line.
[WARNING] src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java:[148,35] (blocks) LeftCurly: '{' at column 35 should be on a new line.
[WARNING] src/test/java/org/eclipse/jetty/rewrite/handler/RewriteHandlerTest.java:[128,49] (blocks) LeftCurly: '{' at column 49 should be on a new line.
```

You can replicate this on your local machine by running a command line build.

```
$ mvn -Pci clean install -DskipTests
```

Also, if you want to integrate your IDE's checkstyle checker, the checkstyle rules are present in git as well.
See: https://github.com/jetty/jetty.project/blob/jetty-12.1.x/build/build-resources/src/main/resources/jetty-checkstyle.xml

**Comment by sbordet** [comment]
@sanjerai @joakime `RewriteHandler` can have a `null` child, for example in those cases where all the rules are "terminating" rules, such as redirects, or validity rules that produce an error response.

This PR would be a breaking behavior change for those cases where `RewriteHandler` has a `null` child.

@gregw opinions?

**Comment by sbordet** [comment]
@sanjerai what is the exact use case that prompted you to issue this PR?

File: jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java [hunk 1]
```diff
@@ -143,6 +143,17 @@ public boolean handle(Request request, Response response, Callback callback) thr
         return input.handle(response, callback);
     }
 
+    @Override
+    protected void doStart() throws Exception
+    {
+        if (getHandler() == null)
```
Comment (sbordet) [inline jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java]: See the other comment, I think having a `null` child `Handler` could be a legit use case.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by sanjerai** [comment]
@sbordet i did changes for this [Bug](https://github.com/jetty/jetty.project/issues/12300)

File: jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java (hunk 1 above)
Comment (sanjerai) [reply jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java]: @sbordet in that case should i change it to a warning log only

**Comment by sbordet** [comment]
@sanjerai I think a better fix would be to change `LastRuleHandler.handle()` and throw the `IllegalStateException` there.

**Comment by gregw** [comment]
> @sanjerai @joakime `RewriteHandler` can have a `null` child, for example in those cases where all the rules are "terminating" rules, such as redirects, or validity rules that produce an error response.
> 
> This PR would be a breaking behavior change for those cases where `RewriteHandler` has a `null` child.
> 
> @gregw opinions?

I do not think it is an error to have a null Handler.   If it was, we should fix in Handler.Wrapper, not just here.

I'm fine to add some debug to note this case, but not to throw ISE.

**Comment by sanjerai** [comment]
@gregw @sbordet i hope we are fine with ISE from LastRuleHandler (PR code updated)
this should take care of scenario where handler is null in case of a non terminating Rule

**Review by sbordet — APPROVED** [review]

**Comment by gregw** [comment]
I'm good with an ISE.
