### PR TITLE
#7461 Fix flakey ConnectionPoolTest.testQueuedRequestsDontOpenTooManyConnections: 

### LINKED ISSUE #7461: Flaky ConnectionPoolTest.testQueuedRequestsDontOpenTooManyConnections()
**Jetty Version**

10.0.x

**Description**

Seen twice now (over the past week).

Latest one is at https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-7454/1/tests

```
org.opentest4j.AssertionFailedError: expected: <2> but was: <1>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
	at org.eclipse.jetty.client@10.0.8-SNAPSHOT/org.eclipse.jetty.client.ConnectionPoolTest.testQueuedRequestsDontOpenTooManyConnections(ConnectionPoolTest.java:319)

Standard Error
Running org.eclipse.jetty.client.ConnectionPoolTest.testQueuedRequestsDontOpenTooManyConnections([4] duplex-maxDuration)
2022-01-27 04:33:15.432:INFO :oejs.Server:main: jetty-10.0.8-SNAPSHOT; built: 2022-01-27T04:16:18.625Z; git: 1ee37a850f739d948fa2a936536b4cef4a9ef376; jvm 11.0.13+8
2022-01-27 04:33:15.434:INFO :oejs.AbstractConnector:main: Started ServerConnector@1b89debc{HTTP/1.1, (http/1.1)}{0.0.0.0:46323}
2022-01-27 04:33:15.434:INFO :oejs.Server:main: Started Server@159314ca{STARTING}[10.0.8-SNAPSHOT,sto=0] @20583ms
2022-01-27 04:33:16.940:INFO :oejs.Server:main: Stopped Server@159314ca{STOPPING}[10.0.8-SNAPSHOT,sto=0]
2022-01-27 04:33:16.942:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@1b89debc{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
```

### PR DESCRIPTION
**Pull request by lorban**
Use less strict assertion for expiring pool to account for potential expirations. Since an expiration check is done by the pool every time a connection is released, it is entirely possible (and legal) that a bad scheduling would close some connections; hence the assertion must be relaxed to account for this in the expiring pool case.

Fixes #7461.

### CODE REVIEW

**Review by gregw — DISMISSED** [review]

File: jetty-client/src/test/java/org/eclipse/jetty/client/ConnectionPoolTest.java [hunk 1]
```diff
@@ -316,7 +318,10 @@ public void resolve(String host, int port, Promise<List<InetSocketAddress>> prom
         assertEquals(1, destinations.size());
         HttpDestination destination = (HttpDestination)destinations.get(0);
         AbstractConnectionPool connectionPool = (AbstractConnectionPool)destination.getConnectionPool();
-        assertEquals(2, connectionPool.getConnectionCount());
+        if (DUPLEX_MAX_DURATION == factory)
+            assertThat(connectionPool.getConnectionCount(), lessThanOrEqualTo(2)); // The connections can expire upon release.
+        else
+            assertThat(connectionPool.getConnectionCount(), is(2));
```
Comment (sbordet) [inline jetty-client/src/test/java/org/eclipse/jetty/client/ConnectionPoolTest.java:319]: This is one fix, but there are many other places where `connectionPool.getConnectionCount()` is called and may therefore fail too.

What's the point of making the duration only 10 ms?

I ask because setting the duration at 1000 ms would probabilistically avoid races, at the cost of possibly making just one test a little slower.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-client/src/test/java/org/eclipse/jetty/client/ConnectionPoolTest.java (hunk 1 above)
Comment (lorban) [reply jetty-client/src/test/java/org/eclipse/jetty/client/ConnectionPoolTest.java:319]: Yes, it looks like `testQueuedRequestsDontOpenTooManyConnections`, `testConnectionMaxUsage` and `testIdleTimeoutNoRequests` could suffer from the same flakeyness. I'm going to check that more closely and adapt them if needed or document why not.

The 10ms duration is very short exactly to ferret out genuine race conditions in the code under test. It's not a delay that tests are waiting for so increasing it to 1000ms would pretty much never trigger an expiration which would make this pool variation useless.

**Review by sbordet — APPROVED** [review]
