### PR TITLE
HttpURI.Mutable path changes should clear out any existing path violations before parsing the new path.

### LINKED ISSUE #11298: Error 400 - Ambiguous URI Empty Segment
**Jetty Version**
12.0.3

**Jetty Environment**
ee8

**Java Version**
JavaSE-17

**Question**
I just migrated from Jetty 10.0.15 to 12.0.3 and I keep getting the following error:
URI:  /badURI
STATUS: 400
MESSAGE: Ambiguous URI empty segment
CAUSED BY: org.eclipse.jetty.http.BadMessageException: 400: Ambiguous URI empty segment

Any ideas what could be causing this?

ambiguous_error

### PR DESCRIPTION
**Pull request by joakime**
The use of HttpURI.Mutable methods that change the path (eg `.path(String)` and `.pathQuery(String)`) should clear out any existing path violations before parsing the newly provided path.

This helps CompactPathRule to also clear out the path violations that the CompactPathRule is capable of addressing.

Updating CompactPathRuleTest testcase to show these new behaviors.

Fixes: #11298

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java [hunk 1]
```diff
@@ -954,6 +954,21 @@ public Collection<Violation> getViolations()
...
+        private void clearPathViolations()
+        {
+            if (_violations == null)
+                return;
+            _violations.removeIf((violation) ->
+                    (violation == Violation.AMBIGUOUS_PATH_PARAMETER) ||
+                    (violation == Violation.AMBIGUOUS_PATH_SEGMENT) ||
+                    (violation == Violation.AMBIGUOUS_PATH_SEPARATOR) ||
+                    (violation == Violation.AMBIGUOUS_PATH_ENCODING) ||
+                    (violation == Violation.AMBIGUOUS_EMPTY_SEGMENT));
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java]: Can you move this to a `UrlCompliance.isPathViolation(Violation)` method?    
Having it in the same class will make it a little less fragile to the addition of new violations.

**Review by gregw — CHANGES_REQUESTED** [review]
This looks good... except to make it a little less fragile it would be good to move the test to a method in UriViolation

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpURI.java]: Done.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java [hunk 2]
```diff
@@ -352,6 +352,21 @@ public UriCompliance without(String name, Violation... violations)
...
 
+    /**
+     * Test if violation is referencing a URI path violation.
+     *
+     * @param violation the violation to test.
+     * @return true if violation is a path violation.
+     */
+    public static boolean isPathViolation(UriCompliance.Violation violation)
+    {
+        return (violation == Violation.AMBIGUOUS_PATH_PARAMETER) ||
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: This should be an enumset

**Review by gregw — CHANGES_REQUESTED** [review]
Sorry .. one more change

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java (hunk 2 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: It makes the removal of individual items on a collection WAY more complicated and slower.

Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: Keep in mind that the usage is `_violations.removeIf(UriCompliance::isPathViolation);`

As an `EnumSet`, this would mean a `EnumSet.contains()` call for every entry in the `_violations` collection.
Why go to all that complication for a simple comparison.

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: EnumSet's are highly optimized for enums with less than 32 values.  A contains operation will be a single bitwise operation and null check.  OK in this case, it is probably hardly different from 4 == and 3 || operations, but I think the code is also more readable.  Also we do other EnumSet comparisons on Violations  (e.g. org.eclipse.jetty.http.UriCompliance#AMBIGUOUS_VIOLATIONS) so best to keep the style the same.


```java
    private static final EnumSet<Violation> PATH_VIOLATIONS = Collections.unmodifiableSet(EnumSet.of( 
        Violation.AMBIGUOUS_PATH_SEGMENT,            
        Violation.AMBIGUOUS_PATH_SEPARATOR,
        Violation.AMBIGUOUS_PATH_ENCODING,
        Violation.AMBIGUOUS_EMPTY_SEGMENT));

    // ...
    
    public static boolean isPathViolation(UriCompliance.Violation violation)
    {
        return PATH_VIOLATIONS.contains(violation);
    } 
```

Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: Change to EnumSet pushed.

**Review by gregw — APPROVED** [review]
