### PR TITLE
Fixes #4020 - Revert ExtensionFactory change to interface.

### LINKED ISSUE #4020: [9.4.20] Incompatible type change in patch version
changing ExtensionFactory from abstract class to interface with 9.4.20 seems to be an incompatible change for third party libraries like spring (Spring Boot 2.1.7) which make some use of this class:

```
2019-08-23 15:22:35.929 ERROR 321 --- [tp1413871034-27,i=127.0.0.1] d.i.r.w.config.logging.HttpErrorFilter   : RETURN 500, url: GET /websocket/731/2y1k2l1j/websocket
2019-08-23 15:22:35.931  WARN 321 --- [tp1413871034-27,] org.eclipse.jetty.server.HttpChannel     : /websocket/731/2y1k2l1j/websocket

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.socket.sockjs.SockJsException: Uncaught failure in SockJS request, uri=http://127.0.0.1/websocket/731/2y1k2l1j/websocket?access_token
....
Caused by: org.springframework.web.socket.sockjs.SockJsException: Uncaught failure in SockJS request, uri=http://127.0.0.1/websocket/731/2y1k2l1j/websocket?access_token=<token>
nested exception is org.springframework.web.socket.sockjs.SockJsTransportFailureException: WebSocket handshake failure; nested exception is java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.websocket.api.extensions.ExtensionFactory, but class was expected
	at org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler.handleRequest(SockJsHttpRequestHandler.java:136)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:53)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	... 103 common frames omitted
Caused by: org.springframework.web.socket.sockjs.SockJsTransportFailureException: WebSocket handshake failure; nested exception is java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.websocket.api.extensions.ExtensionFactory, but class was expected
	at org.springframework.web.socket.sockjs.transport.handler.WebSocketTransportHandler.handleRequest(WebSocketTransportHandler.java:128)
	at org.springframework.web.socket.sockjs.transport.TransportHandlingSockJsService.handleTransportRequest(TransportHandlingSockJsService.java:312)
	at org.springframework.web.socket.sockjs.support.AbstractSockJsService.handleRequest(AbstractSockJsService.java:438)
	at org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler.handleRequest(SockJsHttpRequestHandler.java:133)
	... 107 common frames omitted
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.websocket.api.extensions.ExtensionFactory, but class was expected
	at org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy.buildWebSocketExtensions(JettyRequestUpgradeStrategy.java:170)
	at org.springframework.web.socket.server.jetty.JettyRequestUpgradeStrategy.getSupportedExtensions(JettyRequestUpgradeStrategy.java:164)
	at org.springframework.web.socket.server.support.AbstractHandshakeHandler.doHandshake(AbstractHandshakeHandler.java:283)
	at org.springframework.web.socket.sockjs.transport.handler.WebSocketTransportHandler.handleRequest(WebSocketTransportHandler.java:124)
	... 110 common frames omitted
```

it is possible to get a patched 9.4.x version w/o backward incompatible changes?

### PR DESCRIPTION
**Pull request by joakime**
+ The change in commit 30dc103a129d08304e1f1a99a84c045049de305d
  was done to allow the InflaterPool and DeflaterPool
  to be managed by the Jetty lifecycle.
+ This restore the original abstract class ExtensionFactory.
+ Had to break the traditional LifeCycle usage for a more
  non-traditional one in order to both, not break this existing
  API, and not introduce jetty-util to the webapp classloader.
+ This will restore API / binary compatibility for other
  projects, like spring-boot.

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/WebSocketExtensionFactory.java [hunk 1]
```diff
@@ -37,8 +38,9 @@
 import org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension;
 import org.eclipse.jetty.websocket.common.scopes.WebSocketContainerScope;
 
-public class WebSocketExtensionFactory extends ContainerLifeCycle implements ExtensionFactory
+public class WebSocketExtensionFactory extends ExtensionFactory implements LifeCycle
```
Comment (gregw) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/WebSocketExtensionFactory.java]: This needs to also implement dumpable and also delegate to the lifecycle

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/WebSocketExtensionFactory.java [hunk 2]
```diff
@@ -37,8 +38,9 @@
...
 {
+    private ContainerLifeCycle lifecycle;
```
Comment (gregw) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/WebSocketExtensionFactory.java]: call it `containerLifeCycle` or just `container`

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/WebSocketExtensionFactory.java [hunk 3]
```diff
@@ -47,6 +49,7 @@
 
     public WebSocketExtensionFactory(WebSocketContainerScope container)
     {
+        lifecycle = new ContainerLifeCycle();
```
Comment (gregw) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/WebSocketExtensionFactory.java]: probably need to extend the `toString()` method to call the factories `toString` so that dump is meaningful

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/WebSocketExtensionFactory.java [hunk 4]
```diff
@@ -49,7 +51,7 @@
 
     public WebSocketExtensionFactory(WebSocketContainerScope container)
     {
-        lifecycle = new ContainerLifeCycle();
+        containerLifeCycle = new ContainerLifeCycle();
```
Comment (gregw) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/WebSocketExtensionFactory.java]: You still need to override the toString on the ContainerLifeCycle as otherwise this class itself will not appear in any dumps.
