### PR TITLE
Fixes #13164 - ProxyServlet abort.

### LINKED ISSUE #13164: ProxyServlet abort
**Jetty version(s)**
12.0.x, 12.1.x

**Description**

The test org.eclipse.jetty.ee10.proxy.ProxyServletTest#testExpect100ContinueRespond100ContinueSomeRequestContentThenFailure

passes, but throws:
```
java.lang.IllegalStateException: s=HANDLING rs=COMPLETED os=ABORTED is=IDLE awp=false se=true i=false al=0
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.complete(ServletChannelState.java:830)
	at org.eclipse.jetty.ee10.servlet.AsyncContextState.complete(AsyncContextState.java:61)
	at org.eclipse.jetty.ee10.proxy.AbstractProxyServlet.sendProxyResponseError(AbstractProxyServlet.java:803)
	at org.eclipse.jetty.ee10.proxy.AbstractProxyServlet.onProxyResponseFailure(AbstractProxyServlet.java:762)
	at org.eclipse.jetty.ee10.proxy.ProxyServlet$ProxyResponseListener.onComplete(ProxyServlet.java:228)
	at org.eclipse.jetty.client.transport.ResponseListeners.notifyComplete(ResponseListeners.java:354)
	at org.eclipse.jetty.client.transport.ResponseListeners.notifyComplete(ResponseListeners.java:346)
	at org.eclipse.jetty.client.transport.HttpReceiver.terminateResponse(HttpReceiver.java:451)
	at org.eclipse.jetty.client.transport.HttpReceiver.terminateResponse(HttpReceiver.java:433)
	at org.eclipse.jetty.client.transport.HttpReceiver.lambda$abort$5(HttpReceiver.java:531)
	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:274)
	at org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:174)
	at org.eclipse.jetty.client.transport.HttpReceiver.responseHeaders(HttpReceiver.java:247)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:333)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parseAndFill(HttpReceiverOverHTTP.java:250)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:85)
	at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:97)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:266)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP$FillableCallback.succeeded(HttpConnectionOverHTTP.java:457)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:54)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:484)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:447)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:297)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:982)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1212)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1167)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### PR DESCRIPTION
**Pull request by sbordet**
* Fixed HttpStatus javadocs and added isError(int).
* Fixed double invocations of sendProxyResponseError(). For ProxyServlet and AsyncProxyServlet, the proxyRequest is always sent early, so ProxyResponseListener.onComplete() will take care of calling sendProxyResponseError(), so it is enough to cause the abortion of the proxyRequest.
* Fixed double invocations of onClientRequestFailure(), which was aborting the proxyRequest, but was calling sendProxyResponseError() if the abort was not successful. Aborting the proxyRequest was already calling sendProxyResponseError(), so no need to calling it again if the abort was not successful.
* AsyncMiddleManServlet is different, since it does not send the proxyRequest immediately. Therefore added an attribute to know whether it was sent, and acting accordingly to guarantee that sendProxyResponseError() is called even if the proxyRequest is not sent yet (since there is no ProxyResponseListener.onComplete() installed yet).

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpStatus.java [hunk 1]
```diff
@@ -205,74 +205,64 @@ public String toString()
         }
 
         /**
-         * Simple test against an code to determine if it falls into the
-         * <code>Informational</code> message category as defined in the <a
-         * href="http://tools.ietf.org/html/rfc1945">RFC 1945 - HTTP/1.0</a>,
-         * and <a href="http://tools.ietf.org/html/rfc7231">RFC 7231 -
-         * HTTP/1.1</a>.
+         * Simple test against a code to determine if it falls into the
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpStatus.java]: "Simple" adds nothing to this documentation:

```suggestion
         * Test to determine if the status is of the
```

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpStatus.java]: Ditto below

File: jetty-ee10/jetty-ee10-proxy/src/main/java/org/eclipse/jetty/ee10/proxy/ProxyServlet.java [hunk 2]
```diff
@@ -90,7 +90,14 @@ protected void service(HttpServletRequest request, HttpServletResponse response)
...
                     {
                         Request.Content content = proxyRequestContent(request, response, proxyRequest);
-                        Content.copy(content, delegate, Callback.from(delegate::close, x -> onClientRequestFailure(request, proxyRequest, response, x)));
+                        Content.copy(content, delegate, Callback.from(
+                            delegate::close,
+                            x ->
+                            {
+                                delegate.fail(x);
+                                onClientRequestFailure(request, proxyRequest, response, x);
+                            })
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-proxy/src/main/java/org/eclipse/jetty/ee10/proxy/ProxyServlet.java]: Can the delegate throw?  Should this be:
```suggestion
                            x ->
                            {
                                ExceptionUtil.callAndThen(x, delegate::fail, x - > onClientRequestFailure(request, proxyRequest, response, x));
                            })
```

File: jetty-ee9/jetty-ee9-proxy/src/main/java/org/eclipse/jetty/ee9/proxy/ProxyServlet.java [hunk 3]
```diff
@@ -90,7 +90,14 @@ protected void service(HttpServletRequest request, HttpServletResponse response)
                     try
                     {
                         Request.Content content = proxyRequestContent(request, response, proxyRequest);
-                        Content.copy(content, delegate, Callback.from(delegate::close, x -> onClientRequestFailure(request, proxyRequest, response, x)));
+                        Content.copy(content, delegate, Callback.from(
+                            delegate::close,
+                            x ->
+                            {
+                                delegate.fail(x);
```
Comment (gregw) [inline jetty-ee9/jetty-ee9-proxy/src/main/java/org/eclipse/jetty/ee9/proxy/ProxyServlet.java]: Can this throw?

**Review by gregw — CHANGES_REQUESTED** [review]
a couple of niggles

**Review by lorban — DISMISSED** [review]

**Review by lorban — APPROVED** [review]
