### PR TITLE
Issue #12818 - fix potential NPE from WebSocketConnection

### LINKED ISSUE #12818: NPE with websocket java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.hasRemaining()" because "this.networkBuffer" is null
**Jetty version(s)**
12.0.16

**Jetty Environment**
When using Jenkins

**How to reproduce?**
Not reproducible as is :( 

```
Feb 24, 2025 3:34:38 AM FINE org.eclipse.jetty.websocket.core.WebSocketConnection fillAndParse
Error during fillAndParse() java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.hasRemaining()" because "this.networkBuffer" is null
```
Or 

```

Feb 24, 2025 3:34:38 AM FINE org.eclipse.jetty.websocket.core.WebSocketCoreSession processConnectionError
processConnectionError WebSocketCoreSession@1e4875b6{SERVER,WebSocketSessionState@71a0b388{CLOSED,i=NO-OP,o=NO-OP,c={1011=SERVER_ERROR, CLOSE method error: Cannot invoke "hudson.remoting.CommandTransport$CommandReceiver.terminate(java.io.IOException)" becaus}},[wss://jenkins/wscontrollers/,null,true.[]],af=true,i/o=4096/4096,fs=65536}->JettyWebSocketFrameHandler@23c8275d[jenkins.websocket.Jetty12EE9Provider$2]
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.hasRemaining()" because "this.networkBuffer" is null
	at Jenkins Main ClassLoader//org.eclipse.jetty.websocket.core.WebSocketConnection.fillAndParse(WebSocketConnection.java:438)
	at Jenkins Main ClassLoader//org.eclipse.jetty.websocket.core.WebSocketConnection.onOpen(WebSocketConnection.java:533)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:435)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.succeeded(HttpConnection.java:1529)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpStream$Wrapper.succeeded(HttpStream.java:227)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.internal.CompletionStreamWrapper.succeeded(CompletionStreamWrapper.java:45)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpStream$Wrapper.succeeded(HttpStream.java:227)
	at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.SessionHandler$SessionStreamWrapper.succeeded(SessionHandler.java:122)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.completeStream(HttpChannelState.java:771)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:697)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
Fixes #12818 and #13225

If a close `WebSocketConnection.onClose` event happens during `fillAndParse()` then the network buffer is nulled out while it is still in use potentially causing NPE.

This fixes this issue by introducing a new atomic state so that onClosed() serializes the close actions with `fillAndParse()`.

### CODE REVIEW

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java [hunk 1]
```diff
@@ -429,6 +464,28 @@ public void cancelDemand()
 
     private void fillAndParse()
     {
+        boolean doClose = false;
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java]: Rename to just `close` like above.

**Review by sbordet — DISMISSED** [review]
Just a nit.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java [hunk 2]
```diff
@@ -61,6 +61,14 @@ private enum DemandState
         CANCELLED
     }
 
+    private enum State
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java:74]: Go on - do a  little ascii art state machine diagram :)

**Review by gregw — DISMISSED** [review]
Approved with a niggle

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java [hunk 3]
```diff
@@ -61,6 +61,26 @@ private enum DemandState
...
+     * The state of the WebSocketConnection, used to serialize fillingAndParsing with connection close events.
+     * <pre>
+     *   ┌────IDLE<───────────────┐
+     *   │      │                 │
+     *   │      V                 │
+     *   │    FILLING_AND_PARSING─┤
+     *   │                        │
+     *   │                        V
+     *   └───>CLOSED<────────CLOSING
+     * </pre>
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketConnection.java]:
```suggestion
     * <pre>
     *   IDLE   <------> FILLING_AND_PARSING
     *     |                 |
     *     |                 |
     *     v                 v
     *   CLOSED <-------- CLOSING
     * </pre>
```

**Review by gregw — DISMISSED** [review]
How about this

**Review by gregw — APPROVED** [review]

**Review by sbordet — APPROVED** [review]
