### PR TITLE
Fixes #12289 - Improve ConcurrentPool concurrency.

### LINKED ISSUE #12289: Improve ConcurrentPool concurrency
**Jetty version(s)**
12

**Description**
```
java.lang.ArrayIndexOutOfBoundsException: Index 249 out of bounds for length 249
        at java.base/java.util.concurrent.CopyOnWriteArrayList.elementAt(CopyOnWriteArrayList.java:390)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:403)
        at org.eclipse.jetty.util.ConcurrentPool.sweep(ConcurrentPool.java:200)
        at org.eclipse.jetty.util.ConcurrentPool.reserve(ConcurrentPool.java:178)
        at org.eclipse.jetty.client.AbstractConnectionPool.tryCreate(AbstractConnectionPool.java:281)
        at org.eclipse.jetty.client.AbstractConnectionPool.acquire(AbstractConnectionPool.java:235)
        at org.eclipse.jetty.client.transport.HttpDestination.process(HttpDestination.java:372)
        at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:358)
        at org.eclipse.jetty.client.transport.HttpDestination.succeeded(HttpDestination.java:291)
        at org.eclipse.jetty.client.AbstractConnectionPool.proceed(AbstractConnectionPool.java:315)
        at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.succeeded(AbstractConnectionPool.java:615)
        at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.succeeded(AbstractConnectionPool.java:593)
        at org.eclipse.jetty.util.Promise$Wrapper.succeeded(Promise.java:195)
        at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.onOpen(HttpConnectionOverHTTP.java:209)
        at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:325)
        at org.eclipse.jetty.io.ClientConnector$ClientSelectorManager.connectionOpened(ClientConnector.java:616)
        at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:401)
        at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:1056)
        at org.eclipse.jetty.util.thread.MonitoredQueuedThreadPool$1.run(MonitoredQueuedThreadPool.java:73)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```

### PR DESCRIPTION
**Pull request by sbordet**
A call to `sweep()`, although protected by the lock for concurrent calls to `reserve()`, may be concurrent with `remove(Entry)`.

`remove(Entry)` in turn calls `entries.remove(Object)`, so that the concurrent iteration in `sweep()` over `entries` fails with an `ArrayIndexOutOfBoundsException`.

Now using the bulk `entries.removeIf(Predicate)` method in `sweep()`, so that sweeping is atomic with respect to `entries.remove(Object)`.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 1]
```diff
@@ -666,6 +666,13 @@ protected void notifyExitScope(Request request)
         }
     }
 
+    private static <T> List<T> reverse(List<T> list)
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: This should be extracted out in a helper class, as this implementation is duplicated, a bit expensive and could easily be optimized later on if deemed necessary.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: Done.

**Review by lorban — APPROVED** [review]

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java [hunk 2]
```diff
@@ -1000,17 +1000,17 @@ protected void requestDestroyed(Request baseRequest, HttpServletRequest request)
         if (!_servletRequestListeners.isEmpty())
         {
             final ServletRequestEvent sre = new ServletRequestEvent(_apiContext, request);
-            for (int i = _servletRequestListeners.size(); i-- > 0; )
+            for (ServletRequestListener listener : TypeUtil.reverse(_servletRequestListeners))
```
Comment (gregw) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java:1003]: I'm a big -1 on this unrelated change.
On every request you could be copying and reversing several lists.

Comment (lorban) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java:1003]: Since the reverse iteration is being taken care of in #12297, that concern should probably be completely removed from this PR.

Comment (sbordet) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java:1003]: @lorban this PR is already merged.

Comment (lorban) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java:1003]: Indeed, I noticed after commenting.
