### PR TITLE
Fixes #1949 - Client-side problems with digest authentication.

### LINKED ISSUE #1949: Jetty 9 - Client-side problems with digest authentication
When a Jetty `HttpClient` sends a POST to a URI protected by a `DigestAuthenticator` on a Jetty server, and the server responds with an authentication challenge, the requests fails intermittently on the client side. The larger the content and the slower the internet connection, the more likely the failure occurs. The requests fails with randomly either an `org.eclipse.jetty.io.EofException` thrown in `ChannelEndPoint.flush` or a `java.io.EOFException` thrown in `HttpReceiverOverHTTP.earlyEOF`. Apparently, the client complains about the connection being closed by the server before the request content is sent completely.

The reasons why the server closes the connection without reading all the content are already discussed in issue #651. I also agree to the points raised by @gregw, but I think that the client should be ready for a server behaving in this way and attempt to recover from such a situation. This also seems to be in line with [RFC 7230, section 6.3.1](https://tools.ietf.org/html/rfc7230#section-6.3.1). In particular, since an authentication challenge response indicates that the request must be authenticated before the server can process the request and its content, the client could safely ignore the closed connection, follow the authentication protocol and resend the request with the established credentials using a new connection, even if the request uses a non-idempotent method such as POST.

I also agree with @sbordet that in the case of digest authentication, the credentials should be established with an initial request without content, but this does not solve the problem in the case of stale credentials of a later POST.

On the server side, I implemented @Adebski’s solution, which works fine apart from being a potential DOS risk as noted by @gregw. Therefore, I hope it is possible to change the `HttpClient` such that it also works with servers that close the connection without reading the whole content, at least in the case of digest authentication challenges.

By the way, I use the TCP/IP Monitor integrated in Eclipse IDE for network debugging. When I activate this monitor between a Jetty server and a Jetty `HttpClient`, requests that require digest authentication always fail, regardless of payload size or connection speed (even with client and server running on the same machine). Unfortunately, I cannot tell whether the problem is created by the client, the server, or the monitor, so I do not know where to raise an issue regarding this problem.

Our use case is the distribution and synchronization of data between multiple systems. So, our client executes POSTs, PUTs and DELETEs all day and only rarely a GET. Our exact test environment is Jetty 9.4.7.v20170914, Java 1.8.0_152 and Http1.1.

### PR DESCRIPTION
**Pull request by sbordet**
Introduced ContentProvider.isRepeatable() to detect whether the
request content can be provided more than once, and modified
ContentProvider implementation accordingly.

Modified AuthenticationProtocolHandler to not send an authenticated
request if the content is not repeatable.

Modified AuthenticationProtocolHandler to tolerate request failures.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-client/src/main/java/org/eclipse/jetty/client/util/ByteBufferContentProvider.java [hunk 1]
```diff
@@ -57,6 +57,12 @@ public long getLength()
         return length;
     }
 
+    @Override
+    public boolean isRepeatable()
+    {
+        return true;
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/util/ByteBufferContentProvider.java]: I don't think that just because a content can technically be repeated, that it should be.

I think the user should pass in the constructor if it is repeatable and the default should be false.

File: jetty-client/src/main/java/org/eclipse/jetty/client/util/BytesContentProvider.java [hunk 2]
```diff
@@ -53,6 +53,12 @@ public long getLength()
         return length;
     }
 
+    @Override
+    public boolean isRepeatable()
+    {
+        return true;
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/util/BytesContentProvider.java]: Ditto about default to false

File: jetty-client/src/main/java/org/eclipse/jetty/client/util/PathContentProvider.java [hunk 3]
```diff
@@ -85,6 +85,12 @@ public long getLength()
         return fileSize;
     }
 
+    @Override
+    public boolean isRepeatable()
+    {
+        return true;
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/util/PathContentProvider.java]: ditto

File: jetty-client/src/main/java/org/eclipse/jetty/client/util/ByteBufferContentProvider.java (hunk 1 above)
Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/util/ByteBufferContentProvider.java]: @gregw but the user may not know if a content needs to be repeatable. For example, with digest autentication the server may decide to "refresh" the tokens and send back a 401 on any random request. So either the client will always declare the content as repeatable, or if it does not it may fail.
At that point, the user has the burden of always specifying `repeatable=true`, while we can easily know that from the type of content and save the user some work.

Comment (gregw) [reply jetty-client/src/main/java/org/eclipse/jetty/client/util/ByteBufferContentProvider.java]: @sbordet then maybe `isRepeatable()` is the wrong name, perhaps it should be `isReproducable()`.

To me, `isRepeatable()` is kind of like `isIdempotent()`, meaning that the content is not something like a JSON encoded command to charge €1000 to my credit card.    

But in this case, we are not repeating the content, we are simply reproducing it because we know the first send of it was rejected with a 401.    If we were ever to write code that resent POSTs that failed silently, then we would need to check that the content was `isReproducable() && isRepeatable()`

We need detailed javadoc to say that this is not for resending a failed post, but only for known rejections.

Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/util/ByteBufferContentProvider.java]: `isReproducible()` works for me as a name change, but I think that `ContentProvider` implementations that know that their content is reproducible should default to `true`, not forcing the user to pass this information all the times.

The javadocs will just specify that the method should return true if I can get another iterator out of the `ContentProvider` and get exactly the same bytes.
That is all.

How `isReproducible()` is used by the implementation may be explained, but I think it's out of scope for a `ContentProvider` javadoc. It's the implementation job to use it wisely.

Comment (gregw) [reply jetty-client/src/main/java/org/eclipse/jetty/client/util/ByteBufferContentProvider.java]: I agree that default to `true` is OK.    I think the documentation should just say that this field indicates that the content "can be" reproduced, not that it "should be" and that it is up to the caller to ensure safe reproduction of content.

**Comment by sbordet** [comment]
@gregw I have addressed your review, please re-review.
