### PR TITLE
Fix broken EE9 / EE10 DefaultServlet range requests

### LINKED ISSUE #10330: Jetty 12: ResourceService throws NPE when resource has no filesystem path
**Jetty version(s)**
Jetty 12.0.0

**Jetty Environment**
core, ee8

**Description**
I have my own Resource subclass that fetches content from database. Therefore, it has no Path. This is valid according to documentation and also used by some Resources like MemoryResource.

Unfortunately when the browser wants to do a range request, it fails with NPE:

```
2023-08-16 23:21:37,295 WARN o.e.j.e.n.HttpChannel - /reference/118030/attachments/msm_114_2_vmadcp_75khz.nc
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null
        at java.nio.file.Files.provider(Files.java:105) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
        at org.eclipse.jetty.ee8.nested.ResourceService.lambda$writeContent$1(ResourceService.java:703) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.nested.resource.SeekableByteChannelRangeWriter.skipTo(SeekableByteChannelRangeWriter.java:80) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.nested.resource.SeekableByteChannelRangeWriter.writeTo(SeekableByteChannelRangeWriter.java:63) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.nested.ResourceService.writeContent(ResourceService.java:704) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.nested.ResourceService.sendData(ResourceService.java:628) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.nested.ResourceService.doGet(ResourceService.java:279) ~[jetty-ee8-nested-12.0.0.jar:12.0.0]
        at org.eclipse.jetty.ee8.servlet.DefaultServlet.doGet(DefaultServlet.java:432) ~[jetty-ee8-servlet-12.0.0.jar:12.0.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:503) ~[jetty-servlet-api-4.0.6.jar:?]
```

I have only checked the ee8 ResourceService, not the core one. They may all have the same problem. I have not seen that problem with Jetty 10. The code there uses Resource's byte channel and just checks if it is seekable. Otherwise it falls back to `InputStreamRangeWriter`: https://github.com/eclipse/jetty.project/blob/5bca6994645b62d22dca67cc24f41a9f3a365344/jetty-server/src/main/java/org/eclipse/jetty/server/resource/HttpContentRangeWriter.java#L56-L76

Actually the range writer should check for NULL or -- better -- it should get the channel from the Resource, unfortunately the resource only has ReadableByteChannel, so instanceof check is required. But maybe it can still at least skip?!

### PR DESCRIPTION
**Pull request by lorban**
Note: the discovered bugs affect EE9 and EE10 in the same way.

Fixes #10330

### CODE REVIEW

**Review by uschindler — APPROVED** [review]
To me this looks fine. As mentioned in the issue I already built and deployed this with my embedded app. It passes quick tests with Firefox and Chrome. Also curl was able to retrieve ranges.

About the "Accept-Ranges: none": I am not 100% sure if it is really needed to send this header. The default for this header is "none", so there's no explicit need to send it. The spec is a bit unclear. MDN says that it is seldom to see this header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges):
> `none` Indicates that no range unit is supported. This makes the header equivalent of its own absence and is therefore, rarely used. Although in some browsers, like IE9, this setting is used to disable or remove the pause buttons in the download manager.

Sending the header is also not helpful, if the browser sends a range from the beginning (Chrome and Firefox often do this by default) without actually knowing that the server suppports ranges. If it gets back a 206, all fine, if not, it will replace whole cache contents.

To me it was only important: if you disable ranges in the `ResourceService/DefaultServlet`, the server should not respond with 206 and just send full content with status 200.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java [hunk 1]
```diff
@@ -132,6 +135,34 @@ public boolean addPart(MultiPart.Part part)
...
+     * <p>A specialized {@link org.eclipse.jetty.io.content.InputStreamContentSource}
+     * whose content is sliced by a byte range.</p>
+     */
+    public static class InputStreamContentSource extends org.eclipse.jetty.io.content.InputStreamContentSource
+    {
+        private long toRead;
+
+        public InputStreamContentSource(InputStream inputStream, ByteRange byteRange) throws IOException
+        {
+            super(inputStream);
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java:148]: Can you put a `requiresNotNull` in the constructor of `InputStreamContentSource` just in case a `Resource` has a null input stream.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java [hunk 2]
```diff
@@ -678,7 +684,13 @@ private void sendData(Request request, Response response, Callback callback, Htt
             putHeaders(response, content, range.getLength());
             response.setStatus(HttpStatus.PARTIAL_CONTENT_206);
             response.getHeaders().put(HttpHeader.CONTENT_RANGE, range.toHeaderValue(contentLength));
-            Content.copy(new MultiPartByteRanges.PathContentSource(content.getResource().getPath(), range), response, callback);
+            Path path = content.getResource().getPath();
+            Content.Source source;
+            if (path != null)
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:691]: Maybe a comment to say why a path is preferred (less copying and async)

**Review by gregw — DISMISSED** [review]
A couple of niggles, but otherwise OK.

Can you also open an issue to discuss how we can server generic Resources asynchronously without the need to go to a Path.  Perhaps a `Resource.getContentSource` method?

**Comment by uschindler** [comment]
> A couple of niggles, but otherwise OK.
> 
> Can you also open an issue to discuss how we can server generic Resources asynchronously without the need to go to a Path. Perhaps a `Resource.getContentSource` method?

I think that could work, because there's `Resource#getChannel()`, unfortunately returning only a ReadableByteChannel, which is not seekable. Basically this one can be used in the `open()` method of the `PathContentSource`. The problem is only how to fallback then if the channel is not seekable.

The idea to add `Resource#getContentSource()`is a good one:
- the default impl would use legacy `this.getChannel()`, then fallback to `this.getInputStream()`
- `ContentSource` should always support ranges without extra wrapping. Theres only the special case that legacy `Resource#getChannel()` returns a non-seekable channel, where we could fallback to `InputStream`.
- The methods `Resource#getPath()`, `Resource#getChannel()`, `Resource#getInputStream()` should posisbly be made protected as they are only "easy use" for implementors. All code from core jetty should never ever call them.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java:148]: Done, but in the parent class.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:691]: Done.

**Review by uschindler — APPROVED** [review]
To me this looks fine. I have not tested it again since yesterday, but the changes here were more cosmetic.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/InputStreamContentSource.java [hunk 3]
```diff
@@ -79,7 +81,7 @@ public Content.Chunk read()
         try
         {
             ByteBuffer buffer = streamBuffer.getByteBuffer();
-            int read = inputStream.read(buffer.array(), buffer.arrayOffset(), buffer.capacity());
+            int read = fillBufferFromInputStream(inputStream, buffer);
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/InputStreamContentSource.java]: In the old implementation everything was local and private, so we could assume the `ByteBuffer` was from heap, etc.
Now that we are calling an overridable method, we should avoid assumptions about how the `ByteBuffer` is.
Can we modify the signature of this method to take a `byte[]` instead, so there are no assumptions?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java [hunk 4]
```diff
@@ -181,26 +212,38 @@ protected boolean isReadComplete(long read)
      */
     public static class Part extends MultiPart.Part
     {
-        private final Path path;
+        private final Resource resource;
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java:215]: Please change the class javadocs to not use "file".

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerByteRangesTest.java [hunk 5]
```diff
@@ -79,6 +87,203 @@ public void dispose()
...
+        server.setHandler(handler);
+        server.start();
+    }
+
+    @Test
+    public void testMemoryResourceRange() throws Exception
+    {
+        changeHandler(new ResourceHandler()
+        {
+            final Resource memResource = ResourceFactory.root().newMemoryResource(getClass().getResource("/simple/big.txt"));
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerByteRangesTest.java]: Maybe replace `root()` with `of(this)`?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/InputStreamContentSource.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/InputStreamContentSource.java]: That's a very good suggestion, let me do it.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartByteRanges.java:215]: Done.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerByteRangesTest.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerByteRangesTest.java]: Done.

**Review by sbordet — APPROVED** [review]
I don't particularly like that now `Part` depends on `Resource` -- I think it'll confuse users.
I would have preferred just a dependency on both `Path` and `InputStream`.

**Review by gregw — APPROVED** [review]
