### PR TITLE
Fix #4461 HttpOutput Aggregation

### LINKED ISSUE #4461: IllegalStateException in HttpOutput with Jersey
**Jetty version**
9.4.25.v20191220

**Java version**
OpenJDK 1.8.0_232 (Zulu)

**OS type/version**
macOS Mojave 10.14.6

**Description**
Jetty 9.4.25 seems to have a regression (or stricter behavior) in the `HttpOutput` state machine (likely introduced by #4409) which causes the following exception on `write()`:
```
java.lang.IllegalStateException: s=OPEN,api=BLOCKED,sc=false,e=null
```
Unfortunately, I was not able to create a simple reproduction, but it reproduces reliably when running a Presto unit test in the `presto-jmx` module from this branch: https://github.com/electrum/presto/tree/jetty9425:
```
mvn clean install -DskipTests -pl presto-jmx -am -T1C
mvn test -pl presto-jmx -Dtest=io.prestosql.plugin.jmx.TestJmxQueries#testQuery
```
After running the above, look for the following error in the test output after 5-10 seconds. You can kill the test at this point, since it takes a while to eventually time out.
```
2020-01-07T14:01:47.723-0600 SEVERE An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: com.fasterxml.jackson.databind.JsonMappingException: s=OPEN,api=BLOCKED,sc=false,e=null (through reference chain: io.prestosql.client.QueryResults["data"]->java.util.Collections$UnmodifiableRandomAccessList[12])
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:91)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at io.airlift.http.server.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:102)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1058)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: s=OPEN,api=BLOCKED,sc=false,e=null (through reference chain: io.prestosql.client.QueryResults["data"]->java.util.Collections$UnmodifiableRandomAccessList[12])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:338)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:123)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serializeContents(IterableSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:74)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:12)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:721)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:921)
	at io.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:233)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	... 20 more
Caused by: java.lang.IllegalStateException: s=OPEN,api=BLOCKED,sc=false,e=null
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:767)
	at io.airlift.http.server.TimingFilter$TimedServletOutputStream.write(TimingFilter.java:163)
	at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:325)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:224)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:300)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2136)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeCustomStringSegment2(UTF8JsonGenerator.java:1657)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment(UTF8JsonGenerator.java:1396)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegments(UTF8JsonGenerator.java:1281)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:502)
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	... 40 more
```

### PR DESCRIPTION
**Pull request by gregw**
This is an alternative to #4465 that fixes #4461 and the discovered issue of not aggregating due to an empty at capacity buffer.

+ Added tests to check that aggregation continues after first flush of an aggregated buffer (this triggers both #4461 and the discovered bug of not aggregating because of empty at capacity aggregate buffer).
+ Added getAggregateSize method that does a compact to avoid empty at capacity aggregate buffer
+ Call onWriteComplete if residue of an overflow aggregation can itself be aggregated.

Signed-off-by: Greg Wilkins <gregw@webtide.com>

Closes #4461

### CODE REVIEW

**Comment by gregw** [comment]
@sbordet @joakime In this PR I have fixed both issues together because I think they are very much related.   

I am a bit conflicted about if writes should always do an implicit compact when they have consumed a buffer or not... if so then after writing we would never have a buffer left at p=c,l=c as it would always be compacted to p=0,l=0.

However the javadoc for EndPoint simply says: `The header/buffers position is updated to indicate how many bytes have been consumed`.  So it does not say that we can change the limit to indicate how many bytes are consumed.    Thus I think it is correct for HttpOutput to do the compacting (or clearing) in its own reuse of the aggregate buffer, as we should not assume an implicit compact with a write/flush.

So does that mean that the GzipHandler is wrong and it should not do a compact and only modify the position to be equal to the limit (as per #4465) ???

**Comment by gregw** [comment]
Reading more, the contract for `Channel.write(ByteBuffer)` says:
```
Upon return the buffer's position will be equal to p+n; its limit will not have changed.
```
Thus our normal EndPoints are correct and the clear in GzipHandler is incorrect.  I will fix that also in this PR.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java [hunk 1]
```diff
@@ -378,6 +378,19 @@ private boolean updateApiState(Throwable failure)
...
+    {
+        // If no aggregate, we can allocate one of bufferSize
+        if (_aggregate == null)
+            return getBufferSize();
+
+        // if the position is not zero, compact to avoid empty at capacity
+        if (_aggregate.position() != 0)
+            BufferUtil.compact(_aggregate);
+
+        return BufferUtil.space(_aggregate);
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java:390]: This is, in general, wrong.

If an application sets `bufferSize=512`, when we get `_aggregate` from the buffer pool, we get back a buffer with capacity 1024 (or different, depending on the buffer pool configuration).

We must either not rely on the capacity of the buffer to return the aggregate space, or `slice()` the buffer returned by the buffer pool to the desired capacity.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java [hunk 2]
```diff
@@ -378,6 +378,19 @@ private boolean updateApiState(Throwable failure)
...
 
+    private int getAggregateSpace()
+    {
+        // If no aggregate, we can allocate one of bufferSize
+        if (_aggregate == null)
+            return getBufferSize();
+
+        // if the position is not zero, compact to avoid empty at capacity
+        if (_aggregate.position() != 0)
+            BufferUtil.compact(_aggregate);
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java]: This would be a getter with side effects, it will just bite us back. Must not compact here!

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java [hunk 3]
```diff
@@ -801,9 +826,10 @@ public void write(byte[] b, int off, int len) throws IOException
                 channelWrite(_aggregate, last && len == 0);
 
                 // should we fill aggregate again from the buffer?
-                if (len > 0 && !last && len <= _commitSize && len <= BufferUtil.space(_aggregate))
+                if (len > 0 && !last && len <= _commitSize && len <= getAggregateSpace())
                 {
                     BufferUtil.append(_aggregate, b, off, len);
+                    onWriteComplete(false, null);
                     return;
                 }
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java:833]: This code block should really be removed, so that aggregation will happen only in 1 place, and only due to computing whether it should happen or not only once.

The conditions at line 829 (new code) are slightly different from the conditions at line 757 (new code), so it's difficult to follow the code, trying to understand why in the world there is a call to `onWriteComplete()` inside a block that does aggregation.

Actually, turns out that we do (again) a similar aggregation logic in `AsyncWrite.process()`, so we need to clean this up even more.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java [hunk 4]
```diff
@@ -1670,15 +1696,6 @@ protected Action process() throws Exception
...
 
-            // all content written, but if we have not yet signal completion, we
-            // need to do so
-            if (_last && !_completed)
-            {
-                _completed = true;
-                channelWrite(BufferUtil.EMPTY_BUFFER, true, this);
-                return Action.SCHEDULED;
-            }
-
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java]: Why was this removed?

File: jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java [hunk 5]
```diff
@@ -54,6 +58,8 @@
  */
 public class HttpOutputTest
 {
+    public static final int OUTPUT_AGGREGATION_SIZE = 1024;
+    public static final int OUTPUT_BUFFER_SIZE = 4096;
```
Comment (sbordet) [inline jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java:62]: The test should parametrize on these values, something like `[512, 512], [512, 1024], [1024, 1024], [1024, 4096]`.

File: jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java [hunk 6]
```diff
@@ -64,10 +70,25 @@ public void init() throws Exception
...
+            public ByteBuffer acquire(int size, boolean direct)
+            {
+                return direct ? BufferUtil.allocateDirect(size) : BufferUtil.allocate(size);
+            }
+
+            @Override
+            public void release(ByteBuffer buffer)
+            {
+            }
+        });
```
Comment (sbordet) [inline jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java:85]: With this, this test is testing conditions that will never be the ones with the normal Jetty code, rendering this test useless.

**Review by sbordet — CHANGES_REQUESTED** [review]
Overall, I liked more the changes in #4465 as they removed code that was not necessary, rather than adding more `if/else` to cover for more cases.

I would strive for aggregation in just one place, and if a network write must happen, let's write all we have (less latency) rather than writing some and aggregate again.

For Jetty 10 we need `HttpOutput.Interceptor` be able to do gather writes!

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java (hunk 4 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java]: Because is can never ever happen.  I tried to write a unit test to give it code coverage and I was unable to do so.

File: jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java (hunk 5 above)
Comment (gregw) [reply jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java:62]: why? what does the absolute size of the buffer have to do with it?

File: jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java (hunk 6 above)
Comment (gregw) [reply jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java:85]: Because it is testing aggregation, which is dependent on the actual size of the buffer.  As our buffer pools can give back buffers with larger capacities, this test uses a simple buffer pool that gives back a buffer of exact size and thus allows the tests to be determinant about if they do or do not aggregate/commit etc.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java (hunk 3 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java:833]: I tend to agree, but for jetty-10 only.  In Jetty-9 I do not think we should be making significant behaviour changes as they tend to have unintended consequences.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java (hunk 2 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java]: Do you have a suggestion of where the commit should be done then? 
I initially did the compact after every blocking write and in the callback of every async write, but that put the logic in many places.   Having the compact done immediately before the space is checked is the simplest solution I can think of.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java (hunk 1 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java:390]: How can the calculation of space not be based on capacity?

The spec allows for a larger buffer than set:
```
     * The servlet container will use a buffer at least as large as 
     * the size requested.  The actual buffer size used can be found
     * using <code>getBufferSize</code>.
```
It would be crazy to allocate a larger buffer and then run a shadow capacity to only use a part of it.  If you think we should not use larger buffers than requested, then the buffer pool should never return a larger buffer than requested.

File: jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java (hunk 6 above)
Comment (joakime) [reply jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java:85]: The real buffer pool behaviors are one of the reasons the original code failed in a production capacity.  I think @sbordet has a point, this should use a real world scenario, not a pie-in-the-sky wishful scenario.

**Comment by gregw** [comment]
@sbordet I don't think you have fully understood the problem in your review.  #4465 only fixes part of the problem and changes behaviour significantly.   I think it has some good simplifications, but they should only be considered for jetty-10.

Your review has not answered the fundamental question that I've asked: where should the compact be done?  Options are: a) in the EndPoint; b) after every write, c) immediately before the space is checked?
a) is contrary to the contract for `EndPoint` and `Channel.write(ByteBuffer)`,  I tried b), but it required duplicate code in many places and would be error prone to maintain.     This solution goes for c) and the compact is in only one spot, immediately before the space is checked.

Yes the getter has a side effect in one point of view, but you can also argue that a buffer with p==0,l==0 is equivalent to one with p==c,l==c in all ways other than space.

File: jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java (hunk 6 above)
Comment (gregw) [reply jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java:85]: This is not pie in the sky wishful thinking.  It is a deterministic test case that actually tests what it thinks it is testing, not some random behaviour that is dependent on a buffer pool beyond the control of the test.

Comment (joakime) [reply jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java:85]: OK, then add an alternate test that tests the opposite case.

A new ByteBufferPool implementation that always returns 4x the size requested.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java (hunk 1 above)
Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java:390]: I agree with @sbordet here.

If a user uses `HttpConfiguration.setOutputBufferSize(512)` or `HttpConfiguration.setOutputAggregationSize(256)` then they expect behavior based on that configuration, not some larger / mysterious / black box / implementation specific size.

The fact that our ByteBufferPool _might_ return a larger size is a side-effect of being efficient with memory allocation here.
I would expect our behavior to remain unchanged, using the returned ByteBuffer (regardless of actual space/capacity) for the configured buffer size (eg: 512).

Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java:390]: Sorry but it is nonsensical to return a larger buffer and then only use a part of it.  The contract allows for a larger buffer to be used, so why would we not use it if it has been allocated?

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java (hunk 3 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java:833]: I am also concerned about the performance. Consider an app that always writes small 5, 10, 20 byte writes. Eventually a small write overflows the buffer. Currently the code fills the buffer to max size, flushes it and then aggregates the small remaining data.
The alternative is to flush a non full buffer and then write a small write, so we get 2 non optimal writes instead of one.

The real solution is to add gather writes in jetty-10 or beyond

File: jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java (hunk 6 above)
Comment (gregw) [reply jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java:85]: But that is not what I'm testing.  The tests only need to know if a write is bigger, smaller or the same as the buffers. It is relative size not absolute size that is important here.   If I had a 4x buffer returning pool, then I'd just have to alter the test case to write 4x as much data in each write to test the scenarios that are needed to test.

The point being that the HttpOutputTest is providing very good (well above average) coverage of HttpOutput.   The purpose here is not to test the buffer pools

**Review by sbordet — APPROVED** [review]

**Review by joakime — APPROVED** [review]
Current state i'm happy with.
Looking forward to the cleanup when it merges to Jetty 10.

**Comment by gregw** [comment]
I'm now not so sure about a cleanup in 10.  When we have a nearly full aggregate buffer that is overflowed by a small write, the options are:
 + fill aggregate, flush aggregate and then aggregate remaining: a single optimal write and the current behaviour
 + flush aggregate and fill: a non optimal write a less remaining space in aggregate
 + flush aggregate and flush buffer: two non optimal writes... unless we can have gather writes all the way down.

So we need gather writes to improve this, which would mean we would need gather generates for HTTP, H2, etc.
It is a lot of work to remove a few lines of code. 

I'll open an issue to investigate increased use of gather writes, but it is feeling like a jetty > 10 thing to me.
