### PR TITLE
Fixes #6603 - HTTP/2 max local stream count exceeded (#6639)

### LINKED ISSUE #6603: HTTP/2 max local stream count exceeded
**Jetty version(s)** 9.4.41.v20210516

**Java version/vendor** 1.8.0_271

**OS type/version**: Linux and Windows 10 machine

**Description** 
HTTP/2 max local stream count exceeded

We were using jetty 9.4.35 version  and we encountered this "HTTP/2 max local stream count 1 exceeded" error ,Simon suggested us to upgrade jetty version to 9.4.41 , so we did jetty jar upgrade to 9.4.41 version , but still we see the error .

Below is the code snippet we have written to create http2 client to post requests to destination host.

     HttpClient httpClient = null;
     HTTP2Client http2Client=null;
        try {
            http2Client = new HTTP2Client();
            http2Client.start();
           SslContextFactory sslContextFactory = new SslContextFactory.Client(true);
           final KeyStore sslKeyStore = loadKeystore(); //loadKeystore method loads keystire
          if (sslKeyStore != null) {
             sslContextFactory.setKeyStore(sslKeyStore);
           }
            httpClient = new HttpClient(new HttpClientTransportOverHTTP2(http2Client),
                    sslContextFactory);
            httpClient.setMaxConnectionsPerDestination(100);
            httpClient.setMaxRequestsQueuedPerDestination(250000);
            httpClient.start();
            return httpClient;
        }
        catch (Exception exp) {
       }

**How to reproduce?**
Set the MaxConnectionsPerDestination value to 100 and try to post more than 10K requests.

### PR DESCRIPTION
**Pull request by sbordet**
Made MAX_CONCURRENT_STREAMS setting work on a per-connection basis.
Updated Pool javadocs.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>
Co-authored-by: Greg Wilkins <gregw@webtide.com>
(cherry picked from commit 525fcb31194c62c44c912504ded177e30ff78c52)

### CODE REVIEW

**Comment by sbordet** [comment]
Forward port of #6639 to Jetty 10.

Note that removing usage count is tracked by #6669, while splitting of the Pool is tracked by #6683.

**Comment by gregw** [comment]
@sbordet I fixed the broken test that was due to a change in the dump format

**Review by lorban — DISMISSED** [review]

File: jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java [hunk 1]
```diff
@@ -834,6 +837,9 @@ protected IStream createRemoteStream(int streamId, MetaData.Request request)
             int maxCount = getMaxRemoteStreams();
             if (maxCount >= 0 && remoteCount - remoteClosing >= maxCount)
             {
+                IllegalStateException failure = new IllegalStateException("Max remote stream count " + maxCount + " exceeded: " + remoteCount + "+" + remoteClosing);
```
Comment (lorban) [inline jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java:840]: This exception is only used in the debug log. We could save a few cycles when this error condition occurs by only creating it if debug is enabled.

**Review by lorban — APPROVED** [review]
Just a minor nit, doesn't have much impact.

**Review by gregw — APPROVED** [review]
