### PR TITLE
Make `Environment.ensure()` call from thread-safe context

### LINKED ISSUE #12853: Flaky `WebAppClassLoaderTest.testSystemServerClassDeprecated`
**Jetty version(s)**
12.1.x

**Description**
`org.eclipse.jetty.ee.WebAppClassLoaderTest.testSystemServerClassDeprecated` sometimes fails with:

```
java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap.callMappingFunctionWithCheck(TreeMap.java:786)
	at java.base/java.util.TreeMap.computeIfAbsent(TreeMap.java:640)
	at org.eclipse.jetty.util@12.1.0-SNAPSHOT/org.eclipse.jetty.util.component.Environment.ensure(Environment.java:45)
	at org.eclipse.jetty.ee@12.1.0-SNAPSHOT/org.eclipse.jetty.ee.TestableWebAppClassLoaderContext.initEnvironment(TestableWebAppClassLoaderContext.java:36)
	at org.eclipse.jetty.ee@12.1.0-SNAPSHOT/org.eclipse.jetty.ee.WebAppClassLoaderTest.init(WebAppClassLoaderTest.java:60)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
```

See: https://jenkins.webtide.net/job/jetty.project/job/jetty-12.1.x/479/testReport/junit/org.eclipse.jetty.ee/WebAppClassLoaderTest/Parallel_Stage___Build___Test___JDK23___testSystemServerClassDeprecated/

### PR DESCRIPTION
**Pull request by lorban**
`Environment.ensure()` is explicitly called from `WebAppClassLoaderTest`'s `@BeforeEach` via `TestableWebAppClassLoaderContext.initEnvironment()`, i.e.: when surefire executes tests in parallel, the non-thread-safe `Environment.ensure()` method gets executed by multiple threads in parallel.

Removing `TestableWebAppClassLoaderContext.initEnvironment()` and moving its code to a `TestableWebAppClassLoaderContext` static block makes sure that `Environment.ensure()` is only going to be called only once with the same result.

Fixes #12853

### CODE REVIEW

**Comment by joakime** [comment]
There's 2 ways I would approach this.

1. Flag/Annotate the tests in here that manipulate the Environment as junit isolated so that they do not conflict with each other.  (see past fixes in this regard from @olamy )

2. Embrace the chaos, and just make the Environment name equivalent to the junit TestInfo, which is unique per test case. (easy to setup, not sure how easy it is to troubleshoot)

**Comment by joakime** [comment]
Note: this is essentially a duplicate of #12851

**Comment by janbartel** [comment]
Can we please make `Environment` threadsafe?

**Comment by lorban** [comment]
@janbartel done

File: jetty-core/jetty-ee/src/test/java/org/eclipse/jetty/ee/TestableWebAppClassLoaderContext.java [hunk 1]
```diff
@@ -25,19 +25,19 @@
...
 public class TestableWebAppClassLoaderContext implements WebAppClassLoader.Context
 {
-    private final ResourceFactory resourceFactory;
-    private boolean parentLoaderPriority = false;
-    private ClassMatcher protectedClassMatcher;
-    private ClassMatcher hiddenClassMatcher;
-    private List<Resource> extraClasspath;
-
-    public static void initEnvironment()
+    static
```
Comment (janbartel) [inline jetty-core/jetty-ee/src/test/java/org/eclipse/jetty/ee/TestableWebAppClassLoaderContext.java]: I'm not as keen on this change. If this is now static then an individual test case can't use this class differently.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java [hunk 2]
```diff
@@ -17,7 +17,7 @@
 import java.util.Collection;
 import java.util.Collections;
 import java.util.Map;
-import java.util.TreeMap;
+import java.util.concurrent.ConcurrentSkipListMap;
```
Comment (janbartel) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: Now this is a change I like! :)

**Review by janbartel — CHANGES_REQUESTED** [review]
Maybe reconsider the necessity to make the assignment of the variables in the `TestableWebAppClassLoader` static - this may have unintended consequences for other tests?  But +1 for the thread-safety of `Environment`.

File: jetty-core/jetty-ee/src/test/java/org/eclipse/jetty/ee/TestableWebAppClassLoaderContext.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-ee/src/test/java/org/eclipse/jetty/ee/TestableWebAppClassLoaderContext.java]: So far, this class is only used by one test class which always calls `initEnvironment()` in a thread-unsafe way. IMHO we should postpone that static block refactoring to the day we start using `TestableWebAppClassLoaderContext` differently.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: I kinda agree that `Environment`'s static API should have a thread-safe implementation, but the API itself only displays non-thread-safe behaviors.

We better be careful when using the `set(Environment)` call.

**Review by janbartel — APPROVED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: @lorban I think `Environment.set()` should be removed.

It's easily replaced by the constructor of `Named` putting itself in the `Named.__environments` map.

Also, the `Named` constructor (and likely the whole class) should be private, as we don't want to create `Named` instances that are not in the `Named.__environments` map.
It would be enough to have `Environment.ensure(name, ClassLoader)`.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by lorban** [comment]
@sbordet I replaced `Environment.put()` with `Environment.ensure(name, ClassLoader)` but I'm not sure if that's any better as when `ensure(name, ClassLoader)` does not compute (i.e.: there already is an environment with that name) we should probably compare the classloaders... which kinda is a can of worms.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/NamedEnvironment.java [hunk 3]
```diff
@@ -0,0 +1,54 @@
+package org.eclipse.jetty.util.component;
+
+import java.io.IOException;
+import java.util.Map;
+import java.util.concurrent.ConcurrentSkipListMap;
+import org.eclipse.jetty.util.Attributes;
+import org.eclipse.jetty.util.TypeUtil;
+
+class NamedEnvironment extends Attributes.Mapped implements Environment, Dumpable
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/NamedEnvironment.java:23]: I don't really like creating a new top level class for such a small trivial thing.  What was wrong with Environment.Named as a package or private inner class?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java [hunk 4]
```diff
@@ -32,22 +28,22 @@ public interface Environment extends Attributes
...
     }
 
     static Environment ensure(String name)
     {
-        return Named.__environments.computeIfAbsent(name, Named::new);
+        return ensure(name, null);
     }
 
-    static Environment set(Environment environment)
+    static Environment ensure(String name, ClassLoader classLoader)
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: This should be a `Supplier<ClassLoader>` argument, as ensure semantics should only construct a classloader if the environment doesn't already exist.

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/EnvironmentBuilder.java [hunk 5]
```diff
@@ -61,6 +60,6 @@ public void addClassPath(String... classPaths)
 
     public Environment build() throws Exception
     {
-        return new Environment.Named(_name, new URLClassLoader(_classpath.toArray(new URL[0]), EnvironmentBuilder.class.getClassLoader()));
+        return Environment.ensure(_name, new URLClassLoader(_classpath.toArray(new URL[0]), EnvironmentBuilder.class.getClassLoader()));
```
Comment (gregw) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/EnvironmentBuilder.java]: What if the name already exists? This will just discard the classloader 
We need at least an error

**Review by gregw — CHANGES_REQUESTED** [review]
Sorry but if we are going to "clean this up", it needs a bit more work.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/NamedEnvironment.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/NamedEnvironment.java:23]: The class was implicitly public with no way to alter its visibility as it was enclosed by an interface.

Maybe `Environment` should be a class?

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/EnvironmentBuilder.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/EnvironmentBuilder.java]: `ensure` does not allow that. This doesn't look like it's the right contract for the job here.

Let me think of something else...

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: If `EnvironmentBuilder.build()` is supposed to throw when an environment with such name already exists, there is no need to use a supplier for the classloader.

Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: one or the other

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/NamedEnvironment.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/NamedEnvironment.java:23]: hmmm or just moved NamedEnvironment to an internal sub package

**Comment by lorban** [comment]
@gregw I've reworked the `Environment` static API, this time adding javadoc to make sure the contract is clear. It now throws exceptions when the expectations aren't met, so I modified the tests accordingly to make them parallelizable according to this new contract.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java [hunk 6]
```diff
@@ -30,24 +26,58 @@ public interface Environment extends Attributes
...
     }
 
-    static Environment ensure(String name)
+    /**
+     * Gets the environment with the given name, creating it with the default classloader if necessary.
+     * @param name the environment name
+     * @return the environment
+     * @throws IllegalStateException if an environment with the given name but a non-default classloader already exists
+     */
+    static Environment ensure(String name) throws IllegalStateException
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: I find `ensure()` confusing.

Environments are statics, and are created exactly at the right point by the right classes (the various eeN `ContextHandler`s), and when they do, it's a "create" operation because nobody could have created them.

I think we don't want other code to create environments, other than those eeN `ContextHandler`s.

If that's true, then all the rest of the code should use `get()`, because that code should not create environments as an unexpected side effect, just expect them to exist and use them.

Tests can easily call `create()` and then `get()`.

Am I missing something?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java (hunk 6 above)
Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: @gregw we should discuss how embedded code will be able to deploy different eeN contexts, because I feel that being able to do that will solve the problem with the `Environment` API.

Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: We need a test that deploys both a ee9 servlet _and_ a ee10 servlet on the same embedded server, as the current modifications break that use-case since the `ensure()` call in `ServletContextHandler`  would detect that the environment is present but with a non-default classloader and throw.

This should probably be part of the documentation too as this isn't a trivial setup.

Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: i think this PR has got way out of scope for its original intent.
How about we just roll back to making the map concurrent then:
 + perhaps rename `set` to `add` or `create`?
 + make `set` (or whatever it is called) throw an IAE if the named environment already exists.

**Review by gregw — APPROVED** [review]

**Comment by gregw** [comment]
@lorban I've pushed an update to `Environment.ensure` along the lines discussed with @sbordet this morning.  I've also added an `EnvironmentTest`

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/component/EnvironmentTest.java [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+        assertThat(envB.getClassLoader(), sameInstance(loaderB));
+
+        assertThat(Environment.get("envA"), sameInstance(envA));
+        assertThat(Environment.get("envB"), sameInstance(envB));
+
+        @SuppressWarnings("resource")
+        ClassLoader loaderAX = new URLClassLoader(new URL[0]);
+        assertThrows(IllegalStateException.class, () -> Environment.create("envA", loaderAX));
+
+        System.err.println(Environment.getAll());
```
Comment (sbordet) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/component/EnvironmentTest.java]: Leftover?

**Review by sbordet — APPROVED** [review]
LGTM besides a leftover System.err.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java [hunk 8]
```diff
@@ -13,41 +13,68 @@
...
+     *
+     * @param name the environment name
+     * @return the environment
+     * @throws IllegalStateException if an environment with the given name but a non-default classloader already exists
+     */
+    static Environment ensure(String name, ClassLoader classLoader) throws IllegalStateException
     {
-        return Named.__environments.computeIfAbsent(name, Named::new);
+        Environment environment = NamedEnvironment.ENVIRONMENTS.computeIfAbsent(name, n -> new NamedEnvironment(n, classLoader));
+        if (environment.getClassLoader() != classLoader)
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java:60]: So this check means that `EnvironmentBuilder` and `XmlConfiguration` must not configure `ee*` environments otherwise the `ensure()` call in the multiple `ServletContextHandler`s would make those classes fail to load because of this check.

Did I get this right?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java [hunk 9]
```diff
@@ -13,41 +13,68 @@
...
+        return NamedEnvironment.ENVIRONMENTS.get(name);
     }
 
-    static Environment ensure(String name)
+    /**
+     * Gets the environment with the given name, creating it with the default classloader if necessary.
+     *
+     * @param name the environment name
+     * @return the environment
+     * @throws IllegalStateException if an environment with the given name but a non-default classloader already exists
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: There is no concept of default classloader anymore.

Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: The current javadoc for Environment.getClassLoader makes it seem that there is still a default classloader.  or at least a fallback classloader.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java [hunk 10]
```diff
@@ -133,7 +133,7 @@
 public class ServletContextHandler extends ContextHandler
 {
     private static final Logger LOG = LoggerFactory.getLogger(ServletContextHandler.class);
-    public static final Environment ENVIRONMENT = Environment.ensure("ee11");
+    public static final Environment ENVIRONMENT = Environment.ensure("ee11", ServletContextHandler.class.getClassLoader());
```
Comment (joakime) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java:136]: How is this possible?

The Environment is the classloader for the ServletContextHandler.
So if we reach this point, then ...

1. The Environment for "ee11" exists already.
2. The Environment classloader for "ee11" exists already too.

Right?

So why reference the ServletContextHandler.class.getClassLoader at all?

Comment (gregw) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java:136]: Exactly! Either:
 a) The environment already exists (probably created by XML), in which case ensure checks that the classloader is the same one; OR
 b) The environment does not exist (embedded usage), in which case the environment is created with the loader that loaded the environment specific class.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java (hunk 8 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java:60]: Not at all.   The EB and XC can configure ee* environments, so long as they do so in a way that classes that call ensure are loaded from the classloaders in the created environments

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java (hunk 9 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java]: updated javadoc

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java (hunk 10 above)
Comment (sbordet) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletContextHandler.java:136]: Saves creating the environments explicitly.

Consider:

```java
ClassLoader serverCL = Server.class.getClassLoader();

ClassLoader ee11CL = new URLClassLoader(serverCL, new URL[] { ... });

ContextHandler ee11Ctx = reflectionMagic(ee11CL);

server.setHandler(ee11Ctx);

server.start();
```

There is no need to create the `Environment` explicitly, and the ee11 environment will have the right ClassLoader.
Previously, it would have had the wrong ClassLoader.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java (hunk 8 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/component/Environment.java:60]: ok, thanks for the explanation.

File: jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentManagerTest.java [hunk 11]
```diff
@@ -35,17 +39,19 @@
 import static org.junit.jupiter.api.Assertions.assertNotNull;
 
 @ExtendWith(WorkDirExtension.class)
+@Isolated
```
Comment (olamy) [inline jetty-core/jetty-deploy/src/test/java/org/eclipse/jetty/deploy/DeploymentManagerTest.java:42]: we might not need this anymore if the code is now thread-safe?
