### PR TITLE
Issue #13234 - empty query entries should be retained for Fields and Servlet Parameters

### LINKED ISSUE #13234: Regression in 12.0.21 on handling empty query parameters
**Jetty version(s)**
12.0.21

**Jetty Environment**
ee10 / ee9 / ee8

**Description**
Starting in Jetty 12.0.21 the handling of empty query parameters such as `/path?=` results in no entries when using `HttpServletRequest.getParameterValues("")` and using `HttpServletRequest.getParameter("")` returns null.

In Jetty 12.0.20 and older (this even includes Jetty 11.x, 10.x, and 9.x) this empty parameter is accessible via `HttpServletRequest.getParameterValues("")` and returns an array of 1 entry (which is itself an empty string).

Note: even if the value portion of the parameter has a value, this value is inaccessible due to this regress. (eg: `/path?=foo`)

Of note, more than 1 empty parameter on 12.0.20 and older (eg: `/path?=&=`) is accessible via both `HttpServletRequest.getParameterValues("")` (which returns an array of 2 entries, both at empty string) and using `HttpServletRequest.getParameter("")` returns an empty string.

### PR DESCRIPTION
**Pull request by joakime**
Fix regression in 12.0.21, where empty query parameters should still produce a Field or Servlet Parameter.

That means ..

1. `?=` is a single parameter with key name of empty string (`""`), with a single value of empty string (`""`).
2. `?=&=` is a single parameter with key name of empty string (`""`), with a two values of empty string (`""`).
3. `?&` has no parameters.
4. `?&&` has no parameters.

Closes #13234

### CODE REVIEW

**Comment by joakime** [comment]
@gregw is the case of `?=&=` and `?&` the same? as in two parsed fields, both with empty string key name, and empty string key value?

Currently, if the query ends in an ampersand then that ends the possibility of new fields, which seems like a mismatch in behavior of the two examples in the first line of this comment.

**Comment by joakime** [comment]
Tested the [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) feature two browsers, with code at https://codepen.io/Joakim-Erdfelt/pen/OPVEJdO

Firefox and Chrome both agree with the results of the parsing of the following examples.

Example Query   | Result                       
--------------- | ------------------------------
`a=b&c=d`       | `size:2 [{'a': 'b'}, {'c': 'd'}]`
`a=b?c=d`       | `size:1 [{'a': 'b?c=d'}]`
`=`             | `size:1 [{'': ''}]`
`a=b&a=c&a=d`   | `size:3 [{'a': 'b'}, {'a': 'c'}, {'a': 'd'}]`
`&`             | `size:0 []`
`&&&`           | `size:0 []`
`a=b&&&`        | `size:1 [{'a': 'b'}]`
`&&&a=b`        | `size:1 [{'a': 'b'}]`
`=&=`           | `size:2 [{'': ''}, {'': ''}]`
`&=&`           | `size:1 [{'': ''}]`
`foo`           | `size:1 [{'foo': ''}]`
`foo&bar`       | `size:2 [{'foo': ''}, {'bar': ''}]`
`foo=`          | `size:1 [{'foo': ''}]`
`foo=&`         | `size:1 [{'foo': ''}]`
`=foo`          | `size:1 [{'': 'foo'}]`
`=foo&=bar`     | `size:2 [{'': 'foo'}, {'': 'bar'}]`
`foo==`         | `size:1 [{'foo': '='}]`
`foo===`        | `size:1 [{'foo': '=='}]`
`a===b`         | `size:1 [{'a': '==b'}]`
`a="b"`         | `size:1 [{'a': '"b"'}]`
`"a=b"`         | `size:1 [{'"a': 'b"'}]`
`a=b& =foo`     | `size:2 [{'a': 'b'}, {' ': 'foo'}]`
`===foo`        | `size:1 [{'': '==foo'}]`

Basically, if there is nothing there (no characters, no equals sign) then there is no entry.
If there is any (except equals `=`) characters, it's automatically the name.
Anything after the equals sign is the value.

Should be easy enough to replicate.

**Comment by joakime** [comment]
@gregw could use a review of this please.

I was unable to find a spec talking about how to parse the query into found entries.
But I did find a Browser Javascript spec for a component call URLSearchParams and did some testing in Firefox and Chrome (see https://github.com/jetty/jetty.project/pull/13235#issuecomment-2970714326), produced a set of results from that experimentation, and added those results as testcases in this PR (with small changes to the parser to support these behaviors).

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java [hunk 1]
```diff
@@ -37,6 +37,7 @@ class UrlParameterDecoder
     private final boolean allowTruncatedEncoding;
     private final CharsetStringBuilder builder;
     private String name;
+    private boolean seenEqualsDelim;
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java]:
```suggestion
    private boolean parsingValue;
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java [hunk 2]
```diff
@@ -182,20 +183,24 @@ private boolean parseChar(char c, CharIterator iter) throws IOException
             case '&' ->
             {
                 String str = takeBuiltString();
-                if (name == null)
-                {
-                    onNewField(str, "");
-                }
-                else
+                if (seenEqualsDelim)
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/UrlParameterDecoder.java]: This needs to be set to false in the parse methods above.

**Review by gregw — CHANGES_REQUESTED** [review]
I couple of changes.... and are you really sure the new boolean is needed? When will it be true, but the name will be null?

**Comment by joakime** [comment]
> I couple of changes.... and are you really sure the new boolean is needed? When will it be true, but the name will be null?

I'm not sure now, if you had asked me a week ago I could have explained why I think this is needed.
Meh, I'll remove that new boolean and see what happens.

**Review by gregw — APPROVED** [review]
