### PR TITLE
Don't use `ResourceFactory.root()` in `AttributeNormalizer`

### LINKED ISSUE #9680: Jetty-12 QuickStartTest leaking resources
**Jetty version(s)**
12

**Description**

when running org/eclipse/jetty/ee10/quickstart/QuickStartTest.java, the following warnings are produced:

```
2023-04-26 09:27:44.718:INFO :oejs.Server:main: jetty-12.0.0-SNAPSHOT; built: unknown; git: ; jvm 19.0.2+7-Ubuntu-0ubuntu322.04
2023-04-26 09:27:44.728:WARN :oejshC.ROOT:main: The test-spec webapp is deployed. DO NOT USE IN PRODUCTION!
2023-04-26 09:27:44.729:INFO :oe.jetty:main: WEB-INF/lib/jetty-util.jar logging used!
2023-04-26 09:27:44.734:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql-1_0.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql-1_0.tld
2023-04-26 09:27:44.734:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn.tld
2023-04-26 09:27:44.734:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_0.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_0.tld
2023-04-26 09:27:44.734:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld
2023-04-26 09:27:44.735:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/permittedTaglibs-1_1.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/permittedTaglibs-1_1.tld
2023-04-26 09:27:44.735:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt.tld
2023-04-26 09:27:44.735:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_0.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_0.tld
2023-04-26 09:27:44.735:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/scriptfree.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/scriptfree.tld
2023-04-26 09:27:44.735:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/permittedTaglibs.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/permittedTaglibs.tld
2023-04-26 09:27:44.735:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_0-rt.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_0-rt.tld
2023-04-26 09:27:44.735:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql-1_0-rt.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql-1_0-rt.tld
2023-04-26 09:27:44.736:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld
2023-04-26 09:27:44.736:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x-1_0.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x-1_0.tld
2023-04-26 09:27:44.736:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql-1_1.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql-1_1.tld
2023-04-26 09:27:44.736:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x.tld
2023-04-26 09:27:44.736:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x-1_1.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x-1_1.tld
2023-04-26 09:27:44.737:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld
2023-04-26 09:27:44.737:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/sql.tld
2023-04-26 09:27:44.737:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld
2023-04-26 09:27:44.738:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_0-rt.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_0-rt.tld
2023-04-26 09:27:44.738:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x-1_0-rt.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/x-1_0-rt.tld
2023-04-26 09:27:44.738:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/,root=jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/scriptfree-1_1.tld] for jar:file:///home/gregw/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/scriptfree-1_1.tld
2023-04-26 09:27:44.739:WARN :oejur.ResourceFactoryInternals:main: Leaked Mount[uri=jar:file:///home/gregw/src/jetty-12.0.x/jetty-ee10/jetty-ee10-tests/jetty-ee10-test-quickstart/target/tests/PreconfigureSpecWar/test-spec-preconfigured/WEB-INF/lib/jetty-ee10-demo-web-fragment-12.0.0-SNAPSHOT.jar!/,root=jar:file:///home/gregw/src/jetty-12.0.x/jetty-ee10/jetty-ee10-tests/jetty-ee10-test-quickstart/target/tests/PreconfigureSpecWar/test-spec-preconfigured/WEB-INF/lib/jetty-ee10-demo-web-fragment-12.0.0-SNAPSHOT.jar!/META-INF/resources/] for jar:file:///home/gregw/src/jetty-12.0.x/jetty-ee10/jetty-ee10-tests/jetty-ee10-test-quickstart/target/tests/PreconfigureSpecWar/test-spec-preconfigured/WEB-INF/lib/jetty-ee10-demo-web-fragment-12.0.0-SNAPSHOT.jar!/META-INF/resources/
2023-04-26 09:27:44.782:INFO :oejs.DefaultSessionIdManager:main: Session workerName=node0
```

**How to reproduce?**

### PR DESCRIPTION
**Pull request by lorban**
Since `AttributeNormalizer` cannot guarantee that it will only ever work with `file:` resources, it cannot use `ResourceFactory.root()` as that `ResourceFactory` never unmounts.

Since the generated URI is changed to a `Resource` to check for existence, there is no need to keep the `ResourceFactory` around.

Closes #9680.

### CODE REVIEW

**Review by gregw — COMMENTED** [review]
I'm a little bit concerned that this is fixing a symptom rather than the disease.
I think these resources were originally found on either the server or environment classloader, so do we really need to load them again?  

Is there some way to determine if these jars are already visible to the current classloader and just use that rather than reload them?

**Comment by lorban** [comment]
@gregw I've simplified the changes down to a few lines in a single file, but I don't think we can go any further without breaking the combined resource contract.

Currently `PreconfigureQuickStartWar` can only be given a `PathResource` that is the war file on disk, so we could simply get rid of the `Resource.exists()` check in `AttributeNormalizer` and everything would still work as expected. But if we ever modify `PreconfigureQuickStartWar` so that it sets the base resource of the `WebAppContext` to be a `CombinedResource` then the existence check would be needed. That's very theoretical and may not make sense in practice, though.

If we decide that this can't happen, then the `AttributeNormalizerTest` needs to be modified as `testExpandWebInfAsURI` makes sure that the `AttributeNormalizer` does perform the existence check when it's working on a `CombinedResource`, and maybe document too that `AttributeNormalizer` is not going to check that the expanded strings aren't checked in any way.

**Comment by gregw** [comment]
@lorban thanks,  I'll have a bit more of a ponder about the quickstart mechanism over the weekend and say more on Monday

**Comment by gregw** [comment]
Never mind.... I see the reason for this.  Edited comment to noop.

**Review by gregw — CHANGES_REQUESTED** [review]
We definitely need more work here.  At least need to fix the failed assertions... but I also think we need to look for existing resources before importing new ones

**Comment by gregw** [comment]
@lorban hi-jacking your branch.....

what do you think of this approach, using the original resource to resolve against?      
Probably could be expanded to the system properties as well, so that resource is never null.

**Comment by janbartel** [comment]
Just to be clear, `PreconfigureQuickstartWar` is something that we mostly used for testing. We did document how you could use it in jetty-9 to generate a quickstart war, but I think it's been removed from the jetty-10/11 documentation. Probably doesn't change the outcome of this discussion, but as it's been mentioned I thought I'd clarify.

**Comment by janbartel** [comment]
@lorban @gregw the old `AttributeNormalizer` code didn't need to convert the attribute string into a Resource to do the normalization/expansion. IMHO I don't think it should - it should just be about converting strings (OK, some of them are convertable to URIs etc). The caller of `expand()` can decide what it wants to do with the string - use it as a URI or a Resource or whatever.

**Comment by gregw** [comment]
@janbartel I think this is because now we correctly iterate over a resourceCollection (or whatever it is called now), where previously we would expand to just the first URI in the collection (which just so happened to be correct more often than not).

Now we iterate through all the possible expansions looking for one that can resolve the pattern.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java [hunk 1]
```diff
@@ -411,17 +418,29 @@ private String expand(String prefix, String property, String suffix)
...
                 }
-                catch (Exception ex)
+                else
                 {
-                    if (LOG.isDebugEnabled())
-                        LOG.trace("ignored", ex);
+                    try
+                    {
+                        String uri = prefix + attr.value + suffix;
+                        try (ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable())
```
Comment (janbartel) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java]: @lorban I think we need to avoid needing this section of code. It's a major waste of time to convert to a `Resource` just to do exists when the caller only wants a string, and is probably then going to do their own conversions on this.  If we never allow the `Resource` inside a `URIAttribute` to be null, we can just delete this code.

**Review by janbartel — CHANGES_REQUESTED** [review]
@lorban see comment in the code.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java]: How about if there is only 1 resource, we just expand it.  Then we only go to this code if there are more than 1 and no resources.

**Comment by lorban** [comment]
There are three competing things here:

 - Converting the expanded string to a `Resource` to check for existence is expensive.
 - Not converting the expanded string to a `Resource` to check for existence is wrong when `CombinedResource` is used.
 - The `AttributeNormalizer` is generic and accepts `CombinedResource` while its only use-case (QuickStart) never creates a `CombinedResource`.

We need to reconcile these contradictions.

**Comment by lorban** [comment]
Since the existence check is only needed for combined resources, how about we simply detect that situation and skip the check for non-combined resources?

**Comment by janbartel** [comment]
> * The `AttributeNormalizer` is generic and accepts `CombinedResource` while its only use-case (QuickStart) never creates a `CombinedResource`.

But `QuickStart` does use `CombinedResources` - it is used all the time by the jetty maven plugin that forms a base resource from the unassembled locations of the webapp. Used for all plugin goals that exec a process.

**Comment by lorban** [comment]
@janbartel thanks for pointing this out. This definitely means we need to keep that existence check around then.

**Comment by lorban** [comment]
I'm going to add a `QuickStart` test that creates a `CombinedResource` to cover this.

**Comment by lorban** [comment]
After a conversation with @janbartel and @gregw it became apparent that `AttributeNormalizer` currently cannot work with `CombinedResource`s. https://github.com/eclipse/jetty.project/issues/8921 was about just that, and the necessary code was added in `QuickStartGeneratorConfiguration` to pass only the 1st resource to `AttributeNormalizer`.

So let's add an explicit check in `AttributeNormalizer` to explicitly prevent the use of `CombinedResource`s until we decide we want to support them.

**Review by janbartel — APPROVED** [review]

**Comment by janbartel** [comment]
@lorban the AttributeNormalizer tests are all failing.
