### PR TITLE
Fixes #6184 - JEP-411 will deprecate/remove the SecurityManager from …

### LINKED ISSUE #6184: Remove usages of classes associated with JEP-411 that deprecate/remove the SecurityManager from the JVM
**Jetty version**
All

**Java version**
All

**OS type/version**
All

**Description**
JEP-411 - https://openjdk.java.net/jeps/411

Will deprecate the SecurityManager in a specific way with an eye on removing it entirely in the future.
We should start to either alter our usages and expectations of the SecurityManager, or remove our usages entirely.

One of the techniques JEP-411 is considering is to have `System.getSecurityManager()` always return null.

That could impact our code when we use it like this ...

https://github.com/eclipse/jetty.project/blob/d825299da47a1d923648c52c80df11ac76fed77c/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java#L2529

Another aspect to consider is that `AccessController.doPrivileged(...)` will have no meaning anymore, the action will always be run in the JEP-411 deprecated mode.
Once JEP-411 enters removal mode, our code using AccessController will start to fail.

### PR DESCRIPTION
**Pull request by sbordet**
…the JVM.

Removed usages of `SecurityManager` and `AccessControlller.doPrivileged()`. In places where they are still necessary, now using reflection.

### CODE REVIEW

File: jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/DefaultAuthConfigFactory.java [hunk 1]
```diff
@@ -145,13 +137,43 @@ public RegistrationContext getRegistrationContext(String registrationID)
...
     {
-        SecurityManager sm = System.getSecurityManager();
-        if (sm != null)
-            sm.checkPermission(new AuthPermission("refreshAuth"));
+        checkPermission("refreshAuth");
 
         // TODO: maybe we should re-construct providers created from classname.
     }
 
+    private static void checkPermission(String permission)
```
Comment (janbartel) [inline jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/DefaultAuthConfigFactory.java:146]: Can we have a util class or method that does this as this is used in a few places.

File: jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 2]
```diff
@@ -1815,86 +1813,81 @@ public static void main(final String... args) throws Exception
     {
         try
         {
-            AccessController.doPrivileged((PrivilegedExceptionAction<Void>)() ->
-            {
-                Properties properties = new Properties();
-                properties.putAll(System.getProperties());
+            Properties properties = new Properties();
```
Comment (janbartel) [inline jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java:1816]: If we're running in < jdk18, why don't we continue to do the privileged action?

File: jetty-util/src/main/java/org/eclipse/jetty/util/MemoryUtils.java [hunk 3]
```diff
@@ -25,18 +22,11 @@
...
         {
-            value = Integer.parseInt(AccessController.doPrivileged(new PrivilegedAction<String>()
-            {
-                @Override
-                public String run()
-                {
-                    return System.getProperty("org.eclipse.jetty.util.cacheLineBytes", String.valueOf(defaultValue));
-                }
-            }));
+            value = Integer.parseInt(System.getProperty("org.eclipse.jetty.util.cacheLineBytes", String.valueOf(defaultValue)));
```
Comment (janbartel) [inline jetty-util/src/main/java/org/eclipse/jetty/util/MemoryUtils.java:29]: If running in < jdk 18 don't we still want to do the privileged action?

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 2 above)
Comment (sbordet) [reply jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java:1816]: Because the usage of privileged actions was done in very few places, leaving without many other places that would have required it.
Given that the few ones we had were definitely not enough, I think it's better to have none.

File: jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/DefaultAuthConfigFactory.java (hunk 1 above)
Comment (sbordet) [reply jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/DefaultAuthConfigFactory.java:146]: I thought about this and there are only 2 places, which are quite unrelated: here and `ContextHandler`.
Given that JASPI is not the most common specification, I thought that the less dependencies the better, so a utility class was not worth the effort.
Note also that all JASPI permissions are `AuthPermission`s, while a generic utility class would need a more generic signature, making this class a little more verbose.

**Review by gregw — DISMISSED** [review]
I kind of would like to see a util class for at least `getSecurityManager()`... but then I'm ok with it as is as well. 60:40

File: jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/DefaultAuthConfigFactory.java (hunk 1 above)
Comment (janbartel) [reply jetty-jaspi/src/main/java/org/eclipse/jetty/security/jaspi/DefaultAuthConfigFactory.java:146]: I'm pretty sure this is no more complex than changing the method signature to `checkPermission(Permission)`.  So my preference is still for a utility class/method.

**Review by janbartel — DISMISSED** [review]
Still prefer a utility/class method as the cleanest solution. But I guess we can always refactor that after you commit this.

**Comment by joakime** [comment]
> I kind of would like to see a util class for at least `getSecurityManager()`... but then I'm ok with it as is as well. 60:40

What would this getter return?
The `java.lang.SecurityManager` class is being removed from the JVM.

**Review by joakime — DISMISSED** [review]

**Review by joakime — APPROVED** [review]

**Review by gregw — APPROVED** [review]
Much better
