### PR TITLE
Deny HTTP/3 connection creation for clients missing cert when needClientAuth is true

### LINKED ISSUE #11996: mTLS: client cert verification for QUIC/HTTP3
**Jetty version(s)**
12.0.10
**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.3" 2024-04-16
OpenJDK Runtime Environment Homebrew (build 21.0.3)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.3, mixed mode, sharing)

**OS type/version**
Darwin ... 23.5.0 Darwin Kernel Version 23.5.0 arm64
and
Linux ... 6.5.0-41-generic 22.04.2-Ubuntu x86_64

**Description**
I'm using `SslContextFactory.Server` to configure the context which is used for HTTP 1.1, HTTP 2 and HTTP3. I have set `setNeedClientAuth` to `true`. 

In the case of HTTP 1.1 and HTTP2, the server demands the client certificate and verifies it against the configured trust store before the connection can proceed

HTTP3 does not demand the certificate and allows connection without the client certificate.

It appears that Quiche provides a `verify_peer` option and there is a low level test for it in the code base https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-foreign/src/test/java/org/eclipse/jetty/quic/quiche/foreign/LowLevelQuicheClientCertTest.java#L100

I believe the underlying `verifyPeer` value should be set based on the value of `getNeedClientAuth` on the `SslContextFactory.Server`.

Additionally there should be a way to add the `SecureRequestCustomizer` or equivalent so that the handlers can access the client cert for the QUIC/HTTP3 connection.

**How to reproduce?**
Use an `SslContextFactory.Server` with `setNeedClientAuth(true)` with the example at https://jetty.org/docs/jetty/12/programming-guide/server/http3.html

### PR DESCRIPTION
**Pull request by lorban**
There is no way to tell Quiche to refuse connections from clients who do not hold a client certificate, so when `SslContextFactory.needClientAuth` is set to true and a HTTP/3 request is made, an explicit check for that config setting must be added to explicitly tell Quiche to close the connection when the client cert is missing.

Fixes #11996

### CODE REVIEW

File: jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/AbstractClientServerTest.java [hunk 1]
```diff
@@ -63,34 +63,41 @@ public class AbstractClientServerTest
...
-        SslContextFactory.Server sslServer = new SslContextFactory.Server();
-        sslServer.setKeyStorePath("src/test/resources/keystore.p12");
-        sslServer.setKeyStorePassword("storepwd");
-        return new ServerQuicConfiguration(sslServer, workDir.getEmptyPathDir());
+        startServer(false, listener);
+        startClient();
     }
 
-    protected void start(Session.Server.Listener listener) throws Exception
+    protected void start(boolean needClientAuth, Session.Server.Listener listener) throws Exception
```
Comment (sbordet) [inline jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/AbstractClientServerTest.java]: The `boolean` is quite arbitrary, and does not help much when looking at tests that call `start(true, ...)`.

Can you please revert this, and add for the tests that need it, this line, just after calling `start(...)`:

`connector.getQuicConfiguration().getSslContextFactory().setNeedClientAuth(true);`

File: jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java [hunk 2]
```diff
@@ -58,7 +64,7 @@ public void testConnectTriggersSettingsFrame() throws Exception
     {
         CountDownLatch serverPrefaceLatch = new CountDownLatch(1);
         CountDownLatch serverSettingsLatch = new CountDownLatch(1);
-        start(new Session.Server.Listener()
+        start(true, new Session.Server.Listener()
```
Comment (sbordet) [inline jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java]: Why `true` here?

File: jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java [hunk 3]
```diff
@@ -640,4 +646,46 @@ public void onResponse(Stream.Client stream, HeadersFrame frame)
 
         assertTrue(responseLatch.await(5, TimeUnit.SECONDS));
     }
+
+    @Test
+    public void testMissingNeededClientCertDeniesConnection() throws Exception
```
Comment (sbordet) [inline jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java]: Cert -> Certificate

File: jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicConnection.java [hunk 4]
```diff
@@ -114,6 +116,20 @@ protected QuicSession createSession(SocketAddress remoteAddress, ByteBuffer ciph
...
+                    protocolSession.disconnect(QuicErrorCode.CONNECTION_REFUSED.code(), "missing_client_cert");
+                    // Send the response packet(s) that disconnect() generated.
+                    session.flush();
+                    return null;
+                }
+            }
+
             ServerQuicSession session = newQuicSession(remoteAddress, quicheConnection);
             // Send the response packet(s) that tryAccept() generated.
             session.flush();
```
Comment (sbordet) [inline jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicConnection.java]:
```suggestion
            ServerQuicSession session = newQuicSession(remoteAddress, quicheConnection);

            if (quicConfiguration.getSslContextFactory().getNeedClientAuth())
            {
                byte[] peerCertificate = quicheConnection.getPeerCertificate();
                if (peerCertificate == null)
                {
                    session.outwardClose(QuicErrorCode.CONNECTION_REFUSED.code(), "missing_client_certificate");
                    return null;
                }
            }

            // Send the response packet(s) that tryAccept() generated.
            session.flush();
            return session;
```

There should be no need to create a `ProtocolSession`, to call `disconnect()` on it, just to have `session.outwardClose()` be called.

These are the initial steps of connection establishment, so I think we should just close at the QUIC level, exactly as if some other TLS validation failed -- no need to create the upper layers.

If that is correct, I'd remove the added `disconnect()` methods and overrides -- it should be much simpler.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java]: Good catch, that's a refactoring mistake. Let me revert that.

File: jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/ClientServerTest.java]: Done.

File: jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/AbstractClientServerTest.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-http3/jetty-http3-tests/src/test/java/org/eclipse/jetty/http3/tests/AbstractClientServerTest.java]: Good suggestion, let me do this.

File: jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicConnection.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicConnection.java]: The `disconnect()` call isn't just to call `session.outwardClose()` but also to call `onDisconnect()` on the session's listener, see the `ServerHTTP3Session.disconnect()` impl.

**Comment by lorban** [comment]
@sbordet I had to completely change the implementation as it was totally broken: the peer certificate is accessible only after Quiche declares the connection as established.

File: jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java [hunk 5]
```diff
@@ -44,12 +45,14 @@
 public class ServerQuicSession extends QuicSession implements CyclicTimeouts.Expirable
 {
     private final Connector connector;
+    private final ServerQuicConfiguration quicConfiguration;
```
Comment (sbordet) [inline jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java]: This field is already present in `ServerQuicConnection`, so I would not duplicate it.

File: jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java [hunk 6]
```diff
@@ -44,12 +45,14 @@
...
     private long expireNanoTime = Long.MAX_VALUE;
 
-    public ServerQuicSession(Executor executor, Scheduler scheduler, ByteBufferPool bufferPool, QuicheConnection quicheConnection, QuicConnection connection, SocketAddress remoteAddress, Connector connector)
+    public ServerQuicSession(Executor executor, Scheduler scheduler, ByteBufferPool bufferPool, QuicheConnection quicheConnection, QuicConnection connection, SocketAddress remoteAddress, Connector connector, ServerQuicConfiguration quicConfiguration)
```
Comment (sbordet) [inline jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java]: You can change this constructor to take a `ServerQuicConnection` instead of a `QuicConnection`, so that you can access the `ServerQuicConnection` to get the configuration.

File: jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java [hunk 7]
```diff
@@ -67,6 +70,18 @@ protected ProtocolSession createProtocolSession()
         return new ServerProtocolSession(this);
     }
 
+    @Override
+    protected boolean validateNewlyEstablishedConnection()
+    {
+        if (quicConfiguration.getSslContextFactory().getNeedClientAuth() && getPeerCertificates() == null)
+        {
+            outwardClose(QuicErrorCode.CONNECTION_REFUSED.code(), "missing_client_cert");
```
Comment (sbordet) [inline jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java]: missing_client_cert -> missing_client_certificates (or missing_client_certificate_chain).

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java]: Ok, let me do that change.

File: jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java (hunk 6 above)
Comment (lorban) [reply jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java]: Let me change `ServerQuicSession`'s constructor to take a `ServerQuicConnection`; that will make sure the already existing `getQuicConnection()` method that returns a `ServerQuicConnection` never throws a `ClassCastException`.

File: jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java (hunk 7 above)
Comment (lorban) [reply jetty-core/jetty-quic/jetty-quic-server/src/main/java/org/eclipse/jetty/quic/server/ServerQuicSession.java]: Done.

**Review by sbordet — APPROVED** [review]
