### PR TITLE
Fixes #5217 - Review RoundRobinConnectionPool

### LINKED ISSUE #5217: Review RoundRobinConnectionPool
**Jetty version**
9.4.x

**Description**
With the work of #4975 and #5147 `RoundRobinConnectionPool` has received some attention, but could be improved.

Add javadocs and describe the peculiar behavior of round robin in detail.
Make tests less likely to fail.

### PR DESCRIPTION
**Pull request by sbordet**
Introduced IndexedConnectionPool and RandomConnectionPool.
Clarified semantic of RoundRobinConnectionPool.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-client/src/main/java/org/eclipse/jetty/client/IndexedConnectionPool.java [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+ * an available entry at a different index.</p>
+ */
+@ManagedObject
+public abstract class IndexedConnectionPool extends MultiplexConnectionPool
+{
+    private static final Logger LOG = Log.getLogger(IndexedConnectionPool.class);
+
+    private final Pool<Connection> pool;
+
+    public IndexedConnectionPool(HttpDestination destination, int maxConnections, boolean cache, Callback requester, int maxMultiplex)
```
Comment (lorban) [inline jetty-client/src/main/java/org/eclipse/jetty/client/IndexedConnectionPool.java]: I think the cache should be forced to false, otherwise you risk reaching a steady state where one thread continuously uses the connection at the same index.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-client/src/main/java/org/eclipse/jetty/client/IndexedConnectionPool.java (hunk 1 above)
Comment (gregw) [reply jetty-client/src/main/java/org/eclipse/jetty/client/IndexedConnectionPool.java]: I think there shouldn't be a cache and it should be replaced by round robin: see #5218

File: jetty-client/src/main/java/org/eclipse/jetty/client/RoundRobinConnectionPool.java [hunk 2]
```diff
@@ -43,36 +55,16 @@ public RoundRobinConnectionPool(HttpDestination destination, int maxConnections,
...
-                LOG.debug("activated at index={} entry={}", index, entry);
-            if (entry != null)
-                ++offset;
-        }
-        if (entry == null)
-            return null;
-        Connection connection = entry.getPooled();
-        acquired(connection);
-        return connection;
+        return Math.abs(offset.getAndIncrement() % maxConnections);
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/RoundRobinConnectionPool.java]: When the integer goes overflows, you will start going the opposite way around the the pool

Comment (joakime) [reply jetty-client/src/main/java/org/eclipse/jetty/client/RoundRobinConnectionPool.java]: could always use the overflow throwing behavior of `Math.addExact(int, int)` to trap that.

Comment (lorban) [reply jetty-client/src/main/java/org/eclipse/jetty/client/RoundRobinConnectionPool.java]: Is that a problem?

Comment (gregw) [reply jetty-client/src/main/java/org/eclipse/jetty/client/RoundRobinConnectionPool.java]: It might not be a problem, and unlikely to happen anyway.... but easily fixed with:
```
            return index.getAndUpdate(c -> Math.max(0, c + 1)) % maxConnections;
```

Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/RoundRobinConnectionPool.java]: And I have an even better solution in the latest code.

**Review by lorban — APPROVED** [review]
LGTM

**Review by joakime — APPROVED** [review]
Merge it. :+1:
