### PR TITLE
Issue #5198 - update gzip handler

### LINKED ISSUE #1761: Make GzipHandler module more configurable
There are a number of configuration options in GzipHandler that are not currently available as properties in the gzip.mod

Include/Exclude paths
Include/Excludes mime-types

There are already properties for Include/Exclude methods, It would been keen to see new properties for these as well.

Existing properties:

```
jetty.gzip.excludedMethodList
jetty.gzip.includedMethodList
```

Proposed new properties:

```
jetty.gzip.excludedPathList=<comma or pipe delim list>
jetty.gzip.includedPathList=<comma or pipe delim list>
jetty.gzip.excludedMimeTypeList=<comma or pipe delim list>
jetty.gzip.includedMimeTypeList=<comma or pipe delim list>
```

### LINKED ISSUE #4988: The check for whether a mime type is gzipable modifies (lower-cases) the content type
**Jetty version**

9.4.x (possibly others too)

**Java version**
1.8

**OS type/version**
Linux

**Description**
I'm not sure if this is by design or an issue but if you configure the `GzipHandler` a custom mime type in its include list that contains upper case characters, e.g. `application/json+CUSTOM`, then the handler fails to match the content type and therefore does not compress the response. 

I've tracked this down to the following code:
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java#L174

I'm aware that MIME types are generally lower-case by convention so it's possibly a design choice so does it make sense for both sides of the comparison to be lower-cased? If not a bug, is there any value in clarifying the behaviour in the docs?

### LINKED ISSUE #5198: Update GzipHandler
GzipHandler can user the ByteBuffer API in Jetty-10.
There are also several other open GzipHandler issues that might be addressed in an update: #4988, #4317, #2553, #1761

### LINKED ISSUE #5246: GzipHandler's DeflaterPool should be dumpable
**Jetty version**
9.4.31

**Description**
The DeflaterPool being used by the GzipHandler is not included in the server dump output.
This should be dumped, including details of how big the pool currently is.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
Fixes #5198 - We now use the ByteBuffer API for inflaters/deflaters for `GzipHandler`.
Fixes #4988 - The GzipHandlers `IncludeExclude` for the MIME types now uses case insensitive set.
Fixes #1761 - Added extra configuration in the .ini file for `gzip.mod`.
Fixes #5246 - add deflater/inflater pools to server dump.

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java [hunk 1]
```diff
@@ -355,7 +354,7 @@ protected Action process() throws Exception
                         int off = slice.arrayOffset() + slice.position();
                         int len = slice.remaining();
                         _crc.update(array, off, len);
-                        _deflater.setInput(array, off, len);  // TODO use ByteBuffer API in Jetty-10
+                        _deflater.setInput(array, off, len);
```
Comment (lachlan-roberts) [inline jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java:359]: @gregw I think its probably best not to use the deflaters ByteBuffer method here, the `CRC32` will need an array from the `ByteBuffer` anyway, and if we do it ourselves we get the use the `ByteBufferPool`.

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java [hunk 2]
```diff
@@ -168,7 +172,7 @@
     // non-static, as other GzipHandler instances may have different configurations
     private final IncludeExclude<String> _methods = new IncludeExclude<>();
     private final IncludeExclude<String> _paths = new IncludeExclude<>(PathSpecSet.class);
-    private final IncludeExclude<String> _mimeTypes = new IncludeExclude<>();
+    private final IncludeExclude<String> _mimeTypes = new IncludeExclude<>(CaseInsensitiveSet.class);
```
Comment (joakime) [inline jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java]: Can you use TreeSet instead?

``` java
Set<String> foo = new TreeSet<>(String.CASE_INSENSITIVE_ORDER);
foo.add("Bar");
foo.add("bar");
foo.add("BAR");
foo.add("ZED");
foo.add("zed");

System.out.printf("Has %d elements%n", foo.size());
System.out.printf("contains('baR') = %b%n", foo.contains("baR"));
System.out.printf("contains('zeD') = %b%n", foo.contains("zeD"));
System.out.printf("contains('baz') = %b%n", foo.contains("baz"));
```

Results in ...
```
Has 2 elements
contains('baR') = true
contains('zeD') = true
contains('baz') = false
```

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java [hunk 3]
```diff
@@ -887,17 +902,60 @@ public void setDeflaterPoolCapacity(int capacity)
...
+        return new DeflaterPool(CompressionPool.INFINITE_CAPACITY, Deflater.DEFAULT_COMPRESSION, true);
     }
 
     @Override
     public String toString()
     {
         return String.format("%s@%x{%s,min=%s,inflate=%s}", getClass().getSimpleName(), hashCode(), getState(), _minGzipSize, _inflateBufferSize);
     }
+
+    public static class CaseInsensitiveSet extends HashSet<String>
```
Comment (joakime) [inline jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java]: This can be simplified to just ...

``` java
    public static class CaseInsensitiveSet extends TreeSet<String>
    {
        public CaseInsensitiveSet()
        {
            super(String.CASE_INSENSITIVE_ORDER);
        }
    }
```

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java [hunk 4]
```diff
@@ -771,6 +773,19 @@ public void setExcludedPaths(String... pathspecs)
...
+     *
+     * @param dispatchers the set of {@link DispatcherType} that this filter will operate on
+     */
+    public void setDispatcherTypes(String... dispatchers)
+    {
+        setDispatcherTypes(Stream.of(dispatchers)
+            .flatMap(s -> Stream.of(StringUtil.csvSplit(s)))
+            .map(DispatcherType::valueOf)
+            .toArray(DispatcherType[]::new));
+    }
```
Comment (joakime) [inline jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java:788]: How about ...

``` java
    public void setDispatcherTypes(String... dispatchers)
    {
        _dispatchers = EnumSet.copyOf(
            Stream.of(dispatchers)
                .flatMap(s -> Stream.of(StringUtil.csvSplit(s)))
                .map(DispatcherType::valueOf)
                .collect(Collectors.toSet())
        );
    }
```

**Review by joakime — CHANGES_REQUESTED** [review]
Some minor improvements suggested.

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java]: I thought about this, won't this slow access down from O(1) to O(log n), and we don't really need it to be sorted. Not sure how much this would actually impact the performance.

Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java]: There's only what? like 5 DispatcherTypes?
And the only impact is on setup/configuration/initialization, no real impact during runtime.

Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java]: This is more MIME types, but yeah probably won't be that many in the set.
The set should be accessed on every request.

Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java]: Would a `AsciiLowerCaseSet` in jetty-util be useful (in general)?

Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java]: Another difference ... TreeSet doesn't allow null entries. HashSet does.

Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java]: I think it could be useful in jetty-util, although I don't know where else it could be used.

Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java]: I have now moved this to jetty-util.

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java:359]: I have added a comment as to why we are not using the ByteBuffer API for deflaters.

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java [hunk 5]
```diff
@@ -887,12 +903,38 @@ public void setDeflaterPoolCapacity(int capacity)
...
+    protected InflaterPool newInflaterPool()
+    {
+        return new InflaterPool(CompressionPool.INFINITE_CAPACITY, true);
     }
 
-    protected DeflaterPool newDeflaterPool(int capacity)
+    protected DeflaterPool newDeflaterPool()
     {
-        return new DeflaterPool(capacity, Deflater.DEFAULT_COMPRESSION, true);
+        return new DeflaterPool(CompressionPool.INFINITE_CAPACITY, Deflater.DEFAULT_COMPRESSION, true);
```
Comment (joakime) [inline jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java:937]: What does "INFINITE_CAPACITY" mean?

Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java:937]: It means there is no limit on the number of objects allowed to be pooled.
This is now changed later by the setter, as I have made the capacity of the pool configurable after it is constructed. This lets us make the pool final and add it as a bean to the GzipHandler.

Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java:937]: We want to eventually switch the pools over to using the Pool class, which has it's size set when constructed.  So we need to not assume that the pool size can be configured after construction.

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java [hunk 6]
```diff
@@ -355,7 +354,9 @@ protected Action process() throws Exception
                         int off = slice.arrayOffset() + slice.position();
                         int len = slice.remaining();
                         _crc.update(array, off, len);
-                        _deflater.setInput(array, off, len);  // TODO use ByteBuffer API in Jetty-10
+                        // Ideally we would want to use the ByteBuffer API for Deflaters. However due the the ByteBuffer implementation
+                        // of the CRC32.update() it is less efficient for us to use this rather than to convert to array ourselves.
+                        _deflater.setInput(array, off, len);
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java:359]: Good comment, but can we raise a bug on the JVM to provide an efficient implementation of CRC32 that does not copy ByteBuffers?

**Comment by lachlan-roberts** [comment]
@gregw this PR is ready for review.

**Comment by gregw** [comment]
@lachlan-roberts OK looking... but can you start a second PR that will replace the inflater and deflater pools with a Pool.  This can be in 9.4

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java (hunk 6 above)
Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java:359]: It only does the copying if it is not a `DirectBuffer` and does not have an array.
I don't think I can raise JVM bugs anyway, @sbordet could do this.

Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java:359]: or is a readonly buffer!

Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHttpOutputInterceptor.java:359]: or if it is read-only!

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java (hunk 5 above)
Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java:937]: Opened PR #5295, which uses the new `Pool` class for the `CompressionPool` and still allows the pool size to be changed before it is started.

**Comment by lachlan-roberts** [comment]
@gregw I think we should merge this before considering the further changes to make `CompressionPool` use the new `Pool` class.

**Review by gregw — APPROVED** [review]
