### PR TITLE
Fixes #4904 - WebsocketClient creates more connections than needed.

### LINKED ISSUE #4904: WebsocketClient creates more connections than needed
**Jetty version**
9.4.28
**Java version**
1.8.0.242 adopt openjdk
**OS type/version**
mac
**Description**
I noticed the websocket client is creating more connections than needed when multiple connect is called concurrently.

When I run the following, I see established count went to 64 (expected 50):
```sh
watch -n 0.5 "netstat -an -p tcp | awk '{ print \$4, \$5, \$6 }' | grep ESTABLISHED | grep 174.129.224 | wc -l"
```

```java
public class SimpleSecureEchoClient
{
  public static void main(String[] args)
  {
    String destUri = "wss://echo.websocket.org";
    if (args.length > 0)
    {
      destUri = args[0];
    }

    SslContextFactory ssl = new SslContextFactory.Client();
    ssl.addExcludeProtocols("tls/1.3");
    ssl.setExcludeCipherSuites(); // websocket.org only uses WEAK cipher suites
    HttpClient http = new HttpClient(ssl);
    WebSocketClient client = new WebSocketClient(http);
    ExecutorService executorService = Executors.newFixedThreadPool(50);

    try
    {
      http.start();
      client.start();

      URI echoUri = new URI(destUri);


      for (int i = 0; i < 50; i++) {
        executorService.submit(() -> connect(client, echoUri));
      }

    }
    catch (Throwable t)
    {
      t.printStackTrace();
    }
    finally
    {
      executorService.shutdown();
      try {
        executorService.awaitTermination(10, TimeUnit.SECONDS);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      stop(http);
      stop(client);
    }
  }

  private static void connect(final WebSocketClient client, final URI echoUri) {
    try {
    ClientUpgradeRequest request = new ClientUpgradeRequest();
    SimpleEchoSocket socket = new SimpleEchoSocket();
    request.setHeader("Origin", "https://websocket.org/");
    client.connect(socket, echoUri, request);
    System.out.printf("Connecting to : %s%n", echoUri);
    // wait for closed socket connection.
    socket.awaitClose(5, TimeUnit.SECONDS);
    } catch (Throwable t) {
      t.printStackTrace();
    }
  }

  private static void stop(LifeCycle lifeCycle)
  {
    try
    {
      lifeCycle.stop();
    }
    catch (Exception e)
    {
      e.printStackTrace();
    }
  }
```

### PR DESCRIPTION
**Pull request by sbordet**
Fixed connection pool's `acquire()` methods to correctly take into account the number of queued requests.

Also fixed a collateral bug in `BufferingResponseListener` - wrong calculation of the max content length.

Restored `ConnectionPoolTest` that was disabled in #2540, cleaned it up, and let it run for hours without failures.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

**Comment by sbordet** [comment]
@gregw @lorban ready to review now.

File: jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java [hunk 1]
```diff
@@ -44,13 +44,13 @@
...
     private final AtomicBiInteger connections = new AtomicBiInteger();
-    private final Destination destination;
+    private final HttpDestination destination;
     private final int maxConnections;
     private final Callback requester;
 
     protected AbstractConnectionPool(Destination destination, int maxConnections, Callback requester)
     {
-        this.destination = destination;
+        this.destination = (HttpDestination)destination;
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:52]: IF this can now only be a HttpDestination, why not change the signature of the constructor?

File: jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java [hunk 2]
```diff
@@ -98,11 +98,17 @@ public boolean isClosed()
 
     @Override
     public Connection acquire()
+    {
+        return acquire(true);
+    }
+
+    protected Connection acquire(boolean create)
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:115]: javadoc needed to explain the behaviour of this method...  well perhaps tryCreate needs more javadoc too...

File: jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java [hunk 3]
```diff
@@ -98,11 +98,17 @@ public boolean isClosed()
...
     {
         Connection connection = activate();
         if (connection == null)
         {
-            tryCreate(-1);
+            if (create)
+                tryCreate(destination.getQueuedRequestCount());
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:121]: comment on the strategy here.

File: jetty-client/src/main/java/org/eclipse/jetty/client/HttpConnection.java [hunk 4]
```diff
@@ -228,6 +228,8 @@ protected SendFailure send(HttpChannel channel, HttpExchange exchange)
             }
             else
             {
+                // Association may fail for example if the application
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/HttpConnection.java]: comma after fail

File: jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java [hunk 5]
```diff
@@ -439,25 +459,27 @@ public void release(Connection connection)
...
-            // We need to execute queued requests even if this connection failed.
-            // We may create a connection that is not needed, but it will eventually
-            // idle timeout, so no worries.
+            // We need to execute queued requests
+            // even if this connection was removed.
+            // We may create a connection that is not
+            // needed, but it will eventually idle timeout.
             if (removed)
-                process();
+                process(true);
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java]: should this check that the queue is not 0?  Why acquire a connection if there are no waiting exchanges?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java (hunk 1 above)
Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:52]: Because people may have created their own subclasses and it would break them.
Will do the change in 10 though.

File: jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java (hunk 5 above)
Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java]: The check for the queue is done few lines above. Do you want to do it again here?

File: jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java [hunk 6]
```diff
@@ -98,16 +97,41 @@ public boolean isClosed()
...
     @Override
     public Connection acquire()
+    {
+        return acquire(true);
+    }
+
+    /**
+     * <p>Returns an idle connection, if available;
+     * if an idle connection is not available, and the given {@code create} parameter is {@code true},
+     * then schedules the opening of a new connection;
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java]: Does it always create a new connection?    This should say `if possible` or `may schedule....` . At the very least refer to `tryCreate` for the actual strategy applied.

File: jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java (hunk 5 above)
Comment (gregw) [reply jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java]: Opps didn't see that.  

An `else if (removed)` would be clearer that there is a condition above.

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-client/src/main/java/org/eclipse/jetty/client/MultiplexConnectionPool.java [hunk 7]
```diff
@@ -64,7 +64,11 @@ public Connection acquire()
         Connection connection = activate();
         if (connection == null)
         {
-            int maxPending = 1 + destination.getQueuedRequestCount() / getMaxMultiplex();
```
Comment (lorban) [inline jetty-client/src/main/java/org/eclipse/jetty/client/MultiplexConnectionPool.java:67]: How about this one-liner instead?
```
int maxPending = (destination.getQueuedRequestCount() + getMaxMultiplex() - 1) / getMaxMultiplex();
```

File: jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java [hunk 8]
```diff
@@ -98,16 +97,41 @@ public boolean isClosed()
...
+     * otherwise returns {@code null}.</p>
+     *
+     * @param create whether to schedule the opening of a connection if no idle connections are available
+     * @return an idle connection or {@code null} if no idle connections are available
+     */
+    protected Connection acquire(boolean create)
```
Comment (lorban) [inline jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:115]: The documented contract is not respected by the `RoundRobinConnectionPool` subclass. That should probably be documented too.

File: jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java (hunk 5 above)
Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java]: I think an `else if` would then require the code comment to be moved to a less ideal place so I'm inclined to leave as is.

Comment (gregw) [reply jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java]: The comment would be better in the body of the else if, as it would not need to repeat the "if removed":
```java
if (getHttpExchanges().isEmpty())
{
    tryRemoveIdleDestination();
}
else if (removed)
{
   // Process queued exchanges because waiting exchanges may now be able to progress. 
   process(true);
}

File: jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java [hunk 9]
```diff
@@ -439,25 +459,27 @@ public void release(Connection connection)
...
         }
+        return connectionPool.remove(connection);
+    }
+
+    public void close(Connection connection)
```
Comment (lorban) [inline jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java:483]: Since `close(Connection)` and `remove(Connection)` are now identical, shouldn't one of them be removed?

**Review by gregw — APPROVED** [review]
Some niggles, but LGTM.

File: jetty-client/src/main/java/org/eclipse/jetty/client/RoundRobinConnectionPool.java [hunk 10]
```diff
@@ -69,6 +69,14 @@ public void setMaxMultiplex(int maxMultiplex)
         }
     }
 
+    @Override
+    protected Connection acquire(boolean create)
```
Comment (lorban) [inline jetty-client/src/main/java/org/eclipse/jetty/client/RoundRobinConnectionPool.java:80]: As mentioned earlier, this implementation breaks the javadoc's contract.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-client/src/main/java/org/eclipse/jetty/client/MultiplexConnectionPool.java (hunk 7 above)
Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/MultiplexConnectionPool.java:67]: That is obfuscated... Does it do `ceiling(a/b)`?

File: jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java (hunk 8 above)
Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:115]: Documented.

File: jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java (hunk 9 above)
Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/HttpDestination.java:483]: I deprecated `close(Connection)` to be removed in 10.

File: jetty-client/src/main/java/org/eclipse/jetty/client/MultiplexConnectionPool.java (hunk 7 above)
Comment (lorban) [reply jetty-client/src/main/java/org/eclipse/jetty/client/MultiplexConnectionPool.java:67]: Yes, it's the integer version of the following: 
```
Math.ceil((double) destination.getQueuedRequestCount() / getMaxMultiplex())
```

**Review by lorban — APPROVED** [review]

**Review by lorban — APPROVED** [review]

File: jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java (hunk 1 above)
Comment (joakime) [reply jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:52]: You could create a second constructor that does the right thing and deprecate the old one (preparing people for the Jetty 10 change).

Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:52]: @joakime good point, done.
