### PR TITLE
Fixes #13131 - Surface received GOAWAY in HttpClient.

### LINKED ISSUE #13131: Surface received GOAWAY in HttpClient
**Jetty version(s)**
12.0.x

**Enhancement Description**
Currently, when a server sends a GOAWAY, the client fails the streams that have id greater than the last-stream-id carried by the GOAWAY.

However, this failure is undistinguishable from other generic failures, so a high-level application has no way to know that the request was cancelled locally due to the GOAWAY, and that it can be safely retried.

There should be a mechanism for HTTP/2 and HTTP/3 that provides the high-level application with additional information about the failure of a request, so the application can take decisions whether to retry the request or not.

### PR DESCRIPTION
**Pull request by sbordet**
* Introduced RetryRequestException for the high-level APIs.
* Low-level HTTP/2 and HTTP/3 now fail local streams with id > goaway.last-stream-id with a RetryStreamException.
* When linking with the high-level APIs, RetryStreamException is converted to RetryRequestException, so applications can decide whether to retry the request.

### CODE REVIEW

**Comment by sbordet** [comment]
TODO:
* Perhaps rename the new exceptions to `Retryable...`?
* Make the `RetryStreamException` top-level classes?
* Documentation.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java [hunk 1]
```diff
@@ -1470,6 +1480,14 @@ default void onClose(Session session)
         }
     }
 
+    /**
+     * <p>Exception indicating that the HTTP/2 stream was not handled
+     * by the server, and can therefore be retried, if possible.</p>
+     */
+    public static class RetryStreamException extends RuntimeException
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java]: This doesn't need to be a `RuntimeException`, so it could extend from `Exception`.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/RetryRequestException.java [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+// ========================================================================
+//
+
+package org.eclipse.jetty.client;
+
+/**
+ * <p>Exception indicating that the HTTP request was not handled
+ * by the server, and can therefore be retried, if possible.</p>
+ */
+public class RetryRequestException extends RuntimeException
```
Comment (lorban) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/RetryRequestException.java]: This doesn't need to be a `RuntimeException`, so it could extend from `Exception`.

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java [hunk 3]
```diff
@@ -859,6 +857,14 @@ public String toString()
         return String.format("%s@%x[streams=%d,%s]", getClass().getSimpleName(), hashCode(), streamCount.get(), closeState);
     }
 
+    /**
+     * <p>Exception indicating that the HTTP/2 stream was not handled
+     * by the server, and can therefore be retried, if possible.</p>
+     */
+    public static class RetryStreamException extends RuntimeException
```
Comment (lorban) [inline jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java]: This doesn't need to be a `RuntimeException`, so it could extend from `Exception`.

**Review by lorban — CHANGES_REQUESTED** [review]
Besides the exceptions' type, LGTM.

**Review by lorban — APPROVED** [review]
