### PR TITLE
Issue #13993 - fixes for ThreadLimitHandler with NON_BLOCKING invocation type

### LINKED ISSUE #13993: Jetty 12 server deadlock
**Jetty version(s)**
12.0.22 and earlier

**Jetty Environment**
ee10

**HTTP version**
unknown

**Java version/vendor** `(use: java -version)`
```
openjdk version "21.0.9-ea" 2025-10-21
OpenJDK Runtime Environment (build 21.0.9-ea+8-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 21.0.9-ea+8-Ubuntu-1, mixed mode, sharing)
```

**OS type/version**
Ubuntu 25.10
kernel 6.17.0-6-generic

**Description**
Certain requests cause a deadlock in ResourceServlet.doGet() in a CompletableFuture.  This causes clients to time-out and a thread lost on the server.  Eventually, Jetty must be restarted due to lost threads.
Sample:

```
"qtp1301664418-1394" #1394 [252866] prio=5 os_prio=0 cpu=268.54ms elapsed=296294.48s allocated=1587K defined_classes=0 tid=0x00007ecfb0054640 nid=252866 waiting on condition  [0x00007ed011bec000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@21.0.9-ea/Native Method)
	- parking to wait for  <0x00000006809b4618> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@21.0.9-ea/LockSupport.java:221)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@21.0.9-ea/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@21.0.9-ea/ForkJoinPool.java:3780)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@21.0.9-ea/ForkJoinPool.java:3725)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@21.0.9-ea/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.get(java.base@21.0.9-ea/CompletableFuture.java:2072)
	at org.eclipse.jetty.util.Blocker$2.block(Blocker.java:169)
	at org.eclipse.jetty.ee10.servlet.ResourceServlet.doGet(ResourceServlet.java:579)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1385)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:751)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1622)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1555)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:823)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:440)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:470)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1071)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:181)
	at org.eclipse.jetty.server.handler.ThreadLimitHandler$LimitedRequest.handle(ThreadLimitHandler.java:327)
	at org.eclipse.jetty.server.handler.ThreadLimitHandler$LimitedRequest.handle(ThreadLimitHandler.java:313)
	at org.eclipse.jetty.server.handler.ThreadLimitHandler.onConditionsMet(ThreadLimitHandler.java:171)
	at org.eclipse.jetty.server.handler.ConditionalHandler.handle(ConditionalHandler.java:378)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:563)
	at org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:677)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:416)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:480)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:443)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:981)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1211)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1166)
	at java.lang.Thread.runWith(java.base@21.0.9-ea/Thread.java:1596)
	at java.lang.Thread.run(java.base@21.0.9-ea/Thread.java:1583)
```

**How to reproduce?**
Unknown.  Bots are causing the deadlock.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
### Closes #13993

It is possible for the `ThreadLimitHandler` to get into a deadlock situation, in the case where the handling threads are doing blocking IO waiting on a callback/runnable to be completed, and the `ThreadLimitHandler` will not allow the callback to be run because all the permits are used by the handling threads.

This fixes this by allowing `NON_BLOCKING` invocables to not need to acquire a permit in the `ThreadLimitHandler`.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java [hunk 1]
```diff
@@ -346,8 +346,15 @@ public void demand(Runnable onContent)
             super.demand(new DemandTask(Invocable.getInvocationType(onContent)));
         }
 
-        private void onContent()
+        private void onContent(InvocationType invocationType)
         {
+            // If the invocation type is NON_BLOCKING we do not require a permit.
+            if (invocationType == InvocationType.NON_BLOCKING)
+            {
+                onPermittedContent(null);
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: Don't pass null but rather an instance of `NoopPermit`. There is already a static constant in the `Remote` class that could be moved to the `NoopPermit` class instead.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java [hunk 2]
```diff
@@ -364,7 +371,8 @@ private void onPermittedContent(Permit permit)
             }
             finally
             {
-                permit.release();
+                if (permit != null)
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: Use `NoopPermit` to get rid of the null check.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java [hunk 3]
```diff
@@ -420,13 +435,21 @@ private void permittedSuccess(Permit permit)
...
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: Use `NoopPermit` to get rid of the null check.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java [hunk 4]
```diff
@@ -442,7 +465,8 @@ private void permittedFailure(Permit permit, Throwable x)
...
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: Use `NoopPermit` to get rid of the null check.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java [hunk 5]
```diff
@@ -405,6 +413,13 @@ public void write(boolean last, ByteBuffer byteBuffer, Callback callback)
         @Override
         public void succeeded()
         {
+            Callback callback = _writeCallback.get();
+            if (callback.getInvocationType() == InvocationType.NON_BLOCKING)
+            {
+                permittedSuccess(null);
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: Don't pass null but rather an instance of `NoopPermit`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java [hunk 6]
```diff
@@ -420,13 +435,21 @@ private void permittedSuccess(Permit permit)
...
             }
         }
 
         @Override
         public void failed(Throwable x)
         {
+            Callback callback = _writeCallback.get();
+            if (callback.getInvocationType() == InvocationType.NON_BLOCKING)
+            {
+                permittedFailure(null, x);
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: Don't pass null but rather an instance of `NoopPermit`.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java [hunk 7]
```diff
@@ -378,4 +386,127 @@ public void run()
...
+
+        // Validate the first 100 bytes of the response.
+        byte[] bytes = client.getInputStream().readNBytes(100);
+        String utf8String = StringUtil.toUTF8String(bytes, 0, bytes.length);
+        assertThat(utf8String, Matchers.containsString(" 200 OK"));
+        assertThat(utf8String, Matchers.containsString("xxxxx"));
+
+        // Delay to let the write side get TCP blocked, then close the connection.
+        // This ensures the server write callback will be failed by a different thread.
+        Thread.sleep(1000);
```
Comment (lorban) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java]: Please do not rely on time. If you want to wait until the writer is blocked because of TCP congestion, use the following trick:

 - create an atomic ref: `AtomicReference<Thread> threadRef = new AtomicReference<>();`
 - fill the ref from the handler: `threadRef.set(Thread.currentThread());`
 - use awaitility to wait for the thread to be in WAITING state:
```java
        await().atMost(5, TimeUnit.SECONDS).until(() ->
        {
            Thread thread = threadRef.get();
            return thread != null && thread.getState() == Thread.State.WAITING;
        });
```

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java [hunk 8]
```diff
@@ -346,8 +346,15 @@ public void demand(Runnable onContent)
             super.demand(new DemandTask(Invocable.getInvocationType(onContent)));
         }
 
-        private void onContent()
+        private void onContent(InvocationType invocationType)
         {
+            // If the invocation type is NON_BLOCKING we do not require a permit.
+            if (invocationType == InvocationType.NON_BLOCKING)
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: for completeness, we should also support invocationType.EITHER.   If it is either, then we should use a NoopPermit and then invoke non-blocking.

**Review by gregw — CHANGES_REQUESTED** [review]
EITHER

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: See latest updates, no longer calling `onPermittedContent` here, so no need for the NoopPermit.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java (hunk 7 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java]: This worked, thanks.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java (hunk 8 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: Done.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: This is now done as part of `case BLOCKING`, did you forget to remove that code?

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java [hunk 9]
```diff
@@ -378,4 +386,133 @@ public void run()
...
+
+        // Validate the first 100 bytes of the response.
+        byte[] bytes = client.getInputStream().readNBytes(100);
+        String utf8String = StringUtil.toUTF8String(bytes, 0, bytes.length);
+        assertThat(utf8String, Matchers.containsString(" 200 OK"));
+        assertThat(utf8String, Matchers.containsString("xxxxx"));
+
+        // Delay to let the write side get TCP blocked, then close the connection.
+        // This ensures the server write callback will be failed by a different thread.
+        await().atMost(5, TimeUnit.SECONDS).pollDelay(1, TimeUnit.SECONDS).until(() ->
```
Comment (lorban) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java]: There is no need for a `pollDelay`.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java
Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ThreadLimitHandler.java]: Yep, good catch. This should have been removed.

Removed now.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java (hunk 9 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ThreadLimitHandlerTest.java]: I was using this to manually test something, but forgot to remove it.

I have removed it now.

**Review by gregw — APPROVED** [review]

**Review by lorban — APPROVED** [review]
LGTM, can be ported to 12.1.x as is.
