### PR TITLE
Issue #10231 - ee10 `DefaultServlet` HTTP method support.

### LINKED ISSUE #10231: DefaultServlet no longer supports POST and OPTIONS and returns a 405 instead
**Jetty version(s)**
12 beta 4

**Description**
Bug or feature? That is probably the question here. Most of the time it is probably used only for a index.jsp that does a redirect etc. But in my case it can happen that it is also called using a POST. And others might expect OPTIONS to work there. As this used to work in previous versions and also works for example in Tomcat I would consider this at least quite unexpected and as long there is no really good reason for not supporting POST and OPTIONS the old behavior should be restored IMHO

**Edit:** I just realized that this seems to affect only EE10 while it still should work in EE9? Is that on purpose or a bug?

### PR DESCRIPTION
**Pull request by joakime**
Adding testing (and implementations) for the following methods.

+ `HEAD` support 
+ `TRACE` returns 405 Method Not Allowed
+ `OPTIONS` supported with hard coded `Allow: GET, HEAD, OPTIONS` header
+ `POST` returns 405 Method Not Allowed

### CODE REVIEW

**Comment by joakime** [comment]
Also added same tests to ee9 impl and adjusted the POST / OPTIONS behavior (that wasn't being tested before this PR)

**Review by gregw — DISMISSED** [review]

**Review by sbordet — DISMISSED** [review]

File: jetty-ee9/jetty-ee9-servlets/src/test/java/org/eclipse/jetty/ee9/servlets/AbstractGzipTest.java [hunk 1]
```diff
@@ -45,7 +45,7 @@ public abstract class AbstractGzipTest
 {
     protected static final int DEFAULT_OUTPUT_BUFFER_SIZE = new HttpConfiguration().getOutputBufferSize();
 
-    protected WorkDir workDir;
+    public WorkDir workDir;
```
Comment (joakime) [inline jetty-ee9/jetty-ee9-servlets/src/test/java/org/eclipse/jetty/ee9/servlets/AbstractGzipTest.java:48]: Necessary to run GzipDefaultServletTest in debug on IDE. (junit5 is more strict with setAccessible behaviors now)

File: jetty-ee9/jetty-ee9-servlets/src/test/java/org/eclipse/jetty/ee9/servlets/GzipDefaultServletTest.java [hunk 2]
```diff
@@ -85,6 +85,7 @@ public void testIsGzipByMethod(String method) throws Exception
         ServletContextHandler servletContextHandler = new ServletContextHandler();
         servletContextHandler.setContextPath("/context");
         servletContextHandler.setBaseResource(ResourceFactory.of(server).newResource(contextDir));
+        // The WibbleDefaultServlet overrides the method behaviors
```
Comment (joakime) [inline jetty-ee9/jetty-ee9-servlets/src/test/java/org/eclipse/jetty/ee9/servlets/GzipDefaultServletTest.java:88]: Explaining what is happening

**Review by sbordet — APPROVED** [review]
