### PR TITLE
Issue #11776 - NPE protection in Request.getServerPort

### LINKED ISSUE #11776: NPE from `org.eclipse.jetty.ee8.nested.Request.getRequestURL`
**Jetty version(s)**
12.0.9

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**

```
Cause: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
StackTrace: 
org.eclipse.jetty.util.AbstractTrie.get(AbstractTrie.java:66)
org.eclipse.jetty.server.Request.getServerPort(Request.java:489)
org.eclipse.jetty.ee8.nested.Request.getServerPort(Request.java:1142)
org.eclipse.jetty.ee8.nested.Request.getRequestURL(Request.java:1088)
```

### PR DESCRIPTION
**Pull request by joakime**
If the HttpURI is scheme-less, the attempt to get the port can result in a NPE.

Fixes: #11776

### CODE REVIEW

**Review by olamy — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 1]
```diff
@@ -486,9 +486,13 @@ static int getServerPort(Request request)
...
-        HttpScheme scheme = HttpScheme.CACHE.get(request.getHttpURI().getScheme());
-        if (scheme != null && scheme.getDefaultPort() > 0)
-            return scheme.getDefaultPort();
+        String rawScheme = uri.getScheme();
+        if (StringUtil.isNotBlank(rawScheme))
+        {
+            HttpScheme scheme = HttpScheme.CACHE.get(rawScheme);
+            if (scheme != null && scheme.getDefaultPort() > 0)
+                return scheme.getDefaultPort();
+        }
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: I think most (all?) of our `Index.get(String, int, int)` are robust to having a null passed.  Some even support a null key value I think.

So I think it might be better to fix the `AbstractIndex` impl of `Index.get` to:
```
    public V get(String s)
    {
        return get(s, 0, s == null ? 0 : s.length());
    }
```

@lorban thoughts?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: I second that. We can easily consider a null key to be equivalent to a zero-length string when null keys are not supported so I see no reason why we shouldn't do that. That should be reflected in the `Index` javadoc too.

**Comment by lorban** [comment]
@gregw FYI I'm taking over this PR.

**Review by gregw — APPROVED** [review]
LGTM
