### PR TITLE
Fix `SettingsTest` flakiness

### LINKED ISSUE #13038: `SettingsTest.testMaxHeaderListSizeExceededByClient()` is flaky
**Jetty version(s)**
12.0.x

**Description**
`SettingsTest.testMaxHeaderListSizeExceededByClient()` sometimes fails with:

```
org.opentest4j.AssertionFailedError: Expected java.util.concurrent.ExecutionException to be thrown, but nothing was thrown.
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:73)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at org.eclipse.jetty.http2.tests.SettingsTest.testMaxHeaderListSizeExceededByClient(SettingsTest.java:440)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

See: https://github.com/jetty/jetty.project/pull/13017/checks?check_run_id=41013153586

### PR DESCRIPTION
**Pull request by lorban**
Fixes #13038

### CODE REVIEW

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/SettingsTest.java [hunk 1]
```diff
@@ -431,7 +431,16 @@ public void onGoAway(Session session, GoAwayFrame frame)
             }
         });
 
-        Session clientSession = newClientSession(new Session.Listener() {});
+        CountDownLatch clientSettingsLatch = new CountDownLatch(1);
+        Session clientSession = newClientSession(new Session.Listener() {
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/SettingsTest.java]: Brace at EOL. Fix them all.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/SettingsTest.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/SettingsTest.java]: That broke checkstyle; fixed.

**Review by sbordet — APPROVED** [review]
