### PR TITLE
Fixes #10277 - Review read failures impacting writes.

### LINKED ISSUE #10277: Review read failures impacting writes
**Jetty version(s)**
12

**Description**
Read failures should not impact writes (too much), as a write might still be possible even if the read failed.
Typical examples are early EOF in reads -- they should not impact writes.

The idea is that if a read failure is catastrophic, we would attempt the write anyway and will get the failure through the write, rather than assuming that the writes will fail.

Child issues / prs
 - [ ] #10431 
 - [ ] #10432

### PR DESCRIPTION
**Pull request by sbordet**
Separated read failures from write failures.
In this way it is possible to read even if the write side is failed and write even if the read side is failed.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 1]
```diff
@@ -1115,78 +1111,76 @@ public void write(boolean last, ByteBuffer content, Callback callback)
         {
             long length = BufferUtil.length(content);
 
-            HttpChannelState httpChannelState;
+            HttpChannelState httpChannel;
```
Comment (joakime) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1120]: Why this name change?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 2]
```diff
@@ -1199,14 +1193,13 @@ public void succeeded()
         {
             if (LOG.isDebugEnabled())
                 LOG.debug("write succeeded {}", this);
-            // Called when an individual write succeeds.
```
Comment (joakime) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1202]: Why eliminate these comments?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 3]
```diff
@@ -1227,14 +1220,14 @@ public void failed(Throwable x)
         {
             if (LOG.isDebugEnabled())
                 LOG.debug("write failed {}", this, x);
-            // Called when an individual write succeeds.
```
Comment (joakime) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1230]: Ditto on comment removal?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 4]
```diff
@@ -394,10 +386,10 @@ public Runnable onFailure(Throwable x)
...
 
             // Set the error to arrange for any subsequent reads, demands or writes to fail.
-            if (_failure == null)
-                _failure = Content.Chunk.from(x, true);
-            else if (ExceptionUtil.areNotAssociated(_failure.getFailure(), x) && _failure.getFailure().getClass() != x.getClass())
-                _failure.getFailure().addSuppressed(x);
+            if (_readFailure == null)
+                _readFailure = Content.Chunk.from(x, true);
+            else if (ExceptionUtil.areNotAssociated(_readFailure.getFailure(), x) && _readFailure.getFailure().getClass() != x.getClass())
+                _readFailure.getFailure().addSuppressed(x);
```
Comment (joakime) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Seems like this else branch could just be ...

```suggestion
            else
                ExceptionUtil.addSuppressedIfNotAssociated(_readFailure.getFailure(), x);
```

**Comment by joakime** [comment]
Interesting.
This PR has tests that have historically expected a failure are now succeeding unexpectedly.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1120]: Shorter and used elsewhere as just `httpChannel`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1202]: Because they add nothing and repeat exactly what's written in the log the line above.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1230]: Because it's wrong (should be "write fails") and repeats exactly what's written in the log the line above.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 4 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: The logic is different as there is the check on the class.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 5]
```diff
@@ -330,15 +322,15 @@ public Runnable onIdleTimeout(TimeoutException t)
                 LOG.debug("onIdleTimeout {}", this, t);
 
             // if not already a failure,
-            if (_failure == null)
+            if (_readFailure == null)
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:325]: There is a big assumption here (probably correct), that the `_writeFailure` can never be null when the `_readFailure` is not null.  If that was possible, then a new idle timeout would not be delivered to a write because the read had already failed (at least transitively).

I think we should have some asserts to declare these invariants: 

```suggestion
            assert _readFailure == null  || _readFailure != null && _response._writeFailure != null;
            assert _writeFailure == null || _writeFailure != null && _writeFailure.isLast();
            
            if (_readFailure == null)
```

Maybe do the same asserts in onFailure below.

**Review by gregw — CHANGES_REQUESTED** [review]

**Review by gregw — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:325]: @gregw I think there should not be that assumption, and I removed it from the latest code.
The 2 failures should be independent, so I did not add asserts.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 6]
```diff
@@ -329,43 +321,43 @@ public Runnable onIdleTimeout(TimeoutException t)
...
+                // If there was demand, then arrange for the next read to return a transient chunk failure.
                 if (invokeOnContentAvailable != null)
-                    _failure = Content.Chunk.from(t, false);
+                    _readFailure = Content.Chunk.from(t, false);
+            }
 
-                // If a write call is in progress, take the writeCallback to fail below
-                Runnable invokeWriteFailure = _response.lockedFailWrite(t);
+            // If a write call is pending, take the writeCallback to fail below.
+            Runnable invokeWriteFailure = _response.lockedFailWrite(t, false);
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:337]: the `lockFailWrite` method does not handle the case that there is already a write failure.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 5 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:325]: OK, but you now need to protect the write failure.  See below....

**Review by gregw — DISMISSED** [review]

**Review by gregw — CHANGES_REQUESTED** [review]
@sbordet the changes for the existing write failure are good... but the change to call onFailure appears to be breaking some tests.   Can we revert those and try after this release?  I have some more error changes that might be needed to handle the AsyncIOServletTests that are currently disabled and that I will be looking at as part of #10933

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 7]
```diff
@@ -1649,41 +1641,23 @@ private class HttpChannelSerializedInvoker extends SerializedInvoker
...
+                // It is too late to handle error.
                 super.onError(task, failure);
+                return;
             }
-            else if (error == null)
-            {
-                // Try to fail the request, but we might lose a race.
-                try
-                {
-                    request._callback.failed(failure);
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1671]: I've thought about this some more and I'm OK with this failed called, at least until we are sure.  In the HandlerInvoker, we do similar if the call to handle throws.  This is much the same thing.

Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1671]: @gregw not sure it's the same thing. If we throw from handle() we documented "equivalent to fail callback", but throwing e.g. from a request listener or from a demand callback or from a write callback does not seem equivalent as leaving handle() with an exception.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1671]: @sbordet I'm not sure either.  Your build is green, so OK for this release... but it is a cautious OK.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1671]: @sbordet throwing from a callback that is not meant to throw is a pretty good indication of an application that is not behaving correctly.   I wonder at the wisdom of letting it hang forever saying "you should not have thrown and should have called the callback yourself", when we already know it is broken and if they complain that we have failed the callback, then we just say "don't throw!"

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1671]: It might be better to always fail the callback in this case?

Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1671]: I think of it in a different way: it's an unexpected failure and we have a mechanism for that, failure listeners.

Register a failure listener and you will be notified and you can complete the callback (as you can't really do much else).

[Here](https://github.com/jetty/jetty.project/issues/10916#issuecomment-1830166219) a proposal for a catch-all `Handler`.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1671]: The catch-all is a good idea regardless.     I'm just worried about us being too purist.  We know an application that throws from a callback is bad and we know that we will probably hang forever on that request. 
I agree that we should never fail the callback if there is a possibility the application is acting correctly, but I'm OK with failing it when we know it is not.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1671]: @sbordet eitherway, let's punt to next release. we have more error work to do anyway.

**Review by gregw — APPROVED** [review]
I'll approve as I do not want to hold up the release.
But I still do not agree with the change to handling of exceptions thrown from serialized tasks.  I think we are being too purist and it will bite us.
