### PR TITLE
Issue #5170 - fix NPE during websocket upgrade

### LINKED ISSUE #5170: NullPointerException in HttpReceiverOverHTTP during WebSocket client Upgrade
**Jetty version**
10.0.x

**Description**

Had this exception come up a few times in different websocket tests. This stack trace is from `WebSocketStatsTest`.
This seems to occur very infrequently, have to run the test many times for this to have a chance of happening.

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.eclipse.jetty.websocket.tests.WebSocketStatsTest.echoStatsTest(WebSocketStatsTest.java:127)
        ...
Caused by: java.lang.NullPointerException
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.onUpgradeFrom(HttpReceiverOverHTTP.java:134)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onUpgradeFrom(HttpConnectionOverHTTP.java:202)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:439)
	at org.eclipse.jetty.websocket.core.client.CoreClientUpgradeRequest.upgrade(CoreClientUpgradeRequest.java:446)
	at org.eclipse.jetty.websocket.client.impl.JettyClientUpgradeRequest.upgrade(JettyClientUpgradeRequest.java:69)
	at org.eclipse.jetty.websocket.core.client.HttpUpgraderOverHTTP.upgrade(HttpUpgraderOverHTTP.java:96)
	at org.eclipse.jetty.client.UpgradeProtocolHandler$1.onComplete(UpgradeProtocolHandler.java:86)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpSender.terminateRequest(HttpSender.java:316)
	at org.eclipse.jetty.client.HttpSender.someToSuccess(HttpSender.java:212)
	at org.eclipse.jetty.client.HttpSender$ContentConsumer.succeeded(HttpSender.java:520)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.onCompleteSuccess(HttpSenderOverHTTP.java:259)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:315)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:219)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:84)
	at org.eclipse.jetty.client.HttpSender$ContentConsumer.onContent(HttpSender.java:482)
	at org.eclipse.jetty.client.util.AbstractRequestContent$AbstractSubscription.notifyContent(AbstractRequestContent.java:212)
	at org.eclipse.jetty.client.util.AbstractRequestContent$AbstractSubscription.processContent(AbstractRequestContent.java:186)
	at org.eclipse.jetty.client.util.BytesRequestContent$SubscriptionImpl.produceContent(BytesRequestContent.java:88)
	at org.eclipse.jetty.client.util.AbstractRequestContent$AbstractSubscription.produce(AbstractRequestContent.java:122)
	at org.eclipse.jetty.client.util.AbstractRequestContent$AbstractSubscription.demand(AbstractRequestContent.java:98)
	at org.eclipse.jetty.client.HttpSender.demand(HttpSender.java:241)
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:87)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:84)
	at org.eclipse.jetty.client.HttpChannel.send(HttpChannel.java:130)
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:107)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:288)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:148)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:392)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:368)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:322)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:308)
	at org.eclipse.jetty.client.HttpDestination.succeeded(HttpDestination.java:237)
	at org.eclipse.jetty.client.AbstractConnectionPool.proceed(AbstractConnectionPool.java:234)
	at org.eclipse.jetty.client.AbstractConnectionPool$1.succeeded(AbstractConnectionPool.java:197)
	at org.eclipse.jetty.client.AbstractConnectionPool$1.succeeded(AbstractConnectionPool.java:181)
	at org.eclipse.jetty.util.Promise$Wrapper.succeeded(Promise.java:157)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onOpen(HttpConnectionOverHTTP.java:156)
	at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:312)
	at org.eclipse.jetty.io.ClientConnector$ClientSelectorManager.connectionOpened(ClientConnector.java:342)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:371)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:1030)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:823)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:945)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Closes #5170**

During the WebSocket client upgrade, if the upgrade response completes before the upgrade request then we NPE or potentially just lose the initial bytes of the websocket connection which would corrupt or lose the initial websocket frames.

This change makes it so during an upgrade we do not release the network buffer in the `HttpReceiverOverHttp` until `onUpgradeFrom()` is called. This prevents the NPE and we do not lose the data for the initial websocket buffer.

### CODE REVIEW

File: jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java [hunk 1]
```diff
@@ -235,6 +235,10 @@ private boolean parse()
 
             if (complete)
             {
+                HttpExchange httpExchange = getHttpExchange();
+                if (httpExchange != null && httpExchange.getResponse().getStatus() == HttpStatus.SWITCHING_PROTOCOLS_101)
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java:239]: Previously the test for upgrade was: `connection != endPoint.getConnection()`
Now it is just 101 response status.   Don't we support upgrade like paths (eg for http2) that are not 101s?

**Review by gregw — COMMENTED** [review]
The main part thrust of this LGTM, but I'm a little concerned about the change in the upgrade test.

File: jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java (hunk 1 above)
Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java:239]: @gregw but this class is the HTTP/1.1 specific implementation so it cannot be anything else than 101.
The reason to not do the check to see if the connection was upgraded already is because the 101 response may be finished before the request, so the upgrade did not happen yet (but we know it will since it's a 101).

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java [hunk 2]
```diff
@@ -469,9 +469,12 @@ private void fillAndParse()
         }
         catch (Throwable t)
         {
-            LOG.warn(t.toString());
-            BufferUtil.clear(networkBuffer.getBuffer());
-            releaseNetworkBuffer();
+            LOG.warn("Error during fillAndParse()", t);
```
Comment (sbordet) [inline jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java]: This is now printing the whole stack trace, while before it was only a line.
I am not convinced that we should log this at WARN level, because any I/O error due to the other peer will show up as a big stack trace in the logs.
I'd change `warn()` to `debug()`.

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java [hunk 3]
```diff
@@ -469,9 +469,12 @@ private void fillAndParse()
...
+            if (networkBuffer != null)
+            {
+                BufferUtil.clear(networkBuffer.getBuffer());
+                releaseNetworkBuffer();
+            }
```
Comment (sbordet) [inline jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java:479]: Why do you need the NPE guard now?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java:479]: While reproducing this bug I was occasionally getting some `ReadPendingException` from `fillInterested()`, and we call this after we have already released the network buffer so it was null.

File: jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java]: I agree, we already give this error to the websocket endpoint with `processConnectionError` so no reason to warn here.

**Review by sbordet — APPROVED** [review]
