### PR TITLE
Issue #3481 unflushed TLS close notify

### LINKED ISSUE #3481: TLS close_notify() is not guaranteed
Hi. I've caught javax.net.ssl.SSLException: SSL peer shut down incorrectly exception on a client side. After debug enabled on jetty side i found out that Jetty failed to flush TLS close_notify(). I think this might be caused by socket sender buffer being full. I also read jetty source code and for some reason flushing close_notify() does not happen even it is commented in SSLConnection.flush() method:

```

switch (wrapResultStatus) {
        case CLOSED:
        // The SSL engine has close, but there may be close handshake that needs to be written
        if (BufferUtil.hasContent(_encryptedOutput)) {
           _cannotAcceptMoreAppDataToFlush = true;
           getEndPoint().flush(_encryptedOutput);
           getEndPoint().shutdownOutput();
           // If we failed to flush the close handshake then we will just pretend that
           // the write has progressed normally and let a subsequent call to flush
           // (or WriteFlusher#onIncompleteFlushed) to finish writing the close handshake.
           // The caller will find out about the close on a subsequent flush or fill.
           if (BufferUtil.hasContent(_encryptedOutput))
               return false;
           }
```

false returned value is not checked by caller:

```
else if (!oshut) {
           try {
               _sslEngine.closeOutbound();
               flush(BufferUtil.EMPTY_BUFFER); // Send close handshake // <--- returned value is not checked!
               SslConnection.this.fillInterested(); // seek reply FIN or RST or close handshake
```

Following WA for CLOSED case helps:

```
while(!getEndPoint().flush(_encryptedOutput) && i < 10) {
               try {
                   Thread.sleep(10);
               } catch (InterruptedException e) {
                   LOG.ignore(e);
               }
               i++;
}
getEndPoint().shutdownOutput();
```

### PR DESCRIPTION
**Pull request by gregw**
Fixes #3481 by:
 + if the close notify is not flushed then try again after a thread yield
 + if the retry does not flush then:
    - if close is true, don't bother with the flush and just proceed to close the encrypted
    - if close is false, schedule an async write to do the flush and proceed as if the decrypted endpoint is closed

Added a test harness with a modified encrypted endpoint to test this behaviour.

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

File: jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java [hunk 1]
```diff
@@ -866,7 +870,7 @@ public boolean flush(ByteBuffer... appOuts) throws IOException
                                         if (filled < 0)
                                             throw new IOException("Broken pipe");
                                     }
-                                    return result = false;
+                                    return result = appOuts.length==1 && BufferUtil.isEmpty(appOuts[0]);
```
Comment (sbordet) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java]: I'm not sure about this.
It may happen that we do wrap and consume the `appOuts`, but we have unflushed bytes in `_encryptedOutput`.
Also the special case of testing for `appOuts.length==1` does not seem justified.
Here we are flushing, we have been told to unwrap, we filled but was not enough, I think we should just return `false` - if we return `true` we may never finish to unwrap.

Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java]: The true false return only indicates if we are flushed or not.    
If we have no encrypted bytes, no unencrypted bytes, then we are flushed even if we are in NEED_UNWRAP.   I'll update to reflect that better with less special case pleading....

File: jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java [hunk 2]
```diff
@@ -946,8 +946,13 @@ public boolean flush(ByteBuffer... appOuts) throws IOException
...
                                     if (!flushed)
                                         return result = false;
+
                                     if (isEmpty)
-                                        return result = true;
+                                    {
+                                        if (wrapResult.getHandshakeStatus() != HandshakeStatus.NEED_WRAP ||
+                                                wrapResult.bytesProduced() == 0)
+                                            return result = true;
+                                    }
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java]: +1
