### PR TITLE
Fixes #2663 - Guard Throwable.addSuppressed() calls.

### LINKED ISSUE #2663: Guard Throwable.addSuppressed() calls
Turns out that:

```java
Throwable x;
x.addSuppressed(x);
```

throws `IllegalArgumentException`.

This is bad because we typically add the suppressed exception and then complete some callback or run some other code with the assumption that `addSuppressed()` won't throw.

This happens, for example, when closing sockets but wanting to rethrow to let other code know there has been an error (or the application):

```java
catch (Throwable x) {
  close(x);
  throw x;
}
```

The `close(x)` may have modified some state that is also modified by some other code catching the rethrown exception (and perhaps re-rethrowing).

### PR DESCRIPTION
**Pull request by sbordet**
Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-alpn/jetty-alpn-client/src/main/java/org/eclipse/jetty/alpn/client/ALPNClientConnectionFactory.java [hunk 1]
```diff
@@ -68,7 +68,8 @@ public ALPNClientConnectionFactory(Executor executor, ClientConnectionFactory co
             {
                 if (LOG.isDebugEnabled())
                     LOG.debug(x);
-                failure.addSuppressed(x);
+                if (x != failure)
```
Comment (joakime) [inline jetty-alpn/jetty-alpn-client/src/main/java/org/eclipse/jetty/alpn/client/ALPNClientConnectionFactory.java]: Isn't this always true in this scenario?
'failure' is from line 57, and isn't passed into / used by anything in the loop.

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java [hunk 2]
```diff
@@ -234,23 +234,4 @@ public void setStopTimeout(long stopTimeout)
         @Override public void lifeCycleStopped(LifeCycle event) {}
         @Override public void lifeCycleStopping(LifeCycle event) {}
     }
-
```
Comment (joakime) [inline jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java]: This removal seems unrelated to the issue.

File: jetty-alpn/jetty-alpn-client/src/main/java/org/eclipse/jetty/alpn/client/ALPNClientConnectionFactory.java (hunk 1 above)
Comment (sbordet) [reply jetty-alpn/jetty-alpn-client/src/main/java/org/eclipse/jetty/alpn/client/ALPNClientConnectionFactory.java]: Good catch!

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java (hunk 2 above)
Comment (sbordet) [reply jetty-util/src/main/java/org/eclipse/jetty/util/component/AbstractLifeCycle.java]: It's related because I would have needed to add `if (e != cause)`, but then figured out that it's an unused field, so I removed it.
