### PR TITLE
Issue #3246 - javax-websocket-tests exception stacktraces

### LINKED ISSUE #3246: javax-websocket-tests exception stacktraces
the tests in javax-websocet-tests are all passing but produce concerning exception stacktraces which should be investigated

<details><summary><b>Full Log</b></summary>
<p>

```
2019-01-09 13:54:18.712:INFO::main: Logging initialized @7747ms to org.eclipse.jetty.util.log.StdErrLog

public void org.eclipse.jetty.websocket.javax.tests.server.TextStreamTest.testLargerThenMaxDefaultMessageBufferSize() throws java.lang.Exception is @Disabled

public void org.eclipse.jetty.websocket.javax.tests.server.TextStreamTest.testAtMaxDefaultMessageBufferSize() throws java.lang.Exception is @Disabled
2019-01-09 13:54:22.553:WARN:oejwci.WebSocketChannel:WSCoreClient-407: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:22.613:WARN:oejwci.WebSocketChannel:WSCoreClient-425: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:22.766:WARN:oejwci.WebSocketChannel:WSCoreClient-470: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:22.883:WARN:oejwci.WebSocketChannel:WSCoreClient-506: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:22.940:WARN:oejwci.WebSocketChannel:WSCoreClient-524: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:22.969:WARN:oejwci.WebSocketChannel:WSCoreClient-533: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:23.573:WARN:oejwci.WebSocketChannel:WSCoreClient-741: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:23.956:WARN:oejwci.WebSocketChannel:WSCoreClient-831: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:23.998:WARN:oejwci.WebSocketChannel:WSCoreClient-843: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:365)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:24.150:WARN:oejwci.WebSocketChannel:WSCoreClient-879: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:365)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:24.400:WARN:oejwci.WebSocketChannel:WSCoreClient-930: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)

2019-01-09 13:54:24.530:WARN:oejwci.WebSocketChannel:WSCoreClient-966: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:24.694:WARN:oejwci.WebSocketChannel:WSCoreClient-993: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:24.720:WARN:oejwci.WebSocketChannel:WSCoreClient-1002: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:24.746:WARN:oejwci.WebSocketChannel:WSCoreClient-1011: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:24.929:WARN:oejwci.WebSocketChannel:WSCoreClient-1068: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:365)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:25.067:WARN:oejwci.WebSocketChannel:WSCoreClient-1092: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:25.607:WARN:oejwci.WebSocketChannel:WSCoreClient-1190: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)

Disabled on JRE version: 11.0.1
2019-01-09 13:54:27.707:WARN:oejwci.WebSocketChannel:WSCoreClient-1573: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:365)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:27.731:WARN:oejwci.WebSocketChannel:WSCoreClient-1585: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:365)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:29.502:WARN:oejwjtss.IdleTimeoutOnOpenSocket:Scheduler-1501888239: Unhandled Error: Endpoint org.eclipse.jetty.websocket.javax.tests.server.sockets.IdleTimeoutOnOpenSocket missing onError handler
org.eclipse.jetty.websocket.core.WebSocketTimeoutException: Connection Idle Timeout
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onIdleExpired(WebSocketConnection.java:184)
	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:401)
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:30.948:WARN:oejwci.WebSocketChannel:WSCoreClient-1778: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:365)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:32.593:WARN:oeju.SharedBlockingCallback:qtp413293501-1806: Blocker not complete Blocker@433838b9{null}
Empty test suite.
Empty test suite.
Empty test suite.
Empty test suite.
2019-01-09 13:54:33.228:WARN:oejwci.WebSocketChannel:WSCoreClient-2146: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
Empty test suite.
2019-01-09 13:54:33.408:WARN:oejwci.WebSocketChannel:WSCoreClient-2209: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
Empty test suite.
Empty test suite.
2019-01-09 13:54:33.593:WARN:oejwci.WebSocketChannel:WSCoreClient-2293: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:33.680:WARN:oejwci.WebSocketChannel:WSCoreClient-2313: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:33.735:WARN:oejwci.WebSocketChannel:WSCoreClient-2334: Unhandled Error (closing connection)
java.nio.channels.WritePendingException
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:273)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.process(FrameFlusher.java:186)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.FrameFlusher.enqueue(FrameFlusher.java:86)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.sendFrame(WebSocketConnection.java:590)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$OutgoingState.sendFrame(WebSocketChannel.java:656)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack$Flusher.process(ExtensionStack.java:318)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.sendFrame(ExtensionStack.java:205)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:311)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.close(WebSocketChannel.java:269)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState$2.completed(WebSocketChannel.java:625)
	at org.eclipse.jetty.util.Callback$Nested.succeeded(Callback.java:179)
	at org.eclipse.jetty.websocket.javax.tests.NetworkFuzzer$FrameCapture.onFrame(NetworkFuzzer.java:250)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel$IncomingState.onFrame(WebSocketChannel.java:633)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:107)
	at org.eclipse.jetty.websocket.core.internal.WebSocketChannel.onFrame(WebSocketChannel.java:488)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:197)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:390)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-01-09 13:54:33.968:WARN:oejwci.WebSocketChannel:Javax-WebSocketClient@5426cb36-2463: Error during OPEN: org.eclipse.jetty.websocket.core.WebSocketException: org.eclipse.jetty.websocket.javax.tests.client.misbehaving.AnnotatedRuntimeOnOpen OPEN method error: Intentionally Misbehaving
2019-01-09 13:54:33.979:WARN:oejwci.WebSocketChannel:Javax-WebSocketClient@74024f3-2473: Error during OPEN: org.eclipse.jetty.websocket.core.WebSocketException: org.eclipse.jetty.websocket.javax.tests.client.misbehaving.EndpointRuntimeOnOpen OPEN method error: Intentionally Misbehaving
2019-01-09 13:54:34.253:WARN:oejwjtc.DecoderReaderManySmallTestEventIdSocket:Javax-WebSocketClient@79eeff87-2592: Unhandled Error: Endpoint org.eclipse.jetty.websocket.javax.tests.client.DecoderReaderManySmallTest$EventIdSocket missing onError handler
java.io.IOException: Closed
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onClose(WebSocketConnection.java:172)
	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:345)
	at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:942)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
### Executor: ReservedThreadExecutor@7bc58891{s=0/4,p=0}
2019-01-09 13:54:34.419:WARN:oeju.SharedBlockingCallback:main: Blocker not complete Blocker@2e4389ed{null}
2019-01-09 13:54:34.419:WARN:oeju.SharedBlockingCallback:main: Blocker not complete Blocker@2e4389ed{null}
2019-01-09 13:54:34.428:WARN:oeju.SharedBlockingCallback:Javax-WebSocketClient@29fe4840-2643: Succeeded after IDLE
2019-01-09 13:54:34.428:WARN:oeju.SharedBlockingCallback:Javax-WebSocketClient@29fe4840-2643: Succeeded after IDLE
2019-01-09 13:54:34.774:WARN:oeju.SharedBlockingCallback:main: Blocker not complete Blocker@4ac8768e{null}

Process finished with exit code 0
```
</p>
</details>

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #3246

### CODE REVIEW

File: jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java [hunk 1]
```diff
@@ -100,7 +100,7 @@ protected WriteFlusher(EndPoint endPoint)
      * @param previous the expected current state
      * @param next     the desired new state
      * @return the previous state or null if the state transition failed
-     * @throws WritePendingException if currentState is WRITING and new state is WRITING (api usage error)
+     * @throws IllegalStateException if previous->next is not a legal state transition (api usage error)
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java]: Is this legal javadoc with the -> ?
