### PR TITLE
replace static dn by subtee based ldap lookup for an entry inside _userBaseDn

### LINKED ISSUE #2691: LdapLoginModule does not find accounts in subtrees
The way LdapLoginModule determines the user name by concatenating the user to the basedn (
https://github.com/eclipse/jetty.project/blob/45472bf10bfe86201a47eda367917e0b02c8f352/jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/LdapLoginModule.java#L337). This fails when using nested LDAP structures, like the following

    ou=users
    - ou=team1,ou=users
      - uid=user1,ou=team1,ou=users
      - uid=user2,ou=team1,ou=users
    - ou=team2,ou=users
      - uid=user3,ou=team2,ou=users

This kind of setup is extremely common in real world ldap setups. Now if users from all teams are supposed to use the ldap authentication, the expected behaviour of a well-written ldap client is to *search* for the user below it's configured basedn instead of just concatenating the username to the basedn, assuming a flat structure. A quick google gave the following example on how to do this in java:

https://gist.github.com/jbarber/2909828#file-ldapauth-java-L37

or 

http://www.adamretter.org.uk/blog/entries/LDAPTest.java

### PR DESCRIPTION
**Pull request by p-alik**
PR aims to fix #2691

### CODE REVIEW

**Comment by p-alik** [comment]
[LdapLoginModuleTest.java](https://github.com/p-alik/jetty.project/blob/jetty-9.4.x-2691-test/jetty-jaas/src/test/java/org/eclipse/jetty/jaas/spi/LdapLoginModuleTest.java) is not a part of the PR but was used for testing purpose with [ldif-data.txt](https://github.com/eclipse/jetty.project/files/2306435/ldif-data.txt)

```
mvn clean install -Djava.security.auth.login.config=target/test-classes/ldap-loginModule.conf -Dtest=org.eclipse.jetty.jaas.spi.LdapLoginModuleTest -Djava.security.auth.login.uid=user3 -Djava.security.auth.login.password=xzy
```

**Comment by WalkerWatch** [comment]
@p-alik Before we can accept this you will need to complete the [Eclipse ECA](https://www.eclipse.org/jetty/documentation/current/contributing-patches.html#contributing-eca).

**Comment by p-alik** [comment]
@WalkerWatch, I submitted Eclipse ECA as requested right now.

**Comment by janbartel** [comment]
@p-alik did you use the same identity for the ECA as you signed the commits with?

**Comment by janbartel** [comment]
@p-alik  do you know of an open source in-memory ldap server that we could use in automated tests? I'd like to incorporate your test class if at all possible.

File: jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/LdapLoginModule.java [hunk 1]
```diff
@@ -531,11 +538,6 @@ public boolean bindingLogin(String username, Object password) throws LoginExcept
 
     private SearchResult findUser(String username) throws NamingException, LoginException
```
Comment (janbartel) [inline jetty-jaas/src/main/java/org/eclipse/jetty/jaas/spi/LdapLoginModule.java]: as findUser is private method, feel free to change its signature instead of introducing the findLdapUser method.

**Comment by olamy** [comment]
@janbartel http://directory.apache.org/ is an option to do such tests and started an embedded ldap server.

**Comment by p-alik** [comment]
> @p-alik did you use the same identity for the ECA as you signed the commits with?

yes, my name and email address used for ECA are the same as in the PR commit.

**Comment by p-alik** [comment]
> @p-alik do you know of an open source in-memory ldap server that we could use in automated tests? I'd like to incorporate your test class if at all possible.

Unfortunately no.

**Comment by janbartel** [comment]
@p-alik you've inspired us to fix up testing of the ldap login module. PR #2864  is going to be applied very soon now. Can you grab those changes into your repo and reapply your changes against them please?

Also, we need to get to the bottom of why your ip-validation failed, otherwise we won't be able to accept your PR :( If you click on the ip-validation check on this page, you'll see that it is complaining about mis-matched identity on the commit vs your eclipse identity - looking at the commits, it looks to me like you did not sign them (ie commit -s).

**Comment by p-alik** [comment]
@janbartel, PR's code is rebased as requested. ip-validation is done also.

**Comment by olamy** [comment]
@p-alik as we now have a test class for ldap I wonder if you could add a test for this new feature?

**Comment by p-alik** [comment]
@olamy, PR changes are:
- ldap search: replace static search for a user dn by dynamic variant within root dn and sub tries  
- [prevent ambiguity](https://github.com/eclipse/jetty.project/pull/2842/commits/bd72f8cd0fe23bf9ed7d3b6c30342e53958c355a#diff-3e3c68a26d0be4548233014dabddc62eR573) 

Do you expect an enhancement of
 [JAASLdapLoginServiceTest.java](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-jaas/src/test/java/org/eclipse/jetty/jaas/JAASLdapLoginServiceTest.java) for thous two cases?

**Comment by olamy** [comment]
@p-alik yes definitely that would be great to have a test for your new feature.

**Comment by p-alik** [comment]
@olamy, unfortunately tests of original org.eclipse.jetty.jaas.JAASLoginServiceTest are failing in my environment.

[log.txt](https://github.com/eclipse/jetty.project/files/2340677/log.txt)

**Comment by olamy** [comment]
@p-alik strange we have a working ci https://jenkins.webtide.net/ and the test pass...
I have updated a bit to reduce log noise https://github.com/eclipse/jetty.project/pull/2881

**Comment by joakime** [comment]
Wouldn't be the first time travis has had issues with our build.
That's the main reason we don't use Travis ourselves (it's less reliable then jenkins).  (then there's the lack of up to date os/java/maven and access to java9/java10/java11 ea's, and grid builds, and log limits, and post-build workspace access, etc but that's a different story)

Some advice on setting up your CI for success.
* Use Maven 3.5.2 (or newer)
* Use Java 8u161 (or newer)
* Build everything with (eg `clean install`)
* Run all tests (don't target specific tests with `-Dtestname`)
* Don't skip any other maven plugin that is part of the normal `clean install` phases (such as bundle, license, dependency, etc)

**Comment by janbartel** [comment]
@p-alik  ok we've made some changes to the test, can you do a merge from 9.4.x and try again?

**Comment by p-alik** [comment]
@janbartel, I can hardly do anything more because in my environment 
`mvn clean install` doesn't succeed since rebasing to 9cb9be83fd501c386dba810c83ace1a884568bc6

As far as I can justify my environment met aforementioned requirements 
```
$ mvn --version 
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /opt/devel/workspace/java/apache-maven-3.5.4
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-33-generic", arch: "amd64", family: "unix"
$ java --version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

See [log](https://gist.github.com/p-alik/2770bbd437f45f799d756f8132464c2c) for  2cbe395f29afbeed122930d04e36e80cfe08e83c. There is no line of my own code involved
```
$ git log -1 --oneline 
2cbe395 Cleanup jaas ldaptest (#2881)
$ mvn clean install > /tmp/jetty.project-build-with-mvn-3.5.4.log.txt 2>&1
```

**Comment by janbartel** [comment]
@olamy can you help?

**Comment by p-alik** [comment]
Sorry to bother you, there is a workaround
```bash
$ cd jetty-jaas 
$ mvn clean install -Dtest=org.eclipse.jetty.jaas.JAASLoginServiceTest
```

**Comment by p-alik** [comment]
As my local as [Travis CI](https://travis-ci.org/p-alik/jetty.project/builds/425726294) build passed.
But it seems the tests were not executed properly. There are fife `org.eclipse.jetty.jaas.JAASLoginServiceTest` tests, but regarding to the [message](https://travis-ci.org/p-alik/jetty.project/builds/425726294#L5023-L5026) only two were run.
 
```bash
$ grep -A1 '@Test' ./src/test/java/org/eclipse/jetty/jaas/JAASLdapLoginServiceTest.java
    @Test
    public void testLdapUserIdentity() throws Exception
--
    @Test
    public void testLdapUserIdentityBindingLogin() throws Exception
--
    @Test
    public void testLdapBindingSubdirUniqueUserName() throws Exception
--
    @Test(expected = LoginException.class)
    public void testLdapBindingAmbiguousUserName() throws Exception
--
    @Test(expected = LoginException.class)
    public void testLdapBindingSubdirAmbiguousUserName() throws Exception
```

**Comment by janbartel** [comment]
@p-alik  where are we with this PR? Is it now ready?

**Comment by p-alik** [comment]
Yes, it is ready.

**Comment by p-alik** [comment]
thanks!

**Comment by olamy** [comment]
@p-alik no Thanks to you for your contribution!
