### PR TITLE
Sends the WWW-Authenticate header if a non-Negotiate authorization he…

### LINKED ISSUE #1698: Missing WWW-Authenticate from SpnegoAuthenticator when other Authorization header provided
Josh said:

I've been digging into an interesting case I'd like to run by you all.

I have a Jetty application that requires SPNEGO authentication sitting behind a reverse-proxy that requires HTTP Basic authentication (clients use Basic auth to talk to the reverse-proxy and the reverse-proxy uses SPNEGO to talk to the Jetty application). The problem was that the reverse-proxy was failing to authenticate with the Jetty application.

Digging further, I noticed that the reverse-proxy does not strip the HTTP Basic Authorization header sent by the client. When Jetty see that request, it does not send back the expected HTTP/401 with a WWW-Negotiate header. I just seem a plain HTTP/401 that comes from application (as the user was not authenticated).

Looking at the source of SpnegoAuthenticator[1], the negotiate challenge will _only_ be sent when no Authorization headed was sent by the client. This seemed a bit odd to me, so I re-read RFC-4559[2], section 4.1:

<quote>
If the server receives a request for an access-protected object, and
if an acceptable Authorization header has not been sent, the server
responds with a "401 Unauthorized" status code, and a "WWW-
Authenticate: Negotiate" header as per the framework described in [RFC2616].
</quote>

Given the above, my initial interpretation was that if a client provides some Authorization header which is not sufficient for SPNEGO authentication, SpnegoAuthenticator should sent the challenge request. That is not the case -- SpnegoAuthenticator will only send the challenge request when _no_ Authorization header is provided.

I wanted to drop a note because I can imagine that there are edge-cases which I'm not considering. Thanks in advance!

- Josh

### PR DESCRIPTION
**Pull request by joshelser**
…ader was given

Fixes #1698

### CODE REVIEW

**Comment by joshelser** [comment]
I know I need to do a few things per the contributor guide (CLA, dbl-check style, etc). Will get to those tmrw -- just wanted to get the general idea I had up.

File: jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java [hunk 1]
```diff
@@ -72,8 +72,12 @@ public Authentication validateRequest(ServletRequest request, ServletResponse re
             return new DeferredAuthentication(this);
         }
 
+        final boolean hasNegotiateHeader = header == null ? false : header.startsWith(HttpHeader.NEGOTIATE.asString();
```
Comment (gregw) [inline jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java]: I know this is the same stasrtsWith test as previous....  but headers are mean to be case insensitive, so might need a toLowercase in there.

File: jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java [hunk 2]
```diff
@@ -72,8 +72,12 @@ public Authentication validateRequest(ServletRequest request, ServletResponse re
...
         // check to see if we have authorization headers required to continue
-        if ( header == null )
+        // A challenge should be sent if:
+        //   1. There was not Authorization header provided
+        //   2. There was an Authorization header for a type other than Negotiate
+        if (header == null || (header != null && !hasNegotiateHeader))
```
Comment (gregw) [inline jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java]: this can just be !hasNegotiateHeader, as if  the header is null then line 75 sets hasNegotiateHeader to false.
Probably best to switch this if around then (else block first and remove the !).
Probably don't need the variable then either.

File: jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java (hunk 1 above)
Comment (joshelser) [inline jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java]: Gotcha! Happy to fix that.

File: jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java (hunk 2 above)
Comment (joshelser) [inline jetty-security/src/main/java/org/eclipse/jetty/security/authentication/SpnegoAuthenticator.java]: Yeahh, looking back at this, I'm not sure why I was worried about that (I had it in my mind that there was a reason I had to do that).

**Comment by joshelser** [comment]
Argh. I botched my `.git/config` so my email is wrong. Rebase incoming.

**Comment by joshelser** [comment]
Alright, I finally have the pre-commit checks running.

I'm a little sketched out by including the license header in 003ad2d (I'm assigning my contribution to the copyright of Mortbay consulting? Not the Eclipse Foundation?), but whatever, I guess...

Happy to squash these commits down after we're happy.

**Comment by gregw** [comment]
@joshelser assigning copyright to Mort Bay is not a strict requirement, but it just makes life much easier for us in the long run as chasing copyright holders for a 20 year old project can become a rather large task.   So we've tended to move all copyrights to Mort Bay and replace modules that maintain a different copyright, to the point we have an over zealous header checker in the build.   If there was a significant contribution that wanted to hold a different copyright, then that would be fine so long as the right licences are applied.

So thanks for this contribution.  I'll squash as I merge!

cheers

**Comment by joshelser** [comment]
Thanks for the explanation on the copyright stuff. It struck me as odd, but I can understand where the project is coming from.

I truly appreciate your help in this!
