### PR TITLE
Quoted Request Log #12834

### LINKED ISSUE #12834: Quotes should be escaped in request logs
**Jetty version(s)**
Jetty 12

**Jetty Environment**
ee10

**Java version/vendor**
N/A

**OS type/version**
N/A

**Description**
Currently quotes are not escaped in the Jetty request log.  This is applicable for example to `User-Agent` field.  User agents are not usually quoted but they could be, even maliciously to corrupt logs or break log processing scripts. 
Also applicable to `Referer` field, or in fact any field that comes from the end user.

**How to reproduce?**
Executing this:
`curl -A 'My Quoted " Agent' 'http://localhost:8080/'`

Logs this in the user agent field in the request log:
`"My Quoted " Agent"`

The same on Apache logs this:
`"My Quoted \" Agent"`

### PR DESCRIPTION
**Pull request by gregw**
Fixes #12834 Quote request log values that need to be quoted
Track quotes in format string.

### CODE REVIEW

**Review by janbartel — DISMISSED** [review]
I think it looks fine, but you may want to get a review from someone more au fait with the request log format.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java [hunk 1]
```diff
@@ -477,34 +477,68 @@ protected void doStart() throws Exception
         super.doStart();
     }
 
-    private static void append(StringBuilder buf, String s)
+    private static void append(StringBuilder buf, String s, boolean quoted)
     {
         if (s == null || s.isEmpty())
-            buf.append('-');
+        {
+            if (!quoted)
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:484]: How could this be quoted if it is null or empty string?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java [hunk 2]
```diff
@@ -602,6 +638,11 @@ public Token(String literal)
             this.modifiers = null;
             this.negated = false;
             this.literal = literal;
+            boolean quote = false;
+            for (int i = 0; i < literal.length(); i++)
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:642]: For loop should have braces.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java [hunk 3]
```diff
@@ -602,6 +638,11 @@ public Token(String literal)
...
+                if (literal.charAt(i) == '"')
+                    quote = !quote;
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:644]: Don't really understand why `quote` is only true if there is an odd number of quotes. 
Can we get some javadoc on `isQuote()`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java [hunk 4]
```diff
@@ -477,34 +477,68 @@ protected void doStart() throws Exception
...
+        {
+            if (!quoted)
+                buf.append('-');
+        }
         else
+        {
+            for (int i = 0; i < s.length(); i++)
+            {
+                char c = s.charAt(i);
+                if (c == '\\' || c == '"' || c == ',')
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:492]: Why are we checking for `,` here if we do not delimit it down below.

**Review by lachlan-roberts — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:484]: The quoted here refers to the quoting status of the format string.  For example if you had a format string of `"\"%a\", %b"`, then we know that `%a` is already quoted, but `%b`, is not.   Thus if we logged this and both a and b were null then the result would be `"", -`

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:492]: We don't need to escape commas, only ensure that any value that has a comma is quoted so that we don't break the CSV format.  We need to escape quote and slosh as they are used to control quotes.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:642]: They don't have to.... but in this case when it is more than a 1 liner, I guess we should.  Will do.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:644]: If a literal has one quote, then it leaves the quote open; If it has two quotes, then it opens and closes the quotes, so any tokens after the literal are not in the quotes; Three and it is leaving it open again.

This is handling the quotes that we already allow for in the format string.   If a value is already quoted, we don't want to add another set of quotes, only escape.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java (hunk 4 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:492]: Should we quote anything with a space in it as well?

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java [hunk 5]
```diff
@@ -866,70 +915,77 @@ else if ("d".equals(arg))
 
     //-----------------------------------------------------------------------------------//
     @SuppressWarnings("unused")
-    private static void logNothing(StringBuilder b, Request request, Response response)
+    private static void logNothing(StringBuilder b, Request request, Response response, boolean quoted)
+    {
+    }
+
+    //-----------------------------------------------------------------------------------//
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java]: Let's get rid of these separators, here and in the method above.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:492]: I don't think so, as CSV is robust to spaces.   Maybe not leading or trailing white space, but if somebody is concerned by that, they can quote in the format string.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java:492]: @lachlan-roberts ^

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/CustomRequestLogTest.java [hunk 6]
```diff
@@ -1030,6 +1030,21 @@ public boolean handle(Request request, Response response, Callback callback)
...
     }
 
+    @Test
+    public void testLogBadUserAgent() throws Exception
+    {
+        start("User-Agent: %{User-Agent}i, \"%{User-Agent}i\"");
+
+        HttpTester.Response response = getResponse("""
+            GET / HTTP/1.0
+            User-Agent: bad"value
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/CustomRequestLogTest.java:1040]: I tried to motify this test with `User-Agent: bad\\"value`, as if an application had already escaped the dquote.

The result is: `"User-Agent: \"bad\\\\\\\"value\", \"bad\\\\\\\"value\""`.

Is this expected? I would have expected the original value (perhaps quoted), which was already properly escaped.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]

**Review by lachlan-roberts — APPROVED** [review]
