### PR TITLE
Issue #13603 - Bad Accept-Language parsing fix for Locale. [12.1.x]

### LINKED ISSUE #13603: Bad Accept-Language request headers can result in NPE during HttpServletRequest.getLocale() call
**Jetty version(s)**
12.0.27

**Jetty Environment**
core, ee8, ee9, ee10+

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
If a bad `Accept-Language` request header is received, it can result in an NPE when fetching the locale of the request.

* from Servlet API `HttpServletRequest.getLocale()`
* from Core API `Request.getLocales(Request)`

### PR DESCRIPTION
**Pull request by joakime**
Introduce fix in QuotedQualityCSV (not QuotedCSV) to address bad entries in the parsing results.

This will eliminate bad/invalid entries from being added to the QuotedQualityCSV, which in turn fixes the 
HttpServletRequest.getLocale() issue, along with other things.

Fixes #13603

### CODE REVIEW

**Comment by gregw** [comment]
@joakime I've pushed my version

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java [hunk 1]
```diff
@@ -155,23 +160,28 @@ else if (state == State.PARAM_VALUE)
...
+                                if (valueLength > 0 || paramsOnly)
+                                    parsedParam(buffer, valueLength, paramName, paramValue);
                                 break;
                             default:
                                 throw new IllegalStateException(state.toString());
                         }
 
-                        parsedValueAndParams(buffer, valueLength);
+                        if (valueLength > 0 || paramsOnly)
+                            parsedValueAndParams(buffer);
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java]: I'm surprised this didn't break QuotedCSVTest (I did this same change before, and it broke expectations there)

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 2]
```diff
@@ -527,13 +527,22 @@ static List<Locale> getLocales(Request request)
...
+                {
+                    if (MimeTypes.isKnownLocale(locale))
+                        knownFirst.add(locale);
+                }
+                for (Locale locale : locales)
+                {
+                    if (!MimeTypes.isKnownLocale(locale))
+                        knownFirst.add(locale);
+                }
+                yield knownFirst;
```
Comment (joakime) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: Merge up from `origin/jetty-12.1.x` first, as this code block is different as a result of the changes in 12.0.x that were merged up after this PR was started.

Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: I think some of this change needs to be in the ee9/nested/Request.getLocale() too.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: This is only an optimisation, so not strictly needed in ee9... but low risk so....

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: actually the method is a bit different in ee9, so I think we should leave it as is.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java]: Did you have the paramsOnly concept? It is necessary to support Forwarded header style, which does allow empty values.

**Comment by gregw** [comment]
@lachlan-roberts can you review this as now both @joakime and I have worked on it, so neither of us can review.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java (hunk 2 above)
Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: Yes, the ee9 version is different, in so far as it only ever returns 1 Locale.
But the filtering of valid Locales is still there.

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/QuotedQualityCSVTest.java [hunk 3]
```diff
@@ -337,14 +364,15 @@ protected void parsedParam(StringBuilder buffer, int valueLength, int paramName,
...
         // The provided string is not legal according to some RFCs ( not a token because of = and not a parameter because not preceded by ; )
         // The string is legal according to RFC7239 which allows for just parameters (called forwarded-pairs)
+        // To properly parse RFC7239 forwarded-paris, the QuotedCSV itself is used, not the QuotedQualityCSV.
         values.addValue("p=0.5,q=0.5");
 
         // The QuotedCSV implementation is lenient and adopts the later interpretation and thus sees q=0.5 and p=0.5 both as parameters
-        assertThat(results, contains("parsedValue: ", "parsedParam: p=0.5",
-            "parsedValue: ", "parsedParam: q=0.5"));
+        assertThat(results, contains("parsedValue: ", "parsedParam: p=0.5", "parsedValueAndParams: p=0.5",
+            "parsedValue: ", "parsedParam: q=0.5", "parsedValueAndParams: q=0.5"));
```
Comment (lachlan-roberts) [inline jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/QuotedQualityCSVTest.java]: Something is a bit strange with this.

```java
QuotedQualityCSV values = new QuotedQualityCSV();
values.addValue("p=0.5,q=0.5");
System.err.println("size: " + values.size());
System.err.println("values: " + values);
System.err.println("size: " + values.size());
```

This code outputs the following
```
size: 2
values: []
size: 0
```

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java [hunk 4]
```diff
@@ -84,6 +84,7 @@ public void addValue(String value)
         int nwsLength = 0;
         int lastLength = 0;
         int valueLength = -1;
+        boolean paramsOnly = false;
```
Comment (lachlan-roberts) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java:87]: There seems to be no tests for these changes.

If all the changes are reverted in this file, neither `RequestHeadersTest` or `QuotedQualityCSVTest` fail.

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java:87]: The `testQuality` test fails if the paramsOnly is never set to true.  It passes if you revert all the changes, but for a different (wrong) reason.

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedCSVParser.java:87]: now renamed to `testParamsOnly()`

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/QuotedQualityCSVTest.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/QuotedQualityCSVTest.java]: Fixed

**Comment by lachlan-roberts** [comment]
@gregw this has a failure in `QuotedCSVTest`.

**Review by joakime — COMMENTED** [review]
Approved :+1:  (I cannot review this, as it's my PR)

**Review by gregw — APPROVED** [review]
on behalf of @joakime
