### PR TITLE
Cancel write semantic

### LINKED ISSUE #12776: ByteBufferPool - all ongoing requests fail when single request is cancelled on HTTP/2
**Jetty version(s)**

12.0.16 (11.0.x version since 11.0.21) 12.1.x

**Jetty Environment**

Embedded + EE9

**Java version/vendor (use: java -version)**
```
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)
```

**OS type/version**

Ubuntu 24, Arch Linux, Manjaro...

**Description**

When web browsers plays video / audio and sending requests with header Range and request got cancelled (for example because user is seeking in video),
all other currently processed requests gets cancelled (there is HTTP2_ERROR in Chrome or Firefox network console).

Issue occurs only when HTTP/2 is used.  It works on Jetty 11.0.20, but fails on Jetty 11.0.21, 11.0.22, 11.0.23, 11.0.24 and 12.0.16.

When we disable HTTP/2 or revert this [commit](https://github.com/jetty/jetty.project/commit/57266039d8da2bd04b33b6a3e387744ab067ed80) on Jetty 11.0.24 it never fails.

This issue also never occured when tested on localhost or LAN (probably due to transfer speed).

**How to reproduce?**

[jetty-issue.zip](https://github.com/user-attachments/files/18690326/jetty-issue.zip)

Run attached code with JDK 21 using:
```bash
mvn compile exec:java
```

It starts Jetty 12.0.16 on port 9443 with HTTP/2 connections, downloads sample [video](https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4)
and starts to serve contents of `web` folder and provides endpoint `/video` for serving video data and `/sse` as Server Sent Events source.

When you open web browser https://IP:9443 it estabilish Server Send Event connections and starts to play video.

Try to seek in the video before it gets fully buffered to web browser. You can see that SSE connection will fail (alert will be shown).

NOTE: We were never able to reproduce this when using localhost or LAN address. Only way to reproduce this is to forward port to public IP address and access to address "in internet" (we have tried multiple ISP to be sure that this issue is not caused by some firewalls or network devices).
Our only thought why it happens only when access from internet is effect of transfer speed and thus different buffer usage.

Image

  
  In TCP dump you can see HTTP2 GOAWAY was sent.
  
  Reverting back to Jetty 11.0.20 helps. We also tried to revert commit [commit](https://github.com/jetty/jetty.project/commit/57266039d8da2bd04b33b6a3e387744ab067ed80) on  Jetty 11.0.24 and it also works.
  
  On Jetty 12 our only solution to fix this is to set `ByteBufferPool.NON_POOLING` in constructor of Jetty `Server` instance.

### PR DESCRIPTION
**Pull request by gregw**
Added a cancel write/send semantic so that buffers for failed writes need not be removed from the pool

### CODE REVIEW

**Comment by gregw** [comment]
@sbordet can you implement the cancel semantic for http2.  @lorban ditto for http3

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Stream.java [hunk 1]
```diff
@@ -60,6 +61,27 @@ public HTTP3Stream(HTTP3Session session, QuicStreamEndPoint endPoint, boolean lo
...
+            @Override
+            public void failed(Throwable x)
+            {
+                ExceptionUtil.addSuppressedIfNotAssociated(cause, x);
+                super.failed(cause);
+            }
+        };
+        reset(HTTP3ErrorCode.REQUEST_CANCELLED_ERROR.code(), cause);
+        return nested;
+    }
```
Comment (gregw) [inline jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Stream.java]: @lorban that looks simple enough.  Same as h2.  Any idea how to test this?

Comment (lorban) [reply jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Stream.java]: This is the big question: the implementation looks fairly easy but I've been scratching my head trying to find a way to reliably test that.

**Comment by gregw** [comment]
@sbordet @lorban nudge for actual review

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java [hunk 2]
```diff
@@ -82,6 +82,19 @@ public interface HttpStream extends Callback
      */
     void send(MetaData.Request request, MetaData.Response response, boolean last, ByteBuffer content, Callback callback);
 
+    /**
+     * Cancel any {@link #send(MetaData.Request, MetaData.Response, boolean, ByteBuffer, Callback)} call in progress.
+     *
+     * @param cause The cause of the cancellation
+     * @param callback The callback to ultimately {@link Callback#failed(Throwable) fail} after the cancellation
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java]: It's not clear what callback needs to be passed here. Isn't this just "the callback passed to send()"?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java [hunk 3]
```diff
@@ -82,6 +82,19 @@ public interface HttpStream extends Callback
...
+     * @return A {@link Callback} that must be {@link Callback#failed(Throwable) fail} to complete the cancellation
+     *         and ultimately invoke the passed {@link Callback} (potentially in a different Thread).
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java]:
```suggestion
     * @return A {@link Callback} that must be {@link Callback#failed(Throwable) fail} to complete the cancellation. 
     *         The implementation must guarantee that the callback passed to send() is eventually failed, 
                either by existing mechanisms, or by failing the callback returned by this method.
```

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 4]
```diff
@@ -736,6 +738,39 @@ private SendCallback()
...
+        public Callback cancel(Throwable cause)
+        {
+            // Cancel the IteratingCallback and take the nest Callback
+            CancelSendException cancelSendException = new CancelSendException(cause);
+            abort(cancelSendException);
+
+            // If a write operation has been scheduled cancel it and fail its callback, otherwise complete ourselves
+            Callback writeCallback = getEndPoint().cancelWrite();
+            if (writeCallback != null)
+                writeCallback.failed(cancelSendException);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: In this branch, how is `CancelSendException` ever completed?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 5]
```diff
@@ -937,7 +974,8 @@ protected void onCompleteSuccess()
             }
             Callback callback = resetCallback();
             release();
-            callback.succeeded();
+            if (callback != null)
+                callback.succeeded();
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java:1011]: Need the same null check in `onFailure()` below.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 6]
```diff
@@ -736,6 +738,39 @@ private SendCallback()
...
+            // If a write operation has been scheduled cancel it and fail its callback, otherwise complete ourselves
+            Callback writeCallback = getEndPoint().cancelWrite();
+            if (writeCallback != null)
+                writeCallback.failed(cancelSendException);
+            else
+                cancelSendException.complete();
+
+            // wait for the cancellation to be complete
+            cancelSendException.join();
+            return cancelSendException.getCallback();
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: I don't think this is safe.

`onAbort()` may be called asynchronously at a later time.

`cancelSendException.join();` does not wait for the callback to be set, so `cancelSendException.getCallback()` may return `null`, which seems wrong to me?

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java [hunk 7]
```diff
@@ -1291,6 +1291,11 @@ public Frame frame()
             return frame;
         }
 
+        public boolean isFor(HTTP2Stream stream)
+        {
+            return stream == this.stream;
+        }
+
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java]: Remove, never used.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java [hunk 8]
```diff
@@ -208,6 +210,33 @@ private boolean startWrite(Callback callback)
...
 
+    /**
+     * Cancel the stream with a reset
+     * @param cause The cause of the cancellation
+     * @param callback The {@link Callback} to invoke once the reset and the callback returned from this method have completed
+     * @return A {@link Callback} that is completed to cancel the stream.
+     */
+    public Callback cancel(Throwable cause, Callback callback)
+    {
+        CountingCallback counting = new CountingCallback(new Nested(callback)
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java]: I don't understand this.

The `callback` parameter has been passed to `HTTP2Flusher` by a previous send operation, but we don't "steal" it from the flusher.

The flusher can just complete the send operation and complete the callback, and here we will be completing it a second time, I don't think it's intended?

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java [hunk 9]
```diff
@@ -345,6 +345,7 @@ protected void onSuccess()
     private void finish()
     {
         accumulator.clear();
+        // TODO grab lock
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java]: Leftover?

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Stream.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Stream.java]: Same comment as HTTP/2.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java [hunk 10]
```diff
@@ -201,7 +211,31 @@ private void changeInterests(int operation)
...
 
         if (LOG.isDebugEnabled())
-            LOG.debug("changeInterests p={} {}->{} for {}", pending, oldInterestOps, newInterestOps, this);
+            LOG.debug("addInterests p={} {}->{} for {}", pending, oldInterestOps, newInterestOps, this);
+
+        if (!pending && _selector != null)
+            _selector.submit(_updateKeyAction);
+    }
+
+    private void removeInterests(int operation)
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java:203]: Almost identical to `addInterest`.
Can we factor out the only line that is different, e.g. `changeInterests(int operation, boolean add)`?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java [hunk 11]
```diff
@@ -222,6 +235,17 @@ InvocationType getCallbackInvocationType()
         }
     }
 
+    private class CancellingState extends State
+    {
+        private final Callback _callback;
+
+        private CancellingState(Callback callback)
+        {
+            super(StateType.PENDING);
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java]: Shouldn't this be `CANCELLING`?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java [hunk 12]
```diff
@@ -87,6 +97,9 @@ private enum StateType
         WRITING,
         PENDING,
         COMPLETING,
+        CANCEL,
+        CANCELLING,
+        CANCELLED,
         FAILED
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java]: While the others were kinda obvious, now with 3 different "cancel" perhaps a little javadoc would help.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 13]
```diff
@@ -1457,6 +1535,13 @@ else if (_generator.isCommitted())
                 _sendCallback.iterate();
         }
 
+        @Override
+        public Callback cancelSend(Throwable cause, Callback callback)
+        {
+            // We know that the SendCallback#cancel call will never block, so we can just combine here
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: `SendCallback.cancel()` has an explicit, infinite-waiting `join()` call in it, so the comment seems wrong?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java [hunk 14]
```diff
@@ -512,6 +549,46 @@ public boolean onFail(Throwable cause)
         }
     }
 
+    public Callback cancel()
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java]: Maybe `cancelWrite()` because the other method is `completeWrite()`?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java [hunk 15]
```diff
@@ -512,6 +549,46 @@ public boolean onFail(Throwable cause)
...
+                        return cancelling._callback;
+                    break;
+
+                default:
+                    throw new IllegalStateException();
+            }
+        }
+    }
+
     public void onClose()
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java:615]: I think this method needs to be updated with the cancel states, and so does `toStateString()`.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java [hunk 16]
```diff
@@ -1291,6 +1291,11 @@ public Frame frame()
             return frame;
         }
 
+        public boolean isFor(HTTP2Stream stream)
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java]: That method is not used.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/frames/DisconnectFrame.java [hunk 17]
```diff
@@ -13,6 +13,7 @@
 
 package org.eclipse.jetty.http2.frames;
 
+@Deprecated (forRemoval = true, since = "12.1.0")
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/frames/DisconnectFrame.java:16]: Why deprecating this?

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java (hunk 9 above)
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java]: Is a lock really needed? `finish` is only called from `onSuccess` and `process` so shouldn't that guarantee that only a single thread can call it at any one time?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/EndPoint.java [hunk 18]
```diff
@@ -333,6 +333,18 @@ default void write(boolean last, ByteBuffer byteBuffer, Callback callback)
...
     }
 
+    /**
+     * Cancel any {@link #write(Callback, ByteBuffer...)} operation
+     * in progress.
+     *
+     * @return The callback passed to {@link #write(Callback, ByteBuffer...)} or
+     *         {@code null}
+     */
+    default Callback cancelWrite()
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/EndPoint.java]: I don't like having a default implementation here, especially since it does not respect the javadoc'ed contract.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java [hunk 19]
```diff
@@ -82,6 +82,19 @@ public interface HttpStream extends Callback
...
+     */
+    default Callback cancelSend(Throwable cause, Callback callback)
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java]: Another default implementation that does not respect the javadoc'ed contract?

**Review by sbordet — CHANGES_REQUESTED** [review]
I am dubious about the H2/h3 implementation; we should talk about it.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java (hunk 11 above)
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java]: `StateType.CANCELLING`?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 20]
```diff
@@ -907,6 +942,8 @@ private Callback resetCallback()
 
         private void release()
         {
+            if (_callback != null)
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java:978]: If this check fails, all kind of nasty stuff is going to happen. Since this should never happen, this may be okay?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 21]
```diff
@@ -958,6 +996,46 @@ public String toString()
...
+            {
+                super(cause);
+            }
+
+            public void complete()
+            {
+                _complete.countDown();
+            }
+
+            public void join()
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Make `join` return the `Callback` and get rid of `getCallback`?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/frames/DisconnectFrame.java (hunk 17 above)
Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/frames/DisconnectFrame.java:16]: because it is not used

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java (hunk 8 above)
Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java]: The passed callback is the action that we want to do once: a) the cancel (aka reset) is complete; b) the callback that we have returned has been called by whatever invoker the HttpChannel wants to use to handle errors.     So in this case we need wait until two callbacks have been called: 1) the callback that tells us the reset is complete; and 2) the callback returned that says the error handling has been invoked.

In fact, an argument could be made that the reset frame itself should not be sent until the returned callback is called, so that it will be sent by the error handling invoker.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java (hunk 11 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java]: oops.  shows this needs a test

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java (hunk 15 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java:615]: `onFail` already handles the cancel states.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 21 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: I don't like this.... @sbordet, what are your thoughts?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: See `#onCompleted(Throwable)` below

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 20 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java:978]: Isn't that what ISE is for?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java (hunk 19 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java]: This does respect the contract. Calling failed on the returned callback completes the cancellation (nothing to be done) and ultimately invokes the passed callback.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpStream.java]: There is no "need" to be passed here.   The passed callback is completed when the cancel operation is completed.  This is just like any other callback we pass to a method.      It so happens that HttpChannelState is the only caller and it passes the callback it atomically takes that was passed as the callback to a HttpChannel write operation (different to the send operation in this class).

**Comment by sbordet** [comment]
@gregw another issue is the use of `CountingCallback`: it has the semantic to count for successes, but it fails on the first failure.

So it has not the right semantic for the usage that was done in H2 and H3.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 21 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: @gregw I think it should be:

1. abort() before stealing
2. steal the EndPoint callback via EndPoint.cancelWrite().
3. if stolen, return it.
4. otherwise return Callback.NOOP, as there is nothing to do as we have already aborted.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: That's what it does already, except returning null is more efficient than returning NOOP as it doesn't need to be combined with other callbacks (hmmm we can probably make combine handle that better).

**Comment by gregw** [comment]
> @gregw another issue is the use of `CountingCallback`: it has the semantic to count for successes, but it fails on the first failure.
> 
> So it has not the right semantic for the usage that was done in H2 and H3.

@sbordet See new    `static List<Callback> from(Callback callback, Throwable cause, int count)` method that replaces `CountingCallback`

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java [hunk 22]
```diff
@@ -46,35 +46,45 @@ public abstract class WriteFlusher
     private static final ByteBuffer[] EMPTY_BUFFERS = new ByteBuffer[]{BufferUtil.EMPTY_BUFFER};
     private static final EnumMap<StateType, Set<StateType>> __stateTransitions = new EnumMap<>(StateType.class);
     private static final State __IDLE = new IdleState();
-    private static final State __WRITING = new WritingState();
+    private static final State __FLUSHING = new WritingState();
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java]: You want to rename `WritingState` too then.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java [hunk 23]
```diff
@@ -267,7 +309,7 @@ public void write(Callback callback, SocketAddress address, ByteBuffer... buffer
         if (DEBUG)
             LOG.debug("write: {} {}", this, BufferUtil.toDetailString(buffers));
 
-        if (!updateState(__IDLE, __WRITING))
+        if (!updateState(__IDLE, __FLUSHING))
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java:307]: We probably need a new `isCancelled() { callback.fail(); return; }` check before this `updateState()`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java [hunk 24]
```diff
@@ -267,7 +309,7 @@ public void write(Callback callback, SocketAddress address, ByteBuffer... buffer
...
             throw new WritePendingException();
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java:308]: Now that I see this, it looks wrong: throwing from a method that takes a callback feels like an anti-pattern.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java [hunk 25]
```diff
@@ -512,6 +567,46 @@ public boolean onFail(Throwable cause)
...
+                        return pending._callback;
+                    break;
+
+                case COMPLETING:
+                case FLUSHING:
+                    updateState(current, __CANCEL);
+                    break;
+
+                case CANCEL:
+                    Thread.onSpinWait();
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java:600]: I would add a comment like:
```
A concurrent thread is busy moving from COMPLETING or FLUSHING to CANCELLED. Let's stay in this method until that other thread reached state CANCELLED.
```

**Review by lorban — CHANGES_REQUESTED** [review]
I believe the mechanism is sane, but I can't wrap my head around the newly introduced API and how this should all work.

I've attempted to write a test for this functionality (I've pushed it to this PR) and that left me puzzled. We should probably discuss it.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java [hunk 26]
```diff
@@ -677,9 +677,9 @@ public void failed(Throwable x)
         {
             Callback callback = _callback.getAndSet(null);
             if (callback == null)
-                _buffer.releaseAndRemove();
+                _buffer.release();
             else
-                ExceptionUtil.callAndThen(x, t -> _buffer.releaseAndRemove(), callback::failed);
+                ExceptionUtil.callAndThen(x, t -> _buffer.release(), callback::failed);
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java:682]: I'm surprised this is the only place where we called `releaseAndRemove()`, I'm surprised `HttpOutput` for instance did not.

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java (hunk 26 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java:682]: Oh, it does in 12.0 but not in 12.1!

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java:682]: Oh no!  We have missed some merges from 12.0!   That needs to be investigated!

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java (hunk 23 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java:307]: why? if it is cancelled then it will not be in idle state?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java (hunk 24 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java:308]: I agree, but this pre-dates this PR.  Should we fix this in another PR?

**Comment by gregw** [comment]
@sbordet @lorban have you looked at this recently?   Any updates for h2 or h3?

**Comment by lorban** [comment]
@gregw I've been investigating https://github.com/jetty/jetty.project/issues/12776 which happens to be a user-reported bug that is related to the cancel semantic and it appears that 11.0.x, 12.0.x and 12.1.x are buggy.

Cancelling was implemented in 12.0.x with a semantic close to 11.0.x (remove the buffer from the pool) but the mechanism is buggy. Then it was decided to implement it correctly for 12.1.x (hence the changes around `IteratingCallback.abort()`) so removing the buffers from the pool wouldn't be needed but that was not complete as we figured out more work is needed, and the buffer removing logic was partially added.

So we now have:
 - buggy 10/11 branches with a known regression and potential fix to restore the buffer removal code (#12786)
 - a buggy 12.0.x branch which uses the buffer removal mechanism that seems to be racy
 - a buggy 12.1.x branch with a currently broken write cancelling mechanism

**Comment by gregw** [comment]
@lorban can you re-review this branch and tell me exactly what you think are the current "broken write cancelling mechanism"?   I've forgotten what we discuss last time we hungout on this.

**Comment by lorban** [comment]
@gregw just to be sure: I was speaking about `jetty-12.1.x` and not this branch when I wrote "currently broken write cancelling mechanism".

Here is what can happen for H2 that I call broken:

1. App calls `Response.write(false, buffer, callback)`, which calls `ChannelResponse.write(false, buffer, callback)`, which calls `HttpStream.send()`, which creates a `DataFrame` (which is a wrapper for the buffer) then calls `HTTP2Session.data(h2stream, dataFrame, callback)` which creates a `HTTP2Session.Entry` (which is a wrapper for both `DataFrame` and `Callback`) then appends it into its `HTTP2Flusher` instance.
2. Iterating the `HTTP2Flusher` calls `HTTP2Session.Entry.generate(RBB.Mutable)`, which eventually calls `DataGenerator.generateFrame()` which calls `RetainableByteBuffer.DynamicCapacity.add()` to keep a ref onto the `HTTP2Session.Entry` instance. Eventually, the `RetainableByteBuffer.DynamicCapacity` is written to the `HTTP2Session`'s `EndPoint`.
3. While the write is in progress, a H2 reset arrives; `HTTP2Stream.onReset()` is called which eventually calls `HttpChannel.onRemoteFailure(x)`, which calls `ChannelResponse.lockedFailWrite(x)`.
4. `lockedFailWrite()` calls `_writeCallback.fail()` (`_writeCallback` being the callback passed to `Response.write()`); this signals that the buffer passed to `Response.write()` can be released.
5. There is now a buffer that is both back into the pool and in an endpoint's flusher, possibly given to an in-progress `SocketChannel.write(ByteBuffer[])` call.

**Comment by lorban** [comment]
@gregw The H1 and H2 implementations have been reworked and are now tested.

What this PR lacks before it can be considered complete is handling a set of TODOs, javadoc, naming and minor potential improvements.

The H3 implementation has been deferred to after https://github.com/jetty/jetty.project/pull/12742 is merged, as that other PR changes too drastically the QUIC/H3 interactions so any work on the current impl would need to be completely re-done.

**Comment by gregw** [comment]
@lorban can you re-review this PR and merge it?

**Comment by lorban** [comment]
@gregw Not yet, as I would like a firm confirmation that this PR solves the problem once and for all.

The #12776 issue is exactly about this bug, but not only: yesterday we discovered together with @sbordet that we have an extra bug (#12805) that still makes that user's use-case fail despite the fix in this PR.

I would like to get a confirmation from this user that 12.1 is working before merging this PR as he's been very willing to help, responsive and came up with a reliable reproducer.

**Comment by lorban** [comment]
The H3 implementation will come after #12742 gets merged.

**Comment by lorban** [comment]
@gregw @sbordet this PR is ready for its final review as I consider it ready to be merged

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 27]
```diff
@@ -437,6 +437,20 @@ private void sendContent(MetaData.Request request, ByteBuffer content, boolean l
...
+    {
+        // Append a ResetFrame into the H2 flusher and complete the appCallback once all the frames
+        // up to and including the reset one have been flushed; it is needed to wait to make sure
+        // the completion listeners aren't called while a write is still pending.
+        return () -> _stream.reset(new ResetFrame(_stream.getId(), ErrorCode.CANCEL_STREAM_ERROR.code), Callback.from(() ->
+        {
+            if (LOG.isDebugEnabled())
+                LOG.debug("cancelSend reset callback complete");
+            appCallback.failed(cause);
+        }));
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: `_stream.reset()` may still return early.

How about introducing a `HTTP2Session.flush(Callback)` that queues a "fake" `FlushEntry` into the `HTTP2FLusher` whose only scope is to be flushed and notify the callback when done?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java (hunk 27 above)
Comment (lorban) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: I'll do that, and I'll also write a test similar to `testResetAfterTCPCongestedWrite()` that waits for idle timeout instead of resolving the TCP congestion.

Comment (lorban) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: Done.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java [hunk 28]
```diff
@@ -190,6 +193,16 @@ public void reset(ResetFrame frame, Callback callback)
         }
     }
 
+    /**
+     * Ask to be called back when all the frames of this session have been
+     * flushed to the network.
+     * @param callback the callback that gets notified when the frames have been flushed
+     */
+    public void flush(Callback callback)
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java]: Remove this method, as it is not a "stream" flush, but a "session" flush.
The caller can just do: `stream.getSession().flush(cb)`.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java [hunk 29]
```diff
@@ -342,6 +344,22 @@ public void write(Callback callback, ByteBuffer... buffers) throws WritePendingE
         }
     }
 
+    @Override
+    public Callback cancelWrite(Throwable cause)
+    {
+        try (Blocker.Callback blocker = Blocker.callback())
+        {
+            stream.reset(new ResetFrame(stream.getId(), ErrorCode.CANCEL_STREAM_ERROR.code), blocker);
+            blocker.block();
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java]: I don't think this is right.

The method `write()` above this method initiates a write by calling `stream.data()`; we should "steal" the application callback like we do in `WriteFlusher`.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/frames/FlushFrame.java [hunk 30]
```diff
@@ -0,0 +1,28 @@
...
+{
+    public FlushFrame()
+    {
+        super(FrameType.FLUSH);
+    }
+
+    @Override
+    public String toString()
+    {
+        return String.format("%s", super.toString());
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/frames/FlushFrame.java]: Not necessary, this is equivalent to `super`.

Can we make this class `private`? Do we really need it?

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 31]
```diff
@@ -437,6 +437,24 @@ private void sendContent(MetaData.Request request, ByteBuffer content, boolean l
...
+    @Override
+    public Runnable cancelSend(Throwable cause, Callback appCallback)
+    {
+        // Append a ResetFrame into the H2 flusher and complete the appCallback once all the frames
+        // up to and including the reset one have been flushed; it is needed to wait to make sure
+        // the completion listeners aren't called while a write is still pending.
+        return () ->
+        {
+            _stream.reset(new ResetFrame(_stream.getId(), ErrorCode.CANCEL_STREAM_ERROR.code), Callback.NOOP);
+            _stream.flush(Callback.from(() ->
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: `_stream.getSession().flush(...)`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 32]
```diff
@@ -446,7 +446,7 @@ public Runnable cancelSend(Throwable cause, Callback appCallback)
         return () ->
         {
             _stream.reset(new ResetFrame(_stream.getId(), ErrorCode.CANCEL_STREAM_ERROR.code), Callback.NOOP);
-            _stream.flush(Callback.from(() ->
+            _stream.getSession().flush(_stream, Callback.from(() ->
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: No need to pass the `_stream` here.
Remove the parameter (only need the `Callback`) and pass `null` to the `Entry` constructor.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java (hunk 29 above)
Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java]: @sbordet I don't think we can steal the CB pass to stream.data, but we could steal the CB wrapped inside of the `dataCallback` above.  Is that what you are thinking?

Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java]: @gregw yes, because the wrapped CB would be the one that eventually releases the buffer, and we need to ensure that it is completed after the reset.

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java (hunk 32 above)
Comment (lorban) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: The session has a 1-n relationship with the streams, so that method needs to be told on which stream to work.

**Review by sbordet — APPROVED** [review]

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java [hunk 33]
```diff
@@ -342,51 +326,102 @@ public void write(Callback callback, ByteBuffer... buffers) throws WritePendingE
...
+                            {
+                                // When also the returned callback is complete,
+                                // then complete the pending callback.
+                                if (xx == null)
+                                    pending.callback.succeeded();
+                                else
+                                    pending.callback.failed(xx);
+                            });
+                        });
+                        return returnedCallback;
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java]: @simone I'm not a fan of this approach.  It is 16 lines of complex async CF code that will unlikely be well tested instead of 1 line invoking a utility class that can be extensively tested.

Note that the List<Callback> that I implemented should probably be used in most places that a CountingCallback is used, as that abstraction is wrong as it is based on 1+1+1 == 1+2+0 == 3+0+0 == 0+3+0 etc.   So the utility class will ultimately have more that 1 usage.

Happy for suggestions for better API if `List<Callback>` is a bit clunky?

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java [hunk 34]
```diff
@@ -342,51 +326,90 @@ public void write(Callback callback, ByteBuffer... buffers) throws WritePendingE
...
+                }
+                case PENDING, PENDING_OSHUT ->
+                {
+                    if (writeState.compareAndSet(current, new WriteState(WriteState.State.FAILED, cause)))
+                    {
+                        WriteState.Pending pending = (WriteState.Pending)current;
+                        // Initiate a reset() and a flush().
+                        stream.reset(new ResetFrame(stream.getId(), ErrorCode.CANCEL_STREAM_ERROR.code));
+
+                        try (Callback.Combination callbacks = new Callback.Combination(pending.callback))
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2StreamEndPoint.java]: The `Callback.Combination` constructor is missing the `cause` parameter.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java [hunk 35]
```diff
@@ -389,6 +391,153 @@ static Callback from(Callback callback1, Callback callback2)
...
+         *
+         * @param andThen The {@code Callback} to complete once all {@code Callbacks} in the combination are complete
+         *                and this combination is {@link #close() closed}.
+         * @param failure If not {@code null}, force a failure, so that the {@link Callback#failed(Throwable)} method
+         * will always be called on the {@code Callback} passed to the constructor, once all the
+         * combined callbacks are completed and the {@code Combination} is {@link #close() closed}.
+         */
+        public Combination(Callback andThen, Throwable failure)
+        {
+            this.andThen = andThen;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]:
```suggestion
            this.andThen = Objects.requireNonNull(andThen);
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java [hunk 36]
```diff
@@ -389,6 +391,153 @@ static Callback from(Callback callback1, Callback callback2)
...
+        {
+            while (true)
+            {
+                int s = state.getStamp();
+                Throwable failure = state.getReference();
+
+                if (s >= 0)
+                    throw new IllegalStateException("closed");
+                // we can only create new callbacks when not closed, so we decrement to make a more negative stamp.
+                if (!state.compareAndSet(failure, failure, s--, s))
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]: Is this right? The third parameter is the expected stamp, so shouldn't be `s`, and the fourth parameter be `--s`?

If the code is wrong, it's not tested and should have a test.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java [hunk 37]
```diff
@@ -389,6 +391,153 @@ static Callback from(Callback callback1, Callback callback2)
...
+         * @return A {@code Callback} that must be completed before the callback passed to
+         *         the constructor is completed.
+         * @throws IllegalStateException if the combination has already been completed.
+         */
+        public Callback newCallback()
+        {
+            while (true)
+            {
+                int s = state.getStamp();
+                Throwable failure = state.getReference();
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]: I think you want to take them atomically, so here you should use `state.get(int[])`.
Likewise in the other places.

Actually, my suggestion of `AtomicStampedReference` was more to handle the `Callback` and the counter together... Now that the callback is `final`, I don't think we need `AtomicStampedReference` anymore, we can split again failure and counter, as now we just use the counter as the state of all the callbacks.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java [hunk 38]
```diff
@@ -389,6 +391,153 @@ static Callback from(Callback callback1, Callback callback2)
...
+                // If the stamp is < 0, the combination has not been closed, so we increment, else we decrement.
+                int n = s < 0 ? s + 1 : s - 1;
+                if (!state.compareAndSet(failed, failed == null ? failure : failed, s, n))
+                    continue;
+
+                // combine failures
+                if (failed == null)
+                    failed = failure;
+                else if (failure != null)
+                    ExceptionUtil.addSuppressedIfNotAssociated(failed, failure);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]: Combination of the failures should be done before updating the state?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java (hunk 36 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]: `s--, s` and `s, --s` are identical.  The decrement happens between the two uses of s

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java (hunk 37 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]: We don't need to take them atomically.  If they change between one get and the next, then the CaS will fail anyway.  I guess it is only a single volatile lookup, so maybe better... I'll have a look at it

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java (hunk 36 above)
Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]: Ugh, this is just obscure.
Please change it to:

```suggestion
                if (!state.compareAndSet(failure, failure, s, s - 1))
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java (hunk 37 above)
Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]: I would prefer just `AtomicInteger` for the counter at this point.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java [hunk 39]
```diff
@@ -389,6 +391,158 @@ static Callback from(Callback callback1, Callback callback2)
...
+                    public void succeeded()
+                    {
+                        if (completed.compareAndSet(false, true))
+                            complete(null);
+                    }
+
+                    @Override
+                    public InvocationType getInvocationType()
+                    {
+                        return Invocable.getInvocationType(andThen);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]:
```suggestion
                        return andThen.getInvocationType();
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java [hunk 40]
```diff
@@ -389,6 +391,158 @@ static Callback from(Callback callback1, Callback callback2)
...
+                // combine failures
+                Throwable combined = failure;
+                if (combined == null)
+                    combined = failed;
+                else if (failed != null)
+                    ExceptionUtil.addSuppressedIfNotAssociated(failure, failed);
+
+                // If the stamp is < 0, the combination has not been closed, so we increment, else we decrement.
+                int n = s < 0 ? s + 1 : s - 1;
+                if (!state.compareAndSet(failure, combined, s, n))
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java:530]: If this CAS fails, is exception combination above safe?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java (hunk 36 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]: really?  It is the basic meaning of `--s` vs `s--` ?  But OK,  I'll change it here

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java (hunk 40 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java:530]: It is.  Failure will only go from null to non-null once and then stay at that value.   So we are not trying to hit a moving target. If the cas fails, then the addSuppressed will not add the same exception again, because they will already be associated. But it will be the same target failure, so the previous addSuppressed was the correct thing to do.

Note, it is because of this slight complex race that I had the failure logic after the CaS, but before the the `andThen` callback. I think it is safe there as well with less thought needed, but you asked me to move it.  I think it is probably better where it is now.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java (hunk 37 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Callback.java]: I think the stamped reference is better.  There are still some races with multiple failures that this solves and gives us more deterministic behaviour.

**Review by sbordet — APPROVED** [review]

**Comment by gregw** [comment]
@sbordet I'm going to try to get a clean CI build before merging. I think the failures are flakes or CI issues... but will check.

Also, what is the plan for 12.0.x?  Can any of this be backported easily?   The h2 reset fix?

**Comment by sbordet** [comment]
Plan for 12.0.x is to rely on `releaseAndRemove()`, as we don't have the `onAborted()` and complete event separation semantic in 12.0.x `IteratingCallback`.

**Comment by wendigo** [comment]
🎉

**Comment by losipiuk** [comment]
@sbordet when is the next 12.1.x  release planned?
