### PR TITLE
Do not rethrow Content.Source exceptions

### LINKED ISSUE #13613: HttpInput#read rethrows already thrown exception, leading to possible self-suppressing exception issue
**Jetty version(s)**
* 12.0.27
* 12.1.1

**Jetty Environment**
* ee10

**Java version/vendor** `(use: java -version)`
Not relevant, but reproduced on:

    openjdk version "21.0.4" 2024-07-16 LTS
    OpenJDK Runtime Environment Zulu21.36+17-CA (build 21.0.4+7-LTS)
    OpenJDK 64-Bit Server VM Zulu21.36+17-CA (build 21.0.4+7-LTS, mixed mode, sharing)

**OS type/version**
Not relevant, but reproduced on
macOS 15.6.1

**Description**

`HttpInput#read` can rethrow the same exception if the current chunk is in a failed state. This can happen, for example, when the client hung up, and there was an early EOF.

In itself this seems fine, but when the `HttpInput` is wrapped to deal with, for example, multipart uploads it is easy to run into a situation where the close on the wrapper needs to read the underlying input stream to skip to the next part of the multipart upload, leading to self-suppression issues with the `try-with-resources` construct.

Seems related to #12029 and #11736

**How to reproduce?**

When you have a servlet with this sort of `doPost` implementation, you can run into the issue by starting an upload to the POST endpoint, and interrupting the upload before it finishes

This example servlet uses apache commons file-upload. This is important because it is this library that wraps the `HttpInput` of jetty with an implementation fit for multipart processing.

```java
public class UploadServlet extends HttpServlet {

    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
        response.setContentType("text/html");

        // Hello
        PrintWriter out = response.getWriter();
        out.println("<html><body>");
        out.println("<h1>Hello World</h1>");
        out.println("</body></html>");
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
        // use this with, for example, curl:
        // curl -v -F upload=@large_file.bin http://localhost:8080/upload
        try {
            if (JakartaServletFileUpload.isMultipartContent(request)) {
                JakartaServletFileUpload<?, ?> upload = new JakartaServletFileUpload<>();
                for (FileItemInputIterator it = upload.getItemIterator(request); it.hasNext(); ) {
                    var item = it.next();
                    if (!item.isFormField()) {
                        byte[] buffer = new byte[1024];
                        try (var is = item.getInputStream()) {
                            long total = 0;
                            int read;
                            while ((read = is.read(buffer)) != -1) {
                                total += read;
                            }
                            response.setHeader("X-Content-Length-Echo", Long.toString(total));
                            System.out.println("total read: " + total);
                        }
                    }
                }
                response.sendRedirect("/upload");
            }
        } catch (IOException e) {
            System.err.println("Regular IO Exception: " + e.getMessage());
            throw e;
        } catch (RuntimeException e) {
            // Because of the try-with-resources usage of the input stream,
            // an IllegalArgumentException is thrown regarding self-suppressing
            // exceptions.
            System.err.println("Unexpected error occurred. " + e.getMessage());
            e.printStackTrace();
        }
    }
}
```

You can find a ready-to-run maven project here: https://github.com/datadobi/jetty-self-suppression-issue
* import the project in an IDE supporting maven
* start the `Main` class in that project
* use cURL to upload a big file : curl -v -F upload=@large_file.bin http://localhost:8080/upload
* interrupt the cURL upload (using CTRL-C, for example) before the upload completes

This will result in the following output on the console of the `Main` application:

```
Unexpected error occurred. Self-suppression not permitted
java.lang.IllegalArgumentException: Self-suppression not permitted
	at java.base/java.lang.Throwable.addSuppressed(Throwable.java:1096)
	at com.datadobi.bugreports.uploaddemo.UploadServlet.doPost(UploadServlet.java:36)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:653)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:751)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1622)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1555)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:823)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:440)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:470)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1071)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)
	at org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:677)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:416)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:981)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1211)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1166)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.eclipse.jetty.server.internal.HttpConnection$HttpEofException: Early EOF
	at org.eclipse.jetty.server.internal.HttpConnection$RequestHandler.earlyEOF(HttpConnection.java:1080)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1753)
	at org.eclipse.jetty.server.internal.HttpConnection.parseAndFillForContent(HttpConnection.java:539)
	at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.read(HttpConnection.java:1371)
	at org.eclipse.jetty.server.HttpStream$Wrapper.read(HttpStream.java:167)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelRequest.read(HttpChannelState.java:948)
	at org.eclipse.jetty.server.Request$Wrapper.read(Request.java:919)
	at org.eclipse.jetty.ee10.servlet.AsyncContentProducer.readChunk(AsyncContentProducer.java:324)
	at org.eclipse.jetty.ee10.servlet.AsyncContentProducer.produceChunk(AsyncContentProducer.java:304)
	at org.eclipse.jetty.ee10.servlet.AsyncContentProducer.nextChunk(AsyncContentProducer.java:208)
	at org.eclipse.jetty.ee10.servlet.BlockingContentProducer.nextChunk(BlockingContentProducer.java:100)
	at org.eclipse.jetty.ee10.servlet.HttpInput.read(HttpInput.java:259)
	at org.eclipse.jetty.ee10.servlet.HttpInput.read(HttpInput.java:240)
	at org.apache.commons.fileupload2.core.MultipartInput$ItemInputStream.makeAvailable(MultipartInput.java:356)
	at org.apache.commons.fileupload2.core.MultipartInput$ItemInputStream.read(MultipartInput.java:415)
	at java.base/java.io.InputStream.read(InputStream.java:220)
	at com.datadobi.bugreports.uploaddemo.UploadServlet.doPost(UploadServlet.java:39)
	... 20 more

```

### PR DESCRIPTION
**Pull request by gregw**
Fix https://github.com/jetty/jetty.project/issues/13613. Due to a limitation in the implementation of try-with-resource, we should avoid rethrowing the same exception.  This PR makes a lazy copy of the exception in `Chunk.next(Chunk)`.

### CODE REVIEW

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 1]
```diff
@@ -1106,7 +1107,32 @@ static Chunk next(Chunk chunk)
             if (chunk == null)
                 return null;
             if (Content.Chunk.isFailure(chunk))
-                return chunk.isLast() ? chunk : null;
+            {
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1110]: I don't think this is the right place to handle this issue, I don't see anything wrong with `Content.Source.read()` always returning an error chunk that contains the exact same exception instance.

I think this should be handled at the place where the exception is thrown, like in `ContentSinkOutputStream`. Most (all?) places should already use `IO.rethrow()` so we can probably come up with some similar static helper, maybe like `Content.Chunk.throwIfFailure(Chunk)`?

We should also add some tests similar to `ContentSinkOutputStreamTest` for each codepath that throws a chunk's exception.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSinkOutputStream.java [hunk 2]
```diff
@@ -96,9 +97,13 @@ public void close(Callback callback) throws IOException
...
-        if (failed)
-            throw new IOException(failure.toString());
-        failed = true;
+        if (failed == null)
+            failed = failure;
+        else if (ExceptionUtil.areAssociated(failed, failure))
+            failure = IO.rethrow(ExceptionUtil.copyOf(failure));
+        else
+            failed.addSuppressed(failure);
+
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSinkOutputStream.java]: I don't think we want to keep around a `Throwable` over a `boolean`, and I would not risk adding a large number of suppressed failures to a failure stored as a field.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1110]: @lorban it is now clear that throwing the same instance is not well handled by the JDK and other libraries.

We cannot expect any user-code wrapper (such as `commons-fileupload`) to handle the case where the exception may be self suppressed or there is a loop.

I don't see any other choice than us throwing a different exception every time, or returning a new failure chunk every time.

I'd keep the code we added in #11759 and #13514, but I'm afraid we have to change the read side.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 3]
```diff
@@ -1106,7 +1107,32 @@ static Chunk next(Chunk chunk)
...
+                // handle transient failure
+                if (!chunk.isLast())
+                    return null;
+
+                // handle persistent failure with lazy copy to avoid returning the same exception.
+                return new Empty()
+                {
+                    private transient Throwable failure;
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Not `transient`.

I'd make it `final`, as the only thing to do with a failure chunk is to call `getFailure()`, so lazyness is not necessary.

I would just simplify this by calling `Chunk.from(copyOf(chunk.getFailure()))`.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java [hunk 4]
```diff
@@ -76,6 +77,45 @@ public static <T extends Throwable> T as(Class<T> type, Throwable throwable) thr
...
+                {
+                    if (Modifier.isPublic(constructor.getModifiers()))
+                        return (Throwable)constructor.newInstance(failure.getMessage());
+                }
+                catch (Throwable ignored)
+                {
+                }
+                break;
+            }
+        }
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java]: I would rather try to find the `<ExceptionClass>(Throwable)` constructor first and failing that the parameterless constructor, and pass the original failure as cause or using `initCause()` on the new exception.
The `ISE` is thrown for suppression loops, not for cause loops.

Use `failure.getClass().getConstructor(Throwable.class)`, which returns only the `public` constructor with that signature.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1110]: > I don't see any other choice than us throwing a different exception every time, or returning a new failure chunk every time.

Yes, and my point is that we should throw a different exception every time, and NOT return a new failure chunk every time.

Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1110]: @lorban not sure what you mean here. The chunk is immutable, so we have to return a new chunk instance, just to change the exception instance inside.

User code (libraries and such) will just do `throw chunk.getFailure()` so we can't really ask them to wrap the failure into a new Throwable, can we?

Comment (joakime) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1110]: How about `throw chunk.getWrappedFailure(new IOException())` which just makes the existing `chunk.getFailure()` a cause of the one passed in?

Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1110]: @sbordet I think we can ask users to not `throw chunk.getFailure()`, especially if we provide a helper.

If we don't and change the failure instance each time `getFailure()` is called, I expect difficulties tracing back a problem where an error chunk has been returned as the stack trace will be lost.

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1110]: But we have the Chunk.next() mechanism entirely to handle what the next chunk to be returned is.   If we read multiple times after a failure then we have to return different chunks if we want different exceptions.    So I think this is exactly the correct place to handle it.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: I think lazyness is required.    The normal case should be that we read the failure only once, so we do not want to create two exceptions in the normal case.  We should create the second exception only if there is a second read, and then create the third exception only if there is a third read etc.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java]: The problem with looking for a specific constructor with `getConstructor` is that it throws a `NoSuchMethod` exception if there is no such constructor.    Internally getConstructor(types...) loops through the constructors, so there is no efficiency difference.

We do not want to use pass the original failure as a cause, as the whole point is to avoid exception loops.  As the javadoc of this method says: without cause or suppressed exceptions.

Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java]: > The problem with looking for a specific constructor with getConstructor is that it throws a NoSuchMethod exception if there is no such constructor. Internally getConstructor(types...) loops through the constructors, so there is no efficiency difference.

I don't see the problem?
Also, why copy/pasting JDK code, when the JDK does it for us in a 1 line?

> We do not want to use pass the original failure as a cause

But we don't want to lose the original cause, which has no problem being in a circular loop; only suppression does, and that's why we need to copy, but without losing the cause.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: I think we can do this with a boolean like we did in other places.
We don't need to return an `Empty` subclass the first time.
The subsequent times, we just call `Chunk.from(copyOf(chunk.getFailure())`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1110]: I think we need to review `ContentSourceTransformer.read()`, which does not appear to use `next()` properly.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1110]: @gregw if we do not lose the original cause (following the suggestion @sbordet made in `ExceptionUtil.copyOf()`) then I'm fine with putting the responsibility of making a copy in `Chunk.next()`.

We also have to revisit all our `Content.Source` implementations to make sure they properly call `Chunk.next()`.

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1110]: > @gregw if we do not lose the original cause (following the suggestion @sbordet made in `ExceptionUtil.copyOf()`) then I'm fine with putting the responsibility of making a copy in `Chunk.next()`.

I'm concerned that will still create problems.  But I'll try....
> 
> We also have to revisit all our `Content.Source` implementations to make sure they properly call `Chunk.next()`.

We should do that anyway!

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java]: The problem is that we do not want to create two exceptions and two stack traces for every Throwable that might have some special constructor.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: This is a static method, so we can't have a boolean here.   

Besides, the first chunk has already been returned and we are being asked for the next chunk here.  So the "boolean" is always `true`.  I.e. we have already returned the failure once and any use of the next chunk is the second usage (`true` already).

Any state we remember has to be in the Chunk that we return.   If we are passed in a non-transient failure Chunk, then we return a Chunk that IF AND ONLY IF it is used, will create another failure exception.

Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Ok re lazyness, but remove `transient` from the field modifiers.
`transient` is for Java serialization, and we don't care here.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java [hunk 5]
```diff
@@ -76,6 +77,68 @@ public static <T extends Throwable> T as(Class<T> type, Throwable throwable) thr
...
+     */
+    public static Throwable copyOf(Throwable failure)
+    {
+        if (failure == null)
+            return null;
+
+        Throwable cause = failure.getCause();;
+
+        Class<? extends Throwable> failureType = failure.getClass();
+        while (failureType != Exception.class && failureType != RuntimeException.class && failureType != Error.class && failureType != Throwable.class)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java]: We can do these 2 pages of code with 2 lines of calling the JDK methods.
I don't see the reason to not call the JDK methods?
We should just call `failureType.getConstructor(String.class)` and then `initCause()`.
Am I missing something?

**Review by lorban — DISMISSED** [review]

**Review by sbordet — APPROVED** [review]
