### PR TITLE
Issue #8721 fix jetty:effective-web-xml goal

### LINKED ISSUE #8721: jetty:effective-web-xml doesn't generate quickstart information for web fragment jars that contain META-INF/resources
**jetty-10**

The `jetty:effective-web-xml` goal does not generate `META-INF/resources` into the `effective-web.xml` file when there are web fragment jars that do contain `META-INF/resources`.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #8721

### CODE REVIEW

**Comment by joakime** [comment]
@olamy @janbartel bump

File: jetty-maven-plugin/src/it/jetty-effective-web-xml-it/postbuild.groovy [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+/*File buildLog = new File( basedir, 'build.log' )
+assert buildLog.text.contains( 'Started Server' )
+*/
+
+File effectiveWebXml = new File( basedir, 'webapp-war/target/effective-web.xml');
+assert effectiveWebXml.text.contains('<param-name>org.eclipse.jetty.resources</param-name>\n    <param-value><![CDATA[\n    "${user.dir.uri}/resources/target/classes/META-INF/resources"]]></param-value>\n  </context-param>');
```
Comment (olamy) [inline jetty-maven-plugin/src/it/jetty-effective-web-xml-it/postbuild.groovy]: this comparaison with EOL being system dependent looks a bit fragile to me.
Maybe you could use groovy `XmlSlurper`
with something such
```
def effectiveWebXml = new XmlSlurper().parse( new File( basedir, 'webapp-war/target/effective-web.xml') )
```
then make some assert navigating the xml tree (doc here https://groovy-lang.org/processing-xml.html)

**Review by olamy — CHANGES_REQUESTED** [review]

**Review by olamy — APPROVED** [review]
