### PR TITLE
Fix flakey test `QueuedThreadPoolTest.testThreadPool`

### LINKED ISSUE #9622: Flakey test `QueuedThreadPoolTest.testThreadPool`
**Jetty version(s)**
10.0.x, 11.0.x, 12.0.x

**Description**
`QueuedThreadPoolTest.testThreadPool` started failing with

```
Expected: is <0>
     but: was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.util@11.0.15-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPoolTest.waitForIdle(QueuedThreadPoolTest.java:714)
	at org.eclipse.jetty.util@11.0.15-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPoolTest.testThreadPool(QueuedThreadPoolTest.java:305)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
```

### PR DESCRIPTION
**Pull request by lorban**
Fixes #9622.

Changed the wait loops to use awaitility, and ensure that the tested values are staying stable for a reasonable duration to avoid benign races in the thread counters.

### CODE REVIEW

File: jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java [hunk 1]
```diff
@@ -700,51 +704,29 @@ public void testMaxStopTime() throws Exception
...
+            public void conditionEvaluated(EvaluatedCondition condition)
             {
-                Thread.sleep(50);
             }
-            catch (InterruptedException ignored)
+
+            @Override
+            public void onTimeout(TimeoutEvent timeoutEvent)
             {
+                LOG.info(timeoutEvent.getDescription() + " " + tp);
```
Comment (sbordet) [inline jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java]: Please use "{}" not concatenation.
Also, maybe `tp.dump()`?

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by gregw — DISMISSED** [review]

File: jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java (hunk 1 above)
Comment (lorban) [reply jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java]: This doesn't apply anymore.

**Review by sbordet — APPROVED** [review]
