### PR TITLE
Issue #13259 - Support `javax.naming.Referenceable` from core `Transaction`

### LINKED ISSUE #13259: `org.eclipse.jetty.plus.jndi.Transaction` should support `javax.naming.Referenceable` as a constructor option too.
**Jetty version(s)**
12.0.22

**Jetty Environment**
Any

**Description**
The current core level `org.eclipse.jetty.plus.jndi.Transaction` only has one public constructor.

``` java
public Transaction(String scope, Reference userTransactionRef) throws NamingException
```

It should also support the newer `javax.naming.Referenceable` implementation for Transaction implementations that have migrated to the new interface.

Eg:

``` java
import javax.naming.Referenceable;

public Transaction(String scope, Referenceable userTransactionRef) throws NamingException
```

### PR DESCRIPTION
**Pull request by joakime**
New constructor for supporting `javax.naming.Referenceable` feature.

This would allow an XML to initialize a UserTransaction that comes from a `Referenceable`

XML Example that uses [`com.atomikos.icatch.jta.UserTransactionImp`](https://github.com/atomikos/transactions-essentials/blob/master/public/transactions-jta/src/main/java/com/atomikos/icatch/jta/UserTransactionImp.java) which would be possible with this PR.
(Without this PR, this is an invalid XML setup)

``` xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://jetty.org/configure_10_0.dtd">
<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <New id="usertx" class="org.eclipse.jetty.plus.jndi.Transaction"> <!-- THIS REFERENCE -->
    <Arg><Property name="environment" default="ee8"/></Arg>
    <Arg>
      <New class="com.atomikos.icatch.jta.UserTransactionImp" />
    </Arg>
  </New>
</Configure>
```

Closes #13259

### CODE REVIEW

File: jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/jndi/Transaction.java [hunk 1]
```diff
@@ -71,6 +72,17 @@ public Transaction(String scope, Reference userTransactionRef)
         this(scope, (Object)userTransactionRef);
     }
 
+    /**
+     * @param scope the environment in which to bind the UserTransaction
+     * @param userTransactionReferenceable a {@link Referenceable} to a UserTransaction
+     * @throws NamingException if there was a problem re
+     */
+    public Transaction(String scope, Referenceable userTransactionReferenceable)
```
Comment (janbartel) [inline jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/jndi/Transaction.java:80]:
```suggestion
    public Transaction(String scope, Referenceable referenceable)
```

File: jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/jndi/Transaction.java [hunk 2]
```diff
@@ -71,6 +72,17 @@ public Transaction(String scope, Reference userTransactionRef)
         this(scope, (Object)userTransactionRef);
     }
 
+    /**
+     * @param scope the environment in which to bind the UserTransaction
+     * @param userTransactionReferenceable a {@link Referenceable} to a UserTransaction
```
Comment (janbartel) [inline jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/jndi/Transaction.java:77]:
```suggestion
     * @param referenceable a {@link Referenceable} to a UserTransaction
```

File: jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/jndi/Transaction.java [hunk 3]
```diff
@@ -71,6 +72,17 @@ public Transaction(String scope, Reference userTransactionRef)
...
+     * @throws NamingException if there was a problem re
+     */
+    public Transaction(String scope, Referenceable userTransactionReferenceable)
+        throws NamingException
+    {
+        this(scope, (Object)userTransactionReferenceable.getReference());
```
Comment (janbartel) [inline jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/jndi/Transaction.java:83]:
```suggestion
        this(scope, (Object)referenceable.getReference());
```

**Review by janbartel — APPROVED** [review]
Trivial name change suggested for the `Referenceable` parameter.
