### PR TITLE
Issue #3974 flaky AsyncMiddleManServletTest overflow to filesystem tests

### LINKED ISSUE #3974: Flaky test org.eclipse.jetty.proxy.AsyncMiddleManServletTest.testAfterContentTransformerOverflowingToDisk
same for  org.eclipse.jetty.proxy.AsyncMiddleManServletTest.testAfterContentTransformerDiskInputStreamReset
they tend to fail sometimes on Jenkins
https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x/1087/testReport/
https://jenkins.webtide.net/job/jetty.project/job/jetty-9.4.x/1088/testReport/

`Total timeout 5000 ms elapsed`
maybe increasing timeout?

### PR DESCRIPTION
**Pull request by joakime**
Research into why this test fails occasionally on CI.

This has a few changes to AsyncMiddleManServletTest to attempt to glean information from the failure.

The likely reason is that the FileSystem I/O is overloaded at the time of the test.
And the FileChannel.force(true) is just taking too long to complete.

Bumped up the Client request timeout from 5 seconds to 15 seconds.
That gives the test more time to complete in the high FileSystem I/O scenario, but doesn't impact the normal operations of the test.

### CODE REVIEW

File: jetty-proxy/src/test/resources/jetty-logging.properties [hunk 1]
```diff
@@ -1,6 +1,7 @@
 org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog
+org.eclipse.jetty.LEVEL=INFO
 #org.eclipse.jetty.LEVEL=DEBUG
 #org.eclipse.jetty.client.LEVEL=DEBUG
-#org.eclipse.jetty.proxy.LEVEL=DEBUG
+org.eclipse.jetty.proxy.LEVEL=DEBUG
```
Comment (joakime) [inline jetty-proxy/src/test/resources/jetty-logging.properties]: I need to remove this.

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java [hunk 2]
```diff
@@ -508,46 +508,52 @@ protected ContentTransformer newClientRequestContentTransformer(HttpServletReque
                     throw new NullPointerException("explicitly_thrown_by_test");
                 };
             }
-        });
+        };
+        startServer(new EchoHttpServlet());
```
Comment (gregw) [inline jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Is the changed order of starting significant?  If not can we keep the order to minimise changes

Comment (joakime) [reply jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: This specific change was to take StacklessLogging behavior from the scope of the entire Test class, to specific methods where it was appropriate.
Allowing stacks to be produced in the other cases where knowing details about the failure is important.

I'll review the start order.

Comment (sbordet) [reply jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Yes please restore the inlining of `AsyncMiddleManServlet`.

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java [hunk 3]
```diff
@@ -508,46 +508,52 @@ protected ContentTransformer newClientRequestContentTransformer(HttpServletReque
...
+                        if (++count < 2)
+                            output.add(input);
+                        else
+                            throw new NullPointerException("explicitly_thrown_by_test");
+                    }
+                };
+            }
+        };
+        startServer(new EchoHttpServlet());
+        startProxy(proxyServlet);
```
Comment (sbordet) [inline jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Restore inlining of `AsyncMiddleManServlet`.

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java [hunk 4]
```diff
@@ -625,14 +630,19 @@ public void transform(ByteBuffer input, boolean finished, List<ByteBuffer> outpu
                     }
                 };
             }
-        });
+        };
+        startServer(serverServlet);
+        startProxy(proxyServlet);
```
Comment (sbordet) [inline jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Restore inlining of `AsyncMiddleManServlet`.

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java [hunk 5]
```diff
@@ -983,6 +993,7 @@ public boolean transform(Source source, Sink sink) throws IOException
     }
 
     @Test
+    @Tag("overflow")
```
Comment (sbordet) [inline jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Unused tag?

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java [hunk 6]
```diff
@@ -1037,34 +1048,71 @@ public boolean transform(Source source, Sink sink) throws IOException
...
+                dump.append("\n        at ");
+                dump.append(stackTraceElement);
             }
+            dump.append("\n\n");
         }
+        return dump.toString();
     }
 
     @Test
+    @Tag("overflow")
```
Comment (sbordet) [inline jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Unused tag?

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java [hunk 7]
```diff
@@ -1122,14 +1170,15 @@ public long getLength()
                     return data.length + 1;
                 }
             })
-            .timeout(5 * idleTimeout, TimeUnit.MILLISECONDS)
+            .timeout(15, TimeUnit.SECONDS)
```
Comment (sbordet) [inline jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Was `5 * idleTimeout` so it should be `15 * idleTimeout` now.

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java [hunk 8]
```diff
@@ -1122,14 +1170,15 @@ public long getLength()
...
             .send();
 
         assertTrue(destroyLatch.await(5 * idleTimeout, TimeUnit.MILLISECONDS));
         assertEquals(HttpStatus.REQUEST_TIMEOUT_408, response.getStatus());
     }
 
     @Test
+    @Tag("overflow")
```
Comment (sbordet) [inline jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Unused tag?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java (hunk 3 above)
Comment (joakime) [reply jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Restored inlining.

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java (hunk 4 above)
Comment (joakime) [reply jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Restored

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java (hunk 5 above)
Comment (joakime) [reply jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Removed.

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java (hunk 6 above)
Comment (joakime) [reply jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Removed.

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java (hunk 8 above)
Comment (joakime) [reply jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Removed.

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java (hunk 7 above)
Comment (joakime) [reply jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Based on `15 * idleTimeout` now

File: jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java (hunk 2 above)
Comment (joakime) [reply jetty-proxy/src/test/java/org/eclipse/jetty/proxy/AsyncMiddleManServletTest.java]: Restored.

File: jetty-util/src/main/java/org/eclipse/jetty/util/RuntimeUtil.java [hunk 9]
```diff
@@ -0,0 +1,121 @@
...
+import java.lang.management.LockInfo;
+import java.lang.management.ManagementFactory;
+import java.lang.management.MonitorInfo;
+import java.lang.management.ThreadInfo;
+import java.lang.management.ThreadMXBean;
+
+/**
+ * Java Runtime specific utility methods.
+ */
+public final class RuntimeUtil
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/RuntimeUtil.java]: No, I don't want to maintain this class publicly just for 1 test.
No generic usefulness because we had the same thing in `jetty-monitor` but was not used and we ditched the whole module.
Please remove it.

File: jetty-util/src/test/java/org/eclipse/jetty/util/RuntimeUtilTest.java [hunk 10]
```diff
@@ -0,0 +1,35 @@
...
+
+package org.eclipse.jetty.util;
+
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.TestInfo;
+
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.containsString;
+
+public class RuntimeUtilTest
```
Comment (sbordet) [inline jetty-util/src/test/java/org/eclipse/jetty/util/RuntimeUtilTest.java]: See above, please remove it.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-util/src/test/java/org/eclipse/jetty/util/RuntimeUtilTest.java (hunk 10 above)
Comment (joakime) [reply jetty-util/src/test/java/org/eclipse/jetty/util/RuntimeUtilTest.java]: Removed.

File: jetty-util/src/main/java/org/eclipse/jetty/util/RuntimeUtil.java (hunk 9 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/RuntimeUtil.java]: Removed.

**Review by sbordet — APPROVED** [review]
