### PR TITLE
Issue #10513 - fix multipart lockup with HTTP/2

### LINKED ISSUE #10513: Lockup processing POST request body with Jetty 12.0.1 using http/2
**Jetty version(s)**
12.0.1

**Jetty Environment**
ee10 / http/2

**Java version/vendor** `(use: java -version)`
OpenJDK Runtime Environment (Red_Hat-21.0.0.0.35-1.rolling.fc38) (build 21+35)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.0.0.35-1.rolling.fc38) (build 21+35, mixed mode, sharing)

**OS type/version**
Fedora 38 Workstation

**Description**
This application sets up an embedded Jetty 12.0.1 instance with one servlet class TestServlet1. The doPost method simply tries to read-and-discard the content of the body before sending a short response.
Posting a sufficiently large file to the application will result in a lockup. The curl client will block trying to send more data while the application blocks trying to read. The point where th size of the POST body is printed to stderr is then never reached.

A slight modification of the code makes it use TestServlet2 with a doPost that processes the input expecting a ZIP-formatted body by reading and discarding entries and printing the name:size of each entry to stderr. Posting a sufficiently large ZIP file to it shows that initial entries are processed corrrectly then it locks up the same way as with TestServlet1.

Small POST requests seem to work without issues. GET requests seem to work fine also and our application ported from Jetty 11 to Jetty 12 works mostly fine except for large POST requests.

**How to reproduce?**
See the above description. I am sorry that this is Scala code instead of Java. I currently have no Java development environment setup.

#### Compile/runtime dependencies specified in build.sbt, some of which redundant for the test code

```
libraryDependencies += "org.eclipse.jetty" % "jetty-core" % "12.0.1"
libraryDependencies += "org.eclipse.jetty" % "jetty-io" % "12.0.1"
libraryDependencies += "org.eclipse.jetty" % "jetty-server" % "12.0.1"
libraryDependencies += "org.eclipse.jetty" % "jetty-alpn-server" % "12.0.1"
libraryDependencies += "org.eclipse.jetty" % "jetty-session" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.ee10" % "jetty-ee10-servlet" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.websocket" % "jetty-websocket-jetty-api" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.websocket" % "jetty-websocket-jetty-server" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.ee10.websocket" % "jetty-ee10-websocket-jetty-server" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.http2" % "jetty-http2-server" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.http3" % "jetty-http3-server" % "12.0.1"
```

#### Scala code

``` scala
package nl.idfix.util.test

import java.io._
import java.util.zip._

import jakarta.servlet._
import jakarta.servlet.http._

import org.eclipse.jetty.alpn._
import org.eclipse.jetty.alpn.server._
import org.eclipse.jetty.http2._
import org.eclipse.jetty.http2.server._
import org.eclipse.jetty.http3._
import org.eclipse.jetty.http3.server._
import org.eclipse.jetty.util.resource._
import org.eclipse.jetty.security._
import org.eclipse.jetty.server._
import org.eclipse.jetty.server.handler.{ ContextHandler, ResourceHandler, DefaultHandler, ContextHandlerCollection }
import org.eclipse.jetty.ee10.servlet._
import org.eclipse.jetty.session.{ DefaultSessionIdManager, HouseKeeper }
import org.eclipse.jetty.util.security._
import org.eclipse.jetty.util.ssl._
import org.eclipse.jetty.util.thread._
import org.eclipse.jetty.server._
import org.eclipse.jetty.websocket.api._
import org.eclipse.jetty.ee10.websocket.server._
import org.eclipse.jetty.ee10.websocket.server.config._
import org.eclipse.jetty.http.HttpFields

class NullOutputStream extends OutputStream
{
	def write(byte : Int) = ()
	override def write(buff : Array[Byte]) = ()
	override def write(buff : Array[Byte],start : Int,count : Int) = ()
}

class CountingOutputStream(wrapped : OutputStream) extends OutputStream
{
	private var written : Long = 0
	
	def bytesWritten = written
	
	def write(byte : Int)
	{
		wrapped.write(byte)
		written += 1
	}
	
	override def write(buffer : Array[Byte],offset : Int,bytes : Int)
	{
		wrapped.write(buffer,offset,bytes)
		written += bytes
	}
	
	override def write(buffer : Array[Byte])
	{
		wrapped.write(buffer)
		written += buffer.length
	}
	
	override def flush = wrapped.flush
	override def close = wrapped.close
}

class TestServlet1 extends HttpServlet
{
	override def doPost(request : HttpServletRequest,response : HttpServletResponse)
	{
		val in = request.getInputStream
		val out = new CountingOutputStream(new NullOutputStream)
		in.transferTo(out)
		in.close
		out.close
		System.err.println("BYTE COUNT:" + out.bytesWritten)
		response.setHeader("Content-Type","text/plain")
		val writer = response.getWriter
		writer.println("Thank you")
		writer.close
	}
}

class TestServlet2 extends HttpServlet
{
	override def doPost(request : HttpServletRequest,response : HttpServletResponse)
	{
		val in = request.getInputStream
		val zip = new ZipInputStream(in)

		var entry = zip.getNextEntry
		while (entry != null)
		{
			val out = new CountingOutputStream(new NullOutputStream)
			zip.transferTo(out)
			out.close
			System.err.println(entry.getName + ":" + out.bytesWritten)
			entry = zip.getNextEntry
		}
		zip.close
		val writer = response.getWriter
		writer.println("Thank you")
		writer.close
	}
}

object JettyTest
{
	def main(args: Array[String])
	{
		val pool = new QueuedThreadPool
		val server = new Server(pool)

		/* Create connector */
		val keyStore = "abc.jks"
		val keyPassword = "secret"
		val sslContextFactory = new SslContextFactory.Server
		sslContextFactory.setEndpointIdentificationAlgorithm("HTTPS")
		sslContextFactory.setKeyStorePath(keyStore)
		sslContextFactory.setKeyStorePassword(keyPassword)
		sslContextFactory.setKeyManagerPassword(keyPassword)
		sslContextFactory.setKeyStoreType("JKS")
		val httpsConfig = new HttpConfiguration
		httpsConfig.setSecureScheme("https")
		httpsConfig.setSecurePort(8443)
		val http1 = new HttpConnectionFactory(httpsConfig)
		val http2 = new HTTP2ServerConnectionFactory(httpsConfig)
		val alpn = new ALPNServerConnectionFactory
		alpn.setDefaultProtocol(http1.getProtocol)
		val ssl = new SslConnectionFactory(sslContextFactory,alpn.getProtocol)
		val http2Connector = new ServerConnector(server,ssl,alpn,http2,http1)
		http2Connector.setHost("0.0.0.0")
		http2Connector.setPort(8443)
		http2Connector.setIdleTimeout(1800000L)
		server.addConnector(http2Connector)

		/* Create Servlet context */

		val servletContext = new ServletContextHandler
		servletContext.setContextPath("/")
		val holder = new ServletHolder(classOf[TestServlet1])
		servletContext.addServlet(holder,"/*")

		/* Setup server */
		val ctxHandler = new ContextHandlerCollection
		ctxHandler.setHandlers(servletContext)

		server.setHandler(ctxHandler)
		server.start
		server.join
	}
}
```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Issue #10513

- add `Http2MultiPartServletTest` to replicate the issue 
- proposed fix inside `HTTP2Session.StreamData`.

PR is not complete yet but worth getting some early reviews.

todo: 
- more improvements on the testing, also test HTTP/3 etc...
- investigate why chunks aren't released if the part is being written to a file
- form configuration from the `ServletContextHandler` is overriding configuration from the `MultipartConfigElement`

### CODE REVIEW

**Comment by lorban** [comment]
I saw two failing tests in a PR build because of spurious leaks. Could you please disable leak tracking for them? You just have to annotate:

`org.eclipse.jetty.test.client.transport.HttpClientStreamTest.testInputStreamContentProviderThrowingWhileReading` with `@Tag("DisableLeakTracking:server:H3")`

and

`org.eclipse.jetty.test.client.transport.HttpClientTimeoutTest.testVeryShortTimeout` with
```
@Tag("DisableLeakTracking:client:HTTP")
@Tag("DisableLeakTracking:client:HTTPS")
@Tag("DisableLeakTracking:client:UNIX_DOMAIN")
````

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java [hunk 1]
```diff
@@ -2444,14 +2447,29 @@ public void retain()
...
+
+                // once the reference count goes to zero, then it does not matter if the buffer is empty or not, as it is no
+                // longer available to the application to read, and thus has been consumed (if not already consumed).
+                if (consumed.compareAndSet(false, true))
+                    flowControl.onDataConsumed(HTTP2Session.this, stream, flowControlLength);
+                return true;
             }
-            return result;
+
+            // If all the data has been consumes and at least one release call is made, that indicates that the content
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java]: Typo: _If all the data has been **consumed**_

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/Http2MultiPartServletTest.java [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+    public void before() throws Exception
+    {
+        tmpDir = Files.createTempDirectory(Http2MultiPartServletTest.class.getSimpleName());
+        tmpDirString = tmpDir.toAbsolutePath().toString();
+    }
+
+    private void start(HttpServlet servlet, MultipartConfigElement config) throws Exception
+    {
+        config = config == null ? new MultipartConfigElement(tmpDirString, MAX_FILE_SIZE, -1, 0) : config;
+        server = new Server(null, null, null);
```
Comment (lorban) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/Http2MultiPartServletTest.java]: You should use a leak-tracking buffer pool. See `HttpClientProxyProtocolTest` as an example of how to use `ArrayByteBufferPool.Tracking`.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java [hunk 3]
```diff
@@ -2444,14 +2447,29 @@ public void retain()
...
+            // has been fully consumed. The fact that release count has not gone to zero indicates that the application wants
+            // to retain the data, but not prevent more data being read.
+            // Note that a release with a non-empty buffer, may indicate the release of just a part of the buffer and thus
+            // the data has not been consumed. An optimization might be to consume the data up to the current position on each
+            // release.
+            if (BufferUtil.isEmpty(data.frame().getByteBuffer()) && consumed.compareAndSet(false, true))
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java]: I'm not so sure about this one. How about the following oddity?

```java
Buffer duplicate = buffer.slice();
buffer.get(...); // read everything
duplicate.get(...); // try to read again
```

Wouldn't that be a nasty surprise?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 4]
```diff
@@ -1193,6 +1197,98 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+    public void testUploadWithRetainedData(Transport transport) throws Exception
+    {
+        List<Content.Chunk> chunks = new ArrayList<>();
+
+        start(transport, new Handler.Abstract()
+        {
+            @Override
+            public boolean handle(Request request, org.eclipse.jetty.server.Response response, Callback callback)
+            {
+                Runnable retainer = new Runnable()
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: You may find `o.e.j.util.CompletableTask` better to use instead of bare `Runnable`.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 5]
```diff
@@ -1193,6 +1197,98 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+            }
+        });
+
+        byte[] data = new byte[16 * 1024 * 1024];
+        new Random().nextBytes(data);
+        CountDownLatch latch = new CountDownLatch(1);
+        ByteBufferRequestContent content = new ByteBufferRequestContent(ByteBuffer.wrap(data));
+        client.newRequest(newURI(transport))
+            .body(content)
+            .send(new BufferingResponseListener(data.length)
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: You may use `CompletableResponseListener` here, if it's easier.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 6]
```diff
@@ -1193,6 +1197,98 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+                                }
+                                BufferUtil.clear(byteBuffer);
+                            }
+                            chunk.release();
+
+                            if (Content.Chunk.isFailure(chunk))
+                            {
+                                callback.failed(chunk.getFailure());
+                                return;
+                            }
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: I'd move this just after the null check, as per usual idiom.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 7]
```diff
@@ -1193,6 +1197,98 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+                            if (chunk == null)
+                            {
+                                request.demand(this);
+                                return;
+                            }
+
+                            if (chunk.hasRemaining())
+                            {
+                                ByteBuffer byteBuffer = chunk.getByteBuffer();
+                                if (chunk.canRetain())
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java:1336]: It's a test, surely we can retain?

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/Http2MultiPartServletTest.java [hunk 8]
```diff
@@ -0,0 +1,186 @@
...
+import org.eclipse.jetty.util.thread.QueuedThreadPool;
+import org.junit.jupiter.api.AfterEach;
+import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.Test;
+
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.containsString;
+import static org.hamcrest.Matchers.equalTo;
+
+public class Http2MultiPartServletTest
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/Http2MultiPartServletTest.java]: Move this to module `jetty-ee10-test-client-transport`, so that you don't pollute `ee10-servlet` with http2 deps.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java]: After discussing this issue with @sbordet, we came to an agreement that the right place to open the flow control window is in `HTTP2Stream.readData()`, i.e.: right before handing the buffer to the application code, to decouple the window control from the re-pooling of the buffer. This would make the behavior in line with how H1 works, as the TCP window is controlled by when you read from the socket.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 7 above)
Comment (gregw) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java:1336]: I don't know? Do all the transports provide retainable chunks?

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/Http2MultiPartServletTest.java (hunk 8 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/Http2MultiPartServletTest.java]: I think we can delete this test now, as we have a simpler reproducer that works for all transports in `HttpClientStreamTest`

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/Http2MultiPartServletTest.java (hunk 2 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/Http2MultiPartServletTest.java]: The other test already uses that and I'm deleting this test

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java]: @lorban I don't understand the surprise?  If a make a duplicate, then of course I can read the data again from the buffer.

@sbordet @lorban Might gut reaction to the idea of opening the window in `readData` is NNNNNNNNOOOOOOOoooooo.... but I can't think of a rational reason why not.
That would make reading about consumption and retain/release about buffering.  Good separation of concerns.

Let me try to implement....

**Review by sbordet — APPROVED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 9]
```diff
@@ -1193,6 +1202,109 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
         assertTrue(clientLatch.await(timeoutInSeconds, TimeUnit.SECONDS));
     }
 
+    @ParameterizedTest
+    @MethodSource("transports")
+    @Tag("DisableLeakTracking:server:UNIX_DOMAIN")
```
Comment (lorban) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java:1299]: Please restore the tag disabling leak tracking for server HTTP and HTTPS as those are flaky:

```
@Tag("DisableLeakTracking:server:HTTP")
@Tag("DisableLeakTracking:server:HTTPS")
```

Comment (gregw) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java:1299]: I did this.

@lachlan-roberts but there are still other tests failing.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java [hunk 10]
```diff
@@ -57,113 +51,112 @@ public void testExplicitDemand() throws Exception
...
+            if (data == null)
+            {
+                Thread.sleep(100);
+                continue;
+            }
+            received += data.frame().remaining();
+            data.release();
+            if (data.frame().isEndStream())
+            {
+                assertEquals(received, length);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java]: The two arguments `received` and `length` are in the wrong order.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java [hunk 11]
```diff
@@ -57,113 +51,112 @@ public void testExplicitDemand() throws Exception
...
-        Thread.sleep(1000);
-        assertEquals(1, clientQueue.size());
-
-        // Demand 1 more DATA frames.
+        serverStream.data(new DataFrame(serverStream.getId(), ByteBuffer.allocate(length), true));
+
+        // The client onDataAvailable() should be invoked once because it does one explicit demand.
+        await().atMost(5, TimeUnit.SECONDS).until(() -> clientStreamRef.get() != null);
+        Stream clientStream = clientStreamRef.getAndSet(null);
+        await().during(1, TimeUnit.SECONDS).until(() -> clientStreamRef.get() == null);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java]: You forgot `.atMost(5, TimeUnit.SECONDS)`.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java [hunk 12]
```diff
@@ -57,113 +51,112 @@ public void testExplicitDemand() throws Exception
...
         while (true)
         {
-            serverStream.demand();
-            await().atMost(1, TimeUnit.SECONDS).until(() -> serverQueue.size() == count.get() + 1);
-            count.incrementAndGet();
-            long sum = serverQueue.stream()
-                .mapToLong(data -> data.frame().getByteBuffer().remaining())
-                .sum();
-            if (sum == length)
+            data = serverStream.readData();
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java]: This loop could be rewritten with awaitility, you just need to change the `received` variable on line 99 into an `AtomicInteger`:

```java
// Read all the rest.
await()
    .pollInterval(1, TimeUnit.MILLISECONDS)
    .atMost(5, TimeUnit.SECONDS).until(() ->
{
    Stream.Data d = clientStream.readData();
    if (d == null)
        return false;
    received.addAndGet(d.frame().remaining());
    d.release();
    return d.frame().isEndStream();
});
assertEquals(length, received.get());
```

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java [hunk 13]
```diff
@@ -57,113 +51,112 @@ public void testExplicitDemand() throws Exception
...
         while (true)
         {
-            clientStream.demand();
-            await().atMost(1, TimeUnit.SECONDS).until(() -> clientQueue.size() == count.get() + 1);
-            count.incrementAndGet();
-            long sum = clientQueue.stream()
-                .mapToLong(data -> data.frame().getByteBuffer().remaining())
-                .sum();
-            if (sum == length)
+            data = clientStream.readData();
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java]: This loop could be rewritten with awaitility the same way as above.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java [hunk 14]
```diff
@@ -350,72 +344,56 @@ public Stream.Listener onNewStream(Stream stream, HeadersFrame requestFrame)
...
+                streamRef.set(stream);
             }
         });
+        await().atMost(5, TimeUnit.SECONDS).until(() -> streamRef.get() != null);
 
-        Stream.Data data = exchanger.exchange(null, 5, TimeUnit.SECONDS);
-        checkThatWeAreFlowControlStalled(exchanger);
+        // Did not read yet, verify that we are flow control stalled.
+        Stream stream = streamRef.getAndSet(null);
+        await().during(1, TimeUnit.SECONDS).until(() -> streamRef.get() == null);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java]: You forgot `.atMost(5, TimeUnit.SECONDS)`.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java [hunk 15]
```diff
@@ -350,72 +344,56 @@ public Stream.Listener onNewStream(Stream stream, HeadersFrame requestFrame)
...
-        // Release the first chunk.
+        // Read the first chunk.
+        Stream.Data data = stream.readData();
+        assertNotNull(data);
         data.release();
 
-        data = exchanger.exchange(null, 5, TimeUnit.SECONDS);
-        checkThatWeAreFlowControlStalled(exchanger);
+        // Did not demand, so onDataAvailable() should not be called.
+        await().during(1, TimeUnit.SECONDS).until(() -> streamRef.get() == null);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java]: You forgot `.atMost(5, TimeUnit.SECONDS)`.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java [hunk 16]
```diff
@@ -350,72 +344,56 @@ public Stream.Listener onNewStream(Stream stream, HeadersFrame requestFrame)
...
+
+        // Demand, onDataAvailable() should be called.
+        stream.demand();
+        await().atMost(5, TimeUnit.SECONDS).until(() -> streamRef.get() != null);
 
-        // Release the second chunk.
+        // Did not read yet, verify that we are flow control stalled.
+        stream = streamRef.getAndSet(null);
+        await().during(1, TimeUnit.SECONDS).until(() -> streamRef.get() == null);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java]: You forgot `.atMost(5, TimeUnit.SECONDS)`.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java [hunk 17]
```diff
@@ -484,40 +433,51 @@ else if (dataFrames == 3 || dataFrames == 4 || dataFrames == 5)
...
-        DataFrame dataFrame = new DataFrame(stream.getId(), ByteBuffer.allocate(length), true);
-        stream.data(dataFrame, Callback.NOOP);
+        // Verify that the data arrived to the server.
+        await().atMost(5, TimeUnit.SECONDS).until(() -> serverStreamRef.get() != null);
 
-        Stream.Data data = exchanger.exchange(null, 5, TimeUnit.SECONDS);
-        checkThatWeAreFlowControlStalled(exchanger);
+        // Did not read yet, verify that we are flow control stalled.
+        Stream serverStream = serverStreamRef.getAndSet(null);
+        await().during(1, TimeUnit.SECONDS).until(() -> serverStreamRef.get() == null);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java]: You forgot `.atMost(5, TimeUnit.SECONDS)`.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java [hunk 18]
```diff
@@ -57,113 +51,112 @@ public void testExplicitDemand() throws Exception
...
-        clientStream.data(new DataFrame(clientStream.getId(), ByteBuffer.allocate(length), true), Callback.NOOP);
 
-        // The server should receive only 1 DATA frame because it does 1 explicit demand.
-        // Wait a bit more to be sure it only receives 1 DATA frame.
-        Thread.sleep(1000);
-        assertEquals(1, serverQueue.size());
+        // The server onDataAvailable() should be invoked once because it does one explicit demand.
+        await().atMost(5, TimeUnit.SECONDS).until(() -> serverStreamRef.get() != null);
+        Stream serverStream = serverStreamRef.getAndSet(null);
+        await().during(1, TimeUnit.SECONDS).until(() -> serverStreamRef.get() == null);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java]: You forgot `.atMost(5, TimeUnit.SECONDS)`.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java [hunk 19]
```diff
@@ -57,113 +51,112 @@ public void testExplicitDemand() throws Exception
...
+            if (data == null)
+            {
+                Thread.sleep(100);
+                continue;
+            }
+            received += data.frame().remaining();
+            data.release();
+            if (data.frame().isEndStream())
+            {
+                assertEquals(received, length);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/DataDemandTest.java]: The two arguments `received` and `length` are in the wrong order.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java [hunk 20]
```diff
@@ -484,40 +433,51 @@ else if (dataFrames == 3 || dataFrames == 4 || dataFrames == 5)
...
-        // Consume the first chunk.
+        // Read the first chunk.
+        Stream.Data data = serverStream.readData();
+        assertNotNull(data);
         data.release();
 
-        data = exchanger.exchange(null, 5, TimeUnit.SECONDS);
-        checkThatWeAreFlowControlStalled(exchanger);
+        // Did not demand, so onDataAvailable() should not be called.
+        await().during(1, TimeUnit.SECONDS).until(() -> serverStreamRef.get() == null);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java]: You forgot `.atMost(5, TimeUnit.SECONDS)`.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java [hunk 21]
```diff
@@ -484,40 +433,51 @@ else if (dataFrames == 3 || dataFrames == 4 || dataFrames == 5)
...
-        data.release();
+        // Demand, onDataAvailable() should be called.
+        serverStream.demand();
+        await().atMost(5, TimeUnit.SECONDS).until(() -> serverStreamRef.get() != null);
 
-        assertTrue(dataLatch.await(5, TimeUnit.SECONDS));
-    }
+        // Did not read yet, verify that we are flow control stalled.
+        serverStream = serverStreamRef.getAndSet(null);
+        await().during(1, TimeUnit.SECONDS).until(() -> serverStreamRef.get() == null);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java]: You forgot `.atMost(5, TimeUnit.SECONDS)`.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java [hunk 22]
```diff
@@ -554,95 +514,96 @@ public Stream.Listener onNewStream(Stream stream, HeadersFrame requestFrame)
...
-                    latch.countDown();
-                else
-                    stream.demand();
+                streamRef4.set(stream);
             }
         });
-
         // Verify that the data does not arrive because the server session is stalled.
-        assertFalse(latch.await(1, TimeUnit.SECONDS));
+        await().during(1, TimeUnit.SECONDS).until(() -> streamRef4.get() == null);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java]: You forgot `.atMost(5, TimeUnit.SECONDS)`.

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java [hunk 23]
```diff
@@ -554,95 +514,96 @@ public Stream.Listener onNewStream(Stream stream, HeadersFrame requestFrame)
...
+        consumeAll(streamRef2.get());
+        consumeAll(streamRef3.get());
+        consumeAll(streamRef4.get());
+    }
 
-        dataList2.forEach(Stream.Data::release);
-        dataList3.forEach(Stream.Data::release);
+    private void consumeAll(Stream stream) throws Exception
+    {
+        while (true)
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/FlowControlStrategyTest.java]: I would replace this loop with awaitility, like in `DataDemandTest` so that the test can never hang forever.

**Review by lorban — CHANGES_REQUESTED** [review]
LGTM overall, but the tests could be slightly simplified.

**Review by lorban — APPROVED** [review]
