### PR TITLE
Issue #4798 - Recover from Selector Failures

### LINKED ISSUE #4798: Better handling of fatal Selector failures
**Jetty version**
9.4.x

**Description**
Various `java.nio.channels.Selector` APIs throw `IOException`, such as `Selector.select()`.

However, fatal selector failures should not happen, and recent work especially on Java 13 (see https://mail.openjdk.java.net/pipermail/nio-dev/2020-February/007051.html), made sure that it was the case _implementation_ wise, although the API signature still allows exceptions to be thrown.

Jetty does not handle well fatal selector failures.

If a `ManagedSelector` fails, Jetty exits the selector thread but leaves the `ManagedSelector` in the array of selectors in `SelectorManager._selectors`.

A new connection may arrive and be assigned to the failed selector, ending up in its update queue which will never be drained, since the selector thread has exited already.

#3989 introduced some overridable behavior in `ManagedSelector` but `SelectorManager` still references the failed selector.

### PR DESCRIPTION
**Pull request by sbordet**
The second commit has the changes related to fixing the issue (the first is a code cleanup).

### CODE REVIEW

File: jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java [hunk 1]
```diff
@@ -378,14 +473,25 @@ public String toString()
...
+
+        /**
+         * Callback method invoked when a selectable is transferred
+         * from one selector to a new selector.
+         *
+         * @param oldKey the old SelectionKey
+         * @param newKey the new SelectionKey
          */
-        void updateKey();
+        void replaceKey(SelectionKey oldKey, SelectionKey newKey);
```
Comment (lorban) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: Both implementations of this method don't use the `oldKey` parameter. Use it or drop it?

File: jetty-io/src/main/java/org/eclipse/jetty/io/SocketChannelEndPoint.java [hunk 2]
```diff
@@ -18,24 +18,15 @@
...
 import java.net.Socket;
 import java.nio.channels.SelectableChannel;
 import java.nio.channels.SelectionKey;
 import java.nio.channels.SocketChannel;
 
-import org.eclipse.jetty.util.log.Log;
-import org.eclipse.jetty.util.log.Logger;
 import org.eclipse.jetty.util.thread.Scheduler;
 
 public class SocketChannelEndPoint extends ChannelEndPoint
```
Comment (lorban) [inline jetty-io/src/main/java/org/eclipse/jetty/io/SocketChannelEndPoint.java:28]: This class does very little more than `ChannelEndPoint` Shouldn't the two be merged?

File: tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/AsyncIOServletTest.java [hunk 3]
```diff
@@ -398,6 +399,7 @@ public void onError(Throwable t)
     @ParameterizedTest
     @ArgumentsSource(TransportProvider.class)
     @Tag("Unstable")
+    @Disabled
```
Comment (lorban) [inline tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/AsyncIOServletTest.java:402]: Why disabled?

File: jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java (hunk 1 above)
Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: I think it is strange to have both replaceKey and to pass in the key to onSelected etc.
If you are passing in the key for the main usages, then findKey is probably OK for the remaining cases.
So get rid of one mechanism or the other.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java [hunk 4]
```diff
@@ -160,22 +145,132 @@ protected void doStop() throws Exception
         super.doStop();
     }
 
+    void compute(Selector selector, SelectableChannel channel, SelectionKey selectionKey, Consumer<SelectionKey> action)
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: `compute` is not really very meaningful

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-io/src/main/java/org/eclipse/jetty/io/SocketChannelEndPoint.java (hunk 2 above)
Comment (sbordet) [reply jetty-io/src/main/java/org/eclipse/jetty/io/SocketChannelEndPoint.java:28]: `ChannelEndPoint` becomes `SocketChannelEndPoint`, and `UnixEndPoint` extends `SocketChannelEndPoint`?
We may want to do this in 10, not in 9.4.

File: tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/AsyncIOServletTest.java (hunk 3 above)
Comment (sbordet) [reply tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/AsyncIOServletTest.java:402]: Because the test is unstable and fails for reasons unrelated to this change, but it was annoying that it failed randomly.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java (hunk 4 above)
Comment (sbordet) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: What then? It runs the `Consumer` given those parameters - similar to `Map.compute()`.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java [hunk 5]
```diff
@@ -357,12 +353,16 @@ public Runnable onSelected()
         return task;
     }
 
+    private void updateKey(Selector selector)
+    {
+        _selector.runKeyAction(selector, _channel, _key, this::updateKey);
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java]: you may as well return the key here:
```suggestion
        _key = _selector.runKeyAction(selector, _channel, _key, this::updateKey);
```

File: jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java [hunk 6]
```diff
@@ -94,14 +88,7 @@ public void close()
...
 
-    private final ManagedSelector.SelectorUpdate _updateKeyAction = new ManagedSelector.SelectorUpdate()
-    {
-        @Override
-        public void update(Selector selector)
-        {
-            updateKey();
-        }
-    };
+    private final ManagedSelector.SelectorUpdate _updateKeyAction = this::updateKey;
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java]: This is not used in `updateKey(Selector selector)`  or is it the other update key?   Eitherway, it is confusing, can we change one of the method names?

File: jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java [hunk 7]
```diff
@@ -357,12 +353,16 @@ public Runnable onSelected()
         return task;
     }
 
+    private void updateKey(Selector selector)
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java]: maybe call this one `updateKeyAction`

**Review by gregw — CHANGES_REQUESTED** [review]
almost....

File: jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java (hunk 6 above)
Comment (sbordet) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java]: I don't understand what's confusing? Like before the inner class was calling `Selectable.updateKey()`, now the method reference is eventually calling `Selectable.updateKey()` - so it's the same stuff and it's the same task of updating the key.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java (hunk 7 above)
Comment (sbordet) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java]: Not sure I agree. This method updates the key, it's not the action. The field is called `_updateKeyAction` because it's the action that it is submitted to the selector.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java (hunk 5 above)
Comment (sbordet) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java]: I don't think it's a good idea to return the key, since it's the `Consumer` that is supposed to act on the key so there is no point returning it to the caller.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java (hunk 6 above)
Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java]: there are two methods both called `updateKey`, both are used as method lambdas where you can't see the args without looking elsewhere.  One is set here as a field, the other is passed much later on.    Sorry, it is just confusing and even when I've worked it out, I keep getting reconfused.   Rename one of the methods.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java (hunk 7 above)
Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java]: So the updateKeyAction method is submitted to the selector, which calls us back here and then we call compute on the selector because our _key might be out of date....  All to avoid an array deref in `keyFor`  !!! I think we are getting too tricky.

The other callback pass the key, so we can just use it.  This callback passes the selector, so let's use use `keyFor` here and get rid of `_key` field.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java (hunk 5 above)
Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ChannelEndPoint.java]: let's get rid of the `_key` field (as above)

**Review by gregw — CHANGES_REQUESTED** [review]

**Review by gregw — APPROVED** [review]

**Comment by gregw** [comment]
@sbordet we still need to check benchmark against previous version
Also don't forget to simplify the SocketChannelEndPoint hierarchy in 10

**Review by lorban — APPROVED** [review]
