### PR TITLE
Fixing #9517 - bad url-pattern prefix match behavior

### LINKED ISSUE #9517: Jetty 10.0.14 uses wrong pathSpec for request
**Jetty version(s)**
10.0.14

**Java version/vendor** `(use: java -version)`
17

**OS type/version**
Doesn't matter

**Description**

Related to #9055

We have two servlets:
1) "/*"
2) "/foo/*"

Prior to Jetty 10.0.14, requests to "/foobar/something" were handled by servlet 1. After the upgrade, requests are unable to reach it. 

After debugging I found that problem was related to org.eclipse.jetty.http.pathmap.PathMappings#getMatched method:

```
        // path = "/foobar/something"

        MappedResource<E> prefix = _prefixMap.getBest(path); // ServletPathSpec@1c0d1eaa{/foo/*}

        if (prefix != null)
        {
            MatchedPath matchedPath = prefix.getPathSpec().matched(path);     // null, since found prefix doesn't match path
            if (matchedPath != null)
                return new MatchedResource<>(prefix.getResource(), prefix.getPathSpec(), matchedPath);
        }
```

### PR DESCRIPTION
**Pull request by joakime**
New testcase to ensure we don't have a regression on this behavior.
Restore a prefix matching loop that we previously had in Jetty 10.0.13

### CODE REVIEW

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java [hunk 1]
```diff
@@ -223,13 +230,13 @@ public MatchedResource<E> getMatched(String path)
             //  Loop 3: "foo"
             while ((i = path.indexOf('.', i + 1)) > 0)
             {
-                prefix = _suffixMap.get(path, i + 1, path.length() - i - 1);
-                if (prefix == null)
+                MappedResource<E> suffix = _suffixMap.get(path, i + 1, path.length() - i - 1);
```
Comment (joakime) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java:231]: Just renamed "prefix" here to "suffix" to be more clear about usage.

**Comment by gregw** [comment]
@joakime I pushed an update to the loop that uses the length of the last match to improve the search for a shorter match.  Much better than searching on every string length.

However, I don't like the magic number 3 (which is the "/*" minus 1 more), but I think it works.  Could perhaps have more testing of 1 char patterns?

Also there was another optimized prefix match that needs same fix.

**Review by gregw — DISMISSED** [review]

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java [hunk 2]
```diff
@@ -205,11 +205,13 @@ public MatchedResource<E> getMatched(String path)
 
         // Try a prefix match
         MappedResource<E> prefix = _prefixMap.getBest(path);
-        if (prefix != null)
+        while (prefix != null)
         {
             MatchedPath matchedPath = prefix.getPathSpec().matched(path);
             if (matchedPath != null)
                 return new MatchedResource<>(prefix.getResource(), prefix.getPathSpec(), matchedPath);
+            int specLength = prefix.getPathSpec().getSpecLength();
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java]: Put `prefix.getPathSpec()` in a local variable.

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java [hunk 3]
```diff
@@ -205,11 +205,13 @@ public MatchedResource<E> getMatched(String path)
...
+            prefix = specLength > 3 ? _prefixMap.getBest(path, 0, specLength - 3) : null;
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java]: What's the magic `3`?

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java [hunk 4]
```diff
@@ -286,12 +288,14 @@ private MatchedResource<E> getMatchedIteratively(String path)
...
+                            MappedResource<E> prefix = _prefixMap.getBest(path);
+                            while (prefix != null)
                             {
-                                matchedPath = candidate.getPathSpec().matched(path);
+                                matchedPath = prefix.getPathSpec().matched(path);
                                 if (matchedPath != null)
-                                    return new MatchedResource<>(candidate.getResource(), candidate.getPathSpec(), matchedPath);
+                                    return new MatchedResource<>(prefix.getResource(), prefix.getPathSpec(), matchedPath);
+                                int specLength = prefix.getPathSpec().getSpecLength();
+                                prefix = specLength > 3 ? _prefixMap.getBest(path, 0, specLength - 3) : null;
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java]: Magic `3`?

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java [hunk 5]
```diff
@@ -286,12 +288,14 @@ private MatchedResource<E> getMatchedIteratively(String path)
...
-                            if (candidate != null)
+                            MappedResource<E> prefix = _prefixMap.getBest(path);
+                            while (prefix != null)
                             {
-                                matchedPath = candidate.getPathSpec().matched(path);
+                                matchedPath = prefix.getPathSpec().matched(path);
                                 if (matchedPath != null)
-                                    return new MatchedResource<>(candidate.getResource(), candidate.getPathSpec(), matchedPath);
+                                    return new MatchedResource<>(prefix.getResource(), prefix.getPathSpec(), matchedPath);
+                                int specLength = prefix.getPathSpec().getSpecLength();
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/PathMappings.java]: Put `prefix.getPathSpec()` in a local variable.

File: jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java [hunk 6]
```diff
@@ -92,6 +92,42 @@ public void testServletMatchDefault()
...
+        p.put(new ServletPathSpec("/*"), "any");
+        p.put(new ServletPathSpec("/foo/*"), "foo");
+        p.put(new ServletPathSpec("/a/*"), "a");
+        p.put(new ServletPathSpec("/a/b/*"), "ab");
+
+        assertMatch(p, "/abs/path", "any");
+        assertMatch(p, "/abs/foo/bar", "any");
+        assertMatch(p, "/foo/bar", "foo");
+        assertMatch(p, "/", "any");
+        assertMatch(p, "/foobar", "any");
```
Comment (sbordet) [inline jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java:115]: Can you add here `/fo` and `/foob`?

File: jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java [hunk 7]
```diff
@@ -92,6 +92,42 @@ public void testServletMatchDefault()
...
+        assertMatch(p, "/a/", "a");
+        assertMatch(p, "/a", "a");
+
+        // Try now with order important
+        p.put(new RegexPathSpec("/other.*/"), "other");
+        assertMatch(p, "/abs/path", "any");
+        assertMatch(p, "/abs/foo/bar", "any");
+        assertMatch(p, "/foo/bar", "foo");
+        assertMatch(p, "/", "any");
+        assertMatch(p, "/foobar", "any");
```
Comment (sbordet) [inline jetty-http/src/test/java/org/eclipse/jetty/http/pathmap/PathMappingsTest.java:133]: Ditto

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]
