### PR TITLE
Fix buffer leaks in FCGI and H3 `HttpClientIdleTimeoutTest`

### LINKED ISSUE #10277: Review read failures impacting writes
**Jetty version(s)**
12

**Description**
Read failures should not impact writes (too much), as a write might still be possible even if the read failed.
Typical examples are early EOF in reads -- they should not impact writes.

The idea is that if a read failure is catastrophic, we would attempt the write anyway and will get the failure through the write, rather than assuming that the writes will fail.

Child issues / prs
 - [ ] #10431 
 - [ ] #10432

### PR DESCRIPTION
**Pull request by lorban**
`testClientIdleTimeout` and `testRequestIdleTimeout` leak a buffer because the handler's callback is never completed and they don't give the server a chance to reclaim its resources after idle timeout.

Note: the leak was only detected in FCGI because the client was not uploading any content. Adding some uploaded content uncovered an equivalent leak in H3.

See https://github.com/eclipse/jetty.project/issues/10226

### CODE REVIEW

**Review by joakime — DISMISSED** [review]
So this leak was entirely contained within the test case.
Interesting.
Wonder if we should document how to turn on Leak tracking in our developer guide?

**Comment by lorban** [comment]
> So this leak was entirely contained within the test case. Interesting. Wonder if we should document how to turn on Leak tracking in our developer guide?

I'm open to the idea, but the leak tracking buffer pool currently is rough on the edges, so I'm not keen on exposing it to end users as it currently is. @gregw had a similar suggestion here (https://github.com/eclipse/jetty.project/pull/10325#issuecomment-1695235810), and we agreed that, as it stands, the leak tracker has little value outside the scope of our tests.

**Comment by lorban** [comment]
This requires more investigation as other protocols manage to release their buffers despite the callback not being completed. We, at the very least, need to understand why not FCGI.

**Review by gregw — DISMISSED** [review]

**Review by sbordet — CHANGES_REQUESTED** [review]
Can we fix FCGI instead of just the test?

**Comment by lorban** [comment]
On hold until https://github.com/eclipse/jetty.project/issues/10277 is sorted.

**Comment by lorban** [comment]
@sbordet @gregw @joakime I've reworked these tests by using `Request.addFailureListener()` to detect when the server had a chance to reclaim its resources, identified and fixed the leak in FCGI and slightly improved the tests such as a similar leak became apparent in H3 which I also fixed.

This PR is finally ready for review.

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java [hunk 1]
```diff
@@ -222,8 +229,17 @@ void parseAndFill()
...
+                releaseInputBuffer();
+                break;
+            }
+            int filled = fillInputBuffer();
+            if (filled < 0)
+            {
+                releaseInputBuffer();
+                break;
+            }
+            if (filled == 0)
```
Comment (sbordet) [inline jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java]: You need to release also here.

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Stream.java [hunk 2]
```diff
@@ -372,6 +372,8 @@ public void onTrailer(HeadersFrame frame)
 
     public void onFailure(long error, Throwable failure)
     {
+        HTTP3StreamConnection connection = (HTTP3StreamConnection)endPoint.getConnection();
+        connection.onFailure(error, failure);
```
Comment (sbordet) [inline jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Stream.java]: Don't think it's the right place for this code.
Should all be in H3StreamConnection.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientIdleTimeoutTest.java [hunk 3]
```diff
@@ -35,25 +35,30 @@ public class HttpClientIdleTimeoutTest extends AbstractTest
 
     @ParameterizedTest
     @MethodSource("transports")
-    @Tag("DisableLeakTracking:server:FCGI")
     public void testClientIdleTimeout(Transport transport) throws Exception
     {
+        long serverIdleTimeout = idleTimeout * 3;
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientIdleTimeoutTest.java]: Is `* 2` enough?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientIdleTimeoutTest.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientIdleTimeoutTest.java]: Indeed, `* 2` is enough.

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java]: Yes, let me fix this.

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Stream.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Stream.java]: The problem is that `HTTP3StreamConnection` doesn't get notified in any way. But `HttpStreamOverHTTP3.onFailure()` does get called and looks like the right place to forward the failure to `HTTP3StreamConnection`.

Let me modify this.

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java [hunk 4]
```diff
@@ -214,17 +221,22 @@ void parseAndFill()
     {
         if (LOG.isDebugEnabled())
             LOG.debug("parseAndFill {}", this);
+        acquireInputBuffer();
```
Comment (gregw) [inline jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java:226]: Why is the input buffer not release when parse below returns true?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java:226]: You're right; the buffer could be released when empty and the parser returns true.

**Comment by gregw** [comment]
@lorban the OSGI CI failures look like hard failures. @janbartel any ideas to help out?

**Comment by janbartel** [comment]
@gregw @lorban there is a new osgi test that has been added which is failing in this branch. It seems like the new test class is there, but the new xml file that should be present in the jar is not there? Could this be a build cache issue? @olamy ?

**Comment by olamy** [comment]
I can't see any more issues after rebasing from `jetty-12` branch

**Comment by lorban** [comment]
@sbordet nudge

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java [hunk 5]
```diff
@@ -178,8 +180,12 @@ public void onFillable()
                     LOG.debug("Read {} bytes from {} {}", read, getEndPoint(), this);
                 if (read > 0)
                 {
+                    // The networkBuffer cannot be released immediately after parse()
+                    // even if the buffer has been fully consumed because releaseInputBuffer()
+                    // must be called as the last release for it to be able to null out the
+                    // networkBuffer field exactly when the latter isn't used anymore.
                     if (parse(networkBuffer.getByteBuffer()))
-                        return;
+                        break;
```
Comment (gregw) [inline jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java]: Is there any difference between `break` and `return` here?   or is this just a style thing?

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java [hunk 6]
```diff
@@ -214,17 +225,26 @@ void parseAndFill()
...
         // See also HttpConnection.parseAndFillForContent().
         while (stream != null)
         {
+            // The networkBuffer cannot be released immediately after parse()
+            // even if the buffer has been fully consumed because releaseInputBuffer()
+            // must be called as the last release for it to be able to null out the
+            // networkBuffer field exactly when the latter isn't used anymore.
             if (parse(networkBuffer.getByteBuffer()))
-                return;
+                break;
```
Comment (gregw) [inline jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java]: again, no difference between `break` and `return` here, so I kind of prefer `return` as I don't need to scroll down to see what happens next

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3StreamConnection.java [hunk 7]
```diff
@@ -56,6 +56,15 @@ public HTTP3StreamConnection(QuicStreamEndPoint endPoint, Executor executor, Byt
         parser.init(MessageListener::new);
     }
 
+    public void onFailure(Throwable failure)
+    {
+        if (networkBuffer != null)
+        {
+            networkBuffer.release();
+            networkBuffer = null;
+        }
```
Comment (gregw) [inline jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3StreamConnection.java]:
```suggestion
        releaseInputBuffer();
```

Can you also either change the name of that method or of the field, so they are either both `network` or both `input`.

**Review by gregw — CHANGES_REQUESTED** [review]
a few niggles

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3StreamConnection.java (hunk 7 above)
Comment (lorban) [reply jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3StreamConnection.java]: You're right, this buffer should be called `inputBuffer` and the related methods named likewise. Let me clean this.

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java (hunk 6 above)
Comment (lorban) [reply jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java]: Same as above: for style, so I'll change `break` for `return`.

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java]: It's for style: there isn't any difference between `break` and `return` here. I just aligned this code with what the other branches were doing.

But If you prefer `return`, I'll change them all to use `return` instead of `break`.

**Review by sbordet — DISMISSED** [review]

**Review by sbordet — APPROVED** [review]

**Review by gregw — APPROVED** [review]
