### PR TITLE
Issue #13144 - Cross context dispatch in ee9/ee8 breaks AsyncContext.dispatch

### LINKED ISSUE #13144: Cross Context Dispatch with Async does not honor context
**Jetty version(s)**
12.0.21

**Jetty Environment**
ee9 / ee8 (but could be present in others too)

**Description**
When a cross-context dispatch occurs, and the dispatched to endpoint uses an `AsyncContext.dispatch()`, then the resulting dispatch has the wrong state, and dispatches to the previous context.

Example:

We have 2 contexts involved.

1. Context root `/`
    - has a Filter that performs cross-context-dispatch.
2. Context service `/service`
    - has an Servlet `/alt/*` that uses AsyncContext and performs a dispatch()

The order of events.

1. Context root `/` receives a request.
2. The filter on Context root `/` gets a ServletContext from `/service`
3. The filter gets a RequestDispatcher from `/service` to a path /service/alt/` context.
4. The filter performs a `RequestDispatcher.forward()` to this `/service` endpoint
5. The `/service/alt/*` servlet receives the FORWARD request.
6. The `/service/alt/*` servlet establishes an AsyncContext, waits for a timeout, and then performs a `dispatch()`
7. (Where problem occurs) - this dispatch goes to the root `/` context.

There are two problems observed (could be more).

First in the `jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Dispatcher.java` 

The call to `protected void forward(ServletRequest request, ServletResponse response, DispatcherType dispatch) throws ServletException, IOException` has a _finally_ block that resets several Request settings, like the `HttpURI`, this results in bad `HttpServletRequest.getRequestURL` on the dispatch.

Next is the `jetty-ee9/jetty-ee9-servlet/src/main/java/org/eclipse/jetty/ee9/servlet/ServletHandler.java`

In the call to `public void doScope(String target, Request baseRequest, HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException`, there is a finally block that resets the old scope using `baseRequest.setUserIdentityScope(oldScope)`, this sets the Context back to the original context, which results in the `AsyncContext.dispatch()` calling the original context, not the dispatched to context, like what is expected (and how the behavior works in Jetty 11/10/9).

### PR DESCRIPTION
**Pull request by joakime**
The reset of the request, and the reset of the context, is too aggressive when dealing with `AsyncContext.dispatch()` behaviors.

See issue for details on where the resets occur.

Closes: #13144

### CODE REVIEW

**Comment by janbartel** [comment]
Looking into it. I ported your tested to `ee10`. Also fails there, but for a different reason.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContextEvent.java [hunk 1]
```diff
@@ -42,8 +42,11 @@ public AsyncContextEvent(ServletContextHandler.ServletScopedContext context, Asy
         _asyncContext = asyncContext;
         _servletContext = ServletContextHandler.getServletContext(context);
         _state = state;
-        // TODO better than this:
-        _baseURI = request == null ? null : (request instanceof HttpServletRequest hr) ? HttpURI.from(hr.getRequestURI()) : null;
+
+        if (request instanceof HttpServletRequest hr)
+            _baseURI = HttpURI.build(hr.getRequestURI()).query(hr.getQueryString());
+        else
+            _baseURI = null;
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContextEvent.java]: absolute niggle (but do the rename at least)
```suggestion
        _baseURI =  (request instanceof HttpServletRequest hsr) ? HttpURI.build(hsr.getRequestURI()).query(hsr.getQueryString()) : null;
```

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcher.java [hunk 2]
```diff
@@ -152,9 +152,26 @@ public IncludeResponse(Request coreRequest, HttpServletResponse httpServletRespo
         }
     }
 
+    private class AsyncRequest extends ServletCoreRequest
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcher.java:155]: I think we should add some javadoc even to these private classes so we can remember exactly when/why they are used.  Just a simple one liner will do

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcher.java [hunk 3]
```diff
@@ -152,9 +152,26 @@ public IncludeResponse(Request coreRequest, HttpServletResponse httpServletRespo
...
+    {
+        private final HttpURI _fullyQualifiedURI;
+
+        public AsyncRequest(HttpServletRequest httpServletRequest)
+        {
+            super(httpServletRequest, new ServletAttributes(httpServletRequest));
+            _fullyQualifiedURI = HttpURI.build(httpServletRequest.getRequestURL().toString()).pathQuery(_uri.getPathQuery()).asImmutable();
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcher.java:162]: We don't need to say "fully qualified" for a URI, as they should always be so.
It is only paths that might be "InContext" and encode or decoded.

So either this, or _uri is badly named.

I think _uri is not correct, as it never has scheme nor authority.   It should be just `String _pathQuery` or perhaps `String _encodedPathQuery`

This field here can then either be `_uri` or `_httpURI` as it is the scheme and authority of the actual request merged with the `_encodedPathQuery` of the `CrossContextDispatcher` 

Ahhhh Async Dispatch is different from a normal CrossContextDispatch in that the request scheme and authority will never be different in the source vs target.     In a normal cross context dispatch, the RequestDispatcher is created in isolation from the current request (it may even be obtained long before the current request), so we much mix in the scheme and authority of the current request to get a URI.     But with async dispatch,  it can only happen within the lifecycle of a single real request, so the scheme and authority will never be different.

So do we model that differently?   Or do we just say that all dispatchers have only a pathQuery and that the URI is created only once a dispatcher is combined with a real request?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcher.java [hunk 4]
```diff
@@ -217,6 +234,23 @@ public HttpURI getHttpURI()
         _decodedPathInContext = decodedPathInContext;
     }
 
+    public void async(ServletRequest servletRequest, ServletResponse response) throws ServletException, IOException
+    {
+        HttpServletRequest httpServletRequest = (servletRequest instanceof HttpServletRequest) ? ((HttpServletRequest)servletRequest) : new ServletRequestHttpWrapper(servletRequest);
+        HttpServletResponse httpResponse = (response instanceof HttpServletResponse) ? (HttpServletResponse)response : new ServletResponseHttpWrapper(response);
+
+        AsyncRequest asyncRequest = new AsyncRequest(httpServletRequest);
+        try (Blocker.Callback callback = Blocker.callback())
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcher.java:244]: We should add a comment here like:
```java
        // We must block when do a cross context async dispatch, as we cannot combine the state machines of the servletChannel from the source context and that of the target 
```

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java [hunk 5]
```diff
@@ -753,6 +754,36 @@ public Enumeration<String> getAttributeNames()
...
             return Collections.enumeration(names);
         }
+
+        /**
+         * Get the parameters merged from the wrapped request, and the dispatch URI.
+         * If the dispatch URI is the same as the URI of the wrapped request, then
+         * we do not want to re-extract the query string, as the wrapped request will
+         * have already done the extraction.
+         * @return the request parameters
+         */
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/Dispatcher.java]: Nice comment, but a couple of tweaks:
```suggestion
        /**
         * Get the parameters merged from the request wrapped by this {@code AsyncRequest}
         * and those in the {@code RequestDispatcher}.
         * If the target path is the same as the request path, then
         * we do not want to re-extract the query string, as the wrapped request will
         * have already done the extraction.
         * @return the request parameters
         */
```

Also a comment on the `AsyncRequest` class itself would be good

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java [hunk 6]
```diff
@@ -826,50 +830,138 @@ private void dispatch() throws Exception
...
-            dispatcher.async(asyncContextEvent.getSuppliedRequest(), asyncContextEvent.getSuppliedResponse());
         }
         finally
         {
-            servletContextHandler.requestDestroyed(servletContextRequest, servletApiRequest);
+            targetContextHandler.requestDestroyed(servletContextRequest, servletApiRequest);
+        }
+    }
+
+    private void dispatchCrossContextAsync(CrossContextServletContext crossContextServletContext) throws ServletException, IOException
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java:914]: a bit of overview javadoc would be appreciated

**Review by gregw — CHANGES_REQUESTED** [review]
Just some initial thoughts, mostly on naming whilst I get my head into this

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcher.java (hunk 3 above)
Comment (janbartel) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextDispatcher.java:162]: Agreed to consider this in a different pull request.

**Review by gregw — APPROVED** [review]
OK if it builds, but lets start another PR to do a big cleanup

**Comment by joakime** [comment]
Now that this is green, I'm going to merge this today. (and merge it up to 12.1.x)
