### PR TITLE
Fix `EncoderSink` double release

### LINKED ISSUE #13679: org.eclipse.jetty.compression.gzip.internal.GzipEncoderSink.release: already released oeji.Retainable$ReferenceCounter@4e5e3238[rc=0]
**Jetty version(s)**
12.1.2

**Jetty Environment**
ee11

**HTTP version**
2.0 H2C

**Java version/vendor** `(use: java -version)`

25.0.0

**OS type/version**

MacOS

**Description**

```
2025-10-09T02:47:45.989-0600	ERROR	statement-response-25	org.glassfish.jersey.server.ServerRuntime$Responder	Error while closing the output stream in order to commit response.
java.lang.IllegalStateException: already released oeji.Retainable$ReferenceCounter@4e5e3238[rc=0]
	at org.eclipse.jetty.io.Retainable$ReferenceCounter.lambda$release$0(Retainable.java:228)
	at java.base/java.util.concurrent.atomic.AtomicInteger.updateAndGet(AtomicInteger.java:282)
	at org.eclipse.jetty.io.Retainable$ReferenceCounter.release(Retainable.java:225)
	at org.eclipse.jetty.io.Retainable$Wrapper.release(Retainable.java:151)
	at org.eclipse.jetty.io.ArrayByteBufferPool$PooledBuffer.release(ArrayByteBufferPool.java:769)
	at org.eclipse.jetty.compression.gzip.internal.GzipEncoderSink.release(GzipEncoderSink.java:206)
	at org.eclipse.jetty.compression.EncoderSink$EncodeBufferCallback.onCompleteFailure(EncoderSink.java:123)
	at org.eclipse.jetty.util.IteratingCallback.onCompleted(IteratingCallback.java:266)
	at org.eclipse.jetty.util.ExceptionUtil.callAndThen(ExceptionUtil.java:430)
	at org.eclipse.jetty.util.IteratingCallback.doOnFailureOnCompleted(IteratingCallback.java:286)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:503)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:354)
	at org.eclipse.jetty.compression.EncoderSink.write(EncoderSink.java:39)
	at org.eclipse.jetty.compression.server.internal.CompressionResponse.write(CompressionResponse.java:143)
	at org.eclipse.jetty.compression.server.internal.CompressionResponse.write(CompressionResponse.java:141)
	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:836)
	at org.eclipse.jetty.server.handler.ContextResponse.write(ContextResponse.java:56)
	at org.eclipse.jetty.ee11.servlet.ServletContextResponse.write(ServletContextResponse.java:225)
	at org.eclipse.jetty.ee11.servlet.HttpOutput.channelWrite(HttpOutput.java:248)
	at org.eclipse.jetty.ee11.servlet.HttpOutput.channelWrite(HttpOutput.java:233)
	at org.eclipse.jetty.ee11.servlet.HttpOutput.write(HttpOutput.java:929)
	at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:302)
	at java.base/java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:163)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:286)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:235)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:250)
	at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:569)
	at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:406)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:763)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:398)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:388)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:926)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:963)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:914)
	at io.airlift.jaxrs.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:99)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:79)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)

```

**How to reproduce?**

### PR DESCRIPTION
**Pull request by lorban**
When `EncoderSink` (any of its subclasses) fails to do the last write to the wrapped sink, `release()` is called twice: once from the callback wrapper that calls `finished()` plus once from `onCompleteFailure()`.

Moving the releasing responsibility from `EncodeBufferCallback` to `EncoderSink` to make the responsibilities more obvious.

Fixes #13679

### CODE REVIEW

**Comment by wendigo** [comment]
Running tests now.

File: jetty-core/jetty-compression/jetty-compression-common/src/main/java/org/eclipse/jetty/compression/EncoderSink.java [hunk 1]
```diff
@@ -104,7 +104,7 @@ private void write(WriteRecord writeRecord)
             if (writeRecord.last)
             {
                 state.set(State.FINISHING);
-                callback = Callback.combine(Callback.from(this::finished), callback);
+                callback = Callback.combine(Callback.from(callback.getInvocationType(), this::finished), callback);
```
Comment (sbordet) [inline jetty-core/jetty-compression/jetty-compression-common/src/main/java/org/eclipse/jetty/compression/EncoderSink.java]:
```suggestion
                callback = Callback.from(this::finished, callback);
```

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-compression/jetty-compression-common/src/main/java/org/eclipse/jetty/compression/EncoderSink.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-compression/jetty-compression-common/src/main/java/org/eclipse/jetty/compression/EncoderSink.java]: Done.

**Review by sbordet — DISMISSED** [review]

**Review by sbordet — DISMISSED** [review]

**Review by joakime — DISMISSED** [review]

**Comment by wendigo** [comment]
Unfortunately it still fails with:

```
java.lang.IllegalStateException: already released oeji.Retainable$ReferenceCounter@3a86af84[rc=0]
	at org.eclipse.jetty.io.Retainable$ReferenceCounter.lambda$release$0(Retainable.java:228)
	at java.base/java.util.concurrent.atomic.AtomicInteger.updateAndGet(AtomicInteger.java:281)
	at org.eclipse.jetty.io.Retainable$ReferenceCounter.release(Retainable.java:225)
	at org.eclipse.jetty.io.Retainable$Wrapper.release(Retainable.java:151)
	at org.eclipse.jetty.io.ArrayByteBufferPool$PooledBuffer.release(ArrayByteBufferPool.java:769)
	at org.eclipse.jetty.compression.gzip.internal.GzipEncoderSink.release(GzipEncoderSink.java:207)
	at org.eclipse.jetty.compression.EncoderSink$EncodeBufferCallback.onSuccess(EncoderSink.java:122)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:489)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:354)
	at org.eclipse.jetty.compression.EncoderSink.write(EncoderSink.java:39)
	at org.eclipse.jetty.compression.server.internal.CompressionResponse.write(CompressionResponse.java:143)
	at org.eclipse.jetty.compression.server.internal.CompressionResponse.write(CompressionResponse.java:141)
	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:836)
	at org.eclipse.jetty.server.handler.ContextResponse.write(ContextResponse.java:56)
	at org.eclipse.jetty.ee11.servlet.ServletContextResponse.write(ServletContextResponse.java:225)
	at org.eclipse.jetty.ee11.servlet.HttpOutput.channelWrite(HttpOutput.java:248)
	at org.eclipse.jetty.ee11.servlet.HttpOutput.channelWrite(HttpOutput.java:233)
	at org.eclipse.jetty.ee11.servlet.HttpOutput.write(HttpOutput.java:929)
	at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:302)
	at java.base/java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:163)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:286)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:235)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:250)
	at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:569)
	at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:406)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:763)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:398)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:388)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
```

**Comment by wendigo** [comment]
Actually it's even worse, it fails almost every time:

```
+ echo 'testing/trino-test-jdbc-compatibility-old-driver/bin/run_tests.sh: exiting with 1, failed versions: "352' 369 386 403 420 437 454 '471"'
```

**Review by sbordet — DISMISSED** [review]

**Comment by lorban** [comment]
@wendigo I've updated the fix to take into account other failures. Could you please retry your test?

**Comment by wendigo** [comment]
@lorban uploading locally staged artifacts to r2 now

**Comment by wendigo** [comment]
@lorban I have a problem testing a snapshot in our CI environment. Lack of published snapshots make it really hard to do it. Bare with me, it will take some time

**Comment by wendigo** [comment]
Running tests now, I'll get back to you in ~20 min :)

**Comment by wendigo** [comment]
It passed our testing without a single issue. LGTM

**Review by sbordet — APPROVED** [review]
