### PR TITLE
Issue #5069 - Fixing assumeConnectTimeout test condition

### LINKED ISSUE #5069: HttpClientTimeoutTests can occasionally fail due to unreachable network
**Jetty version**
9.4.x

**Java version**
11.0.7+

**OS type/version**
Linux

**Description**
The tests that utilize the IP 10.255.255.1 can sometimes result in an unexpected `java.net.SocketException: Network is unreachable (connect failed)` when the test is attempting to test for connect timeouts.

```
org.eclipse.jetty.http.client.HttpClientTimeoutTest.testConnectTimeoutIsCancelledByShorterRequestTimeout(Transport)[3]  Time elapsed: 0.006 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
	at org.eclipse.jetty.http.client.HttpClientTimeoutTest.assumeConnectTimeout(HttpClientTimeoutTest.java:523)
	at org.eclipse.jetty.http.client.HttpClientTimeoutTest.testConnectTimeoutIsCancelledByShorterRequestTimeout(HttpClientTimeoutTest.java:345)
Caused by: java.net.SocketException: Network is unreachable (connect failed)
	at org.eclipse.jetty.http.client.HttpClientTimeoutTest.assumeConnectTimeout(HttpClientTimeoutTest.java:511)
	at org.eclipse.jetty.http.client.HttpClientTimeoutTest.testConnectTimeoutIsCancelledByShorterRequestTimeout(HttpClientTimeoutTest.java:345)
```

The method `HttpClientTimeoutTest.assumeConnectTimeout()` should be updated to handle this situation.

https://github.com/eclipse/jetty.project/blob/65de149f84b68e23fb2a2a849e80b06850c8cd29/tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTimeoutTest.java#L503-L525

### PR DESCRIPTION
**Pull request by joakime**
Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

File: tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTimeoutTest.java [hunk 1]
```diff
@@ -520,7 +521,7 @@ private void assumeConnectTimeout(String host, int port, int connectTimeout)
         catch (Throwable x)
         {
             // Abort if any other exception happens.
-            fail(x);
+            throw new TestAbortedException("Not able to validate connect timeout conditions", x);
```
Comment (sbordet) [inline tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTimeoutTest.java:524]: Please use `Assumptions` instead of throwing directly - it's not clear if you want the test to fail or what.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTimeoutTest.java (hunk 1 above)
Comment (joakime) [reply tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTimeoutTest.java:524]: The test will abort, not fail.

Using `Assumptions` makes the test either continue or abort, never fail.
Abort marks the test as ignored.

Using `TestAbortedException` preserves the stacktrace, which is then reported when a test is aborted. (this information is even present in your IDE)
Using `Assumptions` loses this stacktrace.

Comment (joakime) [reply tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTimeoutTest.java:524]: We do a similar thing in the AllowSymLinkAliasCheckerTest.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/test/java/org/eclipse/jetty/server/handler/AllowSymLinkAliasCheckerTest.java

Comment (sbordet) [reply tests/test-http-client-transport/src/test/java/org/eclipse/jetty/http/client/HttpClientTimeoutTest.java:524]: Bleah!

**Review by sbordet — APPROVED** [review]
