### PR TITLE
Issue #13670 - Returning ISE in all getParameter use cases outlined by Servlet 6.1 spec

### LINKED ISSUE #13670: jetty-ee11-servlet getParameter does not throw IllegalStateException
**Jetty version(s)**

12.1.1

**Jetty Environment**

ee11

**HTTP version**

HTTP 1.1

**Java version/vendor** `(use: java -version)`
```
openjdk version "21.0.8" 2025-07-15 LTS
OpenJDK Runtime Environment Corretto-21.0.8.9.1 (build 21.0.8+9-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.8.9.1 (build 21.0.8+9-LTS, mixed mode, sharing)
```

**OS type/version**
Linux

**Description**

`getParameter` documents `@throws IllegalStateException` for invalid parameters, but Jetty throws `BadMessageException`, which does not extend `IllegalStateException`.  It seems like Jetty should throw `IllegalStateException` by default, possibly with an option to restore the current behavior in case there is code dependent on the current exception hierarchy.

I found #11818 looking through issues, but it has no mention of `IllegalStateException`.

**How to reproduce?**
Make a request with `?x=%80`, wrap `getParameter` in a `try`/`catch`, and expect to do custom handling (for example, send a custom JSON payload).
```
try {
  req.getParameter("x");
} catch (IllegalStateException e) {
  // custom handling
}
```

### PR DESCRIPTION
**Pull request by gregw**
Fixes #13670 as an alternate to #13678

Use the existing HttpException mechanism. Perhaps BadMessageException could  be deprecated.
Prefer HttpException.IllegalStateException over BadMessageException, to not generate the wrong exception type in the first place.

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/BadMessageException.java [hunk 1]
```diff
@@ -15,8 +15,9 @@
 
 /**
  * <p>Exception thrown to indicate a Bad HTTP Message has either been received
- * or attempted to be generated.  Typically these are handled with either 400
+ * or attempted to be generated.  Typically, these are handled with either 400
```
Comment (janbartel) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/BadMessageException.java]: `Either` doesn't make sense here unless another way of handling them other than a `400` response is listed.

Comment (janbartel) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/BadMessageException.java]: Also, is now the only reason to keep this class is ee < 11 ?

**Review by janbartel — DISMISSED** [review]
Looks good, niggle about the javadoc as per comment.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/BadMessageException.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/BadMessageException.java]: Now bigger than Ben Hur!

**Comment by gregw** [comment]
@lachlan-roberts @joakime @janbartel review please

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/BadMessageException.java [hunk 2]
```diff
@@ -15,9 +15,11 @@
 
 /**
  * <p>Exception thrown to indicate a Bad HTTP Message has either been received
- * or attempted to be generated.  Typically these are handled with either 400
+ * or attempted to be generated.  Typically, these are handled with {@code 4xx} or {@code 5xx}
  * responses.</p>
+ * @deprecated use HttpException
```
Comment (lachlan-roberts) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/BadMessageException.java]: Can you use a `{@link}` tag here.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java [hunk 3]
```diff
@@ -2079,13 +2080,10 @@ private Collection<Part> getParts(Fields params) throws IOException
...
             }
-            catch (BadMessageException e)
-            {
-                throw e;
-            }
             // Catch RuntimeException to handle IllegalStateException, IllegalArgumentException, CharacterEncodingException, etc .. (long list)
             catch (RuntimeException | IOException e)
             {
+                HttpException.throwIfHttpException(e);
                 throw new BadMessageException("Unable to parse form content", e);
```
Comment (lachlan-roberts) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java:2087]: Should we not use `HttpException` here and other places in this class? or we specifically don't because it is EE9?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java [hunk 4]
```diff
@@ -1103,8 +1103,8 @@ else if (MimeTypes.Type.MULTIPART_FORM_DATA.is(baseType) &&
                         catch (ServletException e)
                         {
                             Throwable cause = e.getCause();
-                            if (cause instanceof BadMessageException badMessageException)
-                                throw badMessageException;
+                            if (cause instanceof HttpException httpException)
+                                HttpException.throwAsUnchecked(httpException);
```
Comment (lachlan-roberts) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java:1107]: `BadMessageException` is still thrown from various places so are you sure we don't need this check still for `BadMessageException` as well?

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java [hunk 5]
```diff
@@ -1131,12 +1130,14 @@ else if (MimeTypes.Type.MULTIPART_FORM_DATA.is(baseType) &&
...
-                throw new BadMessageException("Unable to parse form content", e);
+                _contentParameters = ServletContextRequest.BAD_PARAMS;
+                HttpException.throwIfHttpException(e);
+                throw new HttpException.IllegalStateException(HttpStatus.BAD_REQUEST_400, "Unable to parse form content", e);
             }
         }
     }
 
-    protected void extractQueryParameters() throws BadMessageException
+    protected void extractQueryParameters() throws HttpException.IllegalStateException
```
Comment (lachlan-roberts) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java:1140]: This could be considered a breaking change if someone has overriden this method.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannel.java [hunk 6]
```diff
@@ -687,7 +687,7 @@ protected void handleException(Throwable failure)
     {
         // Unwrap wrapping Jetty and Servlet exceptions.
         Throwable quiet = unwrap(failure, QuietException.class);
-        Throwable noStack = unwrap(failure, BadMessageException.class, IOException.class, TimeoutException.class);
+        Throwable noStack = unwrap(failure, HttpException.class, IOException.class, TimeoutException.class);
```
Comment (lachlan-roberts) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannel.java:690]: Since both BadMessageException and HttpException are currently used in various places should this include both?

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2CServerConnectionFactory.java [hunk 7]
```diff
@@ -67,7 +67,7 @@ public boolean isAcceptable(String protocol, String tlsProtocol, String tlsCiphe
     }
 
     @Override
-    public Connection upgradeConnection(Connector connector, EndPoint endPoint, Request request, HttpFields.Mutable response101) throws BadMessageException
+    public Connection upgradeConnection(Connector connector, EndPoint endPoint, Request request, HttpFields.Mutable response101) throws HttpException.RuntimeException
```
Comment (lachlan-roberts) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2CServerConnectionFactory.java:70]: This is also changing public API so is considered a breaking change.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionFactory.java [hunk 8]
```diff
@@ -76,9 +77,9 @@ public interface Upgrading extends ConnectionFactory
          * @param responseFields The fields to be sent with the 101 response
          * @return Null to indicate that request processing should continue normally without upgrading. A new connection instance to
          * indicate that the upgrade should proceed.
-         * @throws BadMessageException Thrown to indicate the upgrade attempt was illegal and that a bad message response should be sent.
+         * @throws HttpException.RuntimeException Thrown to indicate the upgrade attempt was illegal and that a bad message response should be sent.
          */
-        public Connection upgradeConnection(Connector connector, EndPoint endPoint, MetaData.Request upgradeRequest, HttpFields.Mutable responseFields) throws BadMessageException;
+        Connection upgradeConnection(Connector connector, EndPoint endPoint, MetaData.Request upgradeRequest, HttpFields.Mutable responseFields) throws QuietException.RuntimeException;
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionFactory.java]: Public API change.

**Review by lachlan-roberts — CHANGES_REQUESTED** [review]
I think this should also review the remaining usages of BadMessageException since it is deprecated for removal.

And also noting there are some changes to public APIs which can be considered breaking changes in a dot release.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java (hunk 3 above)
Comment (gregw) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java:2087]: This PR is not changing EE9 nor EE10

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java (hunk 4 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java:1107]: EE10

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java (hunk 5 above)
Comment (gregw) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java:1140]: These are both unchecked exceptions.... and the whole point of this PR is the correct the API to throw ISE instead of just a RTE

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannel.java (hunk 6 above)
Comment (gregw) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannel.java:690]: EE11 should be HttpException only

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2CServerConnectionFactory.java (hunk 7 above)
Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2CServerConnectionFactory.java:70]: ditto

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionFactory.java (hunk 8 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionFactory.java]: ditto

**Review by joakime — DISMISSED** [review]

**Review by lachlan-roberts — DISMISSED** [review]

**Review by sbordet — APPROVED** [review]
