### PR TITLE
Fixes #4542 Root pathspec mapping pathInfo

### LINKED ISSUE #4542: servlet context root mapping incorrect
As per the testing in https://github.com/eclipse-ee4j/servlet-api/issues/300 we are incorrectly setting the pathInfo for context root matched requests

### PR DESCRIPTION
**Pull request by gregw**
#4542 
For the "" root pathspec, the pathinfo should always be the full path and the matched path is ""

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/ServletPathSpec.java [hunk 1]
```diff
@@ -168,52 +168,47 @@ else if (servletPathSpec.startsWith("*."))
     public String getPathInfo(String path)
     {
         // Path Info only valid for PREFIX_GLOB types
```
Comment (janbartel) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/ServletPathSpec.java]: That comment isn't true now, is it?

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/ServletPathSpec.java [hunk 2]
```diff
@@ -168,52 +168,47 @@ else if (servletPathSpec.startsWith("*."))
...
-        if (group == PathSpecGroup.PREFIX_GLOB)
+        switch (group)
         {
-            if (path.length() == (specLength - 2))
-            {
+            case ROOT:
```
Comment (janbartel) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/ServletPathSpec.java:172]: This comment should really go on the PathSpecGroup class, but as it isn't part of the PR I'm putting this comment here instead.

The comments at PathSpecGroup class line 38-42 need fixing I think as they don't contain enough explanation and have contradictory values.

**Review by janbartel — APPROVED** [review]
LGTM if you do something with the 2 comments I've made.
