### PR TITLE
Fixes #4113 - HttpClient fails with JDK 13 and TLS 1.3.

### LINKED ISSUE #4113: HttpClient fails with JDK 13 and TLS 1.3
JDK 13 is now sending a TLS 1.3 `NewSessionTicket` message after an HTTP request/response exchange.

This causes `HttpConnectionOverHTTP` to close the connection, since there is no exchange and it is assumed that if there are bytes in between HTTP requests they are either garbage of a server close.

### PR DESCRIPTION
**Pull request by sbordet**
1. Now forwarding the fillable event rather than assuming that is due
to garbage bytes or by a server close. This ensures that a HTTP read
consumes the TLS bytes and the `NewSessionTicket` message.
2. Avoid to set the `SslConnection` onto the `EndPoint` in
`SslClientConnectionFactory` - this allows upgrades to work properly,
for example when tunnelling through a secure proxy.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslClientConnectionFactory.java [hunk 1]
```diff
@@ -97,7 +97,6 @@ public void setAllowMissingCloseMessage(boolean allowMissingCloseMessage)
         context.put(SSL_ENGINE_CONTEXT_KEY, engine);
 
         SslConnection sslConnection = newSslConnection(byteBufferPool, executor, endPoint, engine);
-        endPoint.setConnection(sslConnection);
```
Comment (joakime) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslClientConnectionFactory.java]: Is this right?
It looks like a bug to remove this line.
