### PR TITLE
Fixes #10482 - RewriteHandler with multiple HeaderPatternRules.

### LINKED ISSUE #10482: RewriteHandler with multiple HeaderPatternRules
**Jetty Version**
12.0.1

**Jetty Environment**
core, ee8

**Java Version**
17.0.8

**Question**
I added some HeaderPatternRules to a RewriteHandler, but only the last rule applies. What I am doing wrong? I assumed that all matching rules will apply...

```
private static final HeaderPatternRule CONTENT_TYPE_OPTIONS = new HeaderPatternRule("*", "X-Content-Type-Options", "nosniff");
private static final HeaderPatternRule XSS_PROTECTION = new HeaderPatternRule("*", "X-XSS-Protection", "0");
private static final HeaderPatternRule PERMISSION_POLICY = new HeaderPatternRule("*", "Permissions-Policy", "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), " +
            "camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), " +
            "execution-while-out-of-viewport=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), " +
            "midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()");
private static final HeaderPatternRule REFERRER_POLICY = new HeaderPatternRule("*", "Referrer-Policy", "no-referrer");

RewriteHandler rh = new RewriteHandler();

rh.addRule(REFERRER_POLICY);
rh.addRule(PERMISSION_POLICY);

rh.addRule(XSS_PROTECTION);
rh.addRule(CONTENT_TYPE_OPTIONS);
```

### PR DESCRIPTION
**Pull request by sbordet**
Reviewed the implementation of RewriteHandler, that was broken for those rules that were overriding `Rule.Handler.handle()`.

The problem was that the handling was not forwarded along the chain of rules, so only the last one was applied.

Removed (a breaking change) `Rule.Handler.handle(Response, Callback)` because it is necessary that the outermost request wrapper is passed to the `RewriteHandler` child `Handler`. Updated implementations to override `handle(Request, Response, Callback)` instead, so that the request parameter is preserved along the chain.

### CODE REVIEW

**Comment by gregw** [comment]
@sbordet As per our call, I don't like that each `Rule.Handler` is-a `Request` and is passed a `Request` in `handle`.

I think we removed the request parameter to avoid that.   Consider the following example to how I imagine it was meant to be working.

 + We have a structure of  `Server -> RewriteHandler -> MyAppHandler`
 + The `RewriteHandler` has 3 rules A, B & C, all of which modify the request in some way by wrapping it.
 + Ultimately that means that `MyAppHandler` should be called with a request that is `c{b{a{request}}}`
 + But each rule also produces creates a `Rule.Handler` instance and those handlers should be invoked in order: `a->b->c->MyAppHandler`
 + Moreover, each `Rule.Handler` should see the request at the appropriate level of wrapping, thus the execution order should be:
    1. `A.handle(request, response, callback)`
    2. `B.handle(a{request}, response, callback)`
    3. `C.handle(b{a{request}}, response, callback)`
    4. `MyAppHandler.handle(c{b{a{request}}}, response, callback)`

The order of the invocation of the handlers could be important.   Let's say that all the handle methods of all the rules did a `response.getHeaders().put("X-Ruled", someSpecialValue)`, then once we get to `MyAppHandler`, the value of that header should be the value that C set, as it overwrote B, which overwrite A.

Moreover, each Rule.Handler should see the request only at the level of wrapping that was applied at the time it was matched.    Consider if rule `A.handle` did `response.getHeaders().put("X-A-cause", request.getHttpURI())`, then it needs to see the request as only `a{request}` so it gets the correct URI.  If it sees `c{b{a{request}}}`, then it will set the wrong URI.

So I think that each `Rule.Handle` should have a final `handle` method that does something like:
```java
    public final boolean handle(Request request, Response response, Callback callback)
    {
        Request wrapped = getWrapped();
        assert wrapped.getRequest() == request;

        return doHandle(wrapped, response, callback);
    }

    // Override this method to handle the rule.
    protected boolean doHandle(Request request, Response response, Callback callback)
    {
        assert getRequest() == request;
        getHandler().handle(request, response, callback);
    }
```

Edit: extra thoughts below

To achieve this, each `Rule.matchAndApply` needs to do something like:

```java
    public Handler matchAndApply(Request request, Iterator<Rule> nextRules, Handler ultimateHandler) throws IOException
    {
         if (match(input))
         {
             Request wrapper = wrap(request);
             Rule.Handler handler = new RuleHandle(wrapper);

             handler.setHandler(nextRules.hasNext()
                 ? nextRules.next().matchAndApply(wrapper, nextRules))
                 : ultimateHandler;
             return  handler 
         }
   
         return nextRules.hasNext()
                 ? nextRules.next().matchAndApply(request, nextRules))
                 : ultimateHandler;
    }
```

**Comment by sbordet** [comment]
@gregw I went a hopefully simpler path, by double linking the `RuleHandler` so that rule applications build wrappers as in `c{b{a{request}}}`, but calling `handle()` runs in the opposite direction so `{a.handle() -> b.handle() -> c.handle() -> MyAppHandler.handle()}`.

There is no need for a `Rule.Handler` to implement `Request.Handler` now, because we never call that method (so does not need to be made `final`), so I removed that to simplify.

File: jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/Rule.java [hunk 1]
```diff
@@ -29,94 +29,96 @@ public abstract class Rule
...
+     * <p>After the {@link Rule} applications, the {@link Rule.Handler}s are then called in
+     * sequence, starting from the innermost and moving outwards with respect to the wrapping,
+     * until finally the {@link org.eclipse.jetty.server.Handler#handle(Request, Response, Callback)}
+     * method of the child {@code Handler} of {@link RewriteHandler} is invoked.</p>
      */
-    public static class Handler extends Request.Wrapper implements Request.Handler
+    public static class Handler extends Request.Wrapper
     {
-        private volatile Handler _handler;
+        private Rule.Handler _wrapper;
```
Comment (gregw) [inline jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/Rule.java]:
```suggestion
        private Rule.Handler _nextRuleHandler;
```

File: jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java [hunk 2]
```diff
@@ -123,14 +131,32 @@ public boolean handle(Request request, Response response, Callback callback) thr
             return false;
 
         Rule.Handler input = new Rule.Handler(request);
-        Rule.Handler output = _rules.matchAndApply(input);
+        Rule.Handler result = getRuleContainer().matchAndApply(input);
 
         // No rule matched, call super with the original request.
-        if (output == null)
+        if (result == null)
```
Comment (gregw) [inline jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java:137]: Maybe
```suggestion
        if (result == null || result == input)
```

File: jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java [hunk 3]
```diff
@@ -123,14 +131,32 @@ public boolean handle(Request request, Response response, Callback callback) thr
...
             return super.handle(request, response, callback);
 
-        // At least one rule matched, call super with the result of the rule applications.
-        output.setHandler(getHandler());
-        return output.handle(output, response, callback);
+        // At least one rule matched, link the last Rule.Handler
+        // to invoke the child Handler of this RewriteHandler.
+        new Output(result, getHandler());
```
Comment (gregw) [inline jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java]:
```suggestion
        new LastRuleHandler(result, getHandler());
```

File: jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java [hunk 4]
```diff
@@ -123,14 +131,32 @@ public boolean handle(Request request, Response response, Callback callback) thr
...
+        return input.handle(response, callback);
+    }
+
+    private static class Output extends Rule.Handler
```
Comment (gregw) [inline jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java]:
```suggestion
    private static class LastRuleHandler extends Rule.Handler
```

File: jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java (hunk 3 above)
Comment (gregw) [inline jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RewriteHandler.java]: Also it would be clearer to explicitly link here rather than use side effect within constructor

**Review by gregw — APPROVED** [review]
That's simpler.... but maybe some renames for clarity.  Output is no longer Output
