### PR TITLE
Fix null host when checking virtual host #10922

### LINKED ISSUE #10922: Fix NPE on null host when checking virtual host
**Jetty version(s)**
- jetty-10.0.18; built: 2023-10-27T01:59:58.245Z; git: 8545fd9bf4cd0d0838f626b405fd4963441546b7
- jetty-12.0.3; built: 2023-10-27T03:25:22.284Z; git: a873259fd5af141dedaa6c7fa8fe8fbdedce0d61

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.1" 2023-10-17 LTS

**OS type/version**
Linux Debian/12.2
Linux jetty02 6.1.0-13-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

**Description**
We have a simple HelloWorld servlet mapped to multiple host names in context.xml that used to work on Jetty-10 but started failing migration tests to Jetty-12.  We tracked the problem to new code in Jetty-12. [This Jetty-10 code worked](https://github.com/jetty/jetty.project/blob/8545fd9bf4cd0d0838f626b405fd4963441546b7/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java#L1138) but [this Jetty-12 based code failed](https://github.com/jetty/jetty.project/blob/a873259fd5af141dedaa6c7fa8fe8fbdedce0d61/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java#L717)

**How to reproduce?**
Deploy your hello world servlet  with a virtual host (www.example.com), and issue curl request to the jetty server using  random host name (random.example.com) .  

On Jetty-10 you will get  HTTP-404.

However, you will encounter a NPE on Jetty-12: 
```java
2023-11-26 16:16:16.666:WARN :oejsh.ContextHandlerCollection:qtp-1602323082-virtual-2: Unaccepted error oejsh.ContextHandlerCollection@734b4264{STARTED}
java.lang.NullPointerException: Cannot invoke "java.lang.String.equalsIgnoreCase(java.lang.String)" because "host" is null
        at org.eclipse.jetty.server.handler.ContextHandler.checkVirtualHost(ContextHandler.java:752)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:774)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:181)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:594)
        at org.eclipse.jetty.server.Server.handle(Server.java:179)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:649)
        at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
        at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.run(HttpStreamOverHTTP2.java:129)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(Unknown Source)
        at java.base/java.lang.VirtualThread.run(Unknown Source)
```

On Jetty-12, remove all virtual host mapping from context.xml, redeploy, and issue your curl command - Bingo (404).
The culprit is here: https://github.com/jetty/jetty.project/blob/a873259fd5af141dedaa6c7fa8fe8fbdedce0d61/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java#L752

### PR DESCRIPTION
**Pull request by gregw**
Fix #10922 
Use the `Request.getServerName` static and check for null host.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 1]
```diff
@@ -719,7 +699,9 @@ public boolean checkVirtualHost(Request request)
         if (_vhosts.isEmpty())
             return true;
 
-        String host = normalizeHostname(request.getHttpURI().getHost());
+        // TODO check why normalizeVirtualHostname is necessary to pass ContextHandlerCollectionTest
+        //      specifically is it valid for a request hostname to end with '.'
+        String host = normalizeVirtualHostname(Request.getServerName(request));
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: @joakime can you recall why we allow trailing dots in request hostnames?

Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: @gregw IIRC `localhost.` is a valid host: `localhost` dot `<empty domain name>`, but hopefully @joakime has more details.

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: Turns out a dot at the end of a host name tells the DNS resolver to not use search domains.

So for "http://foo/path", "foo" needs to be resolved and if your `/etc/resolv.conf` has `search domain.com`, then `foo.domain.com` is looked up.

But for `http://foo./path`, no search domains are used, so that is already a fully qualified domain name.

**Review by sbordet — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: The trailing dot indicates a fully qualified name (host name / dns / resolver / windows machine names / netbios names / etc).

It prevents the lookup of the name within a resolver search list. (eg: the `search` configuration in `/etc/resolv.conf`)

That trailing dot also refers to the root of the dns hierarchy.

This means when you use `https://webtide.com/` the lookup on your linux machine is ...

1. the `/etc/hosts` file
2. the `/etc/resolv.conf` search list is used to consider provided name as possible sub-domains (eg: `webtide.com.localdomain` is looked up)
3. the DNS hierarchy
  a. the `com` TLD
  b. the `webtide` domain

But if you use `https://webtide.com./` then the search is only ever `webtide.com` and that name is never considered a sub-domain of any searched domains.

Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: The DNS protocol uses the trailing dot as well.

``` plain
$ dig jetty.org
; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> jetty.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7287
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;jetty.org.			IN	A

;; ANSWER SECTION:
jetty.org.		233	IN	A	107.22.210.238

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Tue Nov 28 12:11:07 CST 2023
;; MSG SIZE  rcvd: 54
```

Notice the trailing dot in the dns record?

Even the MX records show this trailing dot.

``` plain
$ dig jetty.org MX

; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> jetty.org MX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21841
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;jetty.org.			IN	MX

;; ANSWER SECTION:
jetty.org.		215	IN	MX	10 alt3.aspmx.l.google.com.
jetty.org.		215	IN	MX	5 alt2.aspmx.l.google.com.
jetty.org.		215	IN	MX	1 aspmx.l.google.com.
jetty.org.		215	IN	MX	5 alt1.aspmx.l.google.com.
jetty.org.		215	IN	MX	10 alt4.aspmx.l.google.com.

;; Query time: 4 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Tue Nov 28 12:11:25 CST 2023
;; MSG SIZE  rcvd: 156

```

**Review by joakime — DISMISSED** [review]

**Comment by gregw** [comment]
@sbordet @joakime @lorban I removed the TODOs regarding the trailing '.' and improved the matching so that it avoids making the extra string for wildcards.  Please re-review

**Review by joakime — APPROVED** [review]

**Comment by wsharten** [comment]
Similar, NPE in getVirtualHosts() when ContextHandler _vhosts is null in Jetty 12.0.5. The method's javadoc comment says "A null/empty array means any hostname is acceptable."

java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this._vhosts" is null
	at org.eclipse.jetty.server.handler.ContextHandler.getVirtualHosts(ContextHandler.java:391)
	at org.eclipse.jetty.server.handler.ContextHandler.toString(ContextHandler.java:1032)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:291)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:263)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:225)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:160)
	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:397)
...
	at org.eclipse.jetty.server.handler.ContextHandler.<init>(ContextHandler.java:177)


This appears during a logging call.

To reproduce using embedded:

      MyHandler myHandler = new Myandler();
      ContextHandler myContextHandler = new ContextHandler(myHandler, "/mycontext");

I have not specified any virtual hosts, which is not specified in your available examples either.

**Comment by joakime** [comment]
@wsharten you have something wacky going on.

`this._vhosts` cannot be null.

https://github.com/jetty/jetty.project/blob/62e073c52c567fd18cb5058bc0419b287b209997/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java#L125

**Comment by joakime** [comment]
@wsharten if you can trigger this NPE consistently, **open a new Issue** here and detail your setup to trigger it.

**Comment by wsharten** [comment]
It happens depending on logging mode during init of ContextHandler when run with this logging property: System.setProperty("org.eclipse.jetty.util.log.DEBUG", "true");. Does not happen when ...util.log.DEBUG is false.

this._vhosts has not been initialized yet when this occurs; logging is trying to log _vhosts when it has not been set yet. Probably has not been tested when using this logging mode.

**Comment by wsharten** [comment]
Mistaken--it happens regardless of that logging property. I will try to learn how to open a new issue. New to github.

**Comment by joakime** [comment]
@wsharten use [this link to open a new issue](https://github.com/jetty/jetty.project/issues/new?assignees=&labels=Bug&projects=&template=issue-template.md&title=)

**Comment by wsharten** [comment]
Thanks. Already submitted, issue #11220
