### PR TITLE
Fixes #3952 - Server configuration for direct/heap ByteBuffers.

### LINKED ISSUE #3952: Server configuration for direct/heap ByteBuffers
This issue aggregates #183, #226, #351, #2135.

Currently we have a number of configurations for dealing with direct/heap buffers:

* `HttpConfiguration.useDirectBuffers` - introduced in #348 for #351. While I don't think this is a HTTP configuration (it's more a ServerConnector/ConnectionFactory configuration) I guess it's ok to have it here as we also have `HttpConfiguration.idleTimeout`. Javadocs for `HttpConfiguration.useDirectBuffers` says it's about requests, but it is in fact applied to responses too. It is only used in `HttpConnection` so not for SSL and neither for HTTP/2 nor WebSocket.
* `EndPoint.isOptimizedForDirectBuffers()` - this is a getter only property that supposedly tells whether the `EndPoint` works better with direct buffers. I think there are wrong assumptions here, such as "TLS EndPoints will work better with heap buffers" which may be true when using the JDK TLS implementation (and even then it's questionable if it really is), but it's wrong when we use native implementations such as Conscrypt. I believe this getter should be completely removed since it's based on wrong assumptions.
* `HttpTransport.isOptimizedForDirectBuffers()` - write side only and trickled up from `EndPoint`, same observations, should be removed.
* `HttpOutput.Interceptor.isOptimizedForDirectBuffers()` - ditto.
* `HttpChannel.isOptimizedForDirectBuffers()` - ditto. This is inherited from `HttpOutput.Interceptor`.
* `HttpChannel.useDirectBuffers()` - this is a getter only property that is a duplicate in functionality for `HttpChannel.isOptimizedForDirectBuffers()` and it's used in the write side by `HttpOutput` so now `HttpChannel` has 2 getters for the same thing and `HttpOutput` looks sometimes at one and sometimes at the other - should be removed.
* `SslConnectionFactory.directBuffersFor[Encryption|Decryption]` - introduced by #2135 used only by `SslConnection` which defeats `EndPoint.isOptimizedForDirectBuffers()`.

### PR DESCRIPTION
**Pull request by sbordet**
#3952.

Updated server-side to use direct/heap ByteBuffers based on
getters and setters in the relevant components.
Made HTTP/1.1, HTTP/2, and WebSocket use the same mechanism.

Removed unused obsoleted methods:
* EndPoint.isOptimizedForDirectBuffers()
* HttpTransport.isOptimizedForDirectBuffers()
* HttpOutput.Interceptor.isOptimizedForDirectBuffers()
* HttpChannel.useDirectBuffers()

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/ValidationExtensionTest.java [hunk 1]
```diff
@@ -88,7 +89,7 @@ public void testNonUtf8BinaryPayload() throws Exception
             Frame frame = serverHandler.receivedFrames.poll(5, TimeUnit.SECONDS);
             assertNotNull(frame);
             assertThat(frame.getOpCode(), is(OpCode.BINARY));
-            assertThat(frame.getPayload().array(), is(nonUtf8Payload));
+            assertThat(BufferUtil.toArray(frame.getPayload()), is(nonUtf8Payload));
```
Comment (joakime) [inline jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/extensions/ValidationExtensionTest.java]: oh yeah, i guess that issue floated to the top as a result of these changes.

File: jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/server/WebSocketServerTest.java [hunk 2]
```diff
@@ -207,29 +204,6 @@ public void onFrame(Frame frame, Callback callback)
...
-            receivedCallbacks.poll().succeeded();
-            assertThat(pool.acquire(first.length, false).array(), not(sameInstance(first)));
-            receivedCallbacks.poll().succeeded();
-            assertThat(pool.acquire(first.length, false).array(), sameInstance(first));
-
-            assertThat(pool.acquire(second.length, false).array(), not(sameInstance(second)));
-            receivedCallbacks.poll().succeeded();
-            assertThat(pool.acquire(second.length, false).array(), not(sameInstance(second)));
-            receivedCallbacks.poll().succeeded();
-            assertThat(pool.acquire(second.length, false).array(), sameInstance(second));
```
Comment (joakime) [inline jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/server/WebSocketServerTest.java]: What happened to these tests?

File: jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java [hunk 3]
```diff
@@ -572,6 +599,7 @@ void enqueueFrame(Frame frame, Callback callback, boolean batch)
         private Flusher(Scheduler scheduler, int bufferSize, Generator generator, EndPoint endpoint)
         {
             super(bufferPool, scheduler, generator, endpoint, bufferSize, 8);
+            setUseDirectByteBuffers(isUseOutputDirectByteBuffers());
```
Comment (joakime) [inline jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java]: Not sure I follow this one.
Seems redundant.

File: jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/server/WebSocketServerTest.java (hunk 2 above)
Comment (sbordet) [reply jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/server/WebSocketServerTest.java]: These tests were testing for reference equality on the array wrapped by heap `ByteBuffer`, with the intent to test that the network buffer used to read the websocket frames was actually the same :open_mouth: 
That was super-obscure and super-brittle, as the TCP write could have been split, and they are of course broken if you don't use heap `ByteBuffer`.

File: jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java (hunk 3 above)
Comment (sbordet) [reply jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java]: The base class, `FrameFlusher`, has a `batchBuffer` that needs to be created heap or direct.
However, only here in the actual connection we can retrieve the heap/direct configuration, and fortunately the `FrameFlusher` was already subclassed here, so we set the directness on the flusher with the value from the connection.

File: jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/server/WebSocketServerTest.java (hunk 2 above)
Comment (joakime) [reply jetty-websocket/websocket-core/src/test/java/org/eclipse/jetty/websocket/core/server/WebSocketServerTest.java]: Ah, yeah. good point.
Resolving.

File: jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java (hunk 3 above)
Comment (joakime) [reply jetty-websocket/websocket-core/src/main/java/org/eclipse/jetty/websocket/core/internal/WebSocketConnection.java]: Ah, I understand now.

**Comment by gregw** [comment]
@sbordet can you fix conflict and then I'll review

**Comment by sbordet** [comment]
@gregw conflicts resolved.

File: jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java [hunk 4]
```diff
@@ -56,6 +56,8 @@
     private final ISession session;
     private final int bufferSize;
     private final ExecutionStrategy strategy;
+    private boolean useInputDirectBuffers;
```
Comment (gregw) [inline jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java]: use `fooBarDirectBuffers` or `fooBarDirectByteBuffers` everywhere, but not both!

File: jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java [hunk 5]
```diff
@@ -99,6 +101,26 @@ protected void setInputBuffer(ByteBuffer buffer)
             producer.setInputBuffer(buffer);
     }
 
+    public boolean isUseInputDirectByteBuffers()
```
[the remark this answers is not in the document]
Comment (sbordet) [reply jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java]: @gregw this is consistent everywhere, starting from `HttpConfiguration`.
I don't like "using" because it conveys to me that it may change, while instead I want to configure it in a way and remain in that way - therefore imperative "use".
"Direct" being adjective to "ByteBuffer" I put the two close together, which leaves "Input" and "Output" at the beginning of the name.

Alternative would be "useDirect[Input|Output]ByteBuffers?

[the remark this answers is not in the document]
Comment (gregw) [reply jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java]: OK as is.

**Comment by olamy** [comment]
@gregw I will look at that this weekend

**Comment by olamy** [comment]
@gregw did a bit of testing no huge difference. see here https://jenkins.webtide.net/job/load_testing/job/load-test-pipeline/loadtestresult/ compare versions 10.0.0.3959-SNAPSHOT and 10.0.0-SNAPSHOT

**Comment by gregw** [comment]
@olamy thanks
@sbordet go for merge!
