### PR TITLE
Fixes #13615 - Concurrency issue, headers from different requests are mixed in Jetty 12.0.27.

### LINKED ISSUE #13615: Concurrency issue, headers from different requests are mixed in Jetty 12.0.27
**Jetty version(s)**
Jetty 12.0.27

**Jetty Environment**
ee10

**Java version/vendor**
openjdk 25 2025-09-16 LTS
OpenJDK Runtime Environment Temurin-25+36 (build 25+36-LTS)
OpenJDK 64-Bit Server VM Temurin-25+36 (build 25+36-LTS, mixed mode, sharing)

**OS type/version**
Ubuntu 24.04.3 LTS

**Description**
When navigating on a server with concurrent traffic, sometimes an error page is displayed:
```
HTTP ERROR 400 Illegal header value 
JSESSIONID=aryawzf44....a; language=en; user_id=307.....6104; country=au;

URI: /badRequest
STATUS: 400
MESSAGE:  Illegal header value  JSESSIONID=aryawzf44....a; language=en; user_id=307.....6104; country=au;
```

But for this same request, Google Chrome inspect reports this value for the "Cookie" header:
`language=es; user_id=5540616.....06; country=es; JSESSIONID=aryai7kdg7h...a; <...and other cookies...>`

So clearly the information from one request (the Cookie header at least) is being mixed with another request in what looks like a concurrency issue.

This was not happening at all in Jetty 12.0.22

**How to reproduce?**
Navigate on a server with traffic and wait for the 400 error page.

### PR DESCRIPTION
**Pull request by sbordet**
* Added handling failed MetaData in HTTP2Stream.onHeaders(), in case the response contains bad headers.
* Properly resetting at the end of MetaDataBuilder.build(): before the _streamException field was not reset, leading to failing also the next requests/responses.
* Made sure MetaDataBuilder.build() resets even when a failure is detected early at the beginning of the method.
* Added checks in HpackDecoder for indexed entries that may have been stored with invalid header name/value.
* HpackDecoder now stores a lower-case "content-length: 0", so that subsequent retrievals do not fail the checks added above.
* Added test cases for concurrent good and bad responses.

See https://github.com/jetty/jetty.project/pull/13767 for the 12.1 PR.

### CODE REVIEW

File: jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java [hunk 1]
```diff
@@ -39,6 +39,7 @@
 public class HpackDecoder
 {
     private static final Logger LOG = LoggerFactory.getLogger(HpackDecoder.class);
+    private static final HttpField CONTENT_LENGTH_0 = new PreEncodedHttpField(HttpHeader.CONTENT_LENGTH, "content-length", "0");
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java]: Use `HttpFields.CONTENT_LENGTH_0`

Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java]: Ah you are not using it because you want it lowercase!  A comment or a better name please so somebody does not revert it back:
```suggestion
    private static final HttpField CONTENT_LENGTH_LOWER_CASE_0 = new PreEncodedHttpField(HttpHeader.CONTENT_LENGTH, "content-length", "0");
```

Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java]: Hmmm explain exactly why this is required?  The pre-encoder is already using lowercase name.  Confused?

File: jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/ConcurrentRequestsTest.java [hunk 2]
```diff
@@ -0,0 +1,297 @@
...
+
+        Session clientSession = newClientSession(new Session.Listener() {});
+        // The test will send an invalid header value on this connection.
+        ((HTTP2Session)clientSession).getGenerator().getHpackEncoder().setValidateEncoding(false);
+
+        testConcurrentGoodRequestsWithBadRequests(clientSession, clientSession);
+    }
+
+    @Test
+    public void testConcurrentGoodRequestsWithBadRequestsWithDifferentConnections() throws Exception
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-tests/src/test/java/org/eclipse/jetty/http2/tests/ConcurrentRequestsTest.java:72]: This test failed for me locally when I first ran it.  Now I can't get it to fail... but it might be flaky?

File: jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java]: I replaced with HttpFields.CONTENT_LENGTH_0 and no tests failed?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java]: @gregw I erroneously committed the check on the validity of the header using `getLowerCaseName()`, that's why reverting no test failed.

The problem is that the decoder had a special case for `HttpHeader.CONTENT_LENGTH`, where even when it was decoding the lower case name, it was then returning the `HttpFields.CONTENT_LENGTH_0` constant, which was camel-case, and was then cached.
On a subsequent request, we returned the cached field, which had the camel-case name, so a check on the name would fail.

Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java]: OK - so a comment and/or better name is needed

**Comment by sbordet** [comment]
@lachlan-roberts I moved the work for HTTP/3 to #13767 for 12.1.x, since making it work in 12.0.x H3 was too much work.

This PR for 12.0.x will only fix H2, the PR for 12.1.x will fix it also for H3.

**Review by lorban — APPROVED** [review]
