### PR TITLE
Removed reliance on exception to shutdown non persistent connections

### LINKED ISSUE #12212: ShutdownOutput for non-persistent HTTP/1 connections
**Jetty version(s)**
12

**Enhancement Description**

Currently a needless exception is thrown by the HttpConnection class after every connection is closed:
```
2024-08-30 12:00:37.908:DEBUG:oejsi.HttpConnection:qtp1212899836-30: caught exception HttpConnection@28edcae7::SocketChannelEndPoint@35c31367[{l=/127.0.0.1:8080,r=/127.0.0.1:33516,OPEN,fill=-,flush=-,to=3/30000}{io=0/0,kio=0,kro=1}]->[HttpConnection@28edcae7[p=HttpParser{s=CLOSE,0 of -1},g=HttpGenerator@7c03111a{s=START}]=>HttpChannelState@72c4f0ea{handling=null, handled=false, send=SENDING, completed=false, request=null}] HttpChannelState@72c4f0ea{handling=null, handled=false, send=SENDING, completed=false, request=null}
org.eclipse.jetty.io.RuntimeIOException: Parser is terminated
	at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:559)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:384)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

This can be seen if debug is turned on for the following test server 
```java

    public static void main(String... args) throws Exception
    {
        Server server = new Server();

        ServerConnector connector = new ServerConnector(server);
        server.addConnector(connector);
        connector.setPort(8080);
        connector.setIdleTimeout(30000);
        HttpConfiguration httpConfiguration = connector.getConnectionFactory(HttpConnectionFactory.class).getHttpConfiguration();
        httpConfiguration.setHttpCompliance(HttpCompliance.RFC2616);
        httpConfiguration.setIdleTimeout(30000);

        ContextHandler context = new ContextHandler();
        server.setHandler(context);

        context.setHandler(new Handler.Abstract()
        {
            @Override
            public boolean handle(Request request, Response response, Callback callback) throws Exception
            {
                byte[] bytes = "Now is time for all good men to come to the aid of the party!\n".getBytes(StandardCharsets.UTF_8);
                response.write(true, BufferUtil.toBuffer(bytes), callback);
                return true;
            }
        });

        server.start();
        server.join();
    }
```

and then requests like the following are sent:

```
ardesia: ~/src/jetty-12.0.x/jetty-home/target/jetty-home/base (jetty-12.0.x)
[1991] telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /
Now is time for all good men to come to the aid of the party!
Connection closed by foreign host.

ardesia: ~/src/jetty-12.0.x/jetty-home/target/jetty-home/base (jetty-12.0.x)
[1991] telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.1 200 OK
Server: Jetty(12.0.13-SNAPSHOT)
Date: Fri, 30 Aug 2024 01:53:41 GMT
Content-Length: 62

Now is time for all good men to come to the aid of the party!
Connection closed by foreign host.

ardesia: ~/src/jetty-12.0.x/jetty-home/target/jetty-home/base (jetty-12.0.x)
[1991] telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1
Host: localhost:8080
Connection: close

HTTP/1.1 200 OK
Server: Jetty(12.0.13-SNAPSHOT)
Date: Fri, 30 Aug 2024 01:54:18 GMT
Content-Length: 62
Connection: close

Now is time for all good men to come to the aid of the party!
Connection closed by foreign host.
```

### PR DESCRIPTION
**Pull request by gregw**
Moved the shutdownOutput in HttpStreamOverHttp1 to before the continuation of handling

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 1]
```diff
@@ -1523,12 +1523,17 @@ public void succeeded()
...
 
+            // as this is not an upgrade, we can shutdown the output if we know we are not persistent
+            if (_sendCallback._shutdownOut)
+                getEndPoint().shutdownOutput();
+
             _httpChannel.recycle();
 
+
+            // If we are still expecting 100 Continue and no content was read, then
+            // close the parser so that below it seeks EOF, not the next request.
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: The comment was more correct before, as we are not expecting 100 Continue, we test whether we have sent it.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 2]
```diff
@@ -1523,12 +1523,17 @@ public void succeeded()
                 return;
             }
 
+            // as this is not an upgrade, we can shutdown the output if we know we are not persistent
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Nit: `as` -> `As`, and period at the end of the comment.

**Review by sbordet — DISMISSED** [review]
Change looks good, just nits on the comments.
