### PR TITLE
Fixes #11822 - HTTP/2 responses exceeding SETTINGS_MAX_HEADER_LIST_SIZE do not result in RST_STREAM or GOAWAY.

### LINKED ISSUE #11822: h2 server responses exceeding SETTINGS_MAX_HEADER_LIST_SIZE do not result in RST_STREAM or GOAWAY
**Jetty version(s)**

First observed in Jetty 10.0.16, 11.0.16, 12.0.0.beta2. Latest versions (10.0.20, 11.0.20, 12.0.9) all exhibit the same bug. Appears to have been introduced by https://github.com/jetty/jetty.project/commit/420ec7cc1db65b42693dc002aca0faa567f62f7e.

**Jetty Environment**
Observed with both ee8 and ee9.

**Java version/vendor** `(use: java -version)`
```
$ java -version
openjdk version "21.0.3" 2024-04-16
OpenJDK Runtime Environment (build 21.0.3+9)
OpenJDK 64-Bit Server VM (build 21.0.3+9, mixed mode, sharing)
```
Also observed with Java 8 for Jetty 10, Java 11 for Jetty 11.

**OS type/version**
Linux

**Description**
When a client and server connect, they exchange SETTINGS frames, which permits the client to specify a max size for a headers list. One of those settings is [SETTINGS_MAX_HEADER_LIST_SIZE](https://httpwg.org/specs/rfc7540.html#SETTINGS_MAX_HEADER_LIST_SIZE), which "informs a peer of the maximum size of header list that the sender is prepared to accept, in octets".

Later, [the spec says](https://httpwg.org/specs/rfc7540.html#MaxHeaderBlock) "An endpoint can use the [SETTINGS_MAX_HEADER_LIST_SIZE](https://httpwg.org/specs/rfc7540.html#SETTINGS_MAX_HEADER_LIST_SIZE) to advise peers of limits that might apply on the size of header blocks. This setting is only advisory, so endpoints MAY choose to send header blocks that exceed this limit and risk having the request or response being treated as malformed."

The https://github.com/jetty/jetty.project/commit/420ec7cc1db65b42693dc002aca0faa567f62f7e commit in Jetty improves handling for all things headers related, and introduced handling of this max header size.

The current behavior is that when a HEADERS frame would exceed that limit, the server will end the entire connection abruptly, with TCP FIN rather than killing the affected stream with RST_STREAM, or the h2 connection with GOAWAY. This is the source of the buggy behavior being called out. 

It appears that ending the connection SHOULD instead be (first) done with GOAWAY, https://httpwg.org/specs/rfc7540.html#rfc.section.5.4.1,
> An endpoint that encounters a connection error SHOULD first send a [GOAWAY](https://httpwg.org/specs/rfc7540.html#GOAWAY) frame ([Section 6.8](https://httpwg.org/specs/rfc7540.html#GOAWAY)) with the stream identifier of the last stream that it successfully received from its peer. The [GOAWAY](https://httpwg.org/specs/rfc7540.html#GOAWAY) frame includes an error code that indicates why the connection is terminating. After sending the [GOAWAY](https://httpwg.org/specs/rfc7540.html#GOAWAY) frame for an error condition, the endpoint MUST close the TCP connection.

It perhaps would also be possible to make this only a stream error and leave the connection running for other streams via RST_STREAM.

The bug that this introduces is that while with a GOAWAY, the client knows there was an error that the server observed and shut down the connection, while without, clients do not know what happened, and might attempt to reconnect.

Specifically, this is introducing a failure in gRPC-java support for Jetty, where the client cannot tell why the upstream stopped responding - handling of GOAWAY for gRPC is to interpret the failure as `INTERNAL`, while `UNAVAILABLE` is the result when the socket just ends as Jetty is doing, which is interpreted to be transient (i.e. nothing that a well behaved server would deliberately do).

Also note, this does not happen with http/1.1 in Jetty, instead a 500 error is sent to the client.

**How to reproduce?**
Start a h2 server running one of the affected versions, with a simple handler (here using servlets) to send a giant payload:
```java
public class Server {
    public static void main(String[] args) throws Exception {
        org.eclipse.jetty.server.Server s = new org.eclipse.jetty.server.Server(10000);
        ServerConnector sc = (ServerConnector) s.getConnectors()[0];
        HttpConfiguration httpConfiguration = new HttpConfiguration();

        HTTP2CServerConnectionFactory factory =
                new HTTP2CServerConnectionFactory(httpConfiguration) {
                    @Override
                    protected ServerSessionListener newSessionListener(Connector connector,
                                                                       EndPoint endPoint) {
                        return new HTTPServerSessionListener(endPoint) {
                            @Override
                            public void onSettings(Session session, SettingsFrame frame) {
                                HTTP2Session s = (HTTP2Session) session;
                                System.out.println("Client max: " + s.getGenerator().getHpackEncoder().getMaxHeaderListSize());
                            }
                        };
                    }
                };
        factory.setRateControlFactory(new RateControl.Factory() {
        });
        sc.addConnectionFactory(factory);

        ServletContextHandler context =
                new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/");
        context.addServlet(new ServletHolder(new HugeHeaderServlet()), "/*");
        s.setHandler(context);

        s.start();
        s.join();
    }
}
```
```java
public class HugeHeaderServlet extends HttpServlet {
    // Jetty client defaults to 8192
    private static final String HUGE_HEADER_VALUE = "a".repeat( 16 * 1024);

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setHeader("Huge", HUGE_HEADER_VALUE);
    }
}
```
Attempt to connect with an h2 client with a header limit below the payload size:
```java
public class Client {
    public static void main(String[] args) throws Exception {
        HTTP2Client client = new HTTP2Client();
        client.setMaxResponseHeadersSize(8 * 1024);
        client.setMaxFrameSize(1024 * 1024);
        client.start();
        CompletableFuture<Session> sessionPromise = client.connect(new InetSocketAddress("localhost", 10000), new ServerSessionListener() {
            @Override
            public void onAccept(Session session) {
                ServerSessionListener.super.onAccept(session);
            }
        });
        Session session = sessionPromise.get(5, TimeUnit.SECONDS);
        MetaData request = new MetaData.Request("GET", HttpURI.from("http://localhost:10000/"), HttpVersion.HTTP_2, null);
        CompletableFuture<Stream> streamPromise = session.newStream(new HeadersFrame(request, null, false), new Stream.Listener() {
            @Override
            public void onHeaders(Stream stream, HeadersFrame frame) {
                System.out.println("HEADERS: " + frame);
            }

            @Override
            public void onFailure(Stream stream, int error, String reason, Throwable failure, Callback callback) {
                System.out.println("FAILURE: " + reason);
            }

            @Override
            public void onReset(Stream stream, ResetFrame frame, Callback callback) {
                System.out.println("RESET: " + frame);
            }
        });

        streamPromise.get(5, TimeUnit.SECONDS);
    }
}
```

### PR DESCRIPTION
**Pull request by sbordet**
Now HpackException.SessionException is treated specially in HTTP2Flusher. 

It is caught, it fails all the entries, and then tries to send a GOAWAY, which will be the only frame allowed into the HTTP2FLusher at that point.

### CODE REVIEW

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java [hunk 1]
```diff
@@ -106,6 +108,8 @@ public boolean append(HTTP2Session.Entry entry)
         try (AutoLock ignored = lock.lock())
         {
             closed = terminated;
+            if (closed instanceof HpackException.SessionException)
+                closed = null;
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java]: Niggle... it is strange to set then clear closed.  How about:

```suggestion
            // Comment about why terminated is ignored if it is a SessionException
            closed = (terminated instanceof HpackException.SessionException) ? null : terminated ;
```

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java [hunk 2]
```diff
@@ -106,6 +108,8 @@ public boolean append(HTTP2Session.Entry entry)
...
             if (closed == null)
             {
                 entries.offer(entry);
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java:116]: Can't the return true at line 117/121 below be done here (after the debug below) rather than testing again for `closed == null` outside the lock?

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java [hunk 3]
```diff
@@ -163,7 +167,12 @@ protected Action process() throws Throwable
         try (AutoLock ignored = lock.lock())
         {
             if (terminated != null)
-                throw terminated;
+            {
+                 if (terminated instanceof HpackException.SessionException)
+                     terminated = new ClosedChannelException().initCause(terminated);
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java]: Is the intention here is that next time `process()` is called, that we will throw the HE.SE wrapped as a CCE?

Maybe it would be clearer as
```java
             if (terminated instanceof HpackException.SessionException)
                 // Allow a SessionException to be processed once so that a GoAway can be sent
                 terminated = new ClosedChannelException().initCause(terminated);
             else if (terminated != null)
                 throw terminated;
```

This still feels a bit fragile.  If terminated is a HE.SE, then should we assert that pending contains a single entry that is a go-away?

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java [hunk 4]
```diff
@@ -248,6 +257,15 @@ protected Action process() throws Throwable
...
                     pending.remove();
                 }
+                catch (HpackException.SessionException failure)
+                {
+                    if (LOG.isDebugEnabled())
+                        LOG.debug("Failure generating {}", entry, failure);
+                    onSessionFailure(failure);
+                    // The method above will try to send
+                    // a GOAWAY, so we will iterate again.
+                    return Action.IDLE;
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java:275]: I've walked through the code of `onSessionFailure` and `fail(Throwable)` and it is not obvious what is sending the go-away, so it is not clear what will call iterated again? More importantly, it is not clear if that will always be done?

Is there some way of making that clearer here?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java]: I was able to make the condition more precise now, but it is longer.
I like better the "assign the default case; then look at conditions for the special case", rather than doing it in a one-liner.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java:116]: Done.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java]: Done.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java (hunk 4 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java:275]: `onSessionFailure()` attempts to call `session.close()`, which may send a GOAWAY (if not already closed, etc.).

If the GOAWAY is sent, then the flusher is iterated, and returning IDLE will result in a re-iteration.
Otherwise the flusher is already terminated, and we can return IDLE, as it will be torn down soon after anyway.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java [hunk 5]
```diff
@@ -163,7 +166,21 @@ protected Action process() throws Throwable
...
-                throw terminated;
+            {
+                boolean rethrow = true;
+                if (terminated instanceof HpackException.SessionException)
+                 {
+                     HTTP2Session.Entry entry = entries.peek();
+                     if (entry != null && entry.frame().getType() == FrameType.GO_AWAY)
+                     {
+                         // Allow a SessionException to be processed once to send a GOAWAY.
+                         terminated = new ClosedChannelException().initCause(terminated);
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java:177]: Is this line necessary now?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java:177]: Does not hurt, we want to send the GOAWAY only once.

**Review by gregw — APPROVED** [review]
