### PR TITLE
12.0.x: ` IteratingCallback` reset `_iterate` flag when another processing is scheduled

### LINKED ISSUE #12268: `IteratingCallback` may iterate too much when `process()` returns Action.IDLE
**Jetty version(s)**
9.4.x, 10.0.x, 11.0.x, 12.0.x, 12.1.x

**Description**
When `IteratingCallback.process()` returns `Action.IDLE`, it incorrectly iterates one more time if another thread asks it to iterate and another processing has been scheduled.

### PR DESCRIPTION
**Pull request by lorban**
Fixes #12268

### CODE REVIEW

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/IteratingCallbackTest.java [hunk 1]
```diff
@@ -45,6 +49,37 @@ public void dispose() throws Exception
...
+            protected Action process()
+            {
+                int counter = this.counter++;
+                if (counter == 0)
+                {
+                    iterate();
+                    if (succeededWinsRace)
+                        succeeded();
+                    else
+                        scheduler.schedule(this::succeeded, 100, TimeUnit.MILLISECONDS);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/IteratingCallbackTest.java]: I think it's too short to guarantee that succeeded() loses the race, I'd bump to 500.

**Review by sbordet — CHANGES_REQUESTED** [review]
Small nit on the test, otherwise good.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/IteratingCallbackTest.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/IteratingCallbackTest.java]: You're right, and relying on time is wrong when we can actually wait for a state change. Let me change that.

**Review by sbordet — APPROVED** [review]

**Review by gregw — APPROVED** [review]
