### PR TITLE
Fixes #7348 - Slow CONNECT request causes NPE (#7349)

### LINKED ISSUE #7348: Slow CONNECT request causes NPE
**Jetty version(s)**
9.4.x+

**Description**
When `HttpClient` is configured with an `HttpProxy`, and a request is made through the proxy, this NPE may happen:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.hasRemaining()" because "this.networkBuffer" is null
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.onUpgradeFrom(HttpReceiverOverHTTP.java:123)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onUpgradeFrom(HttpConnectionOverHTTP.java:179)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:432)
	at org.eclipse.jetty.client.HttpProxy$CreateTunnelPromise.tunnelSucceeded(HttpProxy.java:220)
	at org.eclipse.jetty.client.HttpProxy$CreateTunnelPromise.lambda$tunnel$0(HttpProxy.java:189)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpSender.terminateRequest(HttpSender.java:411)
	at org.eclipse.jetty.client.HttpSender.someToSuccess(HttpSender.java:331)
	at org.eclipse.jetty.client.HttpSender$CommitCallback.process(HttpSender.java:744)
	at org.eclipse.jetty.client.HttpSender$CommitCallback.succeeded(HttpSender.java:710)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.onCompleteSuccess(HttpSenderOverHTTP.java:307)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:326)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
	at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:65)
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:212)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:84)
	at org.eclipse.jetty.client.HttpChannel.send(HttpChannel.java:125)
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:241)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:269)
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:88)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:120)
	at org.eclipse.jetty.client.HttpProxy$CreateTunnelPromise.tunnel(HttpProxy.java:180)
	at org.eclipse.jetty.client.HttpProxy$CreateTunnelPromise.succeeded(HttpProxy.java:150)
	at org.eclipse.jetty.client.HttpProxy$CreateTunnelPromise.succeeded(HttpProxy.java:131)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onOpen(HttpConnectionOverHTTP.java:133)
	at org.eclipse.jetty.io.ssl.SslConnection.onOpen(SslConnection.java:372)
	at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:324)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:402)
	at org.eclipse.jetty.io.ManagedSelector.access$2100(ManagedSelector.java:65)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:1069)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by sbordet**
Added NPE guard in `HttpReceiverOverHTTP.onUpgradeFrom()`.
Expanded logic in `HttpReceiverOverHTTP.parse()` to return true in case of CONNECT + 200.

Fixed `ProxyConnection.toConnectionString()` to avoid NPEs.

Fixed `HttpClientTest.testCONNECTWithHTTP10()` logic
after changes to fix this issue.

Now a tunneled connection is not put back into the connection pool,
and if applications explicitly want to use it, they must re-enable
fill interest, similarly to what should be done after upgrade+101.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>
(cherry picked from commit 5eb7b70df7d1e25ffb4ce267126c122f94c181fd)
Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

**Review by joakime — DISMISSED** [review]

File: jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java [hunk 1]
```diff
@@ -19,6 +19,11 @@
 
 public class MetaData implements Iterable<HttpField>
 {
+    public static boolean isTunnel(String method, int status)
```
Comment (gregw) [inline jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java:30]: javadoc

File: jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java [hunk 2]
```diff
@@ -226,14 +231,20 @@ private boolean parse()
...
             if (complete)
             {
                 int status = this.status;
                 this.status = 0;
+                // Connection upgrade due to 101, bail out.
                 if (status == HttpStatus.SWITCHING_PROTOCOLS_101)
                     return true;
+                // Connection upgrade due to CONNECT + 200, bail out.
+                String method = this.method;
+                this.method = null;
```
Comment (gregw) [inline jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java:245]: Is there a reason to null this out here?  can we be complete twice in parse?

**Review by gregw — DISMISSED** [review]
other than a few quibbles, LGTM

File: jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java (hunk 1 above)
Comment (sbordet) [reply jetty-http/src/main/java/org/eclipse/jetty/http/MetaData.java:30]: Done.

File: jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java (hunk 2 above)
Comment (sbordet) [reply jetty-client/src/main/java/org/eclipse/jetty/client/http/HttpReceiverOverHTTP.java:245]: Just for consistency. Few lines above the `complete` and the `status` fields are reset in the same way, so not resetting the `method` field would have been inconsistent.
