### PR TITLE
Issue #10356 Update Weld integration

### LINKED ISSUE #10356: Deploying WAR with `ee10-cdi-spi` fails with Weld 5/CDI 4
**Jetty version(s)**
12.0.0

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

**OS type/version**
Windows 11 22H2

**Description**
The `ee10-cdi-spi` does not work with Weld 5/CDI 4.

```
java.lang.NoSuchMethodException: no such method: jakarta.enterprise.inject.spi.BeanManager.createInjectionTarget(AnnotatedType)InjectionTarget/invokeInterface
```

The `CdiSpiDecorator` attempts to find the `createInjectionTarget` which does not appear in CDI 4. https://jakarta.ee/specifications/coreprofile/10/apidocs/jakarta/enterprise/inject/spi/beanmanager

https://github.com/eclipse/jetty.project/blob/28100e8da711e44c0722ed10bd413ae862497539/jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiSpiDecorator.java#L86

I think the equivalent should be something like 

```java
    public <T> InjectionTarget<T> createInjectionTarget(AnnotatedType<T> type) {
        return getInjectionTargetFactory(type).createInjectionTarget(null);
    }
```

**How to reproduce?**

* `java -jar %JETTY_HOME%/start.jar --add-modules=http,ee10-deploy,ee10-annotations,ee10-websocket-jakarta,ee10-cdi-spi`
* Deploy a WAR with Weld 5

Using `ee10-cdi-decorate` doesn't work either because Weld 5's `org.jboss.weld.environment.jetty.JettyContainer` isn't using the `org.eclipse.jetty.ee10.cdi`, `org.eclipse.jetty.ee10.cdi.decorator`,`org.eclipse.jetty.ee9.cdi`, `org.eclipse.jetty.ee9.cdi.decorator` attributes but I think that requires changes on their end.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #10356

Make jetty-12 work with CDI 4/Weld 5.1.1

### CODE REVIEW

File: jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiSpiDecorator.java [hunk 1]
```diff
@@ -73,21 +77,23 @@ public CdiSpiDecorator(ServletContextHandler context) throws UnsupportedOperatio
...
-            _release = lookup.findVirtual(creationalContextClass, "release", MethodType.methodType(Void.TYPE));
+            _current = cdiClass.getMethod("current", null);
+            _getBeanManager = cdiClass.getMethod("getBeanManager", null);
+            _createAnnotatedType = beanManagerClass.getMethod("createAnnotatedType", Class.class);
+            _getInjectionTargetFactory = beanManagerClass.getMethod("getInjectionTargetFactory", annotatedTypeClass);
+            _createInjectionTarget = injectionTargetFactoryClass.getMethod("createInjectionTarget", beanClass);
+            _createCreationalContext = beanManagerClass.getMethod("createCreationalContext", contextualClass);
+            _inject = injectionTargetClass.getMethod("inject", Object.class, creationalContextClass);
+            _dispose = injectionTargetClass.getMethod("dispose", Object.class);
+            _release = creationalContextClass.getMethod("release", null);
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiSpiDecorator.java:99]: A comment about the classloaders and why reflection is used rather than method handles, would be good

File: jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiSpiDecorator.java [hunk 2]
```diff
@@ -73,21 +77,23 @@ public CdiSpiDecorator(ServletContextHandler context) throws UnsupportedOperatio
...
         }
         catch (Exception e)
         {
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiSpiDecorator.java:102]: I wonder if we should catch Throwable here an then if debug is on, dump the classloader and if any of the classes can be loaded and if so from where.

File: jetty-ee9/jetty-ee9-cdi/src/main/java/org/eclipse/jetty/ee9/cdi/CdiSpiDecorator.java [hunk 3]
```diff
@@ -73,17 +74,20 @@ public CdiSpiDecorator(ServletContextHandler context) throws UnsupportedOperatio
...
+            Class<?> injectionTargetFactoryClass = classLoader.loadClass("jakarta.enterprise.inject.spi.InjectionTargetFactory");
             Class<?> creationalContextClass = classLoader.loadClass("jakarta.enterprise.context.spi.CreationalContext");
             Class<?> contextualClass = classLoader.loadClass("jakarta.enterprise.context.spi.Contextual");
 
             MethodHandles.Lookup lookup = MethodHandles.lookup();
             _current = lookup.findStatic(cdiClass, "current", MethodType.methodType(cdiClass));
             _getBeanManager = lookup.findVirtual(cdiClass, "getBeanManager", MethodType.methodType(beanManagerClass));
             _createAnnotatedType = lookup.findVirtual(beanManagerClass, "createAnnotatedType", MethodType.methodType(annotatedTypeClass, Class.class));
-            _createInjectionTarget = lookup.findVirtual(beanManagerClass, "createInjectionTarget", MethodType.methodType(injectionTargetClass, annotatedTypeClass));
+            _getInjectionTargetFactory = lookup.findVirtual(beanManagerClass, "getInjectionTargetFactory", MethodType.methodType(injectionTargetFactoryClass, annotatedTypeClass));
```
Comment (gregw) [inline jetty-ee9/jetty-ee9-cdi/src/main/java/org/eclipse/jetty/ee9/cdi/CdiSpiDecorator.java]: Interesting that method handles still work for ee9.  I guess we don't have CDI API on the classpath?  But I thought EE9 was using the same transaction API jars as it was already in jakarta namespace?

**Review by gregw — COMMENTED** [review]
So far so good.... just some nits and questions

File: jetty-ee9/jetty-ee9-cdi/src/main/java/org/eclipse/jetty/ee9/cdi/CdiSpiDecorator.java (hunk 3 above)
Comment (janbartel) [reply jetty-ee9/jetty-ee9-cdi/src/main/java/org/eclipse/jetty/ee9/cdi/CdiSpiDecorator.java]: No, they do not, I just haven't fixed them yet!

File: jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiSpiDecorator.java (hunk 1 above)
Comment (janbartel) [reply jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiSpiDecorator.java:99]: Done

File: jetty-ee9/jetty-ee9-cdi/src/main/java/org/eclipse/jetty/ee9/cdi/CdiSpiDecorator.java (hunk 3 above)
Comment (janbartel) [reply jetty-ee9/jetty-ee9-cdi/src/main/java/org/eclipse/jetty/ee9/cdi/CdiSpiDecorator.java]: EE9 is now fixed.

File: jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiConfiguration.java [hunk 4]
```diff
@@ -29,7 +33,16 @@ public CdiConfiguration()
...
 
+    private static String[] getHiddenClasses()
+    {
+        //Only hide the cdi api classes if there is not also an impl on the
+        //environment classpath - vital for embedded uses.
+        if (CdiConfiguration.class.getClassLoader().getResource("META-INF/services/jakarta.enterprise.inject.spi.CDIProvider") == null)
+            return new String[]{"jakarta.enterprise.", "jakarta.decorator."};
+        return new String[0];
+    }
+}
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiConfiguration.java:48]: missing end of line

File: jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiServletContainerInitializer.java [hunk 5]
```diff
@@ -28,21 +28,21 @@
...
- *     "org.eclipse.jetty.ee10.cdi.decorator".</dd>
+ *     "org.eclipse.jetty.cdi.decorator".</dd>
  * </dl>
  *
  * @see AnnotationConfiguration.ServletContainerInitializerOrdering
  */
 public class CdiServletContainerInitializer implements ServletContainerInitializer
 {
-    public static final String CDI_INTEGRATION_ATTRIBUTE = "org.eclipse.jetty.ee10.cdi";
+    public static final String CDI_INTEGRATION_ATTRIBUTE = "org.eclipse.jetty.cdi";
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-cdi/src/main/java/org/eclipse/jetty/ee10/cdi/CdiServletContainerInitializer.java:45]: Maybe a comment on why this is not scoped to ee10 in the name

**Review by gregw — APPROVED** [review]
other than some niggles LGTM

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-cdi/src/test/resources/jetty-logging.properties [hunk 6]
```diff
@@ -1,4 +1,4 @@
 # Jetty Logging using jetty-slf4j-impl
-org.eclipse.jetty.LEVEL=INFO
+org.eclipse.jetty.ee10.annotations.LEVEL=DEBUG
```
Comment (olamy) [inline jetty-ee10/jetty-ee10-tests/jetty-ee10-test-cdi/src/test/resources/jetty-logging.properties]: nit: maybe change back to INFO before merging to avoid too much noise per default?
