### PR TITLE
Issue #13295 support string scope; move jndi tests into core

### LINKED ISSUE #13295: Fix comments in NamingEntry; add support for simple scope name
**12.0.x**

Some of the javadoc comments in `NamingEntry` are incorrect, implying that a declaration like:

```xml
  <New id="testjndi" class="org.eclipse.jetty.plus.jndi.Resource">
    <Arg><Property name="environment" default="ee8"/></Arg>
    <Arg>testjndi</Arg>
    <Arg>
      <New class="java.lang.Integer">
        <Arg>10</Arg>
      </New>
    </Arg>
  </New>
```

Could be looked up simply like:

```java
InitialContext ic = new InitialContext();
Object o = ic.lookup("ee8/testjndi");
```

This isn't the case, we canonicalize the scope very particularly like this:

```java
String str = scope.getClass().getName() + "@" + Long.toHexString(scope.hashCode());
```

Which leads to a non-intuitive lookup of:

``` java
Object o = ic.lookup("java.lang.String@18798/testjndi")
```

Whilst we do not expect users to do these kind of lookups  - preferring always that they link objects bound via xml statements such as the one above into their webapp using the Servlet Specification approved `<resource-ref>` and `<env-entry>` elements defined in `web.xml`, thus never knowing the jetty-specific way we do the binding of objects in the jetty container space - maybe it would be nicer to optimize the name of scopes that are simple strings to just use the string.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #13295 

* Allow a scope that is a `String` to be used as the string itself (with appropriate canonicalization).
* Move some jndi tests out of `ee8,9,10` and into core instead
* Add some tests
* Improve some comments

### CODE REVIEW

File: jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/jndi/NamingEntryUtil.java [hunk 1]
```diff
@@ -225,7 +225,8 @@ private static String canonicalizeScope(Object scope)
         if (scope == null)
             return "";
 
-        String str = scope.getClass().getName() + "@" + Long.toHexString(scope.hashCode());
+        String str = (scope instanceof String) ? (String)scope : scope.getClass().getName() + "@" + Long.toHexString(scope.hashCode());
```
Comment (gregw) [inline jetty-core/jetty-plus/src/main/java/org/eclipse/jetty/plus/jndi/NamingEntryUtil.java]:
```suggestion
        String str = (scope instanceof String s) ? s : scope.getClass().getName() + "@" + Long.toHexString(scope.hashCode());
```

**Review by gregw — DISMISSED** [review]
Tiny nit, otherwise good

**Review by gregw — APPROVED** [review]
