### PR TITLE
Issue #6085 Fix reference counts for multiple valid cookies for sessions

### LINKED ISSUE #6085: Jetty keeps Sessions in use after "Duplicate valid session cookies" Message
**Jetty version**
9.4.26

**Java version**
openjdk version "10.0.2" 2018-07-17

**OS type/version**
CentOS Linux 7 (core)

**Description**
After getting org.eclipse.jetty.http.BadMessageException: 400: Duplicate valid session cookies jetty keeps the duplicate sessions in use state (request counter in session >0). Thats why these session will not be invalidated by the HouseKeeper-Thread.
Is this a bug in jetty?

### PR DESCRIPTION
**Pull request by janbartel**
Closes #6085 

If a request has multiple session cookies, and the sessions for more than one of them are valid, then the request counts for the valid sessions were not being properly decremented.

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java [hunk 1]
```diff
@@ -1667,7 +1667,12 @@ else if (!DispatcherType.REQUEST.equals(baseRequest.getDispatcherType()))
                         if (LOG.isDebugEnabled())
                             LOG.debug("Got Session ID {} from cookie {}", id, sessionCookie);
 
+                        //retrieve the session
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java]:
```suggestion
                        //retrieve the session, which increments the reference count
```

File: jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java [hunk 2]
```diff
@@ -1667,7 +1667,12 @@ else if (!DispatcherType.REQUEST.equals(baseRequest.getDispatcherType()))
...
                         HttpSession s = getHttpSession(id);
+                        //associate it with the request so its reference count
+                        //will be decremented as the request exits
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java]:
```suggestion
                        //will be decremented as the request completes
```

**Review by gregw — APPROVED** [review]
OK other than some niggles.
There is some repeated logic, but I can't see how to clean it up without risking changing behaviour.
