### PR TITLE
Issue #5362 - Adding SslContextFactory.Client to Proxy's HttpClient

### LINKED ISSUE #5362: Default ProxyServlet cannot proxy to https urls
**Jetty version**
9.4.x

**Description**
If you have a default proxy setup like this ...

**WEB-INF/web.xml**

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://java.sun.com/xml/ns/javaee" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" 
metadata-complete="false" 
version="3.0">

  <display-name>Transparent Proxy WebApp</display-name>

  <servlet>
    <servlet-name>JavadocTransparentProxy</servlet-name>
    <servlet-class>org.eclipse.jetty.proxy.ProxyServlet$Transparent</servlet-class>
    <init-param>
      <param-name>proxyTo</param-name>
      <param-value>https://www.eclipse.org/jetty/javadoc/</param-value>
    </init-param>
    <init-param>
      <param-name>hostHeader</param-name>
      <param-value>www.eclipse.org</param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
    <async-supported>true</async-supported>
  </servlet>

  <servlet-mapping>
    <servlet-name>JavadocTransparentProxy</servlet-name>
    <url-pattern>/current/*</url-pattern>
  </servlet-mapping>

</web-app>
```

Then the ProxyServlet will fail as the internal HttpClient has no support for SSL/TLS enabled.

### PR DESCRIPTION
**Pull request by joakime**
Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

File: tests/test-webapps/test-proxy-webapp/src/test/java/org/eclipse/jetty/TestTransparentProxyServer.java [hunk 1]
```diff
@@ -18,118 +18,78 @@
...
+        // We don't have a valid WEB-INF/lib to rely on at this point.
+        // So, open up server classes here, for purposes of this testcase.
+        webapp.getServerClasspathPattern().add(
+            "-org.eclipse.jetty.proxy.",
+            "-org.eclipse.jetty.client.",
+            "-org.eclipse.jetty.util.ssl.");
+        webapp.getSystemClasspathPattern().add(
+            "org.eclipse.jetty.proxy.",
+            "org.eclipse.jetty.client.",
+            "org.eclipse.jetty.util.ss.");
```
Comment (sbordet) [inline tests/test-webapps/test-proxy-webapp/src/test/java/org/eclipse/jetty/TestTransparentProxyServer.java]: Typo for `ss.`?

**Review by sbordet — APPROVED** [review]
