### PR TITLE
Fixes #13915 - You can not have both Frame and Text handler in 12.1.x Jetty websocket.

### LINKED ISSUE #13915: You can not have both Frame and Text handler in 12.1.x Jetty websocket
**Jetty version(s)**

Regression between 12.0.x to 12.1.x 

**Jetty Environment**
Core

**HTTP version**
Does not matter.

**Java version/vendor** `(use: java -version)`
Does not matter ( Java 21 Open JDK Temurin )

**OS type/version**
Does not matter ( affects all ) - ran on Linux.

**Description**

You can not have both Frame and Text handler in 12.1.x Jetty websocket.

**How to reproduce?**

1. Create a WebSocket Server with annotation ( example :  https://github.com/nmondal/cowj/blob/main/app/src/main/java/cowj/ScriptableSocket.java#L20 ) 
2.  Use both text message handler as well as frame handler 
3.  In 12.0.x it would work - both frame and text callback gets called.
4. In 12.1.x it would break - crashing out 

https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerMetadata.java#L131

This here earlier used to only check for "text" type handler previously present or not,
recent changes checks both text and frame type.

Thus,  server can ONLY handle either FRAME or TEXT/Message.

Moreover, the FRAME type should not take a callback according to documentation, but it takes, is mandatory.

### PR DESCRIPTION
**Pull request by sbordet**
* Updated migration guide.
* Updated annotation javadocs.

### CODE REVIEW

File: jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketClose.java [hunk 1]
```diff
@@ -21,13 +21,11 @@
...
  * <p>Annotation for methods to receive WebSocket close events.</p>
- * <p>Acceptable method patterns:</p>
+ * <p>Acceptable method signatures:</p>
  * <ol>
- * <li>{@code public void <methodName>(int statusCode, String reason)}</li>
- * <li>{@code public void <methodName>(Session session, int statusCode, String reason)}</li>
- * <li>{@code public void <methodName>(int statusCode, String reason, Callback callback)}</li>
  * <li>{@code public void <methodName>(Session session, int statusCode, String reason, Callback callback)}</li>
  * </ol>
+ * <p>None of the parameters is mandatory, and you can specify any combination of parameters.</p>
```
Comment (lorban) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketClose.java]:
```suggestion
 * <p>None of the parameters are mandatory, and you can specify any combination of parameters.</p>
```

**Review by lorban — DISMISSED** [review]
Just one nit, otherwise LGTM.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketMessage.java [hunk 2]
```diff
@@ -23,42 +23,38 @@
...
- * <li>{@code public void methodName(Session session, ByteBuffer message, Callback callback)}</li>
- * <li>{@code public void methodName(InputStream stream)}</li>
- * <li>{@code public void methodName(Session session, InputStream stream)}</li>
+ * <li>{@code public void methodName(Session session, *ByteBuffer message, *Callback callback)}</li>
+ * <li>{@code public void methodName(Session session, *InputStream stream)}</li>
  * </ol>
+ * <p>The {@code *} before the parameter type means that the parameter is mandatory.</p>
  * <p>NOTE</p>
  * <p>Method that takes a {@link InputStream} must have
  * {@link WebSocket#autoDemand()} set to {@code true}.</p>
```
Comment (lachlan-roberts) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketMessage.java]: Same with `InputStream`.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketMessage.java [hunk 3]
```diff
@@ -23,42 +23,38 @@
...
- * <li>{@code public void methodName(Session session, String text)}</li>
- * <li>{@code public void methodName(Reader reader)}</li>
- * <li>{@code public void methodName(Session session, Reader reader)}</li>
+ * <li>{@code public void methodName(Session session, *String text)}</li>
+ * <li>{@code public void methodName(Session session, *Reader reader)}</li>
  * </ol>
+ * <p>The {@code *} before the parameter type means that the parameter is mandatory.</p>
  * <p>NOTE</p>
  * <p>Method that takes a {@link Reader} must have
  * {@link WebSocket#autoDemand()} set to {@code true}.</p>
```
Comment (lachlan-roberts) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketMessage.java:34]: Not related to your changes but I think this is wrong. 

You can have `WebSocket#autoDemand() = false`, and then you are responsible for demanding the next message once `onWebSocketMessage` is called.

The `MessageInputStream` will demand until the end of each message regardless of the `autoDemand` setting.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketMessage.java (hunk 2 above)
Comment (lachlan-roberts) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketMessage.java:47]: Same with `InputStream`.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketClose.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketClose.java]: As a curiosity, the correct grammar is the singular, as "none" is a contraction of "not one", but the plural form seems common enough.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketMessage.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketMessage.java:34]: @lachlan-roberts the javadoc is correct, as we do this check:
https://github.com/jetty/jetty.project/blob/jetty-12.1.3/jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java#L442

And we have tests:
`LocalEndpointMetadataTest.testAnnotatedBadAutoDemandWithInputStream()`

If you think we can lift this restriction, can you please file a new issue?
