### PR TITLE
Fixed InfinispanSessionData serialization issues when using infinispan

### LINKED ISSUE #4591: InfinispanSessionData fails to deserialize
**Jetty version**
9.4.26

**Description**

Jetty throws an exception whenever a session is saved to a cache that has **storeAsBinary** enabled. To test this, you can modify the setup method in org.eclipse.jetty.server.session.InfinispanTestSupport class

` InfinispanTestSupport

    public void setup() throws Exception
    {
        File testdir = MavenTestingUtils.getTargetTestingDir();
        File tmp = new File(testdir, "indexes");
        IO.delete(tmp);
        tmp.mkdirs();

        SearchMapping mapping = new SearchMapping();
        mapping.entity(SessionData.class).indexed().providedId().property("expiry", ElementType.FIELD).field();
        Properties properties = new Properties();
        properties.put(Environment.MODEL_MAPPING, mapping);
        properties.put("hibernate.search.default.indexBase", tmp.getAbsolutePath());

        if (_useFileStore)
        {
            _tmpdir = File.createTempFile("infini", "span");
            _tmpdir.delete();
            _tmpdir.mkdir();

            Configuration config = _builder.indexing()
                .index(Index.ALL)
                .addIndexedEntity(SessionData.class)
                .withProperties(properties)
                .persistence()
                .addSingleFileStore()
                .location(_tmpdir.getAbsolutePath())
                .storeAsBinary().enable()
                .build();

            _manager.defineConfiguration(_name, config);
        }
        else
        {
            _manager.defineConfiguration(_name, _builder.indexing()
                .withProperties(properties)
                .index(Index.ALL)
                .addIndexedEntity(SessionData.class).storeAsBinary().enable()
                .build());
        }
        _cache = _manager.getCache(_name);
    }`

Here is the stacktrace of the exception

org.infinispan.commons.CacheException: java.io.IOException: Not ClassLoadingObjectInputStream
	at org.infinispan.commons.dataconversion.BinaryEncoder.fromStorage(BinaryEncoder.java:39)
	at org.infinispan.encoding.DataConversion.extractIndexable(DataConversion.java:223)
	at org.infinispan.query.backend.QueryInterceptor.extractValue(QueryInterceptor.java:398)
	at org.infinispan.query.backend.QueryInterceptor.processChange(QueryInterceptor.java:436)
	at org.infinispan.query.backend.QueryInterceptor.lambda$handleDataWriteCommand$0(QueryInterceptor.java:188)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextThenAccept(BaseAsyncInterceptor.java:105)
	at org.infinispan.query.backend.QueryInterceptor.handleDataWriteCommand(QueryInterceptor.java:181)
	at org.infinispan.query.backend.QueryInterceptor.visitPutKeyValueCommand(QueryInterceptor.java:247)
	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:73)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextThenAccept(BaseAsyncInterceptor.java:98)
	at org.infinispan.interceptors.impl.EntryWrappingInterceptor.setSkipRemoteGetsAndInvokeNextForDataCommand(EntryWrappingInterceptor.java:671)
	at org.infinispan.interceptors.impl.EntryWrappingInterceptor.visitPutKeyValueCommand(EntryWrappingInterceptor.java:302)
	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:73)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndFinally(BaseAsyncInterceptor.java:150)
	at org.infinispan.interceptors.locking.AbstractLockingInterceptor.lambda$nonTxLockAndInvokeNext$1(AbstractLockingInterceptor.java:299)
	at org.infinispan.interceptors.SyncInvocationStage.addCallback(SyncInvocationStage.java:42)
	at org.infinispan.interceptors.InvocationStage.andHandle(InvocationStage.java:65)
	at org.infinispan.interceptors.locking.AbstractLockingInterceptor.nonTxLockAndInvokeNext(AbstractLockingInterceptor.java:294)
	at org.infinispan.interceptors.locking.AbstractLockingInterceptor.visitNonTxDataWriteCommand(AbstractLockingInterceptor.java:126)
	at org.infinispan.interceptors.locking.NonTransactionalLockingInterceptor.visitDataWriteCommand(NonTransactionalLockingInterceptor.java:40)
	at org.infinispan.interceptors.locking.AbstractLockingInterceptor.visitPutKeyValueCommand(AbstractLockingInterceptor.java:82)
	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:73)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:54)
	at org.infinispan.interceptors.impl.CacheMgmtInterceptor.updateStoreStatistics(CacheMgmtInterceptor.java:214)
	at org.infinispan.interceptors.impl.CacheMgmtInterceptor.visitPutKeyValueCommand(CacheMgmtInterceptor.java:179)
	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:73)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNext(BaseAsyncInterceptor.java:54)
	at org.infinispan.interceptors.DDAsyncInterceptor.handleDefault(DDAsyncInterceptor.java:54)
	at org.infinispan.interceptors.DDAsyncInterceptor.visitPutKeyValueCommand(DDAsyncInterceptor.java:60)
	at org.infinispan.commands.write.PutKeyValueCommand.acceptVisitor(PutKeyValueCommand.java:73)
	at org.infinispan.interceptors.BaseAsyncInterceptor.invokeNextAndExceptionally(BaseAsyncInterceptor.java:123)
	at org.infinispan.interceptors.impl.InvocationContextInterceptor.visitCommand(InvocationContextInterceptor.java:90)
	at org.infinispan.interceptors.impl.AsyncInterceptorChainImpl.invoke(AsyncInterceptorChainImpl.java:248)
	at org.infinispan.cache.impl.CacheImpl.executeCommandAndCommitIfNeeded(CacheImpl.java:1918)
	at org.infinispan.cache.impl.CacheImpl.put(CacheImpl.java:1433)
	at org.infinispan.cache.impl.CacheImpl.put(CacheImpl.java:2043)
	at org.infinispan.cache.impl.CacheImpl.put(CacheImpl.java:230)
	at org.infinispan.cache.impl.AbstractDelegatingCache.put(AbstractDelegatingCache.java:448)
	at org.infinispan.cache.impl.EncoderCache.put(EncoderCache.java:675)
	at org.eclipse.jetty.server.session.InfinispanTestSupport.createSession(InfinispanTestSupport.java:149)
	at org.eclipse.jetty.server.session.InfinispanSessionDataStoreTest.persistSession(InfinispanSessionDataStoreTest.java:71)
	at org.eclipse.jetty.server.session.AbstractSessionDataStoreTest.testLoadSessionExpired(AbstractSessionDataStoreTest.java:361)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:127)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: java.io.IOException: Not ClassLoadingObjectInputStream
	at org.eclipse.jetty.server.session.SessionData.deserializeAttributes(SessionData.java:138)
	at org.eclipse.jetty.server.session.SessionData.readObject(SessionData.java:490)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callReadObject(JDKSpecific.java:179)
	at org.jboss.marshalling.reflect.SerializableClass.callReadObject(SerializableClass.java:212)
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1746)
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1395)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272)
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:205)
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
	at org.infinispan.marshall.core.ExternalJBossMarshaller.objectFromObjectStream(ExternalJBossMarshaller.java:47)
	at org.infinispan.marshall.core.GlobalMarshaller.readUnknown(GlobalMarshaller.java:873)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:697)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:361)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:194)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:190)
	at org.infinispan.commons.dataconversion.BinaryEncoder.fromStorage(BinaryEncoder.java:37)
	... 106 more
Caused by: an exception which occurred:
	in object of type org.eclipse.jetty.session.infinispan.InfinispanSessionData

### PR DESCRIPTION
**Pull request by kandrej**
Fixes #4591 InfinispanSessionData serialization issues when using infinispan embedded.

Signed-off-by: Andrej Krota <andrej.krota@gmail.com>

### CODE REVIEW

File: tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanSessionDataStoreTest.java [hunk 1]
```diff
@@ -164,30 +166,26 @@ public boolean checkSessionPersisted(SessionData data) throws Exception
     @Test
     public void testQuery() throws Exception
     {
-        Cache<String, SessionData> cache = _testSupport.getCache();
+        InfinispanSessionData sd1 = new InfinispanSessionData("sd1", "", "", 0, 0, 0, 1000);
```
Comment (janbartel) [inline tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanSessionDataStoreTest.java:163]: Why did you change the test data so that all will have expired?

File: tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanSessionDataStoreTest.java [hunk 2]
```diff
@@ -164,30 +166,26 @@ public boolean checkSessionPersisted(SessionData data) throws Exception
...
 
-        List<Object[]> list = q.list();
-
-        List<String> ids = new ArrayList<>();
-        for (Object[] sl : list)
+        for (int i = 0; i <= 3; i++)
         {
-            ids.add((String)sl[0]);
+            long now = System.currentTimeMillis();
+            Query q = qf.from(InfinispanSessionData.class).having("expiry").lt(now).build();
```
Comment (janbartel) [inline tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanSessionDataStoreTest.java:180]: Also, why did you change the query? The query did the same search as the InfinispanSessionDataStore implementation.

File: tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanTestSupport.java [hunk 3]
```diff
@@ -113,7 +113,7 @@ public void setup() throws Exception
                 .persistence()
                 .addSingleFileStore()
                 .location(_tmpdir.getAbsolutePath())
-                .storeAsBinary()
+                .storeAsBinary().enable()
```
Comment (janbartel) [inline tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanTestSupport.java]: Can we have a test both with and without storeAsBinary enabled, to be on the safe side?

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataSerializer.java [hunk 4]
```diff
@@ -0,0 +1,69 @@
+package org.eclipse.jetty.session.infinispan;
+
+import java.io.ByteArrayOutputStream;
+import java.io.IOException;
+import java.io.ObjectInput;
+import java.io.ObjectOutput;
+
+import org.infinispan.commons.marshall.Externalizer;
+
+public class InfinispanSessionDataSerializer implements Externalizer<InfinispanSessionData>
```
Comment (janbartel) [inline jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataSerializer.java]: Why is this class necessary? We are using the org.eclipse.jetty.session.infinispan.SessionDataMarshaller now, are you saying this class replaces the SessionDataMarshaller?

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataSerializer.java [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+{
+
+    private static final long serialVersionUID = 1L;
+
+    @Override
+    public void writeObject(ObjectOutput output, InfinispanSessionData object) throws IOException
+    {
+        output.writeUTF(object.getId()); //session id
```
Comment (janbartel) [inline jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataSerializer.java]: Please see the o.j.e.session.infinispan.SessionDataMarshaller regarding the requirements for the first field that is serialized: the version.

**Review by janbartel — COMMENTED** [review]
Thanks for your bug report and the pull request. I have several questions about it (see individual comments), and some changes that I'd like to see made. Could you provide a bit more background about the changes you're proposing and how they work or replace the existing SessionDataMarshaller?

File: tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanSessionDataStoreTest.java (hunk 1 above)
Comment (kandrej) [reply tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanSessionDataStoreTest.java:163]: The previous testQuery didn't work from the beginning, so I replaced it with the test used in RemoteInfinispanSessionDataStoreTest

File: tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanTestSupport.java (hunk 3 above)
Comment (kandrej) [reply tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanTestSupport.java]: Yes. It just triggers serialization, so data in the cache is in serialized form

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataSerializer.java (hunk 4 above)
Comment (kandrej) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataSerializer.java]: SessionDataMarshaller is ok in the remote setup, but it is not used in embedded infinispan when storeAsBinary is enabled. In this case the default java serialization rules are used, which fail because the SessionData readObject is invoked and ObjectInputStream is not ClassLoadingObjectInputStream

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionData.java [hunk 6]
```diff
@@ -19,6 +20,7 @@
  * pool and thus these threads have no knowledge of the correct classloader to
  * use.
  */
+@SerializeWith(InfinispanSessionDataSerializer.class)
```
Comment (janbartel) [inline jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionData.java]: You're sure that this annotation will have no effect in the remote case?

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataSerializer.java (hunk 4 above)
Comment (janbartel) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataSerializer.java]: OK. Please see my comment above about the presence of the annotation.

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataSerializer.java (hunk 5 above)
Comment (janbartel) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionDataSerializer.java]: Rather than copying the serialization, I'd rather that there was a refactoring that made it possible for your new class and the SessionDataMarshaller to use the same code.

File: tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanSessionDataStoreTest.java (hunk 1 above)
Comment (janbartel) [reply tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanSessionDataStoreTest.java:163]: Fair enough.

File: tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanTestSupport.java (hunk 3 above)
Comment (janbartel) [reply tests/test-sessions/test-infinispan-sessions/src/test/java/org/eclipse/jetty/server/session/InfinispanTestSupport.java]: I mean can you make a test both with and without storeAsBinaryEnabled please.

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionData.java (hunk 6 above)
Comment (kandrej) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionData.java]: I am not sure, but I run the remote tests and it doesn't seem to have any effect on those

**Comment by janbartel** [comment]
@kandrej can you explain to me why I see InfinispanSessionDataSerializer.writeObject being called when executing the ClusteredSessionScavengingTest? Interestingly, I never see the InfinispanSessionDataSerializer.readObject being called for that test ....

**Comment by kandrej** [comment]
I guess it's because the useFileStore is set to true. The data is persisted to a temporary file using InfinispanSessionDataSerializer. If you comment out the annotation in InfinispanSessionData and rerun the test, you will see the data will be serialized using SessionData.writeObject

**Comment by janbartel** [comment]
@kandrej ok, cool thanks for that explanation.

I think we're close to a good solution! Thinking about the InfinispanSessionDataSerializer, I'm wondering if we could put it's behaviour onto the SessionDataMarshaller instead, so that we have only 1 class that knows how to serialize sessions in infinispan. In other words, SessionDataMarshaller would also implement Externalizer<InfinispanSessionData>.   Ideally, we would be able to wrap the ProtoStreamReader and the ObjectInput in such a way that both readFrom(ProtoStreamReader) and readObject(ObjectInput) would both call the same read(WrappedInput) method so that there is only  1 place where we read the fields to populate the InfinispanSessionData object.  Similarly for the ProtoStreamWriter and ObjectOutput and the write methods.  My concern here is to reduce confusion about which class is being used to serialize the session, and to ensure that if we need to change the serialization we only have to do it in one place. Your thoughts?

BTW, there's a doc on contributing code to jetty here: https://www.eclipse.org/jetty/documentation/current/coding-standards.html. I notice some of the new files are missing the correct file header.

**Comment by kandrej** [comment]
I will merge InfinispanSessionDataSerializer into SessionDataMarshaller. I think there is no need to wrap the inputs/outputs to call a common method because readObject(ObjectInput) behind the scenes always calls readFrom(ProtoStreamReader) and writeObject(ObjectOutput, InfinispanSessionData) always calls writeTo(ProtoStreamWriter, InfinispanSessionData)

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java [hunk 7]
```diff
@@ -30,13 +39,35 @@
...
+            serializationContext.registerMarshaller(new SessionDataMarshaller());
+        }
+        catch (IOException e)
+        {
+            serializationContext = null;
+            LOG.warn("SerializationContext cannot be initialized", e);
+        }
+
+    }
+
```
Comment (janbartel) [inline jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java]: The thing is, we don't want to do this static initialization all the time. Certainly when we use infinispan remote, the use of the session.proto is already configured into a different serialization context, so this static initialization is wasted.

In jetty we are generally static-phobic: we prefer if we can do things per instance.

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java [hunk 8]
```diff
@@ -49,6 +80,50 @@ public String getTypeName()
...
+            int bufferSize = 4 * 1024;
+            byte[] buffer = new byte[bufferSize];
+            int len = -1;
+            while ((len = input.read(buffer, 0, bufferSize)) != -1)
+            {
+                os.write(buffer, 0, len);
+            }
+
+            // invokes readFrom(ProtoStreamReader)
+            InfinispanSessionData data = ProtobufUtil.fromByteArray(serializationContext, os.toByteArray(),
```
Comment (janbartel) [inline jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java]: Also here I wanted to avoid the double copying and buffering of data, which is why I was suggesting having a common method that worked with both ObejectInput and ProtoSteamReader.

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java [hunk 9]
```diff
@@ -39,35 +38,24 @@
...
     private static final int VERSION = 0;
 
-    private static final Logger LOG = Log.getLogger("org.eclipse.jetty.server.session");
-    
-    private static SerializationContext serializationContext;
-
-    static
+    private SerializationContext initSerializationContext() throws IOException
     {
         FileDescriptorSource fds = new FileDescriptorSource();
```
Comment (janbartel) [inline jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:55]: Can we keep the SerializationContext as a field that is lazily initialized only by the readObject/writeObject methods? The field would not be used by the readFrom/writeTo methods.

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java (hunk 9 above)
Comment (kandrej) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:55]: It is useless to keep SerializationContext because a new SessionDataMarshaller instance is created every time readObject or writeObject is called. I can either have it as a lazily initialized static field or create one every time

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java [hunk 10]
```diff
@@ -49,6 +67,33 @@ public String getTypeName()
...
+    {
+        SerializationContext serializationContext = initSerializationContext();
+
+     // invokes writeTo(ProtoStreamWriter, InfinispanSessionData)
+        byte[] data = ProtobufUtil.toByteArray(serializationContext, object);
+        int length = data.length;
+        output.write(ByteBuffer.allocate(4).putInt(length).array());
+        output.write(data);        
+    }
+
```
Comment (janbartel) [inline jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:107]: Can you explain the necessity for this special write? And also the BoundDelegatingInputStream?

Comment (kandrej) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:107]: I found out that when reading the session from a file, the returned ObjectInput has more data than writeObject has written. It seems Infinispan appends some data at the end for some reason.

If I just wrap all the data in an InputStream, Protobuf fails to deserialize the session. So to know exactly how many bytes need to be parsed, the write first saves the length of the data.

BoundDelegatingInputStream is just a wrapper that first reads the length of the data and stops when the length is reached.

Comment (janbartel) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:107]: So if you configure storeAsBinary, but don't use a filestore, what happens? Is that combination even possible?

Comment (kandrej) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:107]: Sure is possible. storeAsBinary means that the data is stored serialized in the cache (memory). The file is always binary

This means that when you put an instance in the cache the instance is first serialized and than saved. When you get an instance from the cache it has to be deserialized first. In this case the data from the cache is just copied to a file

If storeAsBinary is disabled, you put and get the instance itself in the cache. The data is serialized only when it is moved from the cache to the file

Comment (janbartel) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:107]: If storeAsBinary=true but not filestore, which form of serialization is used?

Comment (kandrej) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:107]: Always the Externalizer interface

Comment (kandrej) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:107]: Store as binary is explained in the user guide:

https://infinispan.org/docs/9.4.x/user_guide/user_guide.html#store_binary

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java (hunk 9 above)
Comment (janbartel) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:55]: Lets make it a static, lazily initialized. That way, if the remote protobuf marshalling is being used, it will never be initialized, it is only if the Externalizer methods are called that it will be initialized.

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java (hunk 10 above)
Comment (janbartel) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:107]: I wish infinispan had a unified serialization api!

I think we're good with your solution (just make the serialization context a lazily initialized static).

File: jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java [hunk 11]
```diff
@@ -49,6 +68,39 @@ public String getTypeName()
         return "org_eclipse_jetty_session_infinispan.InfinispanSessionData";
     }
 
+    @Override
+    public InfinispanSessionData readObject(ObjectInput input) throws IOException, ClassNotFoundException
+    {
+        if (serializationContext == null)
```
Comment (janbartel) [inline jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:78]: I think you're going to need some synchronization - the lazy init of the serializationContext fields isn't thread safe, is it?

Comment (kandrej) [reply jetty-infinispan/infinispan-common/src/main/java/org/eclipse/jetty/session/infinispan/SessionDataMarshaller.java:78]: You're right, better be sure

**Review by janbartel — APPROVED** [review]
LGTM. Thank you for this PR!
