### PR TITLE
Fix #12481 Handle headers with 304 responses

### LINKED ISSUE #12481: Exception when a Content-Length is set on a 304 response
**Jetty version(s)**
12

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.12" 2024-07-16

**OS type/version**
Ubuntu 24.04

**Description**
When a Content-Length is set on a 304 response, the following exception occurs :
```
java.io.IOException: written 0 < 454 content-length
        at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1271)
        at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:768)
        at org.eclipse.jetty.server.handler.ContextResponse.write(ContextResponse.java:56)
        at org.eclipse.jetty.ee8.nested.HttpChannel.send(HttpChannel.java:837)
        at org.eclipse.jetty.ee8.nested.HttpChannel.sendResponse(HttpChannel.java:822)
        at org.eclipse.jetty.ee8.nested.HttpChannel.write(HttpChannel.java:891)
        at org.eclipse.jetty.ee8.nested.HttpOutput.channelWrite(HttpOutput.java:286)
        at org.eclipse.jetty.ee8.nested.HttpOutput.complete(HttpOutput.java:466)
        at org.eclipse.jetty.ee8.nested.Response.completeOutput(Response.java:852)
        at org.eclipse.jetty.ee8.nested.HttpChannel.handle(HttpChannel.java:553)
        at org.eclipse.jetty.ee8.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2376)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)
        at org.eclipse.jetty.server.Server.handle(Server.java:182)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
        at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:414)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
RFC7230 allows a Content-Length on 304 responses, see #4208.
The pull request that introduced this control: #10948.

### PR DESCRIPTION
**Pull request by gregw**
Fix #12481 Allow Content-Length header to be set with a 304 response Follow RFC9110 recommendations for headers to be sent with 304 response.

### CODE REVIEW

**Comment by gregw** [comment]
@joakime technically, we should be setting the etag with 304 responses, but it is too difficult for the GzipResponse wrapper to know if the response would have been compressed or not, and thus it cannot tell if the etag should have the suffix appended.
We can do so if there is an If-Match header, as we know how the previous response was compressed.   

All in all, looking for a better solution.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java [hunk 1]
```diff
@@ -728,55 +736,55 @@ protected void writeHttpContent(Request request, Response response, Callback cal
...
-//            HttpHeader.CONTENT_ENCODING,
-//            HttpHeader.ETAG,
-//            HttpHeader.ACCEPT_RANGES,
-//            HttpHeader.CACHE_CONTROL
-//            ));
-//        HttpField lm = content.getLastModified();
-//        if (lm != null)
-//            headers.add(lm);
-//        etc.
+        HttpFields.Mutable headers = response.getHeaders();
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:739]: You removed the TODO but did not handle its concern. Are we giving up on those?

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerTest.java [hunk 2]
```diff
@@ -1480,6 +1480,7 @@ public void testCachingPrecompressedFilesCachedEtagged() throws Exception
                     \r
                     """.formatted(eTag1)));
             assertThat(response3.getStatus(), is(HttpStatus.NOT_MODIFIED_304));
+            assertThat(response3.getField(ETAG), notNullValue());
```
Comment (lorban) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerTest.java:1483]: Shouldn't `Content-Length` and `Last-Modified` be asserted too?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java [hunk 3]
```diff
@@ -58,6 +59,12 @@ public class ResourceService
     private static final Logger LOG = LoggerFactory.getLogger(ResourceService.class);
     private static final int NO_CONTENT_LENGTH = -1;
     private static final int USE_KNOWN_CONTENT_LENGTH = -2;
+    public static final EnumSet<HttpHeader> CONTENT_HEADERS = EnumSet.of(
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java]: Make it `private`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java [hunk 4]
```diff
@@ -58,6 +59,12 @@ public class ResourceService
...
+        HttpHeader.LAST_MODIFIED,
+        HttpHeader.CONTENT_LENGTH,
+        HttpHeader.CONTENT_TYPE
+    );
+    public static final PreEncodedHttpField ACCEPT_RANGES_BYTES = new PreEncodedHttpField(HttpHeader.ACCEPT_RANGES, "bytes");
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java]: This should be `private` too.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java [hunk 5]
```diff
@@ -728,55 +736,55 @@ protected void writeHttpContent(Request request, Response response, Callback cal
...
+                headers.add(et);
+        }
+
+        // Existing content encoding is kept only if not set for content.
+        HttpField ce = content.getContentEncoding();
+        if (ce != null)
+            headers.put(ce);
+
+        // Remove content headers and re-add if we have them
+        headers.remove(CONTENT_HEADERS);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:755]: Is it ok to remove these headers if they have been added by the application?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java [hunk 6]
```diff
@@ -728,55 +736,55 @@ protected void writeHttpContent(Request request, Response response, Callback cal
...
+        putHeaders(response);
+    }
 
-        if (_etags)
-        {
-            HttpField et = content.getETag();
-            if (et != null)
-                response.getHeaders().put(et);
-        }
+    protected void putNotModifiedHeaders(Response response, HttpContent content)
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:770]: Make it `private`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java [hunk 7]
```diff
@@ -728,55 +736,55 @@ protected void writeHttpContent(Request request, Response response, Callback cal
...
+            headers.put(lm);
 
-        if (_acceptRanges && !response.getHeaders().contains(HttpHeader.ACCEPT_RANGES))
-            response.getHeaders().put(new PreEncodedHttpField(HttpHeader.ACCEPT_RANGES, "bytes"));
-        if (_cacheControl != null && !response.getHeaders().contains(HttpHeader.CACHE_CONTROL))
-            response.getHeaders().put(_cacheControl);
+        putHeaders(response);
+    }
+
+    protected void putHeaders(Response response)
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:781]: Make it `private`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:739]: I addressed it as much as I could.  See 755

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java (hunk 5 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:755]: We were doing that before with put

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java (hunk 6 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:770]: protected so the service can be extended.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java (hunk 7 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:781]: protected so the service can be extended

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerTest.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/handler/ResourceHandlerTest.java:1483]: The RFC says ETAG or Last-Modified and stresses we should minimize bytes.
It does not say we SHOULD/MUST send content-length, but says it MAY be sent.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:739]: You're talking about the bit of the TODO that speaks about not overriding the headers if they come from a servlet filter? I'm talking about the fact that there are many `add` and `put` calls and that each one is rather expensive. AFAICT this hasn't changed so maybe that TODO could be left in place.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java:739]: @lorban we are talking about the same thing.
line 755 removes 3 headers that are then added back, instead of 3 puts.

I could not do that with more headers, because the other headers have differing logic about existing headers, which I have attempted to explain in the comments.

**Review by sbordet — APPROVED** [review]

**Review by lorban — APPROVED** [review]
