### PR TITLE
Issue #6654 - Fix NPEs from bad Servlet API use

### LINKED ISSUE #6654: ServerUpgradeRequest.getCookies() can throws NullPointerException
https://github.com/eclipse/jetty.project/blob/b2c420a124392b3e79a6abf263ec00f51e387409/jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java#L93

Hi,
request.getCookies() can be null and this code can throws a NullPointerException

### PR DESCRIPTION
**Pull request by joakime**
Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

File: jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java [hunk 1]
```diff
@@ -135,10 +140,13 @@ public int getHeaderInt(String name)
     {
         Map<String, List<String>> headers = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
         Enumeration<String> headerNames = request.getHeaderNames();
-        while (headerNames.hasMoreElements())
+        if (headerNames != null)
```
Comment (joakime) [inline jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java:147]: The servlet spec indicates that this can also be null.

File: jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java [hunk 2]
```diff
@@ -90,9 +91,13 @@ public ServerUpgradeRequest(WebSocketNegotiation negotiation) throws BadMessageE
...
-            cookies = Arrays.stream(request.getCookies())
-                .map(c -> new HttpCookie(c.getName(), c.getValue()))
-                .collect(Collectors.toList());
+            Cookie[] reqCookies = request.getCookies();
+            if (reqCookies != null)
+            {
+                cookies = Arrays.stream(reqCookies)
+                    .map(c -> new HttpCookie(c.getName(), c.getValue()))
+                    .collect(Collectors.toList());
+            }
```
Comment (sbordet) [inline jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java:100]:
```suggestion
            }
            else
            {
                cookies = List.of();
            }
```

**Review by sbordet — CHANGES_REQUESTED** [review]
I don't like returning `null` if there are no cookies, as it is prone to errors 😃

File: jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java (hunk 2 above)
Comment (joakime) [reply jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java:100]: done.

**Review by sbordet — DISMISSED** [review]

File: jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java [hunk 3]
```diff
@@ -90,9 +91,17 @@ public ServerUpgradeRequest(WebSocketNegotiation negotiation) throws BadMessageE
...
+            else
+            {
+                cookies = List.of();
```
Comment (lachlan-roberts) [inline jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java]: Shouldn't we also return null here if the request had no cookies?

Comment (gregw) [reply jetty-websocket/websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/ServerUpgradeRequest.java]: We had this discussion already recently and determined that `emptyList` was both more readable and more effficient.

```suggestion
                cookies = Collections.emptyList();
```

**Review by gregw — DISMISSED** [review]
one tiny niggle....

**Comment by joakime** [comment]
> one tiny niggle....

The call to `List.of()` is actually a call to `ImmutableCollections.emptyList()` (jvm package private class) already, which seems more correct than `Collections.emptyList()`.
All uses of `List.of(...)` result in immutable lists.

**Review by sbordet — APPROVED** [review]
