### PR TITLE
Fix #6565 Deploy Symlinked applications

### LINKED ISSUE #6565: Improve deployment of symlinked webapplications
**Target Jetty version(s)**
9, 10

**Enhancement Description**

After #6114 we can now deploy symlinked war files with the correct context path. eg.
```
   webapps
      + contextA.war -> /var/lib/myapp.war
      + contextB.war -> /var/lib/myapp.war
```
But the following does not work correctly:
```
   webapps
      + contextA -> /var/lib/myapp/
      + contextB -> /var/lib/myapp/
```

### PR DESCRIPTION
**Pull request by gregw**
Fix #6565 Deploy Symlinked applications by treating extracting context name (which becomes the default context path) from the base resource and then following aliases, so that base resource will not be an alias.   

Added warning in ContextHandler if the base resource is an alias that we may not support this in future releases.

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

File: jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/WebAppProvider.java [hunk 1]
```diff
@@ -265,8 +266,18 @@ public ContextHandler createContextHandler(final App app) throws Exception
...
             throw new IllegalStateException("App resource does not exist " + resource);
 
-        String context = file.getName();
+        final String contextName = file.getName();
 
+        // Resource aliases (after getting name) to ensure baseResource is not an alias
+        if (resource.isAlias())
+        {
+            resource = Resource.newResource(resource.getAlias());
+            file = resource.getFile().toPath().toRealPath().toFile();
```
Comment (lachlan-roberts) [inline jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/WebAppProvider.java]: Do we really need the `toRealPath()` here, shouldn't the `resource.getAlias()` already give you this?

Comment (gregw) [reply jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/WebAppProvider.java]: Maybe not, but I wanted to protect against changes to the implemention of Resource and also to deal with things like symlinks to symlinks.   Better to be safe than sorry.

Comment (lachlan-roberts) [reply jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/WebAppProvider.java]: Maybe then you should do something like:
```java
file = new File(resource.getAlias()).toPath().toRealPath().toFile();
resource = Resource.newResource(file);
```

so that `file` and `resource.getFile()` are the same.

Comment (gregw) [reply jetty-deploy/src/main/java/org/eclipse/jetty/deploy/providers/WebAppProvider.java]: very good point!

**Review by lachlan-roberts — APPROVED** [review]
LGTM

**Review by janbartel — APPROVED** [review]
I don't really like having different behaviour between distro and embedded (we go to a lot of lengths in other cases to ensure that they are the same), but I don't feel strongly enough to give it the thumbs down ;)

**Comment by gregw** [comment]
@janbartel I agree, but I'd like to go with the warning first and see what feedback we get.  If nobody comments, then we can update embedded behaviour in a later PR.
