### PR TITLE
Issue #14566 - Use GzipEncoderConfig syncFlush in CompressionHandler as well

### LINKED ISSUE #14566: CompressionHandler/GzipEncoderSink not respect setSyncFlush(true)
Jetty version(s)
12.1.6

Jetty Environment
ee8

HTTP version
1.1

Java version/vendor (use: java -version)

openjdk 25 2025-09-16 LTS
OpenJDK Runtime Environment Corretto-25.0.0.36.2 (build 25+36-LTS)
OpenJDK 64-Bit Server VM Corretto-25.0.0.36.2 (build 25+36-LTS, mixed mode, sharing)

OS type/version
macOS 15.7.2

Description

It appears there is a regression in `CompressionHandler` compared to `GzipHandler` where `setSyncFlush(true)` is not respected. Upon checking, the option is only used in `ConfigurableGzipOutputStream` but not in `GzipEncoderSink`.

**How to reproduce?**

Here is a minimal reproducible example:

```java
package com.drw.xd.services.hdf5;

import org.eclipse.jetty.compression.Compression;
import org.eclipse.jetty.compression.gzip.GzipCompression;
import org.eclipse.jetty.compression.gzip.GzipEncoderConfig;
import org.eclipse.jetty.compression.server.CompressionConfig;
import org.eclipse.jetty.compression.server.CompressionHandler;
import org.eclipse.jetty.ee8.servlet.ServletContextHandler;
import org.eclipse.jetty.io.ArrayByteBufferPool;
import org.eclipse.jetty.io.ByteBufferPool;
import org.eclipse.jetty.server.*;
import org.eclipse.jetty.util.thread.QueuedThreadPool;

import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

public class TestHttpCmd {

    public static class TestServlet extends HttpServlet
    {
        protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
        {
            try (ServletOutputStream out = response.getOutputStream()) {
                out.println("Response should be flushed immediately");
                out.flush();
                Thread.sleep(10000);
                out.println("Response Completed");
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }

    public static void main(String[] args) throws Exception {
        QueuedThreadPool threadPool = new QueuedThreadPool(200, 20);
        // ZSTD requires larger byte buffer: https://github.com/jetty/jetty.project/issues/14028#issuecomment-3581586722
        ByteBufferPool byteBufferPool = new ArrayByteBufferPool(0, 4096, 132 * 1024);
        Server server = new Server(threadPool, null, byteBufferPool);
        ServerConnector connector = new ServerConnector(server, new HttpConnectionFactory());
        connector.setPort(9090);
        server.addConnector(connector);

        CompressionHandler compressionHandler = new CompressionHandler();
        Compression gzip = new GzipCompression();
        GzipEncoderConfig encoderConfig = new GzipEncoderConfig();
        encoderConfig.setSyncFlush(true);
        gzip.setDefaultEncoderConfig(encoderConfig);
        compressionHandler.putCompression(gzip);
        compressionHandler.putConfiguration("/", CompressionConfig.builder()
                .defaults()
                .build()
        );

        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/");
        context.addServlet(TestServlet.class, "/test");
        compressionHandler.setHandler(context);

        server.setHandler(compressionHandler);
        server.start();
        server.join();
    }
}
```

### PR DESCRIPTION
**Pull request by joakime**
The previous code was only using `GzipEncoderConfig` `syncFlush` for `GzipCompression.newEncoderOutputStream` use cases, this PR also allows `syncFlush` for `GzipEncoderSink`, which in turn allows it for use in `CompressionHandler` as well.

Resolves #14566

### CODE REVIEW

File: jetty-core/jetty-compression/jetty-compression-gzip/src/main/java/org/eclipse/jetty/compression/gzip/internal/GzipEncoderSink.java [hunk 1]
```diff
@@ -228,7 +230,7 @@ private boolean encode(ByteBuffer content, ByteBuffer output)
             addInput(content);
 
         BufferUtil.clearToFill(output);
-        int len = deflater.deflate(output);
+        int len = deflater.deflate(output, Deflater.SYNC_FLUSH);
```
Comment (ZhaoMJ) [inline jetty-core/jetty-compression/jetty-compression-gzip/src/main/java/org/eclipse/jetty/compression/gzip/internal/GzipEncoderSink.java]:
```suggestion
        int len = deflater.deflate(output, this.flushMode);
```

**Review by sbordet — APPROVED** [review]
@joakime I fixed the use of `flushMode`.

**Review by olamy — APPROVED** [review]
