### PR TITLE
Issue #12918 NPE in AuthenticationState.ServeAs.wrap

### LINKED ISSUE #12918: NullPointerException with ServeAs requests (with FormAuthenticator)
**Jetty version(s)**
12.0.17 and 12.0.18

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
```
java version "17.0.14" 2025-01-21 LTS
Java(TM) SE Runtime Environment (build 17.0.14+8-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.14+8-LTS-191, mixed mode, sharing)
```

**OS type/version**
```
Linux everfree.forest 6.13.6-200.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar  7 21:33:48 UTC 2025 x86_64 GNU/Linux
```

**Description**
I'm back to working on ops4j/org.ops4j.pax.web#1802 which uses Jetty, Tomcat and Undertow as backends for OSGi CMPN specifications (Whiteboard - chapter 140, HttpService - chapter 102, Web Applications - chapter 128).

Pax Web 10 is finally going to use `jakarta.servlet` packages (including JSP/JSTL) and while Pax Web 8 used Jetty 9, Pax Web 9 used Jetty 10, Pax Web 10 will use Jetty 12.
I have _a lot_ of OSGi integration tests in Pax Web: https://github.com/ops4j/org.ops4j.pax.web/tree/main-jakarta-2025/pax-web-itest/pax-web-itest-container/pax-web-itest-jetty/src/test/java/org/ops4j/pax/web/itest/jetty

I have an issue with form authentication. I'll skip the "How to reproduce?" section and just describe what's the issue when Jetty is embedded in OSGi.

1. I have a web application with:
```xml
<login-config>
	<auth-method>FORM</auth-method>
	<form-login-config>
		<form-login-page>/login.jsp</form-login-page>
		<form-error-page>/loginError.jsp</form-error-page>
	</form-login-config>
</login-config>
<security-constraint>
	<web-resource-collection>
		<web-resource-name>Protected Area</web-resource-name>
		<description>Protect the Example Servlet</description>
		<url-pattern>/wc/example</url-pattern>
	</web-resource-collection>
	<auth-constraint>
		<description>Authorized Users Group</description>
		<role-name>admin</role-name>
	</auth-constraint>
</security-constraint>
```

2. When `org.eclipse.jetty.ee10.servlet.SessionHandler#handle()` is called for the first time, `org.eclipse.jetty.session.AbstractSessionManager.RequestedSession` object is created which is empty:
```
requestedSession = {org.eclipse.jetty.session.AbstractSessionManager$RequestedSession@15965} "RequestedSession[session=null, sessionId=null, sessionIdFromCookie=false]"
 session: org.eclipse.jetty.session.ManagedSession  = null
 sessionId: java.lang.String  = null
 sessionIdFromCookie: boolean  = false
```

3. `org.eclipse.jetty.security.SecurityHandler#handle()` uses `org.eclipse.jetty.security.authentication.FormAuthenticator` and its `FormAuthenticator#validateRequest()` creates new session.

4. `FormAuthenticator#validateRequest()` returns `org.eclipse.jetty.security.AuthenticationState` which is:
```
authenticationState = {org.eclipse.jetty.security.AuthenticationState$ServeAs@16390} 
 _uri: org.eclipse.jetty.http.HttpURI  = {org.eclipse.jetty.http.HttpURI$Mutable@16399} "http://127.0.0.1:8181/war-formauth/login.jsp"
```

5. security handler (which is an instance of `org.eclipse.jetty.ee10.servlet.security.ConstraintSecurityHandler`) sees that the auth state is `authenticationState instanceof AuthenticationState.ServeAs serveAs`, so `org.eclipse.jetty.security.AuthenticationState.ServeAs#wrap()` is called.

6. request object passed to `wrap()` method is:
```
request = {org.eclipse.jetty.ee10.servlet.ServletContextRequest@16155} "ServletContextRequest@1b5dd06e{GET@5e5f5d61 http://127.0.0.1:8181/war-formauth/wc/example HTTP/1.1}"
 ...
 _managedSession: org.eclipse.jetty.session.ManagedSession  = {org.eclipse.jetty.session.ManagedSession@16383} "ManagedSession@5008afbb{id=node01kdegovy65v791kytastxxmdij1~war-formauth##war-formauth,x=node01kdegovy65v791kytastxxmdij1~war-formauth##war-formauth.node0,req=1,res=true}"

 _requestedSession: org.eclipse.jetty.session.AbstractSessionManager$RequestedSession  = {org.eclipse.jetty.session.AbstractSessionManager$RequestedSession@15965} "RequestedSession[session=null, sessionId=null, sessionIdFromCookie=false]"
 ...
```

`_requestedSession` is empty, but not null and `_managedSession` is new session created by FormAuthenticator

However the request returned from `wrap()` is:
```
result = {org.eclipse.jetty.ee10.servlet.ServletContextRequest@16451} "ServletContextRequest@3b282452{@1c32fde3{ServletContextRequest@1b5dd06e{GET@5e5f5d61 http://127.0.0.1:8181/war-formauth/wc/example HTTP/1.1}}}"
 ...
 _request: org.eclipse.jetty.server.Request  = {org.eclipse.jetty.ee10.servlet.ServletContextRequest$2@16463} "@1c32fde3{ServletContextRequest@1b5dd06e{GET@5e5f5d61 http://127.0.0.1:8181/war-formauth/wc/example HTTP/1.1}}"
  _request: org.eclipse.jetty.server.Request  = {org.eclipse.jetty.ee10.servlet.ServletContextRequest@16155} "ServletContextRequest@1b5dd06e{GET@5e5f5d61 http://127.0.0.1:8181/war-formauth/wc/example HTTP/1.1}"
   ...
   _managedSession: org.eclipse.jetty.session.ManagedSession  = {org.eclipse.jetty.session.ManagedSession@16383} "ManagedSession@5008afbb{id=node01kdegovy65v791kytastxxmdij1~war-formauth##war-formauth,x=node01kdegovy65v791kytastxxmdij1~war-formauth##war-formauth.node0,req=1,res=true}"
   ...
   _requestedSession: org.eclipse.jetty.session.AbstractSessionManager$RequestedSession  = {org.eclipse.jetty.session.AbstractSessionManager$RequestedSession@15965} "RequestedSession[session=null, sessionId=null, sessionIdFromCookie=false]"
   ...
  ...
  uri: org.eclipse.jetty.http.HttpURI  = {org.eclipse.jetty.http.HttpURI$Mutable@16399} "http://127.0.0.1:8181/war-formauth/login.jsp"
 ...
 _requestedSession: org.eclipse.jetty.session.AbstractSessionManager$RequestedSession  = null
 ...
```

This wrapped request contains the original request, but has null value of `_requestedSession` (and `_managedSession`).

7. Eventually `org.apache.jasper.runtime.PageContextImpl#initialize()` gets requests session and hits NPE at:
```java
_sessionManager.newSession(this, _requestedSession.sessionId(), this::setManagedSession);
```

because `_requestedSession` is null...

### PR DESCRIPTION
**Pull request by janbartel**
Fixes #12918

As the `ServletContextRequest` fields `_requestedSession` and `_managedSession` are `private`, they must be explicitly set on the newly created instance in `ServletContextHandler.newServletContextRequest` when the passed-in request is itself a `ServletContextRequest`.

### CODE REVIEW

**Comment by joakime** [comment]
@gregw @janbartel ping, are we good to get this into 12.0.20?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java [hunk 1]
```diff
@@ -190,6 +190,11 @@ public HttpURI getHttpURI()
             decodedPathInContext,
             matchedResource
         );
+        if (request instanceof ServletContextRequest originalServletContextRequest)
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java]: But this will not work if the request is further wrapped.   So you probably need something like:
```suggestion
        ServletContextRequest originalServletContextRequest = Request.as(request, ServletContextRequest.class);
        if (originalServletContextRequest != null)
```

The `Request.as` will unwrap wrappers looking for the type.... but now I'm worried that will see through a cross context dispatch.  Perhaps we need to modify as so that it does not see through cross context dispatch?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java (hunk 1 above)
Comment (janbartel) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java]: @gregw ok, so how about we check that a context boundary isn't crossed as we do the unwrap?  See commit https://github.com/jetty/jetty.project/pull/13041/commits/62852e56321260f65b8cd5d22a30148b3f222e23

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 2]
```diff
@@ -1033,6 +1033,27 @@ static <T> T as(Request request, Class<T> type)
...
     }
 
+    /** Unwrap a Request back to the given type, ensuring that we do not cross a
+     * context boundary (as might be the case during cross-context dispatch).
+     * @param request the possibly wrapped request to unwrap
+     * @param type the type to unwrap to
+     * @param context the limiting context
+     * @return the request unwrapped back to the given type, or null if it cannot be
+     * unwrapped to that type or a context boundary is crossed.
+     */
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java:1050]: Add a @see as(Request,Class<T>) and can you give some javadoc for that method  too?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 3]
```diff
@@ -1033,6 +1033,27 @@ static <T> T as(Request request, Class<T> type)
...
+    {
+        while (request != null)
+        {
+            if (type.isInstance(request))
+                return (T)request;
+            request = request instanceof Request.Wrapper wrapper ? wrapper.getWrapped() : null;
+            if (request == null || request.getContext() != context)
+                return null;
+        }
+        return null;
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: I've change my mind on the order of the test, as it will avoid the double null check:

```suggestion
        while (request != null)
        {
            if (request.getContext() != context)
                return null;
            if (type.isInstance(request))
                return (T)request;
            request = request instanceof Request.Wrapper wrapper ? wrapper.getWrapped() : null;
        }
        return null;
```

**Review by gregw — CHANGES_REQUESTED** [review]
Can you look through any current callers of `as(...)` to see if there are others that should not cross a context boundary

**Comment by joakime** [comment]
As there is only 1 day left in this month, this PR is being pushed to next month's 12.0.21 release.

**Comment by janbartel** [comment]
> Can you look through any current callers of `as(...)` to see if there are others that should not cross a context boundary

Almost all of the usages of `Request.as` come from `ee10`, where we always wrap the inbound request on a cross context dispatch. So where the code is unwrapping to other `ee10` classes, then they will be guaranteed to be the first one on the stack.

There are 4 other usages of `Request.as` in core, 2 of them trivial. The other 2 are in `EagerFormHandler` and `GzipHandler`, both of which _should_ cross a cross context boundary.

So in short I think we're good where we are?

**Comment by joakime** [comment]
If the request enters ee10, gets cross-context-dispatched to something in ee9, which then also cross-context-dispatches to some other ee10 context, is that a problem?

**Comment by gregw** [comment]
IF we are looking for anything contexty (e.g. servlet API), then we should not cross context boundaries.
But if we are looking for anything that is not context related (e.g. gzip) then we can cross context boundaries.

**Review by gregw — CHANGES_REQUESTED** [review]
Can you add a test to check the assertion that we are ok with these unwraps in CCD?

**Comment by janbartel** [comment]
> If the request enters ee10, gets cross-context-dispatched to something in ee9, which then also cross-context-dispatches to some other ee10 context, is that a problem?

This should not be a problem. ee9 code does not use these `Request` methods, and ee10 wraps every time.

**Comment by janbartel** [comment]
> Can you add a test to check the assertion that we are ok with these unwraps in CCD?

It's actually very difficult to write tests for this, as the use of `Request.as` is way down in jetty code. Any tests can only indirectly confirm that the correct unwrap was done, rather than test directly.

I propose that we formalize your statement: 

> IF we are looking for anything contexty (e.g. servlet API), then we should not cross context boundaries.
> But if we are looking for anything that is not context related (e.g. gzip) then we can cross context boundaries.

By changing all uses of `Request.as` to match: if accessing anything "contexty" then we use the 3 param arg version of the method to ensure we don't cross a context boundary, otherwise we just use the current 2 param method (eg for `GzipHandler` and `EagerFormHandler`).

**Comment by janbartel** [comment]
@gregw I have implemented the changes we discussed, and added 2 unit tests: one for `Request.asInContext` and the other for `Response.asInContext`. Please re-review.

**Review by gregw — APPROVED** [review]
