### PR TITLE
Fixes to ConnectionLimit for use with WebSocket

### LINKED ISSUE #13324: ConnectionLimit doesn't work with WebSocket connections.
**Jetty version(s)**

The issue is reproduced for Jetty 12.0.20. It was most likely introduced by change: https://github.com/jetty/jetty.project/pull/12320/files where Set of accepting connections was replaced by simple counter.

**Jetty Environment**

Any
**Java version/vendor** `(use: java -version)`
Any
**OS type/version**
Any
**Description**
`org.eclipse.jetty.server.ConnectionLimit` is created to limit active connections that Jetty server is handling. However, internal logic of this class doesn't work properly for web socket connections. 
The problem is with `_accepting` counter: it is decremented for each onOpened call. In web socket case, onOpened called twice: for handshake and actual WS connection. So `_accepting` counter enters negative values and the behavior of limiter is broken. Logs:
```
14:25:16.140 [qtp1782580546-35-acceptor-0@3ca674fe-ServerConnector@740fb309{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}] DEBUG o.e.jetty.server.ConnectionLimit - Accepting (1+0) <= 5 java.nio.channels.SocketChannel[connected local=/[0:0:0:0:0:0:0:1]:8080 remote=/[0:0:0:0:0:0:0:1]:63507]
14:25:16.175 [qtp1782580546-36] DEBUG o.e.jetty.server.ConnectionLimit - Opened (0+1) <= 5 HttpConnection@4b126155::SocketChannelEndPoint@2c168a4[{l=/[0:0:0:0:0:0:0:1]:8080,r=/[0:0:0:0:0:0:0:1]:63507,OPEN,fill=-,flush=-,to=29/30000}{io=0/0,kio=0,kro=0}]->[HttpConnection@4b126155[p=HttpParser{s=START,0 of -1},g=HttpGenerator@2771ee38{s=START}]=>HttpChannelState@63c5b38f{handling=null, handled=false, send=SENDING, completed=false, request=null}]
14:25:16.222 [qtp1782580546-38] DEBUG o.e.jetty.server.ConnectionLimit - Closed (0+0) <= 5 HttpConnection@4b126155::SocketChannelEndPoint@2c168a4[{l=/[0:0:0:0:0:0:0:1]:8080,r=/[0:0:0:0:0:0:0:1]:63507,OPEN,fill=-,flush=-,to=1/30000}{io=0/0,kio=0,kro=1}]->[HttpConnection@4b126155[p=HttpParser{s=END,0 of -1},g=HttpGenerator@2771ee38{s=END}]=>HttpChannelState@63c5b38f{handling=null, handled=true, send=LAST_COMPLETE, completed=true, request=GET@2a4a534a http://localhost:8080/echo HTTP/1.1}]
14:25:16.222 [qtp1782580546-38] DEBUG o.e.jetty.server.ConnectionLimit - Opened (-1+1) <= 5 WebSocketConnection@3c760760::SocketChannelEndPoint@2c168a4[{l=/[0:0:0:0:0:0:0:1]:8080,r=/[0:0:0:0:0:0:0:1]:63507,OPEN,fill=-,flush=-,to=2/30000}{io=0/0,kio=0,kro=1}]->[WebSocketConnection@3c760760[SERVER,p=Parser@199c38ac[s=START,c=0,o=0x0,m=-,l=0],f=Flusher@6958aafa[IDLE][queueSize=0,aggregate=null],g=org.eclipse.jetty.websocket.core.internal.Generator@11706498]]
14:26:16.279 [qtp1782580546-21] DEBUG o.e.jetty.server.ConnectionLimit - Closed (-1+0) <= 5 WebSocketConnection@3c760760::SocketChannelEndPoint@2c168a4[{l=null,r=null,CLOSED,fill=-,flush=-,to=2/30000}{io=0/0,kio=-1,kro=-1}]->[WebSocketConnection@3c760760[SERVER,p=Parser@199c38ac[s=START,c=0,o=0x0,m=-,l=0],f=Flusher@6958aafa[FAILED][queueSize=0,aggregate=null],g=org.eclipse.jetty.websocket.core.internal.Generator@11706498]]
```

**How to reproduce?**
[Demo repo](https://github.com/ZadokhinDima/web-socket-connection-limit-jetty)
Run application with main class `org.example.websocketdemo.EchoServer`. It has connection limit configured to 5. 
Run python script in root folder. It will successfully open 20 connections.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Issue https://github.com/jetty/jetty.project/issues/13324

Change `ConnectionLimit` class to operate exclusively on TCP connections by adding a `onClosed` notification to the `AcceptListener` class.

This will make it work with `WebSocket` where the `HttpConnection` is closed and replaced with a `WebSocketConnection`.

When upgrading to WebSocket over HTTP/2 the `ConnectionLimit` will only apply to the single `HTTP2Connection`, and not to the multiple `WebSocketConnection`s which can be created over streams on this connection.

### CODE REVIEW

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WebSocketConnectionLimitTest.java [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+
+    @AfterEach
+    public void after() throws Exception
+    {
+        _client.stop();
+        _server.stop();
+    }
+
+    @Test
+    public void test() throws Exception
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WebSocketConnectionLimitTest.java]: Rename to `testConnectionLimit()`

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WebSocketConnectionLimitTest.java [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+        // Now additional connections can be opened without error.
+        TestMessageHandler clientHandler2 = new TestMessageHandler();
+        _client.connect(clientHandler2, uri).get(5, TimeUnit.SECONDS);
+        assertTrue(clientHandler2.openLatch.await(5, TimeUnit.SECONDS));
+        awaitConnections(1);
+        clientHandler2.getCoreSession().close(Callback.NOOP);
+        assertTrue(clientHandler2.closeLatch.await(5, TimeUnit.SECONDS));
+        assertThat(clientHandler2.closeStatus.getCode(), equalTo(CloseStatus.NO_CODE));
+        awaitConnections(0);
+    }
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WebSocketConnectionLimitTest.java]: Please add a test case where the WebSocket connection is closed from an `@OnWebSocketOpen` method of the endpoint.

Seems to me that the changes to `WebSocketConnection` do not have a correspondent test, and the test of closing from `@OnWebSocketOpen` should cover those changes?

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java [hunk 3]
```diff
@@ -85,12 +92,15 @@
 
 public class WebSocketOverHTTP2Test
 {
+    private static final int CONNECTION_LIMIT = 5;
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java]: Move this constant to the only test that uses it.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java [hunk 4]
```diff
@@ -138,6 +148,10 @@ protected void onComplete(Request request, int status, HttpFields headers, Throw
             }
         });
 
+        _connectionLimit = new ConnectionLimit(CONNECTION_LIMIT, connector, tlsConnector);
+        connector.addBean(_connectionLimit);
+        tlsConnector.addBean(_connectionLimit);
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-tests/src/test/java/org/eclipse/jetty/ee10/websocket/tests/WebSocketOverHTTP2Test.java]: Move to the test, you should be able to add the beans after start, and they will be seen when you `connect()`.

**Review by sbordet — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionLimit.java [hunk 5]
```diff
@@ -264,37 +264,31 @@ public void onAcceptFailed(SelectableChannel channel, Throwable cause)
...
             if (LOG.isDebugEnabled())
-                LOG.debug("Opened ({}+{}) <= {} {}", _accepting, _connections, _maxConnections, connection);
-            check();
+                LOG.debug("Accepted ({}+{}) <= {} {}", _accepting, _connections, _maxConnections, channel);
         }
     }
 
     @Override
-    public void onClosed(Connection connection)
+    public void onClosed(SelectableChannel channel)
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionLimit.java]: I was expecting this class to change to having two limits:
 + Channel limit: onAccepting, onAccepted - > onClosed(SelectableChannel)
 + Connection limit: onOpened(Connection) -> onClosed(Connection)

At the very least, the javadoc needs to be changed to explain that it is Channels that are being limited, not connections.  If we leave it as just that, then perhaps the class name needs to be changed as well?

If the class limits both, then its name can stay the same, but more javadoc is needed.

Alternately, we have both ChannelLimit and ConnectionLimit listeners?

**Review by gregw — CHANGES_REQUESTED** [review]

**Comment by joakime** [comment]
From conversation on weekly call...

Deprecate `ConnectionLimit`, copy code to new `NetworkConnectionLimit`.
Limits based on HTTP/2 streams will be handled by other things, like `QoSHandler`.

**Comment by gregw** [comment]
Create another class to limit virtual connections (channels)... Maybe in a different PR

**Comment by sbordet** [comment]
I'm working on this.

**Review by gregw — DISMISSED** [review]

**Review by lachlan-roberts — COMMENTED** [review]
LGTM

**Review by sbordet — APPROVED** [review]
