### PR TITLE
Issue #13268 Ensure charset source is reset after content-type reset if it came from the content-type

### LINKED ISSUE #13268: `charset=null` is automatically added when using `Content-Type: application/problem+json` in Servlet ee10
**Jetty version(s)**
12.0.8

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
JDK17 / temurin

**OS type/version**
Mac / Sequoia 15.5

**Description**
I was debugging Spring-Framework issue.
I think Jetty's ServletApiResponse has a bug.

In summarize, 
ServletApiResponse add 'charset=null' when set Content-Type following order.
- application/json
- null
- application/problem+json

Image

**How to reproduce?**
In the following order, set Content-Type.
- application/json
- null
- application/problem+json

Here's origin issue from Spring-Framework.
https://github.com/spring-projects/spring-framework/issues/35087

### PR DESCRIPTION
**Pull request by janbartel**
closes #13268

### CODE REVIEW

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java [hunk 1]
```diff
@@ -596,6 +596,9 @@ public boolean onRemoveField(HttpField field)
                             case SET_CHARACTER_ENCODING, SET_LOCALE -> _characterEncoding;
                             default -> null;
                         };
+                        //if we obtained the encoding from the content type, then reset it as we've just removed the content-type
+                        if (_encodingFrom == EncodingFrom.SET_CONTENT_TYPE)
+                            _encodingFrom = EncodingFrom.NOT_SET;
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java]: Do this in the default case above.

**Review by gregw — CHANGES_REQUESTED** [review]

**Review by gregw — APPROVED** [review]
