### PR TITLE
Fix `HttpChannelState` mistakenly aborting in certain cases when the `ErrorHandler` is successfully writing back a response

### LINKED ISSUE #14327: Flaky jetty-client behavior against ee11 and bad URLs
**Jetty version(s)**
12.1.x

**Jetty Environment**
All, including Core

**HTTP version**
HTTP/1.1

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
When using jetty-client and HTTP/1.1 against an ee11 webapp that has bad Request Path, it's possible for the jetty-client to fail before receiving the 400 response.

This can be replicated in the `ee11-demo-spec-6-1` test webapp, using one of the following URLs.

```
http://localhost:8080/ee11-demo-spec-6-1/foo%2Fbar
http://localhost:8080/ee11-demo-spec-6-1/foo//bar
http://localhost:8080/ee11-demo-spec-6-1/foo/..;/bar
http://localhost:8080/ee11-demo-spec-6-1/foo/%2e%2e;param/bar
```

There's no error or exception seen on the server side.

There's 3 kinds of stacktraces seen when this occurs ...

1. **org.eclipse.jetty.io.EofException**

```
java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:345)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:440)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2094)
	at org.eclipse.jetty.client.transport.HttpRequest.send(HttpRequest.java:731)
	at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:379)
	at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:364)
	at org.eclipse.jetty.tests.distribution.DemoModulesTests.testSpec(DemoModulesTests.java:451)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:118)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:465)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:309)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:288)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:350)
	at org.eclipse.jetty.client.transport.internal.HttpSenderOverHTTP$HeadersCallback.process(HttpSenderOverHTTP.java:220)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:377)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:354)
	at org.eclipse.jetty.client.transport.internal.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:77)
	at org.eclipse.jetty.client.transport.HttpSender$ContentSender.process(HttpSender.java:576)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:377)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:354)
	at org.eclipse.jetty.client.transport.HttpSender.send(HttpSender.java:86)
	at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.send(HttpChannelOverHTTP.java:86)
	at org.eclipse.jetty.client.transport.HttpChannel.send(HttpChannel.java:143)
	at org.eclipse.jetty.client.transport.HttpConnection.send(HttpConnection.java:113)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:396)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:173)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:453)
	at org.eclipse.jetty.client.transport.HttpDestination.process(HttpDestination.java:414)
	at org.eclipse.jetty.client.transport.HttpDestination.process(HttpDestination.java:368)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:351)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:345)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:322)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:300)
	at org.eclipse.jetty.client.transport.HttpRequest.sendAsync(HttpRequest.java:799)
	at org.eclipse.jetty.client.transport.HttpDestination.send(HttpDestination.java:295)
	at org.eclipse.jetty.client.transport.HttpRequest.send(HttpRequest.java:772)
	at org.eclipse.jetty.client.CompletableResponseListener.send(CompletableResponseListener.java:79)
	... 4 more
Caused by: java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpenAndConnected(SocketChannelImpl.java:224)
	at java.base/sun.nio.ch.SocketChannelImpl.implWrite(SocketChannelImpl.java:587)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:627)
	at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:633)
	at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:112)
	... 32 more
```

2. **java.io.EOFException**

```
java.util.concurrent.ExecutionException: java.io.EOFException: oejcti.HttpConnectionOverHTTP@38409962::oeji.SocketChannelEndPoint@3c7f0ab2[{l=/127.0.0.1:50484,r=localhost/127.0.0.1:42621,ISHUT,fill=-,flush=-,to=0/30000}{io=0/0,kio=0,kro=1}]->[oejcti.HttpConnectionOverHTTP@38409962(l:/127.0.0.1:50484 <-> r:localhost/127.0.0.1:42621,closed=false)=>oejcti.HttpChannelOverHTTP@797d9359(exchange=HttpExchange@74f974c5{req=oejct.HttpRequest[GET /ee11-demo-spec-6-1/foo//bar HTTP/1.1]@48ce68b1[TERMINATED/null] res=HttpResponse[null 0 null]@ca0d180[PENDING/null]})[send=oejcti.HttpSenderOverHTTP@19526c16(req=QUEUED,failure=null)[oejh.HttpGenerator@26326ca5{s=START}],recv=oejcti.HttpReceiverOverHTTP@1d820332(ex=HttpExchange@74f974c5{req=oejct.HttpRequest[GET /ee11-demo-spec-6-1/foo//bar HTTP/1.1]@48ce68b1[TERMINATED/null] res=HttpResponse[null 0 null]@ca0d180[PENDING/null]},rsp=IDLE,failure=null)[oejh.HttpParser{s=CLOSED,0 of -1}]]]
	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:442)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2119)
	at org.eclipse.jetty.client.transport.HttpRequest.send(HttpRequest.java:731)
	at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:379)
	at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:364)
	at org.eclipse.jetty.tests.distribution.DemoModulesTests.testSpec(DemoModulesTests.java:458)
Caused by: 
java.io.EOFException: oejcti.HttpConnectionOverHTTP@38409962::oeji.SocketChannelEndPoint@3c7f0ab2[{l=/127.0.0.1:50484,r=localhost/127.0.0.1:42621,ISHUT,fill=-,flush=-,to=0/30000}{io=0/0,kio=0,kro=1}]->[oejcti.HttpConnectionOverHTTP@38409962(l:/127.0.0.1:50484 <-> r:localhost/127.0.0.1:42621,closed=false)=>oejcti.HttpChannelOverHTTP@797d9359(exchange=HttpExchange@74f974c5{req=oejct.HttpRequest[GET /ee11-demo-spec-6-1/foo//bar HTTP/1.1]@48ce68b1[TERMINATED/null] res=HttpResponse[null 0 null]@ca0d180[PENDING/null]})[send=oejcti.HttpSenderOverHTTP@19526c16(req=QUEUED,failure=null)[oejh.HttpGenerator@26326ca5{s=START}],recv=oejcti.HttpReceiverOverHTTP@1d820332(ex=HttpExchange@74f974c5{req=oejct.HttpRequest[GET /ee11-demo-spec-6-1/foo//bar HTTP/1.1]@48ce68b1[TERMINATED/null] res=HttpResponse[null 0 null]@ca0d180[PENDING/null]},rsp=IDLE,failure=null)[oejh.HttpParser{s=CLOSED,0 of -1}]]]
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:550)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1805)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:323)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parseAndFill(HttpReceiverOverHTTP.java:252)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:85)
	at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:97)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:267)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP$FillableCallback.succeeded(HttpConnectionOverHTTP.java:458)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:54)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:492)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.epcRunTask(AdaptiveExecutionStrategy.java:428)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:401)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:255)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:204)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:317)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:1009)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1239)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1194)
	at java.base/java.lang.Thread.run(Thread.java:1447)
```

3. **java.nio.channels.AsynchronousCloseException**

```
java.util.concurrent.ExecutionException: java.nio.channels.AsynchronousCloseException

	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:442)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2119)
	at org.eclipse.jetty.client.transport.HttpRequest.send(HttpRequest.java:731)
	at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:379)
	at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:364)
	at org.eclipse.jetty.tests.distribution.DemoModulesTests.testSpec(DemoModulesTests.java:458)
Caused by: java.nio.channels.AsynchronousCloseException
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:302)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:548)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1805)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:323)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parseAndFill(HttpReceiverOverHTTP.java:252)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:85)
	at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:97)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:267)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP$FillableCallback.succeeded(HttpConnectionOverHTTP.java:458)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:54)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:492)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.epcRunTask(AdaptiveExecutionStrategy.java:428)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:401)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:255)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:204)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:317)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:1009)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1239)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1194)
	at java.base/java.lang.Thread.run(Thread.java:1447)
```

### PR DESCRIPTION
**Pull request by lorban**
While working on the overhaul of the `ComplianceViolation.Listener` reporting (https://github.com/jetty/jetty.project/pull/14090), an unrelated bug surfaced: we sometimes abort a response after the `ErrorHandler` manages to successfully write a response without even adding the `Connection: close` header.

This is wrong from an HTTP protocol perspective: since the client isn't told that the connection is going to be closed by the server, it may attempt to reuse it to send another request which it may fail writing, or fail reading the response, or be lucky enough to write the request and read the response before the TCP connection actually is closed.

This PR is about making the necessary changes so that when the `ErrorHandler` manages to successfully write a response, the connection is never aborted while it always is when writing the response fails (network issue) or the response was already committed.

Fixes https://github.com/jetty/jetty.project/issues/14327

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 1]
```diff
@@ -1812,19 +1852,9 @@ public void succeeded()
...
-            {
-                _stream.send(_request._metaData, responseMetaData, true, null,
-                    Callback.from(() -> httpChannelState._lastWriteCallback.failed(failure),
-                        x ->
-                        {
-                            ExceptionUtil.addSuppressedIfNotAssociated(failure, x);
-                            httpChannelState._lastWriteCallback.failed(failure);
-                        }));
-            }
+                _stream.send(_request._metaData, responseMetaData, true, null, httpChannelState._lastWriteCallback);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Access of `httpChannelState._lastWriteCallback` out of lock.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by gregw — CHANGES_REQUESTED** [review]
1st shot a what?   please remember to link to issues and give descriptions, so those somewhat out of the loop can help out.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Done.

**Comment by lorban** [comment]
@gregw I've updated the title and description of this issue to explain what these changes are about.

While this PR was just a draft not yet ready to be reviewed, I do agree that I'm often too laconic in my descriptions so I as a New Year's resolution I decided to work on that and be more descriptive. :smile:

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java [hunk 2]
```diff
@@ -188,7 +188,11 @@ public void onFillable()
                     // must be called as the last release for it to be able to null out the
                     // inputBuffer field exactly when the latter isn't used anymore.
                     if (parse(inputBuffer.getByteBuffer()))
+                    {
+                        if (stream == null && inputBuffer.isEmpty())
+                            releaseInputBuffer();
```
Comment (gregw) [inline jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java:193]: Is this another bug found along the way?

File: jetty-core/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ReverseProxyTest.java [hunk 3]
```diff
@@ -169,14 +170,10 @@ public boolean handle(Request request, Response response, Callback callback)
...
-//                response.write(true, null, callback);
-
-                // With HTTP/1.1, succeeding the callback before the actual last write
-                // results in skipping the ErrorHandler and aborting the response and
-                // the connection, which the proxy interprets as a 502.
-                // HTTP/2 always behaves by aborting the connection.
+                // With HTTP/1.1, calling response.write() or callback.succeeded()
+                // would trigger ErrorHandler and result in a 500 to the proxy.
+                // With HTTP/2, the HpackContext cannot be rolled back, so the
+                // connection is aborted, which the proxy interprets as a 502.
```
Comment (gregw) [inline jetty-core/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ReverseProxyTest.java:176]: which raises the question.... what does HTTP/3 do?

File: jetty-core/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ReverseProxyTest.java [hunk 4]
```diff
@@ -215,8 +212,16 @@ protected void onServerToProxyResponseFailure(Request clientToProxyRequest, org.
...
+        if (httpVersion.compareTo(HttpVersion.HTTP_2) < 0)
+        {
+            assertFalse(serverToProxyFailureLatch.await(1, TimeUnit.SECONDS));
+            assertEquals(HttpStatus.INTERNAL_SERVER_ERROR_500, response.getStatus());
+        }
+        else
+        {
+            assertTrue(serverToProxyFailureLatch.await(5, TimeUnit.SECONDS));
+            assertEquals(HttpStatus.BAD_GATEWAY_502, response.getStatus());
+        }
```
Comment (gregw) [inline jetty-core/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ReverseProxyTest.java:225]: Ah so HTTP/3 can't be rolled back either, so the comment above needs to be more generic

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 5]
```diff
@@ -611,6 +614,22 @@ private boolean lockedLastStreamSend()
         return true;
     }
 
+    private Throwable lockedCompleteStreamFailure()
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: javadoc would be nice.  Also I think the name `lockedGetMostSignificantFailure` would be better

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 6]
```diff
@@ -611,6 +614,22 @@ private boolean lockedLastStreamSend()
...
+            return null;
+        Throwable completeStreamFailure = _lastWriteFailure;
+        if (completeStreamFailure == null)
+            completeStreamFailure = _writeFailure;
+        if (completeStreamFailure == null)
+            completeStreamFailure = _consumeAvailableFailure;
+        // Check for committed response with a non-last write then throwing an exception.
+        if (completeStreamFailure == null)
+            completeStreamFailure = _callbackFailure;
+        return completeStreamFailure;
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Would this be clearer and also more defensive:

```suggestion   
        ExceptionUtil.addSuppressedIfNotAssociated(_consumeAvailableFailure, _callbackFailure);
        ExceptionUtil.addSuppressedIfNotAssociated(_writeFailure, _consumeAvailableFailure);
        ExceptionUtil.addSuppressedIfNotAssociated(_writeFailure, _callbackFailure);
     
        return Objects.requireNonNullElse(_lastWriteFailure, 
            Objects.requireNonNullElse(_writeFailure, 
            Objects.requireNonNullElseGet(_consumeAvailableFailure, 
                () -> new IllegalStateException("No failure"))));
```

Or do a better `ExceptionUtil.combineElseGet(Throwable... throwables, Supplier<Throwable> dftEx)`

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 7]
```diff
@@ -731,7 +753,7 @@ public void run()
             }
 
             HttpStream stream;
-            Throwable failure;
+            Throwable completeStreamFailure;
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:754]: this now reads strangely that you have 3 specific types of failure as fields, but this one is not?

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:754]: Ah I see, this is the actual failure...  I think keep it `failure` is clearer.  Or perhaps `mostSignificantFailure`?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 8]
```diff
@@ -792,16 +810,20 @@ private void completeLastWrite(Throwable failure)
...
             try (AutoLock ignored = _lock.lock())
             {
                 assert _callbackCompleted;
-                _streamSendState = StreamSendState.LAST_COMPLETE;
+                _streamSendState = failure == null ? StreamSendState.LAST_COMPLETE : StreamSendState.FAILED;
                 completeStream = _handling == null; // if we have not handled yet or have completed handling
                 stream = _stream;
-                failure = _callbackFailure = ExceptionUtil.combine(_callbackFailure, failure);
+                _lastWriteFailure = failure;
+                _callbackFailure = ExceptionUtil.combine(failure, _callbackFailure);
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Oh you are combining here?  Should you not null the lastWriteFailure then? confused

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 9]
```diff
@@ -125,6 +125,9 @@ private enum StreamSendState
     private Predicate<TimeoutException> _onIdleTimeout;
     private Content.Chunk _readFailure;
     private Consumer<Throwable> _onFailure;
+    private Throwable _consumeAvailableFailure;
+    private Throwable _writeFailure;
+    private Throwable _lastWriteFailure;
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:130]: It is entirely unclear to me why 3 failures fields are required?   Why can they not just be combined as set into a single `_failure` field?   Also it is very hard to work out the difference between lastWF and WF?   I think this code is likely to be fragile and easily broken by changes with lack of understanding.

**Review by gregw — CHANGES_REQUESTED** [review]
Basically I find the changes very confusing.  I need to spend more time to work out exactly why so many failure fields... which makes the code fragile to future changes.

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java:193]: Correct.

File: jetty-core/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ReverseProxyTest.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ReverseProxyTest.java:176]: Probably the same as HTTP/2: we don't have the ability to roll back the QpackContext.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 9 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:130]: Three fields are clearer because they tell which failure actually happened.

With a single field, there is no indication of which stage failed.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I disagree on the rename, "mostSignificant" with respect to what?
The current name explicitly carries the information that we want the failure to fail the stream, if any.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 6 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Not a fan. The if/else is clearer.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 7 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:754]: It actually is the failure to use to complete the stream, so I think the naming is correct.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 8 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: @lorban I agree that it is strange that we assign `_callbackFailure` here, as this is the place to handle last writes.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 5 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: > I disagree on the rename, "mostSignificant" with respect to what? The current name explicitly carries the information that we want the failure to fail the stream, if any.

@sbordet I think this goes to my confusion about this PR.... this method is selecting a throwable based on try-A-try-B-try-C logic looking for a non null exception.   But then there is other logic when A, B & C are set that either sometimes combines A & B or moves B to C.     I find the logic impenetrable and don't understand what distinctions are being made between A, B & C?        I think it would be better to have a single `_failure` field and then some other boolean (or state machine) that captures any different behaviour needed depending on the source/status of that failure.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 6 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I'm not a fan of the entire method.....see above.
But at the very least it needs to add suppressed if there are more than 1 failures.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 7 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:754]: yeah the naming is correct.... but because the other 3 have special names too, the name looks like a 4th special exception type.    Getting rid of the other 3 fields would help....  or a better name for the method that selects the `completeStreamFailure`... how about `lockedGetCompeteStreamFailure`?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 9 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:130]: But WHY do we need to know what failure actually happened, at least more than the Throwable itself tells us?   That is what I'm not understanding.

I'd prefer a single failure field and a separate boolean/state that holds anything we need for failure handling logic.

Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:130]: Because when we debug tests that fail, and further debug what's going on in `HttpChannelState`, it is useful to know which failure is which.
A single failure will just hide the internal workings.

**Comment by joakime** [comment]
Is this work overlapping with #14371 ?

**Comment by sbordet** [comment]
@joakime yes, but it was better to pull it out from that PR.

**Comment by sbordet** [comment]
@gregw please re-review if you can, we have incorporated some of your suggestions.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 9 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:130]: @sbordet I understand all that... what I don't understand is what are the "internal workings" that need to care about what type of failure it is?   That is not clear?  Nor is it clear why that can't be in separate state.

**Review by sbordet — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 9 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:130]: @gregw a human debugging that code would rather see 3 fields than having to go to 1 field, introspect the suppressed exceptions, and from those figure out whether there was a write failure or a consume available failure.
Adding booleans or a state machine to separate the cases is more complex than having the 3 separate failure fields.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 7 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:754]: Renamed to `lockedGetCompleteStreamFailure()`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: There is some other logic, especially in `ChannelCallback` that combines exception to perform local logic, for example turning a `callback.succeeded()` into a failure if there is a read pending or a write pending.
The local logic decides whether to call `ErrorHandler`, or just notify the application, etc.

Then, later, when the 3 legs are done, we need to decide whether to fail the stream or not, so we look at the failures, combine them, but it is a different combination.

I'm not seeing how having a single failure would help, and I find much clearer that at stream completion time I can look at the failures to decide whether to fail the stream or not.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 9 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: @sbordet in case you had not noticed.... I am a human and I still do not know why the 3 fields are needed.  I've looked at the code, asked for comments or explanation and you have not been able to do so.
