### PR TITLE
Issue #5320 - using jetty-websocket-httpclient.xml within webapp

### LINKED ISSUE #5320: Using WebSocketClient with jetty-websocket-httpclient.xml in a Jetty web application causes ClassCastException
**Jetty version**
9.4.31
**Java version**
OpenJDK 1.8.0_251
**OS type/version**
Windows 10 64 bit
**Description**
Typically, using a JSR-356 javax.websocket.ClientEndpoint annotated websocket client with the javax.websocket.ContainerProvider$WebSocketContainer works fine within a Jetty web application. 

However, when you add the jetty-websocket-httpclient.xml file to perform any configuration (e.g. for the ssl context factory) you will see an exception similar to below.

```
java.lang.ClassCastException: org.eclipse.jetty.client.HttpClient cannot be cast to org.eclipse.jetty.client.HttpClient
    at org.eclipse.jetty.websocket.client.XmlBasedHttpClientProvider.get (XmlBasedHttpClientProvider.java:41)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.eclipse.jetty.websocket.client.HttpClientProvider.get (HttpClientProvider.java:37)
    at org.eclipse.jetty.websocket.client.WebSocketClient.<init> (WebSocketClient.java:264)
    at org.eclipse.jetty.websocket.jsr356.ClientContainer.<init> (ClientContainer.java:158)
    at org.eclipse.jetty.websocket.jsr356.server.ServerContainer.<init> (ServerContainer.java:94)
    at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.initialize (WebSocketServerContainerInitializer.java:210)
    at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.onStartup (WebSocketServerContainerInitializer.java:277)
    at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup (ContainerInitializer.java:145)
    at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart (ServletContainerInitializersStarter.java:64)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:72)
...
```
This can easily be reproduced by creating a new web-app that contains only a basic jetty.xml, web.xml and jetty-websocket-httpclient.xml (and pom.xml assuming you are using maven). The above ClassCastException will be thrown shortly before the "Started Jetty Server" message.

On a possibly related note, if you instead use the Jetty implemented websocket (org.eclipse.jetty.websocket.client.WebSocketClient) and use the constructor that takes an HttpClient you receive a LinkageError similar to this:
```
java.lang.LinkageError: loader constraint violation: when resolving method "org.eclipse.jetty.websocket.client.WebSocketClient.<init>(Lorg/eclipse/jetty/client/HttpClient;)V" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, com/example/WebSocketClientWrapper, and the class loader (instance of org/codehaus/plexus/classworlds/realm/ClassRealm) for the method's defining class, org/eclipse/jetty/websocket/client/WebSocketClient, have different Class objects for the type org/eclipse/jetty/client/HttpClient used in the signature
	at com.example.WebSocketClientWrapper.<init>(WebSocketClientWrapper.java:23)
...
```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Issue #5320**

Run the `jetty-websocket-httpclient.xml` with server class access if `WebAppClassLoader` is available.

### CODE REVIEW

File: tests/test-webapps/test-websocket-client-webapp/src/main/java/org/eclipse/jetty/tests/webapp/websocket/WebSocketClientServlet.java [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+    {
+
+        WebSocketClient client = null;
+        try
+        {
+            client = new WebSocketClient();
+            WebSocketClient finalClient = client;
+            runThrowExceptionsAsRuntime(() -> finalClient.start());
+            resp.setContentType("text/html");
+            //resp.getWriter().println("ConnectTimeout: " + client.getHttpClient().getConnectTimeout());
```
Comment (lachlan-roberts) [inline tests/test-webapps/test-websocket-client-webapp/src/main/java/org/eclipse/jetty/tests/webapp/websocket/WebSocketClientServlet.java]: With these changes the WebSocketClient can load and use the jetty-websocket-httpclient XML file with server class access, but we still don't have access to classes like `HttpClient` in the webapp. So this line will result in an exception.

And if instead of doing the line `runThrowExceptionsAsRuntime(() -> finalClient.start());` and I do as intellij suggests and use `runThrowExceptionsAsRuntime(finalClient::start);` then I get an exception as it doesn't know `LifeCycle`.

Comment (sbordet) [reply tests/test-webapps/test-websocket-client-webapp/src/main/java/org/eclipse/jetty/tests/webapp/websocket/WebSocketClientServlet.java]: I don't think you need `ThrowingRunnable` (can't you use `Callable` instead?).
Plus it's not clear what line is the problem -- there should be a comment in the code if it's non trivial due to class loading.
I'd like an explanation that there are 2 cases (webapp classes vs server classes), and what happens in each case.

File: tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java [hunk 2]
```diff
@@ -301,4 +308,91 @@ public void testLog4j2ModuleWithSimpleWebAppWithJSP() throws Exception
...
+                // "jetty.webapp.addServerClasses+=,-org.eclipse.jetty.util.component."
+            };
+
+            try (DistributionTester.Run run2 = distribution.start(args2))
+            {
+                assertTrue(run2.awaitConsoleLogsFor("Started @", 10, TimeUnit.SECONDS));
+
+                // We should get the correct configuration from the jetty-websocket-httpclient.xml file.
+                startHttpClient();
+                URI serverUri = URI.create("ws://localhost:" + port + "/test");
```
Comment (sbordet) [inline tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java]: I'd like to see also a test case for `wss`, as loading the SSL classes may have a similar problem to loading the http client classes.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: tests/test-webapps/test-websocket-client-webapp/src/main/java/org/eclipse/jetty/tests/webapp/websocket/WebSocketClientServlet.java (hunk 1 above)
Comment (lachlan-roberts) [reply tests/test-webapps/test-websocket-client-webapp/src/main/java/org/eclipse/jetty/tests/webapp/websocket/WebSocketClientServlet.java]: `Callable` doesn't work because it still throws exception. I guess I could just put a nested try catch block that wraps the exception with `RuntimeException`. I just thought it would be cleaner with the method reference and was surprised that it didn't work.

**Comment by lachlan-roberts** [comment]
@sbordet you asked me to add the case where we provide the websocket client classes in `WEB-INF/lib`, but the webapp still uses the server versions of `org.eclipse.jetty.websocket.` classes. So it is basically unusable, I get `ClassCastException` and `LinkageError`.

Don't you use some shaded jars in cometd to get around this problem?

File: jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/XmlBasedHttpClientProvider.java [hunk 3]
```diff
@@ -22,27 +22,52 @@
...
+
+        try
+        {
+            Thread.currentThread().setContextClassLoader(HttpClient.class.getClassLoader());
+            return newHttpClient(resource);
+        }
+        catch (Throwable t)
+        {
+            LOG.warn("Failure to load HttpClient from XML", t);
+        }
```
Comment (sbordet) [inline jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/XmlBasedHttpClientProvider.java]: `newHttpClient()` already catches all exception, so there is no need for this catch block here.
Merge the error messages and I think it should be a `LOG.info()`, since if we cannot load it we just fall back.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/WebSocketExtensionFactory.java [hunk 4]
```diff
@@ -42,10 +37,8 @@
 
 public class WebSocketExtensionFactory extends ExtensionFactory implements LifeCycle, Dumpable
```
Comment (sbordet) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/extensions/WebSocketExtensionFactory.java:38]: This class extends a deprecated class -- should this class be deprecated as well?

File: tests/test-webapps/test-websocket-client-provided-webapp/src/main/java/org/eclipse/jetty/tests/webapp/websocket/WebSocketClientServlet.java [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+
+@WebServlet("/")
+public class WebSocketClientServlet extends HttpServlet
+{
+    private WebSocketClient client;
+
+    @Override
+    public void init() throws ServletException
+    {
+        // We must rely on jetty-websocket-httpclient.xml as we do not have access to server classes like HttpClient.
```
Comment (sbordet) [inline tests/test-webapps/test-websocket-client-provided-webapp/src/main/java/org/eclipse/jetty/tests/webapp/websocket/WebSocketClientServlet.java]: Worth clarifying the comment in: "Cannot instantiate an HttpClient here because it's a server class, and therefore must rely on jetty-websocket-httpclient.xml".

File: tests/test-webapps/test-websocket-client-provided-webapp/src/main/java/org/eclipse/jetty/tests/webapp/websocket/WebSocketClientServlet.java [hunk 6]
```diff
@@ -0,0 +1,129 @@
...
+            clientSocket.session.getRemote().sendString("test message");
+            String response = clientSocket.textMessages.poll(5, TimeUnit.SECONDS);
+            clientSocket.session.close();
+            clientSocket.closeLatch.await(5, TimeUnit.SECONDS);
+
+            PrintWriter writer = resp.getWriter();
+            writer.println("WebSocketEcho: " + ("test message".equals(response) ? "success" : "failure"));
+            writer.println("WebSocketEcho: success");
+            // We cannot test the HttpClient timeout because it is a server class not exposed to the webapp.
+            // writer.println("ConnectTimeout: " + client.getHttpClient().getConnectTimeout());
```
Comment (sbordet) [inline tests/test-webapps/test-websocket-client-provided-webapp/src/main/java/org/eclipse/jetty/tests/webapp/websocket/WebSocketClientServlet.java]: I think you can do this via reflection: 

```java
Object httpClient = client.getHttpClient();
// etc.
```

If you cannot, then remove the `connectTimeout` setting from `jetty-websocket-httpclient.xml`.

File: tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java [hunk 7]
```diff
@@ -304,4 +307,104 @@ public void testLog4j2ModuleWithSimpleWebAppWithJSP() throws Exception
             IO.delete(jettyBase.toFile());
         }
     }
+
+    @ParameterizedTest
+    @ValueSource(strings = {"http", "https"})
+    public void testWebsocketClientInWebappProvidedByServer(String scheme) throws Exception
```
Comment (sbordet) [inline tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java:313]: I cannot comment on the `keystore` file, but I don't think it's necessary.
The keystore is copied from module `ssl`, no? The one you added here is not used at all. If that's the case, remove it.

File: tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java [hunk 8]
```diff
@@ -304,4 +307,104 @@ public void testLog4j2ModuleWithSimpleWebAppWithJSP() throws Exception
...
+
+            File webApp = distribution.resolveArtifact("org.eclipse.jetty.tests:test-websocket-client-webapp:war:" + jettyVersion);
+            distribution.installWarFile(webApp, "test");
+
+            int port = distribution.freePort();
+            String[] args2 = {
+                "jetty.http.port=" + port,
+                "jetty.ssl.port=" + port,
+                "jetty.webapp.addServerClasses+=,+org.eclipse.jetty.websocket.",
+                "jetty.webapp.addSystemClasses+=,-org.eclipse.jetty.websocket.",
```
Comment (sbordet) [inline tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java:390]: Worth adding a comment about what these 2 lines do -- I cannot grok it.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]
