### PR TITLE
Issue #10926 - add support for CombinedResource in AttributeNormalizer

### LINKED ISSUE #10926: AttributeNormalizer does not support combined resources
In Jetty 12 `AttributeNormalizer` throws `IllegalArgumentException` if the base resource is a `CombinedResource`. 

A comment was left saying

> Combined resources currently are not supported (see #8921) but such support could be added. That would require some form of (potentially expensive) existence check in expand() to figure out which URIAttribute actually contains the resource.

If a webapp has jars with files in `META-INF/resources` then the base resource is a `CombinedResource`, so we need support for `CombinedResource` with the `AttributeNormalizer`.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #10926

### CODE REVIEW

**Review by sbordet — DISMISSED** [review]
Not pretty to cast to `CombinedResource`, but it is what it is.
We can change the implementation later, as long as there is a test for the feature.

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/AttributeNormalizerTest.java [hunk 1]
```diff
@@ -101,6 +103,11 @@ private static Path asTargetPath(String title, String subpath)
         return path;
     }
 
+    private static Resource asTargetResource(String title, String subpath)
+    {
+        return ResourceFactory.root().newResource(asTargetPath(title, subpath));
```
Comment (joakime) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/AttributeNormalizerTest.java]: Be careful to not let things (eg: mounts) linger in the root ResourceFactory

**Comment by gregw** [comment]
See #8921

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java [hunk 2]
```diff
@@ -195,233 +196,374 @@ public String toString()
...
-
-        if (LOG.isDebugEnabled())
-            Stream.concat(paths.stream(), uris.stream()).map(Object::toString).forEach(LOG::debug);
-    }
-
-    private void addSystemProperty(String key, int weight)
-    {
-        String value = System.getProperty(key);
-        if (value != null)
+        if (baseResource instanceof CombinedResource combinedResource)
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java]: You don't need to do this instanceof check.  Just always iterate over the Resource and you'll get a singleton iteration in the case of a non-combined resource.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java [hunk 3]
```diff
@@ -195,233 +196,374 @@ public String toString()
...
+        if (_normalizers.size() == 1)
+            return _normalizers.get(0).normalizePath(path);
 
-            if (!uPath.startsWith(aPath))
-                continue;
+        for (Normalizer normalizer : _normalizers)
+        {
+            try
+            {
+                String expanded = normalizer.normalizePath(path);
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/AttributeNormalizer.java]: This feels inside-out

I don't think we should be trying to normalize on each of the combined resources in turn as it might match multiple and we will need to duplicate whatever logic is inside CombinedResource here.

We need some way to ask a combined resource for which base resource was used and then just normalize against that.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/AttributeNormalizerTest.java [hunk 4]
```diff
@@ -308,6 +315,34 @@ public void testNormalizeWarDeepAsURI(final Scenario scenario)
...
+
+        // Create files in each of these directories.
+        Files.createFile(r1.getPath().resolve("file1")).toFile().deleteOnExit();
+        Files.createFile(r2.getPath().resolve("file2")).toFile().deleteOnExit();
+        Files.createFile(r3.getPath().resolve("file3")).toFile().deleteOnExit();
+
+        Resource combined = CombinedResource.combine(List.of(r1, r2, r3));
+        AttributeNormalizer normalizer = new AttributeNormalizer(combined);
+
+        // Uses the appropriate resource if the target exists.
```
Comment (gregw) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/AttributeNormalizerTest.java:334]: Can you add tests for overlayed directories which might be found in multiple bases

**Review by gregw — CHANGES_REQUESTED** [review]
I don't like the implementation, but it does appear to work.

Can we hangout and chat about alternatives?

**Review by lachlan-roberts — COMMENTED** [review]
LGTM

Not sure the weights are optimal but don't think it matters too much.
Probably the first resource should be weighted the most because its the most likely to be used.

**Review by lorban — APPROVED** [review]

**Review by joakime — APPROVED** [review]
