### PR TITLE
Issue #12403 - verify XML PublicID behaviors.

### LINKED ISSUE #12403: If jetty.org is down, impossible to start Jetty server (12.0.5) - multiple dtd to eclipse and jetty
**Jetty version(s)**
jetty-12.0.5

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk 17.0.9 2023-10-17

**OS type/version**
Linux or Windows

**Description**
xml in webapps, like
```
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Mort Bay Consulting//DTD Configure//EN" "https://jetty.org/configure_10_0.dtd">
<Configure class="org.eclipse.jetty.server.handler.ContextHandler">
...
```

While https://jetty.org/ is down, I got error

```
2024-10-18 10:41:07.163 [main] WARN  o.e.jetty.deploy.DeploymentManager - Unable to reach node goal: started
java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:954)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:951)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:677)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1397)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1363)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:257)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1152)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1040)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:943)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:254)
	at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:303)
	at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:278)
	at org.eclipse.jetty.deploy.providers.ContextProvider$1.<init>(ContextProvider.java:350)
	at org.eclipse.jetty.deploy.providers.ContextProvider.createContextHandler(ContextProvider.java:349)
	at org.eclipse.jetty.deploy.App.getContextHandler(App.java:108)
	at org.eclipse.jetty.deploy.bindings.StandardDeployer.processBinding(StandardDeployer.java:33)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:522)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:162)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.pathAdded(ScanningAppProvider.java:293)
	at org.eclipse.jetty.deploy.providers.ContextProvider.pathAdded(ContextProvider.java:520)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.pathAdded(ScanningAppProvider.java:69)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:902)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:868)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:775)
	at org.eclipse.jetty.util.Scanner.startScanning(Scanner.java:664)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:636)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:264)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:592)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:263)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:622)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:468)
	at org.eclipse.jetty.server.Server.doStart(Server.java:563)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:2030)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
	at org.eclipse.jetty.start.Main.start(Main.java:519)
	at org.eclipse.jetty.start.Main.main(Main.java:76)
2024-10-18 10:41:07.184 [main] WARN  o.eclipse.jetty.xml.XmlConfiguration - Unable to execute XmlConfiguration
java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:954)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:951)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:677)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1397)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1363)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:257)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1152)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1040)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:943)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:254)
	at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:303)
	at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:278)
	at org.eclipse.jetty.deploy.providers.ContextProvider$1.<init>(ContextProvider.java:350)
	at org.eclipse.jetty.deploy.providers.ContextProvider.createContextHandler(ContextProvider.java:349)
	at org.eclipse.jetty.deploy.App.getContextHandler(App.java:108)
	at org.eclipse.jetty.deploy.bindings.StandardDeployer.processBinding(StandardDeployer.java:33)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:522)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:162)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.pathAdded(ScanningAppProvider.java:293)
	at org.eclipse.jetty.deploy.providers.ContextProvider.pathAdded(ContextProvider.java:520)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.pathAdded(ScanningAppProvider.java:69)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:902)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:868)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:775)
	at org.eclipse.jetty.util.Scanner.startScanning(Scanner.java:664)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:636)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:264)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:592)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:263)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:622)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:468)
	at org.eclipse.jetty.server.Server.doStart(Server.java:563)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:2030)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
	at org.eclipse.jetty.start.Main.start(Main.java:519)
	at org.eclipse.jetty.start.Main.main(Main.java:76)
```

**How to reproduce?**
Shutdown jetty.org ? ;)

### PR DESCRIPTION
**Pull request by joakime**
* The XmlConfiguration instance should not use an XML parser from the classloader. As that XML parser can be broken when it comes to XML entity resolution behaviors. (We always want local entity resolution, never external) Switching to SAXParserFactory.newDefaultInstance() ensures this behavior that we want/need.
* More unit tests for behavior with and without XML PublicID's in the mix.

### CODE REVIEW

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 1]
```diff
@@ -2068,6 +2070,35 @@ private ConfigurationParser(Pool.Entry<ConfigurationParser> entry)
             addCatalog(URI.create(catalogUrl.toExternalForm()));
         }
 
+        protected SAXParserFactory newSAXParserFactory()
+        {
+            // Use JVM default implementation (not the one found in the classloader from non-JVM sources)
+            SAXParserFactory factory = SAXParserFactory.newDefaultInstance();
```
Comment (gregw) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java:2078]: Can you explain how this is different from :
```suggestion
            // Use JVM default implementation (not the one found in the classloader from non-JVM sources)
            SAXParserFactory factory = super.newSAXParserFactory();
```

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 2]
```diff
@@ -2068,6 +2070,35 @@ private ConfigurationParser(Pool.Entry<ConfigurationParser> entry)
...
+
+                // disable all external entity references with Jetty's Configuration XML.
+                xmlReader.setFeature("http://xml.org/sax/features/external-general-entities", false);
+                xmlReader.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
+                xmlReader.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
+            }
+            catch (SAXException e)
+            {
+                LOG.warn(e.getMessage());
+            }
```
Comment (gregw) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: This feel a bit like a side-effect that known the lifecycle of the sax parsers.  Could this not be done in a wrapper of the `SAXParserFactory` created by `newSAXParserFactor()`?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java:2078]: super.newSAXParserFactory uses `SAXParserFactory.newInstance()` which does a lookup for XML Factories across the entire classloader.  Even oddball xerces implementations or alternative embedded implementations from other uber jars.

The `SAXParserFactory.newDefaultInstance() `doesn't do the lookup, and only uses what is in the JVM.

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 2 above)
Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: This is pretty common, we do some of this in the parent `XmlPparser`, but not all of it, but not all of it.
It's not appropriate to have the generic `XmlParser` be this strict, as it's used in other places (like web descriptor parsing).
Only the `XmlConfiguration` needs this level of strictness.

Comment (gregw) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: I'm only proposing that we do it for the SAXParserFactory that is returned above for the `XmlConfiguration`

Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Changing the "generic" XML behavior in `XmlParser` doesn't seem right, as it's used in many scenarios where an alternative XML parser would make sense, and even accessing external entities could make sense.

The only scenario where we want to be strict is `XmlConfiguration`, hence why it is there.

Comment (gregw) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: @joakime I'm only proposing this for XMLConfiguration. But do it in a wrapper in the newSAXParserFactory method rather than as a side effect of a setter based on assumed knowledge of the parser lifecycle

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 3]
```diff
@@ -2068,6 +2070,35 @@ private ConfigurationParser(Pool.Entry<ConfigurationParser> entry)
...
+        }
+
```
Comment (gregw) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Would this not work:

```suggestion
        protected SAXParserFactory newSAXParserFactory()
        {
            // Use JVM default implementation (not the one found in the classloader from non-JVM sources)
            SAXParserFactory factory = SAXParserFactory.newDefaultInstance();
            // Don't allow use of XInclude to reference external entities.
            factory.setXIncludeAware(false);

            if (isValidating())
            {
                setFeature(factory, "http://xml.org/sax/features/external-general-entities", false);
                setFeature(factory, "http://xml.org/sax/features/external-parameter-entities", false);
                setFeature(factory, "http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
            }
            
            return factory;
        }

        private void setFeature(SAXParserFactory factory, String name, boolean value)
        {
            try
            {
                factory.setFeature(name, value);
            }
            catch (Exception e)
            {
                LOG.warn(e.getMessage(), e);
            }
        }
```

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 3 above)
Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Some of those are Factory features, some are XMLReader features (not all factory features translate to the created SAXParser or XMLReader, as those features can select and/or initialize the SAXParser or XMLReader you get as a result of the factory feature)
Also, the XmlParser.setValidating(boolean) method must be called for `_parser` to be initialized properly.
And the check if validating is true or not is irrelevant for XmlConfiguration.

Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: If you want to fix this odd initialization in XmlParser, lets do that in a different PR, for like release 12.1.x

Comment (gregw) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: @joakime this is new code in this PR that is not in the correct location and looks fragile.   If the factory features are different to the parser, then wrap the the factory so it configures all parsers that it creates.    Your current code is using a side effect of a setter that known the lifecycle of a specific parser, so it is very fragile.

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 4]
```diff
@@ -2068,6 +2071,49 @@ private ConfigurationParser(Pool.Entry<ConfigurationParser> entry)
...
+                setFeature(xmlReader, "http://xml.org/sax/features/external-general-entities", false);
+                setFeature(xmlReader, "http://xml.org/sax/features/external-parameter-entities", false);
+                // Configure Xerces
+                setFeature(xmlReader, "http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
+            }
+            catch (SAXException e)
+            {
+                LOG.warn(e.getMessage());
+            }
+        }
```
Comment (gregw) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]:
```suggestion

        protected SAXParserFactory newSAXParserFactory()
        {
            // Use JVM default implementation (not the one found in the classloader from non-JVM sources)
            SAXParserFactory factory = SAXParserFactory.newDefaultInstance();
            // Use secure processing factory level defaults (to allow
            // newly created SAXParsers from this factory to be initialized properly
            // for external entity handling)
            setFeature(factory, XMLConstants.FEATURE_SECURE_PROCESSING, true);
            // Don't allow use of XInclude to reference external entities.
            factory.setXIncludeAware(false);
            
            return new SAXParserFactory() 
            {
                @Override
                public SAXParser newSAXParser() throws ParserConfigurationException, SAXException
                {
                    SAXParser parser = factory.newSAXParser();
                    if (isValidating())
                    {
                        XMLReader xmlReader = parser.getXMLReader();
                        XmlParser.setFeature(xmlReader, "http://xml.org/sax/features/external-general-entities", false);
                        XmlParser.setFeature(xmlReader, "http://xml.org/sax/features/external-parameter-entities", false);
                        // Configure Xerces
                        XmlParser.setFeature(xmlReader, "http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
                    }
                    return null;
                }

                @Override
                public void setFeature(String name, boolean value) throws ParserConfigurationException, SAXNotRecognizedException, SAXNotSupportedException
                {

                }

                @Override
                public boolean getFeature(String name) throws ParserConfigurationException, SAXNotRecognizedException, SAXNotSupportedException
                {
                    return false;
                }
            };
        }
```

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlParser.java [hunk 5]
```diff
@@ -109,6 +112,30 @@ protected SAXParserFactory newSAXParserFactory()
         return SAXParserFactory.newInstance();
     }
 
+    protected void setFeature(SAXParserFactory factory, String name, boolean value)
```
Comment (gregw) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlParser.java]: make static

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlParser.java [hunk 6]
```diff
@@ -109,6 +112,30 @@ protected SAXParserFactory newSAXParserFactory()
...
+        {
+            factory.setFeature(name, value);
+        }
+        catch (SAXNotSupportedException | SAXNotRecognizedException | ParserConfigurationException e)
+        {
+            LOG.warn("Unable to setFeature({}, {})", name, value, e);
+        }
+    }
+
+    protected void setFeature(XMLReader xmlReader, String name, boolean value)
```
Comment (gregw) [inline jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlParser.java]: make static

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 4 above)
Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: This proposal would apply changes before `XmlParser.setValidating(boolean)` which would then undo / override some of the changes we want to make.
Also, the XMLReader feature settings are not dependent on `isValidating()`, they are totally unrelated.

It's not safe to assume that all `.setFeature(String, boolean)` does is that it just sets a flag in a map somewhere, and at a later point that flag is used, its far more complicated than that.  The order in which you set the features is also important.

Your focus seems to be only on XmlConfiguration's internal override of XmlParser, but you haven't proposed similar changes to XmlParser.setValidating(boolean), which has the same behavior.

Again, if you want this kind of change, lets fix the initialization oddities of XmlParser in a different PR.
Not here.  We don't want this simple PR to grow to be some kind of omnibus PR that impacts all usages of XmlParser too.  I'll be happy to start that PR too!

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 3 above)
Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: There are 2 different setFeature usages.

* Factory - the setFeature calls for this are in the .newSAXParserFactory() call already.
* SAXParser - these are in the unfortunately named `.setValidating(boolean)` where the internal SAXParser is created.

Let me try a different approach, instead of wrapping SAXParserFactory, which is just as fragile.

Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Different approach pushed.

File: jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 4 above)
Comment (joakime) [reply jetty-core/jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Different approach pushed here.

**Review by gregw — APPROVED** [review]

**Comment by ArfyFR** [comment]
Hi
The fix is not in ~~12.0.5~~ 12.0.15 sorry ?
I saw "Some checks were not successful"

**Comment by sbordet** [comment]
@ArfyFR this change is in 12.0.15, I assume you meant that.

**Comment by ArfyFR** [comment]
Oooops, yes sorry 12.0.15
