### PR TITLE
Fixes #6159 - Jetty with Conscrypt unable to handle any HTTPS request…

### LINKED ISSUE #6159: Jetty with Conscrypt unable to handle any HTTPS requests when connected by IP rather than hostname.
**Jetty version**
Embedded Jetty 11.0.2 with the following modules: `jetty-server`, `jetty-alpn-server`, `jetty-alpn-conscrypt-server`, `http2-server`, including their dependencies. Conscrypt was added into security providers via `java.security.Security.insertProviderAt(new org.conscrypt.OpenSSLProvider(), 1)` before bootstrapping the server.

**Java version**
AdoptOpenJDK 15.0.2

**OS type/version**
Arch Linux running Linux 5.11.11-zen1-1-zen. (There is no real version I can give.)

**Description**
When connecting to Jetty via an IP, i.e., `127.0.0.1` or `[::1]`, it internally NPEs and gives a handshake error rather than trying to continue on, either going onto the page itself, or into an SSL certificate error depending on the client and what certificate was installed on the server.

Note, this only happens with Conscrypt Alpn (`jetty-alpn-conscrypt-server`). Replacing the module with Java Alpn (`jetty-alpn-java-server`) handles the raw IP connection fine, resulting, at least in my case, in an SSL certificate error as expected.

<details><summary>Server bootstrap (is in Kotlin)</summary>

```kotlin
val httpsPort = 7443
val httpPort = 7080
val keystore = "keystore"
val keystorePassword = "Best not to keep it in code, yes?"

val server = Server()

val httpsConfig = HttpConfiguration()
httpsConfig.securePort = httpsPort
httpsConfig.addCustomizer(SecureRequestCustomizer())

val https11 = HttpConnectionFactory(httpsConfig)
val https2 = HTTP2ServerConnectionFactory(httpsConfig)
val alpn = ALPNServerConnectionFactory()
alpn.defaultProtocol = https11.protocol

val sslContextFactory = SslContextFactory.Server()
sslContextFactory.keyStorePath = keystore
sslContextFactory.setKeyStorePassword(keystorePassword)

val tls = SslConnectionFactory(sslContextFactory, alpn.protocol)

val httpsConnector = ServerConnector(server, tls, alpn, https2, https11)
httpsConnector.port = httpsPort
server.addConnector(httpsConnector)

server.handler = CertificateHandler()

server.start()
```
</details>

<details><summary>The logs.</summary>

```
07:53:02.863 [qtp230835489-21] DEBUG org.eclipse.jetty.io.ManagedSelector - Wakeup ManagedSelector@f5ac9e4{STARTED} id=2 keys=0 selected=0 updates=0
07:53:02.863 [qtp230835489-21] DEBUG org.eclipse.jetty.util.thread.QueuedThreadPool - queue org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint@631e55db startThread=0
07:53:02.863 [qtp230835489-22] DEBUG org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.EPollSelectorImpl@3c4511cb woken with none selected
07:53:02.863 [qtp230835489-22] DEBUG org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.EPollSelectorImpl@3c4511cb woken up from select, 0/0/0 selected
07:53:02.863 [qtp230835489-21] DEBUG org.eclipse.jetty.io.WriteFlusher - ignored: javax.net.ssl.SSLHandshakeException: Cannot invoke "java.util.List.stream()" because the return value of "javax.net.ssl.ExtendedSSLSession.getRequestedServerNames()" is null WriteFlusher@4befb7f7{IDLE}->null
07:53:02.864 [qtp230835489-22] DEBUG org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.EPollSelectorImpl@3c4511cb processing 0 keys, 0 updates
07:53:02.863 [qtp230835489-16] DEBUG org.eclipse.jetty.util.thread.QueuedThreadPool - run org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint@631e55db in QueuedThreadPool[qtp230835489]@dc24521{STARTED,8<=9<=200,i=1,r=-1,q=0}[ReservedThreadExecutor@345965f2{s=1/8,p=0}]
07:53:02.864 [qtp230835489-22] DEBUG org.eclipse.jetty.io.ManagedSelector - updateable 0
07:53:02.864 [qtp230835489-22] DEBUG org.eclipse.jetty.io.ManagedSelector - updates 0
07:53:02.864 [qtp230835489-22] DEBUG org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.EPollSelectorImpl@3c4511cb waiting with 0 keys
07:53:02.864 [qtp230835489-16] DEBUG org.eclipse.jetty.io.ManagedSelector - Destroyed SocketChannelEndPoint@37cd378e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=2/30000}{io=1/1,kio=-1,kro=-1}->SslConnection@6b520bae{NOT_HANDSHAKING,eio=-1/-1,di=-1,fill=IDLE,flush=IDLE}~>DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=10/30000}=>ALPNServerConnection@4acd8e04
07:53:02.864 [qtp230835489-21] DEBUG org.eclipse.jetty.io.FillInterest - onFail FillInterest@4c85840e{null}
javax.net.ssl.SSLHandshakeException: Cannot invoke "java.util.List.stream()" because the return value of "javax.net.ssl.ExtendedSSLSession.getRequestedServerNames()" is null
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.handshakeFailed(SslConnection.java:925)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:785)
	at org.eclipse.jetty.server.NegotiatingServerConnection.fill(NegotiatingServerConnection.java:147)
	at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:92)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:523)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:372)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:158)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "javax.net.ssl.ExtendedSSLSession.getRequestedServerNames()" is null
	at org.eclipse.jetty.util.ssl.SniX509ExtendedKeyManager.chooseServerAlias(SniX509ExtendedKeyManager.java:118)
	at org.eclipse.jetty.util.ssl.SniX509ExtendedKeyManager.chooseEngineServerAlias(SniX509ExtendedKeyManager.java:202)
	at org.conscrypt.ConscryptEngine.chooseServerAlias(ConscryptEngine.java:1695)
	at org.conscrypt.NativeSsl.configureServerCertificate(NativeSsl.java:369)
	at org.conscrypt.ConscryptEngine.serverCertificateRequested(ConscryptEngine.java:1597)
	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:567)
	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1097)
	at org.conscrypt.ConscryptEngine.readPlaintextDataHeap(ConscryptEngine.java:1117)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:878)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:749)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:714)
	at org.conscrypt.Java8EngineWrapper.unwrap(Java8EngineWrapper.java:236)
	at org.eclipse.jetty.io.ssl.SslConnection.unwrap(SslConnection.java:391)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:684)
	... 17 common frames omitted
07:53:02.864 [qtp230835489-16] DEBUG org.eclipse.jetty.io.AbstractConnection - onClose ALPNServerConnection@4acd8e04::DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=10/30000}
07:53:02.864 [qtp230835489-16] DEBUG org.eclipse.jetty.io.AbstractConnection - onClose SslConnection@6b520bae::SocketChannelEndPoint@37cd378e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=2/30000}{io=1/1,kio=-1,kro=-1}->SslConnection@6b520bae{NOT_HANDSHAKING,eio=-1/-1,di=-1,fill=IDLE,flush=IDLE}~>DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=10/30000}=>ALPNServerConnection@4acd8e04
07:53:02.864 [qtp230835489-16] DEBUG org.eclipse.jetty.util.thread.QueuedThreadPool - ran org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint@631e55db in QueuedThreadPool[qtp230835489]@dc24521{STARTED,8<=9<=200,i=1,r=-1,q=0}[ReservedThreadExecutor@345965f2{s=1/8,p=0}]
07:53:02.864 [qtp230835489-21] DEBUG org.eclipse.jetty.server.NegotiatingServerConnection - Unable to fill from endpoint DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=10/30000}
javax.net.ssl.SSLHandshakeException: Cannot invoke "java.util.List.stream()" because the return value of "javax.net.ssl.ExtendedSSLSession.getRequestedServerNames()" is null
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.handshakeFailed(SslConnection.java:925)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:785)
	at org.eclipse.jetty.server.NegotiatingServerConnection.fill(NegotiatingServerConnection.java:147)
	at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:92)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:523)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:372)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:158)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "javax.net.ssl.ExtendedSSLSession.getRequestedServerNames()" is null
	at org.eclipse.jetty.util.ssl.SniX509ExtendedKeyManager.chooseServerAlias(SniX509ExtendedKeyManager.java:118)
	at org.eclipse.jetty.util.ssl.SniX509ExtendedKeyManager.chooseEngineServerAlias(SniX509ExtendedKeyManager.java:202)
	at org.conscrypt.ConscryptEngine.chooseServerAlias(ConscryptEngine.java:1695)
	at org.conscrypt.NativeSsl.configureServerCertificate(NativeSsl.java:369)
	at org.conscrypt.ConscryptEngine.serverCertificateRequested(ConscryptEngine.java:1597)
	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:567)
	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1097)
	at org.conscrypt.ConscryptEngine.readPlaintextDataHeap(ConscryptEngine.java:1117)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:878)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:749)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:714)
	at org.conscrypt.Java8EngineWrapper.unwrap(Java8EngineWrapper.java:236)
	at org.eclipse.jetty.io.ssl.SslConnection.unwrap(SslConnection.java:391)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:684)
	... 17 common frames omitted
07:53:02.864 [qtp230835489-21] DEBUG org.eclipse.jetty.io.AbstractEndPoint - shutdownOutput DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=10/30000}
07:53:02.864 [qtp230835489-21] DEBUG org.eclipse.jetty.io.AbstractEndPoint - close DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=10/30000}
07:53:02.864 [qtp230835489-21] DEBUG org.eclipse.jetty.io.AbstractEndPoint - close(null) DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=10/30000}
07:53:02.864 [qtp230835489-21] DEBUG org.eclipse.jetty.server.NegotiatingServerConnection - ALPNServerConnection@4acd8e04::DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=10/30000} detected close on client side
07:53:02.864 [qtp230835489-21] DEBUG org.eclipse.jetty.io.AbstractEndPoint - shutdownOutput DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=10/30000}
07:53:02.864 [qtp230835489-21] DEBUG org.eclipse.jetty.io.AbstractEndPoint - close DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=10/30000}
07:53:02.864 [qtp230835489-21] DEBUG org.eclipse.jetty.io.AbstractEndPoint - close(null) DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=11/30000}
07:53:02.864 [qtp230835489-21] DEBUG org.eclipse.jetty.io.ssl.SslConnection - <c.onFillable SslConnection@6b520bae::SocketChannelEndPoint@37cd378e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=3/30000}{io=1/1,kio=-1,kro=-1}->SslConnection@6b520bae{NOT_HANDSHAKING,eio=-1/-1,di=-1,fill=IDLE,flush=IDLE}~>DecryptedEndPoint@37262d0e{l=/[0:0:0:0:0:0:0:1]:7443,r=/[0:0:0:0:0:0:0:1]:34608,CLOSED,fill=-,flush=-,to=11/30000}=>ALPNServerConnection@4acd8e04
07:53:02.865 [qtp230835489-21] DEBUG org.eclipse.jetty.util.thread.ReservedThreadExecutor - ReservedThreadExecutor@345965f2{s=2/8,p=0}@35258fbc waiting

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

</details>

### PR DESCRIPTION
**Pull request by sbordet**
…s when connected by IP rather than hostname.

Added null guard for `ExtendedSSLSession.getRequestedServerNames()`
which should never return null, but it does when using Conscrypt.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SniX509ExtendedKeyManager.java [hunk 1]
```diff
@@ -115,12 +117,16 @@ protected String chooseServerAlias(String keyType, Principal[] issuers, Collecti
...
+            List<SNIServerName> serverNames = ((ExtendedSSLSession)session).getRequestedServerNames();
+            if (serverNames != null)
+            {
+                host = serverNames.stream()
+                    .findAny()
+                    .filter(SNIHostName.class::isInstance)
+                    .map(SNIHostName.class::cast)
+                    .map(SNIHostName::getAsciiName)
+                    .orElse(null);
+            }
```
Comment (joakime) [inline jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SniX509ExtendedKeyManager.java:129]: Wouldn't you want an else branch that returns null? (to maintain the behavior as before?)

Comment (sbordet) [reply jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SniX509ExtendedKeyManager.java:129]: The previous behavior is to fall through, not to return.

Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SniX509ExtendedKeyManager.java:129]: Ah. yup.

**Review by joakime — APPROVED** [review]
LGTM

**Review by gregw — APPROVED** [review]
