### PR TITLE
Issue #4645 - ForwardedRequestCustomizer now gives 400 response for bad port values

### LINKED ISSUE #4645: Empty "X-Forwarded-Port" header results in NumberFormatException
**Jetty version**
9.4.25.v20191220
**Java version**
OpenJDK build 1.8.0_232-09
**OS type/version**
Linux 4.15.0-74-generic #83~16.04.1-Ubuntu
**Description**
If the "X-Forwarded-Port" header is present but empty, a NumberFormatException is thrown:

`java.lang.NumberFormatException: For input string: ""`

This is likely not a correct state for the headers, but it would be nice to at least have a more descriptive error message.

Unfortunately there is no way for me to influence the header value that I receive, so any workarounds for this would be appreciated as well.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Issue #4645**

Replace the previous `NumberFormatException` with an `IllegalArgumentException` with a more descriptive error message.

It would also be possible to change the code to just return if we have an empty `X-Forwarded-Port` value, which would ignore it. I'm not sure if that would be more correct than throwing.

### CODE REVIEW

**Review by gregw — CHANGES_REQUESTED** [review]
We should catch exceptions from parsing all these headers and pass to a method on the Customizer, which by default will throw a BadMessageException.

If users want to ignore these bad headers they can extend and change the method

**Comment by gregw** [comment]
@sbordet has also suggested that when we parse a port we check that it is a valid integer for a port... ie >0 <=64k

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java [hunk 1]
```diff
@@ -639,19 +639,23 @@ else if (_for == null)
...
         {
+            String port = getLeftMost(field.getValue());
+            if (StringUtil.isEmpty(port))
+                throw new IllegalArgumentException(field.getName() + " has empty value");
+
             if (!getForwardedPortAsAuthority())
             {
                 if (_for == null)
-                    _for = new PortSetHostPort(_request.getRemoteHost(), Integer.parseInt(getLeftMost(field.getValue())));
+                    _for = new PortSetHostPort(_request.getRemoteHost(), Integer.parseInt(port));
```
Comment (joakime) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: Perhaps add a new method called `parsePort(String rawPort)` that does the Integer.parseInt() and also validates the range of values to be sane (`port >= 1 && port <= 65535`).

**Review by joakime — CHANGES_REQUESTED** [review]
Like @gregw said, we should also be validating the range of possible post-parsed values.

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java [hunk 2]
```diff
@@ -420,6 +432,12 @@ else if (forwarded._server != null)
         }
     }
 
+    protected void onError(HttpField field, Throwable t)
+    {
+        LOG.warn("Exception while processing {}", field, t);
+        throw new BadMessageException("Bad header value for " + field.getName());
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: add the Throwable t as the cause of this exception

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java [hunk 3]
```diff
@@ -420,6 +432,12 @@ else if (forwarded._server != null)
         }
     }
 
+    protected void onError(HttpField field, Throwable t)
+    {
+        LOG.warn("Exception while processing {}", field, t);
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: Don't warn and throw.   Do one or the other.   I think this should just be a debug here.

**Review by gregw — CHANGES_REQUESTED** [review]
Can you add at least one ForwardedRequestCustomerizerTest test that has a bad port.  I want to make sure that the BadMessageException thrown and then wrapped as a RuntimeException is correctly unwrapped to get the 400 (rather than a 500).

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: Ok sure, was just being careful of giving away too much information in the response like simone said.

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java [hunk 4]
```diff
@@ -380,9 +381,16 @@ public void customize(Connector connector, HttpConfiguration config, Request req
...
-                    handle.invoke(forwarded, field);
+                try
+                {
+                    MethodHandle handle = _handles.get(field.getName());
+                    if (handle != null)
+                        handle.invoke(forwarded, field);
+                }
+                catch (Throwable t)
+                {
+                    onError(field, t);
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: Sorry but... thinking about this more, can we avoid the double try blocks.  onError has no declared exceptions, so whatever it throws can be thrown from this method.  If it doesn't throw then we continue.  Why the need to wrap with a RuntimeException?

**Review by gregw — CHANGES_REQUESTED** [review]
almost!

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java (hunk 4 above)
Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: oops.. you're right, fixed.

**Review by gregw — APPROVED** [review]
