### PR TITLE
Issue #13419 - Fix locale formatting: add Locale.ROOT to %f and DecimalFormat init

### LINKED ISSUE #13419: testRemoveAndReleaseFromCompoundPool fails when user locale is en_DE
**Jetty version(s)**
Jetty 12.0.x

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.8" 2025-07-15
OpenJDK Runtime Environment Homebrew (build 21.0.8)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.8, mixed mode, sharing)
java.util.Locale.getDefault() is en_DE

**OS type/version**
macOS 15.5 (24F74)

**Description**
Good evening, the following test fails when I run "mvn install" on my Macbook Air M1 with Homebrew OpenJDK 21 and en_DE locale, because "50,000%" is not matching the expected "50.000%" (comma vs period):

```
[ERROR] org.eclipse.jetty.io.ArrayByteBufferPoolTest.testRemoveAndReleaseFromCompoundPool -- Time elapsed: 0.014 s <<< FAILURE!
java.lang.AssertionError: 

Expected: a string containing "[capacity=4096,in-use=0/0,pooled/acquires/releases=512/1024/1024(50.000%),non-pooled/evicts/removes=0/0/512]"
```

**How to reproduce?**

```
cd jetty-core/jetty-io
mvn clean test -Dtest=ArrayByteBufferPoolTest -Dmaven.build.cache.enabled=false
```

Here are the logs (please wait for my upcoming PR):

[ArrayByteBufferPoolTest-fails.txt](https://github.com/user-attachments/files/21606894/ArrayByteBufferPoolTest-fails.txt)
[ArrayByteBufferPoolTest-fixed.txt](https://github.com/user-attachments/files/21606893/ArrayByteBufferPoolTest-fixed.txt)

### PR DESCRIPTION
**Pull request by afarber**
Fix https://github.com/jetty/jetty.project/issues/13419 and other potential formatting issues by using Locale.ROOT for:

- Percentage formatting in ArrayByteBufferPool statistics dump
- HTTP quality values in QuotedQualityCSV
- Statistics formatting in SampleStatistic
- Test logging in connection pool tests
- Benchmark output formatting

### CODE REVIEW

**Comment by afarber** [comment]
There are more such issues in source code:

jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/statistic/SampleStatistic.java

```
  return String.format("%s@%x{count=%d,max=%d,mean=%f,total=%d,variance=%f,stddev=%f}",
      getClass().getSimpleName(), hashCode(), getCount(), getMax(), getMean(),
      getTotal(), getVariance(), getStdDev());
```

jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/QuotedQualityCSV.java

```
  return String.format("%s@%x[%s,q=%f,i=%d]",
      getClass().getSimpleName(), hashCode(), _value, _quality, _index);
```

tests/jetty-jmh/src/main/java/org/eclipse/jetty/util/thread/jmh/ReservedThreadPoolBenchmark.java
```
  System.err.printf("hit:miss = %.1f%% (%d:%d)", 100.0D * hits / (hits + miss.sum()), hits, miss.sum());
```

jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/ConnectionPoolTest.java
```
  LOG.info("%d requests in %d ms, %.3f req/s".formatted(iterations, elapsed, ...));
```

WebSocket test decoders (EE9 and EE10)
```
  DecimalFormat numberFormat = new DecimalFormat("[#,###]");
```

Should I fix them too?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java [hunk 1]
```diff
@@ -683,7 +684,7 @@ private Map<String, Object> toMap()
             @Override
             public String toString()
             {
-                return "capacity=%d,in-use=%d/%d,pooled/acquires/releases=%d/%d/%d(%.3f%%),non-pooled/evicts/removes=%d/%d/%d".formatted(
+                return String.format(Locale.ROOT, "capacity=%d,in-use=%d/%d,pooled/acquires/releases=%d/%d/%d(%.3f%%),non-pooled/evicts/removes=%d/%d/%d",
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java:687]: I'm wondering if we should have a Jetty.LOCALE constant that defaults to Locale.ROOT, but that we allow to be initialised differently in case somebody really wants localised dumps/logs?

@joakime thoughts?

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java:687]: hmmm AI thinks best practice is to not - localise logs etc. so I think directly using Locale.ROOT is fine.

Comment (joakime) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java:687]: I'm good with hardcoded Locale usage.
I wonder tho, is Locale.ROOT or Locale.ENGLISH a better choice?
Whatever we choose, it should be reflected in the other PR #13417 too.

Locale.ROOT has an odd description, I need to look into it a bit more...
https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Locale.html#ROOT

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java:687]: AI suggested ROOT

**Review by gregw — APPROVED** [review]

**Comment by gregw** [comment]
thanks
