### PR TITLE
Fix #11811 insensitive header name set

### LINKED ISSUE #11811: getHeaderNames should return header name once also when request has it in different case
**Jetty version(s)**
12.0.9

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
Java 22

**OS type/version**
MacOS

**Description**
`request.getHeaderNames` is typically used to iterate over header names in the request and then `request.getHeaders` is used to retrieve values:

```java
// example code supposed tor resemble typical use of getHeaderNames()
Enumeration<String> names = servletRequest.getHeaderNames();
while (names.hasMoreElements()) {
    String name = names.nextElement();
    doSomething(name, servletRequest.getHeaders(name))
}
```

When request contains both `Foo-Bar` and `foo-bar` headers, `getHeaderNames` returns both String values, so `foo-bar` header values are processed twice.

**How to reproduce?**

```shell
curl -H 'Foo-Bar: one' -H 'foo-bar: two'  http://localhost:8080/endpoint
```

### PR DESCRIPTION
**Pull request by gregw**
Fix #11811 insensitive header name set by:
 + Using a EnumSet and TreeSet to ensure no duplicates in the set
 + Using an ArrayList to preserve the ordering (not necessary, but useful).

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 1]
```diff
@@ -596,7 +598,40 @@ default Enumeration<String> getFieldNames()
      */
     default Set<String> getFieldNamesCollection()
     {
-        return stream().map(HttpField::getName).collect(Collectors.toSet());
+        Set<HttpHeader> seenByHeader = EnumSet.noneOf(HttpHeader.class);
+        Set<String> seenByName = null;
+        List<String> list = new ArrayList<>(size());
```
Comment (lachlan-roberts) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:603]: Can't we just allocate a `LinkedHashSet` and return that directly instead of wrapping with an `AbstractSet`, as the `LinkedHashSet` will retain the insertion order.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 2]
```diff
@@ -596,7 +598,40 @@ default Enumeration<String> getFieldNames()
...
+
+        for (HttpField f : this)
+        {
+            HttpHeader header = f.getHeader();
+            if (header == null)
+            {
+                seenByName = Objects.requireNonNullElse(seenByName, new TreeSet<>(String::compareToIgnoreCase));
```
Comment (lachlan-roberts) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Looks like this creates a new `TreeSet` every time and only uses it if `seenByName == null`?

Maybe something like this is better?
```java
if (seenByName == null)
    seenByName = new TreeSet<>(String::compareToIgnoreCase);
```

**Review by lachlan-roberts — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:603]: Two problems with that approach: 
 1. LinkedHashSet doesn't do a case insensitive key
 2. The intention is that most/all headers will be of a known type and never be put into the set and only flagged in the more efficient EnumSet.

Possibly we could create a TreeSet comparator that used the existing order... but that would be more complex.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: ooops

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:603]: I meant just replacing the `ArrayList` with `LinkedHashSet`, instead of having `AbstractSet` backed by an `ArrayList`. You would still use the `TreeSet` for `seenByName`.

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:603]: @lachlan-roberts Ah OK.  However I think the AbstractSet back by a list is still better, as this set is primarily used for iteration rather than queries. So there is no need to build the hash lookup mechanism.

**Review by janbartel — APPROVED** [review]

**Review by lachlan-roberts — APPROVED** [review]

**Review by sbordet — APPROVED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 3]
```diff
@@ -596,7 +598,41 @@ default Enumeration<String> getFieldNames()
...
+            {
+                return list.iterator();
+            }
+
+            @Override
+            public int size()
+            {
+                return list.size();
+            }
+        };
```
Comment (findepi) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:635]: Typically Set implementations support random access or O(log(size)) and rarely have linear access. This may cause surprise performance issues in the calling code.
What about replacing the `List<String> list` variable with a hash set, while retaining all other logic?

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:635]: The returned set will have "random access" via the set API, but it will be implemented by `AbstractSet` as an O(n) search.  Moreover, a user is unlikely to be using the header name set for random access, as they have the direct `get` methods available to seek and individual field.    The only realistic usage of the header set is to iterator over it's values to see all headers.   The list is a perfect compromise in this case.

Note also, that due to HTTP headers need to know about ordering, we have already determined with JMH benchmarks that for realistic sizes of HTTP header collections, it is more efficient to do an O(n) search than to have the expense of building a O(log(n)) map.  Thus rather than creating an ordered map of HttpFields or a map and a list, we simple create a list of HttpFields.  So the `get` methods are actually O(N) as well.   This is something we have carefully considered and will continue to monitor.

Comment (findepi) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:635]: This is based on assumptions how the user uses this set. They may iterate over it (then we are good), or they may use `contains` and then we're less good.  We do not need a sorted set here. HashSet would be faster to  build than TreeSet and would have same semantics as the set returned here. If ordering of headers returned by this method is somehow important,  LinkedHashSet could provide for that.

Comment (findepi) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:635]: BTW, from code maintainer perspective, the previous version of the code didn't look like super optimized -- it used streams' along with their overhead (for example in Trino project we area heavy stream users except for data runtime, where we avoid them). The new code doesn't _look_ as super optimized to me because of AbstractSet. If it indeed is carefully optimized now, my personal preference would be to put a code comment informing the reader about the tradeoffs considered (like "this is optimal for requests that have no more than about x headers").

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:635]: > This is based on assumptions how the user uses this set. 

Indeed, but they are assumptions based on good experience and real world data.  See the detailed benchmarks and discussions in https://github.com/jetty/jetty.project/pull/3682

> They may iterate over it (then we are good), or they may use `contains` and then we're less good. 
Our evidence is that if they use `contains` we are still good.  Only if they use `contains` many times does the list performance approach the cost of building a hashmap or other structure.

> We do not need a sorted set here. 
It is not needed, but HTTP headers are ordered, so maintaining that order can improve compliance with many SHOULD aspects of the RFCs that do specify some aspects of ordering.

> HashSet would be faster to build than TreeSet and would have same semantics as the set returned here.

Except that HashSet is not case insensitive, so additional work is need to change cases etc.

>  If ordering of headers returned by this method is somehow important, LinkedHashSet could provide for that.

again, not suitable for case insensitive.  Also, the order we want is not the natural sort order of the keys.

> BTW, from code maintainer perspective, the previous version of the code didn't look like super optimized -- it used streams' along with their overhead (for example in Trino project we area heavy stream users except for data runtime, where we avoid them). 

We totally agree that streams are not really optimal.

> The new code doesn't look as super optimized to me because of AbstractSet. 

I would not say it is super optimized, but it is somewhat optimized as informed by https://github.com/jetty/jetty.project/pull/3682

> If it indeed is carefully optimized now, my personal preference would be to put a code comment informing the reader about the tradeoffs considered (like "this is optimal for requests that have no more than about x headers").

We tend not to clutter the code with such comments, as the issues and PRs that have all the detail are both persistent and linked from source code.     However, I'm not opposed to making the comment in the HttpFields class generally that it is implemented internally as a list.  I'll reopen #11811 to remind myself to do that.

Comment (findepi) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:635]: > > HashSet would be faster to build than TreeSet and would have same semantics as the set returned here.
> 
> Except that HashSet is not case insensitive, so additional work is need to change cases etc.

The `Set<String>` returned here is not case insensitive either, by virtue of inheriting from `AbstractSet` and defining only iterator and size. `AbstractSet` uses `Object.equals` semantics.

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:635]: @findepi said:
> The Set<String> returned here is not case insensitive either

Good point!  I'm working on fixes.

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:635]: See #11846... still a work in progress.
