### PR TITLE
Issue #13050 - fix flaky websocket OnMessageStream tests

### LINKED ISSUE #13050: Jetty 12.1 Flaky test org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandlerOnMessageTextStreamTest.testInvokeMessageStream
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! -- in org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandlerOnMessageTextStreamTest
[ERROR] org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandlerOnMessageTextStreamTest.testInvokeMessageStream -- Time elapsed: 0.002 s <<< ERROR!
java.lang.RuntimeException: Unexpected error
	at org.eclipse.jetty.ee10.websocket.jakarta.common@12.1.0-SNAPSHOT/org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandlerOnMessageTextStreamTest.lambda$testInvokeMessageStream$0(JakartaWebSocketFrameHandlerOnMessageTextStreamTest.java:77)
	at org.eclipse.jetty.ee10.websocket.jakarta.common@12.1.0-SNAPSHOT/org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandlerOnMessageTextStreamTest.performOnMessageInvocation(JakartaWebSocketFrameHandlerOnMessageTextStreamTest.java:43)
	at org.eclipse.jetty.ee10.websocket.jakarta.common@12.1.0-SNAPSHOT/org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandlerOnMessageTextStreamTest.testInvokeMessageStream(JakartaWebSocketFrameHandlerOnMessageTextStreamTest.java:69)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.websocket.core.messages.DispatchedMessageSink$$Lambda/0x00000007c0352b60@1c4eeb6
	at org.eclipse.jetty.util@12.1.0-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:782)
	at org.eclipse.jetty.websocket.core.common@12.1.0-SNAPSHOT/org.eclipse.jetty.websocket.core.messages.DispatchedMessageSink.accept(DispatchedMessageSink.java:86)
	at org.eclipse.jetty.ee10.websocket.jakarta.common@12.1.0-SNAPSHOT/org.eclipse.jetty.ee10.websocket.jakarta.common.messages.AbstractDecodedMessageSink.accept(AbstractDecodedMessageSink.java:80)
	at org.eclipse.jetty.ee10.websocket.jakarta.common@12.1.0-SNAPSHOT/org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandler.acceptMessage(JakartaWebSocketFrameHandler.java:560)
	at org.eclipse.jetty.ee10.websocket.jakarta.common@12.1.0-SNAPSHOT/org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandler.onText(JakartaWebSocketFrameHandler.java:610)
	at org.eclipse.jetty.ee10.websocket.jakarta.common@12.1.0-SNAPSHOT/org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandler.onFrame(JakartaWebSocketFrameHandler.java:238)
	at org.eclipse.jetty.ee10.websocket.jakarta.common@12.1.0-SNAPSHOT/org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandlerOnMessageTextStreamTest.lambda$testInvokeMessageStream$0(JakartaWebSocketFrameHandlerOnMessageTextStreamTest.java:73)
	... 12 more

```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #13050

### CODE REVIEW

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/common/AbstractJakartaWebSocketFrameHandlerTest.java [hunk 1]
```diff
@@ -22,28 +22,42 @@
...
     }
 
-    @AfterAll
-    public static void stopContainer() throws Exception
+    @AfterEach
+    public void stopContainer() throws Exception
     {
-        components.stop();
-        container.stop();
+        if (components != null)
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/common/AbstractJakartaWebSocketFrameHandlerTest.java]: Just `LifeCycle.stop(components)`, no need to null out the field now that it's not static anymore.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/common/AbstractJakartaWebSocketFrameHandlerTest.java [hunk 2]
```diff
@@ -22,25 +22,30 @@
...
+        decoders = new AvailableDecoders(endpointConfig, coreSession.getWebSocketComponents());
+        uriParams = new HashMap<>();
     }
 
-    @AfterAll
-    public static void stopContainer() throws Exception
+    @AfterEach
+    public void stopContainer() throws Exception
     {
         components.stop();
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-common/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/common/AbstractJakartaWebSocketFrameHandlerTest.java]: You should really use `LifeCycle.stop(components)` and `LifeCycle.stop(container)`.

If, for some reason, in `startContainer()` an exception is thrown, the field will be `null`, and calling `stop()` will cause an NPE.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]

**Review by olamy — APPROVED** [review]
