### PR TITLE
Issue #13683 - UrlParameterDecoder fixed for mixed bytes/chars pct-encoding usage.

### LINKED ISSUE #13683: Badly pct-encoded Shift-JIS is not supported by Jetty 12
**Jetty version(s)**
12.0.0 thru 12.0.28
12.1.0 thru 12.1.2

**Jetty Environment**
All

**HTTP version**
All

**Java version/vendor** `(use: java -version)`
All

**OS type/version**
All

**Description**
When a Shift-JIS form being sent via `x-www-form-urlencoded` contains badly encoded pct-encoded sequences, both Jetty and Java cannot decode them.

Example form data.

```
a=%83z
```

This is expected to be a form with 1 field.  A field with name `a` and value `ホ` ([KATAKANA LETTER HO](https://unicodeplus.com/U+30DB)).

The following sources of this bad encoding ...

* Google Chrome 1.141 with Shift-JIS encoding.
* Firefox 143.0.4 with Shift-JIS encoding.
* Apache HttpClient 4.5.x and 5.x with Shift-JIS encoding.

However, both Jetty and Java decodes the `%83z` as `�z`

```
$ jshell
|  Welcome to JShell -- Version 17.0.15
|  For an introduction type: /help intro

jshell> var shiftJisCharset = java.nio.charset.Charset.forName("Shift-JIS")
shiftJisCharset ==> Shift_JIS

jshell> var result = URLDecoder.decode("%83z", shiftJisCharset)
result ==> "�z"
```

The properly encoded sequence for KATAKANA LETTER HO should be `%83%7A`.

See Java itself ...

```
$ jshell
|  Welcome to JShell -- Version 17.0.15
|  For an introduction type: /help intro

jshell> var shiftJisCharset = java.nio.charset.Charset.forName("Shift-JIS")
shiftJisCharset ==> Shift_JIS

jshell> var result = URLDecoder.decode("%83%7A", shiftJisCharset)
result ==> "ホ"
```

Back in Jetty 9 thru Jetty 11, we had the means to parse this bad encoding.
Something we lack in Jetty 12.

### PR DESCRIPTION
**Pull request by joakime**
Fixed `DecoderStringBuilder.append(char c)` to handle incoming chars with an existing ByteBuffer as just extra bytes for the CharsetDecoder to consume.

More unit tests

### CODE REVIEW

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java [hunk 1]
```diff
@@ -274,7 +271,6 @@ public void reset()
 
     class DecoderStringBuilder implements CharsetStringBuilder
     {
-        private static final Logger LOG = LoggerFactory.getLogger(DecoderStringBuilder.class);
         private final CharsetDecoder _decoder;
         private final StringBuilder _stringBuilder = new StringBuilder(32);
         private ByteBuffer _buffer = ByteBuffer.allocate(32);
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java]: As an aside, we should modify the growth algorithm in `ensureSpace` to match the new one we implemented in `org.eclipse.jetty.util.BlockingArrayQueue.newCapacity` (which probably should be in a utility method somewhere).   Probably not this PR...   I'll create an issue for it.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/URLEncodedTest.java [hunk 2]
```diff
@@ -302,4 +304,33 @@ public void testInvalidDecodeTo(String inputString, Charset charset, Class<? ext
...
+
+    /**
+     * Test of non-standard encoding of Shift_JIS.
+     * This tests a 2 byte sequence making up 1 Shift_JIS character.
+     * But only the first byte is pct-encoded, other byte is "in the raw" and not encoded.
+     * Both bytes are required for the KATAKANA LETTER HO: ホ to be decoded.
+     * See https://unicodeplus.com/U+30DB
+     */
+    @Test
+    public void testSjisNonStandardForm() throws IOException
```
Comment (gregw) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/URLEncodedTest.java]: This test really should just be in `CharsetStringBuilderTest`, as it has nothing to do with the URLness of string being decoded.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/CharsetStringBuilderTest.java [hunk 3]
```diff
@@ -71,34 +75,109 @@ public static Stream<Charset> charsets()
 
     @ParameterizedTest
     @MethodSource("charsets")
-    public void testBasicApi(Charset charset) throws Exception
+    public void testAppendByteBuffersOnly(Charset charset) throws Exception
```
Comment (gregw) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/CharsetStringBuilderTest.java:83]: I'd also like to see a test(s) in this class that have multibyte characters, where any of the bytes that are USASCII are not encoded. (see below)

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/CharsetStringBuilderTest.java [hunk 4]
```diff
@@ -71,34 +75,109 @@ public static Stream<Charset> charsets()
...
+        int sliceSize = 3;
+        int offset = 0;
+        while (offset < chars.length)
+        {
+            int len = Math.min(sliceSize, chars.length - offset);
+            builder.append(input, offset, len);
+            offset += sliceSize;
+        }
+
+        assertThat(builder.build(), is(input));
```
Comment (gregw) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/CharsetStringBuilderTest.java:186]: How about adding this test:

```suggestion
        assertThat(builder.build(), is(input));
    }

    public static Stream<Arguments> japaneseCharsetsTests()
    {
        List<Arguments> args = new ArrayList<>();

        for (Charset charset : List.of(
            StandardCharsets.UTF_8,
            StandardCharsets.UTF_16,
            Charset.forName("Shift_JIS"),
            Charset.forName("EUC-JP")
        ))
        {
            for (String string : List.of("ホ", "カタカナ", "ｶﾞｯﾂﾎﾟｰｽﾞ"))
                args.add(Arguments.of(charset, string));
        }
        return args.stream();
    }

    @ParameterizedTest
    @MethodSource("japaneseCharsetsTests")
    public void testJapaneseCharsetsMixedEncodings(Charset charset, String string) throws Exception
    {
        CharsetStringBuilder builder = CharsetStringBuilder.forCharset(charset);

        byte[] bytes = string.getBytes(charset);
        for (byte b : bytes)
        {
            if (b > 'a' && b < 'z' || b > 'A' && b < 'Z' || b > '0' && b < '9')
                builder.append((char)b);
            else
                builder.append(b);
        }
        assertThat(builder.build(), is(string));
```

**Review by gregw — DISMISSED** [review]
Conditional approval.  I'd like to see the test I suggested added

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java]: @lorban I created #13686 and assigned it to you!

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/CharsetStringBuilderTest.java (hunk 3 above)
Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/CharsetStringBuilderTest.java:83]: That's what CharsetStringBuilderTest.testBuilder() does.

Comment (gregw) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/CharsetStringBuilderTest.java:83]: @joakime Not exactly.  It doesn't mix append(byte) with append(char) and it doesn't test SJIS and other japanese charsets

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/URLEncodedTest.java (hunk 2 above)
Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/URLEncodedTest.java]: Technically this does the UrlParameterDecoder process, char by char, with pct-decoding.
Not the CharsetStringBuilder process, which could be whole char-sequence (no pct-decoding)

I'll add it to UrlParameterDecoderTest instead.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java [hunk 5]
```diff
@@ -306,43 +309,49 @@ public void append(byte b)
...
+                        _stringBuilder.append(c);
+                    }
+                    catch (CharacterCodingException e)
+                    {
+                        if (_decoder.malformedInputAction() == CodingErrorAction.IGNORE)
+                            return;
+                        if (_decoder.malformedInputAction() == CodingErrorAction.REPLACE)
+                        {
+                            _buffer.clear();
+                            _stringBuilder.append("�");
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java]: I would use `\uFFFD` instead of the actual char, or perhaps assign a constant to `\uFFFD` and use the constant here.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java [hunk 6]
```diff
@@ -306,43 +309,49 @@ public void append(byte b)
...
+                            return;
+                        }
+                        throw new IllegalArgumentException("Invalid character " + Integer.toHexString(c), e);
+                    }
+                    return;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java]: I'd remove this and use `else` for the next branch, as we already use `else` if we have no buffer.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java (hunk 5 above)
Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java]: Fixed, we can just use the replacement character(s) that are for the Charset itself (it has that information).

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java (hunk 6 above)
Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/CharsetStringBuilder.java]: Done.

**Review by sbordet — DISMISSED** [review]

**Review by sbordet — APPROVED** [review]
