### PR TITLE
Fix incorrect reliance on autoDemand when handlers are not configured

### LINKED ISSUE #11303: `JettyWebSocketFrameHandler` incorrectly relies on `autoDemand` when handlers are not registered
**Jetty version(s)**
12.0.5

**Jetty Environment**
All

**Description**
When `autoDemand` is configured to `false`, `JettyWebSocketFrameHandler` mistakenly relies on it when it should not for the cases where no handler is registered.

E.g.: if no `openHandle` is registered, we should always demand no matter what the `autoDemand` is configured to. The same is valid for ping frames too.

### PR DESCRIPTION
**Pull request by lorban**
Fixes #11303.

### CODE REVIEW

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java [hunk 1]
```diff
@@ -145,15 +145,16 @@ public void onOpen(CoreSession coreSession, Callback callback)
                 container.notifySessionListeners((listener) -> listener.onWebSocketSessionOpened(session));
 
             callback.succeeded();
+
+            if (openHandle != null)
+                autoDemand();
+            else
+                session.getCoreSession().demand();
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java]: Please refactor this into a method called `internalDemand()`, so it's clearer what it does (and it can be javadoc-ed).

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java [hunk 2]
```diff
@@ -114,4 +137,27 @@ public void testNoDemandWhenProcessingFrame() throws Exception
...
+
+    @Test
+    public void testNoAutoDemand() throws Exception
+    {
+        URI uri = new URI("ws://localhost:" + connector.getLocalPort() + "/listenerSocket");
+        ListenerSocket listenerSocket = new ListenerSocket();
+        Future<Session> connect = client.connect(listenerSocket, uri);
+        Session session = connect.get(5, TimeUnit.SECONDS);
+
+        session.sendPing(ByteBuffer.wrap("ping-0".getBytes(StandardCharsets.UTF_8)), Callback.NOOP);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java:172]: Add a test case where the server sends a PING, so the client receives a PING, and it should be able to receive subsequent frames.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java]: Done.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/ExplicitDemandTest.java:172]: Done.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/FrameListenerTest.java [hunk 3]
```diff
@@ -149,7 +147,6 @@ public void onWebSocketFrame(Frame frame, Callback callback)
                 BufferUtil.toUTF8String(frame.getPayload()),
                 frame.getPayloadLength()));
             callback.succeed();
-            session.demand();
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/server/FrameListenerTest.java:152]: @lachlan-roberts @lorban while currently correct, the removal of this line is not ideal.

If an application wants to handle WebSocket frames directly and only override `onWebSocketFrame()`, it has no direct control over the demand.

I opened https://github.com/jetty/jetty.project/issues/11307

**Review by sbordet — APPROVED** [review]

**Review by lachlan-roberts — APPROVED** [review]
