### PR TITLE
Fix #13883 handle logged null throwable

### LINKED ISSUE #13883: Invalid logger usage in HttpOutput
**Jetty version(s)** 12.1.2
**Jetty Environment** ee9, ee10, ee11
**HTTP version** don't know
**Java version/vendor** `(use: java -version)` Gradle toolchain 21, running in a test so unsure about the exact version, but not relevant anyway.
**OS type/version** Windows 10

Note: I'm using Jetty through Micronaut, so most of the things are set up without my knowledge.

**Description**
These log lines: https://github.com/search?q=repo%3Ajetty%2Fjetty.project+%22LOG.debug%28%5C%22onwritecomplete%22&type=code

https://github.com/jetty/jetty.project/blob/852e3b0258668295c01975bb57fbd609a57cbc81/jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpOutput.java#L330-L332
https://github.com/jetty/jetty.project/blob/852e3b0258668295c01975bb57fbd609a57cbc81/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpOutput.java#L305-L307
https://github.com/jetty/jetty.project/blob/852e3b0258668295c01975bb57fbd609a57cbc81/jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java#L298-L300

Produce a warning when debug logs are enabled:

Image

> **2025-10-26T12:34:22.367710800Z virtual-executor-354635224 WARN found 7 argument placeholders, but provided 8 for pattern `onWriteComplete({},{}) {}->{} c={} cb={} w={}`**
> 2025-10-26T12:34:22,366 DEBUG [virtual-executor-354635224] org.eclipse.jetty.ee10.servlet.HttpOutput(HttpOutput.java:306) onWriteComplete(true,null) s=CLOSING,api=PENDING,sc=false,e=null,wb=oeju.Blocker$Shared@1aa147d6[c=null]->s=CLOSED,api=ASYNC,sc=false,e=null,wb=oeju.Blocker$Shared@1aa147d6[c=null] c=null cb=null w=false

because the `failure` is null, and therefore LOG4J-SLF4J can't figure out that it's a Throwable at: `org.apache.logging.log4j.message.ParameterFormatter#formatMessage`.

**How to reproduce?**
1. Use `log4j-slf4j2-impl` SLF4J backend
2. Enable debug logs for `org.eclipse.jetty`
3. Make a request

### PR DESCRIPTION
**Pull request by gregw**
We can fix issue #13883 with this, but a) it is a bit verbose and b) I'm sure there are other spots in the code.

Utility method maybe ?

### CODE REVIEW

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java [hunk 1]
```diff
@@ -296,8 +296,14 @@ else if (_state == State.CLOSE)
...
             if (LOG.isDebugEnabled())
-                LOG.debug("onWriteComplete({},{}) {}->{} c={} cb={} w={}",
-                    last, failure, state, lockedStateString(), BufferUtil.toDetailString(closeContent), closedCallback, wake, failure);
+            {
+                if (failure == null)
+                    LOG.debug("onWriteComplete({},null) {}->{} c={} cb={} w={}",
+                        last, state, lockedStateString(), BufferUtil.toDetailString(closeContent), closedCallback, wake);
+                else
+                    LOG.debug("onWriteComplete({},{}) {}->{} c={} cb={} w={}",
+                        last, failure, state, lockedStateString(), BufferUtil.toDetailString(closeContent), closedCallback, wake, failure);
```
Comment (olamy) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java]: No need for `failure` as the last parameter as it's already in second position, as this will make 8 objects for 7 placeholders.
I remember one impl was checking parameters type and if exception doing something different (but we cannot rely on logging impl)

Something to try possibly is the fluent log api, not sure if this displays the stacktrace of Throwable though, as it might depend on the final logging implementation but worth to try:


```

      LoggingEventBuilder loggingEventBuilder = LOG.atDebug();
      if(failure != null) loggingEventBuilder = loggingEventBuilder.setCause(failure);
      loggingEventBuilder.log("onWriteComplete({},null) {}->{} c={} cb={} w={}",
              last, state, lockedStateString(), BufferUtil.toDetailString(closeContent), closedCallback, wake);

```

**Review by olamy — DISMISSED** [review]

File: jetty-core/jetty-alpn/jetty-alpn-server/src/main/java/org/eclipse/jetty/alpn/server/ALPNServerConnectionFactory.java [hunk 2]
```diff
@@ -56,7 +56,7 @@ public ALPNServerConnectionFactory(@Name("protocols") String... protocols)
             catch (Throwable x)
             {
                 if (LOG.isDebugEnabled())
-                    LOG.debug(x.getMessage(), x);
+                    LOG.atDebug().setCause(x).log(x.getMessage());
```
Comment (joakime) [inline jetty-core/jetty-alpn/jetty-alpn-server/src/main/java/org/eclipse/jetty/alpn/server/ALPNServerConnectionFactory.java:59]: Not necessary here, you are in a catch block already.

File: jetty-core/jetty-alpn/jetty-alpn-server/src/main/java/org/eclipse/jetty/alpn/server/ALPNServerConnectionFactory.java [hunk 3]
```diff
@@ -70,7 +70,7 @@ public ALPNServerConnectionFactory(@Name("protocols") String... protocols)
             catch (Throwable x)
             {
                 if (LOG.isDebugEnabled())
-                    LOG.debug("Could not initialize {}", processor, x);
+                    LOG.atDebug().setCause(x).log("Could not initialize {}", processor);
```
Comment (joakime) [inline jetty-core/jetty-alpn/jetty-alpn-server/src/main/java/org/eclipse/jetty/alpn/server/ALPNServerConnectionFactory.java:73]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java [hunk 4]
```diff
@@ -635,7 +635,7 @@ public void succeeded(Connection connection)
         public void failed(Throwable x)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("Connection creation failed {}", reserved, x);
+                LOG.atDebug().setCause(x).log("Connection creation failed {}", reserved);
```
Comment (joakime) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:589]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java [hunk 5]
```diff
@@ -238,7 +238,7 @@ public void onComplete(Result result)
             catch (Throwable x)
             {
                 if (LOG.isDebugEnabled())
-                    LOG.debug("Authentication failed", x);
+                    LOG.atDebug().setCause(x).log("Authentication failed");
```
Comment (joakime) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/AuthenticationProtocolHandler.java:241]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/internal/HttpSenderOverHTTP.java [hunk 6]
```diff
@@ -79,7 +79,7 @@ protected void sendHeaders(HttpExchange exchange, ByteBuffer contentBuffer, bool
         catch (Throwable x)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("Unable to send headers on exchange {}", exchange, x);
+                LOG.atDebug().setCause(x).log("Unable to send headers on exchange {}", exchange);
```
Comment (joakime) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/internal/HttpSenderOverHTTP.java:82]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/internal/HttpSenderOverHTTP.java [hunk 7]
```diff
@@ -99,7 +99,7 @@ protected void sendContent(HttpExchange exchange, ByteBuffer contentBuffer, bool
         catch (Throwable x)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("Unable to send content on {}", exchange, x);
+                LOG.atDebug().setCause(x).log("Unable to send content on {}", exchange);
```
Comment (joakime) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/internal/HttpSenderOverHTTP.java:102]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/StandardDeployer.java [hunk 8]
```diff
@@ -121,7 +121,7 @@ public void deploy(ContextHandler contextHandler)
         catch (Throwable t)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("{} Deploy failed {}", this, contextHandler, t);
+                LOG.atDebug().setCause(t).log("{} Deploy failed {}", this, contextHandler);
```
Comment (joakime) [inline jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/StandardDeployer.java:124]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/StandardDeployer.java [hunk 9]
```diff
@@ -153,7 +153,7 @@ public void redeploy(ContextHandler oldHandler, ContextHandler newContextHandler
         catch (Throwable t)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("{} Redeploy failed {}", this, newContextHandler, t);
+                LOG.atDebug().setCause(t).log("{} Redeploy failed {}", this, newContextHandler);
```
Comment (joakime) [inline jetty-core/jetty-deploy/src/main/java/org/eclipse/jetty/deploy/StandardDeployer.java:156]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/transport/internal/HttpConnectionOverFCGI.java [hunk 10]
```diff
@@ -239,7 +239,7 @@ else if (read < 0)
         catch (Exception x)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("Unable to fill from endpoint {}", endPoint, x);
+                LOG.atDebug().setCause(x).log("Unable to fill from endpoint {}", endPoint);
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/client/transport/internal/HttpConnectionOverFCGI.java:242]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ParamsContentParser.java [hunk 11]
```diff
@@ -241,7 +241,7 @@ protected void onParam(String name, String value)
         catch (Throwable x)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("Exception while invoking listener {}", listener, x);
+                LOG.atDebug().setCause(x).log("Exception while invoking listener {}", listener);
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ParamsContentParser.java:244]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ParamsContentParser.java [hunk 12]
```diff
@@ -254,7 +254,7 @@ protected boolean onParams()
...
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ParamsContentParser.java:257]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java [hunk 13]
```diff
@@ -187,7 +187,7 @@ public void parsedHeader(HttpField httpField)
             catch (Throwable x)
             {
                 if (LOG.isDebugEnabled())
-                    LOG.debug("Exception while invoking listener {}", listener, x);
+                    LOG.atDebug().setCause(x).log("Exception while invoking listener {}", listener);
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java:190]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java [hunk 14]
```diff
@@ -200,7 +200,7 @@ private void notifyBegin(int code, String reason)
...
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java:203]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java [hunk 15]
```diff
@@ -213,7 +213,7 @@ private void notifyHeader(HttpField httpField)
...
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java:216]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java [hunk 16]
```diff
@@ -237,7 +237,7 @@ private boolean notifyHeaders()
...
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java:240]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java [hunk 17]
```diff
@@ -273,7 +273,7 @@ private boolean notifyContent(ByteBuffer buffer)
...
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java:276]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java [hunk 18]
```diff
@@ -313,7 +313,7 @@ protected void fail(Throwable failure)
...
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/ResponseContentParser.java:316]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/StreamContentParser.java [hunk 19]
```diff
@@ -92,7 +92,7 @@ public boolean noContent()
         catch (Throwable x)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("Exception while invoking listener {}", listener, x);
+                LOG.atDebug().setCause(x).log("Exception while invoking listener {}", listener);
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/StreamContentParser.java:95]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/StreamContentParser.java [hunk 20]
```diff
@@ -108,7 +108,7 @@ protected boolean onContent(ByteBuffer buffer)
...
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-client/src/main/java/org/eclipse/jetty/fcgi/parser/StreamContentParser.java:111]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java [hunk 21]
```diff
@@ -206,7 +206,7 @@ else if (read == 0)
         catch (Exception x)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("Unable to fill endpoint", x);
+                LOG.atDebug().setCause(x).log("Unable to fill endpoint");
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java:209]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java [hunk 22]
```diff
@@ -279,7 +279,7 @@ private int fillInputBuffer()
         catch (Throwable x)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("Could not fill from {}", this, x);
+                LOG.atDebug().setCause(x).log("Could not fill from {}", this);
```
Comment (joakime) [inline jetty-core/jetty-fcgi/jetty-fcgi-server/src/main/java/org/eclipse/jetty/fcgi/server/internal/ServerFCGIConnection.java:282]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/ByteRange.java [hunk 23]
```diff
@@ -155,7 +155,7 @@ public static List<ByteRange> parse(List<String> headers, long length)
                 catch (Throwable x)
                 {
                     if (LOG.isDebugEnabled())
-                        LOG.debug("could not parse range {}", header, x);
+                        LOG.atDebug().setCause(x).log("could not parse range {}", header);
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/ByteRange.java:158]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 24]
```diff
@@ -185,7 +185,7 @@ else if (token.length() == 4)
         catch (Throwable x)
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("Ignore: Unable to parse Date/Time", x);
+                LOG.atDebug().setCause(x).log("Ignore: Unable to parse Date/Time");
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java:188]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 25]
```diff
@@ -475,7 +475,7 @@ public void fail(Throwable t)
             catch (Throwable x)
             {
                 if (LOG.isDebugEnabled())
-                    LOG.debug("Error closing part {}", this, x);
+                    LOG.atDebug().setCause(x).log("Error closing part {}", this);
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:480]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 26]
```diff
@@ -1285,7 +1285,7 @@ else if (type != HttpTokens.Type.SPACE && type != HttpTokens.Type.HTAB)
             catch (Throwable x)
             {
                 if (LOG.isDebugEnabled())
-                    LOG.debug("parse failure {} {}", state, BufferUtil.toDetailString(buffer), x);
+                    LOG.atDebug().setCause(x).log("parse failure {} {}", state, BufferUtil.toDetailString(buffer));
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1318]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 27]
```diff
@@ -1685,7 +1685,7 @@ private void notifyPartBegin()
             catch (Throwable x)
             {
                 if (LOG.isDebugEnabled())
-                    LOG.debug("failure while notifying listener {}", listener, x);
+                    LOG.atDebug().setCause(x).log("failure while notifying listener {}", listener);
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1718]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 28]
```diff
@@ -1698,7 +1698,7 @@ private void notifyPartHeader(String name, String value)
...
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1731]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 29]
```diff
@@ -1711,7 +1711,7 @@ private void notifyPartHeaders()
...
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1744]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 30]
```diff
@@ -1724,7 +1724,7 @@ private void notifyPartContent(Content.Chunk chunk)
...
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1757]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 31]
```diff
@@ -1737,7 +1737,7 @@ private void notifyPartEnd()
...
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1770]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 32]
```diff
@@ -1750,7 +1750,7 @@ private void notifyComplete()
...
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1783]: Not necessary here, you are in a catch block already.
The Throwable will exist.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 33]
```diff
@@ -1763,7 +1763,7 @@ private void notifyFailure(Throwable failure)
...
```
Comment (joakime) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1796]: Not necessary here, you are in a catch block already.
The Throwable will exist.

**Review by joakime — CHANGES_REQUESTED** [review]
The `LOG.atDebug().setCause(x)...` code is only necessary when you are dealing with code that might have a null Throwable.

The following code blocks are 100% supported by slf4j and log4j2 when the Throwable is not null.
``` java
LOG.debug("message", x);
LOG.debug("message with {} params {}", param1, param2, x);
```

Every code block that is in a `catch (Throwable)` doesn't need to use the `LOG.atDebug().setCause(x)...` technique, as the Throwable is guaranteed to be not null.
You can undo about 90%+ of the change you just made in this PR.

**Review by sbordet — CHANGES_REQUESTED** [review]
I agree with @joakime that we should only use the builder style only when necessary.

**Comment by gregw** [comment]
@joakime @sbordet I was thinking of only using the builder style when it was strictly needed, but then that is an NP-complete problem to fully calculate. So in the end, I thought it was just best to use the fluent style whenever we want to add a cause.  It will then be the default pattern we use and we don't have to think about what happens if the throwable is null.

**Review by sbordet — CHANGES_REQUESTED** [review]
> @joakime @sbordet I was thinking of only using the builder style when it was strictly needed, but then that is an NP-complete problem to fully calculate.

I think you're exaggerating. There are probably just a handful of places outside of catch blocks or fail-style methods such as `fail(Throwable)` that we need to fix.

And I think a warning is way too severe of an event to emit for a DEBUG log that has an extra parameter that is `null` and won't actually log anything either way, so I'd categorize this as a LOG4J weirdness for which we should not really sweat too much.

We certainly do not want to have a utility wrapper also for logging!

**Comment by gregw** [comment]
> > @joakime @sbordet I was thinking of only using the builder style when it was strictly needed, but then that is an NP-complete problem to fully calculate.
> 
> I think you're exaggerating. There are probably just a handful of places outside of catch blocks or fail-style methods such as `fail(Throwable)` that we need to fix.

Well if we used some kind of @NotNull annotation, then this would not be an issue.

But what is wrong with using the fluent style anyway, as I think it is clearer than having to count "{}" to see if the last arg is treated as a cause or just an arg.

**Comment by joakime** [comment]
> But what is wrong with using the fluent style anyway, as I think it is clearer than having to count "{}" to see if the last arg is treated as a cause or just an arg.

IntelliJ tells you this btw.
Not enough (or too many) `{}`, it's an error.
If there is 1 more param than `{}` then the last one better be a `Throwable`, otherwise it's an error.

**Comment by gregw** [comment]
> > But what is wrong with using the fluent style anyway, as I think it is clearer than having to count "{}" to see if the last arg is treated as a cause or just an arg.
> 
> IntelliJ tells you this btw. Not enough (or too many) `{}`, it's an error. If there is 1 more param than `{}` then the last one better be a `Throwable`, otherwise it's an error.

@joakime No it doesn't. It tells you if you have the number wrong.  But it does not tell you which of the two correct interpretations you are using.  Last arg can be a cause or an arg depending on the number of {}

**Comment by joakime** [comment]
> @joakime No it doesn't. It tells you if you have the number wrong. But it does not tell you which of the two correct interpretations you are using. Last arg can be a cause or an arg depending on the number of {}

If you use the Throwable as the `{}`...
Note the colorization of the `{}`, on my color scheme this means there is no associated method parameter that fits this `{}`.

Screenshot from 2025-10-29 16-05-54

If you have a parameter, and attempt to use `{}` on it...
Note the colorization of the `{}`, the left hand one has an associated method parameter, the second one doesn't.

Screenshot from 2025-10-29 16-06-17

The proper usage. (no error)

Screenshot from 2025-10-29 16-06-09

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java (hunk 1 above)
Comment (TWiStErRob) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java]: The difference is whether the stack trace is logged though, isn't it?
`{}` will take the toString only, so we know the exception type and message, while putting it in as a last param makes the logger render the full Throwable nicely.

Of course it depends on your logging intentions.

**Comment by gregw** [comment]
> > @joakime No it doesn't. It tells you if you have the number wrong. But it does not tell you which of the two correct interpretations you are using. Last arg can be a cause or an arg depending on the number of {}
> 
> If you use the Throwable as the `{}`... Note the colorization of the `{}`, on my color scheme this means there is no associated method parameter that fits this `{}`.

I don't agree with intellij's colorization in this case. `LOG.debug("whoops {}", ex);` is a perfectly valid usage of the API.  It is a little ambiguous, hence the reason this PR is a good idea.  Using the fluent API removes the ambiguity if a passed Throwable is a cause or an argument.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 34]
```diff
@@ -757,11 +757,9 @@ protected ClassLoader enterScope(Request contextRequest)
...
             {
                 // Log as warning the first time it happens.
-                String msg = "Error setting a context classloader on thread {}";
-                if (_enterScopeSetClassloaderFailed.compareAndSet(false, true))
-                    LOG.warn(msg, Thread.currentThread(), x);
-                else if (LOG.isDebugEnabled())
-                    LOG.debug(msg, Thread.currentThread(), x);
+                (_enterScopeSetClassloaderFailed.compareAndSet(false, true) ? LOG.atWarn() : LOG.atDebug())
+                    .setCause(x)
+                    .log("Error setting a context classloader on thread {}", Thread.currentThread());
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java:762]: @joakime @sbordet Also with the fluent style, code like this is much nicer as it avoids duplicating the log call!

**Comment by joakime** [comment]
> I don't agree with intellij's colorization in this case. `LOG.debug("whoops {}", ex);` is a perfectly valid usage of the API. It is a little ambiguous, hence the reason this PR is a good idea. Using the fluent API removes the ambiguity if a passed Throwable is a cause or an argument.

There's no ambiguity, the API for `LOG.debug("whoops {}", ex)` is for the method [`Logger.debug(String msg, Throwable t)`](https://github.com/qos-ch/slf4j/blob/v_2.0.17/slf4j-api/src/main/java/org/slf4j/Logger.java#L379)

There are no argument parameters or what you call "cause" in that use case.

Here's the docs for how Throwable is treated in various logging libraries.

* slf4j (last arg Throwable is special) - https://slf4j.org/faq.html#paramException
* log4j (last arg Throwable is special) same behavior in log4j1 and log4j2 - https://logging.apache.org/log4j/2.x/manual/api.html#best-practice-exception
* java.util.logging (Throwable specific methods) -  https://docs.oracle.com/en/java/javase/17/docs/api/java.logging/java/util/logging/Logger.html
* commons-logging (Throwable specific methods) -  https://commons.apache.org/proper/commons-logging/apidocs/org/apache/commons/logging/Log.html

**Comment by joakime** [comment]
Be gentle with fluent style, it will cause more object creation.

**Comment by gregw** [comment]
@joakime you are just re-enforcing my point that there is ambiguity in that API because they have both `debug(String, Throwable)` and `debug(String, Object)` and  `debug(String, Object...)` !

Best to avoid that ambiguity (be it perceived or actual).

The fluent API allows for a clear statement of intent.   The cost is a trivial even wrapper, which will not significantly change object allocation.

**Comment by gregw** [comment]
@sbordet Can I get this reviewed before you go away.  I think these changes are good:
- consistently use the same API for handling causes
- There is no visual or real ambiguity about if a throwable should be logged as a string or a cause
- trivial additional builder cost only if debug is turned on

**Review by sbordet — APPROVED** [review]
I am not thrilled, but also there are some obvious goodnesses, so LGTM.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java [hunk 35]
```diff
@@ -700,7 +700,7 @@ public void run()
                             catch (Throwable x)
                             {
                                 if (LOG.isDebugEnabled())
-                                    LOG.debug("{} while invoking onTimeout listener {}", x.toString(), listener, x);
+                                    LOG.atDebug().setCause(x).log("{} while invoking onTimeout listener {}", x.toString(), listener);
                                 else
                                     LOG.warn("{} while invoking onTimeout listener {}", x.toString(), listener);
```
Comment (Mahoney) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java:705]: You should not change the level you log at based on what level is enabled on the logger. The `isXxxxEnabled` methods should generally only be used for performance optimisation, avoiding building objects to pass them to a logger that will then discard them.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java [hunk 36]
```diff
@@ -866,7 +866,7 @@ protected boolean onError(Throwable th)
                 catch (Throwable x)
                 {
                     if (LOG.isDebugEnabled())
-                        LOG.debug("{} while invoking onError listener {}", x, listener, x);
+                        LOG.atDebug().setCause(x).log("{} while invoking onError listener {}", x, listener);
                     else
                         LOG.warn("{} while invoking onError listener {}", x, listener);
```
Comment (Mahoney) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java:871]: You should not change the level you log at based on what level is enabled on the logger. The `isXxxxEnabled` methods should generally only be used for performance optimisation, avoiding building objects to pass them to a logger that will then discard them.
