### PR TITLE
Issue #4707 wrong value for ServletContext.setSessionTimeout

### LINKED ISSUE #4707: Value for ServletContext.setSessionTimeout is wrong in StandardDescriptorProcessor
**jetty-10.0.x**

o.e.j.webapp.StandardDescriptorProcessor.visitSessionConfig() method is incorrectly multiplying the value of the session-timeout from web.xml by 60 to convert to seconds before calling ServletContext.setSessionTimeout(), which is in fact expecting minutes.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #4707

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java [hunk 1]
```diff
@@ -834,6 +834,7 @@ public void setSessionIdManager(SessionIdManager metaManager)
     public void setMaxInactiveInterval(int seconds)
     {
         _dftMaxIdleSecs = seconds;
+        System.err.println("SETMAXINACTIVE = " + seconds);
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java]: println left in

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java [hunk 2]
```diff
@@ -1386,6 +1386,7 @@ public void setSessionTrackingModes(Set<SessionTrackingMode> sessionTrackingMode
         @Override
         public int getSessionTimeout()
         {
+            System.err.println("CALLING GETSESSIONTIMEOUT");
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java]: ditto... and more below

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/StandardDescriptorProcessor.java [hunk 3]
```diff
@@ -660,8 +660,8 @@ public void visitSessionConfig(WebAppContext context, Descriptor descriptor, Xml
         if (tNode != null)
         {
             long val = Long.parseLong(tNode.toString(false, true));
-            val = TimeUnit.MINUTES.toSeconds(val);
-            if (val > Integer.MAX_VALUE)
+            System.err.println("SESSION CONFIG TIMEOUT = " + val);
```
Comment (gregw) [inline jetty-webapp/src/main/java/org/eclipse/jetty/webapp/StandardDescriptorProcessor.java]: println left in

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/StandardDescriptorProcessor.java [hunk 4]
```diff
@@ -660,8 +660,8 @@ public void visitSessionConfig(WebAppContext context, Descriptor descriptor, Xml
         if (tNode != null)
         {
             long val = Long.parseLong(tNode.toString(false, true));
```
Comment (gregw) [inline jetty-webapp/src/main/java/org/eclipse/jetty/webapp/StandardDescriptorProcessor.java]: can we change the name of val to something that includes the units.  It is not clear that this is where the fix is.

**Review by gregw — CHANGES_REQUESTED** [review]

**Review by gregw — APPROVED** [review]
