### PR TITLE
Fixes #7647 - Document org.eclipse.jetty.client.Socks4Proxy "secure" parameter.

### LINKED ISSUE #7647: Document org.eclipse.jetty.client.Socks4Proxy "secure" parameter
**Target Jetty version(s)**

11.0.8

**Enhancement Description**

Socks4Proxy has a constructor that takes a `boolean secure` argument. I'd love to understand the implication of `true` and `false` values for this parameter. All I know is that when I set `secure=true` I am no longer able to tunnel through a SOCKS proxy :)

First, I'd like to understand what's insecure about `secure=false`. Secondly, I'd like to understand why `secure=true` is failing for me.

What I'm doing:

I used Apache Mina to create a SOCKS proxy over SSH tunnel. I can connect `Socks4Proxy(secure=false)` to it, but `secure=true` fails. If I understood the meaning of this parameter then maybe I could circle back to the MINA guys and ask them what it would take to make `secure=true` work.

### PR DESCRIPTION
**Pull request by sbordet**
Added javadocs and documentation.

### CODE REVIEW

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java [hunk 1]
```diff
@@ -38,35 +38,92 @@
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
+/**
+ * <p>Client-side proxy configuration for HTTP proxying, as specified by
+ * <a href="https://www.rfc-editor.org/rfc/rfc9110.html">RFC 9110</a>.</p>
+ * <p>By default the communication between client and proxy happens using
+ * the HTTP/1.1 protocol, but it may be configured otherwise and use
+ * also other HTTP protocol versions such as HTTP/2.</p>
```
Comment (joakime) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java]:
```suggestion
 * the HTTP/1.1 protocol, but it may be configured to use
 * other HTTP protocol versions, such as HTTP/2.</p>
```

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java [hunk 2]
```diff
@@ -38,35 +38,92 @@
...
+     */
     public HttpProxy(Origin.Address address, boolean secure, Origin.Protocol protocol)
     {
         this(new Origin(secure ? "https" : "http", address, null, protocol, Transport.TCP_IP), null);
     }
 
+    /**
+     * <p>Creates a new instance with the given HTTP proxy address and TLS configuration.</p>
+     * <p>The {@link SslContextFactory} has a possibly different configuration from the
+     * one configured in {@link HttpClient} and it is used to communicate with the HTTP
```
Comment (joakime) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java]:
```suggestion
     * <p>The {@link SslContextFactory} could have a different configuration from the
     * one configured in {@link HttpClient} resulting in the provided configuration being used to communicate with the HTTP
```

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java [hunk 3]
```diff
@@ -38,35 +38,92 @@
...
     public HttpProxy(Origin.Address address, SslContextFactory.Client sslContextFactory)
     {
         this(address, sslContextFactory, new Origin.Protocol(List.of("http/1.1"), false));
     }
 
+    /**
+     * <p>Creates a new instance with the given HTTP proxy address, TLS configuration and protocol.</p>
+     * <p>The {@link SslContextFactory} has a possibly different configuration from the
+     * one configured in {@link HttpClient} and it is used to communicate with the HTTP
+     * proxy only (not to servers).</p>
```
Comment (joakime) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java]:
```suggestion
     * <p>The {@link SslContextFactory} could have a different configuration from the
     * one configured in {@link HttpClient} resulting in the provided configuration being used to communicate with the HTTP
     * proxy only (not to servers).</p>
```

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java [hunk 4]
```diff
@@ -38,35 +38,92 @@
...
     public HttpProxy(Origin.Address address, SslContextFactory.Client sslContextFactory, Origin.Protocol protocol)
     {
         this(new Origin(sslContextFactory == null ? "http" : "https", address, null, protocol, Transport.TCP_IP), sslContextFactory);
     }
 
+    /**
+     * <p>Creates a new instance with the given HTTP proxy {@link Origin} and TLS configuration.</p>
+     * <p>The {@link SslContextFactory} has a possibly different configuration from the
+     * one configured in {@link HttpClient} and it is used to communicate with the HTTP
+     * proxy only (not to servers).</p>
```
Comment (joakime) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/HttpProxy.java]: Ditto, same as above

**Review by joakime — COMMENTED** [review]
Some language tweaks

**Review by joakime — APPROVED** [review]
