### PR TITLE
Fixes #13615 - Concurrency issue, headers from different requests are mixed in Jetty 12.0.27.

### LINKED ISSUE #13615: Concurrency issue, headers from different requests are mixed in Jetty 12.0.27
**Jetty version(s)**
Jetty 12.0.27

**Jetty Environment**
ee10

**Java version/vendor**
openjdk 25 2025-09-16 LTS
OpenJDK Runtime Environment Temurin-25+36 (build 25+36-LTS)
OpenJDK 64-Bit Server VM Temurin-25+36 (build 25+36-LTS, mixed mode, sharing)

**OS type/version**
Ubuntu 24.04.3 LTS

**Description**
When navigating on a server with concurrent traffic, sometimes an error page is displayed:
```
HTTP ERROR 400 Illegal header value 
JSESSIONID=aryawzf44....a; language=en; user_id=307.....6104; country=au;

URI: /badRequest
STATUS: 400
MESSAGE:  Illegal header value  JSESSIONID=aryawzf44....a; language=en; user_id=307.....6104; country=au;
```

But for this same request, Google Chrome inspect reports this value for the "Cookie" header:
`language=es; user_id=5540616.....06; country=es; JSESSIONID=aryai7kdg7h...a; <...and other cookies...>`

So clearly the information from one request (the Cookie header at least) is being mixed with another request in what looks like a concurrency issue.

This was not happening at all in Jetty 12.0.22

**How to reproduce?**
Navigate on a server with traffic and wait for the 400 error page.

### PR DESCRIPTION
**Pull request by sbordet**
* Added handling failed MetaData in HTTP2Stream.onHeaders(), in case the response contains bad headers.
* Properly resetting at the end of MetaDataBuilder.build(): before the _streamException field was not reset, leading to failing also the next requests/responses.
* Made sure MetaDataBuilder.build() resets even when a failure is detected early at the beginning of the method.
* Added checks in HpackDecoder for indexed entries that may have been stored with invalid header name/value.
* HpackDecoder now stores a lower-case "content-length: 0", so that subsequent retrievals do not fail the checks added above.
* Added test cases for concurrent good and bad responses.
* Similar changes for HTTP/3.

See https://github.com/jetty/jetty.project/pull/13700 for the 12.0 PR.

### CODE REVIEW

File: jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java [hunk 1]
```diff
@@ -138,9 +140,18 @@ public MetaData decode(ByteBuffer buffer) throws HpackException.SessionException
                 {
                     if (LOG.isDebugEnabled())
                         LOG.debug("decode Idx {}", entry);
+
+                    String name = field.getName();
+                    if (!HttpTokens.isLegalH2H3FieldName(name))
+                        _builder.streamException("Illegal header name %s", name);
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackDecoder.java:146]: Should this be 
```suggestion
                    String name = field.getName();
                    if (field.getHeader() == null && !HttpTokens.isLegalH2H3FieldName(name))
                        _builder.streamException("Illegal header name %s", name);
```

That will be faster in the most common case.  We could have a lowercase only cache lookup (at line 223 below ) for finding known fields in the first place?

Actually, line 220 is already doing the isLegalH2H3FieldName check?   Perhaps we can replace that with:
```java
                header = HttpHeader.LOWER_CASE_CACHE.get(name);
                if (header == null && (!HttpTokens.isLegalH2H3FieldName(name))
                    _builder.streamException("Illegal header name %s", name);
```

**Review by gregw — APPROVED** [review]
LGTM other than a small optimisation idea

**Review by lorban — APPROVED** [review]
