### PR TITLE
Fixes #12122 - NPE in HttpReceiver.responseContentAvailable().

### LINKED ISSUE #12122: NPE in HttpReceiver.responseContentAvailable()
**Jetty version(s)**
12

**Description**
```
2024-07-29T20:27:41.8354855Z 2024-07-29T19:52:43.928Z	WARN	http-client-scheduler-512	org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy	Task run failed
2024-07-29T20:27:41.8355422Z java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.client.transport.HttpReceiver$NotifiableContentSource.onDataAvailable()" because "this.contentSource" is null
2024-07-29T20:27:41.8355750Z 	at org.eclipse.jetty.client.transport.HttpReceiver.responseContentAvailable(HttpReceiver.java:325)
2024-07-29T20:27:41.8356147Z 	at org.eclipse.jetty.http2.client.transport.internal.HttpReceiverOverHTTP2.lambda$new$0(HttpReceiverOverHTTP2.java:53)
2024-07-29T20:27:41.8356370Z 	at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
2024-07-29T20:27:41.8356731Z 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
2024-07-29T20:27:41.8357793Z 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:426)
2024-07-29T20:27:41.8358221Z 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
2024-07-29T20:27:41.8358723Z 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
2024-07-29T20:27:41.8358949Z 	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:210)
2024-07-29T20:27:41.8359186Z 	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:157)
2024-07-29T20:27:41.8359470Z 	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:442)
2024-07-29T20:27:41.8359659Z 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
2024-07-29T20:27:41.8359936Z 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
2024-07-29T20:27:41.8360287Z 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
2024-07-29T20:27:41.8360671Z 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
2024-07-29T20:27:41.8361206Z 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
2024-07-29T20:27:41.8361544Z 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
2024-07-29T20:27:41.8361869Z 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
2024-07-29T20:27:41.8362311Z 	at org.eclipse.jetty.util.thread.MonitoredQueuedThreadPool$1.run(MonitoredQueuedThreadPool.java:73)
2024-07-29T20:27:41.8362557Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
2024-07-29T20:27:41.8362835Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
2024-07-29T20:27:41.8363097Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
2024-07-29T20:27:41.8363240Z 	at java.base/java.lang.Thread.run(Thread.java:1570)
```

### PR DESCRIPTION
**Pull request by sbordet**
Now also the HttpReceiver.responseContentAvailable() is serialized, so that the access to `this.contentSource` is serialized with failure, and protected by a call to `exchange.isResponseCompleteOrTerminated()`.

Before, it was possible that a thread failed the response, nulling out `this.contentSource`, while another thread was just about to call `responseContentAvailable()` -- this was the case for HTTP/2 in particular, where content is notified asynchronously, rather than being created by a call to `ContentSource.read()`.

### CODE REVIEW

**Comment by wendigo** [comment]
@sbordet can you stage artifacts for me to test?

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java [hunk 1]
```diff
@@ -315,13 +315,35 @@ protected void responseHeaders(HttpExchange exchange)
      * Method to be invoked when response content is available to be read.
      * <p>
      * This method takes care of ensuring the {@link Content.Source} passed to
-     * {@link Response.ContentSourceListener#onContentSource(Response, Content.Source)} calls the
-     * demand callback.
+     * {@link Response.ContentSourceListener#onContentSource(Response, Content.Source)}
+     * calls the demand callback.
+     * The call to the demand callback is serialized with other events.
      */
```
Comment (firoj0) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java:321]: All India Truck

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java [hunk 2]
```diff
@@ -315,13 +315,35 @@ protected void responseHeaders(HttpExchange exchange)
...
-    protected void responseContentAvailable()
+    protected void responseContentAvailable(HttpExchange exchange)
     {
```
Comment (firoj0) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java:323]: All India Truck}

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java [hunk 3]
```diff
@@ -712,9 +734,9 @@ public void onDataAvailable()
         {
             if (LOG.isDebugEnabled())
                 LOG.debug("onDataAvailable on {}", this);
```
Comment (firoj0) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java:736]: - [ ] qureshifiroj88@gmail.com

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java [hunk 4]
```diff
@@ -760,29 +782,28 @@ private void processDemand()
...
             invokeDemandCallback(false);
         }
 
         private void invokeDemandCallback(boolean invoke)
         {
             Runnable demandCallback = demandCallbackRef.getAndSet(null);
             if (LOG.isDebugEnabled())
-                LOG.debug("Invoking demand callback on {}", this);
-            if (demandCallback != null)
+                LOG.debug("Invoking demand callback {} on {}", demandCallback, this);
```
Comment (firoj0) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java:794]: qureshifiroj88@gmail.com

**Review by firoj0 — COMMENTED** [review]
qureshifiroj88@gmail.com

**Comment by firoj0** [comment]
Firoj07

**Comment by wendigo** [comment]
I can confirm that this change fixes the issue that we've seen in our benchmarks while running with HTTP/2

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java [hunk 5]
```diff
@@ -315,13 +315,35 @@ protected void responseHeaders(HttpExchange exchange)
...
+        });
+    }
+
+    /**
+     * Method to be invoked when response content is available to be read.
+     * <p>
+     * This method directly invokes the demand callback, assuming the caller
+     * is already serialized with other events.
+     */
+    protected void responseContentAvailable()
```
Comment (lorban) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java:345]: Shouldn't this method be private?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java:345]: No, it is called from other places when it's known that there is no need to serialize.

**Review by lorban — DISMISSED** [review]

**Review by lorban — APPROVED** [review]
