### PR TITLE
Fixes #3090 - MBeanContainer throws NPE for arrays.

### LINKED ISSUE #3090: MBeanContainer throws NPE for arrays
`MBeanContainer.mbeanFor(obj)` where `obj` is an array of any kind throws `NullPointException`.

This is due to the fact that `obj.getClass().getPackage()` returns `null` and the code assumes there always is a package.

### PR DESCRIPTION
**Pull request by sbordet**
Issue #3090.
Corrected places that were making unguarded calls to Class.getPackage().
Added tests for various array cases.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-jmx/src/main/java/org/eclipse/jetty/jmx/MBeanContainer.java [hunk 1]
```diff
@@ -217,8 +217,11 @@ private static MetaData newMetaData(MBeanContainer container, Class<?> klass)
 
     private static Constructor<?> findConstructor(Class<?> klass)
     {
-        String pName = klass.getPackage().getName();
-        String cName = klass.getName().substring(pName.length() + 1);
+        Package pkg = klass.getPackage();
+        if (pkg == null)
+            return null;
```
Comment (joakime) [inline jetty-jmx/src/main/java/org/eclipse/jetty/jmx/MBeanContainer.java]: Is there no other way to return the constructor?
Or is this specifically for the constructor on the `<package>.jmx.<className>MBean` usage?

Comment (sbordet) [reply jetty-jmx/src/main/java/org/eclipse/jetty/jmx/MBeanContainer.java]: This is the constructor specific for `*.jmx.*MBean`.
