### PR TITLE
Issue #13057 - ServletContext.getResource() failures should result in MalformedURLException or null

### LINKED ISSUE #13057: InvalidPathException instead of MalformedURLException after switching to jetty12
**Jetty version(s)**
12.0.16

**Jetty Environment**
ee10

**Java version/vendor**
java version "21.0.2" 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

**OS type/version**
windows 11

**Description**
In our application we are trying to get the resource. In some cases it can be an html file
```java
jakarta.servlet.ServletContext.getResource("/test.html");
```
or even html code
```java
jakarta.servlet.ServletContext.getResource("/Welcome home <br>");
```

In case of use of html code, after switching to jetty12 and org.eclipse.jetty.ee10.webapp.WebAppContext we got an InvalidPathException instead of MalformedURLException, which caused our application to crash.

```
Caused by: java.nio.file.InvalidPathException: Illegal char <<> at index XXX: C:/XXX/webapp/Welcome home <br>
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175) ~[?:?]
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
        at sun.nio.fs.WindowsUriSupport.fromUri(WindowsUriSupport.java:166) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.getPath(WindowsFileSystemProvider.java:96) ~[?:?]
        at java.nio.file.Path.of(Path.java:204) ~[?:?]
        at java.nio.file.Paths.get(Paths.java:98) ~[?:?]
        at org.eclipse.jetty.util.resource.PathResource.resolve(PathResource.java:294) ~[?:?]
        at org.eclipse.jetty.ee10.servlet.ServletContextHandler.getResource(ServletContextHandler.java:774) ~[?:?]
        at org.eclipse.jetty.ee10.webapp.WebAppContext.getResource(WebAppContext.java:366) ~[?:?]
        at org.eclipse.jetty.ee10.webapp.WebAppContext$ServletApiContext.getResource(WebAppContext.java:1478) ~[?:?]
```

**How to reproduce?**
```java
package org.example;

import org.eclipse.jetty.ee10.annotations.AnnotationConfiguration;
import org.eclipse.jetty.ee10.plus.webapp.EnvConfiguration;
import org.eclipse.jetty.ee10.plus.webapp.PlusConfiguration;
import org.eclipse.jetty.ee10.webapp.*;
import org.eclipse.jetty.ee10.websocket.jakarta.server.config.JakartaWebSocketConfiguration;
import org.eclipse.jetty.server.AllowedResourceAliasChecker;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.handler.ContextHandlerCollection;
import org.eclipse.jetty.server.handler.ErrorHandler;
import org.eclipse.jetty.util.ClassMatcher;

import java.io.IOException;
import java.io.Writer;

public class Main {
	public static void main(String[] args) throws Exception {
		ContextHandlerCollection contexts = new ContextHandlerCollection();
		Server server = new Server(8080);
		WebAppContext webapp = new WebAppContext();
		webapp.setContextPath("/");
		webapp.setBaseResourceAsString("C:\\Projects\\embedded-jetty\\src\\main\\webapp\\");
		webapp.setTempDirectoryPersistent(true);
		webapp.setThrowUnavailableOnStartupException(true);
		webapp.addAliasCheck(new AllowedResourceAliasChecker(webapp));
		webapp.setDefaultsDescriptor(null);
		webapp.addHiddenClassMatcher(new ClassMatcher("org.slf4j.impl.StaticLoggerBinder"));
		webapp.setConfigurations(new org.eclipse.jetty.ee10.webapp.Configuration[] { new WebInfConfiguration(), new MetaInfConfiguration(), new FragmentConfiguration(), new EnvConfiguration(), new PlusConfiguration(), new AnnotationConfiguration(), new WebXmlConfiguration(), new JakartaWebSocketConfiguration() });
		ErrorHandler errorHandler = new ErrorHandler() {
			@Override
			protected void writeErrorHtmlBody(Request request, Writer writer, int code, String message, Throwable cause, boolean showStacks) throws IOException {
				String uri = request.getHttpURI().asString();
				this.writeErrorHtmlMessage(request, writer, code, message, null, uri);
			}
		};
		webapp.setErrorHandler(errorHandler);
		webapp.addServlet(new JakartaServlet(), "/test");
		contexts.addHandler(webapp);
		server.setHandler(contexts);
		server.start();
		System.out.println("Server started at http://localhost:8080/");
		server.join();
	}
}
```
```java
package org.example;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.MalformedURLException;

@WebServlet("/test")
public class JakartaServlet extends HttpServlet {
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
		PrintWriter out = resp.getWriter();
		out.println("HELLO FROM JAKARTA!");
		try {
			getServletContext().getResource("Welcome home <br>");
		} catch (MalformedURLException e) {
			// WORKS
			System.out.println("1 : ERROR : " + e.getMessage());
		}
		try {
			getServletContext().getResource("/Welcome home <br>");
		} catch (MalformedURLException e) {
			// DOES NOT WORK (THROWS java.nio.file.InvalidPathException)
			System.out.println("2 : ERROR : " + e.getMessage());
		}
		// DOES NOT PRINT
		System.out.println("+++END+++");
	}
}
```
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>embedded-jetty</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jetty.version>12.0.16</jetty.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.jetty.ee10.websocket</groupId>
            <artifactId>jetty-ee10-websocket-jakarta-server</artifactId>
            <version>${jetty.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.36</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.example.Main</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

1. mvn clean install
2. run jetty server 
```
C:\Java\jdk-21\bin\java -jar C:/Projects/embedded-jetty/target/embedded-jetty-1.0-SNAPSHOT.jar
```
3. open localhost:8080/test
4. an error is displayed

### PR DESCRIPTION
**Pull request by joakime**
Closes: #13057

### CODE REVIEW

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java [hunk 1]
```diff
@@ -113,7 +113,19 @@ public Set<String> getResourcePaths(String path)
...
+            return _targetContext.getBaseResource().resolve(path).getURI().toURL();
+        }
+        catch (MalformedURLException e)
+        {
+            throw e;
+        }
+        catch (Throwable e)
+        {
+            // catch IOException, RuntimeException, and things like java.nio.fileInvalidPathException here.
+            throw new MalformedURLException(path);
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java]: We don't want to lose the original exception, so you either need to do:
```suggestion
            throw new MalformedURLException(path)
            {
                { 
                    initCause(cause);
                }
            };
```

or create a utility method/class somewhere that does that

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java [hunk 2]
```diff
@@ -2856,29 +2856,41 @@ else if (path.charAt(0) != '/')
...
             {
-                // return first
-                if (Resources.exists(r))
-                    return r.getURI().toURL();
+                throw e;
+            }
+            catch (Throwable e)
+            {
+                // catch IOException, RuntimeException, and things like java.nio.fileInvalidPathException here.
+                throw new MalformedURLException(path);
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java]: ditto

**Review by gregw — CHANGES_REQUESTED** [review]
set the cause

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java (hunk 1 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java]: This was an intentional decision to not include the cause.  Mainly to avoid revealing FileSystem details on error pages.

Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java]: I added a new `org.eclipse.jetty.util.EnhancedMalformedURLException`. (perhaps it should be in jetty-io?)

If we have a need to not include specific causes (like we did in the past), we can add the logic there.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java (hunk 2 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java]: There were more places than just the 2 you flagged in your review.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/EnhancedMalformedURLException.java [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+//
+
+package org.eclipse.jetty.util;
+
+import java.net.MalformedURLException;
+
+/**
+ * Enhanced {@link MalformedURLException} that allows for causes.
+ */
+public class EnhancedMalformedURLException extends MalformedURLException
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/EnhancedMalformedURLException.java]: Maybe:
```suggestion
public class CausalMalformedURLException extends MalformedURLException
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/EnhancedMalformedURLException.java [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+{
+    public EnhancedMalformedURLException(String msg)
+    {
+        super(msg);
+    }
+
+    public EnhancedMalformedURLException(String msg, Throwable cause)
+    {
+        super(msg);
+        initCause(cause);
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/EnhancedMalformedURLException.java]: If we are really concerned about revealing the root cause, we could either:
a) use a system property to not initialise it here (yuck)
b) have options on our default ErrorHandler to reveal either:
     + No exception information
     + Exception type but not message or stack
     + Exception with stack, but no cause or suppressed
     + Exception with stack, causes and suppressions

I think b) would be a good (other PR) enhancement.

**Review by gregw — DISMISSED** [review]
LGTM other than minor naming suggestion.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/EnhancedMalformedURLException.java (hunk 3 above)
Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/EnhancedMalformedURLException.java]: Heh, I read that as "casual" (def: _informal, relaxed_) at first, and was questioning where you were going with that suggestion.

The word "Causal" has multiple meanings to me.

* def group 1: _imaginative, innovative, inventive, unusual_ - this isn't right.
* def group 2: _of, relating to or being a cause of something_ -  this is opposite of what I think it should be.

How about one of these ...

* `DetailedMalformedURLException` - as in the cause is a bit of detail that could be provided.
* `ResourceMalformedURLException` - as in the various resource methods is really the only place this exists (limited in scope).
* `IdealMalformedURLException` - as in this is the ideal form, with an optional cause for detail.
* `CausationMalformedURLException` - as in this exception can have a cause.
* `OptionalCauseMalformedURLException` - just to clear and wordy.

Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/EnhancedMalformedURLException.java]: `CausationMalformedURLException` does what it says on the tin!
or alternately to be really clear and wordy `MalformedURLExceptionWithCauseAsItShouldHaveBeenInTheFirstPlaceExclamationMarkExclamantionMark`

The other option, is to use the normal `MalformedURLException` and just add the cause as a suppressed.  That makes little difference in how we handle it and does avoid losing it without introducing a new class.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java [hunk 5]
```diff
@@ -125,7 +125,7 @@ public URL getResource(String path) throws MalformedURLException
         catch (Throwable e)
         {
             // catch IOException, RuntimeException, and things like java.nio.fileInvalidPathException here.
-            throw new EnhancedMalformedURLException(path, e);
+            throw new CausationMalformedURLException(path, e);
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java]: @joakime I'm good with the name change, but I just noticed your are declaring this in throw clauses. 

How we set the cause is an implementation detail. So no need to change these signatures.. Just throw MalformedURLException

**Review by gregw — CHANGES_REQUESTED** [review]
Sorry.. but one more change

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java (hunk 5 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java]: > @joakime I'm good with the name change, but I just noticed your are declaring this in throw clauses.

Huh?  What throw clauses are you concerned about?
The new class only exists as `throw new CausationMalformedURLException(...` or import lines.
It's not declared as a `void methodFoo() throws CausationMalformedURLException` anywhere I can see.

> How we set the cause is an implementation detail. So no need to change these signatures.. Just throw MalformedURLException

Then we have 6 places to do this stupid block of code ...

``` java
            throw new MalformedURLException(path)
            {
                { 
                    initCause(cause);
                }
            };
```

But with this new class, if we have a future need to be careful of the cause, or the path encoding, then we have 1 place to fix it.

Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/CrossContextServletContext.java]: I dropped the CausationMalformedURLException entirely.
And I'm using the [initCause in the way the javadoc recommends](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Throwable.html#initCause(java.lang.Throwable)).

**Review by gregw — APPROVED** [review]
that's better!
