### PR TITLE
Issue #6138 Fix flakey DuplicateCookieTest

### LINKED ISSUE #6138: Flaky test DuplicateCookieTest.testMultipleIdenticalSessionCookies
**Jetty version**
10.0.x

**Description**
Failed test on jenkins `DuplicateCookieTest.testMultipleIdenticalSessionCookies()`.
see https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-6010/18/tests

```
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:611)
	at org.eclipse.jetty.server.session.DuplicateCookieTest.testMultipleIdenticalSessionCookies(DuplicateCookieTest.java:360)
```

### PR DESCRIPTION
**Pull request by janbartel**
Closes #6138 

DuplicateCookieTest session tests were flakey:  we need to check the request count of the Session _only_ after the request has fully completed, not just after the content of the response has been returned.

### CODE REVIEW

File: tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DuplicateCookieTest.java [hunk 1]
```diff
@@ -70,13 +73,19 @@ public void testMultipleSessionCookiesOnlyOneExists() throws Exception
...
+            scopeListener.setExitSynchronizer(latch);
             Request request = client.newRequest("http://localhost:" + port1 + contextPath + servletMapping + "?action=check");
             request.headers(headers -> headers.add("Cookie", "JSESSIONID=123")); //doesn't exist
             request.headers(headers -> headers.add("Cookie", "JSESSIONID=4422")); //does exist
             ContentResponse response = request.send();
             assertEquals(HttpServletResponse.SC_OK, response.getStatus());
             assertEquals("4422", response.getContentAsString());
 
+            //ensure request has finished processing so session will be completed
+            latch.await(5, TimeUnit.SECONDS);
```
Comment (lachlan-roberts) [inline tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DuplicateCookieTest.java]: I think you should do `assertTrue(latch.await(5, TimeUnit.SECONDS))`, otherwise if it does time out it will return false and not throw. 

Same for the usages below.

**Review by lachlan-roberts — CHANGES_REQUESTED** [review]

File: tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DuplicateCookieTest.java (hunk 1 above)
Comment (janbartel) [reply tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/DuplicateCookieTest.java]: Done.

**Review by lachlan-roberts — APPROVED** [review]
