### PR TITLE
Fixes #11095 - IllegalStateException for completed requests with GzipHandler

### LINKED ISSUE #11095: Jetty 12.0.5 (ee10) throws IllegalStateException for completed requests when Gzip Handler is used
**Jetty version(s)**
12.0.5
I think this issue also exists for Jetty 12.0.4 (I know that we did not get it in 12.0.2 at least).

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)

**OS type/version**
Windows 11 Pro, actually any OS.

**Description**
A seemingly successfully completed requests for most resources in our implementation with Embedded Jetty 12.0.5 logs (perhaps with GZIP involved):
```
[WARNING] 27 Dec 2023  13:08:08.686  <system>  <oeje10s.ServletChannel>  [<WebServer-pool>30,5,<WebServer-pool>]  /iz/css/externalBrowserPages.css: [java.lang.IllegalStateException: s=HANDLING rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0
          	at org.eclipse.jetty.ee10.servlet.ServletChannelState.completed(ServletChannelState.java:1052)
          	at org.eclipse.jetty.ee10.servlet.ServletChannel.lambda$handle$3(ServletChannel.java:553)
          	at org.eclipse.jetty.util.Callback$3.succeeded(Callback.java:162)
          	at org.eclipse.jetty.ee10.servlet.HttpOutput.onWriteComplete(HttpOutput.java:250)
          	at org.eclipse.jetty.ee10.servlet.HttpOutput$WriteCompleteCB.succeeded(HttpOutput.java:1754)
          	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1202)
          	at org.eclipse.jetty.server.handler.ContextResponse$1.succeeded(ContextResponse.java:41)
          	at org.eclipse.jetty.server.handler.gzip.GzipResponseAndCallback.write(GzipResponseAndCallback.java:142)
          	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:735)
          	at org.eclipse.jetty.server.handler.ContextResponse.write(ContextResponse.java:56)
          	at org.eclipse.jetty.ee10.servlet.HttpOutput.channelWrite(HttpOutput.java:204)
          	at org.eclipse.jetty.ee10.servlet.HttpOutput.complete(HttpOutput.java:435)
          	at org.eclipse.jetty.ee10.servlet.ServletContextResponse.completeOutput(ServletContextResponse.java:209)
          	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:553)
          	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
          	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
          	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:761)
          	at com.iizix.jetty.ServletContextHandlers.handle(ServletContextHandlers.java:50)
          	at org.eclipse.jetty.server.Handler$Sequence.handle(Handler.java:781)
          	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:594)
          	at org.eclipse.jetty.server.Server.handle(Server.java:179)
          	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:594)
          	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:424)
          	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
          	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
          	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
          	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
          	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
          	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
          	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
          	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
          	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
          	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
          	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
          	at java.base/java.lang.Thread.run(Thread.java:840)
          ]
```

**How to reproduce?**
In our product "IIZI" with embedded Jetty 12.

The only piece of our code being run is shown below. The `handle(..)` method is more used for internal debugging and passes on the execution into the `org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:761)`.

```java
class ServletContextHandlers extends ServletContextHandler
{
  /**
   * Constructor.
   * 
   * @param indexFiles  The index HTML files array.
   * @param rootDir     The root directory.
   */
  ServletContextHandlers(String [] indexFiles,File rootDir)
    {
    super(SESSIONS);
    
    // Set the base resource.
    setBaseResource(WSHelper.newResource(rootDir));

    // Set the context for all filters and servlets.
    // Required for the internal servlet & filter ServletContext to be sane.
    setContextPath("/");
    
    // The servlet context is what holds the welcome list 
    // (not the ResourceHandler or DefaultServlet)
    setWelcomeFiles(indexFiles);
    
    // Add the filter, and then use the provided FilterHolder to configure it.
    CORSFilter.configureInstance(this);
    }

  @Override
  public boolean handle(Request request,Response response,Callback callback) throws Exception
    {
    if ( WSHelper.DEBUG )
      ILog.INFO(getClass(),"> Handle  request: "+request.getHttpURI());
    
    boolean rc=super.handle(request,response,callback);
    
    if ( WSHelper.DEBUG )
      ILog.INFO(getClass(),"< Handled request = "+rc+": "+request.getHttpURI()+" - status = "+response.getStatus());
    
    return rc;
    }
}
```

The code in `org.eclipse.jetty.ee10.servlet.ServletChannelState.java:1052` seems to be the cause:

```java
    protected void completed(Throwable failure)
    {
        final List<AsyncListener> aListeners;
        final AsyncContextEvent event;
        boolean handle = false;

        try (AutoLock ignored = lock())
        {
            if (LOG.isDebugEnabled())
                LOG.debug("completed {}", toStringLocked());

            if (_requestState != RequestState.COMPLETING)
                throw new IllegalStateException(this.getStatusStringLocked());

            if (_event == null)
            {
                _requestState = RequestState.COMPLETED;
                aListeners = null;
                event = null;
                if (_state == State.WAITING)
                {
                    _state = State.WOKEN;
                    handle = true;
                }
            }
            else
            {
                aListeners = _asyncListeners;
                event = _event;
            }
        }

        // release any aggregate buffer from a closing flush
        _servletChannel.getHttpOutput().completed(failure);

        if (event != null)
        {
            cancelTimeout(event);
            if (aListeners != null)
            {
                runInContext(event, () ->
                {
                    for (AsyncListener listener : aListeners)
                    {
                        try
                        {
                            listener.onComplete(event);
                        }
                        catch (Throwable x)
                        {
                            if (LOG.isDebugEnabled())
                                LOG.warn("{} while invoking onComplete listener {}", x, listener, x);
                            else
                                LOG.warn("{} while invoking onComplete listener {}", x, listener);
                        }
                    }
                });
            }
            event.completed();

            try (AutoLock ignored = lock())
            {
                _requestState = RequestState.COMPLETED;
                if (_state == State.WAITING)
                {
                    _state = State.WOKEN;
                    handle = true;
                }
            }
        }

        if (handle)
            _servletChannel.handle();
    }
```

Are we doing something wrong?

### PR DESCRIPTION
**Pull request by sbordet**
Fixed 2 problems:
* In ServletChannel, in COMPLETE state, there was a check comparing the number of bytes written with that declared by Content-Length. Unfortunately the check was wrong in case of gzip, because it was comparing the application length with the gzipped length, resulting in a late sendErrorOrAbort() that was an abort() because the response was already fully sent. Furthermore, if sendErrorOrAbort() was actually an abort(), there was an unnecessary attempt to complete the output.
* In GzipHandlerResponseAndCallback there were 2 last writes: one when the application calls output.close(), and one when the callback is succeeded. Furthermore, when no content needs to be written, it was still compressed, causing an IOException in ChannelResponse (again when double-checking the bytes written, since Content-Length was 0, but the gzip header and trailer were written).

### CODE REVIEW

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java [hunk 1]
```diff
@@ -209,7 +209,7 @@ public ServletChannelState getServletRequestState()
         return _state;
     }
 
-    public long getBytesWritten()
+    private long getBytesWritten()
```
Comment (lachlan-roberts) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java:212]: Is it okay to change this to private now?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java [hunk 2]
```diff
@@ -220,14 +222,23 @@ protected void commit(boolean last, Callback callback, ByteBuffer content)
...
         }
 
+        // We are varying the response due to accept encoding header.
+        if (_vary != null)
+            fields.ensureField(_vary);
+
+        // If there is nothing to write, don't compress.
+        if (last && BufferUtil.isEmpty(content))
+        {
+            LOG.debug("{} exclude by nothing to write", this);
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java]: Use `if (LOG.isDebugEnabled())`

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java [hunk 3]
```diff
@@ -220,14 +222,23 @@ protected void commit(boolean last, Callback callback, ByteBuffer content)
             return;
         }
 
+        // We are varying the response due to accept encoding header.
+        if (_vary != null)
+            fields.ensureField(_vary);
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java]: What is the reason to move this here?
And why not put it before the other exclusions?

**Review by lachlan-roberts — CHANGES_REQUESTED** [review]
@sbordet there are tests failing, not sure if they are related.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java (hunk 1 above)
Comment (joakime) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java:212]: ServletChannel.getBytesWritten() is used by metrics libraries, it should remain public.

Comment (sbordet) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java:212]: @joakime `ServletChannel.getBytesWritten()` should not be used by anyone, in general the whole `ServletChannel` class should be internal.
We have many other public ways to obtain the number of bytes written, so I think it's fine to make it private as it should have not been public in the first place.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java]: Ok, but will change the whole class, which for some reason never used this pattern.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java]: From [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#field.vary):

> The "Vary" header field in a response describes what parts of a request message, aside from the method and target URI, might have influenced the origin server's process for selecting the content of this response.

So in theory we should always add it when we have the GzipHandler installed, as any response might change since it may be compressed.

However, this will break a number of tests.

Not sure if we interpreted the semantic wrong before (and wrote wrong tests) but I tried to make the minimum amount of changes in this PR.

However, I do think we should square this out once and for all.

@lachlan-roberts your thoughts?

Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java]: @lachlan-roberts not sure if the interpretation could be:

If you ask the server for an empty response, it will always be empty and not compressed so it will be independent from the `Accept-Encoding` header, so it should not have the `Vary` header.

However, the RFC says "aside from the method and target URI".
With these 2 excluded, it basically becomes an announcement of the capabilities of the server, so it should always be there.

I'm not sure what exactly the purpose is, if the method and URI are not considered.

Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java]: > If you ask the server for an empty response, it will always be empty and not compressed so it will be independent from the Accept-Encoding header, so it should not have the Vary header.

I can see how that would make sense. But the response might not always be empty so I think its better to always advertise the servers capability to vary the response on the `Accept-Encoding` header. Should probably just set it in `GzipHandler` instead of `GzipResponseAndCallback`.

Also what about the case where we skip compression because the `CONTENT_ENCODING` has already been set? right now we expect someone else to set the vary header.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java [hunk 4]
```diff
@@ -544,14 +544,16 @@ public void handle()
                         // RFC 7230, section 3.3.  We do this here so that a servlet error page can be sent.
                         if (!_servletContextRequest.isHead() && getServletContextResponse().getStatus() != HttpStatus.NOT_MODIFIED_304)
                         {
-                            long written = getBytesWritten();
-                            if (getServletContextResponse().isContentIncomplete(written) && sendErrorOrAbort("Insufficient content written %d < %d".formatted(written, getServletContextResponse().getContentLength())))
+                            long written = getHttpOutput().getWritten();
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java]: We need a comment here saying why `getByteWritten()` is not used. i.e. because we want to look at the bytes written to the `HttpOutputStream` and not the bytes written to the underlying core response.

It would also be good to comment in `ServletContextResponse` that its `_contentLength` field is the length set by the application, but not necessarily the one set on the response as it may be removed/adjsuted.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java [hunk 5]
```diff
@@ -167,27 +164,27 @@ protected void commit(boolean last, Callback callback, ByteBuffer content)
         if (LOG.isDebugEnabled())
             LOG.debug("commit(last={}, callback={}, content={})", last, callback, BufferUtil.toDetailString(content));
 
-        // Are we excluding because of status?
         Request request = getRequest();
         Response response = this;
+        HttpFields.Mutable fields = response.getHeaders();
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java:169]: If we wanted to be a tiny bit more efficient here, we could iterate over all the fields once and extract `ETAG`, `CONTENT_TYPE`, `CONTENT_ENCODING`, and `CONTENT_LENGTH` in a single loop.

But perhaps the number of response fields is not large enough (and iterators cheap enough) that this is not worth it.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java [hunk 6]
```diff
@@ -95,10 +89,12 @@ public void succeeded()
...
-            // We need to write nothing here to intercept the committing of the response
-            // and possibly change headers in case write is never called.
-            write(true, null, Callback.NOOP);
-            _callback.succeeded();
+            // We need to write nothing here to intercept the committing of the
+            // response and possibly change headers in case write is never called.
+            if (_last)
+                _callback.succeeded();
+            else
+                write(true, null, _callback);
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java:97]: nice!

**Review by gregw — COMMENTED** [review]
Just some comments for now until I see a clean build

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipResponseAndCallback.java:169]: I wrote a JMH benchmark, and iteration is so darn cheap that the extra cost of using the iterator takes a lot to amortize.

It takes a `ImmutableHttpFields` instance containing 20 fields to make looking up the last 4 fields of the internal array cheaper with the iterator.

Looking up less than 4 fields, or having to iterate less than 20 entries per lookup makes the solution using `get` always faster.

**Review by gregw — DISMISSED** [review]

**Review by joakime — CHANGES_REQUESTED** [review]
The test `testStaticContent(String)[3] ee10 – org.eclipse.jetty.tests.distribution.DemoModulesTests` has been consistently broken for the last 8 builds.

That doesn't smell like a flake.

**Comment by sbordet** [comment]
@gregw the test failure was due to welcome files bypassing the Servlet's OutputStream (using core classes directly), so that the check on the content-length was failing (as 0 bytes were written through the HttpOutput).
Please re-review.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java [hunk 7]
```diff
@@ -278,6 +281,18 @@ public long getContentLength()
...
+    public void write(boolean last, ByteBuffer content, Callback callback)
+    {
+        _written += BufferUtil.length(content);
+        super.write(last, content, callback);
+    }
+
+    public long getContentBytesWritten()
+    {
+        return _written;
+    }
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java]: > @gregw the test failure was due to welcome files bypassing the Servlet's OutputStream (using core classes directly), so that the check on the content-length was failing (as 0 bytes were written through the HttpOutput). Please re-review.

I'm not exactly how this method address this issue? The `getContentBytesWritten()` here looks like it will still be bypassed?  But fixed the tests... so I'm good... but an explanation would help.

Also, this method has the same name as `Response.getContentBytesWritten(Response)`, but returns a different value (i.e. pre compressed rather than post compressed).      Can you put some javadoc on both methods.   If you can think of a better name for this one, then change the name... maybe just `getWritten()` ?  Maybe make it package protected?

**Review by gregw — DISMISSED** [review]
Just some niggles at this stage, so conditional approval.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java (hunk 7 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java]: @gregw I made the method package local, added javadocs, but also filed #11325 because the issue needs to be investigated further, but it is orthogonal to GzipHandler.

Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java]: The bypassing in question is done by the `ResourceService` used in the `DefaultServlet` when a static file is served and `DefaultServlet` notices there is no wrapping. In that case, `DefaultServlet` passes the `ServletContextResponse` directly to `ResourceService` instead of wrapping the `HttpServletRequest` as a core `Request` and passing that to `ResourceService`.

The problem this creates here is that `HttpOutput` is unaware of what `ResourceService` writes, and `getBytesWritten` returns how many bytes were written to the socket after `GZIPHandler` compressed them.

So `ServletChannel.handle()` had no reliable way to know how many bytes were written to check if `Content-Length` is correct, hence that extra bytes counter in `ServletContextResponse` was added so that `ServletChannel.handle()` can make that `Content-Length` check.

**Review by gregw — APPROVED** [review]

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java (hunk 7 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextResponse.java]: I'm thinking that the Servlet stuff only needs to track bytes written enough to do the auto commit/flush/close required by the spec.   Perhaps we are doing too much due to tests left over from Jetty-11 when this was the main API for response.    Let's consider this in #11325 for the next release.

**Comment by minduch** [comment]
@sbordet Thank you very much!
When is (this fix available in) 12.0.6 [approximately] released?
Best regards, Christopher Mindus

**Comment by sbordet** [comment]
@minduch early next week if testing goes fine.
