### PR TITLE
Issue #1337 Use either absolute or relative multipart file location

### LINKED ISSUE #1337: MultiPart Part.write(String fileName) - Write method used unexpected path
Hi,
In MultiPartInputStreamParser class is method `public void write(String fileName) throws IOException`  where original JavaDoc says:

> param fileName the name of the file to which the stream will be written. The file is created relative to the location as specified in the MultipartConfig

From Spring Framework is it called by class StandardMultipartHttpServletRequest in transferTo method which looks like:

```
@Override
public void transferTo(File dest) throws IOException, IllegalStateException {
	this.part.write(dest.getPath());
}
```
And in my case, there is absolutePath. 
And in Jetty implementation of write method is:
```
_file = new File (_tmpDir, fileName);
```

Result is that there is duplicated path because _tmpDir contains path already path to tmp files.
There should be checking if variable fileName is absolute, shouldn't be?

### PR DESCRIPTION
**Pull request by janbartel**
Closes #1337 

Now https://github.com/eclipse-ee4j/servlet-api/pull/276 has been merged to the spec, the meaning of Part.write(String) is a bit clearer. This PR implements using either an absolute or relative location (relative to the MultiPartConfigElement.location).

### CODE REVIEW

**Review by joakime — CHANGES_REQUESTED** [review]
This doesn't address what "relative path" means.

The PR at https://github.com/eclipse-ee4j/servlet-api/pull/276 is incomplete and doesn't address this properly.

What about Windows?
What about Virtual File Systems?
What about `java.nio.file.FileSystem` that isn't based on a single root?

File: jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java [hunk 1]
```diff
@@ -535,20 +541,20 @@ protected void parse()
...
             {
-                File f = new File(_config.getLocation());
-                if (f.isAbsolute())
-                    _tmpDir = f;
+                Path location = FileSystems.getDefault().getPath(_config.getLocation());
+                if (location.isAbsolute())
+                    _tmpDir = location;
                 else
-                    _tmpDir = new File(_contextTmpDir, _config.getLocation());
+                    _tmpDir = _contextTmpDir.toPath().resolve(location);
```
Comment (joakime) [inline jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java]: This is the only relevant part of this change.  

The rest is just confusing.

Comment (janbartel) [reply jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java]: Not sure where's the confusion. Around lines 538 in the parse() method we work out where the tmp directory is so we can write to it if we need to (eg the number of bytes received exceed the configured limit for bytes retained in memory). The location of the tmp directory can be given by the MultiPartConfigElement.location, or, if that has not been configured, I default to the context tmp dir. This code has always been there, I just changed to calculating it as a Path instead of a File.

Comment (janbartel) [reply jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java]: To be clear, the main change is at lines 196-199 where we treat the String argument to Part.write() as either absolute or relative: previously we always treated it as relative.

File: jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java [hunk 2]
```diff
@@ -185,12 +186,17 @@ protected void write(byte[] bytes, int offset, int length) throws IOException
         @Override
         public void write(String fileName) throws IOException
         {
+            Path p = Path.of(fileName);
+
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java]: You have the same isAbsolute check in both branches below so perhaps do that here.
```suggestion
            Path p = Path.of(fileName);
            p = p.isAbsolute() ? p : _tmpDir.resolve(p);
```

File: jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java [hunk 3]
```diff
@@ -185,12 +186,17 @@ protected void write(byte[] bytes, int offset, int length) throws IOException
...
+            Path p = Path.of(fileName);
+            
             if (_file == null)
             {
                 _temporary = false;
 
                 // part data is only in the ByteArrayOutputStream and never been written to disk
-                _file = new File(_tmpDir, fileName);
+                if (!p.isAbsolute())
+                    p = _tmpDir.resolve(p);
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java]: move this above

File: jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java [hunk 4]
```diff
@@ -208,7 +214,7 @@ public void write(String fileName) throws IOException
                 _temporary = false;
 
                 Path src = _file.toPath();
-                Path target = src.resolveSibling(fileName);
+                Path target = (p.isAbsolute() ? p : _tmpDir.resolve(p));
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java]: move this absolute check to above

File: jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java (hunk 2 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java]: Note that while I know resolve also handles absolute addresses, I do kind of like seeing it explicit in this code, so you can understand it without the need to have deep knowledge of how resolve behaves.   Maybe have a comment to that effect?

**Review by gregw — APPROVED** [review]
Considering the debate on this one, I thought I'd have a look.    Other than a niggle of repeating the isAbsolute check, it LGTM.

File: jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java [hunk 5]
```diff
@@ -185,12 +186,16 @@ protected void write(byte[] bytes, int offset, int length) throws IOException
         @Override
         public void write(String fileName) throws IOException
         {
+            Path p = Path.of(fileName);
```
Comment (joakime) [inline jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java:189]: Note. `Path.of(String...)` is new for Java 11.
The original technique would be `Paths.get(String...)`
(Just in case you are using these techniques back in Jetty 9.4..x)

File: jetty-server/src/test/java/org/eclipse/jetty/server/MultiPartFormInputStreamTest.java [hunk 6]
```diff
@@ -474,6 +475,77 @@ public void testPartFileNotDeleted() throws Exception
...
+    
+    @Test
+    public void testPartFileAbsolute() throws Exception
+    {
+        MultipartConfigElement config = new MultipartConfigElement(_dirname, 1024, 3072, 50);
+        MultiPartFormInputStream mpis = new MultiPartFormInputStream(new ByteArrayInputStream(createMultipartRequestString("tpfa").getBytes()),
+            _contentType,
+            config,
+            _tmpDir);
+        mpis.setDeleteOnExit(true);
```
Comment (joakime) [inline jetty-server/src/test/java/org/eclipse/jetty/server/MultiPartFormInputStreamTest.java:487]: Should probably add a test in here to know if the file got deleted (or not).

The temp files (note, if the Part was specifically .write(String) then it's no longer a temp file) for a MultiPartFormInputStream should only exist for as long as that MultiPartFormInputStream is live. (ie: if the MPFIS is closed, then the temp files should be deleted), as there's no sane way via the API to access the temporary contents anymore.

Comment (joakime) [reply jetty-server/src/test/java/org/eclipse/jetty/server/MultiPartFormInputStreamTest.java:487]: This should be part of the followup PR on cleanup of behavior.

Comment (janbartel) [reply jetty-server/src/test/java/org/eclipse/jetty/server/MultiPartFormInputStreamTest.java:487]: Parts that have been written only to temporary files are all deleted when a Request is completed. See https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L1423 and https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/MultiPartFormInputStream.java#L333.

Comment (joakime) [reply jetty-server/src/test/java/org/eclipse/jetty/server/MultiPartFormInputStreamTest.java:487]: Yeah, that seems to be more sane.  Cleanup at the end of the Request.

**Review by joakime — APPROVED** [review]
This PR satisfies the scope of issue #1337 
+1 from me.

I'll work Issue #5132 (to cleanup MultipartFormInputStream) after this gets merged.
