### PR TITLE
Fix stack overflow in `HttpStreamOverHttp3.consumeAvailable()`

### LINKED ISSUE #10543: Review HttpStream.consumeAvailable() implementations
**Jetty version(s)**
12

**Description**
`HttpStream.consumeAvailable()` implementation typically delegate to the `static HttpStream.consumeAvailable(HttpStream, HttpConfiguration)`.

However, some of them may not store a possible failure to consume available into the `chunk` field that every implementation has, nor releasing the possibly existing chunk.

This may lead to stack overflow, for example:
https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-10529/3/pipeline

### PR DESCRIPTION
**Pull request by lorban**
Only H3 seems to suffer from the stack overflow problem.

What I do not like about this "fix":

 - there is no easy way to test it
 - it exposes that all protocols leak buffers on the server when a timeout occurs

Fixes #10543

### CODE REVIEW

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 1]
```diff
@@ -1193,6 +1197,82 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+                new Runnable()
+                {
+                    @Override
+                    public void run()
+                    {
+                        while (true)
+                        {
+                            try
+                            {
+                                Thread.sleep(100);
```
Comment (gregw) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: what is this for?

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 2]
```diff
@@ -1193,6 +1197,82 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
         assertTrue(clientLatch.await(timeoutInSeconds, TimeUnit.SECONDS));
     }
 
+    @ParameterizedTest
+    @MethodSource("transports")
+    @Tag("DisableLeakTracking:server")
+    public void testUploadWithRetainedData(Transport transport) throws Exception
```
Comment (gregw) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: This is not the right name for this test

**Review by gregw — CHANGES_REQUESTED** [review]
I'm wondering if we should start using `SoftReference` in our `RetainableByteBuffer` to link to the `ByteBuffer`.   We would also have a hard reference, which we would set when the buffer is in the pool, and null when we allocate the buffer.     If we ever get a buffer in the collection queue, we then know that somebody took a `RetainableByteBuffer` and leaked it.        However, I'm not exactly sure how we would recover from that, as I'm not sure how we can use the collected `ByteBuffer` to find the `RetainableByteBuffer` reference?

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: You're totally right, let me rename it.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: This test is about triggering a timeout on the client during an upload. This `sleep()` makes sure the server is slow enough so that the timeout triggers but fast enough so that it starts consuming some of the uploaded chunks.

Renaming the test will make it more obvious what the test is about, and I'm adding a couple of comments to be more explicit.

**Comment by lorban** [comment]
@gregw Looking at the `ConcurrentPool` implementation, it may be possible to keep both a hard and a weak reference to the pooled object and null out the hard ref when the pooled object is acquired, then assign it back to the hard reference when it is released. We could then "garbage collect" the pool with a timer by removing all entries that have a null `WeakReference`.

That looks feasible and would make our pools totally resistant to leaks like they used to be. We should investigate this idea. I filed #10569 so that we can come back to that subject later on.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 3]
```diff
@@ -1193,6 +1197,85 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+            case H2, H2C -> 100;
+            default -> 1000;
+        };
+        new CompletableResponseListener(client.newRequest(newURI(transport)).body(content).timeout(timeoutMs, TimeUnit.MILLISECONDS))
+            .send()
+            .whenComplete((r, t) ->
+            {
+                errorHolder.set(t);
+                latch.countDown();
+            });
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Can you use `handle((r, t) -> t).get(5, SECONDS)` instead?

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 4]
```diff
@@ -1193,6 +1197,85 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+    @Tag("DisableLeakTracking:server")
+    public void testHttpStreamConsumeAvailableUponClientTimeout(Transport transport) throws Exception
+    {
+        start(transport, new Handler.Abstract()
+        {
+            @Override
+            public boolean handle(Request request, org.eclipse.jetty.server.Response response, Callback callback)
+            {
+                // Consume the uploaded data very slowly to make the client timeout.
+                new Runnable()
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Can you use `CompletableTask` instead?

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 5]
```diff
@@ -1193,6 +1197,85 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+        ByteBufferRequestContent content = new ByteBufferRequestContent(ByteBuffer.wrap(data));
+
+        CountDownLatch latch = new CountDownLatch(1);
+        AtomicReference<Throwable> errorHolder = new AtomicReference<>();
+        long timeoutMs = switch (transport)
+        {
+            case H2, H2C -> 100;
+            default -> 1000;
+        };
+        new CompletableResponseListener(client.newRequest(newURI(transport)).body(content).timeout(timeoutMs, TimeUnit.MILLISECONDS))
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Put chained calls in new lines.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 6]
```diff
@@ -1193,6 +1197,85 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+        // that the client will timeout during the transfer.
+        byte[] data = new byte[16 * 1024 * 1024];
+        new Random().nextBytes(data);
+        ByteBufferRequestContent content = new ByteBufferRequestContent(ByteBuffer.wrap(data));
+
+        CountDownLatch latch = new CountDownLatch(1);
+        AtomicReference<Throwable> errorHolder = new AtomicReference<>();
+        long timeoutMs = switch (transport)
+        {
+            case H2, H2C -> 100;
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: 100 ms is really short, you may timeout in the queue and never send the request.
Or you may never start send the body, not sure if it's important for the test.

How about using `request.onRequestCommit()` so you are sure that the request is sent, and in the commit listener you can call `request.abort()`?

File: jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java [hunk 7]
```diff
@@ -528,6 +528,12 @@ public void onIdleTimeout(TimeoutException failure, BiConsumer<Runnable, Boolean
 
     public Runnable onFailure(Throwable failure)
     {
+        try (AutoLock ignored = lock.lock())
+        {
+            if (chunk != null)
+                chunk.release();
+            chunk = Content.Chunk.from(failure, true);
+        }
```
Comment (sbordet) [inline jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java:543]: I'd like to see, if possible, the remembering of the failed chunk in the same method across the 4 `HttpStream` implementations.
H1 does it in `consumeAvailable`, H2 does not do it, H3 now does it in `onFailure()`.
Can we consolitate that remembering into a similar patter for all 4 (if possible)?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Done.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 6 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Reworked all that timing logic.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Done.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Done.

**Comment by lorban** [comment]
@sbordet I streamlined the H1 `consumeAvailable` impl; actually the fix for the memory leak should have been in `HttpConnection.fillRequestBuffer()`.

But the code I added to H3 should be considered a workaround. There is something more fundamental that is wrong with the way H3 handles exceptions in the lowest layers. I'm going to open an issue about it.

**Review by gregw — APPROVED** [review]
I'm good with this for this release cycle, so long as we get onto #10569 asap next cycle.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 8]
```diff
@@ -587,9 +587,14 @@ private int fillRequestBuffer()
                     filled = getEndPoint().fill(requestBuffer);
 
                 if (filled > 0)
+                {
                     bytesIn.add(filled);
+                }
                 else if (filled < 0)
+                {
+                    releaseRequestBuffer();
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Please add a release in the catch block below too.

Also, release the buffer when we `filled == 0`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 9]
```diff
@@ -1145,18 +1150,7 @@ public Throwable consumeAvailable()
...
-                // If HttpStream.consumeAvailable() returns an error, there may be unconsumed content left,
-                // so we must make sure the buffer is released and that the next chunk indicates the end of the stream.
-                if (_retainableByteBuffer != null)
-                {
-                    _retainableByteBuffer.release();
-                    _retainableByteBuffer = null;
-                }
-                if (_chunk == null)
-                    _chunk = Content.Chunk.from(result, true);
-            }
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java:1159]: I would restore this code for now, I don't think it can be safely removed.

As said in a previous comment, I'd like to see consistent handling of consumeAvailable() across protocols.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 10]
```diff
@@ -1193,6 +1197,92 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+                                return;
+                            }
+                            chunk.release();
+                            if (chunk.isLast())
+                            {
+                                complete(null);
+                                return;
+                            }
+
+                            org.eclipse.jetty.client.Request r = clientRequestRef.getAndSet(null);
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Use `var`.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 11]
```diff
@@ -1193,6 +1197,92 @@ public boolean handle(Request request, org.eclipse.jetty.server.Response respons
...
+                });
+                return true;
+            }
+        });
+
+        byte[] data = new byte[16 * 1024 * 1024];
+        new Random().nextBytes(data);
+        ByteBufferRequestContent content = new ByteBufferRequestContent(ByteBuffer.wrap(data));
+
+        org.eclipse.jetty.client.Request request = client.newRequest(newURI(transport))
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Use `var`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 11 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Done.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 8 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Done.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 9 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java:1159]: Yes, I lost track of your original remark and got lost. This is now done.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 10 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Done.

File: jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java (hunk 7 above)
Comment (lorban) [reply jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java:543]: Done.

**Review by sbordet — APPROVED** [review]
