### PR TITLE
Fixes #2530 - Client waits forever for cancelled uploads.

### LINKED ISSUE #2530: Client waits forever for cancelled large uploads
The test below simply POSTs a payload of increasing size to a Jetty server. With Jetty 9.4.9+ the client waits forever once it reaches 64KB payload size. With Jetty 9.4.8 the client receives an EOF exception @ 32KB payload size.

The client is a Jetty HttpClient, though I've tried using HttpURLConnection also and the behaviour appears the same, so seems to be server related.

[JettyIssueVersion_9_4_9.zip](https://github.com/eclipse/jetty.project/files/1999743/JettyIssueVersion_9_4_9.zip)

### PR DESCRIPTION
**Pull request by sbordet**
#2530: after discussion on openjdk/nio-dev, we now wakeup the selector
after closing a socket, so that the SelectionKey can be removed
from the Selector and the TCP stack notified that the socket
has been really closed, so that it can send RST to clients.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java [hunk 1]
```diff
@@ -236,6 +237,7 @@ private void createEndPoint(SelectableChannel channel, SelectionKey selectionKey
 
     public void destroyEndPoint(final EndPoint endPoint)
     {
+        submit(WAKEUP);
```
Comment (joakime) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: Do we want to document why we do this here? (for our future selves?)

**Comment by joakime** [comment]
I think the original reasoning for the pill is that this will aid in debugging.
Appearing as `SelectorWakeup` in debugging, collections, jmx, stacktraces, and dumps.

**Comment by sbordet** [comment]
@joakime true, but I think @gregw has a point in saving `offer()+poll()` which would also save allocation - although that would have a big effect only for HTTP/1.0.

We did not have problems so far at debugging closes (on the selector), so perhaps it's not that important that the wakeup is a `SelectorUpdate` - it can be as @gregw suggests.

**Comment by sbordet** [comment]
@gregw @joakime I have updated following your suggestions.

**Comment by sbordet** [comment]
@gregw correct, waking up the selector and running `DestroyEndPoint` can be done concurrently as `DestroyEndPoint` is only to notify Jetty components.
