### PR TITLE
Issue #10333 - fix flaky test testLogRequestTimeCustomFormats

### LINKED ISSUE #10333: Flaky Test `org.eclipse.jetty.server.CustomRequestLogTest.testLogRequestTimeCustomFormats`
**Jetty version(s)**
12.0.0

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**

Flaky test ...

```
Error
Expected: is "[Sun Aug 13 15:28:14 -05:00 2023]"
     but: was "[Sun Aug 13 15:28:13 -05:00 2023]"

Stacktrace
java.lang.AssertionError: 
Expected: is "[Sun Aug 13 15:28:14 -05:00 2023]"
     but: was "[Sun Aug 13 15:28:13 -05:00 2023]"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.server@12.0.1-SNAPSHOT/org.eclipse.jetty.server.CustomRequestLogTest.testLogRequestTimeCustomFormats(CustomRequestLogTest.java:566)
```

Looks like it's off by 1 second.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #10333

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 1]
```diff
@@ -223,7 +224,13 @@ static String getPathInContext(Request request)
...
     static long getTimeStamp(Request request)
     {
-        return System.currentTimeMillis() - NanoTime.millisSince(request.getHeadersNanoTime());
+        Long timeStampAttribute = (Long)request.getAttribute(TIMESTAMP_ATTRIBUTE);
+        if (timeStampAttribute != null)
+            return timeStampAttribute;
+
+        long timeStamp = System.currentTimeMillis() - NanoTime.millisSince(request.getHeadersNanoTime());
+        request.setAttribute(TIMESTAMP_ATTRIBUTE, timeStamp);
+        return timeStamp;
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: I don't think we want an attribute for this.  Just create a field.

Actually it is not even worth the cost of a field to deflake a test.  Just make the test not check for an exact timestamp.  Perhaps parse the time and check it is within 1s

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: > Perhaps parse the time and check it is within 1s

It could be more than one second out, its just more unlikely. And then it could just happen to be on the switch of the minute/hour/day so the less specific you make the test the less flaky it is, but there is still a chance it could fail.


Right now the `Request.getTimeStamp` return value can be completely wrong. So you can't really rely on the value. If we are to ignore this in the test we should probably add something to the javadoc to explain this.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: Why can the value be completely wrong?    It determines a period between when the request was created to now in nano seconds, converts to milliseconds and then applies to the wall clock time.  It is only likely to be called 0 or 1 times, so variations do not matter.

It should be trivial to parse the string received by the unit test back into a long, and then you can check that it is within a few seconds of now and you are good!

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: Note that it is likely to only ever be called by logging, which is the last thing ever done to the request.  So any effort to remember the value is wasted effort that will be done to ZILLIONS of requests forever for no good other than to make it easier for this unit test to pass!

Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: It is also used by various auditing and metrics libraries built on Jetty.

So literally every request going through Dropwizard (for example) will utilize this request timestamp for it's own internal metrics tracking (which occurs at multiple steps through the single request processing).

Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: @gregw `Request.getTimeStamp` is implemented as such:
```java
System.currentTimeMillis() - millisElapsed(request.getHeadersNanoTime(), NanoTime.now())
```
so the returned timestamp can vary by 1ms because of the rounding done in currentTimeMillis. No big deal.

But if there is a long GC pause between the `System.currentTimeMillis()` call and the `NanoTime.now()` one, the returned timestamp will be off by the GC pause duration. This _may_ be a bigger deal as a system with frequent long GC pauses can log imprecise timestamps.

I do agree that we need to weigh the business value of precise timestamps vs their cost, and I'm not sure how serious or not this problem is.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: There is little we can do if we want both a nano time for accurate latency and a currentTimeMillis for an accurate wall clock.  No matter what, there could be a GC pause between the two samples so one will not correlate well with the other.
So even if at the time the very first byte arrives we grab both timestamps, then the second one could be delayed by a GC.

However, perhaps that is the least evil approach.   If we think this method may frequently be called, sometimes more than once, then we should grab both timestamps at the same place and have getters for both on the request.  At least that would give a mostly monotonically incrementing wall clock timestamp... but clock adjustments will still cause it to have some jiggle.   It is not a perfect measure no matter how you look at it.

So perhaps an extra field might be justified.... but an attribute is definitely not.

**Comment by gregw** [comment]
@lachlan-roberts I rewrote the test:
```java


    @ParameterizedTest
    @ValueSource(strings = {"%{EEE MMM dd HH:mm:ss zzz yyyy}t", "%{EEE MMM dd HH:mm:ss zzz yyyy|EST}t", "%{EEE MMM dd HH:mm:ss zzz yyyy|EST|ja}t"})
    public void testLogRequestTimeCustomFormats(String format) throws Exception
    {
        AtomicLong requestTimeRef = new AtomicLong();
        start(format, new SimpleHandler()
        {
            @Override
            public boolean handle(Request request, Response response, Callback callback)
            {
                requestTimeRef.set(System.currentTimeMillis());
                callback.succeeded();
                return true;
            }
        });

        HttpTester.Response response = getResponse("GET / HTTP/1.0\n\n");
        assertEquals(HttpStatus.OK_200, response.getStatus());
        String log = _logs.poll(5, TimeUnit.SECONDS);
        assertNotNull(log);

        String[] formats = format.substring(format.indexOf('{') + 1, format.indexOf('}')).split("\\|");

        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern(formats[0])
            .withLocale(formats.length > 2 ? Locale.forLanguageTag(formats[2]) : Locale.getDefault())
            .withZone(formats.length > 1 ? TimeZone.getTimeZone(formats[1]).toZoneId() : TimeZone.getDefault().toZoneId());

        Instant parsed = dateTimeFormatter.parse(log.substring(log.indexOf('[') + 1, log.indexOf(']')), Instant::from);
        Instant request = Instant.ofEpochMilli(requestTimeRef.get());
        assertThat(Math.abs(Duration.between(parsed, request).toSeconds()), Matchers.lessThanOrEqualTo(2L));
    }
```

**Comment by lachlan-roberts** [comment]
@gregw I reverted the changes to `Request`. So the `Request.getTimeStamp(request)` method can still return inconsistent values if called multiple times. 

But this PR should stop the test from being flaky.

**Review by gregw — APPROVED** [review]

**Review by lorban — APPROVED** [review]
