### PR TITLE
Issue #6026 - Cleaning up warning for paths with uncovered HTTP methods

### LINKED ISSUE #6026: the jvm DEBUG flag is not working org.eclipse.jetty.LEVEL=DEBUG
**Jetty version - 9.4.36**

**Java version - ./jdk/bin/java -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 8.0.6.20 - pxa6480sr6fp20-20201120_02(SR6 FP20))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201102_458768 (JIT enabled, AOT enabled)
OpenJ9   - 5b31a42
OMR      - 6ad3a34
IBM      - b7e48f4)
JCL - 20201119_01 based on Oracle jdk8u271-b09**

**OS type/version - Linux XXXX 3.10.0-1062.4.1.el7.x86_64 #1 SMP Wed Sep 25 09:42:57 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux**

** Red Hat Enterprise Linux Server release 7.7 (Maipo) **

**Description - In order to enable jetty http server logs, we used to do following steps**

1) Enable jetty debug log in GUI
2) Add the below code to PSHttpAdapterImpl in asset clump

import org.eclipse.jetty.util.log.Log;
import org.eclipse.jetty.util.log.StdErrLog;

Logger jettyLog = LogService.getLogger("jettylogger");
jettyLog.logDebug("Enabling Jetty Debug Logs:"+jettyLog.isDebug());
if(jettyLog.isDebug()) {
StdErrLog errLog = new StdErrLog();
errLog.setDebugEnabled(true);
Log.setLog(errLog);
}

3. Build asset clump
4. Add -Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog -Dorg.eclipse.jetty.LEVEL=DEBUG 
to SI_INSTALL/noapp/bin/startNoApp.sh
5. Restart application

But, though it used to work in 9.4.26, its not working in 9.4.36. And, we are seeing below errors, in jetty logs, when set as DEBUG during server startup,

[2021-03-03 18:38:10.655] ALL 000000000000 GLOBAL_SCOPE 2021-03-03 18:38:10.655:DBUG:oejs.SecurityHandler:Thread-11:
java.lang.Throwable
at org.eclipse.jetty.security.ConstraintSecurityHandler.checkPathsWithUncoveredHttpMethods(ConstraintSecurityHandler.java:762) at org.eclipse.jetty.security.ConstraintSecurityHandler.doStart(ConstraintSecurityHandler.java:415)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:120)
at org.eclipse.jetty.server.session.SessionHandler.doStart(SessionHandler.java:505)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:120)
at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:970)
at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:375)
at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457)
at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422)
at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911)
at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.server.Server.start(Server.java:423)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at org.eclipse.jetty.server.Server.doStart(Server.java:387)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
at com.sterlingcommerce.woodstock.noapp*.WebServerStartThread.run(WebServerStartThread.java:64)*
at java.lang.Thread.run(Thread.java:822)

### PR DESCRIPTION
**Pull request by joakime**
Closes #6026 

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

File: jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java [hunk 1]
```diff
@@ -741,14 +741,9 @@ public boolean checkPathsWithUncoveredHttpMethods()
...
         {
-            ContextHandler.Context currentContext = ContextHandler.getCurrentContext();
-
-            for (String p : paths)
-            {
-                LOG.warn("{} has uncovered http methods for path: {}", currentContext, p);
-            }
-            if (LOG.isDebugEnabled())
-                LOG.debug("{} has uncovered http methods", currentContext, new Throwable());
+            LOG.warn("{} has paths with uncovered http methods: [{}]",
```
Comment (janbartel) [inline jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: The log warn message is the wrong way around, it is the _uncovered paths_ not _methods_, so it should be:

```suggestion
            LOG.warn("{} has uncovered http methods for paths: [{}]",
```

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java (hunk 1 above)
Comment (joakime) [reply jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: Yet the method name is `checkPathsWithUncoveredHttpMethods` ??

Comment (janbartel) [reply jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: Correct, we are reporting the uncovered _paths_ not the uncovered _methods_.

Comment (joakime) [reply jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: Confusing.

* "has paths with uncovered http methods" - identifies paths, that has uncovered http methods
* "has uncovered http methods for paths" - identifies methods, that are not covered by the paths

Perhaps there's a 3rd choice that's less confusing.  What does "uncovered http method" mean?

Comment (sbordet) [reply jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: Agree with @joakime here, the method name suggests the other way around.
Also, do we really want to use WARN? I don't think nothing happens if we hit this case, and we don't want to clog log files if repeated requests for this case happens?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java (hunk 1 above)
Comment (janbartel) [reply jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: The name of the method is "checkPathsWithUncoveredMethods" - ie we are checking the _paths_ for which there are uncovered methods.  The logging is reporting the _paths_, not the methods - it would be incorrect to imply that we are reporting methods!

Furthermore, this warning is required by the servlet specification: your choice if you want to make it INFO instead of WARN, but the spec _requires_ that we produce this warning at deployment time.

Comment (joakime) [reply jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: Is this the section of the spec this covers?

https://github.com/eclipse-ee4j/servlet-api/blob/5.0.0-RELEASE/spec/src/main/asciidoc/servlet-spec-body.adoc#handling-uncovered-http-methods

**Comment by gregw** [comment]
A bit of background.... the servlet spec is beyond brain dead here!

If an app has a security constraints:
-  `/foo/*` with no methods specified
- `/foo/bar/*` for POST methods

Then a request to `/foo/bar/info` with any method other than `POST` is not constrained at all!!!!  Hence the method is uncovered.
This is a real security issue and deserves a WARNING (at the very least)! Moreover, the methods uncovered are infinite and cannot be enumerated.  Only the path specifications with uncovered methods can be enumerated.

So @janbartel is correct: there should be a warning that enumerates the paths.  I kind of think we should also by default refuse to deploy.... but that's also contrary to the spec and going beyond the scope of this PR to just remove a noisy stack trace... which I agree gave no needed information.

File: jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java (hunk 1 above)
Comment (janbartel) [reply jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: Yes, this is the section. Please see comment by @gregw - we can enumerate the paths that are uncovered but not the methods.

File: jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java [hunk 2]
```diff
@@ -741,14 +741,9 @@ public boolean checkPathsWithUncoveredHttpMethods()
...
+                ContextHandler.getCurrentContext(),
+                String.join(", ", paths));
```
Comment (sbordet) [inline jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: There is no need for `String.join()` as `Set.toString()` already formats like you want (external brackets and commas to separate items).

**Review by sbordet — CHANGES_REQUESTED** [review]
The `boolean` return value from `checkPathsWithUncoveredHttpMethods()` is never used, can it be changed without breaking?

**Comment by joakime** [comment]
Leaving it at WARN level.
Changed the message again, to be more like the original, but with better grammar.
The String.join was removed, in favor of Set.toString() instead.

File: jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java (hunk 2 above)
Comment (joakime) [reply jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: Done.

Comment (joakime) [reply jetty-security/src/main/java/org/eclipse/jetty/security/ConstraintSecurityHandler.java]: if we backport this to 9.4.x then removing the return value is a bad idea.
But for 10+ i'm fine with removing the return value.

**Review by sbordet — APPROVED** [review]

**Review by janbartel — APPROVED** [review]
