### PR TITLE
Fix flaky HttpOutputTest.testEmptyBufferKnown

### LINKED ISSUE #6605: Flaky test: HttpOutputTest.testEmptyBufferKnown
**Jetty version(s)**
9.4.x

**Description**
`HttpOutputTest.testEmptyBufferKnown` fails about 1 of every 20 times on the following assertion:

```java
assertThat(committed.get(), is(false));
```

### PR DESCRIPTION
**Pull request by lorban**
Fixes #6605 

Make sure the assertion does not happen before the committed flag is read.

### CODE REVIEW

**Review by sbordet — APPROVED** [review]

File: jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java [hunk 1]
```diff
@@ -852,7 +853,7 @@ public void handle(String target, Request baseRequest, HttpServletRequest reques
     @Test
     public void testEmptyBufferKnown() throws Exception
```
Comment (sbordet) [inline jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java]: The current test name is weird.
Can you rename the test to be `testResponseIsCommittedWithZeroContentLength()` or similar?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java (hunk 1 above)
Comment (lorban) [reply jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java]: This test is mostly about testing what's going on with an empty buffer, so we should keep the `testEmptyBuffer` prefix.

WDYT of `testEmptyBufferWithZeroContentLength`?

Comment (sbordet) [reply jetty-server/src/test/java/org/eclipse/jetty/server/HttpOutputTest.java]: `testResponseCommittedWithEmptyBufferAndZeroContentLength()`?

**Review by sbordet — APPROVED** [review]
