### PR TITLE
Issue #2620 - guard against exceptions for WebSocket onClose and onError

### LINKED ISSUE #2620: Exception from user endpoint onClose results in unclosed WebSocketSession
Hey, I'm using Jetty `9.4.6.v20170531` in PROD, web-socket is heavily utilized in our service.

Today two nodes are found memory leak, GC threads took up nearly all computing power, after carefully examining the heap dumped, we find many `WebSocketSession`s are not properly released, so are our web-socket handlers.

~~When `onWebSocketError` is called, the following action is taken:~~

        if (this._session != null) {
            // resources clean up here

            if(_session.isOpen()){
                Session s = _session;
                _session = null;
                try {
                    s.disconnect();
                } catch (Exception e) {
                    logger.error("disconnect failed", e);
                }
            }
            logger.info("close user handler finished");
        }
        this._session = null;

~~but, unlike `onWebSocketClose` callback, the source code of [WebSocketSession#disconnect](https://github.com/eclipse/jetty.project/blob/7af2eecf6a78818e674ad13006b1462fb9b062dd/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java#L231) shows us the managed WebSocketSession is not cleared, we later managed to cast `Session` object back to `WebSocketSession`, and call [getContainerScope().onSessionClosed()](https://github.com/eclipse/jetty.project/blob/7af2eecf6a78818e674ad13006b1462fb9b062dd/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/WebSocketSession.java#L350) to manually release leaked sessions as follows:~~

         if(this._session != null) {
                if(this._session instanceof WebSocketSession) {
                    ((WebSocketSession)this._session).getContainerScope().onSessionClosed((WebSocketSession) this._session);
                }
            }

Edited: the initial finding is misleading, see the following discussion.

We believe this behavior is a bug, if you should need information, feel free to ask me.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
Add test case to reproduce the failure scenario described in issue #2620 .
Fix by catching `Throwable` and warning in `callApplicationOnClose()` and `callApplicationOnError()`.

Closes #2620

### CODE REVIEW

File: jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/ErrorCloseTest.java [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+        try (StacklessLogging stacklessLogging = new StacklessLogging(WebSocketSession.class))
+        {
+            assertTrue(serverSocket.closed.await(5, TimeUnit.SECONDS));
+        }
+
+        // Check we have stopped the WebSocketSession properly.
+        assertFalse(serverSocket.session.isOpen());
+        serverCloseListener.await(5, TimeUnit.SECONDS);
+        assertTrue(((WebSocketSession)serverSocket.session).isStopped());
+    }
```
Comment (joakime) [inline jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/ErrorCloseTest.java:277]: Am I missing the `onOpen` and `onMessage` version of this test?
Is that done somewhere else?

**Review by joakime — COMMENTED** [review]
The testcase seems half-complete.

You have 4 methods, but only tests for 2.

File: jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/ErrorCloseTest.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/ErrorCloseTest.java:277]: This was really just aimed at the specific case where `onClose` and `onError` throw after a local error like a timeout occurs. Instead of a timeout we could generate the error by throwing from `onOpen` or `onMessage`, but it won't fail like this unless we still throw in `onClose` or `onError`.

Comment (lachlan-roberts) [reply jetty-websocket/jetty-websocket-tests/src/test/java/org/eclipse/jetty/websocket/tests/ErrorCloseTest.java:277]: I will add some more tests for errors from the other methods as well.

**Comment by lachlan-roberts** [comment]
@joakime I have added the extra test cases you asked for.

**Comment by lachlan-roberts** [comment]
@joakime can I get a re-review for this

**Review by joakime — APPROVED** [review]
LGTM
