### PR TITLE
Port ee9 `BlockingTest` to ee10/11

### LINKED ISSUE #12721: `DemoModulesTest.testSpec()` is flaky
**Jetty version(s)**
12.1.x

**Jetty Environment**
ee10, ee11 only; ee9 looks stable

**Description**
`DemoModulesTest.testSpec()` sometimes fails with:

```
java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@7e3c79db::SocketChannelEndPoint@7a03e2c4[{l=/127.0.0.1:35542,r=localhost/127.0.0.1:42685,ISHUT,fill=-,flush=-,to=0/30000}{io=0/0,kio=0,kro=1}]->[HttpConnectionOverHTTP@7e3c79db(l:/127.0.0.1:35542 <-> r:localhost/127.0.0.1:42685,closed=false)=>HttpChannelOverHTTP@3f0173e0(exchange=HttpExchange@5467eea4{req=HttpRequest[POST /ee11-test-spec/test/xx HTTP/1.1]@c4c0b41[TERMINATED/null] res=HttpResponse[null 0 null]@160396db[PENDING/null]})[send=HttpSenderOverHTTP@131bfb9d(req=QUEUED,failure=null)[HttpGenerator@ef4aa84{s=START}],recv=HttpReceiverOverHTTP@6b047c5c(ex=HttpExchange@5467eea4{req=HttpRequest[POST /ee11-test-spec/test/xx HTTP/1.1]@c4c0b41[TERMINATED/null] res=HttpResponse[null 0 null]@160396db[PENDING/null]},rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]]

	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:345)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:440)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2117)
	at org.eclipse.jetty.client.transport.HttpRequest.send(HttpRequest.java:707)
	at org.eclipse.jetty.tests.distribution.DemoModulesTests.testSpec(DemoModulesTests.java:386)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:294)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:294)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:294)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:294)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.io.EOFException: HttpConnectionOverHTTP@7e3c79db::SocketChannelEndPoint@7a03e2c4[{l=/127.0.0.1:35542,r=localhost/127.0.0.1:42685,ISHUT,fill=-,flush=-,to=0/30000}{io=0/0,kio=0,kro=1}]->[HttpConnectionOverHTTP@7e3c79db(l:/127.0.0.1:35542 <-> r:localhost/127.0.0.1:42685,closed=false)=>HttpChannelOverHTTP@3f0173e0(exchange=HttpExchange@5467eea4{req=HttpRequest[POST /ee11-test-spec/test/xx HTTP/1.1]@c4c0b41[TERMINATED/null] res=HttpResponse[null 0 null]@160396db[PENDING/null]})[send=HttpSenderOverHTTP@131bfb9d(req=QUEUED,failure=null)[HttpGenerator@ef4aa84{s=START}],recv=HttpReceiverOverHTTP@6b047c5c(ex=HttpExchange@5467eea4{req=HttpRequest[POST /ee11-test-spec/test/xx HTTP/1.1]@c4c0b41[TERMINATED/null] res=HttpResponse[null 0 null]@160396db[PENDING/null]},rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]]
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:544)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1797)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:321)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parseAndFill(HttpReceiverOverHTTP.java:250)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:85)
	at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:97)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:267)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP$FillableCallback.succeeded(HttpConnectionOverHTTP.java:458)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:480)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:443)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

It seems that [this PR](https://github.com/jetty/jetty.project/pull/12635) has changes that are making the test fail more reliably, but even vanilla **jetty-12.1.x** can fail.

Running only ee10 or ee11 seems to make the test fail much less often.

Adding a `Thread.sleep()` just before `client.POST(baseURI + "/test/xx").send()` also seems to make the test fail much less often.

### PR DESCRIPTION
**Pull request by lorban**
Porting [ee9 BlockingTest](https://github.com/jetty/jetty.project/pull/12529) to ee10/11 seems to have uncovered some bugs.

There are still some bugs in ee9 too, uncovered by the new `testBlockingCloseWhileReading` test:

1) `asyncContext.complete()` throws after the connection was closed by the client. Historically, this test tolerated these exceptions though.
2) `outputStream.close()` sometimes throws `java.lang.IllegalArgumentException: newPosition > limit: (9 > 0)` which tend to indicate a buffer use after release.

Once this is merged, a new issue should be opened about those.

Also contains a fix for https://github.com/jetty/jetty.project/issues/12721

### CODE REVIEW

**Comment by lorban** [comment]
@gregw @sbordet nudge

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java [hunk 1]
```diff
@@ -466,6 +468,15 @@ public static <T> T get(CompletableFuture<T> completableFuture)
         }
     }
 
+    public static String toString(Throwable x)
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java]: javadoc

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java [hunk 2]
```diff
@@ -395,6 +395,12 @@ void release()
             _condition.signal();
         }
 
+        void fail()
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java:420]: This whole class lacks javadoc.

Rather than have n >= 3 copies of it, why not move to jetty-util and document properly

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/AsyncContentProducer.java [hunk 3]
```diff
@@ -395,6 +395,12 @@ void release()
             _condition.signal();
         }
 
+        void fail()
```
Comment (gregw) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/AsyncContentProducer.java:420]: ditto ee10 comments

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java [hunk 4]
```diff
@@ -562,7 +565,16 @@ public void close() throws IOException
                             _apiState = ApiState.BLOCKED;
                             _state = State.CLOSING;
                             blocker = _writeBlocker.callback();
-                            content = _aggregate != null && _aggregate.hasRemaining() ? _aggregate.getByteBuffer() : BufferUtil.EMPTY_BUFFER;
+                            aggregate = _aggregate;
+                            if (aggregate != null && aggregate.hasRemaining())
+                            {
+                                aggregate.retain();
+                                content = aggregate.getByteBuffer();
```
Comment (gregw) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java]: Generally getting the ByteBuffer from the aggregate is an anti-pattern as we want to avoid unnecessary copies if the aggregate is internally retaining.

Can't the `content` be a RBB and that way you can use RBB.writeTo below?

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java [hunk 5]
```diff
@@ -580,7 +592,16 @@ public void close() throws IOException
                             // Output is idle in async state, so we can do an async close
                             _apiState = ApiState.PENDING;
                             _state = State.CLOSING;
-                            content = _aggregate != null && _aggregate.hasRemaining() ? _aggregate.getByteBuffer() : BufferUtil.EMPTY_BUFFER;
+                            aggregate = _aggregate;
+                            if (aggregate != null && aggregate.hasRemaining())
+                            {
+                                aggregate.retain();
+                                content = aggregate.getByteBuffer();
```
Comment (gregw) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java]: ditto

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java [hunk 6]
```diff
@@ -1209,8 +1209,15 @@ public ServletInputStream getInputStream() throws IOException
...
             throw new IllegalStateException("READER");
         _inputState = ServletContextRequest.INPUT_STREAM;
-        // Try to write a 100 continue, ignoring failure result if it was not necessary.
-        _servletChannel.getResponse().writeInterim(HttpStatus.CONTINUE_100, HttpFields.EMPTY);
+        try
+        {
+            // Try to write a 100 continue, ignoring failure result if it was not necessary.
+            _servletChannel.getResponse().writeInterim(HttpStatus.CONTINUE_100, HttpFields.EMPTY);
+        }
+        catch (IllegalStateException ise)
```
Comment (gregw) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java:1217]: this kind of conflicts with the comment above? please explain?

File: jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/BlockingTest.java
Comment (gregw) [inline jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/BlockingTest.java:1]: Would it make more sense to convert tests like these into integration tests that would written as Servlets written to the Servlet 5.0 API.  We could then deploy them to EE9, EE10 and EE11 without duplicating the code.

**Review by gregw — CHANGES_REQUESTED** [review]
I'm wondering if this should be an integration test rather than a duplicated unit test?

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java (hunk 4 above)
Comment (lorban) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java]: That can be done, and looking more closely at that code I think I figured what the problem is in https://github.com/jetty/jetty.project/issues/12721.

Let me change that.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java (hunk 5 above)
Comment (lorban) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/HttpOutput.java]: ditto.

File: jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/BlockingTest.java
Comment (lorban) [reply jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/BlockingTest.java:1]: That would make sense, much like creating a common code module for EE9/10/11 that we already discussed. But until then, duplicating this code is the only choice.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java (hunk 6 above)
Comment (lorban) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java:1217]: You are right, the `IllegalStateException` should be ignored.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/AsyncContentProducer.java (hunk 3 above)
Comment (lorban) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/AsyncContentProducer.java:420]: Added javadoc.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java]: Done.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java (hunk 2 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java:420]: Added javadoc.
Regarding the 3 copies, EE9 is slightly different but EE10/11 are indeed identical. But this class is very specific to the servlet input FSM so I'd rather move it to a module common between EE* versions rather than moving it to jetty-util as I seriously doubt that it can be reused.

**Review by gregw — APPROVED** [review]
