### PR TITLE
jetty 12.0.x 8867 plugin toolchain

### LINKED ISSUE #8867: Jetty maven plugin is not Maven toolchain aware
**Jetty version(s)**
jetty-maven-plugin: all versions but checking the latest 9.x version: 9.4.49.v20220914 and latest 11.0.12 versions

**Java version/vendor** `(use: java -version)`
any, for e.g. 11.x or 17.x
**OS type/version**
Windows 11

**Description**
When Maven toolchains are used, the jetty-maven plugin does not use the JDK specified there but uses the JDK which is used to build maven

**How to reproduce?**
1. Create a toolchain.xml that specified multiple JDK versions. For e.g:
```
<?xml version="1.0" encoding="UTF-8"?>
<toolchains>
  <!-- JDK toolchains -->
  <toolchain>
	<type>jdk</type>
	<provides>
	  <version>1.17</version>
	  <vendor>oracle</vendor>
	</provides>
	<configuration>
	  <jdkHome>${JDK17_HOME}</jdkHome>
	</configuration>
  </toolchain>
  <toolchain>
	<type>jdk</type>
	<provides>
	  <version>1.11</version>
	  <vendor>oracle</vendor>
	</provides>
	<configuration>
	  <jdkHome>${JDK11_HOME}</jdkHome>
	</configuration>
  </toolchain>
</toolchains>
```

2.. Stick the toolchain.xml into your ~/.m2 folder.
3. In any jetty-maven supported project, add the toolchain plugin entry specifying a JDK version - say 17 in this example - in your build plugins section In you maven pom.xml:
  ```
<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-toolchains-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <goals>
              <goal>toolchain</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <toolchains>
            <jdk>
              <version>17</version>
              <vendor>oracle</vendor>
            </jdk>
          </toolchains>
        </configuration>
      </plugin>
     </plugins>
   </build>
```
4. Add any common jetty maven plugin to run the application to your pom.xml
5. Run a maven build using a different JDK like JDK 11 (assign JAVA_HOME to this JDK, add JDK/bin folder this to the windows path)
6. The jetty maven plugin will use JDK 11 thought the JDK 17 toolchain was specified and activated - the correct JDK 17 version will be used by the maven-compiler-plugin, surefire-plugin etc.

### PR DESCRIPTION
**Pull request by olamy**
- **Issue #8867 Jetty Maven plugin toolchain aware**
- **checkstyle and compilation**
- **checkstyle**
- **lol null check :)**

### CODE REVIEW

File: jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/AbstractWebAppMojo.java [hunk 1]
```diff
@@ -477,6 +511,30 @@ protected void startJetty()
...
+    /**
+     * {@return the tool chain specified by the user in plugin parameters}.
+     */
+    protected final Toolchain getToolchain()
+    {
+        Toolchain tc = null;
+
+        if (jdkToolchain != null)
+        {
+            List<Toolchain> tcs = toolchainManager.getToolchains(session, "jdk", jdkToolchain);
```
Comment (janbartel) [inline jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/AbstractWebAppMojo.java:523]: Need a null check on `toolchainManager`?

File: jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/AbstractWebAppMojo.java [hunk 2]
```diff
@@ -498,7 +556,13 @@ protected JettyEmbedder newJettyEmbedder()
     protected JettyForker newJettyForker()
         throws Exception
     {
-        JettyForker jetty = new JettyForker();
+        Toolchain toolchain = getToolchain();
```
Comment (janbartel) [inline jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/AbstractWebAppMojo.java:559]: If the user just wants to use the same jdk as maven, what happens here?

**Review by janbartel — CHANGES_REQUESTED** [review]
I think you need a null check?

File: jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/AbstractWebAppMojo.java (hunk 1 above)
Comment (olamy) [reply jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/AbstractWebAppMojo.java:523]: nah it's Maven core provided. same as injecting the Project this will be always there

File: jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/AbstractWebAppMojo.java (hunk 2 above)
Comment (olamy) [reply jetty-ee10/jetty-ee10-maven-plugin/src/main/java/org/eclipse/jetty/ee10/maven/plugin/AbstractWebAppMojo.java:559]: if no toolchain (javaPath == null) this will use default java as today see https://github.com/jetty/jetty.project/pull/13288/files#diff-c750b46ce600b8e862b6331f233a43d81b203f47a5353f289e6fcde7ae1eb205R263 (method `protected String getJavaBin()`)

**Review by janbartel — APPROVED** [review]
