### PR TITLE
Modify `HttpContent` caching such as it does not apply to content with unknown length

### LINKED ISSUE #14685: CachingHttpContentFactory#getContent may return null if httpContent size is not set
**Jetty version(s)**
12.1.6

**Jetty Environment**
ee11

**HTTP version**
1.1

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)

**OS type/version**
Ubuntu 24.04.4 LTS

**Description**
In CachingHttpContentFactory#getContent,  when HttpContent size is set to -1, isCacheable may return true and lead to a case where getContent() return `null` instead of the httpContent. 

**How to reproduce?**

```
import org.eclipse.jetty.http.content.CachingHttpContentFactory;
import org.eclipse.jetty.http.content.HttpContent;
import org.eclipse.jetty.http.content.ResourceHttpContent;
import org.eclipse.jetty.io.ByteBufferPool;
import org.eclipse.jetty.util.resource.MemoryResource;

import java.io.IOException;
import java.net.URI;

public class Test {

    private static final String CONTENT_TYPE = "text/html; charset=utf-8";
    private static final URI AN_URI = URI.create("file://test");

    public static void main(String[] args) throws IOException {
        ResourceHttpContent content = new ResourceHttpContent(new MemoryResource(AN_URI, new byte[0]), CONTENT_TYPE);
        HttpContent.Factory delegate = path -> new UnknownLengthHttpContent(content);

        CachingHttpContentFactory cache = new CachingHttpContentFactory(delegate, ByteBufferPool.SIZED_NON_POOLING);

        HttpContent httpContent = cache.getContent("/something");
        System.out.println("httpContent is " + httpContent);
    }

    private static class UnknownLengthHttpContent extends HttpContent.Wrapper {
        public UnknownLengthHttpContent(HttpContent content) {
            super(content);
        }

        @Override
        public long getContentLengthValue() {
            return -1;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by lorban**
Fixes #14685

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java [hunk 1]
```diff
@@ -268,13 +263,16 @@ public HttpContent getContent(String path) throws IOException
             }
         });
 
-        if (added.get())
+        if (cachingHttpContent != null)
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: I think this is now different from before, where added was true only if an entry was added.
Now computeIfAbsent() always return non-null, so this is always true.

Restore the boolean, but perhaps `boolean[] added = new boolean[1]` is enough?

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/content/CachingHttpContentFactoryTest.java [hunk 2]
```diff
@@ -54,6 +58,35 @@ public void tearDown()
         assertThat("Leaks: " + trackingPool.dumpLeaks(), trackingPool.getLeaks().size(), is(0));
     }
 
+    @Test
+    public void testUnknownLength() throws Exception
+    {
+        ResourceHttpContent content = new ResourceHttpContent(new MemoryResource(URI.create("file://test"), new byte[] {(byte)0xAA}), "text/html");
+        HttpContent.Factory delegate = path -> new HttpContent.Wrapper(content)
```
Comment (sbordet) [inline jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/content/CachingHttpContentFactoryTest.java]: I'd prefer to have `"/something" -> new HttpContent...` so that it matches what's done below.

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/content/CachingHttpContentFactoryTest.java [hunk 3]
```diff
@@ -54,6 +58,35 @@ public void tearDown()
...
+        RetainableByteBuffer rbb = IOResources.toRetainableByteBuffer(httpContent.getResource(), sizedPool);
+        try
+        {
+            assertThat(rbb.getByteBuffer().remaining(), is(1));
+            assertThat(rbb.getByteBuffer().get(), is((byte)0xAA));
+        }
+        finally
+        {
+            rbb.release();
+        }
```
Comment (sbordet) [inline jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/content/CachingHttpContentFactoryTest.java:91]: This test is not testing that the unknown-length content is not cached.

Either assert that `CachingHttpContentFactory.cache.size()==0` or perhaps check with `==` that 2 calls return different objects.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: I've restored the atomic boolean, I don't believe a `boolean[]` would yield any measurable perf improvement.

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/content/CachingHttpContentFactoryTest.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/content/CachingHttpContentFactoryTest.java:91]: Indeed, I added extra assertions of the cache size.

**Review by sbordet — APPROVED** [review]
