### PR TITLE
Fix broken client tls negotiation

### LINKED ISSUE #11965: Client: Some HTTP/2 requests are never sent
**Jetty version(s)**
Jetty 12.0.10

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)

**OS type/version**
Windows 11

**Description**
When using the Jetty 12 HttpClient to send a request to certain servers via HTTP/2, the request never completes. In fact, the request is only queued, but sending the request never even begins.

This only happens with some servers, which do support HTTP/2.

**How to reproduce?**
```java
var connector = new ClientConnector();
connector.setSslContextFactory(new SslContextFactory.Client());
var httpClient = new HttpClient(new HttpClientTransportDynamic(connector,
    HttpClientConnectionFactory.HTTP11,
    new ClientConnectionFactoryOverHTTP2.HTTP2(new HTTP2Client(connector))
));
httpClient.start();
ContentResponse response = httpClient.newRequest("https://microsoft.sharepoint.com")
    .onRequestQueued(r -> System.out.println("request queued"))
    .onRequestBegin(r -> System.out.println("request begin"))
    .onRequestContent((r, c) -> System.out.println("request content"))
    .onRequestSuccess(r -> System.out.println("request success"))
    .onResponseBegin(r -> System.out.println("response begin"))
    .onResponseContent((r, c) -> System.out.println("response content"))
    .onResponseSuccess(r -> System.out.println("response success"))
    .send();
System.out.println(response);
httpClient.stop();
```

The above snippet creates a HttpClient that supports both HTTP/1.1 and HTTP2, and makes a request to "https://microsoft.sharepoint.com". Several events are logged, so we see that the request is only ever queued, but never sent.

When forcing the client to use HTTP/1.1, either by removing support for HTTP/2, or by using `version(HttpVersion.HTTP_1_1)`, everything works as expected.

Also, the following curl command sends the same request, also using HTTP/2, and works fine:
`curl "https://microsoft.sharepoint.com" --http2`

### PR DESCRIPTION
**Pull request by lorban**
When the Jetty client needs to negotiate TLS with the server, it fails to do so and cannot open a connection.
The only indication is the following debug log:

```
2024-07-03 10:40:19.579:DEBUG:oeji.FillInterest:HttpClient@59d016c9-24: onFail FillInterest@40dda3e8{null}
java.nio.ReadOnlyBufferException
	at java.base/java.nio.HeapByteBufferR.put(HeapByteBufferR.java:246)
	at org.eclipse.jetty.util.BufferUtil.put(BufferUtil.java:460)
	at org.eclipse.jetty.util.BufferUtil.append(BufferUtil.java:549)
	at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.fill(SslConnection.java:830)
	at org.eclipse.jetty.io.NegotiatingClientConnection.fill(NegotiatingClientConnection.java:102)
	at org.eclipse.jetty.io.NegotiatingClientConnection.onFillable(NegotiatingClientConnection.java:84)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.onFillable(SslConnection.java:574)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:390)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:150)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
```

This happens because we mistakenly pass a read-only empty byte buffer to a `fill()` method that tries to append to it, so it fails with an exception instead of returning that zero byte was copied.

Fixes #11965

### CODE REVIEW

**Review by sbordet — COMMENTED** [review]
I think it's going to be difficult to know when to use one constant vs the newly introduced one.

Can we make the old constant non-read only?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 1]
```diff
@@ -57,6 +57,7 @@
 public class Content
 {
     private static final Logger LOG = LoggerFactory.getLogger(Content.class);
+    private static final ByteBuffer EMPTY_READ_ONLY_BUFFER = BufferUtil.EMPTY_BUFFER.asReadOnlyBuffer();
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Do we really need this?
The buffer is empty, and any attempt to write would result in a `BufferOverflowException` anyway.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: It's needed by `Content.Chunk.asReadOnly()` to avoid needlessly duplicating error/eof/empty chunks, as is tested by `ContentTest.testAsReadOnly()`.

Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Can you expand the test to avoid read-onlyness if remaining() == 0?

**Review by sbordet — CHANGES_REQUESTED** [review]
See comment.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Ok, done.

**Review by sbordet — APPROVED** [review]
