### PR TITLE
Issue #4567 - StdErrLog cleanup and final Arg Throwable support

### LINKED ISSUE #4567: Jetty logging supporting Throwable as last argument
**Jetty version**
10.0.x

**Description**
Like other logging frameworks, would be handy if Jetty logging (`StdErrLog`) could detect whether the last argument is a `Throwable` and if so print its stack trace.

In this way one could write:

```
logger.debug("Log {}", this, new Throwable());
```

rather than:

```
logger.debug("Log " + this, new Throwable())
```

### PR DESCRIPTION
**Pull request by joakime**
Checkstyle fixes ...
+ `Log.__loggers` now `Log.LOGGERS`
+ `Log.__props` now `Log.PROPS`
+ `StdErrLog.__tagpad` now `StdErrLog.THREADNAME_PADDING`
+ `StdErrLog.__source` now `StdErrLog.SOURCE`
+ `StdErrLog.__long` now `StdErrLog.LONG_CLASSNAMES`
+ `StdErrLog.__escape` now `StdErrLog.ESCAPE_CONTROL_CHARS`
+ Removed redundant `public` modifier on Log interface methods

New code ...
+ New `Log.getProperty(String key, String defaultValue)`
  Used by JavaUtilLog, JettyLogHandler, and StdErrLog
+ New `StdErrLog.getConfiguredLevel()`
+ New `StrErrLog.println(String)` used to write StringBuilder
  to configured PrintStream

Removed code ...
+ Removed deprecated prop check in StdErrLog initialization

Cleanup and Corrected code ...
+ If final argument on `Object ... args` is a Throwable, it's used as the logging cause (for stacktrace purposes)
+ `StdErrLog.setDebugEnabled(boolean)` cleanup
+ `StdErrLog._stderr` is now used and is never null
+ Only one `StdErrLog.format()` method entry point
+ `StdErrLog.format(StringBuilder, Throwable)` now called `.formatCause(StringBuilder, Throwable, String)`

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java [hunk 1]
```diff
@@ -426,50 +431,57 @@ public void debug(Throwable thrown)
...
+        if (inArgs != null)
         {
-            format(buffer, thrown);
+            msgArgs = inArgs;
+            msgArgsLen = inArgs.length;
+            if (msgArgsLen > 0)
+            {
+                if (inArgs[msgArgsLen - 1] instanceof Throwable)
+                {
+                    cause = (Throwable)inArgs[msgArgsLen - 1];
```
Comment (gregw) [inline jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java]: Should we do this IFF the number of args is +1 the number of args in the format string?

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java [hunk 2]
```diff
@@ -426,50 +431,57 @@ public void debug(Throwable thrown)
...
+        Throwable cause = null;
+
+        if (inArgs != null)
         {
-            format(buffer, thrown);
+            msgArgs = inArgs;
+            msgArgsLen = inArgs.length;
+            if (msgArgsLen > 0)
+            {
+                if (inArgs[msgArgsLen - 1] instanceof Throwable)
```
Comment (gregw) [inline jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java]: merge the two `if`s into a single `&&` clause.

**Review by gregw — CHANGES_REQUESTED** [review]
Mostly good, just some quibbles.....

.... but tell me again why we can't just do `s/{}/%s/g` and then use normal `String.format`?

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java [hunk 3]
```diff
@@ -65,8 +65,8 @@
 {
     private static final String THIS_CLASS = JavaUtilLog.class.getName();
     private static final boolean __source =
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java]: Should not this be `SOURCE` since it's a `static final` constant?

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java [hunk 4]
```diff
@@ -65,8 +65,8 @@
 {
     private static final String THIS_CLASS = JavaUtilLog.class.getName();
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java]: This constant is ever used once, so it can just be inlined.

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java [hunk 5]
```diff
@@ -65,8 +65,8 @@
...
     private static final boolean __source =
-        Boolean.parseBoolean(Log.__props.getProperty("org.eclipse.jetty.util.log.SOURCE",
-            Log.__props.getProperty("org.eclipse.jetty.util.log.javautil.SOURCE", "true")));
+        Boolean.parseBoolean(Log.getProperty("org.eclipse.jetty.util.log.SOURCE",
+            Log.getProperty("org.eclipse.jetty.util.log.javautil.SOURCE", "true")));
 
     private static boolean _initialized = false;
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java]: Why this `static` has just 1 `_` while the same in `Log` has 2 `__`?

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/Log.java [hunk 6]
```diff
@@ -67,8 +67,8 @@
     /**
      * Logging Configuration Properties
      */
-    protected static final Properties __props = new Properties();
-    private static final ConcurrentMap<String, Logger> __loggers = new ConcurrentHashMap<>();
+    protected static final Properties PROPS = new Properties();
+    private static final ConcurrentMap<String, Logger> LOGGERS = new ConcurrentHashMap<>();
     private static boolean __initialized;
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/log/Log.java:72]: See above, one or two `_`?

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java [hunk 7]
```diff
@@ -92,30 +93,20 @@
 @ManagedObject("Jetty StdErr Logging Implementation")
 public class StdErrLog extends AbstractLogger
 {
-    private static final String EOL = System.getProperty("line.separator");
+    private static final String EOL = System.lineSeparator();
+    private static final Object[] EMPTY_ARGS = new Object[0];
     // Do not change output format lightly, people rely on this output format now.
-    private static int __tagpad = Integer.parseInt(Log.__props.getProperty("org.eclipse.jetty.util.log.StdErrLog.TAG_PAD", "0"));
+    private static int THREADNAME_PADDING = Integer.parseInt(Log.getProperty("org.eclipse.jetty.util.log.StdErrLog.TAG_PAD", "0"));
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java]: This is not `final`, so not a constant, so it should be `__threadNamePadding`.

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java [hunk 8]
```diff
@@ -350,28 +341,35 @@ public boolean isDebugEnabled()
...
-            for (Logger log : Log.getLoggers().values())
+        String name = getName();
+        for (Logger log : Log.getLoggers().values())
+        {
+            if (log.getName().startsWith(name) && log instanceof StdErrLog)
             {
-                if (log.getName().startsWith(getName()) && log instanceof StdErrLog)
-                    ((StdErrLog)log).setLevel(((StdErrLog)log)._configuredLevel);
+                StdErrLog logger = (StdErrLog)log;
+                logger.setLevel(lvlFunc.apply(logger));
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java]: This seems to me more complicated than it needs to.
Was not enough to use a local variable?

```java
StdErrLog logger = (StdErrLog)log;
int level = enabled ? LEVEL_DEBUG : logger.getConfiguredLevel();
logger.setLevel(level);
```

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by joakime** [comment]
> .... but tell me again why we can't just do `s/{}/%s/g` and then use normal `String.format`?

The use of `{}` placeholder is industry standard for loggers, used by java.util.logging, slf4j, logback, log4j 1.x, log4j 2.x.

Plus, if you use the industry standard APIs, the IDE actually helps you by flagging lines that have mismatches of placeholders to arguments as well.

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java (hunk 1 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java]: mismatched placeholders and arguments are usually an error in most IDEs.
scanning the placeholders each and every time isn't a great idea.

I would prefer that we just use the MessageFormatters as-is, and don't reinvent the wheel here.
also, if the logger is using a `org.slf4j.spi.LocationAwareLogger` then the formatting is done with ...

``` java
FormattingTuple ft = MessageFormatter.arrayFormat(msg, argArray);
logger.log(level, ft.getMessage());
```

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java (hunk 2 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java]: Done

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java (hunk 3 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java]: done.

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java (hunk 4 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java]: Done.

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java (hunk 5 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java]: It was `__<constant>` (aka `static final`) and `_<field>` (aka a field).
But a static alone didn't have a old-school jetty syntax/format.

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java (hunk 7 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java]: Done.

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java (hunk 8 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java]: Done.

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/Log.java (hunk 6 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/log/Log.java:72]: Fixed.

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java (hunk 5 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/log/JavaUtilLog.java]: I'll fix it anyway.

File: jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java [hunk 9]
```diff
@@ -426,112 +421,118 @@ public void debug(Throwable thrown)
...
-    }
 
-    protected void format(StringBuilder buffer, Throwable thrown)
-    {
-        format(buffer, thrown, "");
+        if (cause != null)
+        {
+            if (isHideStacks())
+            {
+                builder.append(": " + cause);
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/log/StdErrLog.java]: Small nit, this should be `builder.append(": ").append(cause);`

**Review by sbordet — APPROVED** [review]
Apart the small nit, LGTM.

**Review by gregw — APPROVED** [review]
