### PR TITLE
Use provided buffer size when serving non-Path Resources

### LINKED ISSUE #12963: Slow transfers on custom / non-Path Resource instances
**Jetty version(s)**
12.0.x; tested with 12.0.12; also applicable to latest 12.0.20-SNAPSHOT

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
any; openjdk version "22.0.2" 2024-07-16

**OS type/version**
any; macOS

**Description**
When serving data via custom `Resource` classes that return `null` for `getPath` (and are not `MemoryResource`s), we currently disregard the available buffer size (e.g., 32768) and use a buffer size of 4096 instead when wrapping the Resource's `InputStream`.

This severely impacts download performance.

**How to reproduce?**

Serve content from a custom `Resource` instance that returns `null` for `getPath`, returning a large amount data via `newInputStream`. Measure throughput (e.g., with `curl`, etc.)

With a hardcoded blocksize of 4096, I'm seeing ca. 900 MB/s transferred.
By using the available blocksize (in my case, 32768), I'm seeing ca.  4100 MB/s

**Proposal**
Modify the `InputStream` fallback in `IOResources.asContentSource` such that it uses the buffer pool and size as provided in the method signature, i.e.

replace
```
return new InputStreamContentSource(resource.newInputStream());
```
with
```
return new InputStreamContentSource(resource.newInputStream(), new ByteBufferPool.Sized(bufferPool, false, bufferSize));
```

### PR DESCRIPTION
**Pull request by kohlschuetter**
The helper IOResources.asContentSource wraps a given Resource to be served as a Content.Source. Unless a resource had a Path component, InputStreamContentSource is used as a fallback.

Previously, we were using a hardcoded buffer size of 4096, even if the request size was larger (e.g., 32768).

This severely limited throughput when serving content via non-Path-bearing Resource implementations.

Use the provided buffer pool and size instead.

Fixes #12963

### CODE REVIEW

**Comment by kohlschuetter** [comment]
With this fix in place, on my Mac, I'm seeing ca. 4.5 GB/s with the default 32kb buffer and 6 GB/s for 64kb (set via `HttpConfiguration#setOutputBufferSize`) via `curl`, instead of <~1GB/s for hardcoded 4k buffer.

**Comment by lorban** [comment]
See https://github.com/jetty/jetty.project/pull/12972 for a slightly cleaned up version of that fix.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java [hunk 1]
```diff
@@ -147,7 +147,7 @@ public static Content.Source asContentSource(Resource resource, ByteBufferPool b
         // Fallback to wrapping InputStream.
         try
         {
-            return new InputStreamContentSource(resource.newInputStream());
+            return new InputStreamContentSource(resource.newInputStream(), new ByteBufferPool.Sized(bufferPool, false, bufferSize));
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java:150]: - You should check that `resource.newInputStream()` does not return `null` or throw `IllegalArgumentException` like other methods calling `newInputStream` do.
 - You should not hardcode the `directness` to false as it is provided as a parameter.

**Review by lorban — CHANGES_REQUESTED** [review]

**Comment by lorban** [comment]
You can either modify this PR to handle my review comments, or close it and let https://github.com/jetty/jetty.project/pull/12972 be merged instead, as you prefer.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java (hunk 1 above)
Comment (kohlschuetter) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java:150]: @lorban @joakime 

- Adding a check for `null` would change the current behavior, which is throwing a `NullPointerException` (see the constructor). If such changed behavior is desired, I suggest to fix it separately, as it does not pertain to this bug.

- Setting directness to `direct` rather than `false` causes the code to fail with an `UnsupportedOperationException` (which is, sadly, only logged at DEBUG level):
```
[qtp1866161430-20] DEBUG org.eclipse.jetty.ee10.servlet.ResourceServlet - AsyncContextCallback failed org.eclipse.jetty.ee10.servlet.AsyncContextState@43579abb
java.lang.UnsupportedOperationException

	at java.base/java.nio.ByteBuffer.array(ByteBuffer.java:1471)
	at org.eclipse.jetty.io.content.InputStreamContentSource.read(InputStreamContentSource.java:117)
	at org.eclipse.jetty.io.internal.ContentCopier.process(ContentCopier.java:51)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:251)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:232)
	at org.eclipse.jetty.io.Content.copy(Content.java:102)
	at org.eclipse.jetty.io.Content.copy(Content.java:77)
	at org.eclipse.jetty.io.IOResources.copy(IOResources.java:274)
	at org.eclipse.jetty.server.ResourceService.writeHttpContent(ResourceService.java:722)
	at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:670)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:206)
	at org.eclipse.jetty.ee10.servlet.ResourceServlet.doGet(ResourceServlet.java:524)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
...
```

If I understand correctly, by setting directness to `false`, whereas the passed buffers were `direct`, new non-direct buffers will be created (as they are for the previous 4k buffer size). Which seems OK, because I'm still getting 6x the performance out of it.

If you know how to fix `org.eclipse.jetty.io.internal.ContentCopier` to work in this case,  you'd need to do that first before passing the directness as-is, otherwise you will create a new bug.

Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java:150]: The behavior of throwing `NullPointerException` is definitely a bug, so it should be fixed.

The fact that `InputStreamContentSource` accepts a sized pool that gives out direct buffers but cannot work with them is a bug of the `InputStreamContentSource` itself, so it should be fixed there.

Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java:150]: I just checked the `jetty-12.1.x` branch and `InputStreamContentSource` does silently force the directness to be false in it.

Comment (kohlschuetter) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java:150]: Yes, I hope these other bugs can be fixed, but can we please fix these in a separate PR?

It would be really sad to revert my fix if this broke some other use case.

Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/IOResources.java:150]: I can merge your PR then rebase mine on top. This should give us the best of both world.

**Review by lorban — APPROVED** [review]
