### PR TITLE
Fixes #10390 - jetty http3 client and nghttpx.

### LINKED ISSUE #10390: Jetty HTTP/3 Client fails when connecting to `nghttpx` server
**Jetty version(s)**
12.0.0
(11.x affected too)

**Jetty Environment**
core?

**Java version/vendor** `(use: java -version)`
openjdk 17.0.8 2023-07-18

**OS type/version**
WSL2 Ubuntu 22.04 (Windows 11 22H2 Host)

**Description**

When trying jetty http3 client, I found out that it fails with `nghttpx` http3 server.
For example, the test below fails for `https://nghttp2.org:4433` (or local `nghttpx`), but will pass for `https://http3check.net`
However, `curl` built with http3 support will connect both `https://nghttp2.org:4433` and `https://http3check.net` successfully.
```
curl -kv --http3 https://nghttp2.org:4433
```

**How to reproduce?**

Test code:

```
    @Test
    public void testConnection_nghttp2() throws Exception {
        final HTTP3Client h3Client = new HTTP3Client();
        final HttpClientTransportOverHTTP3 transport = new HttpClientTransportOverHTTP3(h3Client);
        final HttpClient client = new HttpClient(transport);
        client.start();
        final ContentResponse response = client.GET("https://nghttp2.org:4433"); // will pass for 'https://http3check.net`
        assertEquals(200, response.getStatus());
        client.stop();
    }
```

Exception thrown:

```
java.util.concurrent.ExecutionException: java.util.concurrent.CompletionException: org.eclipse.jetty.http3.qpack.QpackException$StreamException: buffer_space_exceeded
```
Full stacktrace:
[http3-exception.log](https://github.com/eclipse/jetty.project/files/12426496/http3-exception.log)

### PR DESCRIPTION
**Pull request by sbordet**
Fixed handling of long settings values, so that they do not overflow. Added logging for GREASE cases.

### CODE REVIEW

**Review by lachlan-roberts — APPROVED** [review]

File: jetty-http3/http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/ServerHTTP3Session.java [hunk 1]
```diff
@@ -170,21 +176,27 @@ public void onSettings(SettingsFrame frame)
         {
             if (key == SettingsFrame.MAX_TABLE_CAPACITY)
             {
-                int maxTableCapacity = value.intValue();
+                int maxTableCapacity = (int)Math.min(value, Integer.MAX_VALUE);
```
Comment (lorban) [inline jetty-http3/http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/ServerHTTP3Session.java:179]: You're capping positive values to `Integer.MAX_VALUE`, but can't the long value be negative too, in which case it should be capped or rejected?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-http3/http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/ServerHTTP3Session.java (hunk 1 above)
Comment (sbordet) [reply jetty-http3/http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/ServerHTTP3Session.java:179]: No the value cannot be negative, as it is encoded as a variable-length integer (https://datatracker.ietf.org/doc/html/rfc9000#name-variable-length-integer-enc).

**Review by lorban — APPROVED** [review]
