### PR TITLE
Fixes #5685 - AsyncProxyServlet calls onProxyResponseSuccess() when internally it throws "Response header too large" exception.

### LINKED ISSUE #5685: AsyncProxyServlet calls onProxyResponseSuccess() when internally it throws "Response header too large" exception
**Jetty version**
9.4.30

**Java version**
8

**OS type/version**
Mac

**Description**
I am using embedded jetty version 9.4.30 and use AsyncProxyServlet to reverse proxy request to the server. When the server returns a very large header, AsyncProxyServlet calls onProxyResponseSuccess() with proxyResponse.status=200 even though the servlet sends http status 500 to the client.  Is it possible to detect "Response header too large" error in AsyncProxyServlet ?

### PR DESCRIPTION
**Pull request by sbordet**
* Introduced "maxResponseHeadersSize" parameter to AbstractProxyServlet.
* Introduced HttpGenerator.maxResponseHeadersSize and added checks to not exceed it.
* Fixed HttpParser to generate a 400 in case HttpParser.maxHeaderBytes are exceeded for a response.
* HTTP2Flusher now resets streams in case of failures.
* Removed cases in HTTP2Session where a GOAWAY frame was generated with lastStreamId=0. GOAWAY.lastStreamId=0 means that not a single request was processed by the server, which was obviously incorrect.
* Written tests for both ProxyHandler and ProxyServlet about max response headers size exceeded.

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java [hunk 1]
```diff
@@ -68,25 +73,14 @@ public enum Result
...
-
-    private static final Index<Boolean> ASSUMED_CONTENT_METHODS = new Index.Builder<Boolean>()
-        .caseSensitive(false)
-        .with(HttpMethod.POST.asString(), Boolean.TRUE)
-        .with(HttpMethod.PUT.asString(), Boolean.TRUE)
-        .build();
-
-    // data
     private boolean _needCRLF = false;
+    private int _maxHeaderBytes;
```
Comment (lorban) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java:83]: I wonder if 0 is a sensible default, even if we always call the setter before using the generator.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java [hunk 2]
```diff
@@ -1259,10 +1259,12 @@ protected boolean parseFields(ByteBuffer buffer)
...
-                LOG.warn("{} is too large {}>{}", header ? "Header" : "Trailer", _headerBytes, _maxHeaderBytes);
-                throw new BadMessageException(header
-                    ? HttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE_431
-                    : HttpStatus.PAYLOAD_TOO_LARGE_413);
+                if (debugEnabled)
+                    LOG.debug("{} is too large {}>{}", header ? "Header" : "Trailer", _headerBytes, _maxHeaderBytes);
+                if (_requestParser)
+                    throw new BadMessageException(header ? HttpStatus.REQUEST_HEADER_FIELDS_TOO_LARGE_431 : HttpStatus.PAYLOAD_TOO_LARGE_413);
+                // There is no equivalent of 431 for response headers.
+                throw new BadMessageException(HttpStatus.BAD_REQUEST_400, "Response Header Fields Too Large");
```
Comment (lorban) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java]: It's not a 400 error either as 4xx codes indicate client errors but here it really is a server error. 500 looks like a more correct response code IMHO.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 3]
```diff
@@ -776,7 +778,7 @@ public Action process() throws Exception
                     case HEADER_OVERFLOW:
                     {
                         if (_header.capacity() >= getHttpConfiguration().getResponseHeaderSize())
-                            throw new HttpException.RuntimeException(INTERNAL_SERVER_ERROR_500, "Response header too large");
+                            throw new HttpException.RuntimeException(INTERNAL_SERVER_ERROR_500, "Response Header Fields Too Large");
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Here, the status is (IMHO correctly) set to 500 when headers are too large, unlike H2.

File: jetty-core/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ReverseProxyTest.java [hunk 4]
```diff
@@ -138,4 +137,290 @@ protected org.eclipse.jetty.client.Request newProxyToServerRequest(Request clien
...
+        });
+
+        startClient();
+
+        ContentResponse response = client.newRequest("localhost", proxyConnector.getLocalPort())
+            .version(httpVersion)
+            .timeout(5, TimeUnit.SECONDS)
+            .send();
+
+//        assertTrue(serverToProxyFailureLatch.await(5, TimeUnit.SECONDS));
```
Comment (lorban) [inline jetty-core/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ReverseProxyTest.java]: Delete this comment?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java:83]: We did not check for response headers max size before, so `0` keeps the original behavior.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java]: Unfortunately `BadMessageException` only allows `4xx` error codes.

I'll check if we can throw a different exception.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Not sure what you mean here? H2 does not generate an HTTP response (it just fails the connection).

File: jetty-core/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ReverseProxyTest.java (hunk 4 above)
Comment (sbordet) [reply jetty-core/jetty-proxy/src/test/java/org/eclipse/jetty/proxy/ReverseProxyTest.java]: It should be restored!

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpParser.java]: It is possible to throw a different exception, `HttpException.RuntimeException`, but this is a client parsing a response: should it really generate a 500 Internal _Server_ Error (emphasis on "Server")?

The server could generate a large response; it's the client that cannot parse it, so it's not technically a server error in HTTP/1.1 where the client cannot inform the server about how much it can parse.

@gregw thoughts?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: I wrote H2, I meant the parser. Silly me.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java [hunk 5]
```diff
@@ -103,6 +97,16 @@ public void reset()
...
 
+    public int getMaxHeaderBytes()
+    {
+        return _maxHeaderBytes;
+    }
+
+    public void setMaxHeaderBytes(int maxHeaderBytes)
+    {
+        _maxHeaderBytes = maxHeaderBytes;
+    }
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java:108]: This is kind of a duplicate in the server as we already have `HttpConfiguration.getResponseHeaderSize()`, and we have use overflowing of that buffer to enforce a header size.

So why are we duplicating this mechanism?  Can't the client just allocate a buffer of a specific size when it is asked for a HEADERs buffer?

**Review by gregw — CHANGES_REQUESTED** [review]
Why not allocate a headers buffer of the appropriate size instead of adding a new counter?

**Review by lorban — CHANGES_REQUESTED** [review]
Besides wiring `HttpConfiguration.getResponseHeaderSize()` like Greg suggested, LGTM.

**Comment by sbordet** [comment]
> Why not allocate a headers buffer of the appropriate size instead of adding a new counter?

Because we cannot rely on buffer capacity to enforce max header size.
When a buffer is acquired from the pool, its capacity is rounded up to the next bucket.

So If I configure `maxHeaderBytes=1200`, I'm actually able to stuff up to `2048` bytes, which breaks HTTP/2 and HTTP/3 clients. This is because it is the client telling the server how much the client can receive via a SETTINGS frame.

So we need a mechanism that is independent of the buffer capacity.

**Comment by gregw** [comment]
> So we need a mechanism that is independent of the buffer capacity.

I agree that h2/h3 need greater accuracy than can be achieved with a buffer from a pool.   I also see you have wired up the HttpConfiguration to the generator, so I think that is OK.... although if the buffer size is exact, it will probably overflow before the limit check is applied.

**Review by gregw — APPROVED** [review]

**Review by lorban — APPROVED** [review]
