### PR TITLE
Issue #4741 - fix issues with HttpServletMapping

### LINKED ISSUE #4741: getHttpServletMapping for async dispatch
Unlike the path methods (contextPath, servletPath, pathInfo), the new 4.0 getHttpServletMapping() method does not change when an AsyncContext.dispatch() is done, making it more like include.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Issue #4741**

There were previously 8 TCK tests which were failing due to `HttpServletMapping`, this PR fixes 7 of them however the remaining one is due to the async dispatch expecting the `HttpServletMapping` of the source and not the target, but we think the spec and tck are wrong on that so it hasn't been fixed for now.

- `HttpServletMapping` is now created and set on the `Request` by the `ServletHandler` and is not created lazily which allows us to get the correct servletName in the mapping.
- Removed the leading / for `matchValues` which is tested for in the TCK.
- For exact matches we now store the `HttpServletMapping` and don't need to re-create it every time `getHttpServletMapping()` is called.

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContextEvent.java [hunk 1]
```diff
@@ -185,4 +183,117 @@ public void addThrowable(Throwable e)
...
+            _servletPath = request.getServletPath();
+            _pathInfo = request.getPathInfo();
+            _query = request.getQueryString();
+            _mapping = request.getHttpServletMapping();
+        }
+
+        static AsyncAttributes fromForwardedAttributes(Attributes attributes)
+        {
+            AsyncAttributes asyncAttributes = new AsyncAttributes(attributes);
+            asyncAttributes._requestURI = (String)attributes.getAttribute(RequestDispatcher.FORWARD_REQUEST_URI);
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContextEvent.java]: Do we need to get these attributes now?  could we just get them from the wrapped attributes if they are got?

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContextEvent.java [hunk 2]
```diff
@@ -185,4 +183,117 @@ public void addThrowable(Throwable e)
...
+            set.add(AsyncContext.ASYNC_CONTEXT_PATH);
+            set.add(AsyncContext.ASYNC_SERVLET_PATH);
+            set.add(AsyncContext.ASYNC_PATH_INFO);
+            set.add(AsyncContext.ASYNC_QUERY_STRING);
+            set.add(AsyncContext.ASYNC_MAPPING);
+            return set;
+        }
+
+        @Override
+        public void setAttribute(String key, Object value)
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/AsyncContextEvent.java]: I'm not entirely sure we need to support setting these attributes?   I think we can let a set of them be a noop.

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 3]
```diff
@@ -452,17 +455,18 @@ public void doScope(String target, Request baseRequest, HttpServletRequest reque
                 String servletPath = pathSpec.getPathMatch(target);
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: Do we still need to get the pathSpec here?  If so, don't get it twice. get it once before the if.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 4]
```diff
@@ -452,17 +455,18 @@ public void doScope(String target, Request baseRequest, HttpServletRequest reque
...
                 }
                 else
                 {
-                    baseRequest.setPathSpec(pathSpec);
                     baseRequest.setServletPath(servletPath);
                     baseRequest.setPathInfo(pathInfo);
+                    baseRequest.setHttpServletMapping(httpServletMapping);
                 }
             }
         }
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java:439]: in the log debug below, maybe just log the mapping and make sure it has a good toString

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 5]
```diff
@@ -452,17 +455,18 @@ public void doScope(String target, Request baseRequest, HttpServletRequest reque
                 String servletPath = pathSpec.getPathMatch(target);
                 String pathInfo = pathSpec.getPathInfo(target);
 
+                HttpServletMapping httpServletMapping = mapping.getHttpServletMapping(servletPath);
                 if (DispatcherType.INCLUDE.equals(type))
                 {
                     baseRequest.setAttribute(RequestDispatcher.INCLUDE_SERVLET_PATH, servletPath);
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: It's not really necessary, but lets do the Attributes wrapping trick here as well!  Do we unset these attributes ever?  We should!

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 6]
```diff
@@ -1731,6 +1739,140 @@ void destroyListener(EventListener listener)
...
+    }
+
+    /**
+     * Extends {@link MappedResource} for {@link ServletHolder} but can be
+     * asked for a {@link HttpServletMapping} which may have been created
+     * in advance for servlets which have EXACT mappings.
+     */
+    public static class MappedServletResource extends MappedResource<ServletHolder>
+    {
+        private final MappedServlet _mappedServlet;
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: Why is this a field and not just the same class?

**Review by gregw — CHANGES_REQUESTED** [review]
Looking good! But let's hangout and discuss niggles.

**Comment by lachlan-roberts** [comment]
@gregw this is ready for re-review

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 7]
```diff
@@ -555,21 +559,23 @@ public void doHandle(String target, Request baseRequest, HttpServletRequest requ
...
+            return match.getResource();
         }
 
-        if (_servletNameMap == null)
-            return null;
         ServletHolder holder = _servletNameMap.get(target);
         if (holder == null)
             return null;
-        return new MappedResource<>(null, holder);
+        return new MappedServlet(null, holder);
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: We probably could return a shared instance for this as well?

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 8]
```diff
@@ -1731,6 +1739,109 @@ void destroyListener(EventListener listener)
...
+                    case DEFAULT:
+                    case ROOT:
+                        _httpServletMapping = getServletMapping(pathSpec, pathSpec.getDeclaration(), servletHolder.getName());
+                        break;
+                    default:
+                        _httpServletMapping = null;
+                        break;
+                }
+            }
+            else
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java:1719]: if pathSpec is null then this is a named dispatch so we can probably create a `_httpServletMapping` here as well?

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java (hunk 7 above)
Comment (gregw) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: Also invert the if above and finish method with return null

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 9]
```diff
@@ -434,41 +437,42 @@ public void doScope(String target, Request baseRequest, HttpServletRequest reque
...
-        final PathSpec old_path_spec = baseRequest.getPathSpec();
+        final HttpServletMapping old_http_servlet_mapping = baseRequest.getHttpServletMapping();
 
         DispatcherType type = baseRequest.getDispatcherType();
 
         ServletHolder servletHolder = null;
         UserIdentity.Scope oldScope = null;
 
-        MappedResource<ServletHolder> mapping = getMappedServlet(target);
+        MappedServlet mapping = getMappedServlet(target);
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: rename `s/mapping/mapped/` because a mapping is a different class.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 10]
```diff
@@ -434,41 +437,42 @@ public void doScope(String target, Request baseRequest, HttpServletRequest reque
...
         if (mapping != null)
         {
             servletHolder = mapping.getResource();
 
-            if (mapping.getPathSpec() != null)
+            PathSpec pathSpec = mapping.getPathSpec();
+            if (pathSpec != null)
             {
-                PathSpec pathSpec = mapping.getPathSpec();
                 String servletPath = pathSpec.getPathMatch(target);
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: why are we still getting serlvetPath and pathInfo directly from the pathSpec.   I feel like we can do this more efficiently if we asked the mapping, as it will already know if it is an exact match etc.

**Review by gregw — DISMISSED** [review]
Sorry, it is almost there, but I'd really like to milk this for all we can in efficiency and simplicity.  Perhaps we should pair program to get the last few niggles out?

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 11]
```diff
@@ -434,41 +437,42 @@ public void doScope(String target, Request baseRequest, HttpServletRequest reque
...
                 String pathInfo = pathSpec.getPathInfo(target);
 
+                HttpServletMapping httpServletMapping = mapping.getHttpServletMapping(servletPath);
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: Just to double down on my comments.   The getHttpServletMapping internally does pretty much all the work that is done in getPathMatch and get PathInfo above.   It just needs to remember the results and return them in the JettyHttpServletMapping and we can do only 1 slice&dice rather than 3.

**Comment by gregw** [comment]
The changes I've been making here are towards an end where we can use the `ServletPathMapping` everywhere for the `servletPath`.

Currently the request has fields for:
 - requestURI 
 - contextPath
 - servletPath
 - pathInfo
 - servletPathMapping

The invarient is that requestURI = contextPath + servletPath + pathInfo (modulo encoding and null handling)
The request starts with contextPath servletPath set to null and pathInfo==requestURI
Then any ContextHandler strips off the context path, so contextPath is set, servletPath is still null and pathInfo == pathInContext
Then any ServletHandler strips off the servletPath from the pathInfo, so all three are now correctly set and the mapping is also set.

The problems are:
 - that we have now lost pathInContext and we frequently recalculate by addPaths(servletPath, pathInfo)
 - the servletPath and pathInfo are fields in our mapping, so we have duplicated them 
 - to do a dispatch we need to set then reset 3 fields (all 5 for cross context).

What this PR is a step towards is the request only carrying:
 - requestURI 
 - contextPath
 - pathInContext
 - servletPathMapping

To obtain the servletPath is `servletPathMapping==null?null:servletPathMapping.getServletPath()`
To obtain the pathInfo is `servletPathMapping==null?pathInContext:servletPathMapping.getPathInfo()`
This is how all the attribute wrappers are now setup in this PR.   Eventually will do the same for the request.
The advantages are:
 - the pathInContext is directly available and does not need to be calculated
 - no duplication
 - for a dispatch only 1 field needs to be set/reset (3 for cross context).

I decided that changing request in this PR would make it too huge.   So I've just implemented this pattern for attributes and dispatchers.  Request can be done later.

File: jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java [hunk 12]
```diff
@@ -0,0 +1,148 @@
...
+public class ServletPathMapping implements HttpServletMapping
+{
+    private final MappingMatch _mappingMatch;
+    private final String _matchValue;
+    private final String _pattern;
+    private final String _servletName;
+    private final String _servletPath;
+    private final String _pathInfo;
+
+    public ServletPathMapping(PathSpec pathSpec, String servletName, String pathInContext)
```
Comment (janbartel) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java:47]: Need a comment in here about the purpose of this class, and particularly how it is used to model both mapping via a path, but ALSO mapping via just a name. In fact, I don't like the name of this class containing the word "path" if path has nothing to do with it.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 13]
```diff
@@ -1731,6 +1689,71 @@ void destroyListener(EventListener listener)
...
+                        _servletPathMapping = new ServletPathMapping(_pathSpec, _servletHolder.getName(), _pathSpec.getPrefix());
+                        break;
+                    default:
+                        _servletPathMapping = null;
+                        break;
+                }
+            }
+            else if (_pathSpec == null)
+            {
+                // Named servlet mapping
```
Comment (janbartel) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: See my comment on the ServletPathMapping class: this comment at like 1722 is the only clue that the ServletPathMapping class can be used as a name-match only .

File: jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java (hunk 12 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java:47]: I would call it just `ServletMapping`, but that name is already taken!  Let me see if we can avoid using it at all for named dispatch....

Comment (janbartel) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java:47]: While you're at it, the ServletMapping class could do with a bit of an overhaul:  the setDefault()/isDefaul() method names I now see are confusing with the whole other meaning of "default". In the case of the ServletMapping these methods just mean whether or not the mapping originated from a webdefault.xml. Can you think of a clearer name?

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java [hunk 14]
```diff
@@ -94,54 +83,15 @@ public void setAttribute(String key, Object value)
         switch (key)
         {
             case AsyncContext.ASYNC_REQUEST_URI:
```
Comment (janbartel) [inline jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java:85]: Seems the intention is to make this immutable. Perhaps we should throw IllegalStateException if setAttribute() is called? That way we would find out where in the code it is being (incorrectly) called, rather than silently failing and being ignored.

Further thoughts: all of the subclasses of Attributes.Wrapper are immutable, see also ProxyAttributes and SslAttributes. Should the Attributes interface be changed to remove setAttribute() and clearAttributes() methods altogether?

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java [hunk 15]
```diff
@@ -94,54 +83,15 @@ public void setAttribute(String key, Object value)
...
             case AsyncContext.ASYNC_QUERY_STRING:
-                _queryString = (String)value;
-                break;
             case AsyncContext.ASYNC_MAPPING:
-                _httpServletMapping = (HttpServletMapping)value;
                 break;
             default:
                 super.setAttribute(key, value);
                 break;
         }
```
Comment (janbartel) [inline jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java:97]: Different behaviour here than ForwardAttribute and IncludeAttribute:  both of those do a remove if the value is null, but see comment above about removing setAttribute() entirely.

File: jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java (hunk 12 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java:47]: It turned out that named dispatchers were broken. Added a test for them and now no longer use a ServletPathMapping for named dispatcher.  Added some javadoc as well.

Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ServletPathMapping.java:47]: rename of isDefault done.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java (hunk 13 above)
Comment (gregw) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: fixed. see above.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java (hunk 15 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java:97]: Added comment and simplified forward/include.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java (hunk 14 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java:85]: I don't think ISE is right.   I've change to always setting the attribute on the wrapped map, which we will hide during the forward. I added comments to explain.

File: jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 16]
```diff
@@ -1925,50 +1842,53 @@ public void setAsyncAttributes()
...
-            contextPath = getContextPath();
-            servletPath = getServletPath();
-            pathInfo = getPathInfo();
-            queryString = getQueryString();
-            httpServletMapping = getHttpServletMapping();
-        }
-
         // Unwrap the _attributes to get the base attributes instance.
         Attributes baseAttributes;
         if (_attributes == null)
```
Comment (janbartel) [inline jetty-server/src/main/java/org/eclipse/jetty/server/Request.java:1847]: This whole section really needs some comments - the pattern of handling the AsyncAttributes appears to be very different to handling the Forward/IncludeAttributes that we should explain why.

File: jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 17]
```diff
@@ -2411,19 +2331,34 @@ else if (oldQueryParams == null || oldQueryParams.size() == 0)
         throw new ServletException("HttpServletRequest.upgrade() not supported in Jetty");
     }
 
-    public void setPathSpec(PathSpec pathSpec)
+    /**
```
Comment (janbartel) [inline jetty-server/src/main/java/org/eclipse/jetty/server/Request.java:2334]: These were public methods on Request, should we be removing them in a point release? Maybe we should mark them as Deprecated and just not call them.

Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/Request.java:2334]: We only used `setPathSpec(PathSpec pathSpec)` on a test case.
There's no practical way to use `Request.setPathSpec(PathSpec)` except in a testcase.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java [hunk 18]
```diff
@@ -555,29 +523,28 @@ public void doHandle(String target, Request baseRequest, HttpServletRequest requ
      * @param target Path within _context or servlet name
      * @return MappedResource to the ServletHolder.  Named servlets have a null PathSpec
```
Comment (janbartel) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHandler.java]: Return is wrong: should be returning MappedServlet

**Review by janbartel — CHANGES_REQUESTED** [review]
A few changes listed in the comments.

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java (hunk 14 above)
Comment (lachlan-roberts) [reply jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java:85]: Why set the attribute on the wrapped map, we never unwrap the AsyncAttributes so this will never be used.

File: jetty-server/src/main/java/org/eclipse/jetty/server/Request.java (hunk 16 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/Request.java:1847]: extra comments in cf0a795475d78d27743bf331b5134a85515c45e7

File: jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java (hunk 14 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/AsyncAttributes.java:85]: Current behaviour is to only set the attribute on the wrapped map for non-async attributes.  Those are used by AsyncAttributes as it passes on non-async gets to the the wrapped map.

**Review by janbartel — APPROVED** [review]
LGTM
