### PR TITLE
Issue #11296 Fix javadoc on AbstractLoginModule

### LINKED ISSUE #11296: AbstractLoginModule porting issue
**Jetty Version**
Jetty 9 to Jetty 12 migration

**Jetty Environment**
ee9

**Java Version**
Java 17

**Question**
I am trying to port our Jetty 9 application to Jetty 12, and have run into an issue with our current implementation of ``AbstractLoginModule``. Our current implemenation provides an implemenation of the ``getUserInfo()`` method, in fact that is where most of the heavy-lifting is done, but this method is missing from the current implementation.

However, the class documentation from ``AbstractLoginModule`` still references overriding this method as the work that needs to be done:
```
/**
 * AbstractLoginModule
 *
 * Abstract base class for all LoginModules. Subclasses should
 * just need to implement getUserInfo method.
 */
```
I don't understand what the current correct pattern is for using the ``AbstractLoginModule``.

The "old" ``AbstractLoginModule`` imposed this signature, however it is now missing from the class definition:
```
public UserInfo getUserInfo(String username)
```

### PR DESCRIPTION
**Pull request by janbartel**
closes #11296 

fix javadoc

### CODE REVIEW

File: jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/jaas/spi/AbstractLoginModule.java [hunk 1]
```diff
@@ -35,7 +35,8 @@
  * AbstractLoginModule
  *
  * Abstract base class for all LoginModules. Subclasses should
- * just need to implement getUserInfo method.
+ * implement getUser method, and subclass JAASUser to implement
+ * doFetchRoles method.
```
Comment (sbordet) [inline jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/jaas/spi/AbstractLoginModule.java]: Please use {@link} to refer to the methods, so that users would be able to follow the links, and we will be sure that method renaming will automatically fix the javadocs.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/jaas/spi/AbstractLoginModule.java (hunk 1 above)
Comment (janbartel) [reply jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/jaas/spi/AbstractLoginModule.java]: Done.

**Review by olamy — APPROVED** [review]
