### PR TITLE
#4877 fix PathSpec long-standing bugs and shortcomings

### LINKED ISSUE #4877: Review PathSpec classes
The current implementation of PathSpec is an abstract base class with mutable protected fields.
PathSpec itself is immutable once constructed, so it would be best if the fields themselves were final and private.  Perhaps the class should just be an interface?

### PR DESCRIPTION
**Pull request by lorban**
A test failure in 10.0.x uncovered some long-standing bugs and hairy problems.

 - `PathMappings.remove()` lacked a if-null check that made it throw when a `UriTemplatePathSpec` with a group of type `EXACT`, `PREFIX_GLOB` or `SUFFIX_GLOB` was removed.
 - The `Comparable.compareTo()` and `Object.equals()` could disagree when their declaration was the same but not their group or specLength. 

I've added to the javadoc of `PathSpec` that `equals` and `hashcode` have to be implemented and overridden `equals()` in each of the `PathSpec` implementations by basically doing a `return compareTo(other) == 0` which makes `equals()` and `compareTo()` at peace.

I believe I didn't break the existing behavior in any way by doing so but I'd appreciate some reviews, especially from @joakime as he changed the `UriTemplatePathSpec.compareTo()` implementation.

### CODE REVIEW

File: jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java [hunk 1]
```diff
@@ -193,4 +194,21 @@ public boolean matches(final String path)
             return getMatcher(path).matches();
         }
     }
+
+    @Override
+    public boolean equals(Object o)
```
Comment (lachlan-roberts) [inline jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java]: This code is duplicated 3 times, why don't we have a simple base class like `AbstractPathSpec`, which could implement this and also maybe `compareTo` and `toString`, and then we could reduce the code duplication.

I made some similar changes like this in my branch at `jetty-9.4.x-4877-PathSpecEquals` if you want to take a look
https://github.com/eclipse/jetty.project/blob/c6a40782571a08ae2410c165bfc58da5976432c8/jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/AbstractPathSpec.java#L23-L60

Comment (gregw) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java]: @lachlan-roberts because I asked him to make all the fields final. Hard to do the abstract and the final fields without more complication.

Comment (lachlan-roberts) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java]: @gregw Take a look at the file I linked, it doesn't prevent having any final fields in the implementations of the abstract class.

Comment (lorban) [reply jetty-http/src/main/java/org/eclipse/jetty/http/pathmap/RegexPathSpec.java]: I like the idea of this abstract class that provides implementations for `toString`, `equals`, `hashcode` and `compareTo`, especially if I can get rid of the  `PathSpec.compareTo` default implementation. But I'd make `equals` and `hashcode` final then to make sure `compareTo` and `equals` always agree. See [my comment](https://github.com/eclipse/jetty.project/issues/4877#issuecomment-638171053) for context.

**Comment by lachlan-roberts** [comment]
@lorban looks like you have some checkstyle issues

**Review by lachlan-roberts — APPROVED** [review]
LGTM

**Review by joakime — APPROVED** [review]
LGTM
