### PR TITLE
Issue #13284 - improve error handling for OpenID Connect

### LINKED ISSUE #13284: jetty-openid library swallows provider errors when getting auth code
**Jetty version(s)**
12.0.22

**Jetty Environment**
jetty-12 jetty-openid

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30, mixed mode, sharing)

**OS type/version**
Windows 10.

**Description**
Errors from the open id provider are swallowed and replaced with an exception saying "new AuthenticationException("no id_token")"

1. jetty-openid makes a webservices call to the provider (eg. microsoft) to get an auth code.
    org.eclipse.jetty.security.openid.OpenIdCredentials.redeemAuthCode()

2. If the provider returns an error the response looks like eg.
`
{
	"trace_id" -> "<some trace id>"
	"error_description" -> "<error description>"
	"correlation_id" -> "<correlation id>"
	"error_codes" -> {Object[1]@8736} 
	"error" -> "invalid_grant"
	"error_uri" -> "https://login.microsoftonline.com/error?code=70008"
	"timestamp" -> "2025-06-20 06:21:23Z"
}
`

3. Then there's a check for an "id_token" in the response and an exception thrown
`
String idToken = (String)response.get("id_token");
if (idToken == null)
    throw new AuthenticationException("no id_token");
`

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #13284

This PR introduces error handling for
- Authentication Error Response (section 3.1.2.6)
- Token Error Response (section 3.1.3.4)

see https://openid.net/specs/openid-connect-core-1_0.html

Previously we only redirected to the `OpenIdAuthenticator` error page with a generic message in the `error_description_jetty` query parameter.

This message has been improved in these two cases. We also now include query parameters for `error`, `error_description`, and `error_uri` which are defined in these sections.

### CODE REVIEW

File: jetty-core/jetty-openid/src/test/java/org/eclipse/jetty/security/openid/OpenIdErrorResponseTest.java [hunk 1]
```diff
@@ -0,0 +1,244 @@
...
+
+        _client = new HttpClient();
+        _client.start();
+    }
+
+    @AfterEach
+    public void stop() throws Exception
+    {
+        _provider.stop();
+        _server.stop();
```
Comment (sbordet) [inline jetty-core/jetty-openid/src/test/java/org/eclipse/jetty/security/openid/OpenIdErrorResponseTest.java:105]: Also stop the client?

File: jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/AuthenticationState.java [hunk 2]
```diff
@@ -46,6 +46,25 @@ static AuthenticationState getAuthenticationState(Request request)
         return state instanceof AuthenticationState authenticationState ? authenticationState : null;
     }
 
+    /**
+     * Get the authentication state of a request resolving any {@link Deferred} authentication.
+     * @param request The request to query.
+     * @return The authentication state of the request or null if none or {@link Deferred} authentication could not be resolved.
+     */
+    static AuthenticationState getUndeferredAuthentication(Request request)
```
Comment (sbordet) [inline jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/AuthenticationState.java]:
```suggestion
    static AuthenticationState getUndeferredAuthenticationState(Request request)
```

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java [hunk 3]
```diff
@@ -257,17 +257,7 @@ public AuthenticationState getAuthentication()
 
     private AuthenticationState getUndeferredAuthentication()
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java]: Perhaps this also should be renamed to `getUndeferredAuthenticationState()`?

Are these other cases that miss the `State` suffix?

**Review by sbordet — CHANGES_REQUESTED** [review]
Same review comments also apply to EE9.

File: jetty-core/jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java [hunk 4]
```diff
@@ -80,7 +80,12 @@ public Map<String, Object> getResponse()
         return response;
     }
 
-    public void redeemAuthCode(OpenIdConfiguration configuration) throws Exception
+    public Fields getErrorFields()
```
Comment (gregw) [inline jetty-core/jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java:89]: javadoc

File: jetty-core/jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java [hunk 5]
```diff
@@ -80,7 +80,12 @@ public Map<String, Object> getResponse()
...
+    {
+        return errorFields;
+    }
+
+    public void redeemAuthCode(OpenIdConfiguration configuration)
```
Comment (gregw) [inline jetty-core/jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java:99]: javadoc

**Review by gregw — DISMISSED** [review]
LGTM, but it needs a bit more javadoc

File: jetty-core/jetty-openid/src/test/java/org/eclipse/jetty/security/openid/OpenIdErrorResponseTest.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-openid/src/test/java/org/eclipse/jetty/security/openid/OpenIdErrorResponseTest.java:105]: done

File: jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/AuthenticationState.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/AuthenticationState.java]: done

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java]: I think I should leave this one as is so it matches the public API directly above.

File: jetty-core/jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java (hunk 4 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java:89]: done

File: jetty-core/jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java (hunk 5 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdCredentials.java:99]: done

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java (hunk 3 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java]: This is a private method, and the public API should either remain as-is, or be deprecated with a new `getAuthenticationState()` method.

File: tests/jetty-test-common/src/main/java/org/eclipse/jetty/tests/OpenIdProvider.java [hunk 6]
```diff
@@ -199,38 +211,37 @@ protected void doGetAuthEndpoint(Request request, Response response, Callback ca
...
             return;
         }
 
-        String scopeString = parameters.getValue("scope");
-        List<String> scopes = (scopeString == null) ? Collections.emptyList() : Arrays.asList(scopeString.split(" "));
-        if (!scopes.contains("openid"))
+        if (!clientId.equals(parameters.getValue("client_id")))
         {
-            Response.writeError(request, response, callback, HttpStatus.FORBIDDEN_403, "no openid scope");
+            sendError(response, callback, redirectUri, state, "invalid_request_object", "invalid client_id", "example.com/client_id");
```
Comment (sbordet) [inline tests/jetty-test-common/src/main/java/org/eclipse/jetty/tests/OpenIdProvider.java:230]: `example.com`?
Is this mandated by OpenID, or a leftover?

File: tests/jetty-test-common/src/main/java/org/eclipse/jetty/tests/OpenIdProvider.java [hunk 7]
```diff
@@ -313,14 +345,25 @@ protected void doTokenEndpoint(Request request, Response response, Callback call
             !"authorization_code".equals(parameters.getValue("grant_type")) ||
             code == null)
         {
-            Response.writeError(request, response, callback, HttpStatus.FORBIDDEN_403, "bad auth request");
+            response.setStatus(HttpStatus.BAD_REQUEST_400);
+            String responseContent = "{" +
+                "\"error\": \"invalid_request\"," +
+                "\"error_description\": \"bad request description\"," +
+                "\"error_uri\":\"https://example.com/description\"" +
```
Comment (sbordet) [inline tests/jetty-test-common/src/main/java/org/eclipse/jetty/tests/OpenIdProvider.java:352]: `example.com`?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: tests/jetty-test-common/src/main/java/org/eclipse/jetty/tests/OpenIdProvider.java (hunk 6 above)
Comment (lachlan-roberts) [reply tests/jetty-test-common/src/main/java/org/eclipse/jetty/tests/OpenIdProvider.java:230]: This `OpenIdProvider` is just a testing utility, so that we can test our implementation locally without relying on an external identity provider.

So `example.com/client_id` is just a dummy value representing the error_uri field.

**Review by sbordet — APPROVED** [review]
