### PR TITLE
Fix flaky assertions in `ConnectionPoolTest`

### LINKED ISSUE #12327: `ConnectionPoolTest.testPreCreateConnections` is flaky
**Jetty version(s)**
12.1.x

**Description**
`org.eclipse.jetty.test.client.transport.ConnectionPoolTest.testPreCreateConnections` sometimes fails with:

```
java.lang.AssertionError: 

Expected: not an empty collection
     but: was <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.test.client.transport.ConnectionPoolTest.testPreCreateConnections(ConnectionPoolTest.java:65)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
        ...
```

See: https://jenkins.webtide.net/job/jetty.project/job/jetty-12.1.x/188/testReport/junit/org.eclipse.jetty.test.client.transport/ConnectionPoolTest/Parallel_Stage___Build___Test___JDK23___testPreCreateConnections_Transport__1__HTTP/

### PR DESCRIPTION
**Pull request by lorban**
Fixes #12327

### CODE REVIEW

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ConnectionPoolTest.java [hunk 1]
```diff
@@ -54,15 +55,25 @@ public void testPreCreateConnections(Transport transport) throws Exception
...
-            case H2C, H2 -> serverConnections.filter(HTTP2ServerConnection.class);
-            case H3 -> serverConnections.filter(ServerQuicConnection.class);
-            case FCGI -> serverConnections.filter(ServerFCGIConnection.class);
-        };
-        assertThat(connections, not(empty()));
+            switch (transport)
+            {
+                case HTTP, HTTPS:
+                    assertThat(serverConnections.filter(HttpConnection.class).size(), is(maxConnectionsPerDestination));
+                    break;
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ConnectionPoolTest.java]: Boo! Using old-style `switch` with `:` and `break` 🤣 
Please use new style.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ConnectionPoolTest.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ConnectionPoolTest.java]: Done.

**Review by sbordet — APPROVED** [review]

**Comment by sbordet** [comment]
@lorban should this PR be done in 12.0.x?
