### PR TITLE
Issue #12906 - URIUtil.correctURI() should be able to handle `file:/`

### LINKED ISSUE #12906: URIUtil#correctURI throws StringIndexOutOfBoundsException - Jetty 12 regression
**Jetty version(s)**
Jetty 12.0.17

**Jetty Environment**
EE 10

**Java version/vendor** `(use: java -version)`
JDK 22

**Description**

```
Caused by: java.lang.StringIndexOutOfBoundsException: Index 6 out of bounds for length 6
	... skipped JDK internals
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.base/java.lang.String.checkIndex(String.java:4832) ~[?:?]
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46) ~[?:?]
	at java.base/java.lang.String.charAt(String.java:1555) ~[?:?]
	at org.eclipse.jetty.util.URIUtil.correctURI(URIUtil.java:1783) ~[jetty-util-12.0.17.jar:12.0.17]
	at org.eclipse.jetty.util.URIUtil.addPath(URIUtil.java:1676) ~[jetty-util-12.0.17.jar:12.0.17]
	at org.eclipse.jetty.util.resource.PathResource.resolve(PathResource.java:293) ~[jetty-util-12.0.17.jar:12.0.17]
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.getResource(ServletContextHandler.java:776) ~[jetty-ee10-servlet-12.0.17.jar:12.0.17]
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletContextApi.getResource(ServletContextHandler.java:2868) ~[jetty-ee10-servlet-12.0.17.jar:12.0.17]
	at org.springframework.web.context.support.ServletContextResource.exists(ServletContextResource.java:105) ~[spring-web-6.1.17.jar:6.1.17]
	at org.springframework.beans.propertyeditors.PathEditor.setAsText(PathEditor.java:106) ~[spring-beans-6.1.17.jar:6.1.17]
	at 
        ... skipped Spring internals
	at org.springframework.beans.AbstractNestablePropertyAccessor.convertForProperty(AbstractNestablePropertyAccessor.java:609) ~[spring-beans-6.1.17.jar:6.1.17]
```

**How to reproduce?**

The exception happens when we set a file path without a 'file:' prefix in Spring XML descriptor.
This triggers the following path:
```
        // Correct any bad `file:/path` usages, and
        // force encoding of characters that must be encoded (such as unicode)
        // for the base
        String base = correctURI(uri).toASCIIString();
```
in Jetty. 

The same setup and values work with Jetty 11; this was noticed during migration from Jetty 11 to 12.

### PR DESCRIPTION
**Pull request by joakime**
Fixing bad corner case of bad input `file:/`.

Note: the URIs `file://` and `file:` are not able to be created, so do not suffer from issues.

```
|  Welcome to JShell -- Version 17.0.11
|  For an introduction type: /help intro

jshell> var u = URI.create("file://")
|  Exception java.lang.IllegalArgumentException: Expected authority at index 7: file://
|        at URI.create (URI.java:906)
|        at do_it$Aux (#1:1)
|        at (#1:1)
|  Caused by: java.net.URISyntaxException: Expected authority at index 7: file://
|        at URI$Parser.fail (URI.java:2976)
|        at URI$Parser.failExpecting (URI.java:2982)
|        at URI$Parser.parseHierarchical (URI.java:3226)
|        at URI$Parser.parse (URI.java:3177)
|        at URI.<init> (URI.java:623)
|        at URI.create (URI.java:904)
|        ...

jshell> var u2 = URI.create("file:")
|  Exception java.lang.IllegalArgumentException: Expected scheme-specific part at index 5: file:
|        at URI.create (URI.java:906)
|        at do_it$Aux (#2:1)
|        at (#2:1)
|  Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 5: file:
|        at URI$Parser.fail (URI.java:2976)
|        at URI$Parser.failExpecting (URI.java:2982)
|        at URI$Parser.parse (URI.java:3182)
|        at URI.<init> (URI.java:623)
|        at URI.create (URI.java:904)
|        ...
```

Fixes #12906

### CODE REVIEW

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 1]
```diff
@@ -1779,6 +1779,9 @@ public static URI correctURI(URI uri)
         if (colon < 0)
             return uri; // path portion not found
 
+        if ((colon + 2) == rawURI.length())
```
Comment (Spikhalskiy) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java:1782]: Maybe >=? It looks like this method shouldn't throw, even on 'file:' or something malformed like this. Or if it throws, it should throw `MalformedURLException`. See `ServletContextHandler#getResource` contract. Its implementation is calling this method without exception catching.

Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java:1782]: this is just testing for the exact input of `file:/`.

or said a different way, if there is nothing after the `file:/` then there's nothing left to evaluate / get from the input, so just produce an output.

**Review by gregw — APPROVED** [review]
