### PR TITLE
Addendum to #12927 for #12916.

### LINKED ISSUE #12916: Bad example in JavaDoc of InputStreamResponseListener
**Jetty version(s)**
12.0.17

**Jetty Environment**
core (client)

**Java version/vendor** `(use: java -version)`
OpenJDK 64-Bit Server VM Temurin-21.0.6+7 (build 21.0.6+7-LTS, mixed mode, sharing)

**OS type/version**
Windows 11

**Description**
The class documentation of `InputStreamResponseListener` includes the following example to demonstrate its usage:

```java
InputStreamResponseListener listener = new InputStreamResponseListener();
client.newRequest(...).send(listener);

// Wait for the response headers to arrive
Response response = listener.get(5, TimeUnit.SECONDS);
if (response.getStatus() == 200)
{
    // Obtain the input stream on the response content
    try (InputStream input = listener.getInputStream())
    {
        // Read the response content
    }
}
```

This works but will leak resources if the status is not 200, because then we never read the content. Therefore, the response stays open forever, or at least until some timeout occurs.

It would be better to abort the response if we don't read it:

```java
Response response = listener.get(5, TimeUnit.SECONDS);
if (response.getStatus() == 200)
{
    // ...
}
else
    response.abort(new CancellationException());
```

To make this easier, you could consider making the whole listener `AutoCloseable`, not just the input stream, so one could use try-with-resources on the listener to make sure the response is completed at the end:

```java
try (InputStreamResponseListener listener = new InputStreamResponseListener())
{
    client.newRequest(...).send(listener);
    Response response = listener.get(5, TimeUnit.SECONDS);
    if (response.getStatus() == 200)
    {
        // ...
    }
}
```

### PR DESCRIPTION
**Pull request by sbordet**
* Fixed InputStreamResponseListener.close() to properly flip the `closed` field. 
* Made InputStreamResponseListener.close() and InputStreamResponseListener.Input.close() call the same code. 
* Fixed buffer leaking by releasing the network buffer upon connection close in HTTP and FCGI.

### CODE REVIEW

**Review by gregw — DISMISSED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 1]
```diff
@@ -529,12 +572,6 @@ public int read()
 
     @ParameterizedTest
     @MethodSource("transports")
-    @Tag("DisableLeakTracking:client:HTTP")
-    @Tag("DisableLeakTracking:client:HTTPS")
-    @Tag("DisableLeakTracking:client:H3")
-    @Tag("DisableLeakTracking:client:FCGI")
-    @Tag("DisableLeakTracking:client:UNIX_DOMAIN")
-    @Tag("flaky")
     public void testDownloadWithCloseBeforeContent(Transport transport) throws Exception
```
Comment (lorban) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java:592]: `@Tag("DisableLeakTracking:client:H3")` should stay.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 2]
```diff
@@ -495,7 +539,6 @@ public void testInputStreamResponseListenerFailedBeforeResponse(Transport transp
 
     @ParameterizedTest
     @MethodSource("transports")
-    @Tag("DisableLeakTracking:client")
```
Comment (lorban) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: This should be replaced with `@Tag("DisableLeakTracking:client:H3")`

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 3]
```diff
@@ -363,7 +412,6 @@ public void onContent(Response response, Content.Chunk chunk, Runnable demander)
...
```
Comment (lorban) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: This should be replaced with @Tag("DisableLeakTracking:client:H3")

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/internal/HttpReceiverOverHTTP.java [hunk 4]
```diff
@@ -294,7 +295,6 @@ else if (read == 0)
         {
             if (LOG.isDebugEnabled())
                 LOG.debug("Error processing {} in {}", endPoint, this, x);
-            releaseNetworkBuffer();
```
Comment (lorban) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/internal/HttpReceiverOverHTTP.java]: This certainly deserves a comment that explains `close()` is going to take care of releasing the buffer but with a thread protection thanks to a CAS.

**Review by lorban — APPROVED** [review]
