### PR TITLE
Fix ssl and h2 buffer leak

### LINKED ISSUE #12862: `HttpClientDemandTest.testGZippedResponseContentWithAsyncDemand()` shows the H2 client can leak buffers
**Jetty version(s)**
12.1.x

**Description**
`HttpClientDemandTest.testGZippedResponseContentWithAsyncDemand()` sometimes fails on the client's leak tracking assertion, indicating the H2 client is leaking buffers:

```
Assertion condition defined as a Lambda expression in org.eclipse.jetty.test.client.transport.AbstractTest Leaks: TrackedBuffer@2f2c2aeb of 16709 bytes on 2025-03-04T10:36:28.048068880Z wrapping 1 acquired at java.lang.Throwable: client-5843
 at org.eclipse.jetty.io.ArrayByteBufferPool$Tracking$TrackedBuffer.<init>(ArrayByteBufferPool.java:969)
 at org.eclipse.jetty.io.ArrayByteBufferPool$Tracking.acquire(ArrayByteBufferPool.java:936)
 at org.eclipse.jetty.io.ssl.SslConnection.acquireEncryptedInput(SslConnection.java:331)
 at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.fill(SslConnection.java:695)
 at org.eclipse.jetty.http2.HTTP2Connection.fill(HTTP2Connection.java:182)
 at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:398)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:514)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:258)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
 at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:231)
 at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:165)
 at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:495)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
 at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.onFillable(SslConnection.java:576)
 at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:391)
 at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:150)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
 at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:54)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:480)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:443)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
 at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
 at java.base/java.lang.Thread.run(Thread.java:1575)

0 retain(s)

0 release(s)

0 over-release(s)

Expected: is <0>
     but: was <1> within 5 seconds.Client Leaks: 
```

See: https://jenkins.webtide.net/job/jetty.project/job/jetty-12.1.x/482/testReport/junit/org.eclipse.jetty.test.client.transport/HttpClientDemandTest/Parallel_Stage___Build___Test___JDK23___testGZippedResponseContentWithAsyncDemand_TransportType__4__H2/

### PR DESCRIPTION
**Pull request by lorban**
Fixes #12862

Also improve `HTTP2Connection` to make it fulfill the _hold no buffer when at rest_ doctrine.

See https://github.com/jetty/jetty.project/pull/12896 for the 10/11 version of the fix.

### CODE REVIEW

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java [hunk 1]
```diff
@@ -420,25 +433,58 @@ else if (filled == 0)
             }
             finally
             {
-                if (networkBuffer.isRetained() && !shutdown)
+                try (AutoLock ignore = lock.lock())
                 {
-                    holdBuffer(networkBuffer);
+                    if (networkBuffer.isRetained() && this.heldBuffer != RELEASE_MARKER && !shutdown)
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java]: Need some javadoc and/or comments to explain the important aspects of these changes?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java]: I've added some comments explaining the mechanism.

**Review by gregw — APPROVED** [review]
