### PR TITLE
Fixes #11892 - mtls not working with http/3.

### LINKED ISSUE #11892: mtls not working with http/3
**Jetty version(s)**
Jetty 12.0.10

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode)

**OS type/version**
Mac OS Sonoma 14.5

**Description**

The server is started on http/2 and http/3 on the same port. http/2 works perfectly fine where client certificate is available at X509Certificate[] certs = (X509Certificate[]) request.getAttribute("jakarta.servlet.request.X509Certificate");
when the request is made over http/3, request attributes are null.

**How to reproduce?**
Start a server on http/3 and set needClientAuth(true)

### PR DESCRIPTION
**Pull request by sbordet**
The client certificate is now exposed in QuicheConnection, so that it can be returned by QuicStreamEndPoint.getSslSessionData().

Not much else is exposed by Quiche, so not much else that we can provide to applications, for example no TLS session id, no cipher suite, etc.

### CODE REVIEW

**Review by lorban — CHANGES_REQUESTED** [review]
You forgot to modify `ForeignQuicheConnection`. It already has a `getPeerCertificate` implementation, but it lacks the `@Override` annotation and for some reason, it's not the chosen binding even when running the tests with JDK 22.

**Review by lorban — DISMISSED** [review]

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicSession.java [hunk 1]
```diff
@@ -423,6 +427,23 @@ private void finishOutwardClose(Throwable failure)
         }
     }
 
+    public X509Certificate[] getPeerCertificates()
```
Comment (gregw) [inline jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicSession.java:438]: Maybe javadoc that only the top/last/single certificate will be returned.

**Review by gregw — DISMISSED** [review]
OK, but javadoc the Quic limitation
