### PR TITLE
Servlet 61 cookie fixes

### LINKED ISSUE #11934: servlet 6.1 tck cookie test errors
**Jetty version(s)**
jetty-12.1.x

### Failing Test `servlet.tck.api.jakarta_servlet_http.cookie.CookieTests.getValueQuotedTest`
This test sends a cookie from the client to the server that is constructed like so: 

```java
"Cookie: name1=\"value1\"; Domain=" + _hostname + "; Path=/servlet_jsh_cookie_web"
```

The test expects that the value of the `name1` cookie is interpreted by the server as `"value1"`, ie that double quotes are retained.

### Failing Test ` servlet.tck.api.jakarta_servlet_http.cookie.CookieTests.setMaxAgeZeroTest`

The test creates a `Cookie` and calls `setMaxAge(0)` on it. The test expects that the `Max-Age` field will be missing on the `Set-Cookie` response header, but we are sending `Max-Age=0`. Looking at RFC6265 it does seem that `Max-Age` should never be `0`:

```
max-age-av        = "Max-Age=" non-zero-digit *DIGIT
```
### Failing Test ` servlet.tck.api.jakarta_servlet_http.cookie.CookieTests.setPartitionedTest`

The test creates a `Cookie` and calls `setAttribute("Partitioned", "")`  The test expects that a `Set-Cookie` will contain `Partitioned`, however, we only send `Partitioned` iff `setAttribute("Partitioned", "true")` was called.

### PR DESCRIPTION
**Pull request by gregw**
Fix #11934 Servlet 6.1 cookies:
 + don't send a max-age=0
 + treat any non null non "false" attribute value as a true
 + don't send = for empty cookie attribute values
 + added compliance mode MAINTAIN_QUOTES to keep the quotes as part of the cookie value.  Added mode RFC6265_QUOTED that includes this violation

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java [hunk 1]
```diff
@@ -276,7 +279,16 @@ else if (_complianceMode.allows(INVALID_COOKIES))
                 case IN_QUOTED_VALUE:
                     if (c == '"')
                     {
-                        value = string.toString();
+                        if (_complianceMode.allows(MAINTAIN_QUOTES))
+                        {
+                            string.append(c);
+                            value = string.toString();
+                            reportComplianceViolation(MAINTAIN_QUOTES, value);
```
Comment (janbartel) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java]: It's a little odd that we are going to log as a violation the presence of quoted values, when in fact that's exactly what the spec allows.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java [hunk 2]
```diff
@@ -761,37 +764,54 @@ public PushBuilder newPushBuilder()
...
             HttpHeader header = field.getHeader();
             if (header == HttpHeader.SET_COOKIE || header == HttpHeader.SET_COOKIE2)
             {
-                HttpCookie httpCookie;
-                if (field instanceof HttpCookieUtils.SetCookieHttpField set)
-                    httpCookie = set.getHttpCookie();
-                else
-                    httpCookie = SET_COOKIE_PARSER.parse(field.getValue());
-                if (httpCookie == null || httpCookie.isExpired())
+                HttpCookie httpCookie = (field instanceof HttpCookieUtils.SetCookieHttpField set)
```
Comment (janbartel) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java:778]: I don't think we have a test for the PushBuilder with expired cookies?

**Review by janbartel — APPROVED** [review]
Couple of comments, but overall +1.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java (hunk 2 above)
Comment (gregw) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java:778]: we do now!

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/RFC6265CookieParser.java]: I've switched it around

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/RFC6265CookieParserTest.java [hunk 3]
```diff
@@ -296,6 +297,20 @@ public void testExcessiveSemicolons()
...
+    {
+        String rawCookie = "A=\"quotedValue\"";
+
+        Cookie[] cookies = parseCookieHeaders(CookieCompliance.RFC6265, rawCookie);
+        assertThat("Cookies.length", cookies.length, is(1));
+        assertCookie("Cookies[0]", cookies[0], "A", "quotedValue", 0, null);
+
+        cookies = parseCookieHeaders(CookieCompliance.RFC6265_QUOTED, rawCookie);
+        assertThat("Cookies.length", cookies.length, is(1));
+        assertCookie("Cookies[0]", cookies[0], "A", "\"quotedValue\"", 0, null);
```
Comment (janbartel) [inline jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/RFC6265CookieParserTest.java:311]: Plus `RFC6265_STRICT` ?

**Review by janbartel — APPROVED** [review]

**Review by janbartel — APPROVED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionMetaData.java [hunk 4]
```diff
@@ -52,9 +52,7 @@ default boolean isSecure()
 
     /**
      * @return whether the functionality of pushing resources is supported
-     * @deprecated in favour of 103 Early Hints
      */
-    @Deprecated(since = "12.0.1")
     default boolean isPushSupported()
```
Comment (joakime) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionMetaData.java:56]: Unrelated change??

**Review by joakime — APPROVED** [review]
The change to ConnectionMetaData.isPushSupported() deprecation seems odd, but ultimately harmless.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionMetaData.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ConnectionMetaData.java:56]: Note entirely. I was fixing the push cookie handling and realized this core method should not be deprecated
