### PR TITLE
jetty-server exception stack traces

### LINKED ISSUE #2424: ServerTimeoutsTest.testBlockingTimeoutWithSlowRead throws ReadPendingException [HTTPS]
The test does not fail, but it throws `ReadPendingException`, which should not happen.
Some times, the test hangs forever.
DEBUG logs attached.
[2424.txt](https://github.com/eclipse/jetty.project/files/1891614/2424.txt)

### LINKED ISSUE #2542: Exception from passing test SslSelectChannelTimeoutTest.testMaxIdleNothingSent()
```
[AdvancedRunner] Running org.eclipse.jetty.server.ssl.SslSelectChannelTimeoutTest.testMaxIdleNothingSent()
Running org.eclipse.jetty.server.ssl.SslSelectChannelTimeoutTest.testMaxIdleNothingSent()
2018-05-16 14:46:41.022:INFO:oejs.Server:main: jetty-9.4.11-SNAPSHOT; built: 2018-05-16T04:43:12.635Z; git: 820b5752d7207fc0ed5294d13887780f7b28a48c; jvm 9.0.1+11
2018-05-16 14:46:41.026:INFO:oejus.SslContextFactory:main: x509=X509@6b4a2887(jetty,h=[jetty.eclipse.org],w=[]) for SslContextFactory@23b087c3[provider=null,keyStore=file:///usr/local/home/gregw/src/jetty-9.4.x/jetty-server/src/test/resources/keystore,trustStore=file:///usr/local/home/gregw/src/jetty-9.4.x/jetty-server/src/test/resources/keystore]
2018-05-16 14:46:41.027:INFO:oejus.SslContextFactory:main: x509=X509@237c8718(mykey,h=[],w=[]) for SslContextFactory@23b087c3[provider=null,keyStore=file:///usr/local/home/gregw/src/jetty-9.4.x/jetty-server/src/test/resources/keystore,trustStore=file:///usr/local/home/gregw/src/jetty-9.4.x/jetty-server/src/test/resources/keystore]
2018-05-16 14:46:41.030:INFO:oejs.AbstractConnector:main: Started ServerConnector@325e03b{SSL,[ssl, http/1.1]}{0.0.0.0:41871}
2018-05-16 14:46:41.032:INFO:oejs.Server:main: Started @35514ms
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1058)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.bytesInCompletePacket(SSLSocketImpl.java:907)
	at java.base/sun.security.ssl.AppInputStream.read(AppInputStream.java:144)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at org.eclipse.jetty.util.IO.copy(IO.java:225)
	at org.eclipse.jetty.util.IO.copy(IO.java:135)
	at org.eclipse.jetty.util.IO.toString(IO.java:318)
	at org.eclipse.jetty.util.IO.toString(IO.java:290)
	at org.eclipse.jetty.server.ConnectorTimeoutTest.testMaxIdleNothingSent(ConnectorTimeoutTest.java:636)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:156)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1031)
	... 25 more
2018-05-16 14:46:43.439:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@325e03b{SSL,[ssl, http/1.1]}{0.0.0.0:0}

```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
fixes some exception stack traces that were being printed out while running the jetty-server tests

closes #2542 
closes #2424

### CODE REVIEW

File: jetty-server/src/test/java/org/eclipse/jetty/server/ConnectorTimeoutTest.java [hunk 1]
```diff
@@ -610,11 +611,17 @@ public void testMaxIdleNoRequest() throws Exception
         }
         catch(SSLException e)
         {
-            e.printStackTrace();
+            if(Log.getLog().isDebugEnabled())
+                Log.getLog().debug(e);
+            else
+                Log.getLog().info(e.getMessage());
```
Comment (sbordet) [inline jetty-server/src/test/java/org/eclipse/jetty/server/ConnectorTimeoutTest.java]: Replace here and in the hunks below with a proper log instance allocated in the test class:

```java
public abstract class ConnectorTimeoutTest extends HttpServerTestFixture
{
    protected static final Logger LOG = Log.getLogger(ConnectorTimeoutTest.class);
    ...
}
```

and then use the `LOG` instance instead of `Log.getLog()`.

File: jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java [hunk 2]
```diff
@@ -134,7 +134,7 @@ private String getResponse(String request) throws IOException, InterruptedExcept
     @Test
     public void testHttpWriteIdleTimeout() throws Exception
     {
-        _httpConfiguration.setBlockingTimeout(500);
+        _httpConfiguration.setIdleTimeout(500);
```
Comment (sbordet) [inline jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java]: Good change.

File: jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java [hunk 3]
```diff
@@ -134,7 +135,7 @@ private String getResponse(String request) throws IOException, InterruptedExcept
     @Test
     public void testHttpWriteIdleTimeout() throws Exception
     {
-        _httpConfiguration.setIdleTimeout(500);
+        _httpConfiguration.setBlockingTimeout(500);
```
Comment (sbordet) [inline jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java]: @lachlan-roberts why did you revert this to be a blocking timeout ? Your change (using `setIdleTimeout()`) was correct.

File: jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java [hunk 4]
```diff
@@ -195,7 +196,7 @@ protected void doNonErrorHandle(String target, Request baseRequest, HttpServletR
             }
         });
     
-        try (StacklessLogging scope = new StacklessLogging(HttpChannel.class))
+        try (StacklessLogging scope = new StacklessLogging(HttpChannel.class, QueuedThreadPool.class))
```
[the remark this answers is not in the document]
Comment (sbordet) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java]: Nope.

Keep `setIdleTimeout()` above, and remove this try-with-resources, it's not needed.

File: jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java]: @sbordet 
you said this on the [issue](https://github.com/eclipse/jetty.project/issues/2424) that `"the test is testing the blocking timeout, so can't be replaced with an idle timeout - although it does fix the ReadPendingException."`

Comment (sbordet) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java]: @lachlan-roberts that was `ServerTimeoutsTest`, this is `ServerConnectorTimeoutTest`.
Plus the method name really tells that's an idle timeout we want to test.

Comment (lachlan-roberts) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java]: i guess you thought i was talking about `ServerTimeoutsTest.testBlockingTimeoutWithSlowRead` which was the issue title but was referring to the error log Joakime posted which was this test.

Comment (lachlan-roberts) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ServerConnectorTimeoutTest.java]: ill change it back

**Comment by gregw** [comment]
@lachlan-roberts can you merge from jetty-9.4.x HEAD to get the fixed tests that broke the build
