### PR TITLE
Fix #6400 QueuedThreadPool always interrupts threads in stop

### LINKED ISSUE #6400: QueuedThreadPool interrupts pool threads when stopped with zero timeout
**Jetty version(s)**

9.4.42

**Java version/vendor** `(use: java -version)`

openjdk version "1.8.0_282"

**OS type/version**

macOS 10.15

**Description**

When `QueuedThreadPool` is configured with a stop timeout of zero it skips trying to stop its threads. This leaves them running until they eventually end after 60s when their idle timeout elapses.

**How to reproduce?**

Running the following code will result in the JVM taking ~60 seconds to exit:

```java
import org.eclipse.jetty.util.thread.QueuedThreadPool;

public class QueuedThreadPoolProblem {

	public static void main(String[] args) throws Exception {
		QueuedThreadPool threadPool = new QueuedThreadPool(2);
		threadPool.setStopTimeout(0);
		threadPool.start();
		threadPool.stop();
	}

}
```

Increasing the timeout to 1ms allows the JVM to exit nigh-on immediately:

```java
import org.eclipse.jetty.util.thread.QueuedThreadPool;

public class QueuedThreadPoolProblem {

	public static void main(String[] args) throws Exception {
		QueuedThreadPool threadPool = new QueuedThreadPool(2);
		threadPool.setStopTimeout(1);
		threadPool.start();
		threadPool.stop();
	}

}
```

### PR DESCRIPTION
**Pull request by gregw**
Fixes #6400 Even if there is no timeout, always interrupt pool threads to attempt to stop them.

### CODE REVIEW

**Comment by gregw** [comment]
I think it was an oversite that we don't at least interrupt threads.   We really wanted to stop threads in that situation, but that API is deprecated.

File: jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 1]
```diff
@@ -234,30 +234,29 @@ protected void doStop() throws Exception
...
-            for (int i = 0; i < threads; ++i)
-            {
-                jobs.offer(NOOP);
-            }
 
-            // try to let jobs complete naturally for half our stop time
-            joinThreads(System.nanoTime() + TimeUnit.MILLISECONDS.toNanos(timeout) / 2);
+        // Fill the job queue with noop jobs to wakeup idle threads.
+        for (int i = 0; i < threads; ++i)
+            jobs.offer(NOOP);
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java:240]: Since we are reviewing this, I don't think this loop guarantees that all threads are woken up.
On a single core, it may be that a single thread wakes up and consumes all the NOOP jobs in the queue.

File: jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 2]
```diff
@@ -234,30 +234,29 @@ protected void doStop() throws Exception
...
-                thread.interrupt();
-            }
+        // If we still have threads running, get a bit more aggressive
+        // interrupt remaining threads
+        for (Thread thread : _threads)
+        {
+            if (LOG.isDebugEnabled())
+                LOG.debug("Interrupting {}", thread);
+            thread.interrupt();
+        }
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java:254]: Now it may be possible that we interrupt threads immediately after submitting the NOOP jobs (or normal jobs) -- I'm not sure we want that if we want to gracefully stop (by letting the current tasks finish).

Also, interrupting is the right thing to do, but e.g. `ReservedThreadExecutor` does not handle it well: it just loops around and goes again into `take()/poll()`.

**Comment by sbordet** [comment]
@gregw why does not QTP implements `Graceful`?

Mmmh. I know I have added review comments and I would like to improve, but I've been running in circles for a while now, and nothing seems better than what we have here 😃

File: jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 1 above)
Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java:240]: I think you are right.  The Runner used to have a `while(isRunning)` loop, so once woken it would check that state.  Now it is only checking the equivalent state only if it doesn't have a job.   So maybe we should always check the running state again?

File: jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 2 above)
Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java:254]: Ah that is a problem. The `ReservedThread#run` method does do a `while(isRunning)`, but there is an inner loop in `ReservedThread#reservedWait` that doesn't.    I'll fix that....

File: jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 1 above)
Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java:240]: Ah no, the running state is already always tested - either in addCounts or explicitly if there is no jobs.  It might be clearer to always call addCounts.... let me see...

Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java:240]: @sbordet I've pushed a refactored version that I think makes this clearer... and I am 95% sure is exactly the same logic.
@lachlan-roberts can you have a look and triple check the latest checking doesn't actually change the idle thread count logic.

File: jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 2 above)
Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java:254]: last check in fixed the inner loop of the ReservedThread

**Review by sbordet — APPROVED** [review]
