### PR TITLE
Issue #13341 - add async close for Jetty WebSocket API

### LINKED ISSUE #13341: Complete WebSocket close handshake asynchronously
**Jetty Version**

Jetty 12.0.22 

**Question**

Upon receipt of a WebSocket close frame, is it possible to keep the connection alive until manually sending the close response frame?

Currently it is possible to change the response closure code, but has to be set immediately in the handler:

```java
@Override
public void onWebSocketClose(int statusCode, String reason) {
    System.out.println("Received close with statusCode=%d reason=%s".formatted(statusCode, reason));
    session.close(4500, "immediate code", Callback.NOOP);
}
```

```
websocat -k -vv --close-status-code 3000 --close-reason "websocat" ws://localhost:8080/
Received close with statusCode=3000 reason=websocat
[DEBUG websocat::ws_peer] The close message is Some(CloseData { status_code: 4500, reason: "immediate code" })
```

However if attempting to set the close status asynchronously:

```java
public class Main {

    public static class ServerListener implements Session.Listener {
        private volatile Session session;

        @Override
        public void onWebSocketOpen(Session session) {
            this.session = session;
            session.demand();
        }

        @Override
        public void onWebSocketClose(int statusCode, String reason) {
            System.out.println("Received close with statusCode=%d reason=%s".formatted(statusCode, reason));
            computeClosureCodeAsync().thenAccept(code -> session.close(code, "async code", Callback.NOOP));
        }

        CompletableFuture<Integer> computeClosureCodeAsync() {
            CompletableFuture<Integer> future = new CompletableFuture<>();
            new Thread(() -> {
                try {
                    Thread.sleep(20);
                    future.complete(4000);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
            }).start();
            return future;
        }
    }

    public static void main(String[] args) throws Exception {
        Server server = new Server();
        ServerConnector connector = new ServerConnector(server, new HttpConnectionFactory());
        connector.setPort(8080);
        server.setConnectors(new Connector[] {connector});
        ContextHandler contextHandler = new ContextHandler();
        server.setHandler(contextHandler);
        WebSocketUpgradeHandler webSocketHandler = WebSocketUpgradeHandler.from(server, contextHandler, container -> {
            container.addMapping("/*", (serverUpgradeRequest, serverUpgradeResponse, callback) -> new ServerListener());
        });
        contextHandler.setHandler(webSocketHandler);
        server.start();
        server.join();
    }

}
```

Expected to see a 4000 closure response but actually 3000 was immediately echoed back:

```
websocat -k -vv --close-status-code 3000 --close-reason "websocat" ws://localhost:8080/
Received close with statusCode=3000 reason=websocat
[DEBUG websocat::ws_peer] The close message is Some(CloseData { status_code: 3000, reason: "websocat" })
```

I believe this is caused by: https://github.com/jetty/jetty.project/blob/jetty-12.0.22/jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java#L653-L682

**Use Case**

When building a WebSocket proxy like [this example](https://github.com/jetty/jetty.project/blob/jetty-12.0.22/jetty-core/jetty-websocket/jetty-websocket-jetty-tests/src/test/java/org/eclipse/jetty/websocket/tests/proxy/WebSocketProxy.java#L169), ideally the close response should wait and use the close response from the remote endpoint, instead of just responding back immediately the same code.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #13341 

- Add new close method to `Session.Listener` taking a callback `void onWebSocketClose(int statusCode, String reason, Callback callback)`.
- Also add option to use a callback with the `@OnWebSocketClose` close method.
- Fixes to `MethodHolder` to make the `bind` methods bind to a new instance and not the current one (same way that `MethodHandles` work).

### CODE REVIEW

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java [hunk 1]
```diff
@@ -227,4 +236,37 @@ public Class<?> returnType()
             return _methodHandle.type().returnType();
         }
     }
+
+    class Wrapper implements MethodHolder
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java]: This class is missing the overrides to the `bindTo()` methods.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java [hunk 2]
```diff
@@ -227,4 +236,37 @@ public Class<?> returnType()
...
+
+        public MethodHolder getWrapped()
+        {
+            return _methodHolder;
+        }
+
+        @Override
+        public Object invoke(Object... args) throws Throwable
+        {
+            return _methodHolder.invoke(args);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java]:
```suggestion
            return getWrapped().invoke(args);
```

And also for the other methods.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java [hunk 3]
```diff
@@ -227,4 +236,37 @@ public Class<?> returnType()
...
         }
     }
+
+    class Wrapper implements MethodHolder
+    {
+        public MethodHolder _methodHolder;
+
+        public Wrapper(MethodHolder methodHolder)
+        {
+            _methodHolder = methodHolder;
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java]:
```suggestion
            _methodHolder = Objects.requireNonNull(methodHolder);
```

File: jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/Session.java [hunk 4]
```diff
@@ -335,11 +335,25 @@ default void onWebSocketError(Throwable cause)
...
+        /**
+         * <p>The WebSocket {@link Session} has been closed.</p>
+         *
+         * @param statusCode the close {@link StatusCode status code}.
+         * @param reason the optional reason for the close.
+         * @param callback the callback used to signal that the close processing is complete.
+         *
+         */
+        default void onWebSocketClose(int statusCode, String reason, Callback callback)
+        {
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/Session.java:354]: This method should call the deprecated one, and then succeed the callback, inside a `try/catch` that fails the callback.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java [hunk 5]
```diff
@@ -277,8 +277,25 @@ private void notifyOnClose(CloseStatus closeStatus, Callback callback)
         try
         {
             if (closeHandle != null)
-                closeHandle.invoke(closeStatus.getCode(), closeStatus.getReason());
-            callback.succeeded();
+            {
+                org.eclipse.jetty.websocket.api.Callback apiCallback = new org.eclipse.jetty.websocket.api.Callback()
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java]:
```suggestion
                var apiCallback = org.eclipse.jetty.websocket.api.Callback.from(callback::succeeded, callback::failed);
```

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java [hunk 6]
```diff
@@ -277,8 +277,25 @@ private void notifyOnClose(CloseStatus closeStatus, Callback callback)
...
+                    @Override
+                    public void fail(Throwable x)
+                    {
+                        callback.failed(x);
+                    }
+                };
+                closeHandle.invoke(closeStatus.getCode(), closeStatus.getReason(), apiCallback);
+            }
+            else
+                callback.succeeded();
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java:286]: Wrap in braces.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java [hunk 7]
```diff
@@ -167,76 +174,127 @@ private JettyWebSocketFrameHandlerMetadata createListenerMetadata(Class<?> endpo
...
+        public Object invoke(Object... args)
+        {
+            Callback callback = (Callback)Arrays.stream(args)
+                .filter(o -> o instanceof Callback)
+                .findFirst()
+                .orElseThrow(IllegalArgumentException::new);
+
+            try
+            {
+                Object value = getWrapped().invoke(args);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java]:
```suggestion
                Object value = super.invoke(args);
```

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java [hunk 8]
```diff
@@ -167,76 +174,127 @@ private JettyWebSocketFrameHandlerMetadata createListenerMetadata(Class<?> endpo
...
+            {
+                callback.fail(t);
+            }
+            return null;
+        }
+
+        @Override
+        public MethodHolder bindTo(Object arg, int idx)
+        {
+            return new CallbackCompletingCloseHolder(getWrapped().bindTo(arg, idx));
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java:299]:
```suggestion
            return new CallbackCompletingCloseHolder(super.bindTo(arg, idx));
```

There is another bindTo() method to override.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerMetadata.java [hunk 9]
```diff
@@ -43,15 +42,15 @@ public void setAutoDemand(boolean autoDemand)
         this.autoDemand = autoDemand;
     }
 
-    public void setBinaryHandle(Class<? extends MessageSink> sinkClass, MethodHandle binary, Object origin)
+    public void setBinaryHandle(Class<? extends MessageSink> sinkClass, MethodHolder binary, Object origin)
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerMetadata.java:45]: This class is `public`, but got a lot of signature changes.
I'm fine as it is a 12.1.x, just wanted to raise a flag in case it was unintended.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java [hunk 10]
```diff
@@ -167,76 +174,127 @@ private JettyWebSocketFrameHandlerMetadata createListenerMetadata(Class<?> endpo
...
         if (errorMethod != null)
         {
-            MethodHandle errorHandle = toMethodHandle(lookup, errorMethod);
+            MethodHolder errorHandle = toMethodHolder(lookup, errorMethod);
             metadata.setErrorHandle(errorHandle, errorMethod);
         }
 
-        Method closeMethod = findMethod(endpointClass, "onWebSocketClose", int.class, String.class);
+        Method deprecatedCloseMethod = findMethod(endpointClass, "onWebSocketClose", int.class, String.class);
+        Method closeMethod = findMethod(endpointClass, "onWebSocketClose", int.class, String.class, Callback.class);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java:238]: I would not do it in this way.
I would just call the new method, and the default implementation would call the old method, simplifying here a lot.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java (hunk 10 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java:238]: For all the `onWebSocket` methods,  we only get the method if it has been overridden. And the `JettyWebSocketFrameHandler` handles it if there is no `MethodHolder` for that method. So that change would make the Listener `onWebSocketClose` a special case. 

Even if I did it this way I would still need the `CallbackCompletingCloseHolder` for the annotated side.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerMetadata.java (hunk 9 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerMetadata.java:45]: These common modules expose a lot of classes that are really intended to be internal classes, and this is one of them.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java]: The reason I didn't implement these here because there is no good implementation for it. I could do
```java
        @Override
        public MethodHolder bindTo(Object arg)
        {
            return getWrapped().bindTo(arg);
        }

        @Override
        public MethodHolder bindTo(Object arg, int idx)
        {
            return getWrapped().bindTo(arg, idx);
        }
```

but then whenever you bind it would lose the wrapper, so you always need to override these methods if you want to create a wrapper for a `MethodHandle`.

Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java]: I don't understand why it would lose the wrapper. It is always accessible in the subclass via `getWrapper()`.

If these methods always need to be overridden, then rename this class to maybe `Forwarder` (as it is different from all the other `Wrapper` we have), and make the 2 methods `abstract`.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java]: Using `from()` makes it more readable.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java (hunk 10 above)
Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory.java:238]: Good point.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java [hunk 11]
```diff
@@ -277,8 +277,27 @@ private void notifyOnClose(CloseStatus closeStatus, Callback callback)
         try
         {
             if (closeHandle != null)
-                closeHandle.invoke(closeStatus.getCode(), closeStatus.getReason());
-            callback.succeeded();
+            {
+                var apiCallback = new org.eclipse.jetty.websocket.api.Callback()
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java]: Is there a reason to not use `from()`? It would make the code more readable.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java (hunk 11 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java]: now using `Callback.from()`

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/MethodHolder.java]: I have now made this an abstract class, but left the name as `Wrapper` as `Forwarder` seems less clear.

> I don't understand why it would lose the wrapper. It is always accessible in the subclass via getWrapper().

You would wrap the `MethodHolder` to provide some custom behavior like I have done in `CallbackCompletingCloseHolder`, but when `bindTo` is called `getWrapped().bindTo(arg)` will return an instance of the wrapped `MethodHolder` class. Then you would lose the custom behavior in the Wrapper.

So that's why you would almost always override `bindTo` to re-wrap the return value of `getWrapped().bindTo(arg)`.

**Review by sbordet — CHANGES_REQUESTED** [review]
LGTM, but there are test failures.

**Review by sbordet — APPROVED** [review]
