### PR TITLE
Issue #9309 - Better jetty.sh integration for start.jar with eye on supporting odd properties

### LINKED ISSUE #9309: `jetty.sh` cannot handle complex Jetty properties from `start.d/*.ini`
**Jetty version(s)**
Jetty 11.0.13

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)

**OS type/version**
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

**Description**
Can't set custom request log format with spaces. Even example from comment.

If I add this line to _requestlog.ini_:
```
jetty.requestlog.formatString=%{client}a - %u %{dd/MMM/yyyy:HH:mm:ss ZZZ|GMT}t "%r" %s %O "%{Referer}i" "%{User-Agent}i"
```
Jetty fails to run with error message (for a full stacktrace see below):
```
2023-02-03 14:22:39.491:WARN :oejx.XmlConfiguration:main: Unable to execute XmlConfiguration
java.security.PrivilegedActionException: java.nio.file.NoSuchFileException: -\
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1818)
```

It is possible to add format without spaces and start Jetty successfully, for example:
```
jetty.requestlog.formatString="%{client}a-%u-%t-"%r"-%s-%O-%{ms}T"
```

Full stacktrace:
```
2023-02-03 14:22:39.491:WARN :oejx.XmlConfiguration:main: Unable to execute XmlConfiguration
java.security.PrivilegedActionException: java.nio.file.NoSuchFileException: -\
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1818)
Caused by: 
java.nio.file.NoSuchFileException: -\
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at org.eclipse.jetty.util.resource.PathResource.getInputStream(PathResource.java:456)
	at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:220)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$4(XmlConfiguration.java:1849)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1818)
Exception in thread "main" java.security.PrivilegedActionException: java.nio.file.NoSuchFileException: -\
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1818)
Caused by: java.nio.file.NoSuchFileException: -\
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at org.eclipse.jetty.util.resource.PathResource.getInputStream(PathResource.java:456)
	at org.eclipse.jetty.xml.XmlConfiguration.<init>(XmlConfiguration.java:220)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$4(XmlConfiguration.java:1849)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	... 1 more
```

### PR DESCRIPTION
**Pull request by joakime**
When bridging output from `start.jar --dry-run` to the `RUN_CMD` in `jetty.sh` weird properties with various special characters and spaces would mess up the command line that eventually gets executed.

A change to `start.jar --dry-run` has been made to wrap individual args that have spaces with `'` (single-tick quote), and a change in `jetty.sh` to separate the various args produced by the `--dry-run` properly for the execution of java and eventually the call to `XmlConfiguration`.

A minor update to CustomRequestLog exception messages has been pushed here as well.

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Review by gregw — DISMISSED** [review]
LGTM

**Comment by jmcc0nn3ll** [comment]
I think the usage of xargs in the jetty.sh script should be fine, but if there is a more strictly bash solution available, it may make sense to investigate that down the road if some reports an issue.

File: jetty-home/src/main/resources/bin/jetty.sh [hunk 1]
```diff
@@ -435,7 +433,7 @@ CYGWIN*) JETTY_START="`cygpath -w $JETTY_START`";;
 esac
 
 RUN_ARGS=$("$JAVA" -jar "$JETTY_START" --dry-run=opts,path,main,args ${JETTY_ARGS[*]} ${JAVA_OPTIONS[*]})
-RUN_CMD=("$JAVA" $JETTY_SYS_PROPS ${RUN_ARGS[@]})
+RUN_CMD=($JETTY_SYS_PROPS ${RUN_ARGS[@]})
```
Comment (gregw) [inline jetty-home/src/main/resources/bin/jetty.sh]: This feels wrong.  We've just added `"$JAVA"` to `RUN_ARGS` above, and now we are stripping it out?
Also if it doesn't contain java then it is not really a `CMD`.

File: jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java [hunk 2]
```diff
@@ -180,7 +156,32 @@ public String toString(String delim)
...
+        return buf.toString();
+    }
+
+    /**
+     * A version of {@link #toString()} where every arg is evaluated for potential {@code '} (single-quote tick) wrapping.
+     *
+     * @param delim the delimiter between args, use {@code ' '} (space) for shell executable command line.
+     * @return the toString but each arg that has spaces is surrounded by {@code '} (single-quote tick)
+     */
+    public String toQuotedString(String delim)
```
Comment (gregw) [inline jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java]: `delim` is not used and the javadoc doesn't look right.

File: jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java [hunk 3]
```diff
@@ -62,31 +62,7 @@ public static String findJavaBin()
...
-            if (!escaped && (c == '\''))
-            {
-                quoted = !quoted;
-            }
-            escaped = (c == '\\');
-            buf.append(c);
-        }
-        // buf.append('"');
-        return buf.toString();
+        return "'" + arg + "'";
```
Comment (gregw) [inline jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java:67]: is this method used?

**Review by gregw — DISMISSED** [review]
a couple of quick comments. I need to review in more depth once these are resolved.

File: jetty-home/src/main/resources/bin/jetty.sh (hunk 1 above)
Comment (joakime) [reply jetty-home/src/main/resources/bin/jetty.sh]: The `RUN_ARGS` line is executing `java -jar start.jar --dry-run=opts,path,main,args` and capturing the output in `RUN_ARGS`
The `RUN_CMD` doesn't have `$JAVA` as that's one of the problems causing the correct execution of the `XmlConfiguration` from within `jetty.sh` with awkward jetty properties.
The later command that takes `$RUN_CMD` and passes it through `xargs` is splitting the args up properly and then passing that into `$JAVA` correctly.

File: jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java (hunk 2 above)
Comment (joakime) [reply jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java]: delim is used on line 178, and it's passed in as 2 different values from Main.java

File: jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java (hunk 3 above)
Comment (joakime) [reply jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java:67]: Not anymore by us.
I left it in place with a naive implementation.
Guess I could flag it for deprecation too.

File: jetty-home/src/main/resources/bin/jetty.sh (hunk 1 above)
Comment (gregw) [reply jetty-home/src/main/resources/bin/jetty.sh]: I think we should swap the names around. Currently `RUN_ARGS` does contain the java command (as it is output by -dry-run), but `RUN_CMD` does not.   It is cooking my noodle and making it hard to understand the rest of the code.

File: jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java (hunk 3 above)
Comment (gregw) [reply jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java:67]: I think we can just delete it.

File: jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java (hunk 2 above)
Comment (gregw) [reply jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java]: Ah,  I got confused by the javadoc.  See comment below now.

File: jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java [hunk 4]
```diff
@@ -180,7 +158,32 @@ public String toString(String delim)
...
+     */
+    public String toQuotedString(String delim)
+    {
+        StringBuilder buf = new StringBuilder();
+
+        for (String arg : args)
+        {
+            if (buf.length() > 0)
+                buf.append(delim);
+            boolean needsQuotes = (arg.contains(" "));
```
Comment (gregw) [inline jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java:180]: should this not be:
```suggestion
            boolean needsQuotes = (arg.contains(delim));
```

Comment (joakime) [reply jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java:180]: Not really, as this is testing for a space present in a single arg.
`delim`, as used above, is the delim between args. 

See the Main.java, the `delim` you see as a method parameter is different depending on if debug enabled or not (with debug it's `\n` (LF), otherwise its ` ` (space))

Comment (gregw) [reply jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java:180]: But isn't it true that you need to quote an arg only if it contains a delimiter?   If space is not the delimiter, then you don't need to quote it.

**Comment by amjaliks** [comment]
With these changes my 10.0.x fails to start as a services. Even before I try to set 'an odd property' (a custom request log format).

A stacktrace:
```
2023-02-18 13:30:13.328:WARN :oejx.XmlConfiguration:main: Unable to execute XmlConfiguration
java.security.PrivilegedActionException: java.security.UnrecoverableKeyException: Get Key failed: Cannot read the array length because "password" is null
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1818)
Caused by: 
java.security.UnrecoverableKeyException: Get Key failed: Cannot read the array length because "password" is null
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:450)
	at java.base/sun.security.util.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:91)
```

The same configuration starts normally with 10.0.13.

File: jetty-home/src/main/resources/bin/jetty.sh (hunk 1 above)
Comment (amjaliks) [reply jetty-home/src/main/resources/bin/jetty.sh]: Please note, if your remove `$JAVA` from `$RUN_CMD`, you need to update a code for `run` action.

Comment (joakime) [reply jetty-home/src/main/resources/bin/jetty.sh]: `RUN_ARGS` does not contain the `java` portion, simply because of the limitation on the `--dry-run` selection.

Example:

``` shell
[jetty-home/target/foobase][fix/jetty-10.0.x/jetty-sh-start-properties]$ java -jar ../jetty-home/start.jar --dry-run=opts,path,main,args
-Djava.io.tmpdir=/tmp -Djetty.home=/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home 
-Djetty.base=/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/foobase 
--class-path /home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/foobase/resources:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/logging/slf4j-api-2.0.5.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/logging/jetty-slf4j-impl-10.0.14-SNAPSHOT.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/jetty-servlet-api-4.0.6.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/jetty-http-10.0.14-SNAPSHOT.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/jetty-server-10.0.14-SNAPSHOT.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/jetty-xml-10.0.14-SNAPSHOT.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/jetty-util-10.0.14-SNAPSHOT.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/jetty-io-10.0.14-SNAPSHOT.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/jetty-security-10.0.14-SNAPSHOT.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/jetty-servlet-10.0.14-SNAPSHOT.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/jetty-webapp-10.0.14-SNAPSHOT.jar:/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/jetty-deploy-10.0.14-SNAPSHOT.jar 
org.eclipse.jetty.xml.XmlConfiguration 
'java.version'='17.0.6' 'java.version.major'='17' 'java.version.micro'='6' 'java.version.minor'='0' 'java.version.platform'='17' 
'jetty.base'='/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/foobase' 
'jetty.base.uri'='file:///home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/foobase' 
'jetty.home'='/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home' 
'jetty.home.uri'='file:///home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home' 
'jetty.webapp.addServerClasses'='org.eclipse.jetty.logging.,file:///home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/lib/logging/,org.slf4j.' 
'runtime.feature.alpn'='true' 
'slf4j.version'='2.0.5' 
/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/etc/jetty-bytebufferpool.xml 
/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/etc/jetty-threadpool.xml 
/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/etc/jetty.xml 
/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/etc/jetty-webapp.xml 
/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/etc/jetty-deploy.xml 
/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/etc/jetty-http.xml 
/home/joakim/code/jetty/jetty.project-10.0.x/jetty-home/target/jetty-home/etc/jetty-requestlog.xml
```

This is because the dry-run part `java` (aka `--dry-run=java`) so that portion is missing.

**Comment by joakime** [comment]
@amjaliks can you include more of the stacktrace on that exception?
It will help me setup a similar jetty.base to you

File: jetty-home/src/main/resources/bin/jetty.sh (hunk 1 above)
Comment (amjaliks) [reply jetty-home/src/main/resources/bin/jetty.sh]: Please look at the line 598.

**Comment by amjaliks** [comment]
@joakime I got this fixed by using `xargs` for calling `start-stop-deamon` in `jetty.sh`.

I replaced this (starting line 467):
```
      start-stop-daemon --start $CH_USER \
       --pidfile "$JETTY_PID" \
       --chdir "$JETTY_BASE" \
       --background \
       --make-pidfile \
       --startas "$JAVA" \
       -- ${RUN_ARGS[@]} start-log-file="$JETTY_START_LOG"
```

With this:
```
      echo ${RUN_CMD[*]} start-log-file="$JETTY_START_LOG" | xargs start-stop-daemon --start $CH_USER \
       --pidfile "$JETTY_PID" \
       --chdir "$JETTY_BASE" \
       --background \
       --make-pidfile \
       --startas "$JAVA" \
       --
```

End even more. I applied similar changes to `jetty.sh` from *10.0.13* and *11.0.13*:
```
      echo $JETTY_SYS_PROPS ${RUN_ARGS[@]} start-log-file="$JETTY_START_LOG" | xargs start-stop-daemon --start $CH_USER \
       --pidfile "$JETTY_PID" \
       --chdir "$JETTY_BASE" \
       --background \
       --make-pidfile \
       --startas "$JAVA" \
       --
```
And this fixed #9309.

**Comment by amjaliks** [comment]
@joakime You need to update lines 586 and 599, otherwise actions `supervise`, `run`, and `demo` will be broken.

**Comment by amjaliks** [comment]
This PR has missed 10.0.14. How about 10.0.15?

**Comment by joakime** [comment]
@amjaliks have you tested this branch on your environment?
@gregw are you ok with this being in Jetty 10.0.15 release? (if so, I need an approval to merge this)

**Comment by joakime** [comment]
I've found a few problems with this branch on Windows that needs to be addressed.

**Comment by joakime** [comment]
I have finished my testing on Windows.

Other than the usual situation with overly long command lines, this PR appears to be working as intended on the Windows platform.

**Review by sbordet — DISMISSED** [review]

File: jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java (hunk 4 above)
Comment (joakime) [reply jetty-start/src/main/java/org/eclipse/jetty/start/CommandLineBuilder.java:180]: No longer relevant, simone convinced me to remove the param

**Comment by joakime** [comment]
@sbordet need a fresh approval, had to fix a build issue with javadoc

**Review by sbordet — APPROVED** [review]
