### PR TITLE
Issue #5162 CDI embedded integration improvements

### LINKED ISSUE #5162: DecoratingListener raises a NullPointerException
**Jetty version**
9.4.31.v20200723 (Maven)

**Java version**
OpenJDK 11

**OS type/version**
Debian stable

**Description**
The sample code from the [Weld embedded](https://www.eclipse.org/jetty/documentation/current/framework-weld.html#weld-embedded) section in the Jetty Reference raises a NullPointerException.

Here is the stack trace.

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at org.eclipse.jetty.servlet.DecoratingListener.<init>(DecoratingListener.java:67)
	at org.eclipse.jetty.webapp.DecoratingListener.<init>(DecoratingListener.java:49)
	at org.eclipse.jetty.webapp.DecoratingListener.<init>(DecoratingListener.java:39)
	at org.eclipse.jetty.webapp.DecoratingListener.<init>(DecoratingListener.java:34)
	at io.github.oliviercailloux.jetty.App.main(App.java:64)
```

This could be a usage problem. It is unclear to me, reading the documentation, if I have to apply anything from the section “Weld Setup” (in the [same page](https://www.eclipse.org/jetty/documentation/current/framework-weld.html)), when running in embedded mode (and if so, what), or if the Weld embedded section is to be applied to the exclusion of the other part. If I have to include the cdi-decorate module, how can I do this with Maven? In any case, the problem also happens with `org.eclipse.jetty:jetty-cdi` included in the project dependencies.

The [Weld documentation](https://docs.jboss.org/weld/reference/latest-3.1/en-US/html/environments.html#_jetty) gives almost the same instructions, but not exactly: one line of code, `context.addEventListener(new Listener());` has been added. Which version is correct? And, similarly, I ignore whether I am supposed to apply section `18.3.2.4. Binding BeanManager to Jetty JNDI` (or others) in supplement to `18.3.2.5. Embedded Jetty` or if `18.3.2.5. Embedded Jetty` is sufficient.

(I also want to use Jersey, which further complicates the matter, but I suppose that this issue is unrelated as the bug happens with a sample code that does not involve Jersey.)

**Possibly related**
#4064 #3804 #4121

### PR DESCRIPTION
**Pull request by gregw**
Clean up CDI integration and documentation to better support embedded usage.
 + made listener public
 + added utility class for SCIs

### CODE REVIEW

**Comment by gregw** [comment]
@janbartel @joakime can I get some feedback on this draft.

File: jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiDecoratingListener.java [hunk 1]
```diff
@@ -24,13 +24,14 @@
 /**
  * A DecoratingListener that listens for "org.eclipse.jetty.cdi.decorator"
  */
-class CdiDecoratingListener extends DecoratingListener
+public class CdiDecoratingListener extends DecoratingListener
```
Comment (gregw) [inline jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiDecoratingListener.java:27]: Made public so it can be directly used without SCI

File: jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiDecoratingListener.java [hunk 2]
```diff
@@ -24,13 +24,14 @@
...
 {
     public static final String MODE = "CdiDecoratingListener";
     public static final String ATTRIBUTE = "org.eclipse.jetty.cdi.decorator";
 
     public CdiDecoratingListener(ServletContextHandler contextHandler)
     {
         super(contextHandler, ATTRIBUTE);
+        contextHandler.setAttribute(CdiServletContainerInitializer.CDI_INTEGRATION_ATTRIBUTE, MODE);
```
Comment (gregw) [inline jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiDecoratingListener.java:35]: Set the mode here, so direct usage still signals to weld the method used.

File: jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java [hunk 3]
```diff
@@ -65,7 +65,10 @@
     public CdiSpiDecorator(ServletContextHandler context) throws UnsupportedOperationException
     {
         _context = context;
+        context.setAttribute(CdiServletContainerInitializer.CDI_INTEGRATION_ATTRIBUTE, MODE);
         ClassLoader classLoader = _context.getClassLoader();
+        if (classLoader == null)
+            classLoader = this.getClass().getClassLoader();
```
Comment (gregw) [inline jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java:76]: make work when there is no classloader

File: jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java [hunk 4]
```diff
@@ -92,6 +95,35 @@ public CdiSpiDecorator(ServletContextHandler context) throws UnsupportedOperatio
...
+     * Test if a specific class name is known to not be decoratable.
+     * @implNote default implementation checks for well known classes that are used to
+     * setup CDI itself, and thus cannot themselves be decorated.
+     * @see #isDecoratable(Class)
+     * @param className The name of the class to check
+     * @return True if the class is known not to be decoratable
+     */
+    protected boolean isKnownUndecoratable(String className)
+    {
+        return "org.jboss.weld.environment.servlet.Listener".equals(className);
```
Comment (gregw) [inline jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java]: This complex little dance is because it is too easy to install `CdiSpiDecorator` and then try to init Weld with it's listener, which will fail because `CdiSpiDecorator` will try to decorate it, but CDI is not enabled yet.     This soft dependency  breaks that chicken-egg problem.

File: jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/ContainerInitializer.java [hunk 5]
```diff
@@ -124,9 +124,6 @@ public void callStartup(WebAppContext context)
         {
             Set<Class<?>> classes = new HashSet<Class<?>>();
 
-            ClassLoader oldLoader = Thread.currentThread().getContextClassLoader();
-            Thread.currentThread().setContextClassLoader(context.getClassLoader());
-
```
Comment (gregw) [inline jetty-plus/src/main/java/org/eclipse/jetty/plus/annotation/ContainerInitializer.java:129]: This is no longer needed.  Always called with correct classloader set.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java [hunk 6]
```diff
@@ -336,9 +338,15 @@ protected ServletHandler newServletHandler()
...
-            sciBean.start();
+        for (ServletContainerInitializerCaller  sci : getBeans(ServletContainerInitializerCaller.class))
+        {
+            if (sci.isStopped())
+            {
+                sci.start();
+                if (isAuto(sci))
+                    manage(sci);
+            }
+        }
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:349]: This allows for multiple SCI Callers.  It also correctly sets them as managed if this handler starts them.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java [hunk 7]
```diff
@@ -1493,4 +1501,43 @@ public void destroy(Object o)
...
+            {
+                _context.getServletContext().setExtendedListenerTypes(true);
+                _sci.onStartup(_classes, _context.getServletContext());
+            }
+            finally
+            {
+                _context.getServletContext().setExtendedListenerTypes(oldExtended);
+            }
+        }
+    }
```
Comment (gregw) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:1542]: This utility class avoids the need to create custom SCI callers.   The name is not perfect, but this name space is a bit messed up.  It does read well when used.

File: tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/CDITests.java [hunk 8]
```diff
@@ -61,7 +61,7 @@
             Arguments.of("weld", "cdi2", null),
             Arguments.of("weld", "cdi-spi", null), // Weld >= 3.1.2
             Arguments.of("weld", "decorate", null), // Weld >= 3.1.2
-            // TODO Arguments.of("weld", "cdi-decorate", null), // Weld >= 3.1.3
+            Arguments.of("weld", "cdi-decorate", null), // Weld >= 3.1.3
```
Comment (gregw) [inline tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/CDITests.java:64]: This test mode is now supported

File: tests/test-webapps/test-weld-cdi-webapp/src/test/java/org/eclipse/jetty/cdi/weld/EmbeddedWeldTest.java [hunk 9]
```diff
@@ -0,0 +1,241 @@
...
+import org.eclipse.jetty.webapp.JettyWebXmlConfiguration;
+import org.eclipse.jetty.webapp.WebAppContext;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.ValueSource;
+
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.containsString;
+
+public class EmbeddedWeldTest
```
Comment (gregw) [inline tests/test-webapps/test-weld-cdi-webapp/src/test/java/org/eclipse/jetty/cdi/weld/EmbeddedWeldTest.java]: Added this unit test to test similar features as the webapp, but from embedded

File: tests/test-webapps/test-weld-cdi-webapp/src/test/java/org/eclipse/jetty/cdi/weld/EmbeddedWeldTest.java [hunk 10]
```diff
@@ -0,0 +1,241 @@
...
+        context.setContextPath("/");
+        server.setHandler(context);
+
+        // Setup context
+        context.addServlet(GreetingsServlet.class, "/");
+        context.addServlet(BeanServlet.class, "/beans");
+        context.addFilter(ServerIDFilter.class, "/*", EnumSet.of(DispatcherType.REQUEST));
+
+        // Setup Jetty weld integration
+        switch (mode)
```
Comment (gregw) [inline tests/test-webapps/test-weld-cdi-webapp/src/test/java/org/eclipse/jetty/cdi/weld/EmbeddedWeldTest.java]: I don't think all these modes are recommended, but all variations are probably used somewhere so best to test to know if we break any usages.

File: tests/test-webapps/test-weld-cdi-webapp/src/test/java/org/eclipse/jetty/cdi/weld/EmbeddedWeldTest.java [hunk 11]
```diff
@@ -0,0 +1,241 @@
...
+        server.setHandler(webapp);
+
+        // Need the AnnotationConfiguration to detect SCIs
+        Configuration.ClassList.setServerDefault(server).addBefore(JettyWebXmlConfiguration.class.getName(),
+            AnnotationConfiguration.class.getName());
+
+        // Need to expose our SCI.  This is ugly could be made better in jetty-10 with a CdiConfiguration
+        webapp.getServerClasspathPattern().add("-" + CdiServletContainerInitializer.class.getName());
+        webapp.getSystemClasspathPattern().add(CdiServletContainerInitializer.class.getName());
+
```
Comment (gregw) [inline tests/test-webapps/test-weld-cdi-webapp/src/test/java/org/eclipse/jetty/cdi/weld/EmbeddedWeldTest.java]: We can add a CdiConfiguration to do this in 10.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java (hunk 7 above)
Comment (joakime) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:1542]: If an SCI is being run on a ServletContextHandler, there's no expectations of bytecode scanning (IMO).

It would be sweet if we could just do ...

``` java
ServletContextHandler handler = new ServletContextHandler();
handler.addBean(new MyLibServletContextInitializer());
handler.addBean(new org.jboss.weld.environment.servlet.EnhancedListener()); // this is an SCI
server.setHandler(handler);
server.start(); // this loads the SCI's from the beans and uses them.
```

Just have ServletContextHandler be aware of SCI as beans and load / call them with no/empty classes.

Or, if this raw/naked SCI as bean concept isn't right, how about a specific call on ServletContextHandler for them?

``` java
ServletContextHandler handler = new ServletContextHandler();
handler.addInitializer(new MyLibServletContextInitializer(), Collections.emptySet());
handler.addInitializer(new org.jboss.weld.environment.servlet.EnhancedListener(), Collections.emptySet());
server.setHandler(handler);
server.start();
```

**Comment by gregw** [comment]
Hmm test harness approach doesn't work without IDE... refactoring...

**Comment by gregw** [comment]
@WalkerWatch can you check the doco changes in this PR

**Review by WalkerWatch — APPROVED** [review]
Documentation is fine with one caveat. We try to make use of [ventilated prose in asciidoc](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line) as it makes maintenance and upkeep easier.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java (hunk 7 above)
Comment (gregw) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:1542]: @joakime if we were adding this mechanism from scratch, I agree that just adding the SCIs as beans would be simplest.
However, we already have the concept of a ServletContainerInitializerCaller set as a bean and it is used at least a little bit.... so adding a utility instance of that feels simpler than having two mechanisms.     I guess we could make `Initializer` private and check for SCI beans... so it would be a feeder to the existing mechanism.... torn.... @janbartel thoughts?

Comment (janbartel) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:1542]: You can't do away with some kind of wrapper for the SCIs because the SCI.onStartup() method can have the list of classes passed in, so you need to remember somewhere what they are.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java [hunk 12]
```diff
@@ -749,13 +757,13 @@ public static ServletContextHandler getServletContextHandler(ServletContext cont
 
     public static class JspPropertyGroup implements JspPropertyGroupDescriptor
     {
-        private List<String> _urlPatterns = new ArrayList<>();
+        private final List<String> _urlPatterns = new ArrayList<>();
```
Comment (janbartel) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:760]: Again with the extraneous changes!

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/ContainerLifeCycle.java [hunk 13]
```diff
@@ -915,11 +915,6 @@ public void updateBeans(Object[] oldBeans, final Object[] newBeans)
         }
     }
 
-    /**
```
Comment (janbartel) [inline jetty-util/src/main/java/org/eclipse/jetty/util/component/ContainerLifeCycle.java:918]: Why is the comment removed?

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java [hunk 14]
```diff
@@ -1493,4 +1501,43 @@ public void destroy(Object o)
             decorator.destroy(o);
         }
     }
+
+    /**
+     * A utility class to hold a {@link ServletContainerInitializer} and implement the
+     * {@link ServletContainerInitializerCaller} interface so that the SCI is correctly
+     * started if an instance of this class is added as a bean to a {@link ServletContextHandler}.
+     */
+    public static class Initializer extends AbstractLifeCycle implements ServletContainerInitializerCaller
```
Comment (janbartel) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:1510]: I don't see any refactoring of the existing ContainerInitializer and ServletContainerInitializersStarter classes used by webapps - I would think that we could extend this ServletContextHandler.Initializer class, or have the other classes extend it. I don't like having 2 completely separate mechanisms.

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java (hunk 12 above)
Comment (gregw) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:760]: yeah - you have to be a little bad sometimes :)

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java (hunk 14 above)
Comment (gregw) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:1510]: We have a single mechanism based on a single interface, `ServletContainerInitializerCaller`, that has two key implementations:
 1. The webapp impl that has a single caller that invokes all the SCIs it has discovered in the order that it wants.
 2. The Initializer impl that is just a convenience class to create your own custom caller.

To make the webapp impl use the Initializer, then it would have to make all discovered SCIs individually wrapped as Initializers and get into the business of sorting beans on the context....  That is doable, but I'm not sure it is worth it for the bugs that it will introduce.  I really don't want to mess with webapps SCI handling if it is not broken.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java (hunk 7 above)
Comment (gregw) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:1542]: Ah yes - naked SCIs only work if they have no classes to be passed in.  Whilst that will be rare for the usage intended, it still would mean another mechanism, so let's just keep it simple.

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/ContainerLifeCycle.java (hunk 13 above)
Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/component/ContainerLifeCycle.java:918]: You don't need to comment overridden methods unless you need to add impl notes.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java (hunk 14 above)
Comment (janbartel) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:1510]: But I thought that the ordering on the beans is that they are called in the order they are added? If so, then we can just have AnnotationConfiguration add them in the order that is established by applying any ordering: currently it just adds the ContainerInitializers to a list in the order determined by the ordering, so I don't see the difference between adding it to that list, and adding it to the  list of beans.

And I think the refactoring I'm talking about should be done in 10, not 9.

Comment (gregw) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java:1510]: Yes it is totally doable... but I just don't want to mess with something that isn't broken.... maybe 10.1?

**Comment by gregw** [comment]
@janbartel What are the show stoppers for you in this PR?

**Comment by gregw** [comment]
@janbartel @joakime nudge!

File: jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java [hunk 15]
```diff
@@ -92,6 +95,35 @@ public CdiSpiDecorator(ServletContextHandler context) throws UnsupportedOperatio
...
+     * The default implementation calls {@link #isKnownUndecoratable(String) }
+     * on the class and all it's super classes.
+     * @param clazz The class to check
+     * @return True if the class and all it's super classes can be decorated
+     */
+    protected boolean isDecoratable(Class<?> clazz)
+    {
+        if (Object.class == clazz)
+            return true;
+        if (isKnownUndecoratable(clazz.getName()))
```
Comment (janbartel) [inline jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java]: Not at all fond of the name isKnownDecoratable(). How about instead you remove isKnownDecoratable() and add a field list of _undecoratables, a setter for them, and in isDecoratable() you just check the list? This might also be a good idea in case CDI adds some other classes that can't be decorated?

File: jetty-documentation/src/main/asciidoc/development/frameworks/cdi.adoc [hunk 16]
```diff
@@ -0,0 +1,119 @@
...
+When starting embedded Jetty programmatically from the `main` method, to use CDI it may be
+necessary:
+
+ * enable a Jetty CDI integration mode
+
+ * and/or enable a CDI frame integration.
+
+However, depending on the exact configuration of the embedded server, either or both steps may not be required as Servlet Container Initializers may be discovered.
+
+The details for embedding CDI will be explain in the Embedded Jetty with Weld section, but can be adapted to other CDI frameworks.
```
Comment (janbartel) [inline jetty-documentation/src/main/asciidoc/development/frameworks/cdi.adoc]: Need a link here?

**Review by janbartel — APPROVED** [review]
So I don't have any showstoppers, but I would like you to take a look at my suggestion for the isKnownDecoratable() method.

File: jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java [hunk 17]
```diff
@@ -92,6 +100,54 @@ public CdiSpiDecorator(ServletContextHandler context) throws UnsupportedOperatio
...
+    public Set<String> getUndecoratedClasses()
+    {
+        return _undecorated;
+    }
+
+    /**
+     * @param undecorated The set of class names that will not be decorated.
+     * @see #isDecoratable(Class)
+     */
+    public void setUndecoratedClasses(Set<String> undecorated)
```
Comment (janbartel) [inline jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java]: I meant "setUndecoratableClasses". Undecorated makes it sound like they haven't been decorated yet.

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java (hunk 17 above)
Comment (gregw) [reply jetty-cdi/src/main/java/org/eclipse/jetty/cdi/CdiSpiDecorator.java]: @janb I saw that, but I think Undecorated also works, is less of a mouthful and eitherway you need to check with the javadoc to really know what it means.

**Review by janbartel — APPROVED** [review]
LGTM
