### PR TITLE
12.0.x: Fix invalid persistence check before `consumeAll()` when completing the `ChannelCallback`

### LINKED ISSUE #13933: completeStream changes introduced "Unconsumed" bug
**Jetty version(s)**
12.0.x and 12.1.x

**Jetty Environment**
core

**HTTP version**
HTTP/1.1

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
The new changes from issue #13470 to call completeStream only once (PR #13814) have broken `RFC2616Test.test824()`

The `RFC2616Test.test824()` is disabled in `jetty-12.0.x` so it didn't catch this issue.
However, the change from PR #13814 has been merged to `jetty-12.1.x`, which has `RFC2616Test.test824()` enabled.

Currently two PRs are experiencing consistent test failures due to this merge (#13690 and #13929)

We should restore/enable `RFC2616Test` entirely in `jetty-12.0.x` branch and fix this issue there, then merge that change up to `jetty-12.1.x`

### PR DESCRIPTION
**Pull request by lorban**
Fix for the #13933 bug that was introduced in #13814

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 1]
```diff
@@ -1568,13 +1568,16 @@ private void completeChannelCallback(Throwable failure)
...
                 // Turn pending demand or unconsumed input on persistent connections into failure
                 if (httpChannelState._onContentAvailable != null)
+                {
                     failure = ExceptionUtil.combine(failure, new IllegalStateException("demand pending"));
-                else if (httpChannelState.getConnectionMetaData().isPersistent())
-                    failure = ExceptionUtil.combine(failure, stream.consumeAvailable());
+                }
                 else
                 {
+                    // Consume available content before checking if the connection is persistent.
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Please update the comment explaining _why_ we need to `consumeAvailable()` _before_ checking `isPersistent()`.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/PartialRFC2616Test.java [hunk 2]
```diff
@@ -550,7 +550,6 @@ public void test823() throws Exception
     }
 
     @Test
-    @Disabled // TODO
     public void test824() throws Exception
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/PartialRFC2616Test.java]: Please rename to `test823()`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/PartialRFC2616Test.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/PartialRFC2616Test.java]: There is already a `test823()` method. Any other suggestion? @joakime?

Comment (sbordet) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/PartialRFC2616Test.java]: `test823_2()`?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I've reworded the comment, changed another earlier one and removed the `isPersistent()` check as that branch has no effect.

**Review by sbordet — APPROVED** [review]

**Review by sbordet — CHANGES_REQUESTED** [review]
@lorban now there are other failures... I added the label to build all tests.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 3]
```diff
@@ -1566,18 +1566,21 @@ private void completeChannelCallback(Throwable failure)
...
                 {
+                    // consumeAvailable() makes the connection non-persistent and returns an exception
+                    // when the content cannot be consumed, this must not result in an error according
+                    // to RFC2616 section 8.2.3.
                     Throwable unconsumed = stream.consumeAvailable();
                     if (failure != null)
                         ExceptionUtil.addSuppressedIfNotAssociated(failure, unconsumed);
                     if (LOG.isDebugEnabled())
-                        LOG.debug("consumeAvailable: {} {} ", unconsumed == null, httpChannelState);
+                        LOG.debug("consumeAvailable: {} {} ", unconsumed == null, httpChannelState, failure);
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: failure could be null so use the fluent style to avoid ambiguity:
```suggestion
                        LOG.atDebug().setCause(failure).log("consumeAvailable: {} {} ", unconsumed == null, httpChannelState);
```

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 4]
```diff
@@ -1566,18 +1566,21 @@ private void completeChannelCallback(Throwable failure)
...
+                {
                     failure = ExceptionUtil.combine(failure, new IllegalStateException("demand pending"));
-                else if (httpChannelState.getConnectionMetaData().isPersistent())
-                    failure = ExceptionUtil.combine(failure, stream.consumeAvailable());
+                }
                 else
                 {
+                    // consumeAvailable() makes the connection non-persistent and returns an exception
+                    // when the content cannot be consumed, this must not result in an error according
+                    // to RFC2616 section 8.2.3.
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]:
```suggestion
                    // If consumeAvailable() cannot consume all the content, then it 
                    // makes the connection non-persistent and returns an exception.
                    // This must not result in an error according to RFC2616 section 8.2.3.
```

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 5]
```diff
@@ -1566,18 +1566,21 @@ private void completeChannelCallback(Throwable failure)
...
                     Throwable unconsumed = stream.consumeAvailable();
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1582]: Can you explain why we need to consumeAvailable on a connection that is already not persistent?

**Review by gregw — CHANGES_REQUESTED** [review]

**Comment by gregw** [comment]
I've done an alternate fix in #13940.
It keeps the original structure, but puts in an exception for expecting requests

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1582]: We should skip that, indeed.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Done.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Done.

**Review by sbordet — DISMISSED** [review]

**Comment by lorban** [comment]
@sbordet the latest change about checking the connection persistence comes with some subtle behavioral changes reflected by my changes to `HttpChannelTest` and `RequestLogTest`.

Are we fine with those?

**Comment by gregw** [comment]
@sbordet @lorban We need to get one fix or the other committed to fix head.  I prefer my fix as I believe it has no behaviour changes, even though it has explicit mention of 100 expectations.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestLogTest.java [hunk 6]
```diff
@@ -200,9 +202,17 @@ public void testNormalPostFormRequest(String requestPath) throws Exception
...
+                if (persistent)
+                {
+                    querySize = 0;
+                    if (requestPath.contains("?"))
+                        querySize = 1; // assuming that parameterized version only has 1 query value
+                }
+                else
+                {
+                    querySize = parameterCount;
+                }
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestLogTest.java]: Why do we have 2 different behaviors for the query parameter count, depending on persistence of the connection?

IIUC, `Request.getParameters(request);` reads the whole body anyway, so there is no `consumeAvailable()` effects because the body has already been fully read.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java [hunk 7]
```diff
@@ -231,6 +231,8 @@ public boolean isCommitted()
     @Override
     public Throwable consumeAvailable()
     {
+        if (_channel.getConnectionMetaData() instanceof MockConnectionMetaData mock)
+            mock.notPersistent();
         return HttpStream.consumeAvailable(this, new HttpConfiguration());
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java]: Don't think this si right. First consumeAvailable(), and only if non-null returned we want to make the connection not persistent.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestLogTest.java (hunk 6 above)
Comment (lorban) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/RequestLogTest.java]: It is because `Request.getParameters(request)` is done from `RequestLog.log()` (the 1st lambda passed to `createServer()` above) which is called from `completeStream()`, so _after_ `consumeAvailable()` is called or not.

I think this change of behavior is wrong: `RequestLog.log()` shouldn't be able to see the `x-www-form-urlencoded` parameters in this case no matter if the connection is persistent or not.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java (hunk 7 above)
Comment (lorban) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java]: You're right, fixed.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 8]
```diff
@@ -1566,18 +1566,26 @@ private void completeChannelCallback(Throwable failure)
...
                 if (httpChannelState._onContentAvailable != null)
+                {
                     failure = ExceptionUtil.combine(failure, new IllegalStateException("demand pending"));
-                else if (httpChannelState.getConnectionMetaData().isPersistent())
-                    failure = ExceptionUtil.combine(failure, stream.consumeAvailable());
+                }
                 else
                 {
+                    // If consumeAvailable() cannot consume all the content, then it
+                    // makes the connection non-persistent and returns an exception.
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1577]: I don't think this is correct!
You are thinking of `org.eclipse.jetty.server.ResponseUtils#ensureConsumeAvailableOrNotPersistent`
There is nothing in consumeAvailable that changes the persistent state.

**Review by gregw — COMMENTED** [review]
@sbordet @lorban Sorry for the late review... this week has been a mess.

I don't mind this version, it is close to the one before last that I tried.  A few more behaviour changes than I'd like.

Key issue for me is that the comment is wrong and it does work the way you think it does!

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 8 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1577]: Indeed this comment is partially wrong, as the connection is made non-persistent only for H1 (see `HttpStreamOverHTTP1.consumeAvailable()`).

Do you have more worries in mind, or should we just modify the comment?

Let's discuss this as soon as you find some time to.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1577]: @lorban at this stage, just the comment
