### PR TITLE
Do not create a session index in the `JDBCSessionDataStore` anymore

### LINKED ISSUE #14408: Redundant database index created by JDBCSessionDataStore
**Jetty version(s)**
12.1.5

**Jetty Environment**
ee11

**HTTP version**
N/A

**Java version/vendor**
N/A

**OS type/version**
N/A

**Description**
`JDBCSessionDataStore.prepareTables()` method creates an index which is not really needed (at least in MySQL and PostgreSQL) because it is already covered by `JettySessions` table primary key.

`idx_JettySessions_session` index contains `sessionId`  and `contextPath`, and the primary key contains `sessionId`, `contextPath` and `virtualHost`.  Since the 2 columns in the index are in the same order and at the start of the primary key, the index is not needed because the primary key can be used and with the same performance.

Having this redundant index has a disk overhead in inserts and updates, and no benefit in selects.

Reference MySQL:
https://dev.mysql.com/doc/refman/8.4/en/multiple-column-indexes.html

>  If the table has a multiple-column index, any leftmost prefix of the index can be used by the optimizer to look up rows. For example, if you have a three-column index on (col1, col2, col3), you have indexed search capabilities on (col1), (col1, col2), and (col1, col2, col3). 

Reference PostgreSQL:
https://www.postgresql.org/docs/current/indexes-multicolumn.html

> A multicolumn B-tree index can be used with query conditions that involve any subset of the index's columns, but the index is most efficient when there are constraints on the leading (leftmost) columns. The exact rule is that equality constraints on leading columns, plus any inequality constraints on the first column that does not have an equality constraint, will always be used to limit the portion of the index that is scanned.

I don't know if this is applicable to other databases, so an option would be to include a setting like:
`jetty.session.jdbc.schema.createSessionIndex=true|false` (default `true` for compatibility)

**How to reproduce?**

Delete `idx_JettySessions_session` index in `JettySessions` table and restart Jetty.  The `idx_JettySessions_session` index is recreated.

### PR DESCRIPTION
**Pull request by lorban**
The index is never used in any query, so let's not create it anymore.

Fixes #14408

### CODE REVIEW

**Review by olamy — DISMISSED** [review]

**Review by lachlan-roberts — DISMISSED** [review]

**Comment by ofrias** [comment]
Hi. After reviewing `JDBCSessionDataStore` code, it looks like `idx_JettySessions_session` index is never used to access `JettySessions` table, in any case and for any database type.

This is the full list methods that build table queries or updates in `JDBCSessionDataStore`:

**Group A:** Methods that select by `sessionId`, `contextPath` and `virtualHost` (all 3 simultaneously), and that, as a consequence, will always use the primary key:
- `getUpdateSessionStatement()`
- `getCheckSessionExistsStatement()`
- `getLoadStatement()`
- `getUpdateStatement()`
- `getDeleteStatement()`

**Group B:** Methods that select by `expiryTime` and that, as a consequence, will use the `idx_JettySessions_expiry` index (and that cannot, in any case use the `idx_JettySessions_session` index or the primary key because they do not query by `sessionId`)
- `getExpiredSessionsStatement()`
- `getMyExpiredSessionsStatement()`
- `getCleanOrphansStatement()`

There is not any case in which the table is queried by `sessionId` and `contextPath` and not by `virtualHost` at the same time, and this would be the only case in which `idx_JettySessions_session` index could make sense for some database types (those not using B-tree indexes).  So there is no point at all in having this index.

So instead of having a configurable setting, my proposal is to remove the `idx_JettySessions_session` index completely.

**Comment by lorban** [comment]
@ofrias I do agree with you that the `idx_JettySessions_session` seems to be unneeded now so I've updated my PR accordingly to entirely remove it instead of adding a config setting to disable it.

@janbartel since I'm not the greatest person to reason about DB indexing, there might be a reason for the existence of this index that I'm not aware of an I do not understand so I'd be happy if you could give this change your seal of approval. Thanks!

**Comment by lorban** [comment]
@ofrias I do agree with you that the `idx_JettySessions_session` seems to be unneeded now so I've updated my PR accordingly to entirely remove it instead of adding a config setting to disable it.

@janbartel since I'm not the greatest person to reason about DB indexing, there might be a reason for the existence of this index that I'm not aware of an I do not understand so I'd be happy if you could give this change your seal of approval. Thanks!

File: jetty-core/jetty-session/src/main/java/org/eclipse/jetty/session/JDBCSessionDataStore.java [hunk 1]
```diff
@@ -276,11 +276,6 @@ public String getCreateIndexOverExpiryStatementAsString(String indexName)
             return "create index " + indexName + " on " + getSchemaTableName() + " (" + getExpiryTimeColumn() + ")";
         }
 
-        public String getCreateIndexOverSessionStatementAsString(String indexName)
```
Comment (sbordet) [inline jetty-core/jetty-session/src/main/java/org/eclipse/jetty/session/JDBCSessionDataStore.java:279]: It's a public method on a public class. Reinstate and deprecate.

**Review by sbordet — CHANGES_REQUESTED** [review]
LGTM besides the method needs to be reinstated and deprecated.

File: jetty-core/jetty-session/src/main/java/org/eclipse/jetty/session/JDBCSessionDataStore.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-session/src/main/java/org/eclipse/jetty/session/JDBCSessionDataStore.java:279]: Restored and deprecated the method.

File: jetty-core/jetty-session/src/main/java/org/eclipse/jetty/session/JDBCSessionDataStore.java [hunk 2]
```diff
@@ -276,9 +276,13 @@ public String getCreateIndexOverExpiryStatementAsString(String indexName)
...
         }
 
+        /**
+         * @deprecated There is no index over the session anymore.
+         */
+        @Deprecated(forRemoval = true, since = "12.1.6")
         public String getCreateIndexOverSessionStatementAsString(String indexName)
         {
-            return "create index " + indexName + " on " + getSchemaTableName() + " (" + getIdColumn() + ", " + getContextPathColumn() + ")";
+            return "";
```
Comment (sbordet) [inline jetty-core/jetty-session/src/main/java/org/eclipse/jetty/session/JDBCSessionDataStore.java]: I would have left it as it was before.
Point being that it is not called anymore by us, so the return value does not really matter, but if a user called it, perhaps keeping the same value is better.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-session/src/main/java/org/eclipse/jetty/session/JDBCSessionDataStore.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-session/src/main/java/org/eclipse/jetty/session/JDBCSessionDataStore.java]: Restored the previous string.

**Review by sbordet — APPROVED** [review]

**Review by olamy — APPROVED** [review]
