### PR TITLE
Issue #11648 - Introducing HttpDateTime class.

### LINKED ISSUE #11648: Introduce new HttpDateTime class for parsing obsolete Date formats in HTTP and Cookie
**Jetty version(s)**

12

**Jetty Environment**

core

**Java version/vendor** `(use: java -version)`
Oracle jdk 17

**OS type/version**
RHE 9

**Description**

2024-04-11T20:23:36.876Z DEBUG 1 --- [ent@3c5044fa-40] o.e.jetty.client.transport.HttpReceiver  : Notifying header Set-Cookie: LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Fri, 11-Apr-2025 20:23:36 GMT; Max-Age=31536000; secure
2024-04-11T20:23:36.876Z DEBUG 1 --- [ent@3c5044fa-40] o.e.jetty.http.RFC6265SetCookieParser    : could not set attribute expires=Fri

java.time.format.DateTimeParseException: Text 'Fri' could not be parsed at index 0
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:600)
	at org.eclipse.jetty.http.HttpCookie.parseExpires(HttpCookie.java:906)
	at org.eclipse.jetty.http.HttpCookie$Builder.attribute(HttpCookie.java:542)
	at org.eclipse.jetty.http.RFC6265SetCookieParser.setAttribute(RFC6265SetCookieParser.java:200)
	at org.eclipse.jetty.http.RFC6265SetCookieParser.parse(RFC6265SetCookieParser.java:186)
	at org.cometd.client.transport.HttpClientTransport.lambda$storeCookies$0(HttpClientTransport.java:60)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.cometd.client.transport.HttpClientTransport.lambda$storeCookies$1(HttpClientTransport.java:59)
	at java.base/java.util.Map.forEach(Map.java:713)
	at org.cometd.client.transport.HttpClientTransport.storeCookies(HttpClientTransport.java:57)
	at org.cometd.client.http.jetty.JettyHttpClientTransport.access$000(JettyHttpClientTransport.java:52)
	at org.cometd.client.http.jetty.JettyHttpClientTransport$ResponseListener.onHeader(JettyHttpClientTransport.java:239)
	at org.eclipse.jetty.client.transport.ResponseListeners.notifyHeader(ResponseListeners.java:129)
	at org.eclipse.jetty.client.transport.ResponseListeners.notifyHeader(ResponseListeners.java:121)
	at org.eclipse.jetty.client.transport.HttpReceiver.lambda$responseHeader$1(HttpReceiver.java:200)
	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	at org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:117)
	at org.eclipse.jetty.client.transport.HttpReceiver.responseHeader(HttpReceiver.java:189)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parsedHeader(HttpReceiverOverHTTP.java:419)
	at org.eclipse.jetty.http.HttpParser.parsedHeader(HttpParser.java:1109)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1268)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1543)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:312)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parseAndFill(HttpReceiverOverHTTP.java:250)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:76)
	at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:194)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:374)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:147)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:842)

**How to reproduce?**

### PR DESCRIPTION
**Pull request by joakime**
+ Introduces HTTP (and Cookie) Date/Time parsing according to spec algorithms.
+ Introduces formatting according to spec mandated preferred RFC 1123 format.
+ Deprecate DateParser

This an alternative implementation for PR #11658

Fixes: #11648

### CODE REVIEW

**Comment by joakime** [comment]
As of commit f1018899ed26c6eaa7a0636c5cb702911de53e28 these are the performance numbers.

```
Benchmark                                         Mode  Cnt        Score       Error  Units
HttpDateTimeParseBenchmark.testParseDateTimeOld  thrpt   10   348595.650 ± 18537.894  ops/s
HttpDateTimeParseBenchmark.testParseNew          thrpt   10  2028949.555 ± 81101.954  ops/s
```

The `testParseDateTimeOld` is the old `DateParser.parseDate()` behavior.
The `testParseNew` is the new `HttpDateTime.parse()` behavior.

**Review by gregw — APPROVED** [review]
Lgtm

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 1]
```diff
@@ -0,0 +1,229 @@
...
+        // RFC 6265 - Section 5.1.1 - Step 6
+        ZonedDateTime dateTime = ZonedDateTime.of(year,
+            month, day, hour, minute, second, 0,
+            ZoneId.of("GMT"));
+
+        // RFC 6265 - Section 5.1.1 - Step 7
+        return dateTime.toInstant();
+    }
+
+    public static String format(Instant instant)
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Javadoc which format,  zone etc.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 2]
```diff
@@ -0,0 +1,229 @@
...
+        }
+    }
+
+    /**
+     * <p>Parses a Date/Time value</p>
+     *
+     * <p>Supports the following Date/Time formats found in both
+     *  <a href="https://datatracker.ietf.org/doc/html/rfc9110#name-date-time-formats">RFC 9110 (HTTP Semantics)</a> and
+     *  <a href="https://datatracker.ietf.org/doc/html/rfc6265#section-5.1.1">RFC 6265 (HTTP State Management Mechanism)</a>
+     * </p>
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Can you put this into the javadoc for the class.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 3]
```diff
@@ -0,0 +1,229 @@
...
+import org.eclipse.jetty.util.StringUtil;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+/**
+ * HTTP Date/Time parsing and formatting.
+ *
+ * <p>
+ *     Also covers RFC6265 Cookie Date parsing and formatting.
+ * </p>
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Improve this javadoc

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 4]
```diff
@@ -0,0 +1,229 @@
...
+     * <p>
+     *  Parsing is done according to the algorithm specified in
+     *  <a href="https://datatracker.ietf.org/doc/html/rfc6265#section-5.1.1">RFC6265: Section 5.1.1: Date</a>
+     * </p>
+     *
+     * @param datetime a Date/Time string in a supported format
+     * @return an {@link Instant} parsed from the given string
+     * @throws IllegalArgumentException if unable to parse date/time
+     */
+    public static Instant parse(String datetime)
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Can the main method of this class return a ZonedDateTime, then have convenience classes converting that to an epoch or an instance.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 5]
```diff
@@ -0,0 +1,229 @@
...
+     *
+     * @param datetime the Date/Time to parse.
+     * @return unix epoch in milliseconds, or -1 if unable to parse the input date/time
+     */
+    public static long parseToEpoch(String datetime)
+    {
+        try
+        {
+            Instant instant = parse(datetime);
+            return instant.toEpochMilli();
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Add a `ZonedDateTime parse(String)` method to avoid going via an `Instant` instance, as you can directly get the epoch from the `ZonedDateTime`, which is used in parse anyway.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 6]
```diff
@@ -0,0 +1,229 @@
...
+            throw new IllegalArgumentException("Invalid [hour]: " + datetime);
+        if (minute > 59)
+            throw new IllegalArgumentException("Invalid [minute]: " + datetime);
+        if (second > 59)
+            throw new IllegalArgumentException("Invalid [second]: " + datetime);
+
+        // RFC 6265 - Section 5.1.1 - Step 6
+        ZonedDateTime dateTime = ZonedDateTime.of(year,
+            month, day, hour, minute, second, 0,
+            ZoneId.of("GMT"));
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: This should be UTC not GMT and there is a constant available:
```suggestion
            ZoneOffset.UTC;
```

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 7]
```diff
@@ -0,0 +1,229 @@
...
+            throw new IllegalArgumentException("Missing [day]: " + datetime);
+        if (month == (-1))
+            throw new IllegalArgumentException("Missing [month]: " + datetime);
+        if (year == (-1))
+            throw new IllegalArgumentException("Missing [year]: " + datetime);
+        if (hour == (-1))
+            throw new IllegalArgumentException("Missing [time]: " + datetime);
+        if (day < 1 || day > 31)
+            throw new IllegalArgumentException("Invalid [day]: " + datetime);
+        if (month < 1 || month > 31)
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: month should be 1-12 , but in the sequence of the RFC you should be checking year >= 1601

**Review by gregw — CHANGES_REQUESTED** [review]
sorry, on re-review, a couple of things...

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 8]
```diff
@@ -0,0 +1,229 @@
...
+
+        try
+        {
+            int tokenCount = 0;
+            StringTokenizer tokenizer = new StringTokenizer(datetime, "\t" + // %x09
+                " !\"#$%&'()*+,-./" + " + " + // %x20-2F
+                ";<=>?@" + // %x3B-40
+                "[\\]^_`" + // %x5B-60
+                "{|}~" // %x7B-7E
+            );
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: This would be betters as:
```suggestion
            StringTokenizer tokenizer = new StringTokenizer(datetime, DELIMITERS);
            );
```

with the constant defined by the actual hex code and the characters described in the comment:
```java
    private static final String DELIMITERS = 
          "\u0009" // Horizontal Tab
        + "\u0020\u0021\u0022\u0023\u0024\u0025\u0026\u0027\u0028\u0029\u002A\u002B\u002C\u002D\u002E\u002F" // Space through '/'
        + "\u003B\u003C\u003D\u003E\u003F\u0040" // ';' through '@'
        + "\u005B\u005C\u005D\u005E\u005F\u0060" // '[' through '`'
        + "\u007B\u007C\u007D\u007E"; // '{' through '~'
    }
```

Strictly speaking, the constant is not needed, but I think it reads better.   Eitherway, even without the constant, I prefer it if the string is defined by the hex codes, so I can verify against the RFC without needing to lookup the values

**Review by gregw — CHANGES_REQUESTED** [review]
another niggle

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java (hunk 4 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: that doesn't save any code.
in fact it pushes the error handling and epoch handling up into a bunch of other classes that use the parseEpoch right now.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java (hunk 6 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: UTC and GMT are different.

GMT is a Time Zone based on astronomy.
UTC is a time standard representing an offset origin based on atomic clocks.

GMT and UTC are not exactly aligned with time too.
In Java, UTC is represented as a 'Z', while GMT is `GMT`.

`ZoneOffset` is not a `ZoneID` and cannot be used interchangeably.

The `ZonedDateTime` tracks ZoneOffset and ZoneID separately.

Note: if you use a `ZoneOffset` in the date/time APIs you are often required to ALSO provide a `ZoneID`.

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: I know UTC and GMT are different.  The RFC says to use UTC so that is primarily why I commented.  

`ZoneOffset` extends `ZoneID` so it is-a `ZoneID`  and the implementation of `ZoneID.getOffset(long)` is `{return this}`.  So `ZoneOffset.UTC` is a perfectly valid constant `ZoneID` to use.  Feel free to make your own constant for `ZoneId.of("UTC")`, but I think you will find it will just return the `ZoneOffset.UTC` instance anyway!

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Currently you have:
```java
    public static Instant parse(String datetime)
    {
        // ...

        // RFC 6265 - Section 5.1.1 - Step 6
        ZonedDateTime dateTime = ZonedDateTime.of(year,
            month, day, hour, minute, second, 0,
            ZoneId.of("GMT"));

        // RFC 6265 - Section 5.1.1 - Step 7
        return dateTime.toInstant();
    }

    public static long parseToEpoch(String datetime)
    {
        try
        {
            Instant instant = parse(datetime);
            return instant.toEpochMilli();
        }
        catch (IllegalArgumentException e)
        {
            if (LOG.isDebugEnabled())
                LOG.debug("Unable to parse Date/Time: {}", datetime, e);
            return -1;
        }
    }
```

I'm just saying that it will be more flexible and potentially a tiny bit more efficient to have:

```java
    public static ZonedDateTime parse(String datetime)
    {
        // ...

        // RFC 6265 - Section 5.1.1 - Step 6 & 7
        return ZonedDateTime.of(year,
            month, day, hour, minute, second, 0,
            ZoneId.of("GMT"));
    }

    public static Instance parseToInstant(String datetime)
    {
        return parse(datetime).toInstant();
    }

    public static long parseToEpoch(String datetime)
    {
        try
        {
            return TimeUnit.SECONDS.toMillis(parse(datetime).toEpochSeconds());
        }
        catch (IllegalArgumentException e)
        {
            if (LOG.isDebugEnabled())
                LOG.debug("Unable to parse Date/Time: {}", datetime, e);
            return -1;
        }
    }
```

This is a utility class and perhaps somebody wants the ZonedDateTime, so best to make it directly available rather than build one, convert to Instant and then convert back to ZDT with a zone.

Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Got it.  I misunderstood what you were asking for.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 9]
```diff
@@ -0,0 +1,229 @@
...
+                {
+                    // This is a horribly bad syntax / format
+                    throw new IllegalStateException("Too many delimiters for a Date/Time format");
+                }
+
+                if (token.isBlank())
+                    continue; // skip blank tokens
+
+                // RFC 6265 - Section 5.1.1 - Step 2.1 - time (00:00:00)
+                if (hour == (-1) && token.length() == 8 && token.charAt(2) == ':' && token.charAt(5) == ':')
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Please get rid of parens around `-1` everywhere.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 10]
```diff
@@ -0,0 +1,240 @@
...
+        if (hour > 23)
+            throw new IllegalArgumentException("Invalid [hour]: " + datetime);
+        if (minute > 59)
+            throw new IllegalArgumentException("Invalid [minute]: " + datetime);
+        if (second > 59)
+            throw new IllegalArgumentException("Invalid [second]: " + datetime);
+
+        // RFC 6265 - Section 5.1.1 - Step 6
+        ZonedDateTime dateTime = ZonedDateTime.of(year,
+            month, day, hour, minute, second, 0, GMT);
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: This has to be UTC as per the RFC:
>    6.  Let the parsed-cookie-date be the date whose day-of-month, month,
       year, hour, minute, and second (**in UTC**) are the day-of-month-
       value, the month-value, the year-value, the hour-value, the
       minute-value, and the second-value, respectively.  If no such
       date exists, abort these steps and fail to parse the cookie-date.

Further,  [RFC9110 5.6.7](https://datatracker.ietf.org/doc/html/rfc9110#section-5.6.7) it explains:
>    An HTTP-date value represents time as an instance of Coordinated Universal Time (UTC). The first two formats indicate UTC by the three-letter abbreviation for Greenwich Mean Time, "GMT", a predecessor of the UTC name; values in the asctime format are assumed to be in UTC.

So the string is often sent as `GMT` but it is to be interpreted as `UTC`

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 11]
```diff
@@ -0,0 +1,240 @@
...
+     * Formats provided Date/Time to a String following preferred RFC 1123 syntax from
+     * both HTTP and Cookie specs.
+     *
+     * @param datetime the date/time to format
+     * @return the String representation of the date/time
+     */
+    public static String format(TemporalAccessor datetime)
+    {
+        return DateTimeFormatter.RFC_1123_DATE_TIME
+            .withZone(GMT)
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: UTC

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java (hunk 11 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Actually this one should be "GMT", as we are meant to generate as GMT, but interpret as UTC.  I guess theoretically we should format with UTC and replace the "UTC" with "GMT", but that would only be significant during leap seconds.  So I'm fine with GMT here.  But above we should use UTC, as per the specification.

Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: left this as GMT.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java (hunk 10 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Using UTC for parse.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java (hunk 9 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: done

**Review by sbordet — DISMISSED** [review]

**Review by sbordet — DISMISSED** [review]

**Review by sbordet — APPROVED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java (hunk 11 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java]: Reverted this.
Now it's UTC as well.
Also, there are not format() test cases.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java [hunk 12]
```diff
@@ -0,0 +1,248 @@
...
+    /**
+     * Formats provided Date/Time to a String following preferred RFC 1123 syntax from
+     * both HTTP and Cookie specs.
+     *
+     * @param datetime the date/time to format
+     * @return the String representation of the date/time
+     */
+    public static String format(TemporalAccessor datetime)
+    {
+        return DateTimeFormatter.RFC_1123_DATE_TIME
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpDateTime.java:244]: Oh interesting! IT does the hard coded "GMT" for us, even if we pass in "UTC".  Nice!   Well not nice... ugly history in evidence... but at least it is consistent.  The time is in UTC, but just reported as "GMT"!

**Review by gregw — APPROVED** [review]
