### PR TITLE
Issue #11574 war should not be extracted unless configured to do so

### LINKED ISSUE #11574: shibboleth idp webapp under jetty 12.0.7
Reported in email to jetty-users list `Subject: shibboleth idp webapp under jetty 12.0.7`

**12.0.7**

**ee-9**

**Description**

> I'm currently running the shibboleth idp webapp 4 under jetty 9, and
> trying to migrate to idp 5 using jetty 12. I've run into an odd problem,
> I get the following error:
> 
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowRegistry' defined in class path resource [net/shibboleth/idp/conf/webflow-config.xml]: Illegal attempt to register pre-existing flow ID 'authn/DuoOIDC'via resource: URL [jar:file:/var/lib/jetty/tmp/jetty-127_0_0_1-80-idp_war-_idp-any-10824638488520165161/webapp/WEB-INF/lib/idp-plugin-duo-impl-2.0.0.jar!/META-INF/net/shibboleth/idp/flows/authn/DuoOIDC/duo-oidc-authn-flow.xml]
> 
> This generally occurs if there are multiple copies of the jar on the
> classpath, such as if the war accidentally included more than one (which
> isn't the case here).
> 
> The deployment descriptor for the idp app is:
> 
> <Configure class="org.eclipse.jetty.ee9.webapp.WebAppContext">
>         <Set name="war">/opt/shibboleth-idp/war/idp.war</Set>
>         <Set name="contextPath">/idp</Set>
>         <Set name="extractWAR">false</Set>
>         <Set name="copyWebDir">false</Set>
>         <Set name="copyWebInf">true</Set>
> </Configure>
> 
> which is the recommended config per the idp documentation. With this
> config, I see two separate copies of the jar in the jetty tmp directory,
> one in webapp and one in webinf:
> 
> `# find | grep duo`                                                               
> ./webapp/WEB-INF/lib/idp-plugin-duo-nimbus-client-impl-2.0.0.jar               
> ./webapp/WEB-INF/lib/idp-plugin-duo-impl-2.0.0.jar                             
> ./webapp/WEB-INF/lib/idp-plugin-duo-api-2.0.0.jar                               
> ./webinf/WEB-INF/lib/idp-plugin-duo-nimbus-client-impl-2.0.0.jar               
> ./webinf/WEB-INF/lib/idp-plugin-duo-impl-2.0.0.jar                             
> ./webinf/WEB-INF/lib/idp-plugin-duo-api-2.0.0.jar                               
> 
> If I update the config and set copyWebInf=false, there's only one copy
> of the jar in the tmp directory (in webapp) and everything works fine.
> 
> Looking at my existing jetty 9 deployment, there's only the webinf
> directory in the tmp dir, not the webapp one. If I update my jetty 9
> config and set extractWAR=true, then I get the same multiple copies (one
> in webapp, one in webinf) as I do with extractWAR=false in jetty 12,
> although this doesn't cause an error under jetty 9. If I set
> extractWAR=true under jetty 12, I see no change in the content of the
> tmp directory as compared to extractWAR=false.
> 
> So I'm confused. Why is jetty 12 apparently extracting the war when
> extractWAR=false? And when it does, how come the same jar file seems to
> get processed twice, when that doesn't occur under jetty 9 with
> extractWAR=true?
> 
> I'm not sure if I'm hitting a bug or have something misconfigured. It
> seems to be working now with copyWebInf=false, but that also seems more
> of a workaround than a resolution. This feels buggy, that jetty is
> extracting the war when it shouldn't be, and also loading the same jars
> from two different places when the war is extracted *and* copyWebInf=true.
> But I'm far from a jetty expert :).
> 
> Thanks for any hints...

### PR DESCRIPTION
**Pull request by janbartel**
Closes #11574

### CODE REVIEW

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java [hunk 1]
```diff
@@ -51,6 +52,15 @@ public abstract class Resource implements Iterable<Resource>
     private static final Logger LOG = LoggerFactory.getLogger(Resource.class);
     private static final LinkOption[] NO_FOLLOW_LINKS = new LinkOption[]{LinkOption.NOFOLLOW_LINKS};
 
+    public static final Comparator<Resource> COMPARATOR_BY_NAME = new Comparator<Resource>()
```
Comment (joakime) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java]: Duplicate of ... `org.eclipse.jetty.util.resource.ResourceCollators.BY_NAME_ASCENDING`

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java [hunk 2]
```diff
@@ -218,19 +218,19 @@ public void unpack(WebAppContext context) throws IOException
             Resource originalWarResource = webApp;
 
             // Is the WAR usable directly?
-            if (Resources.isReadableFile(webApp) && FileID.isJavaArchive(webApp.getURI()) && !webApp.getURI().getScheme().equalsIgnoreCase("jar"))
+            if (Resources.isReadableFile(webApp) && (FileID.isJavaArchive(webApp.getURI()) || FileID.isWebArchive(webApp.getURI())) && !webApp.getURI().getScheme().equalsIgnoreCase("jar"))
             {
                 // Turned this into a jar URL.
                 Resource jarWebApp = context.getResourceFactory().newJarFileResource(webApp.getURI());
-                if (Resources.isReadableFile(jarWebApp)) // but only if it is readable
+                if (jarWebApp.exists() && jarWebApp.isDirectory())
```
Comment (joakime) [inline jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java]: I think `Resources.isDirectory(jarWebApp)` here is a better fit, it tests for missing + isDirectory (and also the isDirectory impl tests for exists)

File: jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java [hunk 3]
```diff
@@ -218,19 +218,19 @@ public void unpack(WebAppContext context) throws IOException
             Resource originalWarResource = webApp;
 
             // Is the WAR usable directly?
-            if (Resources.isReadableFile(webApp) && FileID.isJavaArchive(webApp.getURI()) && !webApp.getURI().getScheme().equalsIgnoreCase("jar"))
+            if (Resources.isReadableFile(webApp) && (FileID.isJavaArchive(webApp.getURI()) || FileID.isWebArchive(webApp.getURI())) && !webApp.getURI().getScheme().equalsIgnoreCase("jar"))
```
Comment (joakime) [inline jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java]: I wonder if `FileID.isArchive(webApp.getURI())` is a better fit here?
It tests for jar, war, and zip.

Or you can just use `FileID.isExtension(webApp.getURI(), "jar", "war")` instead of 2 calls.

**Review by joakime — CHANGES_REQUESTED** [review]
Some improvements in code

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java]: +1

**Review by lorban — CHANGES_REQUESTED** [review]
Besides `Resource.COMPARATOR_BY_NAME`, LGTM.

**Review by joakime — DISMISSED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java [hunk 4]
```diff
@@ -26,6 +26,7 @@
 import java.time.Instant;
 import java.util.ArrayList;
 import java.util.Collection;
+import java.util.Comparator;
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/Resource.java]: Unneeded import?

**Review by lorban — DISMISSED** [review]
Just one tiny nit left: there's one lookingly useless import to remove; otherwise LGTM.

**Review by gregw — DISMISSED** [review]
