### PR TITLE
Fix NPE from WebSocketSession.getUserPrincipal() in Jetty10

### LINKED ISSUE #5850: NPE at WebSocketSession.java,     public Principal getUserPrincipal() method
**Jetty version**
10.0
**Java version**
11.0
**OS type/version**
Xubuntu 20.04
**Description**

the     WebSocketSession.getUserPrincipal reads for **this.frameHandler.getUpgradeRequest()**
but the JavaxWebSocketFrameHandler.upgradeRequest is null

the setter for upgradeRequest has no reference, and in my debugging, it wasn't called
the method JavaxWebSocketFrameHandlerFactory.newJavaxWebSocketFrameHandler

[https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandlerFactory.java#L116](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandlerFactory.java#L116)

... creates the JavaxWebSocketFrameHandler instance, without setting the upgradeRequest to it, while it receives as a parameter

The actual issue we are facing is that after upgrade from 9.4 jetty to 10.0 jetty, there is a nullpointer exception in a series of Vaadin applications. The error was present with Vaadin 8, Vaadin 14, and Vaadin 18, latest minor versions.

The Vaadin exception occures on first pageload, or login attempts.
I didn't find resources yet on Vaadin jetty upgrades yet, this is quite new, probably few people tried it yet.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Closes #5850**

The `UpgradeRequest` was not set on the `JavaxFrameHandler` for server side upgrades. This causes a NPE when `WebSocketSession.getUserPrincipal()` is called.

Also change the `Upgrade` header sent by the server to use lower case `websocket`, which is the correct usage from RFC6455.

### CODE REVIEW

File: jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandlerFactory.java [hunk 1]
```diff
@@ -165,13 +165,16 @@ public JavaxWebSocketFrameHandler newJavaxWebSocketFrameHandler(Object endpointI
...
-        return new JavaxWebSocketFrameHandler(
+        JavaxWebSocketFrameHandler frameHandler = new JavaxWebSocketFrameHandler(
             container,
             endpoint,
             openHandle, closeHandle, errorHandle,
             textMetadata, binaryMetadata,
             pongHandle,
             config);
+
+        frameHandler.setUpgradeRequest(upgradeRequest);
```
Comment (gregw) [inline jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandlerFactory.java]: Why isn't this done with constructor injection?

Comment (lachlan-roberts) [reply jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandlerFactory.java]: It was because that is how it is done on the Jetty WebSocket side, we set these in `WebSocketNegotiator.negotiate()` so that we have the response available as well, but the response isn't needed on the javax side so we can add this right after we create it.

I have now removed this `setUpgradeRequest()` method, and add the upgrade request in the constructor.

**Review by gregw — APPROVED** [review]
LGTM
