### PR TITLE
Issue #13004 - Warn for bounded thread pool queues

### LINKED ISSUE #13004: QueuedThreadPool throws error on quick successive execute calls if initialized with BlockingArrayQueue or ArrayBlockingQueue
**Jetty version(s)**

Tested on [jetty-12.0.x](https://github.com/jetty/jetty.project/commit/b1fc90f97dd77986ebe24b246c8ec88b65282192) and jetty-11.0.x

**Java version/vendor**
java 24 2025-03-18

**OS type/version**
Windows 10

**Description**
QueuedThreadPool has a hazard of throwing `java.util.concurrent.RejectedExecutionException` if its `execute` method is called multiple times without giving it enough time to assign the Runnable to any thread.
* The use-case is that we want to define a waiting queue with a specific max. size to be used when the max. thread limit is already exceeded.

If it's initialized with any of these queues:
```
new BlockingArrayQueue<>(1)
new ArrayBlockingQueue<>(1)
```
even if the minThreads is 2 and maxThreads is 4, it fails to execute the 2nd Runnable, which should be well within the minThreads capacity.

If it's initialized with
```
new ArrayBlockingQueue<>(1, true)
```
if the minThreads is 2 and maxThreads is 4, it will correctly execute 3 Runnables, because first 2 will go directly to the threads and the 3rd one will go into the blocking queue. However, the 4th execute fails, even though it's still within the maxThreads limit.

* As a workaround, we can add an explicit Thread.sleep before execute to wait for the hazard to resolve itself.

I'd suggest implementing a safer approach, **so that we can rely on the maxThreads parameter**.

**How to reproduce?**

You could add the following test case methods to the codebase. Tests fail when `delayWorkaround` is false and pass when it's true.

Add to [QueuedThreadPoolTest.java](https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java):

```java
import java.util.concurrent.ArrayBlockingQueue;
import org.eclipse.jetty.util.BlockingArrayQueue;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.junit.jupiter.params.provider.ValueSources;
```
...
```java
public class QueuedThreadPoolTest extends AbstractThreadPoolTest
```
...
```java
    @ParameterizedTest
    @ValueSources({@ValueSource(booleans = {false, true})})
    public void testQuickExecutesWithBlockingArrayQueue(boolean delayWorkaround) throws Exception
    {
        QueuedThreadPool tp = new QueuedThreadPool(4, 2, new BlockingArrayQueue<>(1));
        tp.setIdleTimeout(1000);
        tp.setThreadsPriority(Thread.NORM_PRIORITY - 1);

        tp.start();

        // min threads started
        waitForThreads(tp, 2);
        waitForIdle(tp, 2);

        // Doesn't shrink to less than min threads
        Thread.sleep(3L * tp.getIdleTimeout() / 2);
        assertThat(tp.getThreads(), is(2));
        assertThat(tp.getIdleThreads(), is(2));
        assertThat(tp.getQueueSize(), is(0));

        // Run job0
        RunningJob job0 = new RunningJob("JOB0");
        tp.execute(job0);
        assertThat(tp.getThreads(), is(2));
        assertThat(tp.getIdleThreads(), is(1));
        assertThat(tp.getQueueSize(), is(0));

        // Run job1
        if (delayWorkaround) {
            Thread.sleep(100);
        }
        RunningJob job1 = new RunningJob("JOB1");
        tp.execute(job1);
        assertThat(tp.getThreads(), is(2));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(0));

        // Run job2
        RunningJob job2 = new RunningJob("JOB2");
        tp.execute(job2);
        assertThat(tp.getThreads(), is(3));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(0));

        // Run job3
        if (delayWorkaround) {
            Thread.sleep(100);
        }
        RunningJob job3 = new RunningJob("JOB3");
        tp.execute(job3);
        assertThat(tp.getThreads(), is(4));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(0));

        // Check no short term change
        Thread.sleep(100);
        assertThat(tp.getThreads(), is(4));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(0));

        // Run job4
        RunningJob job4 = new RunningJob("JOB4");
        tp.execute(job4);
        assertThat(tp.getThreads(), is(4));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(1));

        // Exceed both limits with job5
        RunningJob job5 = new RunningJob("JOB5");
        try {
            tp.execute(job5);
            Assertions.fail("Should not allow to exceed the blocking queue capacity");
        } catch (RejectedExecutionException e) {
        }
        assertThat(tp.getThreads(), is(4));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(1));

        tp.stop();
    }

    @ParameterizedTest
    @ValueSources({@ValueSource(booleans = {false, true})})
    public void testQuickExecutesWithArrayBlockingQueue(boolean delayWorkaround) throws Exception {
        QueuedThreadPool tp = new QueuedThreadPool(4, 2, new ArrayBlockingQueue<>(1, true));
        tp.setIdleTimeout(1000);
        tp.setThreadsPriority(Thread.NORM_PRIORITY - 1);

        tp.start();

        // min threads started
        waitForThreads(tp, 2);
        waitForIdle(tp, 2);

        // Doesn't shrink to less than min threads
        Thread.sleep(3L * tp.getIdleTimeout() / 2);
        assertThat(tp.getThreads(), is(2));
        assertThat(tp.getIdleThreads(), is(2));
        assertThat(tp.getQueueSize(), is(0));

        // Run job0
        RunningJob job0 = new RunningJob("JOB0");
        tp.execute(job0);
        assertThat(tp.getThreads(), is(2));
        assertThat(tp.getIdleThreads(), is(1));
        assertThat(tp.getQueueSize(), is(0));

        // Run job1
        RunningJob job1 = new RunningJob("JOB1");
        tp.execute(job1);
        assertThat(tp.getThreads(), is(2));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(0));

        // Run job2
        RunningJob job2 = new RunningJob("JOB2");
        tp.execute(job2);
        assertThat(tp.getThreads(), is(3));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(0));

        // Run job3
        if (delayWorkaround) {
            Thread.sleep(100);
        }
        RunningJob job3 = new RunningJob("JOB3");
        tp.execute(job3);
        assertThat(tp.getThreads(), is(4));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(0));

        // Check no short term change
        Thread.sleep(100);
        assertThat(tp.getThreads(), is(4));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(0));

        // Run job4
        RunningJob job4 = new RunningJob("JOB4");
        tp.execute(job4);
        assertThat(tp.getThreads(), is(4));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(1));

        // Exceed both limits with job5
        RunningJob job5 = new RunningJob("JOB5");
        try {
            tp.execute(job5);
            Assertions.fail("Should not allow to exceed the blocking queue capacity");
        } catch (RejectedExecutionException e) {
        }
        assertThat(tp.getThreads(), is(4));
        assertThat(tp.getIdleThreads(), is(0));
        assertThat(tp.getQueueSize(), is(1));

        tp.stop();
    }
```

### PR DESCRIPTION
**Pull request by sbordet**
Added a warning in case the `BlockingQueue` passed to a `ThreadPool` is bounded.

Other miscellaneous cleanups.

### CODE REVIEW

**Comment by sbordet** [comment]
@gregw @lorban what do you think of the `LOG.warn()`?

We could escalate that to an exception thrown in 12.1.x, or is it too much?

**Comment by lorban** [comment]
My preference goes to throwing `IllegalArgumentException`, but that might be a bit too harsh in 12.0.x. But we should definitely do that in 12.1.x IMHO.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 1]
```diff
@@ -44,6 +44,12 @@
 
 /**
  * <p>A thread pool with a queue of jobs to execute.</p>
+ * <p>The queue of jobs should be unbounded, because critical jobs that have been submitted for
+ * execution cannot be rejected by the queue, which may be only temporarily full due to a job
+ * submission spike.
```
Comment (joakime) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]:
```suggestion
 * <p>The queue of jobs should be unbounded, because critical jobs that have been submitted for
 * execution must not be rejected by artificial queue limits.  The queue can be temporarily full
 * due to a job submission spike.
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 2]
```diff
@@ -174,6 +180,8 @@ public QueuedThreadPool(@Name("maxThreads") int maxThreads, @Name("minThreads")
             int capacity = Math.max(_minThreads, 8) * 1024;
             queue = new BlockingArrayQueue<>(capacity, capacity);
         }
+        if (queue.remainingCapacity() != Integer.MAX_VALUE)
+            LOG.warn("A bounded thread pool queue may lead to unexpected behavior, use an unbounded queue instead.");
```
Comment (joakime) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]:
```suggestion
            LOG.warn("Detected a bounded thread pool queue ({}), this can lead to unexpected behavior, use an unbounded queue instead.", TypeUtil.toShortName(queue.getClass()));
```

**Review by joakime — CHANGES_REQUESTED** [review]
Some language changes

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 3]
```diff
@@ -44,6 +44,12 @@
 
 /**
  * <p>A thread pool with a queue of jobs to execute.</p>
+ * <p>The queue of jobs should be unbounded, because critical jobs that have been submitted for
+ * execution cannot be rejected due to the queue bound limit.
+ * The queue may be only temporarily full due to a job submission spike.
```
Comment (joakime) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]:
```suggestion
 * The queue might be temporarily full due to a job submission spike.
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 4]
```diff
@@ -174,6 +180,8 @@ public QueuedThreadPool(@Name("maxThreads") int maxThreads, @Name("minThreads")
             int capacity = Math.max(_minThreads, 8) * 1024;
             queue = new BlockingArrayQueue<>(capacity, capacity);
         }
+        if (queue.remainingCapacity() != Integer.MAX_VALUE)
+            LOG.warn("Detected thread pool queue {} bounded at {} entries, which may lead to unexpected behavior. Use an unbounded queue instead.", queue, queue.remainingCapacity());
```
Comment (joakime) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]:
```suggestion
            LOG.warn("Detected thread pool queue {} bounded at {} entries, which can lead to unexpected behavior. Use an unbounded queue instead.", queue, queue.remainingCapacity());
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ExecutorThreadPool.java [hunk 5]
```diff
@@ -93,6 +97,9 @@ private ExecutorThreadPool(ThreadPoolExecutor executor, int minThreads, int rese
             executor.shutdownNow();
             throw new IllegalArgumentException("max threads (" + maxThreads + ") cannot be less than min threads (" + minThreads + ")");
         }
+        BlockingQueue<Runnable> queue = executor.getQueue();
+        if (queue.remainingCapacity() != Integer.MAX_VALUE)
+            LOG.warn("Detected thread pool queue {} bounded at {} entries, which may lead to unexpected behavior. Use an unbounded queue instead.", queue, queue.remainingCapacity());
```
Comment (joakime) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ExecutorThreadPool.java]:
```suggestion
            LOG.warn("Detected thread pool queue {} bounded at {} entries, which can lead to unexpected behavior. Use an unbounded queue instead.", queue, queue.remainingCapacity());
```

**Review by joakime — CHANGES_REQUESTED** [review]
Don't use `may`, it becomes an awkward read.

**Review by joakime — APPROVED** [review]
