### PR TITLE
Wait for started threads in QueuedThreadPool

### LINKED ISSUE #13100: Improve QueuedThreadPool handling of rejected jobs
**Jetty version(s)**
12.0.x

**Enhancement Description**
In `QueuedThreadPool`, if a job fails to be added to the queue, it is immediately rejected.

This is different from JDK's `ThreadPoolExecutor`, where if the job fails to be added to the queue, there is an attempt at creating one more thread with that job already assigned to it, and only if the thread cannot be created then the job is rejected.

### PR DESCRIPTION
**Pull request by gregw**
Fix #13100 by waiting for newly started threads when offering jobs to the queue.

### CODE REVIEW

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 1]
```diff
@@ -789,47 +802,68 @@ public void execute(Runnable job)
...
         {
-            // reverse our changes to _counts.
-            if (addCounts(-startThread, 1 - startThread))
-                LOG.warn("{} rejected {}", this, job);
-            throw new RejectedExecutionException(job.toString());
+            while (true)
+            {
+                // Spin wait to allow threads to start
+                Thread.onSpinWait();
+                if (_counts.get() != counts)
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: I think this is a good basic approach, that if the queue is full we spin waiting for any started threads to have been started.

HOWEVER! This is the wrong test for that. Counts will only be updated if a Runner completes running a job or if more jobs are queued (and they may be spinning as well).

We don't really have anything we can spin on to ensure a thread is started.

The only other approach I can think of is to start a special Runner that has a reference to the job.  When that Runner takes a job from the queue it will immediately offer the job... but that may still race with other threads adding to the queue.  Perhaps it just keeps the job reference and tries to queue it after every job it takes until it can and then nulls it.

Let me try that.

Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: I've implemented this approach, which I think it better. so this comment will be outdated.

**Comment by gregw** [comment]
@sbordet @lorban I've taken a totally different approach.  If the queue is full, but we are starting a thread, then I start a PendingRunner, we takes on the responsibility of queuing the pendingJob once it has taken a job.

I have no idea how to test this????

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java [hunk 2]
```diff
@@ -333,8 +333,7 @@ private void execute(Runnable task)
         }
         catch (RejectedExecutionException x)
         {
-            if (task instanceof Closeable)
-                IO.close((Closeable)task);
+            // ignored.
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: I'm 50:50 on this one.   Perhaps it is best not to close a job on a REE and let the caller decide?
We close jobs when they cannot be executed after execute returns so REE is no longer an option

thoughts?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ExecutorThreadPool.java [hunk 3]
```diff
@@ -263,7 +264,15 @@ public int getIdleThreads()
...
     public void execute(Runnable command)
     {
-        _executor.execute(command);
+        try
+        {
+            _executor.execute(command);
+        }
+        catch (RejectedExecutionException e)
+        {
+            ThreadPool.reject(command, e);
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/ExecutorThreadPool.java]: 540:50 on this.  See above.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 4]
```diff
@@ -788,48 +778,69 @@ public boolean isLowOnThreads()
...
+            // Start additional threads
+            if (startThread)
+                startThread();
+            return;
         }
 
-        if (!_jobs.offer(job))
+        // The job queue is full!
+
+        // if we are starting a thread, we can use a PendingRunner
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: If we will start a thread, there is no need to spin waiting, we can just create a PendingRunner, which will add it to the queue when it can.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 5]
```diff
@@ -788,48 +778,69 @@ public boolean isLowOnThreads()
...
-            throw new RejectedExecutionException(job.toString());
+            startThread(job);
+            return;
         }
 
-        if (LOG.isDebugEnabled())
-            LOG.debug("queue {} startThread={}", job, startThread);
+        // Otherwise, if we have pending threads started, let's wait for them to start
+        while (_pending.get() > 0)
+            Thread.onSpinWait();
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: This spin is in case a thread started from a previous execute has not yet started.  It is not a 100% fix, as there is still a race between the thread saying it has started and it polling the job queue.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 6]
```diff
@@ -1239,4 +1271,55 @@ private void doRunJob(Runnable job)
...
+                {
+                    job = _pendingJob;
+                    _pendingJob = null;
+                }
+            }
+            else if (_pendingJob != null)
+            {
+                // we took a job from the queue, so offer our pending job
+                if (_jobs.offer(_pendingJob))
+                    _pendingJob = null;
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: This is fine if the offer succeeds... but sub optimal if it fails as the job taken might be a blocking job and block for a long time, thus indefinitely delaying the pending job.

Not sure what else can be done with this approach?

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java [hunk 7]
```diff
@@ -1158,6 +1160,59 @@ public void testRealistic() throws Exception
...
+            new BlockingTask(),
+            new BlockingTask(),
+            new BlockingTask(),
+            new BlockingTask()
+        };
+
+        qtp.execute(tasks[0]);
+        qtp.execute(tasks[1]);
+        qtp.execute(tasks[2]);
+        qtp.execute(tasks[3]);
```
Comment (gregw) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java]: This test captures the essence of the need for this PR.    If you configure a QTP with 2 threads and a bounded queue of 2, then you expect to be able to submit 4 jobs without a REE.   Currently this fails on executing the 4th job as the second thread has yet to start.     This PR "fixes" that, but only by shrinking this window of the race.  I think the race still exists.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java [hunk 8]
```diff
@@ -1158,6 +1160,59 @@ public void testRealistic() throws Exception
...
+
+        // Queue is full!
+        assertThrows(RejectedExecutionException.class, () -> qtp.execute(tasks[4]));
+
+        // Allow one more thread to run
+        qtp.setMaxThreads(3);
+        // Can immediately execute the 5th task
+        qtp.execute(tasks[4]);
```
Comment (gregw) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java]: This is kind of just a static way to trigger the dynamic issue discussed above.

**Comment by gregw** [comment]
@sbordet @lorban @lachlan-roberts 

I'm not 100% convinced by this approach to fix the problem, but I am 100% convinced it is a problem we need to fix.
If you configure a QTP of N threads with a bounded queue of M tasks, then you should be able to execute N+M jobs without a RejectedExecutionException.
Currently the delay between starting a thread and it polling the job queue means that we fail to add to the bound queue because the started thread has not yet taken from the queue.

This PR attempts to fix with 2 strategies: a) spin wait for pending threads to start; b) if starting a threads with a full queue, give it the job to append to the queue after it has taken a job from the queue.

The problem with this approach is that both strategies are still racy.  For a), there is still a window between a thread saying it has started and polling the job queue.  For b) the PendingRunner can race with another thread adding a job to the queue and thus indefinitely delay the pending job.

Perhaps rather than these racy strategies we should just have a pending job queue as well as the real job queue.  We can add some jobs to that queue if we have pending threads being started.  Then all runners will attempt to move jobs from the pending queue to the end of the real queue?

thoughts?

**Comment by sbordet** [comment]
@gregw I like the pending queue approach better, although it has a fixed cost that we will always need to pay (check the pending queue and possibly enqueue).

Note that we will always need to maintain this queue: even when we create all `maxThreads` threads, they can be evicted and the problem will present again: the job queue maxes out, but we have to create more threads to replace the evicted ones.

**Review by sbordet — CHANGES_REQUESTED** [review]
I like better a pending queue approach.

**Comment by gregw** [comment]
@sbordet I think I've found a better way. We atomically know the number of threads and the queue length. If they are at max capacity we reject even before trying the queue. If they are not max, then we spin until we can add as we know there is capacity (modulo checking for other state changes).

I think this approach will be fully atomic and cost little. Stand by....

**Comment by gregw** [comment]
@sbordet I've implemented my new approach and it works either will put (if supported) else it warns and falls back to spinning.
I've done a quick implementation of put on BAQ, but it needs careful review and tests.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 9]
```diff
@@ -146,6 +148,7 @@ public void clear()
             {
                 _headLock.unlock();
             }
+            _notFull.signalAll();
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Just `signal()` is enough.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 10]
```diff
@@ -770,54 +828,59 @@ public int getMaxCapacity()
         return _maxCapacity;
     }
 
-    private boolean grow()
+    private void growTailHeadLocked()
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: We typically prefix "locked", so rename to `lockedHeadGrowTail()`?
But how can we just lock "head", this should lock both tail and head?
It does indeed, so this is just `lockedGrow()`.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 11]
```diff
@@ -185,14 +188,15 @@ public E poll()
                 e = (E)_elements[head];
                 _elements[head] = null;
                 _indexes[HEAD_OFFSET] = (head + 1) % _elements.length;
-                if (_size.decrementAndGet() > 0)
-                    _notEmpty.signal();
+                wasFull = signalSizeHeadLocked();
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: I think this method hides the logic too much.
I tried to remove it, and inlining its implementation makes the core clearer, and the inline is typically only 2-3 lines, so I prefer the little duplication over the need to know what this method is doing.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 12]
```diff
@@ -201,6 +205,8 @@ public E poll()
     public E poll(long time, TimeUnit unit) throws InterruptedException
     {
         long nanos = unit.toNanos(time);
+        E e;
+        boolean wasFull = false;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Unnecessary initialization.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 13]
```diff
@@ -220,19 +226,21 @@ public E poll(long time, TimeUnit unit) throws InterruptedException
...
+            wasFull = signalSizeHeadLocked();
         }
         finally
         {
             _headLock.unlock();
         }
+        if (wasFull)
+        {
+            signal(_tailLock, _notFull);
+        }
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Drop braces.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 14]
```diff
@@ -389,13 +401,14 @@ public boolean offer(E e)
...
             // Should we expand array?
-            if (size == _elements.length)
+            if (_growCapacity > 0 && size == _elements.length)
             {
                 _headLock.lock();
                 try
                 {
-                    if (!grow())
-                        return false;
+                    if (_size.get() >= _maxCapacity && _size.get() != _elements.length)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Here we are fully locked, no need to access `_size` twice.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 15]
```diff
@@ -416,15 +429,7 @@ public boolean offer(E e)
...
-            _headLock.lock();
-            try
-            {
-                _notEmpty.signal();
-            }
-            finally
-            {
-                _headLock.unlock();
-            }
+            signal(_headLock, _notEmpty);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Drop braces.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 16]
```diff
@@ -470,8 +527,9 @@ public void add(int index, E e)
                 else
                 {
                     if (_indexes[TAIL_OFFSET] == _indexes[HEAD_OFFSET])
-                        if (!grow())
+                        if (_growCapacity <= 0 || _size.get() == _maxCapacity)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Brace nested `if` statements for clarity.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 17]
```diff
@@ -514,25 +572,25 @@ public void add(int index, E e)
     }
 
     @Override
-    public void put(E o) throws InterruptedException
+    public void put(E e) throws InterruptedException
     {
-        // The mechanism to await and signal when the queue is full is not implemented
-        throw new UnsupportedOperationException();
+        if (!offer(e, Integer.MAX_VALUE, TimeUnit.SECONDS))
+            throw new RejectedExecutionException();
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: I'd rather have a little duplication and use `_notFull.await()`, rather than throwing `RejectedExecutionException` (see JDK's `ArrayBlockingQueue`).

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 18]
```diff
@@ -514,25 +572,25 @@ public void add(int index, E e)
...
     }
 
     @SuppressWarnings("unchecked")
     @Override
     public E take() throws InterruptedException
     {
+        E e = null;
+        boolean wasFull = false;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Unnecessary initializer.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 19]
```diff
@@ -633,6 +690,7 @@ public int drainTo(Collection<? super E> c, int maxElements)
             {
                 _headLock.unlock();
             }
+            _notFull.signalAll();
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: `signal()` is enough.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 20]
```diff
@@ -764,7 +762,10 @@ public int getMaxAvailableThreads()
     @ManagedAttribute("utilization rate of threads executing unleased jobs")
     public double getUtilizationRate()
     {
-        return (double)getUtilizedThreads() / (getMaxThreads() - getLeasedThreads());
+        int available = getMaxThreads() - getLeasedThreads();
+        if (available <= 0)
+            return available == 0 ? 1.0D : 0.0D;
+        return (double)getUtilizedThreads() / available;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: Unnecessary? The original code was fine.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 21]
```diff
@@ -804,32 +803,78 @@ public void execute(Runnable job)
...
+            }
+            catch (InterruptedException e)
+            {
+                addCounts(0, 1);
+                Thread.currentThread().interrupt();
+                throw new RejectedExecutionException(e);
+            }
+            catch (UnsupportedOperationException uoe)
+            {
+                LOG.warn("Detected bounded thread pool queue {} without put support", _jobs.getClass());
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]:
```suggestion
                LOG.warn("Detected bounded thread pool queue {} without put() support", _jobs.getClass());
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 22]
```diff
@@ -804,32 +803,78 @@ public void execute(Runnable job)
...
+            try
+            {
+                _jobs.put(job);
+                return;
+            }
+            catch (InterruptedException e)
+            {
+                addCounts(0, 1);
+                Thread.currentThread().interrupt();
+                throw new RejectedExecutionException(e);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: Is this enough, or we should call `ThreadPool.reject()` to close the job?
Also in other places.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 23]
```diff
@@ -804,32 +803,78 @@ public void execute(Runnable job)
...
+            catch (UnsupportedOperationException uoe)
+            {
+                LOG.warn("Detected bounded thread pool queue {} without put support", _jobs.getClass());
+                _putSupported = false;
+            }
         }
 
-        if (LOG.isDebugEnabled())
-            LOG.debug("queue {} startThread={}", job, startThread);
+        // Put was not supported, so we will just spin instead
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: I don't think this is a good idea.
We have already been reported in the past about excessive CPU consumption due to spin.
We tried `put()`, now we reject, no spinning.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 24]
```diff
@@ -1152,11 +1197,9 @@ public String toString()
 
     private class Runner implements Runnable
     {
-        private Runnable idleJobPoll(long idleTimeoutNanos) throws InterruptedException
+        Runnable idleJobPoll(long idleTimeoutNanos) throws InterruptedException
         {
-            if (idleTimeoutNanos <= 0)
-                return _jobs.take();
-            return _jobs.poll(idleTimeoutNanos, TimeUnit.NANOSECONDS);
+            return (idleTimeoutNanos <= 0) ? _jobs.take() : _jobs.poll(idleTimeoutNanos, TimeUnit.NANOSECONDS);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: They were on different lines to help debugging/stacktraces/flamegraphs.

**Review by sbordet — CHANGES_REQUESTED** [review]
I don't mind the additional implementation in BAQ, but I don't like the solution.
I think the JDK solution is better and simpler.
Can we not use that solution instead?

**Comment by gregw** [comment]
> I think the JDK solution is better and simpler.
> Can we not use that solution instead?

I tried both ArrayBlockingQueue and LinkedTransferQueue in our QTP jmh tests and they were both an order of magnitude slower (30k/s vs 300k/s).
I also tried a variety of AI suggested queues, including third party ones and got a bit closer (200k/s vs 300k/s) but BAQ is still fastest for QTP

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 20 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: There is a chance that leased threads == max threads (not a great config but possible).  This change avoids a divide by zero.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 22 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: That was my first change in this PR, to always reject (close) when we throw REE.  But we do have places in the code that already catch and do that.    So I ended up thinking that we should not tell the app the same thing twice - i.e. we should not both close and throw.  We should either throw in execute, or if we return from execute, then we close if we cannot do it.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 23 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: Hmmm maybe. We do warn and its not a bad spin and I do throttle.     So I'll leave it in for now...   Perhaps we need to see how many Q implementations do not have put?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java (hunk 10 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: we we sometimes just have the head lock or the tail lock.  This requires both, so I thought that should be clear in the name???

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java (hunk 19 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Is it?  If we have multiple threads waiting on notFull, then signal will only start one and the rest may wait forever unless the Q fills up again.  
We could signal notFull on every take, but then that is more work and we'd have to do N signals here.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java (hunk 9 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: I don't think so. See other reply.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 20 above)
Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: I don't think it is possible that leasedThreads==maxThreads, as there would be no "worker" threads, so it would be an illegal configuration, see `ThreadPoolBudget.check()`.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 25]
```diff
@@ -514,25 +629,75 @@ public void add(int index, E e)
...
+                        _headLock.unlock();
+                    }
+                }
+
+                // We can add now after a possible grow
+                int tail = _indexes[TAIL_OFFSET];
+                _elements[tail] = e;
+                _indexes[TAIL_OFFSET] = (tail + 1) % _elements.length;
+                wasEmpty = _size.getAndIncrement() == 0;
+                if (size + 1 < _maxCapacity)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: I think you should "refresh" `size` from the `_size` field when you increment.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 26]
```diff
@@ -670,8 +673,9 @@ else if (_growCapacity > 0 && size == _elements.length)
                 int tail = _indexes[TAIL_OFFSET];
                 _elements[tail] = e;
                 _indexes[TAIL_OFFSET] = (tail + 1) % _elements.length;
-                wasEmpty = _size.getAndIncrement() == 0;
-                if (size + 1 < _maxCapacity)
+                int oldSize = _size.getAndIncrement();
+                wasEmpty = oldSize == 0;
+                if (oldSize + 1 < _maxCapacity)
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: This pattern is being repeated, so maybe it should be extracted to a new private method, like `boolean tailLockedIncrementSizeAndSignalIfNotFull()`?

That method could also add a lock held assertion.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 27]
```diff
@@ -272,9 +272,9 @@ public E poll(long time, TimeUnit unit) throws InterruptedException
             _elements[head] = null;
             _indexes[HEAD_OFFSET] = (head + 1) % _elements.length;
 
-            int size = _size.getAndDecrement();
-            wasFull = size == _maxCapacity;
-            if (size > 1)
+            int oldSize = _size.getAndDecrement();
+            wasFull = oldSize == _maxCapacity;
+            if (oldSize > 1)
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: This pattern is being repeated, so maybe it should be extracted to a new private method, like `boolean headLockedDecrementSizeAndSignalIfNotEmpty()`?

That method could also add a lock held assertion.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java:1]: In `add()` line 596 of the new version, `size = _size.incrementAndGet();` could be moved down right before the checks for notEmpty and notFull signaling is done so that related changes are co-located; like in `remove()` line 361.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 28]
```diff
@@ -216,7 +218,7 @@ public E poll()
 
         E e = null;
         boolean wasFull = false;
-        _headLock.lock(); // Size cannot shrink
+        _headLock.lock(); // Size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Maybe that comment should be moved next to the `_headLock` field, and add the corollary `Size can shrink but not grow when this lock is held` next to the `_tailLock` field?

**Review by lorban — CHANGES_REQUESTED** [review]
I only reviewed the BAQ so far. I think it is now correct, but we could extract all the size-modifying logic to a trio of methods for extra safety and clarity.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java (hunk 26 above)
Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: I prefer the code not to be moved away to another method, so all the code is in the place it belongs to.
In this case, I don't mind a little duplication to get more clarity.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java (hunk 27 above)
Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java (hunk 28 above)
Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: I'm fine with the comment at the field, but a reminder here helps.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 29]
```diff
@@ -407,34 +464,87 @@ public boolean offer(E e)
...
-                _notEmpty.signal();
-            }
-            finally
-            {
-                _headLock.unlock();
-            }
-        }
+        if (wasEmpty)
+            // We signalAll here because there may be many threads waiting to take,
+            // this is more efficient than always grabbing the head lock to always signal 1.
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Remove obsolete comment.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 30]
```diff
@@ -407,34 +464,87 @@ public boolean offer(E e)
...
+            }
+        }
+        finally
+        {
+            _tailLock.unlock();
+        }
+
+        if (wasEmpty)
+            // We signalAll here because there may be many threads waiting to take,
+            // this is more efficient than always grabbing the head lock to always signal 1.
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Remove obsolete comment.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 31]
```diff
@@ -770,54 +926,60 @@ public int getMaxCapacity()
...
-                _elements = elements;
-                _indexes[HEAD_OFFSET] = 0;
-                _indexes[TAIL_OFFSET] = newTail;
-                return true;
-            }
-            finally
-            {
-                _headLock.unlock();
-            }
+    private void signalAll(Lock lock, Condition condition)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Never used, remove.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 32]
```diff
@@ -764,7 +762,10 @@ public int getMaxAvailableThreads()
     @ManagedAttribute("utilization rate of threads executing unleased jobs")
     public double getUtilizationRate()
     {
-        return (double)getUtilizedThreads() / (getMaxThreads() - getLeasedThreads());
+        int available = getMaxThreads() - getLeasedThreads();
+        if (available <= 0)
+            throw new IllegalStateException("too many leased threads");
+        return (double)getUtilizedThreads() / available;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: Unnecessary, cannot be that `maxThread==leasedThreads` since `ThreadPoolBudget` avoids that.
I'd restore the old code.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java [hunk 33]
```diff
@@ -804,32 +803,78 @@ public void execute(Runnable job)
...
+            }
+            catch (InterruptedException e)
+            {
+                addCounts(0, 1);
+                Thread.currentThread().interrupt();
+                throw new RejectedExecutionException(e);
+            }
+            catch (UnsupportedOperationException uoe)
+            {
+                LOG.warn("Detected bounded thread pool queue {} without put() support", _jobs.getClass());
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: If `put()` is not implemented, we will get this WARN a million times in the logs.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 23 above)
Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: I'd really take it out.
If someone complains, then we can add it back, but it's the rare case of a rare case that will bite us back.
I'd prefer fail fast and reject.
`parkNanos()` will also spin, so now we are double-spinning, so I'd remove the spin.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java (hunk 26 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: There is a lot of code duplication.  I had refactored into some common methods, but @sbordet asked me to inline them.
However, I'm not exactly sure inlining does give clarity.  I will named one liner can be clearer than 5 repeated lines that you can't tell if they are exactly the same as the next repetition or not.

I'll have a try to see if I can find a mid ground.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java (hunk 27 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 33 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: No, only once because of the boolean below

**Comment by gregw** [comment]
@sbordet I sided with @lorban over having small utility methods.   Having duplicate code was OK when there were only 2 methods, but now we are implementing all the methods, I think it is clearer to have those private methods.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java (hunk 33 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/QueuedThreadPool.java]: No it was protected from that.... but removed now anyway

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 34]
```diff
@@ -770,57 +897,107 @@ public int getMaxCapacity()
         return _maxCapacity;
     }
 
-    private boolean grow()
+    private void lockedGrow()
     {
-        if (_growCapacity <= 0)
-            return false;
+        final int head = _indexes[HEAD_OFFSET];
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java:767]: Please add an `assert` to check that both locks are held.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 35]
```diff
@@ -770,57 +897,107 @@ public int getMaxCapacity()
...
     }
 
+    /**
+     * Add an element to the tail of the queue with the tail lock held.
+     * The size must be &lt; max capacity when this method is called.
+     * @param e the element to add
+     */
+    private void lockedAddToTail(E e)
+    {
+        int tail = _indexes[TAIL_OFFSET];
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java:812]: Please assert that the lock is held.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 36]
```diff
@@ -770,57 +897,107 @@ public int getMaxCapacity()
...
+    }
+
+    /**
+     * Take an element from the head of the queue with the head lock held.
+     * The size must be &gt; 0 when this method is called.
+     * @return the head element
+     */
+    private E lockedTakeFromHead()
+    {
+        final int head = _indexes[HEAD_OFFSET];
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java:825]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 37]
```diff
@@ -770,57 +897,107 @@ public int getMaxCapacity()
...
+    }
+
+    /**
+     * Increment size under tail lock.
+     * Signal {@link #_notFull} if size remains &lt; max capacity.
+     * @return true if the queue was empty prior to the increment
+     */
+    private boolean lockedIncrementSize()
+    {
+        boolean wasEmpty;
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java:842]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 38]
```diff
@@ -770,57 +897,107 @@ public int getMaxCapacity()
...
+    }
+
+    /**
+     * Decrement size under head lock.
+     * Signal {@link #_notEmpty} if size remains &gt; 0.
+     * @return true if the queue was full prior to the decrement
+     */
+    private boolean lockedDecrementSize()
+    {
+        boolean wasFull;
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java:859]: ditto

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java [hunk 39]
```diff
@@ -1158,6 +1160,57 @@ public void testRealistic() throws Exception
         qtp.stop();
     }
 
+    @Test
+    public void testBoundedQueue() throws Exception
+    {
+        LoggerFactory.getLogger(QueuedThreadPool.class).warn("Bound queue warnings expected");
```
Comment (lorban) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java:1166]: You could silence the warnings of BAQ instead.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 40]
```diff
@@ -270,10 +317,10 @@ public E remove()
     @Override
     public E remove(int index)
     {
-        _tailLock.lock();
+        _tailLock.lock(); // _size cannot grow but can shrink
         try
         {
-            _headLock.lock();
+            _headLock.lock(); // _size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: I'd change the comment to: `both locks are held, _size can either grow or shrink`

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 41]
```diff
@@ -325,10 +376,10 @@ public E remove(int index)
     @Override
     public boolean remove(Object o)
     {
-        _tailLock.lock();
+        _tailLock.lock(); // _size cannot grow but can shrink
         try
         {
-            _headLock.lock();
+            _headLock.lock(); // _size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 42]
```diff
@@ -380,61 +431,101 @@ public boolean offer(E e)
...
             int size = _size.get();
             if (size >= _maxCapacity)
                 return false;
 
             // Should we expand array?
-            if (size == _elements.length)
+            if (_growCapacity > 0 && size == _elements.length)
             {
-                _headLock.lock();
+                _headLock.lock(); // _size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 43]
```diff
@@ -380,61 +431,101 @@ public boolean offer(E e)
...
+                {
+                    if (nanos <= 0L)
+                        return false;
+                    nanos = _notFull.awaitNanos(nanos);
+                    continue; // recheck size
+                }
+                // Otherwise, can we grow?
+                else if (_growCapacity > 0 && size == _elements.length)
+                {
+                    _headLock.lock(); // _size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 44]
```diff
@@ -452,13 +543,13 @@ public void add(int index, E e)
         if (e == null)
             throw new NullPointerException();
 
-        _tailLock.lock();
+        _tailLock.lock(); // _size cannot grow but can shrink
         try
         {
-            _headLock.lock();
+            _headLock.lock(); // _size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 45]
```diff
@@ -514,71 +613,96 @@ public void add(int index, E e)
...
+                // If we are full, then we can wait for space to become available
+                if (size >= _maxCapacity || (_growCapacity <= 0 && size == _elements.length))
+                {
+                    _notFull.await();
+                    continue; // recheck size
+                }
+                // Otherwise, can we grow?
+                else if (_growCapacity > 0 && size == _elements.length)
+                {
+                    _headLock.lock(); // _size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 46]
```diff
@@ -591,10 +715,10 @@ public int drainTo(Collection<? super E> c)
     public int drainTo(Collection<? super E> c, int maxElements)
     {
         int elements = 0;
-        _tailLock.lock();
+        _tailLock.lock(); // _size cannot grow but can shrink
         try
         {
-            _headLock.lock();
+            _headLock.lock(); // _size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 47]
```diff
@@ -647,10 +774,10 @@ public int drainTo(Collection<? super E> c, int maxElements)
     @Override
     public E get(int index)
     {
-        _tailLock.lock();
+        _tailLock.lock(); // _size cannot grow but can shrink
         try
         {
-            _headLock.lock();
+            _headLock.lock(); // _size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 48]
```diff
@@ -678,10 +805,10 @@ public E set(int index, E e)
     {
         Objects.requireNonNull(e);
 
-        _tailLock.lock();
+        _tailLock.lock(); // _size cannot grow but can shrink
         try
         {
-            _headLock.lock();
+            _headLock.lock(); // _size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 49]
```diff
@@ -709,10 +836,10 @@ public E set(int index, E e)
     @Override
     public ListIterator<E> listIterator(int index)
     {
-        _tailLock.lock();
+        _tailLock.lock(); // _size cannot grow but can shrink
         try
         {
-            _headLock.lock();
+            _headLock.lock(); // _size can grow but not shrink
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: ditto

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java [hunk 50]
```diff
@@ -67,11 +107,23 @@ public class BlockingArrayQueue<E> extends AbstractList<E> implements BlockingQu
...
+     * The head lock is only acquired when taking entries from the queue, thus when held, the size can shrink but not grow.
+     */
     private final Lock _headLock = new ReentrantLock();
     private final Condition _notEmpty = _headLock.newCondition();
-    private Object[] _elements;
+    /**
+     * Lock for tail operations.
+     * The tail lock is only acquired when adding entries to the queue, thus when held, the size can grow but not shrink.
+     */
+    private final Lock _tailLock = new ReentrantLock();
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BlockingArrayQueue.java]: Could you please add a comment to say that when both locks are needed, they must always be taken in order: tail first, head second.

**Review by lorban — CHANGES_REQUESTED** [review]
Looks good, except for a number of places where I'd add/change the comments and add some assertions.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java (hunk 39 above)
Comment (gregw) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/QueuedThreadPoolTest.java:1166]: I like seeing such non-verbose (no stack trace) warnings in the log

**Review by lorban — DISMISSED** [review]

**Review by sbordet — APPROVED** [review]
I was unhappy with the comments around the locking of BAQ, as they were inconsistent: sometimes referring to whether the size could shrink/grow, etc.

Replaced the locking using `AutoLock.WithCondition`, much more readable.

LGTM.
