### PR TITLE
Fix #6883 relative welcome redirect (#6886)

### LINKED ISSUE #6883: Welcome file redirects do not honor the relativeRedirectAllowed option
**Jetty version(s)**

9.4.43.v20210629

**Java version/vendor** `(use: java -version)`

openjdk version "11.0.12" 2021-07-20 LTS

**OS type/version**

macOS Big Sur 11.6 (20G165)

**Description**

Last year #5029 Relative Redirection introduced a new `relativeRedirectAllowed` option. (Thanks!) Unfortunately, at least some of the redirects that Jetty itself initiates do not yet honor that option.

For instance, `org.eclipse.jetty.server.ResourceService.sendWelcome` (the method that redirects to add a missing trailing slash if necessary) builds an absolute redirect URL. But `org.eclipse.jetty.server.Response` only honors `HttpConfiguration.isRelativeRedirectAllowed()` if the redirect URL is relative (includes no scheme).

This behavior is problematic for us because in some environments, we use a reverse proxy or load balancer in front of Jetty for SSL termination. As a result, https: requests look to Jetty like http: requests, so it ends up redirecting some https: requests to http: in order to add a trailing slash.

**How to reproduce?**

1. Allow relative redirects by calling `httpConfiguration.setRelativeRedirectAllowed(true)`.
2. Register a servlet at a path like "/docs/*".
3. Issue a GET /docs request.
4. Notice that the Location header in the response contains an absolute URL (containing a scheme and host) instead of just a relative URL such as just "/docs/".

### PR DESCRIPTION
**Pull request by gregw**
Cheery pick 9 to 10

Fix #6883 relative welcome redirect
 + make all redirects able to be relative
 + added test for relative redirection in ResourceService

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Comment by joakime** [comment]
Need to fix the license header

File: tests/jetty-http-tools/src/main/java/org/eclipse/jetty/http/tools/matchers/HttpFieldsHeaderValue.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
+//
+//  ========================================================================
+//  Copyright (c) 1995-2021 Mort Bay Consulting Pty Ltd and others.
+//  ------------------------------------------------------------------------
+//  All rights reserved. This program and the accompanying materials
+//  are made available under the terms of the Eclipse Public License v1.0
+//  and Apache License v2.0 which accompanies this distribution.
+//
+//      The Eclipse Public License is available at
+//      http://www.eclipse.org/legal/epl-v10.html
```
Comment (joakime) [inline tests/jetty-http-tools/src/main/java/org/eclipse/jetty/http/tools/matchers/HttpFieldsHeaderValue.java]: This is the wrong license header for Jetty 10.0.x

**Review by joakime — CHANGES_REQUESTED** [review]
License header needs to be fixed

**Review by joakime — APPROVED** [review]
