### PR TITLE
Fixes #11016 - Jetty 12 IllegalStateException when stopping Server wi…

### LINKED ISSUE #10944: Flaky test `MultiPartServletTest.testMultiPartGzip`
**Jetty version(s)**
12.0.x

**Jetty Environment**
ee10

**Description**
`org.eclipse.jetty.ee10.servlet.MultiPartServletTest.testMultiPartGzip` sometimes fails with:

```
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.client.InputStreamResponseListener$Input.read(InputStreamResponseListener.java:304)
	at java.base/java.io.InputStream.read(InputStream.java:218)
	at org.eclipse.jetty.client.InputStreamResponseListener$Input.read(InputStreamResponseListener.java:279)
	at java.base/java.util.zip.CheckedInputStream.read(CheckedInputStream.java:59)
	at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:266)
	at java.base/java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
	at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.MultiPartServletTest.testMultiPartGzip(MultiPartServletTest.java:429)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:670)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io@12.0.4-SNAPSHOT/org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:167)
	at org.eclipse.jetty.io@12.0.4-SNAPSHOT/org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

When the test fails, the console contains this:

```
2023-11-29 06:14:45.499:INFO :oejs.Server:ForkJoinPool-1-worker-1: Stopped oejs.Server@3fbc5630{STOPPING}[12.0.4-SNAPSHOT,sto=0]
2023-11-29 06:14:45.500:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-1: Stopped ServerConnector@71fff4f{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
2023-11-29 06:14:45.500:INFO :oejes.ServletContextHandler:ForkJoinPool-1-worker-1: Stopped oeje10s.ServletContextHandler@4fab223f{ROOT,/,b=null,a=AVAILABLE,h=GzipHandler@4995fe0{STOPPED,min=32,inflate=-1}}
2023-11-29 06:14:48.000:WARN :oeju.Blocker:qtp280894807-2683: Blocking.Shared incomplete
2023-11-29 06:14:48.001:WARN :oejs.Request:qtp280894807-2683: org.eclipse.jetty.ee10.servlet.ServletContextHandler$$Lambda$696/0x00000007c030bb38@70d2a834 threw
java.lang.IllegalStateException: s=HANDLING rs=BLOCKING os=ABORTED is=IDLE awp=false se=false i=true al=0
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannelState.recycle(ServletChannelState.java:1055)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.recycle(ServletChannel.java:417)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.CompletionStreamWrapper.onCompletion(CompletionStreamWrapper.java:74)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.CompletionStreamWrapper.failed(CompletionStreamWrapper.java:53)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.completeStream(HttpChannelState.java:704)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.failed(HttpChannelState.java:673)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.failed(HttpChannelState.java:1470)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.gzip.GzipResponseAndCallback.failed(GzipResponseAndCallback.java:115)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.abort(ServletChannel.java:834)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.handleException(ServletChannel.java:689)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:612)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:716)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.EagerFormHandler.lambda$handle$0(EagerFormHandler.java:73)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.eclipse.jetty.io@12.0.4-SNAPSHOT/org.eclipse.jetty.io.content.ContentSourceCompletableFuture.parse(ContentSourceCompletableFuture.java:107)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1208)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.ContextRequest$OnContextDemand.run(ContextRequest.java:74)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection$DemandContentCallback.succeeded(HttpConnection.java:690)
	at org.eclipse.jetty.io@12.0.4-SNAPSHOT/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io@12.0.4-SNAPSHOT/org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

See: https://jenkins.webtide.net/job/jetty.project/job/jetty-12.0.x/1714/testReport/junit/org.eclipse.jetty.ee10.servlet/MultiPartServletTest/Parallel_Stage___Build___Test___JDK17___testMultiPartGzip_boolean__1__true/

### LINKED ISSUE #11016: IllegalStateException when stopping Server with pending requests
**Jetty version(s)**
12+

**Jetty Environment**
ee10

**Description**
Stopping a `Server` when a request is suspended, for example in case of a "long-polling" request yields:

```
java.lang.IllegalStateException: s=HANDLING rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannelState.recycle(ServletChannelState.java:1086)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.recycle(ServletChannel.java:418)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.CompletionStreamWrapper.onCompletion(CompletionStreamWrapper.java:74)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.CompletionStreamWrapper.failed(CompletionStreamWrapper.java:53)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.completeStream(HttpChannelState.java:704)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.failed(HttpChannelState.java:673)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$ErrorCallback.failed(HttpChannelState.java:1636)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.Callback$Nested.failed(Callback.java:429)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.lambda$failed$2(HttpChannelState.java:1241)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:117)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.failed(HttpChannelState.java:1241)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection$SendCallback.reset(HttpConnection.java:759)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.send(HttpConnection.java:1421)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.HttpStream$Wrapper.send(HttpStream.java:179)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1181)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.Response$Wrapper.write(Response.java:693)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.ContextResponse.write(ContextResponse.java:56)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.HttpOutput.channelWrite(HttpOutput.java:204)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.HttpOutput.complete(HttpOutput.java:435)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletContextResponse.completeOutput(ServletContextResponse.java:209)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:588)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1202)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1195)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannelState.runInContext(ServletChannelState.java:1213)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannelState.complete(ServletChannelState.java:743)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.AsyncContextState.complete(AsyncContextState.java:61)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.AsyncServletLongPollTest$2.destroy(AsyncServletLongPollTest.java:193)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletHolder.destroyInstance(ServletHolder.java:464)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletHolder.doStop(ServletHolder.java:441)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletHandler.doStop(ServletHandler.java:298)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.Handler$Abstract.doStop(Handler.java:476)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler.lambda$doStop$1(ContextHandler.java:686)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1141)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:686)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:1324)
	at org.eclipse.jetty.ee10.servlet@12.0.4-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStop(ServletContextHandler.java:1075)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
	at org.eclipse.jetty.util@12.0.4-SNAPSHOT/org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.Handler$Abstract.doStop(Handler.java:476)
	at org.eclipse.jetty.server@12.0.4-SNAPSHOT/org.eclipse.jetty.server.Server.doStop(Server.java:669)
```

### PR DESCRIPTION
**Pull request by sbordet**
…th pending requests

* Made ServletChannel error handling more robust. A failure in error handling is now remembered so that the Handler callback can be failed later.
* Avoid failing the Handler callback from ServletChannel.abort(), as it is too early: should be failed when processing the TERMINATED state, similarly to when it is succeeded.
* Removed dead code from HttpConnection.SendCallback.reset(), since response is always non-null.

### CODE REVIEW

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java [hunk 1]
```diff
@@ -777,8 +771,11 @@ public void onCompleted()
 
         // Callback will either be succeeded here or failed in abort().
         Callback callback = _callback;
-        if (_state.completeResponse())
+        Throwable failure = _state.completeResponse();
+        if (failure == null)
             callback.succeeded();
+        else
+            callback.failed(failure);
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java:745]: comment above is now wrong

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 2]
```diff
@@ -292,19 +293,13 @@ public String getStatusString()
         }
     }
 
-    public boolean completeResponse()
+    public Throwable completeResponse()
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:297]: The boolean return was giving protection against calling this method twice.
So either, there is a possibility that we will call it twice, in which case we still need the protection....
OR we will never call it twice, so instead we should throw ISE if we are ever called with it is already in COMPLETED state.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 3]
```diff
@@ -334,15 +329,37 @@ public boolean abortResponse()
                 case OPEN:
                     _servletChannel.getServletContextResponse().setStatus(HttpStatus.INTERNAL_SERVER_ERROR_500);
                     _outputState = OutputState.ABORTED;
+                    _failure = failure;
                     return true;
 
                 default:
                     _outputState = OutputState.ABORTED;
+                    _failure = failure;
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:338]: Perhaps the state should now be called `FAILED`?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 4]
```diff
@@ -559,19 +576,25 @@ public void errorHandling()
         }
     }
 
-    public void errorHandlingComplete()
+    public void errorHandlingComplete(Throwable failure)
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: some javadoc explaining when this is called would be worthwhile.  Specifically it is called when the callback passed to the ErrorHandler.handle method has been completed.    This is either because a core handler has completed handling the response;
OR the request has been passed to a servlet and it has completed the response;
OR the request has been passed to a servlet and it changed state with `startAsync` or `sendError`, so we now need to handle those servlet mechanism.

This last one is a little strange, as we normally avoid calling a Callback passed to a handler until the request/response processing is truly complete. But since we don't have a callback passed to the Servlet, we have to infer if it is complete or not by looking at the state. If it is still in ERRORING state, then the servlet did not change state and we are complete, else we are starting a new servlet dispatch lifecycle!   Hmm I wonder if the ErrorHandler that dispatches to  should really do this. Hmmm but it doesn't have ServletChannelState access?

Also need to document that the `failure` is a failure generated when calling the errorHandler.   Perhaps name it `errorHandlerFailure`?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 5]
```diff
@@ -559,19 +576,25 @@ public void errorHandling()
...
                 _state = State.WOKEN;
+
+            // If there is a failure while trying to
+            // handle a previous failure, just bail out.
+            if (failure != null)
+                abortResponse(failure);
+
             if (_requestState == RequestState.ERRORING)
-                _requestState = RequestState.COMPLETE;
+                _requestState = failure == null ? RequestState.COMPLETE : RequestState.COMPLETED;
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: Need a comment to explain this, as I can't get my head around it (even though I think I suggested it).

If the requestState is still in ERRORING, then it means the ErrorHandler did not change it's state, so therefore `startAsync` or `sendError` have not been called. 

is `failure == null` the right test?  should it not be testing is we are in an async cycle?   Also how can failure be non-null give the test directly above?  something is not right here?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 6]
```diff
@@ -334,15 +329,37 @@ public boolean abortResponse()
                 case OPEN:
                     _servletChannel.getServletContextResponse().setStatus(HttpStatus.INTERNAL_SERVER_ERROR_500);
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: This feels arbitrary and in the wrong spot.

**Review by gregw — CHANGES_REQUESTED** [review]
Mostly just more comments/javadoc needed... but I think there may be a problem with

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 2 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:297]: This method is only called once because it is protected by the `ServletChannel` state machine.
From `ServletChannel.handle()`, we end up in the `TERMINATED` state where we call `onCompleted()` that calls this method.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 3 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:338]: The method is still called `abortResponse()`, so I'd leave it as it is.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 5 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: I changed it to just COMPLETE.

The reason for the check was that if we failed hard trying to write an error page, there is no point going to COMPLETE and trying to flush the `HttpOutput`, so we just go to COMPLETED.

However, there should be no hard trying to flush `HttpOutput` as it can fail in other circumstances and its failure should be handled properly by going to COMPLETED and then terminating.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 4 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: Starting a new Servlet lifecycle from an `ErrorHandler` is fine and we have tests, see ee10 `ErrorPageTest`.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 6 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: Removed.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 2 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:297]: So can we have an assert (or ISE) if it is already in COMPLETED state

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java [hunk 7]
```diff
@@ -735,10 +729,13 @@ public void onCompleted()
             _servletContextRequest.setAttribute(CustomRequestLog.LOG_DETAIL, logDetail);
         }
 
-        // Callback will either be succeeded here or failed in abort().
+        // Callback is completed here.
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java]: Can we say:
```suggestion
        // Callback is only completed here.
```

**Review by gregw — DISMISSED** [review]
All good, but a couple of nigglets.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 2 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:297]: Not sure what you refer to, as there are many COMPLETED states?
If you refer to `_outputState` it can also be ABORTED.
I feel like we don't need this extra assert, as we just want to make the transition OPEN -> COMPLETED.

Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:297]: This method used to return a boolean that indicated if it had just transitioned from OPEN->COMPLETED.  If it returned false, then the callback would not be completed.

Now it returns a throwable to say if there has been a failure, in which case the callback is failed.   But it has lost the protection for multiple calls, so the callback might be called twice.   

I understand that you know this cannot happen because of external factors.... that nothing in this method represents that invariant.   It would be clearer if it had something like:
```java
    assert _failure != null || _outputState == OutputState.OPEN
```

If this assert does not hold, then this PR has changed behaviour in a non obvious way.

**Review by gregw — DISMISSED** [review]
