### PR TITLE
Make the `Content.Chunk.isTerminal()` contract stricter

### LINKED ISSUE #8993: `Content.Chunk.isTerminal()` cannot discriminate `EOF` from chunks containing a pooled empty buffer
**Jetty version(s)**
12.0.x

**Description**
`Content.Chunk.isTerminal()` has a contract that allows some ambiguity: it is not possible to distinguish a `Content.Chunk` that contains a pool-acquired zero-byte buffer and is last from `Content.Chunk.EOF`.

Since `Content.Chunk.EOF.retain()` throws `UnsupportedOperationException`, each time a new chunk is read and before it is wrapped, it must be checked to make sure it isn't `EOF` as `retain()` cannot be called on the latter.

We currently use `isTerminal()` to perform that check but since it cannot discriminate `EOF` from an empty-and-last chunk we either leak the chunk's buffer or double-release it.

The `Content.Chunk` creation, `isTerminal()` and `Retainable` contracts should be reworked to lift this ambiguity.

### PR DESCRIPTION
**Pull request by lorban**
Make the `Content.Chunk.isTerminal()` contract stricter by explicitly disallowing the creation of new last chunks with an empty `ByteBuffer`.

Also replace non-last empty chunks with EMPTY where it makes  sense.

Closes #8993

### CODE REVIEW

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java [hunk 1]
```diff
@@ -50,7 +50,9 @@ public class AsyncContent implements Content.Sink, Content.Source, Closeable
     @Override
     public void write(boolean last, ByteBuffer byteBuffer, Callback callback)
     {
-        write(Content.Chunk.from(byteBuffer, last, callback::succeeded), callback);
+        boolean terminal = !byteBuffer.hasRemaining() && last;
+        Content.Chunk chunk = terminal ? Content.Chunk.EOF : Content.Chunk.from(byteBuffer, last, callback::succeeded);
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: Doesn't this imply that callback succeeded will get called twice? Once for the chunk release and again when the write succeeds?

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: Hmmm it always did... Still a good question?

**Review by gregw — APPROVED** [review]
I like the change. But it raises a question about calling succeeded twice?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: The short answer to your question is no, but you spotted the opposite bug nevertheless: when the chunk is replaced by EOF, the callback is never succeeded.

The reason why is because it is the call to `Chunk.release()` that is meant to succeed the callback, so nowhere in the `AsyncContent` code do we succeed it. Now that I've replaced empty callbacks with EOF, there's no way to detect when EOF.release() is called.

Let me fix that.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ChunksContentSource.java [hunk 2]
```diff
@@ -73,7 +73,7 @@ public Content.Chunk read()
             if (last)
                 terminated = Content.Chunk.EOF;
         }
-        return Content.Chunk.from(chunk.getByteBuffer().slice(), chunk.isLast(), chunk);
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ChunksContentSource.java:76]: Either, this was missing a `retain()` call, or slicing the chunk is the wrong thing to do.

Do we consider the chunks given to this content source to be managed by the reader, or do we consider the reader is getting duplicates and the writer is still supposed to lifecycle the chunks?

The previous impl was a bit in the middle (see the `fail()` impl vs `read()`'s odd creation of a new chunk with a sliced buffer and a common releaser).

I've decided to go for "the reader has to lifecycle the chunks, the writer fire&forgets them" but that should probably be javdoc'ed.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ByteBufferContentSource.java [hunk 3]
```diff
@@ -78,6 +78,8 @@ public Content.Chunk read()
             if (last)
                 terminated = Content.Chunk.EOF;
         }
+        if (!buffer.hasRemaining())
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ByteBufferContentSource.java]: We should probably javadoc that the code instantiating this class is responsible for managing the lifecycle of the buffers, unlike `ChunksContentSource` for which the exact opposite is true.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java [hunk 4]
```diff
@@ -50,7 +50,31 @@ public class AsyncContent implements Content.Sink, Content.Source, Closeable
...
+                public void succeeded()
+                {
+                    // Noop, chunk.release() will trigger the callback's success.
+                }
+            };
+        }
+        write(chunk, cb);
     }
 
     public void write(Content.Chunk chunk, Callback callback)
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: We should probably javadoc when the callback is called as it could be confused with the chunk's lifecycle w.r.t when the chunk's byte buffer gets released.

**Comment by lorban** [comment]
@gregw I answered your question w.r.t succeeding twice the callback in your code comment. In a nutshell, it's never succeeded twice and my original change introduced a bug which made it never be succeeded in certain cases. This is now fixed with some comments explaining the somewhat baroque logic.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java [hunk 5]
```diff
@@ -50,7 +50,31 @@ public class AsyncContent implements Content.Sink, Content.Source, Closeable
...
+            cb = new Callback.Nested(callback)
+            {
+                @Override
+                public void succeeded()
+                {
+                    // Noop, chunk.release() will trigger the callback's success.
+                }
+            };
+        }
+        write(chunk, cb);
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: I would do the other way around.
Have an `private offer()` method called by the 2 `write()` methods, so that you can release the chunk when the read releases the chunk.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java [hunk 6]
```diff
@@ -50,7 +50,31 @@ public class AsyncContent implements Content.Sink, Content.Source, Closeable
     @Override
     public void write(boolean last, ByteBuffer byteBuffer, Callback callback)
     {
-        write(Content.Chunk.from(byteBuffer, last, callback::succeeded), callback);
+        // This class' read() impl calls succeeded() on the callback before returning it to the
+        // caller, so when EOF / EMPTY are used this is perfectly right as the chunk can be
+        // considered consumed and there is no buffer to reclaim. But when a proper buffer is
+        // used the passed callback must be wrapped to make its succeeded() method a noop
+        // as it is the release of the chunk that should trigger the success of the callback.
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: I'd change this comment to a javadoc to explain the semantic of `write()` which is: "the callback is completed when the chunk is read *and* released".

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ChunksContentSource.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ChunksContentSource.java:76]: Agreed, I think just `return chunk` should be enough here.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 7]
```diff
@@ -571,6 +555,23 @@ static Chunk slice(Chunk chunk)
          */
         boolean isLast();
 
+        /**
+         * <p>Returns a new {@code Chunk} whose {@code ByteBuffer} is a slice of the
+         * {@code ByteBuffer} of the source {@code Chunk}.</p>
+         * <p>The returned {@code Chunk} retains the source {@code Chunk} and it is linked
+         * to it via {@link #from(ByteBuffer, boolean, Retainable)}.</p>
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Update javadoc with "unless is EOF or EMPTY" or similar.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 7 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Done.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java (hunk 6 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: Done, but handling EOF/EMPTY adds some complexity which I accounted for in the javadoc.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: Done.

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartTest.java [hunk 8]
```diff
@@ -58,7 +58,7 @@ public void testParseNoPartsInTwoChunks()
 
         assertEquals(0, listener.events.size());
 
-        parser.parse(Content.Chunk.from(BufferUtil.EMPTY_BUFFER, true));
+        parser.parse(Content.Chunk.EOF);
```
Comment (gregw) [inline jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartTest.java:61]: My understanding of this PR is that you didn't need to change this, as `from` would have returned EOF anyway.    Just checking that is true?

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpReceiverOverHTTP2.java [hunk 9]
```diff
@@ -80,10 +81,21 @@ public Content.Chunk read(boolean fillInterestIfNeeded)
...
+            {
+                responseSuccess(getHttpExchange(), null);
+                return Content.Chunk.EOF;
+            }
+            else
+            {
+                return Content.Chunk.EMPTY;
+            }
+        }
+        return Content.Chunk.from(buffer, false, data);
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpReceiverOverHTTP2.java]: Doesn't `from` now do all this logic about choosing to return `EMPTY` or `EOF` if possible?  It was much simpler code to just call `from` and let it work out the details, rather than make the caller do this all the time.

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 10]
```diff
@@ -241,12 +241,19 @@ public Runnable onTrailer(HeadersFrame frame)
...
+        ByteBuffer byteBuffer = frame.getData();
+        if (!byteBuffer.hasRemaining())
+        {
+            // We must NOT retain because we are not passing the
+            // ByteBuffer to the Chunk.
+            if (frame.isEndStream())
+                return Content.Chunk.EOF;
+            else
+                return Content.Chunk.EMPTY;
+        }
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: again, can't we just let `from` do it's stuff rather than put this logic everywhere?

File: jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/internal/HttpReceiverOverHTTP3.java [hunk 11]
```diff
@@ -64,10 +64,20 @@ public Content.Chunk read(boolean fillInterestIfNeeded)
...
+            data.release();
+            if (data.isLast())
+            {
+                responseSuccess(getHttpExchange(), null);
+                return Content.Chunk.EOF;
+            }
+            else
+            {
+                return Content.Chunk.EMPTY;
+            }
```
Comment (gregw) [inline jetty-core/jetty-http3/jetty-http3-client-transport/src/main/java/org/eclipse/jetty/http3/client/transport/internal/HttpReceiverOverHTTP3.java]: ditto

File: jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java [hunk 12]
```diff
@@ -233,12 +233,19 @@ public Runnable onTrailer(HeadersFrame frame)
...
+        ByteBuffer byteBuffer = data.getByteBuffer();
+        if (!byteBuffer.hasRemaining())
+        {
+            // As we are NOT passing the ByteBuffer to the Chunk,
+            // we must not retain.
+            if (data.isLast())
+                return Content.Chunk.EOF;
+            else
+                return Content.Chunk.EMPTY;
+        }
```
Comment (gregw) [inline jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java]: ditto

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java [hunk 13]
```diff
@@ -47,13 +47,55 @@ public class AsyncContent implements Content.Sink, Content.Source, Closeable
...
+     */
     @Override
     public void write(boolean last, ByteBuffer byteBuffer, Callback callback)
     {
-        write(Content.Chunk.from(byteBuffer, last, callback::succeeded), callback);
+        Content.Chunk chunk;
+        if (!byteBuffer.hasRemaining())
+            chunk = last ? Content.Chunk.EOF : Content.Chunk.EMPTY;
+        else
+            chunk = Content.Chunk.from(byteBuffer, last, callback::succeeded);
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: ditto

**Review by gregw — CHANGES_REQUESTED** [review]
I think we should rely on `Chunk.from` to correctly choose from `EOF`, `EMPTY` or a new chunk, rather than have that same logic scatter around the code base.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: Done.

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartTest.java (hunk 8 above)
Comment (lorban) [reply jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartTest.java:61]: If `Chunk.from` would choose from `EOF` or `EMPTY`, you'd be right except that `from(ByteBuffer, boolean)` doesn't know about the lifecycle of the given buffer so it has no way to release it when it decides to replace it with EOF or EMPTY.

We could change this call to `Content.Chunk.from(BufferUtil.EMPTY_BUFFER, true, () -> {})` but I'm not sure it would be any better.

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpReceiverOverHTTP2.java (hunk 9 above)
Comment (lorban) [reply jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpReceiverOverHTTP2.java]: That can be done with the 3 variants of `from` that take a `ByteBuffer`-controlling object as a parameter (when `from` wants to replace the empty byte buffer with EOF/EMPTY, it must release the byte buffer) but not with the 4th one.

I've changed the replacement code scattered everywhere so that this is now done by the 3 `from` variants, I made the 4th one throw an exception and changed the calls to the 4th one to one of the 3 non-throwing one where appropriate.

I find this much cleaner, so I'm in favor of this change.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java (hunk 13 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: This one  is an exception: the callback must not be succeeded until the write is over, which happens when another thread releases the generated chunk after reading it.

So we cannot let `from` call the release callback if it decides to replace the chunk with EOF or EMPTY otherwise we would succeed the callback too early.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 14]
```diff
@@ -624,7 +624,7 @@ public Content.Chunk read()
                     // TODO: use a ByteBuffer pool and direct ByteBuffers?
                     ByteBuffer byteBuffer = UTF_8.encode(builder.toString());
                     state = State.CONTENT;
-                    yield Content.Chunk.from(byteBuffer, false);
+                    yield Content.Chunk.from(byteBuffer, false, () -> {});
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Why this?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 15]
```diff
@@ -457,6 +463,11 @@ static Chunk from(ByteBuffer byteBuffer, boolean last)
          */
         static Chunk from(ByteBuffer byteBuffer, boolean last, Runnable releaser)
         {
+            if (!byteBuffer.hasRemaining())
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: I think it's more readable if you invert the `if`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 16]
```diff
@@ -471,6 +482,11 @@ static Chunk from(ByteBuffer byteBuffer, boolean last, Runnable releaser)
          */
         static Chunk from(ByteBuffer byteBuffer, boolean last, Consumer<ByteBuffer> releaser)
         {
+            if (!byteBuffer.hasRemaining())
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Invert the `if`

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 17]
```diff
@@ -486,6 +502,11 @@ static Chunk from(ByteBuffer byteBuffer, boolean last, Consumer<ByteBuffer> rele
          */
         static Chunk from(ByteBuffer byteBuffer, boolean last, Retainable retainable)
         {
+            if (!byteBuffer.hasRemaining())
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Invert the `if`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java [hunk 18]
```diff
@@ -47,13 +47,55 @@ public class AsyncContent implements Content.Sink, Content.Source, Closeable
...
+        offer(chunk, callback);
     }
 
+    /**
+     * <p>Writes the given {@link ByteBuffer}, notifying the {@link Callback} when the
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]:
```suggestion
     * <p>Writes the given chunk, notifying the {@link Callback} when the
```

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java [hunk 19]
```diff
@@ -47,13 +47,55 @@ public class AsyncContent implements Content.Sink, Content.Source, Closeable
...
+     * <li>successfully just before the {@link Content.Chunk} is returned if the latter {@link Content.Chunk#hasRemaining() has no remaining byte}</li>
+     * </ul>
+     *
+     * @param chunk the Content.Chunk to write
+     * @param callback the callback to notify when the write operation is complete
+     */
     public void write(Content.Chunk chunk, Callback callback)
+    {
+        Content.Chunk c;
+        if (chunk.isTerminal())
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java:82]: Add braces to this chained `if/else`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java [hunk 20]
```diff
@@ -47,13 +47,55 @@ public class AsyncContent implements Content.Sink, Content.Source, Closeable
...
+            chunk = Content.Chunk.from(byteBuffer, last, callback::succeeded);
+        offer(chunk, callback);
     }
 
+    /**
+     * <p>Writes the given {@link ByteBuffer}, notifying the {@link Callback} when the
+     * write is complete.</p>
+     * <p>The callback completes:</p>
+     * <ul>
+     * <li>immediately with a failure when the written chunk is an instance of {@link Content.Chunk.Error}</li>
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java:71]: This feel weird.
I think it should be treated like a normal "special" write of, say, `EOF`, so succeeding the callback.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ByteBufferContentSource.java [hunk 21]
```diff
@@ -78,7 +78,7 @@ public Content.Chunk read()
             if (last)
                 terminated = Content.Chunk.EOF;
         }
-        return Content.Chunk.from(buffer, last);
+        return Content.Chunk.from(buffer, last, () -> {});
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ByteBufferContentSource.java]: Unnecessary?

File: jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/AsyncContentSourceTest.java [hunk 22]
```diff
@@ -125,4 +129,63 @@ public void testWriteErrorChunk() throws Exception
...
+            async.write(true, ByteBuffer.wrap(new byte[0]), Callback.from(successCounter::incrementAndGet, failureRef::set));
+
+            Content.Chunk chunk = async.read();
+            assertThat(successCounter.get(), is(1));
+            assertThat(chunk.isTerminal(), is(true));
+            assertThat(chunk.release(), is(true));
+            assertThat(successCounter.get(), is(1));
+            assertThat(failureRef.get(), is(nullValue()));
+        }
+    }
```
Comment (sbordet) [inline jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/AsyncContentSourceTest.java:193]: Add one more test for the `Error` behavior.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java [hunk 23]
```diff
@@ -33,7 +33,32 @@
 public class MockHttpStream implements HttpStream
 {
     private static final Throwable SUCCEEDED = new Throwable();
-    private static final Content.Chunk DEMAND = Content.Chunk.from(BufferUtil.EMPTY_BUFFER, false);
+    private static final Content.Chunk DEMAND = new Content.Chunk()
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java:36]: Isn't this `EMPTY`? Why do you need it to be different from `EMPTY`?

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java [hunk 24]
```diff
@@ -65,7 +90,7 @@ public boolean isDemanding()
 
     public Runnable addContent(ByteBuffer buffer, boolean last)
     {
-        return addContent((last && BufferUtil.isEmpty(buffer)) ? Content.Chunk.EOF : Content.Chunk.from(buffer, last));
+        return addContent(Content.Chunk.from(buffer, last, () -> {}));
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java]: Unnecessary?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletMultiPartFormData.java [hunk 25]
```diff
@@ -107,7 +107,7 @@ private Parts parse(ServletContextRequest.ServletApiRequest request) throws IOEx
                 formData.parse(Content.Chunk.EOF);
                 break;
             }
-            formData.parse(Content.Chunk.from(ByteBuffer.wrap(buffer, 0, read), false));
+            formData.parse(Content.Chunk.from(ByteBuffer.wrap(buffer, 0, read), false, () -> {}));
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletMultiPartFormData.java]: Unnecessary?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java (hunk 18 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java]: Fixed.

File: jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/AsyncContentSourceTest.java (hunk 22 above)
Comment (lorban) [reply jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/AsyncContentSourceTest.java:193]: There already is `testWriteErrorChunk` that checks error chunks are read and the callback failed.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java (hunk 23 above)
Comment (lorban) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java:36]: No, it's a different instance on purpose as it is assigned and compared with `==`. The buffer and last are meaningless as they are never read, and this chunk never leaves this implementation.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 16 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Ok.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 15 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Ok.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 17 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Ok.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 14 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: It's because the `byteBuffer` may contain 0 byte, so it should be replaced with `EMPTY` but `Content.Chunk.from(ByteBuffer, boolean)` cannot do that as it doesn't know how to release the buffer.

Calling `Content.Chunk.from(ByteBuffer, boolean, Runnable)` can replace a 0 byte buffer with `EMPTY` as when it does so, it can call the `Runnable` to release to buffer. And since this buffer was allocated and not taken from a pool, the `Runnable` can be a no-op and leave the buffer to the GC.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ByteBufferContentSource.java (hunk 21 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ByteBufferContentSource.java]: See above.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java (hunk 24 above)
Comment (lorban) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/MockHttpStream.java]: See above.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletMultiPartFormData.java (hunk 25 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletMultiPartFormData.java]: See above.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java (hunk 19 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java:82]: Done.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java (hunk 20 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/AsyncContent.java:71]: I did not change this contract, it is now in `offer()` but I just documented the existing impl. Do you think it should be changed?

**Review by sbordet — APPROVED** [review]
