### PR TITLE
Fixes #13261 - Improve handling of failed HTTP/2 requests.

### LINKED ISSUE #13261: Improve handling of failed HTTP/2 requests
**Jetty version(s)**
12.0.x

**Description**
In load test scenarios, when the server is overwhelmed and starts closing connections, the client may not properly release acquired connections back to the connection pool.

Eventually, the connection pool may enter a degenerate behavior (for example, using only 1 connection).

### PR DESCRIPTION
**Pull request by sbordet**

### CODE REVIEW

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java [hunk 1]
```diff
@@ -388,8 +388,7 @@ private boolean process(Connection connection)
             LOG.debug("Processing exchange {} on {} of {}", exchange, connection, this);
         if (exchange == null)
         {
-            if (!connectionPool.release(connection))
-                connection.close();
+            releaseConnection(connection);
```
Comment (gregw) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java]: The else clause below is not necessary and makes this code a little harder to read.  Without it, it would be 4 if statements, each returning.

But this is unrelated to this PR

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java [hunk 2]
```diff
@@ -489,15 +484,22 @@ public void release(Connection connection)
         else
         {
             if (LOG.isDebugEnabled())
-                LOG.debug("{} is stopped", client);
+                LOG.debug("Closing {}, {} is stopped", connection, client);
             connection.close();
         }
     }
 
+    private boolean releaseConnection(Connection connection)
```
Comment (gregw) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java]: Two things confusing about this method on first glance:\

 + how is `releaseConnection(Connection)` different to `releaseConnection(Connection)`? Some better names and/or javadoc would help.
 + why is the connection closed if it is not released?  If that is an unexpected situation, then a warn or debug would be good? A comment in the code to explain would be good.    I'm assuming that a connection can be acquired multiple times due to multiplexing, so releasing to non-zero should be normal?  or does the boolean return mean something else?   Oh the boolean return from the release is special.

Maybe call this `releaseOrClose(Connection)`, because either the connection is released or it is closed?

**Review by gregw — DISMISSED** [review]
The fix looks good, with new calls to `releaseConnection` in places that look expected. However, some of the names and lack of comments are a little confusing, so a see comments for some suggestions to improve (but I approved this anyway).

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java [hunk 3]
```diff
@@ -324,6 +324,16 @@ protected Connection activate()
             {
                 Connection connection = entry.getPooled();
 
+                if (connection.isClosed())
```
Comment (lorban) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:327]: A test should be added for this new feature.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java [hunk 4]
```diff
@@ -406,14 +405,13 @@ private boolean process(Connection connection)
...
-                boolean released = connectionPool.release(connection);
-                if (!released)
-                    connection.close();
                 // It may happen that the request is aborted before the exchange
                 // is created. Aborting the exchange a second time will result in
                 // a no-operation, so we just abort here to cover that edge case.
                 exchange.abort(cause, Promise.noop());
+                // The exchange won't be associated to a connection,
+                // and this connection won't be used, release it back.
+                releaseConnection(connection);
```
Comment (lorban) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java]: Shouldn't that be done in the `abort()`'s promise, as `abort()` may try to write to the response?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java [hunk 5]
```diff
@@ -498,9 +498,8 @@ public void close()
      * @param failure the cause of the abort
      * @see #isAborted()
      */
-    public void abort(Throwable failure)
+    public boolean abort(Throwable failure)
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java:503]: Javadoc should document the new returned boolean, and some tests should be added.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java [hunk 6]
```diff
@@ -675,58 +675,49 @@ public void onWriteFailure(Throwable failure)
         streamsState.onWriteFailure(failure);
     }
 
-    protected void abort(String reason, Throwable failure, Callback callback)
+    private void failStreams(Predicate<Stream> matcher, String reason, boolean reset, Callback callback)
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Session.java:687]: There should be a bit of javadoc on this method as what the matcher is used for cannot be inferred from the method name.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java [hunk 7]
```diff
@@ -300,6 +309,12 @@ public void onConnectionFailure(int error, String reason)
         session.onConnectionFailure(error, reason);
     }
 
+    @Override
+    public String toConnectionString()
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java:313]: This method is eventually called by `AbstractEndPoint.toString()` so you cannot take a lock in it, or more precisely in this case: you cannot call a method that takes a lock.

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpReceiverOverHTTP2.java [hunk 8]
```diff
@@ -261,7 +261,31 @@ public Runnable onTimeout(TimeoutException failure, Promise<Boolean> promise)
...
-        Promise<Boolean> promise = Promise.from(failed -> callback.succeeded(), callback::failed);
-        return new Invocable.ReadyTask(Invocable.InvocationType.NON_BLOCKING, () -> responseFailure(failure, promise));
+        HttpExchange exchange = getHttpExchange();
+        if (exchange != null)
+            return new FailureTask(exchange, failure, callback);
+        callback.succeeded();
+        return null;
+    }
+
+    private static class FailureTask extends Invocable.Task.Abstract
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpReceiverOverHTTP2.java:271]: Did you create this class to have nice-looking names in the debug logs? In this case it may be worth stating that in a comment.

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java [hunk 9]
```diff
@@ -307,9 +315,8 @@ void offerTask(Runnable task, boolean dispatch)
     @Override
     public String toString()
     {
-        return String.format("%s@%x(closed=%b)[%s]",
-            getClass().getSimpleName(),
-            hashCode(),
+        return String.format("%s(closed=%b)[%s]",
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java]: Since `isClosed()` now grabs a lock, you cannot call it from `toString()`.

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java [hunk 10]
```diff
@@ -195,98 +217,84 @@ protected void normalizeRequest(HttpRequest request)
...
         return new HttpChannelOverHTTP2(this, getSession());
     }
 
-    protected boolean release(HttpChannelOverHTTP2 channel)
+    protected void release(HttpChannelOverHTTP2 channel)
     {
-        if (LOG.isDebugEnabled())
-            LOG.debug("Released {}", channel);
-        if (activeChannels.remove(channel))
+            boolean removed;
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java]: is that `boolean` mis-indented, or is GitHub messing up this diff?

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java [hunk 11]
```diff
@@ -195,98 +217,84 @@ protected void normalizeRequest(HttpRequest request)
...
     {
         getHttpDestination().remove(this);
     }
 
-    @Override
-    public void close()
+    void onFailure(Throwable failure, Callback callback)
     {
-        close(new AsynchronousCloseException());
+        if (LOG.isDebugEnabled())
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java:262]: The debug log should probably be different when closed is true or false.

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java [hunk 12]
```diff
@@ -195,98 +217,84 @@ protected void normalizeRequest(HttpRequest request)
...
+        destroy();
+        callback.succeeded();
     }
 
-    protected void close(Throwable failure)
+    @Override
+    public void close()
     {
-        if (closed.compareAndSet(false, true))
+        if (LOG.isDebugEnabled())
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpConnectionOverHTTP2.java:277]: The debug log should probably be different when closed is true or false.

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpChannelOverHTTP2.java [hunk 13]
```diff
@@ -112,15 +112,19 @@ public void send(HttpExchange exchange)
         sender.send(exchange);
     }
 
+    void acquire()
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpChannelOverHTTP2.java:115]: Since this method is only logging, I'd rather have it inlined.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java]: The `else` branch is where the exchange is sent.
Not sure what you mean in the comment above.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java]: `ConnectionPool.release(Connection)` is documented, and states that upon returning `false` the connection should be closed, so I won't add a comment.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/AbstractConnectionPool.java:327]: This is really hard, because closing a connection also removed it from the pool.
We would need to exactly hit the race where the connection is closed, but not yet removed from the pool.

File: jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpChannelOverHTTP2.java (hunk 13 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-client-transport/src/main/java/org/eclipse/jetty/http2/client/transport/internal/HttpChannelOverHTTP2.java:115]: It matches the `release()` method just below, and it's easier to track acquire/release logs as they would be logged by the same class.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java]: The current structure of the code is:
```java
    if (A) 
    {
        // do A
        return;
    }
    else
    {
          if (B)
          {
               // do B
               return;
          }

          if (C)
          {
               // do C
               return;
          }

          // do D
    }
```
This is needlessly convoluted and would be much clearer as:
```java
    if (A) 
    {
        // do A
        return;
    }

    if (B)
    {
         // do B
         return;
    }

    if (C)
    {
         // do C
         return;
    }

    // do D
```

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java]: Yeah but that is a strange contract and different from the  `Retainable.release` semantic.    How about the changes  above and below instead?

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java [hunk 14]
```diff
@@ -489,15 +484,22 @@ public void release(Connection connection)
...
         }
     }
 
+    private boolean releaseConnection(Connection connection)
+    {
+        boolean released = connectionPool.release(connection);
+        if (!released)
+            connection.close();
+        return released;
+    }
```
Comment (gregw) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java:500]: This would be clearer:
```suggestion
    {
        boolean close = connectionPool.release(connection);
        if (close)
            connection.close();
        return close;
    }
```

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java (hunk 2 above)
Comment (gregw) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java]:
```suggestion
   /**
     * @return {@code true} if the connection was closed
    private boolean releaseOrCloseConnection(Connection connection)
```

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java [hunk 15]
```diff
@@ -462,23 +464,16 @@ public boolean remove(HttpExchange exchange)
...
-                }
-                else
-                {
-                    connection.close();
-                    send(true);
-                }
+                boolean released = releaseConnection(connection);
+                if (LOG.isDebugEnabled())
+                    LOG.debug("Released: {} {}", released, connection);
+                send(!released);
```
Comment (gregw) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java]:
```suggestion
                boolean closed = releaseOrCloseConnection(connection);
                if (LOG.isDebugEnabled())
                    LOG.debug("Closed: {} {}", closed, connection);
                send(closed);
```

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java (hunk 14 above)
Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java:500]: We cannot change the meaning of the return value of `ConnectionPool.release()`.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java (hunk 15 above)
Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpDestination.java]: This code is inside a `release()` method, so I think it's clearer to keep the narrative about release/releasing than closing: I'm more interested in the logs having "Released: true", which is the common case, rather than "Close: false" and then have to figure out that it actually means that the connection has been released back to the pool.

**Review by lorban — APPROVED** [review]

**Review by gregw — APPROVED** [review]
the rename makes it a little better, but still a confusing API, even though you keep telling us that we are not confused by it:)
