### PR TITLE
Issue #10274 - Improve javadoc + move internal methods

### LINKED ISSUE #10274: java.nio.file.FileSystemNotFoundException when creating a resource from a JAR URL
**Jetty version(s)**
12

**Java version/vendor** `(use: java -version)`
17

**OS type/version**
Windows

**Description**
In my application we are using an embedded jetty that creates multiple web application contexts. The setup is completely custom and consists of collecting multiple JARs in a way so that some of the JARs are shared between the web application contexts while others belong to just one context. For this we are building individual resources using URIs like

jar:file:///C:/app/lib/some.jar!/META-INF/resources
jar:file:///C:/app/lib/other.jar!/META-INF/resources

This worked fine in Jetty 10 but I was not able to get this running when migrating to Jetty 12.  There I was trying to build the resources using

ResourceFactory.getBestByScheme(loUri).newResource(loUri)

 and but that crashes with a FileSystemNotFoundException. I also tried various other ways/URIs to create a resource for that JAR etc but they just returned null.

```
java.nio.file.FileSystemNotFoundException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:156)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:142)
	at org.eclipse.jetty.util.resource.MountedPathResourceFactory.newResource(MountedPathResourceFactory.java:42)
	at org.eclipse.jetty.util.resource.ResourceFactory.newResource(ResourceFactory.java:191)
```

After debugging into MountedPathResourceFactory that is returned by ResourceFactory.getBestByScheme(loUri) and the java.nio.file.FileSystems code I think that MountedPathResourceFactory has a bug regarding the FileSystems.

**How to reproduce?**

```
public class MountedPathResourceFactory implements ResourceFactory
{
	@Override
	public Resource newResource(URI uri)
	{
		try
		{
			FileSystems.getFileSystem(uri);
		}
		catch(FileSystemNotFoundException e)
		{
			try
			{
				FileSystems.newFileSystem(uri, Map.of("create", "true"));
			}
			catch (IOException e1)
			{
				e1.printStackTrace();
			}
		}

		Path path = Paths.get(uri.normalize());
		if (!Files.exists(path))
			return null;
		return new MountedPathResource(path, uri);
	}
}
```

The original code crashes with a FileSystemNotFoundException in Paths.get(uri.normalize()). With the hacked workaround the everything is fine. The resource is resource is created and it also the whole web application context works just fine. I am not familiar with the FileSystems API so I have no idea what is the really proper way to use them. But it looks like it is necessary to create them first explicitly before you can use them and I don't think this is something that the application itself should have to do.

### PR DESCRIPTION
**Pull request by joakime**
Attempt to improve the javadoc experience with `Resource` and `ResourceFactory` use.

### CODE REVIEW

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java [hunk 1]
```diff
@@ -27,7 +27,88 @@
...
- * ResourceFactory.
+ * <p>ResourceFactory is the source of new {@link Resource} instances.</p>
+ *
+ * <p>
+ *     It is important to understand the scope of any {@code ResourceFactory}
+ *     objects you create, as all {@link Resource} instances created from
+ *     it will be tied to the life of the {@link ResourceFactory}.
+ * </p>
+ *
+ * <h2>A {@code ResourceFactory} tied to a Jetty {@link org.eclipse.jetty.util.component.LifeCycle}</h2>
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java]: This is wrong? It's tied to a `Container` not a `LifeCycle`.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java [hunk 2]
```diff
@@ -27,7 +27,88 @@
...
+ * <pre>
+ *     ResourceFactory resourceFactory = ResourceFactory.of(lifecycle);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java]: Ditto.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java [hunk 3]
```diff
@@ -27,7 +27,88 @@
...
+ *     Resource resource = resourceFactory.newResource(ref);
+ * </pre>
+ * <p>
+ *     The use of {@link ResourceFactory#of(Container)} results in a {@link ResourceFactory} that is tied
+ *     to a specific Jetty {@link org.eclipse.jetty.util.component.LifeCycle} such as a {@code Server},
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java]: Ditto.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java [hunk 4]
```diff
@@ -27,7 +27,88 @@
...
+ *     {@code ServletContextHandler}, or {@code WebAppContext}.   This will free the {@code Resource}
+ *     instances created by the {@link org.eclipse.jetty.util.resource.ResourceFactory} once
+ *     the {@code lifecycle} it is associated with is stopped.
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java]: Ditto.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java [hunk 5]
```diff
@@ -27,7 +27,88 @@
...
+ *
+ *     <dt>jar</dt>
+ *     <dd>The standard Java {@code jar:file:/path/to/file.jar!/} syntax</dd>
+ *
+ *     <dt>jrt</dt>
+ *     <dd>The standard Java {@code jrt:module-name} syntax</dd>
+ * </dl>
+ * <p>
+ *     Special Note: An effort is made to discover any new schemes that
+ *     might be present at JVM startup (eg: graalvm and {@code bundle:} scheme).
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java]: Isn't `bundle:` an OSGi thing?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java [hunk 6]
```diff
@@ -27,7 +27,88 @@
 import org.eclipse.jetty.util.component.Dumpable;
 
 /**
- * ResourceFactory.
+ * <p>ResourceFactory is the source of new {@link Resource} instances.</p>
+ *
+ * <p>
+ *     It is important to understand the scope of any {@code ResourceFactory}
+ *     objects you create, as all {@link Resource} instances created from
+ *     it will be tied to the life of the {@link ResourceFactory}.
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java]: I think it would be better to introduce the fact that RF has a scope (I would not call it lifecycle).
After that you can say that resources created from it have the same scope.

What above reads: "the scope of any RF you create ... will be tied to the life of the RF" which is confusing as it is tautological.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java (hunk 5 above)
Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java]: The `bundle:` scheme is overloaded, lots of projects use it.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java [hunk 7]
```diff
@@ -27,7 +27,91 @@
...
- * ResourceFactory.
+ * <p>ResourceFactory is the source of new {@link Resource} instances.</p>
+ *
+ * <p>
+ *     It is important to understand that some {@link Resource} objects
+ *     have internal allocation / release model, that the {@link ResourceFactory}
+ *     is responsible for.   The type of {@link ResourceFactory} you allocate
+ *     will determine how long each {@link Resource} object is valid for (eg:
+ *     once a {@link ResourceFactory.LifeCycle} is stopped, the {@link Resource}
+ *     objects created from that {@link ResourceFactory} are also released.
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java]:
```suggestion
 *     Some {@link Resource} objects
 *     have internal allocation / release model, that the {@link ResourceFactory}
 *     is responsible for.   The  {@link ResourceFactory.LifeCycle lifecycle} of the {@link ResourceFactory} used
 *     to create a {@link Resource} will bound the {@link ResourceFactory.LifeCycle lifecycle} of the  {@link Resource} 
 *     (i.e. once a {@link ResourceFactory.LifeCycle} is stopped, the {@link Resource}
 *     objects it created are also released.
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactoryInternals.java [hunk 8]
```diff
@@ -93,6 +93,44 @@ protected void onMounted(FileSystemPool.Mount mount, URI uri)
...
+     * .byScheme("jar:file://foo.jar!/") == null // full url strings not supported)
+     * }</pre>
+     *
+     * @param scheme the scheme to look up
+     * @return the {@link ResourceFactory} responsible for the scheme, null if no {@link ResourceFactory} handles the scheme.
+     * @see ResourceFactory#registerResourceFactory(String, ResourceFactory)
+     * @see ResourceFactory#unregisterResourceFactory(String)
+     * @see #getBestByScheme(String)
+     */
+    static ResourceFactory byScheme(String scheme)
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactoryInternals.java]: This is a new concept?   We now have two orthogonal reasons for selecting a resource factory.  Should we select one by lifecycle or by scheme?   Why is this necessary?

Edit: Oh I see it is not a new concept... and at least this is moving it internal.   But I'm struggling to see why we need it?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 9]
```diff
@@ -1836,8 +1836,7 @@ public static URI toURI(String resource)
         Objects.requireNonNull(resource);
 
         // Only try URI for string for known schemes, otherwise assume it is a Path
-        ResourceFactory resourceFactory = ResourceFactory.getBestByScheme(resource);
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java:1839]: Oh I never noticed this getting a resource factory by scheme before?   This is not good, as now are we selecting a factory by lifecycle or by scheme?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactoryInternals.java (hunk 8 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactoryInternals.java]: Oh Oh I see we are not actually picking a ResourceFactory by scheme, rather we are checking if we know of the scheme.  Can we change this to a boolean return?

**Review by gregw — CHANGES_REQUESTED** [review]
I think this PR is a general improvement, but it is highlighting that we still have some big issues in our resource abstraction.   Can we schedule a hangout to discuss?

**Comment by joakime** [comment]
@gregw I think I've addressed your last review.

**Review by gregw — APPROVED** [review]

**Comment by joakime** [comment]
@sbordet bump, your out of date change request is blocking this merge.

**Review by sbordet — APPROVED** [review]

**Comment by joakime** [comment]
This javadoc will need more iterations, but this feels like a step in the right direction (at least).
