### PR TITLE
Issue #6085 Fix reference counts for multiple valid cookies for sessions

### LINKED ISSUE #6085: Jetty keeps Sessions in use after "Duplicate valid session cookies" Message
**Jetty version**
9.4.26

**Java version**
openjdk version "10.0.2" 2018-07-17

**OS type/version**
CentOS Linux 7 (core)

**Description**
After getting org.eclipse.jetty.http.BadMessageException: 400: Duplicate valid session cookies jetty keeps the duplicate sessions in use state (request counter in session >0). Thats why these session will not be invalidated by the HouseKeeper-Thread.
Is this a bug in jetty?

### PR DESCRIPTION
**Pull request by janbartel**
cherry  pick from 9.4.x

issue #6085

### CODE REVIEW

**Review by lorban — APPROVED** [review]
This is literally identical to https://github.com/eclipse/jetty.project/pull/6088 so LGTM.

File: jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java [hunk 1]
```diff
@@ -1614,7 +1614,12 @@ else if (!DispatcherType.REQUEST.equals(baseRequest.getDispatcherType()))
                         if (LOG.isDebugEnabled())
                             LOG.debug("Got Session ID {} from cookie {}", id, sessionCookie);
 
+                        //retrieve the session, which increments the reference count
                         HttpSession s = getHttpSession(id);
+                        //associate it with the request so its reference count
+                        //will be decremented as the request completes
+                        if (s != null && isValid(s))
+                            baseRequest.enterSession(s);
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java:1622]: In all other cases, the calls to `enterSession()` and `setSession()` are in 2 consecutive lines.
Is there a reason to split them in this case?

Can this snippet be moved down to line 1650?

Also, the `else if (requestedSessionId.equals(id))` branch does not assign the `session` variable... Given the comment, I think it should?

**Review by sbordet — DISMISSED** [review]
Kinda looks ok, but I think it could be improved by making the `enterSession()` and `setSession()` calls in consecutive lines, like it is done in other places.

**Review by sbordet — CHANGES_REQUESTED** [review]
See comment.

File: jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java (hunk 1 above)
Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java:1622]: I REALLY think we have to stop do "logic cleanups" in the middle of important time critical fixes.  
Such cleanups without clear reasons have broken things before.

Comment (janbartel) [reply jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java:1622]: No, line 1622 cannot be moved down. The whole point of the PR is that when we receive a request that has multiple valid session id cookies, we need to associate both of them with the request so that the request will decrement the reference count on both of them on the way out (the ref count was incremented at line 1618 when each session is loaded).

If the requestedSessionId.equals(id) we don't assign the session object because both ids are the same, and thus the session object will be the same, thus no point in re-assigning it.

**Review by sbordet — APPROVED** [review]
