### PR TITLE
Fixes #10087 - Flaky EventsHandlerTest due to trailers.

### LINKED ISSUE #10087: Flaky `EventsHandlerTest.testUsingEventsResponseAsContentSourceFailsWithTrailers`
**Jetty version(s)**
12

**Description**

`EventsHandlerTest.testUsingEventsResponseAsContentSourceFailsWithTrailers` sometimes fails with:

```
java.io.IOException: written 0 < 6 content-length
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1208)
	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:589)
	at org.eclipse.jetty.server.handler.EventsHandler$EventsResponse.write(EventsHandler.java:349)
	at org.eclipse.jetty.io.internal.ContentCopier.process(ContentCopier.java:73)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.io.Content.copy(Content.java:91)
	at org.eclipse.jetty.test.client.transport.EchoHandler.handle(EchoHandler.java:54)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596)
	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:96)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596)
	at org.eclipse.jetty.server.Server.handle(Server.java:177)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:615)
	at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.run(HttpStreamOverHTTP2.java:128)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:158)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:449)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.Invocable.invokeNonBlocking(Invocable.java:156)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.invokeAsNonBlocking(AdaptiveExecutionStrategy.java:490)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:426)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
Suppressed: 
	|java.lang.NullPointerException: Cannot invoke "java.util.function.Consumer.accept(Object)" because "onFailure" is null
	|	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onFailure$2(HttpChannelState.java:436)
	|	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	|	at org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:117)
	|	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1225)
	|	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:589)
	|	at org.eclipse.jetty.server.handler.EventsHandler$EventsResponse.write(EventsHandler.java:349)
	|	at org.eclipse.jetty.io.internal.ContentCopier.process(ContentCopier.java:73)
	|	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243)
	|	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	|	at org.eclipse.jetty.io.Content.copy(Content.java:91)
	|	at org.eclipse.jetty.test.client.transport.EchoHandler.handle(EchoHandler.java:54)
	|	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596)
	|	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:96)
	|	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596)
	|	at org.eclipse.jetty.server.Server.handle(Server.java:177)
	|	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:615)
	|	at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
	|	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.run(HttpStreamOverHTTP2.java:128)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:421)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
	|	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	|	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:158)
	|	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:449)
	|	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	|	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	|	at org.eclipse.jetty.util.thread.Invocable.invokeNonBlocking(Invocable.java:156)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.invokeAsNonBlocking(AdaptiveExecutionStrategy.java:490)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:426)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
	|	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	|	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by sbordet**
HTTP/2 trailers may arrive and be processed before the application reads request chunks.

Avoid the race condition by storing the trailers aside and returning them during reads.

### CODE REVIEW

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 1]
```diff
@@ -150,37 +151,48 @@ public Content.Chunk read()
...
+        if (data == null)
+            return null;
 
+        // Check if the trailers must be returned.
+        if (data.frame().isEndStream() && trailer != null)
+        {
             try (AutoLock ignored = lock.lock())
             {
-                _chunk = chunk;
+                _chunk = Content.Chunk.next(trailer);
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: You could probably do this in the lock block above without grabbing the lock again,... but not work the complexity for trailers.

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 2]
```diff
@@ -150,37 +151,48 @@ public Content.Chunk read()
...
+        // The data instance should be released after readData() above;
+        // the chunk is stored below for later use, so should be retained;
+        // the two actions cancel each other, no need to further retain or release.
+        chunk = createChunk(data);
+
+        // Some content is read, but the 100 Continue interim
+        // response has not been sent yet, then don't bother
+        // sending it later, as the client already sent the content.
+        if (_expects100Continue && chunk.hasRemaining())
+            _expects100Continue = false;
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java:192]: It feels like this should be done with the lock held... which you are grabbing just below anyway?

**Review by gregw — COMMENTED** [review]
Mostly looks fine, but a  couple of questions before I approve.

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 3]
```diff
@@ -237,8 +248,7 @@ public Runnable onTrailer(HeadersFrame frame)
         HttpFields trailers = frame.getMetaData().getHttpFields().asImmutable();
         try (AutoLock ignored = lock.lock())
         {
-            _demand = false;
-            _chunk = new Trailers(trailers);
+            _trailer = new Trailers(trailers);
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java:254]: We know that end stream has not already been read?  I guess we could not read EOF unless trailers had been delivered?

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java:192]: Accesses to `_expects100Continue` are all driven by the application, so it should not need locking.

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: This code needs to be after `_stream.readData()`, so it cannot be moved above.

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java:254]: `DATA` frames are accumulated in the `Stream` and then read, but the trailer is notified immediately, hence the race condition this PR tries to fix.

When this method is called we know that all `DATA` frames have been accumulated, but they may have not been read yet, so we only remember the trailer here, and figure out the reads in `read()`.

Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java:254]: My concern is the other way around. i.e. can all the data frames be read before (or while) this method is called?  What is the guarantee that we have not already returned an EOF chunk to the application before we get the trailers.

My guess of how it is implemented makes me think that it will be OK, but would be good to confirm exactly why and say so in a comment.

**Review by gregw — DISMISSED** [review]
I still have a slight concern (see above) that could probably be addressed with a comment.   But other than that LGTM

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 4]
```diff
@@ -150,37 +151,48 @@ public Content.Chunk read()
...
+        }
+        if (chunk != null)
+            return chunk;
+
+        Stream.Data data = _stream.readData();
+        if (data == null)
+            return null;
 
+        // Check if the trailers must be returned.
+        if (data.frame().isEndStream() && trailer != null)
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: This check is racy: if the trailer gets delivered after `trailer = _trailer;` is executed under the 1st lock, `trailer` will be null while `_stream.readData()` will return EOF.

In such case, the trailers aren't delivered.

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java:254]: It might be worth mentioning in a comment that when a trailers `HEADERS` frame gets parsed, the stream enqueues a `EOF` data before calling `HttpStreamOverHTTP2.onTrailer()`.

**Review by lorban — CHANGES_REQUESTED** [review]
I think this code is still racy.

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 5]
```diff
@@ -150,37 +151,51 @@ public Content.Chunk read()
...
+            return null;
 
+        // Check if the trailers must be returned.
+        if (data.frame().isEndStream())
+        {
+            Content.Chunk trailer;
             try (AutoLock ignored = lock.lock())
             {
-                _chunk = chunk;
+                trailer = _trailer;
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java:174]: You could also null out `_trailer` here.

**Review by lorban — APPROVED** [review]
LGTM, besides one small nit that I'm leaving up to you to handle or not.

**Review by gregw — APPROVED** [review]

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java:174]: As `HttpStreamOverHTTP2` instances are per-request, I prefer to not null out the field, so that in case of dump/memory inspection we will know if a trailer was delivered.
