### PR TITLE
Call completeStream only once on failure.

### LINKED ISSUE #13470: Jetty 12.0: ManagedSession issues due to recursion and/pr multiple completions of the stream.
**Jetty version(s)**
12.0.17

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.15" 2025-04-15
OpenJDK Runtime Environment Temurin-17.0.15+6 (build 17.0.15+6)
OpenJDK 64-Bit Server VM Temurin-17.0.15+6 (build 17.0.15+6, mixed mode, sharing)

**OS type/version**
Rocky Linux release 9.5 (Blue Onyx)

**Description**

Environment:
- Embedded Jetty ee10 in our application
- Session stack: DefaultSessionCache + NullSessionDataStore
- Production traffic is primarily HTTP/2

After upgrading to Jetty 12, we see a accumulation of ManagedSession instances in DefaultSessionCache. Heap dumps show thousands of sessions remaining in VALID state even though their lastAccessed timestamps are weeks in the past and maxInactiveMs is 600_000 (10 minutes). A common property of all leaked sessions is that their sessionInactivityTimer is set to Long.MAX_VALUE, which appears to prevent the HouseKeeper from ever expiring them. Over several months of uptime, about 6,000 such sessions accumulate. This behavior is only observed on Jetty 12; Jetty 11 behaves correctly with the same application and traffic pattern.

**How to reproduce?**

We cannot reproduce this in our lab/test environment; in lab, sessions are consistently expired and removed as expected.

### PR DESCRIPTION
**Pull request by gregw**
Fix #13470 by calling completeStream only once even when there is a failure in the channel callback.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 1]
```diff
@@ -1576,7 +1576,7 @@ public void succeeded()
                     if (!stream.isCommitted())
                         errorResponse = new ErrorResponse(request);
                     else
-                        completeStream = true;
+                        completeStream = httpChannelState._handling == null;
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I believe this is the fix to prevent completeStream being called whilst we are still handling.  See analysis in main discussion.

**Comment by gregw** [comment]
The issue is fundamentally that `completeStream` is being called twice.

For this to happen, we need a failure to be detected in the `ChannelCallback.succeeded()` method so that the following code isrun:
https://github.com/jetty/jetty.project/blob/8dbd9865cc7407d735084a181cc3f21205872b70/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java#L1573-L1580

This means that  `completeStream` will be called, even though the other "legs of the 3 legged stool" are not complete - specifically we may still be inside the call to `HandlerInvoker.run()`, as in this stack for thread 258 :
```
2025-10-20 08:14:42,457 INFO  [WebServerImpl-258] trace.jetty.session.complete: complete() called on session [ManagedSession@4df349fb{id=MYSECRETSESSIONID,x=MYSECRETSESSIONID.node0,req=6,res=true}]
java.lang.Exception: complete stack
	...
	at org.eclipse.jetty.session.AbstractSessionManager.complete(AbstractSessionManager.java)
	at org.eclipse.jetty.session.AbstractSessionManager$SessionStreamWrapper.doComplete(AbstractSessionManager.java:1509)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1518)
	at org.eclipse.jetty.session.AbstractSessionManager$SessionStreamWrapper.failed(AbstractSessionManager.java:1479)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.completeStream(HttpChannelState.java:788)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.succeeded(HttpChannelState.java:1591)
	at org.eclipse.jetty.server.handler.gzip.GzipResponseAndCallback.succeeded(GzipResponseAndCallback.java:95)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.onCompleted(ServletChannel.java:765)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:429)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:470)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1071)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:138)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:611)
	at org.eclipse.jetty.server.Handler$Sequence.handle(Handler.java:805)
	at org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:677)
	at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:177)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.run(HttpStreamOverHTTP2.java:144)
	...
```

We can see that there is a failure detected in `ChannelCallback.succeeded()` because `SessionStreamWrapper.failed`  is ultimately called.  This means that there must have been one of the following application errors:
 + https://github.com/jetty/jetty.project/blob/8dbd9865cc7407d735084a181cc3f21205872b70/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java#L1543
 + https://github.com/jetty/jetty.project/blob/8dbd9865cc7407d735084a181cc3f21205872b70/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java#L1545
 + https://github.com/jetty/jetty.project/blob/8dbd9865cc7407d735084a181cc3f21205872b70/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java#L1563

These are all plausible application errors, especially with something like server sent events.

So once thread 258 has called `completeStream` it returns all the way out of handling and it can be seen calling `completeStream` again, in this stack trace:
```
java.lang.Exception: complete stack
	...
	at org.eclipse.jetty.session.AbstractSessionManager.complete(AbstractSessionManager.java)
	at org.eclipse.jetty.session.AbstractSessionManager$SessionStreamWrapper.doComplete(AbstractSessionManager.java:1509)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1524)
	at org.eclipse.jetty.session.AbstractSessionManager$SessionStreamWrapper.failed(AbstractSessionManager.java:1479)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.completeStream(HttpChannelState.java:788)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:712)
	at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:177)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.run(HttpStreamOverHTTP2.java:144)
	...
```

which is called from this code after the handler has been invoked:
https://github.com/jetty/jetty.project/blob/8dbd9865cc7407d735084a181cc3f21205872b70/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java#L691-L713

Note that in order for this code to actually call `completeStream` then it must be `true` that `completeStream = callbackCompleted && lastStreamSendComplete`.   Note that this is normally not the case for HTTP/1 because the first call to `completeStream` would have recycled the `HttpChannelState` and the `callbackCompleted` and `lastStreamSendComplete` will both be false.   However, for H2, `HttpChannelState`s are re-used after being recycled, so another request may have come in and set the fields of the state again, so that the second call to `completeStream` incorrectly completes that new request.

Thus I believe the core fix is to not call `completeStream` whilst we are still handling.  Furthermore, if we are to ignore the last write leg of the stool, we should explicitly force `lastStreamSendComplete` to true;

Unfortunately I have been unable to produce a unit test for this, as I believe it needs precisely unlucky timing and an application error.

**Comment by gregw** [comment]
@sbordet @lorban Can you review the diagnosis that @janbartel and I have come up with.  I'm 90% sure this is it, but I cannot reproduce (any thoughts how we might be able to do that?).

**Comment by gregw** [comment]
Note that we added this `completeStream` call in https://github.com/jetty/jetty.project/pull/9684

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 2]
```diff
@@ -1574,9 +1574,14 @@ public void succeeded()
                 {
                     httpChannelState._callbackFailure = failure;
                     if (!stream.isCommitted())
+                        // We are not committed, so we can send an error response.
                         errorResponse = new ErrorResponse(request);
-                    else
+                    else if (httpChannelState._handling == null)
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I think this more precisely should be:


```suggestion
                    else if (httpChannelState._handled)
```

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 3]
```diff
@@ -1574,9 +1574,14 @@ public void succeeded()
...
+                        // We are committed, but no longer handling, so will complete here, ignoring any pending reads/writes
                         completeStream = true;
+                    else
+                        // We are committed and still handling, so let the HandlerInvoker complete, ignoring any pending reads/writes.
+                        httpChannelState._streamSendState = StreamSendState.LAST_COMPLETE;
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Again, not sure we should ignore pending writes.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 4]
```diff
@@ -1574,9 +1574,14 @@ public void succeeded()
                 {
                     httpChannelState._callbackFailure = failure;
                     if (!stream.isCommitted())
+                        // We are not committed, so we can send an error response.
                         errorResponse = new ErrorResponse(request);
-                    else
+                    else if (httpChannelState._handling == null)
+                        // We are committed, but no longer handling, so will complete here, ignoring any pending reads/writes
                         completeStream = true;
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I don't think this is right.

If there is a write pending, we cannot complete the stream, or we bypass one leg.
I think we should call `lockedIsLastStreamSendCompleted()` here to figure out whether that leg is done.

**Review by sbordet — CHANGES_REQUESTED** [review]
`ChannelCallback.failed()` seems not entirely correct either.

Can we write test cases for this scenario?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Or pending reads....  it is a difficult one.   I'll at least change the code to enumerate the possible states

**Comment by gregw** [comment]
> `ChannelCallback.failed()` seems not entirely correct either.

@sbordet I will look....

> Can we write test cases for this scenario?

Very hard, because unless there is another thread racing the second completeStream is not called.  I'm open to suggestions.

**Comment by gregw** [comment]
@sbordet @lorban I'm getting concerned at the number of tests this PR is breaking in its current state.
I think we need to take time to consider the more "cleanup" changes and probably only make this in 12.1.x

So I propose that this PR should simply be https://github.com/jetty/jetty.project/pull/13814/commits/83c17183f6a100253805f435241507cf4707a9d6 for 12.0.x (perhaps with the EventSourceServlet cleanups), and then we can do a wider cleanup and refactor in 12.1.x next month.

**Comment by lorban** [comment]
Regarding the minimal 12.0 fix, I think `httpChannelState._handling == null` should actually be `httpChannelState._handled`

**Comment by gregw** [comment]
@lorban this is passing tests now.... so let's go for this one?
@sbordet @lorban Review please!!

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 5]
```diff
@@ -1537,115 +1554,105 @@ public void succeeded()
...
+                // Turn pending demand or unconsumed input on persistent connections into failure
                 if (httpChannelState._onContentAvailable != null)
                     failure = ExceptionUtil.combine(failure, new IllegalStateException("demand pending"));
+                else if (httpChannelState.getConnectionMetaData().isPersistent())
+                    failure = ExceptionUtil.combine(failure, stream.consumeAvailable());
+                else
+                {
+                    Throwable unconsumed = stream.consumeAvailable();
+                    if (failure != null)
+                        ExceptionUtil.addSuppressedIfNotAssociated(failure, unconsumed);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1578]: Just `ExceptionUtil.combine(failure, stream.consumeAvailable());` as the line above?
But then, this `else` block is identical to the `else-if` above?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java [hunk 6]
```diff
@@ -191,6 +191,34 @@ public static boolean areNotAssociated(Throwable t1, Throwable t2)
...
+    /**
+     * Checks if a given {@link Throwable} is associated with a specific type of {@link Throwable}.
+     * The association is determined by whether the provided type matches the throwable or any of its causes
+     * or suppressed exceptions.
+     *
+     * @param failure The {@link Throwable} to check for association. Can be null.
+     * @param throwable The type of {@link Throwable} class to check association against. Can be null.
+     * @return true if the {@link Throwable} is associated with the provided type; otherwise, false.
+     */
+    public static boolean isAssociated(Throwable failure, Class<? extends Throwable> throwable)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/ExceptionUtil.java]: Reads better `hasAssociated()` to me.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 7]
```diff
@@ -1537,115 +1554,105 @@ public void succeeded()
...
+                        // Callback and handling are completed, so it is just a matter of the last write
+                        if (httpChannelState.lockedIsLastStreamSendCompleted())
+                        {
+                            // We are committed, handling completed, and last write completed, so complete the stream now.
+                            completeStream = true;
+                        }
+                        else if (response.lockedIsWriting())
+                        {
+                            // We are currently writing, so let the completion of that write handle the failure
+                            httpChannelState._callbackFailure = failure;
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Unnecessary line.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 8]
```diff
@@ -1537,115 +1554,105 @@ public void succeeded()
...
+                            failedCallback = response._writeCallback;
+                            response._writeCallback = httpChannelState._handlerInvoker;
+                        }
+                        else
+                        {
+                            // There has been no last write, but we will just fail the stream instead.
+                            completeStream = true;
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1639]: Feels like it should be this, so the third leg is complete:


```suggestion
                            httpChannelState._streamSendState = StreamSendState.FAILED;
                            completeStream = true;
```

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 9]
```diff
@@ -1537,115 +1554,105 @@ public void succeeded()
...
+                        }
+                    }
+                    else if (!httpChannelState.lockedIsLastStreamSendCompleted() && !response.lockedIsWriting())
+                    {
+                        // last write is not going to happen after failure, so we can just fail anyway
+                        httpChannelState._streamSendState = StreamSendState.LAST_COMPLETE;
+                    }
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: If `lockedIsWriting()` I should do the same logic as above: steal the write callback, etc.

I would prefer this `else-if` to be written as just `else`, because the lack of a catch-all `else` branch feels like we're forgetting something: I prefer to have an explicit branch that says "here we should really do nothing".

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 10]
```diff
@@ -1537,115 +1554,105 @@ public void succeeded()
...
-                if (unconsumed != null && httpChannelState.getConnectionMetaData().isPersistent())
-                    failure = ExceptionUtil.combine(failure, unconsumed);
-
-                if (failure != null)
+                // If we are still not failing, is a last stream send needed or can we complete?
+                if (failure == null)
                 {
+                    doLastStreamSend = httpChannelState.lockedLastStreamSend();
+                    if (doLastStreamSend)
+                        response._writeCallback = httpChannelState._handlerInvoker;
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: This feels really sneaky.

Why not just doing `response.write(true, null, httpChannelState._handlerInvoker)`?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 11]
```diff
@@ -619,7 +624,9 @@ public String toString()
         }
     }
 
-    private class HandlerInvoker implements Invocable.Task, Callback
+    // HandlerInvoker is used as the Response's _writeCallback when ChannelCallback is succeeded and the last send still
+    // needs to be done, i.e.: _streamSendState set to LAST_SENDING by lockedLastStreamSend().
+    private class HandlerInvoker implements Task, Callback
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I think we should split the functionality of this class.
Leave `run()` in `HandlerInvoker`, but move the `Callback` functionality into a `LastStreamSendCallback` class.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 12]
```diff
@@ -1537,115 +1554,105 @@ public void succeeded()
...
+                        {
+                            // We are committed, handling completed, and last write completed, so complete the stream now.
+                            completeStream = true;
+                        }
+                        else if (response.lockedIsWriting())
+                        {
+                            // We are currently writing, so let the completion of that write handle the failure
+                            httpChannelState._callbackFailure = failure;
+                            failedCallback = response._writeCallback;
+                            response._writeCallback = httpChannelState._handlerInvoker;
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: In this way, we may wait forever for the write to complete and invoke the `_handlerInvoker`.

How about this:


```suggestion
                            Runnable task = response.lockedFailWrite(failure);
                            failedCallback = Callback.from(task, httpChannelState._handlerInvoker);
```

In 12.1.x we will leverage the new `cancelSend()` feature automatically.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 13]
```diff
@@ -93,7 +93,10 @@ private enum StreamSendState
         LAST_SENDING,
 
         /** Last content sent and completed */
-        LAST_COMPLETE
+        LAST_COMPLETE,
+
+        /** Failing, so last send will never happen */
+        FAILED
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:99]: This state is only read, never assigned.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]:
```suggestion
                completeStream = _handled;
```

Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Retain the `InvocationType`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 5 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1578]: No this  is different.  If failure==null, then it remains null. i.e. it is not a failure to not consume.  I'll comment....

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1578]: Actually, I will try without the whole branch....

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I tried, but we also need to complete a stream in cases where we have not started handling yet.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 11 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: This is really not a 12.0 thing then

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 10 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Because we have done half the write mechanism already by doing the commit at 1578 above. Calling write now will not send the headers.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 12 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I'm not sure that continuing on with a pending write pointing at the HttpChannelState is a good idea.  Feels like an invitation for a race.   What is wrong waiting for the write to complete.  It won't be forever unless they have disabled idle timeout.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 5 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1578]: Branch is needed

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 13 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:99]: oops not fully pushed.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 14]
```diff
@@ -1537,115 +1564,125 @@ public void succeeded()
...
+                            // TODO If we don't want to wait for write completion then do
+                            //      Runnable task = response.lockedFailWrite(failure);
+                            //      failedCallback = Callback.from(task, httpChannelState._handlerInvoker);
+                            failedCallback = response._writeCallback;
+                            response._writeCallback = httpChannelState._lastWriteCallback;
+                        }
+                        else
+                        {
+                            // There has been no last write, but we will just fail the stream instead.
+
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Remove empty line.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 15]
```diff
@@ -1537,115 +1564,125 @@ public void succeeded()
...
+                            httpChannelState._streamSendState = StreamSendState.FAILED;
+                            completeStream = true;
+                        }
+                    }
                     else
-                        completeStream = true;
+                    {
+                        // We are still handling, sof for the most part
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]:
```suggestion
                        // We are still handling, so for the most part
```

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 16]
```diff
@@ -1537,115 +1564,125 @@ public void succeeded()
...
             }
 
             if (LOG.isDebugEnabled())
-                LOG.debug("succeeded: failure={} needLastStreamSend={} {}", failure, needLastStreamSend, this);
+                LOG.debug("succeeded: failure={} doLastStreamSend={} {}", failure, doLastStreamSend, this);
+
+            if (failedCallback != null)
+                failedCallback.failed(Objects.requireNonNullElseGet(failure, IOException::new));
 
             if (errorResponse != null)
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: This should be an `if + else-if` because it is never the case that if we have a `failedCallback` we want to check the other cases below.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 17]
```diff
@@ -1537,115 +1564,125 @@ public void succeeded()
...
+                            //      Runnable task = response.lockedFailWrite(failure);
+                            //      failedCallback = Callback.from(task, httpChannelState._handlerInvoker);
+                            failedCallback = response._writeCallback;
+                            response._writeCallback = httpChannelState._lastWriteCallback;
+                        }
+                        else if (!httpChannelState.lockedIsLastStreamSendCompleted())
+                        {
+                            // last write it is not going to happen after failure, so we can just fail anyway
+                            httpChannelState._streamSendState = StreamSendState.FAILED;
+                        }
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:1657]: I would prefer to have an explicit `else` branch, otherwise feels like we are missing something.
Even if it is `else LOG.debug("Nothing to do in this case")`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Should not this be NON_BLOCKING?
It only completes the `HttpStream`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 12 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: > I'm not sure that continuing on with a pending write pointing at the HttpChannelState is a good idea.

I'm not sure what you mean above.

My point is that failing the callback may return the buffer to the pool, while the write is still pending.
We fixed this in 12.1.x with `cancelSend()`, but we don't leverage it here, while we would if we call `lockedFailWrite()`.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]

**Review by lorban — APPROVED** [review]
