### PR TITLE
Issue #10473 - Better warnings in `jetty.sh` on filesystem permission issues

### LINKED ISSUE #10473: Startup Script reports `ok` too fast, and doesn't wait for actual start of Jetty
**Jetty version(s)**
10.0.16

**Jetty Environment**
N/A

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.8" 2023-07-18 LTS

**OS type/version**
Amazon Linux 2

**Description**
Jetty starts fine, but startup script throws error. PID file is empty, so stopping the service is not working.

Startup:
```
# service jetty start
Starting Jetty: pgrep: option requires an argument -- 'P'

Usage:
 pgrep [options] <pattern>

Options:
 -d, --delimiter <string>  specify output delimiter
 -l, --list-name           list PID and process name
 -a, --list-full           list PID and full command line
 -v, --inverse             negates the matching
 -w, --lightweight         list all TID
 -c, --count               count of matching processes
 -f, --full                use full process name to match
 -g, --pgroup <PGID,...>   match listed process group IDs
 -G, --group <GID,...>     match real group IDs
 -n, --newest              select most recently started
 -o, --oldest              select least recently started
 -P, --parent <PPID,...>   match only child processes of the given parent
 -s, --session <SID,...>   match session IDs
 -t, --terminal <tty,...>  match by controlling terminal
 -u, --euid <ID,...>       match by effective IDs
 -U, --uid <ID,...>        match by real IDs
 -x, --exact               match exactly with the command name
 -F, --pidfile <file>      read PIDs from file
 -L, --logpidfile          fail if PID file is not locked
 --ns <PID>                match the processes that belong to the same
                           namespace as <pid>
 --nslist <ns,...>         list which namespaces will be considered for
                           the --ns option.
                           Available namespaces: ipc, mnt, net, pid, user, uts

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see pgrep(1).
ok Mon Sep  4 10:25:13 CEST 2023
```

Stop:
```
# service jetty stop
Stopping Jetty: ERROR: no pid id found in /var/jetty/run/jetty-helse.pid
```

**How to reproduce?**
Start and stop jetty

### PR DESCRIPTION
**Pull request by joakime**
Adding more checks in `jetty.sh` for common file system permission issues.

Examples:

**Don't have write/create access to JETTY_RUN directory path**

``` shell
[jetty-base]$ export JETTY_RUN=/var/run/jetty-no-exist
[jetty-base]$ ../jetty-home-10.0.17-SNAPSHOT/bin/jetty.sh start
mkdir: cannot create directory ‘/var/run/jetty-no-exist’: Permission denied
** ERROR: Unable to create directory: /var/run/jetty-no-exist
          Correct issues preventing use of $JETTY_RUN and try again.
```

**Don't have write/create access to JETTY_PID file path location**

Note: the `/var/run/` path exist in the following tests, but the Jetty user doesn't have permissions to write there.

``` shell
[jetty-base]$ export JETTY_PID=/var/run/jetty.pid
[jetty-base]$ ../jetty-home-10.0.17-SNAPSHOT/bin/jetty.sh start
Starting Jetty: touch: cannot touch ‘/var/run/jetty.pid’: Permission denied
** ERROR: Unable to touch file: /var/run/jetty.pid
          Correct issues preventing use of $JETTY_PID and try again.
```

**Don't have write/create access to JETTY_STATE file path location**

``` shell
[jetty-base]$ export JETTY_STATE=/var/run/jetty.state
[jetty-base]$ ../jetty-home-10.0.17-SNAPSHOT/bin/jetty.sh start
Starting Jetty: touch: cannot touch ‘/var/run/jetty.state’: Permission denied
** ERROR: Unable to touch file: /var/run/jetty.state
          Correct issues preventing use of $JETTY_STATE and try again.
```

### CODE REVIEW

File: jetty-home/src/main/resources/bin/jetty.sh [hunk 1]
```diff
@@ -358,7 +368,15 @@ fi
...
 then
   JETTY_RUN=$(findDirectory -w /var/run /usr/var/run $JETTY_BASE /tmp)/jetty
-  [ -d "$JETTY_RUN" ] || mkdir $JETTY_RUN
+fi
+
+if [ ! -d "$JETTY_RUN" ] ; then
+  if ! mkdir $JETTY_RUN
+  then
+    echo "** ERROR: Unable to create directory: $JETTY_RUN"
+    echo "          Correct issues preventing use of \$JETTY_RUN and try again."
```
Comment (sbordet) [inline jetty-home/src/main/resources/bin/jetty.sh]:
```suggestion
    echo "          Correct issues preventing the creation of \$JETTY_RUN and try again."
```

File: jetty-home/src/main/resources/bin/jetty.sh [hunk 2]
```diff
@@ -503,13 +526,27 @@ fi
...
 case "$ACTION" in
   start)
-    echo -n "Starting Jetty: "
-
     if (( NO_START )); then
       echo "Not starting ${NAME} - NO_START=1";
       exit
     fi
 
+    if ! touch "$JETTY_PID"
```
Comment (sbordet) [inline jetty-home/src/main/resources/bin/jetty.sh:534]: Assumes that `touch` is available.

Can't we use `bash` built-in stuff like we do when testing for readability?
I.e. `if [ ! -w "$JETTY_PID" ]`

File: jetty-home/src/main/resources/bin/jetty.sh [hunk 3]
```diff
@@ -519,15 +556,16 @@ case "$ACTION" in
...
        --start $CH_USER \
        --pidfile "$JETTY_PID" \
        --chdir "$JETTY_BASE" \
        --background \
+       --output "${JETTY_RUN}/start-stop.log"
        --make-pidfile \
        --startas "$JAVA" \
        --
-
+      (( DEBUG )) && echo "Starting: start-stop-daemon usage"
```
Comment (sbordet) [inline jetty-home/src/main/resources/bin/jetty.sh]:
```suggestion
      (( DEBUG )) && echo "Starting: start-stop-daemon"
```

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-home/src/main/resources/bin/jetty.sh (hunk 2 above)
Comment (joakime) [reply jetty-home/src/main/resources/bin/jetty.sh:534]: The benefit of using `touch` is that if the file doesn't exist it will attempt to create it, which will trigger the permission issue (if such an issue exists)
The `-w` bash option will only return "true if file exists and is writable"

``` shell
# Lets try testing a file that exists, is writable, but I don't have permissions to write.
[joakim@hyperion ~]$ ls -la /var/run/ubuntu-fan/
total 0
drwxr-xr-x  2 root root   60 Sep 28 07:36 .
drwxr-xr-x 46 root root 1340 Sep 28 07:36 ..
-rw-r--r--  1 root root    0 Sep 28 07:36 .lock
[joakim@hyperion ~]$ if [ -w /var/run/ubuntu-fan/.lock ] ; then echo "Is writable"; else echo "Is NOT writable"; fi
Is NOT writable

# Now lets try a bogus file in a directory I'm not allowed to write in
[joakim@hyperion ~]$ if [ -w /var/run/ubuntu-fan/bogus ] ; then echo "Is writable"; else echo "Is NOT writable"; fi
Is NOT writable

# Now lets try a bogus file in a directory I am ALLOWED to write in
[joakim@hyperion ~]$ if [ -w bogus ] ; then echo "Is writable"; else echo "Is NOT writable"; fi
Is NOT writable

# Now lets try a real file, that exists, and I can write to
[joakim@hyperion ~]$ if [ -w .bashrc ] ; then echo "Is writable"; else echo "Is NOT writable"; fi
Is writable
```

Comment (joakime) [reply jetty-home/src/main/resources/bin/jetty.sh:534]: Also, `touch` is not a function I would worry about.

We've had it in `jetty.sh` for a long time without issue.
https://github.com/jetty-project/codehaus-jetty6/blob/master/bin/jetty.sh#L541

Comment (sbordet) [reply jetty-home/src/main/resources/bin/jetty.sh:534]: Okay.

**Review by sbordet — APPROVED** [review]
