### PR TITLE
Issue #10207 Update missing JSP message.

### LINKED ISSUE #10207: Update failed JSP deployment message
**Jetty version(s)**
Jetty 12

**Enhancement Description**
`
2023-08-01 12:23:06.365:INFO :oejshC.jetty_ee10_demo_jsp_webapp_12_0_0_beta4:qtp1392425346-24: No JSP support.  Check that JSP jars are in lib/jsp and that the JSP option has been specified to start.jar
`

I think this message should be updated with module information, either a module name to add or pointer to documentation.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #10207 

Update the message shown when a JSP operation is attempted without jsp being present.

### CODE REVIEW

**Comment by janbartel** [comment]
@jmcc0nn3ll I didn't include a link to the doco because that moves around too much and would cause stale links.

**Comment by jmcc0nn3ll** [comment]
Looks good, agreed a link is a bit much but this gives people some direction at least, thanks!

**Comment by janbartel** [comment]
@jmcc0nn3ll  can you give me an approval review so I can commit?

**Comment by olamy** [comment]
Maybe this one as well needs the same change `org.eclipse.jetty.ee9.servlet.NoJspServlet`?

**Review by jmcc0nn3ll — DISMISSED** [review]
LGTM

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/NoJspServlet.java [hunk 1]
```diff
@@ -28,7 +28,7 @@ public class NoJspServlet extends HttpServlet
     protected void doGet(HttpServletRequest req, HttpServletResponse response) throws ServletException, IOException
     {
         if (!_warned)
-            getServletContext().log("No JSP support.  Check that JSP jars are in lib/jsp and that the JSP option has been specified to start.jar");
+            getServletContext().log("No JSP support. Check that the ee10-jsp module is enabled, or otherwise ensure the jsp jars are on the server classpath.");
```
Comment (joakime) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/NoJspServlet.java:31]: Wouldn't we need the same for ee9/ee8?

**Review by joakime — APPROVED** [review]

**Review by olamy — APPROVED** [review]
LGTM
