### PR TITLE
removal of exception stack traces in tests

### LINKED ISSUE #2567: Exceptions from passing tests in MisbehavingClassTest
[org/eclipse/jetty/websocket/jsr356/misbehaving/MisbehavingClassTest.java](https://github.com/eclipse/jetty.project/blob/09d40dc66507042f1cf865a89e7cacf431d2d584/jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/misbehaving/MisbehavingClassTest.java)

in tests `testListenerRuntimeOnConnect()` and `testAnnotatedRuntimeOnConnect()` the StacklessLogging is only working some of the time and other times the full stack traces are getting logged.

```
2018-05-23 19:10:12.162:WARN:oejwc.WebSocketSession:qtp910091170-26: 
java.lang.RuntimeException: Intentional Exception from onWebSocketConnect
	at org.eclipse.jetty.websocket.server.misbehaving.ListenerRuntimeOnConnectSocket.onWebSocketConnect(ListenerRuntimeOnConnectSocket.java:39)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onConnect(JettyListenerEventDriver.java:106)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:233)
	at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:616)
	at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:544)
	at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:202)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onOpen(AbstractWebSocketConnection.java:446)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:440)
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:385)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:702)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:498)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

### LINKED ISSUE #2569: Exceptions from passing test EchoTest.testEcho()
Getting somewhere in the range of 10-20 exceptions every time i run this test. Doesn't seem to be the same set of test cases every time.

```
2018-05-24 12:46:18.145:WARN:oejwjs.TrackingSocket:Time-limited test: 
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.succeedEntries(FrameFlusher.java:246)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.succeeded(FrameFlusher.java:234)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:342)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.flush(FrameFlusher.java:218)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.process(FrameFlusher.java:157)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:90)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:495)
	at org.eclipse.jetty.websocket.client.io.WebSocketClientConnection.outgoingFrame(WebSocketClientConnection.java:72)
	at org.eclipse.jetty.websocket.common.WebSocketSession.close(WebSocketSession.java:223)
	at org.eclipse.jetty.websocket.common.WebSocketSession.close(WebSocketSession.java:202)
	at org.eclipse.jetty.websocket.jsr356.JsrSession.close(JsrSession.java:147)
	at org.eclipse.jetty.websocket.jsr356.server.EchoClientSocket.close(EchoClientSocket.java:46)
	at org.eclipse.jetty.websocket.jsr356.server.EchoTest.testEcho(EchoTest.java:299)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #2567 
closes #2569

### CODE REVIEW

File: jetty-client/src/test/java/org/eclipse/jetty/client/ssl/SslBytesTest.java [hunk 1]
```diff
@@ -150,7 +150,10 @@ public void run()
             }
             catch (IOException x)
             {
-                x.printStackTrace();
+                logger.warn(x.getClass() + ": " + x.getMessage());
```
Comment (gregw) [inline jetty-client/src/test/java/org/eclipse/jetty/client/ssl/SslBytesTest.java]: perhaps make this an info if the exception is expected

File: jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/misbehaving/MisbehavingClassTest.java [hunk 2]
```diff
@@ -100,20 +95,21 @@ public void testEndpointRuntimeOnOpen() throws Exception
...
+            {
+                container.connectToServer(socket, serverUri);
+                fail("Should have failed .connectToServer()");
+            }
+            catch (IOException e)
+            {
+                assertThat(e.getCause(), instanceOf(RuntimeException.class));
+            }
+
+            assertThat("Close should have occurred", socket.closeLatch.await(1,TimeUnit.SECONDS), is(true));
```
Comment (gregw) [inline jetty-websocket/javax-websocket-client-impl/src/test/java/org/eclipse/jetty/websocket/jsr356/misbehaving/MisbehavingClassTest.java]: Wait 10 seconds at least, so a long GC or other pause does not break the test.

**Comment by gregw** [comment]
@lachlan-roberts can you merge with jetty-9.4.x to get some fixes to flaky tests and we can see if jenkins will build
