### PR TITLE
Fix connection pool's forcible stop

### LINKED ISSUE #9275: Jetty-12 H3 tests passing after 30s timeout
**Jetty version(s)**
12
**Java version/vendor** `(use: java -version)`
java 17

**OS type/version**

linux

**Description**

Many of the H3 tests in org.eclipse.jetty.test.client.transport.HttpClientStreamTest are taking over 30s to complete.

Screenshot from 2023-02-01 14-54-21
Screenshot from 2023-02-01 14-54-04
Screenshot from 2023-02-01 14-53-43

**How to reproduce?**

Run test from IDE

### PR DESCRIPTION
**Pull request by lorban**
Fixes #9275.

### CODE REVIEW

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 1]
```diff
@@ -1099,6 +1104,61 @@ public boolean process(Request request, org.eclipse.jetty.server.Response respon
...
+        client.newRequest(newURI(transport)).send(result -> {});
+
+        // Wait until both requests are in-flight.
+        await().atMost(timeoutInSeconds, TimeUnit.SECONDS).until(processCount::get, is(2));
+
+        // Stop the client while it has requests in-flight.
+        Assertions.assertTimeout(Duration.ofSeconds(timeoutInSeconds), () -> LifeCycle.stop(client));
+
+        // Let the server threads go.
+        processLatch.countDown();
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java:1160]: Probably a good idea here to wait for a latch that is counted down in `send(result -> ...)`, otherwise we risk to stop the server while still inside the `Handler`, so it'll throw exceptions, etc.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java:1160]: Done.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java [hunk 2]
```diff
@@ -1099,6 +1104,63 @@ public boolean process(Request request, org.eclipse.jetty.server.Response respon
...
+
+        // Wait until both requests are in-flight.
+        await().atMost(timeoutInSeconds, TimeUnit.SECONDS).until(processCount::get, is(2));
+
+        // Stop the client while it has requests in-flight.
+        Assertions.assertTimeout(Duration.ofSeconds(timeoutInSeconds), () -> LifeCycle.stop(client));
+
+        // Let the server threads go & wait for the requests to be processed.
+        processLatch.countDown();
+        clientLatch.await(timeoutInSeconds, TimeUnit.SECONDS);
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Missing `assertTrue(...)`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/HttpClientStreamTest.java]: Done.

**Review by sbordet — APPROVED** [review]

**Review by gregw — APPROVED** [review]
