### PR TITLE
Fix #6868 Fix copy constructors

### LINKED ISSUE #6868: _uriCompliance attribute has been forgotten in the HttpConfiguration constructor from another configuration
**Jetty version(s)**
10.0.6 and 10.0.7-SNAPSHOT

**Java version/vendor** `(use: java -version)`
any

**OS type/version**
any

**Description**
In the constructor `public HttpConfiguration(HttpConfiguration config)`, the `_uriCompliance` is not copied from the original.

**How to reproduce?**
setting the jetty.httpConfig.uriCompliance to LEGACY in start.d/server.ini has no effect on the HttpConfiguration used for https

### PR DESCRIPTION
**Pull request by gregw**
Fix #6868 copy constructors found by static code analysis

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/ClassMatcher.java [hunk 1]
```diff
@@ -496,10 +496,16 @@ public ClassMatcher()
...
-        if (patterns != null)
-            setAll(patterns.getPatterns());
+        if (matcher != null)
+        {
+            _entries.putAll(matcher._entries);
+            _patterns.include(matcher._patterns.getIncluded().toArray(new Entry[0]));
+            _patterns.exclude(matcher._patterns.getExcluded().toArray(new Entry[0]));
+            _locations.include(matcher._locations.getIncluded().toArray(new Entry[0]));
+            _locations.exclude(matcher._locations.getExcluded().toArray(new Entry[0]));
+        }
```
Comment (lachlan-roberts) [inline jetty-webapp/src/main/java/org/eclipse/jetty/webapp/ClassMatcher.java]: The `ClassMatcher.add()` method actually sets `_locations` and `_patterns` anyway.

But I think this is equivalent behaviour, unless someone has a subclass of `ClassMatcher` to override `add(Entry)`.

**Review by lachlan-roberts — DISMISSED** [review]

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/ClassMatcher.java (hunk 1 above)
Comment (gregw) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/ClassMatcher.java]: yeah, it was more to keep the static analysis quiet so we can get a clean test.
Hmmm but your point about add is valid.   I'll see if I can suppress the analysis.

**Review by lachlan-roberts — APPROVED** [review]
