### PR TITLE
Issue #12720 - fix servlet error dispatch for errors generated by SecurityHandler

### LINKED ISSUE #12720: Error attributes not set on request in Jetty 12
**Jetty version(s)**
12.1.0.alpha1

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)

**Description**
I have migrated an application from:

Dropwizard 4.0.10
Jetty 11.0.24

to: 

Dropwizard 5.0.0-alpha.5
Jetty 12.1.0.alpha1

In the Jetty 12 version of the application, the error attributes are not getting set on the request, which results in the ErrorPageErrorHandler returning a generic error page rather than my custom error page.

**How to reproduce?**

I have a Jetty 11 and Jetty 12 version of the application here:

https://github.com/rorytorneymf/jetty11-error-attributes/blob/main/src/main/java/com/example/app/App.java 
https://github.com/rorytorneymf/jetty12-error-attributes/blob/main/src/main/java/com/example/app/App.java 

To debug, debug the main method with the arguments `server app-config-dev.json`.

If you debug the Jetty 11 version, setting a breakpoint on the `AttributesMap.setAttribute` and the `ErrorPageErrorHandler.getErrorPage` method, then navigate to an invalid URL such as `http://localhost:3200/bla` you will see that the error attributes are getting set via the `HttpChannelState.sendError` method:

jetty-11-attribute-getting-set

which then results in this line of code in the `ErrorPageErrorHandler` returning an appropriate value (403 in this case), which gets mapped to the custom error page:

```java
errorStatusCode = (Integer)request.getAttribute(Dispatcher.ERROR_STATUS_CODE);
```

However, repeating the above steps in the Jetty 12 version of the app, you will see that the error attributes are **not** getting set, which then results in this line of code in the `ErrorPageErrorHandler` returning null, which results in a generic error page being shown rather than my custom error page:

```java
errorStatusCode = (Integer)request.getAttribute(org.eclipse.jetty.server.handler.ErrorHandler.ERROR_STATUS);
```

From what I can tell, the error attributes should be getting set via [ServletChannelState.sendError](https://github.com/jetty/jetty.project/blob/jetty-12.1.0.alpha1/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java#L1074) in Jetty 12, but that is not getting called.

Note:

I originally thought that this was the same issue as https://github.com/jetty/jetty.project/issues/12505, but I don't think that's the case, as there does not seem to be any error attributes getting set (either server or servlet attributes).

### PR DESCRIPTION
**Pull request by lachlan-roberts**
### Closes #12720

Currently `SecurityHandler` does only `Response.writeError` when a 403 response needs to be sent. However this will not dispatch to a servlet error page, for this we need to do `AuthenticationState.writeError` and handle the case if it returns `AuthenticationState.ServeAs`.

### CODE REVIEW

**Comment by gregw** [comment]
@lachlan-roberts the CI failures look to be more than flakes.

**Review by gregw — CHANGES_REQUESTED** [review]
more than flakes

**Comment by lachlan-roberts** [comment]
@gregw the tests are failing because the `AuthenticationState.writeError` and `ErrorHandler.writeError` do not support taking a message string.

So do you think i should adjust both the `AuthenticationState.writeError` and `ErrorHandler.writeError` API to take a `String message`, or should I adjust the tests to not check for the `!authroized` string?

File: jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java [hunk 1]
```diff
@@ -589,6 +561,79 @@ else if (authenticationState == null)
...
+                    association = deferred.getAssociation();
+                if (association != null)
+                    association.close();
+            }
+        }
+
+        return true;
+    }
+
+    private RequestResponse serveAsWrap(Request request, Response response, AuthenticationState.ServeAs serveAs)
```
Comment (gregw) [inline jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java]: Just return the response and use getRequest

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java]: done

File: jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java [hunk 2]
```diff
@@ -589,6 +560,84 @@ else if (authenticationState == null)
...
+
+                @Override
+                public Request getRequest()
+                {
+                    return wrappedRequest;
+                }
+            };
+        }
+
+        return response;
```
Comment (gregw) [inline jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java]: This can return the unwrapped response, which will provide the unwrapped request.  So either only wrap the request in the if statement above OR you always need to wrap the response to return the wrapped request. See above suggestion

File: jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java [hunk 3]
```diff
@@ -589,6 +560,84 @@ else if (authenticationState == null)
...
+                    return headers;
+                }
+
+                @Override
+                public Request getRequest()
+                {
+                    return wrappedRequest;
+                }
+            };
+        }
```
Comment (gregw) [inline jetty-core/jetty-security/src/main/java/org/eclipse/jetty/security/SecurityHandler.java]:
```suggestion
        HttpURI uri = request.getHttpURI();
        Request wrappedRequest = serveAs.wrap(request);
        HttpFields.Mutable headers;
        if (uri.equals(wrappedRequest.getHttpURI()))
        {
            headers = response.getHeaders()
        }
        else
        {
            // URI is replaced, so filter out all metadata for the old URI
            response.getHeaders().put(HttpHeader.CACHE_CONTROL.asString(), HttpHeaderValue.NO_CACHE.asString());
            response.getHeaders().putDate(HttpHeader.EXPIRES.asString(), 1);
            headers = new HttpFields.Mutable.Wrapper(response.getHeaders())
            {
                @Override
                public HttpField onAddField(HttpField field)
                {
                    if (field.getHeader() == null)
                        return field;
                    return switch (field.getHeader())
                    {
                        case CACHE_CONTROL, PRAGMA, ETAG, EXPIRES, LAST_MODIFIED, AGE -> null;
                        default -> field;
                    };
                }
            };
        }
        return new Response.Wrapper(wrappedRequest, response)
        {
            @Override
            public HttpFields.Mutable getHeaders()
            {
                return headers;
            }

            @Override
            public Request getRequest()
            {
                return wrappedRequest;
            }
        };
    }
```

**Review by gregw — DISMISSED** [review]

**Review by joakime — APPROVED** [review]
