### PR TITLE
Fixes #9141 - Thread-safe Content.Chunk#slice

### LINKED ISSUE #9141: Thread-safe Content.Chunk#slice
**Jetty version(s)**
12

**Description**

The implementation of [`Content.Chunk#slice(int,int,boolean)`](https://github.com/eclipse/jetty.project/blob/jetty-12.0.0.alpha3/jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java#L605-L621) is not threadsafe.

If multiple threads are slicing off the same chunk, then incorrect results may occur as each thread modifies the pointers of the original chunk.   It should be able to use the `ByteBuffer#slice(int,int)` method to slice without modifying the original buffer.

### PR DESCRIPTION
**Pull request by sbordet**
* Changed Content.Chunk.slice(int, int, boolean) to have the same parameters as ByteBuffer.slice(int, int) for consistency.
* Updated Chunk.slice(int, int, boolean) javadocs.
* Update code that was calling Chunk.slice(int, int, boolean).

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 1]
```diff
@@ -596,36 +596,34 @@ default Chunk slice()
         }
 
         /**
-         * <p>Returns a new {@code Chunk} whose {@code ByteBuffer} is a slice, with the given
-         * position and limit, of the {@code ByteBuffer} of the source {@code Chunk} unless the
-         * source is {@link #isTerminal() terminal} in which case {@code this} is returned, or
-         * if {@code position == limit} in which case {@link #EOF} or {@link #EMPTY} is
-         * returned depending on the value of {@code last}.</p>
+         * <p>Returns a new {@code Chunk} whose {@code ByteBuffer} is a slice of the
+         * {@code ByteBuffer} of the this {@code Chunk}.</p>
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: typo: `of the this` -> `of this`

**Review by lorban — CHANGES_REQUESTED** [review]
LGTM besides a typo in the javadoc.

**Review by lorban — APPROVED** [review]

**Review by gregw — APPROVED** [review]
