### PR TITLE
Issue #4505 Ensure get/setInitParam with null arg throws NPE

### LINKED ISSUE #4505: Servlet 4 get/setInitParameter() and get/setAttribute() must throw NPE if arg is null
**jetty-10**

Servlet Spec 4, Changes Since 3.1,  page A-203:

2. Modify javadoc for ServletContext getAttribute() and getInitParameter() ,
specify that NullPointerException must be thrown if the argument “name” is
null.
3. Modify javadoc for ServletContext.setAttribute() and setInitParameter()
to specify that NullPointerException must be thrown if the “name” argument is
null.

### PR DESCRIPTION
**Pull request by janbartel**
Implement throw of NPE if key arg to get/setInitParam is null, as per servlet spec.

Closes #4505

### CODE REVIEW

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java [hunk 1]
```diff
@@ -1287,6 +1287,15 @@ private void checkDynamic(String name)
                 return null; //existing completed registration for servlet name
         }
 
+        @Override
+        public String getInitParameter(String name)
+        {
+            //since servlet spec 4.0
+            if (name == null)
+                throw new NullPointerException();
```
Comment (sbordet) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java]: Can you please use `Objects.requireNonNull()` here?

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java [hunk 2]
```diff
@@ -1296,6 +1305,10 @@ public boolean setInitParameter(String name, String value)
             if (!_enabled)
                 throw new UnsupportedOperationException();
 
+            //since servlet spec 4.0
+            if (name == null)
+                throw new NullPointerException();
```
Comment (sbordet) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletContextHandler.java]: Ditto above.

File: jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java [hunk 3]
```diff
@@ -470,6 +472,46 @@ public void destroyServer() throws Exception
...
+                assertEquals("bar", root.getServletContext().getInitParameter("foo"));
+                assertThrows(NullPointerException.class, 
+                    new Executable()
+                    {
+                        @Override
+                        public void execute() throws Throwable
+                        {
+                            sce.getServletContext().setInitParameter(null, "bad");
+                        }
+                    }
```
Comment (sbordet) [inline jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java]: Can these `Executable` be converted to lambdas?

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]
