### PR TITLE
Fixes #8532 - Review System.nanoTime() usages.

### LINKED ISSUE #8532: Review System.nanoTime() usages
**Jetty version(s)**
10+

**Description**
`System.nanoTime()`, as specified in its javadocs, can roll-over.
Because of that, it's wrong to use the `<` operator between values, as well as `Math.min()` etc.

This problem has already been reported in CometD, see https://github.com/cometd/cometd/issues/1215.

The whole codebase should be reviewed so that `System.nanoTime()` is properly used.

### PR DESCRIPTION
**Pull request by sbordet**
Introduced `o.e.j.util.NanoTime` class to deal with nanoTimes.

Now NanoTime.now() should be used instead of System.nanoTime(),
and various `<unit>elapsed*()` methods to calculate elapsed times.

Furthermore, comparing 2 nanoTimes should be done via `isBefore()`,
rather than using the `<` operator, which is wrong as specified in
the System.nanoTime() javadocs.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-util/src/main/java/org/eclipse/jetty/util/NanoTime.java [hunk 1]
```diff
@@ -0,0 +1,180 @@
...
+        return elapsed(beginNanoTime, now());
+    }
+
+    /**
+     * <p>Calculates the nanoseconds elapsed between the current nanoTime and an end nanoTime.</p>
+     *
+     * @param endNanoTime the end nanoTime
+     * @return the nanoseconds elapsed between the current nanoTime and the given end nanoTime
+     */
+    public static long elapsedTo(long endNanoTime)
```
Comment (lorban) [inline jetty-util/src/main/java/org/eclipse/jetty/util/NanoTime.java]: This name is confusing as `endNanoTime` is supposed to be in the future but the past tense in the method name suggests that it's in the past.
Something like `remaningTo` for instance sounds better to me.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-util/src/main/java/org/eclipse/jetty/util/NanoTime.java (hunk 1 above)
Comment (sbordet) [reply jetty-util/src/main/java/org/eclipse/jetty/util/NanoTime.java]: I like `remainingTo`, updated.

**Review by lorban — DISMISSED** [review]

**Review by gregw — CHANGES_REQUESTED** [review]
Quick review whilst I have network.
Mostly good, but can the methods of NanoTime be renamed:
- elapsed(long, long); since(long); until(long);
- millisElapsed(long, long); millisSince(long); millisUntil(long);
- secondsElapsed(long, long); secondsSince(long); secondsUntil(long);

I'll check more as I go....

File: jetty-server/src/test/java/org/eclipse/jetty/server/StressTest.java [hunk 2]
```diff
@@ -458,24 +458,19 @@ private static class TestHandler extends HandlerWrapper
...
-            long received = baseRequest.getTimeStamp();
 
             _handled.incrementAndGet();
-            long delay = received - start;
-            if (delay < 0)
-                delay = 0;
+            long delay = NanoTime.millisElapsed(start, now);
             _latencies[2].add(delay);
-            _latencies[3].add((now - start));
+            _latencies[3].add(delay);
```
Comment (gregw) [inline jetty-server/src/test/java/org/eclipse/jetty/server/StressTest.java:467]: I don't think this is the same logic?

**Review by gregw — CHANGES_REQUESTED** [review]
I've looked through all the files and other than the one query noted, I've not seen any issues other than better names for NanoTime methods.

File: jetty-util/src/main/java/org/eclipse/jetty/util/NanoTime.java (hunk 1 above)
Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/NanoTime.java]: `remainingTo` is not good phrasing.  It should be `remainingUntil` or just `until`.   I think using `elapsed`, `since` and `until` is clear.

File: jetty-server/src/test/java/org/eclipse/jetty/server/StressTest.java (hunk 2 above)
Comment (sbordet) [reply jetty-server/src/test/java/org/eclipse/jetty/server/StressTest.java:467]: It's not exactly the same logic, but before it was a garbage value, since `baseRequest.getTimeStamp()` returns an epoch millis time, and `delay` was calculated mixing up epoch millis with current nanoTime converted to millis -- a bogus number that could have even be negative.

Maybe `baseRequest.getTimeStamp()` should return a nanoTime, but `CustomRequestLog` relies on it to be a UTC dateTime -- feels like we should either use `Instant` or have 2 values (the nanoTime and the dateTime).

**Review by lorban — APPROVED** [review]
I like the new names better!

**Review by gregw — APPROVED** [review]

File: jetty-server/src/test/java/org/eclipse/jetty/server/StressTest.java (hunk 2 above)
Comment (gregw) [reply jetty-server/src/test/java/org/eclipse/jetty/server/StressTest.java:467]: Ok. It's only a test anyway, so if it is a nonsense value, perhaps delete it.
