### PR TITLE
Fixes #5498 ServletHolder cleanup

### LINKED ISSUE #5498: Review ServletHolder.getServlet
**Jetty version**
9.4.x

See discussion on https://github.com/eclipse/jetty.project/commit/c40b955e09f9cecc3c9048aecedda34a144def5e#commitcomment-43538925

It appears that dropwizard has wrapped the holder class to avoid the synchronisation in `ServletHolder.getServlet()`.  The class uses both a volatile `_servlet` field and synchronisation,  yet always grabs the lock in `getServlet()`.    We should either check the volatile before locking or not use a volatile at all.    Perhaps the following implementation may avoid any contention that was seen on that lock:

```java
    public Servlet getServlet()
        throws ServletException
    {
        Servlet servlet = _servlet;
        if (servlet == null)
        {
            synchronized (this)
            {
                if (_servlet == null && isRunning())
                {
                    if (getHeldClass() != null)
                        initServlet();
                }
                servlet = _servlet;
            }
        }

        return servlet;
    }
```

### PR DESCRIPTION
**Pull request by gregw**
Various cleanups for #5498 including:
 + renaming multiple `_servlet` fields in inner classes to avoid confusion
 + better comments in prepare method to describe why it is needed
 + call prepare from Invoker servlet
 + The `_servlet` field is not set until after the servlet is initialized
 + Consistent wrapping of `SingleThreadedWrapper` now in `initServlet`
 + The `getServlet` method now looks the volatile `_servlet` to avoid locking if possible
 + The `handle` method now calls `getServletInstance` as servlet will have been initialized in `prepare`

### CODE REVIEW

**Comment by gregw** [comment]
@joakime @janbartel @lorban nudge

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java [hunk 1]
```diff
@@ -1229,36 +1244,48 @@ public UnavailableServlet(UnavailableException unavailableException, Servlet ser
             }
             else
             {
-                _servlet = servlet;
-                _available = System.nanoTime() + TimeUnit.SECONDS.toNanos(unavailableException.getUnavailableSeconds());
+                _unavailableServlet = servlet;
+                _available.set(System.nanoTime() + TimeUnit.SECONDS.toNanos(unavailableException.getUnavailableSeconds()));
```
Comment (lorban) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java]: This doesn't take into account the potential numerical overflow of the timeout timestamp.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java [hunk 2]
```diff
@@ -1229,36 +1244,48 @@ public UnavailableServlet(UnavailableException unavailableException, Servlet ser
...
-            if (_available == -1)
-                ((HttpServletResponse)res).sendError(HttpServletResponse.SC_NOT_FOUND);
-            else if (System.nanoTime() < _available)
-                ((HttpServletResponse)res).sendError(HttpServletResponse.SC_SERVICE_UNAVAILABLE);
-            else
+            while (true)
             {
-                synchronized (ServletHolder.this)
+                long available = _available.get();
+                if (available < 0)
```
Comment (lorban) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java]: This doesn't take into account the potential numerical overflow of the timeout timestamp.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java [hunk 3]
```diff
@@ -1229,36 +1244,48 @@ public UnavailableServlet(UnavailableException unavailableException, Servlet ser
...
+                {
+                    ((HttpServletResponse)res).sendError(HttpServletResponse.SC_NOT_FOUND);
+                    return;
+                }
+
+                if (available == 0 || System.nanoTime() < available)
```
Comment (lorban) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java]: This doesn't take into account the potential numerical overflow of the timeout timestamp.

**Review by lorban — CHANGES_REQUESTED** [review]
Your changes look alright, but I found an unrelated bug caused by a mis-use of `System.nanoTime()`.

**Review by lorban — APPROVED** [review]

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java [hunk 4]
```diff
@@ -1229,36 +1237,52 @@ public UnavailableServlet(UnavailableException unavailableException, Servlet ser
...
 
         @Override
         public void service(ServletRequest req, ServletResponse res) throws ServletException, IOException
         {
-            if (_available == -1)
-                ((HttpServletResponse)res).sendError(HttpServletResponse.SC_NOT_FOUND);
-            else if (System.nanoTime() < _available)
-                ((HttpServletResponse)res).sendError(HttpServletResponse.SC_SERVICE_UNAVAILABLE);
-            else
+            while (true)
```
Comment (janbartel) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java]: Can we come up with a solution that removes the while(true) - I think these are best avoided if possible.

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java (hunk 4 above)
Comment (gregw) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java]: Will do, because I can in this situation.  However in general, the while(true) pattern is the best and simplest approach for atomic state machines.   More often than not, we've been wrong when we remove them... but I'm 99.9% sure in this case that we have it right.

**Review by janbartel — APPROVED** [review]
LGTM

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java [hunk 5]
```diff
@@ -557,33 +555,35 @@ private void makeUnavailable(final Throwable e)
...
-                _servlet = getInstance();
-            if (_servlet == null)
-                _servlet = newInstance();
+            if (servlet == null || servlet instanceof UnavailableServlet)
+                servlet = getInstance();
+            if (servlet == null)
+                servlet = newInstance();
+            if (servlet instanceof javax.servlet.SingleThreadModel)
+            {
+                destroyInstance(servlet);
```
Comment (janbartel) [inline jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java]: Actually, this isn't right:  we should _not_ call destroyInstance() because this will call servlet.destroy(), but at this stage we will _not_ have called servlet.init().

**Review by janbartel — CHANGES_REQUESTED** [review]
I'm gonna have to retract my LGTM.

File: jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java (hunk 5 above)
Comment (gregw) [reply jetty-servlet/src/main/java/org/eclipse/jetty/servlet/ServletHolder.java]: This has opened a rats nest  of issues!   It appears  that we do call predestroy on instances that have been passed in.  As we have tests for this potentially wrong behaviour, I think I will not fully address this in 9, but review during the merge to 10.

For now, I have split out a predestroy method, that is called on instances that have not yet been fully initialisd.

**Review by janbartel — APPROVED** [review]
LGTM

**Comment by joakime** [comment]
Why are we even letting people pull the `Servlet` instance out of the `ServletHolder`?

I question this entirely.
I'm of the opinion that we should just eliminate `ServletHolder.getServlet()`.

**Comment by gregw** [comment]
> I'm of the opinion that we should just eliminate `ServletHolder.getServlet()`.

Well perhaps make it private rather than public, but we still need the basic logic..... but making it private is a bridge too far for 9 I think.
