### PR TITLE
Issue #10271 - Introduce `jetty-pid.xml`

### LINKED ISSUE #10271: jetty.sh does not stop jetty anymore
**Jetty version(s)**
10.0.15

**Java version/vendor** `(use: java -version)`
openjdk version "11.0.19" 2023-04-18 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.19.0.7-1.el7_9) (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.19.0.7-1.el7_9) (build 11.0.19+7-LTS, mixed mode, sharing)

**OS type/version**
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Description**
This bug was likely introduced by #9309 which introduces `xargs` to launch `java`. The [relevant lines](https://github.com/eclipse/jetty.project/blob/91455908205a85c68582b1aa01baaae527c5eef3/jetty-home/src/main/resources/bin/jetty.sh#L502) are

```sh
        echo ${RUN_ARGS[*]} | xargs ${JAVA} > /dev/null &
        disown $!
        echo $! > "$JETTY_PID"
```
`$!` now returns the PID of the `xargs` process, not the java one. Consequently, `jetty.sh stop` now stops `xargs`, but at least on my system killing `xargs` (version "xargs (GNU findutils) 4.5.11") does not terminate its child processes.

Note also that on systems with `start-stop-daemon`, this probably works as `start-stop-daemon` writes the child PID in the PID file if I understand the man page correctly.

The probably simplest (not best) way to fix this is to retrieve the correct PID with something like
```sh
 echo `pgrep -P $!` > "$JETTY_PID"
```

**How to reproduce?**
Issue should appear with unmodified jetty distribution on any system without `start-stop-daemon`.

### PR DESCRIPTION
**Pull request by joakime**
New `jetty-pid.xml`, used by `jetty.sh` functions similar to `jetty-started.xml` and will have Jetty itself produce (and remove) a pid file based on configuration in `jetty.sh` (eg: the `$JETTY_PID` value)

### CODE REVIEW

File: jetty-home/src/main/resources/bin/jetty.sh [hunk 1]
```diff
@@ -495,13 +495,10 @@ case "$ACTION" in
         # FIXME: Broken solution: wordsplitting, pathname expansion, arbitrary command execution, etc.
```
Comment (sbordet) [inline jetty-home/src/main/resources/bin/jetty.sh]: Should not this comment be removed?

File: jetty-home/src/main/resources/bin/jetty.sh [hunk 2]
```diff
@@ -495,13 +495,10 @@ case "$ACTION" in
...
         su - "$JETTY_USER" $SU_SHELL -c "
           cd \"$JETTY_BASE\"
-          echo ${RUN_ARGS[*]} start-log-file=\"$JETTY_START_LOG\" | xargs ${JAVA} > /dev/null &
-          disown \$!
-          echo \$! > \"$JETTY_PID\""
+          echo ${RUN_ARGS[*]} --pid-file=\"$JETTY_PID\" start-log-file=\"$JETTY_START_LOG\" | xargs ${JAVA} > /dev/null &
+          "
```
Comment (sbordet) [inline jetty-home/src/main/resources/bin/jetty.sh]: Why `disown` was removed?

File: jetty-home/src/main/resources/bin/jetty.sh [hunk 3]
```diff
@@ -495,13 +495,10 @@ case "$ACTION" in
...
       else
-        echo ${RUN_ARGS[*]} | xargs ${JAVA} > /dev/null &
-        disown $!
-        echo $! > "$JETTY_PID"
+        echo ${RUN_ARGS[*]} | xargs ${JAVA} --pid-file="$JETTY_PID" > /dev/null &
```
Comment (sbordet) [inline jetty-home/src/main/resources/bin/jetty.sh]: In the line above, `--pid-file` is _before_ `xargs`, why here is after?

File: jetty-home/src/main/resources/etc/jetty-pid.xml [hunk 4]
```diff
@@ -0,0 +1,15 @@
+<?xml version="1.0"?>
+<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_9_3.dtd">
+
+<!-- =============================================================== -->
+<!-- Mixin the Start FileNoticeLifeCycleListener                     -->
+<!-- =============================================================== -->
```
Comment (sbordet) [inline jetty-home/src/main/resources/etc/jetty-pid.xml]: Remove this comment, it is wrong and not necessary.

File: jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java [hunk 5]
```diff
@@ -919,6 +920,11 @@ public String getModuleGraphFilename()
         return moduleGraphFilename;
     }
 
+    public String getPidFile()
+    {
+        return pidFile;
```
Comment (sbordet) [inline jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java]: Is this field ever assigned?

File: jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java [hunk 6]
```diff
@@ -1169,6 +1175,13 @@ public void parse(final String rawarg, String source)
             return;
         }
 
+        if (arg.startsWith("--pid-file="))
+        {
+            setProperty("jetty.pid.file", pidFile, source);
+            xmlRefs.add("etc/jetty-pid.xml");
```
Comment (sbordet) [inline jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java]: I don't know if this is the right way, as `jetty-started.xml` is similar but done in a completely different way.

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+
+    @Override
+    public void lifeCycleStarting(LifeCycle event)
+    {
+        long pid = ProcessHandle.current().pid();
+        try
+        {
+            Files.writeString(pidFile, Long.toString(pid), StandardCharsets.UTF_8);
+        }
+        catch (IOException e)
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java]: Catch `Throwable`.

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java [hunk 8]
```diff
@@ -0,0 +1,73 @@
...
+        removePid();
+    }
+
+    private void removePid()
+    {
+        try
+        {
+            Files.deleteIfExists(pidFile);
+        }
+        catch (IOException e)
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java]: Catch `Throwable`.

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java [hunk 9]
```diff
@@ -0,0 +1,73 @@
...
+        {
+            LOG.warn("Unable to remove pidFile: {}", pidFile, e);
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java]: I would log at DEBUG level here.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-home/src/main/resources/bin/jetty.sh (hunk 2 above)
Comment (joakime) [reply jetty-home/src/main/resources/bin/jetty.sh]: It can only disown xargs, which is pointless.

File: jetty-home/src/main/resources/bin/jetty.sh (hunk 3 above)
Comment (joakime) [reply jetty-home/src/main/resources/bin/jetty.sh]: Good point.  This reads as an arg for java, not jetty, which wouldn't work.

Trying to get some environments together to test these various permutations. (with and without start-stop-daemon, for example)

File: jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java (hunk 6 above)
Comment (joakime) [reply jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java]: It is similar, yes.
I'll see if I can work this into jetty.sh exclusively (with no changes to StartArgs)

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java (hunk 9 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java]: If the PID file cannot be removed (eg: a permission issue) that should be presented as a warning.
As that will impact the ability to restart the service.

File: jetty-home/src/main/resources/bin/jetty.sh (hunk 2 above)
Comment (joakime) [reply jetty-home/src/main/resources/bin/jetty.sh]: Came up with a different way, just tell disown to disown the child pids of xargs.

File: jetty-home/src/main/resources/bin/jetty.sh (hunk 3 above)
Comment (joakime) [reply jetty-home/src/main/resources/bin/jetty.sh]: Reworked to not rely on behaviors in StartArgs, but rather using a technique similar to `jetty-started.xml`

File: jetty-home/src/main/resources/etc/jetty.conf [hunk 10]
```diff
@@ -9,3 +9,4 @@
 # in addition to those found in the start.ini file
 # =======================================================
 jetty-started.xml
+jetty-pid.xml
```
Comment (gregw) [inline jetty-home/src/main/resources/etc/jetty.conf]: This might be better as a optional extra behaviour of `org.eclipse.jetty.util.component.FileNoticeLifeCycleListener` (whose name really should better match the xml) rather than as an entirely separate mechanism.

I'm also thinking that both these xmls (or the combined if we go that way) would be best added via a module now, rather than as a special "hidden" argument added by the `jetty.sh` mechanism.   It would be nice if any dry-run command generated by the start process could correctly create/delete the pid file.

So the `jetty.conf` file could instead have a line like:
```
--module=pid,started
```

Comment (gregw) [reply jetty-home/src/main/resources/etc/jetty.conf]: Perhaps keeping the mechanism separate is better? I'm 50:50.   
If we keep them separate, perhaps rename `FileNoticeLifeCycleListener` to `StartedFileLifeCycleListener`

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java [hunk 11]
```diff
@@ -0,0 +1,72 @@
...
+    public void lifeCycleFailure(LifeCycle event, Throwable cause)
+    {
+        removePid();
+    }
+
+    @Override
+    public void lifeCycleStopped(LifeCycle event)
+    {
+        removePid();
+    }
```
Comment (gregw) [inline jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java]: Are these really the right events to remove the PID file?
A server may be stopped and/or failed, but the JVM process can still be running

**Review by gregw — CHANGES_REQUESTED** [review]
I now think the PID mechanism should be different from the started mechanism, as the PID relates to the process and not the server.

Thus I think it should not be a `LifeCycleListener` and instead should be it's own shutdown hook.    As soon as the hook is created, it should create the pid file and register a shutdown hook that will delete the file only as the JVM stops, which is technically unrelated to any stop/start/fails that the server might do.

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java (hunk 11 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java]: Fair enough

Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/component/PidFileLifeCycleListener.java]: Maybe get rid of removePid all together?

**Comment by joakime** [comment]
> I now think the PID mechanism should be different from the started mechanism, as the PID relates to the process and not the server.
> 
> Thus I think it should not be a `LifeCycleListener` and instead should be it's own shutdown hook. As soon as the hook is created, it should create the pid file and register a shutdown hook that will delete the file only as the JVM stops, which is technically unrelated to any stop/start/fails that the server might do.

I'll give that a whirl, in a different PR, to see how it looks.

**Comment by joakime** [comment]
@gregw I reworked this PR (no new PR) to be based on Shutdown behaviors.
WDYT?

File: jetty-server/src/main/java/org/eclipse/jetty/server/PidFile.java [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+    private static final Logger LOG = LoggerFactory.getLogger(PidFile.class);
+
+    private final Path pidFile;
+
+    public PidFile(@Name("file") String filename)
+    {
+        pidFile = Paths.get(filename);
+        try
+        {
+            long pid = ProcessHandle.current().pid();
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/PidFile.java]: I'd put a comment here saying that the file is created in the constructor rather than doStart so that the PID file is created as soon as possible.

File: jetty-server/src/main/config/modules/pid.mod [hunk 13]
```diff
@@ -0,0 +1,19 @@
+# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/
+
+[description]
+Creates and updates pid file used by jetty.sh
+
+[tags]
+start
+
+[depend]
+server
```
Comment (gregw) [inline jetty-server/src/main/config/modules/pid.mod]: I think this should be 
```suggestion
[before]
server
threadpool
jvm
```

and any other module that might started early.  We want this to be the first.

File: jetty-home/src/main/resources/etc/jetty.conf [hunk 14]
```diff
@@ -8,4 +8,4 @@
 # Each line in this file becomes an argument to start.jar
 # in addition to those found in the start.ini file
 # =======================================================
-jetty-started.xml
+--module=state,pid
```
Comment (gregw) [inline jetty-home/src/main/resources/etc/jetty.conf]: just a niggle as in my mind the order is the other way (yeah I know they will be sorted):
```suggestion
--module=pid,state
```

**Review by gregw — COMMENTED** [review]
This looks nice!   Just comment at this stage, will review for approval once not a draft.

File: jetty-home/src/main/resources/bin/jetty.sh [hunk 15]
```diff
@@ -492,16 +492,13 @@ case "$ACTION" in
...
         touch "$JETTY_PID"
         chown "$JETTY_USER" "$JETTY_PID"
-        # FIXME: Broken solution: wordsplitting, pathname expansion, arbitrary command execution, etc.
         su - "$JETTY_USER" $SU_SHELL -c "
           cd \"$JETTY_BASE\"
           echo ${RUN_ARGS[*]} start-log-file=\"$JETTY_START_LOG\" | xargs ${JAVA} > /dev/null &
-          disown \$!
-          echo \$! > \"$JETTY_PID\""
+          disown $(pgrep -P $!)"
+        pgrep
```
Comment (joakime) [inline jetty-home/src/main/resources/bin/jetty.sh]: I need to get rid of this line

Comment (gregw) [reply jetty-home/src/main/resources/bin/jetty.sh]: Note that I saw a previous comment about the disown only affecting the xargs.   However, I think that is enough as the following experiment shows:
```sh
# sleep 100 | sleep 100 &
[1] 588261

# jobs
[1]+  Running                 sleep 100 | sleep 100 &

[] disown %1

# jobs

# ps
    PID TTY          TIME CMD
 587972 pts/1    00:00:00 bash
 588260 pts/1    00:00:00 sleep
 588261 pts/1    00:00:00 sleep
 588317 pts/1    00:00:00 ps
```

Comment (joakime) [reply jetty-home/src/main/resources/bin/jetty.sh]: To show this a different way, lets use `xargs` and `nc` (netcat) in daemon mode.

``` shell
[joakim@hyperion tmp]$ echo "-4 localhost 8888" | xargs nc -d -l &
[1] 55340
[joakim@hyperion tmp]$ echo $!
55340
[joakim@hyperion tmp]$ jobs
[1]+  Running                 echo "-4 localhost 8888" | xargs nc -d -l &
[joakim@hyperion tmp]$ ps
    PID TTY          TIME CMD
  12820 pts/2    00:00:00 bash
  55340 pts/2    00:00:00 xargs
  55344 pts/2    00:00:00 nc
  55372 pts/2    00:00:00 ps
```

This shows that the `$!` is the pid for the `xargs` process, not the `nc` daemon.

If we kill the pid from `$!` (which is xargs) we see ...

``` shell
[joakim@hyperion tmp]$ ps
    PID TTY          TIME CMD
  12820 pts/2    00:00:00 bash
  55340 pts/2    00:00:00 xargs
  55344 pts/2    00:00:00 nc
  55429 pts/2    00:00:00 ps
[joakim@hyperion tmp]$ kill 55340
[joakim@hyperion tmp]$ ps
    PID TTY          TIME CMD
  12820 pts/2    00:00:00 bash
  55344 pts/2    00:00:00 nc
  55496 pts/2    00:00:00 ps
```

Only the `xargs` process was killed, `nc` is still running.

Lets try this again, but use `pgrep` to find the child process. (like what is being done in this PR)

``` shell
[joakim@hyperion tmp]$ echo "-4 localhost 8888" | xargs nc -d -l &
[1] 55632
[joakim@hyperion tmp]$ pgrep -P $!
55636
[joakim@hyperion tmp]$ jobs
[1]+  Running                 echo "-4 localhost 8888" | xargs nc -d -l &
[joakim@hyperion tmp]$ ps
    PID TTY          TIME CMD
  12820 pts/2    00:00:00 bash
  55632 pts/2    00:00:00 xargs
  55636 pts/2    00:00:00 nc
  55712 pts/2    00:00:00 ps
[joakim@hyperion tmp]$ kill 55636
xargs: nc: terminated by signal 15
[1]+  Exit 125                echo "-4 localhost 8888" | xargs nc -d -l
[joakim@hyperion tmp]$ ps
    PID TTY          TIME CMD
  12820 pts/2    00:00:00 bash
  55733 pts/2    00:00:00 ps
```

Killing `nc` (the child pid) will kill both `nc` and `xargs`.

File: jetty-home/src/main/resources/bin/jetty.sh [hunk 16]
```diff
@@ -492,16 +494,13 @@ case "$ACTION" in
...
         su - "$JETTY_USER" $SU_SHELL -c "
           cd \"$JETTY_BASE\"
           echo ${RUN_ARGS[*]} start-log-file=\"$JETTY_START_LOG\" | xargs ${JAVA} > /dev/null &
-          disown \$!
-          echo \$! > \"$JETTY_PID\""
+          disown $(pgrep -P $!)"
       else
+        # Startup if not switching users
         echo ${RUN_ARGS[*]} | xargs ${JAVA} > /dev/null &
-        disown $!
```
Comment (sbordet) [inline jetty-home/src/main/resources/bin/jetty.sh:503]: Since `disown` ha been re-introduced in the branch above, should be re-introduced here as well?

File: jetty-server/src/main/config/modules/pid.mod (hunk 13 above)
Comment (sbordet) [reply jetty-server/src/main/config/modules/pid.mod]: I'm not sure about this.
If a user makes its own custom server/threadpool module, the ordering directive will be lost as this module cannot possibly declare itself before a custom module.

If the order is not that important and we just rely on whatever order comes out after processing `jetty.conf`, then I think the section should be removed.

File: jetty-server/src/main/config/modules/state.mod [hunk 17]
```diff
@@ -0,0 +1,19 @@
+# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/
+
+[description]
+Creates and updates state file used by jetty.sh
+
+[tags]
+start
+
+[depend]
+server
```
Comment (sbordet) [inline jetty-server/src/main/config/modules/state.mod:10]: Ditto. If there is a custom server module, we don't want to pull in the standard server module.

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/FileNoticeLifeCycleListener.java [hunk 18]
```diff
@@ -22,7 +22,9 @@
 /**
  * A LifeCycle Listener that writes state changes to a file.
  * <p>This can be used with the jetty.sh script to wait for successful startup.
+ * @deprecated use {@code org.eclipse.jetty.server.StateLifeCycleListener} instead
  */
+@Deprecated
 public class FileNoticeLifeCycleListener implements LifeCycle.Listener
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/component/FileNoticeLifeCycleListener.java:28]: Can you make it extend the new `StateLifeCycleListener` rather than duplicating?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-util/src/main/java/org/eclipse/jetty/util/component/FileNoticeLifeCycleListener.java (hunk 18 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/component/FileNoticeLifeCycleListener.java:28]: Wrong way for the dependency.
The jetty-server StateLifeCycleListener cannot be referenced in jetty-util

File: jetty-server/src/main/config/modules/pid.mod (hunk 13 above)
Comment (gregw) [reply jetty-server/src/main/config/modules/pid.mod]: @sbordet any custom server module should declare that it provides "server" and then all these sorting criteria are OK.  These are not absolute module names, but general module names and multiple modules can provide the same dependency.   All our modules are ordered, so this is not a problem.

File: jetty-home/src/main/resources/bin/jetty.sh (hunk 15 above)
Comment (gregw) [reply jetty-home/src/main/resources/bin/jetty.sh]: @joakime but the disown is not about killing.   This PR is creating the pid file so that the killing is done correctly.
The disown is about breaking the link between the shell starting jetty and the jetty process itself.   I think my demo shows that disowning the $! pid is enough to break that link.

File: jetty-server/src/main/config/modules/state.mod (hunk 17 above)
Comment (gregw) [reply jetty-server/src/main/config/modules/state.mod:10]: The custom module simple needs to say that it provides "server" and then it will work fine.    We have lots of modules that either depend on "server" or are ordered against it, so any attempt to replace `server.mod` with a custom one will need to provide "server" one way or another.

Having said that, the pid module should be before server not depend on it.

File: jetty-server/src/main/java/org/eclipse/jetty/server/PidFile.java [hunk 19]
```diff
@@ -0,0 +1,67 @@
...
+    public PidFile(@Name("file") String filename)
+    {
+        pidFile = Paths.get(filename);
+        try
+        {
+            // Create the PID file as soon as possible.
+            // We don't want for doStart() as we want the PID creation to occur quickly for jetty.sh
+            long pid = ProcessHandle.current().pid();
+            Files.writeString(pidFile, Long.toString(pid), UTF_8, WRITE, TRUNCATE_EXISTING);
+            ShutdownMonitor.register(this);
```
Comment (joakime) [inline jetty-server/src/main/java/org/eclipse/jetty/server/PidFile.java]: use ShutdownThread, not ShutdownMonitor

File: jetty-server/src/main/config/modules/state.mod [hunk 20]
```diff
@@ -0,0 +1,21 @@
...
+threadpool
+jvm
+
+[xml]
+etc/jetty-state.xml
+
+[ini-template]
+## State Config
+jetty.state=${jetty.base}/jetty.state
```
Comment (sbordet) [inline jetty-server/src/main/config/modules/state.mod]: This property should be commented out.
When the `*.ini` is created, it'll be commented out and users will have to explicitly configure it.

File: jetty-util/src/main/config/modules/pid.mod [hunk 21]
```diff
@@ -0,0 +1,21 @@
...
+server
+threadpool
+jvm
+
+[xml]
+etc/jetty-pid.xml
+
+[ini-template]
+## PID Config
+jetty.pid=${jetty.base}/jetty.pid
```
Comment (sbordet) [inline jetty-util/src/main/config/modules/pid.mod]: This property should be commented out.

File: jetty-util/src/main/config/modules/pid.mod [hunk 22]
```diff
@@ -0,0 +1,21 @@
...
+[description]
+Creates pid file used by jetty.sh
+
+[tags]
+start
+
+[before]
+server
+threadpool
+jvm
```
Comment (sbordet) [inline jetty-util/src/main/config/modules/pid.mod:12]: I would just mark it:

```
[before]
state
```

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-util/src/main/config/modules/pid.mod (hunk 22 above)
Comment (gregw) [reply jetty-util/src/main/config/modules/pid.mod:12]: I think it should always be before server.  We don't want the randomness of any data structures to affect if the pid file is created before/after the server is up and running.  It should be deterministic and that is exactly why we have `before` clauses.

**Review by gregw — DISMISSED** [review]

File: jetty-util/src/main/config/etc/jetty-pid.xml [hunk 23]
```diff
@@ -0,0 +1,6 @@
+<?xml version="1.0"?>
+<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
+
+<Configure id="Pid" class="org.eclipse.jetty.util.PidFile">
+  <Arg name="file"><Property name="jetty.pid" default="./jetty.pid"/></Arg>
```
Comment (lorban) [inline jetty-util/src/main/config/etc/jetty-pid.xml]: I would not prefix the default filename with `./`. Think Windows: the `./` prefix should work but isn't natural. Plus it relates to the CWD exactly like when that prefix is omitted.

File: jetty-server/src/main/config/etc/jetty-state.xml [hunk 24]
```diff
@@ -0,0 +1,12 @@
+<?xml version="1.0"?>
+<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
+
+<Configure id="Server" class="org.eclipse.jetty.server.Server">
+  <Call name="addEventListener">
+    <Arg>
+      <New class="org.eclipse.jetty.server.StateLifeCycleListener">
+        <Arg><Property name="jetty.state" default="./jetty.state"/></Arg>
```
Comment (lorban) [inline jetty-server/src/main/config/etc/jetty-state.xml]: No `./` prefix in the default filename, please.

File: jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java [hunk 25]
```diff
@@ -0,0 +1,69 @@
...
+    public PidFile(@Name("file") String filename)
+    {
+        pidFile = Paths.get(filename);
+        try
+        {
+            // Create the PID file as soon as possible.
+            // We don't want for doStart() as we want the PID creation to occur quickly for jetty.sh
+            long pid = ProcessHandle.current().pid();
+            Files.writeString(pidFile, Long.toString(pid), UTF_8, CREATE, WRITE, TRUNCATE_EXISTING);
+            ShutdownThread.register(this);
```
Comment (lorban) [inline jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: You're registering a new `LifeCycle` instance in the shutdown thread every time an instance of this class is created without ever trying to clean that up or document it in any way.

This means the following valid-looking loop would eventually OOME:

```java
while (true)
{
 Server server = new Server(8080);
 server.addManaged(new PidFile()); // this writes the PID file
 server.start();
 server.stop(); // this deletes the PID file
}
```

At the very least, we should document that this class must not be used with embedded servers.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java (hunk 25 above)
Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: Yeah, but that's not what PidFile does, it registers itself with the ShutdownThread, it's not a Server managed lifecycle.

Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: Can we have a static to make sure only 1 is every installed

Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: I don't understand these comments.
I don't see why we need this complexity.
Few other components have this new requirement.
There's also nothing special about this class that prevents an embedded server from using it (dropwizard, spark, spring-boot, runner should all be able to use it).

The PidFile is a ShutdownThread component, let me at least add javadoc to that point.  Hopefully that will address this requested change.

Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: @joakime we have few other components that register JVM hooks that are not deleted.
The problem with my suggestion is that a simple static boolean would not handle the plausible (if rare) case where two `PidFile` instances are created for different file names.

I think it is really rare that any stop/start cycle will create enough of these objects to ever be a problem... however, the complexity to have a static concurrent set of filenames for which a shutdown hook has already been registered is not that much.   If a filename is already in that static set, then simply do not register the shutdownThread.      Then you have covered the 0.0000001% case as well :)

File: jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java [hunk 26]
```diff
@@ -0,0 +1,78 @@
...
+    {
+        ShutdownThread.deregister(this);
+        try
+        {
+            Files.deleteIfExists(pidFile);
+        }
+        catch (Throwable t)
+        {
+            LOG.warn("Unable to remove pidFile: {}", pidFile, t);
+        }
```
Comment (gregw) [inline jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: @joakime this doesn't work. If we stop a server before exiting the JVM, we still want the PID file deleted.

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java (hunk 26 above)
Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: ... or the other approach is to never delete the pid file.   That way we are safe for any lockups between the deletion and the actual file exit.     Code that deals with PID files should be robust for processes that have already exited....  but what is the re-use policy of PIDs?

Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: > @joakime this doesn't work. If we stop a server before exiting the JVM, we still want the PID file deleted.

That would be invalid, as the process that PID is pointing to still exists in that scenario.
The PID refers to the system process, not the Server.
Once the system process (the JVM) exits (or is exiting), then we should attempt to remove the PID.

If the PID exists when we start again, that would not impact service `start`, but it would impact service `status` style calls.
The following is how systemd `status` calls handle the PID file from a `status` point of view.

Exit Code | Meaning
---- | ----
0 | PID exists, system process exists, status reported from service itself
1 | PID exists, system process does not exist (no status from service) service is reported as "not running"
3 | PID does not exist, service is reported as "not running"
4 | PID exists, system process exists, status not able to be determined from service (hung process, no reply, etc), reported as "unable to determine status", with PID displayed in output.

_Exit code 2 is not used in systemd status calls AFAICT_

Comment (gregw) [reply jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: @Joakim we want the file deleted when the jvm exits regardless of the server is stopped or started. Removing the shutdown hook is wrong. Just don't register more than 1 per filename.

Comment (joakim) [reply jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: @gregw Just a heads up, you're mentioning the wrong Joakim :) It has happened a few times in this repo.

My namesake has an "e" at the end.

Comment (joakime) [reply jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: > @joakim we want the file deleted when the jvm exits regardless of the server is stopped or started. Removing the shutdown hook is wrong. Just don't register more than 1 per filename.

I don't understand.

This is never added to a Server, or any other Jetty Container.
This only exists as a `LifeCycle` to satisfy the Jetty `org.eclipse.jetty.util.thread.ShutdownThread` mechanism.

To recap.

The `org.eclipse.jetty.util.thread.ShutdownThread` ...
1. Is a singleton
2. Is _not_ a Jetty `org.eclipse.jetty.util.component.LifeCycle` or `org.eclipse.jetty.util.component.Container` class.
3. Has no LifeCycle of its own (start/stop).
4. Is registered as a JVM Runtime Shutdown Thread - `Runtime.getRuntime().addShutdownHook(ShutdownThread)` (once and only once)
5. Collects a `List<LifeCycle>` of registered LifeCycle's to call when the JVM shutdown occurs. (because of a call to `ShutdownThread.register(LifeCycle)`)
6. When JVM shutdown occurs the `ShutdownThread.run()` executes.
7. All registered LifeCycle's (on the `ShutdownThread`) have their `LifeCycle.stop()` method called (and optionally a `Destroyable.destroy()`) methods.

I feel the fact that this is a `LifeCycle` is confusing things for you.
The `PidFile` exists only for `ShutdownThread` use in this current HEAD (it is never started, or managed, or added to another lifecycle container).
The `PidFile.doStop()` method is what is executed during JVM shutdown.

Options to get unstuck from this apparent confusion over `LifeCycle` and `ShutdownThread`.

### (A) Remove `LifeCycle` and `ShutdownThread` use entirely in `PidFile`.

Just make `PidFile` a `Runnable`, and have it register itself as a `Runtime.getRuntime().addShutdownHook(PidFile)`.

### (B) Move `ShutdownThread.register()` to `jetty-pid.xml`

`PidFile` remains a `LifeCycle` class, but nothing in Jetty code (or an XML in jetty-home) adds it to any Jetty `org.eclipse.jetty.util.component.Container`.
Leave that strange use case (Using PidFile as a normal LifeCycle in another Container) for embedded jetty users.
Have `jetty-pid.xml` create the `PidFile` instance and register it with the `ShutdownThread`.
Never unregister, as it doesn't make sense for this use case.

Comment (sbordet) [reply jetty-util/src/main/java/org/eclipse/jetty/util/PidFile.java]: I like `A` better because seems way simpler.

**Review by sbordet — APPROVED** [review]

**Review by gregw — APPROVED** [review]
LGTM

**Review by lorban — APPROVED** [review]
