### PR TITLE
Issue #4919 - WebSocket container graceful stop

### LINKED ISSUE #4919: websocket container stop ordering
**Jetty version**
10.0.x

**Description**
In tests which do not explicitly close the all open WebSocket sessions, we frequently get the stack trace error message from `onError`.

```
2020-05-28 16:44:19.365:WARN :oejwjtc.DecoderListTest$DecoderListEndpoint:qtp396883763-17: Unhandled Error: org.eclipse.jetty.websocket.javax.tests.coders.DecoderListTest$DecoderListEndpoint@4947d28
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.websocket.core.internal.WebSocketSessionState.onEof(WebSocketSessionState.java:172)
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:323)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onClose(WebSocketConnection.java:169)
	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:334)
	at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:1060)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:823)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:945)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I think this is because the WebSocket containers are not shutting down in the correct order when `doStop` is called. The order we want is:
1. Stop accepting new websocket connections.
2. Stop the `SessionTracker` which will close any existing connections.
3. Shut down everything else.

We should review the stop order for the client and server containers on both the Javax and Jetty API implementations. The server containers might need to implement the `Graceful` interface to do this properly.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Closes #4919**

Make sure all active websocket connections are closed before the connections are hard closed.

`Server.doStop()` now initiates a graceful shutdown but only waits for the `CompletableFuture` if the `stopTimeout` is set.

### CODE REVIEW

File: jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java [hunk 1]
```diff
@@ -260,4 +262,19 @@ protected void doStart() throws Exception
             deferredEndpointConfigs.clear();
         }
     }
+
+    @Override
+    public CompletableFuture<Void> shutdown()
+    {
+        LifeCycle.stop(sessionTracker);
```
Comment (lachlan-roberts) [inline jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java]: Not sure how we should stop accepting new incoming connections before this.

Comment (gregw) [reply jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java]: Can stopping the sessionTracker take time? Can it block? Can it call user code?   If any of the above, then this is precisely what we don't want to do in a shutdown thread.   Why can't this be done in doStop?  at the very least a comment is needed, but I think a different approach is required.

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java]: It won't block in jetty code but it will call the user code with `onClosed`. We already stop the `SessionTracker` when the server is stopped (in 9.4 as well) so if this is an issue it already exists in the codebase before this change.

The problem here is that `Server.doStop()` shuts down all the connectors before calling `super.doStop()` and this closes the existing connections. So we can't react to the stop and close the WebSocket sessions as all the existing connections have already been closed.

File: jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java [hunk 2]
```diff
@@ -301,4 +303,19 @@ protected void doStart() throws Exception
...
+        CompletableFuture<Void> shutdown = new CompletableFuture<>();
+        shutdown.complete(null);
+        return shutdown;
+    }
```
Comment (gregw) [inline jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java]: Try something like the below.  This lets the caller wait for this to complete or not, as it likes.

```suggestion
    {
        CompletableFuture<Void> shutdown = new CompletableFuture<>();
        new Thread(()->
        {
            try
            {
                LifeCycle.stop(sessionTracker);
            }
            catch(Exception e)
            {
                LOG.warn(e);
            }
            finally
            {
                shutdown.complete(null);
            }
        }.start();
        return shutdown;
    }
```

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java (hunk 2 above)
Comment (joakime) [reply jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java]: Shouldn't the exception be caught and cause the `shutdown` `CompletableFuture` to fail with an exception?

File: jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java [hunk 3]
```diff
@@ -307,9 +307,22 @@ protected void doStart() throws Exception
...
+            }
+            catch (Throwable t)
+            {
+                LOG.warn("Error while stopping SessionTracker", t);
+            }
+            finally
+            {
+                shutdown.complete(null);
+            }
+        }).start();
```
Comment (gregw) [inline jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java]: This thread should be a daemon thread so it doesn't stop the JVM exiting.

I'm also wondering if we should implement `cancel` on the `CompletableFuture` and interrupt the thread if it is called?

We might then need some support in `Graceful.shutdown` or `Server.doStop` to actually do that cancel.... but perhaps that is feature creep for this PR.   So let's just make this thread look OK

File: jetty-websocket/websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/JettyWebSocketServerContainer.java [hunk 4]
```diff
@@ -267,9 +267,22 @@ public void setAutoFragment(boolean autoFragment)
     @Override
     public CompletableFuture<Void> shutdown()
     {
-        LifeCycle.stop(sessionTracker);
         CompletableFuture<Void> shutdown = new CompletableFuture<>();
-        shutdown.complete(null);
+        new Thread(() ->
```
Comment (gregw) [inline jetty-websocket/websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/JettyWebSocketServerContainer.java]: Same comments as above.... looking like we need a utility class to do this threadful stopping.

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java]: I think we might have a bigger problem here if `SessionTracker.doStop()` needs to be called by a different thread. We also use the `SessionTracker` on the client which would have the same issue. So we shouldn't store the `SessionTracker` as a bean anymore and its lifecycle needs to be manually managed.

**Comment by lachlan-roberts** [comment]
@gregw implemented the changes.

There is a problem that there is no API for a Javax `WebSocketContainer` stop timeout, so it can't be stopped gracefully. I could try putting a short set length stop timeout to give some minimal effort to close gracefully, but not sure how that would interact with the `ServerContainer` shutdown.

File: jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java (hunk 3 above)
Comment (gregw) [reply jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java]: Ah yes, `stop()` is synchronized.
I think the SessionTracker should remain as a managed bean so it is stopped normally if the container is stopped, but that shutdown should first remove the tracker as a bean and then stop it in another thread.

Comment (lachlan-roberts) [reply jetty-websocket/websocket-javax-server/src/main/java/org/eclipse/jetty/websocket/javax/server/internal/JavaxWebSocketServerContainer.java]: Wasn't the whole point of this so that we never called the `SessionTracker` stop if the container is stopped as it could block in an `onClosed`? So why would we still have the `SessionTracker` as a managed bean on the container.

File: jetty-websocket/websocket-util/src/main/java/org/eclipse/jetty/websocket/util/ShutdownUtil.java [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+public class ShutdownUtil
+{
+    private static final Logger LOG = LoggerFactory.getLogger(ShutdownUtil.class);
+
+    /**
+     * Shutdown a {@link LifeCycle} in a new daemon thread and be notified on the result in a {@link CompletableFuture}.
+     * @param lifeCycle the LifeCycle to stop.
+     * @return the CompletableFuture to be notified when the stop either completes or fails.
+     */
+    public static CompletableFuture<Void> shutdown(LifeCycle lifeCycle)
```
Comment (gregw) [inline jetty-websocket/websocket-util/src/main/java/org/eclipse/jetty/websocket/util/ShutdownUtil.java]:
```suggestion
    public static CompletableFuture<Void> stop(LifeCycle lifeCycle)
```

File: jetty-websocket/websocket-util/src/main/java/org/eclipse/jetty/websocket/util/ShutdownUtil.java [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+        {
+            @Override
+            public boolean cancel(boolean mayInterruptIfRunning)
+            {
+                boolean canceled = super.cancel(mayInterruptIfRunning);
+                if (canceled && mayInterruptIfRunning)
+                {
+                    Thread thread = stopThreadReference.get();
+                    if (thread != null)
+                        thread.interrupt();
```
Comment (gregw) [inline jetty-websocket/websocket-util/src/main/java/org/eclipse/jetty/websocket/util/ShutdownUtil.java]: This is good.
But now you should probably modify the loop in SessionTracker.doStop() to check if interrupted and if so it can break the iteration.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java [hunk 7]
```diff
@@ -68,6 +71,7 @@
     private final Configuration.ConfigurationCustomizer configurationCustomizer = new Configuration.ConfigurationCustomizer();
     private final WebSocketComponents components = new WebSocketComponents();
     private boolean stopAtShutdown = false;
+    private long _stopTimeout = 200;
```
Comment (gregw) [inline jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java]: Hmmmm I don't really like such hard coded default timeouts.... but at least there is a setter.
What happens if you make the default wait forever?

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java [hunk 8]
```diff
@@ -388,11 +391,48 @@ public synchronized void setStopAtShutdown(boolean stop)
         stopAtShutdown = stop;
     }
 
+    public void setStopTimeout(long stopTimeout)
```
Comment (gregw) [inline jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java:398]: Need javadoc: what are the units? Can it be disabled? Can it be set to wait forever?

**Review by gregw — APPROVED** [review]
I'm approving this other than a javadoc and naming niggle and a suggestion to make cancel work a bit better.

I think this PR should be merged, but then we should start another one looking at other improvements in graceful (eg like actually calling cancel if the stopTimeout expires).

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java (hunk 7 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java]: I have changed this default to `Long.MAX_VALUE`, so it will always do the proper close of all the sessions, which is fine assuming it doesn't block in user code in `onClosed`.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java (hunk 8 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java:398]: It works exactly the same as `Server` stopTimemout, if it is less or equal to 0 we don't attempt a graceful stop, if it is greater than 0 we use the value.

**Comment by lachlan-roberts** [comment]
@gregw I didn't like the state of this PR so I've done some more changes and now I think it is more in line with the way `Graceful` should be used. 

Now the `SessionTracker` always remains a bean on the websocket container and the `SessionTracker` is the one to implement `Graceful` not the container itself. The `SessionTracker` is then shutdown by `Graceful.shutdown(Container)` which will find the `SessionTracker` in the Container hierarchy.

**Review by gregw — APPROVED** [review]

**Comment by chylek-qr** [comment]
EDIT: Moved to #10918

**Comment by joakime** [comment]
@chylek-qr please open a new issue, a comment on a 3 year old PR is unlikely to be tracked.
