### PR TITLE
Issue #11260 - Allow `QuickStartConfiguration` to be used in mixed contexts environment where some do not have a WEB-INF/quickstart-web.xml

### LINKED ISSUE #11260: QuickStartConfiguration cannot be mixed with contexts that do not have a `WEB-INF/quickstart-web.xml`
**Jetty version(s)**
10, 11, 12

**Jetty Environment**
Any

**Java version/vendor** `(use: java -version)`
Any

**OS type/version**
Any

**Description**
If `QuickStartConfiguration` is enabled, and you have a mix of contexts, some with `WEB-INF/quickstart-web.xml` and some without you get an `IllegalStateException` preventing deployment of those contexts that do not have or need a quickstart.

### PR DESCRIPTION
**Pull request by joakime**
+ Converted IllegalStateException to just a warn level logging statement.
+ Improved tracking of _is quickstart enabled_ within WebAppContext itself, not the QuickStartConfiguration
+ Added unit test of an exploded webapp directory that has no WEB-INF or web.xml

### CODE REVIEW

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 1]
```diff
@@ -86,6 +86,14 @@ public QuickStartConfiguration()
         addDependents(WebXmlConfiguration.class);
     }
 
+    private boolean isQuickStartEnabled(WebAppContext context)
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: I don't see the usefulness of the context attribute? Nor why if it's not set, this method returns `true`?

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 2]
```diff
@@ -139,7 +148,9 @@ public void preConfigure(WebAppContext context) throws Exception
                 if (quickStartWebXml.exists())
                     quickStart(context);
                 else
-                    throw new IllegalStateException("No " + quickStartWebXml);
+                {
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:153]: I don't think it's appropriate to skip the deployment if `QUICKSTART` mode is selected.  In a mixed-context environment, you can easily set the context attribute to `AUTO` for those contexts for which quickstart isn't appropriate. I think it's a real error if you've selected `QUICKSTART` mode, but yet no `quickstart-web.xml` file exists.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 3]
```diff
@@ -160,37 +171,42 @@ protected void configure(QuickStartGeneratorConfiguration generator, WebAppConte
     @Override
     public void configure(WebAppContext context) throws Exception
     {
-        if (!_quickStart)
+        if (!isQuickStartEnabled(context))
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: I think this change will break the other modes.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 4]
```diff
@@ -160,37 +171,42 @@ protected void configure(QuickStartGeneratorConfiguration generator, WebAppConte
...
+            return;
         }
-        else
-        {
-            //add the processor to handle normal web.xml content
-            context.getMetaData().addDescriptorProcessor(new StandardDescriptorProcessor());
 
-            //add a processor to handle extended web.xml format
-            context.getMetaData().addDescriptorProcessor(new QuickStartDescriptorProcessor());
+        //add the processor to handle normal web.xml content
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: I'd leave out these changes and the ones following.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 5]
```diff
@@ -160,37 +171,42 @@ protected void configure(QuickStartGeneratorConfiguration generator, WebAppConte
...
+        context.addBean(starter, true);
+
+        LOG.debug("configured {}", this);
     }
 
     @Override
     public void postConfigure(WebAppContext context) throws Exception
     {
-        super.postConfigure(context);
+        if (!isQuickStartEnabled(context))
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: I don't see the reason for the context attribute?

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 6]
```diff
@@ -229,7 +245,10 @@ public Resource getQuickStartWebXml(WebAppContext context) throws Exception
         if (webInf == null || !webInf.exists())
         {
             File tmp = new File(context.getBaseResource().getFile(), "WEB-INF");
-            tmp.mkdirs();
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:232]: ok

**Review by janbartel — CHANGES_REQUESTED** [review]
I think we already have a way to ensure non-quickstartable contexts can be accommodated, even if quickstart is enabled overall on the server by using the mode `AUTO`.

I thought the original bug report had something to do with lack of a `WEB-INF` directory causing a problem?

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 2 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:153]: This would require every context to be supplemented by an XML deployable.
Why isn't the default set to AUTO?
Let me try that as default and see what happens in the test case.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 1 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: The `QuickStartConfiguration` is shared across contexts.
The field `_quickStart` is the wrong way to track this behavior.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 4 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: calling `super.configure(context);` is a no-op.
The rest of the changes in this location are simplifying the if/else logic, that's all.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 3 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: The other modes were fine in testing.
I reworked this without this new attribute, just relying on the information from the existing attribute for mode and the existence or not of the quickstart-web.xml based on that mode.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 2 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:153]: AUTO is the default if unset.
But the Configuration field approach was wrong, as that is keeping track of the Mode in two places.
If the mode is specified in start.d/quickstart.ini then it's automatically set on the context.attributes.
I reworked this to not have the Configuration field too, as the existing context.attribute approach is correct.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 1 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: Also removed the `_mode` field as it's duplicates information that's already present in the context but in the wrong way.

**Comment by joakime** [comment]
@janbartel there's something amiss with AUTO.

The documentation says ...

https://github.com/jetty/jetty.project/blob/8492d1c78f122bb30cce20aecfa07e7283facd47/jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java#L72-L77

But `AUTO` does not generate a `WEB-INF/quickstart-web.xml` if it doesn't exist.
This is true of every released version of Jetty 10.0.x I've tested.

The only behavior difference with `AUTO` and `QUICKSTART` is what `QuickStartConfiguration` does if the `WEB-INF/quickstart-web.xml` isn't present.
* `AUTO` lets the the webapp start.
* `QUICKSTART` will fail startup of context with an ISE.

There's no auto generation of `WEB-INF/quickstart-web.xml` done with `AUTO`.

I see 2 things we should probably fix with `QuickStartConfiguration` in different PRs.

1. Make sure `AUTO` actually generates a `WEB-INF/quickstart-web.xml` or update the documentation.
2. Make sure that we don't use deprecated classes in `QuickStartConfiguration`, but use the non-deprecated versions instead.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 7]
```diff
@@ -72,57 +73,70 @@ public static void configureMode(Server server, String mode)
...
-        if (war == null || war.length() <= 0 || !context.getBaseResource().isDirectory())
-            throw new IllegalStateException("Bad Quickstart location");
+        if (StringUtil.isBlank(war) || !context.getBaseResource().isDirectory())
+            throw new IllegalStateException("Invalid Quickstart location");
 
-        //look for quickstart-web.xml in WEB-INF of webapp
+        // look for quickstart-web.xml in WEB-INF of webapp
         Resource quickStartWebXml = getQuickStartWebXml(context);
-        LOG.debug("quickStartWebXml={} exists={}", quickStartWebXml, quickStartWebXml.exists());
+        if (quickStartWebXml == null)
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: This would be a behaviour change. Better to leave the logic as is. Fix up the javadoc for `AUTO` to match the actual documentation here: https://eclipse.dev/jetty/documentation/jetty-11/operations-guide/index.html#og-quickstart

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 8]
```diff
@@ -72,57 +73,70 @@ public static void configureMode(Server server, String mode)
...
+                quickStartWebXml.exists(),
+                context);
+
+        switch (mode)
         {
             case GENERATE:
             {
                 if (quickStartWebXml.exists())
-                    LOG.info("Regenerating {}", quickStartWebXml);
+                    LOG.info("Regenerating {} for {}", quickStartWebXml, context);
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:121]: Probably don't need the context here, as the path to the `quickstartWebXml` will be relative to the context.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 9]
```diff
@@ -72,57 +73,70 @@ public static void configureMode(Server server, String mode)
...
                 else
-                    LOG.info("Generating {}", quickStartWebXml);
-                
-                super.preConfigure(context);
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:117]: All configs call `super.preConfigure()`, so safest to leave it in.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 10]
```diff
@@ -72,57 +73,70 @@ public static void configureMode(Server server, String mode)
...
+
+                // generate the quickstart file then abort
                 QuickStartGeneratorConfiguration generator = new QuickStartGeneratorConfiguration(true);
                 configure(generator, context);
                 context.addConfiguration(generator);
                 break;
             }
             case AUTO:
             {
+                // TODO: why doesn't AUTO generate a WEB-INF/quickstart-web.xml if not present?
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: Because the javadoc is wrong :)

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 11]
```diff
@@ -131,19 +145,23 @@ public void preConfigure(WebAppContext context) throws Exception
                 {
                     if (LOG.isDebugEnabled())
                         LOG.debug("No quickstart xml file, starting webapp {} normally", context);
-                    super.preConfigure(context);
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:134]: All derived `Configuration` classes call their `super()` methods, so leave it in.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 12]
```diff
@@ -131,19 +145,23 @@ public void preConfigure(WebAppContext context) throws Exception
...
             case QUICKSTART:
+            {
                 if (quickStartWebXml.exists())
+                {
                     quickStart(context);
+                }
                 else
-                    throw new IllegalStateException("No " + quickStartWebXml);
+                {
+                    throw new IllegalStateException("No WEB-INF/quickstart-web.xml file for " + context);
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:154]: Again, probably don't need the the context, as the `quickstart-web.xml` should be unique for each context.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 13]
```diff
@@ -160,37 +178,34 @@ protected void configure(QuickStartGeneratorConfiguration generator, WebAppConte
...
+        context.setAttribute(AnnotationConfiguration.CONTAINER_INITIALIZER_STARTER, starter);
+        context.addBean(starter, true);
+
+        LOG.debug("configured {}", this);
     }
 
     @Override
     public void postConfigure(WebAppContext context) throws Exception
     {
-        super.postConfigure(context);
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: All `Configuration` classes call their `super()` methods, so leave it in.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 14]
```diff
@@ -228,9 +242,27 @@ public Resource getQuickStartWebXml(WebAppContext context) throws Exception
         Resource webInf = context.getWebInf();
         if (webInf == null || !webInf.exists())
         {
-            File tmp = new File(context.getBaseResource().getFile(), "WEB-INF");
-            tmp.mkdirs();
-            webInf = context.getWebInf();
+            switch (getModeForContext(context))
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:246]: There's only 1 mode where a `quickstart-web.xml` will be generated, and that's `GENERATE`.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 15]
```diff
@@ -160,37 +178,34 @@ protected void configure(QuickStartGeneratorConfiguration generator, WebAppConte
     @Override
     public void configure(WebAppContext context) throws Exception
     {
-        if (!_quickStart)
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:163]: I really don't want to change the logic here.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 16]
```diff
@@ -72,57 +73,70 @@ public static void configureMode(Server server, String mode)
...
+                LOG.debug("No quickStartWebXml present on {}", context);
+            return;
+        }
 
-        //Get the mode
-        Mode mode = (Mode)context.getAttribute(MODE);
-        if (mode != null)
-            _mode = mode;
-        
-        _quickStart = false;
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:106]: Let's just add a boolean context attribute that captures if  the context will be quickstarted to replace the `_quickstart` field.

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 15 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:163]: This logic (the `_quickStart` field) breaks when there are more than 1 WebAppProvider or someone that is using parallel deployment.
The use of fields in the Configuration to track behavior between preConfigure / configure / postConfigure is a bug that needs to be fixed.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 13 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: That's an incorrect assumption.
And the super calls are no-ops.

super.preConfigure(context)

- AnnotationConfiguration (overridden only)
- EnvConfiguration (overridden only)
- PlusConfiguration (overridden only)
- FragmentConfiguration (overridden only)
- MetaInfConfiguration (overridden only)
- WebInfConfiguration (overridden only)
- WebXmlConfiguration (overridden only)
- QuickStartConfiguration (overridden + calls super)
- OSGIMetaInfConfiguration (overridden + calls super)
- QuickStartGeneratorConfiguration (overridden + calls super)

super.configure(context)

- AnnotationConfiguration (overridden only)
- EnvConfiguration (overridden only)
- PlusConfiguration (overridden only)
- QuickStartGeneratorConfiguration (overridden only)
- JettyWebXmlConfiguration (overridden only)
- MetaInfConfiguration (overridden only)
- WebXmlConfiguration (overridden only)
- QuickStartConfiguration (overridden + calls super)
- AntWebInfConfiguration (overridden + calls super)
- MavenWebInfConfiguration (overridden + calls super)
- OSGIMetaInfConfiguration (overridden + calls super)

super.postConfigure(context)

- AnnotationConfiguration (overridden only)
- PlusConfiguration (overridden only)
- FragmentConfiguration (overridden only)
- MetaInfConfiguration (overridden only)
- OSGIMetaInfConfiguration (overridden + calls super)
- AnnotationConfiguration (overridden + calls super)
- QuickStartConfiguration (overridden + calls super)

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 14 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:246]: Fixed

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 16 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:106]: We also need a new Mode.

Something like `DISABLED`.

Example scenario: user has a webapp, that has a `WEB-INF/quickstart-web.xml`.
But they do not want to use QuickStart for that specific webapp.
With this new Mode they can set the context attribute on that specific webapp to `DISABLED` and get a normal startup.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 12 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:154]: Context is added for those users that use more than one WebAppProvider and those use parallel deployment techniques (a feature we've supported for a while now)

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 11 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:134]: Incorrect assumption.
See https://github.com/jetty/jetty.project/pull/11261#discussion_r1452613152

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 10 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java]: Removed.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 9 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:117]: Incorrect assumption.
See https://github.com/jetty/jetty.project/pull/11261#discussion_r1452613152

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 8 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:121]: This is for users with more than 1 WebAppProvider and also users that perform parallel deployments.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 15 above)
Comment (janbartel) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:163]: Agreed to remove `_quickstart`, however that can be done without all the other logic changes.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 16 above)
Comment (janbartel) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:106]: @joakime a new `DISABLED` mode could be added for jetty-12 in another PR, but not in this one for jetty-10, which is not having new features added to it.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java [hunk 17]
```diff
@@ -130,20 +138,24 @@ public void preConfigure(WebAppContext context) throws Exception
                 else
                 {
                     if (LOG.isDebugEnabled())
-                        LOG.debug("No quickstart xml file, starting webapp {} normally", context);
-                    super.preConfigure(context);
```
Comment (janbartel) [inline jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:134]: Leave `super` call in here, removing it hasn't got anything to do with the issue and I think minimal changes are best.

File: tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/PreconfigureSpecWar.java [hunk 18]
```diff
@@ -52,10 +51,12 @@ public static void main(String[] args) throws Exception
 
         LOG.info("Preconfigured in {}ms", NanoTime.millisSince(__start));
 
+        /*
```
Comment (janbartel) [inline tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/PreconfigureSpecWar.java:54]: Why is this commented out?

**Review by janbartel — CHANGES_REQUESTED** [review]

File: tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/PreconfigureSpecWar.java (hunk 18 above)
Comment (joakime) [reply tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/PreconfigureSpecWar.java:54]: It just output the quickstart-web.xml to System.out, a useful thing when debugging, but noisy otherwise (way worse than seeing a stacktrace)

If you need to see it during debugging, then just comment it out.

File: jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java (hunk 17 above)
Comment (joakime) [reply jetty-quickstart/src/main/java/org/eclipse/jetty/quickstart/QuickStartConfiguration.java:134]: Done.

**Review by janbartel — APPROVED** [review]
