### PR TITLE
Make succeeded and failed in ICB final + introduce onSuccess

### LINKED ISSUE #11932: Review HttpSender.ContentSender (and other ICB) to remove overridden succeeded method
**Jetty version(s)**
12
**Jetty Environment**
all
**Java version/vendor** `(use: java -version)`
all
**OS type/version**
all

**Description**

Currently the `HttpSender.ContentSender` class is an ICB and it overrides the `succeeded()` method.    This method is not serialized with other ICB action, nor is there a memory barrier.
So for example, code written in onAborted (which is serialized) might be acting of a field that is changed by another thread calling `succeeded()`.

Generally the `ICB.succeeded()` and `ICB.failed(Throwable)`  methods should be considered final and overwritten only in exceptional circumstances.

### PR DESCRIPTION
**Pull request by lorban**
Closes #11932

### CODE REVIEW

**Comment by lorban** [comment]
@gregw I went over all our ICB implementations that override `succeeded` and `failed`, and I came up with two conclusions:

 - Overriding `succeeded` is often used to release a successfully written buffer before moving on to the next one. But that can easily be replaced by a new `onSuccess` protected method that can do the same job but in a safe way.
 - Overriding `failed` is sometimes done to release a buffer, but that can be done in `onCompleteFailure` instead.
 - There are two places where `succeeded` and `failed` are overridden for different reasons, and IMHO those are pure evil. See `CustomTransportTest` and H3's `MessageFlusher` to see what I mean: the 1st one calls `iterate()` from `succeeded` and does not call super, the 2nd one calls `super.succeeded()` from `failed()`.

I'm now looking for a way to modify `MessageFlusher` so that it doesn't need to act this weird, but I'm building a firm belief that overriding `succeeded` and `failed` is never, ever a good idea.

**Comment by lorban** [comment]
I refactored `MessageFlusher` and make ICB's `succeeded` and `failed` methods final.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java [hunk 1]
```diff
@@ -167,6 +167,13 @@ protected IteratingCallback(boolean needReset)
      */
     protected abstract Action process() throws Throwable;
 
+    /**
+     * Invoked when one task has completed successfully.
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java]: More javadoc required about how this is serialized etc.
Specifically that it will not be called if the ICB is aborted and then succeeded.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java [hunk 2]
```diff
@@ -342,7 +356,7 @@ else if (notifyCompleteFailure != null)
      * to call {@code super.succeeded()}.
      */
     @Override
-    public void succeeded()
+    public final void succeeded()
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java]: We can't make these `final` in 12.0.x.   But I do think this PR should be developed with them final so we can potentially make them final in 12.1.x.  We can remove the actual "final" just before merge.

Can you modify the javadoc to say that these methods should be treated as essentially final and only overridden in extraordinary circumstances.  I know nobody reads javadoc, but at least we can point to that if/when we ultimately do make them final.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java:1]: I'm somewhat concerned by the current implementation of ICB and thought we made a lot of good improvements in #11876 to the implementation.

Can you look at the additional tests done in #11876 about testing abort in all states and do something similar in this PR.    If the current implementation passes, then good... else we should consider taking the new implementation (but with tuned down semantics).

File: jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicConnection.java [hunk 3]
```diff
@@ -372,17 +372,9 @@ protected Action process()
         }
 
         @Override
-        public void succeeded()
+        protected void onSuccess()
```
Comment (gregw) [inline jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicConnection.java:368]: I'm wondering why we protect the `entry` field with a lock in `process` but not here.   Both methods are called from the same serialized processing, so both should have same locking and memory barriers.

Comment (gregw) [reply jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicConnection.java:368]: Ah is it that the lock is protecting the queue and not the entry field?  If so, some comments would be good.... or just use a concurrent queue.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java [hunk 4]
```diff
@@ -294,7 +294,7 @@ protected Action process() throws Throwable
     }
 
     @Override
-    public void succeeded()
+    protected void onSuccess()
```
Comment (gregw) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java:297]: I think this change alone might fix a lot of strangeness we get with failures!

**Review by gregw — CHANGES_REQUESTED** [review]
Nice big step in the right direction!  But a few things....

File: jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicConnection.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/QuicConnection.java:368]: Good catch, I'm going to replace the queue with a thread-safe impl.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java]: Ok, I improved javadoc.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java]: Agreed, once we're happy with this PR, I'll revert these `final` markers as the last step before merging.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/internal/HTTP2Flusher.java:297]: :+1:

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java:1]: I'm not sure it's worth it, I even think I should rebase this PR on top of 12.1.x as we're heading into the direction of removing buffers from the pool for 12.0 and not implementing abortable callbacks.

So all changes to `IteratingCallback` should retarget 12.1.x and 12.0.x should be left as-is IMHO. This would also avoid making this an "omnibus" PR, as we've done a bit too much recently.

**Comment by lorban** [comment]
@olamy do you have an idea why the integration tests are failing with a compilation error despite the fact that the code doesn't match what's reported?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java:1]: If this PR and the one on the remove buffers fix the issues, then yes, let's leave further ICB refinement and testing to 12.1

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/IteratingCallback.java]: Remove those now and I'll give the green tick

**Comment by lorban** [comment]
@gregw I reverted the `final` modifiers in ICB, and I also fixed a small bug in the delayed `onSuccess` call and added a test.

I think this can now be merged.

**Comment by lorban** [comment]
@olamy thanks for your help fixing the build!
