### PR TITLE
Issue #11873 - Server resources are not found if the server is subclassed in a different package

### LINKED ISSUE #11873: Server resources are not found if the server is subclassed in a different package
**Jetty version(s)**
12.0.x

**Description**
`Server.getDefaultStyleSheet()` and `Server.getDefaultFavicon()` do not work if the server has been sub classed in a different package.

```
java.lang.IllegalStateException: Missing server resource: favicon.ico
	at org.eclipse.jetty.server@12.0.10-SNAPSHOT/org.eclipse.jetty.server.Server.newResource(Server.java:819)
	at org.eclipse.jetty.server@12.0.10-SNAPSHOT/org.eclipse.jetty.server.Server.getDefaultFavicon(Server.java:806)
```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #11873

### CODE REVIEW

**Review by sbordet — APPROVED** [review]

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/subpackage/ServerDefaultResourcesTest.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+import static org.junit.jupiter.api.Assertions.assertNotNull;
+
+public class ServerDefaultResourcesTest
+{
+    public static Stream<Arguments> arguments()
+    {
+        return Stream.of(
+            new Server(),
+            new Server(){}
+        ).map(Arguments::of);
```
Comment (joakime) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/subpackage/ServerDefaultResourcesTest.java:32]: I don't think this tests what you think it tests.

Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/subpackage/ServerDefaultResourcesTest.java:32]: @joakime this test fails before fix and now passes.

The idea is that it is trying to load `jetty-dir.css`, and it does `getClass().getResource(name)`, internally this appends the package name as the resource does not start with `/`, and because the server is subclassed with the `{}` it is looking for `/org/eclipse/jetty/server/subpackage/jetty-dir.css` which does not exist.

Comment (joakime) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/subpackage/ServerDefaultResourcesTest.java:32]: So the second argument is an anonymous subclass. got it.

**Review by joakime — APPROVED** [review]
