### PR TITLE
Issue #4631 - Warning about skipping of <Arg> nodes is in wrong place for <Configure>

### LINKED ISSUE #4631: Startup XmlConfiguration WARN on Arg threadpool
_Originally posted by @TezzerFX in https://github.com/eclipse/jetty.project/issues/4620#issuecomment-593572876_

There's a WARN message on startup about the threadpool ...

```
$ java -jar ../start.jar
2020-03-02 15:05:36.442:INFO::main: Logging initialized @381ms to org.eclipse.jetty.util.log.StdErrLog
2020-03-02 15:05:36.558:WARN:oejx.XmlConfiguration:main: Ignored arg: <Arg name="threadpool"><Ref refid="threadPool"/></Arg>
2020-03-02 15:05:36.696:WARN::main: demo test-realm is deployed. DO NOT USE IN PRODUCTION!
2020-03-02 15:05:36.698:INFO:oejs.Server:main: jetty-9.4.28-SNAPSHOT; built: 2020-03-02T18:07:43.942Z; git: f2a4c6b6150938c03022f29f3fa25bed5b7451f3; jvm 11.0.6+10
```

### PR DESCRIPTION
**Pull request by joakime**
The warning for skipping of `<Arg>` nodes was left over after the work done in issue #4550
This warning isn't appropriate in the original place any more.

Added unit tests so that warnings are always in the appropriate place.

### CODE REVIEW

**Review by sbordet — CHANGES_REQUESTED** [review]
Do we really need the `Bogus*` classes? They don't add anything and I would rather use existing test classes that have similar signatures to the `Bogus*` introduced.

**Comment by joakime** [comment]
They are just test classes to use during testing of XmlConfiguration.
Starting them with "Test" would have triggered both junit and surefire to treat them as test cases expecting a lot of other things that are not relevant.
jetty-xml only depends on jetty-util, so using the real classes isn't an option.
Besides, the extra requirements of the real classes just would have made the tests far too noisy for no good reason.
The existing test classes in jetty-xml have grown [to be ridiculous](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-xml/src/test/java/org/eclipse/jetty/xml/TestConfiguration.java) and are super fragile now.

File: jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 1]
```diff
@@ -493,21 +501,6 @@ public Object configure() throws Exception
          */
         public void configure(Object obj, XmlParser.Node cfg, int i) throws Exception
```
Comment (gregw) [inline jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java:510]: Something weird has gone on in the history!  I thought the idea of passing in the index was so that leading ignored Args could be skipped!

File: jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 2]
```diff
@@ -466,6 +468,12 @@ public Object configure() throws Exception
                     throw new IllegalStateException(String.format("No matching constructor %s in %s", oClass, _configuration));
                 }
             }
+            else
+            {
+                // The Object already existed, if it has <Arg> nodes, warn about them not being used.
+                XmlConfiguration.getNodes(_root, "Arg")
+                    .forEach((node) -> LOG.warn("Ignored arg {} in {}", node, this._configuration._location));
```
Comment (gregw) [inline jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java:483]: I think we should somehow increment the index variable so that the Arg is ignored

**Review by gregw — CHANGES_REQUESTED** [review]
Something has gone wrong before this PR... but I think it might simplify this PR to deal with it (see comment below).

However I have tested the branch and this impl works fine.

**Comment by gregw** [comment]
@joakime I suspect it was me that broke the index mechanism some time ago.... I'll see if I can fix it for this PR.... stand by....

**Review by gregw — APPROVED** [review]

File: jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java [hunk 3]
```diff
@@ -1309,6 +1318,185 @@ public void testJettyStandardIdsAndPropertiesAndJettyHomeUriAndJettyBaseUri() th
...
+        XmlConfiguration last = null;
+        for (XmlConfiguration configuration : configurations)
+        {
+            if (last != null)
+                configuration.getIdMap().putAll(last.getIdMap());
+            configuration.configure();
+            last = configuration;
+        }
+        return last.getIdMap();
+    }
```
Comment (sbordet) [inline jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java:1498]: I would like to see a test where there is a `Arg` misplaced, as below, so that we define in a test how we should behave.

```xml
<Configure ...>
  <Arg>...</Arg>
  <New ...>...</New>
  <Arg>...</Arg>
</Configure>
```

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java (hunk 3 above)
Comment (joakime) [reply jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java:1498]: @gregw pointed out that the Configure_9_3.dtd (and Configure_10_0.dtd) does not allow a `<Arg>` anywhere but the start of the element list.

https://github.com/eclipse/jetty.project/blob/678385bfda0f90a0bcccf7f86aa272073c1b4f29/jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd#L45-L46

Comment (joakime) [reply jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java:1498]: A test that is expected to fail in this scenario is dependent on the dtd used (or not used) I would think.

Comment (sbordet) [reply jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java:1498]: Then shouldn't we do the same for `Call` and `New`? I don't think the DTD has the same enforcement for those.

Comment (joakime) [reply jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java:1498]: Opened #4658 for these new test cases.

Also `<Call>`

https://github.com/eclipse/jetty.project/blob/678385bfda0f90a0bcccf7f86aa272073c1b4f29/jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd#L168-L169

And `<New>`

https://github.com/eclipse/jetty.project/blob/678385bfda0f90a0bcccf7f86aa272073c1b4f29/jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd#L209-L210

Comment (joakime) [reply jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java:1498]: Also opened #4659 for the missing `Id?,Name?,Class?,Arg*` in the `<Configure>` section on `Configure_10_0.dtd`

Comment (gregw) [reply jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java:1498]: @sbordet we had such a test, but that is invalid XML against the DTD.  I don't think we should be required to process non-valid XML

Note that I'm doing a cleanup in 10 - see #4656
