### PR TITLE
Issue #5786 : Revisit Statistics classes

### LINKED ISSUE #5786: Revisit Statistics classes
**Jetty version**
9.4.x

**Description**
`MonitoredQueuedThreadPool` uses a number of statistics classes to record various properties.

`MonitoredQueuedThreadPool.getTasks()` is wrong, it should call `taskLatencyStats.getCount()` not `taskLatencyStats.getTotal()`.

Also, replace `Atomic*` with `LongAdder`.

Stop using deprecated `SampleStatistic.set()` method.

### PR DESCRIPTION
**Pull request by rk1165**
Signed-off-by: Ravi Kumar <kumarravi1165@gmail.com>

### CODE REVIEW

File: jetty-util/src/main/java/org/eclipse/jetty/util/thread/MonitoredQueuedThreadPool.java [hunk 1]
```diff
@@ -80,7 +80,7 @@ public void run()
                 {
                     long taskLatency = System.nanoTime() - start;
                     threadStats.decrement();
-                    taskLatencyStats.set(taskLatency);
+                    taskLatencyStats.record(taskLatency);
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/thread/MonitoredQueuedThreadPool.java:83]: I think you missed another call to `set()` few lines above.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]

**Comment by gregw** [comment]
@sbordet can we merge this one?

**Review by sbordet — APPROVED** [review]

**Comment by sbordet** [comment]
@rk1165 thanks! and sorry for the delay!
