### PR TITLE
Fix `IllegalArgumentException: demand pending`

### LINKED ISSUE #11694: Seeing `java.lang.IllegalArgumentException: demand pending` during load testing
**Jetty version(s)**
12.0.8

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
JDK21

**OS type/version**
Linux

**Description**

```
java.lang.IllegalArgumentException: demand pending
 	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelRequest.demand(HttpChannelState.java:955)
 	at org.eclipse.jetty.server.Request$Wrapper.demand(Request.java:803)
 	at org.eclipse.jetty.server.Request$Wrapper.demand(Request.java:803)
 	at org.eclipse.jetty.server.Request$Wrapper.demand(Request.java:803)
 	at org.eclipse.jetty.server.handler.ContextRequest.demand(ContextRequest.java:41)
 	at org.eclipse.jetty.ee10.servlet.AsyncContentProducer.isReady(AsyncContentProducer.java:252)
 	at org.eclipse.jetty.ee10.servlet.HttpInput.run(HttpInput.java:325)
 	at org.eclipse.jetty.ee10.servlet.ServletChannel.lambda$handle$1(ServletChannel.java:537)
 	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1292)
 	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1285)
 	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:537)
 	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1298)
 	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.lambda$execute$0(ContextHandler.java:1315)
 	at org.eclipse.jetty.util.thread.MonitoredQueuedThreadPool$1.run(MonitoredQueuedThreadPool.java:73)
 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**How to reproduce?**

Load testing

### PR DESCRIPTION
**Pull request by lorban**
Do not attempt to read from the underlying content source when there is a demand pending, i.e.: when inputState is unready, also cleanup and document the state machine.

Fixes https://github.com/jetty/jetty.project/issues/11694

### CODE REVIEW

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 1]
```diff
@@ -1154,18 +1150,14 @@ public void upgrade()
...
-            {
-                case IDLE:
-                    break;
-                default:
-                    throw new IllegalStateException(getStatusStringLocked());
-            }
+            if (_state != State.IDLE)
+                throw new IllegalStateException(getStatusStringLocked());
+            if (_inputState != InputState.IDLE)
+                throw new IllegalStateException(getStatusStringLocked());
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:1196]: Is this necessary and/or too strict?
For example, I can call isReady(), verify that it returns false so now it is UNREADY, and then do the upgrade?
Or call isReady(), there is content, so we are now in READY, but not do the `read()` and do the upgrade?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 2]
```diff
@@ -1369,6 +1336,8 @@ public void onReadIdle()
             if (LOG.isDebugEnabled())
                 LOG.debug("onReadIdle {}", toStringLocked());
 
+            // Blocking moves from UNREADY -> IDLE
+            // Async moves from READY -> IDLE
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: I would take the chance to document better the state constants.

Some hint, but maybe not complete:

IDLE -> initial state (useful to check that no reads have been made before an upgrade, but see the other comment); and after `read()` has been invoked.
READY -> from UNREADY, after the demand callback has been invoked, but before a call to `read()` (the other calls from the code that move to READY seem weird).
UNREADY -> from IDLE when `isReady()` returns `false`.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 3]
```diff
@@ -1398,11 +1367,11 @@ public void onReadUnready()
             switch (_inputState)
             {
                 case IDLE:
-                case UNREADY:
-                case READY:  // READY->UNREADY is needed by AsyncServletIOTest.testStolenAsyncRead
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:1402]: `AsyncServletIOTest.testStolenAsyncRead()` is flaky for me when I "run the test until failure", I get a failure after 2-3 runs.
I'm not sure it's related though.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 1 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:1196]: I think the problem is that as soon as we are unready, there is demand registered that will callback the `AsyncContentProvider` that might do a read.  So if we attempt to do an upgrade, then the new connection will not be able to read (demand pending) and that demand will go to the old `HttpInput`

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 4]
```diff
@@ -1369,6 +1336,8 @@ public void onReadIdle()
             if (LOG.isDebugEnabled())
                 LOG.debug("onReadIdle {}", toStringLocked());
 
+            // Blocking moves from UNREADY -> IDLE
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: I don't think we should only move from UNREADY TO IDLE if the demand callback is called or fatal error.  Moving from READY to IDLE is OK, as you have to be READY to be able to consume any input.

Note the method name is not really good....

actually, see my other comments, as I don't really see why we need tristate.  Don't we just need to know if we are demanding or not?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 5]
```diff
@@ -1398,11 +1367,11 @@ public void onReadUnready()
             switch (_inputState)
             {
                 case IDLE:
-                case UNREADY:
-                case READY:  // READY->UNREADY is needed by AsyncServletIOTest.testStolenAsyncRead
                     _inputState = InputState.UNREADY;
                     break;
 
+                case READY:
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:1411]: Just thinking out loud here... and maybe this should be in a comment.  We only call this method if:
 + some thread has called isReady
 + We were not already UNREADY
 + An attempt to produce a chunk returned null
 + We are going to demand immediately when this method returns.

So if we are READY, can we ever validly end up here?    We enter READY only when a readListener is first registered or when the demand `Runnable` is called.    The first case could have nothing to read, and the later case might have a chunk that is either empty.   We are meant to leave READY if somebody has read a non null chunk, but they often do that after a superfluous call to isReady.  So I'm not convinced we can't validly be here in READY state.... specially if some other read steals our chunk.

**Review by gregw — DISMISSED** [review]
I don't understand why we need the READY state? The transitions back to IDLE all seam a bit fragile and incomplete.

Why can't we just have a boolean called `unready`.  If `unready` is true, calls to `isReady` simply return false and any call to produceChunks returns null.  If we are `!unready`, then we can try to produce chunks.  If there is a call to `isReady` when we are `!unready`, then we can atomically test and set it to `unready`, we can then try to produce a chunk (bypassing the unready check), if we succeed, we flip back to `!unready`, else we demand and stay in `unready`.

The above might not be entirely correct, but I still don't see the need for 3 states. What is the current difference in behaviour between READY and IDLE?

**Comment by lorban** [comment]
I've spent much needed time reviewing the inputState logic to fully understand it then documenting the FSM _and its transitions_ as it's not obvious and once again, we forgot how that's meant to work.

For blocking mode, only two states are needed, and we use IDLE and UNREADY: UNREADY when a demand is pending and `read()` is blocked, IDLE otherwise.

For async mode, three states are needed:
 * UNREADY when a demand is pending
 * READY when a call to `ReadListener.onDataAvailable()` (or one of its siblings) must be dispatched
 * IDLE otherwise

The root cause of `IllegalArgumentException: demand pending` was that when we're UNREADY, a concurrent thread could call `read()` and possibly 'steal' the content before the demand is serviced, thus resetting the state to IDLE and allowing a second demand to be registered while the first one wasn't serviced yet. BTW, reading from a `Content.Source` while a demand is pending is explicitly discouraged by the `Content.Source` contract.
The fix for that is to stop reading from the content source while the inputState is UNREADY, and return null instead so that it's not possible to steal a pending demand's content anymore.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 1 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:1196]: After discussion, I think we are fine.

We can only go to non-idle if we set a `ReadListener` and then `upgrade()` within the `service()` method, which is bad API usage, so it will rightfully throw ISE.

If `upgrade()` is called from the `ReadListener`, then it should be fine: for a WebSocket GET upgrade we would call `onAllDataRead()` (there is no content), and be in IDLE state because we are inside a `ReadListener` method.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 6]
```diff
@@ -102,12 +103,26 @@ private enum RequestState
...
+     *                                         demand
+     *                                         serviced
+     * </pre>
      */
     private enum InputState
     {
-        IDLE,       // No isReady; No data
-        UNREADY,    // isReady()==false; No data
-        READY       // isReady() was false; data is available
+        IDLE,       // No ReadListener notification pending
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: Please make full javadocs with the following:
* what state it represents
* when this state is reached
* when this state is left

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 5 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:1411]: Before `unhandle()` returns `Action.READ_CALLBACK`, it flips the inputState back to `IDLE` so it should never be possible to transition from `READY` to `UNREADY`. This is now documented.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 6 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: Done.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 3 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:1402]: The test itself was flaky; fixed together.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 4 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: We do need 3 states, hopefully the documentation of the FSM I added should clear this up.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 7]
```diff
@@ -102,12 +103,45 @@ private enum RequestState
...
      */
     private enum InputState
     {
-        IDLE,       // No isReady; No data
-        UNREADY,    // isReady()==false; No data
-        READY       // isReady() was false; data is available
+        /**
+         * The 'default' state, when there is no pending demand nor a pending notification to the ReadListener.
+         * There are 3 ways to transition to this state:
+         * <li>from IDLE: when an async read() is called without a preceding call to isReady()</li>
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: `<li>` without surrounding `<ul>` also in the other javadocs.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 8]
```diff
@@ -102,12 +103,45 @@ private enum RequestState
...
+        /**
+         * The 'demand registered' state. There is only 1 way to transition to this state:
+         * <li>from IDLE: when isReady() is called and there is no content available, so a demand is registered</li>
+         */
+        UNREADY,
+
+        /**
+         * The 'dispatch a notification to the ReadListener' state. There are 2 ways to transition to this state:
+         * <li>from IDLE: when setReadListener() is called while there is content available</li>
+         * <li>from UNREADY: when demand is serviced</li>
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]:
```suggestion
         * <li>from UNREADY: when demand is serviced because content is now available</li>
```

**Review by sbordet — CHANGES_REQUESTED** [review]
Just minor niggles.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 7 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: Fixed.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java (hunk 8 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java]: Done.

**Review by sbordet — APPROVED** [review]
