### PR TITLE
Fixes #13436 - AssertionError in MemoryEndPointPipe.MemoryEndPoint.fill().

### LINKED ISSUE #13436: AssertionError in MemoryEndPointPipe.MemoryEndPoint.fill()
**Jetty version(s)**

    12.0.16

**Jetty Environment**

    core

**Java version/vendor** `(use: java -version)`

    openjdk 21.0.7 2025-04-15 LTS
    OpenJDK Runtime Environment Temurin-21.0.7+6 (build 21.0.7+6-LTS)
    OpenJDK 64-Bit Server VM Temurin-21.0.7+6 (build 21.0.7+6-LTS, mixed mode, sharing)

**OS type/version**

    MacOS 15.1.1

**Description**

When testing `org.eclipse.jetty.io.MemoryEndPointPipe` as an in-memory backend for `org.eclipse.jetty.client.HttpClient` we encounter an `AssertionError` when the received body is > 16k:

    java.lang.AssertionError
	at org.eclipse.jetty.io.MemoryEndPointPipe$MemoryEndPoint.fill(MemoryEndPointPipe.java:178)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parseAndFill(HttpReceiverOverHTTP.java:272)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.read(HttpReceiverOverHTTP.java:125)
	at org.eclipse.jetty.client.transport.HttpReceiver$ContentSource.read(HttpReceiver.java:694)
	at org.eclipse.jetty.client.Response$AsyncContentListener.onContentSource(Response.java:183)
	at org.eclipse.jetty.client.transport.ResponseListeners.notifyContentSource(ResponseListeners.java:242)
	at org.eclipse.jetty.client.transport.ResponseListeners.notifyContentSource(ResponseListeners.java:214)
	at org.eclipse.jetty.client.transport.HttpReceiver.lambda$responseHeaders$2(HttpReceiver.java:310)
	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:268)
	at org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:168)
	at org.eclipse.jetty.client.transport.HttpReceiver.responseHeaders(HttpReceiver.java:243)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.lambda$headerComplete$2(HttpReceiverOverHTTP.java:435)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:320)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parseAndFill(HttpReceiverOverHTTP.java:250)
	at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:76)
	at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:97)
	at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:207)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.MemoryEndPointPipe$FillableTask.run(MemoryEndPointPipe.java:290)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**How to reproduce?**

### PR DESCRIPTION
**Pull request by sbordet**
* Improved MemoryEndPoint.fill() to avoid assuming the space in the buffer parameter.
* Fixed race condition in [try]fillInterested(): now checks if the peer has data available.
* Improved MemoryEndPoint.flush() to flush as many bytes as possible, up to max capacity.

### CODE REVIEW

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/FillInterest.java [hunk 1]
```diff
@@ -91,16 +91,20 @@ public boolean tryRegister(Callback callback)
...
-            LOG.debug("fillable {}", this);
         Callback callback = _interested.get();
-        if (callback != null && _interested.compareAndSet(callback, null))
+        if (callback == null)
+        {
+            if (LOG.isDebugEnabled())
+                LOG.debug("fillable, no callback {}", this);
+            return false;
+        }
+        if (_interested.compareAndSet(callback, null))
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/FillInterest.java:101]: This branch is now missing a debug log.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java [hunk 2]
```diff
@@ -135,62 +145,79 @@ public int fill(ByteBuffer buffer) throws IOException
...
         }
 
+        @Override
+        public void fillInterested(Callback callback)
+        {
+            try (AutoLock ignored = lock.lock())
+            {
+                if (peerEndPoint.byteBuffers.isEmpty())
+                {
+                    super.fillInterested(callback);
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java:204]: Calling `super` while holding a lock looks suspicious.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java [hunk 3]
```diff
@@ -135,62 +145,79 @@ public int fill(ByteBuffer buffer) throws IOException
...
+            callback.succeeded();
+        }
+
+        @Override
+        public boolean tryFillInterested(Callback callback)
+        {
+            try (AutoLock ignored = lock.lock())
+            {
+                if (peerEndPoint.byteBuffers.isEmpty())
+                    return super.tryFillInterested(callback);
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java:221]: Ditto.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java [hunk 4]
```diff
@@ -209,18 +236,35 @@ public boolean flush(ByteBuffer... buffers) throws IOException
...
+                        long space = maxCapacity - capacity;
+                        if (space == 0)
+                        {
+                            result = false;
+                            break;
+                        }
+                        if (remaining <= space)
+                            slice = buffer.slice();
+                        else
+                            slice = buffer.slice(buffer.position(), (int)space);
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java]: Can't the blind cast to `int` here eventually overflow?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java [hunk 5]
```diff
@@ -227,7 +226,7 @@ public InvocationType getCallbackInvocationType()
         State s = _state.get();
         return (s instanceof PendingState)
             ? ((PendingState)s).getCallbackInvocationType()
-            : Invocable.InvocationType.BLOCKING;
+            : Invocable.InvocationType.NON_BLOCKING;
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java]: Why are you changing the invocation type?

**Review by lorban — CHANGES_REQUESTED** [review]
On top of my comments, there are 2 failing tests that seem to be caused by these changes.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java (hunk 4 above)
Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java]: Should be safe because the `else` branch is hit when `remaining > space`, and `remaining` is an `int`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/WriteFlusher.java]: I'll open a new issue where I will also consider the `CancellingState` in this method.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/FillInterest.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/FillInterest.java:101]: Restored.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java:204]: Must be so to avoid to miss notifications if there was a concurrent write that made data available.

**Review by lorban — CHANGES_REQUESTED** [review]
Looks alright, but there are still 2 tests failing that seem related.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java [hunk 6]
```diff
@@ -236,6 +277,24 @@ public boolean flush(ByteBuffer... buffers) throws IOException
             return result;
         }
 
+        private ByteBuffer copy(ByteBuffer buffer)
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/MemoryEndPointPipe.java]: This method assumes that it is called from within a thread, so could you please prefix it with `locked` and make it assert that the current thread holds the lock?

**Review by lorban — DISMISSED** [review]
Just one minor change, otherwise LGTM
