### PR TITLE
9.4.x: Add defensive check in HttpConnection content production

### LINKED ISSUE #6491: onDataAvailable() not called when HttpParser is closed prematurely
**Jetty version(s)**
9.4.42

**Description**
If the `HttpParser` is closed prematurely (state = `CLOSE`), then trying to read content asynchronously fail because `HttpConnection.fillAndParseForContent()` tests whether the parser is in content state.

### PR DESCRIPTION
**Pull request by lorban**
Currently, if the parser gets closed and the connection isn't aborted, the code enters a select/wakeup/fillAndParseForContent/wait infinite loop.

The above should never happen unless a bug gets introduced, but if such bug would happen at least the situation would be detected and acted upon.

See #6491.

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java [hunk 1]
```diff
@@ -316,6 +316,11 @@ else if (filled < 0)
      */
     protected boolean fillAndParseForContent()
     {
+        // Defensive check to avoid an infinite select/wakeup/fillAndParseForContent/wait loop
+        // in case the parser was mistakenly closed and the connection was not aborted.
+        if (_parser.isClose() || _parser.isClosed())
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java]: Didn't we add a `isXxx` that tested both of these states?  If not, let's do so as this double test is done at least one other location.

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java (hunk 1 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java]: Sure, if @sbordet agrees.

Comment (sbordet) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java]: @lorban I agree. I don't see the method in 9.4.x, but I would call it `isTerminated()` rather than `isPastEnd()` or similar.
The javadoc for the new method should be enough to explain the state.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java (hunk 1 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java]: Okay, I introduced `isTerminated()` by copying the mechanism that was already used to implement `isIdle()` and `isComplete()`.

**Review by sbordet — DISMISSED** [review]

**Review by gregw — APPROVED** [review]
