### PR TITLE
Issue #10402 - do not recycle ServletChannel if aborted

### LINKED ISSUE #10402: Investigate NPE from EE10 AsyncServletIOTest
`org.eclipse.jetty.ee10.servlet.AsyncServletIOTest#testCompleteWhilePending`

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.ee10.servlet.ServletContextResponse.setStatus(int)" because the return value of "org.eclipse.jetty.ee10.servlet.ServletChannel.getServletContextResponse()" is null
	at org.eclipse.jetty.ee10.servlet@12.0.1-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannelState.abortResponse(ServletChannelState.java:314)
	at org.eclipse.jetty.ee10.servlet@12.0.1-SNAPSHOT/org.eclipse.jetty.ee10.servlet.ServletChannel.abort(ServletChannel.java:866)
	at org.eclipse.jetty.ee10.servlet@12.0.1-SNAPSHOT/org.eclipse.jetty.ee10.servlet.HttpOutput.onWriteComplete(HttpOutput.java:248)
	at org.eclipse.jetty.ee10.servlet@12.0.1-SNAPSHOT/org.eclipse.jetty.ee10.servlet.HttpOutput$ChannelWriteCB.onCompleteFailure(HttpOutput.java:1429)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:328)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:369)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1267)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextResponse$1.succeeded(ContextResponse.java:41)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.internal.HttpConnection$DemandContentCallback.succeeded(HttpConnection.java:727)
	at org.eclipse.jetty.io/org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io/org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
fixes #10402

The write callback was being completed after the channel had been recycled. So now we maintain an outputState of `ABORTED` and do not allow the `ServletChannel` to be reused.

### CODE REVIEW

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java [hunk 1]
```diff
@@ -157,6 +157,7 @@ public void associate(Request request, Response response, Callback callback)
         _request = request;
         _response = response;
         _callback = callback;
+        _state.open();
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannel.java]:
```suggestion
        _state.openOutput();
```

**Review by gregw — APPROVED** [review]
LGTM... one small naming niggle, but only change if you really agree.
