### PR TITLE
Issue #11310 - multipart parser dropping some relevant CR bytes in parts

### LINKED ISSUE #11310: Uploading big multipart files via jetty 12.0.5 with spring boot 3.2.1 cause problems
**Jetty version(s)**,
12.0.5

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
java version "17.0.2" 2022-01-18 LTS

**OS type/version**
Windows

**Description**
We have a spring boot project which is using jetty server. After upgrading spring boot 3.2+ big file uploads with multipart file has broken something. Current endpoint is working like this:

- There is a post endpoint and client can upload multipart files from there.
- but all the files uploaded from this endpoint already uploaded to somewhere else with other application and we persist all of the md5 hashes of this files.
- The endpoint compares the uploaded file hash and already persisted hash and if it equals, flow continues.
- with spring boot 3.1.7 and jetty server 11.0.19 it is working correctly
- after spring boot versions upgrade (3.2.0, 3.2.1, 3.2.2) this flow is broken uploaded file hash is not equal anymore.
- This is only happening for with the big files (Tried with a file which is bigger than 1GB)
- With small size files there is no problem.
- tested the same flow with tomcat server and it is working
- we think that it could be related with DigestUtils, but then we tried to compare byte arrays directly and it is still problematic

**How to reproduce?**
- Created a sample project in GitHub to produce. (a big zip file is needed and related lines need to be changed in project)
- https://github.com/duzenz/uploadTest
- related endpoint is TestController.java file

### PR DESCRIPTION
**Pull request by joakime**
Fixing the MultiPart.Parser handling of part content that would drop occasional CR bytes if the CR occurs at the border of a network buffer.

This was fixed in PR #11388 (as the bug was first isolated during testing in that PR) but this is more fundamental bug unrelated to the goals of that PR so I created a standalone PR for this bug (also so that it shows up in the changelog for 12.0.7 appropriately)

Fixes #11310

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 1]
```diff
@@ -1392,6 +1392,7 @@ private boolean parseContent(Content.Chunk chunk)
             partialBoundaryMatch = boundaryFinder.endsWith(buffer);
             if (partialBoundaryMatch > 0)
             {
+                notifyCRContent();
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: See my comments in https://github.com/jetty/jetty.project/pull/11388#discussion_r1490603161 as I don't think this is always correct and is at odds with the comment below.

**Review by gregw — CHANGES_REQUESTED** [review]
@lachlan-roberts can you look at this?

**Review by sbordet — DISMISSED** [review]

**Comment by gregw** [comment]
I've looked a little bit more at this and I think we need to never emit a content chunk that ends with a CR, as that may be the first byte of a CRLF preceding a boundary.

We will still need the `if (sliceLimit > 0 && buffer.get(sliceLimit - 1) == '\r')` code to look for CRs within a buffer, but when sliceLimit==0, then the crContent will have already been set.

I think we can better utilize the existing `crContent` boolean to remember if there is a hanging CR (skipped as the last byte of a previous chunk), then when we emit the next content,( including a partially matched boundary), we emit  the CR content first if the boolean is set.

**Comment by sbordet** [comment]
@gregw 

> we need to never emit a content chunk that ends with a CR, as that may be the first byte of a CRLF preceding a boundary

Not sure what you mean here, but we do emit the content chunk excluding the last CR, which we remember in the boolean until we have another chunk to parse.

Not sure I understand the rest of your comment, but I found and fixed another bug.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: @gregw I think this `notifyCRContent()` is correct.

We may have a CR left over from a previous buffer which has not been emitted as content. And at this point (where we have a partial match with content in this buffer before the match), the saved CR can no longer be part of the boundary, so we must emit it and check again at `buffer.get(sliceLimit - 1)` before we can emit the other content.

I think your comment in the other PR is correct but with the `if (partialBoundaryMatch == buffer.remaining())` block here, we can no longer reach the `notifyCRContent()` if the match starts at the beginning of the current buffer.

So I think the check for `sliceLimit > 0` on line 1411 is now redundant because it is not possible. Shouldn't this have been `sliceLimit > pos` anyway?

Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: @lachlan-roberts good point re `sliceLimit > 0`, I removed it.

**Comment by gregw** [comment]
I think I have convinced myself this is correct.... but I also think it needs either some better comments, and/or perhaps some simplifications.
I'll have a fiddle this afternoon and make some suggestions.

**Comment by gregw** [comment]
@joakime @sbordet I have pushed to this branch some simplifications to the logic and some comments that make it easier for me to understand.    If you think they are at all controversial, let's revert and hangout to clarify.

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartFormDataTest.java [hunk 2]
```diff
@@ -663,6 +663,336 @@ public void testDefaultCharset() throws Exception
...
+
+            MultiPart.Part spaces = parts.get(0);
+            String content = spaces.getContentAsString(UTF_8);
+
+            assertEquals("ABC\n\rDEF\n", content);
+        }
+    }
+
+    @Test
+    public void testLFContentByteByByte() throws Exception
```
Comment (joakime) [inline jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartFormDataTest.java]: This seems like a duplicate of the existing `testOneByteChunks()` method

Comment (gregw) [reply jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/MultiPartFormDataTest.java]: ooops it was. Removed.

**Comment by sbordet** [comment]
Sorry @gregw, I liked the code better before your changes, as it was clearer what cases did what.
The new code is more difficult to follow for me because of fall-throughs that now force you do re-read the code above to figure out what cases are covered. I liked the `if/else` blocks better because you knew exactly what case it was.

Also, most of your added comments are just repetitions of what the code does on the next line, so they are unnecessary, and they will rotten away if the code changes.

Lastly, can you please be consistent and start all your comment with a capital letter and end with a period? (Sorry to be pedantic on this, but it's really confusing -- also the "conversation" style of the comments make you re-read from above otherwise the comment is out of context).
Reading many of your comments is unclear if there is a line before that was forgotten (because it starts with a lowercase), or a line after that was forgotten (because it does not end with a period).
Because in other cases you do use a capital to start and a period to end, so one wonders what's missing in the ones that are not like that.

**Comment by gregw** [comment]
@sbordet if it is just the fall throughs that you don't like, then let me put the if elses back, as I think there were some good simplifications even without that.
I'll review the comments as well, for needless repetition of the code.

If you don't like that, then I'll revert both commits and give a negative review on the bits that I found very confusing and let you have a go of either improving them or better comments.

standby...

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 3]
```diff
@@ -1392,12 +1393,22 @@ private boolean parseContent(Content.Chunk chunk)
...
+                    return false;
+                }
+
+                notifyCRContent();
+
                 int limit = buffer.limit();
                 int sliceLimit = limit - partialBoundaryMatch;
                 // BoundaryFinder is configured to search for '\n--Boundary';
-                // if we found '\r\n--Bo' then the '\r' may not be content,
+                // if '\r\n--Bo' is found, then the '\r' may not be content,
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: There is a large amount of duplication between this section of code and that below.  Both are writing out the definite content.   You need both comments explaining what the code is doing and to remove the duplication.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 4]
```diff
@@ -1392,12 +1393,22 @@ private boolean parseContent(Content.Chunk chunk)
...
             {
+                if (partialBoundaryMatch == buffer.remaining())
+                {
+                    // The boundary was partially matched, but it
+                    // is not clear yet if it is content or boundary.
+                    buffer.position(buffer.limit());
+                    return false;
+                }
+
+                notifyCRContent();
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: You need a comment here to make it clear that the CR that might be emitted here is not the CR that might be in front of the just matched partial boundary.   

You need to say something like "we know there is some content in the buffer before the next boundary, so we can emit any hanging CR from the previous chunk"

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 5]
```diff
@@ -1378,7 +1379,7 @@ private boolean parseContent(Content.Chunk chunk)
                 int position = buffer.position();
                 int length = boundaryOffset;
                 // BoundaryFinder is configured to search for '\n--Boundary';
-                // if we found '\r\n--Boundary' then the '\r' is not content.
+                // if '\r\n--Boundary' is found, then the '\r' is not content.
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1385]: the code above this block is:
```java
if (boundaryOffset == 0)
    crContent = false;
if (boundaryOffset >= 0)
{
    notifyCRContent();
```

This should be:

```java
if (boundaryOffset >= 0)
{
    if (boundaryOffset == 0)
        crContent = false;
    else
        notifyCRContent();
```

but with better comments

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 6]
```diff
@@ -1339,7 +1339,8 @@ private boolean parseContent(Content.Chunk chunk)
                     }
                     else
                     {
-                        // The boundary was partially matched.
+                        // The boundary was partially matched, but it
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1342]: This section is confusing with nested if structure:
```java
if (boudnaryMatch > 0)
{
    if (boundaryMath == X)
    {
        // A
    }
    else
    {
        // B
    }
}
else
{
    // C
}
```
This should be:

```java
if (boudnaryMatch > 0)
{
    // A
} 
else if (boundaryMath == X)
{
    // B
}
else
{
    // C
}
```

**Review by gregw — CHANGES_REQUESTED** [review]
The logic needs cleanup and better comments

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 6 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1342]: It is not equivalent.
In your version, when `boundaryMatch == X` it will execute the branch where `boundaryMatch > 0`, which is wrong.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1385]: Done.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 4 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Done.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Removed duplication.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 6 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:1342]: Ooops I meant:
```java
if (boudnaryMatch == X)
{
    // A
} 
else if (boundaryMath > 0)
{
    // B
}
else
{
    // C
}
```

**Review by gregw — APPROVED** [review]
I still think the logic can be cleaned up more in this class.... but let's get the CR fix in.
