### PR TITLE
Issue #14332 - fix idleTimeout bug after upgrading to WebSocket

### LINKED ISSUE #14332: Complete mess with idleTimeout
**Jetty version(s)**
12.0.31

**Jetty Environment**
core, ee10

**HTTP version**
HTTP 1.1

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.6" 2025-01-21 LTS
OpenJDK Runtime Environment Corretto-21.0.6.7.1 (build 21.0.6+7-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.6.7.1 (build 21.0.6+7-LTS, mixed mode, sharing)

**OS type/version**
Any Linux OS

**Description**
Maybe it would be useful for someone. This is how I figured out `Idle timeout expired: 30000/30000 ms` issue for websocket.

I have a legacy app that I'm bound to maintain. The app uses HTTP and WebSocket.
Some customers complain they experience accidental logouts every 30 seconds, as on websocket close app logs out the user. In logs I see these lines

```
Caused by: org.eclipse.jetty.websocket.core.exception.WebSocketTimeoutException: Connection Idle Timeout
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
```
In `JettyWebSocketServlet` derived class `configure` method I had set some value distinct from 30 seconds.
```java
aFactory.setIdleTimeout(Duration.ofMillis(timeout));
```
Regardless of this the issue happens every 30 seconds, but only for some customers.

In other app part there's http server created and the idle timeout set like this. The value also differs from 30 seconds.
```java
final HttpConnectionFactory httpConnectionFactory = new HttpConnectionFactory(httpConfig);
httpConnectionFactory.getHttpConfiguration().setIdleTimeout(timeoutMs);
```

Eventually what I figured out. Endpoints (jetty objects) actually hold idle timeout value, but it turns out it always setup multiple times regardless whether endpoint relates to websocket or httpconnection, doesn't matter.

This is logs
```
@4334e59f{s=END}]=>HttpChannelState@7920438c{handling=null, handled=true, send=LAST_COMPLETE, completed=true, request=GET@1d84cfe3 http://172.17.0.2:62616/oms/websocket HTTP/1.1}]
2026-01-16 17:36:45.745 [qtp1944295884-112] DEBUG org.eclipse.jetty.io.IdleTimeout - Setting idle timeout 0 -> 30000 on SocketChannelEndPoint@639a49e4[{l=/172.17.0.2:62616,r=/172.17.0.1:35200,OPEN,fill=-,flush=-,to=0/30000}{io=0/0,kio=0,kro=0}]->[<null>]
2026-01-16 17:36:45.748 [qtp1944295884-108] DEBUG org.eclipse.jetty.io.IdleTimeout - Setting idle timeout 30000 -> 120000 on SocketChannelEndPoint@639a49e4[{l=/172.17.0.2:62616,r=/172.17.0.1:35200,OPEN,fill=-,flush=-,to=1/120000}{io=0/0,kio=0,kro=1}]->[HttpConnection@65af77d5[p=HttpParser{s=HEADER,0 of -1},g=HttpGenerator@3a9978d1{s=START}]=>HttpChannelState@bfdd30f{handling=null, handled=false, send=SENDING, completed=false, request=GET@2b807330 http://172.17.0.2:62616/oms/websocket HTTP/1.1}]
2026-01-16 17:36:45.750 [qtp1944295884-108] DEBUG org.eclipse.jetty.io.IdleTimeout - Setting idle timeout 120000 -> 60000 on SocketChannelEndPoint@639a49e4[{l=/172.17.0.2:62616,r=/172.17.0.1:35200,OPEN,fill=-,flush=-,to=3/60000}{io=0/0,kio=0,kro=1}]->[HttpConnection@65af77d5[p=HttpParser{s=END,0 of -1},g=HttpGenerator@3a9978d1{s=START}]=>HttpChannelState@bfdd30f{handling=Thread[#108,qtp1944295884-108,5,main], handled=false, send=SENDING, completed=false, request=GET@2b807330 http://172.17.0.2:62616/oms/websocket HTTP/1.1}]
2026-01-16 17:36:45.752 [qtp1944295884-108] DEBUG org.eclipse.jetty.io.IdleTimeout - Setting idle timeout 60000 -> 30000 on SocketChannelEndPoint@639a49e4[{l=/172.17.0.2:62616,r=/172.17.0.1:35200,OPEN,fill=-,flush=-,to=1/30000}{io=0/0,kio=0,kro=1}]->[HttpConnection@65af77d5[p=HttpParser{s=END,0 of -1},g=HttpGenerator@3a9978d1{s=END}]=>HttpChannelState@bfdd30f{handling=null, handled=true, send=LAST_COMPLETE, completed=true, request=GET@2b807330 http://172.17.0.2:62616/oms/websocket HTTP/1.1}]
```
Here you can see three values distinct from zero. 120000 is for http, 60000 is for websocket I mentioned them above and 30000 that turns out hardcoded in the `org.eclipse.jetty.server.AbstractConnector`.  Looks like this flow is not stable and can change, sometimes I saw the end value is 120000.

Image

From logs it's seen the same endpoint object `SocketChannelEndPoint@639a49e4` is assigned different timeouts ending up in 30000. That's the cause of the issue. So to resolve this I was bound to set the same value for the entities at first glance looking untied, like distinct connection instances providing different protocols.

Image
Image

So be aware that http idle timeout will be exposed into your websocket connection instance. When I added above changes (marked  with 2, 3) I now have all the setup points set same value ending up with my value and not 30 seconds hardcoded... In this case only last two lines are for the same object as maybe due to same value check
```
2026-01-16 18:16:58.563 [qtp1944295884-138] DEBUG org.eclipse.jetty.io.IdleTimeout - Setting idle timeout 0 -> 120000 on SocketChannelEndPoint@d350052[{l=/172.17.0.2:62616,r=/172.17.0.1:33888,OPEN,fill=-,flush=-,to=3/120000}{io=0/0,kio=0,kro=0}]->[<null>]
2026-01-16 18:16:58.712 [qtp1944295884-139] DEBUG org.eclipse.jetty.io.IdleTimeout - Setting idle timeout 0 -> 120000 on SocketChannelEndPoint@14e386b5[{l=/172.17.0.2:62616,r=/172.17.0.1:33890,OPEN,fill=-,flush=-,to=0/120000}{io=0/0,kio=0,kro=0}]->[<null>]
2026-01-16 18:16:58.713 [qtp1944295884-140] DEBUG org.eclipse.jetty.io.IdleTimeout - Setting idle timeout 0 -> 120000 on SocketChannelEndPoint@42b28201[{l=/172.17.0.2:62616,r=/172.17.0.1:33896,OPEN,fill=-,flush=-,to=0/120000}{io=0/0,kio=0,kro=0}]->[<null>]
2026-01-16 18:16:59.318 [qtp1944295884-141] DEBUG org.eclipse.jetty.io.IdleTimeout - Setting idle timeout 0 -> 120000 on SocketChannelEndPoint@1c0554c2[{l=/172.17.0.2:62616,r=/172.17.0.1:33910,OPEN,fill=-,flush=-,to=0/120000}{io=0/0,kio=0,kro=0}]->[<null>]
2026-01-16 18:16:59.531 [qtp1944295884-111] DEBUG org.eclipse.jetty.io.IdleTimeout - Setting idle timeout 0 -> 120000 on SocketChannelEndPoint@22bb1a2[{l=/172.17.0.2:62616,r=/172.17.0.1:33922,OPEN,fill=-,flush=-,to=0/120000}{io=0/0,kio=0,kro=0}]->[<null>]
2026-01-16 18:16:59.594 [qtp1944295884-113] DEBUG org.eclipse.jetty.io.IdleTimeout - Setting idle timeout 120000 -> 120000 on SocketChannelEndPoint@22bb1a2[{l=/172.17.0.2:62616,r=/172.17.0.1:33922,OPEN,fill=-,flush=-,to=60/120000}{io=0/0,kio=0,kro=1}]->[HttpConnection@12ae533a[p=HttpParser{s=END,0 of -1},g=HttpGenerator@fb3aa63{s=START}]=>HttpChannelState@50caac96{handling=Thread[#113,qtp1944295884-113,5,main], handled=false, send=SENDING, completed=false, request=GET@392361a6 http://172.17.0.2:62616/oms/websocket HTTP/1.1}]
```
I even saw they set idle timeout to new value in request handlers as well.  Now it works as expected.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Issue #14332

The code in `HttpChannelState.completeStream` under certain conditions is resetting the idleTimeout.

This is causes issues when the connection is upgraded to websocket, and this will override any websocket specific idleTimeout configuration.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 1]
```diff
@@ -342,8 +340,7 @@ public Runnable onRequest(MetaData.Request request)
                 responseHeaders.add(getConnectionMetaData().getConnector().getServer().getDateField());
 
             long idleTO = httpConfiguration.getIdleTimeout();
-            _oldIdleTimeout = _stream.getIdleTimeout();
-            if (idleTO >= 0 && _oldIdleTimeout != idleTO)
+            if (idleTO >= 0 && _stream.getIdleTimeout() != idleTO)
                 _stream.setIdleTimeout(idleTO);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I don't like setting it, and then not resetting it back.

Honestly, I would remove this code and deprecate `HttpConfiguration.idleTimeout`.
@gregw do you remember why this was added?
Why was not the `Connector.idleTimeout` enough that we had to add one in `HttpConfiguration`, do you recall?

The reason is that it is not used consistently, and it is not clear how's different from the connector idle timeout.

For example, `ConnectionLimit` and `NetworkConnectionLimit` do not honor it, and just rely on the connector idle timeout.
Same for `LowResourceMonitor`.

Maybe deprecate `HttpConfiguration.idleTimeout`, and keep this code until we can remove it.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by sbordet** [comment]
@lachlan-roberts sorry but it is not clear what's happening here.

The idle timeout is set by the WebSocket implementation from `AbstractHandshaker.upgradeRequest()`, but this happens _before_ completion of `HttpStreamOverHTTP1` (too early?)

Then the `HttpStreamOverHTTP1` completes, and upgrades the `Connection` onto the `EndPoint`, which calls `WebSocketConnection.onOpen()`, where we would have the chance to set the WebSocket-specific idle timeout _after_ HTTP is complete.

I think we need to rework the sequence of events, and perhaps we can leave `HttpChannelState` unmodified for now (although `HttpConfiguration.idleTimeout` is still questionable, but now it appears to be an orthogonal issue).

**Comment by lachlan-roberts** [comment]
@sbordet There is already some logic in `WebSocketCoreSession` to temporarily delay setting the `idleTimeout` until the `Connection` is set.

So I can just change this to delay instead until `onOpen` is called. And I will revert the other changes to `HttpConfiguration` and `HttpChannelState`.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java [hunk 2]
```diff
@@ -132,15 +132,20 @@ public String getNegotiatedSubProtocol()
...
+            return WebSocketConstants.DEFAULT_IDLE_TIMEOUT;
     }
 
     @Override
     public void setIdleTimeout(Duration timeout)
     {
         idleTimeout = Objects.requireNonNull(timeout);
-        if (connection != null)
-            connection.getEndPoint().setIdleTimeout(timeout.toMillis());
+        if (!sessionState.isConnecting())
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java:147]: Do you really need `WebSocketSessionState.isConnecting()`?

I ask because before a check on the `connection` field was enough, and the check on the `connection` field is still done in `getIdleTimeout()`, so feels like this should just be `if (connection != null)`.

**Review by sbordet — CHANGES_REQUESTED** [review]
I still think it's better to set the idle timeout from `WebSocketConnection.onOpen()`.

In this way, you won't need `isConnected()`, you won't need to "delay" anything

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java:147]: The reason I used the `!sessionState.isConnecting()` check is because this is called during the WebSocket upgrade. And then it will be set back to the HTTP value after by the `HttpChannelState`, and then set again by `onOpen`.

So having this check prevents the idleTimeout on the endpoint being set back and fourth
1. httpIdleTimeout inherited
2. webSocketIdleTimeout set from upgrade
3. httpIdleTimeout restored from HttpChannelState
4. webSocketIdleTimeout set again from onOpen

Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java:147]: I think this should be simplified to just:

1. idle timeout is set on the HttpConnection
2. WS upgrade not setting the idle timeout
3. HttpChannelState "restoring" the idle timeout
4. WS idle timeout set from onOpen()

**Comment by sbordet** [comment]
~~@lachlan-roberts can you also please fix what's reported here, and add a test case:
https://github.com/jetty/jetty.project/issues/14535#issuecomment-4097675884~~

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java:147]: @sbordet that is the purpose of this check, to prevent case in 2 where the idleTimeout is set on the endpoint during the upgrade.

**Review by sbordet — APPROVED** [review]
