### PR TITLE
Jetty 12: `ContextHandler.getTempDirectory()` does not respect the `Context.getTempDirectory()` contract

### LINKED ISSUE #11396: NullPointerException when getting parts from HttpServletRequest
**Jetty version(s)**
12.0.5

**Jetty Environment**

ee10

**Java version/vendor** `(use: java -version)`

Picked up JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode)

**OS type/version**
MacOS M3 

**Description**

There is an NPE when `HttpServletRequest#getParts` is used for a manually configured Jetty server.
The stacktrace is:

```
jakarta.servlet.ServletException: org.eclipse.jetty.http.BadMessageException: 400: bad multipart
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getParts(ServletApiRequest.java:591)
	at com.flowable.content.rest.util.JettyTest$TestServlet.doPost(JettyTest.java:68)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:797)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:428)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:761)
	at org.eclipse.jetty.server.Server.handle(Server.java:179)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:594)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:424)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.eclipse.jetty.http.BadMessageException: 400: bad multipart
	... 21 more
Caused by: java.lang.NullPointerException: Cannot invoke &quot;java.io.File.toPath()&quot; because &quot;filesDirectory&quot; is null
	at org.eclipse.jetty.ee10.servlet.ServletMultiPartFormData.lambda$from$0(ServletMultiPartFormData.java:128)
	at org.eclipse.jetty.http.MultiPartFormData.from(MultiPartFormData.java:86)
	at org.eclipse.jetty.ee10.servlet.ServletMultiPartFormData.from(ServletMultiPartFormData.java:104)
	at org.eclipse.jetty.ee10.servlet.ServletMultiPartFormData.from(ServletMultiPartFormData.java:60)
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getParts(ServletApiRequest.java:508)
	... 20 more
```

Is there a reason why the `ContextHandler` is not using `getServer().getContext().getTempDirectory()`? It is in 

https://github.com/jetty/jetty.project/blob/a683690678fd0323918bb5079341d10ad8979c89/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java#L1125-L1131

If the `ServerContext` is used there then `null` will not be returned since it does:

https://github.com/jetty/jetty.project/blob/a683690678fd0323918bb5079341d10ad8979c89/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java#L948-L951

and `tmpDir` is never null:

https://github.com/jetty/jetty.project/blob/a683690678fd0323918bb5079341d10ad8979c89/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Server.java#L861

**How to reproduce?**

Run the following main class:

```java
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.Collection;

import jakarta.servlet.MultipartConfigElement;
import jakarta.servlet.ServletContextEvent;
import jakarta.servlet.ServletContextListener;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRegistration;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.Part;

import org.eclipse.jetty.ee10.servlet.ServletContextHandler;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;

public class JettyTest {

    public static void main(String[] args) throws IOException, InterruptedException {
        Server server = new Server();
        //server.setTempDirectory(new File(System.getProperty("java.io.tmpdir")));
        ServerConnector connector = new ServerConnector(server);
        connector.setPort(0);
        server.addConnector(connector);
        ServletContextHandler contextHandler = new ServletContextHandler("/test");
        server.setHandler(contextHandler);
        contextHandler.addEventListener(new TestServletListener());

        try {
            server.start();
        } catch (Exception e) {
            throw new RuntimeException("Failed ot start server", e);
        }

        HttpRequest request = HttpRequest.newBuilder(URI.create("http://localhost:" + connector.getLocalPort() + "/test/service/form-data"))
                .header("Content-Type", "multipart/form-data; boundary=boundaryId")
                .POST(HttpRequest.BodyPublishers.ofString("--boundaryId\n"
                        + "Content-Disposition: form-data; name=\"file1\"; filename=\"a.txt\"\n"
                        + "Content-Type: text/plain; charset=ISO-8859-1\n"
                        + "Content-Transfer-Encoding: binary\n"
                        + "\n"
                        + "Content of a.txt\n"
                        + "--boundaryId--\n"))
                .build();
        HttpResponse<String> response = HttpClient.newHttpClient()
                .send(request, HttpResponse.BodyHandlers.ofString());

        System.out.println("Received status code: " + response.statusCode());
        System.out.println("Received response: " + response.body());
    }

    protected static class TestServlet extends HttpServlet {

        @Override
        protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
            Collection<Part> parts = request.getParts();
            response.setStatus(HttpServletResponse.SC_OK);
            response.getOutputStream().print("Received " + parts.size() + " parts");
        }
    }

    protected static class TestServletListener implements ServletContextListener {

        @Override
        public void contextInitialized(ServletContextEvent sce) {
            ServletRegistration.Dynamic registration = sce.getServletContext().addServlet("Test Servlet", new TestServlet());
            registration.addMapping("/service/*");
            registration.setMultipartConfig(new MultipartConfigElement((String) null));
            registration.setLoadOnStartup(1);
            registration.setAsyncSupported(true);
        }

    }

}
```

### PR DESCRIPTION
**Pull request by lorban**
The `Context.getTempDirectory()` contract states that null should never be returned, while the `ContextHandler.getTempDirectory()` implementation may return null depending on the `MultipartConfigElement`.

This PR makes sure that `ContextHandler.getTempDirectory()` never returns null.

Fixes #11396

### CODE REVIEW

**Review by joakime — CHANGES_REQUESTED** [review]
@lorban the `ServletContextHandler` now needs to be updated to make a unique directory within the Server temp directory.

A test case would be ...

* A Server with a default temp directory.
* A `ServletContextHandler` on context-path `/foo` (no temp directory defined at this level)
* A `ServletContextHandler` on context-path `/bar` (no temp directory defined at this level)
* Submit a `multipart/form-data` to `/foo/` that has 2 parts (part `"name"` and part `"file"` which causes a Temp directory write)
* Submit a `multipart/form-data` to `/bar/` that has 2 parts (part `"name"` and part `"file"` with different file contents,  which also causes a Temp directory write)

Those two usages should not step on each others toes.
The `ServletContext.TEMPDIR` attribute should also report as different for each of those `ServletContextHandler` instances.

**Comment by lorban** [comment]
@joakime I think I modified the PR to handle the cases you specified.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java [hunk 1]
```diff
@@ -290,13 +287,6 @@ public ServletContextHandler(String contextPath, SessionHandler sessionHandler,
         relinkHandlers();
     }
 
-    @Override
-    public void setTempDirectory(File tempDirectory)
-    {
-        super.setTempDirectory(tempDirectory);
-        setAttribute(TEMPDIR, getTempDirectory());
```
Comment (joakime) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java]: Where does this spec attribute get set now?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java [hunk 2]
```diff
@@ -304,6 +305,9 @@ public Charset getQueryEncoding()
     @Override
     public Object getAttribute(String name)
     {
+        if (ServletContext.TEMPDIR.equals(name))
+            return getContext().getTempDirectory();
```
Comment (joakime) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java]: This behaves kinda like a synthetic attribute now.

Note: the `ServletContext.TEMPDIR` is a ServletContext attribute, not a Request attribute (I think this code is in the wrong place)

Will this attribute show up when a user iterates the attributes now?

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MultiPartServletTest.java [hunk 3]
```diff
@@ -371,6 +391,152 @@ protected void service(HttpServletRequest request, HttpServletResponse response1
...
+    @Test
+    public void testDefaultTempDirectoryWithMultipleContexts() throws Exception
+    {
+        List<File> tmpDirs = new CopyOnWriteArrayList<>();
+        HttpServlet servlet = new HttpServlet()
+        {
+            @Override
+            protected void service(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
+            {
+                File tmpDirFromAttribute = (File)request.getAttribute(ServletContext.TEMPDIR);
```
Comment (joakime) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MultiPartServletTest.java]: Using `request.getAttribute(ServletContext.TEMPDIR)` should return null.
That attribute doesn't exist on the request, it only exists on the context.

This code should be using `getServletContext().getAttribute(ServletContext.TEMPDIR)` instead.

**Review by joakime — CHANGES_REQUESTED** [review]
Good progress, but the TEMPDIR attribute is in the wrong place now.  
It should only exists on the ServletContext attributes, not the HttpServletRequest attributes

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 4]
```diff
@@ -1124,9 +1126,15 @@ public Resource getBaseResource()
...
             if (tempDirectory == null)
-                tempDirectory = getServer().getTempDirectory();
+            {
+                tempDirectory = ContextHandler.this.getTempDirectory();
+                if (tempDirectory == null)
+                {
+                    tempDirectory = new File(getServer().getContext().getTempDirectory(), _contextPath);
+                    tempDirectory.mkdirs();
+                }
+            }
```
Comment (filiphr) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: How does this behave in a concurrent scenario? From what I can see there is now a private field on the `ScopedContext` which gets assigned on the `ScopedContext` when the `getTempDirectory` method is called.  I don't know much about how all of this gets called. However, from what I could see in the code it gets called from `ServletApiRequest#getParts` and I can imagine that this can get called from multiple threads.

Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: You're correct, this code could be called by multiple concurrent threads. The current version is safe by accident, but it should be improved. Let me work on this.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java (hunk 1 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java]: I've mistakenly moved that attribute from context to request. Let me move it back to where it belongs.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java (hunk 2 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java]: You're right, let me fix that.

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MultiPartServletTest.java (hunk 3 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MultiPartServletTest.java]: You're right, let me fix that.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java [hunk 5]
```diff
@@ -1988,6 +1979,22 @@ public String toString()
...
+        }
+
+        @Override
+        public Set<String> getAttributeNameSet()
+        {
+            Set<String> attributeNameSet = new HashSet<>(super.getAttributeNameSet());
+            attributeNameSet.add(ServletContext.TEMPDIR);
+            return Collections.unmodifiableSet(attributeNameSet);
+        }
+
```
Comment (filiphr) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java]: Isn't the previous code with the `setAttribute(TEMPDIR, getTempDirectory());` in the `ServletContextHandler#setTempDirectory` a bit more performant than this one? 

I don't know the code base much, but from what I could see if the `TEMPDIR` attribute is set in the `ServletContextHandler#setTempDir` you won't need to create this copy of the existing set.

Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java]: You're right, with my latest changes this special getAttribute() implementation isn't needed anymore.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 6]
```diff
@@ -669,8 +680,33 @@ protected void createTempDirectory()
...
+                                System.out.println("  user name: " + System.getProperty("user.name") + " file owner: " + owner + " perm: " + posixFilePermissions);
+                            }
+                            catch (Exception ex)
+                            {
+                                ex.printStackTrace();
+                            }
+                        }
+                        path = path.getParent();
+                    }
+                    throw new IllegalArgumentException("Unable to create temp dir: " + tempDirectory, e);
```
Comment (filiphr) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: I see that you are using `System.out` here. Doesn't it make more sense to use the logger? I was also comparing this a bit with the way you are creating the temp directory in `WebInfConfiguration`

https://github.com/jetty/jetty.project/blob/55e307224782b4b7ed4cc0756deafdd492c9417c/jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebInfConfiguration.java#L155-L182

A slightly different approach is used there. e.g. `Files.createTempDirectory` from Java itself. 

Again, I have no clue about the codebase, and I'm just comparing with a subset of things I can see.

Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: That was very temporary to help me troubleshoot some test failures in CI. Now that I've figured them out, I reverted that ugly change.

Comment (filiphr) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: oops sorry for the noise in that case. I won't mix in your review anymore. Thank you very much for looking into my issue and working on a fix for it.

**Comment by lorban** [comment]
@gregw @janbartel I need your wisdom here.

This PR started as something simple: the `org.eclipse.jetty.server.Context.getTempDirectory()` contract says: _return a non-null temporary directory_ and the `ContextHandler.ScopedContext` implementation does not respect that contract as it returns null when no temp directory is explicitly configured, which makes multipart servlets throw NPE as they make use of the temp directory internally.

So I changed the `ContextHandler.ScopedContext.getTempDirectory()` implementation to never return null by delegating the call to `getServer().getContext().getTempDirectory()` when no temp directory is explicitly configured. That looked easy, but that was, unfortunately, the beginning of a rabbit's hole.

But that did not work as each context should have its own temp directory, which may be persistent, or there may be different running Jetty servers with the same server temp directory (which defaults to `java.io.tmpdir`), so the contexts' temp folder names must be unique (we *do* run into that case simply by running our unit tests in parallel), then @joakime reminded me that we generate temp folder names using a well-known format for webapps (using `WebInfConfiguration.getCanonicalNameForWebAppTmpDir()`) so we may want to do something similar for core contexts. And now, every context has a temp directory that must be created, deleted, checked for persistence and so on while that is rarely needed.

So that got me wondering: is my fix over-engineered? Is the `org.eclipse.jetty.server.Context.getTempDirectory()` too strict in forbidding to return null? Shouldn't multipart servlets be able to cope with that lack of temp folder?

**Comment by joakime** [comment]
> But that did not work as each context should have its own temp directory

I still feel that every `ServletContextHandler` should have it's own private temp directory (as the javadoc for `ServletContext` says).
But having every `ContextHandler` be its own unique temp directory feels like overkill.

**Comment by janbartel** [comment]
@lorban @joakime please see my comment on the original issue.

The only change we need to make is to ensure that `ScopedContext` falls back to `java.io.tmpdir` after trying the `Server.getTempDir()`.

`ServletContextHandler`s in all previous versions of jetty have never had their own, unique temporary directory - that is something we set up for `WebAppContext`s. It's a separate issue and PR if you now want to push the `WebAppContext` temp dir behaviour back down into `ServletContextHandler`s or indeed `ContextHandler`s.  

Let's fix the immediate problem with multipart by making `ScopedContext` honour the javadoc that says it should never return null.

**Comment by joakime** [comment]
> @lorban @joakime please see my comment on the original issue.
> 
> The only change we need to make is to ensure that `ScopedContext` falls back to `java.io.tmpdir` after trying the `Server.getTempDir()`.
> 
> `ServletContextHandler`s in all previous versions of jetty have never had their own, unique temporary directory - that is something we set up for `WebAppContext`s. It's a separate issue and PR if you now want to push the `WebAppContext` temp dir behaviour back down into `ServletContextHandler`s or indeed `ContextHandler`s.
> 
> Let's fix the immediate problem with multipart by making `ScopedContext` honour the javadoc that says it should never return null.

So rollback to commit https://github.com/jetty/jetty.project/pull/11397/commits/f1e7e8d7798fb0458007d1fe2a3ce822c3a30c73 ?

**Comment by janbartel** [comment]
@joakime yes, I guess so.

**Comment by lorban** [comment]
@joakime nudge

**Review by joakime — APPROVED** [review]
