### PR TITLE
Fixes #8913 - Review Jetty XML syntax to allow calling JDK methods

### LINKED ISSUE #8913: Review Jetty XML syntax to allow calling JDK methods
**Jetty version(s)**
10+

**Description**
Jetty XML syntax allow to call methods of any class via reflection.

However, when calling JDK methods, they may return JDK-private implementation classes that are not accessible from Jetty code.
This surfaced in particular while working on #8863, where a new Jetty module for the thread pool that supports virtual threads need to call JDK methods that return JDK-private classes.

For that example, we have:

```xml
<!-- returns JDK private class ThreadBuilders.VirtualThreadBuilder -->
<Call class="java.lang.Thread" name="ofVirtual">
  <!-- Throws IllegalAccessException: class org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration 
cannot access a member of class java.lang.ThreadBuilders$VirtualThreadBuilder (in module java.base) 
with modifiers "public volatile" -->
  <Call name="name">virtual</Call>
</Call>
```

The JDK-private class `ThreadBuilders.VirtualThreadBuilder` is not accessible, but its JDK-public ancestor `Thread.Builder` is.

The proposal is to change slightly the semantic of the `Call` element to support this:

```xml
<!-- static invocation -->
<Call class="java.lang.Thread" name="ofVirtual">
  <!-- virtual invocation -->
  <Call class="java.lang.Thread$Builder" name="name">virtual</Call>
</Call>
```

The second `Call` element specifies the `class` attribute that should be used to reflect the method named `name` but it performs a virtual call, not a static call (because it is in the context of an enclosing `Call` element).

Ambiguities are easily resolved because it's always possible to ask a `Method` if it is `static` and if so perform the invocation passing `null` as the target of the invocation.

### PR DESCRIPTION
**Pull request by sbordet**
Now <Call>, <Get> and <Set> elements can use the "class" attribute to specify the exact class to perform method lookup.

Improved support for <Property>, <SystemProperty> and <Env> so that attribute "name" is now optional (as specified in the DTD), and a "deprecated" attribute may be present instead.
This is necessary to terminally deprecate properties that have no replacement.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java [hunk 1]
```diff
@@ -1765,6 +1767,94 @@ public void testResolvePathInvalidBase()
...
+    public void testVirtualCallWithClassAttribute() throws Exception
+    {
+        // Executors.newSingleThreadScheduledExecutor() returns an
+        // internal class that cannot be accessed, so <Call> must
+        // specify the class to use to lookup the 'shutdown' method.
+        XmlConfiguration configuration = asXmlConfiguration(
+            "<Configure class=\"org.eclipse.jetty.xml.TestConfiguration\">" +
+            "  <Set name=\"Test\">" +
+            "    <Call class=\"java.util.concurrent.Executors\" name=\"newSingleThreadScheduledExecutor\">" +
+            "      <Call class=\"java.util.concurrent.ExecutorService\" name=\"shutdown\" />" +
```
Comment (joakime) [inline jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java:1846]: So the result of this `<Call name="newSingleThreadScheduledExecutor">` is a `ScheduledExecutorService` instance.

The next call, to `shutdown`, should be calling `ScheduledExecutorService.shutdown()` right?

File: jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 2]
```diff
@@ -955,10 +937,6 @@ private Object call(Class<?> oClass, String methodName, Object obj, Args args) t
                 Object[] arguments = args.applyTo(method);
                 if (arguments == null)
                     continue;
-                if (Modifier.isStatic(method.getModifiers()) != (obj == null))
-                    continue;
-                if ((obj == null) && method.getDeclaringClass() != oClass)
-                    continue;
```
Comment (joakime) [inline jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java:961]: Is this what was preventing `testVirtualCallWithClassAttribute` from working?

File: jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 3]
```diff
@@ -1177,27 +1155,39 @@ private Object propertyObj(XmlParser.Node node) throws Exception
         {
             AttrOrElementNode aoeNode = new AttrOrElementNode(node, "Id", "Name", "Deprecated", "Default");
             String id = aoeNode.getString("Id");
-            String name = aoeNode.getString("Name", true);
+            String name = aoeNode.getString("Name", false);
```
Comment (joakime) [inline jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java:1158]: This matches the DTD/XSD now, right?

File: jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java [hunk 4]
```diff
@@ -1177,27 +1155,39 @@ private Object propertyObj(XmlParser.Node node) throws Exception
...
+                    if (d == null)
+                        continue;
+                    String v = properties.get(d.toString());
                     if (v != null)
                     {
                         if (value == null)
-                            LOG.warn("Property '{}' is deprecated, use '{}' instead", d, name);
+                        {
+                            if (name == null)
+                                LOG.warn("Property '{}' is deprecated, do not use it", d);
```
Comment (joakime) [inline jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: s/do not use it/no replacement is available/

File: jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd [hunk 5]
```diff
@@ -286,7 +286,7 @@ System Property Element.
 This element allows JVM System properties to be retrieved as
 part of the value of elements such as Set, Put, Arg, etc.
 The name attribute specifies the property name and the optional
-default argument provides a default value.
+default attribute provides a default value.
```
Comment (joakime) [inline jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd:289]: leave this as argument, as default can be ...

``` xml
<SystemProperty name="Test">
  <Default>value</Default>
</SystemProperty>
```

File: jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd [hunk 6]
```diff
@@ -303,15 +303,14 @@ Environment variable Element.
 This element allows OS Environment variables to be retrieved as
 part of the value of elements such as Set, Put, Arg, etc.
 The name attribute specifies the env variable name and the optional
-default argument provides a default value.
+default attribute provides a default value.
```
Comment (joakime) [inline jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd:306]: Ditto, `<Default>value</Default>` is valid too.

File: jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd [hunk 7]
```diff
@@ -321,7 +320,7 @@ This is equivalent to:
 Property Element.
 This element allows arbitrary properties to be retrieved by name.
 The name attribute specifies the property name and the optional
-default argument provides a default value.
+default attribute provides a default value.
```
Comment (joakime) [inline jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd:323]: Ditto, Argument, not attribute

File: documentation/jetty-documentation/src/main/asciidoc/operations-guide/xml/xml-syntax.adoc [hunk 8]
```diff
@@ -187,12 +189,38 @@ This is equivalent to the following Java code:
 var myhost = InetAddress.getByName("jdk.java.net");
 ----
 
+The `class` attribute can also be used to specify the Java class or interface to use to lookup the non-``static`` method name.
```
Comment (joakime) [inline documentation/jetty-documentation/src/main/asciidoc/operations-guide/xml/xml-syntax.adoc]:
```
The `class` argument ...
```
(it's not always an attribute)

File: documentation/jetty-documentation/src/main/asciidoc/operations-guide/xml/xml-syntax.adoc [hunk 9]
```diff
@@ -187,12 +189,38 @@ This is equivalent to the following Java code:
...
+
+<Configure>
+  <Call class="java.util.concurrent.Executors" name="newSingleThreadScheduledExecutor">
+    #<Call class="java.util.concurrent.ExecutorService" name="shutdown" />#
+  </Call>
+</Configure>
+----
+
+In the example above, `Executors.newSingleThreadScheduledExecutor()` returns an object whose class is a private JDK implementation class.
+Without an explicit `class` attribute, it is not possible to invoke the method `shutdown()` when it is obtained via reflection from the private JDK implementation class, because while the method is `public`, the private JDK implementation class is not, therefore this exception is thrown:
```
Comment (joakime) [inline documentation/jetty-documentation/src/main/asciidoc/operations-guide/xml/xml-syntax.adoc]: Again, `attribute` should be `argument` here.

File: documentation/jetty-documentation/src/main/asciidoc/operations-guide/xml/xml-syntax.adoc [hunk 10]
```diff
@@ -187,12 +189,38 @@ This is equivalent to the following Java code:
...
+
+[source]
+----
+java.lang.IllegalAccessException: class org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration (in module org.eclipse.jetty.xml) cannot access a member of class java.util.concurrent.Executors$DelegatedExecutorService (in module java.base) with modifiers "public"
+----
+
+The solution is to explicitly use the `class` attribute of the `<Call>` element that is invoking the `shutdown()` method, specifying a publicly accessible class or interface that the object in scope extends or implements (in the example above `java.util.concurrent.ExecutorService`).
```
Comment (joakime) [inline documentation/jetty-documentation/src/main/asciidoc/operations-guide/xml/xml-syntax.adoc]: s/attribute/argument/

File: documentation/jetty-documentation/src/main/asciidoc/operations-guide/xml/xml-syntax.adoc [hunk 11]
```diff
@@ -212,6 +240,8 @@ If the JavaBean property is `foo` (or `Foo`), `<Get>` first attempts to invoke _
 </Configure>
 ----
 
+The `class` attribute allows to perform `static` calls, or to lookup the getter method from the specified class, as described in the xref:og-xml-syntax-call[`<Call>` section].
```
Comment (joakime) [inline documentation/jetty-documentation/src/main/asciidoc/operations-guide/xml/xml-syntax.adoc]: s/attribute/argument/

**Review by joakime — CHANGES_REQUESTED** [review]

File: jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java (hunk 1 above)
Comment (sbordet) [reply jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java:1846]: It calls `shutdown()` on the object, so it's going to be a virtual call, not a static call.

It's not calling `ScheduledExecutorService.shutdown()` as that it's an interface method.

It's going to lookup the `shutdown` method in the `ScheduledExecutorService` interface, obtain a `Method` object, and then calling `Method.invoke()` with the object as a target of the virtual call.

File: jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 2 above)
Comment (sbordet) [reply jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java:961]: Not only. There were places where if the `class` attribute was present, then `obj` was nulled out, which also I removed.

File: documentation/jetty-documentation/src/main/asciidoc/operations-guide/xml/xml-syntax.adoc (hunk 8 above)
Comment (sbordet) [reply documentation/jetty-documentation/src/main/asciidoc/operations-guide/xml/xml-syntax.adoc]: Don't like "argument", added  "(or `<Class>` element)" instead.

File: jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 3 above)
Comment (sbordet) [reply jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java:1158]: Yes.

File: jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java (hunk 4 above)
Comment (sbordet) [reply jetty-xml/src/main/java/org/eclipse/jetty/xml/XmlConfiguration.java]: Done.

File: jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd (hunk 5 above)
Comment (sbordet) [reply jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd:289]: "The name attribute ..." so if `name` is an attribute (but can be an element), then also `default` should use the same naming. 
Either they are both "attribute" (and I think it's ok because the first line below enumerate the possible child elements), or we use "attribute/element" everywhere.

File: jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java (hunk 1 above)
Comment (joakime) [reply jetty-xml/src/test/java/org/eclipse/jetty/xml/XmlConfigurationTest.java:1846]: I meant the return type of call ...

``` xml
<Call class="java.util.concurrent.Executors" name="newSingleThreadScheduledExecutor">
```

Is an instance of `java.util.concurrent.ScheduledExecutorService`, which has the `shutdown()` method.
Why is `XmlConfiguration` not using the declared return type? but is instead using the virtual / internal class?

**Review by joakime — APPROVED** [review]
