### PR TITLE
Tweaking DisableUrlCacheTest to identify flaky nature of testcase.

### LINKED ISSUE #11662: `DisableUrlCacheTest.testReloadWebAppWithLog4j2()` is flaky
**Jetty version(s)**
12.0.x

**Jetty Environment**
ee10

**Description**
`org.eclipse.jetty.ee10.tests.distribution.DisableUrlCacheTest.testReloadWebAppWithLog4j2()` sometimes fails with:

```
java.lang.AssertionError: 
Expected: is <200>
     but: was <404>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.ee10.tests.distribution.DisableUrlCacheTest.testReloadWebAppWithLog4j2(DisableUrlCacheTest.java:108)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

See: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-11637/7/tests

### PR DESCRIPTION
**Pull request by joakime**
Fixes: #11662

### CODE REVIEW

File: tests/test-distribution/test-ee10-distribution/src/test/java/org/eclipse/jetty/ee10/tests/distribution/DisableUrlCacheTest.java [hunk 1]
```diff
@@ -38,7 +40,9 @@
 @Isolated
 public class DisableUrlCacheTest extends AbstractJettyHomeTest
 {
-    @Test
+    private static final Logger LOG = LoggerFactory.getLogger(DisableUrlCacheTest.class);
+
+    @RepeatedTest(value = 40, failureThreshold = 1)
```
Comment (olamy) [inline tests/test-distribution/test-ee10-distribution/src/test/java/org/eclipse/jetty/ee10/tests/distribution/DisableUrlCacheTest.java:45]: good one.
we may need this one for other flaky tests?
maybe we do not need here as you fixed it with changing `awaitConsoleLogsFor`

**Review by olamy — APPROVED** [review]

**Review by olamy — APPROVED** [review]

**Comment by gregw** [comment]
Looking at this, it was not a fix... at least no more than adding a sleep(50) would have been.   This PR is still looking for a "starting" event, not a started event.
