### PR TITLE
Fixes #4251 - Http 2.0 clients cannot upgrade protocol in 9.4.22 rele…

### LINKED ISSUE #4251: Http 2.0 clients cannot upgrade protocol in 9.4.22 release
Given:
Java 11 client with HTTP/2.0 protocol set 

When:
Calling jetty server with ```HTTP2CServerConnectionFactory``` 

Expected result:
HTTP 2.0 clients communicates with jetty via HTTP/2.0 protocol

Actual result:
HTTP 2.0 clients communicates with jetty via HTTP/1.1 protocol

Affected version
9.4.22

Investigation:
After change https://github.com/eclipse/jetty.project/commit/22f0cdde29a92cdc3326c07cd41d1c37b47467fd
Settings parser has been broken, more - https://github.com/eclipse/jetty.project/commit/22f0cdde29a92cdc3326c07cd41d1c37b47467fd#r35725542

### PR DESCRIPTION
**Pull request by sbordet**
#4251 
…ase.

Fixed HTTP2-Settings header parsing.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

**Comment by tdanylchuk** [comment]
I'm not familiar that much with the project test structure, if there any place where HTTP 2.0 client calls jetty server? 

Why I'm asking, because we have similar test (which caught the issue), client checks response from server that response http version equals to requrest http version.

**Comment by sbordet** [comment]
@tdanylchuk I'm not sure I understand what you're asking here. We cannot use JDK 11 `HttpClient` since Jetty 9.4.x must support JDK 8.

File: jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/parser/SettingsBodyParser.java [hunk 1]
```diff
@@ -234,7 +239,7 @@ public void onConnectionFailure(int error, String reason)
             }
         });
         if (buffer.hasRemaining())
-            parser.parse(buffer);
+            parser.parse(buffer, 0, buffer.remaining());
```
Comment (gregw) [inline jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/parser/SettingsBodyParser.java]: Why is the `buffer.remaining()`  value here equal to the bodyLength?   what if  you have a partial frame?

Comment (gregw) [reply jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/parser/SettingsBodyParser.java]: Oh I see it is called only  with a synthetic SETTINGs body.    I see how it works, but it's just not obvious from the method/arg/field names.  It needs to be made much clearer that this can only be a full body parsed and there was no header.

Comment (sbordet) [reply jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/parser/SettingsBodyParser.java]: Added javadoc to the method.
