### PR TITLE
Issue #4860 - NPE from HttpFields

### LINKED ISSUE #4860: org.eclipse.jetty.server.HttpChannel busyloop on HttpFields NullPointerException
**Jetty version**

9.4.27

**Java version**

openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10-LTS, mixed mode, sharing)

**OS type/version**

Docker `centos:7` image

**Description**

We are suffering from an unknown issue with a corrupted response `org.eclipse.jetty.http.HttpFields`,  where the `_fields` array appears to contain a `null` value. Previously with jetty 9.4.20 this would result in an error being logged, and the connection was aborted, making it relatively harmless as the request would be retried.

With jetty 9.4.27, the same situation leads to a busyloop in jetty, because the `org.eclipse.jetty.server.HttpChannel` `handle`  -> `Response.resetContent` now fails on the same corrupted `HttpFields`, and keeps failing at a high rate until eventually aborting with an `java.lang.OutOfMemoryError`.

This issue is meant to be about the `org.eclipse.jetty.server.HttpChannel` behavior in 9.4.27 vs 9.4.20, not the actual `HttpFields` corruption itself. I suspect that might be explained by some threading issue (with spring webflux?), but we don't know yet.

Desired behavior would be for jetty to survive the corrupted `HttpFields`, like in older versions.

Initial error:

```
2020-05-08 13:29:29.259|WARN|1|qtp2016038911-26|||org.eclipse.jetty.server.HttpChannel|MAIN||||/api/...
java.lang.NullPointerException: null
	at org.eclipse.jetty.http.HttpFields.put(HttpFields.java:630) ~[jetty-http-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.http.HttpFields.put(HttpFields.java:658) ~[jetty-http-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.server.Response.setHeader(Response.java:592) ~[jetty-server-9.4.27.v20200227.jar!/:9.4.27.v20200227]
```

Busylooping error:

```
2020-05-08 13:29:29.277|WARN|1|qtp2016038911-26|||org.eclipse.jetty.server.HttpChannel|MAIN||||/api/...
java.lang.NullPointerException: null
	at org.eclipse.jetty.server.Response.resetContent(Response.java:1128) ~[jetty-server-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:435) ~[jetty-server-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) ~[jetty-server-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[jetty-io-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) ~[jetty-io-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[jetty-util-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[jetty-util-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[jetty-util-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) ~[jetty-util-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) ~[jetty-util-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) ~[jetty-util-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) ~[jetty-util-9.4.27.v20200227.jar!/:9.4.27.v20200227]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

First 1k of logs attached, the rest is just the same repeating. There's a custom springboot exception handler and spring SSE handler involved.

[20200508-jetty-httpfields-npe-busyloop.txt](https://github.com/eclipse/jetty.project/files/4600175/20200508-jetty-httpfields-npe-busyloop.txt)

### PR DESCRIPTION
**Pull request by gregw**
Fix handling of null fields in `HttpFields` for #4860 :
 + Added paranoid catch in `HttpChannel` so even if fix doesn't work we won't loop forever.
 + Fixed bug in iterator with nextIndex
 + Do not allow null fields to be set with list iterator
 + improved test coverage

### CODE REVIEW

**Comment by gregw** [comment]
@sbordet and @lachlan-roberts I think this issue/fix could relate to our previous discussions about if httpFields.add(null) should be a noop or throw.   If this problem is indeed caused by springboot doing a `httpFields.listIterator().next().set(null)`, then we do have users that are expecting the noop.... but then we are breaking the api in 10...

**Review by joakime — COMMENTED** [review]
I generally like what I'm seeing.

Just wondering if we need to beef up the javadoc / apidoc for this class too?

**Comment by gregw** [comment]
@joakime This class is substantially rewritten in 10, so I think javadoc effort should go there.   Will be interesting to take new tests to 10 as well.

I'm still not 100% convinced this is the actual problem, but can't see another way for a null to get in the array.

**Comment by joakime** [comment]
The OP did say this was during a SSE behavior, so there could be access to the response object after the connection is closed / recycled, no?

**Comment by joakime** [comment]
@gregw the updated testing and changes to HttpFields for null name has been committed to this branch.

File: jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java [hunk 1]
```diff
@@ -710,15 +749,15 @@ public void testPreventNullField()
         assertThat(fields.size(), is(1));
         ListIterator<HttpField> iter = fields.listIterator();
         iter.next();
-        iter.set(null);
+        iter.set(null); // set field to null - null entry in list now
```
Comment (gregw) [inline jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java]: @joakime This comment is wrong.  Setting null used to put in a null entry, but now is a noop.

**Comment by gregw** [comment]
@sbordet Should we change code like:
```
_fields[_size++] = field;
```
to
```
_fields[_size] = field;
_size++;
```

This class is not required to be Thread safe, but doing the updates in that order (and the reverse for deletion) might help avoid NPEs if bad apps are concurrently mutating.... or is the jit just going to reorder anyway, so no point?

File: jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java [hunk 2]
```diff
@@ -40,7 +40,7 @@ public HttpField(HttpHeader header, String name, String value)
         if (_header != null && name == null)
             _name = _header.asString();
         else
-            _name = Objects.requireNonNull(name);
+            _name = Objects.requireNonNull(name, "name");
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/HttpField.java:43]: Since you bothered adding a message to the NPE, make it "header name cannot be null", or at least "header name", as "name" alone is just too laconic to be useful.

File: jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 3]
```diff
@@ -671,6 +676,8 @@ public void put(HttpHeader header, HttpHeaderValue value)
      */
     public void put(HttpHeader header, String value)
     {
+        Objects.requireNonNull(header, "header");
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: "header cannot be null".

File: jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 4]
```diff
@@ -685,7 +692,12 @@ public void put(HttpHeader header, String value)
      */
     public void put(String name, List<String> list)
     {
+        Objects.requireNonNull(name, "name");
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: "name cannot be null"

File: jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 5]
```diff
@@ -723,6 +736,8 @@ public void add(HttpHeader header, HttpHeaderValue value)
      */
     public void add(HttpHeader header, String value)
     {
+        Objects.requireNonNull(header, "header");
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: "header cannot be null"

File: jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 6]
```diff
@@ -723,6 +736,8 @@ public void add(HttpHeader header, HttpHeaderValue value)
...
+
         if (value == null)
             throw new IllegalArgumentException("null value");
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:743]: We are no-op all the other cases, most notably `add(String, String)` above, so why throw here?

File: jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 7]
```diff
@@ -1199,16 +1217,22 @@ public void set(HttpField field)
...
         public void add(HttpField field)
         {
-            _fields = Arrays.copyOf(_fields, _fields.length + 1);
-            System.arraycopy(_fields, _cursor, _fields, _cursor + 1, _size++);
-            _fields[_cursor++] = field;
-            _current = -1;
+            if (field != null)
+            {
+                _fields = Arrays.copyOf(_fields, _fields.length + 1);
+                System.arraycopy(_fields, _cursor, _fields, _cursor + 1, _size++);
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Should not the last parameter be `_size++ - _cursor`?
And yes, I would rather separate the `++` and `--` to different lines so that they are more comprehensible.
For example, it takes too much brain power to know if `5++ - 3` is `2` or `3`.

We have tests that call `add(HttpField)` but the error in the copy does not show because the array is initialized to 16 elements but in the tests _size is only 4-5.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 6 above)
Comment (gregw) [reply jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:743]: Because it will have servlet API impacts.  There is a separate issue that I thought you and and @lachlan-roberts  were working on to normalise the API in 10 to either always noop or always ISE (I can't remember which).  Either way, I don't want to change behaviour in this PR other than to avoid noops and later NPEs (eg from null names or null fields).

File: jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 7 above)
Comment (gregw) [reply jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Yep it's a bug and if I change the capacity to 5 in the test I get a failure... but I don't see that it is the bug we are looking for :(

**Review by sbordet — APPROVED** [review]
