### PR TITLE
Fixes #12488 - HTTP/2 headers may not be split in CONTINUATION frames.

### LINKED ISSUE #12488: HTTP/2 headers may not be split in CONTINUATION frames
**Jetty version(s)**
12.0.x

**Description**
HTTP/2 headers generation invokes the `HpackEncoder` with a `ByteBuffer` that is sized to the `maxFrameSize`.
This is incorrect for those cases where `maxHeaderListSize > maxFrameSize`.

### PR DESCRIPTION
**Pull request by sbordet**
* Removed unnecessary and wrong initialization of Parser and Generator properties, as they are initialized by SETTINGS frames (or they have default values already).
* Fixed headers generation, taking into account maxHeaderListSize and maxFrameSize correctly.

### CODE REVIEW

**Review by lorban — CHANGES_REQUESTED** [review]
There's a broken proxy test that seems directly related to this change.

File: jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackEncoder.java [hunk 1]
```diff
@@ -107,6 +107,7 @@ public HpackEncoder()
         _debug = LOG.isDebugEnabled();
         setMaxTableCapacity(HpackContext.DEFAULT_MAX_TABLE_CAPACITY);
         setTableCapacity(HpackContext.DEFAULT_MAX_TABLE_CAPACITY);
+        setMaxHeaderListSize(4096);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-hpack/src/main/java/org/eclipse/jetty/http2/hpack/HpackEncoder.java]: Shouldn't that be a constant?

**Review by lorban — DISMISSED** [review]
Just one nit.

**Review by lorban — APPROVED** [review]
