### PR TITLE
Issue #13592 ClosedFileSystemException for jar:file base resource

### LINKED ISSUE #13592: ClosedFileSystemException when upgrading to 12.1.1
**Jetty version(s)**
12.1.1

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
21 & 24

**OS type/version**
ubuntu 22.04 & 24.04

**Description**
Tests are failing with the following error when upgrading to 12.1.1

```
java.nio.file.ClosedFileSystemException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1799)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:504)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.readAttributesIfExists(ZipPath.java:831)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.readAttributesIfExists(ZipFileSystemProvider.java:300)
	at java.base/java.nio.file.Files.isDirectory(Files.java:2113)
	at org.eclipse.jetty.util.resource.PathResource.isDirectory(PathResource.java:310)
	at org.eclipse.jetty.util.resource.Resources.isDirectory(Resources.java:66)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.setBaseResource(WebAppContext.java:244)
	at org.eclipse.jetty.ee10.webapp.WebInfConfiguration.deconfigure(WebInfConfiguration.java:91)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.stopContext(WebAppContext.java:1401)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStop(ServletContextHandler.java:1099)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:181)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:203)
	at org.eclipse.jetty.server.Handler$Abstract.doStop(Handler.java:553)
	at org.eclipse.jetty.server.handler.ContextHandler.lambda$doStop$1(ContextHandler.java:913)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1582)
	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:913)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:181)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:203)
	at org.eclipse.jetty.server.Handler$Abstract.doStop(Handler.java:553)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:181)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:203)
	at org.eclipse.jetty.server.Handler$Abstract.doStop(Handler.java:553)
	at org.eclipse.jetty.server.Server.doStop(Server.java:699)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
	at de.rwth.idsg.steve.JettyServer.stop(JettyServer.java:188)
	at de.rwth.idsg.steve.Application.stop(Application.java:93)
	at de.rwth.idsg.steve.ApplicationTest.destroy(ApplicationTest.java:67)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
```

https://github.com/juherr/evolve/actions/runs/17713433605

Deprecated `GZipHandler` is used in the project here: https://github.com/juherr/evolve/blob/f94ed4d7e6538a21d2e110b132fa19e32a8ef405/steve/src/main/java/de/rwth/idsg/steve/SteveAppContext.java#L101 but it fails too when using the new `CompressionHandler` https://github.com/juherr/evolve/pull/103

**How to reproduce?**

Run Github Actions workflow.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #13592

When `setBaseResourceAsString(String)` or `setBaseResourceAsPath(Path)` are called, the context needs to convert the reference into a `Resource`.  Currently the context uses a `ResourceFactory` linked to its lifecycle to do this conversion. Consequently, when the context is stopped, the `Resource` is closed, which in the case of a `jar:file` `Resource` results in the closing of the associated `ZipFileSystem`.  This causes a problem during `stop` because we reset the base resource to its original value (see `WebInfConfiguration.deconfigure()`)  which now refers to a closed `ZipFileSystem`.

For more details on the exact exception, see the OP.

This PR introduces a `ResourceFactory` that is not bound to the lifecycle of a context, and is used by methods that produce `Resources` before the context starts (ie `setBaseResourceAsString(String)` and `setBaseResourceAsPath(Path)`).  The `ResourceFactory` is closed (and thus its resources also closed) only when `context.destroy()` is called. Therefore, over a stop/start the `Resource` reference remains valid.

### CODE REVIEW

File: jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java [hunk 1]
```diff
@@ -673,6 +674,36 @@ protected void service(HttpServletRequest request, HttpServletResponse response)
         }
     }
 
+    @Test
```
Comment (lorban) [inline jetty-ee10/jetty-ee10-webapp/src/test/java/org/eclipse/jetty/ee10/webapp/WebAppContextTest.java:677]: Looks like this test should be replicated in ee9 and ee11.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 2]
```diff
@@ -1125,6 +1133,8 @@ public boolean checkVirtualHost(Request request)
     @Override
     public void destroy()
     {
+        //get rid of any resources that were created before this context was started
+        _nonLifeCycleResourceFactory.close();
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java:1137]: Now `Server.destroy()` needs to be called when a base resource that needs mounting is used otherwise that mount is leaked.

Is the documentation already clear about having to call `destroy()`?

**Review by lorban — CHANGES_REQUESTED** [review]
LGTM in essence, only a couple of minor changes need attention.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java:1137]: I think `Server.destroy()` is only called from `ShutdownThread`, which is only hooked if `Server.stopAtShutdown=true`, which is not the default.
So yes, I think we are going to leak.

This feels like just an ordering issue, where the `ResourceFactory` is added as a bean very late, and so upon stop is stopped very early.

If we call `ResourceFactory.of(this)` very early (e.g. constructor), then it will be stopped very late, and `deconfigure()` should run without problems.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by gregw** [comment]
@lorban @sbordet The problem we need to resolve with this PR is the following code should work:
```java
        Server server = new Server();
        ContextHandler contextHandler = new ContextHandler();
        contextHandler.setBaseResourceAsString("jar:file:///some/path/myapp.jar!/");
        assert contextHandler.getBaseResource().exists();
        server.setHandler(contextHandler);

        server.start();
        server.stop();
        server.start();
        server.stop();
```

It does with this PR because the resource is mounted in the setBRAS and thus the assert passes and the second restart works.

If we unmount anywhere in stop, then then restart will not work.

If we delay mounting until start, then the assert will fail.

This does leak if destroy is not called, but that is why we have destroy.   If you are not calling destroy, then you are probably exiting the JVM and a leak doesn't matter.

So I think we just need to be a bit better about calling destroy ourselves.  I.E. our deployer should destroy contexts as it undeploys them.  @janbartel do you want me to add that to this PR?

**Comment by gregw** [comment]
@janbartel I've done it... will push

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java:1137]: I've added a call to destroy from the DeploymentScanner

Comment (janbartel) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java:1137]: @sbordet difficult to see how this could be achieved as you suggest. Bear in mind that the stopping sequence of a `WebAppContext` is very particular in order to achieve correct servlet spec behaviour. The contained beans of the context will all always be stopped _before_ any of the `Configuration.deconfigure` methods are called.

The sequence is:

``` 
     WAC doStop
     SCH doStop
     WAC   stopContext
           stopWebApp
     SCH     stopContext
     CH        doStop
     H           doStop
     CLC           doStop
                     reverse stop all beans
     CH          cleanupAfterStop
     WAC   call all Configuration.deconfigure
```

**Review by gregw — APPROVED** [review]

**Review by lorban — APPROVED** [review]

**Review by sbordet — APPROVED** [review]
