### PR TITLE
Issue #5368 - ensure onMessage exits before next frame is read

### LINKED ISSUE #5368: WebSocket text event execute in same thread as running binary event and destroy Threadlocal
**Jetty version**: 9.4.31

**Java version**: 11.09 but also with 8.0.x

**OS type/version**: any

**Description**

If the WebSocket MessageHandler is registered as:

```
public void onOpen( Session session, EndpointConfig config ) {
  session.addMessageHandler( new MessageHandler.Whole<InputStream>() {
    public void onMessage( InputStream message ) {
    ...
    }
  }
}
```
then is can occur that inside `message.read()` in the same thread a text message will be processed. In this case two MessageHandler are share the same thread local variables. On security reasons our MessageHandlers destroy all ThreadLocal variables on finish for the current thread. The result for the first binary MessageHandler is that there is no current user scope after some `message.read()`.

This has work in version 9.4.20. It is a regression in a micro version or fatal behavior change. We was not able to find a documentation that forbids Threadlocal with WebSocket events handling. We expected that an intermediate event will process in another thread or later.

A workaround is to switch to `MessageHandler.Whole<byte[]>`. Then there is no `message.read()` call anymore. But it sounds fewer effective.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Issue #5368**
When reading a websocket message with a `Reader` or `InputStream` ensure that the `onMessage()` method has exited before resuming to read and parse websocket frames. Otherwise a call to the `MessageInputStream.read()` or` MessageInputStream.close()` could parse the next websocket frame which could trigger a second nested call to `onMessage()` in the same thread.

### CODE REVIEW

**Comment by joakime** [comment]
Relying on exit/return from the `onMessage()` only with this PR?
We need to tread carefully here.  Past experience shows this can be problematic.

Example:

We get a TEXT Message as  series of frames.
It contains a JSON message, along with more text after the JSON message (it could be whitespace, it could be garbage, it doesn't matter what it is for this example, just that it exists, and is non-trivial in number of frames/size).
The implementation issues a `onMessage(InputStream)` and the application uses an old school JSON library that just reads/parses up to the close of the JSON message.
The application thinks it's done and exits the `onMessage(InputStream)`
There's now more unread / unparsed frames on that message, but no application reading them.
Is this a discard moment?  I don't know.
Quietly discarding data seems like a bad approach.
We need to be NOISY in logs if this occurs (eg: onMessage is exited, but the InputStream isn't at EOF, and the InputStream gets more data, we should log at WARN level each and every frame the application is not reading.  Let them implement their onMessage properly to get rid of the noise)
Or we should be extra-harsh in this scenario and terminate the connection with an onError() indicating that the onMessage() triggered an EarlyEof scenario.

**Comment by lachlan-roberts** [comment]
@joakime we do need to pay attention to the exit for the `onMessage()`, that is the only way to ensure we don't call it twice. But we are not relying on them fully consuming all the data from the websocket message. Currently we will just discard any remaining content and any new frames left of the websocket message if they exit early or close the `InputStream`. So if they decide they don't want to process the rest of the message for whatever reason they can just return or close the  `InputStream`.

I'm not opposed to putting a warning if we end up discarding content, but I feel like it would be excessive to warn once per frame, once per message seems fine. But I don't think its a good idea to be extra-harsh and terminate the connection. This could be a breaking change for people relying on the discard behavior.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/events/JettyAnnotatedEventDriver.java [hunk 1]
```diff
@@ -115,11 +114,11 @@ else if (events.onBinary.isStreaming())
                     }
                     catch (Throwable t)
                     {
-                        // dispatched calls need to be reported
                         session.close(t);
+                        return;
```
Comment (joakime) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/events/JettyAnnotatedEventDriver.java:118]: Wouldn't this return leave a `MessageInputStream` laying around in a different thread?

File: jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/endpoints/JsrEndpointEventDriver.java [hunk 2]
```diff
@@ -209,9 +209,10 @@ else if (wrapper.wantsStreams())
                     catch (Throwable t)
                     {
                         session.close(t);
+                        return;
```
Comment (joakime) [inline jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/endpoints/JsrEndpointEventDriver.java:212]: Wouldn't this return leave a MessageReader laying around in a different thread?

File: jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/endpoints/JsrAnnotatedEventDriver.java [hunk 3]
```diff
@@ -343,9 +338,10 @@ public void onTextFrame(ByteBuffer buffer, boolean fin) throws IOException
                     catch (Throwable e)
                     {
                         session.close(e);
+                        return;
```
Comment (joakime) [inline jetty-websocket/javax-websocket-client-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/endpoints/JsrAnnotatedEventDriver.java:341]: This return seem out of place. shouldn't we at least close/fail the MessageReader too?

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/events/JettyAnnotatedEventDriver.java [hunk 4]
```diff
@@ -262,22 +261,21 @@ public void onTextFrame(ByteBuffer buffer, boolean fin) throws IOException
...
                     try
                     {
-                        events.onText.call(websocket, session, msg);
+                        events.onText.call(websocket, session, reader);
                     }
                     catch (Throwable t)
                     {
-                        // dispatched calls need to be reported
                         session.close(t);
+                        return;
```
Comment (joakime) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/events/JettyAnnotatedEventDriver.java:275]: Ditto, we need to cleanup/close/fail the MessageReader before we return.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java [hunk 5]
```diff
@@ -521,7 +521,7 @@ public void resume()
     {
         ByteBuffer resume = readState.resume();
         if (resume != null)
-            onFillable(resume);
+            getExecutor().execute(() -> onFillable(resume));
```
Comment (joakime) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java:524]: Uhm, we dispatch now for onFillable?
Always?
This seems to be a mistake.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java [hunk 6]
```diff
@@ -209,10 +231,14 @@ public int read() throws IOException
                 }
             }
 
-            int result = activeBuffer.get() & 0xFF;
+            ByteBuffer buffer = BufferUtil.toBuffer(b, off, len);
```
Comment (joakime) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java:238]: do we want a new `ByteBuffer copy(byte[], int, int)` method for this as well?

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java [hunk 7]
```diff
@@ -221,6 +247,11 @@ public int read() throws IOException
                         case CLOSED:
                             return -1;
 
+                        case COMPLETE:
+                            // If we are complete we have read the last frame but
+                            // don't want to resume reading until onMessage() exits.
```
Comment (joakime) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java:256]: What?  I don't understand this comment.

So the application is using `InputStream.read(byte[], int, int)`, and the state is COMPLETE, meaning there's no more frames to read, why are we returning "written" and not -1?

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java [hunk 8]
```diff
@@ -130,47 +145,53 @@ public void close()
...
+        byte[] bytes = new byte[1];
+        while (true)
+        {
+            int read = read(bytes, 0, 1);
+            if (read < 0)
+                return -1;
+            if (read == 0)
+                continue;
+
+            return bytes[0] & 0xFF;
```
Comment (joakime) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java:193]: We loop infinitely on COMPLETE?
If so, I'm not liking this solution.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java [hunk 9]
```diff
@@ -55,6 +55,7 @@
     {
         RESUMED,
         SUSPENDED,
+        COMPLETE,
```
Comment (joakime) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java:69]: You don't explain why we have a new COMPLETE state, and how it's different then the others.
Eg: what is the different between COMPLETE vs CLOSED?

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java (hunk 8 above)
Comment (joakime) [reply jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java:193]: If the message is complete, that should offer the last frame with FIN=true and then an EOF in the buffer queue.
Why do we have a new state?

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java [hunk 10]
```diff
@@ -105,11 +94,14 @@ public void appendFrame(ByteBuffer framePayload, boolean fin) throws IOException
                         state = State.SUSPENDED;
                         break;
 
-                    case SUSPENDED:
+                    default:
                         throw new IllegalStateException();
```
Comment (joakime) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java]: Perhaps we should detail why this state is illegal in the throwable message?

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java [hunk 11]
```diff
@@ -105,11 +94,14 @@ public void appendFrame(ByteBuffer framePayload, boolean fin) throws IOException
...
                 }
 
-                buffers.put(copy);
+                // Put the payload into the queue, by copying it.
+                // Copying is necessary because the payload will
+                // be processed after this method returns.
+                buffers.put(copy(framePayload));
```
Comment (joakime) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java]: We should probably be paying attention to the `fin` parameter on this `appendMessage(ByteBuffer, boolean)` and add the EOF sentinel to the buffers if it's set to true.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java [hunk 12]
```diff
@@ -121,7 +113,30 @@ public void appendFrame(ByteBuffer framePayload, boolean fin) throws IOException
...
+                LOG.warn("MessageInputStream closed without fully consuming content");
+
+            state = State.CLOSED;
+            buffers.clear();
+            buffers.add(EOF);
+        }
+    }
+
+    @Override
+    public void messageComplete()
```
Comment (joakime) [inline jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java]: I don't like this method concept.
We already have the "boolean fin" on the `appendMessage`, why are we not using it?

**Review by joakime — CHANGES_REQUESTED** [review]
I have questions / concerns...

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/events/JettyAnnotatedEventDriver.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/events/JettyAnnotatedEventDriver.java:118]: Not sure what you mean here, this is in the same thread the `MessageInputStream` is being read from. So `onMessage` will have thrown so now we need to close the `Session`. 

If we don't return and call `handlerComplete()`, this will try to resume reading more frames but we have already closed the session. We could close the `MessageInputStream` before returning but this will not have a major effect as no one is reading from it.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java (hunk 5 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/io/AbstractWebSocketConnection.java:524]: We only dispatch for `onFillable()` when resuming. This is so if we get a control frame in the middle of the message eg `PONG`, we don't call the pong `MessageHandler` from within the same thread that is processing the `MessageHandler<InputStream>`. 

The demand in jetty 10 is similar, there is always a call to `getExecutor().execute(this);` when demanding another frame.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java (hunk 8 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java:193]: The state `COMPLETE` means that we have all the content of the message and have appended an EOF buffer in the queue after that. We need this state so we don't resume reading new frames after the `fin==true` and to enforce that no new frames are appended after the `fin==true`.

We will not loop infinitely on COMPLETE, we will read `-1` when we run out of content to read.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java (hunk 9 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java:69]: It might be be possible to remove `COMPELTE` now that `close()` does not call resume.
Although it is still useful to enforce no new frames are appended after `fin=true`.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java (hunk 12 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java]: I don't know, this concept already existed I didn't create it. Seems a bit redundant, but this is the reason we don't use the boolean `fin` in `appendFrame`.

I think its better to move this logic into the `appendFrame` method to get the state change done in the same synchronized block.

File: jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java (hunk 7 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/message/MessageInputStream.java:256]: `COMPLETE` means it has all the content up to `EOF`.
`CLOSED` means all the content has been read up to `EOF` or `close()` has been called. (we will return -1 in `CLOSED` state).

I will add better comments to explain the difference.

**Review by joakime — APPROVED** [review]
Once the CI build is green, go ahead and merge.
