### PR TITLE
Issue #13768 - Sanitizing HTTP/1.x Header Name and Value better

### LINKED ISSUE #13768: Sanitizing of HTTP headers names and values should remove NUL bytes (U+0000)
**Jetty version(s)**
All

**Jetty Environment**
Core

**HTTP version**
HTTP 1.1

**Java version/vendor**
openjdk 21.0.7 2025-04-15 LTS
OpenJDK Runtime Environment Temurin-21.0.7+6 (build 21.0.7+6-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.7+6 (build 21.0.7+6-LTS, mixed mode, sharing)

**OS type/version**
Linux Pop!_OS 22.04

**Description**
The methods `HttpGenerator.putSanitisedName(String, ByteBuffer)` and `HttpGenerator.putSanitisedValue(String, ByteBuffer)` do not check for NUL (U+0000) characters, but this character causes issues in many downstream systems. For example:

**Firefox**: NS_ERROR_DOM_INVALID_HEADER_VALUE when header value contains U+0000

https://github.com/mozilla-firefox/firefox/blob/644f0db17749554fe23a45b43e77e61f42acdfd9/netwerk/protocol/http/nsHttpResponseHead.cpp#L473

**Firefox**: a bit more lenient when U+0000 is in header name, as request is allowed through but the header is removed (this happens for all control characters in header names)

https://github.com/mozilla-firefox/firefox/blob/main/netwerk/protocol/http/nsHttpHeaderArray.cpp#L381

https://github.com/mozilla-firefox/firefox/blob/644f0db17749554fe23a45b43e77e61f42acdfd9/netwerk/protocol/http/nsHttp.cpp#L174

**Chrome**: ERR_INVALID_HTTP_RESPONSE when header name or value contains U+0000

https://github.com/chromium/chromium/blob/main/net/http/http_response_headers.cc#L349

**nginx**: NGX_HTTP_PARSE_INVALID_HEADER when header value contains U+0000

https://github.com/nginx/nginx/blob/78d1ab5a2c00839a36ff6bac661d9785fce3c1a4/src/http/ngx_http_parse.c#L1009

**nginx**: stricter for header names (all control characters blacklisted)

https://github.com/nginx/nginx/blob/78d1ab5a2c00839a36ff6bac661d9785fce3c1a4/src/http/ngx_http_parse.c#L962

**How to reproduce?**

Send header names and values containing U+0000 in HTTP responses.

### PR DESCRIPTION
**Pull request by joakime**
+ Excluding all CTRL (except HTAB) from allowed characters in `HttpGenerator.putSanitisedName` `HttpGenerator.putSanitisedValue`
+ Changing replacement character for the above two sanitization methods to fit into RFC9110 rules
+ Adding unit test.

Closes #13768

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java [hunk 1]
```diff
@@ -1011,8 +1012,9 @@ private static void putSanitisedValue(String s, ByteBuffer buffer)
         {
             char c = s.charAt(i);
 
-            if (c > 0xff || c == '\r' || c == '\n')
-                buffer.put((byte)' ');
+            // Do not allow 8-bit, or CTRL (except HTAB)
+            if (c > 0xff || (c >= 0x00 && c <= 0x1F && c != '\t'))
+                buffer.put((byte)' '); // replacement char has to satisfy RFC9110 Field Value ABNF.
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java:1017]: Space seams like a poor choice, but let's not change for now.
Again feels like a compliance mode that would allow a hard fail here would be good.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java [hunk 2]
```diff
@@ -997,8 +997,9 @@ private static void putSanitisedName(String s, ByteBuffer buffer)
         {
             char c = s.charAt(i);
 
-            if (c > 0xff || c == '\r' || c == '\n' || c == ':')
-                buffer.put((byte)'?');
+            // Do not allow 8-bit, colon (:), or CTRL (except HTAB)
+            if (c > 0xff || c == ':' || (c >= 0x00 && c <= 0x1F && c != '\t'))
+                buffer.put((byte)'.'); // replacement char has to satisfy RFC9110 Field Name ABNF (aka Token).
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java:1002]: Maybe we need a compliance mode to allow a hard fail here

**Review by gregw — DISMISSED** [review]
I think this is a good fix for now.... but feels like we should be stricter in future

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java (hunk 2 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java:1002]: I'll try that in a followup PR.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpGenerator.java:1017]: We could just drop the character, ignore it.
