### PR TITLE
Issue #4697 ServletContext sessionModes methods should throw UnsupportedOperationException

### LINKED ISSUE #4697: Default and EffectiveSessionTrackingModes should throw UnsupportedOperationException
**jetty 10.0**

According to the Servlet Spec, ServletContext.getDefaultSessionTrackingModes and ServletContext.getEffectiveSessionTrackingModes should throw an UnsupportedOperationException if they are called from ServletContextListener.contextInitialized() for a ServletContextListener that was programmatically added.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #4697 

A ServletContextListener that has been added programmatically should obtain an UnsupportedOperationException when calling ServletContext.getDefaultSessionTrackingModes, ServletContext.getEffectiveSessionTrackingModes and ServletContext.setSessionTrackingModes.

### CODE REVIEW

File: jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java [hunk 1]
```diff
@@ -191,6 +222,42 @@ public void contextInitialized(ServletContextEvent sce)
             assertNull(sce.getServletContext().getAttribute("MyContextListener.contextInitialized"));
             sce.getServletContext().setAttribute("MyContextListener.contextInitialized", Boolean.TRUE);
             
+            assertNull(sce.getServletContext().getAttribute("MyContextListener.defaultSessionTrackingModes"));
+            try
+            {
+                sce.getServletContext().getDefaultSessionTrackingModes();
+                sce.getServletContext().setAttribute("MyContextListener.defaultSessionTrackingModes", Boolean.FALSE);
+            }
+            catch (UnsupportedOperationException e)
```
Comment (olamy) [inline jetty-servlet/src/test/java/org/eclipse/jetty/servlet/ServletContextHandlerTest.java:231]: why not using `assertThrows`?

**Review by olamy — APPROVED** [review]

**Review by olamy — APPROVED** [review]
