### PR TITLE
Issue #4415 - Addressing Gzip Decoding of large files

### LINKED ISSUE #4415: GzipHandler invalid input zip size on large (over 2,147,483,647 bytes) request body content
**Jetty version**
9.4.24.v20191120

**Java version**
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)

**OS type/version**
macOS Catalina
version 10.15.1

**Description**
`GZipHandler` will fail to inflate streams that are over `4GB`, the error originate in `GZipContentDecoder`

```java
...
                    case ISIZE:
                    {
                        _value += (currByte & 0xFF) << 8 * _size;
                        ++_size;
                        if (_size == 4)
                        {
                            if (_value != _inflater.getBytesWritten())
                                throw new ZipException("Invalid input size");
...
```

**How to replicate** 
Setup Jetty with `GZipHandler` and specify `setInflateBufferSize` so Jetty will try and inflate your request.

Create dummy data: 
```bash
dd if=/dev/urandom of=too_big.xml bs=1048576 count=4097
```

```bash
curl -X POST -H "Content-Encoding: gzip" -T too_big.xml.gz "http://localhost:port/"
```
Will throw: `java.util.zip.ZipException: Invalid input size`

**Possible solutions**
Don't validate the size if a certain amount of bytes have been written OR cast `_inflater.getBytesWritten()` to int

### PR DESCRIPTION
**Pull request by joakime**
+ Now applying proper RFC 1952 ISIZE check.
+ Bit shifting is done with Longs against Long value.

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

Closes #4415

### CODE REVIEW

File: jetty-http/src/main/java/org/eclipse/jetty/http/GZIPContentDecoder.java [hunk 1]
```diff
@@ -37,13 +37,16 @@
  */
 public class GZIPContentDecoder implements Destroyable
 {
+    // Unsigned Integer Max == 2^32
+    private static final long UINT_MAX = 0xffffffffL;
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/GZIPContentDecoder.java]: Please use upper case for hex "digits": `0xFFFFFFFFL`.

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java [hunk 2]
```diff
@@ -351,4 +358,97 @@ public void testBigBlockWithExtraBytes() throws Exception
         assertTrue(buffer.hasRemaining());
         assertEquals(data2, StandardCharsets.UTF_8.decode(buffer).toString());
     }
+
+    // Signed Integer Max
+    final long INT_MAX = Integer.MAX_VALUE;
+
+    // Unsigned Integer Max == 2^32
+    final long UINT_MAX = 0xffffffffL;
```
Comment (sbordet) [inline jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java]: Please use upper case hex "digits".

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java [hunk 3]
```diff
@@ -351,4 +358,97 @@ public void testBigBlockWithExtraBytes() throws Exception
...
+
+        @Override
+        public void write(byte[] b, int off, int len) throws IOException
+        {
+            ByteBuffer buf = ByteBuffer.wrap(b, off, len);
+            decode(buf);
+        }
+
+        @Override
+        public void write(byte[] b) throws IOException
```
Comment (sbordet) [inline jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java]: Don't override this method, base class already calls `write(byte[], int, int)`.

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java [hunk 4]
```diff
@@ -351,4 +358,97 @@ public void testBigBlockWithExtraBytes() throws Exception
...
+        }
+
+        @Override
+        public void write(int b) throws IOException
+        {
+            ByteBuffer buf = BufferUtil.allocate(32);
+            buf.put((byte)(b & 0xFF));
+            buf.flip();
+            decode(buf);
+        }
```
Comment (sbordet) [inline jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java]: Let's just delegate this also: `write(new byte[]{b})`.

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java [hunk 5]
```diff
@@ -351,4 +358,97 @@ public void testBigBlockWithExtraBytes() throws Exception
...
+                int len = buf.length;
+                if (bytesLeft < buf.length)
+                {
+                    len = (int)bytesLeft;
+                }
+                outputStream.write(buf, 0, len);
+                bytesLeft -= len;
+                writtenBytes += len;
+            }
+            outputStream.close();
```
Comment (sbordet) [inline jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java]: No need to `close()` when using try-with-resources. Move the `assert`s out.

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java [hunk 6]
```diff
@@ -351,4 +358,97 @@ public void testBigBlockWithExtraBytes() throws Exception
...
+
+    @ParameterizedTest
+    @ValueSource(longs = {INT_MAX, INT_MAX + 1, UINT_MAX, UINT_MAX + 1})
+    public void testLargeGzipStream(long origSize) throws IOException
+    {
+        final int BUFSIZE = (1 * 1024 * 1024); // 1MB
+
+        // Create a buffer to use over and over again to produce the uncompressed input
+        byte[] cbuf = "0123456789ABCDEFGHIJKLMOPQRSTUVWXYZ".getBytes(StandardCharsets.UTF_8);
+        byte[] buf = new byte[BUFSIZE];
```
Comment (sbordet) [inline jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java:376]: I don't think you need `buf` at all. 
Write `cbuf` many times, up to `origSize`, and you have the same data and much less code.

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java [hunk 7]
```diff
@@ -351,4 +358,97 @@ public void testBigBlockWithExtraBytes() throws Exception
...
+            System.arraycopy(cbuf, 0, buf, off, len);
+            off += len;
+        }
+
+        GZIPContentDecoder decoder = new GZIPContentDecoder(BUFSIZE);
+
+        try (GZIPDecoderOutputStream out = new GZIPDecoderOutputStream(decoder);
+             GZIPOutputStream outputStream = new GZIPOutputStream(out, BUFSIZE))
+        {
+            long writtenBytes = 0L;
```
Comment (sbordet) [inline jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java]: `writtenBytes` is the same as `origSize`, so you can drop it.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-http/src/main/java/org/eclipse/jetty/http/GZIPContentDecoder.java (hunk 1 above)
Comment (joakime) [reply jetty-http/src/main/java/org/eclipse/jetty/http/GZIPContentDecoder.java]: Done

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java (hunk 2 above)
Comment (joakime) [reply jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java]: Done

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java (hunk 6 above)
Comment (joakime) [reply jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java:376]: and a *REALLY SLOW* test.
I did that originally, and the test for Integer.MAX_VALUE took nearly 2 minutes.
But in this way it takes only 18 seconds.

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java (hunk 7 above)
Comment (joakime) [reply jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java]: `writtenBytes` tracks the write (pre-encode) side.
`out.decodedByteCount` tracks the read (post-decode) side.

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java (hunk 6 above)
Comment (sbordet) [reply jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java:376]: Wow, so what if you make it 16 MiB? Is it any faster?

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java (hunk 7 above)
Comment (sbordet) [reply jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java]: When `writtenBytes` is used, it will have the same value as `origSize` so it's unnecessary.

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java (hunk 6 above)
Comment (joakime) [reply jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java:376]: I tried that.
I can't get it to run faster with a greater than 1MB buffer.
I suspect I switched from being slowed down by the buffer size to being slowed down just due to the gzip encoding itself.

File: jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java (hunk 7 above)
Comment (joakime) [reply jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java]: I reworked that section.
See updated code.

Comment (joakime) [reply jetty-http/src/test/java/org/eclipse/jetty/http/GZIPContentDecoderTest.java]: Removed writtenBytes.

**Review by sbordet — APPROVED** [review]
