### PR TITLE
Fix Request.isSecure() when proxy offloads TLS and then sends PROXY-V2 information to the backend

### LINKED ISSUE #14134: Improve detection of secure requests for HTTP/1
**Jetty version(s)**
12.1.x

**HTTP version**
HTTP/1.1

**Description**
`HttpConnection.HttpStreamOverHTTP1.headerComplete()` tries to detect whether a request is secure via `instanceof SslEndPoint`.

However, this does not work when HAProxy offloads TLS and then sends PROXY-V2 information to the backend.

The correct way is more likely `endPoint.getSslSessionData() != null`.

### PR DESCRIPTION
**Pull request by lorban**
Fixes https://github.com/jetty/jetty.project/issues/14134

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java [hunk 1]
```diff
@@ -689,7 +689,7 @@ private void parseBodyAndUpgrade() throws IOException
                         }
                     }
 
-                    proxyEndPoint = new ProxyEndPoint(endPoint, local, remote, tlvs, client == 0 ? null : EndPoint.SslSessionData.from(null, null, sslCipher, null));
+                    proxyEndPoint = new ProxyEndPoint(endPoint, local, remote, tlvs, (client & PP2_CLIENT_SSL) == 0 ? null : EndPoint.SslSessionData.from(null, null, sslCipher, null));
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java]: I think this should be reverted, because `client == 2` or `client == 4` also mean that the connection was secured.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/ProxyProtocolClientConnectionFactory.java [hunk 2]
```diff
@@ -394,6 +447,11 @@ public enum Protocol
 
             public static class TLV
             {
+                public static final int TYPE_SSL = 0x20;
+                public static final int CLIENT_SSL = 0x01;
+                public static final int SUBTYPE_SSL_VERSION = 0x21;
+                public static final int SUBTYPE_SSL_CIPHER = 0x23;
```
Comment (lorban) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/ProxyProtocolClientConnectionFactory.java]: Those constants are already declared in `ProxyV2ConnectionFactory` although private. If we have to duplicate them, I'd very much prefer that the duplication is in test code.

I'm also not fond of the fact that those constant names don't exactly match the ones defined in the spec (all the same but with the `PP2_` prefix).

File: jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientProxyProtocolTest.java [hunk 3]
```diff
@@ -154,7 +157,37 @@ public boolean handle(Request request, Response response, Callback callback)
...
+                assertEquals(clientPort, Request.getRemotePort(request));
+                callback.succeeded();
+                return true;
+            }
+        });
+        startClient();
+
+        List<V2.Tag.TLV> tlvs = List.of();
+        if (secure)
+            tlvs = List.of(new V2.Tag.TLV(V2.Tag.TLV.TYPE_SSL, new byte[]{V2.Tag.TLV.CLIENT_SSL}));
```
Comment (lorban) [inline jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/HttpClientProxyProtocolTest.java]: My version used to test both 1 (`PP2_CLIENT_SSL`) and 2 (`PP2_CLIENT_CERT_CONN`) as the PROXY protocol specification chapter 2.2.6 (The PP2_TYPE_SSL type and subtypes) states that the client connected over SSL/TLS only when PP2_CLIENT_SSL (bit 0) is 1.

**Review by sbordet — APPROVED** [review]
