### PR TITLE
Don't create circular throwables and don't throw StackOverflowError if one gets logged

### LINKED ISSUE #11792: StdErrAppender should detect exception circular references
**Jetty version(s)**
12+

**Description**
`StdErrAppender.appendCause()` should detect when exceptions have circular references, to avoid `StackOverflowError`.

See for example how `Throwable.lockedPrintStackTrace()` does it.

Furthermore, `AsyncContextEvent.addThrowable()` should use `ExceptionUtil.addSuppressedIfNotAssociated()` to avoid possible circular references.

### PR DESCRIPTION
**Pull request by lorban**
Fixes #11792

### CODE REVIEW

File: jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java [hunk 1]
```diff
@@ -175,7 +177,7 @@ private void format(StringBuilder builder, JettyLogger logger, Level level, long
             }
             else
             {
-                appendCause(builder, cause, "");
+                appendCause(builder, new HashSet<>(), cause, "");
```
Comment (sbordet) [inline jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: I would use, like the JDK, an identity-based set here.

File: jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java [hunk 2]
```diff
@@ -199,9 +201,16 @@ private String renderedLevel(Level level)
         }
     }
 
-    private void appendCause(StringBuilder builder, Throwable cause, String indent)
+    private void appendCause(StringBuilder builder, Set<Throwable> visited, Throwable cause, String indent)
     {
         builder.append(EOL).append(indent);
+        if (visited.contains(cause))
+        {
+            builder.append("[CIRCULAR REFERENCE: ").append(cause.getClass().getName()).append("]");
```
Comment (sbordet) [inline jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Like the JDK, I would append here the whole exception, so call `appendEscaped(builder, cause.toString)` instead of just the class name.

File: jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java [hunk 3]
```diff
@@ -199,9 +201,16 @@ private String renderedLevel(Level level)
         }
     }
 
-    private void appendCause(StringBuilder builder, Throwable cause, String indent)
+    private void appendCause(StringBuilder builder, Set<Throwable> visited, Throwable cause, String indent)
```
Comment (sbordet) [inline jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: I'd move the Set as the last parameter.

File: jetty-core/jetty-slf4j-impl/src/test/java/org/eclipse/jetty/logging/StdErrAppenderTest.java [hunk 4]
```diff
@@ -20,6 +20,27 @@
...
+
+        // Build an exception with circular refs.
+        IllegalArgumentException commonCause = new IllegalArgumentException();
+        Throwable thrown = new Throwable(commonCause);
+        RuntimeException suppressed = new RuntimeException(thrown);
+        thrown.addSuppressed(suppressed);
+
+        appender.emit(logger, Level.INFO, System.currentTimeMillis(), "tname", thrown, "the message");
+
+        output.assertContains("[CIRCULAR REFERENCE: java.lang.Throwable]");
```
Comment (sbordet) [inline jetty-core/jetty-slf4j-impl/src/test/java/org/eclipse/jetty/logging/StdErrAppenderTest.java]: Just test for `CIRCULAR REFERENCE`, as the rest is likely to change.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Done.

File: jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Done.

File: jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Done.

File: jetty-core/jetty-slf4j-impl/src/test/java/org/eclipse/jetty/logging/StdErrAppenderTest.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-slf4j-impl/src/test/java/org/eclipse/jetty/logging/StdErrAppenderTest.java]: Done.

File: jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java [hunk 5]
```diff
@@ -199,9 +202,16 @@ private String renderedLevel(Level level)
         }
     }
 
-    private void appendCause(StringBuilder builder, Throwable cause, String indent)
+    private void appendCause(StringBuilder builder, Throwable cause, String indent, Set<Throwable> visited)
     {
         builder.append(EOL).append(indent);
+        if (visited.contains(cause))
+        {
+            builder.append("[CIRCULAR REFERENCE: ").append(cause).append("]");
```
Comment (sbordet) [inline jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: `append(cause)` appends a naked `cause.toString()`, which in other places is sanitized by calling `appendEscaped()`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Changed.

**Review by sbordet — APPROVED** [review]
