### PR TITLE
Jetty 9.4.x 5844 start download npe

### LINKED ISSUE #5844: --download flag to jetty-start causes NullPointerException
**Jetty version**
9.4.35

**Java version**
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

**OS type/version**
ubuntu-18.04

**Description**

> $ java -jar ${JETTY_HOME}/start.jar --download=https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar\|lib/ext/h2-1.4.200.jar
java.lang.NullPointerException
	at org.eclipse.jetty.start.StartArgs.addFile(StartArgs.java:248)
	at org.eclipse.jetty.start.StartArgs.parse(StartArgs.java:1133)
	at org.eclipse.jetty.start.StartArgs.parse(StartArgs.java:1044)
	at org.eclipse.jetty.start.Main.processCommandLine(Main.java:293)
	at org.eclipse.jetty.start.Main.main(Main.java:75)

looking at [line 1133](https://github.com/eclipse/jetty.project/blob/bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java#L1133) it passes `null` as the first argument to `addFile`:
````
        if (arg.startsWith("--download="))
        {
            addFile(null, Props.getValue(arg));
````
which in turn immediately tries to call some method on it on [line 248](https://github.com/eclipse/jetty.project/blob/bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb/jetty-start/src/main/java/org/eclipse/jetty/start/StartArgs.java#L248):
````
    private void addFile(Module module, String uriLocation)
    {
        if (module.isSkipFilesValidation())
````
so it would be strange if it didn't result in a NullPointerException  ;-)

### PR DESCRIPTION
**Pull request by sbordet**
Fixes #5844

### CODE REVIEW

File: jetty-start/src/test/java/org/eclipse/jetty/start/MainTest.java [hunk 1]
```diff
@@ -146,13 +146,11 @@ public void testWithCommandLine() throws Exception
...
-        lib.append(extraJar.toString());
-        lib.append(File.pathSeparator);
-        lib.append(extraDir.toString());
-
-        cmdLineArgs.add(lib.toString());
+        String lib = "--lib=" +
+            extraJar.toString() +
+            File.pathSeparator +
+            extraDir.toString();
+        cmdLineArgs.add(lib);
```
Comment (gregw) [inline jetty-start/src/test/java/org/eclipse/jetty/start/MainTest.java]: Avoid even the remote possibility of a NPE with
```suggestion
        String lib = "--lib=" + extraJar + File.pathSeparator + extraDir;
        cmdLineArgs.add(lib);
```

**Review by gregw — APPROVED** [review]
LGTM other than a really minor niggle
