### PR TITLE
Fix `HttpFields.Mutable.Wrapper.computeField()`

### LINKED ISSUE #11687: `HttpFields$Mutable$Wrapper.computeField()` incorrectly calls `onAddField()` when null is returned by `computeFn`
**Jetty version(s)**
12.0.8

**Jetty Environment**
ee10

**Description**

The `HttpFields$Mutable.computeField()` contract explicitly specifies that if the `computeFn` returns null, this means the field should be removed. Unfortunately, the default implementation of `computeField()` calls `put()` which incorrectly calls `Wrapper.onAddField()` with a null value.

When the protocol is HTTP 1.0, `ResponseUtils.ensureNotPersistent()` uses `computeField()` to remove the connection header, so that triggers the following exception:

```
java.lang.IllegalStateException: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.http.HttpField.getHeader()" because "field" is null
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.onError(ServletChannelState.java:874)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handleException(ServletChannel.java:667)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:584)
	at org.eclipse.jetty.ee10.servlet.AsyncContentProducer.lambda$isReady$0(AsyncContentProducer.java:260)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1298)
	at org.eclipse.jetty.server.handler.ContextRequest$OnContextDemand.run(ContextRequest.java:74)
	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	at org.eclipse.jetty.server.internal.HttpConnection$DemandContentCallback.succeeded(HttpConnection.java:679)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.MonitoredQueuedThreadPool$1.run(MonitoredQueuedThreadPool.java:73)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.http.HttpField.getHeader()" because "field" is null
	at org.eclipse.jetty.ee10.servlet.ServletContextResponse$HttpFieldsWrapper.onAddField(ServletContextResponse.java:567)
	at org.eclipse.jetty.http.HttpFields$Mutable$Wrapper.put(HttpFields.java:1678)
	at org.eclipse.jetty.http.HttpFields$Mutable.computeField(HttpFields.java:1372)
	at org.eclipse.jetty.server.ResponseUtils.ensureNotPersistent(ResponseUtils.java:40)
	at org.eclipse.jetty.server.ResponseUtils.ensureConsumeAvailableOrNotPersistent(ResponseUtils.java:31)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:554)
	... 17 more
```

### PR DESCRIPTION
**Pull request by lorban**
Make `HttpFields.Mutable.Wrapper.computeField()` call `onRemoveField()` and remove the field when null is returned by `computeFn`.

Also add a bunch of null checks.

Fixes #11687

### CODE REVIEW

**Comment by sbordet** [comment]
@lorban this PR breaks a test that should pass.

**Comment by lorban** [comment]
@sbordet noticed, and fixed - thanks!

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 1]
```diff
@@ -1369,7 +1385,9 @@ default Mutable put(String name, long value)
          */
         default Mutable computeField(HttpHeader header, BiFunction<HttpHeader, List<HttpField>, HttpField> computeFn)
         {
-            return put(computeFn.apply(header, stream().filter(f -> f.getHeader() == header).collect(Collectors.toList())));
+            Objects.requireNonNull(header);
+            HttpField result = computeFn.apply(header, stream().filter(f -> f.getHeader() == header).collect(Collectors.toList()));
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Just `toList()` reads a little better.

**Review by sbordet — DISMISSED** [review]
LGTM.
Up to you if you want to fix the `toList()` niggle.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: You're right so I cleaned that up.

**Review by sbordet — APPROVED** [review]

**Review by joakime — APPROVED** [review]

**Comment by lorban** [comment]
@gregw your opinion on this PR would be welcome.

**Review by gregw — APPROVED** [review]
