### PR TITLE
fixed #10513 ContentSourceInputStream close with available

### LINKED ISSUE #10513: Lockup processing POST request body with Jetty 12.0.1 using http/2
**Jetty version(s)**
12.0.1

**Jetty Environment**
ee10 / http/2

**Java version/vendor** `(use: java -version)`
OpenJDK Runtime Environment (Red_Hat-21.0.0.0.35-1.rolling.fc38) (build 21+35)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.0.0.35-1.rolling.fc38) (build 21+35, mixed mode, sharing)

**OS type/version**
Fedora 38 Workstation

**Description**
This application sets up an embedded Jetty 12.0.1 instance with one servlet class TestServlet1. The doPost method simply tries to read-and-discard the content of the body before sending a short response.
Posting a sufficiently large file to the application will result in a lockup. The curl client will block trying to send more data while the application blocks trying to read. The point where th size of the POST body is printed to stderr is then never reached.

A slight modification of the code makes it use TestServlet2 with a doPost that processes the input expecting a ZIP-formatted body by reading and discarding entries and printing the name:size of each entry to stderr. Posting a sufficiently large ZIP file to it shows that initial entries are processed corrrectly then it locks up the same way as with TestServlet1.

Small POST requests seem to work without issues. GET requests seem to work fine also and our application ported from Jetty 11 to Jetty 12 works mostly fine except for large POST requests.

**How to reproduce?**
See the above description. I am sorry that this is Scala code instead of Java. I currently have no Java development environment setup.

#### Compile/runtime dependencies specified in build.sbt, some of which redundant for the test code

```
libraryDependencies += "org.eclipse.jetty" % "jetty-core" % "12.0.1"
libraryDependencies += "org.eclipse.jetty" % "jetty-io" % "12.0.1"
libraryDependencies += "org.eclipse.jetty" % "jetty-server" % "12.0.1"
libraryDependencies += "org.eclipse.jetty" % "jetty-alpn-server" % "12.0.1"
libraryDependencies += "org.eclipse.jetty" % "jetty-session" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.ee10" % "jetty-ee10-servlet" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.websocket" % "jetty-websocket-jetty-api" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.websocket" % "jetty-websocket-jetty-server" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.ee10.websocket" % "jetty-ee10-websocket-jetty-server" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.http2" % "jetty-http2-server" % "12.0.1"
libraryDependencies += "org.eclipse.jetty.http3" % "jetty-http3-server" % "12.0.1"
```

#### Scala code

``` scala
package nl.idfix.util.test

import java.io._
import java.util.zip._

import jakarta.servlet._
import jakarta.servlet.http._

import org.eclipse.jetty.alpn._
import org.eclipse.jetty.alpn.server._
import org.eclipse.jetty.http2._
import org.eclipse.jetty.http2.server._
import org.eclipse.jetty.http3._
import org.eclipse.jetty.http3.server._
import org.eclipse.jetty.util.resource._
import org.eclipse.jetty.security._
import org.eclipse.jetty.server._
import org.eclipse.jetty.server.handler.{ ContextHandler, ResourceHandler, DefaultHandler, ContextHandlerCollection }
import org.eclipse.jetty.ee10.servlet._
import org.eclipse.jetty.session.{ DefaultSessionIdManager, HouseKeeper }
import org.eclipse.jetty.util.security._
import org.eclipse.jetty.util.ssl._
import org.eclipse.jetty.util.thread._
import org.eclipse.jetty.server._
import org.eclipse.jetty.websocket.api._
import org.eclipse.jetty.ee10.websocket.server._
import org.eclipse.jetty.ee10.websocket.server.config._
import org.eclipse.jetty.http.HttpFields

class NullOutputStream extends OutputStream
{
	def write(byte : Int) = ()
	override def write(buff : Array[Byte]) = ()
	override def write(buff : Array[Byte],start : Int,count : Int) = ()
}

class CountingOutputStream(wrapped : OutputStream) extends OutputStream
{
	private var written : Long = 0
	
	def bytesWritten = written
	
	def write(byte : Int)
	{
		wrapped.write(byte)
		written += 1
	}
	
	override def write(buffer : Array[Byte],offset : Int,bytes : Int)
	{
		wrapped.write(buffer,offset,bytes)
		written += bytes
	}
	
	override def write(buffer : Array[Byte])
	{
		wrapped.write(buffer)
		written += buffer.length
	}
	
	override def flush = wrapped.flush
	override def close = wrapped.close
}

class TestServlet1 extends HttpServlet
{
	override def doPost(request : HttpServletRequest,response : HttpServletResponse)
	{
		val in = request.getInputStream
		val out = new CountingOutputStream(new NullOutputStream)
		in.transferTo(out)
		in.close
		out.close
		System.err.println("BYTE COUNT:" + out.bytesWritten)
		response.setHeader("Content-Type","text/plain")
		val writer = response.getWriter
		writer.println("Thank you")
		writer.close
	}
}

class TestServlet2 extends HttpServlet
{
	override def doPost(request : HttpServletRequest,response : HttpServletResponse)
	{
		val in = request.getInputStream
		val zip = new ZipInputStream(in)

		var entry = zip.getNextEntry
		while (entry != null)
		{
			val out = new CountingOutputStream(new NullOutputStream)
			zip.transferTo(out)
			out.close
			System.err.println(entry.getName + ":" + out.bytesWritten)
			entry = zip.getNextEntry
		}
		zip.close
		val writer = response.getWriter
		writer.println("Thank you")
		writer.close
	}
}

object JettyTest
{
	def main(args: Array[String])
	{
		val pool = new QueuedThreadPool
		val server = new Server(pool)

		/* Create connector */
		val keyStore = "abc.jks"
		val keyPassword = "secret"
		val sslContextFactory = new SslContextFactory.Server
		sslContextFactory.setEndpointIdentificationAlgorithm("HTTPS")
		sslContextFactory.setKeyStorePath(keyStore)
		sslContextFactory.setKeyStorePassword(keyPassword)
		sslContextFactory.setKeyManagerPassword(keyPassword)
		sslContextFactory.setKeyStoreType("JKS")
		val httpsConfig = new HttpConfiguration
		httpsConfig.setSecureScheme("https")
		httpsConfig.setSecurePort(8443)
		val http1 = new HttpConnectionFactory(httpsConfig)
		val http2 = new HTTP2ServerConnectionFactory(httpsConfig)
		val alpn = new ALPNServerConnectionFactory
		alpn.setDefaultProtocol(http1.getProtocol)
		val ssl = new SslConnectionFactory(sslContextFactory,alpn.getProtocol)
		val http2Connector = new ServerConnector(server,ssl,alpn,http2,http1)
		http2Connector.setHost("0.0.0.0")
		http2Connector.setPort(8443)
		http2Connector.setIdleTimeout(1800000L)
		server.addConnector(http2Connector)

		/* Create Servlet context */

		val servletContext = new ServletContextHandler
		servletContext.setContextPath("/")
		val holder = new ServletHolder(classOf[TestServlet1])
		servletContext.addServlet(holder,"/*")

		/* Setup server */
		val ctxHandler = new ContextHandlerCollection
		ctxHandler.setHandlers(servletContext)

		server.setHandler(ctxHandler)
		server.start
		server.join
	}
}
```

### PR DESCRIPTION
**Pull request by gregw**
address close issue discovered in  #10513 ContentSourceInputStream close by making it consume available content whilst seeking EOF

### CODE REVIEW

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceInputStream.java [hunk 1]
```diff
@@ -100,23 +100,32 @@ public int available() throws IOException
...
-            // if the chunk was a last chunk (but not an instanceof EOF), then nothing more to do
-            if (chunk.isLast())
+            // If we have a chunk here, then it needs to be released
+            if (chunk != null)
+            {
+                chunk.release();
+
+                // if the chunk was a last chunk (but not an instanceof EOF), then nothing more to do
+                if (chunk.isLast())
+                    return;
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceInputStream.java]: You should do `chunk = Chunk.next(chunk)` before returning to avoid keeping a ref to a last chunk whose buffer has been released.

**Review by lorban — CHANGES_REQUESTED** [review]

**Comment by ghost** [comment]
I do not expect this to fix #10513 because that is not related to failing to consuming available content. Quite the opposite, the problem there is that the handling code is blocked trying to consume the content.

Please correct me if I'm wrong on this.

**Review by sbordet — CHANGES_REQUESTED** [review]
Same comment as @lorban about using `Chunk.next()`.

**Comment by gregw** [comment]
@silviobierman perhaps this PR will not fix #10513, as I really can't see what here would affect a http2 only stall.    However, it is some wrongness discovered during investigation of that issue, so should be fixed; should not hurt.   I'll update the discription.

To help with 10513, we need to see some thread dumps of the stall.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceInputStream.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceInputStream.java]: done

**Review by lorban — APPROVED** [review]

**Review by sbordet — CHANGES_REQUESTED** [review]
I'm not sure about this change.

If I have a 4 GiB file as input, and the code processing that file throws in a try-with-resources, the implicit `close()` is now reading 4 GiB before terminating.

As this is a generic class, we should not assume it's wrapping the `Request` and hence the semantic of `consumeAvailable()` should be done in `close()`.

I agree it's surprising and annoying to have to consume the input until EOF in the application, but this change may possibly hurt more than it's trying to fix.

**Comment by gregw** [comment]
@sbordet @lorban I have a pushed an alternate version that:
 + will always fail the source if any content is skipped by the close - even if that has already been read and not yet consumed.
 + will attempt only 1 read looking for a real EOF or failure (but will fail if there is more content - even if it is the last content).
 + uses Chunk.next in read to handle failures

I think with these changes we are more consistent with regards to how content and EOF are decomposed into chunks:
 + If there is any left over content (1 byte or 4GB) we will fail. 
 + If there is an EOF available after all the consumed content, we will see it.

The implementation is a bit long, but I thought explicitly unrolling the loop of 1 was clearest.

**Review by lorban — APPROVED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceInputStream.java [hunk 2]
```diff
@@ -98,23 +98,49 @@ public int available() throws IOException
...
+            // If we read a chunk
+            if (chunk != null)
+            {
+                // Handle a failure as read would
+                if (Content.Chunk.isFailure(chunk))
+                {
+                    Content.Chunk c = chunk;
+                    chunk = Content.Chunk.next(c);
+                    throw IO.rethrow(c.getFailure());
+                }
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceInputStream.java:131]: I would not do this, as this is a close() and I don't want an exception in my face if I can't read -- it's a quasi-normal behavior if the other side has already closed as well.
I'd just store the failure (in case of weird extra reads) and return.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by sbordet** [comment]
@gregw I think we should strive for the following: upon close(), if there is a terminal "Transfer-Encoding: chunked" chunk, or zip terminal bytes, or extra newline after JSON, we try to read one chunk only, and if last=true, or an empty last=true chunk, then we silently close with Chunk.EOF.

If there is no chunk we record the failure, if there is a chunk last=false we record the failure.

**Review by sbordet — APPROVED** [review]
