### PR TITLE
Issue #13007 - implement websocket frame and message timeout APIs for 12.1

### LINKED ISSUE #13007: How to Reproduce FrameFlusher Write Timeout in Jetty WebSocket
**Jetty Version** 12.0.19

**Jetty Environment**

ee10
**Java Version** 21

**Question**

We observed the following log in our production environment:

```
25-04-11 23:44:28.642 WARN [jetty.server.scheduler-2 FrameFlusher.timeoutExpired:380] 
FrameFlusher write timeout on entry: Entry{TEXT@5098e21c[len=185,fin=true,rsv=000,m=null]
HeapByteBuffer@5e5f167f[p=0,l=185,c=185,r=185]={<<<{event:CHART,data:{...827320159954665473]]}}>>>},
Flusher@5a60896c[PENDING],false}
```

We are currently analyzing the cause of this log and are trying to reproduce or simulate the same scenario using the Jetty WebSocket client.  

To simulate a blocked receiving scenario, we added a 5-second `sleep` inside the client's `onMessage` method for each received message. However, this did not reproduce the issue.  

We have set the `FrameFlusher`'s idle timeout to 6 seconds.  
Could you advise how we might reliably reproduce this scenario?

Alternatively, could you help explain what conditions might lead to this kind of log being reported, so we can better investigate on our side?

We would like to understand under what circumstances a FrameFlusher.timeoutExpired warning like this could be triggered — whether it is due to a slow client, write buffer saturation, thread starvation, or something else — in order to guide our troubleshooting efforts more effectively.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Issue #13007

- remove deprecated websocket write timeout methods
- implement message timeout in FrameFlusher
- add sendFrame method on CoreSession which takes an OutgoingFrame instance which also contains the message and frame timeout configuration
- use this new API to do message timeout from the Jakarta WS implementations

### CODE REVIEW

**Comment by gregw** [comment]
@lachlan-roberts conflicts!

**Comment by lachlan-roberts** [comment]
@gregw resolved

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
+// ========================================================================
+//
+
+package org.eclipse.jetty.websocket.core;
+
+import org.eclipse.jetty.util.Callback;
+import org.eclipse.jetty.util.TypeUtil;
+
+public class OutgoingEntry
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java:25]: javadocs.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+    private final long frameTimeout;
+    private final long messageTimeout;
+
+    public OutgoingEntry(Frame frame, Callback callback, boolean batch)
+    {
+        this.frame = frame;
+        this.callback = callback;
+        this.batch = batch;
+        this.frameTimeout = -1;
+        this.messageTimeout = -1;
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java]: Chain this constructor to the other, or better remove it, since there is a builder.
Also, constructors should be `private` if there is a builder.
Or remove the builder, as the constructor seems enough to me?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java [hunk 3]
```diff
@@ -0,0 +1,130 @@
...
+
+    public static class Builder
+    {
+        private Frame _frame;
+        private Callback _callback;
+        private boolean _batch;
+        private long _frameTimeout;
+        private long _messageTimeout;
+
+        public Builder(OutgoingEntry outgoingEntry)
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java:93]: Missing empty `Builder()` constructor? How would I build an `OutgoingEntry` without having one already?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/ExtensionStack.java [hunk 4]
```diff
@@ -242,13 +242,13 @@ public void negotiate(List<ExtensionConfig> offeredConfigs, List<ExtensionConfig
...
     @Override
-    public void sendFrame(Frame frame, Callback callback, boolean batch)
+    public void sendFrame(OutgoingEntry entry)
     {
         if (outgoing == null)
             throw new IllegalStateException();
         if (LOG.isDebugEnabled())
-            LOG.debug("Extending out {} {} {}", frame, callback, batch);
-        outgoing.sendFrame(frame, callback, batch);
+            LOG.debug("Extending out {} {} {}", entry.getFrame(), entry.getCallback(), entry.isBatch());
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/ExtensionStack.java]:
```suggestion
            LOG.debug("Extending out {}", entry);
```

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java [hunk 5]
```diff
@@ -0,0 +1,130 @@
...
+        this.callback = callback;
+        this.batch = batch;
+        this.frameTimeout = -1;
+        this.messageTimeout = -1;
+    }
+
+    public OutgoingEntry(Frame frame, Callback callback, boolean batch, long frameTimeout, long messageTimeout)
+    {
+        this.frame = frame;
+        this.callback = callback;
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java]: Both should have `Objects.requireNonNull()`.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingFrames.java [hunk 6]
```diff
@@ -33,5 +33,15 @@ public interface OutgoingFrames
...
+    {
+        sendFrame(new OutgoingEntry(frame, callback, batch));
+    }
+
+    /**
+     * Send an {@link OutgoingEntry} containing a {@link Frame} and {@link Callback}.
+     *
+     * @param entry the frame to eventually write to the network layer.
+     */
+    void sendFrame(OutgoingEntry entry);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingFrames.java:46]: It's a breaking change anyway, so I'd just modify the signature and keep only one method.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/AbstractExtension.java [hunk 7]
```diff
@@ -146,11 +146,11 @@ protected void nextIncomingFrame(Frame frame, Callback callback)
         this.nextIncoming.onFrame(frame, callback);
     }
 
-    protected void nextOutgoingFrame(Frame frame, Callback callback, boolean batch)
+    protected void nextOutgoingFrame(OutgoingEntry entry)
     {
         if (log.isDebugEnabled())
-            log.debug("nextOutgoingFrame({})", frame);
-        this.nextOutgoing.sendFrame(frame, callback, batch);
+            log.debug("nextOutgoingFrame({})", entry.getFrame());
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/AbstractExtension.java]:
```suggestion
            log.debug("nextOutgoingFrame({})", entry);
```

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java [hunk 8]
```diff
@@ -522,11 +507,16 @@ public void sendFrame(Frame frame, Callback callback, boolean batch)
                     () -> closeConnection(sessionState.getCloseStatus(), c),
                     t -> closeConnection(sessionState.getCloseStatus(), Callback.from(c, t)));
 
-                flusher.sendFrame(frame, closeConnectionCallback, false);
+                flusher.sendFrame(new OutgoingEntry.Builder(entry)
+                    .callback(closeConnectionCallback)
+                    .batch(batch)
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java]: Remove, as `batch` did not change.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java [hunk 9]
```diff
@@ -808,7 +798,12 @@ public Flusher(Configuration configuration)
         @Override
         protected void forwardFrame(Frame frame, Callback callback, boolean batch)
         {
-            negotiated.getExtensions().sendFrame(frame, callback, batch);
+            OutgoingEntry currentEntry = new OutgoingEntry.Builder(getCurrentEntry())
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java:800]: This feels weird; why do we have to call `getCurrentEntry()` here, as it was not done before.

This is where we go from incoming frames to outgoing frames, so we build one `OutgoingEntry` from the incoming pieces, so I would expect to only use the parameters.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/FragmentExtension.java [hunk 10]
```diff
@@ -46,7 +47,12 @@ public FragmentExtension()
             @Override
             protected void forwardFrame(Frame frame, Callback callback, boolean batch)
             {
-                nextOutgoingFrame(frame, callback, batch);
+                OutgoingEntry entry = new OutgoingEntry.Builder(getCurrentEntry())
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/FragmentExtension.java:50]: Ditto re `getCurrentEntry()`.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java [hunk 11]
```diff
@@ -267,20 +268,23 @@ private class OutgoingFlusher extends TransformingFlusher
...
         private Frame _frame;
-        private boolean _batch;
 
         @Override
         protected boolean onFrame(Frame frame, Callback callback, boolean batch)
         {
             if (frame.isControlFrame())
             {
-                nextOutgoingFrame(frame, callback, batch);
+                OutgoingEntry entry = new OutgoingEntry.Builder(getCurrentEntry())
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java:277]: Ditto re `getCurrentEntry()`.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java [hunk 12]
```diff
@@ -364,7 +368,11 @@ else if (_frame.isFin())
             chunk.setPayload(payload);
             chunk.setFin(_frame.isFin() && finished);
 
-            nextOutgoingFrame(chunk, callback, _batch);
+            OutgoingEntry entry = new OutgoingEntry.Builder(getCurrentEntry())
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/internal/PerMessageDeflateExtension.java:371]: Ditto re `getCurrentEntry()`.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/FragmentingFlusher.java [hunk 13]
```diff
@@ -45,20 +43,19 @@ public FragmentingFlusher(Configuration configuration)
     @Override
     protected boolean onFrame(Frame frame, Callback callback, boolean batch)
     {
+        payload = frame.getPayload().slice();
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/FragmentingFlusher.java]: Why you need to slice here?
If it's not fragmented, it is unnecessary, no?

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/TransformingFlusher.java [hunk 14]
```diff
@@ -32,16 +33,22 @@
...
 
     private final AutoLock lock = new AutoLock();
-    private final Queue<FrameEntry> entries = new ArrayDeque<>();
+    private final Queue<OutgoingEntry> entries = new ArrayDeque<>();
     private final IteratingCallback flusher = new Flusher();
     private boolean finished = true;
     private Throwable failure;
+    private OutgoingEntry current;
+
+    public OutgoingEntry getCurrentEntry()
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/TransformingFlusher.java:48]: Not sure about this, because this flusher received `OutgoingEntry`, but then unwraps them to call `onFrame()`.
Perhaps it is better to change the signature of `onFrame()` to take an `OutgoingEntry` too, rather than the exploded components.

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/CapturedHexPayloads.java [hunk 15]
```diff
@@ -17,20 +17,19 @@
...
 
     @Override
-    public void sendFrame(Frame frame, Callback callback, boolean batch)
+    public void sendFrame(OutgoingEntry entry)
     {
-        String hexPayload = Hex.asHex(frame.getPayload());
+        String hexPayload = Hex.asHex(entry.getFrame().getPayload());
         captured.add(hexPayload);
-        if (callback != null)
+        if (entry.getCallback() != null)
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/CapturedHexPayloads.java]: It should be always guaranteed that the callback is not null, no need for this check.
For testing reasons, if the callback is null, it can be normalized to `Callback.NOOP` or equivalent.

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/OutgoingFramesCapture.java [hunk 16]
```diff
@@ -62,8 +62,10 @@ public int getFrameCount(byte op)
     }
 
     @Override
-    public void sendFrame(Frame frame, Callback callback, boolean batch)
+    public void sendFrame(OutgoingEntry entry)
     {
+        Frame frame = entry.getFrame();
+        Callback callback = entry.getCallback();
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/OutgoingFramesCapture.java:68]: Below, `callback` always non-null.

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/OutgoingNetworkBytesCapture.java [hunk 17]
```diff
@@ -55,8 +55,10 @@ public List<ByteBuffer> getCaptured()
     }
 
     @Override
-    public void sendFrame(Frame frame, Callback callback, boolean batch)
+    public void sendFrame(OutgoingEntry entry)
     {
+        Frame frame = entry.getFrame();
+        Callback callback = entry.getCallback();
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/OutgoingNetworkBytesCapture.java:61]: Below, `callback` always non-null.

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java [hunk 18]
```diff
@@ -0,0 +1,175 @@
...
+
+import static org.hamcrest.CoreMatchers.containsString;
+import static org.hamcrest.CoreMatchers.instanceOf;
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.junit.jupiter.api.Assertions.assertThrows;
+import static org.junit.jupiter.api.Assertions.assertTrue;
+
+public class WriteTimeoutTest
+{
+    private static final CountDownLatch MESSAGE_LATCH = new CountDownLatch(1);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java]: Don't use `static`s.
Store the `CountDownLatch` in `ServerSocket`, and store `ServerSocket` as a normal field in `start()`.

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java [hunk 19]
```diff
@@ -0,0 +1,175 @@
...
+        {
+        }
+    }
+
+    private Server server;
+    private WebSocketCoreClient client;
+    private ServerConnector connector;
+
+    @BeforeEach
+    public void start() throws Exception
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java]: Better if `start()` takes the server-side endpoint as a parameter, since it is different for each of the 2 tests.

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java [hunk 20]
```diff
@@ -0,0 +1,175 @@
...
+        client = new WebSocketCoreClient();
+        client.getHttpClient().setIdleTimeout(-1);
+        client.start();
+        server.start();
+    }
+
+    @AfterEach
+    public void stop() throws Exception
+    {
+        client.stop();
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java]: Use `LifeCycle.stop(client)`.

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java [hunk 21]
```diff
@@ -0,0 +1,175 @@
...
+        // Send the first frame of the message with a 1-second timeout.
+        try (Blocker.Callback callback = Blocker.callback())
+        {
+            Frame frame = new Frame(OpCode.TEXT, false, "hello");
+            session.sendFrame(new OutgoingEntry(frame, callback, false, -1, 1000));
+            callback.block();
+        }
+
+        // The next frame of the message should fail because we waited over a second.
+        Thread.sleep(1100);
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java]: Too small of a margin, wait 1.5 or 2 seconds.

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java [hunk 22]
```diff
@@ -0,0 +1,175 @@
...
+        TestMessageHandler clientEndpoint = new TestMessageHandler();
+        client.connect(clientEndpoint, uri).get();
+        CoreSession session = clientEndpoint.getCoreSession();
+        MESSAGE_LATCH.countDown();
+
+        // Send the first frame of the message with a 1-second timeout.
+        try (Blocker.Callback callback = Blocker.callback())
+        {
+            Frame frame = new Frame(OpCode.TEXT, false, "hello");
+            session.sendFrame(new OutgoingEntry(frame, callback, false, -1, 1000));
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java]: Store `1000` in a variable to be used below to wait.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/common/JakartaWebSocketAsyncRemote.java [hunk 23]
```diff
@@ -39,18 +39,19 @@ public class JakartaWebSocketAsyncRemote extends JakartaWebSocketRemoteEndpoint
...
     {
-        return getWriteTimeout();
+        return messageWriteTimeout;
     }
 
     @Override
     public void setSendTimeout(long timeoutmillis)
     {
-        setWriteTimeout(timeoutmillis);
+        messageWriteTimeout = timeoutmillis;
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/common/JakartaWebSocketAsyncRemote.java]: Fix parameter name camelCase.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/WriteTimeoutTest.java [hunk 24]
```diff
@@ -89,14 +90,15 @@ public void testTimeoutFromSlowReads() throws Exception
     {
         EventSocket clientEndpoint = new EventSocket();
         Session session = client.connectToServer(clientEndpoint, server.getWsUri());
-        session.getAsyncRemote().setSendTimeout(1000);
+        RemoteEndpoint.Async asyncRemote = session.getAsyncRemote();
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/WriteTimeoutTest.java:109]: Fix this test too, like the core one: remove the static `CountDownLatch`, etc.

File: jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/client/WriteTimeoutTest.java [hunk 25]
```diff
@@ -29,11 +32,14 @@
 
 import static org.hamcrest.CoreMatchers.instanceOf;
 import static org.hamcrest.MatcherAssert.assertThat;
+import static org.junit.jupiter.api.Assertions.assertThrows;
 import static org.junit.jupiter.api.Assertions.assertTrue;
 
 public class WriteTimeoutTest
 {
-    @ServerEndpoint("/logSocket")
+    private static final CountDownLatch MESSAGE_LATCH = new CountDownLatch(1);
```
Comment (sbordet) [inline jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/client/WriteTimeoutTest.java]: Fix this test like to core one: remove the static `CountDownLatch`, etc.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java:25]: Done.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java]: done, now this can only be constructed through the builder

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java:93]: I have now added this.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/ExtensionStack.java (hunk 4 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/ExtensionStack.java]: done

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java (hunk 5 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingEntry.java]: done

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingFrames.java (hunk 6 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/OutgoingFrames.java:46]: Its only a breaking change to people implementing this, which is probably no one.

But people will be calling the `sendFrame(Frame frame, Callback callback, boolean batch)` if using the core API, it is also called 181 jetty times in Jetty.

Or I could add this method only onto CoreSession interface and inline the rest of the usages.

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/AbstractExtension.java (hunk 7 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/AbstractExtension.java]: done

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java (hunk 8 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java]: done

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/FragmentingFlusher.java (hunk 13 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/util/FragmentingFlusher.java]: I have moved it back to just before where `fragment()` is called.

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/OutgoingFramesCapture.java (hunk 16 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/OutgoingFramesCapture.java:68]: done

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/OutgoingNetworkBytesCapture.java (hunk 17 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/OutgoingNetworkBytesCapture.java:61]: done

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java (hunk 18 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java]: done

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java (hunk 19 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java]: done

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java (hunk 20 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java]: done

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java (hunk 21 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java]: now sleeping for  `messageWriteTimeout + 500`

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java (hunk 22 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/WriteTimeoutTest.java]: done

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/common/JakartaWebSocketAsyncRemote.java (hunk 23 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-common/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/common/JakartaWebSocketAsyncRemote.java]: Done.

It just inherited the parameter name from the Jakarta API class which does not have the camelCase.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/WriteTimeoutTest.java (hunk 24 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/WriteTimeoutTest.java:109]: I can do this for the core version, but not sure how to do it in the Jakarta API. 

To register the server endpoint you use the class not an instance, so I don't think there is a way to do it without the static.

File: jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/CapturedHexPayloads.java (hunk 15 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-tests/src/test/java/org/eclipse/jetty/websocket/core/CapturedHexPayloads.java]: done

File: jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java (hunk 9 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java:800]: Its really taking an outgoing frame and splitting it into one or more outgoing frames.

So it does need to preserve the write timeouts from the original entry.

I was planning to do a follow up PR to redo all the websocket flushers and also update the API to use OutgoingEntry. I could combine that into this PR if you want. But I see that one as more of an internal change.

Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-core-common/src/main/java/org/eclipse/jetty/websocket/core/WebSocketCoreSession.java:800]: > So it does need to preserve the write timeouts from the original entry.

Sure, but then `forwardFrame()` should have as only parameter an `OutgoingEntry`.
If you plan to do that in a different PR, great.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/WriteTimeoutTest.java (hunk 24 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/WriteTimeoutTest.java:109]: You can, with this (a sketch, but you get the idea):

```java
start(Supplier<ServerSocket> endPointSupplier) 
{
    ...
            server.getServerContainer().addEndpoint(ServerEndpointConfig.Builder.create(ServerSocket.class, "/")
            .configurator(new ServerEndpointConfig.Configurator()
            {
                @Override
                public <T> T getEndpointInstance(Class<T> endpointClass) throws InstantiationException
                {
                    return endPointSupplier.get();
                }
            }).build());
    ...
}
```

**Review by sbordet — CHANGES_REQUESTED** [review]
Just fix the eeN tests, and it's good, as long as you also work on the flushers in a different PR.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/WriteTimeoutTest.java (hunk 24 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/WriteTimeoutTest.java:109]: Yep that works, done.

File: jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/client/WriteTimeoutTest.java (hunk 25 above)
Comment (lachlan-roberts) [reply jetty-ee11/jetty-ee11-websocket/jetty-ee11-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee11/websocket/jakarta/tests/client/WriteTimeoutTest.java]: done

**Review by sbordet — APPROVED** [review]
