### PR TITLE
Issue #12124 fix jsp scratchdir location for ee9.

### LINKED ISSUE #12124: JSP temp directory regression, possibly due to fix for #12044
The 12.0.12 patch for issue 12044 seems to have possibly caused a regression in the JSP temp folder creation step.

Starting 12.0.12 I get this:
Caused by: java.lang.IllegalStateException: Could not create JSP scratch directory

I can see on 12.0.11 I get a jsp folder under "tmp/jetty-0_0_0_0-80-idp_war-_idp-any-4380240850460342364"

On 12.0.12, it can't create it. I think the internal name of the tmp folder is being munged so by the time it goes to create the jsp folder, it isn't using the right path. I noticed I think an extra hyphen or possibly some other stray character in the folder name it created, so something seems to have gone wrong somewhere, like the folder created on disk doesn't match the internal variable holding the folder path it defaults the jsp path to.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #12124

After #12044, the jsp scrachdir is showing up in `jetty.base` instead of under the webapp's tmp dir.
Also, the name of the webapp's tmp dir (if created by jetty) is missing the name of the war.

### CODE REVIEW

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java [hunk 1]
```diff
@@ -2852,4 +2864,9 @@ public boolean handle(org.eclipse.jetty.server.Request coreRequest, Response res
             }
         }
     }
+
+    public Resource getResourceAsBaseName()
```
Comment (gregw) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java]: How about calling this:
```suggestion
    public Resource getNestedResourceForeTempDirName()
```

**Review by gregw — DISMISSED** [review]

**Comment by joakime** [comment]
Still some test failures.

**Comment by joakime** [comment]
wrong danged button push!

File: jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java [hunk 2]
```diff
@@ -140,42 +149,98 @@ public void jettyBaseWorkExists(WorkDir workDirExt) throws Exception
...
     }
+
+    @Test
+    public void testExplicitTempDir(WorkDir workDir) throws Exception
+    {
+        Path myTempDir = workDir.getEmptyPathDir().resolve("my-temp-dir");
+        FS.ensureDirExists(myTempDir);
+
+        // Create war on the fly
+        Path testWebappDir = MavenTestingUtils.getProjectDirPath("src/test/webapp");
```
Comment (olamy) [inline jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java:182]: this may not work with generated ee8 as resources are in target/test-classes.
But depends if the test only need the web.xml or the other resources as the web.xml will not be in this directory)
```suggestion
        Path testWebappDir = MavenTestingUtils.getTargetPath("test-classes/webapp");
```

File: jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java [hunk 3]
```diff
@@ -140,42 +149,98 @@ public void jettyBaseWorkExists(WorkDir workDirExt) throws Exception
...
+        File tempDirectory = webAppContext.getTempDirectory();
+        assertThat(webAppContext.getAttribute(ServletContext.TEMPDIR), is(tempDirectory));
+        assertThat(tempDirectory.toPath(), is(myTempDir));
+    }
+
+    @Test
+    public void testFreshTempDir(WorkDir workDir) throws Exception
+    {
+        // Create war on the fly
+        Path testWebappDir = MavenTestingUtils.getProjectDirPath("src/test/webapp");
```
Comment (olamy) [inline jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java:201]: same comment 
```suggestion
        Path testWebappDir = MavenTestingUtils.getTargetPath("test-classes/webapp");
```

File: jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java [hunk 4]
```diff
@@ -140,42 +149,98 @@ public void jettyBaseWorkExists(WorkDir workDirExt) throws Exception
...
+        assertNull(webAppContext.getTempDirectory());
+        webAppContext.start();
+        assertThat(tempDirectory.toPath(), not(PathMatchers.isSame(webAppContext.getTempDirectory().toPath())));
+    }
+
+    @Test
+    public void testSameTempDir(WorkDir workDir) throws Exception
+    {
+        // Create war on the fly
+        Path testWebappDir = MavenTestingUtils.getProjectDirPath("src/test/webapp");
```
Comment (olamy) [inline jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java:222]: same comment
```suggestion
        Path testWebappDir = MavenTestingUtils.getTargetPath("test-classes/webapp");
```

**Review by olamy — CHANGES_REQUESTED** [review]

File: jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java (hunk 2 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java:182]: The new `MavenPaths` object has several `.find*` methods that will work as intended on ee8/ee9.
Can we use one of those?

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java (hunk 1 above)
Comment (janbartel) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java]: Done.

File: jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java (hunk 4 above)
Comment (janbartel) [reply jetty-ee9/jetty-ee9-webapp/src/test/java/org/eclipse/jetty/ee9/webapp/TempDirTest.java:222]: I'm confused, the tests appear to be working on ee8?

**Review by gregw — APPROVED** [review]
