### PR TITLE
Do not throw from HttpChannelState.read() method

### LINKED ISSUE #11363: ContentSourcePublisher throws from request
**Jetty version(s)**

**Jetty Environment**
12

**Description**

In the [spring integration branch](https://github.com/spring-projects/spring-framework/pull/32097) we are seeing the following exception:

```
java.lang.IllegalStateException: channel already completed
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelRequest.lockedGetHttpChannelState(HttpChannelState.java:809) ~[jetty-server-12.0.6.jar:12.0.6]
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelRequest.read(HttpChannelState.java:873) ~[jetty-server-12.0.6.jar:12.0.6]
	at org.eclipse.jetty.io.content.ContentSourcePublisher$SubscriptionImpl.process(ContentSourcePublisher.java:114) ~[jetty-io-12.0.6.jar:12.0.6]
	at org.eclipse.jetty.io.content.ContentSourcePublisher$SubscriptionImpl.request(ContentSourcePublisher.java:85) ~[jetty-io-12.0.6.jar:12.0.6]
	at org.reactivestreams.FlowAdapters$ReactiveToFlowSubscription.request(FlowAdapters.java:182) ~[reactive-streams-1.0.4.jar:?]
	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.BaseSubscriber.request(BaseSubscriber.java:214) ~[reactor-core-3.6.2.jar:3.6.2]
	at org.springframework.http.codec.multipart.MultipartParser.requestBuffer(MultipartParser.java:196) ~[spring-web-6.1.4-SNAPSHOT.jar:6.1.4-SNAPSHOT]
```

However, the reactive specification says that "Calling Subscription.request MUST return normally". So our `ContentSourcePublisher` is breaking that rule and throwing rather than calling `onError`

### PR DESCRIPTION
**Pull request by gregw**
Fixes #11363 by ensuring that read never throws, but instead returns an Error chunk.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 1]
```diff
@@ -867,20 +867,27 @@ public long getLength()
...
+                        return error;
 
-                stream = httpChannel._stream;
+                    stream = httpChannel._stream;
+                }
+                chunk = stream.read();
+            }
+            catch (Throwable t)
+            {
+                return Content.Chunk.from(t, true);
```
Comment (joakime) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:899]: Shouldn't this notify onError() too?

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:899]: No. There is no `onError` in our `Content.Source` contract. There are various `onError` methods in layers above, and these should be called when a `Chunk.Error` is read.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 2]
```diff
@@ -867,20 +867,27 @@ public long getLength()
...
+                    httpChannel._readFailure = Content.Chunk.next(error);
+                    if (error != null)
+                        return error;
 
-                stream = httpChannel._stream;
+                    stream = httpChannel._stream;
+                }
+                chunk = stream.read();
+            }
+            catch (Throwable t)
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:897]: I would extend the `try` to the whole method.
The lines below should not throw, but neither the above should have, so I'd extend the scope of the try to the whole method to state the intention that the whole method must not throw, not only certain parts of the method.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 3]
```diff
@@ -867,31 +867,38 @@ public long getLength()
         @Override
         public Content.Chunk read()
         {
-            HttpStream stream;
-            try (AutoLock ignored = _lock.lock())
+            Content.Chunk chunk;
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: This line can be moved down now, as it is only used inside the try.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]
