### PR TITLE
Issue #13588 - Improve ResourceFactory.split() and URIUtil.toURI to work properly on Windows.

### LINKED ISSUE #13588: CONTAINER_JAR_PATTERN ignored on Windows
**Jetty version(s)**
Jetty 12.1.1

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
openjdk-24.0.+12-54 x86-64

**OS type/version**
Windows 11

**Description**
The CONTAINER_JAR_PATTERN setting is ignored on Windows.

Upon further debugging, the problem is as follows:
1. `MetaInfConfiguration.findAndFilterContainerPaths()` is called, which in turn calls `ResourceFactory.split()` to split up `java.class.path`.
2. `ResourceFactory.split()` however always returns an empty list on Windows. The reason is that `URIUtil.hasScheme()` returns true for `C:\foo\bar`, causing the follow-up `new URI()` to throw an exception (since `C:\foo\bar` isn't a parsable URI).

**How to reproduce?**

```java
final WebAppContext context = new WebAppContext();
final Resource webRoot = findWebRoot(context.getResourceFactory().newResource("C:\\"));
context.setBaseResource(webRoot);
context.setContextPath("/");
context.setAttribute(MetaInfConfiguration.CONTAINER_JAR_PATTERN, ".*\\.jar|.*/classes/.*");
context.setConfigurationDiscovered(true);
var server = new Server();
server.setHandler(context);
server.start();
```
On Linux, classpath is properly scanned, servlets are auto-discovered and activated. On Windows, no servlets are auto-discovered.

### PR DESCRIPTION
**Pull request by joakime**
+ New testcases in `ResourceFactoryTest.testSplit*`
  - including a test for doing a split of the `java.class.path` in an expected way.
+ Restore `URIUtil.toURI(String)` for the purpose of converting a raw string reference to a URI without causing a Resource mount to occur.

The existing implementation would Mount, then unwrap, then leave the mount mounted.
This new implementation doesn't even create the mount if unwrap is true.
The responsibility is to convert String references to absolute URIs.
Then it can be used to create a Resource.
Having this all be done within Resource.newResource() results in extra mounts and reference counts for no good reason.

### CODE REVIEW

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 1]
```diff
@@ -1901,72 +1900,75 @@ else if (scheme.equalsIgnoreCase("file"))
...
-                URI uri = new URI(resource);
-
-                if (ResourceFactory.isSupported(uri))
-                    return correctURI(uri);
-
-                // We don't have a supported URI scheme
-                if (uri.getScheme().length() == 1)
+                // At this point we have a string detected as a URI.
+                // But that could also include Windows paths like "C:\path\to\foo.jar" or "C:/path/to/foo.jar"
+                String scheme = uri.getScheme();
```
Comment (janbartel) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java:1939]: If on windows I pass in a `reference` of `file:///c:/some/thing.txt` then is the `scheme` reported after conversion to `URI` `file` or `c`?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 2]
```diff
@@ -1901,72 +1900,75 @@ else if (scheme.equalsIgnoreCase("file"))
...
+             * Example: reference parameter is the String "file:///path/to/dir"
+             *
+             * On Unix, the Path.of(reference) will result in a relative directory reference
+             * that includes the "file:" portion in the path after the current working directory.
+             * You'll wind up with something like "file:///home/user/code/jetty/12.1.x/jetty-core/jetty-util/file:///path/to/dir" in this case
+             *
+             * On Windows, the Path.of(reference) will not allow a Path.of("file:///path/to/dir") to work.
+             * This is because there cannot be multi-character drive letters (yes, Windows is limited to only 26 drive letters max)
+             */
+            URI uri = URI.create(reference);
```
Comment (janbartel) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java]: We should use `new URI(reference)` here as the javadoc for `create(String)` makes it clear that it its use is not for strings that may come from user input etc. So just catch `URISyntaxException`.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java [hunk 3]
```diff
@@ -523,40 +525,40 @@ default List<Resource> split(String str, String delims, boolean unwrap)
...
-                            list.add(newResource(uri.toASCIIString()));
+                        list.add(newResource(URIUtil.unwrapContainer(uri)));
                     }
                     else
                     {
-                        Path p = Paths.get(reference);
-                        if (!p.isAbsolute() && LOG.isDebugEnabled())
-                            LOG.warn("Non-absolute path: {}", reference);
-                        list.add(newResource(p.toAbsolutePath()));
+                        list.add(newResource(uri));
```
Comment (janbartel) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:561]: I'm a bit cautious that this is a behaviour change - previously relative references were ignored, but now they will be used.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java [hunk 4]
```diff
@@ -339,104 +338,159 @@ public void testSplitSinglePath() throws URISyntaxException
...
+                rawInputs.add("jar:file:///foo/bar.jar!/");
+                rawInputs.add("jar:file:///foo/bar.jar");
+                rawInputs.add("/foo/bar.jar");
+            }
 
-            //test that an unwrapped jar:file will try to be mounted and fail because it isn't a real location
-            resources = resourceFactory.split("jar:file:///foo/bar.jar!/", ",", false);
-            assertThat(resources.size(), is(0));
+            String rawConfig = String.join(",", rawInputs);
+            List<Resource> resources = resourceFactory.split(rawConfig, ",", true);
```
Comment (janbartel) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:365]: The previous code explicitly tests `jar:file:///foo/bar.jar!/` with `unwrap` of  `false`. Here it is tested with `true`.

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java:1939]: The scheme would be `file`

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java (hunk 3 above)
Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:561]: Relative references are 100% necessary to support here.
This is a code path for many configuration from jetty-home/jetty-base and it's properties.
It's very common to use relative paths in the configuration, so that the same configuration can be supported across dev, qa, docker images, production, etc...

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java (hunk 4 above)
Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:365]: We have the unwrap == false version in the other testcase.

Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:365]: See: testSplitExistingJarFileSystemNotUnwrappedIsMounted
and testSplitNonExistentFileReferenceNotUnwrapNotMounted

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java:1939]: See the testcases in ResourceFactoryTest.testSplitIsAbsolute for some windows examples.

Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java:1939]: Also the testcases in URIUtilTest.testToURI (and it's parameters at URIUtilTest.toURICases)

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java (hunk 3 above)
Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:561]: Prior to your change, relative references were not ignored.
Admittedly they were poorly tested, but that lack of testing is hopefully addressed in this PR.

Comment (joakime) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java:561]: Example:

```
[joakim@hyperion jetty-home-12.0.10]$ jshell --class-path lib/jetty-util-12.0.10.jar:lib/logging/jetty-slf4j-impl-12.0.10.jar:lib/logging/slf4j-api-2.0.12.jar 
|  Welcome to JShell -- Version 17.0.15
|  For an introduction type: /help intro

jshell> import org.eclipse.jetty.util.resource.*;

jshell> try (ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable()) {
   ...>     var result = resourceFactory.split("bar/a,bar/b,foo/z");
   ...>     System.out.println(result);
   ...> }
[file:///home/joakim/code/jetty/distros/jetty-home-12.0.10/bar/a, file:///home/joakim/code/jetty/distros/jetty-home-12.0.10/bar/b, file:///home/joakim/code/jetty/distros/jetty-home-12.0.10/foo/z]

jshell> /exit
|  Goodbye
```

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java [hunk 5]
```diff
@@ -339,104 +338,159 @@ public void testSplitSinglePath() throws URISyntaxException
...
+                rawInputs.add("jar:file:///C:/foo/bar.jar!/");
+                rawInputs.add("jar:file:///C:/foo/bar.jar");
+                rawInputs.add("C:/foo/bar.jar");
+            }
+            else
+            {
+                rawInputs.add("jar:file:///foo/bar.jar!/");
+                rawInputs.add("jar:file:///foo/bar.jar");
+                rawInputs.add("/foo/bar.jar");
+            }
```
Comment (janbartel) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:362]: Both the windows and non-windows code here is missing this type of url: ```file:///foo/bar.jar```, please add back in.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java [hunk 6]
```diff
@@ -339,104 +338,159 @@ public void testSplitSinglePath() throws URISyntaxException
...
+            assertThat(resources.size(), is(1));
+            assertThat(resources.get(0), not(instanceOf(MountedPathResource.class)));
+            assertThat(resources.get(0).getPath().isAbsolute(), is(true));
         }
     }
 
+    /**
+     * If a jar filesystem {@code jar:file://} URI string reference is used against a real file that exists,
+     * with unwrap turned off, then this will result in a Resource that is mounted.
+     */
```
Comment (janbartel) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: We don't ever want to result in any mounting from `ResourceFactory.split`.  See my comment here: https://github.com/jetty/jetty.project/pull/13427#discussion_r2274740562

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java (hunk 6 above)
Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: The whole point of the unwrap boolean is to control that.
* If you set unwrap == true then that's no mounting.
* If you set unwrap == false then that's mounting.

Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: Don't look at ResourceFactory.split as only having one use case.
There's many use cases for this method, and many of them want a mounted Resource.
It's only the java.class.path use case where we don't want a mounted resource from the get go.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java (hunk 5 above)
Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:362]: Added it back.
I also changed the filenames on each input line just to make it clear in the code which one we are actively parsing.

**Comment by joakime** [comment]
@janbartel should ResourceFactory.split() collapse duplicates?

Eg: if we have 3 entries ...

```
"/foo/bar.jar;/foo/zed.jar;/foo/bar.jar"
```

Should the second entry for `"/foo/bar.jar"` be ignored as it's already present?

What about equivalent entries?

```
"/foo/bar.jar;file:///foo/bar.jar"
```

Both of those point to the same URI.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java (hunk 5 above)
Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:362]: Done.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java (hunk 6 above)
Comment (janbartel) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: No, `unwrap` doesn't determine whether or not it is mounted. It controls whether or not you want a `jar:file:` url stripped back to just the `file:` part. See the code comments here: https://github.com/jetty/jetty.project/blob/jetty-12.1.x/jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/resource/ResourceFactory.java#L545

**Comment by janbartel** [comment]
> @janbartel should ResourceFactory.split() collapse duplicates?
> 
> Eg: if we have 3 entries ...
> 
> ```
> "/foo/bar.jar;/foo/zed.jar;/foo/bar.jar"
> ```
> 
> Should the second entry for `"/foo/bar.jar"` be ignored as it's already present?
> 
> What about equivalent entries?
> 
> ```
> "/foo/bar.jar;file:///foo/bar.jar"
> ```
> 
> Both of those point to the same URI.

No, I don't think its the job of `ResourceFactory` to second guess what the caller wants to do with the list that is passed in.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java (hunk 6 above)
Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: Also keep in mind that `unwrap` is only for `jar:file://` based URIs in the ResourceFactory.split().

Other schemes, supported by Resource layer, can be present on the input string, and wont ever unwrap.

In graalvm a Jetty Resource can be created from the URI form `resource:/foo/bar/root/`.
That is a syntax often used for WebAppContext.setExtraClassPath(String) for example.
In graalvm, the root of that Path is already mounted by the time the JVM is fully started.
In Jetty Resource layer we use MountedPathResource to see it.

Comment (janbartel) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: The unwrap param mostly applies to `jar:file` urls, because it is using the pre-existing `URIUtil.unwrapContainer` that will be unaffected by anything other than a `jar:file` url. It is imperative that `jar:file` urls are never mounted by the `ResourceFactory`, but is left to the caller to decide if it wants to mount. There may be other url schemes such as `resource:` as you mention, but we don't have any code in jetty that explicitly tries to deal with it, so if it's already mounted by the time the jvm starts, then it's out of our control - we just have to make sure we're not adding any unnecessary mounts.

Comment (gregw) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: > Don't look at ResourceFactory.split as only having one use case. There's many use cases for this method, and many of them want a mounted Resource. It's only the java.class.path use case where we don't want a mounted resource from the get go.

@joakime We've been down this road a few times... if utility methods that may be called during configuration mount, then we leak resources.  Every time we've done this, we've been bitten and had to reverse out the changes.    We cannot mount resources until we have an appropriate lifecycle managed resource factory that will handle the unmount.

Utility methods cannot mount because they cannot take responsibility for unmounting.

Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: > @joakime We've been down this road a few times... if utility methods that may be called during configuration mount, then we leak resources. Every time we've done this, we've been bitten and had to reverse out the changes. We cannot mount resources until we have an appropriate lifecycle managed resource factory that will handle the unmount.
> 
> Utility methods cannot mount because they cannot take responsibility for unmounting.

Then we should restore URIUtil.split() and work with ONLY the URIs.

As there are strings like `resource:/foo/bar/` that would always use the `Resource` type `MountedPathResource`.
Mounting is a given if you are using `Resource`, not optional in some cases.

But working with URI is totally free of any `ResourceFactory.newResource()` side effects.

Comment (gregw) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: We can't work with URIs because we may be passed an filename rather than a URI.   What is the issue with the current implementation of `ResourceFactory.split` that you are trying to solve?

Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: > We can't work with URIs because we may be passed an filename rather than a URI. 

That's taken care of by URIUtil.split() now.
It will attempt to convert all inputs to absolute URIs.

> What is the issue with the current implementation of `ResourceFactory.split` that you are trying to solve?

Jan has stated that ResourceFactory.split should NEVER mount.
I'm saying that's not 100% possible.
There are several scenarios (URIs on input that are not `jar:file://` or `file://`) where it will mount, as there are inputs that have to use `MountedPathResource` for the `Resource` to even exist (see above mentioned graalvm behavior).

If Jan wants a utility method that never uses `MountedPathResource`, and wants to iterate through the results on her own, then do it via the URIs not the `Resource`.

Also, keep in mind that `ResourceFactory.split()` is not a static method.  You must have a valid `ResourceFactory` instance to even call it, so you are in essence forced to use it with a valid `ResourceFactory` (such as one from a WebAppContext).  So if you use it correctly, it will clean up after itself in the way you established the `ResourceFactory`.

These are the current usages of `ResourceFactory.split()` - (not an exhaustive list, just a quick search in the codebase)

`MetaInfConfiguration.findAndFilterContainerPaths`

  * will split on `System.getProperty("java.class.path")`
  * using `File.pathSeparator` and unwrap=true
  * Code will iterate through results.
  * This use case rarely has URIs as it uses `java.class.path` as input (I need to check if things like graalvm with scheme `resource://`, or jlink with resource `jrt://`, expose their own filesystem stuff in "java.class.path")

`CoreAppContext.setExtraClassPath(String)`
`WebAppContext.setExtraClassPath(String)`

  * will split input on `",;|"` (this is a bug in some code bases)
  * Code will call `setExtraClassPath(List<Resource> resources)` with results of `ResourceFactory.split()`
  * This use case can have URIs on the input (and is a usecase seen in graalvm).
  
`WebAppPropertyConverter.fromProperties`

  * will split on `File.pathSeparator`, unwrap=true
  * Code will call `WebAppContext.setExtraClassPath(String)`
  * This is a bug, it should be calling `WebAppContext.setExtraClassPath(String)`  and let a single implementation handle it.
  * The above mentioned bug also means that `WebAppPropertyConverter` cannot handle `URIs` in the input on Linux.

Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:456]: > @joakime We've been down this road a few times... if utility methods that may be called during configuration mount, then we leak resources. Every time we've done this, we've been bitten and had to reverse out the changes. We cannot mount resources until we have an appropriate lifecycle managed resource factory that will handle the unmount.
> 
> Utility methods cannot mount because they cannot take responsibility for unmounting.

This is moot for `ResourceFactory.split()` as it is not a static utility method, but rather a method on an instance of `ResourceFactory`.  A `ResourceFactory` which you should have created with the correct lifecycle before you called the split method.

Example: For `WebAppContext.setExtraClassPath(String)` use of `ResourceFactory.split()` it's the `ResourceFactory` belonging to the `WebAppContext`.

**Comment by janbartel** [comment]
@joakime I think we are slightly talking at cross purposes here. `unwrap` determines whether or not a `jar:file:` url will be reduced to `file:` before it is converted into a resource. If indeed the caller passed `jar:file:/some/path!/` into `split()` but with `unwrap=false`, then yes, I guess the `newResource()` method will wind up mounting it. But that is for the caller to decide - as long as we have a way for the caller to control whether or not a mount occurs, then I'm fine. However, you seem to be arguing that `split()` _should_ mount, which just cannot work. 

If there are some schemes that we don't explicitly handle (BTW `URIUtil.unwrapContainer() will ignore all non `jar:` schemes ` and just return the original `uri` so it can be called without first checking the uri starts with `jar:`) then they will be passed through to `ResourceFactory.newResource()` and I guess it depends on the implementation of that method as to whether or not a mount would occur. Looking at our impl for the `resource:` scheme, it looks like we _do_ have some special handling for that scheme, and we would indeed do a mount and it would be leaked.  That seems off, I think we should revisit our code for `resource:` handling.

**Comment by janbartel** [comment]
I've opened an issue to look at the special Graal `ResourceFactory` code to see if it is really necessary to retain, see #13702

**Review by janbartel — APPROVED** [review]
