### PR TITLE
Issue #13487 - add annotations for Ping & Pong in the Jetty WebSocket API

### LINKED ISSUE #13487: Regression in Jetty 12.1.0: @OnWebSocketFrame and @OnWebSocketMessage can no longer coexist
**Jetty version(s)**
Jetty version: 12.1.0
Previous version (working): 12.0.25

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
java21

**OS type/version**
Linux

### Description

After upgrading from **Jetty 12.0.25 → 12.1.0**, our WebSocket adapter class that combines both `@OnWebSocketMessage` and `@OnWebSocketFrame` no longer works.

In 12.0.25 this was valid and allowed us to process **text/binary messages** via `@OnWebSocketMessage` and handle **Pong frames** via `@OnWebSocketFrame`.
Starting with 12.1.0, the same code fails with `InvalidWebSocketException`.

---

### Reproducer

```java
@WebSocket
public class XWebSocketAdapter {
    @OnWebSocketMessage
    public void onWebSocketText(String text) {
        // handle text
    }

    @OnWebSocketMessage
    public void onWebSocketBinary(ByteBuffer data, @Out Callback out) {
        // handle binary
        out.succeed();
    }

    @OnWebSocketFrame
    public void onWebSocketFrame(Frame frame, @Out Callback out) {
        // specifically handle Pong frames
        if (frame.getOpCode() == OpCode.PONG) {
            // custom pong handling
        }
        out.succeed();
    }
}
```

---

### Actual Behavior (12.1.0)

```
Caused by: org.eclipse.jetty.websocket.api.exceptions.InvalidWebSocketException: Cannot replace previously assigned [FRAME Handler] at MethodHandle(XWebSocketAdapter,Session,Frame,Callback)void with public void cn.nextop.gadget.web.support.socket.XWebSocketAdapter.onWebSocketText(java.lang.String)
```

---

### Expected Behavior (same as 12.0.25)

* `@OnWebSocketMessage` should handle normal text/binary messages.
* `@OnWebSocketFrame` should be allowed to process frames (in our case, Pong).
* No conflict should occur.

---

### Questions

* Is this restriction in Jetty 12.1.0 intentional?

* If yes, what is the recommended migration path for applications that previously used `@OnWebSocketFrame` only for handling Pong frames while still using `@OnWebSocketMessage`?

* Jetty does not provide `@OnWebSocketPing` / `@OnWebSocketPong` annotations, so it is unclear what the intended replacement is for these cases.

---

### Additional Notes

* This is a **behavior change** between **12.0.25 (works)** and **12.1.0 (fails)**.
* If intentional, it would be helpful to clarify this in the release notes or migration guide.

---

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #13487

### CODE REVIEW

File: jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketPong.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+package org.eclipse.jetty.websocket.api.annotations;
+
+import java.lang.annotation.Documented;
+import java.lang.annotation.ElementType;
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+
+/**
+ * <p>Annotation for methods to receive WebSocket ping events.</p>
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketPong.java]:
```suggestion
 * <p>Annotation for methods to receive WebSocket PONG events.</p>
```

File: jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketPing.java [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+package org.eclipse.jetty.websocket.api.annotations;
+
+import java.lang.annotation.Documented;
+import java.lang.annotation.ElementType;
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+
+/**
+ * <p>Annotation for methods to receive WebSocket ping events.</p>
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/annotations/OnWebSocketPing.java]:
```suggestion
 * <p>Annotation for methods to receive WebSocket PING events.</p>
```

**Review by sbordet — CHANGES_REQUESTED** [review]
Just javadoc nits.

**Review by sbordet — APPROVED** [review]
