### PR TITLE
Fixes #13048 - Exception from oeje11wjt.JakartaClientClassLoaderTest#websocketProvidedByServer

### LINKED ISSUE #13048: Exception from oeje11wjt.JakartaClientClassLoaderTest#websocketProvidedByServer
**Jetty version(s)**
12.1.x

**Jetty Environment**
ee11 (probably others?)

**Description**
The test `org.eclipse.jetty.ee11.websocket.jakarta.tests.JakartaClientClassLoaderTest#websocketProvidedByServer`
passes, but produces the following exception:
```
2025-04-25 21:25:04.220:WARN :oeju.TypeUtil:qtp-LocalServer-75: Service Provider failed to load
java.util.ServiceConfigurationError: 
	at org.eclipse.jetty.util.ServiceLoaderSpliterator$ServiceProvider.get(ServiceLoaderSpliterator.java:101)
	at org.eclipse.jetty.util.TypeUtil.mapToService(TypeUtil.java:728)
	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:289)
	at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:46)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at org.eclipse.jetty.client.HttpClient.doStart(HttpClient.java:243)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:120)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addManaged(ContainerLifeCycle.java:482)
	at org.eclipse.jetty.ee11.websocket.jakarta.client.JakartaWebSocketClientContainer.getWebSocketCoreClient(JakartaWebSocketClientContainer.java:119)
	at org.eclipse.jetty.ee11.websocket.jakarta.client.JakartaWebSocketClientContainer.connect(JakartaWebSocketClientContainer.java:166)
	at org.eclipse.jetty.ee11.websocket.jakarta.client.JakartaWebSocketClientContainer.connectToServer(JakartaWebSocketClientContainer.java:253)
	at org.eclipse.jetty.ee11.websocket.jakarta.tests.JakartaClientClassLoaderTest$WebSocketClientServlet.doGet(JakartaClientClassLoaderTest.java:112)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:633)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.eclipse.jetty.ee11.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1370)
	at org.eclipse.jetty.ee11.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee11.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.ee11.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
	at org.eclipse.jetty.ee11.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee11.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1640)
	at org.eclipse.jetty.ee11.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1601)
	at org.eclipse.jetty.ee11.servlet.ServletChannel.dispatch(ServletChannel.java:802)
	at org.eclipse.jetty.ee11.servlet.ServletChannel.handle(ServletChannel.java:439)
	at org.eclipse.jetty.ee11.servlet.ServletHandler.handle(ServletHandler.java:469)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
	at org.eclipse.jetty.ee11.servlet.SessionHandler.handle(SessionHandler.java:763)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1123)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:178)
	at org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:671)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:411)
	at org.eclipse.jetty.server.internal.HttpConnection$FillableCallback.succeeded(HttpConnection.java:1811)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:54)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: 
java.util.ServiceConfigurationError: org.eclipse.jetty.compression.Compression: Provider org.eclipse.jetty.compression.gzip.GzipCompression not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1215)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1224)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1269)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1305)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1387)
	at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:37)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at org.eclipse.jetty.client.HttpClient.doStart(HttpClient.java:243)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:120)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addManaged(ContainerLifeCycle.java:482)
	at org.eclipse.jetty.ee11.websocket.jakarta.client.JakartaWebSocketClientContainer.getWebSocketCoreClient(JakartaWebSocketClientContainer.java:119)
	at org.eclipse.jetty.ee11.websocket.jakarta.client.JakartaWebSocketClientContainer.connect(JakartaWebSocketClientContainer.java:166)
	at org.eclipse.jetty.ee11.websocket.jakarta.client.JakartaWebSocketClientContainer.connectToServer(JakartaWebSocketClientContainer.java:253)
	at org.eclipse.jetty.ee11.websocket.jakarta.tests.JakartaClientClassLoaderTest$WebSocketClientServlet.doGet(JakartaClientClassLoaderTest.java:112)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:633)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.eclipse.jetty.ee11.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1370)
	at org.eclipse.jetty.ee11.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee11.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.ee11.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
	at org.eclipse.jetty.ee11.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee11.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1640)
	at org.eclipse.jetty.ee11.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1601)
	at org.eclipse.jetty.ee11.servlet.ServletChannel.dispatch(ServletChannel.java:802)
	at org.eclipse.jetty.ee11.servlet.ServletChannel.handle(ServletChannel.java:439)
	at org.eclipse.jetty.ee11.servlet.ServletHandler.handle(ServletHandler.java:469)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
	at org.eclipse.jetty.ee11.servlet.SessionHandler.handle(SessionHandler.java:763)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1123)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:178)
	at org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:671)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:411)
	at org.eclipse.jetty.server.internal.HttpConnection$FillableCallback.succeeded(HttpConnection.java:1811)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:54)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

This exception should be fixed, or suppressed if expected.

### PR DESCRIPTION
**Pull request by sbordet**
Converted LOG.warn() into LOG.debug() for `ServiceLoader` attempts via `TypeUtil` that result in an exception.

Such cases may be normal and don't really warrant a warning.

### CODE REVIEW

**Review by joakime — CHANGES_REQUESTED** [review]
> Such cases may be normal and don't really warrant a warning.

I what scenarios is the ServiceLoader failing not a warning?

I'm a -1 on changing this logging level.

If the ServiceLoader finds the service file, but cannot load the class, then that's a quite bad situation.
In the same level of importance as Instantiation errors.
The configuration was setup to work, but that configuration is failing.
Moving this from warn to debug is just wrong.

**Comment by joakime** [comment]
I consider this a controversial change, and want to bump it to 12.0.21 to get wider consensus, or a better implementation.
It's not suitable for 12.0.20 IMO.

**Comment by sbordet** [comment]
@joakime we have this policy of warnings only for unrecoverable things.

This is fully recoverable.

The scenario of the `ServiceLoader` failing and not being a warning is exactly that of this test, and it's detailed in the issue.

We don't want to start emit warnings for perfectly valid configurations.
For invalid configurations, the system won't work as expected, and normal troubleshooting applies.

**Comment by joakime** [comment]
> @joakime we have this policy of warnings only for unrecoverable things.
> 
> This is fully recoverable.

If we have a classloader problem and the XML cannot load a class, we warn, with stacktrace.
If it occurs during start.jar we exit.
If it occurs during webapp redeploy, we still warn, but don't exit.
If the WEB-INF references a class that cannot be loaded, we throw a warning too.
Those are the policy in these cases.

If the WebApp Configurations don't load that not recoverable.
And that is totally silent if we eliminate the warning, the webapp will startup in most cases just fine.
Just some things might not be present.
Things that change behavior most of the time, but don't fail the webapp.

> The scenario of the `ServiceLoader` failing and not being a warning is exactly that of this test, and it's detailed in the issue.

The fix for the issue is to suppress stacktrace logging for that websocket test.
Not to squelch the warning here.
 
> We don't want to start emit warnings for perfectly valid configurations. For invalid configurations, the system won't work as expected, and normal troubleshooting applies.

If ALPN fails to load because of ServiceLoader issues, that's a big deal.
That's not a "perfectly valid configuration".

There are many things that use ServiceLoader stuff, just because 1 of the many use cases can result in "perfectly valid configuration" doesn't mean all uses of ServiceLoader have the same behavior.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java [hunk 1]
```diff
@@ -729,15 +734,17 @@ private static <T> Stream<T> mapToService(ServiceLoader.Provider<T> provider)
...
             return Stream.empty();
         }
     }
 
     /**
      * Utility method to provide a stream of the service type from a {@link ServiceLoader}.
-     * Log warnings will be given for any {@link ServiceConfigurationError}s which occur when loading or
-     * instantiating the services.
+     * {@link ServiceConfigurationError}s thrown when loading or instantiating the services
+     * are logged and ignored, so that the stream can proceed with the next service provider.
```
Comment (joakime) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java]: specify that they are logged at debug level.

**Review by joakime — DISMISSED** [review]
Using the `Configurations` from jetty-ee10-webapp.
We can see that existing (and unchanged) `TypeUtil.serviceProviderStream` behavior is a good method to use to show warning (or throw exception), the change in this PR is to a different method.

But fix the javadoc please.

**Review by joakime — APPROVED** [review]

**Review by gregw — APPROVED** [review]
