### PR TITLE
Jetty 12.1.x simplified epc no pending

### LINKED ISSUE #13470: Jetty 12.0: ManagedSession issues due to recursion and/pr multiple completions of the stream.
**Jetty version(s)**
12.0.17

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.15" 2025-04-15
OpenJDK Runtime Environment Temurin-17.0.15+6 (build 17.0.15+6)
OpenJDK 64-Bit Server VM Temurin-17.0.15+6 (build 17.0.15+6, mixed mode, sharing)

**OS type/version**
Rocky Linux release 9.5 (Blue Onyx)

**Description**

Environment:
- Embedded Jetty ee10 in our application
- Session stack: DefaultSessionCache + NullSessionDataStore
- Production traffic is primarily HTTP/2

After upgrading to Jetty 12, we see a accumulation of ManagedSession instances in DefaultSessionCache. Heap dumps show thousands of sessions remaining in VALID state even though their lastAccessed timestamps are weeks in the past and maxInactiveMs is 600_000 (10 minutes). A common property of all leaked sessions is that their sessionInactivityTimer is set to Long.MAX_VALUE, which appears to prevent the HouseKeeper from ever expiring them. Over several months of uptime, about 6,000 such sessions accumulate. This behavior is only observed on Jetty 12; Jetty 11 behaves correctly with the same application and traffic pattern.

**How to reproduce?**

We cannot reproduce this in our lab/test environment; in lab, sessions are consistently expired and removed as expected.

### PR DESCRIPTION
**Pull request by gregw**
Added a max depth recursion limit for EPC recursion (when a consumed task calls produce)
Set IDLE before the attempt so a reserved thread can always become the producer

### CODE REVIEW

**Comment by gregw** [comment]
see also #13371

**Comment by sbordet** [comment]
CometD tasks are all BLOCKING.
Reserved threads at default, which yields 32.
8 connections across 4 selectors
The AES of the 8 HTTP/2 connections:
```
[pc=0,pic=0,pec=767045,epc=260811]
[pc=0,pic=0,pec=1743803,epc=557801]
[pc=0,pic=0,pec=1391611,epc=466419]
[pc=0,pic=0,pec=2118239,epc=691435]
[pc=0,pic=0,pec=1237826,epc=401432]
[pc=0,pic=0,pec=2044330,epc=672052]
[pc=0,pic=0,pec=1107714,epc=325072]
[pc=0,pic=0,pec=1909493,epc=616003]
```

The AES of the 4 selectors:
```
[pc=0,pic=414609,pec=1,epc=60]
[pc=0,pic=594745,pec=3,epc=107]
[pc=0,pic=537541,pec=1,epc=33]
[pc=0,pic=474283,pec=1,epc=10]
```

**Comment by gregw** [comment]
@sbordet I have reworked this a bit:
 + merged your latest changes from 12.1.x
 + EPC now works from REPRODUCING state as well
 + There is now a maxEpcDepth configuration to allow limited recursion

**Comment by gregw** [comment]
@sbordet can you flame graph this branch again?

**Comment by gregw** [comment]
@lorban @sbordet @lachlan-roberts review please!

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 1]
```diff
@@ -134,7 +134,16 @@ private enum SubStrategy
     private final Executor _executor;
     private final TryExecutor _tryExecutor;
     private final Executor _virtualExecutor;
-    private final AtomicBiInteger _state = new AtomicBiInteger();
+    private final AtomicInteger _state = new AtomicInteger();
+    private final ThreadLocal<Integer> _epcDepth = new ThreadLocal<>()
```
Comment (lachlan-roberts) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: You can replace this with `ThreadLocal.withInitial(() -> 0)`.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 2]
```diff
@@ -153,29 +162,39 @@ public AdaptiveExecutionStrategy(Producer producer, Executor executor)
...
+     */
+    public int getMaxEpcDepth()
+    {
+        return _maxEpcDepth;
+    }
+
+    /**
+     * EPC can call a task with a previous producing thread, which can then itself
+     * call {@link #produce()}. This field limits the possible recursion depth.
+     * @param maxEpcDepth The maximum recursion depth of a a thread calling EPC (default 8)
```
Comment (lachlan-roberts) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Typo "depth of a a thread".

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 3]
```diff
@@ -153,29 +162,39 @@ public AdaptiveExecutionStrategy(Producer producer, Executor executor)
             LOG.debug("created {}", this);
     }
 
+    /**
+     * @return The maximum recursion depth of a a thread calling EPC (default 8)
```
Comment (lachlan-roberts) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Typo "depth of a a thread".

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/EatWhatYouKill.java [hunk 4]
```diff
@@ -1,28 +0,0 @@
...
-
-package org.eclipse.jetty.util.thread.strategy;
-
-import java.util.concurrent.Executor;
-
-/**
- * @deprecated This class has been renamed to {@link AdaptiveExecutionStrategy}
- */
-@Deprecated(forRemoval = true)
-public class EatWhatYouKill extends AdaptiveExecutionStrategy
```
Comment (lachlan-roberts) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/EatWhatYouKill.java:22]: If we want to remove this we should probably try to get this in for `12.1.0`.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 5]
```diff
@@ -375,42 +357,54 @@ private SubStrategy selectSubStrategy(Runnable task, boolean nonBlocking)
...
+                        case IDLE:
+                            if (!_state.compareAndSet(state, PRODUCING))
+                                continue;
+                            // We are the producer again, so we are not EPC
+                            return false;
+                        case PRODUCING:
+                        case REPRODUCING:
+                            if (!_state.compareAndSet(state, REPRODUCING))
+                                continue;
+                            // Somebody else is producing so we can be EPC after reducing pending count
```
Comment (lachlan-roberts) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: There is no longer a pending count.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 6]
```diff
@@ -134,7 +134,16 @@ private enum SubStrategy
     private final Executor _executor;
     private final TryExecutor _tryExecutor;
     private final Executor _virtualExecutor;
-    private final AtomicBiInteger _state = new AtomicBiInteger();
+    private final AtomicInteger _state = new AtomicInteger();
```
Comment (lachlan-roberts) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Can we just have the state as an AtomicReference to an enum now?

**Review by lachlan-roberts — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/EatWhatYouKill.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/EatWhatYouKill.java:22]: yeah... tooo late for that.  But we can remove after 12.1.0 as it has been deprecated for a long time.

**Review by lachlan-roberts — DISMISSED** [review]

**Comment by lorban** [comment]
This has no measurable perf impact in the Core API with H1: https://jenkins.webtide.net/job/load_testing/job/jetty-profiler-12.1.x/42/artifact/core/target/reports/CoreHandlerPerfTest_testNoGzipAsync/ according to our standard benchmark.

(main branch reference: https://jenkins.webtide.net/job/load_testing/job/jetty-profiler-12.1.x/41/artifact/core/target/reports/CoreHandlerPerfTest_testNoGzipFullyAsyncHandlerTree/)


There is a small degradation with H2C but it's within the error margin: https://jenkins.webtide.net/job/load_testing/job/jetty-profiler-12.1.x/47/artifact/core/target/reports/CoreHandlerPerfTest_testNoGzipAsync/server/load-master/perf.hlog.html

(main branch reference: https://jenkins.webtide.net/job/load_testing/job/jetty-profiler-12.1.x/46/artifact/core/target/reports/CoreHandlerPerfTest_testNoGzipAsync/server/load-master/perf.hlog.html)

You can also see that there's an order of magnitude more PEC executions with [this branch](https://jenkins.webtide.net/job/load_testing/job/jetty-profiler-12.1.x/47/artifact/core/target/reports/CoreHandlerPerfTest_testNoGzipAsync/server/load-master/ServerDump.txt) than with the [main branch](https://jenkins.webtide.net/job/load_testing/job/jetty-profiler-12.1.x/46/artifact/core/target/reports/CoreHandlerPerfTest_testNoGzipAsync/server/load-master/ServerDump.txt) so maybe the small degradation is due to this, even if it's still a negligible amount of jobs that are executed as PEC.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 7]
```diff
@@ -487,20 +472,39 @@ private void pcRunTask(Runnable task)
...
+    protected void epcRunTask(Runnable task)
     {
+        _epcMode.increment();
+        Integer depth = _epcDepth.get();
+        _epcDepth.set(1 + depth);
         runTask(task);
+        if (depth > 0 || !isUseVirtualThreads())
+            _epcDepth.set(depth);
+        else
+            _epcDepth.remove();
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: That `remove()` calls looks fishy as the TL would contain null afterwards and the beginning of this method does ` + 1` on an auto-unboxed value without a null check, so that could leak to a NPE.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 8]
```diff
@@ -375,42 +353,54 @@ private SubStrategy selectSubStrategy(Runnable task, boolean nonBlocking)
...
-                    if (!_state.compareAndSet(biState, pending, state))
-                        continue;
+    private boolean tryExecuteProduceConsume()
+    {
+        State state = _state.get();
 
-                    // Otherwise use PEC: the task is consumed by the executor and this producer thread continues to produce.
-                    return SubStrategy.PRODUCE_EXECUTE_CONSUME;
+        // If we are producing, not already in EPC, then try to switch to IDLE in anticipation of EPC
+        if (state != State.IDLE && _epcDepth.get() < _maxEpcDepth && _state.compareAndSet(state, State.IDLE))
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: So if a thread has recused too deeply, `tryExecute()` fails and the picked strategy is then PEC?

It feels like `tryExecuteProduceConsume()` should not be called before the stack has been unwound and this is just a workaround.

**Comment by gregw** [comment]
@sbordet can you flame graph this one again?
I'm good to commit this... but my only note of caution is the new configuration for the max depth of recursion.   Should we not expose this and just set it to a reasonable value?   We've not had any reports of stack overflow in the wild and we only observed deep stacks on a load test.  So a default of 8 or 16 should be fine.

Or should we provide a way to configure via properties/XML?  I think that is premature and we should run for a while with a preset value.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java (hunk 7 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: I believe this is the recommended approach to stop "leaking" if this code is run with a virtual thread.   Instead of setting to 0, the entry is removed.  Then when it is next access the initialiser passed in the constructor of the threadlocal provides the 0 value.  So a null is never returned from get

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java (hunk 8 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Ideally we would not produce again until the stack has unwound, but when you look at it, it is not possible.  In h2/h3 we often have tasks that produce another task, put it on a list and then call produce.    If such a task is offered to EPC, then the whole idea is to let the producer thread call it with a hot cache, but if that task then calls produce again we have recursed.      We can't not produce, because that call to produce might be part of some blocking code that calls an async method with a callback (the queued task) and then blocks waiting for that callback to be called.   So it might be that the stack will never unwind until a task is produced and consumed.

We could just never recurse at all (max depth == 1), but then we have seen the flame graph for that in cometd and it reduces EPC to about 5% of executions and we always do PEC (at least for that load profile). 

So this PR is limiting recursion depth to 8 and it will be very interesting to see how that effects the flame graph from cometd benchmarks.

Given that h2/h3 can recurse like this, it is surprising that we have not seen stack overflows.  Perhaps there have been and that results in the occasional lost message, but not enough to be reported?  Or may the stack overflow is non fatal, so long as something else continues producing?

So either we do something like this to keep EPC as a reasonable proportion of the strategies, or we give up and remove EPC and just to PC or PEC.

That's why we need to benchmark this and then the same thing with 0 reserved threads to see if EPC is still worthwhile.

Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: @lorban @sbordet thinking about this a bit more, the issue really is that the h2 producer is not blocking.   With h1, the producer blocks in select, so we have selector threads dedicated to producing.  These might call the application in PC or EPC, but the application never calls produce, as there is always a selector thread or reserved thread acting as producer).

But with h2 (and h3), the producer does not block, nor could it else we'd need a thread per connection.   So in order to do production, we have a queue with the model that you add something to the queue and then you call produce.  Thus any thread could become a producer, including the application.   Perhaps application threads should call execute rather than produce, so they ensure there is a producer, but they themselves do not become the producer.  This would remove the recursion issue, but I'm not sure at what cost.   I'll try to make a PR that does that to see, but meanwhile, I think this PR should progress as it is better than unconstrained recursion that we have now.

Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: I agree that adding a limit to the recursion is a decent stopgap solution we should merge ASAP.

Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: @lorban @sbordet I've updated this so:
 + The recursion control applies to PC, PIC and EPC.
 + If we are recursing and a reserved thread is available, then it is used to produce instead of recursing.

**Comment by gregw** [comment]
@lorban can you perf this one again with the latest changes.

**Comment by gregw** [comment]
@sbordet @lorban Can I get a review of this ASAP.  I think there is a related bug in 12.0.x (#13470), so I'd like to get feedback before backporting.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java [hunk 9]
```diff
@@ -207,13 +207,19 @@ public boolean onIdleExpired(TimeoutException timeoutException)
...
+     *                 delayed. Callers from I/O threads should use {@code false} to avoid thread hops.
+     */
     public void offerTask(Runnable task, boolean dispatch)
     {
         offerTask(task);
         if (dispatch)
             dispatch();
         else
-            produce();
+            this.produce();
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Connection.java]: Unnecessary `this.`

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java [hunk 10]
```diff
@@ -221,7 +221,10 @@ else if (!_demand)
         {
             Runnable task = _httpChannel.onContentAvailable();
             if (task != null)
-                _connection.offerTask(task, false);
+            {
+                // We must dispatch, so an application thread does not become a producer and then consume another request.
```
Comment (sbordet) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HttpStreamOverHTTP2.java]: Just compacting the comment.

```suggestion
                // We must dispatch, so an application thread does not 
                // become a producer and then consume another request.
```

File: jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java [hunk 11]
```diff
@@ -185,7 +185,10 @@ public void demand()
         {
             Runnable task = httpChannel.onContentAvailable();
             if (task != null)
-                connection.offerTask(task);
+            {
+                // we must dispatch so that an application thread does not become a producer thread.
```
Comment (sbordet) [inline jetty-core/jetty-http3/jetty-http3-server/src/main/java/org/eclipse/jetty/http3/server/internal/HttpStreamOverHTTP3.java]: Same comment as h2.
```suggestion
                // We must dispatch, so an application thread does not 
                // become a producer and then consume another request.
```

File: jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/ProtocolSession.java [hunk 12]
```diff
@@ -252,12 +252,18 @@ public void disconnect(ConnectionCloseFrame frame, Throwable failure, Promise.In
         getSession().disconnect(frame, failure, Promise.Invocable.toPromise(promise, s -> this));
     }
 
-    public void offerTask(Runnable task)
+    /**
+     * @param task The task to offer to the connection.
```
Comment (sbordet) [inline jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/ProtocolSession.java]:
```suggestion
     * @param task The task to offer to the execution strategy.
```

File: jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/QuicheSession.java [hunk 13]
```diff
@@ -372,13 +372,20 @@ protected int data(QuicheStream stream, boolean last, ByteBuffer buffer) throws
         return quiche.feedClearBytesForStream(stream.getId(), buffer, last);
     }
 
+    /**
+     * @param task  The task to offer to the connection.
```
Comment (sbordet) [inline jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/QuicheSession.java]:
```suggestion
     * @param task  The task to offer to the execution strategy.
```

File: jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/QuicheStream.java [hunk 14]
```diff
@@ -254,7 +254,7 @@ public void demand()
         // The production might have idled, as all the network
         // data was fed to Quiche, but there was no demand.
         // Restart production now that there is demand.
-        session.produce();
+        Invocable.invokeNonBlocking(session::produce);
```
Comment (sbordet) [inline jetty-core/jetty-quic/jetty-quic-quiche/jetty-quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/QuicheStream.java]: I think it is better to call `session.produce(true)`, and then have `session` call either `produce()` or `dispatch()`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/MemoryConnector.java [hunk 15]
```diff
@@ -170,7 +170,7 @@ private void offer(Invocable.Task task)
             if (LOG.isDebugEnabled())
                 LOG.debug("offer {} to {}", task, MemoryConnector.this);
             tasks.offer(task);
-            strategy.produce();
+            Invocable.invokeNonBlocking(strategy::produce);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/MemoryConnector.java]: I don't think this is necessary, `strategy.produce()` should be enough, although `dispatch()` is probably better.

In `MemoryConnector` the tasks offered here are equivalent to the read/write interest tasks produced by NIO on the peer `EndPoint`: socket A writes data, socket B is woken up with read interest, which produces a task to be run.

Given that in the network case it happens on a different host and different thread, perhaps `dispatch()` would mimic the same, although for BLOCKING tasks there would be a double handoff.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 16]
```diff
@@ -153,29 +158,39 @@ public AdaptiveExecutionStrategy(Producer producer, Executor executor)
...
+    /**
+     * PC, EPC and PIC strategies can call a task with a previous producing thread, which can then itself
+     * call {@link #produce()}. This field limits the possible recursion depth.
+     * @param maxConsumeDepth The maximum recursion depth of a thread calling EPC (default 8)
+     */
+    public void setMaxConsumeDepth(int maxConsumeDepth)
+    {
+        _maxConsumeDepth = maxConsumeDepth;
+    }
+
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Let's not make these public.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 17]
```diff
@@ -134,7 +137,9 @@ private enum SubStrategy
     private final Executor _executor;
     private final TryExecutor _tryExecutor;
     private final Executor _virtualExecutor;
-    private final AtomicBiInteger _state = new AtomicBiInteger();
+    private final AtomicReference<State> _state = new AtomicReference<>(State.IDLE);
+    private final ThreadLocal<Integer> _consumeDepth = ThreadLocal.withInitial(() -> 0);
+    private int _maxConsumeDepth = 8;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Let's run with IllegalStateException, so maxDepth=1.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 18]
```diff
@@ -260,43 +272,40 @@ private void tryProduce(boolean wasPending)
...
+                    if (consumeTask(task, selectSubStrategy(task, nonBlocking)))
+                        // continue producing
+                        continue;
+                    // do not continue producing
+                    return;
+                }
 
-                // If we did not produce a task
-                if (task == null)
+                // No task produce, so determine if we should keep producing.
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java:262]:
```suggestion
                // No task produced, so determine if we should keep producing.
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 19]
```diff
@@ -318,6 +327,9 @@ private SubStrategy selectSubStrategy(Runnable task, boolean nonBlocking)
         switch (taskType)
         {
             case NON_BLOCKING:
+                // If we are recursing too deep, then we must fall back to PEC
+                if (_consumeDepth.get() >= _maxConsumeDepth)
+                    return SubStrategy.PRODUCE_EXECUTE_CONSUME;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Remove this if we throw ISE.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 20]
```diff
@@ -375,42 +361,54 @@ private SubStrategy selectSubStrategy(Runnable task, boolean nonBlocking)
...
-                    return SubStrategy.PRODUCE_EXECUTE_CONSUME;
+        // If we are producing, not already in EPC, then try to switch to IDLE in anticipation of EPC
+        if (state != State.IDLE && _consumeDepth.get() < _maxConsumeDepth && _state.compareAndSet(state, State.IDLE))
+        {
+            // If we can execute another producer, then we are EPC
+            if (_tryExecutor.tryExecute(this))
+                return true;
+
+            // No reserved thread available, so we need to try to return to production
+            if (!_state.compareAndSet(State.IDLE, State.PRODUCING))
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Unnecessary `if`, the `while` loop should cover this `if`.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 21]
```diff
@@ -375,42 +361,54 @@ private SubStrategy selectSubStrategy(Runnable task, boolean nonBlocking)
...
-                    if (!_state.compareAndSet(biState, pending, state))
-                        continue;
+    private boolean tryExecuteProduceConsume()
+    {
+        State state = _state.get();
 
-                    // Otherwise use PEC: the task is consumed by the executor and this producer thread continues to produce.
-                    return SubStrategy.PRODUCE_EXECUTE_CONSUME;
+        // If we are producing, not already in EPC, then try to switch to IDLE in anticipation of EPC
+        if (state != State.IDLE && _consumeDepth.get() < _maxConsumeDepth && _state.compareAndSet(state, State.IDLE))
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Review if we throw ISE

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 22]
```diff
@@ -375,42 +361,54 @@ private SubStrategy selectSubStrategy(Runnable task, boolean nonBlocking)
...
+                    state = _state.get();
+                    switch (state)
+                    {
+                        case IDLE:
+                            if (!_state.compareAndSet(state, State.PRODUCING))
+                                continue;
+                            // We are the producer again, so we are not EPC
+                            return false;
+                        case PRODUCING:
+                        case REPRODUCING:
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Just `return` if `REPRODUCING`?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 23]
```diff
@@ -477,8 +469,9 @@ private boolean consumeTask(Runnable task, SubStrategy subStrategy)
      *
      * @param task the task to run
      */
-    private void pcRunTask(Runnable task)
+    protected void pcRunTask(Runnable task)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Make them `private` again.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 24]
```diff
@@ -487,35 +480,59 @@ private void pcRunTask(Runnable task)
...
     /**
      * Runs a task in produce-invoke-consume mode.
      *
      * @param task the task to run
      */
-    private void picRunTask(Runnable task)
+    protected void picRunTask(Runnable task)
     {
+        Integer depth = _consumeDepth.get();
+        _consumeDepth.set(1 + depth);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Use `boolean` to avoid allocation now that we throw ISE.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/strategy/ExecutionStrategyTest.java [hunk 25]
```diff
@@ -220,4 +221,46 @@ public Runnable produce()
...
         LifeCycle.stop(threadPool);
     }
+
+    @ParameterizedTest
+    @MethodSource("pooledStrategies")
+    public void recursiveTest(Class<? extends ThreadPool> threadPoolClass, Class<? extends ExecutionStrategy> strategyClass) throws Exception
+    {
+        ThreadPool threadPool = threadPoolClass.getDeclaredConstructor().newInstance();
+        LifeCycle.start(threadPool);
+        System.err.printf("threadPool=%s%n", threadPool);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/strategy/ExecutionStrategyTest.java]: Remove.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/strategy/ExecutionStrategyTest.java [hunk 26]
```diff
@@ -220,4 +221,46 @@ public Runnable produce()
 
         LifeCycle.stop(threadPool);
     }
+
+    @ParameterizedTest
+    @MethodSource("pooledStrategies")
+    public void recursiveTest(Class<? extends ThreadPool> threadPoolClass, Class<? extends ExecutionStrategy> strategyClass) throws Exception
```
Comment (sbordet) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/thread/strategy/ExecutionStrategyTest.java]: Rename to `testRecursion()` and use `dispatch()` instead.

Also add a test for the throw of the ISE.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by lorban** [comment]
@gregw I've pushed the extra EPC stat.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java [hunk 27]
```diff
@@ -133,14 +133,11 @@ private enum SubStrategy
     private final LongAdder _picMode = new LongAdder();
     private final LongAdder _pecMode = new LongAdder();
     private final LongAdder _epcMode = new LongAdder();
-    private final LongAdder _epcProduce = new LongAdder();
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: Mind to explain your reasoning why you removed that new stat counter?

Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/thread/strategy/AdaptiveExecutionStrategy.java]: @lorban ahhhh merge oopsie.  Can you fix again.  If not, I'll do so in the morning

**Review by sbordet — APPROVED** [review]

**Review by lorban — DISMISSED** [review]

**Comment by sbordet** [comment]
@gregw please review the latest changes that @lorban and I made.

**Comment by sbordet** [comment]
@gregw while testing this, we still found recursion happening.

It happens when `HttpStreamOverHTTP2.demand()` calls `HTTP2Stream.demand()`: it may happen that the stream has data, so it will eventually notify `HttpStreamOverHTTP2.onDataAvailable()`, which returns a task that is offered without dispatching.

The problem is that `HttpStreamOverHTTP2.onDataAvailable()` is designed to be called from the lower layer (and as such would not need to dispatch tasks), but it may also be called from the upper layer as explained above.

@lorban and I pushed two alternative solutions in different branches:

1. `jetty-12.1.x-simplifiedEPC-no-pending-demand-threadlocal`, where a `ThreadLocal` is used to detect whether `HttpStreamOverHTTP2.onDataAvailable()` is called from `HttpStreamOverHTTP2.demand()`, and if so dispatch.
1. `jetty-12.1.x-simplifiedEPC-no-pending-demand-executor` where `HTTP2Stream.demand()` always executes the call to `processData()`. Before it was possible that the thread calling `demand()` would call `onDataAvailable()`, now it's always another thread calling `onDataAvailable()`.

Apparently, solution 1. has a slightly better performance, but so far they are just experiments and we need more data.

I punted this PR to 12.1.2, because it needs more discussion and more testing.

**Review by sbordet — CHANGES_REQUESTED** [review]
Recursion still happening, see comment.

**Comment by gregw** [comment]
@sbordet @lorban should we put general recursion detection back in and just dispatch if we recurse?

**Comment by sbordet** [comment]
@gregw that would be solution 1. above, I think?

**Comment by gregw** [comment]
@sbordet @lorban Ignore my comment about "general recursion detection", as this recursion is not via the execution strategy, so it does not apply.

In this case, it would actually be harmless to allow a little bit of recursion.   So if we go with solution 1. with a ThreadLocal, then it may as well count recursions and allow N before executing.
If we don't want any recursion, then solution 2. looks cleaner, but I can see why it is slower as it is always dispatching, even if there is no recursion at all.

So I'm probably leaning towards solution 1, with N defaulting to a small number (maybe 1).

However, would it be worthwhile to look at the Invocation type of the task, and if non-blocking (say a wakeup of a blocking call), then call directly?   I guess typically we'd have a full execution strategy here... perhaps overkill, but we could do a lite version?

**Comment by gregw** [comment]
@sbordet I committed this change to solution 1:
```java

        Runnable task = _httpChannel.onContentAvailable();
        if (task == null)
            return null;
        return switch (Invocable.getInvocationType(task))
        {
            case BLOCKING ->
            {
                if (DEMANDING.get() != Boolean.TRUE) 
                    yield task;
                _connection.offerTask(task, true);
                yield null;
            }
            case NON_BLOCKING -> task;
            case EITHER -> () -> Invocable.invokeNonBlocking(task);
        };
```

**Comment by gregw** [comment]
@sbordet @lorban I've got an alternative approach in `jetty-12.1.x-simplifiedEPC-no-pending-demand-threadlocal-dispatch`.  I use the threadlocal to detect if we are DEMANDING and use that to set the dispatch boolean arg

**Comment by gregw** [comment]
@sbordet @lorban I've now pushed (to this PR) a 4th approach, so now we have:

1. `jetty-12.1.x-simplifiedEPC-no-pending-demand-threadlocal`, where a `ThreadLocal` is used to detect whether `HttpStreamOverHTTP2.onDataAvailable()` is called from `HttpStreamOverHTTP2.demand()`, and if so dispatch.
2. `jetty-12.1.x-simplifiedEPC-no-pending-demand-executor` where `HTTP2Stream.demand()` always executes the call to `processData()`. Before it was possible that the thread calling `demand()` would call `onDataAvailable()`, now it's always another thread calling `onDataAvailable()`.
3. `jetty-12.1.x-simplifiedEPC-no-pending-demand-threadlocal-dispatch`, similar to 1. where a `ThreadLocal` is used to detect `demand()` calls, but in this case it is used to set the existing `dispatch` arg on the `offerTask(Runnable,boolean)` method
4. `jetty-12.1.x-simplifiedEPC-no-pending` (this PR) in which an extended Stream.Listener interface is used to pass the `dispatch` argument down from the implementation of `demand()` to the existing `dispatch` arg on the `offerTask(Runnable,boolean)` method

I think 2. is a non starter, as it always executes even if there is already a producer  (as would be the case if the current task is NON_BLOCKING).
Both 1. and 3. are OK, but using a `ThreadLocal` has a cost and there are issues with virtual threads.
I think 4. is best, even though it perverts the API a little bit.

**Comment by janbartel** [comment]
Is this anywhere nearing a resolution? This has been ongoing since 22 July, and there are real-world bug reports relying on it. Can we focus on this and bring to a reasonable conclusion?

**Comment by gregw** [comment]
> Is this anywhere nearing a resolution? This has been ongoing since 22 July, and there are real-world bug reports relying on it. Can we focus on this and bring to a reasonable conclusion?

I'm pretty happy with solution 4. (in this PR)..... other than the branch has gone stale with unrelated changes from head that I'm hopefully fixing.
As there is no new public API, can we just merge that and fix the problem, then optimise from there?

I probably need to back-port some of this to 12.0.x

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java [hunk 28]
```diff
@@ -886,12 +886,17 @@ private void notifyHeaders(HeadersFrame frame, Callback callback)
...
-    private void notifyDataAvailable()
+    private void notifyDataAvailable(boolean dispatch)
     {
         Listener listener = Objects.requireNonNullElse(getListener(), Listener.AUTO_DISCARD);
         try
         {
-            listener.onDataAvailable(this);
+            if (listener instanceof DispatchableListener dispatchableListener)
+                dispatchableListener.onDataAvailable(this, dispatch);
+            else if (dispatch && session.getEndPoint().getConnection() instanceof HTTP2Connection h2c)
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java]: Wouldn't `session.getEndPoint().getConnection() instanceof HTTP2Connection` always be true?

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java [hunk 29]
```diff
@@ -1053,4 +1058,9 @@ public List<StreamFrame> getFrames()
             return frames;
         }
     }
+
+    public interface DispatchableListener extends Stream.Listener
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java]: This interface should have javadoc explaining it's needed for backward compatibility reasons.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java [hunk 30]
```diff
@@ -1053,4 +1058,9 @@ public List<StreamFrame> getFrames()
...
+    {
+        void onDataAvailable(Stream stream, boolean dispatch);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java]: This method should have javadoc, at least to explain the `boolean dispatch` parameter and the the fact that it solves a recursion problem.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java [hunk 31]
```diff
@@ -537,23 +537,23 @@ public Data readData()
...
+                dispatch = true;
             }
         }
         if (LOG.isDebugEnabled())
-            LOG.debug("Demand, {} data processing for {}", process ? "proceeding" : "stalling", this);
-        if (process)
-            processData();
+            LOG.debug("Demand, {} data processing for {}", dispatch ? "proceeding" : "stalling", this);
+        if (dispatch)
+            processData(true);
```
Comment (lorban) [inline jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java:559]: I'd like a comment explaining why we must dispatch here, similar to the one in `HttpStreamOverHTTP2`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java [hunk 32]
```diff
@@ -75,7 +75,7 @@ public void setInputBufferSize(int inputBufferSize)
         _inputBufferSize = inputBufferSize;
     }
 
-    protected Executor getExecutor()
+    public Executor getExecutor()
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/AbstractConnection.java]: I would leave this method `protected` and override it in `HTTP2Connection` to change the visibility to public, like we do in `WebSocketConnection`.

File: jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/ProtocolSession.java [hunk 33]
```diff
@@ -252,12 +252,18 @@ public void disconnect(ConnectionCloseFrame frame, Throwable failure, Promise.In
...
+     * Callers from application threads should use {@code true}, otherwise they may be arbitrarily
+     * delayed. Callers from I/O threads should use {@code false} to avoid thread hops.
+     */
+    public void offerTask(Runnable task, boolean dispatch)
     {
         if (task == null)
             return;
         AbstractSession session = (AbstractSession)getSession();
-        session.offerTask(task);
+        session.offerTask(task, false);
```
Comment (lorban) [inline jetty-core/jetty-quic/jetty-quic-common/src/main/java/org/eclipse/jetty/quic/common/ProtocolSession.java]: Shouldn't the 2nd parameter be `dispatch`?

**Review by lorban — CHANGES_REQUESTED** [review]
There are a few nits and some lack of javadoc, but overall this looks good.

File: jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java (hunk 28 above)
Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java]: probably, but no harm checking.

Comment (lorban) [reply jetty-core/jetty-http2/jetty-http2-common/src/main/java/org/eclipse/jetty/http2/HTTP2Stream.java]: This cast to `HTTP2Connection` makes me believe that the executor should actually be injected via the constructor.

**Review by lorban — DISMISSED** [review]
There is that annoying cast in `HTTP2Stream` which hints that the executor should be injected via the constructor, but this PR has already been in progress for too long so I won't hold the merge because of that reason.

Otherwise, LGTM.

**Comment by sbordet** [comment]
@gregw I liked the proposal of having `onDataAvailable(Stream, boolean)`, because the knowledge of the `boolean` is in the low-level APIs.

I lifted that method into the `Stream.Listener` API (and removed `DispatchableListener`), so now it's what the implementation calls.
Only in two places we override it (when we want to move to the upper HTTP layer in the client and the server).
All the rest of the API still overrides the old version, but that's fine, as they don't have execution strategy problems, and recursion was always avoided.

I also updated in the same way HTTP/3 and QUIC, which are based on similar APIs.

@lorban [this run](https://jenkins.webtide.net/job/load_testing/job/jetty-profiler-12.1.x/217/), based on this PR, does not show "recursion", but neither does [this other run](https://jenkins.webtide.net/job/load_testing/job/jetty-profiler-12.1.x/218/), based on 12.1.x HEAD.

I remember "recursion" to be really visible, but I cannot recall exactly what parameters were necessary to reproduce it?

**Review by sbordet — DISMISSED** [review]

**Comment by gregw** [comment]
@sbordet please approve again.  Also @lorban

**Review by sbordet — APPROVED** [review]
