### PR TITLE
Fix CachingHttpContentFactory$CachedHttpContent already released buffer

### LINKED ISSUE #12681: CachingHttpContentFactory$CachedHttpContent already released buffer
**Jetty version(s)**
12.1.x

**Jetty Environment**
EE11

**Description**

Whilst developing PR https://github.com/jetty/jetty.project/pull/12678, I have woken up `org.eclipse.jetty.servlet6.embedded.Http2Server` even though there is no `PushCacheFilter` anymore.  The intention is to convert it to early hints instead.

However, whilst running the draft Http2Server, I often get exceptions like below when serving the tiles:
```
2025-01-09 10:46:54.482:WARN :oejs.ResourceService:qtp100555887-48: Failed to serve resource: /tiles/tile19.jpg
java.lang.IllegalStateException: already released ReferenceCounter@650e7559[r=0]
	at org.eclipse.jetty.io.Retainable$ReferenceCounter.lambda$release$2(Retainable.java:226)
	at java.base/java.util.concurrent.atomic.AtomicInteger.updateAndGet(AtomicInteger.java:281)
	at org.eclipse.jetty.io.Retainable$ReferenceCounter.release(Retainable.java:223)
	at org.eclipse.jetty.io.Retainable$Wrapper.release(Retainable.java:149)
	at org.eclipse.jetty.io.ArrayByteBufferPool$PooledBuffer.release(ArrayByteBufferPool.java:665)
	at org.eclipse.jetty.http.content.CachingHttpContentFactory$CachedHttpContent.writeTo(CachingHttpContentFactory.java:365)
	at org.eclipse.jetty.server.ResourceService.sendData(ResourceService.java:669)
	at org.eclipse.jetty.server.ResourceService.doGet(ResourceService.java:206)
	at org.eclipse.jetty.ee11.servlet.ResourceServlet.doGet(ResourceServlet.java:545)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:633)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.eclipse.jetty.ee11.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee11.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1666)
	at org.eclipse.jetty.servlet6.embedded.Http2Server$PushedTilesFilter.doFilter(Http2Server.java:153)
	at org.eclipse.jetty.ee11.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee11.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1638)
	at org.eclipse.jetty.ee11.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1599)
	at org.eclipse.jetty.ee11.servlet.ServletChannel.dispatch(ServletChannel.java:802)
	at org.eclipse.jetty.ee11.servlet.ServletChannel.handle(ServletChannel.java:439)
	at org.eclipse.jetty.ee11.servlet.ServletHandler.handle(ServletHandler.java:469)
	at org.eclipse.jetty.ee11.servlet.SessionHandler.handle(SessionHandler.java:763)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1064)
	at org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:673)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:411)
	at org.eclipse.jetty.server.internal.HttpConnection$FillableCallback.succeeded(HttpConnection.java:1688)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:480)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:443)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

**How to reproduce?**

run the `Http2Server` class, hit http://localhost:8080, do shift reload a few times

### PR DESCRIPTION
**Pull request by lorban**
Atomically retain the buffer with a check that it still is in the cache, otherwise delegate to the wrapped content.

Fixes #12681

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java [hunk 1]
```diff
@@ -354,19 +353,39 @@ public String getKey()
...
                 callback.failed(x);
             }
         }
 
+        /**
+         * Atomically checks that this content still is in cache (so it hasn't been released yet and is still usable) and retain
+         * its internal buffer if it is.
+         * @return true if this content can be used and has been retained, false otherwise.
+         */
+        private boolean retain()
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: Can you rename this to 
```suggestion
        private boolean cachedRetain()
```

**Review by gregw — CHANGES_REQUESTED** [review]

**Comment by gregw** [comment]
@lorban also is there a version of this for 12.0?

**Comment by gregw** [comment]
I merged this to #12678 to check it works with the demos.  All good there.

**Review by sbordet — APPROVED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: Done.

**Comment by lorban** [comment]
@gregw I backported this fix to 12.0.x here: https://github.com/jetty/jetty.project/pull/12710

The logic is sightly different as 12.0 does not have a `writeTo()`  method but exposes `retain()` instead. It's quite ugly but since it's 12.0 only I think it's alright.

Merging both PRs to 12.1 is going to be fun!

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java [hunk 2]
```diff
@@ -366,19 +365,39 @@ public String getKey()
...
                 callback.failed(x);
             }
         }
 
+        /**
+         * Atomically checks that this content still is in cache (so it hasn't been released yet and is still usable) and retain
+         * its internal buffer if it is.
+         * @return true if this content can be used and has been retained, false otherwise.
+         */
+        private boolean cachedRetain()
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: I don't like this name, feels like "cache a retain operation"... what's wrong with just `retain()`, it is exactly what it does, and it is already on the class `CachedHttpContent`, so there is no confusion.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: How about `retainIfCached()`?

**Comment by lorban** [comment]
@sbordet @gregw please come to an agreement about the private `cachedRetain()` method's name.

**Comment by gregw** [comment]
> @sbordet @gregw please come to an agreement about the private `cachedRetain()` method's name.

I agree that `cachedRetain()` is not good.  But I do think `retainIfCached` is a much clearer name than just `retain`.  We have many `retain` methods and none of them do logic like this method, nor return a boolean.
Another alternative could be `tryRetain`

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: In the backport for Jetty 12, it is just `retain()`.

`retainIfCached()` would read strange because it would always be called in an `if` statement, so `if (retainIfCached())` with the double `if`.

I guess I could be fine with the double `if`, but I really don't see why calling it differently from `retain()`.

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: @sbordet what about tryRetain?

It is different from all our other retain because it may not retain and it breaks the contract for one release for every retain call

Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: `tryRetain()` it is.

**Review by gregw — APPROVED** [review]
