### PR TITLE
NPE protection on WebInfConfiguration.deconfigure()

### LINKED ISSUE #5480: NPE from WebInfConfiguration.deconfigure during WebAppContext shutdown
**Jetty version**
9.4.x

**Description**
When shutting down WebAppContext, there occasionally is seen a NullPointerException.

```
java.lang.NullPointerException
	at org.eclipse.jetty.util.IO.delete(IO.java:368)
	at org.eclipse.jetty.webapp.WebInfConfiguration.deconfigure(WebInfConfiguration.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1433)
	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:1115)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:297)
	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:547)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
```

### PR DESCRIPTION
**Pull request by joakime**
* NPE protection on IO.delete(File)
* Fail in jetty-maven-plugin if unable to create temp directory.
* NPE protection in WebInfConfiguration.deconfigure()
* Removing Temp dir forced deletion in WebInfConfiguration.configureTempDirectory()

### CODE REVIEW

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java [hunk 1]
```diff
@@ -522,21 +522,16 @@ public void configureTempDirectory(File dir, WebAppContext context)
         if (dir == null)
             throw new IllegalArgumentException("Null temp dir");
 
-        //if dir exists and we don't want it persisted, delete it
-        if (dir.exists() && !context.isPersistTempDirectory())
+        // if it doesn't exist make it
```
Comment (janbartel) [inline jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:535]: I'm not sure about this .... we need to check that if the dir should not be persisted then anything that is already in it should be removed before we try and unpack the webapp into it.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java [hunk 2]
```diff
@@ -522,21 +522,16 @@ public void configureTempDirectory(File dir, WebAppContext context)
...
 
-        //if it doesn't exist make it
-        if (!dir.exists())
-            dir.mkdirs();
-
-        if (!context.isPersistTempDirectory())
-            dir.deleteOnExit();
-
-        //is it useable
+        // is it useable
```
Comment (janbartel) [inline jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:552]: You need to keep the if (!context.isPersistTempDirectory) dir.deleteOnExit.

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java [hunk 3]
```diff
@@ -522,21 +522,16 @@ public void configureTempDirectory(File dir, WebAppContext context)
         if (dir == null)
             throw new IllegalArgumentException("Null temp dir");
 
-        //if dir exists and we don't want it persisted, delete it
-        if (dir.exists() && !context.isPersistTempDirectory())
+        // if it doesn't exist make it
+        if (!dir.exists())
```
Comment (gregw) [inline jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:536]: You've changed the logic here.   This was always deleting and recreating a non persistent temp dir.

We  don't want to do that any more because of hijacking!   But I think we have to ensure the tempdir is empty if it is not persistent.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java [hunk 4]
```diff
@@ -355,7 +355,7 @@ public void configure(WebAppContext context) throws Exception
     public void deconfigure(WebAppContext context) throws Exception
     {
         //if we're not persisting the temp dir contents delete it
-        if (!context.isPersistTempDirectory())
+        if (!context.isPersistTempDirectory() && context.getTempDirectory() != null && context.getTempDirectory().exists())
```
Comment (gregw) [inline jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java]: assign `getTempDirectory()` to a variable

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 1 above)
Comment (joakime) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:535]: But we cannot remove it arbitrarily here, only under small circumstance will removing the directory itself be safe.

This step isn't really necessary as both the WebInfConfiguration.deconfigure() and the Temp directory specific File.deleteOnExit() both cover the deletion angle.

As an alternative, we could simply clear out the directory contents.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 2 above)
Comment (joakime) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:552]: That's covered in makeTempDirectory() already.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 1 above)
Comment (gregw) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:535]: yep I think we need to clear it out

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 2 above)
Comment (joakime) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:552]: Scratch that, i'm wrong about this specific one.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 1 above)
Comment (janbartel) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:535]: Yes, I'd prefer to clear out the directory contents, and leave the dir in place.

This is safeguarding if the previous deconfigure() failed, and deleteOnExit might not come into play because you're just restarting the context/server without restarting the jvm.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 2 above)
Comment (janbartel) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:552]: No, it's also called directly by resolveTempDirectory in the case where someone has explicitly supplied the temp directory to use or the javax.servlet.context.tempDir has been set - whether these are persisted or not is optional and configured by configureTempDirectory.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 1 above)
Comment (joakime) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:535]: The temp directory deletion block has been restored.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 2 above)
Comment (joakime) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:552]: deleteOnExit has been restored.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java [hunk 5]
```diff
@@ -504,13 +506,15 @@ public void makeTempDirectory(File parent, WebAppContext context)
...
             tmpDir = new File(parent, temp);
+            configureTempDirectory(tmpDir, context);
         }
         else
         {
-            //ensure file will always be unique by appending random digits
+            // ensure dir will always be unique by having classlib generate random path name
             tmpDir = Files.createTempDirectory(parent.toPath(), temp).toFile();
+            tmpDir.deleteOnExit();
+            ensureTempDirUsable(tmpDir);
```
Comment (joakime) [inline jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:516]: This execution path does not use `configureTempDirectory`.
It's always a new, and unique, directory.
Also, it is always `!isPersisTempDirectory()`

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java [hunk 6]
```diff
@@ -504,13 +506,15 @@ public void makeTempDirectory(File parent, WebAppContext context)
             //if it is to be persisted, make sure it will be the same name
             //by not using File.createTempFile, which appends random digits
             tmpDir = new File(parent, temp);
+            configureTempDirectory(tmpDir, context);
```
Comment (gregw) [inline jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:509]: probably should now be called `ensureTempDirectory` ?

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 1 above)
Comment (joakime) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:535]: About the concern about prior directory (example given is context/server restart) ... 
The `Files.createTempDirectory` path (or the older `File.createTempFile` path), this delete would never have deleted the prior directory, as each time you enter this block you have a new directory path.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java [hunk 7]
```diff
@@ -522,21 +526,30 @@ public void configureTempDirectory(File dir, WebAppContext context)
         if (dir == null)
             throw new IllegalArgumentException("Null temp dir");
 
-        //if dir exists and we don't want it persisted, delete it
-        if (dir.exists() && !context.isPersistTempDirectory())
+        // if dir exists and we don't want it persisted, delete it
+        if (!context.isPersistTempDirectory() && dir.exists() && !IO.delete(dir))
```
Comment (gregw) [inline jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:530]: how hard is it to check if it is empty or not.   if it is empty, it would be good to avoid deleting it.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 4 above)
Comment (joakime) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java]: Done.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 6 above)
Comment (joakime) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:509]: This is a public API / method, don't want to change it for 9.4.x.
Be happy to change it for 10.0.x though.

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 7 above)
Comment (joakime) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:530]: Not to terrible to check if empty.
Let me try.

**Review by janbartel — APPROVED** [review]
LGTM

**Review by gregw — APPROVED** [review]

File: jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java (hunk 7 above)
Comment (joakime) [reply jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebInfConfiguration.java:530]: This has been implemented and is available in this PR.
