### PR TITLE
ForwardedRequestCustomizer behavior should not be applied to requests without forwarding headers

### LINKED ISSUE #5437: ForwardingRequestCustomizer can change request.metadata even if there are no Forwarding headers present
**Jetty version**
9.4.32.v20200930

**Description**

Originally spotted by @bentmann on commit https://github.com/eclipse/jetty.project/commit/ac42cbd1436f6a161ef03e1ca7f9c4a2bf686933#r43135647

The `ForwardingRequestCustomizer` can change request.metadata even if there are no Forwarding headers present.

The example given is a Request with ...

* No Forwarding headers.
* An absolute Request URI in the HTTP request line.  `GET https://localhost:12345`
* ForwardingRequestCustomizer impacts the proto / scheme of the request.metadata.
* SecureRequestCustomizer runs and doesn't see the correct proto / scheme and fails to run also.

### LINKED ISSUE #5443: Request without Host header fails with NullPointerException in ForwardedRequestCustomizer
**Jetty version**
9.4.32.v20200930

**Java version**
11

**OS type/version**
Red Hat Enterprise Linux Server 7

**Description**
Requests (Healthcheck probes) using HTTP/1.0 without Host header started to fail after upgrade from 9.4.31.v20200723 to 9.4.32.v20200930 with http-forwarded module enabled.

Steps to reproduce:

1. Vanilla distribution 9.4.32.v20200930.
2. Add _--module=http-forwarded_ to start.ini.
3. Start jetty.
4. _curl "http://localhost:8080/" --http1.0 -H 'Host:' -v_

Same test with 9.4.31.v20200723 does not fail.

[NPE_ForwardedRequestCustomizer.txt](https://github.com/eclipse/jetty.project/files/5370253/NPE_ForwardedRequestCustomizer.txt)

### PR DESCRIPTION
**Pull request by joakime**
If the request has no Forwarding headers, the customization that ForwardingRequestCustomizer typically does should be skipped.

Closes #5443 

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java [hunk 1]
```diff
@@ -461,81 +461,88 @@ public void customize(Connector connector, HttpConfiguration config, Request req
...
+            }
 
-        // Set authority
-        String host = null;
-        int port = -1;
+            // Set Scheme from configured protocol
+            if (forwarded._proto != null)
+            {
+                proto = forwarded._proto;
+                request.setScheme(proto);
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: why setting here and not below?

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java [hunk 2]
```diff
@@ -461,81 +461,88 @@ public void customize(Connector connector, HttpConfiguration config, Request req
...
 
-        // Set Remote Address
-        if (forwarded.hasFor())
-        {
-            int forPort = forwarded._for._port > 0 ? forwarded._for._port : request.getRemotePort();
-            request.setRemoteAddr(InetSocketAddress.createUnresolved(forwarded._for._host, forPort));
+            // Set secure status
+            if (forwarded.isSecure() ||
+                proto.equalsIgnoreCase(config.getSecureScheme()) ||
+                port == getSecurePort(config))
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: I'm don't think that just because it arrives on the secure port is sufficient to make it secure.  Some ports might do both secure and insecure requests.

**Review by gregw — CHANGES_REQUESTED** [review]
The proto and secure logic is spread out too much and too convoluted.
I think it should just be in one spot and should be something like:
```java
    if (forwarded._proto != null)
    {
      request.setScheme(forwarded._proto);
      if (forwarded._proto.equalsIgnoreCase(config.getSecureScheme())
        request.setSecure(true);
    }
    if (forwarded.isSecure())
    {
        request.setSecure(true);
        if (forwarded._proto == null)
          request.setScheme(config.getSecureScheme());
    }
```

that might not be exactly right... but you get the idea.  Put it all in one spot and try to separate concerns as much as possible.

**Comment by gregw** [comment]
Isn't this for #5437 not #5443 ???

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java [hunk 3]
```diff
@@ -461,81 +461,88 @@ public void customize(Connector connector, HttpConfiguration config, Request req
...
             {
                 onError(field, t);
             }
         }
 
-        String proto = "http";
-
-        // Is secure status configured from headers?
-        if (forwarded.isSecure())
+        if (match)
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java:482]: I don't think this match logic should be required.   There are many headers and some are orthogonal to others, so the logic below must be robust and can't be gated by a match, which may be for an unrelated header.

In the OPs case, proto must not be changed unless there is an explicit header that changes it - either giving a proto or forcing secure.

Perhaps this match is an optimisation to avoid several ifs below, but I don't think it is necessary as this customizer is typically only deployed when all request will have such a header.

Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java:482]: The match logic here (in jetty-9.4.x) was taken from jetty-10.0.x.

https://github.com/eclipse/jetty.project/blame/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java#L464-L482

The idea behind it is that if there's no Forwarding headers (even those not-quite-forwarding headers `X-Proxied-Https`, `Proxy-auth-cert`, and `Proxy-ssl-id` that ForwardingRequestCustomizer also pays attention to) then there should be no action taken by ForwardingRequestCustomizer, as the incoming request is not based on forwarding.

**Comment by joakime** [comment]
> Isn't this for #5437 not #5443 ???

Issue #5437 is about this kind of request ...

```
GET https://localhost:12345 HTTP/1.1
Host: localhost
```

A request with no forwarding headers, a fully qualified URL in the request-line, with https.
Which altered the scheme/proto in the wrong way.

Which is a (modified) test case in this PR ...

https://github.com/eclipse/jetty.project/blob/0b646ee6b78c5e4e1dff6ddbf641b839360d8a87/jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java#L178-L186

This testcase is just to prevent regression in the future.  

But the fix was actually handled in PR #5419 

The fix to not act if there are no forwarding headers, which is what this PR covers, also addresses this above example, not changing the request.metadata if there's no forwarding headers. (so in essence issue #5437 was fixed in two different ways).

Issue #5443 is about an NPE when there are no forwarding headers and the Host is empty (example in issue is given in HTTP/1.0)

Which is two test cases in this PR ...

https://github.com/eclipse/jetty.project/blob/0b646ee6b78c5e4e1dff6ddbf641b839360d8a87/jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java#L138-L157

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java (hunk 1 above)
Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: The `forwarded._proto` tracking value is set from 3 different scenarios.

1. `X-Forwarded-Proto: <value>` header.
2. `X-Proxied-Https: on` sets it to `https`.
3. `Forwarding: proto=<value>` header.

So this one that you highlighted is correct.

The below action is to handle the not-quite-forwarding-headers oddball cases.

https://github.com/eclipse/jetty.project/blob/0b646ee6b78c5e4e1dff6ddbf641b839360d8a87/jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java#L731-L743

Which has the `ForwardingRequestCustomizer.setSslIsSecure(true)` which should trigger both the proto/scheme to `https` and the `request.setSecure(true)` if the `Proxy-Ssl-Id` or `Proxy-auth-cert` headers are present.

Let me see if I can simplify this a bit.

**Review by gregw — APPROVED** [review]

**Comment by bentmann** [comment]
Thank you!
