### PR TITLE
Issue #6020 Fix redeploy error jetty-maven-plugin

### LINKED ISSUE #6020: Review Jetty Maven Plugin scanning defaults
**Jetty version**
10.0.x

**Description**
By default, the Jetty Maven Plugin has `scan=0` which means when running `jetty:run` on a terminal, the following is printed:

```
Hit <enter> to redeploy:
```

However, this default is confusing because hitting `<enter>` on the terminal is useful to separate start-up log lines from application log lines, or application log lines between different requests.

Setting `scan=5` disables the above "hit enter" but prints:

```
[INFO] Scan interval ms = 5
```

The time unit is wrong, should be `seconds`.

Then, modifying `web.xml` and waiting for the re-scan, the following is printed:

```
[INFO] Restarting o.e.j.m.p.MavenWebAppContext@2c54c497{CometD Test WebApp,/,[file:///home/simon/opensource/cometd/cometd6/cometd-demo/src/main/webapp/, file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-dojo-6_0_2-SNAPSHOT_war/, file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-jquery-6_0_2-SNAPSHOT_war/, file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-angular-6_0_2-SNAPSHOT_war/, file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-examples-dojo-6_0_2-SNAPSHOT_war/, file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-examples-jquery-6_0_2-SNAPSHOT_war/, file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-examples-angular-6_0_2-SNAPSHOT_war/, file:///home/simon/opensource/cometd/cometd6/cometd-demo/target/jetty_overlays/cometd-javascript-examples-vanilla-6_0_2-SNAPSHOT_war/],AVAILABLE}{file:///home/simon/opensource/cometd/cometd6/cometd-demo/src/main/webapp/}
[INFO] Classes = /home/simon/opensource/cometd/cometd6/cometd-demo/target/classes
[ERROR] Error reconfiguring/restarting webapp after change in watched files
java.lang.InterruptedException: sleep interrupted
    at java.lang.Thread.sleep (Native Method)
    at org.eclipse.jetty.maven.plugin.MavenWebAppContext.doStop (MavenWebAppContext.java:340)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop (AbstractLifeCycle.java:132)
    at org.eclipse.jetty.maven.plugin.JettyRunMojo.restartWebApp (JettyRunMojo.java:339)
    at org.eclipse.jetty.maven.plugin.JettyRunMojo$2.filesChanged (JettyRunMojo.java:194)
    at org.eclipse.jetty.util.Scanner.reportBulkChanges (Scanner.java:824)
    at org.eclipse.jetty.util.Scanner.reportDifferences (Scanner.java:735)
    at org.eclipse.jetty.util.Scanner.scan (Scanner.java:628)
    at org.eclipse.jetty.util.Scanner$ScanTask.run (Scanner.java:140)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:304)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:630)
    at java.lang.Thread.run (Thread.java:831)
```

### PR DESCRIPTION
**Pull request by janbartel**
Closes #6020

* Use TimerScheduler instead of ScheduledExecutorScheduler as the latter produces InterruptedException
*  Fix startup message of scan from ms to secs

### CODE REVIEW

File: jetty-util/src/main/java/org/eclipse/jetty/util/Scanner.java [hunk 1]
```diff
@@ -516,7 +516,7 @@ public void doStart() throws Exception
 
 
         //Create the scheduler and start it
-        _scheduler = new ScheduledExecutorScheduler("Scanner-" + SCANNER_IDS.getAndIncrement(), true, 1);
+        _scheduler = new TimerScheduler("Scanner-" + SCANNER_IDS.getAndIncrement(), true);
```
Comment (sbordet) [inline jetty-util/src/main/java/org/eclipse/jetty/util/Scanner.java]: We want to move away from `Timer` as it's not configurable, has problems, etc. so this needs to go back to `ScheduledExecutorScheduler`.

Test case?

**Review by sbordet — CHANGES_REQUESTED** [review]
One of the main points of the issue is to change the default for `scan`, and it's not been addressed?

File: jetty-util/src/main/java/org/eclipse/jetty/util/Scanner.java (hunk 1 above)
Comment (janbartel) [reply jetty-util/src/main/java/org/eclipse/jetty/util/Scanner.java]: The problem is that the ScheduledExecutorScheduler doesn't work: it interrupts its threads and throws the error you originally reported. The TimerScheduler doesn't manage its threads in that fashion and works just fine.

**Comment by janbartel** [comment]
Introduced scan=-1 meaning that no redeployment is done, and made it the default. 0 means manual redeployment using Enter key, and any other positive integer is the scan interval for hot redeployment.

**Comment by janbartel** [comment]
@sbordet  nudge for re-review

**Review by olamy — APPROVED** [review]

File: documentation/jetty-documentation/src/main/asciidoc/programming-guide/maven/jetty-maven-plugin.adoc [hunk 2]
```diff
@@ -77,8 +77,8 @@ mvn jetty:run
 This starts Jetty and serves up your project on http://localhost:8080/.
 
 Jetty will continue to run until you stop it.
-By default, it will not automatically restart your webapp: you can force a redeploy by hitting the `Enter` key.
-Set a non-zero &lt;scan&gt; value to have jetty scan your webapp for changes and automatically redeploy.
+By default, it will not automatically restart your webapp.
+Set a non-zero `&lt;scan&gt;` value to have jetty scan your webapp for changes and automatically redeploy, or set `&lt;scan&gt;` to `0` to cause manual redeployment by hitting the `Enter` key.
```
Comment (sbordet) [inline documentation/jetty-documentation/src/main/asciidoc/programming-guide/maven/jetty-maven-plugin.adoc]: Replace HTML entities with correspondent characters.

Comment (sbordet) [reply documentation/jetty-documentation/src/main/asciidoc/programming-guide/maven/jetty-maven-plugin.adoc]: Use `kbd:[Enter]` to indicate the "Enter" key -- it will render more nicely, see https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#keyboard-button-and-menu-macros

File: jetty-util/src/main/java/org/eclipse/jetty/util/Scanner.java (hunk 1 above)
Comment (sbordet) [reply jetty-util/src/main/java/org/eclipse/jetty/util/Scanner.java]: This is not fixed yet.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-util/src/main/java/org/eclipse/jetty/util/Scanner.java (hunk 1 above)
Comment (janbartel) [reply jetty-util/src/main/java/org/eclipse/jetty/util/Scanner.java]: Changed to ScheduledExecutorScheduler - IMHO it's a bit ugly, but ....

I also think if you don't want TimerScheduler used, the class needs to be deprecated.

File: documentation/jetty-documentation/src/main/asciidoc/programming-guide/maven/jetty-maven-plugin.adoc [hunk 3]
```diff
@@ -11,6 +11,8 @@
 // ========================================================================
 //
 
+:experimental:
```
Comment (sbordet) [inline documentation/jetty-documentation/src/main/asciidoc/programming-guide/maven/jetty-maven-plugin.adoc]: This attribute should be moved to the `.asciidoctorconfig` file.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]
