### PR TITLE
Fix shared blocking callback hang

### LINKED ISSUE #13066: Managed Async thread pool threads hang under contention in HttpOutput.channelWrite
**Jetty version(s)**
12.0.19 and 12.0.20

**Jetty Environment**
ee8 and ee10

**Java version/vendor** `(use: java -version)`
openjdk 21.0.7 2025-04-15 LTS
OpenJDK Runtime Environment Temurin-21.0.7+6 (build 21.0.7+6-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.7+6 (build 21.0.7+6-LTS, mixed mode, sharing)

**OS type/version**
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 22.04.5 LTS
Release: 22.04
Codename: jammy

**Description**
Some managed Async thread pool threads can starting hanging under high connection load and never recover, leading to unavailability / reduced parallelism.

example thread dump for hanging thread in this state:

```
"jersey-server-managed-async-executor-2266@9998" tid=0x3915 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
	  at java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
	  at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1712)
	  at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:214)
	  at org.eclipse.jetty.ee8.nested.HttpOutput.channelWrite(HttpOutput.java:282)
	  at org.eclipse.jetty.ee8.nested.HttpOutput.write(HttpOutput.java:775)
	  at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:301)
	  at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:170)
	  - locked <0x95c2> (a java.io.ByteArrayOutputStream)
	  at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:278)
	  at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:232)
	  at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:247)
	  at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:842)
	  at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:389)
	  at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:707)
	  at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:373)
	  at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:419)
	  at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$4.run(ServerRuntime.java:872)
	  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
```

see full stack trace in attached zip in hangthread-single.txt

potential relation/maybe caused by https://github.com/jetty/jetty.project/issues/13065 

**How to reproduce?**
see attached project. instructions:
* start the project
* wait for stdout to become quiet (all threads are running and connected)
* press any key on stdin to start closing client connections to jetty, via forceful task cancel / thread pool shutdown
* wait for program to settle on stdout (bunch of exceptions usually)
* take a thread dump, eg jstack -l on the PID
*  find one or more threads hanging in above state

works for me practically every run, but likely a bit timing dependent.

[hang-repro.zip](https://github.com/user-attachments/files/19979207/hang-repro.zip)

### PR DESCRIPTION
**Pull request by lorban**
3 changes are needed:
 1. do not call `onFailure` from `earlyEOF()` in the H1 parser's `RequestHandler`
 2. do not call the failure listeners if we have either a reader or a writer task in `HttpChannel.onFailure()`
 3. do not call `sendError` from `HttpChannelState.onError()`, both in ee9 and ee10

Fixes #13066

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 1]
```diff
@@ -1092,7 +1092,8 @@ public void earlyEOF()
                     stream._chunk = Content.Chunk.from(bad);
                 }
 
-                ThreadPool.executeImmediately(getServer().getThreadPool(), _httpChannel.onFailure(bad));
+//              Case 1
+//                ThreadPool.executeImmediately(getServer().getThreadPool(), _httpChannel.onFailure(bad));
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: @gregw said: _I think we should notify EOF as a failure._

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java [hunk 2]
```diff
@@ -837,6 +837,8 @@ protected boolean onError(Throwable th)
                 {
                     if (_asyncListeners == null || _asyncListeners.isEmpty())
                     {
+//                      Case 3
+//                        return false;
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java]: @gregw said:  _There is nothing explicit in the servlet spec saying that calling startAsync() should change the way exceptions thrown from a service method are handled. However, since the servlet spec allows exceptions to be matched to error pages, which are served with an ERROR dispatch, it would be nonsensical to have a synchronous ERROR dispatch happening whilst an async cycle was in progress. So if we are ASYNC, we should definitely not call sendError - EVEN IF there are no listeners registered._

_So I think this change is good._

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: As discussed with @sbordet, `earlyEOF()` can only be invoked when the user-code does a read, hence setting the `stream._chunk` to an error chunk is enough to notify the user-code that something bad happened (the error chunk would be returned by Core, the held exception thrown by EE*).

Spawning a thread to call the `onFailure` path would notify the failure listener (in Core; which would call `AsyncListener.onError()` on EE*) in parallel to the blocking read, hence delivering the same error twice by two concurrent threads.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java (hunk 2 above)
Comment (lorban) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java]: This change is more delicate IMHO as it makes some tests in `AsyncContextTest` fail as we currenly explicitly assert for this specific behavior: `testStartCompleteThrow` and `testStartDispatchThrow` expect to be dispatched to the error page after `AsyncContext.complete()` or `AsyncContext.dispatch()` respectively got called if `service()` throws an exception.

While I do believe this change is "more correct", it also introduces a behavioral change that seems likely that users would rely on, and breaking it could be very surprising.

Maybe this is one of those bugs that should not be fixed in EE9, but only in EE10/11?

**Comment by lorban** [comment]
As @gregw previously wrote, _Our documentation explicitly says that we will call the (core Failure*) listener even if there is are demand and write callbacks._ so the Case 1 implementation breaks that contract for H1 as the newly added `AsyncRequestContentTest.testEarlyEofWithDemand()` test demonstrates.

This behavior is mandated by core, but breaks servlets. Did we mess up the Core contract or the EE* implementations are just missing some extra filtering?

**Comment by lorban** [comment]
So we have 2 problems:

 - Implementing case 3 might be detrimental to EE9 backward compatibility.
 - Implementing case 1 breaks the Core API for H1.

We need to take a decision for case 3 and either an alternative implementation for case 1, or a contract change for Core, plus H2 and H3 changes.

(`testEarlyEofWithDemand()` is broken for FCGI too, but differently)

**Comment by sbordet** [comment]
I don't see how we can implement case 1 without producing races.

An application can perform blocking reads from a container thread, or a spawned application thread, so we will always be concurrent between the container (or application spawned thread) when we wake up the blocked read and the execution of the failure listener in a second container thread.

I think the introduction of failure listeners was to notify applications of asynchronous failures when other means were not available (no reads nor writes pending), so I'm now leaning towards case 2: we do not call the failure listeners if we have notified the application otherwise.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java (hunk 2 above)
Comment (gregw) [reply jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpChannelState.java]: Hmm yes it is more nuanced.   The application should be able to call sendError and then complete.
But we should not call sendError on behalf of the application.

**Comment by gregw** [comment]
> I think the introduction of failure listeners was to notify applications of asynchronous failures when other means were not available (no reads nor writes pending), so I'm now leaning towards case 2: we do not call the failure listeners if we have notified the application otherwise.

@sbordet I think that is a too nuanced approach.  I think we should always call listeners, but tell them if there has been another notification.  They can then decide for themselves if they will do further notification.

For our listeners, we will know not to call AC.onError if there was a read/write notification.   But applications might want to have listeners just for logging or other purposes that will not race with an exception returned to a read/write.  Making the race explicit with a boolean (or two) arguments is probably the clearest think to do.

**Comment by gregw** [comment]
@lorban @sbordet see #13133 to add a notified argument to error listeners.
Does this help?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 3]
```diff
@@ -481,6 +482,11 @@ private Runnable onFailure(Throwable x, boolean remote)
                 };
 
                 // Serialize all the error actions.
+
+//                Case 2
+                if (invokeOnContentAvailable != null || invokeWriteFailure != null)
+                    invokeOnFailureListeners = null;
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I look at this and it just feels wrong.  To silently throw away listeners in a very specific case does not feel right.
I'm leaning back towards something like my PR... but perhaps with EventListener interfaces?

**Comment by gregw** [comment]
@sbordet @lorban see #13137 for a way to allow a listener for all failures if somebody needs one.

**Comment by lorban** [comment]
@gregw https://github.com/jetty/jetty.project/pull/13137 is a very elegant a way to allow listening for all failures, but AFAICT we do not need that, and I fail to see how that could be useful as you always risk concurrent calls to methods designed to be serialized.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 4]
```diff
@@ -388,9 +388,19 @@ public Runnable onIdleTimeout(TimeoutException t)
...
+                    {
+                        if (onIdleTimeout.test(t))
+                        {
+                            // If the idle timeout listener(s) return true, then we call onFailure and run any task it returns.
+                            Runnable task = onFailure(t);
+                            if (task != null)
+                                task.run();
+                        }
+                    }
+                    catch (Throwable x)
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:396]: We do not want to catch exceptions thrown from the `onFailure()` task, and call again `onFailure()`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 5]
```diff
@@ -465,8 +475,10 @@ private Runnable onFailure(Throwable x, boolean remote)
                 Consumer<Throwable> onFailure = _onFailure;
                 _onFailure = null;
 
+                boolean hasFailureConsumer = onFailure == null;
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Bad variable name?

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelTest.java [hunk 6]
```diff
@@ -1169,6 +1169,72 @@ public void demand()
...
+        try (StacklessLogging ignore = new StacklessLogging(Response.class))
+        {
+            callbackRef.get().failed(new Throwable("FAILED"));
+        }
+
+        // Request handling was completed.
+        assertTrue(stream.isComplete());
+
+        // onFailure listeners were not called.
+        assertThat(error.get(), nullValue());
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelTest.java]: I'd copy this block also just before completing the request.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/AsyncRequestContentTest.java [hunk 7]
```diff
@@ -16,28 +16,114 @@
...
+                if (result.isFailed())
+                    clientResponseFuture.completeExceptionally(result.getFailure());
+                else
+                    clientResponseFuture.complete(result);
+            });
+
+        assertTrue(serverHandleLatch.await(5, TimeUnit.SECONDS));
+
+        // Stop the client while an upload is in progress -> abruptly closes the connection so that provokes an early EOF on the server.
+        LifeCycle.stop(client);
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/AsyncRequestContentTest.java]: I would call `request.abort()` -- something like:

```java
Request request = client.POST(newURI(transport))
            .body(content);
request.send(...);

...

request.abort(new ...);
```

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContextTest.java [hunk 8]
```diff
@@ -114,7 +115,7 @@ public void testStartThrow() throws Exception
         });
 
         String request =
-            "GET /ctx/startthrow HTTP/1.1\r\n" +
+            "GET /ctx/startthrow?timeout=100 HTTP/1.1\r\n" +
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContextTest.java]: Why do you need a timeout now?
Please convert to text block.

I would like to see this test to assert that there is no response, and another `testStartThrowComplete()` that tests that there is an error response.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/AsyncIOServletTest.java [hunk 9]
```diff
@@ -338,13 +338,11 @@ public void onAllDataRead()
...
+                        assertThat(t.getMessage(), is("explicitly_thrown_by_test_1"));
                         errors.incrementAndGet();
-                        throw new NullPointerException("explicitly_thrown_by_test_2")
-                        {
-                            {
-                                this.initCause(t);
-                            }
-                        };
+                        response.setStatus(HttpStatus.IM_A_TEAPOT_418);
+                        asyncContext.complete();
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/AsyncIOServletTest.java:345]: Please rename the test method.

File: jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java [hunk 10]
```diff
@@ -0,0 +1,230 @@
...
+
+        public HangInputStream(CountDownLatch latch)
+        {
+            this.latch = latch;
+        }
+
+        @Override
+        public int read()
+        {
+            if (count == 1_000_000)
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java]: Why 1M?

File: jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java [hunk 11]
```diff
@@ -0,0 +1,230 @@
...
+            {
+                try
+                {
+                    latch.countDown();
+                    Thread.sleep(Duration.ofDays(1).toMillis());
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java]: Can we sleep less?

File: jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java [hunk 12]
```diff
@@ -0,0 +1,230 @@
...
+    public void test() throws Exception
+    {
+        CountDownLatch latch = new CountDownLatch(THREAD_COUNT);
+        for (int i = 0; i < THREAD_COUNT; i++)
+        {
+            executorService.submit(() ->
+            {
+                httpClient.POST(server.getURI())
+                    .body(new InputStreamRequestContent("text/plain", new HangInputStream(latch)))
+                    .timeout(1, TimeUnit.DAYS)
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java]: Less timeout.

File: jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java [hunk 13]
```diff
@@ -0,0 +1,230 @@
...
+    @AfterEach
+    public void tearDown()
+    {
+        executorService.shutdownNow();
+        LifeCycle.stop(server);
+        LifeCycle.stop(httpClient);
+    }
+
+    @Test
+    public void test() throws Exception
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java:139]: Annotate as "stress"?

Also maybe add a comment saying: "this test tries to reproduce the issue #... by running THREAD_COUNT request in the hope to reproduce the issue statistically."

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:396]: Fixed.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Indeed, fixed.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelTest.java (hunk 6 above)
Comment (lorban) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/HttpChannelTest.java]: Done.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/AsyncRequestContentTest.java (hunk 7 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/AsyncRequestContentTest.java]: Done.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/AsyncIOServletTest.java (hunk 9 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/AsyncIOServletTest.java:345]: Done.

File: jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java (hunk 13 above)
Comment (lorban) [reply jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java:139]: Done.

File: jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java (hunk 12 above)
Comment (lorban) [reply jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java]: Done.

File: jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java (hunk 11 above)
Comment (lorban) [reply jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java]: Yes, we can do without sleeping; changed.

File: jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java (hunk 10 above)
Comment (lorban) [reply jetty-ee9/jetty-ee9-tests/jetty-ee9-test-jersey/src/test/java/org/eclipse/jetty/ee9/jersey/tests/HungBlockingThreadsTest.java]: That's not really needed; 1 KB of data upload seems sufficient to reproduce the issue.

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContextTest.java (hunk 8 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContextTest.java]: I've cleaned up and simplified the tests that were impacted.

Now the behavior of `testStartThrow()` might be surprising.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 14]
```diff
@@ -475,10 +476,10 @@ private Runnable onFailure(Throwable x, boolean remote)
                 Consumer<Throwable> onFailure = _onFailure;
                 _onFailure = null;
 
-                boolean hasFailureConsumer = onFailure == null;
+                boolean hasNoFailureConsumer = onFailure == null;
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Rename to `noFailureListener`.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/AsyncRequestContentTest.java [hunk 15]
```diff
@@ -98,7 +96,8 @@ public void run()
 
         AsyncRequestContent content = new AsyncRequestContent();
         CompletableFuture<Result> clientResponseFuture = new CompletableFuture<>();
-        client.POST(newURI(transport))
+        org.eclipse.jetty.client.Request request = client.POST(newURI(transport));
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/AsyncRequestContentTest.java]: Use `var` instead of fqcn.

**Review by sbordet — DISMISSED** [review]
LGTM, just fix the 2 nits.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 14 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Done.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/AsyncRequestContentTest.java (hunk 15 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/AsyncRequestContentTest.java]: Done.

**Review by sbordet — APPROVED** [review]
