### PR TITLE
Fixes #2913 - ClassNotFoundException: sun.reflect.Reflection with JDK 11

### LINKED ISSUE #2913: java.lang.ClassNotFoundException: sun.reflect.Reflection with Open-JDK 11
When testing with Open-JDK 11 I get the following exception (using Jetty-9.4.11, but the code causing this hasn't changed in the 9.4.x branch):
```
java.lang.ClassNotFoundException: sun.reflect.Reflection
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
at org.eclipse.jetty.util.Loader.loadClass(Loader.java:65)
at org.eclipse.jetty.server.handler.ContextHandler$Context.getClassLoader(ContextHandler.java:2572)
at org.apache.tomcat.util.descriptor.tagplugin.TagPluginParser.<init>(TagPluginParser.java:49)
at org.apache.jasper.compiler.TagPluginManager.init(TagPluginManager.java:95)
at org.apache.jasper.compiler.TagPluginManager.apply(TagPluginManager.java:58)
at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:244)
at org.apache.jasper.compiler.Compiler.compile(Compiler.java:374)
at org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
at org.apache.jasper.compiler.Compiler.compile(Compiler.java:335)
at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:595)
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:368)
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:112)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
at de.espirit.firstspirit.io.servlet.SecurityFilter.doFilter(SecurityFilter.java:121)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:531)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by sbordet**
Issue #2913.
Replaced usage of sun.reflect.Reflection with a
SecurityManager subclass, so that it works in all JDKs.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 1]
```diff
@@ -2585,19 +2584,18 @@ public ClassLoader getClassLoader()
...
                 try
                 {
-                    Class<?> reflect = Loader.loadClass("sun.reflect.Reflection");
-                    Method getCallerClass = reflect.getMethod("getCallerClass",Integer.TYPE);
-                    Class<?> caller = (Class<?>)getCallerClass.invoke(null,2);
-
+                    Class<?> caller = new Caller().getCallerClass(2);
                     boolean ok = false;
-                    ClassLoader callerLoader = caller.getClassLoader();
+                    ClassLoader callerLoader = caller == null ? null : caller.getClassLoader();
```
Comment (joakime) [inline jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: Couldn't we skip this null check by having `new Caller().getCallerClassLoader(2)` instead?

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 2]
```diff
@@ -2585,19 +2584,18 @@ public ClassLoader getClassLoader()
...
                 // check to see if the classloader of the caller is the same as the context
-                // classloader, or a parent of it
+                // classloader, or a parent of it, as required by the javadoc specification.
                 try
                 {
-                    Class<?> reflect = Loader.loadClass("sun.reflect.Reflection");
-                    Method getCallerClass = reflect.getMethod("getCallerClass",Integer.TYPE);
-                    Class<?> caller = (Class<?>)getCallerClass.invoke(null,2);
-
+                    Class<?> caller = new Caller().getCallerClass(2);
```
Comment (pejobo) [inline jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: "new Caller()" should be wrapped in an `java.security.AccessController.doPrivileged(..)` block..

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java (hunk 1 above)
Comment (sbordet) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: I don't understand how? If depth 2 is not valid, what `ClassLoader` do I return?

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java (hunk 2 above)
Comment (sbordet) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: Will do, but we're going into a rabbit hole here - Jetty has not been coded with a SecurityManager in mind.

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java (hunk 1 above)
Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: What i'm proposing ...

From:
``` java
Class<?> caller = new Caller().getCallerClass(2);
boolean ok = false;
ClassLoader callerLoader = caller == null ? null : caller.getClassLoader();
...
    private static class Caller extends SecurityManager
    {
        public Class<?> getCallerClass(int depth)
        {
            if (depth < 0)
                return null;
            Class<?>[] classContext = getClassContext();
            if (classContext.length <= depth)
                return null;
            return classContext[depth];
        }
    }
```

To:
``` java
boolean ok = false;
ClassLoader callerLoader = new Caller().getCallerClassLoader(2);
...
    private static class Caller extends SecurityManager
    {
        public ClassLoader<?> getCallerClassLoader(int depth)
        {
            if (depth < 0)
                return null;
            Class<?>[] classContext = getClassContext();
            if (classContext.length <= depth)
                return null;
            return classContext[depth].getClassLoader();
        }
    }
```

You are already doing a better job at validity checking down in the `Caller`.
Plus if you get past your 2 range checks, is it possible to have a null classContext entry??

File: jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 3]
```diff
@@ -2591,27 +2592,23 @@ public ClassLoader getClassLoader()
...
+                // Wrap so that only Jetty code requires the "createSecurityManager" permission.
+                Caller caller = AccessController.doPrivileged((PrivilegedAction<Caller>)Caller::new);
+                Class<?> callerClass = caller.getCallerClass(2);
+                boolean ok = false;
+                ClassLoader callerLoader = callerClass == null ? null : callerClass.getClassLoader();
+                while (!ok && callerLoader != null)
                 {
-                    LOG.warn("Unable to check classloader of caller",e);
+                    if (callerLoader == _classLoader)
+                        ok = true;
```
[the remark this answers is not in the document]
Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: Like this?

``` java
                // Wrap so that only Jetty code requires the "createSecurityManager" permission.
                Caller caller = AccessController.doPrivileged((PrivilegedAction<Caller>)Caller::new);
                ClassLoader callerLoader = caller.getCallerClassLoader(2);
                while (callerLoader != null)
                {
                    if (callerLoader == _classLoader)
                        return _classLoader;
                    callerLoader = callerLoader.getParent();
                }

                // No classloader match, check permission
                AccessController.checkPermission(new RuntimePermission("getClassLoader"));
                return _classLoader;
```

[the remark this answers is not in the document]
Comment (pejobo) [reply jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: Thumbs up!

**Comment by pejobo** [comment]
Looks good for me 👍
