### PR TITLE
Issue #6489 - fix RFC3986_UNAMBIGUOUS and UNSAFE UriCompliance modes.

### LINKED ISSUE #6489: Some URI valid compliance modes cannot be set in .ini file.
**Jetty version(s)**
10.0.x - 11.0.x

The `RFC3986_UNAMBIGUOUS` and `UNSAFE` URI compliance modes are not able to be set with `jetty.httpConfig.uriCompliance` in the `server.ini` file.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #6489

### CODE REVIEW

**Review by sbordet — APPROVED** [review]

File: jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java [hunk 1]
```diff
@@ -159,7 +159,7 @@ public String getDescription()
 
     public static UriCompliance valueOf(String name)
     {
-        for (UriCompliance compliance : Arrays.asList(DEFAULT, LEGACY, RFC3986, STRICT, SAFE))
+        for (UriCompliance compliance : Arrays.asList(DEFAULT, LEGACY, RFC3986, RFC3986_UNAMBIGUOUS, UNSAFE, SAFE, STRICT))
```
Comment (sbordet) [inline jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java]: Other `*Compliance` classes have a static `KNOWN_MODES` list, and I think for consistency it should be introduced in this class too.

Nit: try to use `List.of()` instead of `Arrays.asList()`.

**Review by sbordet — CHANGES_REQUESTED** [review]
Can you please

**Review by sbordet — APPROVED** [review]
