### PR TITLE
Issue #13812 - NPE from CompressionHandler when using Content.Sink.asOutputStream

### LINKED ISSUE #13812: NullPointerException in GzipEncoderSink, breaking all requests with CompressionHandler
**Jetty version(s)**
12.1.2

**Jetty Environment**

**HTTP version**
HTTP/1 HTTP/2

**Java version/vendor** `(use: java -version)`
24

**OS type/version**

**Description**

https://github.com/jetty/jetty.project/blob/fd29d1d911e6d2d96c05e8c0e008999d4f0a280c/jetty-core/jetty-compression/jetty-compression-gzip/src/main/java/org/eclipse/jetty/compression/gzip/internal/GzipEncoderSink.java#L146

`content` can be null, for example from here:

https://github.com/jetty/jetty.project/blob/fd29d1d911e6d2d96c05e8c0e008999d4f0a280c/jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSinkOutputStream.java#L93

### PR DESCRIPTION
**Pull request by joakime**
+ Be null content resistant in the various Compression Encoders
+ Add unit tests

Closes #13812

### CODE REVIEW

File: jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/org/eclipse/jetty/compression/brotli/internal/BrotliEncoderSink.java [hunk 1]
```diff
@@ -80,7 +80,7 @@ protected WriteRecord encode(boolean last, ByteBuffer content)
                 {
                     try
                     {
-                        while (content.hasRemaining())
+                        while (content != null && content.hasRemaining())
```
Comment (sbordet) [inline jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/org/eclipse/jetty/compression/brotli/internal/BrotliEncoderSink.java]: Use `BufferUtil.hasContent()` instead, reads better.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/org/eclipse/jetty/compression/brotli/internal/BrotliEncoderSink.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-compression/jetty-compression-brotli/src/main/java/org/eclipse/jetty/compression/brotli/internal/BrotliEncoderSink.java]: done

**Review by sbordet — APPROVED** [review]
