### PR TITLE
Issue #6661 - Make ServerConnector socket options setting optional

### LINKED ISSUE #6661: Some SocketOptions not supported on Windows
**Jetty version(s)**
10.0.x

**Java version/vendor** `(use: java -version)`
11.0.12

**OS type/version**
Windows 10

**Description**

The recent work on Issue #6372 is not compatible with Windows 10.

```
Caused by: java.lang.UnsupportedOperationException: 'SO_REUSEPORT' not supported
	at java.base/sun.nio.ch.ServerSocketChannelImpl.setOption(ServerSocketChannelImpl.java:151)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:338)
```

### PR DESCRIPTION
**Pull request by joakime**
Closes #6661

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java [hunk 1]
```diff
@@ -348,6 +349,18 @@ protected ServerSocketChannel openAcceptChannel() throws IOException
...
 
+    private <T> void setSocketOption(ServerSocketChannel channel, SocketOption<T> name, T value)
+    {
+        try
+        {
+            channel.setOption(name, value);
+        }
+        catch (Throwable t)
+        {
+            LOG.warn("Unable to set socket option {} to {}", name, value, t);
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java]: Don't want to warn here, see `ClientConnector.setSocketOption(...)`, just use the same debug that's there.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java (hunk 1 above)
Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ServerConnector.java]: Updated.

**Review by sbordet — APPROVED** [review]

**Comment by joakime** [comment]
Going to wait for green from CI before merging.
