### PR TITLE
Jetty 12 static path in context

### LINKED ISSUE #8749: Jetty 12 - `request.getContext().getContextPath()` should return full context, not just last one
**Jetty version(s)**
12

**Description**
The `request.getContext().getContextPath()` only returns the last context seen, not the full context path up to this point.

``` java
    @Test
    public void testNestedThreeDeepContextHandler() throws Exception
    {
        ContextHandler contextHandlerA = new ContextHandler();
        contextHandlerA.setContextPath("/a");
        ContextHandler contextHandlerB = new ContextHandler();
        contextHandlerB.setContextPath("/b");
        ContextHandler contextHandlerC = new ContextHandler();
        contextHandlerC.setContextPath("/c");

        contextHandlerA.setHandler(contextHandlerB);
        contextHandlerB.setHandler(contextHandlerC);
        contextHandlerC.setHandler(new Handler.Processor()
        {
            @Override
            public void process(Request request, Response response, Callback callback)
            {
                response.getHeaders().put(HttpHeader.CONTENT_TYPE, "text/plain; charset=utf-8");
                String msg = "contextPath=" + request.getContext().getContextPath();
                response.write(true, BufferUtil.toBuffer(msg), callback);
            }
        });

        startServer(contextHandlerA);

        String rawRequest = """
            GET /a/b/c/d HTTP/1.1\r
            Host: local\r
            Connection: close\r
                        
            """;
        HttpTester.Response response = HttpTester.parseResponse(connector.getResponse(rawRequest));
        assertEquals(HttpStatus.OK_200, response.getStatus());
        assertEquals("contextPath=/a/b/c", response.getContent());
    }
```

In this scenario, where we have 3 `ContextHandler` nested inside of each other, the final Handler only sees the last contextPath.
(The assertion fails, as it expected `/a/b/c` but only got `/c`)

This makes it hard to rewrite / redirect / change the URI without the knowledge of the full context.
(for example, putting a `RewriteHandler` after a `ContextHandler`)

### PR DESCRIPTION
**Pull request by gregw**
Convert getPathInContext to a static.
Also contains work from @joakime 's deep context branch #8751

### CODE REVIEW

**Comment by gregw** [comment]
@sbordet this is a WIP... I ran out of time to complete today.

**Comment by gregw** [comment]
This resolves #8749 by making even contexts use the full context path and not a relative path.  Thus it also replaces #8751

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Context.java [hunk 1]
```diff
@@ -56,4 +56,7 @@ public interface Context extends Attributes, Decorator, Executor
     
     /** scope the calling thread to the context and request and run the runnable. */
     void run(Runnable runnable, Request request);
+
+    /** Return a URI path scoped to this context **/
+    String pathInContext(String path);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Context.java]: Rename to `getPathInContext(String fullPath)` and add proper javadocs (3rd person, paragraphs wrapped by `<p>`).

File: jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/CompactPathRule.java [hunk 2]
```diff
@@ -27,18 +28,20 @@ public class CompactPathRule extends Rule
     @Override
     public Request.WrapperProcessor matchAndApply(Request.WrapperProcessor input) throws IOException
     {
-        String path = input.getPathInContext();
+        String path = Request.getPathInContext(input);
```
Comment (sbordet) [inline jetty-core/jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/CompactPathRule.java]: Now I think this `Rule` should work on the full path, otherwise it won't catch cases such as `//ctx/foo`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 3]
```diff
@@ -689,4 +702,11 @@ public void process(Request ignored, Response response, Callback callback) throw
                 processor.process(this, response, callback);
         }
     }
+
+    static HttpURI updateHttpURI(Request request, String newPathInContext)
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: I'd rename this to `newHttpURI()` or `newHttpURIFrom()`, as "update" seems that it is updating in place the request `HttpURI`, but that's not the case.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 4]
```diff
@@ -151,10 +153,27 @@ public interface Request extends Attributes, Content.Source
...
+     * @see Context#getContextPath()
+     */
+    static String getContextPath(Request request)
+    {
+        return request.getContext().getContextPath();
+    }
+
+    /**
+     * <p>Get the canonically encoded path of the URI, scoped to the current context.</p>
+     * <p>The <code>pathInContext</code> represents the targeted resource within the current content for the request.</p>
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: I would remove this line (confusing) and replace it with an example instead.

```suggestion
     * <p>For example, when {@code contextPath=/ctx} and the request {@code HttpURI.canonicalPath=/ctx/foo}, then {@code pathInContext=/foo}.</p>
```

I would also mention that it does not include the query string, nor any path parameter.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java [hunk 5]
```diff
@@ -540,9 +538,7 @@ private WelcomeAction processWelcome(Request request, Response response) throws
             response.getHeaders().putLongField(HttpHeader.CONTENT_LENGTH, 0);
             // TODO need URI util that handles param and query without reconstructing entire URI with scheme and authority
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java]: TODO is now obsolete?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/MovedContextHandler.java [hunk 6]
```diff
@@ -102,8 +102,8 @@ public void process(Request request, Response response, Callback callback) throw
                 return;
 
             String path = _newContextURL;
-            if (!_discardPathInfo && request.getPathInContext() != null)
-                path = URIUtil.addPaths(path, request.getPathInContext());
+            if (!_discardPathInfo && Request.getPathInContext(request) != null)
+                path = URIUtil.addPaths(path, Request.getPathInContext(request));
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/MovedContextHandler.java]: Store `Request.getPathInContext(request)` in a local variable to avoid calling it twice.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ResourceHandler.java [hunk 7]
```diff
@@ -111,7 +111,7 @@ public Request.Processor handle(Request request) throws Exception
             return super.handle(request);
         }
 
-        HttpContent content = _resourceService.getContent(request.getPathInContext(), request);
+        HttpContent content = _resourceService.getContent(Request.getPathInContext(request), request);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ResourceHandler.java:115]: Store `Request.getPathInContext(request)` in a local variable to avoid calling it multiple times.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ErrorProcessorTest.java [hunk 8]
```diff
@@ -71,21 +73,21 @@ public void before() throws Exception
             @Override
             public void process(Request request, Response response, Callback callback)
             {
-                if (request.getPathInContext().startsWith("/badmessage/"))
+                if (Request.getPathInContext(request).startsWith("/badmessage/"))
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/ErrorProcessorTest.java]: Store `Request.getPathInContext(request)` in a local variable to avoid calling it multiple times.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java [hunk 9]
```diff
@@ -697,6 +697,29 @@ public static String decodePath(String path, int offset, int length)
         }
     }
 
+    /**
+     * @param path The path to check for legality
+     * @return True if the path does not contain any illegal path characters
+     */
+    public static boolean isLegalPath(String path)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java]: Rename to `isValidPath(String)` as feels better than "legal".

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java [hunk 10]
```diff
@@ -1185,8 +1185,9 @@ protected void doStop() throws Exception
     }
 
     @Override
-    protected ServletContextRequest wrap(Request request, String pathInContext)
+    protected ServletContextRequest wrap(Request request)
     {
+        String pathInContext = getContext().pathInContext(request.getHttpURI().getCanonicalPath());
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java]: Use `Request.getPathInContext(request)` instead?

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java [hunk 11]
```diff
@@ -237,8 +242,8 @@ public Object getAttribute(String name)
         {
             case "o.e.j.s.s.ServletScopedRequest.request" -> _httpServletRequest;
             case "o.e.j.s.s.ServletScopedRequest.response" -> _response.getHttpServletResponse();
-            case "o.e.j.s.s.ServletScopedRequest.servlet" -> _mappedServlet.getServletPathMapping(getPathInContext()).getServletName();
-            case "o.e.j.s.s.ServletScopedRequest.url-pattern" -> _mappedServlet.getServletPathMapping(getPathInContext()).getPattern();
+            case "o.e.j.s.s.ServletScopedRequest.servlet" -> _mappedServlet.getServletPathMapping(_pathInContext).getServletName();
+            case "o.e.j.s.s.ServletScopedRequest.url-pattern" -> _mappedServlet.getServletPathMapping(_pathInContext).getPattern();
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java]: I would restore usage of the getter here.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/security/authentication/FormAuthenticator.java [hunk 12]
```diff
@@ -223,12 +223,12 @@ public Authentication validateRequest(Request req, Response res, Callback callba
...
         ServletContextRequest.ServletApiRequest servletApiRequest = servletContextRequest.getServletApiRequest();
 
-        boolean jSecurityCheck = isJSecurityCheck(req.getPathInContext());
+        boolean jSecurityCheck = isJSecurityCheck(Request.getPathInContext(req));
         mandatory |= jSecurityCheck;
         if (!mandatory)
             return new DeferredAuthentication(this);
 
-        if (isLoginOrErrorPage(req.getPathInContext()) && !DeferredAuthentication.isDeferred(res))
+        if (isLoginOrErrorPage(Request.getPathInContext(req)) && !DeferredAuthentication.isDeferred(res))
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/security/authentication/FormAuthenticator.java]: Store `Request.getPathInContext(request)` in a local variable to avoid calling it twice.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java [hunk 13]
```diff
@@ -170,60 +170,60 @@ static <T extends Attributes.Wrapper> T unwrap(Attributes attributes, Class<T> t
...
         {
-            return _attributes;
+            return _wrapped;
         }
 
         @Override
         public Object removeAttribute(String name)
         {
-            return _attributes.removeAttribute(name);
+            return _wrapped.removeAttribute(name);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java]: Like in all other wrapper classes, these should call `getWrapped()`, so that a subclass may just override `getWrapped()` instead of all methods.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java [hunk 14]
```diff
@@ -1546,8 +1546,8 @@ void onRequest(org.eclipse.jetty.server.Request coreRequest)
         _uri = coreRequest.getHttpURI();
 
         _pathInContext = _context.getContextHandler().isCanonicalEncodingURIs()
-            ? coreRequest.getPathInContext()
-            : URIUtil.decodePath(coreRequest.getPathInContext());
+            ? org.eclipse.jetty.server.Request.getPathInContext(coreRequest)
+            : URIUtil.decodePath(org.eclipse.jetty.server.Request.getPathInContext(coreRequest));
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java]: Store `Request.getPathInContext(request)` in a local variable to avoid calling it twice.

**Review by sbordet — CHANGES_REQUESTED** [review]
@gregw please rebase this PR against the latest HEAD, as it contains changes that have already been merged into mainline.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java (hunk 10 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextHandler.java]: Can't yet, as request is not yet wrapped. We are in process of doing that. I'll write that in a comment

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 15]
```diff
@@ -151,10 +153,29 @@ public interface Request extends Attributes, Content.Source
     Context getContext();
 
     /**
-     * TODO see discussion in #7713, as this path should probably be canonically encoded - ie everything but %25 and %2F decoded
-     * @return The part of the decoded path of the URI after any context path prefix has been removed.
+     * <p>Get the context pat. this is equivalent to <code>request.getContext().getContextPath()</code>
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: Typo: "pat".
Replace `<code>` with `@{code }`.
"this" should be "This".

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java [hunk 16]
```diff
@@ -151,10 +153,29 @@ public interface Request extends Attributes, Content.Source
...
+     *
+     * @param request The request to get the context path from.
+     * @return The contextPath of the request. .
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java]: Double dot?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java [hunk 17]
```diff
@@ -452,9 +452,7 @@ protected void sendWelcome(HttpContent content, String pathInContext, boolean en
             if (!uri.getCanonicalPath().endsWith("/"))
             {
                 // TODO need URI util that handles param and query without reconstructing entire URI with scheme and authority
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java]: This other TODO also obsolete?

**Review by sbordet — APPROVED** [review]
@gregw few niggles to fix, otherwise LGTM.
