### PR TITLE
Fix multipart locking and buffer leaks

### LINKED ISSUE #9410: Jetty 12: review locking in `MultiPartFormData` and `MultiPartByteRanges`
**Jetty version(s)**
12

**Description**
Both classes call `Multipart.AbstractPartsListener.fail(Throwable cause)` when `CompletableFuture.completeExceptionally()` is called. This can happen at any time by any thread, so this code has to be thread-safe and currently isn't.

### PR DESCRIPTION
**Pull request by lorban**
Fixes #9410

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 1]
```diff
@@ -126,9 +126,10 @@ public abstract static class Part implements Closeable
         private final String name;
         private final String fileName;
         private final HttpFields fields;
-        private Content.Source contentSource;
         private Path path;
-        private boolean temporary = true;
+        private final AutoLock lock = new AutoLock();
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Move this up close to the other `final` fields. I like initialized fields to be even before `final` fields that are initialized in the constructor.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 2]
```diff
@@ -267,18 +275,21 @@ public void writeTo(Path path) throws IOException
...
+            try (AutoLock ignored = lock.lock())
+            {
                 this.temporary = false;
             }
         }
 
         public void delete() throws IOException
         {
-            if (this.path != null)
+            if (this.path != null && Files.exists(this.path))
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: `Files.exist()` seems redundant.
If the implementation sets a value for `path` we know it exists; if it is set by the application, it deserves `Files.delete()` to throw.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 3]
```diff
@@ -267,18 +275,21 @@ public void writeTo(Path path) throws IOException
...
                 Files.delete(this.path);
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Should we not null-out `this.path` after `Files.delete()`?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 4]
```diff
@@ -347,15 +361,18 @@ public String toString()
...
         private final AutoLock lock = new AutoLock();
+        private final List<Content.Chunk> content = new ArrayList<>();
+        private final List<Content.Source> contentSources = new ArrayList<>();
         private boolean closed = false;
 
         public ChunksPart(String name, String fileName, HttpFields fields, List<Content.Chunk> content)
         {
             super(name, fileName, fields);
-            this.content = Objects.requireNonNull(content);
+            try (AutoLock l = lock.lock())
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Don't think it's necessary to lock here (because the constructor publishes)?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 5]
```diff
@@ -366,30 +383,53 @@ public Content.Source newContentSource()
...
         @Override
         public void close()
         {
             List<Content.Source> contentSourcesToFail = null;
             try (AutoLock l = lock.lock())
             {
+                if (closed)
+                    return;
                 closed = true;
                 if (!contentSources.isEmpty())
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Remove the if to make the code more readable?
It's just the `close()` operation, if `contentSources.isEmpty()` (unlikely) we just to very little more work.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java [hunk 6]
```diff
@@ -435,7 +429,13 @@ public void onPartContent(Content.Chunk chunk)
...
             {
                 long maxFileSize = getMaxFileSize();
-                fileSize += buffer.remaining();
+                long fileSize;
+                try (AutoLock ignored = lock.lock())
+                {
+                    fileSize = this.fileSize;
+                    fileSize += buffer.remaining();
+                    this.fileSize = fileSize;
+                }
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: I don't think `this.fileSize` needs locking. It is only ever accessed by the parser in the callbacks.
Same for `this.memoryFileSize`.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java [hunk 7]
```diff
@@ -445,7 +445,13 @@ public void onPartContent(Content.Chunk chunk)
                 long maxMemoryFileSize = getMaxMemoryFileSize();
                 if (maxMemoryFileSize >= 0)
                 {
-                    memoryFileSize += buffer.remaining();
+                    long memoryFileSize;
+                    try (AutoLock ignored = lock.lock())
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: No locking necessary here?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java [hunk 8]
```diff
@@ -468,32 +479,41 @@ public void onPartContent(Content.Chunk chunk)
...
             int remaining = buffer.remaining();
             while (remaining > 0)
             {
-                int written = fileChannel.write(buffer);
-                if (written == 0)
-                    throw new NonWritableChannelException();
-                remaining -= written;
+                try (AutoLock ignored = lock.lock())
+                {
+                    int written = fileChannel.write(buffer);
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Would not do the write with the lock held.
The only reason for the lock is to access `fileChannel`?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java [hunk 9]
```diff
@@ -468,32 +479,41 @@ public void onPartContent(Content.Chunk chunk)
...
+                        throw new NonWritableChannelException();
+                    remaining -= written;
+                }
             }
         }
 
         private void close()
         {
-            try
+            try (AutoLock ignored = lock.lock())
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Would not do the close with the lock held.
Can we just have a `fileChannel()` method that locks and returns the field?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: True, a barrier is emitted at the end of the constructor because there are final fields. Let me remove this lock.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: I thought this `if` made things clearer, but it can be removed. Let me do it.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java (hunk 6 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: You're right, but those are the only two fields that don't require locking, and they are read and modified under lock in `onPart`. For consistency and ease of mind, I think it's better to always access those two under lock.

Are you sure these two locking bits bother you that much?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java (hunk 7 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Same as above.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java (hunk 8 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Yes, it's for reading the `fileChannel` field. I could move the `write` out of the lock, but since buffers are unlikely to be big I thought this wouldn't matter.

Let me rework this.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java (hunk 9 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Same as above.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Done.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: I've done the change to set `this.path` to null after deletion, but this has one side-effect: calling `getPath()` after `delete()` now returns null while it previously returned the deleted path.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: This is a slight behavior change compared to what we used to do. I like nulling out the path after deletion better, though.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java [hunk 10]
```diff
@@ -435,7 +429,13 @@ public void onPartContent(Content.Chunk chunk)
             if (fileName != null || isUseFilesForPartsWithoutFileName())
             {
                 long maxFileSize = getMaxFileSize();
-                fileSize += buffer.remaining();
+                long fileSize;
+                try (AutoLock ignored = lock.lock())
+                {
+                    fileSize = this.fileSize;
+                    fileSize += buffer.remaining();
+                    this.fileSize = fileSize;
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: I find this way of doing it very confusing.  Isn't this just:
```suggestion
                    fileSize = this.fileSize += buffer.remaining();
```

or maybe:

```suggestion
                    this.fileSize += buffer.remaining();
                    fileSize = this.fileSize;
```

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java [hunk 11]
```diff
@@ -445,7 +445,13 @@ public void onPartContent(Content.Chunk chunk)
                 long maxMemoryFileSize = getMaxMemoryFileSize();
                 if (maxMemoryFileSize >= 0)
                 {
-                    memoryFileSize += buffer.remaining();
+                    long memoryFileSize;
+                    try (AutoLock ignored = lock.lock())
+                    {
+                        memoryFileSize = this.memoryFileSize;
+                        memoryFileSize += buffer.remaining();
+                        this.memoryFileSize = memoryFileSize;
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: same as above

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java (hunk 10 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Done.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java (hunk 11 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Done.

**Review by gregw — APPROVED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Not done?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java (hunk 6 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Locking identifies the fields that possibly are subject to concurrency, so helps understanding what are the concurrency entry points.
Having other stuff locked that does not need to seems more confusing to me.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 12]
```diff
@@ -293,8 +314,11 @@ public void fail(Throwable t)
             try
             {
                 getContentSource().fail(t);
-                if (temporary)
-                    delete();
+                try (AutoLock ignored = lock.lock())
+                {
+                    if (temporary)
+                        delete();
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: As there are only a handful filesystem operations, I'm leaning towards doing them out of locking.
Can we have a `private void delete(Path)` called outside locks that is called after `this.path = null`?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java [hunk 13]
```diff
@@ -468,23 +475,29 @@ public void onPartContent(Content.Chunk chunk)
...
+            }
         }
 
         private void write(ByteBuffer buffer) throws Exception
         {
             int remaining = buffer.remaining();
             while (remaining > 0)
             {
-                int written = fileChannel.write(buffer);
+                int written = fileChannel().write(buffer);
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: `fileChannel()` may return `null`.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java [hunk 14]
```diff
@@ -552,28 +583,34 @@ public void onFailure(Throwable failure)
...
+        }
+
         private void delete()
         {
-            try
+            try (AutoLock ignored = lock.lock())
             {
-                if (fileChannel != null)
+                if (filePath != null)
                     Files.delete(filePath);
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Can we do filesystem I/O outside locking?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java (hunk 14 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Done.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 12 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Done.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java (hunk 6 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Okay, but then `fileSize` and `memoryFileSize` are to be reset outside lock scope in `onPart` for consistency.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java (hunk 13 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPartFormData.java]: Sure, but apart from throwing a different type of exception than NPE, nothing different should be done.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 5 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: @lorban this is not resolved.
Also, removing the `if` will make the code in `fail()` and `close()` nearly identical, so perhaps extract it in a common method?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 15]
```diff
@@ -383,13 +433,14 @@ public void close()
...
                 {
-                    contentSourcesToFail = new ArrayList<>(contentSources);
+                    contentSourcesToFail = List.copyOf(contentSources);
                     contentSources.clear();
                 }
+                content.forEach(Content.Chunk::release);
+                content.clear();
             }
 
             super.close();
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Calling `super` calls `fail()`, which will do nothing because the data structures have been cleared.
I find this confusing (as you think "am I failing twice?"), so perhaps just don't call `super` at all, as we are doing all the work anyway in this overridden version.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 15 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Actually, `fail()` and `close()` are almost doing the same thing, and since `super.close()` already calls `fail()`, `close()` can just go away.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Now done.

**Review by sbordet — APPROVED** [review]
