### PR TITLE
Fixes #9539 - HttpClientTimeoutTest#testTimeoutOnFuture H3 logs excep…

### LINKED ISSUE #9539: org.eclipse.jetty.test.client.transport.HttpClientTimeoutTest#testTimeoutOnFuture  H3 logs exception
**Jetty version(s)**
12

**Description**

When running `org.eclipse.jetty.test.client.transport.HttpClientTimeoutTest#testTimeoutOnFuture` the h3 variant logs the following exception:

```
2023-03-26 00:01:43.118:WARN :oejs.Response:server-12311: writeError: status=500, message=java.io.IOException: close, response=org.eclipse.jetty.server.internal.HttpChannelState$ErrorResponse@4d1c9506
java.io.IOException: close
        at org.eclipse.jetty.http3.HTTP3Session.failStreams(HTTP3Session.java:721)
        at org.eclipse.jetty.http3.HTTP3Session.onClose(HTTP3Session.java:840)
        at org.eclipse.jetty.http3.server.internal.ServerHTTP3Session.onClose(ServerHTTP3Session.java:189)
        at org.eclipse.jetty.quic.common.ProtocolSession$StreamsProducer.produce(ProtocolSession.java:236)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:507)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:253)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
        at org.eclipse.jetty.quic.common.ProtocolSession.produce(ProtocolSession.java:78)
        at org.eclipse.jetty.quic.server.ServerProtocolSession.lambda$new$0(ServerProtocolSession.java:31)
        at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:436)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:196)
        at org.eclipse.jetty.quic.common.QuicConnection.onFillable(QuicConnection.java:164)
        at org.eclipse.jetty.quic.common.QuicConnection$FillableCallback.succeeded(QuicConnection.java:425)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:473)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:436)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:288)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:136)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Is this exception expected? If so the test needs to suppress the stack trace.
Why is this only in h3?

### PR DESCRIPTION
**Pull request by sbordet**
…tion.

HTTP3Session.onClose() was calling failStreams(), which allocated an IOException to fail the streams and eventually fail the response. Since the failure was not a QuietException, it was logged at WARN level.

### CODE REVIEW

**Review by gregw — APPROVED** [review]
Looks good

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java [hunk 1]
```diff
@@ -216,7 +217,7 @@ private CompletableFuture<Void> goAway(GoAwayFrame frame)
             {
                 long error = HTTP3ErrorCode.REQUEST_CANCELLED_ERROR.code();
                 String reason = "go_away";
-                failStreams(stream -> true, error, reason, true);
+                failStreams(stream -> true, error, reason, true, new ClosedChannelException());
```
Comment (lorban) [inline jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java:220]: Shouldn't this be a `QuietException` too?

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java [hunk 2]
```diff
@@ -666,7 +667,7 @@ public void inwardClose(long error, String reason)
             }
         }
 
-        failStreams(stream -> true, error, reason, true);
+        failStreams(stream -> true, error, reason, true, new IOException(reason));
```
Comment (lorban) [inline jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java:670]: Shouldn't this be a `QuietException` too?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java:220]: No because the quiet exceptions are used when receiving an event, while here it's generating the event.

File: jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java (hunk 2 above)
Comment (sbordet) [reply jetty-core/jetty-http3/jetty-http3-common/src/main/java/org/eclipse/jetty/http3/HTTP3Session.java:670]: No because the quiet exceptions are used when receiving an event, while here it's generating the event.

**Review by lorban — APPROVED** [review]
