### PR TITLE
Issue #4520 Reinstate throw of UnreadableSessionDataException

### LINKED ISSUE #4520: Jetty jdbc session manager causing exceptions for violating primary key in inserting session in the table
**Jetty version**
9.4.26.v20200117 and jetty-9.4.25.v20191220, maybe some older versions too

**Java version**
8

**Description**
Our application uses dropwizard 1.3.15, which comes shipped with Jetty version 9.4.18.v20190429. We have had to force bump all jetty modules to jetty-9.4.25.v20191220 in order to expose setting the samesite attribute to the session cookie for Chrome 80. Unfortunately, our application reports the following stacktrace several times a day after upgrading:

```
! com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'JETTYSESSIONS_PK'. Cannot insert duplicate key in object 'dbo.JETTYSESSIONS'. The duplicate key value is (4251317910uwtktdazin8denyp4qfdyqs57126, , 0.0.0.0). 
! at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217) 
! at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1635) 
! at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:426) 
! at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:372) 
! at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:6276) 
! at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1793) 
! at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:184) 
! at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:159) 
! at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:315) 
! at org.eclipse.jetty.server.session.JDBCSessionDataStore.doInsert(JDBCSessionDataStore.java:727) 
! at org.eclipse.jetty.server.session.JDBCSessionDataStore.doStore(JDBCSessionDataStore.java:676) 
! at org.eclipse.jetty.server.session.AbstractSessionDataStore$1.run(AbstractSessionDataStore.java:142) 
! at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1382) 
! at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1401) 
! at org.eclipse.jetty.server.session.SessionContext.run(SessionContext.java:92) 
! at org.eclipse.jetty.server.session.AbstractSessionDataStore.store(AbstractSessionDataStore.java:155) 
! at org.eclipse.jetty.server.session.AbstractSessionCache.release(AbstractSessionCache.java:566) 
! at org.eclipse.jetty.server.session.SessionHandler.complete(SessionHandler.java:368) 
! at org.eclipse.jetty.server.Request.leaveSession(Request.java:399) 
! at org.eclipse.jetty.server.Request.onCompleted(Request.java:1531) 
! at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:732) 
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:363) 
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) 
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) 
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) 
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) 
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) 
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) 
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) 
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) 
! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) 
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) 
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) 
! at java.lang.Thread.run(Thread.java:748) 
```

At the same time we are receiving these errors, I don't see any user making a call to our application, which lets me to believe that this is happening in the background every few hours or so without user interaction (simply the application running). As you can see, the full stacktrace does not include our application code, only jetty and sql related. 

We also tried version 9.4.26.v20200117, but it appears this issue still persists.

I think some change between version 9.4.18.v20190429 and 9.4.26.v20200117 caused this bug to appear, but it's quite difficult for me to try out all versions. The root issue is jetty tries to insert the same session id into the jdbc session table causing a primary key violation.

### PR DESCRIPTION
**Pull request by janbartel**
The fix for issue #3913 accidentally removed the throw of an UnreadableSessionDataException from AbstractSessionCache.get() method (the implementation of get() was changed to eventually use a lambda expression and the throw was therefore omitted).  The missing throw meant that a session that could not be read from the session data store was treated as not existing rather than existing and being unusable.  If the session is unusable the previous behaviour was to invalidate it and delete it in the store across all contexts. 

This omission came to light in issue #4520, where a flaky database connection was throwing an exception when trying to read existing session data when a request accessed the session. As null was returned rather than an exception, it seemed as if the session merely didn't exist. When application code later in the request handling asked to create a session, normal practise is to be able to use that same id, if that id is already in use (this is part of cross-context dispatch). As the faulty session had not been detected and deleted, it looked like the same id could be re-used causing a primary key clash.

Closes #4520

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/session/AbstractSessionCache.java [hunk 1]
```diff
@@ -366,10 +368,15 @@ protected Session getAndEnter(String id, boolean enter) throws Exception
...
             {
                 LOG.warn("Error loading session {}", id, e);
+                exception.set(e);
                 return null;
             }
         });
 
+        Exception ex = exception.get();
+        if (ex != null)
+            throw ex;
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/session/AbstractSessionCache.java:377]: Since now you are rethrowing the exception, you don't want to log it at warn level at 370 - otherwise it will be printed out twice.

File: tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java [hunk 2]
```diff
@@ -43,6 +48,62 @@
...
+        public boolean delete(String id) throws Exception
+        {
+            _deletedIds.add(id);
+            return true;
+        }
+
+        @Override
+        public void doStore(String id, SessionData data, long lastSaveTime) throws Exception
+        {
+            System.err.println("DOSTORE: " + id + " lastsave=" + lastSaveTime);
```
Comment (sbordet) [inline tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java]: Remove `System.err`.

File: tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java [hunk 3]
```diff
@@ -65,7 +126,56 @@ public void sessionDidActivate(HttpSessionEvent se)
...
+            Session session = context.getSessionHandler().getSession("1234");
+            assertNull(session);
+            assertTrue(store._deletedIds.contains("1234"));
+
+            //now try to make a session with the same id as if from a request with
+            //a SESSION_ID cookie set
+            Request request = new Request(null, null);
+            request.setRequestedSessionId("1234");
+            HttpSession newSession = context.getSessionHandler().newHttpSession(request);
+            assertFalse("1234".equals(newSession.getId()));
```
Comment (sbordet) [inline tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java]: Replace with `assertNotEquals()`.

File: tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java [hunk 4]
```diff
@@ -43,6 +48,62 @@
...
+        {
+            return false;
+        }
+
+        @Override
+        public boolean exists(String id) throws Exception
+        {
+            if (!_deletedIds.contains(id))
+                return true;
+            return false;
```
Comment (sbordet) [inline tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java]: Simplify into `return !...`.

File: tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java [hunk 5]
```diff
@@ -65,7 +126,56 @@ public void sessionDidActivate(HttpSessionEvent se)
...
+            HttpSession newSession = context.getSessionHandler().newHttpSession(request);
+            assertFalse("1234".equals(newSession.getId()));
+        }
+        finally
+        {
+            server.stop();
+        }
+    }
+
+
```
Comment (sbordet) [inline tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java]: Unnecessary empty line.

File: jetty-server/src/main/java/org/eclipse/jetty/server/session/AbstractSessionCache.java [hunk 6]
```diff
@@ -334,12 +335,13 @@ public Session get(String id) throws Exception
...
      * @param enter if true, the usage count of the session will be incremented
-     * @return
-     * @throws Exception
+     * @return the session if it exists, null otherwise
+     * @throws Exception if the session cannot be loaded
      */
     protected Session getAndEnter(String id, boolean enter) throws Exception
     {
         Session session = null;
+        final AtomicReference<Exception> exception = new AtomicReference<Exception>();
```
Comment (sbordet) [inline jetty-server/src/main/java/org/eclipse/jetty/server/session/AbstractSessionCache.java]: No need for `final` here.

**Review by sbordet — CHANGES_REQUESTED** [review]
I'm not sure I understand the test case.

Seems to me that it is particularly testing the fact that a deleted id is remembered, but I don't think any other data store is doing that. The JDBC data store is actually deleting the row, so a subsequent call to `exists()` for the same id would return `true`, not `false` like in the test.

I would have expected `UnreadableSessionDataStore` to just null out the field `_data` in `delete()` and implement the rest based on `_data`.

If I replace `UnreadableSessionDataStore` with `FileSessionDataStore` the test fails final assertion, i.e. it would be possible to create a new session with the same id.

File: tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java [hunk 7]
```diff
@@ -43,6 +48,62 @@
  */
 public abstract class AbstractSessionCacheTest
 {
+    public static class UnreadableSessionDataStore extends AbstractSessionDataStore
+    {
+        public Set<String> _deletedIds = ConcurrentHashMap.newKeySet();
```
Comment (sbordet) [inline tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java]: Perhaps you can just use `_data` in the implementation, so you won't need to remember deleted ids.

File: tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java (hunk 3 above)
Comment (sbordet) [reply tests/test-sessions/test-sessions-common/src/test/java/org/eclipse/jetty/server/session/AbstractSessionCacheTest.java]: Please add a comment here about the fact that since the session has been deleted, its id cannot be reused, and delete the javadoc of the method (which basically says the same, but in the wrong spot - and who reads test javadocs anyway?!? :smile:)

**Review by sbordet — APPROVED** [review]
After re-review, the fix looks good and I now understand the test better, so LGTM apart the few nitpicks detailed in the comments.
