### PR TITLE
Fix sporadic NPE in `HttpChannelState.onFailure()`

### LINKED ISSUE #12746: Sporadic NPE in HttpChannelState.onFailure
**Jetty version(s)**

12.0.16

**Jetty Environment**

ee10 

**Java version/vendor**

openjdk version "17.0.10" 2024-01-16 LTS
OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)

**OS type/version**

ubuntu22.04

**Description**
```
2025-01-29 21:15:55,115 [jetty-immediate-executor] ERROR com.tc.server.TCServerMain - Thread:Thread[jetty-immediate-executor,5,TC Thread Group] got an uncaught exception. calling CallbackOnExitDefaultHandlers.
     java.lang.NullPointerException: Cannot read field "_callback" because "this._request" is null
     	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onFailure$1(HttpChannelState.java:444)
     	at java.base/java.lang.Thread.run(Thread.java:840)
```
**How to reproduce?**

It's a Heizenbug.

### PR DESCRIPTION
**Pull request by lorban**
Backports the fix for 12.1.x.

Fixes #12746

### CODE REVIEW

**Review by gregw — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 1]
```diff
@@ -441,7 +441,10 @@ private Runnable onFailure(Throwable x, boolean remote)
             // If not handled, then we just fail the request callback
             if (!_handled && _handling == null)
             {
-                task = () -> _request._callback.failed(x);
+                if (LOG.isDebugEnabled())
+                    LOG.debug("failing request not yet handled {} {}", _request, this);
+                Callback callback = _request._callback;
+                task = () -> callback.failed(x);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:447]: This does not feel right.

`_request` is nulled out by `recycle()`.

How it is possible that `recycle()` is called _before_ one of the 3 legs of the stool (the `Handler` callback) is complete?

@gregw @lorban thoughts?

**Review by sbordet — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:447]: @sbordet this is for a failure when the request has not been handled, so do we have a 3 legged stool if nothing has handled?
The leg for handling completed does not apply.  The callback has to be completed, which this code is doing.  Hmmm who does the last write?

but then why does this PR fix anything. @lorban what exactly is the race?

**Comment by lorban** [comment]
We got this in the provided logs:
```
2025-03-27 21:56:55,526 [jetty-immediate-executor] ERROR com.tc.server.TCServerMain - Thread:Thread[jetty-immediate-executor,5,TC Thread Group] got an uncaught exception. calling CallbackOnExitDefaultHandlers.
java.lang.NullPointerException: Cannot read field "_callback" because "this._request" is null
	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onFailure$1(HttpChannelState.java:444)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
which can only come from a call to `ThreadPool.executeImmediately( HttpChannel.onFailure() )`. There was also this in the logs:

```
2025-03-27 21:56:55,518 [L2_L1:TCComm Main Selector Thread_R (listen 0:0:0:0:0:0:0:0:45451)] WARN com.tc.net.core.CoreNIOServices - Exception trying to process interest request: java.nio.channels.ClosedChannelException
```

I interpreted the _Exception trying to process interest request_ message as a clue that the callback given to `FillInterest` gets failed, i.e.: `DemandContentCallback.failed()` got called, which does the `ThreadPool.executeImmediately( HttpChannel.onFailure() )` call described above. Unfortunately, there is not enough information in the provided logs to get a clue about when the callback was failed, that could have happened before, during or after handling. But it seems to be related to some sort of abrupt failure at the socket level.

IIRC the Terracotta server is using its own connector to pass data to Jetty, so there's a chance that it creates a behavior that cannot happen with the `ServerConnector`.

**Comment by GaryWKeim** [comment]
The failure is caused by the TerracottaConnector reader thread continuing to try to read from the socket channel (even though the proxied request is consumed initially due to the SEDA stage ensuring it's complete) and sometimes seeing a new request on the channel. In trying to handle the new request (pass it to the LocalConnector endpoint), the writer completes handling the original response and closes the channel/streams/socket. I've changed the reader thread to just read (the complete request) from the channel once and the failures have ceased. So, this has been happening forever. I still think this lambda fix is righteous.

**Comment by lorban** [comment]
@GaryWKeim thanks for the feedback, that helps!

@gregw @sbordet we now know that the root cause was a bug in the Terracotta connector, but I do believe we should merge this change as it does align what 12.0 and 12.1 do.

**Review by gregw — APPROVED** [review]
