### PR TITLE
Fixes #3989 - Selector restart with custom ManagedSelector

### LINKED ISSUE #3989: Inform custom ManagedSelector of dead selector via optional onFailedSelect()
Well, not quite quietly, but it does close it with a Log.warn() message.

https://github.com/eclipse/jetty.project/blob/6a0a2883ad354f2987cf6ff6f09519bf23425906/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java#L234-L271

If the `int selected = selector.select();` has an exception ... 

Example exception:

```
java.io.IOException: Interrupted function call
 at sun.nio.ch.FileDispatcherImpl.close0(Native Method)
 at sun.nio.ch.SocketDispatcher.close(SocketDispatcher.java:55)
 at sun.nio.ch.SocketChannelImpl.kill(SocketChannelImpl.java:879)
 at sun.nio.ch.AbstractPollSelectorImpl.implDereg(AbstractPollSelectorImpl.java:194)
 at sun.nio.ch.SelectorImpl.processDeregisterQueue(SelectorImpl.java:149)
 at sun.nio.ch.PollSelectorImpl.doSelect(PollSelectorImpl.java:91)
 at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
 at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
 at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
 at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:243)
 at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:191)
 at org.eclipse.jetty.util.thread.strategy.ProduceExecuteConsume.execute(ProduceExecuteConsume.java:69)
 at org.eclipse.jetty.io.ManagedSelector.run(ManagedSelector.java:147)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
 at java.lang.Thread.run(Thread.java:748)
```

... then the selector is `closeNoExceptions(_selector);` and `select()` returns `false`

Which returns a `produce()` of `null`
Which the PEC.execute() interprets as no task and waits on its lock.
We now have no Selector running, and no way to detect this. (as the selector close produces no events, and the selector itself is not an exposed field to interrogate).

This results in a dead ServerConnector that can no longer process network events or even handle new incoming requests/connections.

### PR DESCRIPTION
**Pull request by joakime**
+ Adds onSelectFailed(Throwable)
+ Adds startSelector()
+ Unit test to demonstrate behavior on both execution
  strategies

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

File: jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java [hunk 1]
```diff
@@ -96,12 +101,25 @@ protected Selector newSelector() throws IOException
...
     }
 
+    public Selector getSelector()
+    {
+        return _selector;
+    }
+
+    protected void onSelectFailed(Throwable cause)
+    {
+        LOG.warn(toString(), cause);
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: I think we should restart the selector by default here.
If the selector has failed, then we have a dead server - unless somehow a selector restart happens. 
By restarting here we risk only that we might get into a restart loop - which again gives us a dead server, but one eating 100% CPU so it will be more obvious than one that dropped a selector.

For good servers running on proper OSs, the selector never fails in this way, so this is never a problem.  So I see little risk in restarting here.... if we ever do get a problem with restart loops, we could consider a restart quota.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java [hunk 2]
```diff
@@ -258,14 +276,17 @@ private boolean select()
...
+                {
+                    onSelectFailed(x);
+                }
                 else
                 {
                     LOG.warn(x.toString());
                     LOG.debug(x);
                 }
-                closeNoExceptions(_selector);
+                closeNoExceptions(selector);
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: Is this good enough to give close/fail notifications to all the registered EndPoints? 
I don't think it is - so we need to either ensure the endpoints are properly closed or somehow pass them to the new selector.

File: tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java [hunk 3]
```diff
@@ -0,0 +1,254 @@
...
+    public void testRebuildServerSelector() throws Exception
+    {
+        // Request /hello
+        assertRequestHello();
+
+        // Request /selector/close
+        assertRequestSelectorClose();
+
+        // Wait for selectors to close from action above
+        TimeUnit.MILLISECONDS.sleep(1000);
```
Comment (gregw) [inline tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java]: can we do this without a wait.  add a latch to your test selector so  you can see when the restart is finished

File: tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java [hunk 4]
```diff
@@ -0,0 +1,254 @@
...
+        }
+
+        @Override
+        protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException
+        {
+            resp.setContentType("text/plain");
+            resp.setCharacterEncoding("utf-8");
+            resp.getWriter().printf("Closing selectors in %,d ms%n", DELAY_MS);
+            scheduledExecutorService.schedule(interruptSelectorRunnable, DELAY_MS, TimeUnit.MILLISECONDS);
+        }
```
Comment (gregw) [inline tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java]: Can we make this a more difficult test (or another test).   Do a startAsync and register a AsyncListener, then return to jetty and have another thread do the interrupt of the selector.    If we are not rescueing end points, then the AsyncListener.onError should be called to tell the async process that you're dead!

File: jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java (hunk 2 above)
Comment (joakime) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: A SelectorProducer.select() failure has never notified registered endpoints, that would be new functionality.

The method `closeNoExceptions(Closeable)` is identical to `IO.close(Closeable)` (and in fact, could be removed from ManagedSelector)

I believe the notification of registered endpoints occurs via one of the other tasks, like DestroyEndPoint, which I don't think would work if the selector thread is dead.

Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: We never notified endpoints on select failure before because we always thought that could not happen in anyway other than a fatal exception.    But if are treating it as non fatal, then we have to either rescue the existing endpoints or close them properly. We can't just continue with hanging endpoints.

File: tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java (hunk 4 above)
Comment (joakime) [reply tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java]: ew!

File: tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java (hunk 3 above)
Comment (joakime) [reply tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java]: good idea.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java (hunk 2 above)
Comment (joakime) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: Since we would need to ask the selector what the endpoints are, we cannot reliably get the endpoints on a dead selector. 
The `Selector.keys()` will throw an exception.

**Comment by gregw** [comment]
@joakime @sbordet Hey! I've still got unresolved concerns about this, yet you have merged already!

File: tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java [hunk 5]
```diff
@@ -0,0 +1,410 @@
...
+                }
+
+                @Override
+                public void onStartAsync(AsyncEvent event)
+                {
+                }
+            });
+
+            scheduledExecutorService.schedule(new InterruptSelector(connector), DELAY_MS, TimeUnit.MILLISECONDS);
+            /* trigger EofException after selector close
```
Comment (gregw) [inline tests/test-integration/src/test/java/org/eclipse/jetty/test/RebuildSelectorTest.java]: remove commented out code
