### PR TITLE
[jetty-http-spi] Add Https Implementation

### LINKED ISSUE #13484: [jetty-http-spi] HttpsServer not implemented
**Jetty version(s)**
All of them (12, 11, 10...)

**Jetty Environment**
All of them 

**Java version/vendor** 
Java 24

**OS type/version**
Windows 

**Description**

Description
I ported code that used Java's built-in HTTP server (com.sun.net.httpserver) to Jetty's adapter. The code uses the `HttpsConfigurator` to configure SSL parameters for the server.

When trying to swap implementations to Jetty, an `UnsupportedOperationException` is thrown when trying to create it.

What's the best way to configure Jetty's SSL using the SPI? 

**How to reproduce?**

[it's just not implemented](https://github.com/SentryMan/jetty.project/blob/f335f24369c8991bb33d3bc95aacc18e51006803/jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServerProvider.java#L62-L66)

### PR DESCRIPTION
**Pull request by SentryMan**
Resolves #13484

### CODE REVIEW

File: jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java [hunk 1]
```diff
@@ -48,18 +51,28 @@ public class JettyHttpServer extends com.sun.net.httpserver.HttpServer
     private final Map<String, JettyHttpContext> _contexts = new HashMap<>();
     private final Map<String, Connector> _connectors = new HashMap<>();
     private InetSocketAddress _addr;
+    private int _backlog;
+    private HttpsConfigurator configurator;
 
-    public JettyHttpServer(Server server, boolean shared)
+    public JettyHttpServer(Server server, boolean shared, InetSocketAddress addr, int backlog)
```
Comment (olamy) [inline jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java]: Thanks for the contribution.
This is breaking backward. Would it be possible to keep backward compatibility? And add `@deprecated` where needed. Eventually remove when merging in 12.1.

**Review by olamy — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java (hunk 1 above)
Comment (SentryMan) [reply jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java]: resolved

File: jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java [hunk 2]
```diff
@@ -99,19 +104,29 @@ public void bind(InetSocketAddress addr, int backlog) throws IOException
...
+  private ServerConnector createSecureConnector(Server server) 
+  {
+    _httpConfiguration.addCustomizer(new SecureRequestCustomizer());
+    var params = new JettyHttpsParameters(configurator, _addr);
+
+    configurator.configure(params);
+    HttpConnectionFactory http11 = new HttpConnectionFactory(_httpConfiguration);
+
+    SslConnectionFactory tls =
+        new SslConnectionFactory(params.getSSLFactoryServer(), http11.getProtocol());
```
[the remark this answers is not in the document]
Comment (joakime) [reply jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java:121]: That is **not** what we want.

@SentryMan ignore this (and anything else from Copilot)

**Comment by olamy** [comment]
LGTM maybe adding a test as well?

**Comment by SentryMan** [comment]
> LGTM maybe adding a test as well?

It is done

**Comment by SentryMan** [comment]
@olamy should I make a duplicate PR for 12.1.x or what?

**Comment by olamy** [comment]
> @olamy should I make a duplicate PR for 12.1.x or what?

nah this should be fine. maybe just squash your current PR. Once I merged it, we can cherry pick to 12.1.x

File: jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java [hunk 3]
```diff
@@ -39,7 +42,7 @@
 /**
  * Jetty implementation of {@link com.sun.net.httpserver.HttpServer}.
```
Comment (olamy) [inline jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java]: javadoc link need to be updated

```suggestion
 * Jetty implementation of {@link com.sun.net.httpserver.HttpsServer}.
```

**Review by olamy — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java (hunk 3 above)
Comment (SentryMan) [reply jetty-core/jetty-http-spi/src/main/java/org/eclipse/jetty/http/spi/JettyHttpServer.java]: HttpsServer itself extends HttpServer, so it's still technically correct. Even so, I have updated it

**Review by olamy — APPROVED** [review]

**Comment by olamy** [comment]
@SentryMan thanks for your contribution (and your patience :) )
merge to 12.1 via #13536
