### PR TITLE
Issue #14264 - Send Redirect should allow for URI Fragment.

### LINKED ISSUE #14264: org.eclipse.jetty.server.Response.sendRedirect doesn't allow a location containing a fragment (/#fragment)
**Jetty version(s)**
12.1.5

**Jetty Environment**
ee11

**HTTP version**
all

**Java version/vendor** `(use: java -version)`
temurin-21-jdk-21.0.9.0.0.10-0.x86_64

**OS type/version**
Fedora release 43 (Forty Three)

**Description**

org.eclipse.jetty.server.Response.sendRedirect doesn't allow a location containing a fragment (/#fragment)

I cannot produce a nice stack trace (as requested in #11579), the following calls are made:

org.eclipse.jetty.ee11.servlet.ServletApiResponse.sendRedirect
org.eclipse.jetty.server.Response.sendRedirect

**How to reproduce?**

```
jakarta.servlet.http.HttpServletResponseWrapper().sendRedirect("https://example.com/#fragment");
```

### PR DESCRIPTION
**Pull request by joakime**
The HttpConfiguration.redirectUriCompliance should allow FRAGMENT in URI.
That is allowed per HTTP spec.

Fixes #14264

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java [hunk 1]
```diff
@@ -82,7 +83,8 @@ public class HttpConfiguration implements Dumpable
     private long _minResponseDataRate;
     private HttpCompliance _httpCompliance = HttpCompliance.RFC9110;
     private UriCompliance _uriCompliance = UriCompliance.DEFAULT;
-    private UriCompliance _redirectUriCompliance = UriCompliance.DEFAULT;
+    // Redirects are allowed to have FRAGMENT
+    private UriCompliance _redirectUriCompliance = new UriCompliance("3986RedirectDefault", EnumSet.of(UriCompliance.Violation.FRAGMENT));
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java]: Please confirm my understanding: does that modification mean that RFC 3986 (URI stuff) does not allow fragments while RFC 9110 (HTTP stuff) do allow them?

If my understanding is correct, would you mind clarifying your comment like so (or equivalent?):

```
// Redirects are allowed to have FRAGMENT per RFC 9110 while the default URI compliance prevents them
```

**Review by lorban — DISMISSED** [review]
LGTM if my understanding of the change is right

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java]: The RFC3986 spec is about the URI standard.
The RFC9110 spec controls the `http` (and `https`) URI scheme.

For RFC9110, the incoming request cannot have a FRAGMENT (it is either a failure, or it could be dropped / ignored).
But for outgoing responses, namely the `Location` response header, the FRAGMENT is allowed.

Comment (joakime) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java]: I'll update the comment to be more clear.

**Comment by joakime** [comment]
@lorban I updated the docs a bit to make things clearer, this work?

**Review by lorban — APPROVED** [review]

**Comment by lorban** [comment]
@joakime cristal clear now, thanks!
