### PR TITLE
Refine offset, length size handling in Content.Sources

### LINKED ISSUE #13685: Infinite loop on Content.copy() with Content.Source.from(... , Path, ) when Path has size 0.
**Jetty version(s)**
12.1.2

**Jetty Environment**
Jetty-12

**HTTP version**
N/A

**Java version/vendor** `(use: java -version)`
java version "21.0.2" 2024-01-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)

**OS type/version**
Linux  6.8.0-79-generic #79-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 12 14:42:46 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

**Description**

Content.copy(source,sink,cb) does not come back when a Content.Source.from(path) is given on a file that has 0 length (org.eclipse.jetty.io.internal.ByteChannelContentSource$PathContentSource).

The same is true when PathContentSource is used as the source (org.eclipse.jetty.io.content.PathContentSource).

The same does not happen on String or Byte sources. 

When PathContentSource is a part on a MultiPart ContentSource the same issue happens.

Off by 1 someplace.

**How to reproduce?**

```
import org.eclipse.jetty.io.Content;
import org.eclipse.jetty.util.BufferUtil;
import org.eclipse.jetty.util.Callback;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class PathContentSourceBug {

    static void p (String msg, Object ... args) {
        System.out.printf(msg,args);
        System.out.flush();
    }

    void ok () {
        p("Callback OK\n");
    }
    void fail(Throwable t) {
        p("Fault: \n");
        t.printStackTrace( System.out );
    }

    Content.Sink stdout () {
        return (last, byteBuffer, callback) -> {
            try
            {
                BufferUtil.writeTo(byteBuffer, System.out);
                callback.succeeded();
            }
            catch (Throwable t)
            {
                callback.failed(t);
            }
        };
    }

    void run(String[] args) throws IOException {
        Content.Sink sink = stdout();
        for(var next : args) {
            Path path = Paths.get(next);

            Content.Source source = Content.Source.from( path );
            p("Contents of: %s (size: %d bytes)\n", path, Files.size(path));
            Content.copy(source,sink,Callback.from(this::ok, this::fail));
            p("----------\n");
        }
    }

    public static void main(String[] args) throws IOException {
        new PathContentSourceBug().run(args);
    }
}
```

### PR DESCRIPTION
**Pull request by gregw**
Fix #13685 by handling zero length resources

### CODE REVIEW

**Review by lachlan-roberts — DISMISSED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ByteChannelContentSource.java [hunk 1]
```diff
@@ -155,6 +155,13 @@ public Content.Chunk read()
         try (AutoLock ignored = lock.lock())
         {
             lockedEnsureOpenOrTerminal();
+
+            if (_length == 0)
+            {
+                lockedSetTerminal(Content.Chunk.EOF);
+                return Content.Chunk.EOF;
+            }
+
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ByteChannelContentSource.java:168]: This block should be moved after the check on `_terminal` below.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ByteChannelContentSource.java
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ByteChannelContentSource.java:1]: The `locked*` methods in this class lack the `assert lock.isHeldByCurrentThread()` markers. Would you mind adding them in this PR?

File: jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java [hunk 2]
```diff
@@ -211,12 +215,15 @@ public void testAsContentSourceWithFirstAndLength(Resource resource) throws Exce
     {
         TestSink sink = new TestSink();
         Callback.Completable callback = new Callback.Completable();
-        Content.Source contentSource = IOResources.asContentSource(resource, bufferPool, 100, 500);
+
+        long offset = Math.min(resource.length(), 100);
+        long length = Math.min(resource.length() - offset, 500);
+        Content.Source contentSource = IOResources.asContentSource(resource, bufferPool, offset, length);
```
Comment (lorban) [inline jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java:228]: Interestingly, when keeping the hardcoded `offset` and `length` parameters the test still passes. But if a `MemoryResource` with length smaller than 100 was passed, that one would throw.

It looks like the contract of offset/length should be better documented and tested when they're greater than the resource size.

File: jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java
Comment (lorban) [inline jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java:1]: Some test methods still have `WithFirst` in their name, but the `first` parameter got renamed to `offset` between 12.0 and 12.1. Would you mind renaming the test methods to use `WithOffset` instead?

**Review by lorban — CHANGES_REQUESTED** [review]

**Review by sbordet — DISMISSED** [review]

File: jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java:228]: @lorban looking around we have many different implementations, some of which just ignore offset and length!
What do you think the contract should be?   IAE? Correct if possible?

@lachlan-roberts I not many of the multipart methods ignore offset and length.   Is this correct? Can you check them? I've added TODOs to this PR.

@sbordet I've dismissed your review as I agree with @lorban that we should cleanup and document this in this PR.

Comment (gregw) [reply jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java:228]: Perhaps we should standardize on using `java.util.Objects#checkFromIndexSize(offset, length, size)` ?
Transposing the args to the javadoc, this will check  that he sub-range is defined to be out of bounds if any of the following inequalities is true:
 + offset < 0
 + length < 0 (we may need to correct that to length == size for our existing contract before calling check)
 + offset + length > size, taking into account integer overflow
 + size < 0, (we may need to treat that as unknown size?)

Comment (gregw) [reply jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java:228]: Hmmm  ` IOResourceTest` has explicit tests for offset>size and length = 0, that return an empty content, plus length greater than size returns a truncated length.   I will change the contract to match.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 3]
```diff
@@ -354,6 +354,9 @@ public final Content.Source createContentSource()
         @Override
         public Content.Source newContentSource(ByteBufferPool.Sized bufferPool, long offset, long length)
         {
+            // TODO support offset and length, or document why we are keeping this
+            //      or wrap the returned Content.Source to support offset and length.
+            //      or document that we should wrap if somebody needs it.
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: This is a default implementation that is correctly overwritten by classes that support this.
So I don't think the TODO is necessary: when possible, this is implemented.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 4]
```diff
@@ -535,9 +547,30 @@ public ChunksPart(String name, String fileName, HttpFields fields, List<Content.
...
+        }
+
         @Override
         public Content.Source newContentSource(ByteBufferPool.Sized bufferPool, long offset, long length)
         {
+            long size = getLength();
+            length = TypeUtil.checkOffsetLengthSize(offset, length, size);
+
+            // TODO implement offset and length support!
+
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: This added code is not used. Leftover, or not finished?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 5]
```diff
@@ -650,9 +683,17 @@ public ContentSourcePart(String name, String fileName, HttpFields fields, Conten
...
+        public long getLength()
+        {
+            return content.getLength();
+        }
+
         @Override
         public Content.Source newContentSource(ByteBufferPool.Sized bufferPool, long offset, long length)
         {
+            length = TypeUtil.checkOffsetLengthSize(offset, length, content.getLength());
+            // TODO implement offset and length support!
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Leftover or unfinished?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ByteChannelContentSource.java [hunk 6]
```diff
@@ -263,7 +276,12 @@ public PathContentSource(ByteBufferPool.Sized byteBufferPool, Path path)
 
         public PathContentSource(ByteBufferPool.Sized byteBufferPool, Path path, long offset, long length)
         {
-            super(byteBufferPool, null, offset, length < 0L ? size(path) : length);
+            this(byteBufferPool, path, size(path), offset, length);
+        }
+
+        private PathContentSource(ByteBufferPool.Sized byteBufferPool, Path path, long size, long offset, long length)
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ByteChannelContentSource.java]: Why this new constructor?
It is possible to call `TypeUtil.checkOffsetLengthSize` from the original constructor.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java [hunk 7]
```diff
@@ -312,6 +315,77 @@ public static ByteBuffer slice(ByteBuffer buffer, int offset, int length)
...
+            if (remaining <= 0)
+                continue;
+
+            if (offset >= remaining)
+            {
+                offset -= remaining;
+                continue;
+            }
+
+            if (allAvailable)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java]: I would understand it better if this was just `if (length == -1)` given that below there is a `if (length == 0)`, so that it is clear that these branches are different cases of the `length` value.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Comment by sbordet** [comment]
@gregw lots of TODO in this PR, still a work in progress?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: The default implementation should not be wrong.  Either is should throw if `offset !=0 || length != -1 && length!=getLength()`   OR it can just implement the contract correctly.   I think Lachlan needs to implement a generic `Source` wrapper that can do an offset and length, so that can be used here.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Not finished.   @Lachlan is working on it (I hope)

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 5 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: unfinished

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ByteChannelContentSource.java (hunk 6 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ByteChannelContentSource.java]: Because before I implemented the checkOffsetLengthSize utility method, the size was needed multiple times and was expensive to calculate.

**Comment by gregw** [comment]
@lachlan-roberts I'v created #13789 with just the bug fix elements of the PR.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 8]
```diff
@@ -0,0 +1,140 @@
...
+// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
+// ========================================================================
+//
+
+package org.eclipse.jetty.io.internal;
+
+import org.eclipse.jetty.io.Content;
+import org.eclipse.jetty.util.TypeUtil;
+
+public class ContentSourceRange implements Content.Source
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java:25]: @lachlan-roberts I know this is internal, but a little javadoc would be good!

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 9]
```diff
@@ -0,0 +1,140 @@
...
+        {
+            Content.Chunk chunk = _source.read();
+            if (chunk == null)
+                return null;
+
+            if (_offsetRemaining > 0)
+            {
+                if (_offsetRemaining >= chunk.remaining())
+                {
+                    // We can skip this whole chunk.
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java:107]: @lachlan-roberts What if it is an error chunk?  especially what if it is a transient error chunk?  I've added the failure check above (when I push)

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 10]
```diff
@@ -0,0 +1,140 @@
...
+                    _offsetRemaining = 0;
+                }
+            }
+
+            // We can start processing the limited length if we have reached the starting offset.
+            if (_offsetRemaining == 0 && _lengthRemaining >= 0)
+            {
+                if (_lengthRemaining == 0)
+                {
+                    // Release the chunk and continue until we find a last chunk.
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: @lachlan-roberts I wonder if we should just fail the source and return EOF rather than reading until the end? Maybe an option to do that?

Comment (lachlan-roberts) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: Yeah good point, I added this as an option (which is now the default).

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java (hunk 8 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java:25]: done

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java (hunk 9 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java:107]: This was already handled before with the `chunk.isLast()` case.

But I think this additional check is fine.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 11]
```diff
@@ -0,0 +1,176 @@
...
+        _lengthRemaining = _length;
+    }
+
+    /**
+     * @param readToEof - if true, read until EOF of the source after the range is read.
+     */
+    public void setReadToEof(boolean readToEof)
+    {
+        _readToEof = readToEof;
+    }
```
Comment (gregw) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: pass in as final field

Comment (lachlan-roberts) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: done

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 12]
```diff
@@ -535,9 +546,28 @@ public ChunksPart(String name, String fileName, HttpFields fields, List<Content.
             content.forEach(Content.Chunk::retain);
         }
 
+        @Override
+        public long getLength()
+        {
+            long length = 0;
+            for (Content.Chunk c : content)
+                length += c.size();
+            for (Content.Source s : contentSources)
```
Comment (lorban) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: I don't think `contentSources` should be accounted for as a new one referencing the `content` chunk list is created each time `newContentSource()` is called.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 13]
```diff
@@ -556,7 +586,7 @@ public Content.Source newContentSource(ByteBufferPool.Sized bufferPool, long off
                 ChunksContentSource newContentSource = new ChunksContentSource(chunks);
                 chunks.forEach(Content.Chunk::release);
                 contentSources.add(newContentSource);
-                return newContentSource;
+                return Content.Source.from(newContentSource, offset, length);
```
Comment (lorban) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:582]: If the length is short enough that it leaves some chunks totally untouched in the wrapped content source, wouldn't that lead to some buffer leak as the `ContentSourceRange` won't read until EOF?

There should be a test explicitly doing this and using the leak tracking pool.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 14]
```diff
@@ -0,0 +1,187 @@
...
+
+import java.nio.channels.ClosedChannelException;
+
+import org.eclipse.jetty.io.Content;
+import org.eclipse.jetty.util.TypeUtil;
+
+/**
+ * A {@link Content.Source} that provides a range of content from another {@link Content.Source}.
+ */
+public class ContentSourceRange implements Content.Source
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java:25]: I like that this wrapper allows to have the bounds checks done in a single place. But I do not like that it introduces a concern represented by the `_readToEof` flag controlling if the wrapped resource should be depleted or not. I fear it would be too easy to introduce a resource leak by using this wrapper and not considering the flag whose default to `false` would create a leak if the wrapped resource is not lifecycled separately.

File: jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java [hunk 15]
```diff
@@ -180,11 +182,16 @@ public void testAsContentSource(Resource resource) throws Exception
 
     @ParameterizedTest
     @MethodSource("all")
-    public void testAsContentSourceWithFirst(Resource resource) throws Exception
+    public void testAsContentSourceWithOffset(Resource resource) throws Exception
     {
         TestSink sink = new TestSink();
         Callback.Completable callback = new Callback.Completable();
 
+        if (resource.length() < 100)
```
Comment (lorban) [inline jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/IOResourcesTest.java]: How about when `resource.length()` returns -1 (length unknown) but the resource does contain over 100 bytes?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java [hunk 16]
```diff
@@ -906,4 +896,38 @@ else if (value.getClass().isArray())
...
+     * @param length the length of the subrange, -1 for the full length available from the offset,
+     *               otherwise must be greater than or equal to 0.
+     *               If the size is known, then the length will be reduced if necessary to fit within the size-offset.
+     * @param size the size of the range, or -1 if unknown.
+     * @return the length of the subrange, which may be calculated if length was less than 0 or if the length is limited by
+     *         a known size.
+     * @throws IndexOutOfBoundsException if the offset or length are out of range.
+     * @throws ArithmeticException if the length is not -1 and offset+length overflows.
+     */
+    public static long checkOffsetLengthSize(long offset, long length, long size)
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java]: You should add a `throws` directive following the javadoc.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java [hunk 17]
```diff
@@ -906,4 +896,38 @@ else if (value.getClass().isArray())
...
+    {
+        if (length == 0)
+            return 0;
+
+        if (offset < 0)
+            throw new IndexOutOfBoundsException("Negative offset: " + offset);
+        if (length < -1)
```
Comment (lorban) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/TypeUtil.java]: Could you please suffix your long constants with a `L` so that they look like `0L` or `-1L`? This makes it immediately obvious that we're dealing with `long`s and help reading the code.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 13 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:582]: The ContentSourceRange class will either read to EOF or fail the content source.  So the fail impl should do the right thing with releasing unread chunks.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java (hunk 14 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java:25]: If this class doesn't read to EOF it fails the source.  If that leaks, then that is a fault of the source and not this class.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 13 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:582]: Right, I missed that when `ContentSourceRange` does not read to EOF it fails the wrapped source.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java (hunk 14 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java:25]: Agreed, I missed that not reading to EOF means failing the wrapped resource.

**Review by lorban — APPROVED** [review]

**Review by lorban — CHANGES_REQUESTED** [review]
Could you please review `FileMappingHttpContentFactory` too?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 18]
```diff
@@ -0,0 +1,187 @@
...
+            if (_offsetRemaining > 0)
+            {
+                if (_offsetRemaining >= chunk.remaining())
+                {
+                    // We can skip this whole chunk.
+                    _offsetRemaining -= chunk.remaining();
+                    if (chunk.isLast())
+                    {
+                        chunk.clear();
+                        return chunk;
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: I find this confusing, and I think it is missing a call to `release()`.
I don't think we can trust the application to call `release()` on a last+empty chunk, as it is often assumed that the buffer inside is `BufferUtil.EMPTY_BUFFER` and so it does not need `release()`.
I would rather do it here where we know we have to `release()`.

Should not it be:


```suggestion
                        chunk.release();
                        return Chunk.EOF;
```

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 19]
```diff
@@ -0,0 +1,187 @@
...
+                    }
+
+                    // Release the chunk and continue until we find a last chunk.
+                    if (!chunk.isLast())
+                    {
+                        chunk.release();
+                        continue;
+                    }
+
+                    chunk.clear();
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: I think again this is missing a `release()`.


```suggestion
                    chunk.release();
                    return Chunk.EOF;
```

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 20]
```diff
@@ -0,0 +1,187 @@
...
+                }
+                else if (_lengthRemaining >= chunk.remaining())
+                {
+                    // We can take the whole chunk.
+                    _lengthRemaining -= chunk.remaining();
+                }
+                else if (_lengthRemaining < chunk.remaining())
+                {
+                    // We must limit the size of the chunk to the remaining length.
+                    chunk.limit(_lengthRemaining);
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: I think here we should `slice()` rather than changing the limit, so we are sure the application cannot read past what it is supposed to.

Comment (sbordet) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: I would also change this chain of `else-if` into just `if` with an explicit return (no need for the `if` for the last case)`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 21]
```diff
@@ -0,0 +1,187 @@
...
+                else
+                {
+                    // Advance position to the correct offset.
+                    chunk.skip(_offsetRemaining);
+                    _offsetRemaining = 0;
+                }
+            }
+
+            // We can start processing the limited length if we have reached the starting offset.
+            if (_offsetRemaining == 0 && _lengthRemaining >= 0)
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: Isn't `_offsetRemaining == 0` always true here?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 22]
```diff
@@ -0,0 +1,187 @@
...
+            {
+                if (_lengthRemaining == 0)
+                {
+                    if (!_readToEof)
+                    {
+                        // We do not have to read until EOF of the source, so we can return EOF now and fail the source.
+                        _source.fail(new ClosedChannelException());
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]:
```suggestion
                        fail(new ClosedChannelException());
```

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java [hunk 23]
```diff
@@ -312,6 +315,76 @@ public static ByteBuffer slice(ByteBuffer buffer, int offset, int length)
...
+     * Slice a collection of ByteBuffers given an offset and a length, with checks similar to
+     * {@link TypeUtil#checkOffsetLengthSize(long, long, long)}.
+     *
+     * @param byteBuffers The buffers to slice (positions/limits respected; no mutation)
+     * @param offset The offset, relative to the current position of the buffers, must be non-negative
+     * @param length The length; -1 means "to the end" of the buffers
+     * @return the sliced buffers in a new collection, which may be immutable and may contain the original buffers or slices of them
+     * @throws IndexOutOfBoundsException if the offset or length are invalid
+     */
+    public static Collection<ByteBuffer> slice(Collection<ByteBuffer> byteBuffers, long offset, long length)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java]: I would return `List` because it implies the order of the buffers is important, but it's minor.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 24]
```diff
@@ -0,0 +1,194 @@
...
+        return _length;
+    }
+
+    @Override
+    public Content.Chunk read()
+    {
+        if (_terminal != null)
+        {
+            Content.Chunk chunk = _terminal;
+            _terminal = Content.Chunk.next(_terminal);
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: To be consistent with other places in this class:


```suggestion
            _terminal = Content.Chunk.next(chunk);
```

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 25]
```diff
@@ -0,0 +1,194 @@
...
+                return chunk;
+            }
+
+            if (_offsetRemaining > 0)
+            {
+                if (_offsetRemaining >= chunk.remaining())
+                {
+                    // We can skip this whole chunk.
+                    _offsetRemaining -= chunk.remaining();
+                    chunk.clear();
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: No need to clear?
I do not think we should modify the original chunk in any way, as the original `Content.Source` may be read by other code.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 26]
```diff
@@ -0,0 +1,194 @@
...
+
+            // We can start processing the limited length if we have reached the starting offset.
+
+            if (_lengthRemaining == 0)
+            {
+                // We have read all we need to
+                if (_readToEof)
+                {
+                    // Release the chunk and continue until we find the last chunk.
+                    chunk.clear();
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: No need to clear?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 27]
```diff
@@ -0,0 +1,194 @@
...
+                fail(new ClosedChannelException());
+                return _terminal = Content.Chunk.EOF;
+            }
+
+            if (_lengthRemaining > 0 && _lengthRemaining < chunk.remaining())
+            {
+                // We must limit the size of the chunk to the remaining length.
+                RetainableByteBuffer slice = chunk.slice(_lengthRemaining);
+                _lengthRemaining = 0;
+                chunk.clear();
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: No need to clear?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 28]
```diff
@@ -0,0 +1,194 @@
...
+                    chunk.clear();
+                    chunk.release();
+                    if (chunk.isLast())
+                        return _terminal = Content.Chunk.EOF;
+                    continue;
+                }
+                else
+                {
+                    // Advance position to the correct offset.
+                    chunk.skip(_offsetRemaining);
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: This changes the chunk of the nested `Content.Source`, while in all the other places we slice it and we don't change the original chunk.

I am worried that for original `Content.Source` that do not create the chunks on-the-fly, modifying one of their chunks here would eventually be a problem if some other code reads independently the original `Content.Source`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java (hunk 25 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: I agree there is no need to clear, but not for the reason you give.

**Comment by gregw** [comment]
@sbordet I don't really agree that we should not modify the the chunk at all.  But I made the changes anyway, as it should be cheap with reference counting.

**Review by sbordet — DISMISSED** [review]

**Review by lorban — DISMISSED** [review]
I added missing range checks in `HttpContent.writeTo()` implementations.

LGTM, but please review my (rather small) changes before merging.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java [hunk 29]
```diff
@@ -367,6 +368,7 @@ public void writeTo(Content.Sink sink, long offset, long length, Callback callba
             boolean retained = false;
             try
             {
+                TypeUtil.checkOffsetLengthSize(offset, length, _buffer.remaining());
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: `TypeUtil.checkOffsetLengthSize()` returns a value that is ignored here.
I think `length` should be updated with the return value?
Same for the other places.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java (hunk 29 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: @sbordet this is a small change in behaviour of `writeTo`, but the previous behaviour was not documented, so OK.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java [hunk 30]
```diff
@@ -334,7 +335,7 @@ public CachedHttpContent(String key, HttpContent httpContent)
                 throw new IllegalArgumentException("Resource is too large: length " + contentLengthValue + " > " + _maxCachedFileSize);
 
             // Read the content into memory
-            _buffer = IOResources.toRetainableByteBuffer(httpContent.getResource(), _bufferPool);
+            _buffer.set(IOResources.toRetainableByteBuffer(httpContent.getResource(), _bufferPool));
```
Comment (lorban) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java:338]: Can `IOResources.toRetainableByteBuffer()` ever return null?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java (hunk 30 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java:338]: @lorban it doesn't matter if it does. That will just cause calls to be delegated to the original wrapped content

Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java:338]: My point is that I don't think it ever can, so the null checks shouldn't be needed.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java [hunk 31]
```diff
@@ -394,15 +402,20 @@ private boolean tryRetain()
...
             }) != null;
         }
 
         @Override
         public void release()
         {
-            _buffer.release();
+            RetainableByteBuffer buffer = _buffer.get();
+            if (buffer != null && buffer.release())
+                _buffer.set(null);
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: Use `AtomicReference.getAndUpdate()` instead.


```suggestion
            _buffer.getAndUpdate(buffer -> 
            {
                if (buffer != null && buffer.release())
                    return null;
                return buffer;  
            });
```

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java (hunk 31 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: If the `_buffer` field can ever be null (see my previous comment), I don't mind this suggestion. But my understanding of the code is that `_buffer` can never be null.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java (hunk 30 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java:338]: The null check is needed because we now null the reference when the buffer is released

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java (hunk 31 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/content/CachingHttpContentFactory.java]: @lorban, we are deliberately nulling the reference so that if the buffer is released this content still works if writeTo is called.   I'm not exactly sure of the use-case for that, but we do have a test for it.

**Review by sbordet — DISMISSED** [review]

**Review by lorban — DISMISSED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 32]
```diff
@@ -0,0 +1,195 @@
...
+                    continue;
+                }
+                else
+                {
+                    // Advance position to the correct offset.
+                    RetainableByteBuffer slice = chunk.slice();
+                    _offsetRemaining -= slice.skip(_offsetRemaining);
+                    chunk.release();
+                    if (_offsetRemaining > 0)
+                        continue;
```
Comment (lachlan-roberts) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: I don't think this case could ever occur because at this point we know `_offsetRemaining < chunk.remaining()`.

So I think this case can be removed. But if you keep it I think this needs an extra `chunk.release()`.

I assume we have the `chunk.release()` on line 119 because the `slice` does a retain, but if we do a `continue` and discard the chunk then we need to fully release it.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java [hunk 33]
```diff
@@ -0,0 +1,195 @@
...
+                    chunk = Content.Chunk.from(slice, chunk.isLast());
+                }
+            }
+
+            // We can start processing the limited length if we have reached the starting offset.
+
```
Comment (lachlan-roberts) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: remove empty line

**Review by lachlan-roberts — CHANGES_REQUESTED** [review]
There are also merge conflicts.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java (hunk 32 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceRange.java]: This should never happen with our current implementations of skip, but the contract returns "the number of bytes actually skipped", so there may be reasons for less bytes to be skipped than we wanted to.  Actually, we should just loop in that case...

**Comment by lachlan-roberts** [comment]
@gregw there is a test failure about unconsumed content.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 34]
```diff
@@ -961,6 +1004,11 @@ static Chunk from(ByteBuffer byteBuffer, boolean last)
             return last ? EOF : EMPTY;
         }
 
+        static Chunk from(RetainableByteBuffer buffer, boolean last)
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java:1015]: Please add some Javadoc.

**Review by lorban — DISMISSED** [review]
There's one bit of javadoc missing, otherwise LGTM.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 35]
```diff
@@ -961,6 +1004,19 @@ static Chunk from(ByteBuffer byteBuffer, boolean last)
             return last ? EOF : EMPTY;
         }
 
+        /**
+         * <p>Creates a Chunk with the given RetainableByteBuffer</p>
+         * <p>The returned Chunk must is not {@link #retain() retained} and {@link #release() releasing it
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]:
```suggestion
         * <p>The returned Chunk is not {@link #retain() retained} and {@link #release() releasing it
```

**Review by lorban — DISMISSED** [review]
Just one last tiny nit.
