### PR TITLE
Fix contains in HttpFields name set and prove random access to HttpFields via EnumMap not worth it.

### LINKED ISSUE #11811: getHeaderNames should return header name once also when request has it in different case
**Jetty version(s)**
12.0.9

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
Java 22

**OS type/version**
MacOS

**Description**
`request.getHeaderNames` is typically used to iterate over header names in the request and then `request.getHeaders` is used to retrieve values:

```java
// example code supposed tor resemble typical use of getHeaderNames()
Enumeration<String> names = servletRequest.getHeaderNames();
while (names.hasMoreElements()) {
    String name = names.nextElement();
    doSomething(name, servletRequest.getHeaders(name))
}
```

When request contains both `Foo-Bar` and `foo-bar` headers, `getHeaderNames` returns both String values, so `foo-bar` header values are processed twice.

**How to reproduce?**

```shell
curl -H 'Foo-Bar: one' -H 'foo-bar: two'  http://localhost:8080/endpoint
```

### PR DESCRIPTION
**Pull request by gregw**
This is an experiment towards fix #11811 with regards to the extra comments received on #11823

It provides an optional random access implementation and fixes the issue that the name set returned is not case sensitive.

Another approach could be to always create the EnumMap when an immutable HttpFields is created and only do the iteration lookup on fields that are not  known HttpHeaders

### CODE REVIEW

**Comment by gregw** [comment]
@sbordet @lachlan-roberts @lorban review please

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 1]
```diff
@@ -618,6 +641,8 @@ else if (seenByHeader.add(header))
             }
         }
 
+        Set<String> seenByName = buildByName;
```
Comment (lorban) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:632]: Nit: you could make `Set<String> seenByName` a final field of the anonymous AbstractSet.

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java [hunk 2]
```diff
@@ -371,9 +385,19 @@ public void testCaseInsensitive()
         assertThat(header.get("Foo-Bar"), is("one"));
         assertThat(header.getValuesList("foo-bar"), contains("one", "two"));
         assertThat(header.getValuesList("Foo-Bar"), contains("one", "two"));
+        assertTrue(header.contains("foo-bar"));
+        assertTrue(header.contains("Foo-Bar"));
 
         // We know the order of the set is deterministic
-        assertThat(header.getFieldNamesCollection(), contains("expect", "RaNdOm", "Accept-Charset", "foo-bar"));
+        Set<String> names = header.getFieldNamesCollection();
```
Comment (lorban) [inline jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java:390]: You should test `iterator()` too.

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java [hunk 3]
```diff
@@ -1467,4 +1491,70 @@ public HttpField onReplaceField(HttpField oldField, HttpField newField)
...
+
+        assertThat(header.get("foo-bar"), is("one"));
+        assertThat(header.get("Foo-Bar"), is("one"));
+        assertThat(header.getValuesList("foo-bar"), contains("one", "two"));
+        assertThat(header.getValuesList("Foo-Bar"), contains("one", "two"));
+        assertTrue(header.contains("foo-bar"));
+        assertTrue(header.contains("Foo-Bar"));
+
+        // We know the order of the set is deterministic
+        Set<String> names = header.getFieldNamesCollection();
```
Comment (lorban) [inline jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java]: You should test `iterator()` too.

**Review by lorban — CHANGES_REQUESTED** [review]
Almost LGTM. I would just like to see some checks for the iterator.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 4]
```diff
@@ -196,6 +203,18 @@ default HttpFields asImmutable()
...
     }
 
+    /**
+     * <p>Returns an immutable version of this {@code HttpFields} instance, possibly optimized for random field
+     * access via {@link Map} implementations. If this {@code HttpFields} is mutable, then subsequent modifications
+     * are not reflected in the instance returned by this method.</p>
+     *
+     * @return an {@link HttpFields} instance, which may be optimized for random access.
+     */
+    default HttpFields asMappedAccess()
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Do we really need this?
It's a lot of code, a lot of tests, and I fail to see the use case.

We have already determined that `Set` is _in practice_ slower than `List` in almost all cases, despite the theory.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Probably not.    This was more an exercise in improving the testing of HttpFields and to see what random access could look like.   Now that it is written, I think we could offer it, with no harm as it is entirely optional.
When I have a moment, I'll do some extras JMH tests with EnumSet.   Or maybe we just offer the class as a wrapper?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java:632]: @lorban actually I can't, as buildByName is not itself final, it can't be used to initialze even a final field in the inner class.

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java:390]: I'm pretty sure that is what `contains` is doing?  Or do you mean the header iterator?

File: jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-http/src/test/java/org/eclipse/jetty/http/HttpFieldsTest.java]: which iterator? test how other than what `contains` does below?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: @lorban @sbordet 
Probably not.    This was more an exercise in improving the testing of HttpFields and to see what random access could look like.   Now that it is written, I think we could offer it, with no harm as it is entirely optional.
When I have a moment, I'll do some extras JMH tests with EnumSet....  oh did it...

```
Benchmark                                             Mode  Cnt          Score          Error  Units
HashMapVsEnumMapBenchmark.testEnumMapBuildAndLookup  thrpt    3  238432890.283 ± 79828131.575  ops/s
HashMapVsEnumMapBenchmark.testHashMapBuildAndLookup  thrpt    3   58008556.754 ±  4374032.136  ops/s
```

So EnumMap is an order of magnitude faster than HashMap.   I wonder if we should just always build a `EnumMap` of known headers and let the others be done with the list.   The problem there is that misses will always need to iterate.

Hmmmm

Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: I'm tempted to believe that iterating the list will have comparable perf to looking up in a hash map, assuming the list stays small.

After a second thought, I don't mind this extra `asMappedAccess()` but if it doesn't bring any measurable improvement, it should probably go.

Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: > I'm tempted to believe that iterating the list will have comparable perf to looking up in a hash map, assuming the list stays small.

We measured multiple times that a list is faster than a map/set up until about 250 elements, which is never going to be the case for the number of HTTP headers.

I don't see the point of adding more APIs to maintain, and I'm positive any difference will be buried into the noise of all the rest.
I'd keep it simpler.

Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: I expanded the JMH to test enum field look up vs a list, but also using the full HttpHeader enum rather than a nominal little enum.  List is still way better, even for small sets of fields and missed lookup.  So I'm closing this.

**Comment by gregw** [comment]
I have removed the random access class,   but there are some other minor fixes in this PR (for contains checks in name sets). Also some javadoc improvements and the JMH test to show that even enumMap doesn't help.

**Review by lorban — APPROVED** [review]

**Review by lachlan-roberts — APPROVED** [review]

**Review by sbordet — APPROVED** [review]
