### PR TITLE
Remove buffer from pool on write failure

### LINKED ISSUE #11854: HTTP2 async failure on a stream can lead to the connection being aborted
**Jetty version(s)**
12.0.9

**Description**
If an HTTP2 stream gets interrupted by an async failure (like a RESET frame), there is a possibility that the connection gets aborted abruptly.

The cause of this problem is that if the server is busy writing some byte buffers to the socket while `HttpChannel.onFailure()` is called by a different thread, the callback passed to `ChannelResponse.write()` is failed, releasing the byte buffers back to the pool after resetting them while the `SocketChannel.write()` is still running. Upon returning, the NIO call fails with `IllegalArgumentException` while trying to update the `limit`, like so:

```
java.lang.IllegalArgumentException: newPosition > limit: (14 > 0)
	at java.base/java.nio.Buffer.createPositionException(Buffer.java:352)
	at java.base/java.nio.Buffer.position(Buffer.java:327)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1551)
	at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:328)
	at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:73)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:237)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:158)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:574)
	at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:660)
	at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:111)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:275)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:368)
	at org.eclipse.jetty.http2.internal.HTTP2Flusher.process(HTTP2Flusher.java:292)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:250)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:231)
	at org.eclipse.jetty.http2.HTTP2Session.frame(HTTP2Session.java:817)
	at org.eclipse.jetty.http2.HTTP2Session.frames(HTTP2Session.java:790)
	at org.eclipse.jetty.http2.HTTP2Stream.send(HTTP2Stream.java:146)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2.sendHeaders(HttpStreamOverHTTP2.java:395)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2.send(HttpStreamOverHTTP2.java:286)
	at org.eclipse.jetty.server.HttpStream$Wrapper.send(HttpStream.java:179)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1263)
	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:751)
	at org.eclipse.jetty.server.handler.EventsHandler$EventsResponse.write(EventsHandler.java:353)
	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:751)
	at org.eclipse.jetty.server.handler.EventsHandler$EventsResponse.write(EventsHandler.java:353)
	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:751)
	at org.eclipse.jetty.server.handler.ContextResponse.write(ContextResponse.java:56)
	at org.eclipse.jetty.ee10.servlet.ServletContextResponse.write(ServletContextResponse.java:288)
	at org.eclipse.jetty.ee10.servlet.HttpOutput.channelWrite(HttpOutput.java:205)
	at org.eclipse.jetty.ee10.servlet.HttpOutput.complete(HttpOutput.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletContextResponse.completeOutput(ServletContextResponse.java:212)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:576)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:851)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740)
	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:81)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740)
	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:81)
	at org.eclipse.jetty.server.Server.handle(Server.java:179)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:635)
	at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.run(HttpStreamOverHTTP2.java:133)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	at org.eclipse.jetty.http2.server.internal.HTTP2ServerConnection.onOpen(HTTP2ServerConnection.java:115)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:435)
	at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.upgrade(HttpConnection.java:1495)
	at org.eclipse.jetty.server.internal.HttpConnection.upgrade(HttpConnection.java:582)
	at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.headerComplete(HttpConnection.java:1321)
	at org.eclipse.jetty.server.internal.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:962)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1345)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1641)
	at org.eclipse.jetty.server.internal.HttpConnection.parseRequestBuffer(HttpConnection.java:568)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:391)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.MonitoredQueuedThreadPool$1.run(MonitoredQueuedThreadPool.java:73)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

or

```
java.lang.IllegalArgumentException: newPosition > limit: (370 > 0)
	at java.base/java.nio.Buffer.createPositionException(Buffer.java:352)
	at java.base/java.nio.Buffer.position(Buffer.java:327)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1551)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:237)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:158)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:574)
	at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:660)
	at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:111)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:275)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:368)
	at org.eclipse.jetty.http2.internal.HTTP2Flusher.process(HTTP2Flusher.java:292)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:250)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:231)
	at org.eclipse.jetty.http2.HTTP2Session.frame(HTTP2Session.java:817)
	at org.eclipse.jetty.http2.HTTP2Session.frames(HTTP2Session.java:790)
	at org.eclipse.jetty.http2.HTTP2Stream.send(HTTP2Stream.java:146)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2.sendHeaders(HttpStreamOverHTTP2.java:395)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2.send(HttpStreamOverHTTP2.java:286)
	at org.eclipse.jetty.server.HttpStream$Wrapper.send(HttpStream.java:179)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1263)
	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:751)
	at org.eclipse.jetty.server.handler.EventsHandler$EventsResponse.write(EventsHandler.java:353)
	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:751)
	at org.eclipse.jetty.server.handler.EventsHandler$EventsResponse.write(EventsHandler.java:353)
	at org.eclipse.jetty.server.Response$Wrapper.write(Response.java:751)
	at org.eclipse.jetty.server.handler.ContextResponse.write(ContextResponse.java:56)
	at org.eclipse.jetty.ee10.servlet.ServletContextResponse.write(ServletContextResponse.java:288)
	at org.eclipse.jetty.server.handler.ErrorHandler.generateAcceptableResponse(ErrorHandler.java:254)
	at org.eclipse.jetty.server.handler.ErrorHandler.generateResponse(ErrorHandler.java:160)
	at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:115)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:496)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:597)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:851)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740)
	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:81)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740)
	at org.eclipse.jetty.server.handler.EventsHandler.handle(EventsHandler.java:81)
	at org.eclipse.jetty.server.Server.handle(Server.java:179)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:635)
	at org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.run(HttpStreamOverHTTP2.java:133)
	at org.eclipse.jetty.util.thread.MonitoredQueuedThreadPool$1.run(MonitoredQueuedThreadPool.java:73)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Since that exception is thrown from the lowest layer, it is the `HTTP2Flusher` that catches it and its only option is to close the TCP connection as it cannot differentiate between streams.

### PR DESCRIPTION
**Pull request by gregw**
Fixes #11854 by removing buffers from the pool when failed during a write.
This is an alternative solution to #11876

### CODE REVIEW

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java [hunk 1]
```diff
@@ -581,29 +588,69 @@ private Pool.Entry<RetainableByteBuffer> evict()
...
-            }
+                ArrayByteBufferPool.this.release(_bucket, _entry);
             return released;
         }
 
+        @Override
+        public boolean remove()
+        {
+            boolean removed = ArrayByteBufferPool.this.remove(_bucket, _entry);
+            release();
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java]: Calling release here looks wrong: this would reset the buffer - which we do not want here - and increment the released stat and the removed stat which would be incremented twice because `ArrayByteBufferPool.remove()` already incremented it once.

But calling `super.release()` is still needed to decrement the ref counter.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java [hunk 2]
```diff
@@ -581,29 +588,69 @@ private Pool.Entry<RetainableByteBuffer> evict()
         }
     }
 
-    private static class Buffer extends AbstractRetainableByteBuffer
+    private interface Removable
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java]: I'd prefer to make this interface an abstract class extending from `AbstractRetainableByteBuffer`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java [hunk 3]
```diff
@@ -205,24 +205,33 @@ public RetainableByteBuffer acquire(int size, boolean direct)
...
-        if (entry != null)
+        if (entry == null)
         {
-            bucket.recordPooled();
-            RetainableByteBuffer buffer = entry.getPooled();
-            ((Buffer)buffer).acquire();
-            return buffer;
+            ByteBuffer buffer = BufferUtil.allocate(bucket.getCapacity(), direct);
+            ReservedBuffer reserved = new ReservedBuffer(buffer, bucket);
+            reserved.acquire();
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java]: This `acquire()` call could be moved to the `ReservedBuffer` constructor.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpOutput.java
Comment (lorban) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpOutput.java:1]: A similar change is needed in EE9 and `ErrorHandler`.

**Review by lorban — CHANGES_REQUESTED** [review]

**Comment by gregw** [comment]
@lorban I can make the changes you suggest.... but what do you think of the general approach?  Workable?

**Comment by lorban** [comment]
@gregw I commented this approach here: https://github.com/jetty/jetty.project/pull/11876#issuecomment-2188442737

In short: I think this is the best way to go for 12.0, and we should move most/all `Callback.abort()` work to 12.1.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java [hunk 4]
```diff
@@ -579,20 +580,27 @@ public String toString()
...
+        public void succeeded()
         {
-            _retainable.release();
+            ExceptionUtil.callAndThen(_buffer::release, _callback::succeeded);
+        }
+
+        @Override
+        public void failed(Throwable x)
+        {
+            ExceptionUtil.callAndThen(x, t -> _buffer.remove(), _callback::failed);
```
Comment (lorban) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java]: So in the case of an async abort, `failed` would be called, removing the buffer and decrementing its ref counter then `succeeded` would be called to, trying to decrement the ref counter once more.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java [hunk 5]
```diff
@@ -159,6 +159,18 @@ default void clear()
...
     }
 
+    /**
+     * {@link #release() Release} the buffer in a way that will remove it from any pool that it may be in.
+     * If the buffer is not in a pool, calling this method is equivalent to calling {@link #release()}.
+     * Calling this method satisfies any contract that requires a call to {@link #release()}.
+     * @return {@code true} if a call to {@link #release()} would have returned {@code true}.
+     * @see #release()
+     */
+    default boolean remove()
```
Comment (lorban) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: I very much don't like this new RBB method, for at least these reasons:

First, do we want to introduce this API change in 12.0 but not have it in 12.1? That doesn't sound right to me.

Then I don't think conflating the removal from the pool with the ref counter tracking is the right way to go: when `failed/abort` is called between `write` and `succeeded` the RBB should be removed from the pool but its ref counter should be left untouched as we're still waiting for the `succeeded` call. But there's also the complicating factor of the `write` / `failed` sequence that should release but not remove.

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java (hunk 5 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: @lorban The problem without having this method is two fold:
 + Buffers cannot be wrapped (as in tacking apps) as that will prevent downcasting to find a removable buffer.   Perhaps a standard wrapper might help, but ultimately a buffer could be wrapped strangely.
 + We'd have to pass the pool around in places, so that we have something to remove the buffer from

Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/RetainableByteBuffer.java]: I will remove the API for 12.0 and e unwrapping.   We can review in 12.1

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpOutput.java [hunk 6]
```diff
@@ -576,25 +577,32 @@ public ByteBuffer getByteBuffer()
...
-            _aggregate = pool.acquire(getBufferSize(), useOutputDirectByteBuffers);
+        {
+            _pool = _servletChannel.getRequest().getComponents().getByteBufferPool();
+            _aggregate = _pool.acquire(getBufferSize(), useOutputDirectByteBuffers);
+        }
         return _aggregate;
     }
 
-    private void releaseBuffer()
+    private void lockedReleaseBuffer(boolean failure)
```
Comment (lorban) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpOutput.java:598]: If you prefix this method's name with `locked` because a lock needs to be held before it is called, you should add as its 1st line an assertion that checks the lock is held.

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpOutput.java [hunk 7]
```diff
@@ -642,23 +644,30 @@ public ByteBuffer getByteBuffer()
...
-            _aggregate = _channel.getByteBufferPool().acquire(getBufferSize(), _channel.isUseOutputDirectByteBuffers());
+        {
+            _pool = _channel.getByteBufferPool();
+            _aggregate = _pool.acquire(getBufferSize(), _channel.isUseOutputDirectByteBuffers());
+        }
         return _aggregate;
     }
 
-    private void releaseBuffer()
+    private void lockedReleaseBuffer(boolean failure)
```
Comment (lorban) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/HttpOutput.java:663]: Ditto

**Review by lorban — DISMISSED** [review]
Two nits, otherwise LGTM

**Comment by joakime** [comment]
I added the assert on `_channelState.isLockHeldByCurrentThread()`.
If I get a green build, I'll merge this and stage the release.

**Comment by joakime** [comment]
From https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-11951/13/pipeline

```
[ERROR] Errors: 
[ERROR]   ServerConnectorHttpServerTest>HttpServerTestBase.testShutdown:1763 » NullPointer 
   Cannot invoke "org.eclipse.jetty.http.HttpTester$Response.getStatus()" because "response" is null
```

Not going to merge this one myself.

**Comment by gregw** [comment]
@joakime  OK looking... stand by ...

**Comment by gregw** [comment]
@joakime I'm 99% sure that was a flake. rebuilding to check and then will merge.
