### PR TITLE
Jetty 9.4.x 4855 h2spec failures

### LINKED ISSUE #4855: occasional h2spec failures on jenkins
**Jetty version**
jetty-10.0.x

**Java version**
14.0.1, vendor: AdoptOpenJDK

**OS type/version**
"linux", version: "4.15.0-99-generic", arch: "amd64", family: "unix"

**Description**

Occasional h2spec failures on jenkins, I've seen this a few times now but it usually disappears if you re-run the build.

https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/jetty-9.4.x-4789-ShutdownThread/1/pipeline
```
Hypertext Transfer Protocol Version 2 (HTTP/2)
  5. Streams and Multiplexing
    5.1. Stream States
      × 11: closed: Sends a DATA frame
        -> The endpoint MUST treat this as a connection error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     RST_STREAM Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: Timeout

Finished in 2.3936 seconds
145 tests, 144 passed, 0 skipped, 1 failed
```

### PR DESCRIPTION
**Pull request by sbordet**
The bulk of the fix is in 8d60636.

### CODE REVIEW

**Comment by sbordet** [comment]
@gregw @lorban see https://github.com/eclipse/jetty.project/issues/4855#issuecomment-639673169 for a description of the problem and the solution.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2ServerConnection.java [hunk 1]
```diff
@@ -245,22 +246,10 @@ public boolean onSessionTimeout(Throwable failure)
...
-        else
-        {
-            CountingCallback counter = new CountingCallback(callback, streams.size());
-            for (Stream stream : streams)
-            {
-                onStreamFailure((IStream)stream, failure, counter);
-            }
-        }
+            LOG.debug("Processing session failure on {}", getSession(), failure);
+        // All the streams have already been failed, just succeed the callback.
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2ServerConnection.java:251]: Is this method still required?  It doesn't override any contract?

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 2]
```diff
@@ -352,117 +353,259 @@ public void abort(Throwable failure)
...
-                    this.commit = commit;
-                    return true;
+                    case PRE_SEND:
+                    {
+                        _state = State.POST_SEND;
+                        return;
+                    }
+                    case SUCCEED:
+                    {
+                        callback = _callback;
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:453]: Some comments on how we could get to these states between preSend and postSend would be good.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 3]
```diff
@@ -352,117 +353,259 @@ public void abort(Throwable failure)
...
+                        commit = _commit;
+                        failure = null;
+                        reset();
+                        break;
+                    }
+                    case FAIL:
+                    {
+                        _state = State.FAILED;
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: Why does `SUCCEED` just remember stuff while this one moves the state on? Comments needed

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 4]
```diff
@@ -352,117 +353,259 @@ public void abort(Throwable failure)
...
+                        callback = _callback;
+                        commit = _commit;
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:464]: should _commit be nulled so we know we can only call it once?

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 5]
```diff
@@ -352,117 +353,259 @@ public void abort(Throwable failure)
...
+                    }
                 }
             }
             if (failure == null)
-                failure = new IllegalStateException("Invalid transport state: " + state);
-            callback.failed(failure);
-            return false;
+                succeed(callback, commit);
+            else
+                fail(callback, commit, failure);
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:482]: what if callback is null?  I think it is an ISE, so that should be explicitly thrown

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 6]
```diff
@@ -352,117 +353,259 @@ public void abort(Throwable failure)
...
-                    this.callback = null;
-                    this.commit = false;
+                    case PRE_SEND:
+                    {
+                        _state = State.SUCCEED;
+                        // Succeeding the callback will be done in postSend().
+                        return;
+                    }
+                    case POST_SEND:
+                    {
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:501]: comment

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 7]
```diff
@@ -352,117 +353,259 @@ public void abort(Throwable failure)
...
+                        callback = _callback;
+                        commit = _commit;
+                        reset();
+                        break;
+                    }
+                    default:
+                    {
+                        // The race to succeed was lost and other states
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: the race with whom?

**Review by gregw — CHANGES_REQUESTED** [review]
I can see what it is doing, but it is hard to thoroughly review without more comments explaining each state transition and the races being faced.  So can I get some more comments and then I'll review again

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 8]
```diff
@@ -352,117 +353,259 @@ public void abort(Throwable failure)
...
         {
-            State state;
+            assert Thread.holdsLock(this);
+            _state = State.IDLE;
+            _callback = null;
+            _commit = false;
+            _failure = null;
+        }
+
+        private void send(Callback callback, boolean commit, Consumer<Callback> consumer)
```
Comment (lorban) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: Since all lambdas passed to this method are always capturing, I see no point in passing it the `Callback`. I think changing the signature here to accept a `Runnable` instead of a `Consumer` would be slightly more readable.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 9]
```diff
@@ -352,117 +353,259 @@ public void abort(Throwable failure)
...
+                    failure);
+            if (timeout)
+                callback.failed(failure);
         }
     }
 
     private enum State
     {
-        IDLE, WRITING, FAILED, TIMEOUT
+        IDLE, PRE_SEND, POST_SEND, SUCCEED, FAIL, FAILED
```
Comment (lorban) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: These states and their transitions should be javadoc'ed as it's not easy to grok what the FSM looks like by reading the code.

File: jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/api/Stream.java [hunk 10]
```diff
@@ -227,8 +227,24 @@ default boolean onIdleTimeout(Stream stream, Throwable x)
          * @param stream the stream
          * @param error the error code
          * @param reason the error reason, or null
+         * @param failure the failure
          * @param callback the callback to complete when the failure has been handled
          */
+        default void onFailure(Stream stream, int error, String reason, Throwable failure, Callback callback)
```
Comment (lorban) [inline jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/api/Stream.java:233]: I find this new method's signature and default implementation surprising. I would have expected that the `error` and `reason` parameters to go away especially since the overriding implementations just ignore them. Plus the fact that the default implementation drops the `failure` in favor of calling the deprecated implementation instead of directly succeeding the callback also makes me scratch my head. 

Maybe `FailureFrame.getFailure()` should return some sort of `H2Exception` that wraps the original exception as well as containing the reason and error code?

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 8 above)
Comment (gregw) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: I agree.  At the very least the param name needs to be changed to `sendFrame`.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 11]
```diff
@@ -350,119 +351,356 @@ public void abort(Throwable failure)
...
+         * <ul>
+         *   <li>{@link #SUCCEED}, when {@link TransportCallback#succeeded()}
+         *   is called synchronously because the send succeeded</li>
+         *   <li>{@link #FAIL}, when {@link TransportCallback#failed(Throwable)}
+         *   is called synchronously because the send failed</li>
+         *   <li>{@link #POST_SEND}, when {@link TransportCallback#postSend()}
+         *   is called before the send completes</li>
+         * </ul>
+         */
+        PRE_SEND,
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: I don't like the `PRE_SEND`,  `POST_SEND` and `SUCCEED`names as they are confusing in that during `PRE_SEND` sending is happening and in `POST_SEND` the send is pending.  

How about: `IDLE` -> `SENDING` -> `PENDING` -> `SUCCEEDED` -> `FAILED`

I think `ING` and `ED` names line up better with our practises elsewhere.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 12]
```diff
@@ -350,119 +351,356 @@ public void abort(Throwable failure)
...
+                consumer.accept(this);
+                postSend();
+            }
+            else
+            {
+                callback.failed(failure);
+            }
+        }
+
+        private Throwable preSend(Callback callback, boolean commit)
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: rename method to `onSending`

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 13]
```diff
@@ -350,119 +351,356 @@ public void abort(Throwable failure)
...
+                        _commit = commit;
+                        return null;
+                    }
+                    default:
+                    {
+                        Throwable failure = _failure;
+                        if (failure == null)
+                            failure = new IllegalStateException("Invalid transport state: " + _state);
+                        return failure;
+                    }
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: This is not one case but two. Also needs comments:

```suggestion
                    case FAIL:
                        // better comment that an async failure happened while we were just about to send something
                        return _failure;
                    default:
                        return new IllegalStateException("Invalid transport state: " + _state);
```

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 14]
```diff
@@ -350,119 +351,356 @@ public void abort(Throwable failure)
...
+                }
+            }
+        }
+
+        private void postSend()
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: rename to `onSent`

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 15]
```diff
@@ -350,119 +351,356 @@ public void abort(Throwable failure)
...
-                if (state == State.IDLE)
+                switch (_state)
                 {
-                    this.state = State.WRITING;
-                    this.callback = callback;
-                    this.commit = commit;
-                    return true;
+                    case PRE_SEND:
+                    {
+                        _state = State.POST_SEND;
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]:
```suggestion
                        // The send has not yet completed, wait for success or failure
                        _state = State.PENDING;
```

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 16]
```diff
@@ -350,119 +351,356 @@ public void abort(Throwable failure)
...
+                        return;
+                    }
+                    case SUCCEED:
+                    {
+                        callback = _callback;
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:453]:
```suggestion
                        // The send has already completed successfully but callback not yet called, we can process callback now
                        callback = _callback;
                        _callback = null;
```

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 17]
```diff
@@ -350,119 +351,356 @@ public void abort(Throwable failure)
...
+                        reset();
+                        break;
+                    }
+                    case FAIL:
+                    {
+                        _state = State.FAILED;
+                        callback = _callback;
+                        commit = _commit;
+                        failure = _failure;
+                        break;
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]:
```suggestion
                    case FAIL:
                    {
                        // The send has already failed (either synchronously or asynchronously), but callback not yet called, so handle now
                        _state = State.FAILED;
                        callback = _callback;
                        _callback = null;
                        commit = _commit;
                        failure = _failure;
                        break;
```

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 18]
```diff
@@ -350,119 +351,356 @@ public void abort(Throwable failure)
...
+                    }
                 }
             }
             if (failure == null)
-                failure = new IllegalStateException("Invalid transport state: " + state);
-            callback.failed(failure);
-            return false;
+                succeed(callback, commit);
+            else
+                fail(callback, commit, failure);
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:482]:
```suggestion
                succeed(callback, commit);
            else if (callback != null )
                fail(callback, commit, failure);
            else
                threw new IllegalStateException();
```

**Review by gregw — CHANGES_REQUESTED** [review]
Big block comments are good, but names are bad and more inline comments needed

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 8 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: I like the `Consumer<Callback>` for 2 reasons:
* it allows `TransportCallback.send()` to give to the `Consumer` some other callback if needs to without having the `sendXXXFrame()` methods be aware of what callback to use
* it keeps the semantic of the `sendXXXFrame()` clear: they take a callback parameter, and therefore they are asynchronous

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 9 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: Done.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 8 above)
Comment (gregw) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: @sbordet if you keep the `Consumer` it has to have a better name than `consumer`.   I think `sendFrame` is best as it indicates what the Consumer is meant to do.

File: jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/api/Stream.java (hunk 10 above)
Comment (sbordet) [reply jetty-http2/http2-common/src/main/java/org/eclipse/jetty/http2/api/Stream.java:233]: This is at the HTTP/2 low-level API so our implementation may not use `error` and `reason` but users of these APIs may.
However, there are cases where we still have a failure but not an associated `error` (e.g. idle timeout and aborts).

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 11 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: They are not correct.

SUCCEED and FAIL are commands, it's what `postSend()` should do, either succeed by calling `succeeded()` or fail by calling `failed(Throwable)`.

I'm ok with PRE_SEND -> SENDING and POST_SEND -> PENDING, but I need 2 more states for SUCCEED and FAIL _as commands_ about what to do next. 

FAILED is a terminal state (so it cannot be used for the command), but we don't have a SUCCEEDED terminal state (we go back to IDLE).

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 13 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: FAIL here is an illegal state.
FAILED here is legal and I can return `failure` like you propose.
However, is that what you meant?

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 18 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:482]: Nope, callback cannot be `null` - if it is then we would have a bad state and we handle it already in the `default` case.
Plus I don't want to throw from this class but fail the callback instead.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 12 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: Perhaps, after we agree on state names.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 14 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java]: Perhaps, after we agree on state names.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 16 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:453]: This is wrong, here `succeeded()` has already been called.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 19]
```diff
@@ -350,119 +351,363 @@ public void abort(Throwable failure)
...
+                        // The send has not completed the callback yet,
+                        // wait for succeeded() or failed() to be called.
+                        _state = State.PENDING;
+                        return;
+                    }
+                    case SUCCEEDING:
+                    {
+                        // The send already completed successfully, but the
+                        // call to succeeded() was delayed, so call it now.
+                        callback = _callback;
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:453]: I think we should null `_callback` whenever we take it.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 20]
```diff
@@ -350,119 +351,363 @@ public void abort(Throwable failure)
...
+        private boolean _commit;
+        private Throwable _failure;
 
-        public boolean start(Callback callback, boolean commit)
+        private void reset()
         {
-            State state;
+            assert Thread.holdsLock(this);
+            _state = State.IDLE;
+            _callback = null;
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:389]: if we null `_callback` when we take it, we can throw ISE here if it is not null

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 21]
```diff
@@ -350,119 +351,363 @@ public void abort(Throwable failure)
...
+                        _failure = failure;
+                        callback = _callback;
+                        timeout = true;
+                        break;
+                    }
+                    case IDLE:
+                        // The application may be suspended, ignore the idle timeout.
+                    case SENDING:
+                        // A send has been started at the same time of an idle timeout;
+                        // Ignore the idle timeout and let the write continue normally.
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:573]: I kind of think the timeout should win this race.  Who knows what else has been closed already by the timeout, plus the timeout might be due to a really slow generation of the frame.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 22]
```diff
@@ -350,119 +351,363 @@ public void abort(Throwable failure)
...
+                        callback = _callback;
+                        if (callback == null)
+                            callback = Callback.NOOP;
+                        timeout = true;
+                        failure = _failure;
+                        break;
+                    }
                 }
             }
+            idleTimeout(callback, timeout, failure);
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:597]: just inline the idleTimeout method here.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java [hunk 23]
```diff
@@ -350,119 +351,363 @@ public void abort(Throwable failure)
...
+            return timeout;
+        }
+
+        private void succeed(Callback callback, boolean commit)
```
Comment (gregw) [inline jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:601]: perhaps `onCompleteSuccess`  to tie in with common behaviour of `IteratingCallback`?

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java [hunk 24]
```diff
@@ -819,11 +819,16 @@ protected void onError(Throwable th)
...
             // If we are still async and nobody has called sendError
             if (_requestState == RequestState.ASYNC && !_sendError)
+            {
                 // Then the listeners did not invoke API methods
                 // and the container must provide a default error dispatch.
                 sendError(th);
-            else
+            }
+            // Otherwise the listeners have called AsyncContext.complete().
+            else if (_requestState != RequestState.COMPLETE)
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java:826]: Is this an unrelated fix?

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java [hunk 25]
```diff
@@ -819,11 +819,16 @@ protected void onError(Throwable th)
         {
             // If we are still async and nobody has called sendError
             if (_requestState == RequestState.ASYNC && !_sendError)
+            {
                 // Then the listeners did not invoke API methods
                 // and the container must provide a default error dispatch.
                 sendError(th);
-            else
+            }
+            // Otherwise the listeners have called AsyncContext.complete().
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java]: this comment comment is outside the if, so should be phrased as a conditional, or moved inside the if body

**Review by gregw — CHANGES_REQUESTED** [review]
still a few things...

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 19 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:453]: It is in `reset()` few lines below.

**Review by lorban — APPROVED** [review]
LGTM once the naming has been sorted out.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 20 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:389]: Don't want to throw from this class, it will just hang the server.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 21 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:573]: Nope, we should support ignoring idle timeouts in case the application is idle as per Servlet specification, so if we were just unlucky here we should ignore the idle timeout.
I think we should enforce the idle timeout only when we are PENDING, i.e. really sure that we have initiated a write but it won't complete in time.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 22 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:597]: Nah, it nicely complements the succeed() and fail() methods, with logging callback action.

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 23 above)
Comment (sbordet) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:601]: Not a big fan, as we are not iterating here.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java (hunk 24 above)
Comment (sbordet) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java:826]: Correct, it has been introduced in a separate commit, 9dec284cc2afeeb49d3f4fce4a0656d8d98c6d48.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java (hunk 25 above)
Comment (sbordet) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelState.java]: I'm not a big fan of comments outside `if/else` that just say what the `if/else` is doing.
I'm for removing both.

**Comment by gregw** [comment]
@sbordet CI failed

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2ServerConnection.java (hunk 1 above)
Comment (gregw) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HTTP2ServerConnection.java:251]: @sbordet ?

File: jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java (hunk 20 above)
Comment (gregw) [reply jetty-http2/http2-server/src/main/java/org/eclipse/jetty/http2/server/HttpTransportOverHTTP2.java:389]: If we get here with a non null callback, then the server is as good as dead anyway.  At least the exception will tell us why!

**Review by gregw — APPROVED** [review]
