### PR TITLE
Remove special cookie attributes with null value

### LINKED ISSUE #13539: HttpCookie.Builder does not allow removing SameSite
**Jetty version(s)**
12.1.0

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.15" 2025-04-15
OpenJDK Runtime Environment Temurin-17.0.15+6 (build 17.0.15+6)
OpenJDK 64-Bit Server VM Temurin-17.0.15+6 (build 17.0.15+6, mixed mode, sharing)

**OS type/version**
Microsoft Windows [Version 10.0.26100.4946]

**Description**
`HttpCookie.Builder` allows setting several attributes, including customized methods for well-known attributes. It also allows removing all of these attributes except for one: `SameSite`. Where values for attributes like `Expires` contain `null` checks (see https://github.com/jetty/jetty.project/blob/c8372b65bd15404de1444d68902c0455a3a69b64/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java#L632), such a check is missing for `SameSite` (see https://github.com/jetty/jetty.project/blob/c8372b65bd15404de1444d68902c0455a3a69b64/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java#L656). As a result, trying to clear the `SameSite` attribute this way results in a `NullPointerException`.

The alternative using `.attribute("SameSite", null)` will also fail due to the `null` check at https://github.com/jetty/jetty.project/blob/c8372b65bd15404de1444d68902c0455a3a69b64/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java#L574. As a result, once it has been set the `SameSite` attribute can never be removed again.

**How to reproduce?**
```java
HttpCookie.build("name", "value")
        .expires(Instant.now()) // succeeds
        .expires(null) // succeeds
        .sameSite(SameSite.STRICT) // succeeds
        .sameSite(null); // fails with a NullPointerException

HttpCookie.build("name", "value")
        .sameSite(SameSite.STRICT) // succeeds
        .attribute(HttpCookie.SAME_SITE_ATTRIBUTE, null) // fails with an IllegalArgumentException
```

### PR DESCRIPTION
**Pull request by gregw**
Fix #13539 by allowing null to be used to remove cookie special attributes.

### CODE REVIEW

**Review by sbordet — CHANGES_REQUESTED** [review]
@gregw I don't mind the changes, but there are a few cookie test failures.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java [hunk 1]
```diff
@@ -560,33 +560,12 @@ public Builder attribute(String name, String value)
...
-                    secure(true);
-                }
-                case "partitioned" ->
-                {
-                    if (!isTruthy(value))
-                        throw new IllegalArgumentException("Invalid Partitioned attribute");
-                    partitioned(true);
-                }
+                case "expires" -> expires(StringUtil.isBlank(value) ? null : parseExpires(value));
+                case "httponly" -> httpOnly(isTruthy(value));
```
Comment (janbartel) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java]: Not sure I get this - isn't "false" an acceptable value for the `httponly` cookie field? The javadoc for `jakarta.servlet.http.Cookie` thinks it is.

**Review by janbartel — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java]: It is.  Look at the implementation of `isTruthy`.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java [hunk 2]
```diff
@@ -560,41 +563,26 @@ public Builder attribute(String name, String value)
...
         private boolean isTruthy(String value)
         {
-            return value != null && (value.isEmpty() || "true".equalsIgnoreCase(value));
+            if (value == null)
+                return false;
+            if (value.isEmpty() || "true".equalsIgnoreCase(value))
+                return true;
+            if ("false".equalsIgnoreCase(value))
+                return false;
+            throw new IllegalArgumentException("Invalid value");
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java]: I preferred like it was before, because before it would return more precise information about what attribute was wrong ("Invalid SameSite attribute" but now it is just "Invalid value"), and now `isTruthy()` is not just about truth, but also falseness, so should have been renamed to `isTruthyOrFalsy()`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpCookie.java]: But it is confusing to call `isTruthy("false")` and get back `true`, see other comment.

**Review by janbartel — APPROVED** [review]

**Comment by gregw** [comment]
@sbordet nudge

**Review by sbordet — APPROVED** [review]
