### PR TITLE
Fix NPE in HttpChannelState

### LINKED ISSUE #10382: NPE thrown during HttpClient tests
**Jetty version(s)**
12

**Jetty Environment**
core

**Description**
Unsuppressed NPE during successful build https://jenkins.webtide.net/blue/rest/organizations/jenkins/pipelines/jetty.project/branches/jetty-12.0.x/runs/1451

```java
Running HttpClientTimeoutTest.testVeryShortTimeout() [3] H2C
2023-08-22 21:30:39.639:INFO :oejs.Server:ForkJoinPool-1-worker-3: jetty-12.0.1-SNAPSHOT; built: 2023-08-22T21:15:43.448Z; git: a51c67dbb4d6f78dc8dc7cbca6997b19308dec65; jvm 21-ea+32-2482
2023-08-22 21:30:39.640:INFO :oejus.SslContextFactory:ForkJoinPool-1-worker-3: x509=X509@511c3803(mykey,h=[localhost],a=[/127.0.0.1, /0:0:0:0:0:0:0:1],w=[]) for Server@304159f4[provider=null,keyStore=null,trustStore=null]
2023-08-22 21:30:39.640:INFO :oejs.Server:ForkJoinPool-1-worker-1: jetty-12.0.1-SNAPSHOT; built: 2023-08-22T21:15:43.448Z; git: a51c67dbb4d6f78dc8dc7cbca6997b19308dec65; jvm 21-ea+32-2482
2023-08-22 21:30:39.641:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-1: Started ServerConnector@2e04103f{h2c, (h2c)}{0.0.0.0:45935}
2023-08-22 21:30:39.641:INFO :oejs.Server:ForkJoinPool-1-worker-1: Started oejs.Server@691fd46{STARTING}[12.0.1-SNAPSHOT,sto=0] @83181ms
2023-08-22 21:30:39.652:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-3: Started ServerConnector@236201e4{SSL, (ssl, alpn, h2)}{0.0.0.0:41859}
2023-08-22 21:30:39.653:INFO :oejs.Server:ForkJoinPool-1-worker-3: Started oejs.Server@18072f49{STARTING}[12.0.1-SNAPSHOT,sto=0] @83192ms
2023-08-22 21:30:39.656:INFO :oejus.SslContextFactory:ForkJoinPool-1-worker-1: x509=X509@3f99a3ee(mykey,h=[localhost],a=[/127.0.0.1, /0:0:0:0:0:0:0:1],w=[]) for Client@4880f0b7[provider=null,keyStore=null,trustStore=null]
2023-08-22 21:30:39.668:INFO :oejus.SslContextFactory:ForkJoinPool-1-worker-3: x509=X509@2cf5fcfe(mykey,h=[localhost],a=[/127.0.0.1, /0:0:0:0:0:0:0:1],w=[]) for Client@207d2b4b[provider=null,keyStore=null,trustStore=null]
2023-08-22 21:30:39.669:WARN :oejusS.config:ForkJoinPool-1-worker-1: No Client EndPointIdentificationAlgorithm configured for Client@4880f0b7[provider=null,keyStore=null,trustStore=null]
2023-08-22 21:30:39.671:WARN :oejut.SerializedInvoker:server-7942: Serialized invocation error
java.lang.NullPointerException: Cannot read field "_stream" because "httpChannelState" is null
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.failed(HttpChannelState.java:1542)
	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onFailure$2(HttpChannelState.java:484)
	at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
	at org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2.lambda$onFailure$2(HttpStreamOverHTTP2.java:592)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:158)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:449)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**How to reproduce?**
See CI build: https://jenkins.webtide.net/blue/rest/organizations/jenkins/pipelines/jetty.project/branches/jetty-12.0.x/runs/1451/nodes/7/steps/44/log/?start=0

### LINKED ISSUE #10539: NPE in HTTP2 StreamResetTest.testClientResetConsumesQueuedData
**Jetty version(s)**
12

**Jetty Environment**
all

**Java version/vendor** `(use: java -version)`

**OS type/version**

**Description*

Whilst building a javadoc only change: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-10527/5/pipeline/

```
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 15.19 s -- in org.eclipse.jetty.http2.tests.MaxConcurrentStreamsTest
2023-09-17 19:40:53.633:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@5a705a25{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:40:53.633:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@4173b1bb{h2c, (h2c)}{0.0.0.0:0}
2023-09-17 19:40:53.636:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:40:53.638:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@1fbf0f15{h2, (h2)}{0.0.0.0:38411}
2023-09-17 19:40:53.638:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@6d7bd9fc{STARTING}[12.0.2-SNAPSHOT,sto=0] @86209ms
2023-09-17 19:40:54.646:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@6d7bd9fc{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:40:54.646:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@1fbf0f15{h2, (h2)}{0.0.0.0:0}
2023-09-17 19:40:54.650:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:40:54.653:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@480bfcd6{h2, (h2)}{0.0.0.0:42721}
2023-09-17 19:40:54.653:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@5e2969e3{STARTING}[12.0.2-SNAPSHOT,sto=0] @87224ms
2023-09-17 19:40:57.160:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@5e2969e3{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:40:57.160:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@480bfcd6{h2, (h2)}{0.0.0.0:0}
2023-09-17 19:40:57.163:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:40:57.164:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@72bf65a8{h2, (h2)}{0.0.0.0:35889}
2023-09-17 19:40:57.164:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@182b5240{STARTING}[12.0.2-SNAPSHOT,sto=0] @89735ms
2023-09-17 19:40:59.171:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@182b5240{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:40:59.171:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@72bf65a8{h2, (h2)}{0.0.0.0:0}
2023-09-17 19:40:59.175:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:40:59.177:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@178e10f5{h2, (h2)}{0.0.0.0:45199}
2023-09-17 19:40:59.177:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@24c55980{STARTING}[12.0.2-SNAPSHOT,sto=0] @91748ms
2023-09-17 19:41:01.184:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@24c55980{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:41:01.185:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@178e10f5{h2, (h2)}{0.0.0.0:0}
2023-09-17 19:41:01.189:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:41:01.190:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@28ab56e5{h2, (h2)}{0.0.0.0:43899}
2023-09-17 19:41:01.190:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@3d92874{STARTING}[12.0.2-SNAPSHOT,sto=0] @93761ms
2023-09-17 19:41:02.198:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@3d92874{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:41:02.199:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@28ab56e5{h2, (h2)}{0.0.0.0:0}
2023-09-17 19:41:02.203:INFO :oejs.Server:ForkJoinPool-1-worker-4: jetty-12.0.2-SNAPSHOT; built: 2023-09-17T19:24:59.154Z; git: ad08b01f2e1a48a4dd46fc2826f5d9c3569edc9a; jvm 17.0.8+7
2023-09-17 19:41:02.205:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Started ServerConnector@383f097b{h2, (h2)}{0.0.0.0:42439}
2023-09-17 19:41:02.205:INFO :oejs.Server:ForkJoinPool-1-worker-4: Started oejs.Server@2e512670{STARTING}[12.0.2-SNAPSHOT,sto=0] @94776ms
processing request /1
processing request /2
2023-09-17 19:41:03.713:WARN :oejuts.AdaptiveExecutionStrategy:server-4008: Task run failed
java.lang.NullPointerException: Cannot read field "_callback" because "this._request" is null
	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onIdleTimeout$1(HttpChannelState.java:402)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:158)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:449)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-09-17 19:41:03.713:WARN :oejuts.AdaptiveExecutionStrategy:server-4005: Task run failed
java.lang.NullPointerException: Cannot read field "_callback" because "this._request" is null
	at org.eclipse.jetty.server.internal.HttpChannelState.lambda$onIdleTimeout$1(HttpChannelState.java:402)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:158)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:449)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-09-17 19:41:03.947:INFO :oejs.Server:ForkJoinPool-1-worker-4: Stopped oejs.Server@2e512670{STOPPING}[12.0.2-SNAPSHOT,sto=0]
2023-09-17 19:41:03.947:INFO :oejs.AbstractConnector:ForkJoinPool-1-worker-4: Stopped ServerConnector@383f097b{h2, (h2)}{0.0.0.0:0}
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 27.93 s -- in org.eclipse.jetty.http2.tests.IdleTimeoutTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   StreamResetTest.testClientResetConsumesQueuedData:443 expected: <0> but was: <32768>
```

### PR DESCRIPTION
**Pull request by lorban**
The `ChannelCallback.failed()` callback can race with successful completion when a timeout occurs.

Fixes #10382 and #10539

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 1]
```diff
@@ -1537,6 +1539,9 @@ public void failed(Throwable failure)
             try (AutoLock ignored = _request._lock.lock())
             {
                 httpChannelState = _request._httpChannelState;
+                if (httpChannelState == null)
```
Comment (lachlan-roberts) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I think you could just call this and it will do the null check.
```java
httpChannelState = _request.lockedGetHttpChannelState();
```

**Review by lachlan-roberts — COMMENTED** [review]
So the callback is being failed after `HttpChannelState.recycle()` has been called and that's what was triggering the NPE.

Are we sure that this cannot happen when the `HttpChannel` is being re-used after the recycle?

**Comment by gregw** [comment]
@sbordet note that issues like this are convincing me that we should not fail the callback on an idle timeout.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: `_request.lockedGetHttpChannelState()` throws if the httpChannelState is null. We don't want to do that in a callback's `failed()` method.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: @lorban are you sure?   If we want multiple calls to a callback to be a noop, then the throw in _request.lockedGetHttpChannelState() is wrong.     Since that is a throw, doesn't it indicate that we are throwing elsewhere?

We should decide one way or another and javadoc in the Callback class if we should throw or noop.

Comment (gregw) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: Note that I'm OK with noop... (but would have preferred a boolean return), but just saying that the current code suggests we might throw

Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java]: I think @lachlan-roberts meant `lockedCompleteCallback()` instead of `_request.lockedGetHttpChannelState()` as this one does the null check and is already called a few lines afterward. Moving the call before the `_request._httpChannelState` deref should be all that's needed.

**Review by sbordet — APPROVED** [review]

**Review by gregw — APPROVED** [review]
