### PR TITLE
Jetty 10.0.x: avoid buffer use after repooling

### LINKED ISSUE #12776: ByteBufferPool - all ongoing requests fail when single request is cancelled on HTTP/2
**Jetty version(s)**

12.0.16 (11.0.x version since 11.0.21) 12.1.x

**Jetty Environment**

Embedded + EE9

**Java version/vendor (use: java -version)**
```
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)
```

**OS type/version**

Ubuntu 24, Arch Linux, Manjaro...

**Description**

When web browsers plays video / audio and sending requests with header Range and request got cancelled (for example because user is seeking in video),
all other currently processed requests gets cancelled (there is HTTP2_ERROR in Chrome or Firefox network console).

Issue occurs only when HTTP/2 is used.  It works on Jetty 11.0.20, but fails on Jetty 11.0.21, 11.0.22, 11.0.23, 11.0.24 and 12.0.16.

When we disable HTTP/2 or revert this [commit](https://github.com/jetty/jetty.project/commit/57266039d8da2bd04b33b6a3e387744ab067ed80) on Jetty 11.0.24 it never fails.

This issue also never occured when tested on localhost or LAN (probably due to transfer speed).

**How to reproduce?**

[jetty-issue.zip](https://github.com/user-attachments/files/18690326/jetty-issue.zip)

Run attached code with JDK 21 using:
```bash
mvn compile exec:java
```

It starts Jetty 12.0.16 on port 9443 with HTTP/2 connections, downloads sample [video](https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4)
and starts to serve contents of `web` folder and provides endpoint `/video` for serving video data and `/sse` as Server Sent Events source.

When you open web browser https://IP:9443 it estabilish Server Send Event connections and starts to play video.

Try to seek in the video before it gets fully buffered to web browser. You can see that SSE connection will fail (alert will be shown).

NOTE: We were never able to reproduce this when using localhost or LAN address. Only way to reproduce this is to forward port to public IP address and access to address "in internet" (we have tried multiple ISP to be sure that this issue is not caused by some firewalls or network devices).
Our only thought why it happens only when access from internet is effect of transfer speed and thus different buffer usage.

Image

  
  In TCP dump you can see HTTP2 GOAWAY was sent.
  
  Reverting back to Jetty 11.0.20 helps. We also tried to revert commit [commit](https://github.com/jetty/jetty.project/commit/57266039d8da2bd04b33b6a3e387744ab067ed80) on  Jetty 11.0.24 and it also works.
  
  On Jetty 12 our only solution to fix this is to set `ByteBufferPool.NON_POOLING` in constructor of Jetty `Server` instance.

### PR DESCRIPTION
**Pull request by lorban**
Fixes the Jetty 11 problem reported at #12776: the change made in #11527 is safe for H1 but not for H2.

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java [hunk 1]
```diff
@@ -648,12 +648,15 @@ private ByteBuffer acquireBuffer()
...
+    private void releaseBuffer(Throwable failure)
     {
         if (_aggregate != null)
         {
             ByteBufferPool bufferPool = _channel.getConnector().getByteBufferPool();
-            bufferPool.release(_aggregate);
+            if (failure == null)
+                bufferPool.release(_aggregate);
+            else
+                bufferPool.remove(_aggregate);
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java]: Can we make this behaviour conditional on version >= 2.0 ? Otherwise we open a simple h1 DOS vector that will allow the buffer pool to be cycled too easily.

The real fix is #12727

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java (hunk 1 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java]: We can't backport https://github.com/jetty/jetty.project/pull/12727 to 10.0.x/11.0.x without a huge effort and these releases are EOL, so adding a simple extra if (httpVersion < 2) then always release looks reasonable.

Let me add that.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java [hunk 2]
```diff
@@ -648,12 +649,16 @@ private ByteBuffer acquireBuffer()
         return _aggregate;
     }
 
-    private void releaseBuffer()
+    private void releaseBuffer(Throwable failure)
     {
         if (_aggregate != null)
         {
+            boolean asyncCancelPossible = _channel.getRequest().getMetaData().getHttpVersion().getVersion() >= HttpVersion.HTTP_2.getVersion();
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java]: minor niggle.... probably resolved by JIT.... we only need to follow those 4 de-references to check the version if there is a failure.

**Review by gregw — DISMISSED** [review]
I'm approving with a minor niggle... probably fixed by the JIT... but it might also read better if you re-ordered the code.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java (hunk 2 above)
Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpOutput.java]: Ok, I've inlined the HTTP version check to the right side of the `||`.

**Review by gregw — APPROVED** [review]
