### PR TITLE
Issue #4572 - Introduce jetty-slf4j-impl (part 1 of 3)

### LINKED ISSUE #4572: Replace Jetty Logging
# Proposal

## Drop org.eclipse.jetty.util.log

The entire package `org.eclipse.jetty.util.log` is deleted

## Create jetty-slf4j-impl module

A new module called `jetty-slf4j-impl` is created.

This module performs the equivalent to Jetty's StdErrLog.

* Same output formatting as `StdErrLog` in 9.x
* Supports `jetty-logging.properties` for configuring logging levels

It has a `META-INF/services/org.slf4j.spi.SLF4JServiceProvider`

A package space of org.eclipse.jetty.logging
A JPMS of jetty-logging ?

This new module would be included as a `<scope>test</scope>`
across the other Jetty modules that need it for testing.

## Migrate logging properties

Existing properties

* `org.eclipse.jetty.util.log.class` (classname, default "org.eclipse.jetty.util.log.Slf4jLog") - use to select the logger
* `org.eclipse.jetty.util.log.announce` (boolean, default "true") - used to control announcement text `"Logging to {} via {}"`
* `org.eclipse.jetty.util.log.IGNORED` (boolean, default "false") - used to control if Log.ignored() should be shown or not
* `org.eclipse.jetty.util.log.StdErrLog.TAG_PAD` (number, default "0") - used for minimum padding width of the Thread.name
* `org.eclipse.jetty.util.log.SOURCE` (boolean, default "false") - used as default for showing of source (filename and line number) in stacktraces
* `org.eclipse.jetty.util.log.stderr.SOURCE` (boolean, default "false") - used for showing of source (filename and line number) in stacktraces
* `org.eclipse.jetty.util.log.stderr.LONG` (boolean, default "false") - used for condensing the logger name package
* `org.eclipse.jetty.util.log.stderr.ESCAPE` (boolean, default "true") - used for escaping the output of the logger message.

Dropped properties

* `org.eclipse.jetty.util.log.class` - controlled by slf4j-api now
* `org.eclipse.jetty.util.log.announce` - controlled by slf4j-api now
* `org.eclipse.jetty.util.log.SOURCE` - we only have 1 logger now.

Renamed properties

* `org.eclipse.jetty.logging.IGNORED` (boolean, default "true") - used to control if Log.ignored() should be shown or not
* `org.eclipse.jetty.logging.THREAD_PADDING` (number, default "0") - used for minimum padding width of the Thread.name
* `org.eclipse.jetty.logging.SOURCE` (boolean, default "false") - used for showing of source (filename and line number) in stacktraces
* `org.eclipse.jetty.logging.NAME_CONDENSE` (boolean, default "true") - used for condensing the logger name package
* `org.eclipse.jetty.logging.MESSAGE_ESCAPE` (boolean, default "true") - used for escaping the output of the logger message

## Migrate source to use slf4j

Migrate code from ...

``` java
import org.eclipse.jetty.util.log.Log;
import org.eclipse.jetty.util.log.Logger;

private static final Logger LOG = Log.getLogger(DoSFilter.class);
```

... to ...

``` java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

private static final Logger LOG = LoggerFactory.getLogger(DoSFilter.class);
```

The usage of `Log.ignore(Throwable)` would need to be migrated as well.

``` java
LOG.trace("IGNORED", cause);
```

The `org.eclipse.jetty.util.StacklessLogging` would be moved to
`org.eclipse.jetty.logging.StacklessLogging` (in the new `jetty-slf4j-impl` 
module) to provide the same behaviors as before for testing.

## New logging modules for jetty-home

The existing logging modules in Jetty 9.4.x are ...

* console-capture.mod
* jcl-slf4j.mod
* jul-impl.mod
* jul-slf4j.mod
* log4j2-api.mod
* log4j2-impl.mod
* log4j2-slf4j.mod
* log4j-impl.mod
* logback-impl.mod
* logging-jetty.mod
* logging-jul.mod
* logging-log4j.mod
* logging-log4j2.mod
* logging-logback.mod
* logging-slf4j.mod
* slf4j-api.mod
* slf4j-jul.mod
* slf4j-log4j.mod
* slf4j-log4j2.mod
* slf4j-logback.mod
* slf4j-simple-impl.mod

We would simplify this a great deal to just ...

* console-capture.mod
* logging-jetty.mod
* logging-jul.mod
* logging-log4j.mod
* logging-log4j2.mod
* logging-logback.mod

Where each logging module captures all logging implementations
via the various slf4j bridge jars, and enables the appropriate
slf4j implementation jar based on your logging module selection.

The new modules would also no longer force a forking of a JVM.

_Originally posted by @joakime in https://github.com/eclipse/jetty.project/issues/4567#issuecomment-585861202_

### PR DESCRIPTION
**Pull request by joakime**
This is part 1 (of 3) for the Replace Jetty Logging with slf4j effort.

See PR #4643 for part 2.

Introduction of slf4j implementation that performs what StdErrLog does.

This is the initial PR to focus the new work on.

A followup PR will occur after this one has been accepted, and will represent the change over to slf4j-api (and using this new `jetty-slf4j-impl` module for use in testing and `jetty-home`)

### CODE REVIEW

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+//
+// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
+// ========================================================================
+//
+
+package org.eclipse.jetty.logging;
+
+public interface JettyAppender
+{
+    void emit(JettyLoggingEvent event);
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: I don't particularly like this because it is designed to _force_ allocation, and we can avoid it.
This can just be `emit(JettyLogger, Level, String, Object...)` as all the rest can be computed by the implementation.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLogger.java [hunk 2]
```diff
@@ -0,0 +1,663 @@
...
+    public String toString()
+    {
+        final StringBuilder sb = new StringBuilder();
+        sb.append(JettyLogger.class.getSimpleName());
+        sb.append(':').append(name);
+        sb.append(":LEVEL=").append(levelToString(level));
+        return sb.toString();
+    }
+
+    private JettyLoggingEvent asEvent(Level level, String msg)
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLogger.java]: See above, all these `asEvent()` are not necessary.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java [hunk 3]
```diff
@@ -0,0 +1,250 @@
...
+
+    /**
+     * Get a {@link JettyLogger} instance, creating if not yet existing.
+     *
+     * @param name the name of the logger
+     * @return the JettyLogger instance
+     */
+    public JettyLogger getJettyLogger(String name)
+    {
+        assertInitialized();
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: We want to write the code in a way that this assert is not necessary - why paying the cost for _every_ call?

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java [hunk 4]
```diff
@@ -0,0 +1,250 @@
...
+
+import java.util.Objects;
+import java.util.concurrent.ConcurrentHashMap;
+import java.util.concurrent.ConcurrentMap;
+import java.util.function.Consumer;
+
+import org.slf4j.ILoggerFactory;
+import org.slf4j.Logger;
+
+public class JettyLoggerFactory implements ILoggerFactory
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java:29]: The `static` parts of this class need to be synchronized, or eagerly initialized.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java [hunk 5]
```diff
@@ -0,0 +1,250 @@
...
+    {
+        if (instance == null)
+        {
+            instance = new JettyLoggerFactory();
+        }
+
+        return instance;
+    }
+
+    protected static void setInstance(JettyLoggerFactory loggerFactory)
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: Why do we need this at all? Just for testing?

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java [hunk 6]
```diff
@@ -0,0 +1,250 @@
...
+        if (name.equals(ROOT_LOGGER_NAME))
+        {
+            return getRootLogger();
+        }
+
+        JettyLogger jettyLogger = loggerMap.get(name);
+        if (jettyLogger == null)
+        {
+            jettyLogger = createLogger(name);
+            loggerMap.putIfAbsent(name, jettyLogger);
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: This is not atomic. Use `loggerMap.compute()`.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java [hunk 7]
```diff
@@ -0,0 +1,250 @@
...
+            }
+        }
+    }
+
+    public JettyLogger getConfiguredJettyLogger(Class<?> clazz)
+    {
+        return getConfiguredJettyLogger(clazz.getName());
+    }
+
+    public JettyLogger getConfiguredJettyLogger(String name)
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: This method and the one above are never used.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingEvent.java [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+// ========================================================================
+//
+
+package org.eclipse.jetty.logging;
+
+import org.slf4j.Marker;
+import org.slf4j.event.Level;
+import org.slf4j.event.LoggingEvent;
+
+public class JettyLoggingEvent implements LoggingEvent
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingEvent.java]: Not needed, see above.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingServiceProvider.java [hunk 9]
```diff
@@ -0,0 +1,78 @@
...
+    private BasicMarkerFactory markerFactory;
+    private MDCAdapter mdcAdapter;
+
+    @Override
+    public void initialize()
+    {
+        JettyLoggerConfiguration config = new JettyLoggerConfiguration().loadRuntime(this.getClass().getClassLoader());
+        loggerFactory = JettyLoggerFactory.getLoggerFactory().initialize(config);
+        markerFactory = new BasicMarkerFactory();
+        mdcAdapter = new NOPMDCAdapter(); // TODO: Provide Jetty Implementation?
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingServiceProvider.java:47]: Can't we use `BasicMDCAdapter`? I don't think we need a Jetty specific one, but we may want to use the MDC, so we want to have a working implementation.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingServiceProvider.java [hunk 10]
```diff
@@ -0,0 +1,78 @@
...
+
+    private JettyLoggerFactory loggerFactory;
+    private BasicMarkerFactory markerFactory;
+    private MDCAdapter mdcAdapter;
+
+    @Override
+    public void initialize()
+    {
+        JettyLoggerConfiguration config = new JettyLoggerConfiguration().loadRuntime(this.getClass().getClassLoader());
+        loggerFactory = JettyLoggerFactory.getLoggerFactory().initialize(config);
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingServiceProvider.java]: What if 2 thread concurrently trigger the first initialization of this service provider? Does SLF4J make any guarantee that this will not happen?
If it does not, then we may have a concurrent call to a `static` object that must be guarded.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StacklessLogging.java [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+            }
+        }
+    }
+
+    @Override
+    public void close()
+    {
+        for (JettyLogger log : squelched)
+        {
+            log.setHideStacks(false);
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StacklessLogging.java:120]: We do not remember if the stack were hidden before? We should restore to whatever value it was before, rather than forcing `false`, no? Make `squelched` a `Map` and we should be good.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java [hunk 12]
```diff
@@ -0,0 +1,251 @@
...
+     * True to have output show condensed logger names, false to use the as defined long names.
+     */
+    private final boolean condensedNames;
+    /**
+     * True to have messages escaped for control characters, false to leave messages alone.
+     */
+    private final boolean escapedMessages;
+    /**
+     * True to have formatting be based on the strict definition of Slf4J's {@link MessageFormatter},
+     * where there has to be a match to the number of <code>{}</code> in the format string
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Use `{@code ...}` instead of `<code>`.

File: pom.xml [hunk 13]
```diff
@@ -19,9 +19,9 @@
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <build-support.version>1.4</build-support.version>
     <checkstyle.version>8.20</checkstyle.version>
-    <slf4j.version>1.8.0-beta2</slf4j.version>
-    <log4j2.version>2.11.2</log4j2.version>
-    <logback.version>1.3.0-alpha4</logback.version>
+    <slf4j.version>1.8.0-beta1</slf4j.version>
```
Comment (sbordet) [inline pom.xml]: Why we want back to 1.8.0-beta1 from 1.8.0-beta2?

**Review by sbordet — CHANGES_REQUESTED** [review]
I think we should care a little about the performance, since we do have features that can be enabled in production where we want to minimize the logging impact. Following this line, the _design_ should not force inefficiencies - the initial implementation can but at least can be replaced.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java (hunk 1 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: This is in preparation for the slf4j 2.0.0 behaviors.
Which will use the `org.slf4j.event.LoggingEvent` to handle the differences between normal loggers and location aware loggers, along with the markers and context key value pairs.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 3 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: This is only and impact during initialization of a Logger itself, which should occur only once per JVM per named logger.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingEvent.java (hunk 8 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingEvent.java]: Absolutely needed for our slf4j 2.0.0 (near) future

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingServiceProvider.java (hunk 9 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingServiceProvider.java:47]: Using a MDC would also mean we have a custom logger output (appender) to do something with that MDC content.
(yay, we have the key value pairs, now what do we do with them in StdErrAppender?)
Also, in slf4j 2.0.0 this is replaced with a better KeyValuePairs handling in the org.slf4j.event.LoggingEvent

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingServiceProvider.java (hunk 10 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingServiceProvider.java]: Yes, slf4j makes sure this doesn't happen.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StacklessLogging.java (hunk 11 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StacklessLogging.java:120]: Good point.
But to be fair, we only really use StacklessLogging in our unit tests.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 12 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Using `{@code ...}` for content that contains `{` or `}` has caused problems in the javadoc tooling (in the past).

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java (hunk 1 above)
Comment (sbordet) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: I see this as just an implementation detail. 
Whether we will be forced by an implementation to create an event it's orthogonal to the design of this interface.
Events are not part of the SLF4J API so we don't need them.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 3 above)
Comment (sbordet) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: Nope, that is called _every_ time you get a logger. 
Assuming that it only happens once is assuming too much. For example, CometD uses per-instance loggers and there can be thousands/millions of instances created in the lifespan of the application.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java (hunk 1 above)
Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: We can always have an Appender that makes events if they are needed by an integration

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingEvent.java (hunk 8 above)
Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggingEvent.java]: Can you explain why it is needed for slf4j 2.0?  I'ver had a quick look at the API and most of it is unchanged and doesn't require events.  Even the LoggingEventBuilder API should only require a builder implementation and there is no compulsion for normal logging to use that path.

File: pom.xml (hunk 13 above)
Comment (gregw) [reply pom.xml]: Can we do this work against 2.0.0-alpha0.  I know that is an early release, but there is no point going to 1.8 for this change.  If we work against the alpha then we can see any problems and give feedback

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java (hunk 1 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: The new interface would look like this ...

``` java
    void emit(Level level, long timestamp, String threadName, String name, String condensedName, String message, Throwable throwable, Object[] argumentArray, 
              boolean hideStacks, Marker marker);
```

And when slf4j 2.0.0 hits (currently in alpha, no public log4j 2 support yet) the API will look like this ...

``` java
    void emit(Level level, long timestamp, String threadName, String name, String condensedName, String message, Throwable throwable, Object[] argumentArray, 
              boolean hideStacks, List<Marker> markers, List<KeyValuePair> keyValueContextPairs);
```

Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: > We can always have an Appender that makes events if they are needed by an integration

Slf4j will give us `org.slf4j.event.LoggingEvent` instances from the API itself in version 2.0.0+
The idea of an Appender to make events isn't really a thing, we receive them, not the other way around.

File: pom.xml (hunk 13 above)
Comment (joakime) [reply pom.xml]: While slf4j-api `2.0.0-alpha0` exists, there's no public (or SNAPSHOT) release of `log4j2` that uses it (yet).
That's the only reason I stuck with 1.8.0

Comment (joakime) [reply pom.xml]: I'd probably go with `2.0.0-alpha1` if you are ok with no log4j2 support (yet)

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 5 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: It's to help with testing, yes.
That's also the reason it's protected and not public.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 3 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: That's just a horrible use of logging in CometD, this is why Markers and MDC and KeyValuePairs exist.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java (hunk 1 above)
Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: This is now feeling a lot more like we are using slf4j implementation rather than their interface, making me much less interested in this idea.
I just don't see why the implementation of `LOG.debug("foo");` should end up in being much more than a `System.err.printf` under the hood.   We don't want our default implementation to be a stream of slf4j event objects.

I don't understand your point about us not generating events.  The proposed code for debug is:
```java
     @Override
    public void debug(String msg)
    {
        if (isDebugEnabled())
        {
            getAppender().emit(asEvent(Level.DEBUG, msg));
        }
    }
```

But there is no reason that it cannot be:
```java
     @Override
    public void debug(String msg)
    {
        if (isDebugEnabled())
        {
            getAppender().emit(Level.DEBUG, msg);
        }
    }
```

and if events are needed, then emit can create them.... but in fact I can't even see why we need the abstraction of an appender? Shouldn't this code just be:


But there is no reason that it cannot be:
```java
     @Override
    public void debug(String msg)
    {
        if (isDebugEnabled())
        {
            emit(Level.DEBUG, msg);
        }
    }
```

If we want to do something more complex, then the whole implementation of debug is replaced with another jar.    We don't want to reinvent log interception/filtering/appending etc. etc.  we just want a simple StdErr implementation that is statically initialised and can be replaced with a third party implementation if anything sophisticated is desired.

File: pom.xml (hunk 13 above)
Comment (gregw) [reply pom.xml]: We know we will want to go to 2 as soon as it is available, so I think working with 1.8 is not really productive.
I'd much rather find out problems with 2 now when we have a chance to influence the design.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java (hunk 1 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: Splitting up the Logger from what actually produces the log (Appender) makes things easier to maintain and test, and as a bonus it uses less memory (as each logger instance is no longer doing the entire job of emitting the log).

I'll give it a go at making our Appender have multiple entry points.

And with slf4j 2.0.0  ...
We have Markers and KeyValuePairs as well to make a decision on. (do we care to support them or not).
Markers are supported by logback only (currently).
KeyValuePairs (the end result of MDC use) are supported by log4j1 impl, logback impl, and jdk/jul impls currently. (log4j2 impl in git shows signs of supporting them too).

Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: A split API for Appender would now look like ...

``` java
    void emit(JettyLogger logger, Level level, long timestamp, String threadName, String message);

    void emit(JettyLogger logger, Level level, long timestamp, String threadName,
              Throwable throwable, String message);

    void emit(JettyLogger logger, Level level, long timestamp, String threadName, String message,
              Object[] argumentArray);

    void emit(JettyLogger logger, Level level, long timestamp, String threadName, String name,
              Throwable throwable, String message, Object[] argumentArray);
```

Where each parameter is ...
* `JettyLogger logger` is used for the logger name (full or condensed based on appender config), and the hideStacks configuration for that logger.
* `Level level` is for the level of the event itself.
* `long timestamp` the timestamp at logging event time (either from the raw `Logger` methods like `.info()` and `.debug`, but also from `org.slf4j.event.LoggingEvent` data given to us)
* `String threadName` the threadName at logging event time (either from the raw `Logger` methods like `.info()` and `.debug`, but also from `org.slf4j.event.LoggingEvent` data given to us)
* `String message` the log message (or log message format)
* `Throwable throwable` the throwable given. (presented as a whole stacktrace or not, based on logger's hideStacks configuration)
* `Object[] argumentArray` the array of arguments given to the log.

Comment (sbordet) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: There is no need for all those parameters. The 4 I gave in the initial comment are sufficient.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 3 above)
Comment (sbordet) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: It's not "horrible use", it's actually a feature. What I'm saying is that I don't want to bind design decision to assumptions that are wrong, so let's base on the least number of assumptions.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java (hunk 1 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: > This is now feeling a lot more like we are using slf4j implementation rather than their interface, making me much less interested in this idea.

The entirety of Jetty uses only `org.slf4j.Logger` and `org.slf4j.LoggerFactory`, we are using their interface.
This `jetty-slf4j-impl` is our implementation of those, and are completely optional.
In fact, only the `StacklessLogging` class is used directly by Jetty test cases, the rest is not used directly by Jetty.

**Scenario 1**

The use of slf4j also allows us to (for example) capture other loggers and route them to any slf4j implementation we want.

Jetty uses the `org.slf4j.Logger` API to create it's logging events.
We have the following jars on the classpath.
* `slf4j-api.jar`
* `jetty-slf4j-impl.jar` (this is the slf4j impl in use)
* `jcl-over-slf4j.jar` (bridge api for commons-logging)
* `jul-to-slf4j.jar` (bridge api for java.util.logging, JSP and mail jars use this)
* `log4j-to-slf4j.jar` (bridge api for log4j 1.x and log4j 2.x)

(For slf4j 1.x there are also bridge API jars for apache juli, and osgi logging, haven't checked for slf4j 2.x)

We can receive events from any of the logging APIs now.
Our `org.eclipse.jetty.logging.JettyLogger` can receive those events as ...
* Calls to equivalent `.info()` or `.debug()` style methods
* A call to `public void log(org.slf4j.event.LoggingEvent event)` (depends on bridge API - this is the `SubstituteLogger` internal slf4j API).
* A call to `public void log(Marker marker, String callerFQCN, int level, String msg, Object[] arguments, Throwable t)` (depends on bridge API and if source/location features - this is the `LocationAwareLogger` internal slf4j API)

The existence of the `org.slf4j.event.LoggingEvent` is to handle loggers that process events in a non-direct way:
* lost threadname information (like java.util.logging)
* timestamp skews (like osgi logging)

With this PR, the `jetty-slf4j-impl` can handle all of those events, and can now be written to `System.err` via the `StdErrAppender` (not supported in Jetty 9.4.x or current 10.x HEAD) and we don't have to care about where it came from, just implement the interface `org.slf4j.Logger` (with `LocationAwareLogger` and `SubstituteLogger` extensions)

**Scenario 2**

Jetty uses the `org.slf4j.Logger` API to create it's logging events.
The user has chosen to use it's own slf4j impl (lets call it `corp-slf4j-impl.jar`)
Jetty participates with logging level / name / MDC / location without extra work or effort.
All of the classes in this PR are unused and are not present.

Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: > There is no need for all those parameters. The 4 I gave in the initial comment are sufficient.

No, they are not.
Especially when using slf4j bridge APIs for capturing other loggers into our `jetty-slf4j-impl`

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLogger.java (hunk 2 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLogger.java]: JettyLoggingEvent has been removed.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 3 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: initialized assert removed

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 4 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java:29]: For normal (non-testing) usage, this is only initialized by slf4j-api during it's `org.slf4j.LoggerFactory.getInstance()` call which results in our service provider being kicked off during a formal initialization phase.
See `JettyLoggingServiceProvider.initialize()`

File: pom.xml (hunk 13 above)
Comment (joakime) [reply pom.xml]: Updated to `2.0.0-alpha1`

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java (hunk 1 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyAppender.java]: The entire StdErrAppender API interface has been redone.
No more JettyLoggingEvent.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StacklessLogging.java (hunk 11 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StacklessLogging.java:120]: No work is needed here.
The `squelched` collection only has loggers that were originally `logger.isHideStacks == false;`
Entries that were originally `logger.isHideStacks == true` are not present in the `squelched` list.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java [hunk 14]
```diff
@@ -0,0 +1,331 @@
...
+        switch (level)
+        {
+            case ERROR:  // New for Jetty 10+
+                return "ERROR";
+            case WARN:
+                return "WARN";
+            case INFO:
+                return "INFO";
+            case DEBUG:
+                return "DBUG"; // keeping abbreviated name for historical reasons
```
Comment (olamy) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: I'm really curious about the story behind this? :) ERROR is 5 characters so DEBUG will not be longer

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java [hunk 15]
```diff
@@ -0,0 +1,213 @@
...
+import java.util.concurrent.ConcurrentHashMap;
+import java.util.concurrent.ConcurrentMap;
+import java.util.function.Consumer;
+
+import org.slf4j.ILoggerFactory;
+import org.slf4j.Logger;
+
+public class JettyLoggerFactory implements ILoggerFactory
+{
+    protected static JettyLoggerFactory getLoggerFactory()
```
Comment (gregw) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: Do we need this static instance at all?  The instance we will use is the one created by the `JettyLoggingServiceProvider` so why confuse things and have another lazy static?

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java [hunk 16]
```diff
@@ -0,0 +1,331 @@
...
+     * Configuration keys specific to the StdErrAppender
+     */
+    public static final String NAME_CONDENSE_KEY = "org.eclipse.jetty.logging.appender.NAME_CONDENSE";
+    public static final String THREAD_PADDING_KEY = "org.eclipse.jetty.logging.appender.THREAD_PADDING";
+    public static final String MESSAGE_ESCAPE_KEY = "org.eclipse.jetty.logging.appender.MESSAGE_ESCAPE";
+    public static final String STRICT_SLF4J_FORMAT_KEY = "org.eclipse.jetty.logging.appender.STRICT_SLF4J_SYNTAX";
+    public static final String ZONEID_KEY = "org.eclipse.jetty.logging.appender.ZONE_ID";
+
+    private static final Object[] EMPTY_ARGS = new Object[0];
+    private final DateTimeFormatter timestampFormatter;
```
Comment (gregw) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Why are we not using `DateCache`?    I know it is not as flexible as a modern formatter, but it is fast for the simple data stamp that this log needs.  If users want anything fancier, they should replace our logging.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java [hunk 17]
```diff
@@ -0,0 +1,331 @@
...
+        builder.append(threadName); // TODO: support TAG_PAD configuration
+        builder.append(':');
+
+        // Message
+        builder.append(' ');
+
+        if (strictFormat)
+        {
+            FormattingTuple ft = MessageFormatter.arrayFormat(message, argumentArray);
+            appendEscaped(builder, ft.getMessage());
```
Comment (gregw) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: what is this?  Looks like slf4j implementation to me.... and a mode of operation.   We don't want either.
We just want simple formatting as we currently do, if anything different is required then we replace the logging jar.
Modes of operation are just slow and confusing.

So we definitely have to remove the modes.

Are the slf4j helper classes in the API jar?   What are the differences between their format and ours?

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java [hunk 18]
```diff
@@ -0,0 +1,331 @@
...
+            }
+        }
+    }
+
+    private String renderedLevel(Level level)
+    {
+        switch (level)
+        {
+            case ERROR:  // New for Jetty 10+
+                return "ERROR";
```
Comment (gregw) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java:182]: The intention is that all the level tags are the same length so that they read nicely down the screen (not sure how ignored escaped that), so they should either be:
```
"ERR "
"WARN"
"INFO"
"DBUG"
```
or
```
"ERROR"
"WARN "
"INFO "
"DEBUG"
```

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 14 above)
Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: ERROR is a new level that was not there before. See my comment above.

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 14 above)
Comment (olamy) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: my question is more why keep the "DBUG" :) we can use "DEBUG"

Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Sure we can use "DEBUG", but we then have to use "WARN " instead of "WARN" to keep the formatting nice.  I'm OK with that... or even if we pad with "%5s" when printing (although adding the space here is probably a lot faster/simpler).

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 17 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Our formatter is historical and frankly broken.
I'll remove our formatter (the MessageFormatter is in the slf4j-api jar and handles formatting along with final Throwable logic)

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 16 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Our DateCache exists in jetty-util (which we cannot depend on), and it uses the standard Java DateTimeFormatter in exactly the same way like this code does (when formatting with milliseconds like this Appender does).
The DateCache only works on caching results that are on the same second and do not contain a millisecond formatting string.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 15 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: That static is used by both our implementation (to handle cascading level and hidestacks runtime changes) and the JettyLoggingServiceProvider's own `initialize()` phase.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 18 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java:182]: I'll use the second form.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 17 above)
Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: OK - but can you explain the differences?

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 16 above)
Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: StdErrLog uses DateCache and separately handles the ms.  So why can't we depend on jetty-util?      I know it is a very old class.... but when it was introduced it was VERY beneficial.  If we are doing full logging, we can avoid thousands of time formats per second - well worth it!

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 17 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: MessageFormatter will ...

* perform the `{}` formatting
* handle escaped `\\{}` entries in the input format string
* honor the provided `{}` and not add extra ones that are missing
* handle null argument array entries properly (by not showing `null` in the output)
* skip formatting if arguments array is empty 
* if final argument is a throwable make note of it and return it

Our formatter will ...

* perform the `{}` formatting
* not honor escaped `\\{}` entries
* add missing `{}` entries to process entire arguments array
* format even if arguments array is empty or contains null characters
* format Throwable via `Throwable.toString()` as any other argument in the array

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 16 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Yes, and I tested StdErrLog's DateCache usage, and found it has a 100% cache-miss on uses with DateCache simply because it formats with milliseconds.
Which means, DateCache always used java's DateTimeFormatter to format.

Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Opened #4605 to review DateCache.
The results of that can determine what we do here.
Use it more aggressively everywhere (including this jetty-slf4j-impl), or something else.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 17 above)
Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: OK sounds near enough... and if we have the helpers on the classpath anyway!

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 16 above)
Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Then let's not remove it and have to review to have it replace.  Keep it and review to see if we remove it!

Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: I cannot add the dependency on jetty-util here as jetty-util uses logging it's a loop in both the dependencies on maven and the load order at jvm runtime.
I would rather just rip out the DateTimeFormatter entirely and just use raw inline formatting against the Java 8+ date/time APIs.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 15 above)
Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: I think this is needlessly complex and the use of initiailize methods means we cannot use fast finals.
The JettyLoggingServiceProvider should just make it's own instance and pass the configuration into the constructor. If slf4j is providing us with a life cycle mechanism, then I don't see why we need to duplicate with statics.  Can you try to get rid of this

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 16 above)
Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: StdErrLog uses it, so this can use it.    Avoiding calling any formatter thousands of times per second is very valuble.

Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: I just ran StdErrLogTest and it had 1 MISS and every other log in the test was a date cache hit!

Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Note the solution to the dependency issue is to make this implementation part of org.eclipse.jetty.util.log in jetty-util

Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: I did this differently:

* Brought in DateCache into jetty-sfl4j-impl
* Stripped out everything that jetty-slf4j-impl wouldn't use (down to 1 public method)
* Renamed it to Timestamp
* Have millisecond formatting done within Timestamp on top of the cached Tick.formattedString (if a cache hit or cache miss on the second cache, just like DateCache does)

Comment (gregw) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Oh but we can't do that... because then we can't replace the jar.... hmmmmm

Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: This is the only method in DateCache that a logger would use.

https://github.com/eclipse/jetty.project/blob/7ce14a419fd1c7cec42d808ac3e6fd862ce517b4/jetty-util/src/main/java/org/eclipse/jetty/util/DateCache.java#L203-L222

Incidentally, in the process, I discovered a bug in DateCache, filed in #4606

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 17 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: The lax formatting that Jetty StdErrLog had is now removed

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 15 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: Removed singletons at JettyLoggerFactory

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java (hunk 14 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/StdErrAppender.java]: Fixed.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 4 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java:29]: Removed singletons at JettyLoggerFactory level

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java [hunk 19]
```diff
@@ -0,0 +1,196 @@
...
+import java.util.function.Consumer;
+
+import org.slf4j.ILoggerFactory;
+import org.slf4j.Logger;
+
+public class JettyLoggerFactory implements ILoggerFactory
+{
+    private static final String ROOT_LOGGER_NAME = "";
+    private JettyLoggerConfiguration configuration;
+    private JettyLogger rootLogger;
```
Comment (gregw) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]:
```suggestion
    private final JettyLoggerConfiguration configuration;
    private final JettyLogger rootLogger;
```

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java [hunk 20]
```diff
@@ -0,0 +1,196 @@
...
+    /**
+     * Reinitialize this Factory, forgetting about all prior config and loggers.
+     * <p>
+     * This is really only used in test cases.
+     * </p>
+     *
+     * @param config the configuration to reset to
+     */
+    protected void initialize(JettyLoggerConfiguration config)
+    {
```
Comment (gregw) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]:
```suggestion
```

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 19 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: This is the side effect of eliminating the singleton.
I need to be able to reset the active configuration that `org.slf4j.LoggerFactory` is tracking, as I cannot reset the active `LoggerFactory` to test scenarios.
I either have a Singleton with final fields where I can reset the singleton itself, or I have the ability to reset the configuration.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 20 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: I need this for testing, all of your prior recommendations have eliminated all of my options, don't get rid of this one too.

Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: Done.

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java (hunk 19 above)
Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: Done

File: jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java [hunk 21]
```diff
@@ -69,7 +69,7 @@ public JettyLogger getJettyLogger(String name)
      * @return the Slf4j Logger
      */
     @Override
-    public Logger getLogger(String name)
+    public synchronized Logger getLogger(String name)
```
Comment (sbordet) [inline jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: Nope. This is not needed.

Comment (joakime) [reply jetty-slf4j-impl/src/main/java/org/eclipse/jetty/logging/JettyLoggerFactory.java]: reverted.

**Review by olamy — APPROVED** [review]

**Review by sbordet — APPROVED** [review]

**Comment by joakime** [comment]
Merged (manually) into `jetty-10.0.x`
