### PR TITLE
Issue #12609 - better validation for response codes in setStatus

### LINKED ISSUE #12609: Change of behaviour with HttpServletResponse.sendError(0) in EE10
**Jetty version(s)**
12.0.x

**Jetty Environment**
ee10

**Description**
I noticed that `resp.sendError(0)` has a change of behaviour in EE10 compared to EE8 and Jetty 9.4

Previously Jetty would throw IAE for status 0.
Now this will send back a 200 response with no body.

```
java.lang.IllegalArgumentException
        at org.eclipse.jetty.ee8.nested.Response.setStatus(Response.java:666)
        at org.eclipse.jetty.ee8.nested.HttpChannelState.sendError(HttpChannelState.java:782)
        at org.eclipse.jetty.ee8.nested.Response.sendError(Response.java:449)
        at org.eclipse.jetty.ee8.nested.Response.sendError(Response.java:422)
        at org.example.DemoServlet.service(DemoServlet.java:16)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.eclipse.jetty.ee8.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1146)
        at org.eclipse.jetty.ee8.servlet.ServletHolder.handle(ServletHolder.java:640)
```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
closes #12609

### CODE REVIEW

**Review by gregw — CHANGES_REQUESTED** [review]
Let's do this only in 12.1.x

Also why not do it in core Response?

**Comment by lachlan-roberts** [comment]
@gregw this came up because there was a change in behavior testing sendError on GAE, so I think its worth keeping it for `12.0.x`.

> Also why not do it in core Response?

good point, fixed now

File: jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Response.java [hunk 1]
```diff
@@ -754,7 +754,7 @@ public void addIntHeader(String name, int value)
     @Override
     public void setStatus(int sc)
     {
-        if (sc <= 0)
+        if (sc < 100 || sc > 999)
```
Comment (gregw) [inline jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Response.java:757]: I assume that if we didn't check here the core response check would eventually throw?  But probably best to check here so the throw comes at the expected method rather than a later flush

**Review by gregw — APPROVED** [review]

**Review by janbartel — APPROVED** [review]
