### PR TITLE
Issue #6205 - Fix issues with OpenID redirecting to wrong URI

### LINKED ISSUE #6205: OpenIdAuthenticator may use incorrect redirect
**Jetty version**

Jetty 10/11

**Java version**

**OS type/version**

**Description**

If a javascript application is running in the background of a browser (like cometd trying to connect) and the server is stopped and then started then when the user submits a request for an address within the application the openid authenticator will likely redirect to an internal cometd url instead of the original clicked link.

2021-04-21 06:34:13.497:DEBUG:oejso.OpenIdAuthenticator:qtp640363654-49: validateRequest(Request(GET http://localhost:8080/)@5cfae74f,HTTP/1.1 200 |Date: Wed, 21 Apr 2021 11:34:13 GMT<|<|,true)
...
2021-04-21 06:34:16.399:DEBUG:oejso.OpenIdCredentials:qtp640363654-32: claims { ... }
2021-04-21 06:34:16.407:DEBUG:oejso.OpenIdAuthenticator:qtp640363654-32: authenticated OpenId{User,OPENID,DefaultUserIdentity('111707093257242721596')}->http://localhost:8080/core/connect
2021-04-21 06:34:16.414:DEBUG:oejso.OpenIdAuthenticator:qtp640363654-27: Restoring original method POST for http://localhost:8080/core/connect with method GET
2021-04-21 06:34:16.415:DEBUG:oejso.OpenIdAuthenticator:qtp640363654-27: validateRequest(Request(POST http://localhost:8080/core/connect)@5cfae74f,HTTP/1.1 200 |Date: Wed, 21 Apr 2021 11:34:16 GMT<|Set-Cookie: JSESSIONID=node01w1inwnrz1uzc1oon36n09gqm21.node0; Path=/<|Expires: Thu, 01 Jan 1970 00:00:00 GMT<|<|,true)
2021-04-21 06:34:16.415:DEBUG:oejso.OpenIdAuthenticator:qtp640363654-27: auth retry SessionAuthentication@1eb39854{-,DefaultUserIdentity('111707093257242721596')}->http://localhost:8080/core/connect
2021-04-21 06:34:16.415:DEBUG:oejso.OpenIdAuthenticator:qtp640363654-27: auth SessionAuthentication@1eb39854{-,DefaultUserIdentity('111707093257242721596')}

This looks like it might be addressed with the partially implemented 'alwaysSaveUri' functionality in the jetty-openid module.  Investigating.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Closes #6205**

This change uses the CSRF token to index into a `Map` of `CSRF_TOKEN` to `RedirectInfo`. By doing this we can get the URI and method of the original request which started the OpenID authentication process. This will allow it to find the correct URI and not get confused with other resources requested by the browser, or by some calls made by javascript running on the page.

### CODE REVIEW

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java [hunk 1]
```diff
@@ -260,48 +263,53 @@ public Authentication validateRequest(ServletRequest req, ServletResponse res, b
...
+                    sendError(request, response, "auth failed: no state parameter");
+                    return Authentication.SEND_FAILURE;
+                }
+
+                // Verify anti-forgery state token.
+                UriRedirectInfo uriRedirectInfo;
+                synchronized (session)
+                {
+                    uriRedirectInfo = removeAndClearCsrfMap(session, state);
+                    if (uriRedirectInfo == null)
```
Comment (sbordet) [inline jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: This `if` block should be outside of `synchronized`.

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java [hunk 2]
```diff
@@ -464,16 +450,15 @@ private String getRedirectUri(HttpServletRequest request)
...
         HttpSession session = request.getSession();
         String antiForgeryToken;
         synchronized (session)
         {
-            antiForgeryToken = (session.getAttribute(CSRF_TOKEN) == null)
-                ? new BigInteger(130, new SecureRandom()).toString(32)
-                : (String)session.getAttribute(CSRF_TOKEN);
-            session.setAttribute(CSRF_TOKEN, antiForgeryToken);
+            Map<String, UriRedirectInfo> csrfMap = ensureCsrfMap(session);
+            antiForgeryToken = new BigInteger(130, new SecureRandom()).toString(32);
```
Comment (sbordet) [inline jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: Please use `Character.MAX_RADIX` instead of 32.

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java [hunk 3]
```diff
@@ -494,7 +479,80 @@ protected String getChallengeUri(HttpServletRequest request)
...
+    }
+
+    private UriRedirectInfo removeAndClearCsrfMap(HttpSession session, String csrf)
+    {
+        @SuppressWarnings("unchecked")
+        Map<String, UriRedirectInfo> csrfMap = (Map<String, UriRedirectInfo>)session.getAttribute(CSRF_MAP);
+        if (csrfMap == null)
+            return null;
+
+        UriRedirectInfo uriRedirectInfo = csrfMap.remove(csrf);
```
Comment (sbordet) [inline jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: Use `get()` instead of `remove()` since you are clearing on the next line.

**Review by jmcc0nn3ll — COMMENTED** [review]
I cherrypicked this over to jetty-11.0.x and it no longer tries to redirect to cometd internal urls.

However, I enabled the session-store-file and it is failing to persist:

java.io.NotSerializableException: org.eclipse.jetty.security.openid.OpenIdAuthenticator$UriRedirectInfo

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java [hunk 4]
```diff
@@ -260,48 +263,53 @@ public Authentication validateRequest(ServletRequest req, ServletResponse res, b
...
+                if (LOG.isDebugEnabled())
+                    LOG.debug("authenticated {}->{}", openIdAuth, uriRedirectInfo.getUri());
 
-                        response.setContentLength(0);
-                        baseResponse.sendRedirect(nuri, true);
-                        return openIdAuth;
-                    }
-                }
+                // Save redirect info in session so original request can be restored after redirect.
+                session.setAttribute(J_URI, uriRedirectInfo.getUri());
```
Comment (sbordet) [inline jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: Be consistent with `session` locking in all the places.

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java [hunk 5]
```diff
@@ -494,7 +479,80 @@ protected String getChallengeUri(HttpServletRequest request)
...
+                {
+                    return size() > MAX_SIZE;
+                }
+            };
+            session.setAttribute(CSRF_MAP, csrfMap);
+        }
+        return csrfMap;
+    }
+
+    private static class UriRedirectInfo
```
Comment (sbordet) [inline jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: @janbartel are there strict rules about custom classes saved to the `HttpSession`? Like class should be `public`, `Serializable`, etc.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java (hunk 5 above)
Comment (janbartel) [reply jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: The best thing to do is to make any attribute you store in the `HttpSession` `be Serializable`. Otherwise your attribute could implement the `HttpSessionActivationListener` interface instead: it can transform itself in some way on the `sessionWillPassivate()` and `sessionWillActivate()` methods.

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java [hunk 6]
```diff
@@ -494,7 +479,80 @@ protected String getChallengeUri(HttpServletRequest request)
...
+        Map<String, UriRedirectInfo> csrfMap = (Map<String, UriRedirectInfo>)session.getAttribute(CSRF_MAP);
+        if (csrfMap == null)
+        {
+            // Create a custom Map so we can only have a limited number of request URIs saved.
+            csrfMap = new LinkedHashMap<>()
+            {
+                private static final int MAX_SIZE = 64;
+
+                @Override
+                protected boolean removeEldestEntry(Map.Entry<String, UriRedirectInfo> eldest)
```
Comment (janbartel) [inline jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java:530]:
```suggestion
                protected boolean removeOldestEntry(Map.Entry<String, UriRedirectInfo> eldest)
```

**Review by janbartel — CHANGES_REQUESTED** [review]

**Review by janbartel — CHANGES_REQUESTED** [review]
Make session attribute serializable and change name of method as indicated in comments.

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java (hunk 6 above)
Comment (lachlan-roberts) [reply jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java:530]: @janbartel This overrides an existing method on `LinkedHashMap`. 
So I don't think I can change the name of this to `removeOldestEntry`.

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: I think 32 is very common to be used for things like session IDs for reasons described in.
https://stackoverflow.com/questions/29183818/why-use-tostring32-and-not-tostring36/

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java (hunk 6 above)
Comment (janbartel) [reply jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java:530]: Hah! LinkedHashMap is wrong: "eldest" is just for people, "oldest" is for things.

**Review by janbartel — DISMISSED** [review]
LGTM

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java [hunk 7]
```diff
@@ -260,71 +272,78 @@ public Authentication validateRequest(ServletRequest req, ServletResponse res, b
...
-                    session.removeAttribute(SessionAuthentication.__J_AUTHENTICATED);
-                }
-                else
+                Authentication authentication = (Authentication)session.getAttribute(SessionAuthentication.__J_AUTHENTICATED);
+                if (authentication != null)
                 {
-                    synchronized (session)
+                    // Has authentication been revoked?
+                    if (authentication instanceof Authentication.User && _loginService != null &&
+                        !_loginService.validate(((Authentication.User)authentication).getUserIdentity()))
```
Comment (sbordet) [inline jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: This is a call to `LoginService` with the lock held on the `session`. I would prefer to have it outside the lock.

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java (hunk 2 above)
Comment (sbordet) [reply jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: Good point.

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java [hunk 8]
```diff
@@ -494,7 +491,82 @@ protected String getChallengeUri(HttpServletRequest request)
...
+                {
+                    return size() > MAX_SIZE;
+                }
+            };
+            session.setAttribute(CSRF_MAP, csrfMap);
+        }
+        return csrfMap;
+    }
+
+    private static class UriRedirectInfo implements Serializable
```
Comment (sbordet) [inline jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java:540]: Are we sure this class can be `private`? How can it be restored by the jetty-session module? How does it work with JPMS, which has stricter rules?

If you don't want to expose a `private` class, use a `Map` for the 3 values that it stores.

It is important to get this right from the beginning to avoid incompatibilities when updating the Jetty version.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java (hunk 2 above)
Comment (gregw) [reply jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: However, I don't like the `new SecureRandom()` here.  Can't we have a `SecureRandom` instance that is reused rather than making a new one each call?

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java (hunk 8 above)
Comment (janbartel) [reply jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java:540]: @sbordet  I don't know about JPMS, but it seems that java serialization doesn't care about public,private,protected.  Our session attribute serialization calls `ObjectOutputStream.writeObject() `for each attribute value in the session. I created a test that did substantially the same thing as this code (storing a `HashMap` as the session attribute, where some of the entries in the `HashMap` were instances of a private class) and used the `FileSessionDataStore` to persist the session:  the session was serialized and deserialized without error.

File: jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-openid/src/main/java/org/eclipse/jetty/security/openid/OpenIdAuthenticator.java]: done

**Review by sbordet — APPROVED** [review]

**Comment by jmcc0nn3ll** [comment]
@lachlan-roberts I still see persist issues on Jetty 11. 

```
2021-05-12 08:49:01.707:WARN :oejss.SessionHandler:qtp99451533-38: Unable to renew Session Id node01rgo03lt33jlxemrsf2crziju0:node01rgo03lt33jlxemrsf2crziju0.node0 -> node01lo2cluwb6gdl1dd42sp3pzjj1:node01lo2cluwb6gdl1dd42sp3pzjj1.node0
org.eclipse.jetty.server.session.UnwriteableSessionDataException: Unwriteable session node01lo2cluwb6gdl1dd42sp3pzjj1 for node0__0.0.0.0
	at org.eclipse.jetty.server.session.FileSessionDataStore.doStore(FileSessionDataStore.java:333)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore.lambda$store$2(AbstractSessionDataStore.java:220)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1425)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1462)
	at org.eclipse.jetty.server.session.SessionContext.run(SessionContext.java:87)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore.store(AbstractSessionDataStore.java:230)
	at org.eclipse.jetty.server.session.AbstractSessionCache.renewSessionId(AbstractSessionCache.java:787)
	at org.eclipse.jetty.server.session.AbstractSessionCache.renewSessionId(AbstractSessionCache.java:752)
	at org.eclipse.jetty.server.session.SessionHandler.renewSessionId(SessionHandler.java:1108)
	at org.eclipse.jetty.server.session.DefaultSessionIdManager.renewSessionId(DefaultSessionIdManager.java:450)
	at org.eclipse.jetty.server.session.Session.renewId(Session.java:811)
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.renewSession(LoginAuthenticator.java:126)
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:65)
	at org.eclipse.jetty.security.openid.OpenIdAuthenticator.login(OpenIdAuthenticator.java:167)
	at org.eclipse.jetty.security.openid.OpenIdAuthenticator.validateRequest(OpenIdAuthenticator.java:308)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:515)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1358)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1280)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:562)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:399)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:656)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:391)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: 
java.io.NotSerializableException: org.eclipse.jetty.security.openid.OpenIdAuthenticator
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at org.eclipse.jetty.server.session.SessionData.serializeAttributes(SessionData.java:111)
	at org.eclipse.jetty.server.session.FileSessionDataStore.save(FileSessionDataStore.java:481)
	at org.eclipse.jetty.server.session.FileSessionDataStore.doStore(FileSessionDataStore.java:325)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore.lambda$store$2(AbstractSessionDataStore.java:220)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1425)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1462)
	at org.eclipse.jetty.server.session.SessionContext.run(SessionContext.java:87)
	at org.eclipse.jetty.server.session.AbstractSessionDataStore.store(AbstractSessionDataStore.java:230)
	at org.eclipse.jetty.server.session.AbstractSessionCache.renewSessionId(AbstractSessionCache.java:787)
	at org.eclipse.jetty.server.session.AbstractSessionCache.renewSessionId(AbstractSessionCache.java:752)
	at org.eclipse.jetty.server.session.SessionHandler.renewSessionId(SessionHandler.java:1108)
	at org.eclipse.jetty.server.session.DefaultSessionIdManager.renewSessionId(DefaultSessionIdManager.java:450)
	at org.eclipse.jetty.server.session.Session.renewId(Session.java:811)
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.renewSession(LoginAuthenticator.java:126)
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:65)
	at org.eclipse.jetty.security.openid.OpenIdAuthenticator.login(OpenIdAuthenticator.java:167)
	at org.eclipse.jetty.security.openid.OpenIdAuthenticator.validateRequest(OpenIdAuthenticator.java:308)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:515)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1358)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1280)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:562)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:399)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:656)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:391)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jmcc0nn3ll** [comment]
resolved!
