### PR TITLE
Fix jetty 12.0.x transient timeouts

### LINKED ISSUE #9169: Idle timeout is ignored if callback is not completed
**Jetty version(s)**
Jetty 12

**Description**
If the Handler.process() Callback is not completed, the Idle timeout mechanism is ignored / doesn't happen.

Is this as intended? or a relic of the Servlet API behavior that slipped into core?

### LINKED ISSUE #10234: Make idle timeouts transient
**Jetty version(s)**
12

**Enhancement Description**

Idle timeouts delivered via read() should be transient, i.e. another read can be attempted after the timeout of the read chunk is not last

### LINKED ISSUE #10277: Review read failures impacting writes
**Jetty version(s)**
12

**Description**
Read failures should not impact writes (too much), as a write might still be possible even if the read failed.
Typical examples are early EOF in reads -- they should not impact writes.

The idea is that if a read failure is catastrophic, we would attempt the write anyway and will get the failure through the write, rather than assuming that the writes will fail.

Child issues / prs
 - [ ] #10431 
 - [ ] #10432

### LINKED ISSUE #10357: EE10 `ServletChannelState` input FSM should be reviewed
**Jetty version(s)**
12.0.0

**Jetty Environment**
EE10

**Description**
While fixing https://github.com/eclipse/jetty.project/issues/10315, it became apparent that the implementation behind the FSM backing `HttpInput` should be reviewed entirely.

The impedance mismatch between the Jetty 10/11 `needContent()` / `produceContent()` contract vs the Jetty 12 `demand()` / `read()` one means the state checks and transitions need to be placed slightly differently in certain situations.

For instance, #10315 was about the fact that `needContent()` fills, parses and registers for fill interest if necessary while being idempotent; doing the same thing in EE10 requires calling `read()` then `demand()` if necessary, but also needs to take into account that `read()` must not be called while there is a pending demand as the idempotency is gone from the EE10-backing API. Fixing that bug required checking that when using the blocking API, `ServletInputStream.isReady()` must not call `read()` while the FSM is in `UNREADY` state otherwise we would call `read()` during a pending demand. Fixing the bug required changing the state transitions so that `BlockingContentProducer` moves back to `IDLE` state when a demand has been serviced. This means the comments in `BlockingContentProducer.onContentProducible()` which describe this mechanism don't apply anymore to EE10 (`HttpChannelState.asyncError()` went away for instance) and the references to the tests covering this mechanism are stale too.

Another point requiring investigation is that some tests like `ProxyServletTest.testExpect100ContinueRespond100ContinueSomeRequestContentThenFailure` log the following warning when executed, while passing and being apparently correct:
```
java.lang.IllegalStateException: s=HANDLING rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=false al=0
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.handling(ServletChannelState.java:357)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:462)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1264)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1251)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.lambda$execute$0(ContextHandler.java:1276)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

All the state transitions both in blocking and unblocking modes, as well as test coverage (including using H2 / H3) should be re-assessed for EE10 as we know from experience that this FSM is very delicate.

### PR DESCRIPTION
**Pull request by gregw**
Fixes #10234 and #10277 and also #10357. Builds on #10814 and #10801

### CODE REVIEW

**Comment by gregw** [comment]
@lorban I'm making some progress on this, but there are lots of failures in servlet land because AsyncProducer has not been written with transient failures in mind.   It keeps reading again expecting to get the same chunk.   I have done some hacky fixes to improve this, but it is not enough.   Feel free to play in this branch and see if you can fix more.... but ultimately we probably want to take a step back a re-implement AsyncProducer with the new transient failure contract in mind.... but maybe bandaids can get us there.

**Comment by lorban** [comment]
I reviewed the ee10 `ContentProducer` FSM, "ported" the tests from ee9 and added some tests for transient errors.

It looks like everything is in order now, and #10357 can be included in the list of issues this PR solves.

**Comment by lorban** [comment]
We need to review all `Content.Chunk.isFailure(Chunk c)` calls as they currently all assume that a failure content is also a last content.

Now, there must be a distinction between terminal and transient failures, and in the latter case, one of the following actions has to be taken depending on the context:

 - Pass the chunk to another layer to decide what to do.
 - Ignore (silently?) the transient error.
 - Consider the transient failure as a terminal failure.

In the case of `Content.Source` read loops, if the transient error is ignored, we should loop again, while if it is considered terminal, the `Content.Source` must be explicitly ended with `fail()`.

There are a lot of places to review and many tests to add or modify to inject some transient errors and check the behavior.

**Comment by gregw** [comment]
@lorban perhaps we can hangout in your morning and go through this?   @sbordet join?

**Comment by gregw** [comment]
@lorban nice tests!

**Comment by lorban** [comment]
@gregw @sbordet I reviewed all `Content.Chunk.isFailure(Chunk)` usages, added a bunch of tests, and fixed a few bugs, so this PR is now ready for review.

FYI only one of the changes we made in the first pass was wrong (it was in `MultiPart.AbstractContentSource.read()`, but there were other bugs).

Overall, transient failures work and can be elegantly retrofitted without changing the `Content.Source` contract.

**Comment by gregw** [comment]
I can't review this PR, so over to you @sbordet

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/Response.java [hunk 1]
```diff
@@ -190,6 +190,8 @@ default void onContentSource(Response response, Content.Source contentSource)
             if (Content.Chunk.isFailure(chunk))
             {
                 response.abort(chunk.getFailure());
+                if (!chunk.isLast())
+                    contentSource.fail(chunk.getFailure());
```
Comment (sbordet) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/Response.java:194]: This block is ok. But should we fail in the `catch` below, or just `LOG.info()` like we do when notifying user code?

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java [hunk 2]
```diff
@@ -598,34 +603,47 @@ protected Content.Chunk transform(Content.Chunk inputChunk)
...
+
+                if (!_chunk.hasRemaining())
+                {
+                    Content.Chunk result = _chunk.isLast() ? Content.Chunk.EOF : null;
+                    if (LOG.isDebugEnabled())
+                        LOG.debug("Could not decode more from this chunk, releasing it, r={}", result);
+                    _chunk.release();
+                    _chunk = null;
+                    return result;
+                }
```
Comment (sbordet) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java]: Please review this logic against the original.
Contract is that if decoded == null then need more input, otherwise trust the decoded.

File: jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/AsyncContentListenerTest.java [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+            Content.Chunk.from(ByteBuffer.wrap(new byte[] {1}), false),
+            Content.Chunk.from(ByteBuffer.wrap(new byte[] {2}), false),
+            Content.Chunk.from(new NumberFormatException(), false),
+            Content.Chunk.from(ByteBuffer.wrap(new byte[] {3}), true)
+        );
+
+        List<Content.Chunk> collectedChunks = new ArrayList<>();
+        Response.AsyncContentListener asyncContentListener = (response, chunk, demander) ->
+        {
+            collectedChunks.add(chunk);
```
Comment (sbordet) [inline jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/AsyncContentListenerTest.java:50]: Technically you should retain the chunk here, because it's stored for later use.
For this test it is not necessary only because the buffers are not consumed, nor recycled, but would be best if we can stick to the doctrine :)

File: jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/TestSource.java [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+
+import java.nio.ByteBuffer;
+import java.util.Arrays;
+import java.util.List;
+import java.util.Queue;
+import java.util.concurrent.ConcurrentLinkedQueue;
+
+import org.eclipse.jetty.io.Content;
+
+public class TestSource implements Content.Source
```
Comment (sbordet) [inline jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/TestSource.java]: Can you reuse `ChunksContentSource` instead of writing this class from scratch?
I'm fine to have a `TestSource` class, just wondering if we can reuse `ChunksContentSource` for its implementation.

The constructor of this class breaks the doctrine, so this class needs to have javadocs that say that's special, and can only receive newly created `Chunk`s, etc.

Would be great to avoid all these special cases, otherwise we may possibly introduce bugs because this class does not behave as per doctrine, but the tests pass because they make assumptions.

File: jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/transport/ResponseListenersTest.java [hunk 5]
```diff
@@ -85,65 +86,127 @@ public void run()
...
+                public void run()
+                {
+                    Content.Chunk chunk = source.read();
+                    chunks.add(chunk);
+                    if (chunk == null)
+                    {
+                        source.demand(this);
+                        return;
+                    }
+                    chunk.release();
```
Comment (sbordet) [inline jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/transport/ResponseListenersTest.java]: This release should not be done, as the chunk is stored for later use, as per doctrine.

File: jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/transport/ResponseListenersTest.java [hunk 6]
```diff
@@ -85,65 +86,127 @@ public void run()
...
+        assertThat(chunks.get(1).getByteBuffer().get(), is((byte)1));
+        assertThat(chunks.get(1).isLast(), is(false));
+        assertThat(chunks.get(2).getByteBuffer().get(), is((byte)2));
+        assertThat(chunks.get(2).isLast(), is(false));
+        assertThat(chunks.get(3).getByteBuffer().get(), is((byte)2));
+        assertThat(chunks.get(3).isLast(), is(false));
+        assertThat(Content.Chunk.isFailure(chunks.get(4), false), is(true));
+        assertThat(chunks.get(4).getFailure(), instanceOf(TimeoutException.class));
+        assertThat(Content.Chunk.isFailure(chunks.get(5), true), is(true));
+        assertThat(chunks.get(5).getFailure(), instanceOf(NumberFormatException.class));
```
Comment (sbordet) [inline jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/transport/ResponseListenersTest.java:150]: This is a bit unexpected. I would have expected (4 -> transient failure), (5 -> transient failure), (6 -> terminal failure), (7 -> terminal failure).

Is it a glitch of the test?

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 7]
```diff
@@ -407,7 +407,13 @@ public Content.Source newContentSource()
                 // because the content sources may not be read, or their chunks could be
                 // further retained, so those chunks must not be linked to the original ones.
                 List<Content.Chunk> chunks = content.stream()
-                    .map(chunk -> Content.Chunk.from(chunk.getByteBuffer().slice(), chunk.isLast()))
+                    .map(chunk ->
+                    {
+                        // TODO is this a reliable way to duplicate a chunk while eventually severing it from its retainable?
+                        if (Content.Chunk.isFailure(chunk))
+                            return chunk;
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:413]: Move this to a `filter()` call.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 8]
```diff
@@ -407,7 +407,13 @@ public Content.Source newContentSource()
                 // because the content sources may not be read, or their chunks could be
                 // further retained, so those chunks must not be linked to the original ones.
                 List<Content.Chunk> chunks = content.stream()
-                    .map(chunk -> Content.Chunk.from(chunk.getByteBuffer().slice(), chunk.isLast()))
+                    .map(chunk ->
+                    {
+                        // TODO is this a reliable way to duplicate a chunk while eventually severing it from its retainable?
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Remove TODO

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java [hunk 9]
```diff
@@ -759,8 +765,13 @@ public Content.Chunk read()
                 case CONTENT ->
                 {
                     Content.Chunk chunk = part.getContentSource().read();
-                    if (chunk == null || Content.Chunk.isFailure(chunk))
+                    if (chunk == null)
+                        yield null;
+                    if (Content.Chunk.isFailure(chunk, true))
+                    {
+                        errorChunk = chunk;
```
Comment (sbordet) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: `errorChunk` should be set holding the lock.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java [hunk 10]
```diff
@@ -95,6 +95,11 @@ public static void copy(Source source, Sink sink, Chunk.Processor chunkProcessor
 
     /**
      * <p>A source of content that can be read with a read/demand model.</p>
+     * <p>To avoid leaking its resources, a source <b>must</b> either:</p>
+     * <ul>
+     * <li>be read until it returns the {@link Chunk#isLast() last chunk}</li>
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]:
```suggestion
     * <li>be read until it returns a {@link Chunk#isLast() last chunk}, either EOF or a terminal failure</li>
```

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceCompletableFuture.java [hunk 11]
```diff
@@ -83,9 +85,17 @@ public void parse()
...
+                if (chunk.isLast())
+                {
+                    completeExceptionally(chunk.getFailure());
+                }
+                else
+                {
+                    if (onTransientFailure(chunk.getFailure()))
+                        continue;
+                    completeExceptionally(chunk.getFailure());
+                    _content.fail(chunk.getFailure());
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceCompletableFuture.java]: These 2 lines should be swapped, as we want to notify the CF last, because it can act before we failed `_content`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourcePublisher.java [hunk 12]
```diff
@@ -129,6 +129,8 @@ private void process()
                 {
                     terminate();
                     subscriber.onError(chunk.getFailure());
+                    if (!chunk.isLast())
+                        content.fail(chunk.getFailure());
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourcePublisher.java]: I'd swap these lines and notify the `subscriber` as last, as it can act before the content is failed.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentCopier.java [hunk 13]
```diff
@@ -61,14 +61,7 @@ protected Action process() throws Throwable
...
         if (Content.Chunk.isFailure(current))
-        {
-            if (current.isLast())
-                throw current.getFailure();
-            if (LOG.isDebugEnabled())
-                LOG.debug("ignored transient failure", current.getFailure());
-            succeeded();
-            return Action.SCHEDULED;
-        }
+            throw current.getFailure();
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentCopier.java:64]: If the read a transient failure, I think we should behave as if we read `null` for the goal of copying.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceByteBuffer.java [hunk 14]
```diff
@@ -47,6 +47,8 @@ public void run()
             if (Content.Chunk.isFailure(chunk))
             {
                 promise.failed(chunk.getFailure());
+                if (!chunk.isLast())
+                    source.fail(chunk.getFailure());
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceByteBuffer.java:51]: This is reading and accumulating into a single BB.
If we have a transient failure, should we not just continue as if we read `null`?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceString.java [hunk 15]
```diff
@@ -45,6 +45,8 @@ public void convert()
             if (Content.Chunk.isFailure(chunk))
             {
                 promise.failed(chunk.getFailure());
+                if (!chunk.isLast())
+                    content.fail(chunk.getFailure());
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceString.java:49]: Ditto.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceConsumer.java [hunk 16]
```diff
@@ -44,6 +44,8 @@ public void run()
             if (Content.Chunk.isFailure(chunk))
             {
                 callback.failed(chunk.getFailure());
+                if (!chunk.isLast())
+                    source.fail(chunk.getFailure());
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceConsumer.java:48]: Ditto.

File: jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/TestSource.java [hunk 17]
```diff
@@ -0,0 +1,109 @@
...
+
+package org.eclipse.jetty.io;
+
+import java.nio.ByteBuffer;
+import java.util.Arrays;
+import java.util.List;
+import java.util.Queue;
+import java.util.concurrent.ConcurrentLinkedQueue;
+
+public class TestSource implements Content.Source
```
Comment (sbordet) [inline jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/TestSource.java]: Same comment as for the duplicate in `jetty-client`.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 18]
```diff
@@ -432,34 +422,20 @@ else if (ExceptionUtil.areNotAssociated(_failure.getFailure(), x) && _failure.ge
...
-                ChannelRequest request = _request;
-                Runnable invokeOnFailureListeners = () ->
-                {
-                    Consumer<Throwable> onFailure;
-                    try (AutoLock ignore = _lock.lock())
-                    {
-                        onFailure = _onFailure;
-                    }
 
+                Consumer<Throwable> onFailure = _onFailure;
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:426]: Field `_onFailure` should be read with the lock held.
Also, not sure we want to read it here, it's too early. We only want it when we execute its runnable (and previous runnables may generate errors).

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java [hunk 19]
```diff
@@ -432,34 +422,20 @@ else if (ExceptionUtil.areNotAssociated(_failure.getFailure(), x) && _failure.ge
...
                         ExceptionUtil.addSuppressedIfNotAssociated(x, throwable);
                     }
-
-                    // If the application has not been otherwise informed of the failure
-                    if (invokeOnContentAvailable == null && invokeWriteFailure == null && onFailure == null)
-                    {
-                        if (LOG.isDebugEnabled())
-                            LOG.debug("failing callback in {}", this, x);
-                        request._callback.failed(x);
-                    }
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:462]: Is it correct that this block has been removed?

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java [hunk 20]
```diff
@@ -1094,7 +1094,17 @@ public void earlyEOF()
                 BadMessageException bad = new BadMessageException("Early EOF");
 
                 if (Content.Chunk.isFailure(stream._chunk))
-                    stream._chunk.getFailure().addSuppressed(bad);
+                {
+                    if (stream._chunk.isLast())
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Assign `stream._chunk` to a local variable for better readability.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/TestSource.java [hunk 21]
```diff
@@ -0,0 +1,111 @@
...
+
+import java.nio.ByteBuffer;
+import java.util.Arrays;
+import java.util.List;
+import java.util.Queue;
+import java.util.concurrent.ConcurrentLinkedQueue;
+
+import org.eclipse.jetty.io.Content;
+
+public class TestSource implements Content.Source
```
Comment (sbordet) [inline jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/TestSource.java]: Gosh, 3rd time :(
Can't we move these tests to a common place?

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java [hunk 22]
```diff
@@ -75,7 +76,10 @@ public boolean handle(Request request, Response response, Callback callback)
             {
 
                 if (listener)
+                {
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java:78]: Parameter `listener` can be either `true` or `false`, but this test is annotated with `@MethodSource("transportsAndTrueIdleTimeoutListeners")` which seems to indicate only `true`.
If the method-source name correct?

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java [hunk 23]
```diff
@@ -130,15 +134,13 @@ public boolean handle(Request request, Response response, Callback callback)
...
-        assertTrue(Content.Chunk.isFailure(chunk, true));
+        assertTrue(Content.Chunk.isFailure(chunk, false));
         Throwable cause = chunk.getFailure();
         assertThat(cause, instanceOf(TimeoutException.class));
 
-        /* TODO if transient timeout failures are supported then add this check
         // Can read again
         assertNull(requestRef.get().read());
-        */
+
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java:141]: Remove empty line.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java [hunk 24]
```diff
@@ -198,6 +200,7 @@ public void testIdleTimeoutErrorListenerReturnsFalseThenTrue(Transport transport
             public boolean handle(Request request, Response response, Callback callback)
             {
                 request.addIdleTimeoutListener(t -> error.getAndSet(t) != null);
+                request.addFailureListener(callback::failed);
```
Comment (sbordet) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java:199]: Please fix the comment before the asserts few lines below.
The first time the idle timeout listener returns `false`, not `true`.

File: jetty-ee10/jetty-ee10-proxy/src/main/java/org/eclipse/jetty/ee10/proxy/ProxyServlet.java [hunk 25]
```diff
@@ -260,6 +260,8 @@ public Content.Chunk read()
             if (Content.Chunk.isFailure(chunk))
             {
                 onClientRequestFailure(request, proxyRequest, response, chunk.getFailure());
+                if (!chunk.isLast())
+                    super.fail(chunk.getFailure(), true);
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-proxy/src/main/java/org/eclipse/jetty/ee10/proxy/ProxyServlet.java]: I'd swap the lines.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java [hunk 26]
```diff
@@ -292,10 +304,9 @@ private Content.Chunk produceChunk()
                         LOG.debug("channel has no new chunk {}", this);
                     return null;
                 }
-                else
-                {
-                    _servletChannel.getServletRequestState().onContentAdded();
-                }
+                _servletChannel.getServletRequestState().onContentAdded();
+                if (Content.Chunk.isFailure(_chunk, false))
+                    return _chunk;
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java]: Would be great if we can fold this logic into the existing one above.
Can we call `continue;` here to loop around and execute the logic at the top?
This would get rid of the duplicated logic below this code.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducer.java [hunk 27]
```diff
@@ -149,19 +149,18 @@ public boolean onContentProducible()
         // This is why this method always returns false.
         // But async errors can occur while the dispatched thread is NOT blocked reading (i.e.: in state WAITING),
         // so the WAITING to WOKEN transition must be done by the error-notifying thread which then has to reschedule
-        // the dispatched thread after HttpChannelState.asyncError() is called.
+        // the dispatched thread.
         // Calling _asyncContentProducer.onContentProducible() changes the channel state from WAITING to WOKEN which
-        // would prevent the subsequent call to HttpChannelState.asyncError() from rescheduling the thread.
-        // AsyncServletTest.testStartAsyncThenClientStreamIdleTimeout() tests this.
+        // would prevent the async error thread from noticing that a redispatching is needed.
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducer.java:154]: This paragraph seems to be outdated? We do not call `_asyncContentProducer.onContentProducible()` below.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducer.java [hunk 28]
```diff
@@ -149,19 +149,18 @@ public boolean onContentProducible()
...
         if (LOG.isDebugEnabled())
             LOG.debug("onContentProducible releasing semaphore {} unready={}", _semaphore, unready);
         // Do not release the semaphore if we are not unready, as certain protocols may call this method
         // just after having received the request, not only when they have read all the available content.
         if (unready)
         {
-            // Call nextChunk() to switch the input state back to IDLE, otherwise we would stay UNREADY.
-            _asyncContentProducer.nextChunk();
+            // Switch the input state back to IDLE, otherwise we would stay UNREADY.
+            _asyncContentProducer.getServletChannel().getServletRequestState().onReadIdle();
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducer.java:163]: Is this ok? Seems weird because the async version calls `onReadReady()` which seems more appropriate for this event.
If it is ok, needs additional comments as to why we go idle rather than ready.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpInput.java [hunk 29]
```diff
@@ -42,8 +41,8 @@ public class HttpInput extends ServletInputStream implements Runnable
     private final ServletChannel _servletChannel;
     private final ServletChannelState _channelState;
     private final byte[] _oneByteBuffer = new byte[1];
-    private final BlockingContentProducer _blockingContentProducer;
-    private final AsyncContentProducer _asyncContentProducer;
+    final BlockingContentProducer _blockingContentProducer;
+    final AsyncContentProducer _asyncContentProducer;
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/HttpInput.java:45]: Not a big fan, see below.

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducerTest.java [hunk 30]
```diff
@@ -0,0 +1,208 @@
...
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.equalTo;
+import static org.hamcrest.Matchers.instanceOf;
+import static org.hamcrest.Matchers.is;
+import static org.hamcrest.Matchers.lessThanOrEqualTo;
+import static org.hamcrest.Matchers.notNullValue;
+import static org.hamcrest.Matchers.nullValue;
+import static org.junit.jupiter.api.Assertions.fail;
+
+public class AsyncContentProducerTest extends AbstractContentProducerTest
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducerTest.java:39]: Not a big fan of these tests, as they require a framework to run (base test class + mocks), a 9 parameters method, and only test some parts (the content producers) but not others (httpinput).

Can we rewrite these in a simpler way, as they don't seem to test anything specific just some normal content cases (e.g. content no eof, content with eof, content with failure, etc.).

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducerTest.java [hunk 31]
```diff
@@ -0,0 +1,184 @@
...
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.equalTo;
+import static org.hamcrest.Matchers.instanceOf;
+import static org.hamcrest.Matchers.is;
+import static org.hamcrest.Matchers.lessThanOrEqualTo;
+import static org.hamcrest.Matchers.notNullValue;
+import static org.hamcrest.Matchers.nullValue;
+import static org.junit.jupiter.api.Assertions.fail;
+
+public class BlockingContentProducerTest extends AbstractContentProducerTest
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducerTest.java:36]: Ditto

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MockConnectionMetaData.java [hunk 32]
```diff
@@ -0,0 +1,132 @@
...
+import org.eclipse.jetty.io.Connection;
+import org.eclipse.jetty.io.EndPoint;
+import org.eclipse.jetty.server.ConnectionMetaData;
+import org.eclipse.jetty.server.Connector;
+import org.eclipse.jetty.server.HttpConfiguration;
+import org.eclipse.jetty.util.Attributes;
+import org.eclipse.jetty.util.HostPort;
+
+// TODO shared copy of this class
+public class MockConnectionMetaData extends Attributes.Mapped implements ConnectionMetaData
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MockConnectionMetaData.java:31]: Let's try to not use mocks.

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MockRequest.java [hunk 33]
```diff
@@ -0,0 +1,173 @@
...
+import org.eclipse.jetty.io.Content;
+import org.eclipse.jetty.server.Components;
+import org.eclipse.jetty.server.ConnectionMetaData;
+import org.eclipse.jetty.server.Context;
+import org.eclipse.jetty.server.HttpStream;
+import org.eclipse.jetty.server.Request;
+import org.eclipse.jetty.server.Session;
+import org.eclipse.jetty.server.TunnelSupport;
+
+public class MockRequest implements Request
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MockRequest.java:33]: Ditto.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/AbstractTest.java [hunk 34]
```diff
@@ -143,7 +146,16 @@ protected void prepareServer(Transport transport, HttpServlet servlet) throws Ex
...
+        jobFailures = new CopyOnWriteArrayList<>();
+        QueuedThreadPool serverThreads = new QueuedThreadPool()
+        {
+            @Override
+            protected void onJobFailure(Throwable x)
+            {
+                super.onJobFailure(x);
+                jobFailures.add(x);
+            }
+        };
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/AbstractTest.java]: This is so weird and only used in 1 test at the Servlet level, and not sure why we are checking the failures of thread pool jobs?

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/HttpClientContinueTest.java [hunk 35]
```diff
@@ -676,6 +678,56 @@ public void onComplete(Result result)
...
+                if (result.isFailed() && result.getResponse().getStatus() == HttpStatus.CONTINUE_100)
+                    clientLatch.countDown();
+            });
+
+        // Wait more than the idle timeout to break the connection.
+        Thread.sleep(2 * idleTimeout);
+
+        assertTrue(serverLatch.await(5, TimeUnit.SECONDS));
+        assertTrue(clientLatch.await(5, TimeUnit.SECONDS));
+        assertThat(jobFailures, empty());
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/HttpClientContinueTest.java]: Why this last assert? Seems way too far away in abstractions layers to be tested here.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/ServerTimeoutsTest.java [hunk 36]
```diff
@@ -463,7 +462,8 @@ protected void service(HttpServletRequest request, HttpServletResponse response)
                     @Override
                     public void onDataAvailable() throws IOException
                     {
-                        assertEquals(0, input.read());
+                        while (input.isReady())
+                            assertEquals(0, input.read());
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/ServerTimeoutsTest.java]: Why this? The client only sends 1 byte, we have been called in `onDataAvailable()` so when we read we must read 1 byte, as the previous code was doing.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/ServerTimeoutsTest.java [hunk 37]
```diff
@@ -648,19 +641,13 @@ public BlockingReadServlet(CountDownLatch handlerLatch)
...
-                input.read();
-            }
-            catch (IOException x)
-            {
-                handlerLatch.countDown();
-                throw x;
-            }
+            IOException x = assertThrows(IOException.class, input::read);
+            handlerLatch.countDown();
+            throw x;
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/ServerTimeoutsTest.java:663]: Nice!

File: jetty-ee9/jetty-ee9-proxy/src/main/java/org/eclipse/jetty/ee9/proxy/ProxyServlet.java [hunk 38]
```diff
@@ -260,6 +260,8 @@ public Content.Chunk read()
             if (Content.Chunk.isFailure(chunk))
             {
                 onClientRequestFailure(request, proxyRequest, response, chunk.getFailure());
+                if (!chunk.isLast())
+                    super.fail(chunk.getFailure());
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-proxy/src/main/java/org/eclipse/jetty/ee9/proxy/ProxyServlet.java]: Swap lines.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MockConnectionMetaData.java (hunk 32 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/MockConnectionMetaData.java:31]: I know mocks are not a good universal test strategy and sometimes they are used way too much and take too much effort and often test the mock rather than the class....
But sometimes there is vital code that you really want to explicitly test and there is now other way to create a unit test to check it.    By all means create an integration test as well to ensure the mock test is not a bad test, but I see no reason to not have some reasonable mock tests when appropriate.

I think we should be mock reluctant, but not mock-phobic.    If there is a way to do a unit test without a mock, let's do that.    But I don't think the solution should be to always turn a unit test into an integration test.   There is value it checking the contract of a component is implemented as we imagined.

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducerTest.java (hunk 30 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducerTest.java:39]: On the contrary, I am a big fan of these tests.   We have imagined a `ContentProducer` contract and these tests are checking that contract.   It may well be that `HttpInput` uses the `ContentProducers` differently, but then that is either an issue with the contract not being good enough or that `HttpInput` is not respecting the contract.

I think having these simple tests is definitely worth it.   But it does not mean we should not also test with `HttpInput`

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/ServerTimeoutsTest.java (hunk 36 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/ServerTimeoutsTest.java]: I think the idea was to check that both an `isReady` and a `read` could be done.    So it probably could have been done with an `if` rather than a `while`, but the `while` is the more natural style.

However, we should probably also have a test of a `read` without a prior `isReady` call (as it was before... we should test both).

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java (hunk 26 above)
Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java]: I think we can do the loop as @sbordet suggested.    However, when I tried it, I thought we should also be calling `Chunk.next(_chunk)` on the transient failure, but that breaks tests.     I thought that was our general pattern, so we need to comment why it does not apply here.     My code was:

```java
    private Content.Chunk produceChunk()
    {
        if (LOG.isDebugEnabled())
            LOG.debug("produceChunk() {}", this);

        while (true)
        {
            if (_chunk != null)
            {
                if (Content.Chunk.isFailure(_chunk, false))
                {
                    // TODO comment why these lines are not needed here:
                    // Content.Chunk chunk = _chunk;
                    // _chunk = Content.Chunk.next(chunk);
                    return _chunk;
                }
                if (_chunk.isLast() || _chunk.hasRemaining())
                {
                    if (LOG.isDebugEnabled())
                        LOG.debug("chunk not yet depleted, returning it {}", this);
                    return _chunk;
                }
                if (LOG.isDebugEnabled())
                    LOG.debug("current chunk depleted {}", this);
                _chunk.release();
                _chunk = null;
            }
            else
            {
                if (LOG.isDebugEnabled())
                    LOG.debug("reading new chunk {}", this);
                _chunk = readChunk();
                if (_chunk == null)
                {
                    if (LOG.isDebugEnabled())
                        LOG.debug("channel has no new chunk {}", this);
                    return null;
                }
                _servletChannel.getServletRequestState().onContentAdded();
            }
        }
    }
```

Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducer.java]: Ah - I have answered my own question:  `produceChunk()` may be called by `available()` and `isReady()`, which do not consume the chunk, so we cannot move to the next chunk here. Only in `nextChunk()` should we move to the next chunk.   I'll commit my code changes.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducer.java (hunk 28 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducer.java:163]: The `READY` input state is meaningless in blocking mode: it means data has arrived and we may have to redispatch the request. But in blocking mode, we know that if are in input state `UNREADY`, the request is blocked on the semaphore; there is no need to redispatch anything as releasing the semaphore is all you need to unblock the request.

This is what the two comment blocks in this method try to explain.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/HttpClientContinueTest.java (hunk 35 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/HttpClientContinueTest.java]: This was the only half-sane way I found to create a reliable reproducer for the problem initially reported in #10357. I added this test as part of PR #10814 upon which this PR is based.

I detailed the actual problem here: https://github.com/jetty/jetty.project/issues/10357#issuecomment-1786824936 and discussed with @gregw here: https://github.com/jetty/jetty.project/pull/10801#discussion_r1376991169

It's not directly related to the transient failures, but it's part of the family of problems for which transient failures are a piece of the puzzle.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/ServerTimeoutsTest.java (hunk 36 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/ServerTimeoutsTest.java]: Let me add such test.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/AbstractTest.java (hunk 34 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/AbstractTest.java]: It's about https://github.com/jetty/jetty.project/issues/10357#issuecomment-1786824936, see below.

File: jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducerTest.java (hunk 30 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/test/java/org/eclipse/jetty/ee10/servlet/AsyncContentProducerTest.java:39]: `ContentProducer`s are not as testable independently as I wish they should be, but those tests have assertions that would be very complicated to replicate with integration tests.

I think they're a reasonable compromise.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducer.java (hunk 27 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/BlockingContentProducer.java:154]: It's what the comment is about: calling `_asyncContentProducer.onContentProducible()` is wrong as the dispatching logic is very different between blocking and async.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java (hunk 22 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java:78]: `transportsAndTrueIdleTimeoutListeners` does provide both `true` and `false` as `listener` values but its name is indeed confusing.

Let me rename it.

File: jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/TestSource.java (hunk 21 above)
Comment (lorban) [reply jetty-core/jetty-server/src/test/java/org/eclipse/jetty/server/TestSource.java]: Unfortunately, we don't want this class anywhere in the production code, we don't want to productize it and there is no easy way to share a test util class...

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 18 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:426]: AFAICT, this code is within the context of a lock.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceByteBuffer.java (hunk 14 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceByteBuffer.java:51]: That would silently ignore idle timeouts, which I think isn't a reasonable default. We could eventually add a mechanism that allows taking decisions on what to do with failures, but that's outside the scope of this PR.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceString.java (hunk 15 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceString.java:49]: Same answer.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceConsumer.java (hunk 16 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentSourceConsumer.java:48]: Same answer.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentCopier.java (hunk 13 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/internal/ContentCopier.java:64]: I disagree as that would silently ignore idle timeouts.

File: jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/transport/ResponseListenersTest.java (hunk 6 above)
Comment (lorban) [reply jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/transport/ResponseListenersTest.java:150]: No, it's an actual glitch in the implementation as failing a multiplexed content source mistakenly replaces its `ALREADY_READ_CHUNK` with the failure chunk. Let me fix this.

File: jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/transport/ResponseListenersTest.java (hunk 5 above)
Comment (lorban) [reply jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/transport/ResponseListenersTest.java]: You're right, let me fix this.

File: jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/TestSource.java (hunk 4 above)
Comment (lorban) [reply jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/TestSource.java]: `TestSource` can inject null reads, which I do not think we want in any production-ready content source impl. But you're right that it should respect the doctrine, even if it's a test class.

Let me fix this.

File: jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/AsyncContentListenerTest.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-client/src/test/java/org/eclipse/jetty/client/AsyncContentListenerTest.java:50]: Let me fix this.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 8 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Did we give up on the idea of trailer chunks, and other kind of non-content, non-failure, non-EOF, non-EMPTY chunks?

If we did, this comment can go away, otherwise this code won't correctly duplicate the chunk.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 7 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java:413]: Once the TODO below is resolved, yes, I can do that.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java (hunk 9 above)
Comment (lorban) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/MultiPart.java]: Good catch, but the fact that the lock only protects a subset of the fields (`errorChunk` but not `part` nor `state`) is confusing and should be documented. But that's a job for another PR.

Let me add the lock.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceCompletableFuture.java (hunk 11 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceCompletableFuture.java]: Done.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourcePublisher.java (hunk 12 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourcePublisher.java]: Done.

File: jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/TestSource.java (hunk 17 above)
Comment (lorban) [reply jetty-core/jetty-io/src/test/java/org/eclipse/jetty/io/TestSource.java]: Not sure what do do here.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java (hunk 19 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java:462]: Yes, it's part of the change that `testAsyncReadHttpIdleTimeoutOverridesIdleTimeout` covers, see the big TODO that was removed from that test.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java (hunk 20 above)
Comment (lorban) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpConnection.java]: Done.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java (hunk 23 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java:141]: Done.

File: jetty-ee10/jetty-ee10-proxy/src/main/java/org/eclipse/jetty/ee10/proxy/ProxyServlet.java (hunk 25 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-proxy/src/main/java/org/eclipse/jetty/ee10/proxy/ProxyServlet.java]: Done.

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java (hunk 24 above)
Comment (lorban) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ServerTimeoutsTest.java:199]: Done.

File: jetty-ee9/jetty-ee9-proxy/src/main/java/org/eclipse/jetty/ee9/proxy/ProxyServlet.java (hunk 38 above)
Comment (lorban) [reply jetty-ee9/jetty-ee9-proxy/src/main/java/org/eclipse/jetty/ee9/proxy/ProxyServlet.java]: Done.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/Response.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/Response.java:194]: @lorban I mean this:

```java
            try
            {
                onContent(response, chunk, () -> contentSource.demand(demandCallback));
                chunk.release();
            }
            catch (Throwable x)
            {
                chunk.release();
                response.abort(x);
                **contentSource.fail(x);**
            }
```

Comment (lorban) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/Response.java:194]: You're right, but this is a pre-existing bug. Let me fix it.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java (hunk 2 above)
Comment (lorban) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java]: You're right, let me rework this to minimize the changes.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java (hunk 10 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/Content.java]: Done.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java [hunk 39]
```diff
@@ -602,6 +607,12 @@ protected Content.Chunk transform(Content.Chunk inputChunk)
                 {
                     // The decoded ByteBuffer is a transformed "copy" of the
                     // compressed one, so it has its own reference counter.
+                    if (!decodedBuffer.canRetain())
```
Comment (sbordet) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java]: Can you invert the `if` so it's more readable.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/ResponseListeners.java [hunk 40]
```diff
@@ -679,10 +680,18 @@ public void fail(Throwable failure)
...
+                    ExceptionUtil.addSuppressedIfNotAssociated(cause, failure);
+                }
+                else
+                {
+                    if (currentChunk != null && currentChunk != ALREADY_READ_CHUNK)
+                        currentChunk.release();
+                    this.chunk = Content.Chunk.from(failure);
+                }
                 onDemandCallback();
                 registerFailure(this, failure);
```
Comment (sbordet) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/ResponseListeners.java]: I think the 2 calls should be swapped.
If not, needs a comment why this order is the way it is.

File: documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/ContentDocs.java [hunk 41]
```diff
@@ -54,13 +54,33 @@ public void read(Content.Source source)
...
+                // If there is a fatal failure reading, handle it.
+                if (Content.Chunk.isFailure(chunk, true))
                 {
-                    handleFailure(chunk.getFailure());
+                    handleFatalFailure(chunk.getFailure());
                     return;
                 }
 
+                // If there is a transient failure reading, handle it.
+                if (Content.Chunk.isFailure(chunk, false))
```
Comment (sbordet) [inline documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/ContentDocs.java]: I prefer a single `if` for the failure case, and explicit variables, e.g. `var transientFailure = !chunk.isLast()`.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ChunksContentSource.java [hunk 42]
```diff
@@ -60,18 +75,16 @@ public long getLength()
...
             if (iterator == null)
                 iterator = chunks.iterator();
-            if (!iterator.hasNext())
-                return terminated = Content.Chunk.EOF;
             chunk = iterator.next();
-            last = !iterator.hasNext();
-            if (last)
+            if (chunk != null && chunk.isLast())
+                terminated = chunk;
+            if (terminated == null && !iterator.hasNext())
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ChunksContentSource.java]: Don't want to remember as `terminated` a "normal" chunk that has bytes _and_ is last.
Can we use here `Chunk.next()`?

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/ResponseListeners.java (hunk 40 above)
Comment (lorban) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/ResponseListeners.java:696]: Done.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java (hunk 39 above)
Comment (lorban) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpReceiver.java]: Done.

File: documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/ContentDocs.java (hunk 41 above)
Comment (lorban) [reply documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/ContentDocs.java]: Done.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ChunksContentSource.java (hunk 42 above)
Comment (lorban) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ChunksContentSource.java]: Yes, this should be:
```java
terminated = Content.Chunk.next(chunk);
```
Done.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/ResponseListeners.java (hunk 40 above)
Comment (lorban) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/ResponseListeners.java]: Ok, swapped them.

File: jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/HttpClientContinueTest.java (hunk 35 above)
Comment (lorban) [reply jetty-ee10/jetty-ee10-tests/jetty-ee10-test-client-transports/src/test/java/org/eclipse/jetty/ee10/test/client/transport/HttpClientContinueTest.java]: After discussing this, we agreed to remove the assertion.

**Review by sbordet — APPROVED** [review]
