### PR TITLE
Issue #8353 - websocket automatic pong response frames

### LINKED ISSUE #8353: Automatic pongs should not be sent when connection is closed
**Jetty version(s)**
9.4.48.v20220622

**Java version/vendor**
Eclipse Adoptium OpenJDK Runtime Environment 11.0.15+10

**OS type/version**
Linux 5.4.0-122-generic (amd64)

**Description**
We observe that Jetty websocket client automatically replies to pings with pongs, even though the channel has already been closed in the meantime. In this scenario, we expect that no pong should be sent.

```
java.nio.channels.ClosedChannelException	
    at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue (SourceFile:109)	
    at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame (SourceFile:579)	
    at org.eclipse.jetty.websocket.client.io.WebSocketClientConnection.outgoingFrame (SourceFile:58)	
    at org.eclipse.jetty.websocket.common.extensions.ExtensionStack$Flusher.process (SourceFile:403)	
    at org.eclipse.jetty.util.IteratingCallback.processing (SourceFile:241)	
    at org.eclipse.jetty.util.IteratingCallback.iterate (SourceFile:223)	
    at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.outgoingFrame (SourceFile:280)	
    at org.eclipse.jetty.websocket.common.WebSocketSession.outgoingFrame (SourceFile:360)	
    at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame (SourceFile:322)	
    at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendAsyncFrame (SourceFile:243)	
    at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendPong (SourceFile:386)	
    at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame (SourceFile:133)	
    at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame (SourceFile:326)	
    at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame (SourceFile:202)	
    at org.eclipse.jetty.websocket.common.Parser.notifyFrame (SourceFile:225)	
    at org.eclipse.jetty.websocket.common.Parser.parseSingleFrame (SourceFile:259)	
    at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable (SourceFile:459)	
    at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable (SourceFile:440)	
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (SourceFile:311)	
    at org.eclipse.jetty.io.FillInterest.fillable (SourceFile:105)	
    at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable (SourceFile:555)	
    at org.eclipse.jetty.io.ssl.SslConnection.onFillable (SourceFile:410)	
    at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded (SourceFile:164)	
    at org.eclipse.jetty.io.FillInterest.fillable (SourceFile:105)	
    at org.eclipse.jetty.io.ChannelEndPoint$1.run (SourceFile:104)	
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask (SourceFile:338)	
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce (SourceFile:315)	
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce (SourceFile:173)	
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run (SourceFile:131)	
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run (SourceFile:409)	
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (SourceFile:883)	
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run (SourceFile:1034)	
    at java.lang.Thread.run (Thread.java:829)
```

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Closes #8353

- Pay attention to the callback to the ping frame (do not demand until response pong frame has been sent).

### CODE REVIEW

File: jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandler.java [hunk 1]
```diff
@@ -596,10 +587,24 @@ private void acceptMessage(Frame frame, Callback callback)
 
     public void onPing(Frame frame, Callback callback)
     {
-        ByteBuffer payload = BufferUtil.copy(frame.getPayload());
-        coreSession.sendFrame(new Frame(OpCode.PONG).setPayload(payload), Callback.NOOP, false);
-        callback.succeeded();
-        coreSession.demand(1);
+        if (coreSession.isOutputOpen())
```
Comment (sbordet) [inline jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandler.java]: This check is racy anyway, as you can receive a ping in any moment while the application is writing, possibly asynchronously, and the write could fail anyway, as the output may already be shutdown.

File: jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandler.java [hunk 2]
```diff
@@ -596,10 +587,24 @@ private void acceptMessage(Frame frame, Callback callback)
...
+            ByteBuffer payload = BufferUtil.copy(frame.getPayload());
+            coreSession.sendFrame(new Frame(OpCode.PONG).setPayload(payload), Callback.from(() ->
+            {
+                callback.succeeded();
+                coreSession.demand(1);
+            }, t ->
+            {
+                callback.failed(t);
+                coreSession.demand(1);
+            }), false);
```
Comment (sbordet) [inline jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandler.java]: There is a `Callback.from()` method that takes a `Callback` and a `Runnable` that is run afterwards.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java [hunk 3]
```diff
@@ -365,16 +351,37 @@ private void onPingFrame(Frame frame, Callback callback)
...
+            callback.succeeded();
+            demand();
         }
         else
         {
-            // Automatically respond
-            ByteBuffer payload = BufferUtil.copy(frame.getPayload());
-            getSession().getRemote().sendPong(payload, WriteCallback.NOOP);
+            // Automatically respond if output is open.
+            if (coreSession.isOutputOpen())
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java]: Same concern about checking for the output in an input method (`onPingFrame()`).

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandler.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandler.java]: Its not racy because we won't receive any new frames until we demand from the coreSession, and we don't demand until the write succeeds.

Comment (sbordet) [reply jetty-websocket/websocket-javax-common/src/main/java/org/eclipse/jetty/websocket/javax/common/JavaxWebSocketFrameHandler.java]: In case of idle timeouts you have demand and the idle timeout fires and closes the output, as you send a Close frame but typically keep the input open to wait for the reply.

Also, if you received a message and give it to the application, the application could have spawned a thread so that you have demand again. At any moment the application can decide to close from the spawned thread.

Both not possible?

**Comment by joakime** [comment]
@lachlan-roberts you have at least 11 checkstyle errors to fix in this PR

**Review by sbordet — APPROVED** [review]
