### PR TITLE
Issue #4329 - Fixing RuleContainer to handle path parameters

### LINKED ISSUE #4329: rewrite prevents URL session tracking.
**Jetty version**
9.4.23
**Java version**
any
**OS type/version**
any
**Description**

The rewrite rules as configured for the demo webapp in a jetty distribution remove URI parameters so that session tracking by URI does not work.
Ideally rewrite should be able to be used without preventing URL session tracking.... even if it has to be a special rule to extract and remember the jsessionid somehow.

### PR DESCRIPTION
**Pull request by joakime**
+ Introducing HttpURI.setParam(String)
+ Updating DemoBaseTest.testSessionDump() to follow expected behavior

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

Closes #4329

### CODE REVIEW

File: tests/test-webapps/test-jetty-webapp/src/main/java/com/acme/SessionDump.java [hunk 1]
```diff
@@ -124,6 +124,7 @@ public void doGet(HttpServletRequest request,
         }
         catch (IllegalStateException e)
         {
+            e.printStackTrace(System.err);
```
Comment (gregw) [inline tests/test-webapps/test-jetty-webapp/src/main/java/com/acme/SessionDump.java]: probably should use servletContext.log rather than System.err

File: jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RuleContainer.java [hunk 2]
```diff
@@ -185,7 +187,18 @@ protected String apply(String target, HttpServletRequest request, HttpServletRes
...
                     else
-                        baseRequest.setURIPathQuery(encoded);
+                    {
+                        String uriPathQuery = encoded;
+                        HttpURI baseUri = baseRequest.getHttpURI();
+                        // Copy path params from original URI if present
+                        if ((baseUri != null) && StringUtil.isNotBlank(baseUri.getParam()))
+                        {
+                            HttpURI uri = new HttpURI(uriPathQuery);
+                            uri.setParam(baseUri.getParam());
```
Comment (gregw) [inline jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RuleContainer.java:197]: We should probably note that our path param handling is fundamentally flawed in that we only handle parameters on the last segment of a path.... the spec allows `/foo;param1=value/bar;param2=value` but we don't handle that and I think the complexity of doing so in a rewrite scenario would be significant.

**Review by gregw — APPROVED** [review]
LGTM other than some minor quibbles

File: jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RuleContainer.java (hunk 2 above)
Comment (joakime) [reply jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RuleContainer.java:197]: I'm also wondering if we should limit this reinsertion of the parameters to only `jsesssionid`?
But if we do that, then we need to hook into the Session configuration stuff to know what that session keyname is.

Comment (joakime) [reply jetty-rewrite/src/main/java/org/eclipse/jetty/rewrite/handler/RuleContainer.java:197]: The closed issue #430 had some issues with this as well.
So I'm currently leaning towards not restricting it.

But in your example ... `/foo;param1=value/bar;param2=value`
The `HttpURI` parsing will parse that as the path = `/foo` and the param = `;param1=value/bar;param2=value` (ew!)
