### PR TITLE
Jetty 9.4.x unconsumed content2

### LINKED ISSUE #6168: Improve handling of unconsumed content
**Jetty version**
9.4.x

**Description**
The case of unconsumed content, and `HttpInput.Interceptor` throwing an exception, should be handled better.
In particular, make sure that exceptions thrown by the interceptor are correctly handled.

### PR DESCRIPTION
**Pull request by sbordet**
Improved behavior in case of HttpInput.Interceptor throwing.

### CODE REVIEW

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java [hunk 1]
```diff
@@ -354,11 +359,14 @@ private int fillRequestBuffer()
...
             {
-                LOG.debug(e);
+                if (LOG.isDebugEnabled())
+                    LOG.debug(e);
                 _parser.atEOF();
                 return -1;
             }
         }
+
+        // TODO: must return _requestBuffer.remaining()!
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java]: Can you explain this TODO more?

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java [hunk 2]
```diff
@@ -295,6 +295,14 @@ else if (filled < 0)
...
             }
         }
+        catch (Throwable x)
+        {
+            if (LOG.isDebugEnabled())
+                LOG.debug("{} caught exception {}", this, _channel.getState(), x);
+            BufferUtil.clear(_requestBuffer);
+            releaseRequestBuffer();
+            close();
+        }
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java:305]: This is the only one of the new catch clauses  added that does not actually pass on the caught exception.
So perhaps add a comment saying why the close is enough... Actually, why are we not calling `getEndPoint().close(x);` ??

**Review by gregw — DISMISSED** [review]
The core of this fix is good.
I remain very cautious about the extra catch blocks and have included some niggles.
I think we have more work to do even after  merging this one to proactively explore the error space more.  So please open another issue, which together with @lachlan-roberts work on interceptors,  will explore the error issues more.

**Review by lorban — DISMISSED** [review]
LGTM

**Comment by sbordet** [comment]
@gregw opened #6167.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java (hunk 1 above)
Comment (sbordet) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java]: It was a leftover.

File: jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java (hunk 2 above)
Comment (sbordet) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java:305]: Because there is no such method `EndPoint.close(Throwable)` in 9.4.x (it's only in 10).

Comment (gregw) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java:305]: @lachlan-roberts @lorban can you fix in 10 to pass the throwable to close in your work on #6167

Comment (lorban) [reply jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java:305]: @gregw will do.
