### PR TITLE
Issue #5150 - Infinite connection timeout support in ManagedSelector

### LINKED ISSUE #5150: Zero connection timeout is not supported in HTTP client with non-blocking connect
Jetty version: `org.eclipse.jetty:jetty-client:9.4.30.v20200611`
Java version: `1.8`
OS: `Windows 10`

I am trying to set infinite connection timeout in `HttpClient` by setting it's connection timeout to zero value. The setting does makes connection timeout infinite in blocking mode (`HttpClient.setConnectBlocking(true)`) and makes connections fail with timeout exception in non-blocking mode (`HttpClient.setConnectBlocking(true)`).

Example:
```java
HttpClient client = new HttpClient();
client.setConnectBlocking(false);
client.setConnectTimeout(0);
client.newRequest(...).send(); // fails with SocketTimeoutException()
```

The reason seems to be no special handling for zero value in `ManagedSelector.Connect` constructor, see https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java#L892

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #5150 
`ManagedSelector` never timeouts connection in case connection timeout is set to zero.

### CODE REVIEW

**Comment by joakime** [comment]
Thank you for the pull request.

But we need to satisfy the requirements of Eclipse Legal in order to accept / merge this pull request.

The Eclipse Foundation ECA validation has failed for the commits on this pull request.

See the "Details" link on the `eclipsefdn/eca` check to know what you have failed to do.

See also https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/CONTRIBUTING.md#eclipse-contributor-agreement

**Comment by olegmoz** [comment]
@joakime thanks, I have signed-off the commit

**Review by joakime — APPROVED** [review]
LGTM.

@sbordet you should review this too.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java [hunk 1]
```diff
@@ -888,7 +888,11 @@ public String toString()
         {
             this.channel = channel;
             this.attachment = attachment;
-            this.timeout = ManagedSelector.this._selectorManager.getScheduler().schedule(this, ManagedSelector.this._selectorManager.getConnectTimeout(), TimeUnit.MILLISECONDS);
+            final long timeout = ManagedSelector.this._selectorManager.getConnectTimeout();
```
Comment (sbordet) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ManagedSelector.java]: Please remove `final`, not necessary.

**Review by sbordet — CHANGES_REQUESTED** [review]
Can you please update the javadocs for `HttpClient.setConnectionTimeout()` and `HttpClient.getConnectTimeout()`, adding that the value `0` means infinite timeout?
Other than that looks good.

**Comment by olegmoz** [comment]
@sbordet thanks, removed `final` and updated the javadocs. Please review

**Review by sbordet — APPROVED** [review]
