### PR TITLE
Fixes #10211 - NPE in ArrayByteBufferPool.findOldestEntry()

### LINKED ISSUE #10211: NPE in ArrayByteBufferPool.findOldestEntry()
**Jetty version(s)**
10+

**Description**

Below the stack trace in 12, but I think the problem may happen in 10/11 too.

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.ArrayByteBufferPool$Buffer.getLastNanoTime()" because the return value of "org.eclipse.jetty.util.Pool$Entry.getPooled()" is null
        at org.eclipse.jetty.io.ArrayByteBufferPool.lambda$findOldestEntry$6(ArrayByteBufferPool.java:440)
        at java.base/java.util.Comparator.lambda$comparingLong$6043328a$1(Comparator.java:515)
        at java.base/java.util.function.BinaryOperator.lambda$maxBy$1(BinaryOperator.java:74)
        at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
        at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:698)
        at org.eclipse.jetty.io.ArrayByteBufferPool.findOldestEntry(ArrayByteBufferPool.java:440)
        at org.eclipse.jetty.io.ArrayByteBufferPool.evict(ArrayByteBufferPool.java:393)
        at org.eclipse.jetty.io.ArrayByteBufferPool.releaseExcessMemory(ArrayByteBufferPool.java:370)
        at org.eclipse.jetty.io.ArrayByteBufferPool.acquire(ArrayByteBufferPool.java:207)
        at org.eclipse.jetty.http2.HTTP2Connection$NetworkBuffer.<init>(HTTP2Connection.java:500)
        at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.acquireNetworkBuffer(HTTP2Connection.java:401)
        at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:338)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:512)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:258)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)
        at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:211)
        at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:158)
        at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:449)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.onFillable(SslConnection.java:554)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:373)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:1623)
```

### PR DESCRIPTION
**Pull request by sbordet**
Fixed algorithm to check for oldest entry to avoid NPE. Added comments for clarity.

### CODE REVIEW

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java [hunk 1]
```diff
@@ -390,13 +392,14 @@ private void evict(boolean direct, long excess)
 
                 if (oldestEntry.remove())
                 {
-                    int clearedCapacity = oldestEntry.getPooled().capacity();
+                    RetainableByteBuffer buffer = oldestEntry.getPooled();
+                    int clearedCapacity = buffer.capacity();
```
Comment (joakime) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:396]: Is it possible for `oldestEntry.getPooled()` to return null?

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java [hunk 2]
```diff
@@ -382,6 +382,8 @@ private void evict(boolean direct, long excess)
 
         while (totalClearedCapacity < excess)
         {
+            // Run through all the buckets to avoid removing
+            // the buffers only from the first bucket(s).
             for (RetainedBucket bucket : buckets)
             {
                 RetainedBucket.Entry oldestEntry = findOldestEntry(now, bucket);
```
Comment (joakime) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:389]: What if there are no buffers? (possibly because of threading)  wouldn't findOldestEntry return null?

Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:389]: yes, but that is fine, the caller will loop around and see that is is smaller than max size and exit loop

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java [hunk 3]
```diff
@@ -430,19 +433,23 @@ public void dump(Appendable out, String indent) throws IOException
...
-                    oldestEntry = entry;
-            }
-            else
-            {
-                oldestEntry = entry;
-            }
+            RetainableByteBuffer buffer = entry.getPooled();
+            // Concurrently removed? Try next.
+            if (buffer == null)
+                continue;
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java]: I think returning here is probably better as the "oldest" calculation may now be wrong anyway after the concurrent access.
```suggestion
                return null;
```

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java [hunk 4]
```diff
@@ -430,19 +433,23 @@ public void dump(Appendable out, String indent) throws IOException
...
+            long age = NanoTime.elapsed(buffer.getLastUpdate(), now);
+            if (oldestBuffer != null && age < oldestAge)
+                continue;
+            oldestEntry = entry;
+            oldestBuffer = buffer;
+            oldestAge = age;
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java]: I prefer:
```suggestion
            if (oldestBuffer == null || age < oldestAge)
            {
                oldestEntry = entry;
                oldestBuffer = buffer;
                oldestAge = age;
            }
```

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java (hunk 2 above)
Comment (joakime) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:389]: If `findOldestEntry` returns null, the next line `oldestEntry.remove()` will NPE.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java (hunk 1 above)
Comment (sbordet) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:396]: No, `getPooled()` returns `null` only between `reserve()` and `enable()`.
The line before we won the race for `remove()` so we know the entry has been enabled.

**Review by gregw — COMMENTED** [review]
A couple of niggles, but I won't request changes in case I'm out of contact and can't approve any changes.  So I'm -0 as is, and +1 with the niggles fixed.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java (hunk 3 above)
Comment (sbordet) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java]: The comment is wrong, it is not a concurrent remove, but a case in between `reserve()` and `enable()`, so it's a very recent entry, so we still want to find the oldest.
Eventually, any entry that is found will have to go through an atomic `remove()`.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java (hunk 4 above)
Comment (sbordet) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java]: The loop tests for other conditions that when they are true mean "continue", so for consistency I would prefer keeping the "test and if true continue" blocks.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java [hunk 5]
```diff
@@ -430,19 +433,23 @@ public void dump(Appendable out, String indent) throws IOException
...
+            RetainableByteBuffer buffer = entry.getPooled();
+            // Reserved but not acquired yet? Try next.
+            if (buffer == null)
+                continue;
+            long age = NanoTime.elapsed(buffer.getLastUpdate(), now);
+            if (oldestBuffer != null && age < oldestAge)
+                continue;
+            oldestEntry = entry;
+            oldestBuffer = buffer;
+            oldestAge = age;
```
Comment (gregw) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java]: There you go... you can be both consistent and readable:
```suggestion
            if (buffer != null)
            {
                long age = NanoTime.elapsed(buffer.getLastUpdate(), now);
                if (oldestBuffer == null || age > oldestAge)
                {
                    oldestEntry = entry;
                    oldestBuffer = buffer;
                    oldestAge = age;
                }
            }
```

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java (hunk 2 above)
Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:389]: in 12 there is a null check in the calling loop.  We should put that in 10/11 as well.

Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:389]: @joakime there is an null check in the next line below

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java (hunk 3 above)
Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java]: OK... I still think that return null would be better.... but no harm continuing either.

**Review by gregw — DISMISSED** [review]
One niggle left, but I'll approve anyway

**Comment by gregw** [comment]
@sbordet ... and we should add tests for this... but in another later PR is fine

File: jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java [hunk 6]
```diff
@@ -390,13 +392,14 @@ private void evict(boolean direct, long excess)
 
                 if (oldestEntry.remove())
```
Comment (joakime) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:393]: No null check here?
This same code in `jetty-12.0.x` has a null check. (yes, i'm aware this PR is for `jetty-10.0.x`)

https://github.com/eclipse/jetty.project/blob/e71fa6dedd862aeea05f2ef54dc5789dddef7971/jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayByteBufferPool.java#L393-L397

Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:393]: @joakime 

https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java#L388-L389

Gee how do you make it include the code here?

Comment (joakime) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:393]: This PR changes `ArrayRetainableByteBufferPool.java` in `jetty-10.0.x` and is missing that null check.

Comment (joakime) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:393]: I'm going to retract and get more sleep
Disregard everything I've said in the last hour. :-(

Comment (gregw) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java:393]: maybe as a blob:

https://github.com/eclipse/jetty.project/blob/7a7d69a69f4f51772e20813332291189a24e91b1/jetty-io/src/main/java/org/eclipse/jetty/io/ArrayRetainableByteBufferPool.java#L387-L389

**Review by gregw — APPROVED** [review]
Thanks

**Review by joakime — APPROVED** [review]
