### PR TITLE
Fixes #14752 - Jetty 12.1 Violation of RFC9113 with Host and :authority headers

### LINKED ISSUE #14752: Jetty 12.1 Violation of RFC9113 with Host and :authority headers
**Jetty version(s)**
12.1.7

**Jetty Environment**
core

**HTTP version**
HTTP/2

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.9" 2025-10-21 LTS
OpenJDK Runtime Environment Temurin-21.0.9+10 (build 21.0.9+10-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.9+10 (build 21.0.9+10-LTS, mixed mode, sharing)

**OS type/version**
Debian 13

**Description**
From the [RFC9113](https://www.rfc-editor.org/rfc/rfc9113.html#name-request-pseudo-header-field)
> Clients MUST NOT generate a request with a Host header field that differs from the ":authority" pseudo-header field

But Jetty client 12.1.7 generates different headers.

**How to reproduce?**

Below `GET https://google.com` request with `java.io.IOException: protocol_error`

```java
ClientConnector clientConnector = new ClientConnector();
HTTP2Client h2Client = new HTTP2Client(clientConnector);
HttpClientTransportOverHTTP2 transport = new HttpClientTransportOverHTTP2(h2Client);
HttpClient httpClient = new HttpClient(transport);
httpClient.start();
try {
  Request request = httpClient
    .newRequest("https://google.com")
    .method(HttpMethod.GET);
  ContentResponse response = request.send();
  System.out.println("Status: " + response.getStatus());
  System.out.println("Response: " + response.getContentAsString());
} catch (Throwable error) {
  System.out.println("Error: " + error.getMessage());
}
httpClient.stop();
```

From logs
```
17:29:45.046 [HttpClient@3a7442c7-34] DEBUG o.e.j.http2.internal.HTTP2Flusher -- Processing oejh2f.HeadersFrame@3dd3c547#1[end=true,{GET{u=https://google.com/,HTTP/2.0,h=3,cl=-1,p=null}},priority=null]
17:29:45.046 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- CtxTbl[429d552b] encoding
17:29:45.052 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[429d552b] resized max=4096->4096
17:29:45.052 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[429d552b] entries=0, size=0, max=4096
17:29:45.052 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode IdxFieldS1:':method: GET' to '3fE11f82'
17:29:45.054 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[429d552b] added {D,0,:authority: google.com:443,52d9be86}
17:29:45.054 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[429d552b] entries=1, size=56, max=4096
17:29:45.054 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode LitIdxNS2HuffVIdx:':authority: google.com:443' to '3fE11f82418a98E79a82Ae43D371A699'
17:29:45.054 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode IdxFieldS1:':scheme: https' to '3fE11f82418a98E79a82Ae43D371A69987'
17:29:45.054 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode IdxFieldS1:':path: /' to '3fE11f82418a98E79a82Ae43D371A6998784'
17:29:45.055 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[429d552b] added {D,1,Accept-Encoding: gzip, br, zstd,63ae25eb}
17:29:45.055 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[429d552b] entries=2, size=117, max=4096
17:29:45.055 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode LitIdxNS2HuffVIdx:'Accept-Encoding: gzip, br, zstd' to '3fE11f82418a98E79a82Ae43D371A6998784508b9bD9AbFa523b3e94F684C9'
17:29:45.055 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[429d552b] added {D,2,User-Agent: Jetty/12.1.7,7c2239cc}
17:29:45.055 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[429d552b] entries=3, size=171, max=4096
17:29:45.056 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode LitIdxNS2HuffVIdx:'User-Agent: Jetty/12.1.7' to '3fE11f82418a98E79a82Ae43D371A6998784508b9bD9AbFa523b3e94F684C97a89Ca54A7D30112E15dDf'
17:29:45.056 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[429d552b] added {D,3,Host: google.com,12d0de47}
17:29:45.056 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[429d552b] entries=4, size=217, max=4096
17:29:45.056 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode LitIdxNS2HuffVIdx:'Host: google.com' to '3fE11f82418a98E79a82Ae43D371A6998784508b9bD9AbFa523b3e94F684C97a89Ca54A7D30112E15dDf668798E79a82Ae43D3'
17:29:45.056 [HttpClient@3a7442c7-34] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- CtxTbl[429d552b] encoded 51 octets
```

```
HdrTbl[429d552b] added {D,3,Host: google.com,12d0de47}
HdrTbl[429d552b] added {D,0,:authority: google.com:443,52d9be86}
```

**Work around**

We can remove Host header manually and then request won't fail

```java
request.onRequestBegin(it -> {
  it.headers(headers -> headers.remove(HttpHeader.HOST));
});
```

Logs
```
17:36:23.253 [HttpClient@3a7442c7-35] DEBUG o.e.j.http2.internal.HTTP2Flusher -- Processing oejh2f.HeadersFrame@269d4347#1[end=true,{GET{u=https://www.google.com/,HTTP/2.0,h=2,cl=-1,p=null}},priority=null]
17:36:23.253 [HttpClient@3a7442c7-35] DEBUG o.eclipse.jetty.util.ConcurrentPool -- returning entry oeju.ConcurrentPool$ConcurrentEntry@3678948b{terminated=false,multiplex=1,pooled=oeji.ArrayByteBufferPool$PooledBuffer@457e5ec2[0/8192,d=true,rc=0]} for oeju.ConcurrentPool@43f6d40c[strategy=THREAD_ID,inUse=1,size=1,max=100,leaked=0,terminated=false]
17:36:23.254 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- CtxTbl[7741ef14] encoding
17:36:23.254 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[7741ef14] resized max=4096->4096
17:36:23.254 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[7741ef14] entries=0, size=0, max=4096
17:36:23.254 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode IdxFieldS1:':method: GET' to '3fE11f82'
17:36:23.254 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[7741ef14] added {D,0,:authority: www.google.com:443,1e5c9e37}
17:36:23.254 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[7741ef14] entries=1, size=60, max=4096
17:36:23.254 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode LitIdxNS2HuffVIdx:':authority: www.google.com:443' to '3fE11f82418eF1E3C2F31cF35055C87a6e34D33f'
17:36:23.255 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode IdxFieldS1:':scheme: https' to '3fE11f82418eF1E3C2F31cF35055C87a6e34D33f87'
17:36:23.255 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode IdxFieldS1:':path: /' to '3fE11f82418eF1E3C2F31cF35055C87a6e34D33f8784'
17:36:23.255 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[7741ef14] added {D,1,Accept-Encoding: gzip, br, zstd,77c43f68}
17:36:23.255 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[7741ef14] entries=2, size=121, max=4096
17:36:23.255 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode LitIdxNS2HuffVIdx:'Accept-Encoding: gzip, br, zstd' to '3fE11f82418eF1E3C2F31cF35055C87a6e34D33f8784508b9bD9AbFa523b3e94F684C9'
17:36:23.255 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[7741ef14] added {D,2,User-Agent: Jetty/12.1.7,3bf09d02}
17:36:23.255 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackContext -- HdrTbl[7741ef14] entries=3, size=175, max=4096
17:36:23.255 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- encode LitIdxNS2HuffVIdx:'User-Agent: Jetty/12.1.7' to '3fE11f82418eF1E3C2F31cF35055C87a6e34D33f8784508b9bD9AbFa523b3e94F684C97a89Ca54A7D30112E15dDf'
17:36:23.255 [HttpClient@3a7442c7-35] DEBUG o.e.jetty.http2.hpack.HpackEncoder -- CtxTbl[7741ef14] encoded 46 octets
```

### PR DESCRIPTION
**Pull request by sbordet**
* Do not add the `Host` header in client requests for HTTP protocol versions for which must not be sent.
* Improved logic in `HttpConnection.normalizeRequest()`.

### CODE REVIEW

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpConnection.java [hunk 1]
```diff
@@ -69,6 +70,16 @@ public HttpDestination getHttpDestination()
...
 
+    protected HttpVersion getHttpVersion()
+    {
+        return null;
+    }
+
+    protected boolean requiresHostHeader()
+    {
+        return false;
+    }
```
Comment (lorban) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpConnection.java]: Why not making both methods abstract?

**Review by lorban — CHANGES_REQUESTED** [review]
This change seems to break upgrade to websockets.

Otherwise, I'd prefer `getHttpVersion()` and `requiresHostHeader()` to be abstract: can anyone but us provide implementations for the client's `HttpConnection`?
Besides that, LGTM.

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpConnection.java (hunk 1 above)
Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpConnection.java]: Done.

**Review by lorban — APPROVED** [review]
