### PR TITLE
Fixes #8858 - Jetty 12 Review MovedContextHandler.

### LINKED ISSUE #8858: Jetty 12 - Review MovedContextHandler
**Jetty version(s)**
12+

**Description**
`MovedContextHandler` is not tested and it's currently broken.
Methods are still named after Servlets, but should be renamed to a more generic naming.

### PR DESCRIPTION
**Pull request by sbordet**
Updated method names to avoid references to Servlet concepts. Added test cases.
Updated XML files.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/MovedContextHandler.java [hunk 1]
```diff
@@ -23,122 +23,168 @@
...
 
-    /**
-     * @param expires the expires header value or null if no expires header
-     */
-    public void setExpires(String expires)
-    {
-        _expires = expires;
+            String cacheControl = getCacheControl();
+            if (cacheControl != null)
+                response.getHeaders().put(HttpHeader.CACHE_CONTROL, cacheControl);
```
Comment (gregw) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/MovedContextHandler.java]: If we wanted to optimise, then when the cache control is set, we could construct a `PreEncodedHttpField` and then put that rather than build a new HttpField on every request.

**Review by gregw — APPROVED** [review]
Other than a minor performance niggle...

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/MovedContextHandler.java [hunk 2]
```diff
@@ -13,132 +13,180 @@
...
  */
 public class MovedContextHandler extends ContextHandler
 {
-    final Redirector _redirector;
-    String _newContextURL;
-    boolean _discardPathInfo;
-    boolean _discardQuery;
-    boolean _permanent;
-    String _expires;
+    private int _statusCode = HttpStatus.SEE_OTHER_303;
```
Comment (joakime) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/MovedContextHandler.java:33]: Should document this default value in the javadoc somewhere.

In `getStatusCode()` perhaps?

**Review by joakime — CHANGES_REQUESTED** [review]
Looks good, just want to see some javadoc telling folks about the default statuscode.

**Review by joakime — APPROVED** [review]
