### PR TITLE
fix ByteBufferPool race condition

### LINKED ISSUE #5775: Potential data race in ByteBufferPool
**Jetty version**
9.4.x

**Description**

A data race detector was run over jetty 9.4.34 and flagged a potential race at 
ByteBufferPool.java:199 in org.eclipse.jetty.io.ByteBufferPool$Bucket.release(Ljava/nio/ByteBuffer;)V

### PR DESCRIPTION
**Pull request by lorban**
Closes #5775

### CODE REVIEW

File: jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java [hunk 1]
```diff
@@ -158,7 +158,7 @@ public void release(ByteBuffer buffer)
         private final int _capacity;
         private final int _maxSize;
         private final AtomicInteger _size;
-        private long _lastUpdate = System.nanoTime();
+        private volatile long _lastUpdate = System.nanoTime();
```
Comment (sbordet) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java]: In this way we always pay the cost of `volatile`, which is updated much more often than it's being read.

Frankly, I would leave it non-`volatile`.
Next best is using `AtomicLong.lazySet()` in 9.4.x and `VarHandle` in 10.0.x.
I would refrain using `volatile` unconditionally like proposed here, if possible.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java (hunk 1 above)
Comment (lorban) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java]: You're right that we could do better than simply using `volatile`.

On JDK 8, `AtomicLong`'s `lazySet()`/`get()` is probably best.
On JDK 9+, `lazySet()`/`getAcquire()` provide the exact semantics we want at the cheapest possible cost.

Let me update this PR, and I'll include the and `get()` -> `getAcquire()` change during the 10.0.x merge.

File: jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java [hunk 2]
```diff
@@ -252,6 +252,7 @@ int size()
 
         long getLastUpdate()
         {
+            // This could be changed to a getOpaque() call on JDK 9+.
```
Comment (sbordet) [inline jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java]: I think it should be `getAcquire()` because we want to see all modifications made by other threads (i.e. we want the semantic of a volatile read). I would remove the comment entirely -- the code difference would be enough.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java (hunk 2 above)
Comment (lorban) [reply jetty-io/src/main/java/org/eclipse/jetty/io/ByteBufferPool.java]: Sure, I'll remove the comment.

**Review by sbordet — APPROVED** [review]
After discussion, I think "opaque" semantic is fine for Jetty 10, so please use `[get|set]Opaque()` when merging to 10.
