### PR TITLE
Issue #11911 Fix documentation example for Request.getHttpUri

### LINKED ISSUE #11911: 11 -> 12 Migration guide wrongly suggests Request.getHttpURI as replacement for HttpServletRequest.getRequestURL
**Jetty version(s)**
Jetty 12.0.10

**Jetty Environment**
core, docs

**Description**
Both [the migration guides in the docs](https://jetty.org/docs/jetty/12/programming-guide/migration/11-to-12.html#handler-request-apis) as well as [this code sample](https://github.com/jetty/jetty.project/blob/9d0a457e59d94fd8374c1466ff9613549a7e00c3/documentation/jetty-documentation/src/main/java/org/eclipse/jetty/docs/programming/migration/ServletToHandlerDocs.java#L63-L66) mention that `Request.getHttpURI` replaces `HttpServletRequest.getRequestURL`. However, they are not identical: `Request.getHttpURI` also includes the query part, while `HttpServletRequest.getRequestURL` doesn't. This becomes obvious when looking at Jetty's servlet API implementation, which strips the query part before returning the URL:
https://github.com/jetty/jetty.project/blob/9d0a457e59d94fd8374c1466ff9613549a7e00c3/jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletApiRequest.java#L504-L508

This might not make a difference in many cases, but we did have a case where this incorrect migration introduced a bug, so it might be worth pointing out in the migration guides.

### PR DESCRIPTION
**Pull request by janbartel**
Closes #11911

Migration documentation implies that `Request.getHttpURI()` is the jetty-12 substitute for `Request.getRequestURL()` in  prior versions, which is not strictly true. Clarified the code example.

### CODE REVIEW

File: documentation/jetty/modules/code/examples/src/main/java/org/eclipse/jetty/docs/programming/migration/ServletToHandlerDocs.java [hunk 1]
```diff
@@ -60,10 +61,10 @@ public boolean handle(Request request, Response response, Callback callback) thr
             //   - servletRequest.getProtocol();
             String protocol = request.getConnectionMetaData().getProtocol();
 
-            // Gets the full request URI.
+            // Gets the request URL.
             // Replaces:
             //   - servletRequest.getRequestURL();
-            String fullRequestURI = request.getHttpURI().asString();
+            StringBuffer requestURL = new StringBuffer(HttpURI.build(request.getHttpURI()).query(null).asString());
```
Comment (sbordet) [inline documentation/jetty/modules/code/examples/src/main/java/org/eclipse/jetty/docs/programming/migration/ServletToHandlerDocs.java]: I think splitting makes it more clear what is the Jetty API, and what is boilerplate:

```suggestion
            HttpURI uri = HttpURI.build(request.getHttpURI()).query(null);
            StringBuffer requestURL = new StringBuffer(uri.asString());
```

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]
