### PR TITLE
Issue #5018 - add WebSocketClient UpgradeRequest timeout to jetty 10

### LINKED ISSUE #5018: WebSocketClient connect / upgrade timeout not configurable
**Jetty version**
9.4.28
**Java version**
1.8.0.252
**OS type/version**
Centos 6
**Description**
WebSocketClient.connect(...) creates WebSocketUpgradeRequests with indefinite timeout.  Even with the Future<Session>.cancel(), it would not cancel the requests.

This also leads to a big problem because: When the HttpDestination exchange queued exceeded, no new requests can be added.  The requests stay in the queue forever.

Reproduction steps:

1. Set HttpClient MaxConnectionsPerDestination = 1 and MaxRequestsQueuedPerDestination = 1
2. Asynchronously create 20 simultaneous connections (to the same server)
3.  Observed the HttpDestination queued is full and the request would never dequeue without the timeout

No new requests can be made, as queue is full.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
Changes for Jetty-10 based off PR #5024 for issue #5018.

I have changed the signature for `WebSocketClient.connect()` back to what it was in jetty 9.4.x, it is now taking a `ClientUpgradeRequest` and not the api `UpgradeRequest`. This is an API change so not sure if that is still okay now the beta release is out.

I don't think we want the timeout on the `org.eclipse.jetty.websocket.api.UpgradeRequest` as it is only usable for the clients upgrade request anyway.

### CODE REVIEW

**Comment by gregw** [comment]
This failed CI?     But no problems changing API like this in a Beta.... but last chance as we are going final real soon now!

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java [hunk 1]
```diff
@@ -297,6 +292,25 @@ public void setSession(Object session)
...
+     * zero or negative if the timeout is disabled
+     */
+    public long getTimeout()
+    {
+        return timeout;
+    }
+
     /**
      * ABNF from RFC 2616, RFC 822, and RFC 6455 specified characters requiring quoting.
      */
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:316]: Please move this static field to the top of the class and make it `private`.

Also, no need to pass it as parameter to `quoteIfNeeded()`.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java [hunk 2]
```diff
@@ -161,13 +161,13 @@ public String getHost()
     @Override
     public String getHttpVersion()
     {
-        return httpVersion;
+        throw new UnsupportedOperationException("HttpVersion not available on ClientUpgradeRequest");
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: Return the hardcoded value `HttpVersion.HTTP_1_1.asString()`.
We don't want to throw if someone calls this method for logging purposes.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java [hunk 3]
```diff
@@ -161,13 +161,13 @@ public String getHost()
...
     }
 
     @Override
     public String getMethod()
     {
-        return method;
+        throw new UnsupportedOperationException("Method not available on ClientUpgradeRequest");
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:170]: Return hardcoded `HttpMethod.GET.asString()`.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java [hunk 4]
```diff
@@ -149,9 +149,8 @@ public void onHandshakeResponse(HttpRequest request, HttpResponse response)
                 }
             });
         }
-        upgradeRequest.setConfiguration(configurationCustomizer);
-        CompletableFuture<Session> futureSession = new CompletableFuture<>();
 
+        CompletableFuture<Session> futureSession = new CompletableFuture<>();
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java:153]: You don't need to allocate this `CF`, just return what `whenComplete()` returns below.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/impl/JettyClientUpgradeRequest.java [hunk 5]
```diff
@@ -53,15 +50,7 @@ public JettyClientUpgradeRequest(WebSocketCoreClient coreClient, UpgradeRequest
             request.getHeaders().forEach(fields::put);
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/impl/JettyClientUpgradeRequest.java]: Uh, no. It's a mistake that `request.getHeaders()` returns a `HttpFields.Mutable`.
I'll fix `jetty-10.0.x` so please rebase this PR.
This code should be: `headers(fields -> request.getHeaders().forEach(fields::put))`.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/impl/JettyClientUpgradeRequest.java [hunk 6]
```diff
@@ -71,13 +60,8 @@ public JettyClientUpgradeRequest(WebSocketCoreClient coreClient, UpgradeRequest
...
                 .collect(Collectors.toList()));
 
-            // Copy method from upgradeRequest object
-            if (request.getMethod() != null)
-                method(request.getMethod());
-
-            // Copy version from upgradeRequest object
-            if (request.getHttpVersion() != null)
-                version(HttpVersion.fromString(request.getHttpVersion()));
+            // Copy timeout from upgradeRequest object
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/impl/JettyClientUpgradeRequest.java]: No need for the comment.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java (hunk 1 above)
Comment (joakime) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:316]: This suggestion is unrelated to this issue.
Good for a different PR related to general cleanup tho.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java (hunk 3 above)
Comment (joakime) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:170]: Should just remove the `.getMethod()` entirely, it's always `GET`

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java (hunk 4 above)
Comment (joakime) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java:153]: That doesn't seem right.  
We want to return immediately, and let the whenComplete handle the success/exception at a later point in time.

Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java:153]: This `CF` is giving a Jetty WS API `Session`, and the one with the `whenComplete()` returns a `CoreSession`. They're not interchangeable.
The core connect is used to complete the future for the jetty ws api connect.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: What if we're doing websocket over HTTP/2? 
I don't think we have enough information available here to know if we are using HTTP/2 or not. 

The previous implementation of this just returned null for both as there were no setters for it.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java (hunk 4 above)
Comment (sbordet) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java:153]: @lachlan-roberts CFs can be `map()`ed to transform their result; or perhaps use `CF.handle()` rather than `whenComplete()`.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/impl/JettyClientUpgradeRequest.java (hunk 6 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/impl/JettyClientUpgradeRequest.java]: All the other operations in this block have a similar comment. I was trying to fit in with the current style.
Should I remove all these comments to make it more compact?

Comment (sbordet) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/impl/JettyClientUpgradeRequest.java]: @lachlan-roberts if the comment just says what the code does, remove it.
This one was also rotten, as it was referring to an `upgradeRequest object` which does not exist in the code.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java (hunk 4 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java:153]: Just looked at that, but I don't think we can map the exception like we are currently doing using `CF.handle()`.

Comment (sbordet) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java:153]: @lachlan-roberts good point about the transformation of the exception.
Code is good as is, returning the CF created on the fly, rather than the one returned by `whenComplete()`.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:316]: I will do this in a separate cleanup PR then.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:170]: Same as above, for HTTP/2 this would be `CONNECT`. So at this stage we don't really know.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java (hunk 2 above)
Comment (sbordet) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: @lachlan-roberts so why there are these 2 methods then? A relic of 9.4.x?
If we cannot implement them like you correctly point out, let's remove them.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: We need these methods here because this implements the `org.eclipse.jetty.websocket.api.UpgradeRequest` interface. These methods can be used on the server side, and are implemented on the client after the upgrade once you get it from the `Session`.

**Review by sbordet — APPROVED** [review]

**Review by sbordet — APPROVED** [review]

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java (hunk 2 above)
Comment (iiliev2) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: @lachlan-roberts @sbordet Why is it not possible to specify the protocol of the websocket upgrade in this class, and instead we have to use separate clients? When building a proxy server with jetty, one can't use a single client due to this, because the proxy will not be able to set the http version for web socket proxying(which should be the same as between the source and the proxy).

Comment (sbordet) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: @iiliev2 I don't understand?
Did you actually try and it's not working? 
If so please open a new issue with more details.

Comment (iiliev2) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: Is there an official way that I can do this? How can I try it? This class throws an error that http version is not supported.

Comment (sbordet) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: @iiliev2 sorry, but I still don't understand what the problem is.
Why are you calling this method? What use would you do with the return value?
It throws because it cannot return a correct value.

Comment (iiliev2) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: I am not calling this method. I was looking for a `setHttpVersion`, then I saw not only is it not available, there is this `get` method which explicitly denies this being possible.

Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: Why are you trying to set the HttpVersion? can you explain your use case, are you trying to use WebSocket over HTTP/2?

And the best place for this discussion is a new issue (this PR was merged over 4 years ago).

Comment (iiliev2) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:164]: Opened https://github.com/jetty/jetty.project/issues/12659
