### PR TITLE
Issue #13335 - fixes for HttpServletRequest.upgrade

### LINKED ISSUE #13335: Servlet Upgrade Support is too eager
**Jetty version(s)**

12.1.0.beta1

**Jetty Environment**

ee10

**Description**

I'm currently try to use the [new Servlet Upgrade support](https://github.com/jetty/jetty.project/pull/12186) but found some issues, if I call the method:

https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/http/httpservletrequest#upgrade(java.lang.Class)

jetty checks several conditions on the response(!)

>         if (response.getStatus() != HttpStatus.SWITCHING_PROTOCOLS_101)
>             throw new IllegalStateException("Response status should be 101");
>         if (response.getHeaders().get("Upgrade") == null)
>             throw new IllegalStateException("Missing Upgrade header");
>         if (!"Upgrade".equalsIgnoreCase(response.getHeaders().get("Connection")))
>             throw new IllegalStateException("Invalid Connection header");
>         if (response.isCommitted())
>             throw new IllegalStateException("Cannot upgrade committed response");
>         if (_servletChannel.getConnectionMetaData().getHttpVersion() != HttpVersion.HTTP_1_1)
>             throw new IllegalStateException("Only requests over HTTP/1.1 can be upgraded");

None of these conditions are described in the API though and instead it says:

> **Creates** an instance of HttpUpgradeHandler for a given class and uses it for the http protocol upgrade processing

So my expectation would be that (if such checks are need to be made) not earlier than before sending the actual response to the client. This is also reflected by `throw new IllegalStateException("Cannot upgrade committed response");` so before the response is actually committed I could modify anything that is checked here anyways (or should be, see below!).

I would also expect it to automatically set `SWITCHING_PROTOCOLS_101` or `Upgrade: Connection` if it is the only valid choice anyways and missing at these point.

Another issue (compared to implementation in other webservers) seem that creating the handler commits the response as well as calling init with the web connection, so a handler has no real chance to perform anything after construction time (and one can't pass a prebuild instance to the method), what makes it returning the handler from the method quite useless in many cases.

Also the [Javadoc](https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/http/httpupgradehandler) mentions

> It is called once the HTTP Upgrade process has been completed

So unless I have created my handler and the response is written I suppose it can not be claimed to be completed.

Also [the spec describes the process as follows](https://jakarta.ee/specifications/servlet/6.0/jakarta-servlet-spec-6.0#upgrade-processing):

> When an upgrade request is received, the servlet can invoke the HttpServletRequest.upgrade method, which starts the upgrade process. This method **instantiates** the given HttpUpgradeHandler class. The returned HttpUpgradeHandler instance **may be further customized**.

and later on

> **After exiting the service method of the servlet**, the servlet container completes the processing of all filters and marks the connection to be handled by the HttpUpgradeHandler. It then calls the HttpUpgradeHandler's init method, passing a WebConnection to allow the protocol handler access to the data streams.

*So long story short* I would expect that  `HttpServletRequest.upgrade(Class<T>)` only creates the handler and performs whatever book keeping is required. Then after the service method of the Servlet (or Filter) is done the checks are performed and the `HttpUpgradeHandler.init(WebConnection)` is called (possibly asynchronous). Currently the init happens to early (e.g. as part of the method call).

### PR DESCRIPTION
**Pull request by lachlan-roberts**
Closes #13335

This PR prevents `HttpUpgradeHandler.init` being called from within the `HttpServletRequest.upgrade` implementation, this should only instantiate the `HttpUpgradeHandler`.  
see https://jakarta.ee/specifications/servlet/6.1/jakarta-servlet-spec-6.1#upgrade-processing

> After exiting the service method of the servlet, the servlet container completes the processing of all filters and marks the connection to be handled by the HttpUpgradeHandler. It then calls the HttpUpgradeHandler's init method, passing a WebConnection to allow the protocol handler access to the data streams.

This PR also changes the  `HttpServletRequest.upgrade` implementation to automatically set required headers for the upgrade.

### CODE REVIEW

**Comment by lachlan-roberts** [comment]
@gregw can you please review this PR, currently only for EE11, but I can duplicate these changes for EE10 once we get the EE11 code reviewed.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java [hunk 1]
```diff
@@ -757,201 +750,20 @@ public Part getPart(String name) throws IOException, ServletException
...
-                    outputStreamComplete.complete(null);
-                }
-                catch (Throwable t)
-                {
-                    outputStreamComplete.completeExceptionally(t);
-                    throw t;
-                }
-            }
+        response.setStatus(HttpStatus.SWITCHING_PROTOCOLS_101);
+        response.getHeaders().put(HttpHeader.CONNECTION, HttpHeaderValue.UPGRADE);
```
Comment (gregw) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java:759]: why not the same change in EE10?

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannel.java [hunk 2]
```diff
@@ -608,6 +634,268 @@ public void handle()
...
+            if (!"Upgrade".equalsIgnoreCase(response.getHeaders().get("Connection")))
+                throw new IllegalStateException("Invalid Connection header");
+            if (response.isCommitted())
+                throw new IllegalStateException("Cannot upgrade committed response");
+            if (getConnectionMetaData().getHttpVersion() != HttpVersion.HTTP_1_1)
+                throw new IllegalStateException("Only requests over HTTP/1.1 can be upgraded");
+
+            CompletableFuture<Void> outputStreamComplete = new CompletableFuture<>();
+            CompletableFuture<Void> inputStreamComplete = new CompletableFuture<>();
+            ServletOutputStream outputStream = new ServletOutputStreamWrapper(_servletContextRequest.getHttpOutput())
```
Comment (gregw) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannel.java]: Can this be moved to a top level class?  Better stack traces and less verbosity in this class.

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannel.java [hunk 3]
```diff
@@ -608,6 +634,268 @@ public void handle()
...
+                        @Override
+                        public void onError(Throwable t)
+                        {
+                            writeListener.onError(t);
+                            outputStreamComplete.completeExceptionally(t);
+                        }
+                    });
+                }
+            };
+            ServletInputStream inputStream = new ServletInputStreamWrapper(_servletContextRequest.getHttpInput())
```
Comment (gregw) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannel.java]: Ditto.
Maybe move both input and output to be inner classes of a ServletUpgrade class that cannot be constructed?

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannel.java [hunk 4]
```diff
@@ -608,6 +634,268 @@ public void handle()
...
+                outputStream.flush(); // commit the 101 response
+                upgradeableConnection.startTunnel();
+            }
+            else
+            {
+                LOG.warn("Unexpected connection type {}", connection);
+                throw new IllegalStateException();
+            }
+
+            WebConnection webConnection = new WebConnection()
```
Comment (gregw) [inline jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletChannel.java]: Again avoid inner class for things that might turn up in stack traces.  make inner class of new ServletUpgrade class

**Review by gregw — CHANGES_REQUESTED** [review]
Looks good, but I'd prefer if most of the upgrade verbosity was moved to its own class as a namespace and to make stacks look better

File: jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-ee11/jetty-ee11-servlet/src/main/java/org/eclipse/jetty/ee11/servlet/ServletApiRequest.java:759]: Done.

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java [hunk 5]
```diff
@@ -94,6 +94,7 @@ private enum RequestState
         DISPATCH,    // AsyncContext.dispatch() has been called
         EXPIRE,      // AsyncContext timeout has happened
         EXPIRING,    // AsyncListeners are being called
+        UPGRADING,   // Request is being upgraded
```
Comment (gregw) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletChannelState.java:97]: update state diagram

**Review by gregw — CHANGES_REQUESTED** [review]

**Review by gregw — APPROVED** [review]

**Comment by laeubi** [comment]
@lachlan-roberts many thanks can't await the release!
