### PR TITLE
Issue #12888 support error dispatch for static error pages on POST

### LINKED ISSUE #12888: ErrorPageHandler dispatcher returns incorrect 405 for failing POST requests (e.g. JAX-RS)
**Jetty version(s)**
Jetty 12.0.16

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
JDK 21 temurin, but likely irrelvant for this issue

**OS type/version**
Not relevant. My host is Mac, but we observe the same issue in a Docker container based on `jetty:12.0.16-jdk21-eclipse-temurin`

**Description**
We have recently migrated our application to Jettty 12 (in an EE10 environment). We found one change in behavior, which in effect a consequence of what is already discussed in https://github.com/jetty/jetty.project/issues/11889.

As part of Jetty12 the DefaultServlet no longer handles POST requests, which is perfectly fine.

In our application we make use of JAX-RS (i.e. regular REST APIs) and we have configured error pages for the webapp (e.g. for 403 pointing to `/error-pages/403.html`)

Now our JAX-RS ecosystem makes use of annotations, which in the evaluation path somewhere do `httpServletResponse.sendError(403)`. This is then picked up by the Jetty error handler and it attempts to find and return the configured error page.

For GET requests this is working fine, however, for POST requests we are seeing "405" instead of the expected "403" (with the content of the error page)

The issue originates in how the event is dispatched in `org.eclipse.jetty.ee10.servlet.ServletChannel.handle()` around line 486 and handled further in `org.eclipse.jetty.ee10.servlet.ErrorHandler.handle()`with the actual dispatcher.

**How to reproduce?**

I cannot share our complex environment, but managed to get the symptom visualized in a standalone embedded jetty:

``` java
package com.metaphacts.jetty.launcher;

import java.io.File;
import java.io.IOException;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import org.eclipse.jetty.deploy.DeploymentManager;
import org.eclipse.jetty.ee10.servlet.ErrorPageErrorHandler;
import org.eclipse.jetty.ee10.webapp.WebAppContext;
import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.server.handler.ContextHandlerCollection;
import org.eclipse.jetty.server.handler.DefaultHandler;

public class ErrorPageHandlerBug {

    public static void main(String[] args) throws Exception {

        // create and configure Jetty server
        Server server = new Server();
        DeploymentManager deploymentManager = new DeploymentManager();
        ContextHandlerCollection contexts = new ContextHandlerCollection();

        ServerConnector httpConnector = new ServerConnector(server);
        httpConnector.setPort(8080);
        server.addConnector(httpConnector);

        WebAppContext webapp = new WebAppContext();
        webapp.setContextPath("/");
        webapp.setBaseResourceAsPath(new File(".").toPath());

        ErrorPageErrorHandler errorHandler = new ErrorPageErrorHandler();
        errorHandler.addErrorPage(403, "/forbidden.html");
        webapp.setErrorHandler(errorHandler);

        webapp.getServletHandler().addServletWithMapping(DemoServlet.class, "/demo");

        contexts.addHandler(webapp);

        Handler.Sequence handlers = new Handler.Sequence();
        handlers.addHandler(contexts);
        handlers.addHandler(new DefaultHandler());

        server.setHandler(handlers);

        deploymentManager.setContexts(contexts);
        server.addBean(deploymentManager);

        server.start();
        server.join();

    }

    public static class DemoServlet extends HttpServlet {

        private static final long serialVersionUID = 1L;

        @Override
        protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
            System.out.println("do get");
            resp.sendError(403);
        }

        @Override
        protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
            System.out.println("do post");
            resp.sendError(403);
        }
    }
}
```

When running this and invoking the servlet with a POST request, Jetty returns a 405 (while forbidden 403 would be expected)

```
curl -X POST http://localhost:8080/demo
```

Our workaround so far is to map a custom ResourceServlet to our "error-pages/" which overrides "doPost()" to delegate to "doGet()", i.e. roughly what was to my understanding happening in Jetty 11

Expectation: the Jetty Error dispatcher modifies the incoming HTTP method and dispatches the error page as GET (i..e get it properly handled by the default servlet)

Let me know when there are questions or further information required

### PR DESCRIPTION
**Pull request by janbartel**
Closes #12888

This PR enables the `DefaultServlet` to serve static error pages in response to error dispatches from a `POST` request.

### CODE REVIEW

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java [hunk 1]
```diff
@@ -75,6 +78,15 @@ public void init() throws ServletException
         super.init();
     }
 
+    @Override
+    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
```
Comment (joakime) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java:82]: Is POST the only one?
What about PUT or any other method?

I feel like this should exist in the `.service()` method instead of specifically the doPost method.

Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java:82]: I think sending static content responses for `PUT`s and `TRACE` methods would be a really bad idea.   We don't want to send any body for those.
I think that sending a body for a `POST` is OK.   

BUT... for non-post methods, sending a unsupported method response would be confusing.  So I do agree we should implement service and do as follows
```java
if (isErrorDispatch())
{
    switch(method)
        case "GET", "POST" -> doGet(request,response);
        default -> sendMinimalErrorResponse()
}
```

Actually.... should we even get here for non GET methods?   We should only do an error dispatch to an error page for methods that we know can have content?
If so, then just implementing doPost is fine. @janbartel can you check/confirm?

Comment (janbartel) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java:82]: `ErrorHandler.errorPageForMethod` only supports error pages for `GET`, `POST` and `HEAD`. Of those `GET` and `HEAD` should already work as they are supported methods in the `DefaultServlet`. It is only `POST` that is not supported.

Comment (gregw) [reply jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/DefaultServlet.java:82]: So the solution in this PR should be fine.

**Review by gregw — APPROVED** [review]
