### PR TITLE
Issue #14436 - Fix NPE in HttpFields.from() quality CSV parsing

### LINKED ISSUE #14436: Jetty 12.1.6 HttpFields from(HttpField...) does not provide opportunity to set compliance listener
**Jetty version(s)**

Jetty 12.1.6

**Jetty Environment**

EE11

**HTTP version**

HTTP/1.1

**Java version/vendor** `(use: java -version)`
openjdk version "25.0.2" 2026-01-20 LTS
OpenJDK Runtime Environment Zulu25.32+22-SA (build 25.0.2+10-LTS)
OpenJDK 64-Bit Server VM Zulu25.32+22-SA (build 25.0.2+10-LTS, mixed mode, sharing)

**OS type/version**
Windows 11 x64

**Description**

The HTTP compliance enhancements in https://github.com/jetty/jetty.project/issues/14397 now provide a method of setting custom HTTP compliance and listeners to HTTP header parsing. However, we observe that a previous 12.1.5 workflow provides no clear opportunity to set a listener, resulting in a NPE.

When attempting to use the HttpFields from factory to build the object:

```
    HttpFields fields = HttpFields.from(new HttpField(HttpHeader.ACCEPT_LANGUAGE, acceptLanguageHeader));
    List<String> acceptable = fields.getQualityCSV(HttpHeader.ACCEPT_LANGUAGE);
```

we observe:

```
  Caused by: org.eclipse.jetty.websocket.core.exception.WebSocketException: WebSocket OPEN method error: Cannot invoke "java.util.function.Supplier.get()" because "this._listenerSupplier" is null
        ... 36 more
  Caused by: java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this._listenerSupplier" is null
        at org.eclipse.jetty.http@12.1.6/org.eclipse.jetty.http.ImmutableHttpFields.newQuotedQualityCSV(ImmutableHttpFields.java:167)
        at org.eclipse.jetty.http@12.1.6/org.eclipse.jetty.http.HttpFields.getQualityCSV(HttpFields.java:787)
        at org.eclipse.jetty.http@12.1.6/org.eclipse.jetty.http.HttpFields.getQualityCSV(HttpFields.java:763)
```

It appears that the Immutable factory sequence:

```
    /**
     * <p>Returns an immutable {@link HttpFields} instance containing the given
     * {@link HttpField}s.</p>
     *
     * @param fields the {@link HttpField}s to be contained in the returned instance
     * @return a new immutable {@link HttpFields} instance with the given {@link HttpField}s
     */
    static HttpFields from(HttpField... fields)
    {
        return new org.eclipse.jetty.http.ImmutableHttpFields(fields);
    }

...

    /**
     * Initialize HttpFields from copy.
     *
     * @param fields the fields to copy data from
     */
    protected ImmutableHttpFields(HttpField[] fields)
    {
        this(fields, fields.length);
    }

    protected ImmutableHttpFields(HttpField[] fields, int size)
    {
        this(null, null, fields, size);
    }

    ImmutableHttpFields(HttpCompliance httpCompliance, Supplier<ComplianceViolation.Listener> listenerSupplier, HttpField[] fields, int size)
    {
        _httpCompliance = httpCompliance;
        _listenerSupplier = listenerSupplier;
        _fields = fields;
        _size = size;
    }
```

Provides no workflow for setting '_listenerSupplier ' which later produces NPE at:

```
  @Override
    public QuotedCSV newQuotedCSV(boolean keepQuotes)
    {
        return new QuotedCSV(_httpCompliance, _listenerSupplier.get(), keepQuotes);
    }
```

We have worked around this issue with the following alternative:

```
    HttpFields.Mutable headers = HttpFields.build();
    headers.put(new HttpField(HttpHeader.ACCEPT_LANGUAGE, acceptLanguageHeader));
    HttpFields fields = headers.asImmutable();
    List<String> acceptable = fields.getQualityCSV(HttpHeader.ACCEPT_LANGUAGE);
```

as this uses, and copies to the immutable instance, the default listener:

```
  protected MutableHttpFields(int capacity)
    {
        _httpCompliance = null;
        _listenerSupplier = () -> null;
        _fields = new HttpField[capacity];
    }
```

It seems as though using the default listener () -> null might be an appropriate action for the HttpFields.from() workflow.

**How to reproduce?**
```
    String acceptLanguageHeader = completedUpgradeRequest.getHeader(HttpHeader.ACCEPT_LANGUAGE.toString());

    ...

    HttpFields fields = HttpFields.from(new HttpField(HttpHeader.ACCEPT_LANGUAGE, acceptLanguageHeader));
    List<String> acceptable = fields.getQualityCSV(HttpHeader.ACCEPT_LANGUAGE);
```

### PR DESCRIPTION
**Pull request by afarber**
Fixes #14436

`HttpFields.from(HttpField...)` creates `ImmutableHttpFields` through a constructor path that left `_listenerSupplier` as `null`, so `getQualityCSV(...)` could throw `NullPointerException` when `newQuotedQualityCSV(...)` calls `_listenerSupplier.get()`.

This is a regression introduced by #14400 which added listener-based CSV creation in `ImmutableHttpFields` but did not initialize the default supplier in the `from(...)` constructor path.

Changes in this PR:

- Add regression test `HttpFieldsTest.testFromGetQualityCSV()` reproducing the NPE via `HttpFields.from(...)`
- Guard against null `listenerSupplier` in the main `ImmutableHttpFields` constructor via `Objects.requireNonNullElse()`
- Clarify `HttpFields.from(...)` Javadoc to document default compliance/listener behavior

Verification:

- Before fix: `mvn -Dmimir.enabled=false -pl jetty-core/jetty-http -Dtest=HttpFieldsTest#testFromGetQualityCSV test` fails with NPE
- After fix: same command passes

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/ImmutableHttpFields.java [hunk 1]
```diff
@@ -43,7 +43,7 @@ protected ImmutableHttpFields(HttpField[] fields)
 
     protected ImmutableHttpFields(HttpField[] fields, int size)
     {
-        this(null, null, fields, size);
+        this(null, () -> null, fields, size);
```
Comment (lorban) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/ImmutableHttpFields.java]: Since `null` is never a valid value, I'd rather modify the constructor below to add a null check to set a default value instead of setting one here:

`_listenerSupplier = Objects.requireNonNullElse(listenerSupplier, () -> null)`

**Review by lorban — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/ImmutableHttpFields.java (hunk 1 above)
Comment (afarber) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/ImmutableHttpFields.java]: Ok, added the `Objects.requireNonNullElse` in the main constructor

**Review by lorban — APPROVED** [review]
