### PR TITLE
Better support for implied ports on ForwardedRequestCustomizer

### LINKED ISSUE #5417: Badly configured HttpConfiguration.securePort can lead to wrong port produced by ForwardedHeader
**Jetty version**
9.4.32

**Java version**
AdoptOpenJDK build 1.8.0_262-b10

**OS type/version**
Linux CentOS 7.8 Kernel 3.10.0-1062.el7.x86_64

**Description**
For us the changes related to #5224 or #5247 have some surprising regression with 9.4.32
Our reverse-proxy (haproxy) always sends a RFC7239 style forwarded header towards jetty.
This always worked fine with 9.4.31 but with 9.4.32 it suddenly adds the (wrong) port to the requestURL
A simple example just printing out `request.getRequestURL()`
Request forwarded from upstream haproxy:
```
GET /sdpVab/test-forwarded.jsp HTTP/1.1
user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-language: en,en-US;q=0.95,de;q=0.89,fr-FR;q=0.84,nl;q=0.79,de-DE;q=0.74,en-GB;q=0.68,de-US;q=0.63,en-EN;q=0.58,fr;q=0.53,nl-NL;q=0.47,de-formal;q=0.42,en-CA;q=0.37,en-AU;q=0.32,es-ES;q=0.26,es;q=0.21,en-DE;q=0.16,eng-US;q=0.11,eng;q=0.05
accept-encoding: gzip, deflate, br
dnt: 1
upgrade-insecure-requests: 1
cache-control: max-age=0
te: trailers
host: web-144-237.ect-telecoms.de
cookie: JSESSIONID=oj47pppk3nxc1k1cyy156nqlx0;
forwarded: for=192.168.253.64;host=web-144-237.ect-telecoms.de;proto=https;proto-version=h2
```

Answer from 9.4.31:
```
HTTP/1.1 200 OK
Content-Type: text/html;charset=utf-8
Set-Cookie: JSESSIONID=nxeetp3wb734e9udszzebmvs0; Path=/sdpVab; Secure; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Transfer-Encoding: chunked


<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Forward test</title>
</head>
<body>
<p>https://web-144-237.ect-telecoms.de/sdpVab/test-forwarded.jsp</p>
</body>
</html>
```

Answer from 9.4.32:
```
HTTP/1.1 200 OK
Content-Type: text/html;charset=utf-8
Set-Cookie: JSESSIONID=oj47pppk3nxc1k1cyy156nqlx0; Path=/sdpVab; Secure; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Transfer-Encoding: chunked


<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Forward test</title>
</head>
<body>
<p>https://web-144-237.ect-telecoms.de:8443/sdpVab/test-forwarded.jsp</p>
</body>
</html>
```

Looks like the port 8443 is added in error here.

### PR DESCRIPTION
**Pull request by joakime**
#5417 
Implied ports were taken from the active connector's HttpConfiguration, this was a bad idea.

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
@gregw I'm not 100% sure this is correct on this PR.

See issue #5419 and then look at this commit.
This PR might be 100% invalid and no change to ForwardedRequestCustomizer is necessary.

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java [hunk 1]
```diff
@@ -783,6 +794,71 @@ public void testConfiguredBehavior(Request request, Expectations expectations) t
...
+    public static Stream<Arguments> nonStandardPortCases()
+    {
+        return Stream.of(
+            // RFC7239 Tests with https.
+            Arguments.of(new Request("RFC7239 with https and h2")
+                    .headers(
+                        "GET /test/forwarded.jsp HTTP/1.1",
+                        "Host: web.euro.de",
+                        "Forwarded: for=192.168.2.6;host=web.euro.de;proto=https;proto-version=h2"
+                        // Client: https://web.euro.de/test/forwarded.jsp
```
Comment (gregw) [inline jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java]: remove this comment

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java [hunk 2]
```diff
@@ -783,6 +794,71 @@ public void testConfiguredBehavior(Request request, Expectations expectations) t
...
+                    .requestURL("https://web.euro.de/test/forwarded.jsp")
+                    .remoteAddr("192.168.2.6").remotePort(0)
+            ),
+            // RFC7239 Tests with https and proxy provided port
+            Arguments.of(new Request("RFC7239 with proxy provided port on https and h2")
+                    .headers(
+                        "GET /test/forwarded.jsp HTTP/1.1",
+                        "Host: web.euro.de:9443",
+                        "Forwarded: for=192.168.2.6;host=web.euro.de:9443;proto=https;proto-version=h2"
+                        // Client: https://web.euro.de:9443/test/forwarded.jsp
```
Comment (gregw) [inline jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java]: remove this comment

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java [hunk 3]
```diff
@@ -783,6 +794,71 @@ public void testConfiguredBehavior(Request request, Expectations expectations) t
...
     }
 
+    public static Stream<Arguments> nonStandardPortCases()
+    {
+        return Stream.of(
+            // RFC7239 Tests with https.
+            Arguments.of(new Request("RFC7239 with https and h2")
+                    .headers(
+                        "GET /test/forwarded.jsp HTTP/1.1",
+                        "Host: web.euro.de",
```
Comment (gregw) [inline jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java]: Use another domain name like `web.example.org`

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java [hunk 4]
```diff
@@ -82,6 +84,15 @@ public void init() throws Exception
         connector = new LocalConnector(server, http);
         server.addConnector(connector);
 
+        // Alternate behavior Connector
+        HttpConnectionFactory httpAlt = new HttpConnectionFactory();
+        httpAlt.setInputBufferSize(1024);
```
Comment (gregw) [inline jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java]: I wonder why we are setting the input buffer  size in this test?

**Review by gregw — CHANGES_REQUESTED** [review]
Looks good, but a few changes needed.

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java [hunk 5]
```diff
@@ -512,12 +512,7 @@ public void customize(Connector connector, HttpConfiguration config, Request req
         {
             port = requestURI.getPort();
         }
-        if (port == MutableHostPort.IMPLIED) // is implied
-        {
-            // get Implied port (from protocol / scheme) and HttpConfiguration
-            int defaultPort = 80;
-            port = proto.equalsIgnoreCase(config.getSecureScheme()) ? getSecurePort(config) : defaultPort;
-        }
+        // if (port == MutableHostPort.IMPLIED) // is implied, no port change needed
```
Comment (gregw) [inline jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: can you make this comment not look like commented out code.  It is good info to have, but I found the format confusing

File: jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java (hunk 4 above)
Comment (joakime) [reply jetty-server/src/test/java/org/eclipse/jetty/server/ForwardedRequestCustomizerTest.java]: no clue, i'll remove it and see what happens

File: jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java (hunk 5 above)
Comment (joakime) [reply jetty-server/src/main/java/org/eclipse/jetty/server/ForwardedRequestCustomizer.java]: True. will fix.

**Review by gregw — APPROVED** [review]
