### PR TITLE
Fixes #12916 - Bad example in JavaDoc of InputStreamResponseListener.

### LINKED ISSUE #12916: Bad example in JavaDoc of InputStreamResponseListener
**Jetty version(s)**
12.0.17

**Jetty Environment**
core (client)

**Java version/vendor** `(use: java -version)`
OpenJDK 64-Bit Server VM Temurin-21.0.6+7 (build 21.0.6+7-LTS, mixed mode, sharing)

**OS type/version**
Windows 11

**Description**
The class documentation of `InputStreamResponseListener` includes the following example to demonstrate its usage:

```java
InputStreamResponseListener listener = new InputStreamResponseListener();
client.newRequest(...).send(listener);

// Wait for the response headers to arrive
Response response = listener.get(5, TimeUnit.SECONDS);
if (response.getStatus() == 200)
{
    // Obtain the input stream on the response content
    try (InputStream input = listener.getInputStream())
    {
        // Read the response content
    }
}
```

This works but will leak resources if the status is not 200, because then we never read the content. Therefore, the response stays open forever, or at least until some timeout occurs.

It would be better to abort the response if we don't read it:

```java
Response response = listener.get(5, TimeUnit.SECONDS);
if (response.getStatus() == 200)
{
    // ...
}
else
    response.abort(new CancellationException());
```

To make this easier, you could consider making the whole listener `AutoCloseable`, not just the input stream, so one could use try-with-resources on the listener to make sure the response is completed at the end:

```java
try (InputStreamResponseListener listener = new InputStreamResponseListener())
{
    client.newRequest(...).send(listener);
    Response response = listener.get(5, TimeUnit.SECONDS);
    if (response.getStatus() == 200)
    {
        // ...
    }
}
```

### PR DESCRIPTION
**Pull request by sbordet**
Made InputStreamResponseListener implement AutoCloseable. Updated tests, javadocs and documentation.

### CODE REVIEW

**Review by lorban — APPROVED** [review]

File: jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/InputStreamResponseListener.java [hunk 1]
```diff
@@ -187,6 +189,12 @@ public void onComplete(Result result)
         chunkCallbacks.forEach(t -> t.releaseAndFail(failure));
     }
 
+    @Override
+    public void close() throws IOException
+    {
+        stream.updateAndGet(input -> input == null ? InputStream.nullInputStream() : input).close();
```
Comment (mperktold) [inline jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/InputStreamResponseListener.java:195]: This doesn't really change anything if the stream was never created.

I expected this to release all chunks that have been received already, and probably abort an already demanded but not yet received chunk, or maybe the whole response (does that actually happen in `Input.close`?).

So when the InputStream hasn't been created yet, the behavior should be similar to `getInputStream().close()`. You could achieve this by changing this slightly to create a real `Input` instead of a `nullInputStream`, or you could try avoiding to create a stream and invoking the corresponding logic directly.

Comment (sbordet) [reply jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/InputStreamResponseListener.java:195]: @mperktold good catch!

**Comment by sbordet** [comment]
See also https://github.com/jetty/jetty.project/pull/12931.

**Comment by sbordet** [comment]
@mperktold can you please review https://github.com/jetty/jetty.project/pull/12931?

**Comment by mperktold** [comment]
@sbordet looks good now!

I see that you also improved releasing the buffers, that's great! 👍
