### PR TITLE
Issue #11092 - Allow MetaInfConfiguration parsing of `java.class.path` to support globs

### LINKED ISSUE #11092: Jetty 12.x startup fails because MetaInfConfiguration is throwing an exception while parsing java classpath with URIUtil when classpath contains wildcard ./mypath/*
**Jetty version(s)**
12.0.4

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
Java VM: OpenJDK 64-Bit Server VM 17.0.8.1+1, mixed mode, sharing, Eclipse Adoptium

**OS type/version**
Windows 10 Enterprise

**Description**
org.eclipse.jetty.ee10.webapp.MetaInfConfiguration is calling URIUtil::toURI with values from the classpath. If the classpath contains wildcard values like .\mypath\* it fails with an java.nio.file.InvalidPathException

Extract from MetaInfConfiguration : 

        String classPath = System.getProperty("java.class.path");
        if (classPath != null)
        {
            Stream.of(classPath.split(File.pathSeparator))
                .map(URIUtil::toURI)
                .filter(uriPatternPredicate)
                .forEach(addContainerResource);
        }

java.nio.file.InvalidPathException: Illegal char <*> at index xx : C:\temp\test\.\mypath\*
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
	at java.base/java.nio.file.Path.of(Path.java:147) ~[?:?]
	at java.base/java.nio.file.Paths.get(Paths.java:69) ~[?:?]
	at org.eclipse.jetty.util.URIUtil.toURI(URIUtil.java:1841) ~[jetty-util-12.0.4.jar:12.0.4]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.eclipse.jetty.ee10.webapp.MetaInfConfiguration.findAndFilterContainerPaths(MetaInfConfiguration.java:165) ~[jetty-ee10-webapp-12.0.4.jar:12.0.4]

**How to reproduce?**

import org.eclipse.jetty.util.URIUtil;

public class URIUtilTest {
	public static void main(String[] args) {
		URIUtil.toURI("C:\\mainpath\\mypath\\*");
	}
}

### LINKED ISSUE #12283: Cannot start embedded Jetty from an application that uses classpath wildcards
**Jetty version(s)**
12.0.13

**Jetty Environment**
ee10 

**Java version/vendor** `

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

**OS type/version**

Windows Server 2012

**Description**
Cannot use embedded Jetty started from an application that uses classpath  wildcards.

DEBUG:oejur.ResourceFactory:main: **Input string cannot be converted to URI "D:\testlibs\\*"**

`
java.lang.IllegalArgumentException: Cannot be converted to URI
	at org.eclipse.jetty.util.resource.ResourceFactory.newResource(ResourceFactory.java:376)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.jetty.ee10.webapp.MetaInfConfiguration.findAndFilterContainerPaths(MetaInfConfiguration.java:173)
	at org.eclipse.jetty.ee10.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:99)
	at org.eclipse.jetty.ee10.webapp.Configurations.preConfigure(Configurations.java:487)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.preConfigure(WebAppContext.java:457)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart(WebAppContext.java:498)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:491)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:624)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:491)
	at org.eclipse.jetty.server.Server.doStart(Server.java:565)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
`

**How to reproduce?**
    Start an embedded Jetty from an application that uses classpath wildcards.

### PR DESCRIPTION
**Pull request by joakime**
Use ResourceFactory.split(String) to properly parse the `java.class.path` so that globs can be supported in MetaInfConfiguration as well.

Fixes #11092 
Fixes #12283

### CODE REVIEW

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java [hunk 1]
```diff
@@ -404,6 +404,39 @@ public void testSplitOnSemicolon()
         }
     }
 
+    @Test
+    public void testSplitOnPathSeparatorWithGlob() throws IOException
+    {
+        try (ResourceFactory.Closeable resourceFactory = ResourceFactory.closeable())
```
Comment (janbartel) [inline jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:410]: Could you add another term to the glob string that is just a single jar file, to mimic a classpath that has both glob _and_ individual jar files on it.

File: jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaInfConfiguration.java [hunk 2]
```diff
@@ -169,9 +169,10 @@ public void findAndFilterContainerPaths(final WebAppContext context) throws Exce
         String classPath = System.getProperty("java.class.path");
         if (classPath != null)
         {
-            Stream.of(classPath.split(File.pathSeparator))
-                .map(resourceFactory::newResource)
-                .filter(r -> uriPatternPredicate.test(r.getURI()))
+            resourceFactory.split(classPath, File.pathSeparator)
```
Comment (janbartel) [inline jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaInfConfiguration.java:172]: Heh, technically we shouldn't fix ee8 and ee9 because they should be bug-for-bug compatible with jetty 10/11. But ok.

**Review by janbartel — CHANGES_REQUESTED** [review]
If you could add the extra term to the glob string as per my comment, then I think we're ok.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:410]: This test kind has that already, 2 non globs, and 1 glob.
Also the existing test `testSplitOnPipeWithGlob()` has the same.
Do you want the non-glob to be specifically a jar?

File: jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaInfConfiguration.java (hunk 2 above)
Comment (joakime) [reply jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaInfConfiguration.java:172]: In Jetty 10/11 we ignore globs here.
The raw string is created a `File` and then if it doesn't exist, it's ignored.
The thing is, a `File` with a `*` glob always produces a `File` instance that doesn't exist (or can be opened).
But a Path cannot even be created with a `*` glob, it throws an Exception.

File: jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:410]: Followup, do you want the extra non-globs to be before or after the glob?

Comment (janbartel) [reply jetty-core/jetty-util/src/test/java/org/eclipse/jetty/util/resource/ResourceFactoryTest.java:410]: I don't really mind the position of the jar, just so long as the test is a combination of dirs, a dir with glob and at least one explicit jar.

File: jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaInfConfiguration.java (hunk 2 above)
Comment (janbartel) [reply jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/MetaInfConfiguration.java:172]: understood.

**Comment by janbartel** [comment]
@joakime some test failures to address here as well.

**Comment by janbartel** [comment]
@joakime is this one ready for re-review?

**Comment by joakime** [comment]
> @joakime is this one ready for re-review?

Yes.  Review away.

**Comment by joakime** [comment]
@janbartel bump

**Review by janbartel — APPROVED** [review]
