### PR TITLE
Issue #14319 - Fix ZSTD byte duplication at 128KB boundary

### LINKED ISSUE #14319: ZSTD CompressionHandler may duplicate bytes in response
**Jetty version(s)**
12.1.5

**Jetty Environment**
ee8

**HTTP version**
1.1

**Java version/vendor** `(use: java -version)`

openjdk 25 2025-09-16 LTS
OpenJDK Runtime Environment Corretto-25.0.0.36.2 (build 25+36-LTS)
OpenJDK 64-Bit Server VM Corretto-25.0.0.36.2 (build 25+36-LTS, mixed mode, sharing)

**OS type/version**
macOS 15.7.2

**Description**
When frequently flushing the output stream, Jetty 12 ZSTD CompressionHandler may sometimes duplicate raw bytes in the original response.

**How to reproduce?**

Here is a minimal reproducible example:
```Java
import org.eclipse.jetty.compression.server.CompressionConfig;
import org.eclipse.jetty.compression.server.CompressionHandler;
import org.eclipse.jetty.compression.zstandard.ZstandardCompression;
import org.eclipse.jetty.ee8.servlet.ServletContextHandler;
import org.eclipse.jetty.io.ArrayByteBufferPool;
import org.eclipse.jetty.io.ByteBufferPool;
import org.eclipse.jetty.server.*;
import org.eclipse.jetty.util.thread.QueuedThreadPool;

import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

public class TestHttpCmd {

    public static class TestServlet extends HttpServlet
    {
        protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
        {
            try (ServletOutputStream out = response.getOutputStream()) {
                for (int i = 1; i <= 21847; i++) {
                    String s = String.format("%05d", i);
                    out.write(s.getBytes());
                    out.write('\n');
                    out.flush();
                }
            }
        }
    }

    public static void main(String[] args) throws Exception {
        QueuedThreadPool threadPool = new QueuedThreadPool(200, 20);
        // ZSTD requires larger byte buffer: https://github.com/jetty/jetty.project/issues/14028#issuecomment-3581586722
        ByteBufferPool byteBufferPool = new ArrayByteBufferPool(0, 4096, 132 * 1024);
        Server server = new Server(threadPool, null, byteBufferPool);
        ServerConnector connector = new ServerConnector(server, new HttpConnectionFactory());
        connector.setPort(9090);
        server.addConnector(connector);

        CompressionHandler compressionHandler = new CompressionHandler();

        compressionHandler.putCompression(new ZstandardCompression());
        compressionHandler.putConfiguration("/", CompressionConfig.builder()
                .defaults()
                .build()
        );

        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/");
        context.addServlet(TestServlet.class, "/test");
        compressionHandler.setHandler(context);

        server.setHandler(compressionHandler);
        server.start();
        server.join();
    }
}
```

```Bash
~  curl http://localhost:9090/test -o original
~  curl http://localhost:9090/test -o zstd --compressed
~ diff zstd original
21846c21846
< 2121846
---
> 21846
```

Notice that at the end of the ZSTD'ed output, 21846 becomes 2121846 for some reason.

One interesting observation is that the duplicate `21` is exactly at the 128KB boundary (21845 * 6 = 131072 = 128KB).

### PR DESCRIPTION
**Pull request by afarber**
Fixes #14319

When ZSTD compression produces output before consuming all input bytes, the encoder incorrectly rolled back to the original buffer position instead of accounting for bytes already consumed by zstd. This caused byte duplication at the 128KB boundary.

- `continueOp()`: Change `content.position(originalPosition)` to `content.position(originalPosition + inputBuf.getByteBuffer().position())` for heap buffers only
- `ensureDirect()`: Refactored per review feedback - uses absolute `put()` and doesn't modify source buffer position (position tracking now happens solely in `continueOp()`)

### CODE REVIEW

**Comment by afarber** [comment]
Tested on my Macbbok M1 using Homebrew `jbang` and `zstd`:

image

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.eclipse.jetty:jetty-server:12.1.6-SNAPSHOT
//DEPS org.eclipse.jetty.compression:jetty-compression-server:12.1.6-SNAPSHOT
//DEPS org.eclipse.jetty.compression:jetty-compression-zstandard:12.1.6-SNAPSHOT
//REPOS mavenLocal

import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import org.eclipse.jetty.compression.server.CompressionHandler;
import org.eclipse.jetty.compression.zstandard.ZstandardCompression;
import org.eclipse.jetty.http.HttpHeader;
import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.Response;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.util.Callback;

public class ZstdServer {
    public static void main(String[] args) throws Exception {
        Server server = new Server();
        ServerConnector connector = new ServerConnector(server);
        connector.setPort(8080);
        server.addConnector(connector);

        CompressionHandler compressionHandler = new CompressionHandler();
        compressionHandler.putCompression(new ZstandardCompression());

        compressionHandler.setHandler(new Handler.Abstract() {
            @Override
            public boolean handle(Request request, Response response, Callback callback) throws Exception {
                byte[] data = Files.readAllBytes(Path.of("/tmp/testdata.txt"));
                response.setStatus(200);
                response.getHeaders().put(HttpHeader.CONTENT_TYPE, "text/plain");
                response.write(true, ByteBuffer.wrap(data), callback);
                return true;
            }
        });

        server.setHandler(compressionHandler);
        server.start();
        System.out.println("Server started on http://localhost:8080");
        System.out.println("Press Ctrl+C to stop");
        server.join();
    }
}
```

Here the commands:

```bash
seq -f '%05g' 1 25000 > /tmp/testdata.txt
wc -c /tmp/testdata.txt
curl -v -s -H "Accept-Encoding: zstd" http://localhost:8080/ -o /tmp/response.zst
file /tmp/response.zst
zstd -d /tmp/response.zst -o /tmp/response.txt -f
ls -la /tmp/testdata.txt /tmp/response.zst /tmp/response.txt
diff /tmp/testdata.txt /tmp/response.txt
```

**Review by lorban — DISMISSED** [review]
LGTM, nice catch!

**Comment by afarber** [comment]
I was excited to discover it

**Review by sbordet — CHANGES_REQUESTED** [review]
I think there are more problems in `ensureDirect()`, and I think the fix is only valid in certain cases.

I am analyzing it in more details, I'll post the analysis later.

**Comment by joakime** [comment]
@afarber please reach out (via email) to ...

* sbordet@webtide.com
* jesse@webtide.com

File: jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/internal/ZstandardEncoderSink.java [hunk 1]
```diff
@@ -106,8 +106,14 @@ protected RetainableByteBuffer ensureDirect(ByteBuffer buffer, int size)
...
-            buffer.order(ByteOrder.LITTLE_ENDIAN); // zstandard requirement
-            return RetainableByteBuffer.wrap(buffer);
+            int length = Math.min(buffer.remaining(), size);
+            // Slice so returned buffer starts at position 0, same as heap path.
+            ByteBuffer slice = buffer.slice();
+            slice.limit(length);
+            slice.order(ByteOrder.LITTLE_ENDIAN); // zstandard requirement
+            // Adjust position to account for bytes already consumed by zstd.
+            buffer.position(buffer.position() + length);
+            return RetainableByteBuffer.wrap(slice);
```
Comment (sbordet) [inline jetty-core/jetty-compression/jetty-compression-zstandard/src/main/java/org/eclipse/jetty/compression/zstandard/internal/ZstandardEncoderSink.java]: Please restore what was before, as it was ok: the buffer is already direct, we don't copy it, so no need to chunk it.

The "direct" branch does not modify `content.position()`.

For the "indirect" branch, we should copy with chunks like it is done now, but we should not modify `content.position()`, to be consistent.

The `content.position()` is modified after compression in `continueOp()` (after your fix), so that is the only place where it is modified.

In `ensureDirect()` for the "indirect" case, please use `put(0, buffer, pos, length)` to avoid playing with the buffer position and limit.

File: jetty-core/jetty-compression/jetty-compression-zstandard/src/test/java/org/eclipse/jetty/compression/zstandard/ZstandardEncoderSinkTest.java [hunk 2]
```diff
@@ -83,4 +145,56 @@ public void testWriteLastTwice() throws Exception
...
+        }
+
+        assertThat(directBuffer.remaining(), is(0));
+
+        byte[] decompressed = decompress(compressed);
+        assertThat(decompressed.length, is(originalData.length));
+        for (int i = 0; i < originalData.length; i++)
+        {
+            assertThat("Mismatch at byte " + i, decompressed[i], is(originalData[i]));
+        }
```
Comment (sbordet) [inline jetty-core/jetty-compression/jetty-compression-zstandard/src/test/java/org/eclipse/jetty/compression/zstandard/ZstandardEncoderSinkTest.java]:
```suggestion
        assertArrayEquals(originalData, decompressed);
```

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — APPROVED** [review]
