### PR TITLE
Issue #6407 - Fix URI validation for WebSocket ClientUpgradeRequest

### LINKED ISSUE #6407: Malformed scheme logical expression check in WebSocket ClientUpgradeRequest
**Jetty version(s)**  11.0.5

**Java version/vendor** `(use: java -version)`  15.0.1

**OS type/version** Windows 10

**Description**
in the class ClientUpgradeRequest there is a malformed check in the constructor:
`if (!HttpScheme.WS.is(scheme) || !HttpScheme.WSS.is(scheme))`

That should obviously be
`if (!HttpScheme.WS.is(scheme) && !HttpScheme.WSS.is(scheme))`

**How to reproduce?**
Perform a websocket upgrade request

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Closes #6407

- Fix logic for URI validation in the constructor of `ClientUpgradeRequest`.
- Deprecate that constructor as the `URI` is not used and the validation is repeated after calling the `WebSocketClient.connect()` method.

### CODE REVIEW

File: jetty-websocket/websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/util/WSURI.java [hunk 1]
```diff
@@ -104,22 +104,13 @@ public static URI toWebsocket(final URI inputUri) throws URISyntaxException
         Objects.requireNonNull(inputUri, "Input URI must not be null");
         String httpScheme = inputUri.getScheme();
         if ("ws".equalsIgnoreCase(httpScheme) || "wss".equalsIgnoreCase(httpScheme))
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/util/WSURI.java:109]: Replace this line too using `HttpScheme.WS[S].is(...)`

File: jetty-websocket/websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/util/WSURI.java [hunk 2]
```diff
@@ -104,22 +104,13 @@ public static URI toWebsocket(final URI inputUri) throws URISyntaxException
...
-        {
-            // keep as-is
             return inputUri;
-        }
 
+        String afterScheme = inputUri.toString().substring(httpScheme.length());
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/util/WSURI.java:112]: `httpScheme` may be `null`, you need a guard like in `Negotiated.toWebSocket()`.

Is it possible to implement this method once and call it from different places?

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java [hunk 3]
```diff
@@ -50,11 +50,12 @@ public ClientUpgradeRequest()
         this.host = null;
     }
 
+    @Deprecated
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:56]: Add javadoc `@deprecated` that explains what to use instead.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-websocket/websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/util/WSURI.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/util/WSURI.java:109]: We can't really do this in the Jetty WebSocket API, we don't want to add a dependency on `jetty-http`.

File: jetty-websocket/websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/util/WSURI.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-api/src/main/java/org/eclipse/jetty/websocket/api/util/WSURI.java:112]: > Is it possible to implement this method once and call it from different places?

Not really as the API does not have dependencies on anything and where it is used in `websocket-core` cannot depend on `websocket-jetty-api`.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java [hunk 4]
```diff
@@ -50,11 +50,16 @@ public ClientUpgradeRequest()
         this.host = null;
     }
 
+    /**
+     * @deprecated use the no-args constructor instead.
+     * @see ClientUpgradeRequest#ClientUpgradeRequest()
```
Comment (sbordet) [inline jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java]:
```suggestion
     * @deprecated use {@link #ClientUpgradeRequest()} instead.
```

**Review by sbordet — CHANGES_REQUESTED** [review]
One last nit.

**Review by sbordet — APPROVED** [review]

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java (hunk 3 above)
Comment (joakime) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:56]: Should we just deprecate all of the ClientUpgradeRequest.requestURI behaviors too? (as in `.getRequestURI()` should probably be deprecated and always return null too.

**Review by joakime — DISMISSED** [review]
I think we should remove all of requestURI internals from ClientUpgradeRequest, and deprecate the constructor and getters.

File: jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-websocket/websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/ClientUpgradeRequest.java:56]: @joakime it implements these methods from the `UpgradeRequest` interface, and these methods need to be used on other implementations of this interface so they can't be deprecated.
