### PR TITLE
Issue #4836 - Too Many Files Error with AWS ALB.

### LINKED ISSUE #4836: Too Many Files Error with AWS ALB
I've opened a support case with AWS about this as well, but it might be worth someone looking at it to see about hardening against misbehaving load balancers or other components.

We have an application that would occasionally get this error:

java.io.IOException: Too many open files
at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:419)
at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:247)
at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:385)
at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:701)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
at java.lang.Thread.run(Thread.java:748)

After a fair amount of experimentation, I isolated the issue to connections made by the AWS Application Load Balancer apparently not being closed properly.  Creating an ec2 instance (Ubuntu 18.04) with a public IP address and connecting directly to that address did not cause the problem, but accessing that same machine via the ALB did cause the problem.

I can work around this issue by using an nginx instance to decrypt/re-encrypt the requests forwarded by the ALB, but this doesn't seem elegant to me.  

Please find attached the source code for a small sample application that can demonstrate the issue (although you will need to install in AWS and set up the ALB and so forth) and an Apache JMeter test for forcing it to happen (server names will not be valid, but it shows the idea). 

[leaky-jmeter-test.zip](https://github.com/eclipse/jetty.project/files/4565974/leaky-jmeter-test.zip)
[connection-leak-example_source.zip](https://github.com/eclipse/jetty.project/files/4565976/connection-leak-example_source.zip)

### PR DESCRIPTION
**Pull request by sbordet**
Added test to replicate the traffic seen in the issue.
The test shows that we do close the server EndPoint.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

**Comment by sbordet** [comment]
@gregw I have re-enabled the test in Java 11 but forced TLS 1.2 since the test expects very specific TLS < 1.3 behavior.

File: jetty-client/src/test/java/org/eclipse/jetty/client/ssl/SslBytesServerTest.java [hunk 1]
```diff
@@ -88,8 +89,9 @@
 import static org.junit.jupiter.api.condition.OS.LINUX;
 import static org.junit.jupiter.api.condition.OS.WINDOWS;
 
-// This whole test is very specific to how TLS < 1.3 works.
-@EnabledOnJre({JRE.JAVA_8, JRE.JAVA_9, JRE.JAVA_10})
+// Other JREs have slight differences in how TLS work
+// and this test expects a very specific TLS behavior.
+@EnabledOnJre({JRE.JAVA_8, JRE.JAVA_11})
```
Comment (gregw) [inline jetty-client/src/test/java/org/eclipse/jetty/client/ssl/SslBytesServerTest.java:94]: Can we have a simplified test for Java > 11?

**Review by gregw — APPROVED** [review]
