### PR TITLE
Issue #11280 update ee10 osgi embedded xml files

### LINKED ISSUE #11280: Jetty 12 EE10 OSGi Boot invalid jetty.xml Handler configuration
**Jetty version(s)**
Jetty 12.0.3 (but according to the source code it affects the current jetty-12 main as well)

**Jetty Environment**
ee10 (ee8 working without problems)

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)

**OS type/version**
Microsoft Windows 10 22H2 (OS Build 19045.3930)

**Description**
When trying to run an embedded Jetty 12 Jakarta EE10 in an OSGi unit test environment via the `jetty-ee10-osgi-boot` bundle it fails because the jetty.xml file incorrectly references the Handler class from jetty-server module, specifically this line:
```
    ...
    <Set name="handler">
      <New id="Handlers" class="org.eclipse.jetty.server.handler.Handler.Collection">   <----- Handler interface is in the org.eclipse.jetty.server package not in the handler package.
        <Set name="handlers">
        ...
```

Replacing the [Handler configuration section](https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-ee10/jetty-ee10-osgi/jetty-ee10-osgi-boot/jettyhome/etc/jetty.xml#L26-L39) in the EE10 jetty.xml from the EE8 boot's [jetty.xml](https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-ee8/jetty-ee8-osgi/jetty-ee8-osgi-boot/jettyhome/etc/jetty.xml#L25-L27) solves the issue and Jetty 12 can start without any errors.

**How to reproduce?**
I don't have a simple example project that demonstrates the problem, but if that's needed let me know.

### PR DESCRIPTION
**Pull request by janbartel**
closes #11280

### CODE REVIEW

File: jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestOSGiUtil.java [hunk 1]
```diff
@@ -95,6 +96,34 @@ public static List<Option> configureJettyHomeAndPort(boolean ssl, String jettySe
...
     }
+
+    public static List<Option>  configureJettyHomeAndPortViaBootBundle(String jettyConnectorListenerFileName)
+    {
+        //use the default set of config files embedded in jetty boot jar
+        List<Option> options = new ArrayList<>();
+        StringBuffer xmlConfigs = new StringBuffer();
+        xmlConfigs.append(JettyBootstrapActivator.DEFAULT_JETTY_ETC_FILES);
+        xmlConfigs.append(",");
+        /*
```
Comment (olamy) [inline jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestOSGiUtil.java]: @janbartel do we need this commented section?

Comment (janbartel) [reply jetty-ee10/jetty-ee10-osgi/test-jetty-ee10-osgi/src/test/java/org/eclipse/jetty/ee10/osgi/test/TestOSGiUtil.java]: Nope, we didn't. Deleted it.

**Review by olamy — APPROVED** [review]
