### PR TITLE
Fix  EE10 removeAttributes

### LINKED ISSUE #10714: Can't remove org.eclipse.jetty.server.Request.maxFormKeys attribute from Request
Related to omnibus issue #10712, tck tests:

```
com/sun/ts/tests/servlet/api/jakarta_servlet/servletrequest/URLClient.java.getAttributeNamesEmptyEnumTest
com/sun/ts/tests/servlet/pluggability/api/jakarta_servlet/servletrequest/URLClient.java.getAttributeNamesEmptyEnumTest
```

These tests iterate over all of the request attributes and remove each one.

However, it is not possible to remove the request attribute `org.eclipse.jetty.server.Request.maxFormKeys`

### PR DESCRIPTION
**Pull request by gregw**
Fixes #10714
Allow all attributes, including synthetic ones, to be removed.

### CODE REVIEW

**Review by joakime — DISMISSED** [review]

File: jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java [hunk 1]
```diff
@@ -261,6 +262,18 @@ public Charset getQueryEncoding()
         return _queryEncoding;
     }
 
+    private static final Object NULL_VALUE = new Object();
```
Comment (janbartel) [inline jetty-ee10/jetty-ee10-servlet/src/main/java/org/eclipse/jetty/ee10/servlet/ServletContextRequest.java]: Move to top of file in field declaration section.

**Review by janbartel — CHANGES_REQUESTED** [review]

**Comment by gregw** [comment]
I'm 99% certain the CI tests are unrelated.   @olamy any thoughts why CI is failing?

**Comment by olamy** [comment]
> I'm 99% certain the CI tests are unrelated. @olamy any thoughts why CI is failing?

the tests  org.eclipse.jetty.tests.distribution.DistributionTests.testWebAppWithProxyAndJPMS(String) are proxying requests to https://eclipse.dev/jetty/javadoc/jetty-12/index.html?overview-summary.html
which looks to have an expired certificate...  (expiration date 16Th October 2023 :) )
you can wait Eclipse fix it, apply similar changes as here (https://github.com/jetty/jetty.project/pull/10686) tagging the test as requiring some external resources, or merge as it as we know the reason

**Review by janbartel — APPROVED** [review]
