### PR TITLE
Immutable local/remote SocketAddress within a ConnectionMetaData

### LINKED ISSUE #10806: Can't always access remote address from RequestLog
**Jetty version(s)**
12.0.2

**Jetty Environment**
ee10

**Java version/vendor** 
OpenJDK Runtime Environment Corretto-17.0.5.8.1 (build 17.0.5+8-LTS)

**OS type/version**
MacOS

**Description**
Using `CustomRequestLog` with the `NCSA_FORMAT`, the remote address is often (but not always) missing from the resulting logs. There doesn't seem to be any pattern to this, often two runs of the exact same test will produce different results (sometimes the remote address is present, other times it is blank).

In debugging through what's going on, I've pinpointed this down to:

* CustomRequestLog uses `Remote.getRemoteAddr(request)` here:

https://github.com/jetty/jetty.project/blob/7be6c4b375de7cf44f71f4f7e7f1c87ed386ef9b/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/CustomRequestLog.java#L821-L824

* getRemoteAddr calls `getRemoteSocketAddress` here:

https://github.com/jetty/jetty.project/blob/7be6c4b375de7cf44f71f4f7e7f1c87ed386ef9b/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L391-L395

* ...but `SocketChannelImpl` has a check that the socket is still open, but finds the socket closed by the time the RequestLog is called and therefore throws an exception:

https://github.com/openjdk/jdk/blob/1ec0d02717b6be4faeb13cd0596d80eea90e81ed/src/java.base/share/classes/sun/nio/ch/SocketChannelImpl.java#L255-L260

### PR DESCRIPTION
**Pull request by gregw**
The local/remote SocketAddress is cached within the ConnectionMetaData or Connection instance, so that any changes are not visible during the request lifetime. 
Ensure that all server Connection types respect HttpConfiguration#getLocalAddress

This is an alternate to both #10861 and #10815 to fix #10806

Co-authored-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by gregw** [comment]
@joakime Can you remind me why `HttpConfiguration#getLocalAddress` was not implemented as a request Customizer?

Could we change the implementation so that if a non null address is set on the HttpConfiguration, then that is equivalent to adding a customizer that will force the address.
We can then remove all the handling in the connections for this.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java [hunk 1]
```diff
@@ -133,7 +133,7 @@ public SocketAddress getLocalSocketAddress()
             SelectableChannel channel = getChannel();
             if (channel instanceof NetworkChannel)
                 return ((NetworkChannel)channel).getLocalAddress();
-            return super.getLocalSocketAddress();
+            return null;
```
Comment (joakime) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java:136]: is returning `null` a wise thing here?
Wouldn't the HttpConnection.localAddress be appropriate here?

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/DatagramChannelEndPoint.java [hunk 2]
```diff
@@ -46,6 +46,21 @@ public DatagramChannel getChannel()
...
+        try
+        {
+            return getChannel().getRemoteAddress();
+        }
+        catch (Exception e)
+        {
+            if (LOG.isTraceEnabled())
+                LOG.trace("ignored", e);
+        }
+        return null;
```
Comment (joakime) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/DatagramChannelEndPoint.java:61]: Can we return HttpConfiguration.remoteAddress here? (not sure, as this is deep in jetty-io)

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HTTP2ServerConnection.java [hunk 3]
```diff
@@ -74,6 +76,8 @@ public HTTP2ServerConnection(Connector connector, EndPoint endPoint, HttpConfigu
         this.listener = listener;
         this.httpConfig = httpConfig;
         this.id = StringUtil.randomAlphaNumeric(16);
+        localSocketAddress = httpConfig.getLocalAddress() != null ? httpConfig.getLocalAddress() : endPoint.getLocalSocketAddress();
+        remoteSocketAddress = endPoint.getRemoteSocketAddress();
```
Comment (joakime) [inline jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HTTP2ServerConnection.java:80]: Seems like we can have a null localSocketAddress and remoteSocketAddress this way, is that wise?

**Review by joakime — COMMENTED** [review]
Just questions about the returning of null and storing of null in final fields.
And seemingly missing handling of HttpConfiguration.(local)Address.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/SelectableChannelEndPoint.java:136]: The super implementation was just to return null.  I removed the default implementation to ensure it was clear that implementations needed to provide this.
So returning null is not new.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/DatagramChannelEndPoint.java (hunk 2 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/DatagramChannelEndPoint.java:61]: No need to.  We are applying HttpConfiguration.localAddress at the level of the Connection, not the endpoint.   There is not HttpConfiguration.remoteAddress

File: jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HTTP2ServerConnection.java (hunk 3 above)
Comment (gregw) [reply jetty-core/jetty-http2/jetty-http2-server/src/main/java/org/eclipse/jetty/http2/server/internal/HTTP2ServerConnection.java:80]: Always could.   If there is no address, there is no address.

**Comment by gregw** [comment]
@joakime I've pushed a few more commits dealing with HttpConfiguration.getLocalAddress().   We were dealing with that in servlet land... which was fine when we didn't have a core request.  Now that it is dealt with at the connection level, we can remove all that handling from the servlet implementation(s).

**Review by joakime — DISMISSED** [review]

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractMetaDataConnection.java [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+ * local and remote addresses.
+ */
+public abstract class AbstractMetaDataConnection extends AbstractConnection implements ConnectionMetaData
+{
+    private final Connector _connector;
+    private final HttpConfiguration _httpConfiguration;
+    private final SocketAddress _localSocketAddress;
+    private final SocketAddress _remoteSocketAddress;
+
+    public AbstractMetaDataConnection(Connector connector, EndPoint endPoint, Executor executor, HttpConfiguration httpConfiguration)
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractMetaDataConnection.java]: No need to pass the `Executor` as it is always taken from the `Connector`.
Also, I'd like to have longer lifecycle components first, so `(Connector, HttpConfiguration, EndPoint)` would be best.

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/DatagramChannelEndPoint.java [hunk 5]
```diff
@@ -46,6 +46,21 @@ public DatagramChannel getChannel()
         return (DatagramChannel)super.getChannel();
     }
 
+    @Override
+    public SocketAddress getRemoteSocketAddress()
```
Comment (sbordet) [inline jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/DatagramChannelEndPoint.java:50]: This should be moved to `SelectableChannelEndPoint` where `getLocalSocketAddress()` is.
And be removed also from `SocketChannelEndPoint`.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/DatagramChannelEndPoint.java (hunk 5 above)
Comment (gregw) [reply jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/DatagramChannelEndPoint.java:50]: You can't as the `getRemoteAddress` on a `DatagramChannel` is a different method than the one on `SocketChannel` and does not exist in `NetworkChannel`.

There is a reason it is as it is.

**Review by joakime — APPROVED** [review]

**Review by sbordet — APPROVED** [review]
