### PR TITLE
Jetty 12.1.x 13529 servletcontext tempdir

### LINKED ISSUE #13529: ServletHolder.initJspServlet() throws exception with MavenWebAppContext on redeploy
**Jetty version(s)**
Jetty 12.0.25, 12.1.0

**Jetty Environment**
ee10, ee11

**Java version/vendor**
tested with Oracle OpenJDK 23.0.1

**OS type/version**
tested with Windows 11

**Description**
`ServletHolder.initJspServlet()` throws `NullPointerException` on redeploy when running with `MavenWebAppContext`. Server starts without errors initially. This happens when scan is enabled to trigger automatic redeploy after changes in resources (`<scan>` value >0). After redeployment, server starts to respond requests with `503 Service unavailable` leaving application in broken state.

Setting tempDirectory manually with `<tempDirectory>${project.build.directory}/tmp</tempDirectory>` didn't change the result. 

Jetty 12.0.23 doesn't have this issue. Tried also with ee11 with different exception from the same place. See both below.

Full error stacktrace whe run with ee10:
```
jakarta.servlet.ServletException: ServletContext Temp Directory is required for JSP to function.
    at org.eclipse.jetty.ee10.servlet.ServletHolder.initJspServlet (ServletHolder.java:690)
    at org.eclipse.jetty.ee10.servlet.ServletHolder.initServlet (ServletHolder.java:628)
    at org.eclipse.jetty.ee10.servlet.ServletHolder.initialize (ServletHolder.java:427)
    at org.eclipse.jetty.ee10.servlet.ServletHandler.lambda$initialize$2 (ServletHandler.java:665)
    at org.eclipse.jetty.util.ExceptionUtil.call (ExceptionUtil.java:370)
    at org.eclipse.jetty.util.ExceptionUtil$MultiException.callAndCatch (ExceptionUtil.java:302)
    at org.eclipse.jetty.ee10.servlet.ServletHandler.lambda$initialize$3 (ServletHandler.java:662)
    at java.util.stream.SortedOps$SizedRefSortingSink.end (SortedOps.java:357)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:571)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:560)
    at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining (StreamSpliterators.java:315)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining (Streams.java:735)
    at java.util.stream.ReferencePipeline$Head.forEach (ReferencePipeline.java:807)
    at org.eclipse.jetty.ee10.servlet.ServletHandler.initialize (ServletHandler.java:685)
    at org.eclipse.jetty.ee10.servlet.ServletContextHandler.startContext (ServletContextHandler.java:1350)
    at org.eclipse.jetty.ee10.webapp.WebAppContext.startWebapp (WebAppContext.java:1426)
    at org.eclipse.jetty.ee10.webapp.WebAppContext.startContext (WebAppContext.java:1384)
    at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0 (ServletContextHandler.java:1066)
    at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call (ContextHandler.java:1582)
    at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart (ServletContextHandler.java:1063)
    at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart (WebAppContext.java:520)
    at org.eclipse.jetty.ee10.maven.plugin.MavenWebAppContext.doStart (MavenWebAppContext.java:312)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:93)
    at org.eclipse.jetty.ee10.maven.plugin.JettyEmbedder.redeployWebApp (JettyEmbedder.java:60)
    at org.eclipse.jetty.ee10.maven.plugin.JettyRunMojo.restartWebApp (JettyRunMojo.java:361)
    at org.eclipse.jetty.ee10.maven.plugin.JettyRunMojo$1.filesChanged (JettyRunMojo.java:170)
    at org.eclipse.jetty.util.Scanner$BulkListener.pathsChanged (Scanner.java:364)
    at org.eclipse.jetty.util.Scanner$BulkListener.pathsChanged (Scanner.java:343)
    at org.eclipse.jetty.util.Scanner.reportDifferences (Scanner.java:918)
    at org.eclipse.jetty.util.Scanner.scan (Scanner.java:817)
    at org.eclipse.jetty.util.Scanner$ScanTask.run (Scanner.java:142)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:572)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:304)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
    at java.lang.Thread.run (Thread.java:1575)
```

Full error stacktrace whe run with ee11:
```
java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "tmp" is null
    at org.eclipse.jetty.ee11.servlet.ServletHolder.initJspServlet (ServletHolder.java:689)
    at org.eclipse.jetty.ee11.servlet.ServletHolder.initServlet (ServletHolder.java:628)
    at org.eclipse.jetty.ee11.servlet.ServletHolder.initialize (ServletHolder.java:427)
    at org.eclipse.jetty.ee11.servlet.ServletHandler.lambda$initialize$2 (ServletHandler.java:666)
    at org.eclipse.jetty.util.ExceptionUtil.call (ExceptionUtil.java:370)
    at org.eclipse.jetty.util.ExceptionUtil$MultiException.callAndCatch (ExceptionUtil.java:302)
    at org.eclipse.jetty.ee11.servlet.ServletHandler.lambda$initialize$3 (ServletHandler.java:663)
    at java.util.stream.SortedOps$SizedRefSortingSink.end (SortedOps.java:357)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:571)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:560)
    at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining (StreamSpliterators.java:315)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining (Streams.java:735)
    at java.util.stream.ReferencePipeline$Head.forEach (ReferencePipeline.java:807)
    at org.eclipse.jetty.ee11.servlet.ServletHandler.initialize (ServletHandler.java:686)
    at org.eclipse.jetty.ee11.servlet.ServletContextHandler.startContext (ServletContextHandler.java:1345)
    at org.eclipse.jetty.ee11.webapp.WebAppContext.startWebapp (WebAppContext.java:1311)
    at org.eclipse.jetty.ee11.webapp.WebAppContext.startContext (WebAppContext.java:1269)
    at org.eclipse.jetty.ee11.servlet.ServletContextHandler.lambda$doStart$0 (ServletContextHandler.java:1062)
    at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call (ContextHandler.java:1582)
    at org.eclipse.jetty.ee11.servlet.ServletContextHandler.doStart (ServletContextHandler.java:1059)
    at org.eclipse.jetty.ee11.webapp.WebAppContext.doStart (WebAppContext.java:498)
    at org.eclipse.jetty.ee11.maven.plugin.MavenWebAppContext.doStart (MavenWebAppContext.java:312)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:93)
    at org.eclipse.jetty.ee11.maven.plugin.JettyEmbedder.redeployWebApp (JettyEmbedder.java:60)
    at org.eclipse.jetty.ee11.maven.plugin.JettyRunMojo.restartWebApp (JettyRunMojo.java:361)
    at org.eclipse.jetty.ee11.maven.plugin.JettyRunMojo$1.filesChanged (JettyRunMojo.java:170)
    at org.eclipse.jetty.util.Scanner$BulkListener.pathsChanged (Scanner.java:364)
    at org.eclipse.jetty.util.Scanner$BulkListener.pathsChanged (Scanner.java:343)
    at org.eclipse.jetty.util.Scanner.reportDifferences (Scanner.java:918)
    at org.eclipse.jetty.util.Scanner.scan (Scanner.java:817)
    at org.eclipse.jetty.util.Scanner$ScanTask.run (Scanner.java:142)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:572)
    at java.util.concurrent.FutureTask.run (FutureTask.java:317)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:304)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
    at java.lang.Thread.run (Thread.java:1575)
```

**How to reproduce?**
1. Download attached zip and unpack.
2. run it with `mvn jetty:run`
3. touch `target/classes/com/example/HelloWorldServlet.class` file and wait for redeployment (scan is set to 5 seconds)
4. see error in console `jakarta.servlet.ServletException: ServletContext Temp Directory is required for JSP to function.`

```
@WebServlet(urlPatterns = {"/*"}, loadOnStartup = 1)
public class HelloWorldServlet extends HttpServlet {
    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException {
        response.getOutputStream().println("Hello World");
    }
}
```
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>war</packaging>
    <groupId>org.eclipse.jetty.demo</groupId>
    <artifactId>jetty-helloworld-webapp</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <jetty.version>12.1.0</jetty.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.jetty.ee10</groupId>
            <artifactId>jetty-ee10-annotations</artifactId>
            <version>${jetty.version}</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.2</version>
                <configuration>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.eclipse.jetty.ee10</groupId>
                <artifactId>jetty-ee10-maven-plugin</artifactId>
                <version>${jetty.version}</version>
                <configuration>
                    <scan>5</scan>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

[jetty-temp-dir-test.zip](https://github.com/user-attachments/files/22041323/jetty-temp-dir-test.zip)

### PR DESCRIPTION
**Pull request by janbartel**
Fixes #13529.

The issue is that after a context restart, the value of the `ServletContext.TEMPDIR` variable should have been preserved, because it was set via a call to `WebAppContext.setTempDirectory()`, but it was reported as unset. Investigation revealed this was due to the way the `Attributes` class worked, which was retaining the value of an unset attribute, and marking it as `REMOVED`, which means it would always be reported as unset.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 1]
```diff
@@ -919,9 +919,11 @@ protected void doStop() throws Exception
 
     protected void cleanupAfterStop() throws Exception
     {
-        File tempDirectory = getTempDirectory();
+        // Restore persistent attributes
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: "Restore" is weird here.
I would say "Clear the transient attributes", as the persistent are not really "restored", they are there and won't be touched.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java [hunk 2]
```diff
@@ -503,22 +503,35 @@ public Attributes getPersistentAttributes()
             return getWrapped();
         }
 
+        /**
+         * Clear the layer attributes, leaving the persistent attributes intact / restored
+         */
+        public void clearLayer()
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java]: Rename to `clearLayerAttributes()`.
It matches with other methods of this class such as `getPersistentAttributes()`, etc.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java [hunk 3]
```diff
@@ -503,22 +503,35 @@ public Attributes getPersistentAttributes()
...
         {
-            Object p = super.getAttribute(name);
+            Object persistentValue = super.getAttribute(name);
             try
             {
-                Object v = _layer.setAttribute(name, REMOVED);
-                if (v == REMOVED)
+                if (persistentValue == null)
+                {
+                    Object oldValue = _layer.removeAttribute(name);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java]: Now `_layer.removeAttribute(name)` is called twice: here and in the `finally` block.

I'm not sure why the logic needs to be changed if `persistentValue == null`?
A clarifying comment would help.

**Review by sbordet — CHANGES_REQUESTED** [review]
I find strange that there are only changed to ee10.
While I saw that ee11's `ServletContextHandler` is different, I would like the tests to be present in ee11 too, so that we're sure that the behavior is the same in both ee10 and ee11.

**Comment by janbartel** [comment]
@sbordet your changes have been addressed, can I get a re-review pls?

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java (hunk 3 above)
Comment (sbordet) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java]: This has not been addressed, as `_layer.removeAttribute(name)` is still called twice.
Please add comments because the new logic is unclear.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java [hunk 4]
```diff
@@ -503,22 +503,35 @@ public Attributes getPersistentAttributes()
...
+                }
+                Object oldValue = _layer.setAttribute(name, REMOVED);
+                if (oldValue == REMOVED)
                     return null;
-                if (v != null)
-                    return v;
-                return p;
+                if (oldValue != null)
+                    return oldValue;
+                return persistentValue;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java]: I don't think this is right either.

I would expect that calling `removeAttribute("foo") == <obj>` followed by `getAttribute("foo")` would yield `null`.

But here, we return the persistent value from `removeAttribute()`, which is persistent so it's not removed.

We should return `null` because we have not removed any value.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java (hunk 4 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java]: I've reworked this method.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java [hunk 5]
```diff
@@ -503,24 +503,35 @@ public Attributes getPersistentAttributes()
...
-                if (v != null)
-                    return v;
-                return p;
-            }
-            finally
-            {
-                if (p == null)
-                    _layer.removeAttribute(name);
+                // There is no persistent value, so just remove from the layer
+                Object oldValue = _layer.removeAttribute(name);
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java]: If the persistent attribute is not present, then there cannot be a `REMOVED` layer attribute (as there is nothing to "hide").

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java [hunk 6]
```diff
@@ -503,24 +503,35 @@ public Attributes getPersistentAttributes()
...
+
+            // There is a persistent value, so we need to hide it by marking it as REMOVED in the layer
+            Object oldValue = _layer.getAttribute(name);
+            // if it was already marked as REMOVED, then nothing to do
+            if (oldValue == REMOVED)
+                return null;
+            // otherwise mark it as REMOVED
+            _layer.setAttribute(name, REMOVED);
+            // and return either the persistent value or any transient value that was there
+            return oldValue == null ? persistentValue : oldValue;
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java]:
```suggestion
            Object oldValue = _layer.getAttribute(name);
            if (oldValue == REMOVED)
                return null;

            Object persistentValue = super.getAttribute(name);
            if (oldValue != null)
            {
                if (persistentValue == null)
                {
                    // There is no persistent value, so just remove from the layer.
                    return _layer.removeAttribute(name);
                }    
                // Hide the persistent value.
                _layer.setAttribute(name, REMOVED);
                return oldValue;
            }
            else
            {
                if (persistentValue == null)
                    return null;
                // Hide the persistent value.
                _layer.setAttribute(name, REMOVED);
                return persistentValue;
            }    
```

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java (hunk 5 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java]: @sbordet The persistent layer may be changed underneath this layer.   There could have been a persistent value that was removed, so a REMOVED value is here.  The persistent value might then have been removed by something with access to the wrapped Attributes, and finally the call here is made to remove the same attribute.  It will find a null persistent value and a REMOVE, so it returns null after removing the REMOVE.

The wrapped Attributes is only persistent from this layer

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java (hunk 6 above)
Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Attributes.java]: I prefer my version.  It is shorter, simpler, clearer and more correct with regards to mutations of the wrapped Attributes....

actually I can see an even shorter, simpler, clearer version..... stand by....

**Review by sbordet — APPROVED** [review]
