### PR TITLE
Issue #6017 - Start Property Overrides

### LINKED ISSUE #6017: Property overriding does not work
**Jetty version**
10.0.x

**Description**
These commands:

```
$ java -jar $JETTY_HOME/start.jar --add-modules=ssl,https,test-keystore
$ java -jar $JETTY_HOME/start.jar jetty.sslContext.keyStorePath=bogus
```

produce:

```
java.lang.IllegalStateException: /tmp/jetty.base/etc/test-keystore.p12 is not a valid keystore
```

The wrong property value is reported in the error message.

But furthermore:

```
$ java -jar $JETTY_HOME/start.jar jetty.sslContext.keyStorePassword=bogus
```

starts Jetty without errors.

There is something wrong in how properties are handled.

### PR DESCRIPTION
**Pull request by joakime**
Improve start property behavior with regards to properties and overrides.

With this PR Default properties from `*.mod` files can be overridden by either in `${jetty.base}/start.d/*.ini` configuration or command line.

### CODE REVIEW

File: jetty-start/src/main/java/org/eclipse/jetty/start/Module.java [hunk 1]
```diff
@@ -408,7 +408,29 @@ public void process(BaseHome basehome) throws FileNotFoundException, IOException
...
+                                    {
+                                        _defaultConfig.add(String.format("%s?=%s", key, value));
+                                    }
+                                }
+                                else
+                                {
+                                    _defaultConfig.add(line);
+                                }
+                            }
                                 break;
```
Comment (sbordet) [inline jetty-start/src/main/java/org/eclipse/jetty/start/Module.java:433]: Move `break` inside braces.

File: jetty-start/src/test/java/org/eclipse/jetty/start/usecases/PropertyOverrideTest.java [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+            "${jetty.home}/lib/main.jar",
+            "${jetty.home}/lib/other.jar"
+        );
+        List<String> actualLibs = results.getLibs();
+        assertThat("Libs", actualLibs, ordered(expectedLibs));
+
+        // === Validate Resulting Properties
+        List<String> expectedProperties = new ArrayList<>();
+        // we should see value from command line
+        expectedProperties.add("" + "jetty.sslContext.keyStorePassword" + "=storepwd");
```
Comment (sbordet) [inline jetty-start/src/test/java/org/eclipse/jetty/start/usecases/PropertyOverrideTest.java]: Remove all string concatenation.

File: tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java [hunk 3]
```diff
@@ -964,4 +965,43 @@ public void testModuleWithExecEmitsWarning() throws Exception
...
+        String jettyVersion = System.getProperty("jettyVersion");
+        JettyHomeTester distribution = JettyHomeTester.Builder.newInstance()
+            .jettyVersion(jettyVersion)
+            .mavenLocalRepository(System.getProperty("mavenRepoPath"))
+            .build();
+
+        Path jettyBase = distribution.getJettyBase();
+        Path jettyBaseModules = jettyBase.resolve("modules");
+        Files.createDirectories(jettyBaseModules);
+        String passwordProperty = "jetty.sslContext.keyStorePath";
```
Comment (sbordet) [inline tests/test-distribution/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java]: Variable should be named `pathProperty`.

**Review by sbordet — CHANGES_REQUESTED** [review]

**Review by sbordet — DISMISSED** [review]

**Review by sbordet — APPROVED** [review]
