### PR TITLE
Issue #12429 - case-insensitive headers for websocket

### LINKED ISSUE #12429: HandshakeRequest getHeaders are case sensitive.
**Jetty version(s)**
12.0.14

**Jetty Environment**
ee8

**Java version/vendor** `(use: java -version)`
17.0.12

**OS type/version**
Ubuntu 24.04.1 LTS

**Description**
In JsrHandshakeRequest the method getHeaders() is case sensitive.

In JavaEE8 and JakartaEE9/10 
https://javaee.github.io/javaee-spec/javadocs/javax/websocket/server/HandshakeRequest.html#getHeaders--
_Return the read only Map of Http Headers that came with the handshake request. The header names are case insensitive._

**How to reproduce?**

* In Jetty 9.4.56 : 
  * hReq..getHeaders().get("cookie") return headers for Cookie
  * hReq..getHeaders().get("Cookie")  return headers for Cookie
* In Jetty 12.0.14 :
  * hReq..getHeaders().get("cookie") is null
  * hReq..getHeaders().get("Cookie") return headers for Cookie

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Issue #12429

Add a new static method `HttpFields.asMap(HttpFields fields)` and use it everywhere in WebSocket where the `HttpFields` are converted into a `Map<String, List<String>>` so that the headers in the map are treated as case-insensitive.

### CODE REVIEW

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 1]
```diff
@@ -927,6 +928,13 @@ default int size()
         return size;
     }
 
+    static Map<String, List<String>> asMap(HttpFields fields)
+    {
+        Map<String, List<String>> headers = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
+        fields.getFieldNamesCollection().forEach(name -> headers.putIfAbsent(name, fields.getValuesList(name)));
+        return headers;
+    }
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: This could be more efficiently implemented without the temporary name collection:
```suggestion
    static Map<String, List<String>> asMap(HttpFields fields)
    {
        Map<String, List<String>> headers = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        for (HttpField f : fields)
        {
            if (!headers.containsKey(f.getName()))
            {
                HttpHeader header = f.getHeader();
                headers.put(f.getName(), header == null ? fields.getValuesList(f.getName()) : fields.getValuesList(header));
            }
        }
        return headers;
    }
```

File: jetty-core/jetty-websocket/jetty-websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/internal/DelegatedJettyClientUpgradeRequest.java [hunk 2]
```diff
@@ -78,7 +79,7 @@ public List<String> getHeaders(String name)
     @Override
     public Map<String, List<String>> getHeaders()
     {
-        return null;
+        return Collections.unmodifiableMap(HttpFields.asMap(delegate.getHeaders()));
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/internal/DelegatedJettyClientUpgradeRequest.java]: Does it need to be unmodifieable?
Are we sure the delegate is still valid when this is called? Perhaps do in the constructor?

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeRequestDelegate.java [hunk 3]
```diff
@@ -73,14 +72,7 @@ public int getHeaderInt(String name)
...
     {
-        Map<String, List<String>> result = new LinkedHashMap<>();
-        HttpFields headers = request.getHeaders();
-        for (HttpField header : headers)
-        {
-            String name = header.getName();
-            result.put(name, headers.getValuesList(name));
-        }
-        return result;
+        return HttpFields.asMap(request.getHeaders());
```
Comment (gregw) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeRequestDelegate.java:75]: Sometimes you've made it immutable, other times you have not?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeRequestDelegate.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeRequestDelegate.java:75]: I didn't look too deeply into this I just tried to maintain the behavior we had before. So if it was already immutable I just kept it that way.

But I will now do a deeper review of each case and assess whether it should be immutable or not.

Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeRequestDelegate.java:75]: ### Javax/Jakarta API
- On `JsrUpgradeListener.onHandshakeRequest`, the request headers should be mutable because you can set custom headers.
- During server websocket negotiation (`JsrHandshakeRequest`/`JsrHandshakeResponse`) only the request headers should be immutable because you can't change request headers.
- On the `JsrUpgradeListener.onHandshakeResponse`, the headers should be immutable because the response has already been received.

### Jetty API
- For the `ClientUpgradeRequest`, they should be mutable so request headers can be set.
- For the `DelegatedJettyClientUpgradeRequest` and `DelegatedJettyClientUpgradeResponse` they should be immutable because this is kept after the upgrade and aren't designed to be modified.
- For `UpgradeRequestDelegate` and `UpgradeResponseDelegate` they should be immutable because they are kept after the upgrade and are not intended to be modified.
- In `DelegatedServerUpgradeRequest` the headers should be immutable because this is during the negotiation.
- In `DelegatedServerUpgradeResponse` they should be mutable so response headers can be set in the upgrade response during negotiation.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Wouldn't it be easier to read as ...

``` java
    static Map<String, List<String>> asMap(HttpFields fields)
    {
        Map<String, List<String>> headers = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        for (HttpField f : fields)
            headers.putIfAbsent(f.getName(), fields.getValueList(f.getHeader());
        return headers;
    }
```

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeRequestDelegate.java (hunk 3 above)
Comment (joakime) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeRequestDelegate.java:75]: Just would like to point out that some people use the upgrade process to modify (strip out / remove) the websocket compression extension.

That way the actual upgrade does not use it and upgrades without compression.
I don't see a need for it to be immutable during upgrade.

But after upgrade, once the websocket is connected, the request is already done, nothing more is really used from it in a websocket sense.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 1 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: @joakime the problem with that version, is that if a header is repeated, then the value list is generated multiple times, but only used once.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeRequestDelegate.java (hunk 3 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeRequestDelegate.java:75]: > some people use the upgrade process to modify (strip out / remove) the websocket compression extension

Yep, this is why the response headers are mutable during the server side negotiation. But it doesn't make sense for the request headers to be mutable at this stage.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/internal/DelegatedJettyClientUpgradeRequest.java (hunk 2 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-client/src/main/java/org/eclipse/jetty/websocket/client/internal/DelegatedJettyClientUpgradeRequest.java]: Now the `asMap` method now determines whether it is immutable or not based on whether an instance of `HttpFields` was provided or `HttpFields.Mutable`

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: @gregw then use `computeIfAbsent` via a lamda ...

``` java
    static Map<String, List<String>> asMap(HttpFields fields)
    {
        TreeMap<String, List<String>> headers = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        for (HttpField f : fields)
            headers.computeIfAbsent(f.getName(), k -> fields.getValueList(f.getHeader());
        return headers;
    }
```

**Comment by lachlan-roberts** [comment]
@gregw @joakime I have changed it so that the `HttpFields.asMap` decides if the map is modifiable or not. If it is not modifiable it will wrap the `HttpFields` instead of being backed by a `TreeMap`, so that any modification to the map is also made to the `HttpFields`.

I have also reviewed the error handling for the `WebSocketCreator`s, which I found to be incorrect in some places.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFieldsMap.java [hunk 4]
```diff
@@ -0,0 +1,151 @@
...
+import java.util.AbstractMap;
+import java.util.AbstractSet;
+import java.util.Iterator;
+import java.util.List;
+import java.util.Objects;
+import java.util.Set;
+
+import org.eclipse.jetty.util.StringUtil;
+
+class HttpFieldsMap extends AbstractMap<String, List<String>>
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFieldsMap.java]: javadoc

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 5]
```diff
@@ -927,6 +928,34 @@ default int size()
...
+
+    /**
+     * @param fields the {@link HttpFields} to convert to a {@link Map}.
+     * @return a {@link Map} where changes to the contents will be reflected in the supplied {@link HttpFields}.
+     */
+    static Map<String, List<String>> asMap(HttpFields.Mutable fields)
+    {
+        return new HttpFieldsMap(fields);
+    }
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: I'm not sure that using a separate signature is the right way to go, as often a mutable HttpFields is not held as a Mutable.    I think an instanceof Mutable check in the other method is a better way to go.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 6]
```diff
@@ -927,6 +928,34 @@ default int size()
...
+        for (HttpField f : fields)
+        {
+            if (!headers.containsKey(f.getName()))
+            {
+                HttpHeader header = f.getHeader();
+                List<String> values = header == null ? fields.getValuesList(f.getName()) : fields.getValuesList(header);
+                headers.put(f.getName(), Collections.unmodifiableList(values));
+            }
+        }
+        return Collections.unmodifiableMap(headers);
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: The other thing to consider here is just wrapping as a HttpFieldsMap and then returning the asImmutable version of it.   That may be simpler and easier than doing the full copy here?

**Review by gregw — CHANGES_REQUESTED** [review]
Looking good, but a few niggles

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 5 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: I think I might just separate these into separate methods, `asMap()` and `asMutableMap()`, because I think its clearer reading the code to understand what the intention is. And you can check all the places each of them are called to verify they are correct.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 6 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: I considered doing this, but I would have to create a separate implementation of the `HttpFieldsMap` which takes `HttpFields` instead of `HttpFields.Mutable`.

Comment (lachlan-roberts) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: I added this.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java [hunk 7]
```diff
@@ -927,6 +927,24 @@ default int size()
...
+
+    /**
+     * @param fields the {@link HttpFields} to convert to a {@link Map}.
+     * @return a {@link Map} where changes to the contents will be reflected in the supplied {@link HttpFields}.
+     */
+    static Map<String, List<String>> asMutableMap(HttpFields.Mutable fields)
+    {
+        return new HttpFieldsMap.Mutable(fields);
+    }
+
```
Comment (gregw) [inline jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Meh!

```suggestion
    /**
     * @param fields the {@link HttpFields} to convert to a {@link Map}.
     * @return an unmodifiable {@link Map} representing the contents of the {@link HttpFields}.
     */
    static Map<String, List<String>> asMap(HttpFields fields)
    {
        return (fields instanceof HttpFields.Mutable mutable)
            ? new HttpFieldsMap.Mutable(mutable);
            : new HttpFieldsMap.Immutable(fields);
    }
```

This give mutable for mutable, immutable for immutable and you don't have to worry about the actual type.   We already do similar instanceof checks in MutableHttpFields, so best to follow that pattern

**Review by gregw — CHANGES_REQUESTED** [review]
Sorry, but I do think one method is best.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 6 above)
Comment (gregw) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Nice!

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 7 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: I'll do this, but I do think it makes the code a lot more confusing.

Before you could easily view where each method is called to see where we allow the application to modify the headers, now it is not possible.

Comment (lachlan-roberts) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Done.

File: jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java]: Resolving this as now we are wrapping the `HttpFields` instead of creating a `TreeMap`.

**Review by gregw — DISMISSED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/ServerWebSocketContainer.java [hunk 8]
```diff
@@ -359,14 +360,12 @@ private org.eclipse.jetty.websocket.core.server.WebSocketCreator newWebSocketCre
...
-                Object webSocket = creator.createWebSocket(new ServerUpgradeRequestDelegate(rq), new ServerUpgradeResponseDelegate(rq, rs), cb);
-                if (webSocket == null)
-                    cb.succeeded();
-                return webSocket;
+                return creator.createWebSocket(new ServerUpgradeRequestDelegate(rq), new ServerUpgradeResponseDelegate(rq, rs), cb);
             }
             catch (Throwable x)
             {
-                cb.failed(x);
+                LOG.warn("Could not create WebSocket endpoint");
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/ServerWebSocketContainer.java]: I'd change this to debug level, because a failure can be triggered by the remote client, and we do not want to raise a warning or clog the server logs.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseDelegate.java [hunk 9]
```diff
@@ -64,14 +63,7 @@ public Set<String> getHeaderNames()
...
     {
-        Map<String, List<String>> result = new LinkedHashMap<>();
-        HttpFields.Mutable headers = response.getHeaders();
-        for (HttpField header : headers)
-        {
-            String name = header.getName();
-            result.put(name, headers.getValuesList(name));
-        }
-        return result;
+        return Collections.unmodifiableMap(HttpFields.asMap(response.getHeaders()));
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseDelegate.java]: Why the unmodifiable wrapper here?

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/JakartaWebSocketServerContainer.java [hunk 10]
```diff
@@ -322,9 +322,9 @@ public void upgradeHttpToWebSocket(Object httpServletRequest, Object httpServlet
             servletContextRequest.setAttribute(WebSocketConstants.WEBSOCKET_WRAPPED_RESPONSE_ATTRIBUTE, response);
 
             if (handshaker.upgradeRequest(negotiator, servletContextRequest, servletContextResponse, callback, components, defaultCustomizer))
-            {
                 callback.block();
-            }
+            else
+                throw new IllegalStateException("Invalid WebSocket Upgrade Request");
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/JakartaWebSocketServerContainer.java:327]: I would use `WebSocketException` here, since `handshaker.upgradeRequest()` throws that.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/internal/JakartaWebSocketCreator.java [hunk 11]
```diff
@@ -169,7 +167,7 @@ public Map<String, Object> getUserProperties()
         catch (Throwable x)
         {
             LOG.warn("Unable to create websocket: {}", config.getEndpointClass().getName(), x);
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/internal/JakartaWebSocketCreator.java]: Use `debug` level here.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java [hunk 12]
```diff
@@ -78,7 +77,6 @@ public static class AnnotatedEndpointConfigurator extends ClientEndpointConfig.C
         @Override
         public void afterResponse(HandshakeResponse hr)
         {
-            hr.getHeaders().put("X-Test", Collections.singletonList("Extra"));
             super.afterResponse(hr);
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java]: This method now just calls `super`, can it be removed?
Was it ok to remove the "headers.put()`, or was it not tested anywhere?

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java [hunk 13]
```diff
@@ -158,7 +160,8 @@ public void addMapping(String pathSpec, JettyWebSocketCreator creator)
             }
             catch (Throwable t)
             {
-                cb.failed(t);
+                LOG.warn("Could not create WebSocket endpoint", t);
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java]: Use `debug` level.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java [hunk 14]
```diff
@@ -203,12 +206,14 @@ public boolean upgrade(JettyWebSocketCreator creator, HttpServletRequest request
...
                 Object webSocket = creator.createWebSocket(new DelegatedServerUpgradeRequest(req), new DelegatedServerUpgradeResponse(resp));
-                cb.succeeded();
+                if (webSocket == null)
+                    cb.succeeded();
                 return webSocket;
             }
             catch (Throwable t)
             {
-                cb.failed(t);
+                LOG.warn("Could not create WebSocket endpoint", t);
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java]: Use `debug` level.

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/JakartaWebSocketServerContainer.java [hunk 15]
```diff
@@ -323,9 +323,9 @@ public void upgradeHttpToWebSocket(Object httpServletRequest, Object httpServlet
             baseRequest.setAttribute(WebSocketConstants.WEBSOCKET_WRAPPED_RESPONSE_ATTRIBUTE, response);
 
             if (handshaker.upgradeRequest(negotiator, baseRequest, baseResponse, callback, components, defaultCustomizer))
-            {
                 callback.block();
-            }
+            else
+                throw new IllegalStateException("Invalid WebSocket Upgrade Request");
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/JakartaWebSocketServerContainer.java:328]: Use `WebSocketException` here.

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/internal/JakartaWebSocketCreator.java [hunk 16]
```diff
@@ -168,8 +166,8 @@ public Map<String, Object> getUserProperties()
         }
         catch (Throwable x)
         {
-            LOG.warn("Unable to create websocket: {}", config.getEndpointClass().getName(), x);
-            callback.failed(x);
+            LOG.warn("Unable to create WebSocket: {}", config.getEndpointClass().getName(), x);
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/internal/JakartaWebSocketCreator.java]: Use `debug` level.

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee9/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java [hunk 17]
```diff
@@ -78,7 +77,6 @@ public static class AnnotatedEndpointConfigurator extends ClientEndpointConfig.C
         @Override
         public void afterResponse(HandshakeResponse hr)
         {
-            hr.getHeaders().put("X-Test", Collections.singletonList("Extra"));
             super.afterResponse(hr);
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee9/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java]: Remove method that only calls `super`?

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee9/websocket/server/JettyWebSocketServerContainer.java [hunk 18]
```diff
@@ -155,12 +156,14 @@ public void addMapping(String pathSpec, JettyWebSocketCreator creator)
...
                 Object webSocket = creator.createWebSocket(new DelegatedServerUpgradeRequest(req), new DelegatedServerUpgradeResponse(resp));
-                cb.succeeded();
+                if (webSocket == null)
+                    cb.succeeded();
                 return webSocket;
             }
             catch (Throwable t)
             {
-                cb.failed(t);
+                LOG.warn("Could not create WebSocket endpoint", t);
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee9/websocket/server/JettyWebSocketServerContainer.java]: Use `debug` level.

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee9/websocket/server/JettyWebSocketServerContainer.java [hunk 19]
```diff
@@ -205,12 +208,14 @@ public boolean upgrade(JettyWebSocketCreator creator, HttpServletRequest request
...
                 Object webSocket = creator.createWebSocket(new DelegatedServerUpgradeRequest(req), new DelegatedServerUpgradeResponse(resp));
-                cb.succeeded();
+                if (webSocket == null)
+                    Response.writeError(req, resp, cb, HttpStatus.INTERNAL_SERVER_ERROR_500, "Could not create WebSocket endpoint");
                 return webSocket;
             }
             catch (Throwable t)
             {
-                cb.failed(t);
+                LOG.warn("Could not create WebSocket endpoint", t);
```
Comment (sbordet) [inline jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee9/websocket/server/JettyWebSocketServerContainer.java]: Use `debug` level.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/ServerWebSocketContainer.java (hunk 8 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/ServerWebSocketContainer.java]: Done.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseDelegate.java (hunk 9 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseDelegate.java]: Because this is not used in the negotiation but stored in the `FrameHandler` after websocket upgrade. So it makes no sense for them to alter the HttpHeaders after the websocket upgrade is completed.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/JakartaWebSocketServerContainer.java (hunk 10 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/JakartaWebSocketServerContainer.java:327]: The javadoc for `jakarta.websocket.server.ServerContainer#upgradeHttpToWebSocket` says 
> Throws: IllegalStateException – if the provided request does not meet the requirements of the WebSocket handshake

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/internal/JakartaWebSocketCreator.java (hunk 11 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/internal/JakartaWebSocketCreator.java]: I think this really should be a warning though.
We only get here if the class could not be constructed.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java (hunk 12 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java]: It was not tested that the header was set, because it was only set in this local map returned from getHeaders(), this is after the response has been received on the client. 

So these headers are now immutable.

I will leave the class because it is tested that a custom Configurator can be set, but I will remove the method override.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java (hunk 13 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java]: done

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java (hunk 14 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java]: done

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/JakartaWebSocketServerContainer.java (hunk 15 above)
Comment (lachlan-roberts) [reply jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/JakartaWebSocketServerContainer.java:328]: That would be a violation of the contract defined in jakarta websocket 2.1

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/internal/JakartaWebSocketCreator.java (hunk 16 above)
Comment (lachlan-roberts) [reply jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/internal/JakartaWebSocketCreator.java]: I think this should be a warning.

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee9/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java (hunk 17 above)
Comment (lachlan-roberts) [reply jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee9/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java]: Done.

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee9/websocket/server/JettyWebSocketServerContainer.java (hunk 18 above)
Comment (lachlan-roberts) [reply jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee9/websocket/server/JettyWebSocketServerContainer.java]: Done.

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee9/websocket/server/JettyWebSocketServerContainer.java (hunk 19 above)
Comment (lachlan-roberts) [reply jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee9/websocket/server/JettyWebSocketServerContainer.java]: Done.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseDelegate.java (hunk 9 above)
Comment (sbordet) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseDelegate.java]: I think it is assuming too much of what the callers of this method are doing.
If the caller needs it unmodifiable, should be the caller wrapping it.

Besides, should not all the other methods wrap as unmodifiable?
For example, `getHeaderNames()`, getHeaders(String)`?

I'm fine to make everything unmodifiable in this class, since it's only used in 1 place, or have the 1 caller to make everything unmodifiable, but not half/half.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/internal/JakartaWebSocketCreator.java (hunk 11 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/internal/JakartaWebSocketCreator.java]: I don't think there is a point to make a log warn, as nobody would look at the logs if there is a problem instantiating the endpoint class.
We don't log much at warn level to avoid monitoring consoles to go crazy if that mapping gets hammered by a client.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java (hunk 12 above)
Comment (sbordet) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java]: Override was not removed?

File: jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/internal/JakartaWebSocketCreator.java (hunk 16 above)
Comment (sbordet) [reply jetty-ee9/jetty-ee9-websocket/jetty-ee9-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee9/websocket/jakarta/server/internal/JakartaWebSocketCreator.java]: Ditto as the other.

**Review by sbordet — CHANGES_REQUESTED** [review]
I replied to your comments.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java (hunk 12 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-tests/src/test/java/org/eclipse/jetty/ee10/websocket/jakarta/tests/client/AnnotatedClientEndpointTest.java]: just forgot to push the changes

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/internal/JakartaWebSocketCreator.java (hunk 11 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jakarta-server/src/main/java/org/eclipse/jetty/ee10/websocket/jakarta/server/internal/JakartaWebSocketCreator.java]: Changed to debug.

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseDelegate.java (hunk 9 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseDelegate.java]: > Besides, should not all the other methods wrap as unmodifiable?
> For example, getHeaderNames(), getHeaders(String)`?

The difference is that `getHeaders().put(....)` will add actually modify the `HttpFields` on the response.
But `getHeaderNames()` and `getHeaders(String)` will return a new `Set` or `List` and so will not change the underlying `HttpFields` if you add to them.

Anyway, I removed the unmodifiableMap... But it is completely wrong for the application to modify the headers of the `Response` after we have fully upgraded to WebSocket.

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java [hunk 20]
```diff
@@ -203,12 +207,15 @@ public boolean upgrade(JettyWebSocketCreator creator, HttpServletRequest request
...
+                if (webSocket == null)
+                    cb.succeeded();
                 return webSocket;
             }
             catch (Throwable t)
             {
-                cb.failed(t);
+                if (LOG.isDebugEnabled())
+                    LOG.debug("Could not create WebSocket endpoint", t);
+                Response.writeError(req, resp, cb, HttpStatus.INTERNAL_SERVER_ERROR_500, "Could not create WebSocket endpoint");
```
Comment (sbordet) [inline jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java]: Can you check whether `cb.failed()` is enough, because the javadocs of `creator.createWebSocket()` say to use `JettyServerUpgradeResponse. sendError()`.

File: jetty-core/jetty-websocket/jetty-websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/internal/CreatorNegotiator.java [hunk 21]
```diff
@@ -59,7 +61,7 @@ public FrameHandler negotiate(ServerUpgradeRequest request, ServerUpgradeRespons
         }
         catch (Throwable t)
         {
-            callback.failed(t);
+            Response.writeError(request, response, callback, HttpStatus.INTERNAL_SERVER_ERROR_500, t.getMessage());
```
Comment (sbordet) [inline jetty-core/jetty-websocket/jetty-websocket-core-server/src/main/java/org/eclipse/jetty/websocket/core/server/internal/CreatorNegotiator.java]: I think `cb.failed()` is more correct, as it will fail a callback that may come from the upper layer (e.g. Servlet), so the right `Servlet` mechanism will be used to send an error.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseDelegate.java (hunk 9 above)
Comment (gregw) [reply jetty-core/jetty-websocket/jetty-websocket-jetty-server/src/main/java/org/eclipse/jetty/websocket/server/internal/UpgradeResponseDelegate.java]: The response header fields are switched internally to be immutable when the response is committed.  So this should be safe.

**Review by gregw — APPROVED** [review]

File: jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java (hunk 20 above)
Comment (lachlan-roberts) [reply jetty-ee10/jetty-ee10-websocket/jetty-ee10-websocket-jetty-server/src/main/java/org/eclipse/jetty/ee10/websocket/server/JettyWebSocketServerContainer.java]: I think `cb.failed()` is probably better. This will result in the `JettyWebSocketServerContainer#upgrade` throwing, which can be caught and handled by their application, or if its not caught will result in a `sendError()` anyway.

**Review by sbordet — APPROVED** [review]
