### PR TITLE
Make `Fields` interpret null values as empty strings

### LINKED ISSUE #12018: NPE when passing null value to Request.param
**Jetty version(s)**
Jetty 12.0.10

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)

**OS type/version**
Windows 11

**Description**
When passing null as a query parameter value to `Request.param`, a NullPointerException is thrown. It happens when the value is wrapped in a List using `List.of`, which doesn't like null values.

I don't think this is intentional. With Jetty 11, null values were allowed. Also, the value is passed to a private method `urlEncode`, which allows null and is only used for query parameters:
https://github.com/jetty/jetty.project/blob/803fe5c86b380fe9eaf27351be41aba77eacfa2b/jetty-core/jetty-client/src/main/java/org/eclipse/jetty/client/transport/HttpRequest.java#L339

**How to reproduce?**
```java
var httpClient = new HttpClient();
httpClient.start();
System.out.println(
    httpClient.newRequest("https://google.com/search")
        .param("q", null)
        .send()
);
httpClient.stop();
```

When running the above code with Jetty 12, it throws the following exception:

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:563)
	at java.base/java.util.List.of(List.java:937)
	at org.eclipse.jetty.util.Fields$Field.<init>(Fields.java:366)
	at org.eclipse.jetty.util.Fields.lambda$add$0(Fields.java:225)
	at java.base/java.util.HashMap.compute(HashMap.java:1324)
	at org.eclipse.jetty.util.Fields.add(Fields.java:221)
	at org.eclipse.jetty.client.transport.HttpRequest.param(HttpRequest.java:334)
	at org.eclipse.jetty.client.transport.HttpRequest.param(HttpRequest.java:329)
	...
```

It works fine with Jetty 11 though.

### PR DESCRIPTION
**Pull request by lorban**
`HttpRequest` on the client used to interpret null parameter values as empty strings in Jetty 11, and some of the 12 code still contains such checks, e.g.:

```java
    private String urlEncode(String value)
    {
        if (value == null)
            return "";

        return URLEncoder.encode(value, StandardCharsets.UTF_8);
    }
```

but the `Fields` class throws NPE when a null value is given.

This PR makes `Fields` consider a null value as empty strings.

Fixes #12018

### CODE REVIEW

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java [hunk 1]
```diff
@@ -246,13 +248,30 @@ public void add(String name, String... values)
...
         }
     }
 
+    static List<String> toList(String... strings)
+    {
+        try
+        {
+            return List.of(strings);
+        }
+        catch (NullPointerException e)
```
Comment (sbordet) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java]: Don't really like exceptions as control flow... Not really on the hot path, I'd go for `ArrayList` and iteration over the array.

**Review by sbordet — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java [hunk 2]
```diff
@@ -190,8 +190,9 @@ public List<String> getValuesOrEmpty(String name)
      */
     public void put(String name, String value)
     {
+        String v = value == null ? "" : value;
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java]: This aligns with HttpField +1

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java [hunk 3]
```diff
@@ -246,13 +248,30 @@ public void add(String name, String... values)
...
-                    return new Field(name, List.of(values));
+                    return new Field(name, toList(values));
                 else
-                    return new Field(f.getName(), f.getValues(), List.of(values));
+                    return new Field(f.getName(), f.getValues(), toList(values));
             });
         }
     }
 
+    static List<String> toList(String... strings)
```
Comment (gregw) [inline jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java]: This belongs in `StringUtil`

Comment (gregw) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java]: Also,  why do the JVM libraries always have `foo()`, `foo(Object o1)`, `foo(Object o1, Object o2)`, ... , `foo(Object o1, Object o2, ... , Object o10)` and `foo(Object... object)` ?        Is there something the JIT can't optimize away with few args calls to a varargs method?

**Review by gregw — CHANGES_REQUESTED** [review]

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java]: @gregw it's because there are well-known shortcomings in the JIT making it unable to eliminate the array allocation. Iterating the array with a variable index, or reading its length are some of those IIRC.

This is discussed in [this old blog](https://jpbempel.github.io/2020/08/02/when-escape-analysis-fails-you.html) but here's a recent example of yet another failure to optimize: https://bugs.openjdk.org/browse/JDK-8332840

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java (hunk 1 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java]: Done.

File: jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java (hunk 3 above)
Comment (lorban) [reply jetty-core/jetty-util/src/main/java/org/eclipse/jetty/util/Fields.java]: Moved to `StringUtils`.

**Review by gregw — APPROVED** [review]

**Review by janbartel — APPROVED** [review]

**Review by sbordet — APPROVED** [review]
